### ISSUE TITLE
Work on Copy for "What is Giveth"

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#10]
@GriffGreen commented on [Sun Jul 12 2020](https://github.com/Giveth/giveth-2/issues/67)

Edit all the text make sure that Kris is ok with it :-D

https://docs.google.com/document/d/1noGXWxVT_nzoGv_0L0gz-XOuowjm6w3Q2_yn7zNHsrk/edit?usp=sharing

**Comment by GriffGreen** [comment]
Made a PR... https://github.com/Giveth/giveth-2/pull/76

**Comment by ForestSoleil** [comment]
This copy has been updated on the website. https://docs.giveth.io/whatisgiveth/
