### ISSUE TITLE
‘Grafitti’ Logos and URL marketing Cryptovoxel campaign

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-planning#100]
I reached out to some parcel owners in Cryptovoxel about offering a wall space for Giveth logo and a url or QR leading to Giveth.io for launch, or whatever we want.

Sounds like so far have access to about 30 different parcels.

Need: 
-decide on url/qr, where does it send people to?
-what logo, multiples?
-send files to parcel owners, add to Cryptovoxel

**Comment by tommygiveth** [comment]
Which url are we using for this?
Giveth.io?

When is it ok to post links to this page?

**Comment by tommygiveth** [comment]
https://www.cryptovoxels.com/play?coords=E@231E,404N

https://www.cryptovoxels.com/play?coords=N@81E,270S,8.5F

https://www.cryptovoxels.com/parcels/1504

![image](https://user-images.githubusercontent.com/75334355/110263557-ba1bfa00-7f7c-11eb-83b7-18ce03ef6fea.jpeg)![image](https://user-images.githubusercontent.com/75334355/110263565-bdaf8100-7f7c-11eb-9031-b094f1cdb453.jpeg)![image](https://user-images.githubusercontent.com/75334355/110263567-c0aa7180-7f7c-11eb-92e5-96dcd7e296b7.jpeg)

**Comment by tommygiveth** [comment]
More will be added.

**Comment by WhyldWanderer** [comment]
@tommygiveth was this only for Metafest?
