### ISSUE TITLE
Special POAPs 

### ISSUE THREAD

**Issue by rodricastillo9013** [Giveth/giveth-planning#1000]
we agreed with Lauren to create new POAPs for special dates. We did it for Halloween, we will also do it for Christmas and New Years. If you think you can contribute any new important special date, it would be great to prepare it in time.

**Comment by c0ric0ri** [comment]
Love: Valentine's Day - Feb 14
Regen: Earth Day - April 22

**Comment by divine-comedian** [comment]
Yeah sure let's add a few special days:

National Catalonia Day - Sept. 11
Easter (Pascua) - April 9
Beginning of Ramadan - March 22
canada day - July 1
carnaval de barranquilla - 18-21 febrero
africa day - may 25

**Comment by laurenluz** [comment]
@divine-comedian I love these ideas, though... I think maybe we should stay clear of independence days because there are too many countries... and I would feel back to represent Canada, for example, and not represent the states? wdyt?

**Comment by divine-comedian** [comment]
Canada is awesoume tho 

states is :-1:  canada is :+1: 

I'm okay with removing independence days but I thought a couple fun holidays representing where some of the team are from would be interesting. 

The USA is in general more internationally controversial than Canada or Mexico so I figured the latter two are a safe bet.

**Comment by laurenluz** [comment]
I think it might be worth to skip them and save those rounds for just business as usual Giveth POAPs,. Feels like we're reaching very limited circles with them, and personally, I'm not a fan of country borders anyway.

**Comment by rodricastillo9013** [comment]
hi team! proposals are good! But I agree with @laurenluz , I think we should try to only choose some very general and global topics, such as Christmas, New Year, Valentine's Day, Regens Day, some date related to blockchain, crypto, public goods, I will do some research and propose some :)

**Comment by c0ric0ri** [comment]
Agreed with @rodricastillo9013 above - I would also avoid religious holidays to keep things inclusive for our global community.

So skipping Easter, and for example I would say Christmas can perhaps be labeled instead as "Holiday POAP" with things on it that could be interpreted across various winter holidays. (snow, green pine trees, stars, candles, red bows, etc)

Aside from major global topics, I like the idea of highlighting major global days relevant to Giveth's mission of positive impact through projects - Earth Day, Indigenous Day, possibly also International Women's Day (as this gets growing international recognition every year and relates to women's education, topics like this).

**Comment by rodricastillo9013** [comment]
If I agree with you @c0ric0ri , I think those more global and inclusive themes are great.

**Comment by oyealmond** [comment]
Are we still doing special POAPs @divine-comedian?

**Comment by WhyldWanderer** [comment]
I think we can still do some special POAPs if anyone has some inspiration for one that has a global theme...

**Comment by oyealmond** [comment]
great! :D thanks @WhyldWanderer!

**Comment by rodricastillo9013** [comment]
hey @WhyldWanderer If you want, let's carry this out, do you think we can make a list of topics and start preparing the designs?

**Comment by WhyldWanderer** [comment]
Here is a list of some holidays:
https://www.bankbazaar.com/holiday/international-holidays.html

There are some interesting and fun ones on that list, however, Im not sure how widely recognized some of them are.
Such as:

Software Freedom Day | 15 September 2023
World Gratitude Day | 21 September 2023
International Internet Day | 29 October 2023
International Volunteers Day | 5 December 2023

Ill see if I can find some more lists I think we should run the final list by the comms team though to make sure that we are all aligned on publicly promoting these topics...

**Comment by WhyldWanderer** [comment]
Here are some other resources:
https://indialends.com/indian-holidays-list/international-holiday-calendar
https://www.un.org/en/observances/international-days-and-weeks
