### ISSUE TITLE
PFP Promo Drop Video

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-planning#1002]
Promo video to announce The Givers PFP collection is now LIVE! Get people to mint

**Comment by c0ric0ri** [comment]
Hey @tropicalmangos love this idea with the explanatory script! Would love to see this video cut in 2 different ways.

1. One to use as a hype video several weeks beforehand, flashing the collection and encouraging people to join whitelist 

2. One to use on day of launch to announce that minting is live

**Comment by laurenluz** [comment]
Hey @tropicalmangos - good start, I think having a script setup like this would be cool but that the messaging is a bit off. Critical points:
- the PFP collection is nowhere near as big of an undertaking as the entire GIVeconomy, we shouldn't frame it like that.
- "boosting" isn't really an understood concept yet... it's not launched & the details of how PFPs will affect it are still pending...

I think this needs a new core message/approach. Some ideas:
- bring people into the community.. the PFP is supposed to be a profile pic afterall... it's the chance for people to identify as givers or as part of the giveth community
- concept of using web3 to transform public goods funding... get an NFT, it has upside... use it to support your favourite projects

This is a perfect example of something that you could have asked feedback on in our call, and we could have brainstormed together... please try to use our calltimes more effectively by using me for comments on stuff like this.
