### ISSUE TITLE
Create POAP for Projects 101 Course

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1003]

**Comment by ahmadabugosh** [comment]
hey @rodricastillo9013 can you create a simple POAP for our "Projects 101 Course"? Even just a copy of the [Donors 101 ](https://assets.poap.xyz/giveth-donor-101-course-completion-2022-logo-1651873791692.png) one changing the wording would be ok.

**Comment by rodricastillo9013** [comment]
<img width="901" alt="CoursePOAP" src="https://user-images.githubusercontent.com/61791380/200805444-211c4b7b-e7c7-442a-829d-36b895788bf7.png">

Wdyt? @ahmadabugosh

**Comment by ahmadabugosh** [comment]
@rodricastillo9013 I think that's good, but can you please make it say "Giveth Projects Owners 101 Course"

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh @rodricastillo9013 please move issues through the pipeline! This is still sitting under New Issues.

**Comment by c0ric0ri** [comment]
Hey @rodricastillo9013 is this still being worked on? When do you think it'll be complete?

**Comment by rodricastillo9013** [comment]
hi! Sorry, I had missed this, I'll have it for tomorrow @c0ric0ri

**Comment by rodricastillo9013** [comment]
![GivethOwnerCourse](https://user-images.githubusercontent.com/61791380/207571413-b718dcf5-dca5-4c36-b051-26fc4793844a.png)

Wdyt @ahmadabugosh ?

**Comment by ahmadabugosh** [comment]
Thanks @rodricastillo9013!
