### ISSUE TITLE
Create Quiz for Projects 101 Course

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1004]

**Comment by laurenluz** [comment]
Hey @ahmadabugosh! are we doing this? the course is supposed to launch tomorrow

**Comment by laurenluz** [comment]
@danelsuga @c0ric0ri FYI

**Comment by ahmadabugosh** [comment]
@laurenluz @c0ric0ri @danelsuga  I think we should announce it tomorrow as planned minus the quiz and POAP. I already reached out to Blockchain Learning and they said they'll post it on their platform, so what I suggest is tomorrow we announce the YouTube playlist, then in a week or so (once it's on Blockchain learning, we have the quiz and the POAP), we say now you can get a POAP if you launched a project and took our course and we funnel people into the Blockchain learning portal for that.
