### ISSUE TITLE
Manually invite projects to transition over from G1 to G2

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#101]
## 📋 Anything to add?
Moving projects over from Giveth 1 to Giveth 2. Next steps: reach out to G1 projects and ask them to create project on G2. By next week, we'll be ready to onboard new projects. Manually inviting projects to transition over. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Danibelle** [comment]
Updated the email invitation and looking over the invite list, most project owners are in this list as they had to request access to beta :)

This issue is linked to this one I believe, basically the same: https://github.com/Giveth/giveth-2/issues/313

**Comment by laurenluz** [comment]
@Danibelle can we close this issue?
