### ISSUE TITLE
Mandatory updates - Comms support

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1013]
Hi dear comms team and @c0ric0ri , asking for your help to promote our Mandatory updates requirements as we still need more project owners to wake up to some more action.

Maybe some nice banner would help if Rodri has the capacity or come up with some cool meme.

We would need to cover as many platforms as possible:

Twitter
Facebook
LinkedIn

Draft is here, any feedback? wyt? :)

https://docs.google.com/document/d/1AbSJW0MsnPmm__bUuzlluHlbKgNpOhbbo9G98bXiaHM/edit?usp=sharing

**Comment by laurenluz** [comment]
yeah! anyone can comment access would be great!

Also FYI @c0ric0ri I love Nikola's step by step for projects here... it's a good idea in our tweet thread to actually help projects provide the update. Maybe you can use some of what she wrote here in #807

**Comment by NikolaCreatrix** [comment]
@c0ric0ri should work for suggestions now https://docs.google.com/document/d/1AbSJW0MsnPmm__bUuzlluHlbKgNpOhbbo9G98bXiaHM/edit?usp=sharing
