### ISSUE TITLE
Tweet to announce GIVbacks rd 22 being out!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1015]
GIV & $nice have been sent!  https://forum.giveth.io/t/round-22-givbacks-nice-distribution/875/3

@c0ric0ri can you draft a tweet for this to go out tomorrow?

**Comment by c0ric0ri** [comment]
Draft ready for review @laurenluz !

https://docs.google.com/document/d/1rjMikrpIOt_gZMNHN8076RnlpKu1fYGx2BwNsbRqPBo/edit

**Comment by laurenluz** [comment]
Hey @c0ric0ri it's good! thank you! making minor tweaks - just make sure next time to double check the links, the POAP claim link was wrong.

**Comment by c0ric0ri** [comment]
Oh wow sorry about that! Will remember to double check from now on

**Comment by laurenluz** [comment]
thanks! <3 https://twitter.com/Givethio/status/1590374412339056640
