### ISSUE TITLE
Notification Center Update Tweet

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1016]
Updates are coming to the Notification Center on giveth.io, which requires a comms announcement.

A tweet should prepared to let users know.

Timing: Around early December

@MoeNick to provide more details here!

**Comment by danelsuga** [comment]
Anybody have the Twitter link for this? Would be great to paste it here. Thx!

**Comment by danelsuga** [comment]
Perhaps this: https://twitter.com/Givethio/status/1630916315912237060

**Comment by laurenluz** [comment]
yeah that might be it 🤔
