### ISSUE TITLE
Video descriptions for Project Owners 101 Series course

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1018]
The videos are all posted with the default youtube description. We should post unique descriptions that, in a short summary, explain what the video is about.

@c0ric0ri does this make sense? can you help find the right person for the job?

We should try to get this done sometime this week or next since the course already launched.

**Comment by ahmadabugosh** [comment]
hey @laurenluz I agree we should change some of the default descriptions, but I did already add all the links or resources if they were mentioned in a video. For example, for [this one](https://www.youtube.com/watch?v=1z66GxECThM&list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm&index=8), [this one](https://www.youtube.com/watch?v=8myBgJCKXiU&list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm&index=5)

**Comment by laurenluz** [comment]
@ahmadabugosh gotcha.. well whoever make summaries can use you links in them in that case.

**Comment by danelsuga** [comment]
Do we need to remove FTX from the offramping video @ahmadabugosh ?

**Comment by danelsuga** [comment]
This video really needs to come down or be fixed: 
Bonus Workshop: Fundraising 101 for Projects
https://www.youtube.com/watch?v=QO6iQgnKvfw&list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm&index=10

At the beginning you can clearly hear someone in the background of Melody say, "So they know that you're lying? So what!"

Also, the sound at the beginning is generally very terrible. At least the beginning of the video needs a new introduction with all of that part removed.
 
@ahmadabugosh @laurenluz @c0ric0ri

**Comment by ahmadabugosh** [comment]
Hey @danelsuga, 

Thanks for this!

 1) For the incorrect number in the success video, I think I can edit that directly from YouTube, should be easy to cut out. 

2) For the Fundraising workshop, yeah I tried to clean up the audio, but it's very raw. However, @WhyldWanderer and I thought it still had good information in it. Do you think there is any way to salvage it? Maybe cutting out the beginning part completely? Wdyt?

3) For the video descriptions doc, I just requested access

**Comment by danelsuga** [comment]
Thanks @ahmadabugosh! 

I think the bonus video just needs a new intro as far as I can tell.

**Comment by ahmadabugosh** [comment]
hey @danelsuga , I edited the video taking out the wrong figure, added all the descriptions you sent, and also took at the beginning part of the [fundraising video ](https://www.youtube.com/watch?v=QO6iQgnKvfw&list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm&index=10&ab_channel=Giveth)

**Comment by danelsuga** [comment]
You are lightning fast! I'll catch up with your improvements tomorrow. Thank you!

**Comment by oyealmond** [comment]
thank you for fixing my mistake @ahmadabugosh :(

**Comment by danelsuga** [comment]
it's ok @oyealmond ! very understandable mistake. no worries.

**Comment by danelsuga** [comment]
Great job on the edits @ahmadabugosh.

**Comment by c0ric0ri** [comment]
Hey @danelsuga @ahmadabugosh I looked through all the video descriptions and noticed they're not all up to date with relevant links. Can we add this blurb that I see in some of them, to all of them?

"Join [http://join.giveth.io](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbFVQV3NEU0FwY0J2aFRwQ3JGYnkyWktHT0JDd3xBQ3Jtc0tuSUZ6LUlpcEEwWUZMWmc5OUV6bU11d25GVHhoNzJncFdHOW5DTmR2bkFQd05jam01YWk5cGtDMUQ5OXBROVE0ZnNleGpCSnZoUTlHaC1ndk41MUYzNWZLWGdHTDdReHdneWdWbi1yRFJabzZCVk04TQ&q=http%3A%2F%2Fjoin.giveth.io%2F&v=u5nUpYIbABE)
Donate [http://donate.giveth.io](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbDd5Wk1yeG1NbWtIMzlWbzR6dUZHN3R5ODF3Z3xBQ3Jtc0trbUpxajV5ZHZjQy01VWEyeEEyYmJpNTdpc2lTWjlnRzBzeDY5aU1FbmZmRzRUU2JoWHdGVWt2QlVVR1ZQOUs4cG5OeV91Z09MMVdDVlB4OWxHbEtJM2o4TEkwTm51Z1BEY3UtRUIxMjF5by1GQXFRUQ&q=http%3A%2F%2Fdonate.giveth.io%2F&v=u5nUpYIbABE)
Discover [http://giveth.io](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbjRlVGlMdEhKSVhua2VLY1RMQVNjd0xjbl84UXxBQ3Jtc0ttTGFLelZ6cXlweDl3eG0zR1FZVk5mdmh5WmRoWkVRQU9lUEZLOXk3Ny1CczBHc1FTVGl0N0xqX3NlNDZkczJLc0M4MGFNNnA0d3pYZDJKMGc3OU8zbDczRVdtVmFnMGlmU21xVnZRQURVeDhmQjY1WQ&q=http%3A%2F%2Fgiveth.io%2F&v=u5nUpYIbABE)"

I think we could also standardize the descriptions a bit more, double check spacing for easy reading (bullet points > paragraphs). I like the second video description the best as an example to reference.

**Comment by ahmadabugosh** [comment]
@c0ric0ri I cleaned up the descriptions and added those links at the bottom of all of them. I think we can close this issue now.

**Comment by danelsuga** [comment]
Thanks @ahmadabugosh. Did you edit the descriptions in the doc? I don't see them. 

https://docs.google.com/document/d/1rVj2SIMByDwvilU7_nfULaGIdC-v0kG7OpVSNDAI2no/edit?usp=sharing

I didn't do the "bonus" one yet. Sorry.

**Comment by ahmadabugosh** [comment]
@danelsuga hey yes, I updated all the video descriptions on the playlist directly (plus I added a simple one for the bonus video too): https://www.youtube.com/playlist?list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm

**Comment by danelsuga** [comment]
OK, groovy. Thank you @ahmadabugosh !
