### ISSUE TITLE
Is this a true statement?  and provides a level of transparency and accountability no other platform can offer.

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-planning#102]
![image](https://user-images.githubusercontent.com/75334355/107846669-15f2c900-6dab-11eb-9930-59f1cc344538.png)

**Comment by WhyldWanderer** [comment]
Now that Giveth TRACE has gone live, we will be deciding how to integrate the two platforms in the coming months. We have discussed the proposed user flow and I do believe that once this integration is complete, this statement will definitely be true.

I also believe that these statements and this part of the page will be updated with the new rebranding as well as the completion of our mission, vision, values and roadmap workshops.

**Comment by laurenluz** [comment]
closing this. agree with you Ashley - we can update the copy when we update the design after the integration. I think it's fine as is for now.
