### ISSUE TITLE
Add new swag to the swap shop!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1020]
Hey @rodricastillo9013 

It would be great to add:
- a hoodie
- socks
- the bucket hat from ETH barcelona that I forgot to add before

And perhaps switch up our t-shirt designs (or add more!)

Can you help w/ exploring that? We need to consider:
- Minimzing the cost of new additions
- The best price for new items like hoodies
- Making our designs new and fresh!

I think we could reach out to @missgene too if we need more support.

**Comment by laurenluz** [comment]
FYI @divine-comedian

**Comment by c0ric0ri** [comment]
hey @rodricastillo9013 do you have some updates on this?

**Comment by missgene** [comment]
Do you need support here? How can I help? @rodricastillo9013 @c0ric0ri

**Comment by rodricastillo9013** [comment]
This week I will have progress on this!
