### ISSUE TITLE
GIVpower launch video

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1021]

**Comment by laurenluz** [comment]
https://docs.google.com/document/d/139zJLyZaNZBGyWht9WrkY_sPYrOWcLQdjvEjyMlBx9c/edit

**Comment by laurenluz** [comment]
@ahmadabugosh @danelsuga - sorry ! I forgot to update the access. You can now comment - would love your thoughts. DM me if any questions

**Comment by laurenluz** [comment]
@oyealmond & I have made the script! Graymachine is working on the timing cut & will have something by the end of tomorrow

**Comment by laurenluz** [comment]
Tweets from Almond - round 1:

Hey team! Sharing some tweets to add to this section, as I think will be very cool to add as many tweets as possible: 
https://twitter.com/akathesmith/status/1547925294908338176
https://twitter.com/MerlinEgalite/status/1478033655448625157
https://twitter.com/rainbow_rolls/status/1461779355529580546
https://twitter.com/willyogo/status/1475961344088100865
https://twitter.com/sagetosaddle/status/1475987319706591232
https://twitter.com/jojoliciosa/status/1590386941006344192
https://twitter.com/GivJake/status/1575019595618222080
https://twitter.com/willyogo/status/1507401044778573828
https://twitter.com/Tithe_w_Bitcoin/status/1592681392835465216
https://twitter.com/markoprljic/status/1497653386715574272
https://twitter.com/PanvalaHQ/status/1474490949996670978
https://twitter.com/AtlantisDAO1/status/1577540736769490944

**Comment by laurenluz** [comment]
@oyealmond - let's get some good "my project is verified and we're doing x" tweets, assuming that this section is subtitled "Support for-good projects" or "Make an impact on public goods"

**Comment by oyealmond** [comment]
hey @laurenluz ! 
Wdyt of this selection? Try to find projects... 

https://twitter.com/bestape/status/1598715114177572864 
https://twitter.com/Yassi_Omd/status/1598234721959702529 
https://twitter.com/Fatalmeh/status/1598085477747552256 
https://twitter.com/SusieKav/status/1597808532950511616  
https://twitter.com/OurBloomNetwork/status/1597748695029907456 
https://twitter.com/bridgitdao/status/1597229688484958208 
https://twitter.com/ThessyMehrain/status/1597101038254710784 
https://twitter.com/Nicccoh/status/1596931042614865920 
https://twitter.com/FreshelleT/status/1596055299844374529 
https://twitter.com/Milca0_/status/1595561845066289152 
https://twitter.com/fundotherworlds/status/1593925599672033282 
https://twitter.com/schetty/status/1593696089944850433 
https://twitter.com/0xnats/status/1593314432083435524
https://twitter.com/cmlsburundi/status/1592522645719126024 
https://twitter.com/stayonline_eth/status/1591988857092059136 
https://twitter.com/divine_comedian/status/1597593901007003656 
https://twitter.com/tmoindustries/status/1598788100804775949 
https://twitter.com/GLFledge/status/1598354140593213442 
https://twitter.com/cole_vt/status/1591080842767761410

**Comment by laurenluz** [comment]
Hey @oyealmond! Pretty good, some notes:
- it ok to have one or two with our general auto-tweet, but I think we should avoid too many. I'm talking about ones that say basically word-for-word [this](https://twitter.com/Milca0_/status/1595561845066289152)
- let's avoid more than one or two that mention giving tuesday - I don't want to distract from GIVpower with this other (ultimately non-giveth campaign)
- It would be nice to showcase a variety or projects, and avoid too many Iran related ones. I would do max one or two iran tweets
- let's avoid hard-to-understand or broken english tweets like [this](https://twitter.com/cmlsburundi/status/1592522645719126024) They're OK, but not ideal.
- I like having one or two in Spanish, but not more - since the video is mostly in English

I put some notes on the tweets (w/ my thoughts on useable/not useable). My favourites are these two:
https://twitter.com/fundotherworlds/status/1593925599672033282
https://twitter.com/divine_comedian/status/1597593901007003656

Because they're more personal, heartfelt.

Here are the other notes:

https://twitter.com/bestape/status/1598715114177572864 ok
https://twitter.com/Yassi_Omd/status/1598234721959702529 ok (iran)
https://twitter.com/Fatalmeh/status/1598085477747552256 tough! too much iran
https://twitter.com/SusieKav/status/1597808532950511616 giving tuesday plug not ideal
https://twitter.com/OurBloomNetwork/status/1597748695029907456  giving tuesday plug not ideal
https://twitter.com/bridgitdao/status/1597229688484958208 giving tuesday plug not ideal
https://twitter.com/ThessyMehrain/status/1597101038254710784 ok (iran)
https://twitter.com/Nicccoh/status/1596931042614865920 ok - spanish
https://twitter.com/FreshelleT/status/1596055299844374529 ok (iran)
https://twitter.com/Milca0_/status/1595561845066289152 great, but generic shill
https://twitter.com/fundotherworlds/status/1593925599672033282  GREAT
https://twitter.com/schetty/status/1593696089944850433 great
https://twitter.com/0xnats/status/1593314432083435524 nice, like the spansih
https://twitter.com/cmlsburundi/status/1592522645719126024 broken enligsh, ok
https://twitter.com/stayonline_eth/status/1591988857092059136 good
https://twitter.com/divine_comedian/status/1597593901007003656  really good, but mentioned giving tues
https://twitter.com/tmoindustries/status/1598788100804775949  ok
https://twitter.com/GLFledge/status/1598354140593213442 ok
https://twitter.com/cole_vt/status/1591080842767761410 good

Can you take that feedback & find a few more winners?

**Comment by oyealmond** [comment]
Hey @laurenluz ! 
Thank you for the feedback. It was really helpful! 
Let me know if these are better: 


Bankless - https://twitter.com/BanklessAcademy/status/1579466156968005632 
Diamante - https://twitter.com/DiamanteBridge/status/1553086749131374592 
IberoAM - https://twitter.com/iberoam_xyz/status/1578425030245224448
no links - https://twitter.com/spread_love_org/status/1475125458656284676 
Regen - https://twitter.com/RegenCLT/status/1521188160293806084
Vlad - https://twitter.com/vladhzc/status/1494743456308240384
Clara - https://twitter.com/clara_zi/status/1597669291905941504 
Willy - https://twitter.com/willyogo/status/1537190867529658368 
TEC - https://twitter.com/tecmns/status/1559252818657218560
Joanna - https://twitter.com/jojoliciosa/status/1590386941006344192
A lot of cryptomurals - https://twitter.com/cryptomurals/status/1590465507710246914 
not project but nice partnership tweet - https://twitter.com/DeSciWorld/status/1475441519087730688
Campaign - https://twitter.com/cagriyalcin93/status/1489159046473134082 
without links - https://twitter.com/jonimadere/status/1432821201647415296 
Vlad - https://twitter.com/vladhzc/status/1597978980677980163
nice - https://twitter.com/nia_org/status/1552977105402601473

**Comment by laurenluz** [comment]
Awesome @oyealmond - thank you!! I sent these ones to graymachine:

https://twitter.com/spread_love_org/status/1475125458656284676
https://twitter.com/fundotherworlds/status/1593925599672033282
https://twitter.com/divine_comedian/status/1597593901007003656
https://twitter.com/clara_zi/status/1597669291905941504
https://twitter.com/willyogo/status/1537190867529658368
https://twitter.com/tecmns/status/1559252818657218560
https://twitter.com/jojoliciosa/status/1590386941006344192
https://twitter.com/jonimadere/status/1432821201647415296
https://twitter.com/cole_vt/status/1591080842767761410
https://twitter.com/schetty/status/1593696089944850433
https://twitter.com/Fatalmeh/status/1598085521779326976
https://twitter.com/tmoindustries/status/1598788100804775949
https://twitter.com/RegenCLT/status/1521188481271271426
https://twitter.com/Tithe_w_Bitcoin/status/1592681392835465216
https://twitter.com/AtlantisDAO1/status/1577540736769490944

**Comment by laurenluz** [comment]
I think that's good enough for now

**Comment by laurenluz** [comment]
Working with graymachine on this, he's doing a final edit after my last review. hopefully it's done today!

**Comment by laurenluz** [comment]
https://www.youtube.com/watch?v=KvMR-6JQ_fc
