### ISSUE TITLE
Tweet Verification Workshop Recording. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1022]
Hey dear team! @laurenluz @c0ric0ri 
Sharing a Tweet draft to share the verification workshop recording we had yesterday [here](https://docs.google.com/document/d/1KdrgJpBa8LCsQpKRimQ47Z_HgaL6i66Yq9fAnkjgGxU/edit?usp=sharing)

Could you help us review and schedule? 
Thank you!

**Comment by laurenluz** [comment]
Hey @oyealmond !

I think this tweet doesn't really say too much the get people interested.

What actually happened in the workshop? you showed people how to get verified / why to get verified / how to maintain status?

What were some interesting questions people asked? what did people get stuck on?

I would redraft this tweet with those things in mind... say something like that answers a common question or provides some guidance/did you knows.

Can you give it another shot?

**Comment by laurenluz** [comment]
Here's what Ashley said happened:

We introduced the launch of the video series...
Then Nikola talked about how giveth uses verification, why its important and the benefits of getting verified
Then I did a live demo of filling out the application and explaining the key points as well as common reasons why projects get denied...
Then I talked about what to expect after you submit your application, how long it takes, what will get your badge revoked and emphasized mandatory updates

**Comment by oyealmond** [comment]
Thanks for the summary @laurenluz! It was a really cool session. 
[I re draft the tweet trying to make it more juicy and engaging. ](https://docs.google.com/document/d/1KdrgJpBa8LCsQpKRimQ47Z_HgaL6i66Yq9fAnkjgGxU/edit?usp=sharing)
Let me know your thoughts!

**Comment by laurenluz** [comment]
wayyyyyy better! I edited it directly & scheduled for sunday

**Comment by oyealmond** [comment]
Loved the edits @laurenluz thank you as always!

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1592156151508094976
