### ISSUE TITLE
GIVfarm APR Tweet Nov 11

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1023]

**Comment by c0ric0ri** [comment]
@laurenluz draft for review for tomorrow! 

https://docs.google.com/document/d/1gbo8sWaix4bfEiYrLu1MsJ_ibmbdMsOZjVkYn2PHFDw/edit

FYI I'm testing out this issue flow for recurring content so just bear with me.

**Comment by laurenluz** [comment]
reviewed! awesome :)

and ok 😅  I'll just not close issues until you fill me in on our next call

**Comment by c0ric0ri** [comment]
Thanks! I just made revisions and left a comment to align on thread content.  I would assume we leave out mention of the Cult RegenFarm this week since we already said last week it's on pause. And I would personally keep the tweet pointing to the regenfarm nomination form for every weekly thread.

**Comment by laurenluz** [comment]
love it
