### ISSUE TITLE
Meet the makers promo Tweets ✨

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1024]
Hey team :) @c0ric0ri @laurenluz 
we're having our next Meet The Makers session next Wed 23rd at the same time of our regular AMAs session . 

I prepared some tweets to promote it, [could you help me review them? ](https://docs.google.com/document/d/1o5xorWeech3t7fWS70hZ__BXTGy0FD0qLMhg9Mwa3QU/edit?usp=sharing)

✨ Thank you 
cc @NikolaCreatrix

**Comment by laurenluz** [comment]
Hey girl @oyealmond !

I edited the 1st minorly and scheduled for Sat morning.. Left comments on the others - please check 'em out an tag me again after you're happy w/ it.

**Comment by laurenluz** [comment]
Almond you are so amazing - I love how you take feedback and implement it super effectively and super fast. Your changes were great and i scheduled both for this week.
