### ISSUE TITLE
Proposal to create interactive map of projects & our network

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#1025]
Background:
In the recent donor survey stewarded by @SnakeGH - one of the findings was that donors would like an easy visual enabling them to discover projects operating in particular regions/countries. 

Proposed solution:
This could be achieved by creating an interactive map and plotting project locations on the map.

Wider impact:
Such a map could be really powerful for providing information and networking projects, donors/investors, collaborators, non-profits, supporters, mentors: creating an live, interaction repository of links by location. Essentially, creating a regional representation of our refi network (and wider Ethereum network, where relevant).

The goals of the map is to visually document our refi network, particularly to:
- better support projects
- bring donors and projects together
- create a tool to aid collaboration and information sharing with Giveth ecosystem and wider Ethereum community

Feasibility:
This issue has been created to research and investigate feasibility of creating such an interactive map.

**Comment by clara-zi** [comment]
Currently, the region/country data in Giveth database is not standardised.

**Comment by clara-zi** [comment]
@Santigs

**Comment by SnakeGH** [comment]
Love this, thanks for putting it into action!!!

**Comment by clara-zi** [comment]
https://docs.google.com/document/d/1oYGyOo6ZzTj0JTrddj0j8sjptaQUblJaRbtcE34kmZI/edit#heading=h.aqfghe5ntdfy

@MoeNick to review for devs input

**Comment by clara-zi** [comment]
https://github.com/Giveth/giveth-planning/issues/1025
Proposal submitted.

**Comment by clara-zi** [comment]
related issue #588
