### ISSUE TITLE
Does Giveth need a file to track non-salary expense?

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#1026]
Pull invoices together and assess whether it's worth creating a file to document/track non-salary expenses.

**Comment by freshelle** [comment]
There are some non-salary expenses I track using the nrGIV reimbursement/payments done. The categories include:

- Allowances and Conferences
- Bounties
- Compensation (Salary)
- Sponsorship
- Subscriptions
- Swag
- Vesting

This can be found in [this google sheet](https://docs.google.com/spreadsheets/d/1VUyk93K4ybjgJDD-fnIK7ii1k-V_svA8qtThLrA3VGs/edit?usp=sharing) (nrGIV Expenses tab). 

For the subscriptions expenses, we'll be making one more reimbursement request (do some retroactive computation from May 1, 2022 to present) before we change the way we pay for subscriptions based on [this forum post](https://forum.giveth.io/t/change-the-way-we-handle-paying-for-subscriptions/814). So then we can have an updated figure of how much we spend on subscriptions, and a new way to track it (_request funding in advance or reimbursement request quarterly or biannual_)

Other than these expenses I'm aware of, maybe we can have a file to track it. I'm not sure what else Giveth is spending on aside from this.

**Comment by clara-zi** [comment]
Thanks @freshelle. Does subs. no include these regular invoices?:
<img width="72" alt="image" src="https://user-images.githubusercontent.com/100724132/202678024-e7667883-a15e-4879-aa8b-0dceebb6f090.png">
A quick round-up of these regular, smaller invoice totals at just under $1k each month.

Either way, I think the solution that Kay is suggesting will allow for better tracking of these smaller regular expenses.

@GriffGreen are there any other (regular) expenses that we should consider tracking that have not yet been listed here.
Thanks

**Comment by GriffGreen** [comment]
the devops team knows more about this than i do. @geleeroyale might have input

**Comment by clara-zi** [comment]
thanks @GriffGreen synced with @geleeroyale and pulled list of exp. above. 
Will wait until we know the outcome of subs payments post, which should make exp. tracking easier and more automatic.

**Comment by clara-zi** [comment]
file created
