### ISSUE TITLE
Sea of Hertz tweet for first show! :) 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1028]
Hey team! @c0ric0ri @laurenluz 

[We partner with Sea of Hertz radio show to interview Giveth Spanish Speaking projects](https://forum.giveth.io/t/sea-of-hertz-radio-giv-projects-interview/815) :) And the first show is happening this Thursday ! [I prepare this tweet to invite ppl jump in and listen to the Giveth project Owners](https://docs.google.com/document/d/10Tr3MEQPl9fEns-BhS8TdyyN_H89Gu2VNHH5_3OtoKk/edit?usp=sharing)

Could you check it out and help us schedule? 
Thank youuuu

**Comment by laurenluz** [comment]
@clara-zi FYI

**Comment by laurenluz** [comment]
Thanks @oyealmond - I made some more edits in Tweethunter & then just/copy pasted into the doc for your reference. Added a gif to the last tweet.

Thanks so much!!

Scheduled for Thursday morning at 8am Costa Rica time.
