### ISSUE TITLE
Community call spotlight video clips

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1030]
@oyealmond @WhyldWanderer

**Comment by laurenluz** [comment]
Idea to cut of the communtiy spotlights to share w/ our audiences

**Comment by oyealmond** [comment]
Hey team! I see the max Twitter Video duration is for 2 min 20 sec. 
I read Twitter will be promoting more video content, wdyt of cutting a 2 min section of the community spotlight to post in twitter, w a link to the whole community spotlight section? 

@laurenluz @WhyldWanderer 
Lmk your thoughts

**Comment by laurenluz** [comment]
yeah I think that's a good idea!

**Comment by oyealmond** [comment]
we could start rescuing past Community Spotlight to tweet.
@WhyldWanderer , I can cut the 2 min frame :) 
Maybe could you share some of your fav community spotlights we could rescue?

**Comment by WhyldWanderer** [comment]
Heres a few

Positive Billboards - https://youtu.be/mGODlu-C-L8
GIVswag Giveaway Wheel - https://youtu.be/URiQejliAqs
Return to Green - https://youtu.be/YAULegpG10w
DreamDAO - https://youtu.be/444vqtT0-OY
Bob Burnquist - https://youtu.be/NDGeb-bNH3I
ETH Safari - https://youtu.be/b5UAUBPeHzY
Regens Unite - https://youtu.be/33HxZuT4aKw
Token Engineering Academy - https://youtu.be/hjEwSm1ZQLw

**Comment by WhyldWanderer** [comment]
I think that sounds good!.. is there a way to add a screen shot or image... maybe we can capture the slide or something instead of the video??

**Comment by oyealmond** [comment]
Is happening! 🤩
https://twitter.com/Givethio/status/1608101295285567489
https://twitter.com/Givethio/status/1614986697644679170
https://twitter.com/Givethio/status/1601578328137367553
