### ISSUE TITLE
Verified projects Tweet Thread R23

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1033]

**Comment by NikolaCreatrix** [comment]
Hola @laurenluz cc @c0ric0ri 

This is the draft for R23 waiting for your review :) https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by c0ric0ri** [comment]
Thanks a lot @NikolaCreatrix ! I left some comments and suggestions. Please take a look, and also double check the character limits of each tweet after changes have been accepted. I'm not sure if any of them went too long now.

**Comment by NikolaCreatrix** [comment]
Hey @c0ric0ri 

Thanks for your edits and feedback, after checking on twitter I had to edit additionaly #3 nad #8 and changed the lead tweet ... ready for your review.

**Comment by laurenluz** [comment]
Thanks both - I scheduled for Friday after some edits

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1596867193949638656?s=20&t=GMfYPy0ChVFzEKdia136pg
