### ISSUE TITLE
Tweet to announce DoinGud partnership & GIVholders perks

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1035]
Hey team! on the 22 starts DoinGud private sale to [acquired a 'membership' for their DAO](https://forum.giveth.io/t/giveth-doinguddao-membership/816).   

All GIVholders have access to this private sale + a discount. [I wrote this tweet to announce the partnership + the private sale... ](https://docs.google.com/document/d/1t2wg33_eybuE31PKvcGWI3JfMmZH1siRnFWBKGA_C34/edit?usp=sharing)

This was kind of hard as I tried this tweet to not sound as a sell, but I will love your thoughts around .@laurenluz @c0ric0ri  

Also the sale starts on the 22th so I was planning to scheduled this day :) 

Ty!

**Comment by c0ric0ri** [comment]
Reviewed and left some comments @oyealmond !

**Comment by oyealmond** [comment]
thank you @c0ric0ri I added your comments, but left one note about the partnership... 

cc @laurenluz

**Comment by laurenluz** [comment]
@oyealmond - I left a comment, I find this very confusing. have a look

**Comment by oyealmond** [comment]
Yeah, you're right, it was very confusing for me too as the info was not clear. I added a third tweet with @WhyldWanderer version adding the perks of the "individual membership" different from the perks of "the dao membership" .

@laurenluz @c0ric0ri

**Comment by oyealmond** [comment]
hey team :) 
the doingud team asked me about this communication. I modified the draft, but maybe I can think in other way to present it. :) 
lmk your thoughts! thank you again! @c0ric0ri @laurenluz

**Comment by laurenluz** [comment]
looking into it now

**Comment by laurenluz** [comment]
ok I edited it a little, and put my draft in the doc. I scheduled it for tomorrow. hopefully that's good @oyealmond - if you have an issues w/ the final edit just DM me :)

**Comment by oyealmond** [comment]
Uho! that's perfect. Thank you. Ty for all your help on this one @laurenluz @c0ric0ri @WhyldWanderer , this was a specially hard  to draft!

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1596142420227510274
