### ISSUE TITLE
Tweet about the Iran project. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1037]
Hey @laurenluz ! 

[I did this thread draft](https://docs.google.com/document/d/1th4ZUYOwKK5Vt95SZE819uVXeJFRKb6WjZ4dtulUsBY/edit?usp=sharing) for you to review if it would be good to tweet about it. 

I went ahead and added a Griff's  community spotlight intervention .
But I know this tweet may not come out. So check it out, & let me know your thoughts. Don't worry if it doesn't come out.

**Comment by laurenluz** [comment]
I think this has potential! let me check w/ @GriffGreen

**Comment by oyealmond** [comment]
thank you :) @laurenluz

**Comment by laurenluz** [comment]
ok! talked to Griff about it and he's down! I think we can not link the spotlight and just add the soundbite & the info on the project. this can be part of #1038

**Comment by oyealmond** [comment]
yeey super cool :)  🥰

**Comment by c0ric0ri** [comment]
Moving this to icebox as we decided not to proceed with the Iran campaign and this falls under the topic. @laurenluz
