### ISSUE TITLE
Giveth Essentials Feedback

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1042]
We should get feedback from our contributors on what they want & if they liked the seesion in an easy/pracitcal way.

Some ideas:
- make polls to ask people to vote on topics they want to hear about (include subtopics)
- make agenda & see what people want to hear about at the beginning of the call (get ratification)
- get quick feedback on points throughout the call to see where we should take it
- leave time for feedback at the end (perhaps even give a short survey? and give 5 min to fill it out)

@c0ric0ri & I talked about this in our 1:1 sync - it would be great to understand if we're really bringing people forward or not

@oyealmond - got any thoughts?

**Comment by laurenluz** [comment]
we should also repeat session! Cori & I both thought that the twitter one might have been too granular and not 101-level enough

**Comment by laurenluz** [comment]
It's really important for us to know if these sessions are adding value to people or not... our goal should be to smooth out pain points & the only way to know if we are doing that... is by asking people their thoughts.

We can also try to do more session on the same topics with specific subtopics so that we can add real value, make it more Q&A back & forth, and actually be sure we are helping.

**Comment by oyealmond** [comment]
yeeey loved it! Thank you both for adding your feedback on this to get the session better. 
I think repeat a topic is a great idea too! 

I will say to this to start w this we should: 
1) starting tmrrw, make an agenda around ppl session expectations at the beginning 
2) at the end give a time slot to hear ppl thoughts & feedback around the sessions so far, saying we will ask them to fill a survey as well. 


To strenght the feedback, let me put a feedback/survey Google form in which I will add the options: 
- do you think this sessions are helpful, why yes? why not? 
- repeat sessions to make the information around better
- a section for ppl to add the topics they want to dig more (thinking in subtopics too) 

Wdyt? 
Do you think we should add any other action item, or point to the feedback survey? 
@c0ric0ri @laurenluz

**Comment by oyealmond** [comment]
also I'll add a section in the feedback form around tomorrow's session.

**Comment by c0ric0ri** [comment]
This looks great!

I think a key thing here to add is also integrating regular check-ins throughout the session to get quick feedback. You can even ask what would be most interesting to move to next. Encourage some interaction so the session is more dynamic (but within reason, having things prepared).

In our Twitter session, a good question to ask would have been "what are one or two things that are currently blocking you from using Twitter or make you unsure?" to find out what people are struggling with. If we know what the struggles are, then we can also make sure to talk about those things.

**Comment by oyealmond** [comment]
Perfect @c0ric0ri ! 
I'll have this in mind too! 

Could you check out this survey please? @c0ric0ri @laurenluz  
https://forms.gle/8USrSqzMjGnX79qn6

**Comment by c0ric0ri** [comment]
Hey @oyealmond here are the questions rewritten with just some small grammatical corrections. I like the questions you picked and I think it's good to keep the poll short like this. 

When introducing the poll, I would let people know that we really need their direct, honest feedback because GIveth Essentials is meant to help us all improve and we want these sessions to be very effective.

- Have you found these sessions personally useful so far?
- Why do you find them useful, or why haven't you found them useful?
- Should we repeat any of the sessions with a different format? For example - live Q&A, team conversation format, etc. If yes, which session & which format would you suggest? 
- Which topics would you like to focus on in a session? You can add subtopics too! For example: Twitter Spaces session. Bonding Curves session. nrGIV session.

**Comment by oyealmond** [comment]
Hey team! @laurenluz @c0ric0ri , already sent everyone's the survey for them to fill out, and maybe we can gather really quick later to see the results. 

Maybe next Monday? 

Thank you!

**Comment by oyealmond** [comment]
Hey dear team! @c0ric0ri @laurenluz 

Circling back on this, %66.7 of the team find Giveth Essentials Very useful and 22.2% find them useful. 

They asked to go deep into tokenomics & governance. 

"they are a great crash course into the fundamentals of what we are building and with many of us focusing on different areas they really do help to understand the whole ecosystem better." 

I think the team find these sessions valuable, and will be worth to keep improving them. Wdyt? 

[Leaving the feedback results here for you to check them out. ](https://docs.google.com/forms/d/e/1FAIpQLSe7aA6JbChSpXB_cET1-h0akEUrUlISyxxMThYCN_3GHqAsnA/viewform?usp=sharing)

**Comment by c0ric0ri** [comment]
Oh, I like the point about going deeper into governance. I can't see the results with this link, but it sounds like we should continue the sessions and keep improving. It would make sense to map out a sequence of them so people can build upon their knowledge.

**Comment by oyealmond** [comment]
Sorry ! @c0ric0ri @laurenluz 
[I think you can see them now](https://docs.google.com/forms/d/1u8KA7gQ7OPiTbpNo6BvpnyBQ3DnwRNHBHXDLJCJQ2xg/edit) . Yeah! 
Agree we should keep going and improving
