### ISSUE TITLE
Newsletter November 2022

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1043]

**Comment by ahmadabugosh** [comment]
Does anything else come to mind for the newsletter? @laurenluz @danelsuga @oyealmond @c0ric0ri

**Comment by WhyldWanderer** [comment]
Iranian projects - https://github.com/Giveth/giveth-planning/issues/1038

**Comment by laurenluz** [comment]
griff on greenpill podcast: https://twitter.com/BanklessHQ/status/1595063351779934208

I would love to feature "Relocating web3 iranians" as the featured project

also, for the GIVfarm thing, they key points are:
- we reimbursed everyone who lost and funds (framing - we take care of our users!)
- we launched the continuation of the CULT/ETH farm
- and FYI... we are not relaunching mainnet GIVfarms (but I think you could leave this out)

Giveth Project Owners 101 course?

And maybe we mention the new feature for donations to Giveth: https://twitter.com/Givethio/status/1595068459951525888

**Comment by danelsuga** [comment]
Thanks @ahmadabugosh ! To clarify, I'm not writing a piece on Greenpill at the moment but just making a huge summary so that it can be used to promote later on. I can totally write a recap ( @laurenluz @c0ric0ri ?), but it wouldn't be immediate. Only the detailed summary is coming immediately.

**Comment by danelsuga** [comment]
And by "detailed summary", I mean an internal doc.

**Comment by laurenluz** [comment]
Looks pretty good @ahmadabugosh - I left some small comments & suggestions.

**Comment by c0ric0ri** [comment]
I left some comments and tweaks as well @ahmadabugosh !

**Comment by ahmadabugosh** [comment]
Thanks @danelsuga yeah no worries, I think even as an internal doc though it would be useful to see your notes and highlight some parts of it. Maybe we should make an epic out of it as well and extract content for it for a blog post, tweet thread and video snippets? (especially since so many tools are mentioned, it would be great to tag all of those and it would get a ton of exposure)

Thanks @laurenluz and @c0ric0ri !

**Comment by laurenluz** [comment]
I agree that we can expand on the podcast & make some content out of it. After revisitng this though, I think we should add a mention in the newsletter since it is fresh... waiting a month doesn't make too much sense. and this is a really nice piece of content. I added a bullet point near the top ( and think we should add this in the tweet as well to replace the cult mention). @ahmadabugosh

**Comment by ahmadabugosh** [comment]
Will do! I just combined the suggestions, and I think it's good to go now @laurenluz @danelsuga
