### ISSUE TITLE
Iran Support Twitter Space

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1048]
When: Nov 7th

Who: Iranian projects, influencers, & points of contact who can speak to the topics

Topic ideas: what's going on in Iran, how it's affecting contributors there, how people can support (pointing to projects on Giveth), how web3 can be used for good for these types of issues

**Comment by c0ric0ri** [comment]
Twitter space candiates: Amin Solani, people at consensus, coin iran media platform, 30 or so people in a tg group that @GriffGreen is part of that we could push comms to and get support from.

**Comment by oyealmond** [comment]
Hey @c0ric0ri ! Same w/ this. We're pausing the support Iran campaign until we talk w/ the rest of the team. 
cc @laurenluz

**Comment by oyealmond** [comment]
moving this to backlog as is in pause

**Comment by c0ric0ri** [comment]
Moving this to icebox as we decided not to proceed with this campaign.
