### ISSUE TITLE
Vetting Iranian Support Projects on Giveth

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1049]
As mentioned by @WhyldWanderer & @NikolaCreatrix it is important to research the Iranian support projects before we publicize them as there are often scams during times of crises.

Here is a list of the projects @WhyldWanderer has seen come through so far with a focus on supporting the situation in Iran:

https://giveth.io/project/love-for-iran
https://giveth.io/project/stand-up-for-iranians-stand-up-for-web3-inclusivity
https://giveth.io/project/relocating-web3-iranians
https://giveth.io/project/stand-up-for-woman-life-and-freedom-movement

Let's build out a full list and get a review on it for legitimacy for our comms content.

**Comment by c0ric0ri** [comment]
Hey @NikolaCreatrix you mentioned you can support, so I'm assigning this to you if that's ok!

**Comment by NikolaCreatrix** [comment]
Hi there, I'm on it.

https://giveth.io/project/love-for-iran - could not confirm project legitimacy - the link for their twitter doesn't work. I am sending them an email asking if they can provide us with more detail about their online identity...
https://giveth.io/project/stand-up-for-iranians-stand-up-for-web3-inclusivity - LEGIT, twitter handle is @crypt0zan
https://giveth.io/project/relocating-web3-iranians - LEGIT, twitter handle @WiBlockchain
https://giveth.io/project/stand-up-for-woman-life-and-freedom-movement - Seems LEGIT, telegram chat here: [https://telegram.me/](https://telegram.me/navidkite)nkitefly

**Comment by c0ric0ri** [comment]
Thanks @NikolaCreatrix! Remember to move the issue to "In Progress" when you're working on it. 

So just to confirm, are there only 4 total projects? Griff mentioned there might be like 8-10 on the call, but I think @WhyldWanderer @oyealmond both said they found these 4 so I want to double check.

How do you all think we should proceed if the first project doesn't get back to us?

**Comment by NikolaCreatrix** [comment]
https://giveth.io/project/love-for-iran is LEGIT too, twitter handle @healing4iran

**Comment by c0ric0ri** [comment]
Moving this to icebox as we decided not to proceed with this campaign.
