### ISSUE TITLE
Compile list of previous Giveth contributors for airdrop

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#105]
As the Giveth community, we want to reward all past contributors to Giveth's development and operations.

Notes:
There are some spreadsheets floating around that list everyone. Here is a spreadsheet of known contributors over the past year: https://docs.google.com/spreadsheets/d/1Lp0Nw_9PD-HTbFTqzdLaMlNg0LcqjK010oHmV5duXyw/edit?usp=sharing 

Action items:
- [x] @ForestSoleil will schedule a hack sesh with @GriffGreen and @Danibelle to compile the complete list of previous Giveth contributors and contact info.
- [ ] We need to reach out to these individuals to confirm which address they want to use for the airdrop. If we don't hear back by x deadline, they won't be included in the initial airdrop, but ideally we can retroactively reward them with tokens held by the rGIV DAO if we hear from them after the deadline.
- [x] 4,000,000 tokens are allocated to past Giveth contributors. We need to determine how these tokens should be allocated. Here's a basic, in-progress example of allocating tokens to current contributors (would love some feedback/suggestions on this): https://docs.google.com/spreadsheets/d/1lNBQnqJeE80waHNV6yeoUjL_ffVsWNs4InPA8Fa-Drs/edit?usp=sharing 
- [ ] Once the list is finalized with addresses and amounts, the list is added to the final spreadsheet of all airdrop recipients: https://docs.google.com/spreadsheets/d/1rKHOzH54ijukDXGSq-690Ln_ojqFkrbbPuEaO1ex8ew/edit?usp=sharing

**Comment by Danibelle** [comment]
Griff and Dani hacked 2/17 and completed the list. 
Dani will work on the contact info next.

**Comment by ForestSoleil** [comment]
Bowen going through ~130 contributors list and updating contact info.

**Comment by ForestSoleil** [comment]
Bowen 15% complete with list. Work in progress. Building trust and doing outreach.

**Comment by WhyldWanderer** [comment]
Latest spreadsheet:
https://docs.google.com/spreadsheets/d/1Kp8WqRwDGyORqaDcXpeGR2PnhVTMKlTdU-eDRWeDBN8/edit#gid=1091643654

**Comment by ForestSoleil** [comment]
Hey @bowensanders can this issue for past contributors be closed?

**Comment by bowensanders** [comment]
Yes it can :)
