### ISSUE TITLE
Tweet Threads to promote Iran projects

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1050]
Idea here is to draft a few tweet threads talking about what is happening in Iran, and tying in promotion of projects who are addressing certain topics. Think of it as a themed fundraising effort.

It would help to review the [list of reviewed projects](https://github.com/giveth/giveth-planning/issues/1049) to see which ones correlate with each other, and around what topics. And also see what main topics are in the news.

The threads can be structured in this way potentially:

    - "This is what is happening in Iran" & these x projects are addressing it this way. We should agree on a couple outlines.
    - make sure to point out our USP in this: Giveth is willing to take on projects like this when others aren't (without pointing anyone out negatively, just focusing on the positive factor)
    - promote the fact that more projects like this can add themselves on Giveth
    - tie in how web3 is for good - this is a use case

I'd propose let's start with an outline of 2 or 3 threads which states what the topic would be, and which projects to promote around that topic. And once that's reviewed then someone actually write the threads.

**Comment by c0ric0ri** [comment]
@ahmadabugosh @clara-zi @danelsuga @laurenluz @oyealmond @tropicalmangos @NikolaCreatrix @WhyldWanderer  would love some input here on outlining 2 to 3 topics from the news that we could focus on for these tweet threads.

For each thread it would help if we can outline & agree on:

- A specific news topic
- a couple projects on Giveth that are gathering support to help this topic

**Comment by oyealmond** [comment]
I already drafted a tweet thread about 'Relocating Web3 Iranians’ project. 
Adding here the issue for visibility :) 
https://github.com/Giveth/giveth-planning/issues/1037

**Comment by c0ric0ri** [comment]
Here are some ideas on how we could outline 3 tweets for the projects Nikola already confirmed...

https://giveth.io/project/love-for-iran - TBD on verification

https://giveth.io/project/stand-up-for-iranians-stand-up-for-web3-inclusivity
**News Topic:** US sanctions against Iran are hard to understand and this is causing web3 to block support to web3 Iranians. 
**Promote this project:** raising to fund and draft guidelines with experts in the field of sanctions on the scope of economic sanctions against Iran and how best to navigate them within the crypto decentralized space.

https://giveth.io/project/relocating-web3-iranians - @oyealmond WIP tweet thread linked above

https://giveth.io/project/stand-up-for-woman-life-and-freedom-movement
**News topic:** the numbers of how many have been killed & arrested in the protests
**Promote this project:** fund legal aid for people in prison by hiring lawyers and providing legal fees and Bail for their temporary release, as well as helping the families of imprisoned people with legal follow-up and support for the families of those killed these days. 

"According to the Human Rights Activists in Iran organization, at least 233 protesters have been killed by regime forces as of 14 October, this figure includes 32 children and 1,500 people who were arrested during that time."

**Comment by oyealmond** [comment]
Hey @c0ric0ri! Just talked to @laurenluz & a couple of team members have some objections to the campaign idea. So I believe is better to stop working on this until we discussed w/ the rest of the team what are best actions to follow

FYI @WhyldWanderer @NikolaCreatrix @tropicalmangos @clara-zi @danelsuga

**Comment by c0ric0ri** [comment]
Moving this to icebox as it was decided not to proceed with this campaign.
