### ISSUE TITLE
The Giveth House Twtter Space. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1057]
Hey team! @c0ric0ri @laurenluz 

Here's the[ planning doc](https://docs.google.com/document/d/1MvHA-E-uK8xfvlJIsnOjHQq3mAAJuxqStQi8kC-wI84/edit?usp=sharing ) for the next Twitter Space. Could you please help me review the drafts of the tweets to promote? 

Thank you :)

**Comment by laurenluz** [comment]
Hey @oyealmond - great job!! I edited the tweets & scheduled them for next week.

**Comment by oyealmond** [comment]
yeeey ty so much @laurenluz !

**Comment by c0ric0ri** [comment]
Looks good! New hashtag?

**Comment by oyealmond** [comment]
yes! Ty for bring this @c0ric0ri . I was thinking in Stee recommendations for our twitter spaces of building a hashtag to brand them, thought #GIVtalk could be a good idea. But youre right. Let's standardized if first, we like this, & second in case we do, we like more #GIVtalk or #GIVtalks.

**Comment by laurenluz** [comment]
I think #GIVtalk works better if we want to write sentences around it.

**Comment by oyealmond** [comment]
https://twitter.com/i/spaces/1rmGPkVPgDgKN?s=20 :)
