### ISSUE TITLE
GIVbacks Round 24 Tweet

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1058]
Tweet to announce GIVbacks round 24.

**Comment by c0ric0ri** [comment]
Tweet thread draft:

https://docs.google.com/document/d/181GMbfSf_agXNSDUwn7kfxwDN_LiSAD-RKXLhvV-tZc/edit

@laurenluz

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1600491118503907329
