### ISSUE TITLE
Compile list of current Giveth contributors for airdrop

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#106]
As the Giveth community, we want to reward all currrent contributors to Giveth's development and operations.

Notes:
In progress spreadsheet of active, known contributors: https://docs.google.com/spreadsheets/d/1lNBQnqJeE80waHNV6yeoUjL_ffVsWNs4InPA8Fa-Drs/edit?usp=sharing

Action items:

- [x]  @ForestSoleil will schedule a hack sesh with @GriffGreen and @willyogo to make sure all current contributors are accounted for
- [x]  We need to reach out to these individuals to confirm which address they want to use for the airdrop. If we don't hear back by x deadline, they won't be included in the initial airdrop, but ideally we can retroactively reward them with tokens held by the rGIV DAO if we hear from them after the deadline.
- [x] 4,000,000 tokens are allocated to current Giveth contributors. We need to determine how these tokens should be allocated.
- [x] Once the list is finalized with addresses and amounts, the list is added to the final spreadsheet of all airdrop recipients: https://docs.google.com/spreadsheets/d/1rKHOzH54ijukDXGSq-690Ln_ojqFkrbbPuEaO1ex8ew/edit?usp=sharing

**Comment by laurenluz** [comment]
GIV token distribution: https://docs.google.com/spreadsheets/d/1vpoKMSYVIuV2Db84TVJC1AUPj9GReWg8qTkBoMfFyXA/edit#gid=865109239

Missing Eth addresses being hunted by Hannah:
https://docs.google.com/spreadsheets/d/1kxv4f1_YIo0czDGNt0viomFeJhPgWXZta3PiF-ZcC4U/edit#gid=0
