### ISSUE TITLE
Bear Market Content Brainstorm

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1060]
Based off our Comms discussion around building the voice of Giveth in the bear market, it would make sense for us to produce content around some topics that will build trust in Giveth with our community and especially new audiences. 

This will pair really well with our increase in Twitter Spaces and Podcast efforts, which will hopefully be reaching new groups. The goal is to position Giveth as an experienced, reliable DAO in the space in a time where user trust is struggling in web3. Our project is positioned to sustain the bear market because this is not our first time here, we create real impact on the ground and are therefore a real world use case, and we know web3 can do good things in the world. We know why we are here.

@danelsuga and I had a sync and started brainstorming some ideas for Medium articles that would be relevant + current topics. The articles don't necessarily need to be long, we can also create a series of shorter posts if we think that's best, but first just wanted to open this up for group feedback on the topic brainstorm. Then we'll break it up and prioritize from there.

Some first ideas:

- The advantage of transparency on chain for donations (how web3 enables this)
- Real world impact generated by a crypto platform (real world use case of web3)
- Supporting projects that could not otherwise accept fiat (conflict, local government, etc)
- How Giveth prepared for the bear market
- DAOs as resilient organizations (to sustain changing market conditions)
- Understanding crypto vs blockchain (they are not the same), and how do they enable web3 for good

**Comment by c0ric0ri** [comment]
@clara-zi @SymSL @laurenluz @tropicalmangos @oyealmond @franculio @GriffGreen @ahmadabugosh @Cotabe @WhyldWanderer @NikolaCreatrix

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri, nice idea! I think some other topics that would broaden the audience could be:

- Talking about the importance of self custody and P2P (which is why Giveth never holds the donations and is truly decentralized)
- Discussing the differences between CEX's and DEX's and different ways to offboard funds. For example, some of the ways that Shapeshift has on their site like Mt Pelerin or Onramper

**Comment by laurenluz** [comment]
Responding to the bear market idea (better than "we have always been prepared)
- rate of hiring
- mission-focused projects survive
- different culture around DAO spending
- $nice
- opt-in donations

**Comment by c0ric0ri** [comment]
Notes from discussion with @laurenluz :

Not sure how interesting the first point is, as we launched GivethTrace which didn't really work out and people didn't seem so confirmed with this topic. Perhaps this is a subset of another article.

Point 2 makes sense.

Lessons learned by Giveth in the bear market (instead of how we prepared for it). Having a substantial vision, values of web3 for public goods, having strong mission-focused drive isn't dependent on pumps

DAOs as resilient organizations is really interesting.

The last point has been written about a lot so probably doesn't make sense to rewrite crypto vs blockchain definitions, but more pointing out how dApps and builders are enabling web3 for good (and how cryptocurrency can do the same).

**Comment by oyealmond** [comment]
hey :) 

We have 2 interviews with outstanding projects (in Spanish) that we can frame with the web3 for good theme. 
These interviews are part of our Sea of Hertz partnership, could be used in youtube & twitter. 

We could organize some Twitter Spaces to close the year w some of these topics: 
- DAOs as resilient organizations 
- mission-focused projects survive 
- Decentralized Donations 

Dates available: 

Dec 7th
Dec 14th (GIVpower boosting launch) 
Dec 21th

**Comment by clara-zi** [comment]
> Medium articles that would be relevant

There is the option to add articles in Linked profile - wdyt about adding Suga's medium article to LI article also:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/100724132/204554615-d716c611-80b2-42d1-a9f2-8fcfb1589fcf.png">

**Comment by Cotabe** [comment]
I just got a couple of ideas on Giveth's voice on 2023.

1. Giveth is in a great position to grow despite the bear market. Even though many web3 projects may struggle to grow or survive on a bear market, Giveth can keep growing by offering a brand new and shinny toolkit to any non-profit or for a good project that might need it. We actually have the opportunity to grow much more compared to most web3 projects if we do harness this opportunity and reach more for good projects.

2. I think our voice in twitter, linked in, Facebook & Instagram should be at times more interactive and not exclusively read-only. Ask more questions, use polls. I stumble into this article today on my linked in (it's in Spanish https://www.linkedin.com/feed/update/urn:li:activity:7010233181874315264/) but it basically says that the most engaging content (on Linked in, but a lot of it can be extrapolated to other social networks) are:

a. Video Engaging and emotional connection.
b. Make questions. Share ideas, ask opinions, use polls. Let you users engage and hear what they have to say.
c. Storytelling. Tell stories of your users, or your contributors, 
d. Educate. Powerful format. It inspires, builds authority
e. Entertainment.
