### ISSUE TITLE
Email announcing GIVpower launch to Giveth database of GIVers & Projects - Dec 9

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1062]
This email should be ready to go out to announce our launch, right after GIVpower goes live on Dec 13th at 11AM EST.

Can reference email from Staking / Locking launch for drafting:

https://github.com/giveth/giveth-planning/issues/885

**Comment by laurenluz** [comment]
- embed the video
- link to blog or tweet
- have a mention about what this means for each audience - donors, projects, GIV holders
- link to giveth for sure so people can try it out

**Comment by c0ric0ri** [comment]
First draft of the email is here for review! @laurenluz @ahmadabugosh @WhyldWanderer 

https://docs.google.com/document/d/1zmnX5qeA7zb8n3aJchmsv7qetzjmw6z3VDODWJl55Kc/edit

**Comment by laurenluz** [comment]
ahh Cori  you forgot to make it comment access.

**Comment by laurenluz** [comment]
To save time, I just made a copy & added you as an editor - let's make this the new working doc: https://docs.google.com/document/d/1IqRajGDJq17UBDazfMzy4tFqtVAM42wsT0km7kKn0ek/edit

Left some suggestions, it's great! Don't forget to add in the links & video once it's ready!!

**Comment by laurenluz** [comment]
Not sure who is the best person to get this ready to go in autopilot. @ahmadabugosh @tropicalmangos @Cotabe @WhyldWanderer

**Comment by c0ric0ri** [comment]
Thanks @laurenluz! Implemented changes with one more suggestion.

**Comment by ahmadabugosh** [comment]
Sent!
