### ISSUE TITLE
MyCrypto - add GIV to this token list

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#1065]
website: https://mycrypto.com/

instructions: https://support.mycrypto.com/developers/add-token-to-default-list

**Comment by SnakeGH** [comment]
Adding Your Token as a Default Token

MyCrypto ships with a default token list that allows our Token Scanner functionality to check balances for a pre-determined set of tokens, which is displayed to the user.

If your token is not yet included on our default token list, you can add it at https://github.com/ethereum-lists/tokens. Once your token is on ethereum-lists/tokens, it will automatically be added to MyCrypto, usually within 12 hours.

If you want to add price data for your token, either reach out to us through Telegram or Discord, or add your token price information to our assets repository.

You can always email us for one-on-one help using support@mycrypto.com

**Comment by SnakeGH** [comment]
Reached out to our contact at MyCrypto to ensure we are listed on their token list

**Comment by SnakeGH** [comment]
Thanks to @MoeNick and Ramin, we have a JSON file to submit :)

**Comment by RamRamez** [comment]
> Thanks to @MoeNick and Ramin, we have a JSON file and it has been submitted here :)
> 
> [ethereum-lists/tokens#762](https://github.com/ethereum-lists/tokens/pull/762)

Our PR in MyCrypto is merged.

**Comment by SnakeGH** [comment]
Thank you @RamRamez and @MoeNick for all your hard work and assistance. Within the next 12 hours we will be listed on MyCrypto Token Exchange
