### ISSUE TITLE
Send an email invitation for our next workshop. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1070]
Hey dear team! gm! 

The one and only @Danibelle is hosting next week pimp your Giveth project workshop! A session dedicated to guide and support project owners improve their projects in order and get more funds. 

Could you please help me first, [reviewing the email draft](https://docs.google.com/document/d/1UydtFiLZyz2LutkWTHVBRjsWObTmZyYSL5-jVUk68no/edit?usp=sharing) to send it afterwards please? 

Would love your support. 
@c0ric0ri 
@ahmadabugosh 
@tropicalmangos 
@danelsuga

**Comment by danelsuga** [comment]
I gave it a quick copyedit. Nothing substantial. Can look again after others have a peek.

**Comment by oyealmond** [comment]
Ty @danelsuga !! 
a few more reviews and we will be good to go

**Comment by oyealmond** [comment]
yeees @tropicalmangos please could you help me put this email together?

**Comment by oyealmond** [comment]
Full list please! 
Could you schedule for Monday? 
@ahmadabugosh do you agree we send this on Mon, having in mind we just sent the newsletter? And also, could you help me review to have 3 reviewers pls ?

**Comment by ahmadabugosh** [comment]
hey @oyealmond yes I would say go for it on Monday or Tuesday, all good! :) 

Also, I made some suggestions on the doc to make it more attractive 😄

**Comment by oyealmond** [comment]
oh ty @ahmadabugosh ! 
Loved the edits! looks much better now. 
@tropicalmangos is ready to go now. 
Could you pls schedule for Monday morning Eastern time? 10 am Eastern may work!
