### ISSUE TITLE
Pimp your Giveth project workshop tweets :) 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1071]
Hey dear team! @c0ric0ri @laurenluz 

[Sharing some tweets to promote the Pimp your Giveth project workshop](https://docs.google.com/document/d/1NZOFjVJLQkkys0NO8bxgzm_RCh8F_sN7WDLeUqowpZA/edit?usp=sharing), facilitated by @Danibelle ✨

Could you help me review & schedule? I tried to keep these simple to attract Giveth followers attention. 

Thank you!

**Comment by oyealmond** [comment]
Thank you @c0ric0ri! 
Already accept them all.

**Comment by laurenluz** [comment]
Thanks both - I scheduled them. Had to make some small changes, one tweet was too long.

**Comment by oyealmond** [comment]
thank you so much!! @laurenluz @c0ric0ri

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1599403918261370880
https://twitter.com/Givethio/status/1600506179880452097
https://twitter.com/Givethio/status/1600128698094686208
