### ISSUE TITLE
GIV listed on DEX token lists

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#1072]
Using this new one to create an epic and add all specific token lists as individual issues under this epic

**Comment by oyealmond** [comment]
@SnakeGH can I close this epic?

**Comment by SnakeGH** [comment]
I'm good with closing it but @SteffanThorn has picked this back up recently, so I'm not sure if he wants to add his CEX & DEX's here too, or he has created his own issue
