### ISSUE TITLE
Transformative Impact Summit Tweet

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1073]
Griff & I are both representing Giveth on two panels at this conference.

The site: https://www.catalist.network/event/transformative-impact-summit
Their Twitter: https://twitter.com/globalunityorg

Panel 1:  Funding Impact At Scale - link: https://www.catalist.network/eventpage/1669392952517x358596098766420900
Panel 2: Web3 as a force for good - link: https://www.catalist.network/eventpage/1669756489485x765027985384122600

We're both on both panels. It would be great to have a thread about this ready to send out Dec 1 or 2 that invites people to join. (The panels take place on Dec 2)
- Tweet 1: intro to the summit, mention that Griff & I will be there
- Tweet 2 about panel 1
- Tweet 3 about panel 2

We should include links to where to join + tag all the people who will be on the panels in the appropriate tweets

**Comment by laurenluz** [comment]
@c0ric0ri or @oyealmond can one of you girls take this to have ready for tomorrow?

**Comment by oyealmond** [comment]
on it! @laurenluz @c0ric0ri

**Comment by oyealmond** [comment]
Ready[ Tweet thread](https://docs.google.com/document/d/1Qu6ParLFHNHiBE8luD8QoBPH50hoFXDxg9f7Ei7cwDQ/edit) whenever you can check it out! Ty! 

@laurenluz @c0ric0ri

**Comment by laurenluz** [comment]
Thanks @oyealmond ! I made some small edits in tweethunter and scheduled for tomorrow.

**Comment by oyealmond** [comment]
lg!!!!

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1598679186595627009
