### ISSUE TITLE
Q&A GIVpower Twitte Space! - Dec 14

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1075]
Hey team! 

We're having a Q&A Twitter Space on the 14th around GIVpower boosting launch, with a couple of action items to be done: 

· Gather beforehand questions around GIVpower to include in @c0ric0ri's Script. - @oyealmond 
· Include the Twitter Space info to add to the press release email https://github.com/Giveth/giveth-planning/issues/1027, & the GIVpower Twitter partner outreach email https://github.com/Giveth/giveth-planning/issues/887 - @oyealmond & @c0ric0ri 
· Create a data base w donors, project owners & GIVholders to reach out inviting them to join & participate asking GIVpower questions.  @SnakeGH , could you help us on this? 

The details: 
Dec 14th 
9 am CT
Host @c0ric0ri 
Guests @laurenluz @divine-comedian

**Comment by SnakeGH** [comment]
Hey @oyealmond can wait to see GIVpower go live and good news, the donors, project owners and partnerships that I have performed outreach can be conveniently found in our CRM Hubspot. The exact reason we started this. Feel free to play around and find everything you need there, and of course, I am here to help or direct you to the right spot as needed :)

**Comment by divine-comedian** [comment]
Is there a calendar invite? :sweat_smile:

**Comment by oyealmond** [comment]
yeah, I sent it to ecp.ozz@gmail.com. But maybe was not the best email @divine-comedian can you share the best email pls?

**Comment by laurenluz** [comment]
Ok @oyealmond ! I used your ideas for the promo tweets and changed them - sheduled and set for tomorrow at 1pm & then wed morning before the space!

left the old tweets in there too for inspiration

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1603027843562315779
https://twitter.com/Givethio/status/1602725799651590146
https://twitter.com/Givethio/status/1602705443985440769
