### ISSUE TITLE
Twitter Content Batching for Holidays

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1078]
@laurenluz will be taking the last 2 weeks of Dec off (19-30) so we should content batch a number of tweets to schedule out Twitter as much as possible during this time.

For reference from the last batching we did in August/September: https://docs.google.com/document/d/13RjNKMopItIAWtwVKh7U18Syq_2CYAGeZHOzQBQJa1U/edit

Topics to create tweets around:

- GIVbacks are out! Tweet Thread (biweekly ish)
- Verified projects Tweet Thread (biweekly)
- GIVpower reminders (weekly)
- Recycled soundbites
- Newsletter end of month
- Project Owners 101 Course reminder
- Donor 101 Course reminder
- Promote Medium articles

**Comment by laurenluz** [comment]
GIVpower related:
- round is almost over (before Dec 27)- last chance to affect the very 1st rank of giveth projects!
- new GIVbacks round (Dec 27)- now projects have a rank! when you donate to projects, you can get a different % of GIVbacks back, boost projects to affect their next weeks round

And I would do basically at least 1 if not 2 GIVpower-related tweets for the next several weeks.
