### ISSUE TITLE
Tweet Thread for R24 Verified Projects

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1079]

**Comment by NikolaCreatrix** [comment]
Working on it here:

https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by NikolaCreatrix** [comment]
Ready for review here: :) https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by c0ric0ri** [comment]
@NikolaCreatrix reviewed and left some comments! Looks like @laurenluz did too.

If you can possibly clean this up on Thursday (tomorrow) that would be ideal so we can already tweet it out this week :)

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1600884593476902918

**Comment by laurenluz** [comment]
This was GREAT Nikola. Your 1st tweet was amazing! I knew you could do it!
