### ISSUE TITLE
Create Spec doc for Airdrop UI/UX

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#108]

**Comment by ForestSoleil** [comment]
Included in Deployment Spec: https://www.notion.so/giveth/Spec-Deployment-499a05e59ccb4c20bed780bd13acf4fb

@markoprljic do you need more specific info than what is outlined in the above document?

**Comment by markoprljic** [comment]
I'm a bit out of loop on all this in the spec, need someone to walk me through form a bigger picture. You up for this @ForestSoleil or maybe @laurenluz @divine-comedian ?

**Comment by laurenluz** [comment]
I'd be happy to! We can have a call today if you want, my day is really light on calls

**Comment by ForestSoleil** [comment]
were you two able to connect? @laurenluz @markoprljic let me know if any additional clarity is needed around airdrop ui/ux =)

**Comment by markoprljic** [comment]
> were you two able to connect? @laurenluz @markoprljic let me know if any additional clarity is needed around airdrop ui/ux =)

Yes, all done. Thanks!
