### ISSUE TITLE
GIVpower launch Twitter Thread - Dec 9

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1081]

**Comment by laurenluz** [comment]
Include "join our Twitter space"!

**Comment by laurenluz** [comment]
should ask people to submit their questions for our AMA

**Comment by laurenluz** [comment]
Got a draft! @oyealmond @c0ric0ri - want to review?

https://docs.google.com/document/d/1BjoNjXbGd2O8xbRR9U8Wls56mcxBleXnkoUwgNF6fpk/edit

**Comment by c0ric0ri** [comment]
OK I made a bunch of suggestions @laurenluz

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1602705396946423813
