### ISSUE TITLE
Update GIVbacks documentation because "up to 75" isn't right anymore

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1082]
We should mentioned that it was up to 75% *before* GIVpower launch... and then changes Dec 13.

@divine-comedian - can you draft it?

https://docs.giveth.io/giveconomy/givbacks#getting-givbacks

**Comment by divine-comedian** [comment]
Actually I already wrote this - you can find it at the bottom of the GIVpower documentation draft
https://docs.google.com/document/d/1pIwsCE9k2rlnEVtbESLI2TxBJHwDio-JHFvhi4gsag0/edit?usp=sharing

**Comment by laurenluz** [comment]
https://docs.giveth.io/giveconomy/givbacks
