### ISSUE TITLE
Giveth Year in Review

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1083]
An article summarizing & linking out to Giveth's major accomplishments, milestones, and activities in 2022.

Including, for example:

- Product launches / GIVeconomy development
- Events attended
- ETH Barcelona as a major event sponsored (with 100 new donors onboarded)
- Key talks given
- Number of new contributors onboarded?

Open to more ideas here, the above are just some to start with. 

Maybe it's cool to structure it as 12 sections (12 months of the year) and reference the relevant activities under each? 

Helpful: https://www.getrevue.co/profile/giveth/add_subscriber

**Comment by c0ric0ri** [comment]
Hey @danelsuga I think you would be great to take on this piece, as you have been in the team since almost the start of this year and do a great job with recaps. Would you be up for it?

Would be great to have it prepped to post around New Years time - either right before or right after, when the timing is most relevant.

**Comment by danelsuga** [comment]
Thanks for thinking of me, but I will be taking a chunk of time off just before the end of the year. I can work on something before and after possibly, but it seems like a bit of a crunch! Maybe if we could create an idea dump doc, and I can work on shaping it perhaps. However, @laurenluz will be on vacation from Dec. 19 to Jan. 2, so it seems slightly not good to write a piece like this without her input and guidance.

**Comment by c0ric0ri** [comment]
Another route we could go is sketching an outline first for approval (would this be more palatable for you to do @danelsuga?) and then having someone else write & fill in the piece based on that outline.

The outline could simply be a bulleted list under each month of the year that captures the major points, and then someone else can take on the writing next week.

**Comment by danelsuga** [comment]
I can make time next week to write. But yeah would be awesome if a collaborative outline were in the works first.

**Comment by c0ric0ri** [comment]
Ok let's use this draft to start outlining! https://docs.google.com/document/d/1DlfWTOogWd80AMeHoSEleGSgomBKk2sVHeJIoKiIcus/edit

**Comment by c0ric0ri** [comment]
@ahmadabugosh , would you have some capacity to help us fill in this outline using the newsletters from the past 12 months? Even if you copy and paste the main highlights in first, then we can narrow it down and clean it up from there

**Comment by laurenluz** [comment]
If we have something for review next week I will happily check it out before leaving! and can make time on vacation for a final look :) Thanks @danelsuga for thinking of me, I do really like to have opinions on our blog posts 😅

**Comment by c0ric0ri** [comment]
@WhyldWanderer would you be able to help fill in some of the earlier months on this outline? The Giveth newsletter only dates back to May, I'm pulling highlights from there but maybe you have some ideas from the first quarter of the year.

**Comment by c0ric0ri** [comment]
I've created a first outline draft based on all past 11 newsletters. Can you take a first look with your experience @WhyldWanderer @danelsuga @laurenluz? 

Do we want to keep everything in there? Anything significant missing?

**Comment by danelsuga** [comment]
Thanks, @c0ric0ri. Looking good. Yes, 12 sections is the most manageable way, I think. It's going to be a whopper of a doc!

**Comment by laurenluz** [comment]
love the 12 sections. I left some comments & a section at the bottom with some ideas... just sat with griff and brainstormed.

I think a bunch of them are really cool.

**Comment by c0ric0ri** [comment]
Thank you! Also - I just received an email of Celo's year in review article, which is a great example to check out:

[Celo Year in Review Email.pdf](https://github.com/Giveth/giveth-planning/files/10248380/Celo.Year.in.Review.Email.pdf)

**Comment by clara-zi** [comment]
I like the way the newsletter info has been summarised into monthly sections but wdyt about organising all that info into topics to help the reader understand the progress made during the year - in particular, this could improve understanding of progress of roadmap and development of GIVeconomy. In no particular order, categories (summarised from newsletter headlines) could be something like this:

- Conferences / Events / podcasts / talks / interviews
- GIVeconomy / GIVbacks / Regen Farms / Product launches / $NICE
- Partnerships
- The heroics / Positive spin on unfortunate events and what we learned.
- Training / Giveth Education for Projects and donors / Giveth 101 and Hitchhiker’s Guide
- The redefining of the way public goods are funded & Giveth roadmap progress in leyman terms with a sprinkling of cryptoanarchy
- Donation / project highlights

I think it would be good to start with an intro of Giveth community and also a reflection on how this crazy year has changed / impacted Giveth.

**Comment by clara-zi** [comment]
> I could use some support getting these metrics together in an organized list based on the feedback in the draft, our analytics dashboards, and quick final review from Griff perhaps. Can @ahmadabugosh or @clara-zi help?

WIP list here: @c0ric0ri 
https://docs.google.com/spreadsheets/d/1bvgTMeoJ3mH6xQETT9dX0CL6nGYGnKrsHhx3xhWz0QM/edit?usp=sharing 

@NikolaCreatrix @WhyldWanderer please double-check and confirm verified projects numbers in sheet.
@freshelle @Nicbals - There is a section for no. of contributors and the no. of different countries they are based (end 2021 vs end 2022).
@laurenluz I've added some GIVeconomy stats - please check nos / complete fields, add or remove stats to better present info
@ahmadabugosh What you got in Google Analytics? Who else can I ask.

Please feel free to add, comment, edit etc. Thank-you.

**Comment by NikolaCreatrix** [comment]
Hi there, @clara-zi I updated the number of Verified projects as well as the total n of new projects. If you want to ping me in dm shortly before sending this out, and I can do a final update.

**Comment by c0ric0ri** [comment]
I've started drafting the intro message for this. Do we want this to come from @GriffGreen (like Celo's version) or should it read as coming from the Giveth DAO?

Do we want this to be an email to our existing base, or a blog post to sit on our Medium? Wdyt?

@ahmadabugosh @laurenluz @danelsuga @WhyldWanderer

**Comment by danelsuga** [comment]
I can review tomorrow. I think Giveth DAO is better. Imo we don't want to encourage use of some centralized, authoritative (read more important) voice.

**Comment by danelsuga** [comment]
Definitely on Medium.

**Comment by c0ric0ri** [comment]
Hey @danelsuga @ahmadabugosh @clara-zi @tropicalmangos @WhyldWanderer I could really use review support in double checking all the points & metrics over the 12 months, adding links & tags, & ensuring the wording is good.

The intro page is also ready for a final review.

It's definitely a lot to cover and we want to put it up by the end of this week, so  I would really appreciate a collaborative Comms team push on this tomorrow (Thursday) if you have capacity!

Would love to get your reviews @GriffGreen @laurenluz as well

**Comment by c0ric0ri** [comment]
@clara-zi I love your ideas around categories, but due to the time frame to get this out, the 12-month breakdown is going to be faster to execute. I think we could create a separate piece on our learnings or something similar that could leverage your structure however.

**Comment by laurenluz** [comment]
scheduled to publish tomorrow at 8:29 am ET

@c0ric0ri it would be awesome if you made a post tomorrow in the announcements channel (tag @ everyone, and hit "publish" after you post it) in discord, and ask everyone to clap for it.

it's an awesome post, I really love it!!
