### ISSUE TITLE
Get GIV and other tokens listed on Trust Wallet

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1087]
Getting the GIV token and potentially other tokens in the GIveth Galaxy listed on Trust Wallet. There is an option to add a bulk list of tokens so we can try to get as many of our friends in there as possible! 

The Trust Wallet will help the GIV token image show up in Uniswap.

Can coordinate with @GriffGreen @Zeptimus  for support and outreach to other communities

**Comment by SnakeGH** [comment]
At this time, we have listed GIV on all DEX that have been recommended. Closing this issue for now
