### ISSUE TITLE
Tweet the Pimp my project workshop video :) 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1088]
Hey team! @c0ric0ri @laurenluz 

[Made a draft for a tweet to share ](https://docs.google.com/document/d/1obiSuf4CIgwapALakuZ7QykXO896Y33uAzYb9iCNBAg/edit)the recent Pimp your project @Danibelle s workshop. It was very successful! Hope to have it again next year. 

Let me know your thoughts.

**Comment by laurenluz** [comment]
I made some edits directly & scheduled for tomorrow - thanks girl!

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1601215866900815872
