### ISSUE TITLE
Translate GIVpower & GIVbacks  docs into Spanish

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1092]
The GIVpower doc is ready to go! 

We should get a full spanish translation for it.

Also parts of the GIVbacks documentation have been modified and need to be translated as well. 

here is the final GIVpower doc
https://github.com/Giveth/giveth-docs/blob/givpower-final/dapps/GIVpower.md

here is the final GIVbacks doc
https://github.com/Giveth/giveth-docs/blob/givpower-final/dapps/givbacks.md

here is the current GIVbacks doc 
for comparison:
https://docs.giveth.io/giveconomy/givbacks/
and the current spanish version:
https://docs.giveth.io/es/giveconomy/givbacks/

Who can take this?? @tropicalmangos @franculio @oyealmond @Cotabe 

JFYI @c0ric0ri

**Comment by franculio** [comment]
Hey @divine-comedian ! I'll start working on the translations today and put a google doc here for review when ready.

**Comment by franculio** [comment]
OK! Here's the doc with the translation I did. It really needs reviewing, there was a lot of specific terminology that was difficult to translate into Spanish. Maybe @oyealmond @Cotabe @mateodaza @Santigs could give it a read and see if everything looks fine?

**Comment by oyealmond** [comment]
Omg, this was so hard!! Praise @franculio for doing the hard work to translate this into Spanish! 
There are several therms that we should agree on how the translation will be like: "impulsar" I think will be better if we leave in "boostear" for mkt purposes. Also Stalking , I think the spelling shoulde be "Stalkear" . But this is really hard as I believe in Spa theres no smth Stablish yet. 

I made some comments, but it needs more reviews @divine-comedian

**Comment by franculio** [comment]
Thank you @oyealmond so much ! I completely agree that we should find correct translations for specific words, it was the main challenge I found. 

Boost = Boostear 
Stake = Stakear? (Stalk means something else)
Unstake = Unstakear? 
Rank = "Puestos/clasificación" or we just use "Rank" which is also understandable in Spanish?

**Comment by Cotabe** [comment]
@franculio @oyealmond Great work.

I agree with leaving the term in English and spanishize them.... however I think the first time they come up we should put quotation marks and provide a definition.

Boost = "Boostear", impulsar un proyecto con tu GIVpower.
Stake = "Stakear", depositar tu GIV en los contratos inteligentes de Giveth (el contrato está hecho de tal manera que cuando quieraas lo podrás retirar)
Unstake = "Desestakear" (creo que me gusta un poco mas que unstakear, aunque tampoco me gusta mucho), retirar tu GIV de los contratos inteligentes de Giveth.
Rank = "Ranking" (se usa mucho en México), la clasificación que se le da a los proyectos basada en quien tiene más GIVpower.

**Comment by franculio** [comment]
Gracias @Cotabe ! I'm going to go through the doc again and correct this terms and see how I can include the quotation marks and definition. 

One more:
Lock = "Bloquear" no? esa la dejamos así?

**Comment by divine-comedian** [comment]
check out this guide for making hover tooltips using html

https://www.w3schools.com/howto/howto_css_tooltip.asp

**Comment by franculio** [comment]
@divine-comedian I've revised it and and I think this [translation for GIVpower](https://docs.google.com/document/d/1T6aFcOSPQTdGPE6f-uue-k6iFxwdmfBpaAXPN-Iprpo/edit?usp=sharing) is ready. Do you need me to write it in a MD file? 

I'll start with the updated translation of the GIVbacks today.

**Comment by divine-comedian** [comment]
> @divine-comedian I've revised it and and I think this [translation for GIVpower](https://docs.google.com/document/d/1T6aFcOSPQTdGPE6f-uue-k6iFxwdmfBpaAXPN-Iprpo/edit?usp=sharing) is ready. Do you need me to write it in a MD file? Or what is the next step?
> 
> I'll start with the updated translation of the GIVbacks today.

Yes definitely needs to be in an .md file - ideally I can empower you to make a PR yourself so you can more directly update the docs

**Comment by franculio** [comment]
> > @divine-comedian I've revised it and and I think this [translation for GIVpower](https://docs.google.com/document/d/1T6aFcOSPQTdGPE6f-uue-k6iFxwdmfBpaAXPN-Iprpo/edit?usp=sharing) is ready. Do you need me to write it in a MD file? Or what is the next step?
> > I'll start with the updated translation of the GIVbacks today.
> 
> Yes definitely needs to be in an .md file - ideally I can empower you to make a PR yourself so you can more directly update the docs

Yeah! I got a little bit confused with my last PR, let me put it into an MD and then I'll ask for help with the PR.

**Comment by laurenluz** [comment]
is this done @franculio ?

**Comment by franculio** [comment]
This is done
