### ISSUE TITLE
Tweet Thread R25 Verified Projects

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1093]
Working on the next one for R25, I am aiming to have it done this week.

**Comment by NikolaCreatrix** [comment]
Hello ladies, this time I let myself go a little wild with the lead tweet, let me know if you like it...it might need to be shortened....

The draft is ready for your review here @laurenluz @c0ric0ri  I am just adding some emojis:

https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by laurenluz** [comment]
It's great @NikolaCreatrix ! Can you clean it up a little and I'll schedule it for next week?

I left suggestions and would love you to see them

**Comment by NikolaCreatrix** [comment]
Ready. 👍

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1605206893961543681
