### ISSUE TITLE
Project Owners 101 Course Reminder Tweet

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1096]
We launched the course back in November and it makes sense to promote it again during the holiday weeks. It's a good time for learning, reviewing talks and course work.

Would be great to have a good Quote Tweet drafted that links to the tweet thread launch of the course.

**Comment by ahmadabugosh** [comment]
@c0ric0ri I think it would be good if we get a promo video as well to boost it. 

Maybe if @GriffGreen doesn't have time, @laurenluz can help with a short one?

**Comment by c0ric0ri** [comment]
@oyealmond would you be willing to pick this one up?

**Comment by oyealmond** [comment]
Hey sure! One question, the same tweet I drafted for https://github.com/Giveth/giveth-planning/issues/1097 issue is useful for this too? 

@c0ric0ri

**Comment by oyealmond** [comment]
Hey @c0ric0ri & @ahmadabugosh :) 
[Here's the quoting for projects ](https://docs.google.com/document/d/1D86NuaMT7hBVeZ3JzVcFCMGJ_SmaMjZeVSjaU1N7fpY/edit) let me know your thoughts!

**Comment by laurenluz** [comment]
I DM'd @GriffGreen to see if he's down to record a video, I think it would be great! if he can't, I could do something.

What do you have in mind particularly @ahmadabugosh ? A "this is why raising funds in crypto is important"? or "this is why giveth is a unique opportunity for projects"?

@oyealmond - I edited your tweet a little in the doc, it's great. video or no video we can put this out next week.

**Comment by laurenluz** [comment]
@Danibelle might be the best choice for recording this video - I reached out to her.

We can also use almond's tweet and make a new issue for the video... share the course multiple times.

**Comment by GriffGreen** [comment]
yeah I can do it, or lauren but really Dani represents the projects on the platform really well and would make a great opening video IMO

**Comment by Danibelle** [comment]
I can do this tonight yes.. so under a minute.. audience is project owners, intention is..  
With Boosting live and the holidays upon us, opportunity abounds.. whether you have a project already or are preparing to create one, the project owners video course is full of tips and tricks to share your story and reach your fundraising goals.. 

Let me know anything I missed or misunderstoood?

**Comment by laurenluz** [comment]
yeah! that's great Dani!

**Comment by Danibelle** [comment]
@c0ric0ri @ahmadabugosh @laurenluz 

Let me know if this is what you are looking for!
https://user-images.githubusercontent.com/39466970/209557416-b4138b15-5b9f-4be2-bd86-814124d18a9b.mp4

**Comment by ahmadabugosh** [comment]
Thanks @Danibelle !

I think I'll create a video like this out of it: https://www.canva.com/design/DAFV9UaiUEg/EK6yya_bEqpvxc5DSBD0YQ/edit?utm_content=DAFV9UaiUEg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton


1) Do you have a version of the video with just you (without the background)? 
2) Are you ok with your name and title how I displayed it? 
3) @laurenluz @c0ric0ri , Do you have any feedback on the video ?

**Comment by c0ric0ri** [comment]
Hey @Danibelle @ahmadabugosh can you please copy this info over to the relevant issue for the video? https://github.com/Giveth/giveth-planning/issues/1017

**Comment by laurenluz** [comment]
hahah it's cuuute @Danibelle - let's go for it @ahmadabugosh

**Comment by ahmadabugosh** [comment]
hey @laurenluz the video file is here if it's ready to be tweeted out: https://drive.google.com/file/d/1w4dx6YDRk6UmcogzTvAEapNhkLREZFyY/view?usp=sharing

**Comment by laurenluz** [comment]
@tropicalmangos - do you want to make a new quick draft for a tweet that will include this video & shill the project owner's course?

The tweet in this issue was already sent out but I think it's good to do one more.

Can be a single tweet or a very short thread... should definitely link to the course (and perhaps also to the pimp my project workshop in another tweet).

**Comment by laurenluz** [comment]
These are awesome @tropicalmangos ! 

I can use them both.
