### ISSUE TITLE
Donor 101 Course Reminder Tweet

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1097]
Would make sense to promote this during the holiday weeks, which is always a good time for learning.

This can be drafted as a Quote Tweet to promote the original launch thread, maybe framing it around "giving back for the holidays is a great time to make your first donation on Giveth!"

**Comment by ahmadabugosh** [comment]
@c0ric0ri How about we do a combined "learning tweet thread" and combine the Donors and Projects 101 course together?

**Comment by c0ric0ri** [comment]
@ahmadabugosh we could do that, but I also think they speak to very different audiences so was thinking more like targeted messages to each with a retweet of the original launch threads.

But I'm open, wdyt @oyealmond @laurenluz ?

**Comment by c0ric0ri** [comment]
@oyealmond would you be willing to pick this one up?

**Comment by oyealmond** [comment]
hey sure!

[I draft smth](https://docs.google.com/document/d/1D86NuaMT7hBVeZ3JzVcFCMGJ_SmaMjZeVSjaU1N7fpY/edit). Is this what you were expecting? 
Lmk your thoughts. 

@c0ric0ri

**Comment by oyealmond** [comment]
Hey team! I made a new thread as I found the o[riginal tweet kind of old](https://twitter.com/Givethio/status/1529482655343034370) and w/ content that may not be valid anymore. 
[Let me know your thoughts :) ](https://docs.google.com/document/d/1YErqAq0epyEQ1SNq3lZ3vmi6AOAFUYpM2WMXLBCMnnA/edit)

**Comment by laurenluz** [comment]
Awesome @oyealmond - I made some edits, will schedule for next week
