### ISSUE TITLE
GIVpower Reminder Tweets

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1098]
Copied from @laurenluz comments:

GIVpower related:

- round is almost over (before Dec 27)- last chance to affect the very 1st rank of giveth projects!
- new GIVbacks round (Dec 27)- now projects have a rank! when you donate to projects, you can get a different % of GIVbacks back, boost projects to affect their next weeks round

And I would do basically at least 1 if not 2 GIVpower-related tweets for the next several weeks.

**Comment by c0ric0ri** [comment]
Drafts are here: https://docs.google.com/document/d/1_CFzNi1JydDHk4jjm6d8UnzZKtTbuqOB5_orywD0hLM/edit

**Comment by laurenluz** [comment]
I made some edits & added to these and scheduled them
