### ISSUE TITLE
Propose projects for launch

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-planning#11]

**Comment by Danibelle** [comment]
Add projects here!
https://www.notion.so/giveth/5c5e9754be5541298b9751b9d124f19d?v=685ce97feae04812b628d6b16a4a4b20

**Comment by Danibelle** [comment]
Costa Rica Crew / Diamante Bloom Project List:
https://docs.google.com/spreadsheets/d/1P5V11UcVmbws3qDAvMWX57hKfq_CN19aYXntT3aPe2w/edit#gid=0
