### ISSUE TITLE
1 Year Anniversary GIVbacks Rounds Tweet

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1101]
At the end of Round 26, it will be our one year anniversary of rewarding donors with our token. 

It would be cool to celebrate it in a tweet, and we should also find out how many GIV tokens we have rewarded to donors this year!

**Comment by laurenluz** [comment]
WhyldWanderer(Ashley) — Yesterday at 6:20 PM
So far... for rounds 1-24, we have distributed 9,178,180 GIV which equals $666,354.23 if you use the value of GIV at the time of each round's calculation.. 
We just need the numbers for rounds 25 and 26

**Comment by laurenluz** [comment]
We also have a great christmas POAP, and it is the very last round before the new ranks take effect w/ GIVpower

**Comment by laurenluz** [comment]
This tweet is:
- our last round in a full year of GIVbacks (1 year anniversary)
- christmas time
- the very last round that all projects get 75% GIVbacks before GIVpower rankings take effect

I'm trying to see if we can get an animated POAP for the occasion & encourage more donations

**Comment by c0ric0ri** [comment]
@WhyldWanderer thanks for adding the numbers for Rounds 25 & 26 tomorrow, you can throw them in right here!

**Comment by ahmadabugosh** [comment]
hey @c0ric0ri the amount for round 25 takes the total to over 10 Million GIV, so I think we can just use that. 
 
 I made a draft of a thread here: https://docs.google.com/document/d/1AuZrE5WPoi0wiErkQ5UhBkchalPAELdydUpkLvURieY/edit

**Comment by c0ric0ri** [comment]
Reviewed!

**Comment by WhyldWanderer** [comment]
> @WhyldWanderer thanks for adding the numbers for Rounds 25 & 26 tomorrow, you can throw them in right here!

R25 - 961943.01 GIV - $21068.90
R26 - 149411.2 GIV - $2636.03

**Comment by ahmadabugosh** [comment]
hey @c0ric0ri, thanks for the feedback, I added the $ amount instead of the GIV amount (which is above $690K). 

Who's going to schedule out this tweet thread?

**Comment by c0ric0ri** [comment]
@laurenluz is handling all scheduling, I've let her know about this one

**Comment by laurenluz** [comment]
I scheduled it for tomorrow. FYI - GIVpower ranking takes effect this round... like as of Dec 27... so now you can get up to *80%* of your donation back in GIV (if you donate to the top ranked project). (The 3rd tweet was actually incorrect).

Please check out our docs and make sure that the GIVpower/GIVbacks stuff is crystal clear for you, and if it's not, lmk so I can help clear it up. (just so that we get this right in all our future comms).

https://docs.giveth.io/giveconomy/givbacks#rank--calculation

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1608825992524488704
