### ISSUE TITLE
Determine ICP (ideal customer profile)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1102]
Stee was suggesting we improve our bio further (after launching GIVpower) on the Twitter, but before doing so should determine our ideal customer profile.

He asked me to fill this out: https://www.notion.so/ICP-Ideal-Customer-Profile-30acbc147622423da014b93f0ac93441

Maybe this is something you could take on @c0ric0ri ?

**Comment by laurenluz** [comment]
@oyealmond - FYI - might interest you

**Comment by oyealmond** [comment]
thank you ofc! 
I don't have access tho, I need to ask Stee for access . One sec!

**Comment by oyealmond** [comment]
**(Please read before going through the profiles)** 
I based these 3 profiles in Stee's division (Which is great) . 

1. **The newcomers** are ppl without Crypto experiences willing to learn and be part of a Web3 community. These can be creative profiles (for ex) without a specific Web3 interest. Just learning what everything is about. The attractive offer I figured: "come join a stablished and respected Web3 community, learn, contribute & get rewarded" . 

**2. The second is more of enthusiasts w/ not much time in the Space, but w/ a lot of passion.** They understand Web3 & want to build their own projects. The offer I figured for this profile is: "Come to Giveth and open a project in which you can fund your dream using Web3 innovations" . 

**3. The third profile, I thought in ppl experiences (specially in DeFi) w/ interest in social impact.** This was hard tho. Basically philanthropists w/ DeFi knowledge that will be interested in using Blockchain4Good. The offer is: "Join the GIVeconomy, an economy that empowers and rewards donors for giving." (advanced DeFi GIveth products)  


1. [Newcomers/ Web3 novices](https://www.notion.so/Newcomers-Web3-novices-556168c7ec5847899fb873b3f9af81d5)
2. [Active Users/Web3 players](https://www.notion.so/Active-Users-Web3-players-8cc0a4cd3d264e06934c5fbcf5c6d56e)
4. [Experienced Users/Web3 players](https://www.notion.so/Experienced-Users-Web3-players-7b449cfcda664fc8b0c900a42c4bbc8b)

I believe the next step will be to check this profiles, complement/give feedback on them, and start creating messaging for all three. 

@laurenluz @c0ric0ri 

@WhyldWanderer (this is kind of what we were talking today :D)

**Comment by oyealmond** [comment]
Update: 
Stee reviewed & made some fixes. I think he nailed it :) 
Will be great if we can make some space to present this early next year in one of the comms calls. 
@laurenluz @c0ric0ri
