### ISSUE TITLE
Tweet about donating to Giveth over the holidays

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1103]
Short tweet or thread speaking to a DeFi audience, which can be easily shared or referenced by DeFi protocols during the holiday season.

We want to highlight that we are DeFi-for-good, and a great option to give back during the holidays (give back for GIVbacks!)

The idea would be to link to this tweet in a newsletter blurb and in outreach communications to various DeFi protocols who have new user-bases for us to get in front of.

**Comment by c0ric0ri** [comment]
Drafting here: https://docs.google.com/document/d/1DTx6iUOb6aeF8HXAbGgq5oh7AfEazzclqHlBnqLmipo/edit

**Comment by c0ric0ri** [comment]
@laurenluz @GriffGreen @Cotabe @divine-comedian would love reviews & your input here. I went  for something a little different.

I tried to avoid using any Giveth jargon (GIVbacks, GIVeconomy, etc) or niche jargon (public goods, refi, etc), and then I also included a straightforward appeal for participation. 

My take is, we position ourselves heavily as building DeFi-for-good in a time where DeFi holds extra weight in the industry and that we need help to really get it off the ground - honest, but not desperate.

**Comment by clara-zi** [comment]
@c0ric0ri love that this tweet thread avoids jargon to keep it accessible.

I've been thinking. The purpose of this campaign is to **bring extra donations for our projects** over the holiday season.

**People donate with their hearts and not their heads** - it's usually in response to a charitable plea, an emotion and is often spontaneous. They want to help alleviate some suffering or satisfy some other emotional need. 

This tweet thread is wonderfully educational and informative but as a potential donor - it is not clear to me that I'm expected to donate and doesn't give me enough of that warm, fuzzy, holiday giving feeling. 

The wording is technical and Giveth product focussed. We should get inside the head of the donor. 

Here is an example of what I mean.
“Give & make change this holiday & empower grassroots communities to solve problems where they are. Help fight climate change, provide education, alleviate suffering or make the world a better place through tech at Giveth.io.

CTA: Donate crypto on Giveth & receive rewards as thanks”. 

Then I think we can add the GIVeconomy info without overpowering the basic message and CTA to donate. **Most important is that it’s clear we want people to donate.**

FYI Some reports that discuss motives for charitable giving in more detail:
https://www.theguardian.com/voluntary-sector-network/2015/mar/23/the-science-behind-why-people-give-money-to-charity 
https://www.cafonline.org/my-personal-giving/long-term-giving/resource-centre/why-do-people-give

Look at this from Save the Children:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/100724132/208393534-65611d1e-6a2d-4636-b61c-c5d2566896ea.png">

**Comment by MoeNick** [comment]
> @c0ric0ri I think would be a perfect one for the filtering landing pages you mentioned, but it might be too soon for the holidays [Giveth/Roadmap#45](https://github.com/Giveth/Roadmap/issues/45)
> 
> @MoeNick Do you know if there's a simple way for us to spin up a landing page on our site that wouldn't take much dev resources?

Hey, the blocker is more on the design side than implementation I guess, if you have something ready for these 2 days @mosaeedi @Tosinolawale we can jump into it very quickly.

**Comment by laurenluz** [comment]
@c0ric0ri i reviewed your thread, i think it's great. Male a couple of comments in there. Once you're done with it, DM me and i can schedule it when you need.

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1605594294974152706
