### ISSUE TITLE
Newsletter Blurb & QT Support for Holiday Outreach

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1104]
A short blurb that we can offer to DeFi protocols to slide into their holiday newsletter during the giving season.

We want to highlight that we are a great option to give back during the holidays (give back for GIVbacks!), and we can link to our tweet (https://app.zenhub.com/workspaces/giveth-planning-5f08ce1f9264b300166a0185/issues/gh/giveth/giveth-planning/1103).

**Comment by clara-zi** [comment]
https://docs.google.com/document/d/1HgsakJkLB8NdYlY24rNJhtQKIXkq5_uy-WZIBOdQT9Y/edit

link to .doc with newsletter, cold outreach and some Tweet example for QA
@c0ric0ri @SymSL @laurenluz @danelsuga @SnakeGH

**Comment by clara-zi** [comment]
There are 4 options for newsletter blurb. I think we only need one option perhaps two? @c0ric0ri do you want to select the blurb that best fits the campaign?

**Comment by clara-zi** [comment]
Other draft messages:
Initial outreach: 
https://docs.google.com/document/d/1HgsakJkLB8NdYlY24rNJhtQKIXkq5_uy-WZIBOdQT9Y/edit 

Some sample Tweets for orgs to use that either don't have a newsletter or prefer to Tweet us:
https://docs.google.com/document/d/1bHnoDQthDxRwsDcPwC3G7ox3JbwPv4S9PL-xgIaDmkE/edit

**Comment by c0ric0ri** [comment]
Thank you so much @clara-zi & @SymSL !

I've cleaned this up for external use in this document: https://docs.google.com/document/d/1M9R7g4e59jEJaF_bGtroO7fWZIqpf2xsXXwErMVIv3w/edit

**Comment by laurenluz** [comment]
Just reviewed, some small comments. This is great @c0ric0ri @clara-zi !
