### ISSUE TITLE
Promote Dec AMA on Twitter. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1108]
Hey @c0ric0ri :) 

[Could you review this draft & schedule for tomorrow Tue 20 Dec? ](https://docs.google.com/document/d/1rRiOmAchhjUtJ2E5GtkIh6vtiu_iBsNFXEfgdV4jYMo/edit)
Is to promote our Wed AMA call. 
Ty!

**Comment by c0ric0ri** [comment]
Reviewed with suggestions!

**Comment by oyealmond** [comment]
accepted @c0ric0ri :) 
thanks!

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1605194516750909442
