### ISSUE TITLE
Newsletter December 2022

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1111]

**Comment by ahmadabugosh** [comment]
Topics to include:

1. Launch of GIVPower 
2. End of year donation push + special POAP
3. Gitcoin Grants 2.0 on Fantom
4. Coordination Mechanisms - Green Pill Podcast Highlights
5. GIV listing on CoW Swap

Anything else come to mind @laurenluz @c0ric0ri ?

**Comment by c0ric0ri** [comment]
1 year anniversary for GIVbacks on Dec 27 (total GIV we've distributed till then!) and other cool stats

**Comment by SnakeGH** [comment]
@ahmadabugosh , just listing them, here, if any of the other DEX inclusions are worth mentioning with CoW swap too, but these are the other new ones this month: Kleros, Ethereum / MyCrypto and Zerion

**Comment by ahmadabugosh** [comment]
@SnakeGH nice, those are all good too!

Are there any GIVfriends / partners you think we should shout out ?

**Comment by SnakeGH** [comment]
was MyNFT already spotlighted, I can't remember if that happened last month or not?

**Comment by ahmadabugosh** [comment]
@SnakeGH yes last month we featured them :)

**Comment by SnakeGH** [comment]
@ahmadabugosh I had a sneaking suspicion that was the case. Maybe @spectoregia might have some org from the grants side that she would like to highlight or give a guest blurb to help in our grant outreach potential...

**Comment by ahmadabugosh** [comment]
It's ready for review: https://docs.google.com/document/d/19uxhS3AbrVInbw1PXMg05wlYv0EPDsh0HlRIvL1y5OE/edit# 

I want to send it out Friday, so please let me know if you have any comments before then 🙏 @c0ric0ri @danelsuga @laurenluz

**Comment by danelsuga** [comment]
Thanks @ahmadabugosh ! I desperately want the Greenpill summary article included. Are you done editing @GriffGreen ? Is it good to go after that @laurenluz ? I've got it up-to-date. Waiting for Griff's final edits, if any (I had two questions for you under Praise). 🙏

**Comment by danelsuga** [comment]
Meanwhile, I read the newsletter and left comments and edits. Thanks @ahmadabugosh !

**Comment by laurenluz** [comment]
@ahmadabugosh - reviewed - this should be good to go tomorrow!

**Comment by laurenluz** [comment]
Hey @ahmadabugosh - jthis just came up... the "giveth year in review" is scheduled to publish on our medium tomorrow morning at 8:29am ET.. 

It would be nice to include a bullet on that and a link to it in the newsletter as well so we get more eyes on it :)

**Comment by ahmadabugosh** [comment]
Thanks @laurenluz @danelsuga and @c0ric0ri !

I just incorporated your feedback (and I also added a bullet point about the year in review if you can take a quick look @danelsuga )

**Comment by danelsuga** [comment]
Looking good @ahmadabugosh !
