### ISSUE TITLE
Cover for GM! podcast episode 1. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1113]
Hey Rodri :) 
Could you please helo me create a design for the GM! podcast episode 1? 
The size needed is Cover for Youtube. 
As we discussed it should have Griff and Brett places somewhere. 

**Text:**  

GM! podcast hosted by Griff Green
Ep 1 What is money? With Brett Scott 
[Image of Brett Scott here](https://drive.google.com/file/d/1H4fKNKcDS7ACTl50ynBW60TlBudYUKWE/view?usp=sharing)

***

Pls feel free to place the text as you think will look better.

**Comment by rodricastillo9013** [comment]
![EP1](https://user-images.githubusercontent.com/61791380/209335713-d889921f-fcd6-4e6f-a73e-fbf0bd83675d.png)
wdyt?
