### ISSUE TITLE
Regen Foundation - Community Spotlight Tweet

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1116]
This is related to this issue: https://github.com/giveth/giveth-planning/issues/1030 

@c0ric0ri could you help me [review and schedule this community spotlight tweet please](https://docs.google.com/document/d/1turIF3i8DZICP2FyL5HYMCMLdbDgN5Bu48uEU9jYj2k/edit)? 
Tnx!

**Comment by c0ric0ri** [comment]
@oyealmond reviewed! needs a few more edits, please take a look. We'll need to DM this to @laurenluz to schedule.

**Comment by oyealmond** [comment]
ty @c0ric0ri :) 
Pinging @laurenluz .

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1608101295285567489
