### ISSUE TITLE
Binance Charity 

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#1117]
https://www.binance.charity/

Research if they have a grant opportunity or just apply as an NGO / project on their platform

**Comment by SnakeGH** [comment]
They do not have a direct application portal, will need to email them for more information at: 

bcf@binance.charity

**Comment by spectoregia** [comment]
email is sent - waiting for reply.

Also in a different issue @tropicalmangos made this comment regarding Binance:
https://github.com/giveth/giveconomy/issues/772

"https://binancex.dev/
Apply here: https://forms.monday.com/forms/214bb8567c3ab90aa19a7bb405e669ef"

I will also apply on this form just in case.
