### ISSUE TITLE
Tweet reminding about Fantom Gitcoin Grant

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1118]
We should tweet it again before Jan 2

**Comment by c0ric0ri** [comment]
Draft here @laurenluz 

https://docs.google.com/document/d/1vETxoxTfCbQLBgIZ75JbJ86xCzuP2eo7sN6scpDBnN4/edit

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1608540861117210627
