### ISSUE TITLE
Tweet for Project Ranking Forum Post

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1119]
Now that GIVpower has launched, we are looking for ways to level up our project curation and ranking game.
Here is a forum post discussing how we can improve the way projects are shown on the Projects page.

Besides GIVpower rank, we want to include a way for project owners that may not hold GIV or have little GIV because they are using their donations to complete the mission of their project. We are discussing using Pairwise (Budget Box) for this and including this score in the ranking. Pairwise is a tool that would allow verified project owners to curate projects.

In addition to GIVpower and Pairwise, we would also take into consideration impact of a project that would be integrated into the project verification system.

This and more!

It would be so great to hear the opinions and feedback of our community. 
Participate in the conversation and help steward the direction and evolution of the donation platform!
💜 

https://forum.giveth.io/t/concrete-project-ranking-model/944

**Comment by oyealmond** [comment]
Hey team! @c0ric0ri @laurenluz made 2 versions :D , one without ranking factors (to avoid bias), and a second w/ factors for you to choose what you think is best. 

https://docs.google.com/document/d/1yPdQbevmKlCrdXRrz51uMjgK8GFzzMGagHH8FswVIgA/edit

**Comment by laurenluz** [comment]
These are good @oyealmond but after looking through it a few times, I don't think we should tweet this soon... we need to sort out our internal thoughts first.

iceboxing.

**Comment by oyealmond** [comment]
Agree. @laurenluz :) thanks for the update!
