### ISSUE TITLE
SEO Optimization on a monthly basis

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#1121]
In the GIVeconomy Call, @MohammadPCh mentioned that it is hard to find Giveth via google and that SEO should get updated every month... I agree! How can we prioritize SEO?

**Comment by MohammadPCh** [comment]
Hey guys :)
I was thinking that how can a user find us? I mean imagine I'm a guy that wants to donate to a good project, what I will search on google? 
do we have some keywords and regularly analyze our rank on google for them?
as much as I know about SEO, we need to create more content and update them regularly. to be top on search results.
think about a blog that has many links to our pages, with rich content that describes our missions, our features, and maybe our projects.
consider about one post each week.
I think we need a workgroup for it and regularly analyze our SEO metrics.
actually, SEO, and google ranking system is a competition. and if we have a plan to acquire users from there and be a winner we have to be ready for it. :heart: 
@GriffGreen @ahmadabugosh @c0ric0ri

**Comment by ahmadabugosh** [comment]
Thanks for flagging this @MohammadPCh ! I'll bring this up in our comms call. It's something that we used to do, but haven't for a while, it's a good reminder to start having tasks that we do at least once a week or month. 

FYI, before we did an audit back in March of last year for the relevant [keywords here](https://docs.google.com/spreadsheets/d/12WramHIFG2dZDI7PA-Pwqsa_dQHR3yRFi_msaV0dUWo/edit#gid=0),
