### ISSUE TITLE
Tweet about GreenPill summary blog - coordination mechanisms

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1122]
Could be a thread or a simple tweet, for next week.

https://medium.com/giveth/coordination-mechanisms-notes-from-a-conversation-with-griff-green-kevin-owocki-af95f3e831b1

@c0ric0ri @oyealmond - if you want to take this, go ahead, or I can do it if it doesn't get picked up sooner.

**Comment by oyealmond** [comment]
Hey @laurenluz @c0ric0ri! 
Wdyt?[ I made a short recap](https://docs.google.com/document/d/1djkaenyGLmIJjPoVFbHpzDugxFxpY3pr5KLpPDq91x0/edit) to also be an informative useful tweet that ppl could share.. 

i can add more Coordination Mechanisms, or make a 1 tweet CTA instead.

**Comment by laurenluz** [comment]
Thanks @oyealmond !!

I think I would like to get the article out there sooner (i.e. in the 1st tweet) so I revised a little, and moved things around. I scheduled it for tomorrow.

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1610275582561886213
