### ISSUE TITLE
Tweet about the Trivia Takeover

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1123]
Hey dear team gm :) @laurenluz @c0ric0ri 

[Could you help me review this draft to tweet our next week's Trivia special edition? ](https://docs.google.com/document/d/1-RM2OR8JaQvfLI8TEHbwYrcV-73W4Vz8lAxDWiYMuXQ/edit)

Thank you so much!

**Comment by laurenluz** [comment]
scheuduled :)

https://twitter.com/Givethio/status/1609936840345231360
