### ISSUE TITLE
Create a graphic announcing GM! launch for Twitter. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1129]
Hola @rodricastillo9013 :) 

Como platicamos hoy ocupamos un diseño para Twitter anunciando el estreno de GM! podcast con Griff Green. 
La info que habría que agregar es: 

GM! podcast hosted by Green Green launch 
Jan 13th 
10 am CT / 5 pm CET
At: @Givethio Tw & Yt (¿a lo mejor aquí agregar los símbolos de Twitter y Youtube en vez del texto?) 

***
¿Que te parece? 
Muchas gracias!

**Comment by rodricastillo9013** [comment]
hey team, i've already talked to lauren, i'll start this this week! I keep them updated!

**Comment by oyealmond** [comment]
![Twitter_-_Post](https://user-images.githubusercontent.com/110692280/210677424-edc51698-0bb0-4031-86f0-146978ec9e64.jpg)
