### ISSUE TITLE
Video announce of Bloom Network & Giveth Partnership

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#113]

**Comment by ForestSoleil** [comment]
3/5 Marketing update:
- Scheduled for early next week, will confirm calendar time.

**Comment by ForestSoleil** [comment]
Do we want to re-record this and discuss the coming value add to our Giveth verified projects? @Danibelle @magentaceiba

**Comment by ForestSoleil** [comment]
@Danibelle @WhyldWanderer @laurenluz @divine-comedian  Do you feel this is valuable to re-record? Maybe with a different spin on the value add for verified projectsm that we decided as a part of Bloom Network's agreement?

**Comment by WhyldWanderer** [comment]
Yes!

**Comment by laurenluz** [comment]
+1 to yes!

**Comment by magentaceiba** [comment]
I'm down. I think we should write a shared agenda to have a coherent flow - Dani and I have such a long history together and the whole thing is such a big story that focus will be helpful for viewers to follow us. <3

**Comment by ForestSoleil** [comment]
Great! Please let us know when this is scheduled. @magentaceiba @Danibelle

**Comment by laurenluz** [comment]
@Danibelle if this isn't happened, can we close the issue?
