### ISSUE TITLE
Tweet Thread Verified Project R26

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1130]
I will ping you when its ready for review, working on draft here:
https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by NikolaCreatrix** [comment]
Hey hey ready for review @laurenluz & @c0ric0ri 

https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing 

...finally...sorry for the holidays delay, didn't quite plan on that.

**Comment by laurenluz** [comment]
This was awesome Nikola! I wanted to send it out today, so I just made direct edits in tweethunter: https://twitter.com/Givethio/status/1611399454380199938

Please have a look at the thread to see what I changed. The main things:
- check to make sure the tweets are 280 characters or less (many were too long)
- cut out words where possible... like "a project focusing on mitigating.." could just be said as "a project mitigating..."

Also - looooved the 1st tweet so much. Tweethunter said it was "high potential" 😄 

I'm thinking for future threads, we can keep in mind GIVpower... so we can say like:
"Donate or boost this project to...".. just keep in mind that we now have those 2 CTAs for verified projects :)

Great work.
