### ISSUE TITLE
Send Panvala partnership email for project owners! 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1131]
Hey dear @ahmadabugosh & @tropicalmangos! 

Very soon we'll announce the partnership w/ Panvala! 
Verified Projects on Giveth will have the chance to earn more $$$ thanks to the Panvala Stamps program. 

We need to send an email for Project Owners announcing this new opportunity. 
The sending date will be defined next Tuesday, in the meantime, 

[Can you please help me review this email draft?](https://docs.google.com/document/d/1zKhcdssaEuiPhabqAKQOnmlecL22eICMJTxKYf7-tqY/edit?usp=sharing)

cc @danelsuga @ahmadabugosh @tropicalmangos @c0ric0ri

**Comment by oyealmond** [comment]
fyi @WhyldWanderer 🧚🏻‍♂️

**Comment by ahmadabugosh** [comment]
Thanks @oyealmond, I left some comments on this one and the other one for donors.

**Comment by danelsuga** [comment]
Thanks @oyealmond ! I left some comments too. Will pass again after you have a look and integrate.

**Comment by oyealmond** [comment]
Thank you you all! 
@danelsuga @ahmadabugosh, I did some edits following your comments. 
[Can you check out again please? ](https://docs.google.com/document/d/1zKhcdssaEuiPhabqAKQOnmlecL22eICMJTxKYf7-tqY/edit)

**Comment by danelsuga** [comment]
I'll give it a go in the morning (12 hours from now).

**Comment by danelsuga** [comment]
Looking great! Love the new changes. Well done.

**Comment by oyealmond** [comment]
Hey team! we already defined a date for the Panvala emails to be send! Will be this thursday Jan 12th. So @ahmadabugosh , could you help me sending this email to project owners on the 12th please?

**Comment by ahmadabugosh** [comment]
Sent!

**Comment by oyealmond** [comment]
Thank you so much @ahmadabugosh !
