### ISSUE TITLE
Send Panvala partnership email for donors!

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1132]
This issue is related to https://github.com/Giveth/giveth-planning/issues/1131. 

The same way we're announcing the Panvala partnership for projects owners, we're sending a separated email for **Giveth donors** with a slightly different CTA.  

Same as https://github.com/Giveth/giveth-planning/issues/1131, the sending date will be define next Tue. 

[In the meantime, can you review this draft too please? ](https://docs.google.com/document/d/1DifsFdq_foqZnmRDDyJGDe1v71RGvqGSWF5AKIqM2JM/edit?usp=sharing)

cc @c0ric0ri @ahmadabugosh @danelsuga @tropicalmangos

**Comment by oyealmond** [comment]
fyi @WhyldWanderer 🎩

**Comment by ahmadabugosh** [comment]
Reviewed!

**Comment by danelsuga** [comment]
Reviewed by me too.

**Comment by oyealmond** [comment]
Hey @danelsuga @ahmadabugosh, same here, 
[could you give a final check please? ](https://docs.google.com/document/d/1DifsFdq_foqZnmRDDyJGDe1v71RGvqGSWF5AKIqM2JM/edit)
Thank you so much!

**Comment by danelsuga** [comment]
Yes. In 12 hours. :)

**Comment by danelsuga** [comment]
Looking good to me.

**Comment by oyealmond** [comment]
Hey team! we already defined a date for the Panvala emails to be send! Will be this Thursday Jan 12th. So @ahmadabugosh , could you help me sending this email to donors on the 12th please?

**Comment by ahmadabugosh** [comment]
Sent to Donors (but if they were a project and a donor, they should have got just the project email)

**Comment by oyealmond** [comment]
This is great. Thank you so much as always @ahmadabugosh .
