### ISSUE TITLE
Send GM! podcast launch press release. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1133]
Hey dear team! 

Asking for support to send the GM! podcast press release to our media data base, I'll like to send this email next Wed Jan 11th / am CT. 

But first, could you check it out? @ahmadabugosh already reviewed doing great edits. @danelsuga @c0ric0ri @laurenluz need some more eyes :)[ I tried to write this email w/ in a more fun & reliable style. ](https://docs.google.com/document/d/1q67W9hYHR-7Om9k52x_dfOB8bBcyxu81JEga12mHp7U/edit)

**Comment by danelsuga** [comment]
OK, I had a go. :)

**Comment by oyealmond** [comment]
Great suggestions @danelsuga! Thank you :) 

@c0ric0ri @laurenluz , [could you check it out? ](https://docs.google.com/document/d/1q67W9hYHR-7Om9k52x_dfOB8bBcyxu81JEga12mHp7U/edit)We're missing one more review.

**Comment by oyealmond** [comment]
hey @ahmadabugosh :) 
We already have enough reviews for the [press release](https://docs.google.com/document/d/1q67W9hYHR-7Om9k52x_dfOB8bBcyxu81JEga12mHp7U/edit) to be send. Can you please send it am CST this Wednesday Jan 11th please? 

[Also I added new emails for the data base,](https://docs.google.com/spreadsheets/d/1ZrifFUwZ6YvunEdye_wpkAscAhmEqYuE-dM8igLuHEM/edit#gid=1443039363) can you add them before sending the email?

Thanks!

**Comment by ahmadabugosh** [comment]
Looks good @oyealmond, when do you want to send it out? Can it wait for next week (since we're sending out a lot of messages this week)?

**Comment by ahmadabugosh** [comment]
Sent!

**Comment by oyealmond** [comment]
Your the best @ahmadabugosh ! Thank you so much!
