### ISSUE TITLE
GM! podcast launching tweets. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1134]
Hey dear team! @laurenluz @c0ric0ri 

[I drafted some tweets for the GM! launch :) ](https://docs.google.com/document/d/1lBbYAjOlZvzzrW0S4-zJpXLT9tto6jqbxB6tQ_CsIrw/edit)
I will really appreciate your feedback. I draft them short, & to the point to not loose attention. 

Thought to start tweeting next week. 

Thank you :D

**Comment by laurenluz** [comment]
They good @oyealmond !

I made small changes, waiting to hear back from you in DM and we'll have them out next week.

**Comment by oyealmond** [comment]
aww, I loved the 🌞 GM! 🌞 style :) 

they're perfect the edits you made regarding youtube and twitter! 
Ty so much as always! @laurenluz

**Comment by c0ric0ri** [comment]
I left some comments and edits as well, awesome job!

**Comment by oyealmond** [comment]
Ty @c0ric0ri !
