### ISSUE TITLE
Outreach to Denver non-profits

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1136]
# Jan 5 relevant notes

> - [ ]  Ashley/Almnd coordinate w/ nonprofits
    - Ashley’s update - in touch with bryan from Cut the Plastic. He has defined some of the needs of the Denver community and we are working to create quests around these needs.
    - Almond’s update - 
    Already contacted:
    - [[Denver Pet Partners](https://giveth.io/project/denver-pet-partners)](https://giveth.io/project/denver-pet-partners)
    - [[Denver Scholarship Foundation](https://giveth.io/project/denver-scholarship-foundation)](https://giveth.io/project/denver-scholarship-foundation)
    - [[Boys And Girls Clubs Of Metro Denver Foundation](https://giveth.io/project/boys-and-girls-clubs-of-metro-denver-foundation)](https://giveth.io/project/boys-and-girls-clubs-of-metro-denver-foundation)
    - [[Metro Denver Homeless Initiative](https://giveth.io/project/Metro-Denver-Homeless-Initiative-0)](https://giveth.io/project/Metro-Denver-Homeless-Initiative-0)
    * waiting for them to answer. 
    Any other organization to contact?
    - test onboarding change projects from denver - projects look very basic - wouldn’t want to feature them for impact quests
    - maybe non-profits are hard to work with - have been hard to communicate with denver non-profits
    - IRL art?? - they have a project on giveth - maybe they can help us connect with more projects
    - bryan is connected to mutual aid communities
        - food clothing, personal care needs, people in transitional housing or other arrangement
        - huge migrant crisis happening - last week or so, got a lot of people sent from texas by non-profits into denver
        - compounding problems from current transient housing issues
    - sundays - occupy wall street / Janet’s Kitchen
        - headwaters protectors - take water and sanitation services to bring them fresh drinking water
        - monday mutual aid
    - bryan can make a letter of introduction email with givether (ashley?) to all these groups he is in touch with
    - gmail is the best way to contact bryan
        - make some plans to move forward
    - has been doing outreach in the last 10 years in denver!
    - looking to do quests - is there anything close to the convention center that people can interact with for non-profits or charities
    - 20 blocks or more to service area providers
    - heather interned at mental health clinic that was nearby once upon a time
    - could coordinate with these groups to take people down to pick up supplies - they could help us out with logistics
        - bryan can help make those arrangement with other mutual aid workers!
        - sunday morning/monday night event - could provide transportation if we want to bring people to an event

**Comment by WhyldWanderer** [comment]
## Notes from Jan 12 meeting

    - Ashley’s update - Layla from MDHI, Brian will connect
    - Almond’s update - Idea about project owners joining us at the booth for sections of time and discussing posters or best ways to highlight non-profits
    - [[Impact Quest Coordination Doc](https://www.notion.so/Impact-Quest-Coordination-1ccd7c3184384b9f9b6be792f7a2bacd)](https://www.notion.so/Impact-Quest-Coordination-1ccd7c3184384b9f9b6be792f7a2bacd)
    - Send emails to all change projects - Almond to send emails
    - Heather can help to do outreach
    - use network effect
