### ISSUE TITLE
Create POAPs for Impact Quests

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1137]
# notes from jan 5 meeting 

> - [ ]  Create POAPs for each impact quest. - Rodri
    - will start when quests are more defined - ashley will coordinate for POAPs with rodri
    - could make a base template and just change the text or the lettering
    - have at least 10 different quests for impact quests
    - colorado landscapes
    - maybe we need the same POAP art for FLII
        - maybe we need a separate set
    - rodri is a rockstar and can handle all this no problem

**Comment by WhyldWanderer** [comment]
Hey @rodricastillo9013!

As promised, here is the list of confirmed impact quests that we have so far:

- Donate items to the clothing collection

- Donate items to the non-perishable food collection

- Donate to a Denver based project on Giveth

- Make a twitter post featuring 3 of your favorite Giveth projects

- End or prevent homelessness for 1 local Denver household (partnering with Metro Denver Homeless Initiative - https://www.mdhi.org/) - their giveth project https://giveth.io/project/Metro-Denver-Homeless-Initiative-0

- **This one should me extra fancy! Maybe animated?** 
Deliver pizza to the homeless - Collab with PizzaDAO (maybe we want to include some design assets of theirs?) 

- **This one should me extra fancy! Maybe animated?** 
Complete an in-person volunteer shift by signing up with Hedera Hashgraff (we probably want to include some design assets of Hedera's in tandem with Giveth) - they are working on getting approval for design use.

I will add the others in this issue as we confirm them.

I think we want a unique image for each that portrays creating local impact in Denver... we can include Colorado landscapes, 
It should have the words 'Impact Quest' and 'ETHDenver' somewhere on each image... also I think we should include the year.

**Comment by WhyldWanderer** [comment]
![image](https://user-images.githubusercontent.com/74267818/221253480-82dfa3f8-4208-41c5-b322-e152ffe1d830.png)
![image](https://user-images.githubusercontent.com/74267818/221253493-87682fa4-88c5-4bbf-b60c-c8be436579d2.png)

The first two are complete, reviewed, and confirmed... making the drops now.. requesting 500 links for each.

**Comment by WhyldWanderer** [comment]
![image](https://user-images.githubusercontent.com/74267818/221412295-586fd0cb-081a-4988-9c84-24e563e50f01.png)
![image](https://user-images.githubusercontent.com/74267818/221412296-048f2c4a-0634-403a-bb2d-30f1710f57e3.png)
![image](https://user-images.githubusercontent.com/74267818/221412300-54825534-b87c-4f66-9722-540e13ae44de.png)
![image](https://user-images.githubusercontent.com/74267818/221412301-3088962d-f19f-4aa1-91c0-d3a8613af62d.png)

**Comment by c0ric0ri** [comment]
Can we close this issue? @WhyldWanderer
