### ISSUE TITLE
ETH Denver Budgeting

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1142]
# notes from jan 5 meeting

Contributors are asking… they want to know.. will Giveth cover any of the expenses to attend this event? Plane tickets? Accommodation? Etc?

- for both eth denver and FLII we should make some sort of budget - if everything fits then that’s great but otherwise we deal out percentage discount

what budget makes sense?

flights? 80% reimbursement?

do a percentage base up to a cap

accomodations?

coordinate budgeting accounting with freshelle 

griff says 15k is a lot - maybe too much for a budget

ashley will start writing a document

**Comment by WhyldWanderer** [comment]
Ashley is working on creating a budget outline with Dani and Freshelle - confirming who all plans to come and related expenses. More updates next week.

**Comment by laurenluz** [comment]
do you need this issue @freshelle - or can I close it? I know it's not quite done, but I don't see it as useful really and I'm cleaning the board.

**Comment by freshelle** [comment]
Yup, we can close this @laurenluz
