### ISSUE TITLE
email to invite GIVpower users to special session. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1144]
Hey team! 

We're organizing a special session to gather feedback around GIVpower. We'll send an email to[ GIVpower users](https://docs.google.com/spreadsheets/d/1EJ1MLgs_oKNmsaG-ix-MJsDCbvoclBXi2nKxx6-_90k/edit#gid=0) inviting them to join & participate. 

Could you help me check this[ email invitation draft](https://docs.google.com/document/d/1iOZfShouZIY-3XZpEjUlJIcTcGqUmRggURKFnKfKPWA/edit) please? This will be send through Giveth's email. 

cc @danelsuga @ahmadabugosh @c0ric0ri @laurenluz

**Comment by danelsuga** [comment]
Will do! In 12 hours. :)

**Comment by danelsuga** [comment]
OK, I gave it a pass. Looking good.

**Comment by laurenluz** [comment]
good stuff @oyealmond ! no comments

**Comment by oyealmond** [comment]
Hey @ahmadabugosh! 
How are you? 

Could you help me send this [already reviewed email invitation](https://docs.google.com/document/d/1iOZfShouZIY-3XZpEjUlJIcTcGqUmRggURKFnKfKPWA/edit), **to [this email list of the GIVpower users](https://docs.google.com/spreadsheets/d/1EJ1MLgs_oKNmsaG-ix-MJsDCbvoclBXi2nKxx6-_90k/edit#gid=1377469046) please?**

**Comment by ahmadabugosh** [comment]
@oyealmond sent! 

Btw, I had to change the Google calendar link (the one you included didn't have the timezone built into it). 

How I got around this was:
1) Duplicating the event to my own personal calendar
2) Clicking "Publish event"
3) Take the link from there (which does include the timezone)

**Comment by oyealmond** [comment]
thank you as always @ahmadabugosh for making things better!
