### ISSUE TITLE
Tweet Panvala partnership announcement. :D

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1145]
Hey team! @c0ric0ri @laurenluz 

We're announcing our Panvala's Partnership that will allow project on Giveth to get extra funding through their Stamps program on **Thu Jan 12th**

[I drafted this pair of tweets](https://docs.google.com/document/d/1hXJYLQrYHIGnuteBJPCweHVmnMo5GUGZT3o573t44mA/edit) announcing the launch. 
Could you check out please, & help us sharing your feedback? 

Thank you :)

**Comment by oyealmond** [comment]
cc @WhyldWanderer

**Comment by c0ric0ri** [comment]
Reviewed and suggested some edits!

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1613556484872323074

https://twitter.com/Givethio/status/1614624200462897153
