### ISSUE TITLE
Gitcoin Protocol Alpha Tests Jan. 17-31

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#1146]
Gitcoin has become fully decentralized! To that end, they are transitioning to a different way of setting up grants. 

Thus far, we are invited to participate in the Jan. 17-31 Gitcoin grants round. (Others include UNICEF and Fantom [Dec. 2022] and Optimism and Alchemix [Feb. 2023].) Info here:  https://go.gitcoin.co/blog/announcing-the-gitcoin-alpha-tests

I have updated our grant based on their old formatting, assuming it will remain the same. https://docs.google.com/document/d/1tC7AiyYwzxSX3hbpQSaT_zKqnzHmu3xYRuS7wKRtgFg/edit#

Please help with Giveth updates essential to this grant proposal. Thanks.

@laurenluz 
@ahmadabugosh 
@GriffGreen 
@c0ric0ri

**Comment by brichis** [comment]
Hey! Sorry for sneaking around but do you know where we can share some feedback about the Alpha test with Fantom? :D Thank you!

**Comment by danelsuga** [comment]
Sorry @brichis I have no idea. Giveth was not part of the Alpha test with Fantom.

After a little poking around, I found this:

https://support.gitcoin.co/gitcoin-knowledge-base/misc/contact-us

There is a feedback link on the closed grants round page, but it didn't work for me, maybe because we weren't in it. You could try that too: 

https://grant-explorer.gitcoin.co/#/round/250/0xebdb4156203c8b35b7a7c6f320786b98e5ac67c3 (under "Help" on the right.)

You can also just email support@gitcoin.co for further support.

**Comment by danelsuga** [comment]
Back to the issue at hand, I'd love some more feedback on the Gitcoin grant proposal. Thank you!
 https://docs.google.com/document/d/1tC7AiyYwzxSX3hbpQSaT_zKqnzHmu3xYRuS7wKRtgFg/edit#

@laurenluz
@c0ric0ri

**Comment by c0ric0ri** [comment]
Reviewed @danelsuga and left some suggestions!

**Comment by danelsuga** [comment]
Everybody cool if I take care of setting up the new grant? Requires wallet connect, banner, links, etc. No sweat for me but want to know if someone else desperately needs to do this @laurenluz @GriffGreen ?

https://grantshub.gitcoin.co/

**Comment by danelsuga** [comment]
Since it seems this grant will be submitted and unmodifiable at that point I'm thinking, @GriffGreen and @laurenluz , that maybe it shouldn't feature what's been going on recently and instead provide a full overview. It is no longer an extension of previous Gitcoin grants, correct? And so we are not "updating" it. We are applying anew for a grant. What do you think?

**Comment by laurenluz** [comment]
This is really urgent to get up, tried DMing you @danelsuga earlier.

I'm going to jump into it now and see if I can get it in asap, unless  I hear from you sooner.

**Comment by danelsuga** [comment]
Yes, I know. I avant going to submit without hearing from you today though. I revised it all according to your and Griff's edits and was just waiting for a final check in with you today!

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/212731818-1ffb3059-7ef1-40f0-ac01-bf03da9ef671.png)

**Comment by laurenluz** [comment]
we were approved, should have the link tomorrow

**Comment by danelsuga** [comment]
[Our grant](https://grant-explorer.gitcoin.co/#/round/1/0xd95a1969c41112cee9a2c931e849bcef36a16f4c/0xb746c0f648f9b930ea4568cf8741067a7fc7eb3928ac13cced8076212cf3cf37-0xd95a1969c41112cee9a2c931e849bcef36a16f4c)
