### ISSUE TITLE
FrontierDAO Grant Application with SDG/Giveth Foundation

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-planning#1147]
Per request from Paige at FrontierDAO they are applying for a grant to fund FrontierRegistry and need non-profit status / fiscal sponsorship to do so.

Through SDG Impact, the Giveth Foundation sub-DAF can provide this for our projects.

I've provided Paige with the following documentation of necessary details for the application:

[SDG IRS Letter](https://drive.google.com/file/d/1lXccdnzpELPA56CwpPB5roaBDXJCv4mZ/view?usp=share_link)
[Giveth Foundation Welcome Letter](https://drive.google.com/file/d/1Has-elQcUgumBzk2sJN4IDbAB8_zynCs/view?usp=share_link)
[SDG Impact / Giveth Foundation SubFund Status Letter](https://drive.google.com/file/d/14ersgOrBh0pR84CMuqyuz_3petrTxVpP/view?usp=share_link)

**Comment by oyealmond** [comment]
hey @Cotabe ! 
Do you know if we can close this?
