### ISSUE TITLE
Gitcoin Alpha Round Comms Plan

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1148]
We are confirmed in the alpha round happening Jan 17 - 31

**Comment by Cotabe** [comment]
Here are a few ideas:

1. Get donations early:
1.a Donation Party.
1.b Donor hearder (like for Clara & Brichis for Fantom).

2. Teamwork with other grantees. (Xpollination, especially with Giveth Galaxy, Giveth makers, ReFi & Impact projects)
2.a Organize twitter spaces with other projects.
2.b Create a Discord DM/TG group to share opportunities with other grantees. 
2.c Create a public goods project list and work with those projects promoting each other & the list.

3. Twitter work.
3.1 Make copy ideas to help anyone that would like to share about Giveth.
3.2 Have the grant link on Giveth's twitter profile.
3.3 For the giveth team, share giveth's link when a person ask... which projects to donate to.
3.4 Keep a twitter space schedule (maybe have different Giveth voices in them)

Maybe give non-financial rewards (POAP, discord event post grants with DJ Almond?)

**Comment by ahmadabugosh** [comment]
I would add

4. Outreach / Email
 4.1 Email existing old Gitcoin Donors to Giveth (from Gitcoin admin panel)
 4.2 Create an email campaign on Autopilot (our Donor list)
 4.3 Reach out to top 50 Donors on the Gitcoin leader board (maybe through Twitter)? @SnakeGH can support on this : https://gitcoin.co/leaderboard/earners?cadence=yearly&keyword=&product=all

**Comment by SnakeGH** [comment]
great ideas, @ahmadabugosh let me know when to kick off the top 50 donor gitcoin outreach. Probably once we are live im assuming, as they will forget prior

**Comment by laurenluz** [comment]
Our application was approved and we should get the link tomorrow the round starts!
