### ISSUE TITLE
Video for hompage of giveth

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1151]
Explain: What is Giveth? What is our mission? Where are we going?

**Comment by c0ric0ri** [comment]
Having multiple core contributors interviewed, clips of people hanging out, maybe clips of projects, overlay of music, etc.

**Comment by c0ric0ri** [comment]
Call notes from meetings with Chuy & @laurenluz:

https://docs.google.com/document/d/11rYB6qRRtxDb7ZNKuTK5Pi3zRrVmMb1V0KcRwj4gIvI/edit

I will be meeting with Chuy tomorrow to plan out steps to capture footage & interviews at ETH Denver.
