### ISSUE TITLE
Emails for Gitcoin Grant Alpha Round

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1158]
We should set up maybe 3 email drafts for outreach.

We can email existing old Gitcoin Donors to Giveth (from Gitcoin admin panel), and create an email campaign on Autopilot (our Donor list).

- one to go out on the 17th announcing the round has started (reference our upcoming Twitter space)
- one reminder email halfway through round
- one reminder that round is closing

**Comment by c0ric0ri** [comment]
@ahmadabugosh @Cotabe can you support on this?

**Comment by Cotabe** [comment]
@c0ric0ri @laurenluz @ahmadabugosh @WhyldWanderer 

Here is a draft for the first email. Soon I will start working on the 2nd & 3rd.

https://docs.google.com/document/d/1E9QDzLvYAXZuWmLDuxbIBfAsyme3RDhLqBHu7TH5e-A/edit?usp=sharing

**Comment by c0ric0ri** [comment]
Thanks @Cotabe ! Made some edits and suggestions.

**Comment by c0ric0ri** [comment]
hey @ahmadabugosh why is this issue closed? We only have one draft from what I see

@Cotabe are you working on the last two drafts today? We need to send them out this week. 

Second one by tomorrow, third just before end of the round.

**Comment by Cotabe** [comment]
I updated the doc for the second email and I will start working on the third now

**Comment by c0ric0ri** [comment]
Awesome job @Cotabe ! I reviewed the first one.

@ahmadabugosh can we have it go out in a couple of hours, or is it better to wait until tomorrow morning?

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri I'm going to sleep now, but can schedule it 9AM EST tomorrow once the edits are ready

**Comment by ahmadabugosh** [comment]
Second email sent

**Comment by laurenluz** [comment]
Just read this email in my inbox. It's full of inaccurate or misleading information!

From the dune analytics dashboard, it looks like we are totally not one of the most donated to projects in OSS... we're not even in the top 30!!

Also there is $333k available for matching in OSS, and while I think it's not totally wrong to say "direct some of the $1M matching to us", I think "if things keep going in this direct we'll receive a big part of the $1M in matching" is just very misleading.

PLEASE. I can't look at every single thing before it goes out. DYR, double check. make sure we're not lying or misdirecting our users & supporters in our comms. @Cotabe @c0ric0ri

**Comment by ahmadabugosh** [comment]
hey @laurenluz, 

I get your frustration and not to defend anything, but the ranking did go down a lot today (we were number 8 when we first composed the email and I noticed we're now at 16 in donation amount so I removed the language about us being in the top ten), and we wanted to include some stats to make the email more interesting. Also, we had a discussion in a previous comms meeting about mentioning the 1M number as opposed to 333K, and we voted that 1M sounds better and is technically true for all 3 rounds. 

I do think we can do better though and make the emails exciting while also being more straightforward. I think it's a balance between being a little salesy (which we do need to a certain extent) and not being misleading.

**Comment by laurenluz** [comment]
Donation *amount* maybe, but this does not make us by any means one of the most donated to projects. "Most donated to" sounds like you're talking about number of unique donors - which is critical for QF.

And yes, $1M total matching is available for all projects. but to say that "we will receive a *big chunk* of $1M" is just totally wrong!!

We need everyone in comms thinking more critically - and checking facts.

**Comment by ahmadabugosh** [comment]
hey @c0ric0ri @Cotabe @danelsuga @laurenluz , 

I want to send the last Gitcoin email today or early morning tomorrow. Can I get a couple of eyes on the last email for a quick proof read (I simplified it and edited a few things in it): https://docs.google.com/document/d/1E9QDzLvYAXZuWmLDuxbIBfAsyme3RDhLqBHu7TH5e-A/edit#

**Comment by danelsuga** [comment]
Gave it a look! Couple tiny things. Thanks @ahmadabugosh

**Comment by laurenluz** [comment]
looks good
