### ISSUE TITLE
Join Gitcoin Grant Twitter spaces & rep Giveth!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1159]
We (the comms team & extended!) should join as many twitter spaces about gitcoin grants as possible & try to get up as "speakers" to talk about our grant & raise awareness.

We should:
- Search Twitter for all gitcoin grants spaces
- Set reminders for them
- Get our team to take ownership to join as many as possible (we just need 1 representative to be in a space)
- Join as Giveth (perhaps preferable) or if the rep doesn't have access, as themself
- Share our grant!!

@oyealmond @c0ric0ri - I think, since you two are the most familiar w/ twitter, it would be nice if you could make a list of spaces to join and put the links in here. Either of you want to take this on?

@danelsuga @SnakeGH @Cotabe - you would be great at this as well!

We just need one owner, and if the person could make the time today/tomorrow, would be ideal.

**Comment by laurenluz** [comment]
Spaces:

https://twitter.com/web3beach/status/1615080877653983233

**Comment by c0ric0ri** [comment]
We can start collaboratively working out of this to create a list:

https://docs.google.com/spreadsheets/d/1zGSB6BDZlwcBcKEMDNg4htq4V-aP5wt-T7UaMG0ioZ0/edit#gid=0

**Comment by SnakeGH** [comment]
> We can start collaboratively working out of this to create a list:
> 
> https://docs.google.com/spreadsheets/d/1zGSB6BDZlwcBcKEMDNg4htq4V-aP5wt-T7UaMG0ioZ0/edit#gid=0

Thanks @c0ric0ri for putting this together, Ill jump on the one during the Comms call today.

**Comment by danelsuga** [comment]
In light of promoting our Gitcoin grant, it would also be great to get out the Looking Forward post ASAP, as in before the end of this week (**at the latest!**).

Could I get some reviewers please?

[Issue 1125](https://github.com/Giveth/giveth-planning/issues/1125
) 
[Doc](https://docs.google.com/document/d/1KzflJecaLhaqnGq1B2gm4RQMXC8IuUBh4D_G4XIq0Dk/edit?usp=sharing)

**Comment by danelsuga** [comment]
Thanks, @SnakeGH 
Have you got the one immediately preceding too? I think they're in cahoots. The one that starts during Comms is "kick-off" and a half an hour later is "grantees".

> > We can start collaboratively working out of this to create a list:
> > https://docs.google.com/spreadsheets/d/1zGSB6BDZlwcBcKEMDNg4htq4V-aP5wt-T7UaMG0ioZ0/edit#gid=0
> 
> Thanks @c0ric0ri for putting this together, Ill jump on the one during the Comms call today.

**Comment by danelsuga** [comment]
[Our grant](https://grant-explorer.gitcoin.co/#/round/1/0xd95a1969c41112cee9a2c931e849bcef36a16f4c/0xb746c0f648f9b930ea4568cf8741067a7fc7eb3928ac13cced8076212cf3cf37-0xd95a1969c41112cee9a2c931e849bcef36a16f4c)

**Comment by SnakeGH** [comment]
> [Our grant](https://grant-explorer.gitcoin.co/#/round/1/0xd95a1969c41112cee9a2c931e849bcef36a16f4c/0xb746c0f648f9b930ea4568cf8741067a7fc7eb3928ac13cced8076212cf3cf37-0xd95a1969c41112cee9a2c931e849bcef36a16f4c)

We are live! Awesome!

**Comment by SnakeGH** [comment]
> Thanks, @SnakeGH Have you got the one immediately preceding too? I think they're in cahoots. The one that starts during Comms is "kick-off" and a half an hour later is "grantees".
> 
> > > We can start collaboratively working out of this to create a list:
> > > https://docs.google.com/spreadsheets/d/1zGSB6BDZlwcBcKEMDNg4htq4V-aP5wt-T7UaMG0ioZ0/edit#gid=0
> > 
> > 
> > Thanks @c0ric0ri for putting this together, Ill jump on the one during the Comms call today.

No, I was only going off of the google doc and there is nothing on there preceding it, do you have the link for "kick-off" that you could share with me and/or add to the google shared excel @danelsuga ???

**Comment by danelsuga** [comment]
It's on the doc! The one at the beginning and the one (currently) at the end.

**Comment by danelsuga** [comment]
Gitcoin kick-off: https://twitter.com/i/spaces/1jMJgLrjdrexL

**Comment by SnakeGH** [comment]
> It's on the doc! The one at the beginning and the one (currently) at the end.

My apologies, my brain thought it was next week due to being out of order, but it is clear as day. I will make sure to be on both twitter spaces. See you there.

**Comment by danelsuga** [comment]
Groovy! Yeah maybe we should put them in order. :P
