### ISSUE TITLE
Write & send "Thank you" to Past GitCoin Grant Donors to Encourage More Donations

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#116]

**Comment by ForestSoleil** [comment]
Lauren & Ashley to sync with Magenta on this. Make sure the folks on the GitCoin Grant list are receiving a message that applies to what you are already sending them + thanking for past donations and also requesting additional donations if they feel called.

**Comment by WhyldWanderer** [comment]
@ForestSoleil @magentaceiba @willyogo  Do you know where I can find the contact info for past gitcoin donors?

**Comment by magentaceiba** [comment]
@WhyldWanderer it looks like the last round was exported here (via issue #59), though it only shows their github handle: https://docs.google.com/spreadsheets/d/1vpoKMSYVIuV2Db84TVJC1AUPj9GReWg8qTkBoMfFyXA/edit#gid=964790023

I see these 2 options to message people in the gitcoin interface:

At the bottom of the grant description, you can "Email grant funders" - the little megaphone there has a checkbox.
![image](https://user-images.githubusercontent.com/38021350/111330871-b5270c80-8646-11eb-98a8-cdd8038ae6af.png)

And this one, an option to post on a person's gitcoin profile, on their "wall":
![image](https://user-images.githubusercontent.com/38021350/111330982-d12aae00-8646-11eb-8113-aad32b8522fb.png)

**Comment by laurenluz** [comment]
@WhyldWanderer - is this done? can we close?

**Comment by WhyldWanderer** [comment]
Yes! It needed to be done by the grant owner.
@willyogo sent one for Giveth.io
@Danibelle sent one for trace
<3
