### ISSUE TITLE
Gitcoin grants tweets & threads

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1162]
We should shill our grant, and try to focus also on public goods in general... get others to RT by mentionig their grants.

Notes from Daryl of ReFi DAO:
- a "promote others first" and "more public goods" tone and ethic resonates strongly with these existing communities, gets RT'd, and is often enough to get them to add $1 for your project to their list
(John wrote a few beautiful threads last time talking up other projects, which got a LOT of attention)
- Introducing your community to other great projects is literally positive sum. 
- There are much larger adjacent communities than within the climate x crypto space that we should be connecting with, and I think that's going to be particularly valuable when we have the combo of CS x ReFi DAO as the headline. 

Audience is previous donors, not newbies. Get more of them to donate $1 to our project.

**Comment by laurenluz** [comment]
Can use the grants from #1161 

Starting drafts here: https://docs.google.com/document/d/1Gf_Rl2NheD57k2UrBouI1FqjPG2nNkyxykq-n192LlQ/edit

**Comment by c0ric0ri** [comment]
Here is a draft of a longer thread for review @laurenluz 

https://docs.google.com/document/d/1YNZYp07Y-OGrKTtv1Xgfu7J00CBLIgtbdtCBD__6XoI/edit

**Comment by laurenluz** [comment]
epic

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1618615534752305154

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1620446566392774656?s=20&t=agjs9YxCZarDA1w4vt-ASg

https://twitter.com/Givethio/status/1620064823844151299?s=20&t=agjs9YxCZarDA1w4vt-ASg
