### ISSUE TITLE
Cryptocurrency Jobs Partnership 

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#1166]
One of our DeFi Holiday Newsletter Outreach do'ers wants to form more of a "partnership," so I want to get more thoughts on this.

Insight into their org and how it could benefit Giveth:
1.) Founder, Daniel is an OG in web3, has over 20K followers through his newsletter and he is full on web3 like Giveth, so very aligned. 
2.) They usually charge $299 per job posting but would look at waiving for a certain number of Giveth openings. 

Here are the current asks:
1.) add their logo and description to our partners website page 
2.) make an announcement about partnership in next newsletter  

Thoughts? Approve to move forward? @ahmadabugosh @c0ric0ri

**Comment by SnakeGH** [comment]
@laurenluz would also love to get your thoughts, as it is more a comms thing :)

**Comment by ahmadabugosh** [comment]
Hey @SnakeGH, for sure I think let's do it. Would they be able to post our jobs first (mainly [this](https://giveth.recruitee.com/o/general-magic-director-of-technology-services) and [this one](https://giveth.recruitee.com/o/cofounder-nontechnical-praise))? That way in the newsletter I can say we're partners and here are a couple of jobs from the Giveth Galaxy? 

As for the partner page, I would say yes as well (once we figure out the [partnership groups](https://github.com/Giveth/giveth-planning/issues/1167) thing)

**Comment by SnakeGH** [comment]
Let me find out now with them. Great ideas @ahmadabugosh

**Comment by SnakeGH** [comment]
Hey @ahmadabugosh and @laurenluz looks like the proposal has changed some, so please review (as well as anyone else) and let me know if we should proceed....

Proposal terms: 

- Inclusion on each other's partners pages
- Help with amplifying new features, initiatives in our newsletters, social media
- Job discounts for the Giveth ecosystem.

For reference, standard pricing:

- 1 job listing: $299
- Pre-buy a 3 job pack for $807 and save 10%
- Pre-buy a 5 job pack for $1270 and save 15%
- Pre-buy a 10 job pack for $2392 and save 20%

The auto-bump feature is $129/listing, a listing is automatically bumped up to the top of the front page after 14 days.

For Giveth:

- 1 job listing for $200
- Pre-buy a 3 job pack for $540 and save 10%
- Pre-buy a 5 job pack for $850 and save 15%
- Pre-buy a 10 job pack for $1600 and save 20%

- Auto-bump feature: $50


do we move forward with this?

**Comment by laurenluz** [comment]
I think @ahmadabugosh is more qualified than me to respond here. my thought though... well, we're not really even looking to hire more people now... more like scaling down. so I don't think it really makes sense to pay for the listings. 

but if we just create the social connection 1st and then can decide later if we want to job packs... then it's pretty low effort to add them into our comms a little.

**Comment by ahmadabugosh** [comment]
Thanks @laurenluz , yes @SnakeGH for now we don't have any jobs we want to push, but it's good to know we have this discount for the future. If we can make it just a content partnership for now that would be good.

 Let's proceed, let me know what the next steps are.

**Comment by ahmadabugosh** [comment]
hey @SnakeGH, I can include them in our new monthly newsletter (going out in about a week and a half). Do they have a blurb they'd like us to include?

**Comment by SnakeGH** [comment]
Thanks @ahmadabugosh here is what Daniel would love to see, of course, tailor it as you need for the newsletter :) 



Cryptocurrency Jobs [1] is the leading job board for blockchain and crypto jobs. Since 2017, we've been on a mission to enable talented humans and companies to work together and build our decentralized future.

We help hundreds of companies grow their teams. They've made the switch from legacy recruiting platforms. Join them.

Cryptocurrency Jobs is more than a platform. We're a partner and friend, we're here for the community. [2] We're independent, bootstrapped, and the platform is run just by Daniel [3].

Hear how we help industry-leading teams like solve their hiring challenges [4].

Building this future takes people, from developers and researchers to designers and writers, working together.

That's why the Cryptocurrency Jobs tagline is: the decentralized future is people.

Find us on Twitter. [5]

[1]: [https://cryptocurrencyjobs.co](https://t.co/gqaGQj4uRW)
[2]: https://cryptocurrencyjobs.co/about/#community
[3]: https://twitter.com/3reps
[4]: [https://cryptocurrencyjobs.co/testimonials/](https://t.co/slKRtRRzWs)
[5]: https://twitter.com/jobsincrypto

**Comment by SnakeGH** [comment]
for some reason only half the links work, so here they are all: 

[1]: [https://cryptocurrencyjobs.co](https://t.co/gqaGQj4uRW)
[2]: https://cryptocurrencyjobs.co/about/#community
[3]: https://twitter.com/3reps
[4]: [https://cryptocurrencyjobs.co/testimonials/](https://t.co/slKRtRRzWs)
[5]: https://twitter.com/jobsincrypto

**Comment by SnakeGH** [comment]
Here is their logo and tag line sentence for adding them to the "Giveth Friends" (Use to be Partnership) page...

Name: Cryptocurrency Jobs
Tagline: The decentralized future is people.
Website: https://cryptocurrencyjobs.co/
Logo: https://cryptocurrencyjobs.co/images/cryptocurrency-jobs-logo.svg

**Comment by ahmadabugosh** [comment]
@MoeNick Can you help to add them as a partner on this page: https://giveth.io/partnerships

**Comment by MoeNick** [comment]
Sure, can we make it more clear for me? 
1-Add Cryptocurrency jobs? at the end of the list? 
2- Should we change the Partnership term to Giveth Friends? I know @danelsuga has suggested other words for partnership on different pages, please let me know if I'm wrong.

**Comment by SnakeGH** [comment]
> Sure, can we make it more clear for me? 1-Add Cryptocurrency jobs? at the end of the list? 2- Should we change the Partnership term to Giveth Friends? I know @danelsuga has suggested other words for partnership on different pages, please let me know if I'm wrong.

Thanks @MoeNick - Yes, add them to our Partners page but in alphabetical order like the rest of the partners with the logo and org tag line provided by them in my previous message

And my opinion
 is absolutely change the title of that page to "Giveth Friends" instead of Partnerships, and I know @ahmadabugosh would agree with me on that too

**Comment by danelsuga** [comment]
@SnakeGH Not to add confusion but alas, I thought we were saying GIVfriends not Giveth Friends.

**Comment by danelsuga** [comment]
@SnakeGH Not to add confusion but alas, I thought we were saying GIVfriends not Giveth Friends.
@ahmadabugosh @laurenluz @c0ric0ri @WhyldWanderer

**Comment by SnakeGH** [comment]
> @SnakeGH Not to add confusion but alas, I thought we were saying GIVfriends not Giveth Friends. @ahmadabugosh @laurenluz @c0ric0ri @WhyldWanderer

you are 100% correct, apologies for trying to add confusion but I did mean to GIVfriends :)

**Comment by danelsuga** [comment]
@MoeNick 👆

**Comment by laurenluz** [comment]
@SnakeGH - his draft is fine w/ me.

**Comment by SnakeGH** [comment]
Thanks for confirming @laurenluz as I know @ahmadabugosh is going to get the newsletter announcement out in this month's edition. 

For the twitter announcement, Ill send you over a couple bullet points to draft up the tweet. :)

**Comment by SnakeGH** [comment]
Cryptocurrency jobs has been added to Giveth.io partnership page - check

**Comment by MoeNick** [comment]
> Thanks @SnakeGH I also added them to our Newsletter (which should go out in a day or two).
> 
> Did they add us to their partnership page as well?

Yes sir :) 
https://giveth.io/partnerships

**Comment by SnakeGH** [comment]
> Thanks @SnakeGH I also added them to our Newsletter (which should go out in a day or two).
> 
> Did they add us to their partnership page as well?

@ahmadabugosh good news, yup, it is already here:  https://cryptocurrencyjobs.co/partners/

And his newsletter with the announcement will go out on Thursday of this week. 

Lastly, he is just going to retweet whatever @laurenluz puts out for an announcement too 

Close to closing this item

**Comment by SnakeGH** [comment]
official newsletter has been released by both orgs...

https://cryptocurrencyjobs.substack.com/p/weekly-jobs-update-2-mar-2023?utm_source=substack&utm_medium=email 

...and both orgs have partnership listed on their page. 

Closing this item as complete now
