### ISSUE TITLE
Partnership Groups 

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#1167]
Should Giveth organize their UI partnership page to have different levels or categories of partners? For example, "our marketing friends" etc. 

Thoughts? 

@WhyldWanderer @ahmadabugosh @laurenluz @GriffGreen @MoeNick @c0ric0ri

**Comment by ahmadabugosh** [comment]
@SnakeGH how about we rebrand that page to be GIVfriends (since we're already using that in the newlsetter)? 

Then change the text where it says "We have many partnerships in the Ethereum Community." to something like: "We can’t Build the Future of Giving alone! Check out our GIVfriends: partners and fellow organizations that are helping us further our mission."

Maybe categories would make more sense than groups, since that would be easier to sort them, so it could be for example: 

- Giving partners (Gitcoin, Panvala etc.)
- Regen Farms (Shapeshift, The Standard, Cult)
- DeFI (for exchanges DEX's etc that list us)
- DAO Tooling (1Hive, Aragon)

and we can keep adding to them for any other category we can think of. 
Wydt @WhyldWanderer ?

**Comment by WhyldWanderer** [comment]
I like GIVfriends! and I love the text change...

Im curious what the goal is by having levels, groups, or categories? Is it valuable?
IF a partner is both a marketing partner and a regen farm partner, do they go in both categories?

I would like to emphasize that I dont think we should have levels (gold silver etc) or show the page in a way that makes any partner seem better than others.

**Comment by ahmadabugosh** [comment]
@WhyldWanderer Yeah true, I guess we skip the categories? 

What it would do would let the end user (or new potential partners) sort between them better and see what other partners are in that category (see all the DeFi partners for example), but maybe that's not a strong enough reason for that.

**Comment by laurenluz** [comment]
> how about we rebrand that page to be GIVfriends (since we're already using that in the newlsetter)?

> Then change the text where it says "We have many partnerships in the Ethereum Community." to something like: "We can’t Build the Future of Giving alone! Check out our GIVfriends: partners and fellow organizations that are helping us further our mission."

+1 on all this. I'm neutral on the cateogies.

**Comment by danelsuga** [comment]
I can drop a request to change the text from "Partnerships" to "GIVfriends". I'm already working on an issue for minor text edits on the DApp ([2613](https://github.com/Giveth/giveth-dapp/issues/2613)).

Questions for you, then, are: 1) change the name of the link as well? Yes imo.
2) change the title of the page? Yes imo.
3) change the subtext ("we have many partnerships...")? No imo.

**Comment by ahmadabugosh** [comment]
Thanks @danelsuga , yes please! 

For 3) the subtext, if you don't like what I wrote, could you come up with something else then? Since I think the current one "We have many partnerships in the Ethereum Community."  I think needs rewriting

**Comment by danelsuga** [comment]
Oh, sorry. I just meant don't change the word from "partnerships" to "GIVfriends" in the subtext.
![Screenshot 2023-02-16 9 59 53 AM](https://user-images.githubusercontent.com/81351744/219317422-41fc08a5-9e3d-4ebc-abd3-95b44571fd11.png)

But now I see that you want to update that text too. Sure!

"We can’t Build the Future of Giving alone! Check out our GIVfriends: partners and fellow organizations that are helping us further our mission."

I might not put in that first line though? "We can't Build the Future of Giving alone!" I don't think that's the point here. We're just presenting our community of DAOs. What do you think?

**Comment by ahmadabugosh** [comment]
@danelsuga Yeah up to you, I think it's just a question of voice. The first sentence is a bit playful, but if you think it sounds better without it, we can leave it out.

**Comment by danelsuga** [comment]
"GIVfriends" has been implemented. :D

**Comment by oyealmond** [comment]
hey @danelsuga ! Saw the other issue for this topic https://github.com/Giveth/giveth-dapps-v2/issues/2185 
Should we just close this one?

**Comment by danelsuga** [comment]
Sure! Looks like I closed and reopened. Don't know why.
