### ISSUE TITLE
GM! Episode 2 Tweets :) 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1168]
Hey team! @c0ric0ri @laurenluz 

[Here you'll find the draft for GM! Ep2 tweets :) ](https://docs.google.com/document/d/1hHIwyXk0E5qi-SqD2p7qxa0VvrT1J6ZCf_sEtpcS1qE/edit)
Could you help me review & schedule please? 

Thank you!

**Comment by laurenluz** [comment]
These were great @oyealmond - I made some edits (pasted in the doc as well) and scheduled both :)

https://twitter.com/Givethio/status/1616086728795885570

**Comment by oyealmond** [comment]
Ty so much @laurenluz ! 

https://twitter.com/Givethio/status/1616086728795885570

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1616451246789124098
