### ISSUE TITLE
Giveth homepage copy & user survey

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1169]
This issue is for creating better copy on the giveth homepage.

Working notes doc:
https://docs.google.com/document/d/1VSKb3DuhSqG3wnHz9Lq5rxGGAfd4XGnyYKsBz0IIZxc/edit

Homepage figma:
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17711%3A350162&t=oRKU7sn0p8tm5ox6-4

Next steps include:
-  [ ] draft better preliminary copy
- [ ] build survery for users to find out what's important
- [ ] revise copy as needed, based on results of the survey

This is a collab w/ Cori, Stee & me (don't have his github)

cc @mosaeedi

**Comment by laurenluz** [comment]
related to #1152 & #1151

**Comment by c0ric0ri** [comment]
I've compiled a new draft in this document for review, based on all the notes and feedback so far:

https://docs.google.com/document/d/181yiJK7GNxXhDhNuUisSjUg_maD6pAoT4UjHi1RKqzo/edit

@laurenluz @mosaeedi & Stee

**Comment by c0ric0ri** [comment]
@ahmadabugosh regarding the topic of SEO, is there something we should be taking into consideration here?

**Comment by laurenluz** [comment]
@c0ric0ri - I love where this is going.

I made some comments for improvements and as well some suggestions for rewrites. Can you have a look and leave your feedback?

Regarding SEO - we need to make sure we are putting things like: crypto donations, blockchain donations, web3. We want to come up when people search "crypto donations" - you know?

I know you avoided mentioning web3 because you wanted to not scare people off, but we need a balance here. I added in some suggestions, I think it can be even further improved, so I would love at least 2 more back & forth on this with you.

**Comment by laurenluz** [comment]
cc @mateodaza @MoeNick @mosaeedi  - just FYI - we are working on the copy here for the homepage in this issue

**Comment by laurenluz** [comment]
All the copy is updated in the figma [here](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19416%3A246933&t=gtzczDjyvSvbRoNv-4)

There is just one more part that needs addressing.... @c0ric0ri I left a comment in our [google doc](https://docs.google.com/document/d/181yiJK7GNxXhDhNuUisSjUg_maD6pAoT4UjHi1RKqzo/edit) on it based on @GriffGreen 's comments

**Comment by c0ric0ri** [comment]
Closing this issue as we finalized the copy in February and published the new homepage by Feb 26.
