### ISSUE TITLE
Update Giveth Brand Guide with Giveth.io Logo and New Color Palette

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#117]
- @magentaceiba to make final edits to logo centering.
- @ForestSoleil Friday marketing call discussion: Giveth TRACE branding vs Giveth new app branding to propose in Governance call. 
- @Danibelle DAO proposal about Giveth TRACE branding vs Giveth new app branding.
- Create 2021 Giveth Brand Guide for Giveth TRACE and Giveth.io

**Comment by ForestSoleil** [comment]
3/5 Marketing update:
- @magentaceiba made some updates to the Giveth logo --> Made it "giveth.io" text. Please share files here. 
- @markoprljic to review and approve. 
- Brand Guide is out of date (https://drive.google.com/drive/folders/1T0vWj9S95tRdXAn4UObkinkW4DJn7Yhk) and needs to be marked for Giveth TRACE branding.
- Then @markoprljic to approve new color palette for new Giveth app. Then edit Brand Guide to clearly outline what branding is for Giveth TRACE and what branding is for new Giveth app.

**Comment by magentaceiba** [comment]
For review. @markoprljic All feedback welcome.

Here's a PDF of color options - I wasn't sure which pink you wanted, if you want both a pink and a blue as an option. You will need the white sometimes. https://drive.google.com/file/d/1lHgkSWnia9qaO4W6yi8iI2ssbfBIOGJQ/view?usp=sharing

I found a folder of fonts from Giveth v1 branding and used those to make a Giveth Trace logo. Any of these color combos seem right? Giveth Trace will need a white version as well in the final. I don't have the design chops yet to make the Trace in what looks like a custom font that was made for the Giveth wordmark.

Here is the color palette I made from the colors in the Figma design file for V2: https://drive.google.com/file/d/19DLfq3A_dr4ONf9Cdt26rU1ThJXGBz29/view?usp=sharing

**Comment by ForestSoleil** [comment]
@markoprljic  is this ready to close?

**Comment by markoprljic** [comment]
No, I'm working on this.

**Comment by laurenluz** [comment]
@markoprljic can I close this now?? 

https://www.figma.com/proto/bV3f7aLHK2pIs7tlzLGVgH/Giveth.io-Branding?page-id=387%3A0&node-id=387%3A207&viewport=271%2C261%2C0.03756708279252052&scaling=scale-down-width

**Comment by markoprljic** [comment]
Yes.
