### ISSUE TITLE
Newsletter January 2023

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1171]

**Comment by ahmadabugosh** [comment]
Topics to include this month:

- Gitcoin Grant
- GM Podcast (first 2 episodes)
- 2023 look ahead article
- Fiat integration (testing, we could invite them to give it a try)
- Teaser for ETHDenver
- Panvala Stamps
- Cryptocurrency Jobs (if you think it's ready this month @SnakeGH, otherwise we can highlight them in Feb )

**Comment by SnakeGH** [comment]
@ahmadabugosh waiting for some more info from them, so not sure they will make the deadline for this month's newsletter, but when I get that back, I'll be in touch with you immediately.

**Comment by laurenluz** [comment]
IT might be cool to feature this project, as it is # 3 ranked by GIVpower: https://giveth.io/project/evmcrispr-0

You can mention that you'll get up to x% (close to 80%... you can ask @divine-comedian for the exact) GIVbacks

**Comment by c0ric0ri** [comment]
I'd suggest making the Gitcoin Grant blurb stand on it's own at the top, including updates on numbers and a few details on of grant.

If the regen economies blog post is done and out this week, let's make sure to include it

Meet the Makers - Feb 8th - topic is Inclusion

**Comment by ahmadabugosh** [comment]
Hey @danelsuga @laurenluz @c0ric0ri , 

The newsletter is ready for feedback (if you review it by today, I'll send it asap)! [https://docs.google.com/document/d/1BrEDSXiB69xXeSKb--hYF2J-AJ6E3XrfDk0zfMYa0-c/edit#](https://docs.google.com/document/d/1BrEDSXiB69xXeSKb--hYF2J-AJ6E3XrfDk0zfMYa0-c/edit#)

**Comment by danelsuga** [comment]
done, @ahmadabugosh ! great job as always!

**Comment by c0ric0ri** [comment]
Reviewed @ahmadabugosh ! Added a couple points, namely CTA for subscribers to the podcast. Great job!

**Comment by laurenluz** [comment]
looks good @ahmadabugosh

**Comment by ahmadabugosh** [comment]
hey @laurenluz, 

I just sent it out as a newsletter, but didn't share it on Twitter yet (I'm not sure what our queue is like): 


Can you share something like: 

" 
In the first issue of GIVnews for the year:
 
💙 @Gitcoin Alpha round in full swing 
🔮 A look ahead at our roadmap for 2023
🎙️First 3 episodes of the GM! podcast
 🫶 Joining as first  Network Chapter @PanvalaHQ 
and more! https://paragraph.xyz/@giveth/givnews13"

**Comment by laurenluz** [comment]
scheduled for tomorrow - thanks Ahmad
