### ISSUE TITLE
Tweet thread verified projects Round 27 & 28

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1172]

**Comment by NikolaCreatrix** [comment]
Working on the thread here: https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

I am aiming to have the draft ready tmrw.

**Comment by NikolaCreatrix** [comment]
Ready for review. https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by laurenluz** [comment]
Awesome Nikola! for some reason my access just changed so I can't make edits in the doc... but I edited a bit in tweet hunter. Just pasting here for your reference, I didn't change much:

⏰ Ready to get rewarded for your good deeds?

Your donation means:
🔑 100% of funds go directly to for-good projects
💝 You get rewarded with $GIV & can participate in GIVeconomy

This is not a dream, this is reality.

Check out our newly verified projects 🧵👇


🌱 @SintrópicaBarichara is contributing to territorial, environmental & social regeneration through Syntropic Agriculture, & is strengthening social relations in their community.

Donate to help fund ongoing educational activities & expanding knowledge.
https://giveth.io/project/escuela-de-agricultura-sintropica-en-barichara-colombia


🖼️ @Mafiacreativaro is a decentralized, mission-driven organization passionate about authentic NFT/art curation, onboarding & guiding new artists, & launching creative experiments in the cities of Romania.

Donate to support these creative endeavours!
https://giveth.io/project/mafia-creativa


🔎 @relay_eth is building crossroads for encrypted messaging, decentralized identity & Lens social graph.

100% of your donation will go to hiring developers & 100% of their code will be open source.
https://giveth.io/project/relay


👩‍🌾 @projectregro aims to connect land owners, farmers & growers through Regenerative & Conservation Agriculture, Permaculture & non-invasive practices.

Donate to help regro farmers protect & augment our forests.
https://giveth.io/project/help-regro-farmers-protect-and-augment-our-forests


If these projects speak to you, help them spread the word by RTing the first tweet 👇
[tweet]

**Comment by NikolaCreatrix** [comment]
Awesome, thanks @laurenluz and sorry about the doc access, it was an issue on my site. Should work again... I will apply the changes for reference.

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1621162311456006145
