### ISSUE TITLE
WFP potential response

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1176]
@SnakeGH this is the message that I'm planning to send to the WFP, let me know what you think. 

FYI... Suzana would be able to come back to us with an inner perspective next week

Hey Diana,

Thanks for letting us know where you stand at the moment.

We are sad to hear that you currently want to put on hold our partnership because we are motivated to support the efforts to reverse the 345 million people marching toward starvation. The tools that we have built and that we keep building are planned to help communities steward public goods and maximize their impact.

Since our talk, we began to discuss the specs both for a new traceability feature based on our learnings and making a whitelabel platform to support the WFP needs.

We remain very motivated to support you on the Food For Crisis Initiative. Hence, if there is anything we can do on our side to make this partnership move forward, please let us know. We welcome any feedback that can help us improve.

Best wishes,
Cotabe

**Comment by SnakeGH** [comment]
Really good message @Cotabe but maybe back it down a little bit....these are my edits and thoughts:

"Hi Diana, 

Thanks for the response and letting us know how WFP would like to currently proceed. Even though I am very saddened to hear this, I think it is still a great opportunity to better understand each other and why it’s a no right now.

As you are much more aware than us, there are over 345 million people either in or coming into starvation, and we at Giveth are extremely driven to stop and reverse these numbers in any way we can, which we thought was by partnering with the greatest, and largest food organization in the world. 

If you are able to find a couple extra minutes to provide us with some more details about why we are not currently aligned / how we could assist you by becoming more aligned, before an official partnership would be established, we would be beyond grateful and appreciative. 

 Thank you in advance! 

Best wishes, 
All of us here at the Giveth Galaxy"

**Comment by Cotabe** [comment]
Sent
