### ISSUE TITLE
SEO - Fix 404 Pages & Broken Links

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1178]

**Comment by geleeroyale** [comment]
hmmm - I see what you mean. Maybe your example was the only one that makes sense though. All the others on the main site seem too outdated - or are missing a counterpart that we could point to? Wdyt?

**Comment by geleeroyale** [comment]
One additional thing. With DNS we can only forward subdomains to full URLs. We can't take in full URLs and point them to other full URLs.

BUT - we can do this with Vercel. I would argue however that it should then be handled by the developers.

Here is how: https://vercel.com/guides/does-vercel-support-permanent-redirects

**Comment by ahmadabugosh** [comment]
hey @geleeroyale, 

I looked into this and I think there are 2 things we need to fix to close this issue. 

1) Can you add a wildcard redirect for all links on the subdomain (giv.giveth.io) to the root domain? For example https://giv.giveth.io/giveconomy to http://giveth.io/giveconomy. This is done for some pages, but I think we need a catch-all wildcard redirect. 

2) Can you add a redirect rule for all non lower case urls to lower case? For example, https://giveth.io/GIVeconomy to https://giveth.io/giveconomy (but as a rule for all ones)? 

@MoeNick tagging you here as well, in case this needs any other devs support.

**Comment by geleeroyale** [comment]
@ahmadabugosh @MoeNick - I changed the configuration of the forwarder - it should show the correct behaviour. Pls test 🙏

**Comment by ahmadabugosh** [comment]
thanks @geleeroyale !

1) looks good 

For 2) In that case, what do you think the solution is?

**Comment by ahmadabugosh** [comment]
Hey @MoeNick, Do we have a solution for the second issue (the lower case and upper case urls)?

**Comment by geleeroyale** [comment]
I will give this another go - I think I have found a solution

**Comment by geleeroyale** [comment]
I broke our nginx install!

And then fixed it again!

Its no use - we have to untangle this darn server and all its services and move it to an up to date host - will make a priority issue in `devops`

**Comment by aminlatifi** [comment]
It seems it's possible to fix the second issue on the frontend app. @MohammadPCh @RamRamez @alireza-sharifpour @mateodaza Is it possible to lowercase pathname of URLs hit 404 page and retry?
```js
import { NextRequest, NextResponse } from "next/server";

export function middleware(request: NextRequest) {
   if (request.nextUrl.pathname === request.nextUrl.pathname.toLocaleLowerCase())
       return NextResponse.next();
   return NextResponse.redirect(`${request.nextUrl.origin}${request.nextUrl.pathname.toLocaleLowerCase()}${request.nextUrl.search}`);
}
```
https://stackoverflow.com/questions/64310832/how-to-make-path-for-pages-in-nextjs-case-insensitive

**Comment by MohammadPCh** [comment]
@aminlatifi Yes we have something like this for our landings route.

**Comment by divine-comedian** [comment]
@MohammadPCh @aminlatifi - what were the next steps on this? Is it still relevant?
