### ISSUE TITLE
Update Giveth's profile on DappRadar

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1179]
I noticed that we have a profile here:
https://dappradar.com/ethereum/other/giveth

Should we update it? Who owns it? How do we claim it?
It seems like it would be valuable to update if its not too much work to get access.

**Comment by oyealmond** [comment]
you know smth about this @divine-comedian ?

**Comment by divine-comedian** [comment]
No idea!! @oyealmond
