### ISSUE TITLE
GM! Ep3. Tweets promotion :) 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1180]
Hey team :)  @c0ric0ri @laurenluz 

Griff asked to stream the podcast one hour before meaning 9am CST, [so could you please check out this drafts to promote episode 3](https://docs.google.com/document/d/1_kV9HjtRNnwWwrlCKFuG7FmX6VE-4i5SZOz1QW0NuGI/edit)?

Already added the time change.  

Thank you :)

**Comment by laurenluz** [comment]
ok I scheduled them all

**Comment by oyealmond** [comment]
you're the best!! : D @laurenluz

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1618701087707373581
https://twitter.com/Givethio/status/1618972857018490881
https://twitter.com/Givethio/status/1618701087707373581
