### ISSUE TITLE
User Poll for Homepage Messaging

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1182]
After meeting with Lauren, Stee and Mo about the new homepage copy, it was determined that we should poll our user base to understand their experience with Giveth and what messaging will resonate the most with new visitors.

We can put polls out on Twitter, but also we should also send them out by email after the Gitcoin Grants round has ended.

Since we already have the project survey going out soon, I think that will cover us getting the feedback we need from the project side. In addition, we could create a twitter poll for this audience.

For donors, it would be great to have a poll set up with the following questions (if we don't have this information already from our recent donor survey):

Poll:

- What benefits first attracted you to Giveth?
- What really excites you about Giveth?
- When you explain Giveth to other people, what do you say?
- When you first started using Giveth, is there anything you found really difficult or confusing? Can you explain why?
- Are you using your GIV for GIVpower & the GIVfarm?
- What’s your favorite project that you’ve donated to and why did you choose that one? What are you usually looking for when donating to a project? (is it a certain category you care about? or something else?)
- What do you think Giveth could do better?

It would great to prep these over the next week so we can get them out sooner than later.

**Comment by c0ric0ri** [comment]
Hey @clara-zi is this something you'd be interested to set up?

**Comment by clara-zi** [comment]
hey @c0ric0ri I am working in 2 documents currently tackling the 6th point:  

**"What are you usually looking for when donating to a project? (is it a certain category you care about?)"** 
There is a wealth of info in the donor survey around this. It also seems to be a really good place to start for getting a better understanding of what will resonate most with new visitors (donors in particular for this question.

Working file for aggregating survey response data:
https://docs.google.com/spreadsheets/d/1Uv9YdI9UHVKF4g015BRHXHk8L74J0xld/edit?usp=sharing&ouid=109498166059183643204&rtpof=true&sd=true

Drafting a reader friendly report :
https://docs.google.com/document/d/1qHIdxlEKaTOnbPd4cOqIhlnYmCVW5PeN43cBcfhVQPI/edit?usp=sharing

**Comment by SnakeGH** [comment]
super impressive data collection @clara-zi . Really impressed but what you are gathering and building. Well done!

**Comment by clara-zi** [comment]
Summary of info to date:
1) What benefits first attracted you to Giveth? 
(will collect some info from projects in project survey https://github.com/Giveth/giveth-planning/issues/978). 
Contains this question: "What are the Giveth features that you find most attractive?"
We don't have donor perspective.

2) What really excites you about Giveth? 
We don't really have this info

3) When you explain Giveth to other people, what do you say? 
We don't really have this info

4) When you first started using Giveth, is there anything you found really difficult or confusing? Can you explain why?
We don't really have any info on this - project survey will collect some feedback but does not address this 
5) Are you using your GIV for GIVpower & the GIVfarm?
We don't really have this info

6) What’s your favorite project that you’ve donated to and why did you choose that one? What are you usually looking for when donating to a project? (is it a certain category you care about? or something else?) See report above in Google doc - we have lot of info for this, thanks to the donor survey @SnakeGH 

7) What do you think Giveth could do better? We also have a good amount of feedback for this question from a donor perspective (again Donor survey).

**Comment by clara-zi** [comment]
@c0ric0ri created a task list for each item - are you thinking to run a separate poll for each piece of feedback? Frequency?
Do you want to consider running one through ContentStudio tomorrow as a test?

If we send these out by email this week, it will coincide with project survey - should we consider sending to different audience. Could probably aim to collect feedback on all items in one email - create another Typeform - wdyt is the best way?

**Comment by c0ric0ri** [comment]
SInce we collected this through the donor & project surveys, I will move this issue to closed.

https://lookerstudio.google.com/u/0/reporting/65865d10-e8e6-43f0-9f30-cef750d4a76e?s=pJsE89ZpZYk
