### ISSUE TITLE
Send meet the makers email invitation. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1184]
Hey team, 

We need to send the next Meet the Makers invite invitation on Feb 6th am CST please?
[But before, could you help me review this draft? ](https://docs.google.com/document/d/1ibKE4-EQ-Q451z38kJdqSUDYysXCXKzNorqfpIzUin0/edit) cc @danelsuga @ahmadabugosh @c0ric0ri 

Thank you!

**Comment by oyealmond** [comment]
cc @NikolaCreatrix @WhyldWanderer

**Comment by danelsuga** [comment]
Great! Thanks! I had a quick edit and also left a comment. Can look again in the morning. Late here.

**Comment by oyealmond** [comment]
Thank you so much @danelsuga :D

**Comment by oyealmond** [comment]
@WhyldWanderer

**Comment by WhyldWanderer** [comment]
Looks good @oyealmond! I added some preview text for the subject line...

**Comment by oyealmond** [comment]
Great! Thank you! @WhyldWanderer 💖
Maybe we can schedule the email today in our synch?

**Comment by WhyldWanderer** [comment]
sent!
