### ISSUE TITLE
GM! Ep4. promotional Tweets

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1189]
Hello @laurenluz & @c0ric0ri :) 

Could you please help me review [the GM! Ep4. Promotional Tweets](https://docs.google.com/document/d/1QQ4K5W_F-xngaNHGmJC-9DhkOkeTm93OvQCe5xhUfJQ/edit) please? 
Thank you! :D

**Comment by laurenluz** [comment]
ok, they're in the queue <3

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1620799932625027077
https://twitter.com/Givethio/status/1621192523636002816
https://twitter.com/Givethio/status/1621509577320677376
