### ISSUE TITLE
GIVback mockups

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#119]

**Comment by ForestSoleil** [comment]
SPEC Doc: https://www.notion.so/GIVBack-MVP-Spec-2d6335964e5b414082e41d7df89f9b3d

**Comment by ForestSoleil** [comment]
**GIVbacks*
- 1) Map out full user journey (Marko)
- 2) Design work (Marko)
    - done for io, but hasn't been deployed yet b/c it's not all spec'd out yet

**Comment by laurenluz** [comment]
https://www.notion.so/giveth/GIV-Design-Components-fc72bb8503604a349ad31d897dbe4b6d#35e7a1036ac74f52971b1fdb3ce7bdf2

**Comment by laurenluz** [comment]
Design by @markoprljic in progress
https://www.figma.com/file/FBqHg0UfeuaIueDEZG0tBS/Giveth.io?node-id=5815%3A2020

**Comment by laurenluz** [comment]
closing this, we'll use the GIVeconomy board for design stuff
