### ISSUE TITLE
Select Keywords for SEO - April 13

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1190]

**Comment by ahmadabugosh** [comment]
I made a list of the top keywords we're ranking for here (in the Targeted keyword tab): https://docs.google.com/spreadsheets/d/10e9ltdCl16rXgZ82gxAEZ-ROlhQiSnnIItUKfSaGUgc/edit#gid=1905862193

I think one cluster of keywords to go after would be the **donation** related keywords:

- crypto donation platform	
- donation projects	
- ethereum donations	
- web3 donations	
- official donations cryptocurrency	
- crypto airdrop rewards donations

I think we could make a page on the website , just for SEO that has a "donations" keyword theme. It could be a very basic page that is hidden from the navigation and just appears on Google when people search for those words (with just an image on top and some text).

I made a draft here of what the basic content could be: https://docs.google.com/document/d/10StNqgY411icT6FmhfPcnxHimiwBFWrV7pydWJSRvRs/edit#

Let me know what you think! @danelsuga @c0ric0ri @danelsuga

**Comment by danelsuga** [comment]
Great idea, @ahmadabugosh 
Let's do that for sure. The page you created is fantastic.

**Comment by ahmadabugosh** [comment]
Hey @mosaeedi @MoeNick, We want to make a landing page for SEO purposes. 

Can you make it into a template we can easily use to create more pages in the future? 

It will be a page that doesn't appear on the navigation and can be super simple. For the top maybe a simple image that we already have and the rest is just text. 

Can you start with this page here please? https://docs.google.com/document/d/10StNqgY411icT6FmhfPcnxHimiwBFWrV7pydWJSRvRs/edit#heading=h.5zovxx6ai50x

Thanks!

**Comment by c0ric0ri** [comment]
Where to place keywords on webpages:

- Title of Page
- Header of Page
- URL
- Image Names
- Body Text (mention 2x at most)
- Meta Description

**Comment by c0ric0ri** [comment]
Hey @clara-zi @MoeNick @danelsuga do you have any words to add here to be searched by Ahmad? Let's build out this list more this week so we can start implementing keywords soon. 

The idea would be to have some "niche" words that we can rank high for *public goods, refi, etc", and then have some "mainstream" search words and terms that more people are likely to search "crypto nonprofit, crypto donations, donation platform, fundraising for nonprofits."

We are aiming for a list of 50 keywords, and align on 10 of the most important right now to start working on.

**Comment by danelsuga** [comment]
Ok! Will brainstorm.

**Comment by ahmadabugosh** [comment]
We created the first SEO landing page here: https://giveth.io/landings/web3-crypto-donation-platform

Closing this issue now
