### ISSUE TITLE
Banner creation for ETHdenver. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1191]
Hey Rodri! 
So we need to design the banners we're going to have at ETHDenver! 

We would like to have 3 different banners: 

1 pendon banner of 120 x 90 cms
![PendonColgar1.jpg](https://images.zenhubusercontent.com/62f65d77fa19b9bc859863bc/27745980-2c5b-468b-8a64-0e039412e168) 

and 2 roll ups of 80 x 200 cms 

![banner-roll-up-85-x-200cm-1-cara.jpg](https://images.zenhubusercontent.com/62f65d77fa19b9bc859863bc/2810be28-0379-4354-a0ae-d8578e6e8f96)

Could you please help us design three proposals for the team to choose: 

**- horizontal neutral giveth banner 120 x 90 cms** (include Giveth social media, and the mission: Building the Future of Giving.) 
**- 1 roll up Giveth Neutral banner 80 x 200 cms.** Include the Giveth logo, and public goods phrase around the Giveth logo (the same design you made for swag) and social media. 
**- 1 roll up with the ETHDenver & Giveth design you made 80 x 200 cms.**  It could say: Giveth at ETHdenver 2023

**Comment by oyealmond** [comment]
cc @freshelle @divine-comedian @WhyldWanderer

**Comment by oyealmond** [comment]
Let's review this tomorrow: 

https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?node-id=2748%3A18086&t=77tTSFWXydQsrw55-1 

cc @divine-comedian

**Comment by c0ric0ri** [comment]
Has this been reviewed and approved?
