### ISSUE TITLE
Project Survey: Draft email, Tweet, social post to project owners

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#1192]
To ask project owners to complete the project survey to collect important feedback on their experience being part of the Giveth community and platform.

Some points to consider including:
- Start of the year; looking forward; Giveth is a year old and it's a good time to take stock and listen to our projects
- Giveth is continually evolving
- Projects are at the heart of our platform and our community - really important to get their feedback to continually improve.
- Survey takes 5-10 mins, depending on how involved a project is with Giveth.
- Reward is entering a raffle to boost project with GIVpower / promoting project ranking on platform for 3 months (see [forum post](https://forum.giveth.io/t/rewards-for-project-survey-respondents/965/14) for more info) 

Anything else to add? @danelsuga @c0ric0ri

**Comment by danelsuga** [comment]
Here's a start on the email:

https://docs.google.com/document/d/113lKsjb1SiA1unBf1jgRibVGSshk4bqaoPuEhWiwVH4/edit

**Comment by clara-zi** [comment]
@danelsuga Thank-you so much for drafting our outreach mail.

**Comment by danelsuga** [comment]
Pleasure. Change it anyway you like of course @clara-zi !

**Comment by clara-zi** [comment]
@c0ric0ri

**Comment by clara-zi** [comment]
Tweet draft in same file: https://docs.google.com/document/d/113lKsjb1SiA1unBf1jgRibVGSshk4bqaoPuEhWiwVH4/edit

**Comment by clara-zi** [comment]
Facebook and LinkedIn draft copy at bottom of same file:
https://docs.google.com/document/d/113lKsjb1SiA1unBf1jgRibVGSshk4bqaoPuEhWiwVH4/edit

Should we use survey cover page as image or some other artwork?

**Comment by clara-zi** [comment]
@ahmadabugosh

**Comment by clara-zi** [comment]
@SnakeGH @WhyldWanderer @c0ric0ri  where's the best place to find projects' social profiles to tag them in our social media posts? (Twitter handles, Facebook, LI etc). I have some info in Orbit but it's a bit scattered, wondering if there was a more comprehensive source?

**Comment by NikolaCreatrix** [comment]
Hi @clara-zi answering your question - honestly I believe that the only place we do have stored all this information is adminbro. But even there, you'd have to open up one by one projects to be able to see their social media accounts - if there are any.

I would like if @WhyldWanderer can confirm my statement, but I don't think we have such a comprehensive source - I imagine Hubspot would be a good place to store all this info - It just seems like a big project to actually transfer all that info into the hubspot.... I will keep thinking about this today and see if i have any other idea hitting me...

**Comment by laurenluz** [comment]
Hey @clara-zi - left some comments in the doc on the tweet (and pasted my edit)

Would love to see 3 tweets for this kind of thing - with different variations - so we can post multiple times. Can you draft a couple more?

Also I scheduled it for 11am Costa rica time tomorrow because Cori said this needs to go out tomorrow. If that's not right, lmk. 

We can also add a second tweet to the thread tagging projects (a good idea I think) - but I will need like a list of the handles that I can just copy/paste in there. lmk

**Comment by c0ric0ri** [comment]
Love the re-write @laurenluz, I added another 1st tweet draft as well. 

Let's double check in the Comms call that it makes sense to tweet already at 11am - I am not 100% sure of the timing tomorrow.

**Comment by clara-zi** [comment]
@ahmadabugosh - email is ready for scheduling, suggest 11am Costa Rica time - the same as the Tweet? wdyt?

Email copy can be found at the top of this document - let me know if you need anything.
https://docs.google.com/document/d/113lKsjb1SiA1unBf1jgRibVGSshk4bqaoPuEhWiwVH4/edit?usp=sharing

Please forward me a list of all the email addresses that the survey goes out to, so I can track responses. Can you get a report that provides any more detail alongside the email list eg Project name, project owner, social handles, giveth.io link, anything else useful I may have missed? Chancing my arm a bit but the more info the better ;) Thank-you

**Comment by clara-zi** [comment]
@ahmadabugosh did the email get scheduled / go out yet?

**Comment by ahmadabugosh** [comment]
@clara-zi Yes sent out!

**Comment by clara-zi** [comment]
Tweaked the original email a little - headed 'email reminder copy' - can be found at the top of the drafting doc - link above. Please give it the once over. Thanks @ahmadabugosh

**Comment by ahmadabugosh** [comment]
Done
