### ISSUE TITLE
Thread to promote #GIVtalk podcast

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1194]
Hey team :) @laurenluz 

Our #GIVtalk Twitter Spaces are now available in Spotify & Youtube! 
I made a [thread to promote](https://docs.google.com/document/d/1ROWYSO_pYBoONu4hVPwoxs00gkbBICL_4nFtgtyrmqI/edit), could you please review & share your comments? 

Thank you

**Comment by laurenluz** [comment]
edited & scheduled

**Comment by oyealmond** [comment]
loved the edits. Thank youuu

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1621887073891262465
