### ISSUE TITLE
ETH Denver Landing Page

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1195]
We can have a landing page set up to direct ETH Denver attendees to during the conference. Dev confirmed that it only takes a day (a few hours) to set one up if we have everything in order, so Comms can create whatever we feel would be best.

Some ideas discussed so far:

- TL:DR what is Giveth doing at ETH Denver
- Show projects that are being donated to - link to filtered Denver projects. Maybe a dynamic banner giving a glimpse of the top donated-to projects?
- Link to the mentorship channel
- Pizza DAO
- Talk times where Giveth will be speaking
- Impact Quest Information (or link to that page)
- A specific CTA to include? Probably encouraging donations?

P.S. What do we mean by landing page? Here's an example: https://giveth.io/gitcoingrants

**Comment by c0ric0ri** [comment]
Thank you @ahmadabugosh for taking on the facilitation of this landing page in regards to working with dev to get this page set up and optimized for SEO, etc.

Since Ahmad won't be attending ETH Denver, we just need to ensure that we support him by providing him with all relevant content for this page with clear direction. Appreciate any input you can provide here in the issue!

I've created a draft doc for the landing page for us to organize information and add relevant links: https://docs.google.com/document/d/1a1tqHiAyU6Pn96prlfSYS3_G04SLXas530vppqXnteE/edit

@WhyldWanderer @NikolaCreatrix @SnakeGH @divine-comedian @oyealmond @laurenluz

**Comment by c0ric0ri** [comment]
@MoeNick here is the issue

**Comment by MoeNick** [comment]
@ahmadabugosh did you already start the design with @mosaeedi or @Tosinolawale? Can I help?

**Comment by ahmadabugosh** [comment]
hey @c0ric0ri I have a draft of the outline [here](https://docs.google.com/document/d/1a1tqHiAyU6Pn96prlfSYS3_G04SLXas530vppqXnteE/edit#). 

However, we still need a lot of info for the Impact Quests and Impact Track Mentorship sections. 

--- 

@MoeNick No we didn't start design yet (the content is still not finalized). Can the team get started on a draft of the design while we're finalizing the final copy? (since I think the main sections wouldn't change much)

**Comment by mateodaza** [comment]
@MoeNick @c0ric0ri is it too much effort to make it work for the FLII as well? @Cotabe can hel with the copy but would be great to make the design easily adaptable for both events @ahmadabugosh

**Comment by divine-comedian** [comment]
echoing this here! BUIDL week of ETH Denver starts tomorrow (Friday) so if this is to have any relevance at all it needs to be live ASAP

**Comment by mateodaza** [comment]
> @mosaeedi will deliver it tonight for review.

@mosaeedi please don't forget about the FLII 😭 - at least tome way to change the title and the logo

**Comment by MoeNick** [comment]
@mateodaza Lets have another issue from comms team, I don't know the context about FLII

**Comment by mosaeedi** [comment]
## Design resource

### Event banner (>1280 & <1439)

**Comment by mosaeedi** [comment]
## Design resource | Banner on homepage

**(>1280 & <1439)**
[Link to Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20492%3A276727&t=AZvwUEHabDDbIPxz-4)

**(>1024  & <1279)**
[Link to Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20492%3A276728&t=AZvwUEHabDDbIPxz-4)

**(>768  & <1024)**
[Link to Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20492%3A276729&t=AZvwUEHabDDbIPxz-4)

**(Mobile)**
[Link to Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20492%3A276730&t=AZvwUEHabDDbIPxz-4)

---



<img width="935" alt="Screenshot 2023-02-24 at 3 26 39 PM" src="https://user-images.githubusercontent.com/13708322/221173455-52e9bd64-e846-4a96-bfd2-ef2c0b64d68f.png">

**Comment by c0ric0ri** [comment]
https://giveth.io/landings/ethdenver
