### ISSUE TITLE
Giveth Projects socials data base . 

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#1199]
This will improve our ability to tag projects and improve engagement across our social platforms.
Bulk upload to HubSpot / Orbit.

**Comment by clara-zi** [comment]
https://docs.google.com/spreadsheets/d/1vDcohid8ehSlPg_ZzAJONhTRZ9PsL8H2kTy6JrlZv9g/edit?usp=sharing

**Comment by oyealmond** [comment]
thanks @clara-zi! 
Putting this in icebox in the meantime.

**Comment by oyealmond** [comment]
some linkedIn projects URL and FB as well. Maybe this is useful for you @missgene @SteffanThorn? 
https://docs.google.com/spreadsheets/d/1vDcohid8ehSlPg_ZzAJONhTRZ9PsL8H2kTy6JrlZv9g/edit?usp=sharing

**Comment by SteffanThorn** [comment]
Is there a list somewhere of all the giveth projects' twitter handles? 
If so, I can make a twitter list with them and would be much easier to interact on there.

**Comment by oyealmond** [comment]
would be so great to count with that list @SteffanThorn . If you have the capacity to do it please go, I would be a very appreciated effort!

**Comment by missgene** [comment]
I have started getting some details during the GIveth QF Alpha Round @SteffanThorn . You can see some of the project details with their twitter usernames here: https://docs.google.com/spreadsheets/d/1vAH98Q_yhEETouuHheMg-0xD_xxZLeVp1MJ--2lOtMI/edit?usp=sharing
