### ISSUE TITLE
GIVBacks MVP

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#120]

**Comment by ForestSoleil** [comment]
Flesh out Notion doc with more details in each bullet point.
Then turn these points into GitHub issues.
Griff & Forest to tag team - 1 hour session. Forest to schedule. Invite Willy if he's able to join.

**Comment by WhyldWanderer** [comment]
for reference: https://www.notion.so/giveth/GIVBack-MVP-Spec-2d6335964e5b414082e41d7df89f9b3d
