### ISSUE TITLE
Tweet for Verified projects R29

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1201]
Hi there, I am expecting to deliver the draft this week, but as for now I am waiting for 2/3 more projects to complete sm posts so they can get verified, I am waiting for their email responses...and that way we have more than 2 projects on the thread. 

So the draft should be ready no later than this Friday. That's my goal.

**Comment by NikolaCreatrix** [comment]
Working on the draft here https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by NikolaCreatrix** [comment]
Okay done. Earthquake newly verified projects included (except the GRACEaid - which has already been verified for some time).

https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

@laurenluz

**Comment by laurenluz** [comment]
Amazing @NikolaCreatrix - it's so good ❤️ 

I made some very minor edits in tweet hunter & copied it into the doc.

**Comment by laurenluz** [comment]
actually, I think I will schedule this on on Tuesday and make a custom tweet for the 1st one - can we use your draft 1st one for next round?
