### ISSUE TITLE
Make summary notes of the important focal points of the stewards call

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1203]
Notes: https://www.notion.so/giveth/Giveth-Stewards-Call-05963c91fe4d41aca8aac61e5186c25c

Video: https://www.youtube.com/watch?v=W8GgHgLd9mo

Would love to see this as a notion or google doc, bulleted list - clear key points/thoughts from the call :)

**Comment by danelsuga** [comment]
How's this?

https://docs.google.com/document/d/1RtqPeCpWXlAaCt_UIh_lAEujM8UAC4Pp-ZRWn_y2A40/edit?usp=sharing

**Comment by laurenluz** [comment]
this was PERFECT - thank you so much, you are my hero <3
