### ISSUE TITLE
GIVtalk Twitter Space ft. Web3 Education. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1204]
Hey dear team! @laurenluz @c0ric0ri 

Could you help me review[ the planning document around our next GIVtalk Twitter Space ft. Web3 Education challenges ](https://docs.google.com/document/d/1i514ynlQBewIUQUtkBkXvFNEw9W8lhfs0nEB22n7ccI/edit)please? 

The tweets as always are in the same doc too. 💫

**Comment by laurenluz** [comment]
edited & scheduled - thanks @oyealmond
