### ISSUE TITLE
GM! Ep5. promotional Tweets. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1205]
Hey @laurenluz 💫

Could you help me [review the drafts for GM! Ep5 ](https://docs.google.com/document/d/1mLBfnjLIZkiDWYcDHdHI8i4lFeBcBwdeHLwqIVo45Ec/edit)please? 

Thank you as always!

**Comment by laurenluz** [comment]
Thank you @oyealmond - as always - they're great!

I scheduled them all, first one goes out today!

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1623366844068274176
