### ISSUE TITLE
Fiat Integration Launch Comms Strategy

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1206]
We'll be launching fiat integration at the end of March, targeting March 31 depending on how testing goes.

**Comment by c0ric0ri** [comment]
@Cotabe thanks for stepping up to test this with the dev team and determine the key points for Comms to highlight around this launch. Please provide the updates here in the epic so that they can be used for the various pieces of content we need to prepare.

Would you be able to provide them here by March 24 so we can finalize content next week?

**Comment by Cotabe** [comment]
Hey @c0ric0ri sorry for the delay. I'm not sure that we will be ready to launch the Fiat integration by the 31st. 

Here are the results of the testing https://docs.google.com/spreadsheets/d/1Z622fxXDSkbsGQ07XfV9TW3UvUpDypsaAVsiVD99HLc/edit#gid=651927522

Here are some of the key points anyways:

Donorbox, 100% success rate, Incredibly smooth if you have Paypal, you can donate small amounts like 10 USD, but only works for Giveth. 

Onramper seems to be working good for me, but I know the success rate has been under 50 & I don't think it will be released yet. In onramper what you need to do first is choose your currency, choose how you want to pay & click on buy ETH. If it's the first time you will have to create a password & do a KYC (with official ID & a selfie) its long the first time you do it. But once you do it, the process becomes way smoother.

Mt. Pelerin. has not been tested by anyone as far as I can see. It seems you can buy XDAI with bank transfer with 0% commission for up to 500 CHF, after there is a commission of 1.3%. You can buy with 14 popular currencies  (EUR, CHF, USD, AUD, GBP, CAD, DKK, HKD, JPY, NOK, NZD, SEK, ZAR, SGD). With credit card you can only get charged in EUR & CHF. You will need to go through KYC (ID & a pic holding the ID and a paper with the date). I tried, but my first KYC was unsuccessful, I repeated it on Thursday, but I still have not heard back.
