### ISSUE TITLE
Research on Mainstream Publications for PR Outreach

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1209]
Coming out of a meeting with @danelsuga - in regards to getting in front of new audiences and driving more activity to Giveth, an idea would be to explore opportunities to get published in larger, more mainstream publications.

It would be interesting to submit content that focused more on the mission than on the details of the product, and that talks about blockchain-in-good in a time where crypto has a particularly bad reputation.

To research:

- What's the process for getting published in say, Forbes or the Huffington Post? 
- Can we apply with content pitches? Do we need to do concerted outreach to PR departments?
- What publications would be ideal?

**Comment by c0ric0ri** [comment]
Hey @danelsuga , this woman joined our [Twitter Space](https://twitter.com/i/spaces/1nAKErMzZZeGL?s=20) today with Susie where we spoke about Giveth. Might be an interesting contact to connect with on this initiative. She followed me on Twitter and she also [posted a question](https://twitter.com/SusieKav/status/1628807029077811205?s=20). Do you want to reach out? Maybe answering the question is a good way to open a discussion?

https://twitter.com/ElleToussi?s=20

She is the chair of https://twitter.com/SPJ_IC

**Comment by danelsuga** [comment]
I missed this @c0ric0ri 
I just looked at the question but I don't know what she's talking about. I feel a bit out of the loop to connect without having any context.
