### ISSUE TITLE
Onboard Bowen to GIV Token Team

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#121]

**Comment by ForestSoleil** [comment]
Primary role:
- Reviewing Airdrop contributors to ensure we aren't missing anyone.
- Ensuring our scoring of contribution is accurate. 
- Make sure everyone who deserves tokens receives them. 
- Have a plan/process (Google form link people can fill out) if they respond AFTER our Airdrop. Way to capture & hopefully send tokens to them retroactively. 
- Communicating with folks and tracking down addresses. 
- Marketing content creation: blog posts, memes, ideation.

**Comment by bowensanders** [comment]
This may also involve making a new alias for "token related support" that I would have to deal with, especially for #4 - and have that in whatever marketing copy is written. I'm sure it will be trivial to set something like that up that forwards to my bowen@giveth.io

**Comment by ForestSoleil** [comment]
@geleeroyale See Bowen's comment above.
