### ISSUE TITLE
Homepage Banner to link to Earthquake Relief Projects

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1211]
We're creating a blog post quickly to list out the projects on Giveth which are providing aid to the victims of the recent earthquake in Syria and Turkey. Related issue: https://github.com/Giveth/giveth-planning/issues/1208

We would love to update the homepage as soon as possible with a banner that links to this blog post, encouraging support for aid!

**Comment by c0ric0ri** [comment]
"We're raising support for the Turkey-Syria Earthquake!"

@WhyldWanderer @danelsuga @NikolaCreatrix @ahmadabugosh would this work for a banner text to use on the blog and on the homapage?

**Comment by ahmadabugosh** [comment]
Maybe instead "Donate crypto directly to earthquake disaster relief in Turkey and Syria!" (or a variation of that) , since I think the main things we want to highlight are 1) How they are donating crypto 2) How it's going directly to efforts on the ground (and not to us)

**Comment by danelsuga** [comment]
Yes to @ahmadabugosh also bc:

- changes narrative from what WE'RE doing to what donor can do

- puts emphasis on the action of the donor to do good

**Comment by danelsuga** [comment]
I recommend without exclamation point.

**Comment by danelsuga** [comment]
@rodricastillo9013 can you help with this asap? I don't remember your timezone. I'm CET. This will need to be published latest in 8 hours from now, I'd say.

**Comment by danelsuga** [comment]
Banner text:

Donate crypto directly to earthquake disaster relief in Turkey and Syria

**Comment by rodricastillo9013** [comment]
![Donate banner](https://user-images.githubusercontent.com/61791380/217827403-e55e95a7-31d5-4626-80b9-8ac4856a31d4.png)
@danelsuga @c0ric0ri
