### ISSUE TITLE
Aprendamos Refi design creation. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1212]
Hola querido Rodri :) 

Pues con la novedad que estamos x lanzar un podcast nuevo en español y ocupamos una identidad gráfica para lanzarlo y comunicarlo. 

¿Podrías ayudarme a diseñar una propuesta de identidad como hiciste con GIVtalk y GM! podcast por fi? 

Te pediría el acceso a Figma para que pueda cambiarle los títulos. 

Información:

**Podcast:** 
Aprendamos ReFi x Giveth 

**Título:** 
xxx (dejar espacio para diferentes títulos) 

**Invitados:** 
xxx (dejar espacio para diferentes invitadxs) 

**Hosts:**
@Cotabe_M & @oyealmond 

**** 

Basicamente sería eso :) 
¿y podrías ayudarme creando también un banner como el que hiciste con GM! anunciando el lanzamiento del podcast? 

![FmHcOsLWIAIfwgj-1.jpg](https://images.zenhubusercontent.com/62f65d77fa19b9bc859863bc/d305d362-2577-4225-a902-b4c7f217c038)

Como ese pero cambiando la info: 

Aprendamos ReFi x Giveth
LAUCH (xxx dejar espacio para modificar la info)
(xxx dejar espacio para modificar la hora) 
y agregar 
@Givethio Youtube. 

(No saldrá en Twitter. Sólo FYI)

Mil gracias :)

**Comment by laurenluz** [comment]
is this done @oyealmond ?

**Comment by oyealmond** [comment]
Oh, Is actually done yes! Thank you @laurenluz
