### ISSUE TITLE
Tweet for Earthquake Disaster Relief

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1213]
Hey @c0ric0ri 

This is the tweet draft for review. https://docs.google.com/document/d/1YPm9k4A7i31K3DurKDJS_VVbzE2_PRyB0LoT6hfNLU0/edit?usp=sharing

You have edit access in case you need it. I
 know it's basic, but I think it feels urgent enough.

And can also serve other platforms (Facebook + linkedIn)

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1623492965480951811
