### ISSUE TITLE
Community Spotlight Tweet for Earthquake Relief

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1215]

**Comment by c0ric0ri** [comment]
Drafting here: https://docs.google.com/document/d/1iM4pFUzRpOor8eFj9vN7952QR1ymXmASGn9USGl3QkY/edit

**Comment by c0ric0ri** [comment]
Ready for review...do we have the tags right for who presented today?

**Comment by laurenluz** [comment]
I edited it, looks good, I can put this out this afternoon.

if you find the tags for the people who presented, let me know, and DM me when you're done w/ it @c0ric0ri

**Comment by c0ric0ri** [comment]
So far I have @raybankless on Twitter - would love the other two twitter handles for Sum & Karlibrk, I've DMed them

**Comment by c0ric0ri** [comment]
Ok the orgs who presented today are @BanklessTr & @ITUblockcain

@ITUblockcain presenters did inform us about @ahbap who they support.  

@BanklessTr was presented by @raybankless (personal handle).

So if we want to use @ahbap and @raybankless somewhere in the thread, this is an option.

@laurenluz

**Comment by laurenluz** [comment]
@c0ric0ri @ahmadabugosh - do we have the audio clip?

**Comment by oyealmond** [comment]
heeey @ahmadabugosh :) 
I will post the clip to Instagram. 
Is it ready? 
Thank you!

**Comment by ahmadabugosh** [comment]
@oyealmond I still can't download it! 😭 I tried so many times but it seems like it's still processing...

**Comment by c0ric0ri** [comment]
Hmmm. Is it possible to record the youtube recording, and use the audio from that? Some creative hack in this sense? @ahmadabugosh 

If all else fails, should we just use a clip of the youtube video with that quote that we want? I mean the iphone allows you to screen record, for example.

**Comment by c0ric0ri** [comment]
I am working on screen capturing right now with my cell phone.

Remember the purpose of this - it's extremely urgent. Trying to get a video now so we can move forward with this. Monday is 3 days away, that's a long time

**Comment by oyealmond** [comment]
I think we can promote the blog post, and the new tweets & projects we have rn on Twitter until Monday. 
And then generate new content Monday when the help will still be needed.

**Comment by c0ric0ri** [comment]
Ok yes it's a good point. Think I'm just overly focused on getting video/audio content out because it can be so powerful :/ but yeah, within our capabilities

**Comment by c0ric0ri** [comment]
Perhaps we can use the youtube link to start at the beginning of the project spotlight for this thread.

And next week we then use audio clips sporadically in shorter tweets once we can pull them.

@oyealmond @laurenluz @ahmadabugosh

**Comment by c0ric0ri** [comment]
Ok we could use this link to start for the project presentation: https://www.youtube.com/live/LZ3FRjiEu20?feature=share&t=2575

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri @laurenluz @oyealmond , 

It still didn't process, so I just played it back and recorded my screen. 

I uploaded the video from the last 17 minutes of the call and I also made 4 shorter clips (since I don't think we can upload the entire 17 minutes on Twitter because it's too long): https://drive.google.com/drive/u/0/folders/1xh6PQn8WZ96wmGqJAQX3fImoeauay1mi

**Comment by laurenluz** [comment]
Thank you ahmad! You are amazing.

I added clip 3 to the tweet and set it to go out in about 30 min.
