### ISSUE TITLE
Giveth project update - due May 10

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1216]
We'll need to update the giveth project before May 10 again!

@NikolaCreatrix - can you make sure this doesn't slip through the cracks in a couple of months?

**Comment by NikolaCreatrix** [comment]
Yes, thank you @laurenluz and yes I will make sure to remind us at the beginning of May!

**Comment by c0ric0ri** [comment]
@NikolaCreatrix would you be up for collecting some bullet point ideas here in a draft, and when we get agreement on it someone can draft the update?

**Comment by laurenluz** [comment]
We pretty much have it together in #1286

**Comment by NikolaCreatrix** [comment]
Thanks @laurenluz just checked and I agree. Looks great for the updates too!

**Comment by c0ric0ri** [comment]
@danelsuga trying to find a writer for this, would you be willing to take this on? It should be pretty fast using the points linked in the issue above. We should post the update on Tuesday so it can be done when you're back on Monday?

**Comment by danelsuga** [comment]
Ok will tackle Monday.

**Comment by laurenluz** [comment]
I made an update already on the project to mention our gitcoin grants. We can still make another update, but I would make it short/quick @danelsuga 

You could add links to our recent launches twitter thread and then say what we're working on now, can pull stuff from our gitcoin grant. I wouldn't spend more than 20-30 min on this.

**Comment by danelsuga** [comment]
https://docs.google.com/document/d/1NttEFF1PDPigvdKxG8kXTx66u3t6nkZaBPiGrNUbO_4/edit?usp=sharing

wondering about a shorter list version of the retrospective or the descriptive version...

**Comment by danelsuga** [comment]
@c0ric0ri

**Comment by c0ric0ri** [comment]
Thanks @danelsuga, left you a comment there. I think the shorter version is ok with the link

**Comment by danelsuga** [comment]
another reviewer please! :D
@NikolaCreatrix 
@laurenluz

**Comment by laurenluz** [comment]
Posted it. Thanks @danelsuga - great job

Next time double check though to see what might have changed since the thread... we added optimism & celo for example... and also we're not really spending much time on fiat anymore...

2 weeks is kind of long time in our development WG, and it's nice to be posting what's really most recent/new because things change fast.

Anyway, I don't it makes a huge difference anyway for a small thing like this, but keep it in mind.
