### ISSUE TITLE
Turn homepage copy notes into Tweets

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1217]
As discussed, we had some awesome one-liners in the copy here that we're not going to use. @c0ric0ri if you can make then into a doc of small tweets, it would be awesome!

https://docs.google.com/document/d/181yiJK7GNxXhDhNuUisSjUg_maD6pAoT4UjHi1RKqzo/edit

**Comment by c0ric0ri** [comment]
Maybe a reminder tweet later in the week to state how much we've raised so far.

If we raise 25k by Monday, then follow up information is needed on things like: When would the round be? How many projects will be in this round? 

We can tweet about all of this when we have the info as well.

**Comment by c0ric0ri** [comment]
I've been drafting here: https://docs.google.com/document/d/1DpsKb7b6kDK8SRzH1ptliIS_mqKJ1I917aPs3YDBXUA/edit

**Comment by laurenluz** [comment]
can you make comment access @c0ric0ri ?

**Comment by c0ric0ri** [comment]
Hey @laurenluz , this is ready for review! I've consolidated statements down into various tweets that are checked for character limits, etc.

**Comment by laurenluz** [comment]
@clara-zi - these can be repurposed for linkedin
