### ISSUE TITLE
Tweets for Feb 13 to 19th 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1218]
Hey @laurenluz! 

I drafted some tweets for next week, covering community reminders (tried to include Turkey support too), GM!, & more. 

[Could you help me review? ](https://docs.google.com/document/d/1IiAIT466V-tPZpIM7PaPBPySOs6eifWdlVmkcWnt2cA/edit)

Thank you!

**Comment by laurenluz** [comment]
girl, you are amazing! these are amazing! thank you!!

so just to confirm - we are taking a break from releasing more GM episodes for a few weeks? when does season 2 start? we're not putting a new one our on friday - right?

**Comment by oyealmond** [comment]
exactly! There's no new one until we start season 2 :)

Aww, thank you @laurenluz!

**Comment by laurenluz** [comment]
wow almond these were so great - I put them all in tweet hunter with minor edits

**Comment by oyealmond** [comment]
uhooo 🕺🏼💫 thanks @laurenluz !
