### ISSUE TITLE
Create forum post: donations from DAOs for earthquake fundraisers

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#1219]
Create a forum post that can be used in different DAO forums, requesting donations from the DAOs to support earthquake fundraisers of Giveth.

"Make sure to emphasize that they would get GIV in return for their donation".

To include: 
- some background to the situation
- brief details and links to each fundraiser on Giveth - currently 4

**Comment by clara-zi** [comment]
Draft ready for review: @GriffGreen @danelsuga @laurenluz @WhyldWanderer @c0ric0ri @ahmadabugosh 

https://docs.google.com/document/d/1066Fvh31YQFBXUaUnDNOzQPMurvFfqMFIH3EyfQxKMU/edit?usp=sharing

**Comment by clara-zi** [comment]
adding @spectoregia @Zeptimus for review

**Comment by danelsuga** [comment]
Reviewed @clara-zi 
I hope it can go up asap!

**Comment by Zeptimus** [comment]
Reviewed and shared some comments

**Comment by clara-zi** [comment]
Thanks for all your helpful comments /edits. Review is complete. If everyone is happy I will close this issue @danelsuga @Zeptimus @ahmadabugosh @spectoregia
