### ISSUE TITLE
Tweet thread about Matching Pool for Earthquake

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1221]
We are trying to raise $25k by Monday to launch a quadratic funding round in partnership with Gitcoin.

If we don't raise $25,000 by Monday Feb 20th, we will return all the funds back to the donors and not run the round.

If we raise $25,000 or more by Monday, all the funds donated to this campaign will be distributed using the Allo Protocol, the latest evolution of Gitcoin Grants just as was done in the Alpha round.

https://giveth.io/project/earthquake-relief-qf-matching-pool

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1625179326873305088

**Comment by laurenluz** [comment]
It would be great to have another one of this out later this week, as we have more updates
