### ISSUE TITLE
ETHDenver Twitter Space planning. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1222]
Hey dears @laurenluz , @divine-comedian [here's the planning document](https://docs.google.com/document/d/1pjaSVgKN4SeHO4V6y-0_x_PPtcqIJPV6_qD2ahniQ2I/edit) for next week ETHDenver Twitter Space for you to review :) 

@laurenluz the Tweets are ready to schedule :)

**Comment by laurenluz** [comment]
@oyealmond - scheduled the tweets & I made some direct edits in the doc (just grammar stuff)
