### ISSUE TITLE
Tweet Thread on Giveth Talks at ETH Denver

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1223]

**Comment by c0ric0ri** [comment]
Hey @laurenluz can you help review that this is all the talks we have to promote? is it 3 total, and just you and Griff?

Two talks for Lauren:

https://events.ethdenver.com/eden23/attendease/networking/experience/de0f05af-c9da-4429-a4a3-21cdcd37a1b7/0f92cb6a-289c-46ef-b4b8-4ff3a5ad785a

https://events.ethdenver.com/eden23/attendease/networking/experience/3185f05e-1283-47c4-b1cd-c456c3b6af3a/dd50c09c-f707-4389-a60a-75c2d37c2aa5

Talks for Griff:

https://events.ethdenver.com/eden23/attendease/networking/experience/9dfae4fa-a017-47bb-837c-e2b7b8da8468/af96b57b-a734-45c0-918f-f32bb030cbcc

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri I think this first talk is not by our @laurenluz , but someone else named Lauren https://events.ethdenver.com/eden23/attendease/networking/experience/de0f05af-c9da-4429-a4a3-21cdcd37a1b7/0f92cb6a-289c-46ef-b4b8-4ff3a5ad785a

**Comment by laurenluz** [comment]
1. Yeah Ahmad is right. I'm giving one talk at eth denver: https://events.ethdenver.com/eden23/attendease/networking/experience/3185f05e-1283-47c4-b1cd-c456c3b6af3a/dd50c09c-f707-4389-a60a-75c2d37c2aa5

The info is wrote (I just submitted a change request). It's called "Why DAOs will change the world". Here is the synopsis: https://docs.google.com/document/d/1I0isd92WCV6DvmVkGh0HdZVEngfa1s6hirZNgPOIhPE/edit

2. I'm also speaking on a Panel on Saturday at Camp Buidl. At 1:45pm MST. Here is the info. For the tweet, we should tag the other contributors and the moderator. https://docs.google.com/document/d/1-9vxLDJm25HqviXG4KvRGdqKMSJmue0crmbsXo5W_qY/edit

3. I'm also speaking on a Panel at DAOs @ Denver. At 2:05pm MST. Here is the info. We should tag metacartel as well, and I think Tally Ho who is hosting it (you should look this up)
https://docs.google.com/document/d/1iVXp3SiTmbNsjpHh2L7M8RSSgzUOXPx5RbQk_Mk-kzA/edit

4. Griff is speaking on a Panel at DAOs @ Denver. Here's the info: https://twitter.com/DaoLens/status/1628765431875141632

5. Griff is speaking on mainstage at ETH Denver. IT will be called "Combatting the Metacrisis". The info in the schedule is correct: https://events.ethdenver.com/eden23/attendease/networking/experience/9dfae4fa-a017-47bb-837c-e2b7b8da8468/af96b57b-a734-45c0-918f-f32bb030cbcc

@c0ric0ri will you have this thread ready to tweet for tomorrow? With the 1st talk on Satrday I think it would be good

**Comment by laurenluz** [comment]
I think these should be listed/explained in chronological order (not in the order I listed them :)

And @ahmadabugosh if we can add this info to the landing page, it would be nice.

**Comment by laurenluz** [comment]
I'm also speaking at DAOplanet, but I have no idea when and about what!

**Comment by laurenluz** [comment]
@ahmadabugosh - would you be down to put all these talks & their locations on a google calendar so that people could add it to their calendars easily in one click?

**Comment by laurenluz** [comment]
https://twitter.com/daosatdenver/status/1626625107283136513

**Comment by laurenluz** [comment]
I scheduled this FYI as a standalone for Sat morning:

Today at @EthereumDenver's Camp #Buidl:

Learn how to be an effective contributor in a DAO or web3 project

Hosted by @borrowlucid w/ panelists @karmaticacid @DekanBro @sminert & pancho

⏰ 1:45-2:30pm
📌 https://www.google.com/maps/place/CSU+Spur/@39.783795,-104.9734008,17z/data=!3m1!4b1!4m6!3m5!1s0x876c799939583a41:0xf5d80567263c1e3b!8m2!3d39.783795!4d-104.9734008!16s%2Fg%2F11s18j9_f4?hl=en&source=opensearch&coh=164777&entry=tt&shorturl=1 
Full schedule: https://docs.google.com/spreadsheets/d/1efW_GZfwhgFbDV5ioDiw5yBLKgRNaG_YatOQWK9Oq_0/edit#gid=137061469

**Comment by c0ric0ri** [comment]
Draft here for review! https://docs.google.com/document/d/1gOCWcU43ehRReVj0vz56Q4RhGvbQqi5KdEt7IT4YlJY/edit

@oyealmond @laurenluz 

My eyes are little burned today so really hoping I didn't miss any tags, would appreciate more eyes on details there

**Comment by oyealmond** [comment]
Hey @Cori :) 
I think is great, Im not aware of the talks info, maybe @laurenluz review will be way more useful than mine

**Comment by laurenluz** [comment]
This is great @c0ric0ri - I made some fixes (Added links etc.) and have it scheduled to go out in and hr & 15.

Thank you so much!!

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1629210319548547072

**Comment by ahmadabugosh** [comment]
@laurenluz I made an "Add all to calendar" link here: https://calendar.google.com/calendar/u/0?cid=Z2l2ZXRoZXRoZGVudmVyQGdtYWlsLmNvbQ
