### ISSUE TITLE
Tweet pointing to the landing page with key highlights

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1224]
We could pin this to our profile during the conference.

**Comment by c0ric0ri** [comment]
Draft here for review. I thought it's best to keep it simple to one tweet instead of a thread, but let me know what you think:

https://docs.google.com/document/d/1SMyWALfFYHZQTRw8sUtoA2bKrXUsQwwibCL2EyCxrgA/edit

@laurenluz @oyealmond

**Comment by laurenluz** [comment]
it's great - do you know the landing page will be up?

**Comment by laurenluz** [comment]
https://giveth.io/landings/ethdenver

I scheduled for tomorrow
