### ISSUE TITLE
Evolving Nonprofits Tweet thread

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1225]
Stee drafted (and I edited) a tweet thread to summarize Griff's recent blog.

I think it's o.k. but could still be improved a little. I would love some support on this - someone to jump in there and make some suggestions... maybe add on the ending a bit or clear up anything that feels off/confusing.

@danelsuga - since you are really familiar w/ this blog, could you take it on?

I would love if you could:
- edit the thread (direct suggestions are ideal)
- add any memes you think are relevant
- add extra tweets if you feel info is missing

Tweet draft: https://docs.google.com/document/d/144oTxAYpa-KexgYfgY-ZvwJ_7hZfZ3_V-K2DGlz8WZ4/edit

Blog (for reference): https://medium.com/giveth/evolving-nonprofits-into-regen-economies-f8282f97f8d3

FYI - when there are 3 line breaks, it means it is a new tweet :)

**Comment by danelsuga** [comment]
I put in some ideas. Let me know what you think @laurenluz

**Comment by danelsuga** [comment]
@laurenluz did you recently mention you created a tweet thread on this already using AI? otherwise, where do we stand on this?

**Comment by SteffanThorn** [comment]
I've redone the first half of the thread and edited through the second half so it fits as a thread. 

@laurenluz please review.

**Comment by laurenluz** [comment]
ok I edited it. thanks @SteffanThorn 

I think we should take out the entire reputation token thing and if we want that can be its own thread.  it just gets way too long and exhausting otherwise with too many details.

**Comment by SteffanThorn** [comment]
Yes this was a long one. 
Let’s create a new issue for the reputation thread.

**Comment by laurenluz** [comment]
cool. can you give this thread another proofread, fix up the images & schedule it @SteffanThorn ?

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1697263494704611570
