### ISSUE TITLE
Banner for ETH Denver Landing Page

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1226]
We need a top banner for this page - https://github.com/Giveth/giveth-planning/issues/1195

Here is the draft of the content for reference: https://docs.google.com/document/d/1a1tqHiAyU6Pn96prlfSYS3_G04SLXas530vppqXnteE/edit#heading=h.yfnw8qz0ybkv

**Comment by c0ric0ri** [comment]
Hey @rodricastillo9013 , we are currently working on the content for a landing page for ETH Denver. Can you help us make a banner?

@ahmad FYI

**Comment by c0ric0ri** [comment]
@mosaeedi @Tosinolawale tagging you here, saw your comment in Discord about banners

**Comment by rodricastillo9013** [comment]
![ETHdenver Banner](https://user-images.githubusercontent.com/61791380/220905907-05777ed3-2f68-453a-8577-d18caf8d6504.png)

I don't know if they have a defined copy for the banner! tell me what you think! @c0ric0ri @ahmadabugosh

**Comment by danelsuga** [comment]
Think this issue is closable @c0ric0ri ?
