### ISSUE TITLE
Promoting & hire 1-2 full time smart contract devs

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#123]
- Even though it’s not in the MVP - it would be nice to have a smart contract dev. Put in efforts to hire 1-2 full time devs on long term commitment. 
- Forest to support in: Creating formal job outline (mission, etc.) and post listings to our social media.
- Smart Contract Dev Role: Support Edu in reviewing the code. Change some things. Smart contract dev can do other dev work.
- People/organizations to reach out to:
    - Mariana in Barcelona - Women Who Code / Blockchain organization
    - Black Girls Code - tap these organizations directly.
- Ideally someone who has worked with a project before. Need teacher, not a student. Or an early student from previous year who has some pedigree and references for code.

**Comment by ForestSoleil** [comment]
Forest to ping Griff for details.

**Comment by ForestSoleil** [comment]
3/10 update:
Got required details from Griff. 
Input draft into Notion doc: 
Need to spend some time outlining the content in more detail and making it look professional for job postings.

**Comment by WhyldWanderer** [comment]
Job Description has been created and approved: https://docs.giveth.io/jobs/
We are currently reaching out in different channels to promote.

We can keep a list in this issue of the places that weve reached out to make sure that weve got all the bases covered.

**Comment by WhyldWanderer** [comment]
related to https://github.com/Giveth/giveth-planning/issues/36

**Comment by ForestSoleil** [comment]
Updated email to receive applications from Griff to givethdotio@gmail.com
Have not yet received any submissions

**Comment by WhyldWanderer** [comment]
As we receive submissions, Dani and I are adding the info into this spreadsheet to be reviewed by Dani and Griff for interview scheduling

https://docs.google.com/spreadsheets/d/1gNkXbC2eYX4HWk6vkAY8mCeKnm20tIXOs3_6xUB5v2Y/edit?usp=sharing

**Comment by ForestSoleil** [comment]
Interviews with Griff are in progress
Continuining momentum of outreach
Published to several crypto jobs sites & newsletters for promo

**Comment by laurenluz** [comment]
I'll make another tweet for this for today. Sunday seems like a good day to apply for a job haha
