### ISSUE TITLE
Chainvine / Referral Program Tweet Thread - March 25

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1230]

**Comment by ahmadabugosh** [comment]
Hey @laurenluz @oyealmond , Can one of you start working on a Tweet thread for the Giveth Referral program (to post and announce the program to the public in mid March)? Here are the details you would need:

Landing page on Giveth https://giveth.io/referral
Chainvine Page https://app.chainvine.xyz/giveth
Video Explainer https://youtu.be/02C9KcRNgP0

**Comment by laurenluz** [comment]
heck yeah!

**Comment by laurenluz** [comment]
projects can share their own referral link and get GIVbacks

**Comment by c0ric0ri** [comment]
Draft for review. I guess this week it will just be for Lens....

https://docs.google.com/document/d/1U68tStiIxHH7vP_Cp52dExsQYKniZKiRVncZRu3MBz8/edit

I left the details out regarding the exact breakdown of rewards. I think this is covered well in the blog post and the docs. 

@danelsuga @laurenluz @ahmadabugosh

**Comment by laurenluz** [comment]
great job Cori - I left a small comment.

**Comment by c0ric0ri** [comment]
Worked through the comments @ahmadabugosh @danelsuga @laurenluz , let me know thoughts on this final version.

**Comment by laurenluz** [comment]
I made some minor edits, let's call it done, I'll schedule it once we set the launch & have the blog up.

**Comment by laurenluz** [comment]
https://twitter.com/Giveth/status/1641822684555235328
