### ISSUE TITLE
Tweet announcing Giveth's impact quests! @ ETHDenver

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1232]
Hey dear team! @c0ric0ri @laurenluz 

We're ready to announce Giveth's Impact Quests! 
Could you help us[ tweeting the announcement](https://docs.google.com/document/d/1S7H5SmxuoqDKgQ1HR0qy_q2zH65fMciky-pK-ihO178/edit)? 

Thank you so much! 

cc @divine-comedian @WhyldWanderer

**Comment by laurenluz** [comment]
edited and scheduled for today at 2pm EST
