### ISSUE TITLE
Turkey-Syria Earthquake Background for Matching Pool support

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#1236]
Support Gorkem from Inverter for a piece on the Turkey-Syria earthquake to be published on emergencyrelief.xyz pointing people to our matching pool project.

https://docs.google.com/document/d/1xEVEdX7V6wNUjH_tPxhroLdsI6wMhYPHjaVOpoUvQqE/edit

@c0ric0ri

**Comment by danelsuga** [comment]
Gorkem and I went through the edits yesterday 22 Feb.

**Comment by c0ric0ri** [comment]
Thank you so much @danelsuga ! I synced with Gorkem as well to provide feedback and he really loved your edits. Hopefully this should be finalized today for publishing.

**Comment by danelsuga** [comment]
Great!

**Comment by c0ric0ri** [comment]
Yes

[emergencyrelief.xyz/about](https://t.co/fBQ8Ux4X2J)
