### ISSUE TITLE
Tweet about Panvala leader board results

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1237]
Here's a Giveth Chapter leaderboard with results from the last distribution. Would be cool to share in a tweet!

![image.png](https://images.zenhubusercontent.com/62950e99b3c411288e6df660/ab4db194-c00f-420b-b975-3830a08025f9)

**Comment by c0ric0ri** [comment]
@laurenluz might be good content to create quickly to schedule this week?

**Comment by laurenluz** [comment]
sure @c0ric0ri - but I'd either need someone to draft it, or I would need more context (link, what this means, etc.)

I have an idea, but am not sure.
