### ISSUE TITLE
Tweet Thread for Verified projects dedictated to ETHDenver

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1239]
Based on the discussion from the last comms call, I am creating a thread with verified projects from Denver.

**Comment by NikolaCreatrix** [comment]
Holala, I'm somehow getting better with the amount of time this task consumes from me @laurenluz 

Alrighty, this is the final draft for review. I hope it doesn't need much editing, I was a bit brain-dead at the end, lol.

maybe we can also link it somehow to the galactic impact quest for another option on how to make a difference in Denver...

https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by laurenluz** [comment]
This is sooo good. I scheduled it for tomorrow morning ❤️

**Comment by laurenluz** [comment]
Alsio AMAZING to hear that this is getting better for you!! I love the threads you create @NikolaCreatrix <3

**Comment by NikolaCreatrix** [comment]
Aww, thanks Lauren, it seems to have some engagement already! So cool!

https://twitter.com/Givethio/status/1629904638093799425

Closing this issue. ;)
