### ISSUE TITLE
Panvala League Coalition - Create mission, vision, intention

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#124]
Panvala League Coalition - Create mission, vision, intention before money is in the pot. Magenta, Dani & Ashley to hack on this. Deadline coming up in a few days.

**Comment by ForestSoleil** [comment]
3/5 Marketing update:
- Deadline is today, Friday March 5th
- Already announced that we are 1 of 3 new coalitions. They expect us to be ready for this grant round. 
- Actions: Ashley to create multisig on xDAI chain that money can be put into. Ashley to write copy description.

**Comment by WhyldWanderer** [comment]
I have created a Gnosis multisig on xDai
I will create an outline for the mission, vision, intention in the next few days and will post link here for the working document.

**Comment by WhyldWanderer** [comment]
Vision, Mission, Values can be found here
https://docs.google.com/document/d/1FEFWfFMTPGo_0uN4s0YGNnX-nDR3mAhEgALcx3_Obrk/edit?usp=sharing
