### ISSUE TITLE
Facebook / Instagram account linking - issue for Facebook features

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#1244]
I'm getting this 'alert' on Facebook account, (which might explain why I've not been able to create carousels in Facebook through Planable).

![image.png](https://images.zenhubusercontent.com/6228be80d06a422295d2247f/e1718883-48e5-40d9-b62c-5e33bc653a20)

It's just an admin thing - it does not mean that posts will feed through from Facebook to Instagram.
However, I think we should consider selected posts going to Instagram - they can be autoposted and scheduled in the same way as Facebook and LinkedIn. The only time consuming part is sometimes linking/finding the social handles and making the connections.

**Comment by clara-zi** [comment]
@c0ric0ri @laurenluz @oyealmond - do you have login deets for Instagram, so I can resolve this issue? (obvs not urgent - could wait until the other side of ETH Denver).

**Comment by clara-zi** [comment]
I don't think we have anyone taking care of our Instagram: getting notifications like these. I don't have access to respond.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/100724132/221891674-0f36e25d-2da1-471d-8f9e-17b20f34f569.png">

**Comment by laurenluz** [comment]
@oyealmond and I have access to the Instagram, and she's been doing some work on it to breate more life in. I think it's ok if we cross-post sometimes to facebook 🤔 

Talk with Almond or maybe we can discuss in our comms call on tuesday.
