### ISSUE TITLE
Add Giveth Referral Program to Docs

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1249]

**Comment by ahmadabugosh** [comment]
Hey @franculio, can you work on adding a section on the Docs for the Giveth Referral Program? Maybe starting with a Google doc draft we can comment on? 

You can find all details here: 

1) Landing page on Giveth https://giveth.io/referral 
2) Chainvine Page https://app.chainvine.xyz/giveth
3) Video Explainer https://youtu.be/02C9KcRNgP0

**Comment by franculio** [comment]
Hey @ahmadabugosh. Here's a draft for the Chainvine doc https://docs.google.com/document/d/1TWhUVxwUVLTLhUxp7iCNt7mBwmKjcubtSrrybAeRDEM/edit?usp=sharing

Maybe @danelsuga when you have time you could give it a look?

**Comment by danelsuga** [comment]
@franculio I've had a look. Thanks! I have some pretty serious questions at the end! :D

**Comment by franculio** [comment]
Thank you @danelsuga! About those last questions I have the same doubt, maybe @ahmadabugosh can clarify better since he added those two last paragraphs.

**Comment by franculio** [comment]
The doc file is ready to be uploaded whenever. @c0ric0ri let me know when I should push the button

**Comment by ahmadabugosh** [comment]
hey @franculio, I say go for it, just make sure the url is the one we talked about earlier: https://docs.giveth.io/giveconomy/referral

**Comment by ahmadabugosh** [comment]
Looks good, thanks @franculio !

Can you also add the infographic that Rodri made to the "How Rewards Work" section? https://github.com/Giveth/giveth-planning/issues/1297

**Comment by laurenluz** [comment]
I added it
