### ISSUE TITLE
Finalize Referral Reward Process with GIVbacks program

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1250]

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh this is finalized now, right? 

10% of the GIVbacks will go to the referrer, and the other 90% will go to the donor. Is that correct?

**Comment by c0ric0ri** [comment]
@ahmadabugosh can you confirm that this is correct for rewards issued from referrals?

- New donors/users: 50% of the GIVbacks go to the referrer, other 50% goes to the new donor. This stays for all donations during the first 2 GIVbacks rounds
- Existing donors/users: 50% of the GIVbacks go to the referrer, other 50% goes to the existing donor. This applies for all donations within the first 24 hour period from the first donation

**Comment by ahmadabugosh** [comment]
Yes, although I would clarify for the second point, it isn't their first donation, but 24 hours from when they click the referral link, so it would be "Existing donors/users: 50% of the GIVbacks go to the referrer, other 50% goes to the existing donor. This applies for all donations within the first 24 hour period from returning users clicking on a referral link."
