### ISSUE TITLE
Create Chainvine Blogpost - March 29

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1252]

**Comment by danelsuga** [comment]
https://docs.google.com/document/d/1HIeHowGsWJVaTXL5D3nNMOIks5fQLBWJOBde7fGfobo/edit?usp=sharing

**Comment by ahmadabugosh** [comment]
Hey @danelsuga, one more thing to add to the blog post that would make it interesting would be the fact that this is the first time that projects can earn GIVbacks. Typically, we don't allow projects to earn GIVbacks since we block projects from donating to other projects on Giveth (since some people might game the system that way). 

However, with the referral program now projects can encourage their audience to donate with their referral link and they can earn a portion of that user's GIVbacks. This essentially is another "donation game" and way to create incentives for both projects and donors to raise money for good causes. This also creates the opportunity to  "donate" to 2 projects at once and support a project financially without donating to them directly (if you use a project's referral link they get a portion of your GIVbacks if you donate to another project).

**Comment by c0ric0ri** [comment]
Hey @rodricastillo9013 could you support us here with a cool banner for this blog post?

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri why not just use the existing one we have? (the one we have as a header here: https://giveth.io/referral)

**Comment by danelsuga** [comment]
That's what I was thinking. That's why I didn't already request one.

**Comment by ahmadabugosh** [comment]
@danelsuga maybe Cori meant the graphic you have in the middle of the blogpost (the infographic)? I think that would be useful if @rodricastillo9013 has the time

**Comment by danelsuga** [comment]
I don't think she meant that. In any case, Rodri is already on it! We're hashing it out. 😁

**Comment by danelsuga** [comment]
issue for banner: https://github.com/Giveth/giveth-planning/issues/1297

**Comment by ahmadabugosh** [comment]
Wow looks great @rodricastillo9013!
 
@danelsuga for the middle point could we simplify it to"Your network donates to any verified Giveth project through your link." ?

For the last point, should we add a short explanation of what GIVbacks are? So for example, like this: "For each donation made through your link, you and the donor receive GIVbacks (GIV token rewards)."

**Comment by ahmadabugosh** [comment]
Also for the graphic on the left under where it says "Share your unique URL", we need a new screenshot, since we removed the "Your Rewards (USD)" section from the Chainvine landing page. 
<img width="736" alt="Screenshot 2023-03-28 at 6 35 51 PM" src="https://user-images.githubusercontent.com/4855928/228273357-4c54fc7a-4996-4b04-9f43-6816b278a51e.png">

**Comment by rodricastillo9013** [comment]
![image](https://user-images.githubusercontent.com/61791380/228279248-90c994ed-1cac-47c7-a0d3-733fa411167f.png)
@ahmadabugosh wdyt?

**Comment by danelsuga** [comment]
Could this line maybe be emphasized? What do you's think?

Also, put a period at the end of the second and third purple bubbles (you've already got one in the first). 
![image](https://user-images.githubusercontent.com/81351744/228283815-747b61e2-4afa-4da7-8d63-87e816ffd448.jpeg)

**Comment by laurenluz** [comment]
I don't want to make this too many cooks - it is fine imo as it is.

If i'm being picky:
- copy on the last bubble... we can delete the first bit... so it says "You and donor both receive GIVbacks (GIV token rewards)."
- and the duplicated GIVbacks at the bottom was hard for me to understand on 1st glance. maybe we remove "GIVbacks" and just have the token image?

These are just suggestions, take it or leave it. @ahmadabugosh - you're the boss

**Comment by danelsuga** [comment]
I actually disagree with both of Lauren's suggestions.

**Comment by danelsuga** [comment]
Note that this is not the first iteration Rodri created. I had the idea for the need of an infographic, and Rodri developed something based on my (hilariously terrible) sketch. Then we discussed a couple versions he made based on that. This iteration seemed great and ready to share for input. Thank you @rodricastillo9013!

**Comment by danelsuga** [comment]
I think there's some confusion? Banner is great. Infographic is great. (Maybe change the purple like you said.)

**Comment by danelsuga** [comment]
updated from rodri!
![image-1](https://user-images.githubusercontent.com/81351744/228490019-ddd3fe35-21ef-4e0f-a129-2ded848e5e5c.png)

**Comment by danelsuga** [comment]
updated from rodri!

![image-2](https://user-images.githubusercontent.com/81351744/228494742-b03fc01e-ea92-4dd1-92ea-b0f9e3565a21.png)

**Comment by ahmadabugosh** [comment]
@danelsuga love it!

**Comment by c0ric0ri** [comment]
Nice! Much easier to read!

**Comment by danelsuga** [comment]
The step by step was based on language and explanations that have been modified as of late. I will update that.

**Comment by danelsuga** [comment]
Updated the post and ended up including several examples after hashing out ideas with @ahmadabugosh this morning, thinking it's good to show how it works since it seems a bit confusing. [Check it out](https://docs.google.com/document/d/1HIeHowGsWJVaTXL5D3nNMOIks5fQLBWJOBde7fGfobo/edit?usp=sharing) @laurenluz and [here it is](https://medium.com/p/a701db72b5cb/edit
) on Medium too.

**Comment by danelsuga** [comment]
(@laurenluz think maybe you can't use the medium link but no worries. same draft as docs plus emojis. :P)

**Comment by c0ric0ri** [comment]
Hey @danelsuga I've left some comments here. I think examples are good, but could be reduced for simplicity and added to the docs - with maybe just the first one referenced in the article.

Ideally let's use the article to promote and excite people about the program, and keep the docs for the more granular details.

Also the step-by-step can be simplified a bit more, i added suggestions. Let me know what you think.

**Comment by danelsuga** [comment]
ok! incorporated all changes! do you want to doublecheck? when do i publish? thaaaaanks!
@c0ric0ri @laurenluz

**Comment by laurenluz** [comment]
@danelsuga - can you just submit it to the publication w/o publishing? I will publish it when it's ready to announce (might be v. soon)

**Comment by laurenluz** [comment]
https://medium.com/giveth/giveth-referral-program-a701db72b5cb
