### ISSUE TITLE
Create Onboarding Landing Page

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1254]

**Comment by ahmadabugosh** [comment]
We want to create a page for users under the **Easy Onboarding** section of our homepage
<img width="575" alt="Screenshot 2023-03-07 at 7 13 46 PM" src="https://user-images.githubusercontent.com/4855928/223464205-2f09b73e-03b4-4cd0-8d9e-53da2575b6fc.png">

I created a draft of this page here: https://docs.google.com/document/d/101QsSCJNaw_JyOKmBG_RExZakDkolLZXUEc3XFgFeOI/edit#

**Comment by danelsuga** [comment]
@danelsuga

**Comment by clara-zi** [comment]
@clara-zi

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh @clara-zi @danelsuga what is going on with this issue, do we still need this open?

**Comment by ahmadabugosh** [comment]
@c0ric0ri yes, it needs content review! @danelsuga 

Once we're good with the content, I'll follow up to design the page and then get it live.

**Comment by danelsuga** [comment]
Check out some suggestions, @ahmadabugosh.

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh i added in a bunch of content here. I think this page still needs flushing out before it's ready to go live.

Would love @laurenluz to take a look, @clara-zi @WhyldWanderer & @NikolaCreatrix from an onboarding perspective as well

**Comment by laurenluz** [comment]
love your edits @c0ric0ri, and thanks @ahmadabugosh for starting this out. I added some more feedback in there, and added some content around "What is GIV and how can you use it?" I think the sections might need some rearranging now though....

I feel like the section after the "zero fees, transparency" bullets is not quite there yet.

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh it would be great to make progress on this. Can you accept the reviews and let us know what's still needed?

**Comment by ahmadabugosh** [comment]
hey @c0ric0ri @danelsuga @laurenluz , I cleaned this up and incorporated all of your feedback (as much as I could!) Let me know if you have any comments on this next version: https://blog.giveth.io/evolving-nonprofits-into-regen-economies-f8282f97f8d3

**Comment by laurenluz** [comment]
had a quick look, looks good. might be too much text overall for a page, so you might need to work a little w/ our designers on it, but I think it's a perfect jumping off point for that.

**Comment by NikolaCreatrix** [comment]
I just had a look as well and my only comment is related to the Verified projects... check it out. ;)

**Comment by ahmadabugosh** [comment]
Thanks team!

@mosaeedi @MoeNick can we start designing this page?

**Comment by danelsuga** [comment]
back from vacation and just left some comments (and typo, etc. corrections).

**Comment by oyealmond** [comment]
https://giveth.io/onboarding
