### ISSUE TITLE
Banner for ETHDen 2023 Medium article

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#1259]
Hi @mosaeedi and @Tosinolawale 

Could I please get a banner for a forthcoming piece on ETHDen 23 please? I think something like the banner from @rodricastillo9013 for the site would be fine (if the subtitle was changed or removed) ([issue 1126](https://github.com/Giveth/giveth-planning/issues/1226)).

Thanks!

**Comment by Tosinolawale** [comment]
![Event banner](https://user-images.githubusercontent.com/35389241/224059513-eee41c5d-d54c-4186-a2dc-e3ce1b8f9114.png)
Will this do?
 @danelsuga

**Comment by danelsuga** [comment]
Thanks! Looks good to me.
