### ISSUE TITLE
FLII social media post

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#1260]
Hi,
@Cotabe @brichis - it would be great to have some info and a pic/vid from FLII for social media: Twitter & FB/LI.

**Comment by Cotabe** [comment]
Hey @clara-zi

Here is the summary of our results at FLII: https://www.notion.so/FLII-results-1cd51d832d714192a4f18e07afd4e711

Here are pics and videos: https://drive.google.com/drive/folders/10t0Te7zBfxl890ZlUNV4FElMXtGv6aW0?usp=share_link

Both are still in progress and more will be added.

**Comment by laurenluz** [comment]
this was a long time ago now.. is there any reason we should still post something? or was it done already? @clara-zi 

would like to close the issue.

**Comment by clara-zi** [comment]
sorry, meant to close this.
