### ISSUE TITLE
Threads to promote PFP allowlist & Twitter Space. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1261]
Hello @laurenluz ! 

[I made some Twitter threads drafts ](https://docs.google.com/document/d/1iEjOV-oVDEamyuftya3qP5lvQDabv640E6CzWChZYHA/edit)to build hype around Giveth's PFP collection, promote the allowlist and the upcoming Twitter Space. 

Could you help me check them out & schedule please? 

thank you!

**Comment by laurenluz** [comment]
both posted
