### ISSUE TITLE
Twitter Space: Giveth's PFP collection launch 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1262]
Hey team! 

[Here you'll find the script](https://docs.google.com/document/d/1y-LFpxK5pBx1H1cwBe-rz2_Fhp_g8o_fhzFhnDWtg_U/edit) for our next week GIVtalk. 

check it out and share your feedback @Santigs @divine-comedian. 

@laurenluz, I added here a tweet draft promoting the Space 1 hr before. 
Could you help me review & schedule?

**Comment by laurenluz** [comment]
https://twitter.com/i/spaces/1djxXlAqAvOxZ
