### ISSUE TITLE
DAOdrops email

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1263]
DAOdrops voting is open - we should email our audience with it.

Here is the content: https://daodrops.io/

@danelsuga can draft it!

@ahmadabugosh or @WhyldWanderer - can you help coordinate the best day to get this out? DAOdrops voting period goes until Friday March 24

**Comment by danelsuga** [comment]
Anything more than this? 

https://docs.google.com/document/d/1hb_9hBhqWfkC6tTEDMlUik_PGbK75RLNWwR5vdRABl4/edit?usp=sharing

**Comment by danelsuga** [comment]
ready for some eyes and send!

@laurenluz 
@ahmadabugosh 
@c0ric0ri 
@WhyldWanderer

**Comment by laurenluz** [comment]
Looks good @danelsuga! I made some comments and small fixes. Give me a day to see if I can get that tweet thread out so we could link it in there.

**Comment by laurenluz** [comment]
@danelsuga - today, I posted the tweet thread for optimism... it doesnt say everything we did, and I was planning to make another for dao drops... but we could link this and get the email out sooner.

I already added to the doc, and it's here: https://twitter.com/Givethio/status/1636076322492383232

If that sounds good to you, it might be better to get this out sooner rather than later - maybe you can help coordinate it?
