### ISSUE TITLE
Revise copy on Chainvine site

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1264]
Hey @ahmadabugosh - I find some of the copy in here to be confusing, would love to make some suggestions that we can send through.

https://app.chainvine.xyz/giveth?referrer_id=TLH10fqFuegu3mKO2b48wrrFh532

**Comment by laurenluz** [comment]
Thanks @ahmadabugosh - I made some comments and suggestions in the doc.

I hear you on 1.
Re: 2. Check out my comment at the bottom there. We can just say up to 8% & 72% for numbers... but we should be careful not to say "8% of the donation amount" because it sounds like we are skimming off the donation to give to the referrer... we should be really careful not to make it seem like that's happening.

**Comment by laurenluz** [comment]
Also! This banner needs to change!!


We should delete "GIVferral Reward Program" from the graphic (because it is not the final title, and the title is redundant on the page there).

So:

![image](https://user-images.githubusercontent.com/75490971/224846743-1daa3830-8743-46d7-bb85-fa765ae845e1.png)

**Comment by laurenluz** [comment]
@CarlosQ96 just FYI on here

**Comment by ahmadabugosh** [comment]
I submitted these changes to the Chainvine team to update our page.

**Comment by ahmadabugosh** [comment]
Hey @laurenluz @danelsuga, All these changes were implemented on https://app.chainvine.xyz/giveth . Let me know if we can close this issue or if you have other comments.

**Comment by c0ric0ri** [comment]
hey @ahmadabugosh also pointing out that the font sizing / bold is missing which makes this text look very....bland.

"How it works" is the same size as everything else, also the titles "First time donors on Giveth" and "Earn even more rewards". Can we make them stand out like they do in the Google Doc version?

Also - the emojis honestly don't look great in the app. I would maybe just keep both with a blue heart. It almost looks like a typo with the two emojis next to "Earn even more rewards."

<img width="602" alt="Screen Shot 2023-03-27 at 10 42 03 PM" src="https://user-images.githubusercontent.com/106524383/228130315-e3dac03d-4dbf-44ef-9756-e1ee4181dbd7.png">

**Comment by ahmadabugosh** [comment]
@c0ric0ri The thing is, their text editor doesn't allow any different text styles like bold or larger font sizes, so we need to work with what we have. 

If you have suggestions to make it look better based on that constraint (that there is only one font for the entire doc) let me know (that's why I used emojis that ay).

**Comment by c0ric0ri** [comment]
Ok understood! left a couple comments in the doc @ahmadabugosh

**Comment by laurenluz** [comment]
I don't think it is worth the coordination time and effort for Ahmad to ask the chainvine team to change a couple of emojis and add a colon. The coordination effort vs. the impact of these changes doesn't balance out

**Comment by laurenluz** [comment]
Chatted with @c0ric0ri about this today - I don't think it's worth the coordination effort to get chainvine just to change emojis... but Cori also brought up a great point.

The "start" button for people actually to donate is kind of hidden below this wall of text. @ahmadabugosh is there any way to work with them so that we could add a big "START DONATING" somewhere at the top that is automatically a link to giveth? then the person who clicked a referral link actually has a greater chance of actually executing on the donation.

**Comment by c0ric0ri** [comment]
Thank you Lauren. Yes ideally we reduce the friction as much as possible, so when someone clicks on a referral link it is immediately obvious to them on the page to continue directly to our project page (not our home page).

The start button is quite small, if chainvine's formatting allows it would be great to make it more obvious in addition to moving it to the top.

Then below that, we can keep the explainer text.

**Comment by c0ric0ri** [comment]
We are working on removing this page from the process, right? Does it still make any sense to put more effort in this if that's the case? Just checking before pursuing. 

@ahmadabugosh @laurenluz

**Comment by laurenluz** [comment]
yeah, we're changing the UX so the start button changes suggested here aren't relevant anymore.

**Comment by c0ric0ri** [comment]
Ok then @ahmadabugosh I would suggest to close this issue if there's no objections to it, as we'll be changing the UX to move past this page

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri , I think we should wait because once we move the "Start" step from the flow, Donors won't have to visit Chainvine (they'll be taken directly to the Giveth site), which means that the Chainvine site will only be used for people that want to generate a referral link, which means that we can simplify that landing page and only have it talk about how Referrers can generate a link. 

I simplified the [copy here](https://docs.google.com/document/d/1ToM7dG_jtzwcdC6vokROk876EbJDujfv_gxMZCKNIf0/edit#), however I think we still need to add a section on updating the project link (it's a feature they said they would add to the page). I'll edit this copy once that part is done.
