### ISSUE TITLE
Polygon intergtation Tweet Thread announcement - March 16 or 17

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1265]

**Comment by laurenluz** [comment]
so we integrated polygon, now you can donate on polygon
project owners will need to add a new address for that chain

if people love this and use it a lot, we will think about adding givbacks on to polygon maybe? check w/ @GriffGreen

**Comment by laurenluz** [comment]
or check w/ @spectoregia on what our future plans are w/ them

**Comment by c0ric0ri** [comment]
Notes for drafting:

now you can donate to projects on Polygon chain

check with Yass what the agreement was to keep building on this with next grant

projects will need to add a new address if they want to recieve donations in Polygon

GIVbacks eligible - but you receive GIV on Gnosis chain (fact check with MoeNick)

**Comment by laurenluz** [comment]
@c0ric0ri we need this for tomorrow and there are some details, I'm going to take it now

**Comment by laurenluz** [comment]
https://docs.google.com/document/d/1DQ05nOfMDveEiuISn7vGWI-j3DmN8_mRrDnw3MWo0f0/edit
