### ISSUE TITLE
FIAT integration announcement tweet thread - April 30

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1267]

**Comment by laurenluz** [comment]
We will go live w/ Mt pellegrin 1st... and then add the onramper intrgreation later.

Whoever takes this should work with @mateodaza to get all the accurate info for the tweet thread

**Comment by c0ric0ri** [comment]
As more Mt Pelegrin testing needs to happen before this is ready to launch, I will move this to Backlog and change date to April

**Comment by laurenluz** [comment]
We will be commenting this out of the dApp because it failed testing
