### ISSUE TITLE
Earthquake QF tweet thread - March 14

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1268]
Create tweet thread to push for last donations by March 20th!

Include recent stats, inverter article, GIVbacks reminder, and amount we’ve already raised and where we’re trying to get to (25k).

**Comment by c0ric0ri** [comment]
Draft is here for review @laurenluz 

https://docs.google.com/document/d/1MpJqYgAod8Pz2TCuBe479UCJOhLCMfvOmXM2Z6O5WU0/edit

**Comment by laurenluz** [comment]
awesome Cori! I made some small tweaks and scheduled for tomorrow - thank you

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1635627343380115459?s=20
