### ISSUE TITLE
Discussion: Giveth TRACE - should we change "Milestone" to "Projects"? How can we facilitate consistency across DApps and/or transition of projects from giveth.io to TRACE?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#127]
Open questions from Dev1 call 2021-03-08 (from @markoprljic):

- How do we approach renaming Milestones to Projects? Or do we rename Campaign to Project? (in the new milestone creation flow there are 4 options)
- How do we convert a Project on Giveth.io to Giveth Trace? Is it a Campaign or a Community? Do we even want to offer user to convert, or do we just advertise Giveth Trace and let them go the standard route of creating either a Campaign or a Community? Can user upgrade from Campaign to Community on Giveth Trace?

This affects #101

**Comment by Danibelle** [comment]
1. How do we approach renaming Milestones to Projects?
Do not approach. Run away.

2. Or do we rename Campaign to Project?
Renaming anything on v1 is quite counterintuitive IMHO. A project is a temporary endeavor (in v2, it's just a request for money) that in v1 could be a Campaign with many Milestones or a single Milestone for a Campaign that does not have an end goal (like caring for a watershed or teaching children).
3. in the new milestone creation flow there are 4 options -- [link to issue referenced]
4. How do we convert a Project on Giveth.io to Giveth Trace? Is it a Campaign or a Community? Do we even want to offer user to convert, or do we just advertise Giveth Trace and let them go the standard route of creating either a Campaign or a Community?
I think we decided that we do not want to do this, that a user may need greater flexibility, scaling and/or fund control at which time they can choose to also create on TRACE.
**docs page on this needed**
5. Can user upgrade from Campaign to Community on Giveth Trace?
Yes, ideally a community is collaborative with multiple parties and projects, so a DAC can be created; then delegating funds from the DAC to the Campaign links them.

**Comment by GriffGreen** [comment]
Traces is the winner! It was decided in the Comms meeting today

**Comment by markoprljic** [comment]
Oh wow, that's nice :) Makes sense. How didn't we think of it earlier!? :D :D
