### ISSUE TITLE
DAO drops RPGF tweet thread - March 20

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1270]
could be together w/ the optimism thread

**Comment by laurenluz** [comment]
can use from #1269

**Comment by laurenluz** [comment]
https://docs.google.com/document/d/1UxZSfhdwjQ9w9fSqsY_NwFk_PltY8KzWUyr-UlCmk9c/edit

**Comment by c0ric0ri** [comment]
@laurenluz is this considered done? Can't access the file.

**Comment by laurenluz** [comment]
no

**Comment by laurenluz** [comment]
scheduled for tomorrow - This is a really good one and we should link it before we close the issue for sure.

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1638164082749571073
