### ISSUE TITLE
Scholarly article on regen - regenerative economics - for placement in reputable journal in the field

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#1274]
At the behest of a committee including @laurenluz @GriffGreen @c0ric0ri Gideon and @danelsuga, and with a preliminary interest in placing an article on regen econ in SSIR, Suga wrote an article that was eventually rejected by SSIR as not critical at its basis (in their rejection feedback, they cited their article "[Web3 and the Trap of 'For Good'](https://ssir.org/articles/entry/web3_and_the_trap_of_for_good)" as an example worth examining. The original issue was [#707](https://github.com/Giveth/giveth-planning/issues/707).

The article: https://docs.google.com/document/d/1y5Pek2vVavNL_J56sv-ZzgEbK6_vg_KnArojU0IDL8c/edit

We are now seeking publication elsewhere. Current good prospect is in [The Chronicle of Philanthropy](https://www.philanthropy.com/).

**Comment by danelsuga** [comment]
I am waiting to hear back from Philanthropy Daily. I recontacted them yesterday about it.

**Comment by oyealmond** [comment]
hey @danelsuga! 
How is this looking?

**Comment by danelsuga** [comment]
Following up with a journal again on this.

**Comment by oyealmond** [comment]
hey @danelsuga ! 
Should we move this to icebox? 
Do you have any updates?

**Comment by danelsuga** [comment]
I have pinged a journal just today for a follow up.

**Comment by laurenluz** [comment]
did this never get posted? I think @danelsuga at this point it would be great to just publish at least in medium & we can do a bit of marketing around it.

**Comment by danelsuga** [comment]
No, I did not hear back from most of the journals in the end. I'll publish it on Medium asap.
