### ISSUE TITLE
April Fools' Landing Page

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1276]
Hey team,

I thought about a funny idea for a tongue-in-cheek landing page we can launch on April 1st:

https://docs.google.com/document/d/1b4R6TCnpCM3SxYcOFLMm3mkhTIwjC17wOmDK5WXPct8/edit?usp=sharing

Let me know if you think this is a good idea 😄

@laurenluz @danelsuga @c0ric0ri

**Comment by danelsuga** [comment]
Bwah ahah!!! 🤣

**Comment by laurenluz** [comment]
this is sssooooooo funnny I love it omg - thank you Ahmad for making my day so much lighter.

Let's do it! I think we can tweak it an make it a little shorter in some parts.. and we should talk to @MoeNick about it.

or maaaybe - we can make this a separate page... like giveth.io/taketh... and then just update it and tweet it etc? so it's not actually replacing the existing giveth.io, but still good for a nice laugh.

**Comment by ahmadabugosh** [comment]
@laurenluz hahaha yess, glad my dad humor made you laugh! 

Maybe we can even get @rodricastillo9013 to spin up a simple Taketh logo?

**Comment by c0ric0ri** [comment]
omg @ahmadabugosh this is brilliant, I am seriously impressed. love the edits also @laurenluz 

I agree with the landing page idea to tweet out for the day on our socials!

**Comment by c0ric0ri** [comment]
@ahmadabugosh can I assign this to you?

**Comment by ahmadabugosh** [comment]
@mosaeedi Can you start working on this? 😄

**Comment by c0ric0ri** [comment]
Timeline:

- Design by end of this week
- Launch by March 31 latest

Consider a disclaimer footnote that clarifies this whole thing is a joke, but we do love donations (link). Something like that

**Comment by danelsuga** [comment]
It is typical in many countries (Italy, Belgium, France and French-speaking countries, Switzerland, Canada, Nordic countries and of course many others around the world) to publish false news for fun on April 1. 

In addition, for all of the French-speaking countries (as well as Italy apparently and possibly others I don't know about) the FISH is the symbol for the day of pranks. In fact, children at school will tape a fish on the back of one another as a joke, so often times for funny media stories, a fish will be present to indicate in a kind of subtle way that the story is a joke. 

I recommend we place fish in some way on the landing page!

We could create a Giveth project that is collecting funds for fish "an ancient method to ward off bad luck at the start of spring" or something like that.

Or perhaps the project is collecting $fish --Giveth is soon rolling out fiat donations, so we're trying it out first by rolling out FISH donations! And what better time than the start of spring? Giveth is raising $fish for spring. Please donate...

(And the link to the project could simply go to the Giveth matching pool.)

**Comment by danelsuga** [comment]
Bwah ah ah @rodricastillo9013 should put a fish in the banner.

**Comment by danelsuga** [comment]
Also @mosaeedi I think we opted out of asking for private keys just in case. 

Right, crew? @ahmadabugosh @laurenluz @c0ric0ri @clara-zi @WhyldWanderer 

(Also, last sentence at end of page needs a period.)

**Comment by c0ric0ri** [comment]
Yes that's right @danelsuga.

@mosaeedi @ahmadabugosh can we make sure to change that line? We don't want people accidentally tweeting us their keys in case they miss the joke and are new to web3

**Comment by ahmadabugosh** [comment]
@c0ric0ri Done and this looks like it should be live soon (see the developer issue here): https://github.com/Giveth/giveth-dapps-v2/issues/2405
