### ISSUE TITLE
Project Survey Tweet Thread Announcing Winners - March 21

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1278]
Tweet Thread announcing winners

**Comment by c0ric0ri** [comment]
Hey @clara-zi, are you able to provide a draft for this by tomorrow still?

**Comment by clara-zi** [comment]
here is the vid for winners: 
https://www.loom.com/share/5ae402806e9449f5ad4c1bb2fc3791d9

**Comment by clara-zi** [comment]
ready for review @c0ric0ri @ahmadabugosh @laurenluz @danelsuga

**Comment by danelsuga** [comment]
looking good @clara-zi !

**Comment by clara-zi** [comment]
Can I please get another reviewer for this Tweet thread. Also adding the vid clip for winners spin-the-wheel @laurenluz @c0ric0ri @ahmadabugosh 

https://user-images.githubusercontent.com/100724132/228499359-663679be-2b76-4572-9c30-b25ea6a9a07f.mp4

Would be great if this could go out today or tomorrow.

**Comment by danelsuga** [comment]
So cool! (Heh heh, I already reviewed though. :D )

**Comment by laurenluz** [comment]
some issues in the thread here @clara-zi - can you check the comments?

**Comment by laurenluz** [comment]
I made some edits and scheduled it for today. edits are in the doc

**Comment by clara-zi** [comment]
Thanks 😊

**Comment by clara-zi** [comment]
Tweet went out Mar 30,  23

https://twitter.com/Giveth/status/1641455909133074432?s=20
