### ISSUE TITLE
Verified Projects thread R30, 31,32

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1280]
Hey @laurenluz you may be wondering where the regular thread is, but the truth is that only a couple of projects made it through the recent 2 rounds and so will make one again after the R32 is over.

**Comment by laurenluz** [comment]
Thanks @NikolaCreatrix !

**Comment by NikolaCreatrix** [comment]
Almost done, will review it one more time after giving break to my brain.
https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by laurenluz** [comment]
https://twitter.com/Giveth/status/1643224404283863041
