### ISSUE TITLE
PFP Allowlist & hype build

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1281]
We need at least:
 - [ ] weet for March 19 saying it's the last day to join the allowlist
 - [ ] Tweet for March 23 telling allowlist members about the premint party (or maybe we skip this?)

@oyealmond

**Comment by oyealmond** [comment]
Hey @laurenluz! 

[Created a couple of Tweets](https://docs.google.com/document/d/1i-lDy-NOU064OoIJJxlMM2rHrm1Gnl2Kpqxlxkjm86w/edit) to post these days. 

Let me know your thoughts. I can adjust them and/or make more

**Comment by laurenluz** [comment]
Amazing as always @oyealmond !! I made some small adjustments in tweethunters and they are all scheduled.
