### ISSUE TITLE
Swag shop tweet thread

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1283]
we added credit card payments + new designs
opportunity to shill nice

**Comment by oyealmond** [comment]
ey @laurenluz ! Found this issue. Do we still need this tweet thread? If yes, could you provide more guidance on this, or who can I ask for more info? Thanks!

**Comment by laurenluz** [comment]
the idea @oyealmond is to make a tweet thread telling people about our swag shop... saying that you can get cool swag from there. the thread can include some links to new/cool swag items w/ images, and it should also mention the payment methods:
1. you can pay with $nice. get $nice at a 1:1 ratio when you donate to the Giveth community of makers project on Giveth. you'll get it within 2 weeks (right in your wallet) when it is distributed along w/ GIVbacks. 
2. you can pay with a credit card

It's still relevant and would be nice for twitter. anyone who wants to can draft it, it's not too complicated.

tagging @SteffanThorn if he wants to grab it, or if he has other feedback.

**Comment by oyealmond** [comment]
cool! I made [this draft ](https://docs.google.com/document/d/1YNgYf_QRFy4ZSeq6sFG7XFYgtVXRrFIMQ3sTQx2yHkY/edit)

Could you check it out please @SteffanThorn @laurenluz ?

**Comment by oyealmond** [comment]
love the edits! @SteffanThorn ! Thanks :) 
I believe you can schedule whenever. you think's best.

**Comment by laurenluz** [comment]
Just had a read through as well, agree w/ @SteffanThorn 's edits and happy if @SteffanThorn can scheduled it too! Thanks team :)

**Comment by oyealmond** [comment]
hey team! :) 
Just checking this is schedules too @laurenluz @SteffanThorn

**Comment by laurenluz** [comment]
scheduled.

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1674765238137241600
