### ISSUE TITLE
Verified Project Updates Thread of Tweets - March 20 (latest 21)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1284]
@danelsuga or @c0ric0ri - can you take this one today?

Basically, last week we tweeted a verified project update every day... this week I want to make a thread of these tweets as a summary of all the updates.

I already wrote the intro/outros. What I need is for someone to find all those tweets, add the links to the doc... and write a sentence about each update (and tag the project) in each corresponding tweet.

https://docs.google.com/document/d/1Baz6j6eNXA_JZE6z58MeISLkZ2oCchvDCZprrMXFMMc/edit

**Comment by danelsuga** [comment]
I plugged them in. I will have to do the descriptions later though, if that's OK. (For now, they're mostly just copied from the Tweets.) @laurenluz

**Comment by laurenluz** [comment]
great!

**Comment by laurenluz** [comment]
Hey @danelsuga - thanks for this!

I edited it and scheduled the thread. For next time, please be mindful that tweets can't be more than 280 characters... and the links to the tweet should be at the very end of the tweet.

You can look in the doc to see how I changed it if you wish.

**Comment by danelsuga** [comment]
@laurenluz Didn't realize you were asking me to build tweets. Was just providing the info requested. No worries on changes.

**Comment by laurenluz** [comment]
yesss I was hoping you would write short tweet summaries w/ the links to the previous updates. but all good :)

**Comment by danelsuga** [comment]
😬

**Comment by laurenluz** [comment]
https://twitter.com/Giveth/status/1641048093268365314
