### ISSUE TITLE
Projects Page Update Tweet Thread - March 24

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1285]
We are implementing several updates to the individual project page and should tweet this out to our user base.

We should point out that the changes are based on direct feedback from users.

Updates include:
- Discussion tab
- Overview tab 
- & more

**Comment by mosaeedi** [comment]
Thanks, @c0ric0ri, for this issue!

We started to fix some issues and add discussions and project update comments. In the end, we came up with a new structure for the project details, public view, and owner view and also introduced some new elements to create a more intuitive user experience for project owners and donors.

# Project details

## Project details public view

### 1. The new project detail structure (Public view)
Here you can take a look
Without any donation or boosting-> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=134-72524&t=cU9n1CZKH3PwOA2H-4)
Donated and boosted project -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=135-73200&t=cU9n1CZKH3PwOA2H-4)


**Note:** We tried to make project detail more straightforward and effortless for donors to read and support a better space for the project banner. 

<img width="1015" alt="Screenshot 2023-04-05 at 11 09 25 AM" src="https://user-images.githubusercontent.com/13708322/230013723-b0a93551-4f22-402c-bdca-265422c27a62.png">




### 2. Separated tabs for managing Project story
Now the **"About"** section has a new sub-tab to divide information and make it easier for the project owners to share details about their project with donors.

**Note:** You can use the previous link at the top to view this on Figma.

<img width="1015" alt="Screenshot 2023-04-05 at 11 10 18 AM" src="https://user-images.githubusercontent.com/13708322/230013922-a0659a1c-3964-4a75-ada8-12cdbee47128.png">


### 3. Project update commenting

To make updates more interactive, we are going to let donors comment on the project updates.
Project updates tab -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=131-56930&t=cU9n1CZKH3PwOA2H-4)

Viewing an update comments -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=139-75601&t=cU9n1CZKH3PwOA2H-4)

Writing a comment -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=142-76976&t=cU9n1CZKH3PwOA2H-4)

<img width="771" alt="Screenshot 2023-04-05 at 11 15 56 AM" src="https://user-images.githubusercontent.com/13708322/230015181-c2dafa13-94b6-40bf-a956-326ed36be2e2.png">


### 4. Project discussion
Project discussion is the new tab that lets project owners and donors connect and ask/answer all types of questions regarding the project. 

Discussion tab -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=131-61412&t=cU9n1CZKH3PwOA2H-4)

<img width="890" alt="Screenshot 2023-04-05 at 11 19 18 AM" src="https://user-images.githubusercontent.com/13708322/230015962-3be78239-bdd5-4400-9bd7-4691552f5f84.png">




## Project details owner view

### 1. Better overview for project owners
Right now, we don't offer the owners a complete overview of the project, so we tried to make it easier for users to see all details about their project.

**Showing project stats in the owner view**
<img width="1016" alt="Screenshot 2023-04-05 at 11 21 06 AM" src="https://user-images.githubusercontent.com/13708322/230016430-83a14aa0-5533-4880-a884-a04e9394147d.png">

**And the project overview tab to show all available statistics**

<img width="1011" alt="Screenshot 2023-04-05 at 11 39 25 AM" src="https://user-images.githubusercontent.com/13708322/230021399-f7232860-eb9d-4824-897d-6ad6eaa53cf2.png">


### 2. More effortless flow for writing an update for project owners

We received a lot of complaints that indicate writing a project update is not an easy experience for project owners, so here is the new flow,
By going to the **update** tab on **project detail owner view**, users should tap on the **Write a new update** button to be able to open the editor in a **new tab** and write their updates without any distractions, 

<img width="1146" alt="Screenshot 2023-04-05 at 11 46 08 AM" src="https://user-images.githubusercontent.com/13708322/230022679-fa11d5c0-e80d-49ad-8e68-2eb003d81f32.png">


**and then the editor tab**
<img width="881" alt="Screenshot 2023-04-05 at 11 46 33 AM" src="https://user-images.githubusercontent.com/13708322/230022769-4ae06698-f1ae-4dee-b18a-2f97ee1b99a4.png">


(Owner view) update tab -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=230-52580&t=cU9n1CZKH3PwOA2H-4)


(Owner view) new update tab -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=231-51227&t=cU9n1CZKH3PwOA2H-4)





# Create/Edit project form

We introduced a lot of changes to the project details, public view, and owner view. Also, recently, we have faced a lot of challenges in saving new details for the project.
We made some changes to the Create/Edit project form to solve those issues while making it easier for users to create a project.

Create/edit project -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=406-51405&t=cU9n1CZKH3PwOA2H-4)
**Note:** On Figma, move to the right to see all tabs on this form.
