### ISSUE TITLE
Launch retrospective tweet thread - April 25

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1286]
We had a lot of recent launches, once we get mt pelerin out, we should make a thread of threads... saying that 

"At Giveth, we're always shipping! Last month we launched a bunch of epic things... here they all are:"

And make one tweet for each:
- polygon launch
- mt pelerin
- internationalization
- PFP
- homepage

What else? I might be missing something.

Whoever takes this should go through the giveth twitter, grab all the announcement tweets, and then compile a longer thread of threads. with one tweet per product launch.

**Comment by danelsuga** [comment]
https://docs.google.com/document/d/1xmOO3J000mC6lM6fuWi1qc1AQ0MqKRcsOQkR7YIAan8/edit?usp=sharing

**Comment by danelsuga** [comment]
@laurenluz check out the bottom of the doc too where I wonder if several other mentioned topics should be included (e.g., ReFiDAO/CS had a big announcement for 1st node applications today).

**Comment by danelsuga** [comment]
Thx! Ok, will rearrange @laurenluz! But we're waiting for fiat and referral, right? Both should be next week.

**Comment by laurenluz** [comment]
yep! so when those are posted, you can add them in and then we can schedule it after :)

**Comment by c0ric0ri** [comment]
Does this still need a review? Not sure what you've got planned @laurenluz so just checking

**Comment by danelsuga** [comment]
It's not finished @c0ric0ri. Waiting for fiat to launch.

**Comment by danelsuga** [comment]
@laurenluz so fiat is still off the table for the time being? do we hold on to this until it's ready?

**Comment by laurenluz** [comment]
yeah take fiat off, but this week we might launch optimism and celo - maybe we wait on those.

and we can add the regenfarms UI update to this thread as well.

**Comment by laurenluz** [comment]
sounds great Suga.
Tomorrow I'll put out a thread announcing Giveth in Catalan.
And monday we'll have Celo announcement.

Then we can finish this off and post it like next week Wed? April 26?

Can you have it ready by Tuesday with all the final links in there.

**Comment by danelsuga** [comment]
so we're adding tweets in this thread for:
RegenFarms UI updates
Giveth in Catalan
Celo integration

What about Optimism integration?

Also, I can't find a tweet for RegenFarms UI updates.

**Comment by laurenluz** [comment]
yep! that's regen farms.

Giveth in Catalan will post on Monday so let's include that one. Here's my [draft](https://docs.google.com/document/d/1gufs07Hi_wJCTJAKUIfIhRccapoI2nOXVEvlAiFZj_k/edit?usp=sharing)

Celo is delayed, we can skip it for this one.

Optimism will launch in about 2 weeks, so let's skip it for this one. We can do another thread later with it.

**Comment by laurenluz** [comment]
@danelsuga - nice job! I made some edits, can you review them and take note for next time? Some tips:
- use line breaks between short sentences because it's easier to read
- find the twitter handles of people you mention and include them
- remember a closing tweet

**Comment by danelsuga** [comment]
Yeah! Thanks. Oh gosh. Sorry about those points, and thank you for the reminders! Of course! 😳☺️😊 Thank you.
