### ISSUE TITLE
Email to our PR database that minting in live

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1287]
To go out on the 24th of March to let our PR database know that public minting is now live!

**Comment by danelsuga** [comment]
looking good @oyealmond !

**Comment by c0ric0ri** [comment]
@oyealmond sure but I'm not able to leave comments, can you open access please?

**Comment by c0ric0ri** [comment]
Added in some suggestions. This is looking awesome @oyealmond !

**Comment by oyealmond** [comment]
thank you @c0ric0ri! Answered some of your suggestions and made some edits. Thank you! 

@ahmadabugosh do you think you could give a last check and help me scheduled?

**Comment by ahmadabugosh** [comment]
Done! This is loaded up and schedule to send the email to the PR database (including the extra emails you sent me) at 11am central time.
