### ISSUE TITLE
Feedback quick poll on auto-confirm emails upon sign-up

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#1290]
We already have automated emails sent to: 
- confirm sign-up to the platform
- confirm when projects go live
- confirm when projects make an update
- confirm verification

Wouldn't it be great if we could add a quick pop-up simple poll - asking if it the process was easy/good or difficult / bad?

**Comment by clara-zi** [comment]
wdyt? @ahmadabugosh @c0ric0ri @NikolaCreatrix @WhyldWanderer @laurenluz 
I have no idea if this is easily possible or how much work would be involved?

**Comment by ahmadabugosh** [comment]
Hey @clara-zi, 
1) For simple things like just signing up, I don't think it makes sense to send them a survey or poll, but maybe we could send one after a first donation is made, or after a project goes live or gets verified. 
2)  I think this could also be tied to the onboarding flow issue when sending emails https://github.com/giveth/giveth-planning/issues/1253 
3) Another thought, should we look to have a live chat type feature so those kind of messages would be on the websites directly?
