### ISSUE TITLE
Schedule campaigns for featured projects on homepage

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1291]
We have a designated space on the new homepage to feature a specific theme of projects that we want to create campaigns around.

The dev team needs to know in advance what the next campaigns are, so we should create a schedule of fresh campaigns for the next 6 months, and then make sure it's updated accordingly by comms in Adminbro.

- [x] Create notion doc to outline campaign schedule
- [ ] Agree on campaigns for the next 6 months
- [ ] Make sure a few comms contributors are comfortable using adminbro
- [x] Update to next campaign by April 5

**Comment by c0ric0ri** [comment]
Created a [notion page here](https://www.notion.so/giveth/Homepage-Content-Updates-7551d8e2084b4ee19120b099f59846ea#ec8efb8f4d994b0ba869cd14d0f8ccb2) to organize our campaigns.

Would love to get input on topics for the next 4-6 months, can we brainstorm here @WhyldWanderer @NikolaCreatrix as you've got a great overview of our projects?

**Comment by NikolaCreatrix** [comment]
Heyy @c0ric0ri just got to this. 
Yes we can start with Earth Day theme for the next campaign. It'll be great to feature the projects that are be invited to MTM...

How many projects do you imagine to fit into the 'featured'?

I suggest we just start with featuring themes according to the categories in the filter on the platform. - then it's easy to select those projects under a certain category and you don't even need me or Ashley to be able to do this... just the amount of projects under different categories will vary...logically.

I can prepare the ones for Earth Day this week no prob, just need to know how you want this to look... shall paste them in the notion, or?!

**Comment by WhyldWanderer** [comment]
I have the same question as Nikola.. how many projects is a good number to feature in this campaign?

This will be for a manually selected campaign correct? Here?
![image](https://user-images.githubusercontent.com/74267818/228302228-1b52e386-979b-42c4-b8f4-13f6de83910a.png)

What should our hashtag be? #GIVearth? #NatureGIVes? idk.. im not very good at this haha

-------------------------------------------------------------------------------------
It would be cool to be able to feature it in the lower section as well and have it link to the projects page with categories selected.. maybe this link? https://giveth.io/projects/nature

--------------------------------------------------------------------------------------
I will add some ideas to the Notion doc... can we make space for more than one idea? That way more people can brainstorm in there and we can choose the one we like best?

-------------------------------------------------------------------------------------
- Working on getting the comms team people access... just waiting on the role and VPN accounts to be created by @mohammadranjbarz  - I have sent a DM to you Mohammad with the user information for those who need "campaignManager" role in Adminbro as well as VPN access.
Once people have access, I would be happy to jump on a call with anyone who doesnt feel comfortable to walk them through the steps once more.

-----------------------------------------------------------------------------------

**Comment by c0ric0ri** [comment]
Wrote a comment in the other issue. Do we need two issues on this by the way? Seems confusing. The idea was to organize via this issue and use Notion to compile the info. I feel like I have to respond in 2 issues this way....

12-15 project featured on the homepage, should be about 5 scrolls max. Then it links to a project page that is filtered by the Nature category. I like your suggestion @NikolaCreatrix , makes sense.

We need a title and a hashtag. I actually like #NatureGIVes! haha. We can write them in the Notion. I wrote a title suggestion there. Feel free to create more space if needed, otherwise we can just list multiple options per box and highlight the chosen one.

@WhyldWanderer I know we featured the Syria / Turkey earthquake campaign in the What's up on Giveth section, but I'm not really sure why to be honest. It feels like overkill when the section directly above promotes that in a much bigger way. I would keep the two sections for separate purposes. The Meet the Makers section would be more relevant for example.

**Comment by WhyldWanderer** [comment]
The Earth Day campaign is now live!
Nikola and I had fun choosing projects <3

We have yet to add the new Whats up on Giveth part - still waiting for designs.

**Comment by c0ric0ri** [comment]
Great @WhyldWanderer @NikolaCreatrix ! So next up, would be awesome if we choose topics for the next upcoming months. That way we can plan ahead a bit with a schedule. 

Any ideas for May, June, July based on the projects we have right now? Perhaps we start with a different category per month?

**Comment by WhyldWanderer** [comment]
I put a couple things in the notion... 

I think we can always use the SDG Goals or one of our project categories as a theme... 
https://sdgs.un.org/goals

Or some of the 'Awareness Month' themes... 
https://www.luriechildrens.org/en/ways-to-help/Ways-to-Give/awareness-days-observances/
https://www.goodgoodgood.co/articles/awareness-calendar

**Comment by NikolaCreatrix** [comment]
Hey @c0ric0ri and @WhyldWanderer  I think the May theme is cool!

I've been looking at the other links for the next few months.

For June and Pride - just want to say that we don't really have many projects to feature I believe...marginalized communities maybe, but I did check in here: https://www.goodgoodgood.co/articles/awareness-calendar - I think going for something like one of these would make more sense considering what types of projects we have in abundance: 

World Environment Day - June 5th
World Ocean Day - June 8th

July - similar to the Pride, not sure how many Barcelona-based projects we have...unless we onboard them - don't think it's worth of the whole month's space. So I suggest one of these instead:
- The month of relief/feeding the hungry
- DAOs

August:
Children's care

And for other months:

Art & Culture
Community
Education...

**Comment by WhyldWanderer** [comment]
Yeah... I agree with the pride one.. i dont know how many projects we will have in that category

For the Barcelona ones, I am hoping to onboard some non-profits based in Barcelona the same way we did with the Denver projects for ETH Denver.. lets see how many we can get and if there arent enough, we can choose something else for July

**Comment by c0ric0ri** [comment]
Hey @NikolaCreatrix @WhyldWanderer I filled in campaign slogans for June and July in the Notion page for World Ocean Day (June) and hunger/relief aid (July).

Can you fill in the list of associated projects?

June should be submitted to the homepage as soon as possible, @danelsuga @oyealmond if you also like how the June campaign is setup.

**Comment by oyealmond** [comment]
Thanks @c0ric0ri! 
@NikolaCreatrix , @WhyldWanderer let me know if you need support selecting the projects :) 
question, @WhyldWanderer you usually submit this section to Giveth's homepage?

**Comment by oyealmond** [comment]
hey @WhyldWanderer @NikolaCreatrix ! Here's some ocean related projects that we can feature: 

https://giveth.io/project/healing-coral
https://giveth.io/project/modoc-earthrace-conservation
https://giveth.io/project/Rios-Limpios-Grey-Water-Filters-Costa-Rica-0
https://giveth.io/project/seaworthy-foundation

let me know your thoughts :)

**Comment by WhyldWanderer** [comment]
June is finished! There arent as many projects for this theme so I added a couple Giving Block projects.

I didn't include the Grey Water Filter one as it doesnt really have much to do with oceans but I can always include it if it needs to be.

**Comment by oyealmond** [comment]
here we can keep the convo about the highlighted projects on the Giveth home page @WhyldWanderer @NikolaCreatrix

**Comment by NikolaCreatrix** [comment]
Hey ladies, so just to clarify - basically what I can start doing is to update the homepage every month or 14 days with newly verified projects and just keep the # MeetTheMakers @oyealmond so this thread may not be needed anymore? :)

**Comment by oyealmond** [comment]
Yes! Communitas will have full ownership of what happen w/ the featured projects section. How's it going? Are you planning to update anytime soon? @NikolaCreatrix

**Comment by NikolaCreatrix** [comment]
Updated!
