### ISSUE TITLE
Plan updates for What's Up on Giveth Homepage Section - April 8

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1292]
Comms should be providing regular updates for this section to promote new product launches and latest initiatives.

An idea would be to use Notion for a schedule around this, and review it periodically with the comms team to keep an active funnel of new content.

Adminbro can be used to update this.

- [x] Create notion page to outline content
- [ ] Set schedule for when to update via adminbro
- [ ] Choose topics to update this section with

**Comment by c0ric0ri** [comment]
I created [a notion page](https://www.notion.so/giveth/Homepage-Content-Updates-7551d8e2084b4ee19120b099f59846ea#ec8efb8f4d994b0ba869cd14d0f8ccb2) to organize content for this section of th homepage. 

We need to decide how often to update this section. For now I outlined a **minimum** of once a quarter. Technically we could also leave some sections up for longer, while changing others out more frequently.

Shall we brainstorm some ideas here to add to the content schedule for the upcoming months? Keep in mind they should link to something.

For example, upcoming soon:
- Giveth Referral Program landing page

Would love to get input from the group! @oyealmond @divine-comedian @clara-zi @laurenluz @SnakeGH @ahmadabugosh @danelsuga @WhyldWanderer @NikolaCreatrix @Cotabe

**Comment by laurenluz** [comment]
I put some content suggestions for April what's up. Imo, we should add:
- Polygon Donations
- Spanish Translations

And will need text & banners for them - maybe someone could take ownership of that.

**Comment by c0ric0ri** [comment]
We can technically have more than 4 (we've had 5 at one point) but in my opinion 4 is a nice number.

I think I like Claire's list bc we've had $nice and GIVpower on the homepage for an entire quarter now. We can always cycle them back in next month, or add a 5th for GIVpower if we feel like it needs to be up there.

**Comment by c0ric0ri** [comment]
Hey @laurenluz @danelsuga @ahmadabugosh I've updated the section slots for April and wrote some taglines.

Let me know if this works, then just need to ensure we have the graphics ready.

**Comment by danelsuga** [comment]
Looking good @c0ric0ri ! I would just change the Spanish Giveth to not say "Spanish translations". Giveth is now available in Spanish, period.

**Comment by divine-comedian** [comment]
> I put some content suggestions for April what's up. Imo, we should add:
> 
> * Polygon Donations
> * Spanish Translations
> 
> In addition to
> 
> * PFP
> 
> And we should consider keeping:
> 
> * $nice
> * GIVpower
> 
> We will need text & banners for them polygon & spanish translations - maybe someone could take ownership of that.

I like Lauren's suggestions!

**Comment by danelsuga** [comment]
Looking good. Just to reiterate: 

**It should NOT be called "Spanish translations".** 

It is not considered a "translation". Obviously, translations took place, but it is not the case that one version is the true, correct, original (i.e., English). That is only the case with authored-media like books, etc. It diminishes the value of the Spanish site itself to call it a "translation" (i.e., a copy in another language) of something else. It can be called a "Spanish version" or simply "Giveth in Spanish".

**Comment by c0ric0ri** [comment]
What links should we use for the Spanish part and the Polygon part?

Or are we ok not linking to anything and just having the blurb?

@danelsuga @divine-comedian @laurenluz

**Comment by c0ric0ri** [comment]
@danelsuga would you be willing to work on getting the designs for the Spanish section and the Polygon section in the 16 x 9 format?

I already have the Referral program one, and we have the GIvers of course.

**Comment by danelsuga** [comment]
The Spanish featured link should be: The link should be: https://giveth.io/es

The Polygon link: could be the forum post about requesting input for more Polygon tokens?

**Comment by danelsuga** [comment]
![polygon](https://user-images.githubusercontent.com/81351744/229525971-d3c50031-268f-4e5f-9de2-7716f57784a4.jpeg)

**Comment by laurenluz** [comment]
I think we should do better for designs for the homepage if they're going to be there for months, I think those are the simple ones we just put up for twitter @danelsuga 

I just sent Rodri a quick message to see if he has time to make something for us. If not, we can use those that you posted.

**Comment by danelsuga** [comment]
Got it. Yeah, that was my original question!

**Comment by c0ric0ri** [comment]
Is this the right link to use for the Polygon integration blurb? 

https://forum.giveth.io/t/givbacks-token-list/253/21

It feels kind of weird to link to a forum post but I'm not sure where else to point to.

@MoeNick any input?

**Comment by danelsuga** [comment]
Yes, this is actually my comment.

**Comment by laurenluz** [comment]
I left this comment in notion already. I think we should link: https://twitter.com/Giveth/status/1636352128280154119

**Comment by danelsuga** [comment]
Thanks, @laurenluz. I was curious if we should link to Twitter...

**Comment by WhyldWanderer** [comment]
Heres what we have for MTM graphic.. not sure if we want to ask Rodri about this one as well
![Earth_Day](https://user-images.githubusercontent.com/74267818/229974221-627b64e3-952c-48f8-80e4-a3f4cdf5f862.png)

Not sure how many characters, but maybe something like this? "Join us for this an event where project owners come together to share their vision, mission & impact"

Link to the Giveth Events Calendar? Or to the Giveth YouTube/Twitter?

**Comment by c0ric0ri** [comment]
I think they look too similar to one another @laurenluz if we are putting both up. Would be nice if they had different background colors at least to make the scrolling experience better

**Comment by c0ric0ri** [comment]
@WhyldWanderer I'm cool with the existing banner for MTM, I like the graphic and it gives all the details so we don't need to put it in the blurb.

 Edited the text slightly and added to Notion: "Join us during Earth Day week to hear project owners share their vision, mission & impact." I'd say link to our Discord? First off it drives traffic to our discord from the homepage, and it's where people need to go to join this event live.
