### ISSUE TITLE
Compile projects for April's Featured Campaign

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1294]
As we had discussed Earth Day as a theme for April, we should compile a list of projects to feature on the homepage campaign section.

Related to https://github.com/Giveth/giveth-planning/issues/1291

**Comment by c0ric0ri** [comment]
@NikolaCreatrix  can I assign this to you to create a list with @WhyldWanderer ?

Would be great if we can update the campaign by Monday April 3

**Comment by WhyldWanderer** [comment]
How many should we feature?
Can we use the categories?
Also, should they only be verified projects?

**Comment by c0ric0ri** [comment]
Hey @NikolaCreatrix @WhyldWanderer 

I would say 12-15 projects featured on the homepage. That should be about 5 sliders, which seems like a reasonable cap. Then when you click on the campaign title, it should take us to a complete filtered list of projects using a category. I think you had suggested Nature to use.

Ashley I thought you had confirmed that we can use the categories to filter. Do you still need that confirrmed with devs?

I wouldn't say they need to all be verified. Maybe the ones we show on the homepage, but not on the page that the campaign leads to. Unless you have a reason why not.
