### ISSUE TITLE
Newsletter March 2023

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1296]

**Comment by ahmadabugosh** [comment]
For this newseltter, I want to cover:

- Giver PFP
- Giveth Referral Program
- Integration with Polygon
- Giveth website in Spanish
- Giveth at ETHDenver medium article.
 
Anything else? @c0ric0ri @laurenluz @danelsuga

**Comment by NikolaCreatrix** [comment]
@ahmadabugosh :) 

Can we also say April 19th we'll have another Meet The Makers in honor of Earth day, all in Spanish - special edition, but no worries recordings will be with English subtitles...

Also a friendly reminder for verified projects - smth like watch out we are revoking badges for inactive verified projects; make sure you post an update to your project 'updates section'

**Comment by c0ric0ri** [comment]
Great job @ahmadabugosh ! Left my comments and edits throughout. Let's consider adding in Optimism results? Should we also include DAO drops?

**Comment by danelsuga** [comment]
Great job @ahmadabugosh. Still reading through but wanted to say: I see there's a big mention on also talking about Giveth Galaxy. A couple days ago I suggested including this: 

announcing giveth galaxy update with commons stack/refidao?
just before the weekend, they launched the ReFi DAO Local Node Prize, now open for applicants.
https://twitter.com/refidaoist/status/1638947958912860160

You didn't respond, and I let it drop b/c I thought maybe it's too far out to include the newsletter, but looking at the newsletter now and that "Giveth Galaxy" reference, I think it would be remiss not to include it, as it's a really big deal.

**Comment by danelsuga** [comment]
Read through and left some comments @ahmadabugosh. Thanks!

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri , I included the Optimism part in GIVfriends, and just added the amount we raised. Let me know what you think. I didn't include DAOdrops, because I thought we already had too in the newsletter as it is. 

Oh sorry I missed that, @danelsuga I just added a point for that

**Comment by laurenluz** [comment]
Looks good @ahmadabugosh, except for one (sort of important) thing: the projects you put in there had recent updates, but were NOT recently verified.

I added a link to the thread (yet to be posted) that highlights newly verified ones.

I do think we should change this because I think those projects were featured in previous newsletters already, and we should give new ones the spotlight.

**Comment by c0ric0ri** [comment]
Good catch @laurenluz . @ahmadabugosh if you make the last changes as per Lauren's comment, and the suggested grammar tweaks, we should be good on this.

@clara-zi can you add in that content to the draft?

**Comment by clara-zi** [comment]
Something like this @c0ric0ri @ahmadabugosh 
"
Congrats to our project survey winners! These amazing projects have each won a boost of 200k GIVpower to improve their ranks for 3 months. This means more visibility and more GIVbacks rewards for future donors! And the lucky winners are: 

[LunCo](https://giveth.io/project/lunco-accelerates-lunar-colonization-with-opensource) 
[Emprende DAO](https://giveth.io/project/emprende-dao)
[Web3beach](https://giveth.io/project/web3beach-accelerating-web3-adoption-in-latam)
[SplitWave](https://giveth.io/project/splitwave-split-secure-simplify)
[ARTXV](https://giveth.io/projects?term=ARTXV)

Thanks again to all our participants. Your feedback helps us to learn, grow and improve. If you have any comments or suggestions, please use our [feedback form](https://giveth.typeform.com/feedback): And if you who missed the survey but would still like to take part, the [survey is still open](https://giveth.typeform.com/projectsurvvey).
"

**Comment by ahmadabugosh** [comment]
hey @clara-zi I don't think I can include it unfortunately in this edition (it's already too packed as it is and I need to send it asap), but I'll follow up on the other issue you posted and send out a seperate an email to the projects (this one https://github.com/Giveth/giveth-planning/issues/1275)


@laurenluz, when you get a chance can you tweet it out (maybe tomorrow on April 2nd :P) : 

"
In our latest GIVnews 👇

💙 The launch of the Giver PFP collection & the Giveth Referral Program! 

🦄 Recap of @EthereumDenver 

🌍 ReFi Incubator with @refidaoist and @commonsstack 

🙌 Featured project @DAppNode 

🔴 GIVfriends @optimismFND 

https://paragraph.xyz/@giveth/givnews15
"

**Comment by laurenluz** [comment]
scheduled the tweet for today @ahmadabugosh - thanks.

**Comment by clara-zi** [comment]
will also post on FB

**Comment by clara-zi** [comment]
@ahmadabugosh Twitter link at the bottom of newsletter is still pointing to @givethio 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/100724132/229544183-15578834-8e5c-41ef-af2b-6a854286ec1d.png">

<img width="531" alt="image" src="https://user-images.githubusercontent.com/100724132/229544497-bcb98918-b8a2-4329-a2c2-860b47615a77.png">

**Comment by clara-zi** [comment]
now added to LI

**Comment by ahmadabugosh** [comment]
> @ahmadabugosh Twitter link at the bottom of newsletter is still pointing to @givethio <img alt="image" width="370" src="https://user-images.githubusercontent.com/100724132/229544183-15578834-8e5c-41ef-af2b-6a854286ec1d.png">
> 
> <img alt="image" width="531" src="https://user-images.githubusercontent.com/100724132/229544497-bcb98918-b8a2-4329-a2c2-860b47615a77.png">

Good catch, just fixed it!
