### ISSUE TITLE
infographic for Chainvine launch (referral program) article

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#1297]
https://github.com/Giveth/giveth-planning/issues/1252

@rodricastillo9013 did this.

@ahmadabugosh @laurenluz @c0ric0ri

**Comment by danelsuga** [comment]
![image](https://user-images.githubusercontent.com/81351744/228245219-d3e1edf1-1a24-4353-a3bd-8eb7fc8c4aa7.png)

**Comment by c0ric0ri** [comment]
Awesome! I also think this one is great for a cover image on the blog post

![image](https://user-images.githubusercontent.com/106524383/228297897-897b91f6-e75b-42af-9184-8367f663ea84.png)

**Comment by c0ric0ri** [comment]
Or by banner image do you mean that same slot?

**Comment by laurenluz** [comment]
I think it's cool.

if I'm being picky I would suggest moving the GIvbacks title up closer to the arrows? where it is now seems like a duplicated title on 1st glance.

**Comment by c0ric0ri** [comment]
I like the infographic! One feedback is I find the purple text bubbles hard to read, even when zooming in. Since we have so much space in the graphic, do you think we can use the room and make them bigger with slightly larger font?

**Comment by danelsuga** [comment]
updated from rodri!
![image-2](https://user-images.githubusercontent.com/81351744/228494453-3c80b457-fe57-4f6f-b775-62297e323326.png)

**Comment by c0ric0ri** [comment]
Looks good to me! Shall we move this to Done?
