### ISSUE TITLE
Implement User verification (3box, ceramic or otherwise)

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#130]
- As Giveth admins, we want projects to verify their identity with twitter, github, or email to prevent imposters.
    - To be a verified project for GIVBacks, the project must verify on 3Box.
        - Test that a project can be verified on 3Box with a [Tor.us](http://tor.us) wallet.

**Comment by WhyldWanderer** [comment]
Looks like these are the options for signing in to 3box as of now.
Is it a possibility to talk them into adding Torus?

![image](https://user-images.githubusercontent.com/74267818/116009841-e517e700-a5d8-11eb-9e98-eae937b52920.png)

**Comment by WhyldWanderer** [comment]
related to issue #135
