### ISSUE TITLE
April Fools Landing Page - Tweet - March 31

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1300]
We should create a tweet or short thread to post on Saturday, April 1 promoting the "Taketh" landing page as a joke. 

We can position it as if we are rebranding Giveth to Taketh :)

**Comment by laurenluz** [comment]
https://docs.google.com/document/d/1GEvRcBtov4Ta_GZhhGvYQkNHojt8NSZsa_tezvo2xTI/edit
