### ISSUE TITLE
PFP Promotion - Series of Tweets - April 3

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1303]
Let's create 4 easy tweets to promote our PFP collection consistently, 1x a week for the next 4 weeks.

**Comment by c0ric0ri** [comment]
@oyealmond would you be down to draft these?

**Comment by oyealmond** [comment]
sure!

**Comment by oyealmond** [comment]
Hey @c0ric0ri! 

Drafted 3 tweets , for the 4th one to be an update around the sell or good news of the cosmetic benefits. 
wdyt? 
You can check the drafts [here](https://docs.google.com/document/d/1y2qifA59wmMsBjGBUlCGJhHZ9l8r2RcPWJLeeZw9-Y4/edit) 

cc @laurenluz

**Comment by laurenluz** [comment]
Thanks @oyealmond! they are great - I set one to go out each week

**Comment by c0ric0ri** [comment]
https://twitter.com/Giveth/status/1648658212273504258?s=20

https://twitter.com/Giveth/status/1645396717703950336?s=20

https://twitter.com/Giveth/status/1643992493523087360?s=20
