### ISSUE TITLE
Project survey report winners - dApp - end Mar / beginning Apr 2023

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#1306]
We have 5 project winning 3 months of 200k of GIVpower boosting for 3 months!

These are the winners:
LunCo 
Emprende DAO
Web3beach
SplitWave
ARTXV

@divine-comedian  - what are the next steps for getting the GIVpower ranking boosted?

**Comment by divine-comedian** [comment]
I just made the transaction for us to wrap our GIV in the liquidity multisig to get GIVpower 

https://app.safe.global/gno:0xf924fF0f192f0c7c073161e0d62CE7635114e74f/transactions/tx?id=multisig_0xf924fF0f192f0c7c073161e0d62CE7635114e74f_0x7b2e14e787c7807fea159f8f5a1e6f842065a75e6f183ff2221dc312a31a82bd

**Comment by clara-zi** [comment]
LunCo
Emprende DAO
Web3beach
LexDAO
ARTXV

@divine-comedian - this is the final list of verified projects to be boosted with GIVpower for completing project survey. What's the next step?

**Comment by divine-comedian** [comment]
done! 

![image](https://user-images.githubusercontent.com/67759413/230660370-cf900187-c158-42c6-8396-ad80e8b15b57.png)

**Comment by clara-zi** [comment]
Nice. Thanks. Closing issue :)
