### ISSUE TITLE
Mandatory Updates - updating documentation + video guide

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1307]
Ashley and Nikola create more guidance for project owners to know how exactly to post an update since it seems to be somewhat unclear for many project owners.

Rasks:

- [x] Create a new section in Giveth Docs and upload documentation for "How to post an update" 
@WhyldWanderer 

- [x] Create a short video guide and add it to Project Owners 101 course
@NikolaCreatrix

**Comment by NikolaCreatrix** [comment]
Hey hey team!! @ahmadabugosh @c0ric0ri @WhyldWanderer 

I have recorded this short video guide for mandatory updates, please can you review?

And @ahmadabugosh do you think we could add this to our Project Owners 101?

https://www.loom.com/share/1782cfede981481f92da7d5c217ac3f9

**Comment by WhyldWanderer** [comment]
Looks great @NikolaCreatrix! 
We just need one more reviewer and then we can add it to the YouTube... I can help with this when its ready.

Here is a thumbnail image for the video 
![image](https://user-images.githubusercontent.com/74267818/229162201-422b6dd9-15f1-4549-a46e-45a31b08f71d.png)

**Comment by c0ric0ri** [comment]
Cool @NikolaCreatrix ! Looks great. Just one thing, can you add that projects should submit a minimum of one update every 3 months to retain their verified status? I think that's a very important piece of information

**Comment by NikolaCreatrix** [comment]
@c0ric0ri I hear you but I also had to consider that this video will serve all project owners, not only verified projects and it was already a lot of text to fit in a very short video...I think this video could be just a complementary tutorial included in our documentation where this 3 months requirement will be mentioned as well as in every email that's sent to the newly approved verified project. We are also working on notifications that project owners will receive in the notification center... Do you think that will do it? Or still would like to see me redo it? I'm open.

**Comment by WhyldWanderer** [comment]
Uploaded the video to YouTube: https://youtu.be/sRhp74CcGU8

**Comment by NikolaCreatrix** [comment]
Hi team, so for the documentation part, we want to create a new section in docs:

"Adding Updates to Your Project"

![image](https://user-images.githubusercontent.com/100084867/235212718-b099bd4a-3126-47bb-8820-a439eeddfa8d.png)

Draft of the text is here:

https://docs.google.com/document/d/1H8h7BN2QEab3Iwsag3NSBgN3CzIfUr4u0rTi6jjkNWs/edit?usp=sharing

Please review @WhyldWanderer and @c0ric0ri 
Do you think this is enough for the section or shall we cover anything else?

**Comment by WhyldWanderer** [comment]
Reviewed! I love it.. thanks for doing this Nikola.
Its simple, streamlined, concise and links to video that is easy to understand.

I made a few edits at the end... 

We just need one more review.. maybe @danelsuga or @clara-zi can give us a thumbs up if Cori is busy?
Then @franculio can add it to the docs! 🚀

**Comment by NikolaCreatrix** [comment]
Excellent, thanks @WhyldWanderer & @clara-zi I implemented your edits and now it's all shiny and ready to be uploaded.

 @franculio  👍 Let me know please when it's done by posting the section link here, so we can close the issue. ;)

**Comment by franculio** [comment]
Hey @NikolaCreatrix ! Great work! Where do you exactly propose to add this sub-section? Inside the **Project Verification Process and Guidelines**? Or do you want a separate one just below that one on the submenu? 

If it inside the **Project Verification Process and Guidelines**, should it be down below after the **Graduated Sanctions for flagged projects** section? 

I just want to be sure before I update! Thanks!

**Comment by franculio** [comment]
@NikolaCreatrix the doc has been uploaded. Feel free to review and close the issue if everything seems ok.

**Comment by NikolaCreatrix** [comment]
Looks great! Thanks @franculio :)
