### ISSUE TITLE
Promote Chainvine - Tweets - April 8

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1310]
Let's draft a series of promotional tweets about the Referral program to schedule out for next week. Would be great to get this draft by Friday!

Main CTA is: refer your friends, generate your link today and start earning, hey regen influencers - teach people about giveth and refer them to donate (we'll reward you for it)

**Comment by oyealmond** [comment]
Hey @c0ric0ri @laurenluz :) 

Sharing the tweets [here](https://docs.google.com/document/d/1qn6_njepERxB2xUpKRRiq05WZiR2mrF3AUPB9eCYeds/edit). Hope they're useful!

**Comment by laurenluz** [comment]
thanks Almond! I made some edits and scheduled them all.

**Comment by oyealmond** [comment]
they're great! thank you so much @laurenluz
