### ISSUE TITLE
The importance of Latam for Web3  Twitter Space

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1312]
[Created the guide](https://docs.google.com/document/d/1RjQxmpwm8vZHH_efFRGcFKPqadxCtLS2njph82TZyyQ/edit?usp=sharing) for our Latam and Web3 Twitter Space. 

@laurenluz could you help me review the promotion tweets drafts? 

Thanks! 
cc @WhyldWanderer

**Comment by laurenluz** [comment]
tweets all scheduled
