### ISSUE TITLE
Augment Project cancelled NEW Giveth 2.0 Email in Auptopilot to include fraudulant activity

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1314]
Current email:

![image](https://user-images.githubusercontent.com/74267818/230103023-6664b939-ef87-4f30-8cc7-78f8f6facb7d.png)

We should add something like "Fraudulently creating a project for an organization that you are not actually a representative of"

 
What do you think @laurenluz?

**Comment by laurenluz** [comment]
Agree we should add the bullet, but need to consider that "you" in this case may not actually be the person who created the project. So perhaps we change:

- [ ] The 1st line to:  "The project {project name} has been cancelled"
- [ ] Add a bullet "Fraudulently creating a project for an organization that the creator is not actually a representative of"
- [ ] Last line to: "Review this project on Giveth, or try to get it re-activated and open for donations by reaching out in the support channgel in the Giveth Discord."

**Comment by oyealmond** [comment]
@WhyldWanderer Ash, can I close this? Should I move it to Notion?

**Comment by WhyldWanderer** [comment]
@oyealmond - Wow! Were digging up some gems recently.. It will be so nice to have all of this old clutter cleaned out and organized. Thanks for doing the work to make it happen!

I think we should move this issue to notion just to ensure that it is reflected and included in the new email process. 
Feel free to tag me there and I can follow through on it.

**Comment by oyealmond** [comment]
word. Thanks!

**Comment by oyealmond** [comment]
here @WhyldWanderer 

https://www.notion.so/giveth/Augment-Project-cancelled-NEW-Giveth-2-0-Email-in-Auptopilot-to-include-fraudulant-activity-ea60a8a09c4741348a367260767e36b5?pvs=4
