### ISSUE TITLE
PFP Influencer Outreach

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1315]
To get more reach for the PPF collection, we should consider offering a select number of PFPs to gift to influencers in exchange for promotional support.

This would look like:

- [ ] Identify list of 10 ideal influencers, considering number of followers, ideal audience for us
- [ ] Create a message for outreach: We just launched this collection with this objective, we'd love to give one to you - would you be willing to help us promote the initiative?
- [ ] Do the outreach via Twitter or Telegram

**Comment by c0ric0ri** [comment]
Building the list here: https://docs.google.com/spreadsheets/d/1ZrifFUwZ6YvunEdye_wpkAscAhmEqYuE-dM8igLuHEM/edit#gid=664201838

@Cotabe @oyealmond @laurenluz @GriffGreen @Santigs if you have any input I'd love to know, aligned friends or regen influencers with followings of at least 3-4k (ideally higher than this for more reach) who would likely be willing to promote this with us.

Perhaps also people who have been on the GM podcast with us?
Strong promoters of public goods?
Strong promotors of NFTs to fund public goods?

**Comment by c0ric0ri** [comment]
@laurenluz mentioned that Vitor from General Magic runs an NFT newsletter, checking in with him to see if he has ideas on who could be an NFT influencer for us.

Also would be awesome if they would promote the Givers in their next edition!

**Comment by laurenluz** [comment]
what's going on here @c0ric0ri ?

It might be good to just generally do some research on google or twitter to find some accounts who might be helpful. Or you could ask Stee

**Comment by c0ric0ri** [comment]
Hey @laurenluz I synced with Almond on this last week, and we're just going to proceed with starting some outreach to a few people. I also asked Stee for help on research several weeks ago as you suggested, but didn't receive agreement from him on that. So the running list we have here is from my research and will just start with that and gauge initial responses

**Comment by laurenluz** [comment]
Hey @SteffanThorn - can you help Cori a little here with some suggestions on NFT influencers, or ways of finding the right people to reach out to?

**Comment by SteffanThorn** [comment]
https://drive.google.com/file/d/1bSgWJm5duSvolCEEUUzkNPhcPKdayMrB/view

This drive includes an NFT influencer guide with suggested influencers and where to find others. 

hope it helps.
