### ISSUE TITLE
Verified Projects Landing Page - Website - May 30

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1319]
A informational landing page to describe our verification process, providing details on what it means for a project to be verified, what the benefits of it are, and how we go about verifying projects.

**Comment by c0ric0ri** [comment]
Reuse content from things TropicalMango may have been working on - @danelsuga and @NikolaCreatrix could you check if we already have these points somewhere and add it here for drafting?

**Comment by NikolaCreatrix** [comment]
So the issue I had in mind and content we could potentially re-use/revise is from this issue:
https://github.com/giveth/giveth-planning/issues/946

The document is here:
https://docs.google.com/document/d/1AxcjjN2msJ1WmXabaLerXE_czyWJa8-apsXKDRrGvQs/edit#heading=h.b9x2ain8myd1

@danelsuga you mentioned in the call that you have some content already prepared?

Please feel free to tag me again once you need revision and testing by verification team. ;)

**Comment by c0ric0ri** [comment]
Here is a first draft of the verification landing page. I tried to keep it simple and focused more on the benefits than the actual process, but with a link to the docs:

https://docs.google.com/document/d/16FvZlR6EySuhzqj7lNDxYnN-aaNnH5Y27v36AdGD3Bo/edit

@ahmadabugosh @danelsuga @oyealmond @laurenluz

**Comment by WhyldWanderer** [comment]
@c0ric0ri - I requested access

**Comment by danelsuga** [comment]
Same.

**Comment by NikolaCreatrix** [comment]
I see that Ashley and Lauren already commented and reviewed it.

I would just like to make sure that we update the documentation before this one goes out - please review the content also here #1368  @danelsuga @ahmadabugosh so we can update the docs.

**Comment by oyealmond** [comment]
@divine-comedian did you know about this issue? @ahmadabugosh do we have a verified projects landing page? Does this makes sense to build?

**Comment by divine-comedian** [comment]
I think between the documentation and the projects onboarding page we have this covered https://giveth.io/onboarding/projects
