### ISSUE TITLE
Verified Projects thread R33 + 34

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1320]

**Comment by NikolaCreatrix** [comment]
Draft for review ready steady :) @laurenluz 

https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by laurenluz** [comment]
Awesome Nikola!!

We plan on tweeting about a lot of earth-focused verified project this week and next (leading up to earth day), so as per @c0ric0ri 's suggestion, I put just the 3 in the thread to go out tomorrow...

And we can save the others to tweet about next round. I made all these edits in the doc already so you can just have a look and accept if it sounds good!

Thank you! And amazing thread, as always.
