### ISSUE TITLE
Gitcoin Beta round grant application for Decentral - April 14

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#1321]
Submit Decentral to the Gitcoin Beta round for grants.
Also to any relevant featured rounds (to be announced next week).

The Beta Round is planned for April 25th - May 9th. Are you new to Gitcoin Grants and interested in participating in the upcoming Gitcoin Program Beta Round? Check out the Upcoming Round Resources section below! Projected timeline: Start updating/creating your grant in Builder the first week of April; apply for the applicable round (where you meet the eligibility criteria) April 12th- 18th. Applications will be reviewed April 19th - 24th. Round goes live on April 25th. See Onboarding Guide below for more information.

https://docs.google.com/document/d/1YUvoAMFs69g-AL7WCfiKvhgwPcOXnbNIBdlmr3MJS7g/edit
The Gitcoin Program Beta Round is the second set of Gitcoin Program QF rounds that will run on the new decentralized Grants Stack. The planned dates for this round are April 25th to May 9th and there will be 5 Core Rounds each with a distinct matching pool: 
Climate Solutions
Ethereum Infrastructure
[Web3 Community & Education](https://docs.google.com/document/d/1PbGCHW_LpTVxGz0nBTiCKeCuNkJi2uwVCxFgIElQHcc/edit)
Web3 Open Source Software
ZK Tech

**Comment by danelsuga** [comment]
What do you think @laurenluz ?

https://docs.google.com/document/d/1g44GRBJ96XN3WlRIS6P2Dm9l6xo-kNAgxWDDp1DOYiM/edit?usp=sharing

**Comment by laurenluz** [comment]
Hey @danelsuga - I think it's pretty good, it really needs some photos and some formatting. Subheadings or bullet points so it's easier to read/skim. Lmk if you need help digging up some photos.

Also some links to burning man principes, or perhaps also to the old camp website might be valuable as well - so it looks more credible.

**Comment by danelsuga** [comment]
Thanks!

Yes, the website will be linked. 

For pics I could just use the the ones on the website though. Wdyt? I've already put the big one from the website as the banner for the grant. 

Thx!

**Comment by laurenluz** [comment]
Yeah these ones I think are good from the site:

![image](https://user-images.githubusercontent.com/75490971/233122437-f43cde81-de42-407d-b1b0-320d4fcf0215.png)
![image](https://user-images.githubusercontent.com/75490971/233122519-21f86144-8713-4ea8-947e-a09161d19a8e.png)
![image](https://user-images.githubusercontent.com/75490971/233122896-cfbbe0e0-1eb7-4270-815b-0b0979ef9c06.png)
![image](https://user-images.githubusercontent.com/75490971/233122685-b1f3f2de-14a7-47f1-874c-4bc21e0e535c.png)

And this is a nice team photo from last year:
![image](https://user-images.githubusercontent.com/75490971/233123245-f27aced3-391f-4f3a-8af8-5d89a1b10ea6.png)

**Comment by laurenluz** [comment]
I think this is the best primary image because it shows the talks:

**Comment by danelsuga** [comment]
Thanks! Think I need some more info:

1) previous funding 
2) payout address 
3) past rounds?
4) team size 
5) project is how old

@GriffGreen ?

**Comment by GriffGreen** [comment]
1. 0
2. 0xbd0CcE3FeFB1848aF6db5f9523945862DA2bDd7c
3. none
4. 60 
5. Since 2017

**Comment by danelsuga** [comment]
Phew!

https://builder.gitcoin.co/#/chains/1/registry/0x03506eD3f57892C85DB20C36846e9c808aFe9ef4/projects/719
