### ISSUE TITLE
GIVtalk Twitter Space - NFTs as funding mechanisms May TBD

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1322]
Find issue here @c0ric0ri

**Comment by oyealmond** [comment]
@c0ric0ri Gitcon Beta round start Apro 25 to Apr 9. Scheduling this Twitter Space to Apr 10. Or you think May 17th will be better?

**Comment by laurenluz** [comment]
did this one happen @oyealmond ? icebox? close?

**Comment by oyealmond** [comment]
hey @laurenluz! 
@c0ric0ri and I were not able to align on this. She'll share her thoughts on the idea of this twitter space tmrrw, so I can coordinate it.

**Comment by c0ric0ri** [comment]
As discussed with Almond and I today, the idea here is to have a topic centered around NFTs a web3 fundraising mechanisms for nonprofits

Potentially invite to the discussion:
- Public Nouns (as another collection to share their experience)
- John Ellison (perspective as a Giver holder)
- invite an NFT project outside of our sphere that is raising for social impact
- EcoDAO? Inviting David Phelps to speak on his opinion on NFTs for fundraising for environmental impact
