### ISSUE TITLE
LinkedIn Content Batching - April Week 3 - April 17

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1324]
Batching 7 posts for a week of posting.

**Comment by c0ric0ri** [comment]
Ideas - creating posts to promote projects from this category for the entire week for Earth Day. Let's choose projects that have LinkedIn profiles

https://giveth.io/projects/nature

**Comment by c0ric0ri** [comment]
Here's a draft doc to use: https://docs.google.com/document/d/1wS7w526C8Lfzwi2UyMKKxUfILED8o7xiouDemuWKYFA/edit

**Comment by clara-zi** [comment]
recent grants awarded with #fundraising

**Comment by c0ric0ri** [comment]
Per our convo @clara-zi we'll use Plannable for this

**Comment by c0ric0ri** [comment]
Friendly reminder @clara-zi please update the status of these issues. Since they're not moving to In Progress or Review, I'm not sure from looking at them what stage they're at.

**Comment by clara-zi** [comment]
did  you manage to get into Planable?
