### ISSUE TITLE
Twitter Space Apr 26 / Gitcoin Beta Round

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1327]

**Comment by oyealmond** [comment]
GM @laurenluz :) 

Could you please help me review [next week Gitcoin's Beta round Twitter Space](https://docs.google.com/document/d/1RVT6GU8BkVPOcTCehU0h8UuAsY-FflN2ctrQaR71RO0/edit) please?

**Comment by laurenluz** [comment]
I scheduled all the tweets!

**Comment by laurenluz** [comment]
Just lefts some comments & edits. Thanks Almond!
