### ISSUE TITLE
Promote Web3 & Latin America podcast. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1329]
Hey @laurenluz  :) 

Could you please review[ this tweet draft ](https://docs.google.com/document/d/1LkPaAMn7_BKrwSfK1ImtFhhxuDWZXkstzfpAddx41rI/edit?usp=sharing) promoting our most recent #GIVtalk podcast? Thank you :)

**Comment by laurenluz** [comment]
scheduled
