### ISSUE TITLE
Add Referral Program to GIVbacks email

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1332]

**Comment by ahmadabugosh** [comment]
Hey @laurenluz @WhyldWanderer @danelsuga , 

I thought it would make sense to add the Giveth referral program to the GIVbacks email. Let me know what you think: https://docs.google.com/document/d/1isw3cpQR4Es00EGIPi_ySUEzi9KfTMhG49Sk7mmdn4Q/edit

Also, do you think it's worth mentioning the Panvala Stamps program?

**Comment by laurenluz** [comment]
The email looks fine like that @ahmadabugosh. 

What would we say about the Panvala Stamps program?

**Comment by ahmadabugosh** [comment]
@laurenluz Yeah true I guess it's not relevant (I thought I saw a mention of it on a previous GIVbacks sheet, but maybe I got confused)
