### ISSUE TITLE
Project Survey Action Points

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#1335]
Action points for Comms - recommendations from Project Owners

@c0ric0ri

**Comment by clara-zi** [comment]
Suggested action points:

More Donor-Targeted Comms:
- [ ] Educational content - how to fundraise and reach donors
- [ ] Projects would like GIVpower - maybe we can do competitions / games to earn
- [ ] Advertising
- [ ] Projects promotion
- [ ] Reach and shill to high net worth potential donors


Project Promotional Campaigns:
- [ ] Focussed fundraising campaigns - finite duration
- [ ] Rotating random project feature on projects page


Educational Content to Make Giveth More Accessible:
- [ ] Education infographics aimed at donors
- [ ] Education infographics to explain GIVpower


More Cross-Promotion:
- [ ] Cross promotion across platforms
- [ ] Invitations to Twitter Spaces and other events

**Comment by clara-zi** [comment]
https://docs.google.com/document/d/1AI9EV6XqTH4sIHuZu_f1dYVUe8FsS4_9MLiiMxWkOak/edit 
for drafting ideas

**Comment by oyealmond** [comment]
hey @WhyldWanderer ! 
This could be useful for communitas plans?
