### ISSUE TITLE
PFP Integration Announcement - Tweet - April 27

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1340]
We need to announce the PFP Integration on the dApp.

So basically: You can now set your PFP as your profile pic on Giveth! Here's a cool preview of what that looks like, etc

**Comment by oyealmond** [comment]
Sure! Where can I find the preview image @c0ric0ri?

**Comment by c0ric0ri** [comment]
@oyealmond I got a good tip from Mitch to use the Figma for screenshots:

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?node-id=14997%3A268092&t=50llIe6maWeIiR7I-1

**Comment by oyealmond** [comment]
[Ready thread draft. ](https://docs.google.com/document/d/145z87hqVktTy4GL6Ui9R2xrXgu6NfJlCoOYd56xoEc0/edit)

@laurenluz @c0ric0ri

**Comment by c0ric0ri** [comment]
Hey @oyealmond, sure - I can definitely try to do that in the future to provide more direction. But just FYI in the end I would need to research it the same way as you to find out where to get the screenshot and decide what looks best, so it would be helpful in the future if this is considered part of the issue task. In any case we have the review process to adjust pictures if needed.

**Comment by c0ric0ri** [comment]
Thanks for putting this together @oyealmond ! I just did a quick review with some suggestions to create an intro tweet and perhaps combine the first 2 instructional tweets, using the screenshot that shows the PFP already applied. I think we could use an actual Giver NFT for the first tweet, but that's my opinion.

**Comment by oyealmond** [comment]
Hey @c0ric0ri sure :) Let's review the process, it will be helpful. With tweets review @laurenluz always edit my drafts directly, 
in cases like this, I will be applying your feedback for Lauren to review afterwards?, Or will @laurenluz make the editions directly? 

Will be great to unify the process. 
Thanks!

**Comment by laurenluz** [comment]
it's cool @oyealmond - I can just review @c0ric0ri's comments and accept the ones I like so you don't need to spend more time on it.

**Comment by laurenluz** [comment]
ok I scheduled it for this week.

**Comment by oyealmond** [comment]
perfect! :D thank you @c0ric0ri @laurenluz
