### ISSUE TITLE
Gitcoin Grant Recap - Tweet Thread - April 24

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1341]
We should post a thread on Gitcoin Beta round launch day that summarizes our grant and let's everyone know that we're participating.

**Comment by c0ric0ri** [comment]
Drafting here: https://docs.google.com/document/d/1rqCXXqa7iICJsxh0R-XHizdWuz_VcxYAYdyRgxQzvjA/edit

**Comment by danelsuga** [comment]
looking great, @c0ric0ri

**Comment by laurenluz** [comment]
https://twitter.com/Giveth/status/1650878151268941824
