### ISSUE TITLE
AI April Twitter Campaign

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1343]
We'll take all the winners that @GriffGreen shares, cut the videos and show them off on Twitter

@oyealmond will make the videos
@laurenluz will make the tweets

Starting with:
Ramin from the first week
Lauren Aband Justina from last week

**Comment by oyealmond** [comment]
Im just experimenting but, wdyt of having something like this on each post? @laurenluz 
https://drive.google.com/file/d/1pK1oII3IZZULxm-CtaEQjI-r6Ox9uppW/view?usp=sharing

**Comment by oyealmond** [comment]
Hey @laurenluz! 
Sending the 1st videos: 

[Ramin](https://drive.google.com/file/d/1nLR4fmN9vGQMUr1Wl7zGWQfg4fWlsZBG/view?usp=sharing) 
[Lauren](https://drive.google.com/file/d/13d0HQCKazEH8OCaxbP-oYFhcaFnIP0Cy/view?usp=sharing)
[Justina](https://drive.google.com/file/d/1Q9ylNLfvgusoKvgrRcLpaLOCV6L74LJb/view?usp=sharing)
[Ahmad](https://drive.google.com/file/d/1Yyh5ZEhDetw3SgRYFEXKo6GRNIABcysU/view?usp=sharing)
[Danil](https://drive.google.com/file/d/1USVi3AqoVobjUkf4W-H34TKIc7ksjHtS/view?usp=sharing)
[Tam](https://drive.google.com/file/d/199N-wYPvy7oohRRaMiPb57MwF7W_XBMD/view?usp=sharing)
[Cori](https://drive.google.com/file/d/1lC5RIeXGk136M4Z3BnIHZtYyhWHyNjPx/view?usp=share_link)

**Comment by laurenluz** [comment]
Hey @oyealmond! oh no! Twitter doesn't allow videos more than 140 seconds long. Mine, for example is too much

**Comment by oyealmond** [comment]
oh no! Let me adjust them

**Comment by oyealmond** [comment]
that's very weird, I previously investigated in the length and I tried to make them shorter than that yours is 135 sec , that's very weird, maybe to not struggle I can make them all 120 sec long?

**Comment by laurenluz** [comment]
Hey @oyealmond! 

I've been drafting these and scheduling them out. got 4 so far, working in this doc and made you editor: https://docs.google.com/document/d/1vQaaZwWikkMemnhqGddho-USIlH1K70V9BnNPnfnCFM/edit

I've been looking in the tg chat to see what griff wrote about the project, finding relevant links etc, seeing what prizes they won, and making tweets from there.

Two questions:
1. are we making more videos? Some - like Amin's or Guil's for example - were super cool. Do you have a list of ones to create?
2. If you have some time and want to help craft any tweets, it would also be really helpful. no pressure, but if you do, just mention it in the issue here, and add them to the doc.

**Comment by oyealmond** [comment]
Yes Im missing more! 
Im going to start working on Guil's one, and then Im missing all of the last round . 
Griff mentioned everyone from the last round except Ivy, Algene, MaryJaf and Heather will need videos. Wdyt? 

Sure! I can help you draft them to. I'll share the rest of the videos tomorrow, and then we can divided them howhever's best

**Comment by laurenluz** [comment]
I didn't see all the videos from the last round, but let's definitely make sure we get anyone who won something.

Amin, Guil, Kay, brichis, pablo, mateo, alireza, carlos/mitch/mateo, angela/rohan

phew, I'm tired just listing them 😵 let me see if I can loop in someone else to help w/ drafts

**Comment by laurenluz** [comment]
@carlosjmelgar - you think you could help us draft some tweets for this campaign? there are lot that we have to tackle :)

**Comment by oyealmond** [comment]
@laurenluz 

New one: 
[Guild](https://drive.google.com/file/d/1xKwbyp0kPMJv8Rd29yNiP6TZuH-EbtYP/view?usp=sharing)

**Comment by oyealmond** [comment]
[Kay](https://drive.google.com/file/d/1k2kXtsYMz-oPIVERG1UO5MeKdIDDTFM9/view?usp=sharing)

**Comment by oyealmond** [comment]
[Rohan](https://drive.google.com/file/d/1NSM0rSdZr70empL1TR8b88M34VTyrxTk/view?usp=sharing)

**Comment by oyealmond** [comment]
[Bricia](https://drive.google.com/file/d/1DHWRxYvb3FVHmiAHPyoGwoCFQcsBXKRP/view?usp=sharing)

[Mitch](https://drive.google.com/file/d/1uhCImXZx7k7elcDRxrwdUH29WZslJgma/view?usp=sharing)

**Comment by oyealmond** [comment]
[Carlos](https://drive.google.com/file/d/1JaGSUHtF08iDYEc3D1BNxSECs5l6iofp/view?usp=sharing)

**Comment by laurenluz** [comment]
@carlosjmelgar is going to draft tweets for Guil and Bricia... @oyealmond - can you change the name on Guil's to "Guil" you made a little typo

**Comment by oyealmond** [comment]
sure! right away. @laurenluz

**Comment by oyealmond** [comment]
@laurenluz 

Here's [Guil](https://drive.google.com/file/d/1Rfgjxh0n6DJQrJC38KWKNLNX7l3pPlcw/view?usp=sharing)

Im almost done w/ all the videos, 
I can draft Mitch'Carlos and Mateo's tweets

**Comment by laurenluz** [comment]
EPIC

**Comment by oyealmond** [comment]
[Mateo](https://drive.google.com/file/d/12cIja4HYwMKp9bWZE3yOvQtzMtMVJdoU/view?usp=sharing)

**Comment by oyealmond** [comment]
[ Angela/Rohan fixed](https://drive.google.com/file/d/12cIja4HYwMKp9bWZE3yOvQtzMtMVJdoU/view?usp=sharing)

**Comment by oyealmond** [comment]
[Alireza](https://www.notion.so/giveth/Maye-e1b93c073b714d279c6da86b5265cf38?pvs=4)

**Comment by oyealmond** [comment]
[Amin](https://drive.google.com/file/d/1FwQUUp-tGz2UHA1RiLKMIr94FyElW2CF/view?usp=sharing)

**Comment by oyealmond** [comment]
[Here's all the videos](https://drive.google.com/drive/folders/1jj5KxH4KDbmhCyIiayoNSuOpGJcEl8lf?usp=sharing)! Let me know if I missed any

**Comment by oyealmond** [comment]
Drafted Mateo, Carlos, Mitch, Amin & Alireza

https://docs.google.com/document/d/1vQaaZwWikkMemnhqGddho-USIlH1K70V9BnNPnfnCFM/edit

**Comment by carlosjmelgar** [comment]
@laurenluz Guil tweet is done. 

[https://docs.google.com/document/d/1vQaaZwWikkMemnhqGddho-USIlH1K70V9BnNPnfnCFM/edit](url)

**Comment by laurenluz** [comment]
I think we're missing tweets for:
- Danil / David
- Angela/Rohan
- Freshelle

Am I right?  Anyone want to take them?

**Comment by laurenluz** [comment]
Hey @carlosjmelgar - I made some edits to your tweet, pasted below the originals in the doc. please have a look and try to take some feedback from the changes!

The only I have left to schedule is Kay, and I'm waiting on the new video from @oyealmond .

Final step: We need someone to make a "thread of threads" for this campaign, tagging each contributor again and giving like a one-line intro to their project... then linking the tweet.

I put a list of all the tweet links (minus the two that aren't yet posted) in our [doc](https://docs.google.com/document/d/1vQaaZwWikkMemnhqGddho-USIlH1K70V9BnNPnfnCFM/edit)

Who has time to make a draft of that final step? @SteffanThorn @c0ric0ri @oyealmond @danelsuga ? would be amazing to have a draft by the end of monday.

**Comment by danelsuga** [comment]
Are you not making vids, tweets, etc. for all the winners? Just some? My group won, but we're not in your list, for example.

**Comment by danelsuga** [comment]
The winner of the Best Community Organizing use of AI is:

Suga, Humberto, Rod & Vadim!!!

@Sugasug, @HBesso31, @ionrod & @VadimOlegowich built GIVai - a completely open source AI chatbot that can be trained to answer any questions about Giveth. Really cool deepdive into the possibilities of training our own AI for community management. Really epic use case and honestly if we could train it on praise and our docs, I'm sure it could answer questions better than anyone of us could.

**Comment by danelsuga** [comment]
If you will include my group's win, would be good to include that Humberto (HBesso31) is from Urbanika and Rod from @LunCoSim and that Vadim was the real dev of the whole thing.

**Comment by laurenluz** [comment]
@oyealmond can you make one last clip for Suga's project? @danelsuga - could you link the youtube video & timestamp to make it easier for almond?

I'm fine to do this one more but then I'm drawing the time. this has taken too many hours of my time as it is.

**Comment by danelsuga** [comment]
I couldn't care less personally. I don't think this thread has any particular significance, but my question was if you are doing all winners, it would only be correct to actually do them all.

**Comment by danelsuga** [comment]
Actually, I do care for the sake of the people in my group who worked hard and won. 

Are there any others that were forgotten?

I saw my name tagged so checked it out. Saw the missing info and pointed it out. Don't have bandwidth to take on the final thread.

**Comment by laurenluz** [comment]
there are others we didn't do as well. if you "couldn't care less personally", "don't this thread has any particular significance" and don't have time to help on it, please spare me the further discussion/championing.

**Comment by danelsuga** [comment]
my comment about not caring less was based on your response that it was taking too much of your time, as though i was violating that, and i was trying to note that it wasn't personal but a response to what i saw as a consistency issue. i was just asking a question if all winners were included or not because i saw a hole. i wrote don't personally care for the reason expressed here above, and then realized that i do care if nothing else on behalf of the guys i worked with (if it's a full winner type task). and admittedly, i care too in the end b/c it feels shitty to be left out. and if many are left out, no biggie, i guess? somehow that doesn't seem to be the case? if you need me to join in on the work, b/c somehow i am now responsible, i can try, but i don't think it's the best use of my time at this point with loads going on in other circuits at the mo. hugs to you, sister.

**Comment by c0ric0ri** [comment]
@laurenluz I can help with drafting this but i already had other things planned for today, so it needs to wait until later this evening

**Comment by laurenluz** [comment]
Thanks @c0ric0ri, I'm actually almost done, since I didn't hear from anyone before. Feel free to review what I put together in the doc already though.

**Comment by laurenluz** [comment]
I wrote the thread & scheduled it already, this is done!

**Comment by danelsuga** [comment]
@laurenluz sorry for not correctly acknowledging the work you did here and commenting in a way that came off as insensitive and butting in and without offering actual support. thank you for taking on this task.

**Comment by laurenluz** [comment]
Thanks @danelsuga - I really appreciate that. I do agree it's nice to acknowledge people in the tweets, just Almond & I have already spent so many hours editing so many videos and tweets... that the end result imo is not as impactful as our time was worth.

I'm also very stressed lately so that kind of hit a nerve. Anyway, I appreciate your feedback always 🙏
