### ISSUE TITLE
announce hats bug bounties Tweet

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1345]
https://twitter.com/hatsfinance/status/1648388475530678272

https://hatsfinance.medium.com/bug-bounty-alert-welcome-giveth-abea8d427962

**Comment by laurenluz** [comment]
Thread is ready, but we should post after we add more GIV to the vault:
https://docs.google.com/document/d/1ZbU_XU3dBPTRODg9ar1Xrz4xa9YYYl_ZMCHumA13sBU/edit?usp=sharing

**Comment by c0ric0ri** [comment]
Just keeping an eye on this, when do we know that more GIV has been added to schedule this?

**Comment by laurenluz** [comment]
well I had left a comment in the [forum](https://forum.giveth.io/t/giveth-bug-bounty-vault/1039)

@geleeroyale was manning this ship on this one, I sent him some messages in DM today to follow up.
