### ISSUE TITLE
Grants Notion Page - April 25

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1346]
This idea is to have one link to use for outreach and communications when fundraising and solicitiing support for Giveth,

This task is to create a notion page to summarize all the grants that Giveth has open where people can support us.

**Comment by c0ric0ri** [comment]
In progress here, collecting input from the Fundraising channel.

https://www.notion.so/giveth/Giveth-Grants-List-8ee89a3ffc52406ebd3b01a8847d1b7e

**Comment by c0ric0ri** [comment]
@SnakeGH @danelsuga struggling to find Yas's handle

**Comment by danelsuga** [comment]
@spectoregia

**Comment by c0ric0ri** [comment]
Moving to review for feedback, any other ideas here or something missing that you'd want on this page? 

@SnakeGH @GriffGreen @laurenluz @danelsuga

**Comment by laurenluz** [comment]
As I mentioned in [discord](https://discord.com/channels/679428761438912522/790268394251354143/1100928645238890537)...

![image](https://user-images.githubusercontent.com/75490971/235560212-e98406d5-2151-4b5c-8ec5-ea7a8d7755f0.png)

Also why did you link and describe the giveth matching pool & giveth project on Giveth? It kinds of makes me wonder what use case you actually had in mind for this... all the gitcoin links will be stale by May 9... and then afterwards it wouldn't make sense to use this notion to share to raise funds for our QF matching pool....

**Comment by c0ric0ri** [comment]
Yeah thanks, the request originally came from @GriffGreen and the matching pool / giveth project links came as input from the fundraising team.

My understanding is that this link should ultimately aid fundraising efforts. That's why I'm putting it for review here to ensure it's adding value to the team who requested it. 

Step-by-step guides....I could see linking OUT to something like that, the blog post as well perhaps, but I wouldn't necessarily make this page too much longer or wordier by adding guides into it. WIll fiddle around more with it.
