### ISSUE TITLE
Shilling other Gitcoin Projects - Tweet Thread - May 1

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1347]
A big part of successfully fundraising in Gitcoin rounds is shilling other projects, and having them to do the same for ours.

The idea here is to create a tweet thread to promote other projects in this Gitcoin Grants round, including a little blurb about their project and their Twitter handle.

For example.
Giveth Galaxy projects
Solarpunk Guild projects
Partners (ReFiDAO, etc)

**Comment by c0ric0ri** [comment]
@danelsuga would you be up for working on this for next week?

**Comment by danelsuga** [comment]
I'll be off next week unfortunately!

**Comment by laurenluz** [comment]
https://twitter.com/Giveth/status/1651971675217440769
