### ISSUE TITLE
Share last Meet the Makers session. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1348]
Hey @laurenluz 💫

Could you please check out this draft to share the last Meet the Makers session? 

https://docs.google.com/document/d/11ZvrEm5YqDF9qGnTRVkZK36w3NiU_HAQNsNIJ-n2FRo/edit 

Thanks!

**Comment by laurenluz** [comment]
oh gosh, so sorry, I lost this one, but just scheduled for tomorrow.

**Comment by oyealmond** [comment]
oh no worries! Thank you @laurenluz ! 💫

**Comment by c0ric0ri** [comment]
https://twitter.com/Giveth/status/1655271787402240002?s=20
