### ISSUE TITLE
Re share Panvala GIVtalk. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1349]
GM @laurenluz 💫

could you please review this draft to re share Panvala's GIVtalk? 

https://docs.google.com/document/d/1_rb97gMVAchDURSwjq-0gT8hY1CfogSWOmctCNc66QQ/edit 

thank you :D

**Comment by laurenluz** [comment]
thanks Almond - scheduled w/ minor edits.

**Comment by oyealmond** [comment]
reviewed the edits! Thank you L!
