### ISSUE TITLE
Octant Recipient Information - May 5

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1350]
Our QF matching pool has been chosen as a trusted recipient of public goods funding from Octant. We need to make a write up to satisfy all the requirements in their doc here: [Octant Recipient PDF](https://app.zenhub.com/files/278726184/e5e23ef8-ab8a-414a-8df8-b92f105c66da/download)

**Comment by laurenluz** [comment]
@danelsuga or @divine-comedian - can one of you read the PDF I attached to the issue w/ requirements, and then review this doc? It's our application for Giveth to get funds from Octant for our QF pool, long overdue

https://docs.google.com/document/d/1PIoJIcuA36VA6MDYb72LmEl_Wf7AnN_45perCR-CZ4g/edit

**Comment by danelsuga** [comment]
on it.

**Comment by laurenluz** [comment]
Sent!
