### ISSUE TITLE
ReFi Keyword Landing Page - SEO - May 19

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1352]
Create a landing page to improve our SEO for the keyword, "ReFi".

Once we've drafted and reviewed a landing page in Comms, we'll need to create a second issue in the Dev board to have the page created.

**Comment by laurenluz** [comment]
The 1st landing page is up already here: https://giveth.io/landings/web3-crypto-donation-platform

It should mention that we are on multiple chains (not just mainnet & gnosis), but other than that serves as a good template to write these others.

@danelsuga or @c0ric0ri - can you create a draft for this one? assign yourself if you can take it and then let's be sure to have 1 or 2 reviewers before passing to devs.

**Comment by danelsuga** [comment]
https://docs.google.com/document/d/1oD1fxHYLLY_hh8tidYZkINUcGNLmDEAsGTAt8Di8jN4/edit?usp=sharing

Here is the text for the SEO ReFi landing page. Let me know what you think please. It might be too long? In which case, the descriptions of the first list could be removed for example.

Should it have some charts or images? 

@c0ric0ri @ahmadabugosh

**Comment by c0ric0ri** [comment]
Hey @danelsuga awesome job on this! I left some points to check out. 

I do like what's written there, perhaps some of the points can be displayed side by side in the page design to save space.

And otherwise perhaps we can include an image or infographic on ReFi, if it's easy to find. And I mentioned social icons at the bottom

**Comment by laurenluz** [comment]
this is really cute! I gave it a read thorugh and left small comments. When you are all happy, someone should create an issue in [dapps-v2](https://github.com/Giveth/giveth-dapps-v2/issues/new/choose), add the link to the google doc and assign Mo, Tosin or marko to make a quick mockup.

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh anything stand out to you here that we should tweak for SEO purposes? Otherwise I'll go ahead and start an issue for devs.

**Comment by danelsuga** [comment]
FYI I arranged the bottom text as a circle and the same should be done with the top text (in a diff way that I describe). That will make it visually more appealing imo.

**Comment by ahmadabugosh** [comment]
hey @danelsuga, I left a few comments on ways we can make maximum this page's SEO effectiveness

**Comment by c0ric0ri** [comment]
@danelsuga just let me know when you feel good about this to go to development!

**Comment by danelsuga** [comment]
oh yeah! i think this one is done!

**Comment by c0ric0ri** [comment]
I'ce sent this to @MoeNick and @RamRamez to start working on it

**Comment by mosaeedi** [comment]
I created a template before for this kind of landing page, and I believe it's been developed. 
Why are we not using that template?
I know it's just for SEO purposes, but it can be a bit prettier if we use that template!

Just for reference -> [Figma link](https://www.figma.com/file/hNqwpebu4JCy1XIed2c862/Giveth-Public?type=design&node-id=244-21173&t=I4ejc12bNg1l5rTs-4)

CC: @laurenluz @MoeNick @c0ric0ri

**Comment by danelsuga** [comment]
That's fine if you want to use that template. I'm not sure what that entails. There are no images to add. It should just have the pieces of text around the central concept, in the two instances. Those themselves can be regarded as "images" to the eye of the viewer, but they are text because they are capturing SEO key terms. I don't really think we need to add images, etc. on top of all that. It really should just be clean and straightforward. Thank you!

**Comment by ahmadabugosh** [comment]
Thanks @mosaeedi , For this one, we can keep it simple since it's mainly an SEO page, even something like this page would be ok (just content and no special graphics or images): https://giveth.io/landings/web3-crypto-donation-platform

**Comment by danelsuga** [comment]
And was this one implemented @ahmadabugosh ?

**Comment by oyealmond** [comment]
https://giveth.io/landings/refi
