### ISSUE TITLE
Public Goods Landing Page - SEO - May 19

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1353]
Create a landing page to improve our SEO for the keyword, "Public Goods".

Once we've drafted and reviewed a landing page in Comms, we'll need to create a second issue in the Dev board to have the page created.

**Comment by laurenluz** [comment]
The 1st landing page is up already here: https://giveth.io/landings/web3-crypto-donation-platform

It should mention that we are on multiple chains (not just mainnet & gnosis), but other than that serves as a good template to write these others.

@danelsuga or @c0ric0ri - can you create a draft for this one? assign yourself if you can take it and then let's be sure to have 1 or 2 reviewers before passing to devs.

**Comment by danelsuga** [comment]
https://docs.google.com/document/d/1nTipoh7gAyGVENY8Ww4mmwQMKZouF_e3Krr52JHPpEQ/edit?usp=sharing

**Comment by laurenluz** [comment]
this is ready for review @danelsuga ? can you tag some reviewers you'd like on it?

**Comment by danelsuga** [comment]
Still working on it. Thx! But anyone can have a look if they want!

**Comment by danelsuga** [comment]
(It's mostly done but didn't want to waste anyone's time before I did all I could.)

**Comment by laurenluz** [comment]
Ok perfect, just tag people when you're done :)

**Comment by danelsuga** [comment]
that's my plan! ;)

**Comment by danelsuga** [comment]
I think it'd be great to get some eyes on this doc now. Thanks!

@c0ric0ri @ahmadabugosh

**Comment by danelsuga** [comment]
Thanks! I integrated most and will reduce tomorrow. 

I was overall feeling the same and with the refi page too. Bad I ally, I wrote a thing about each topic and then Giveth in relation. Seems like it could just be the first part with a mention of the second since they're just seo landing pages?

But yeah, let's hear from Ahmad from the technical side to see how to optimize!

Thanks!

**Comment by danelsuga** [comment]
This is ready for another review! Thanks. @c0ric0ri @ahmadabugosh 

https://docs.google.com/document/d/1nTipoh7gAyGVENY8Ww4mmwQMKZouF_e3Krr52JHPpEQ/edit?usp=sharing

**Comment by ahmadabugosh** [comment]
hey @mosaeedi @MoeNick, can we design this landing page on the new template and add it to the queue? https://docs.google.com/document/d/1nTipoh7gAyGVENY8Ww4mmwQMKZouF_e3Krr52JHPpEQ/edit

**Comment by mosaeedi** [comment]
Can you take a look at this?

https://www.figma.com/file/hNqwpebu4JCy1XIed2c862/Giveth-Public?type=design&node-id=820-47460&mode=design&t=cyOhRQBBKfdjrpwR-4

**Comment by MoeNick** [comment]
If you show the green light @ahmadabugosh I will assign it to Ramin.

**Comment by ahmadabugosh** [comment]
@MoeNick I left comments on this and I think it's good to go. Is it scheduled?

**Comment by MoeNick** [comment]
I was thinking its ready to go

https://giveth-dapps-v2-git-public-goods-in-crypto-and-6d2ace-givethio.vercel.app/landings/public-goods

If you put comments on Figma we should recheck again.

**Comment by ahmadabugosh** [comment]
@MoeNick We already passed that phase, so it's good to go. 

The only small thing is the button on the bottom should say "Explore Public Goods Projects on Giveth" and link to giveth.io/projects

**Comment by oyealmond** [comment]
@divine-comedian does this happened?

**Comment by divine-comedian** [comment]
Looks like its here!

https://giveth.io/landings/public-goods
