### ISSUE TITLE
Crowdfunding Platform Landing Page - SEO - June 2

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1354]
Create a landing page to improve our SEO for the keyword, "crowdfunding platform".

Once we've drafted and reviewed a landing page in Comms, we'll need to create a second issue in the Dev board to have the page created.

**Comment by laurenluz** [comment]
@c0ric0ri - "how to donate to crypto" doesn't make sense... also "how to donate on crypto" also doesn't make sense... what is the correct keyword here?

@ahmadabugosh

**Comment by c0ric0ri** [comment]
This was a typo, supposed to say "how to donate with crypto".

However, I would repurpose this issue to instead focus on the keyword "crowdfunding platform" which is better one to target next, as we just got through the first few top words "refi" and "public goods"

**Comment by c0ric0ri** [comment]
I went ahead with drafting this one positioned as a history and overview of digital crowdfunding, with a lead into Giveth. Let me know your thoughts, happy to tweak this with input.

https://docs.google.com/document/d/1qlipvoOE3r98zIGnQUYhvfRFJhfWMDfsAsQzQY6BEaE/edit

@laurenluz @danelsuga @ahmadabugosh

**Comment by danelsuga** [comment]
Thanks @c0ric0ri ! I appreciate all this content! I added a few comments but feel like I want to take more time with it when I get another chance (not this week).

**Comment by oyealmond** [comment]
https://giveth.io/landings/web3-crypto-donation-platform
