### ISSUE TITLE
Newsletter April 2023

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1356]

**Comment by ahmadabugosh** [comment]
Topics to cover in this Newsletter:

- Gitcoin round
- Celo and Optimism
- Reminder of referral program (mentioning Twitter space)
- Giveth in Catalan
- Taketh landing page

**Comment by c0ric0ri** [comment]
Input from @laurenluz: 

Let's skip Celo until we actually announce it
Mention AI April

**Comment by c0ric0ri** [comment]
Blurb on our active Gitcoin grant + some educational links on how to donate on gitcoin, how QF works, maybe there's a video walkthrough

**Comment by c0ric0ri** [comment]
PFP integration on the dApp - you can now set your Giver PFP as your profle pic!

**Comment by c0ric0ri** [comment]
looking great @ahmadabugosh , I left some tweaks and comments

**Comment by laurenluz** [comment]
ok, I reviewed, good job @ahmadabugosh

**Comment by ahmadabugosh** [comment]
Thanks @c0ric0ri @laurenluz I incorporated your feedback. There are still a couple of small pending issues in the comments https://docs.google.com/document/d/1nWS26fs00o_hCZkSzvCR37xGkaRGDV6OjnC8Umy-S8c/edit#

**Comment by laurenluz** [comment]
Looks good!

**Comment by ahmadabugosh** [comment]
Sent! 

@laurenluz Can we queue up a tweet?  Feel free to edit of course: 


"In our latest newsletter 📧

💙 How to maximize your impact in the @gitcoin Beta Round for Giveth, @givepraise, @commonsstack and across the Giveth Galaxy 🌌

🤖 Giveth AI Hackathon with @OpenAI 

🙌 Featured Project @HelpersSocial 

https://news.giveth.io/givnews16"

**Comment by laurenluz** [comment]
scheduled!
