### ISSUE TITLE
Email Gitcoin donors - Email Campaign - April 28

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1357]
We should send a couple emails to all of the donors on our list letting them know that we have another grant active this round. 

I would suggest 2 emails throughout the round since we try not to have too many emails, but would leave this up to the owner to decide.

We need to:
- draft the messages for 2 emails
- plan out when to send them

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh here's the issue for emailing donors to promote our grant. Let us know what support you need!

**Comment by c0ric0ri** [comment]
Thnks @ahmadabugosh I reviewed this and left comments

**Comment by ahmadabugosh** [comment]
First email sent, will send the next one on the 8th.
