### ISSUE TITLE
Top 10 Gitcoin Projects - Medium post - April 27

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1358]
Create a page or article to list 10 other gitcoin projects we want to promote. This could be projects with projects on Giveth, projects we really align with and want to elevate, projects also with big communities we want to reach.

To avoid dev work being involved, it would be easiest to create a page for this on Notion or on Medium.

Once the page is created, we can link to it in the What's Up on Giveth section of our homepage.

**Comment by c0ric0ri** [comment]
Thank you so much @danelsuga and @WhyldWanderer for stepping up to work on creating a page and selecting projects for this!

**Comment by danelsuga** [comment]
Hi! I've got 17 projects in the galaxy, I think...
I am putting in a quick one line description for each one.
I haven't checked if they're all on Giveth. I would be surprised if they weren't.

https://docs.google.com/document/d/12jTPYZinQiftD7qPh08mcrjsipxnberqe9HJoCaTXas/edit?usp=sharing

**Comment by danelsuga** [comment]
@ahmadabugosh @laurenluz Gettin you's in the loop here to see if this can get pushed out on Thursday now. I just need some reviews and support in direction. I'll put it on Medium if nothing else. Thank you!

**Comment by c0ric0ri** [comment]
@danelsuga I think medium or Notion are both fine for this so that we can instantly publish this week. I would avoid the website so we don't need to involve the devs for work on this. 

Jumping in to review.

**Comment by danelsuga** [comment]
Ok. But think we'd need at least something on the site to direct folks to it? There is a gap in our comms there generally speaking... (we've talked about this before, I know.) Thanks!

**Comment by danelsuga** [comment]
Not much to review btw. Just a blurb plus links and projects. (I will obviously clean it up when I go to publish.)

**Comment by WhyldWanderer** [comment]
Looking now!
I think that the blogpost or Notion is the best way to go as there are quite a few with no project on Giveth and it would be really nice to feature them all....

As far as linking to the blogpost, we can put it in the Whats up on Giveth section?

**Comment by c0ric0ri** [comment]
We can feature the article in our "Whats up on Giveth" section of the homepage, per discussion with @WhyldWanderer yesterday. This wouldn't require dev work.

**Comment by danelsuga** [comment]
Yayyyy!!! Thank you, gals! Sounds great! Leave me whatever is necessary and Ill do it tomorrow. 

Basically, I'll have the article ready to go, and then Ashley maybe we can sync after Community call? And embed it. Or you can just "pop" it in there. ;) 

Either way, I'll publish it tomorrow on Medium if all looks good to you's today.

**Comment by c0ric0ri** [comment]
We'll just need a graphic for the post, and for the What's Up on Giveth section we should have a 16 x 9 size graphic.

@NikolaCreatrix would you be able to work with @danelsuga to get the post added to the What's Up on Giveth section?

**Comment by danelsuga** [comment]
Ok. Great. Will do. Rodri is in my timezone so I can do that tomorrow. 

Also just got info from Lauren about ordering it based on the different rounds and the various groupings that go under them instead of going by project. Will sort that in the morn!

**Comment by laurenluz** [comment]
nice job @danelsuga ! small comments in the doc, and I see you got my message about the carts thing.

**Comment by WhyldWanderer** [comment]
Done reviewing!
I changed the structure a bit so that the descriptions come before the grant links.
I also left some small suggestions as well as added the links to their Giveth projects if they have one.

Thanks for getting this started Suga! Sorry our timezones are so out of whack

**Comment by danelsuga** [comment]
Thanks, everybody.

OK, this is as good as it gets, I think:
I thought it'd be good to put a table first and group them by round in it, but you can't put tables in Medium.
I thought about putting the groupings together anyway - like, having that first followed by the descriptions with their own individual links, but the thing would get so big and weird and long.
I know it would be good to have the groupings, but it feels impossible to do that in Medium in any reasonable way.
So I've just cleaned it up as much as possible.

It's not just that Medium is a bit clunky in that way, it's that the Gitcoin structure itself is still clunky (and I known they're working on it for future rounds, etc.!). But it all just means that this can't really look as streamlined as we would like.

In any case, contributors would still have to click on ALL the links to be able to build a cart anyway (or click on one, more likely, and add the others in their own way on Gitcoin through searches). Unfortunately, we cannot offer a link that already has a cart of all the grants.

I don't it matters really anyway. This is just to get a little exposure. It's not really a "tool" for building carts or anything, as much as we would like it to be. It's the best it can be just to highlight some pal projects and just to get the word out a bit. We can then tweet it and share it and so on.

**Comment by danelsuga** [comment]
Thanks, everybody!

OK, this is as good as it gets, I think:
I thought it'd be good to put a table first and group them by round in it, but you can't put tables in Medium.
I thought about putting the groupings together anyway - like, having that first followed by the descriptions with their own individual links, but the thing would get so big and weird and long.
I know it would be good to have the groupings, but it feels impossible to do that in Medium in any reasonable way.
So I've just cleaned it up as much as possible.

It's not just that Medium is a bit clunky in that way, it's that the Gitcoin structure itself is still clunky (and I know they're working on it for future rounds, etc.!). But it all just means that this can't really look as streamlined as we would like.

In any case, contributors would still have to click on ALL the links to be able to build a cart anyway (or click on one, more likely, and add the others in their own way on Gitcoin through searches). Unfortunately, we cannot offer a link that already has a cart of all the grants.

I don't think it matters really anyway. This is just to get a little exposure. It's not really a "tool" for building carts or anything, as much as we would like it to be. It's the best it can be just to highlight some pal projects and just to get the word out a bit. We can then tweet it and share it and so on.

**Comment by danelsuga** [comment]
Thanks @laurenluz !

https://blog.giveth.io/17-great-giveth-galaxy-projects-in-the-gitcoin-grants-beta-round-cfa874280a96

it's up! tweak it if needed! (no emojis... :P just didn't want to overwhelm it, you know. it's so busy and full and boring already. also thought about images for each project but just too much (and wasted time imo). lmk if you think diff.)

thaaaaaanks! 

tweet it and so on!! :D

**Comment by c0ric0ri** [comment]
Hey @danelsuga did Rodri provide you the image in 16 x 9 so we can update the homepage today?

**Comment by danelsuga** [comment]
I will get that.

**Comment by rodricastillo9013** [comment]
hey! 16:9 banner :)

![image](https://user-images.githubusercontent.com/61791380/235114514-3a8768b6-798e-4d33-863c-86b8bea8c189.png)

**Comment by danelsuga** [comment]
Thank you @rodricastillo9013 !

Is it @WhyldWanderer who will link it? Thanks!!
