### ISSUE TITLE
ReShare our last GIVtalk podcast (Gitcoin Beta Round) 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1363]
Hey @laurenluz! 

Could you review [this draft](https://docs.google.com/document/d/1cnuX49nLqjokHziBHtjqzHSvuMPDY870Z0fl5VRnLbg/edit) that shares our latest GIVtalk? 

Thanks!

**Comment by laurenluz** [comment]
all set! edited and scheduled
