### ISSUE TITLE
One Pager for Gitcoin Beta Round

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1364]
Create a cheat sheet with all the relevant information on our Gticoin grants to use when DMing our network for support.

**Comment by c0ric0ri** [comment]
Thanks @Cotabe for taking this one!

**Comment by c0ric0ri** [comment]
Hey @Cotabe I went ahead and moved the last 3 pages to a linked doc, added a Giveth logo and edited some of the copy. Let's get feedback from the outreach team on this.

<img width="907" alt="Screen Shot 2023-05-03 at 11 17 49 PM" src="https://user-images.githubusercontent.com/106524383/236054039-53f842b2-ba25-40af-a477-f04e8d30dcf8.png">

**Comment by Cotabe** [comment]
The Fundraising WG decided to reference project success stories.

I volunteer to take care of this and chose some stories.

The made the table nicer.
