### ISSUE TITLE
Optimism on Giveth - Tweet - May 8

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1365]
Optimism is now live on Giveth, so it's time to prepare an announcement tweet thread to let our community know.

Donations on Optimism are GIVbacks eligigble.

Details on which tokens we accept can be found here: https://github.com/Giveth/Roadmap/issues/64

Please look through this and confirm these details with MoeNick when drafting the thread for review. We should look to announce this on Monday, May 8th.

**Comment by laurenluz** [comment]
@c0ric0ri you really should have assigned someone to this and made sure it got done. now it's monday and since it was never assigned I have to last minute put something together.

**Comment by laurenluz** [comment]
so many things should not rely on me.

**Comment by c0ric0ri** [comment]
@laurenluz let me pick this up today, you don't need to take it

**Comment by c0ric0ri** [comment]
Draft is here, I am just looking to add some images:

https://docs.google.com/document/d/1JdmErrhRIpDul0m8bHixP7wNvtRb7A1XSUDtHASddCg/edit

**Comment by laurenluz** [comment]
thank you @c0ric0ri - that was great, and quick. I made edits and scheduled for tomorrow.
