### ISSUE TITLE
Promote next GIVtalk: support Giveth projects on Gitcoin. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1367]
hey @laurenluz :) 

Last minute favor, could you please help me [review the tweets I drafted ](https://docs.google.com/document/d/1mIumAKv72qor2TToxIIyuMKIV7CIycTZNokpIxKNKAs/edit)promoting our (last min) Monday Twitter Space please? 

Thank you so much!

**Comment by laurenluz** [comment]
scheduled. took me just 5 min, thanks for the great work!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1653822311026360321
