### ISSUE TITLE
Improving documentation Verification Process

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1368]
We don't clearly state what types of projects can get verified as well as giving more insights into the qualifying factors for the verification team. So I'm opening up this issue with the intention of creating more content explaining what we look at during the verification process as well as what makes the project eligible to participate in the program. This might be little tricky to explain, but I'll try.

I will work on a draft and then polish it together with @WhyldWanderer

**Comment by laurenluz** [comment]
Tagging @franculio here as well who can help with getting this up in the docs once it's done.

**Comment by NikolaCreatrix** [comment]
Okay finally getting back to this. Working on improving the documentation for https://docs.giveth.io/dapps/projectVerification

Edits and suggestions are in the document here: 
https://docs.google.com/document/d/1I3KeHFwC5w85v_W8BuigkPLEWMYTlkI1YC-mvj8cf5s/edit?usp=sharing

Ready for review @WhyldWanderer wdyt?

**Comment by danelsuga** [comment]
Quick review: looks great @NikolaCreatrix !

**Comment by NikolaCreatrix** [comment]
Wonderful, thanks Suga! @franculio it's ready to be uploaded into the docs, please. :)

https://docs.google.com/document/d/1I3KeHFwC5w85v_W8BuigkPLEWMYTlkI1YC-mvj8cf5s/edit?usp=sharing

**Comment by franculio** [comment]
This has been updated, closing the issue!
