### ISSUE TITLE
Projects ~ Google Form to Apply for GIVBacks

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#137]
- In order to apply, the user must fill out a Google form and provide the following information:
    - Official point of contact and contact info (email, github, or twitter) ✅
    - Are you a registered non-profit organization? If so, please share with us how we can verify your standing and if not, please tell us more about how your organization is structured. ✅
    - Short description of how they plan to use funds that are raised ✅
    - Check a box saying "I pledge that funds raised will be used for public benefit, not for personal gain" ✅
    - Check a box saying "I understand Giveth will be analyzing all donations looking for fraud or abuse. If Giveth has any reason to suspect abuse, I understand my donors may not receive any GIVBacks and that Giveth may share any evidence of fraud publicly." ✅
    - Check a box saying "We will only accept new external donations through Giveth, and if we are found to be recirculating our own funds through this system this is considered abuse of the system." (please rephrase) ✅
        - SHAME! SHAME!
    - Check a box saying "We know our donation data will be reviewed, and if it seems like in any way we are abusing the system, our donors will not receive GIVBacks, and we will lose our verified status." ✅
    - Google application: [https://forms.gle/ZDjgoyMx5qagioBU8](https://forms.gle/ZDjgoyMx5qagioBU8)
    - Link to edit: [https://docs.google.com/forms/d/1A9sInz_067mI8qwmyYOrO-1ATpGyNizSwDRGBzxAx14/edit?usp=sharing](https://docs.google.com/forms/d/1A9sInz_067mI8qwmyYOrO-1ATpGyNizSwDRGBzxAx14/edit?usp=sharing)

**Comment by ForestSoleil** [comment]
Google Form has been created. Is there a next step on this @willyogo ? Just looking for reviewers?

**Comment by WhyldWanderer** [comment]
I have reached out to the few people on the team that own projects on Giveth.io to begin filling out the form. 
We can solicit feedback in this issue about the form and make any necessary changes.
We will be holding the first verification party sometime this week.

This issue is related to #140 and #136

**Comment by Danibelle** [comment]
Reviewing!

**Comment by markoprljic** [comment]
Your full name instead of Main Contact's Full Name, and then Main Contact's Full Name (if there is a different) with checkbox "I'm the main contact"

> Besides being a beautiful ethical person, we want to make sure you have a reason to use the funds raised in the way that you say you are going to. Our goal is to ensure there is no fraudulent use of GIVbacks. Please let us know what reputation is at stake for you and/or your project. 

This is a confusing section, not sure what to add here :/

> Are you a registered non-profit? 

Should we add country where non-profit is registered? Feels natural to me to add it. 

> Please upload proof of your project's non-profit registration.

Sadly I don't have this document on file at the moment someone else from our org has it. Now I cannot complete the form because if this requirement.

I uploaded a dummy image and got this question...

> Okay, it sounds like your project is not a registered non-profit. Please tell us a bit about how your organization is structured.

I'm confused :/ I did select that I'm registered non-profit, why this question now?

**Comment by laurenluz** [comment]
> Main Contact's Full Name *

+1 on Marko's suggestion above regarding name... also this could be "Project Creator's Full Name" and another option "Organization Representative" and a checkbox "I'm the organization representative"

> Twitter, Github, or Email (please provide at least one) 

Suggest formatting... i.e. "Twitter, Github, or Email (please provide at least one and indicate which e.g. @ yourtwitter (twitter) 
@ yourgithub (github) @ youremail (email))

> Besides being a beautiful ethical person, we want to make sure you have a reason to use the funds raised in the way that you say you are going to. Our goal is to ensure there is no fraudulent use of GIVbacks. Please let us know what reputation is at stake for you and/or your project.

This is extremely confusing to me... I suggest taking out some of the extra words and then adding a clear example, like:

"Our goal is to avoid fraudulent use of GIVbacks by making sure that you have reason to use the funds in the way you say you are going to. What reputation do you/your project have to uphold? (e.g. "I am an active contributor to the Commons Stack, a well-known altruistic DAO that aims to develop and provide tools that empower communities in to design their own Commons. If I were to be caught fraudulently using funds for this project, I may lose my status as a member of the Trusted Seed, and would be outcasted from a community whose values I strive to uphold)

> Okay, it sounds like your project is not a registered non-profit. Please tell us a bit about how your organization is structured. 

I think another example here would do a lot to illustrate clearly what you want.

**Comment by GriffGreen** [comment]
+2 on Would be good to include a link to the project on the giveth.io site

**Comment by GriffGreen** [comment]
"Twitter, Github, or Email (please provide at least one)"

Make this 3 different questions and make them all optional

**Comment by WhyldWanderer** [comment]
Things to add:

Link to giveth project
reputation example
require email address for contact purposes
Notify what documentation will be needed and that they need to be accessible

**Comment by GriffGreen** [comment]
We need 3box integration to verify the address they are using to raise donations

**Comment by WhyldWanderer** [comment]
Updated Typeform can be found here.

https://the-commons-stack.typeform.com/to/GZSKJRoS

**Comment by WhyldWanderer** [comment]
> We need 3box integration to verify the address they are using to raise donations

relevant to https://github.com/Giveth/giveth-2/issues/286

**Comment by ForestSoleil** [comment]
**Edits for Typeform:**

- Edit intro paragraph to reflect edits in line below... namely GIVbacks
- Question #9 GIVBacks should be spelled GIVbacks
- Question #13 should ask "do you understand?" right now it's just a statement and yes/no does not make sense
