### ISSUE TITLE
Collaborate with CryptoDose for an article about Giveth

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1370]
An author from crypto dose has reached out to write an article about Giveth.
Find the information in Discord here: https://discord.com/channels/679428761438912522/790268394251354143/1103778555529281577

![image](https://user-images.githubusercontent.com/74267818/236320357-b5282a1e-edb6-42df-aab6-d3ef028f3325.png)

Is there someone that could team up with him to make sure he gets what he needs to make it happen?
Maybe when @danelsuga is back from vacation?

**Comment by danelsuga** [comment]
Yes!

**Comment by c0ric0ri** [comment]
Hey @danelsuga , could you provide a quick update here on where things are with this? (And if it's in progress, please update the issue status :) )

**Comment by danelsuga** [comment]
Just waiting for his reply. I'll ping him again. :)

**Comment by oyealmond** [comment]
Hey @danelsuga ! 
can we close this?

**Comment by danelsuga** [comment]
I will reach out to this guy again. He has never responded to me after the initial interest couple months ago.

**Comment by oyealmond** [comment]
thanks @danelsuga!

**Comment by oyealmond** [comment]
hey @danelsuga ! 
Do you heard back from him?

**Comment by danelsuga** [comment]
Never heard back. Putting this in the icebox.
