### ISSUE TITLE
GM! podcast season 2 launch! 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1371]
Hey @laurenluz ! 

Srry for the very last minute notice.. we're launching GM! season 2 this Friday, could you review these[ tweet drafts?](https://docs.google.com/document/d/1bzoTtCn_evKniaxOmPhBSYHxX1Tg3KFCC4h5OzEq0p4/edit) 

@rodricastillo9013 is almost ready w/ the episode 1 design, so we can start promoting on twitter...

**Comment by c0ric0ri** [comment]
https://twitter.com/Giveth/status/1657023346352050178?s=20

https://twitter.com/Giveth/status/1657037867850317830?s=20

https://twitter.com/Giveth/status/1656721356292083712?s=20
