### ISSUE TITLE
Instant Boosting Comms Messaging

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1374]
- [ ] We should prepare a Tweet for this
- [ ] We should mention this in our next newsletter @ahmadabugosh 

Here's the mini spec: https://www.notion.so/Instant-Boost-Mini-Spec-cea340e1bbf2456f8c7b237c07e5f8aa

**Comment by laurenluz** [comment]
FYI @c0ric0ri @oyealmond

**Comment by oyealmond** [comment]
hey @laurenluz ! 
Double checking on this, do we still need to implement this?

**Comment by laurenluz** [comment]
we got this out today: https://twitter.com/Giveth/status/1683463319825383425

it would be nice to write a few other tweets mentioning that you can affect the project sort... and it updates every 5 min. @SteffanThorn - do you want to write a few?

**Comment by laurenluz** [comment]
so basically, you can boost projects now... and based on your boosts, they will be updates in the project sort every 5 min

**Comment by SteffanThorn** [comment]
Made a bunch. Let me know which ones are good to schedule @laurenluz 
And which ones you like @oyealmond 

https://docs.google.com/document/d/1CurZu0uEaPP7PDwr__a9JZEFRE4-kLZMR7DpPFXYBxY/edit?usp=sharing

**Comment by oyealmond** [comment]
I asked for edit permission. @SteffanThorn 

I think that these need more work still. 
As the GIVpower pm, I would as @laurenluz input on these too

**Comment by laurenluz** [comment]
made an edit with the ones I think are good (w some tweaks). made it a new google doc because I could edit:

https://docs.google.com/document/d/1AgBfVCgvvC4oRaWbm9mPYZ3ARpQ2ud0HxYbJIjaSDyk/edit

**Comment by oyealmond** [comment]
Thanks @laurenluz! 
I scheduled them all. 1 every week in the next 4 weeks. Please feel free to jump into tweethunter and review them. cc @SteffanThorn

**Comment by laurenluz** [comment]
amazing @oyealmond !
