### ISSUE TITLE
send GM! season 2 press release

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1375]
hey @ahmadabugosh @danelsuga @laurenluz 

Could you help me review this [press release draft](https://docs.google.com/document/d/1tW2zWU8TyEV1xleFbqdph-dFYSfjNq3qU_CW0Pp6eR4/edit?usp=sharing)?

**Comment by danelsuga** [comment]
Wow! Looking good! And sounds amazing. 

I inserted a couple barely noticeable commas. 

And I thought taking out "the" before "crypto OG" was a good idea, but that is really just a matter of taste. 

It looks great. Well done. Can't wait.

**Comment by oyealmond** [comment]
thanks @danelsuga! 🤩
