### ISSUE TITLE
Aprendamos ReFi podcast launch - LinkedIn Post - May 17

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1377]

**Comment by Cotabe** [comment]
Here is the doc:

https://docs.google.com/document/d/1RgLdbIn6oapijGYBP2vpJTWyPiV55-shcLyCyvs3iUY/edit?usp=sharing

**Comment by Cotabe** [comment]
Who can help me review this and post it on our linked in and facebook?

@c0ric0ri @oyealmond

**Comment by c0ric0ri** [comment]
I can definitely help post it, and formatting looks good but would help to have a native Spanish speaker check it if @oyealmond can

@Cotabe do you have a cover image? That would improve the post

**Comment by Cotabe** [comment]
This doc has been translated to English. Can you review @oyealmond @c0ric0ri

**Comment by c0ric0ri** [comment]
Added my review @Cotabe

**Comment by Cotabe** [comment]
Thanks @c0ric0ri 

I made added the links and accepted most of the changes. I just have 3 questions that are outlined in the doc.

**Comment by c0ric0ri** [comment]
This is posted: https://www.linkedin.com/feed/update/urn:li:activity:7066427432848805888
