### ISSUE TITLE
Launch partners & supporters doc

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1379]

**Comment by Cotabe** [comment]
Here is the doc:

https://docs.google.com/spreadsheets/d/1TxaerqhGVLnEnWtzKn0GI0EYP1j6UmkYURVrWjErrw8/edit#gid=786627218

**Comment by Cotabe** [comment]
@brichis @oyealmond @CarlosQ96 @mateodaza 

Me pueden ayudar a agregar a más personas y comunidad de crypto, ReFi o impacto a este documento para el Lanzamiento de Aprendamos ReFi

**Comment by oyealmond** [comment]
síi creo algo que podrías hacer es preguntar en los grupos de refi por los mails de los que están dentro @Cotabe

**Comment by brichis** [comment]
No puedo editar el doc pero creo que faltan Celo, ReFi DAO, quizá algunos de Tokenización de Carbono?
