### ISSUE TITLE
Video description for EP1 - Aprendamos ReFi Podcast Launch

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1382]

**Comment by Cotabe** [comment]
Here is the draft: 

https://docs.google.com/document/d/1DTV3FOJVms7iOdY8B-PL6rGDAHh_PM6KcKvKFCmMDRw/edit?usp=sharing

**Comment by c0ric0ri** [comment]
@Cotabe are we keeping this in Spanish? What about having it in both languages?

@oyealmond for review

**Comment by c0ric0ri** [comment]
@Cotabe let's definitely have this in English at least. I think having Spanish below it is also cool, if there is room.

**Comment by Cotabe** [comment]
This has been translated

**Comment by c0ric0ri** [comment]
Thanks @Cotabe, I've made edits and this should be good to upload
