### ISSUE TITLE
Draft a press release for the launch of Aprendamos ReFi

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1383]

**Comment by Cotabe** [comment]
Here is the press release draft:

https://docs.google.com/document/d/1AE473eR6MHTC6RQpgsYt6Am1-rlCUi4ojRFdnvAXBx8/edit

**Comment by c0ric0ri** [comment]
@Cotabe who is this press release meant for? I'm asking as this is also written in Spanish.

**Comment by c0ric0ri** [comment]
Ok per our DMs you said you want to share it with some Spanish speaking groups from impact communities

**Comment by c0ric0ri** [comment]
@oyealmond would you be able to provide a quick review on this?

**Comment by oyealmond** [comment]
ready @c0ric0ri ! 
Left some edits for @Cotabe to review
