### ISSUE TITLE
July Updates for Giveth Homepage - Jun 23th. 

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1389]
Selecting topics we want to highlight in June in the What's Up on Giveth section:

https://www.notion.so/giveth/Homepage-Content-Updates-7551d8e2084b4ee19120b099f59846ea

**Comment by c0ric0ri** [comment]
The June section is ready for review before we post on the homepage. Let me know how this looks to you @oyealmond @danelsuga

**Comment by oyealmond** [comment]
great! one quick comment, @c0ric0ri 
could we replace the Optimism text w/ the Giveth - Optimism campaign ? 

Maybe the texto could be

We're supporting projects on Optimism by offering a 25 $OP token reward to the top 640 verified projects that add their Optimism address and start receiving donations through OP. Join & and stay tuned for your 25 $OP!

<img width="1920" alt="Op   Giveth" src="https://github.com/Giveth/giveth-planning/assets/110692280/50404bd5-8b87-41f8-9e48-97e0a3977589">

**Comment by danelsuga** [comment]
Great, @c0ric0ri, thanks! Looking good.

A little late to the party but I see an error in the Ambassador Program Typeform. @oyealmond maybe you can get this fixed? In English, you cannot say, "How should we call you?" It has to be "What".

**Comment by oyealmond** [comment]
done @danelsuga ! tnx!

**Comment by c0ric0ri** [comment]
Hey @oyealmond, thanks for the input - I updated the text to something shorter and changed the twitter link:

"You can now use Optimism on Giveth, and we’re offering 25 $OP to the first 640 verified projects who add their Optimism address to their profile. Join in to win 25 $OP!"

**Comment by oyealmond** [comment]
thanks @c0ric0ri !

**Comment by WhyldWanderer** [comment]
I am adding these updates right now...
It looks like the image for GM! Season 2 is not in the correct 16 x 9 aspect ratio so part of it is getting cut off.

@oyealmond are you able to adjust this in figma? or do we need to ask a designer?

**Comment by oyealmond** [comment]
hey @WhyldWanderer! thanks again for the help on this. here's the re sized image. 
![gm cover  ](https://github.com/Giveth/giveth-planning/assets/110692280/3355d7ec-1dc0-4e4e-b8e2-bd18c56e2cf5)
