### ISSUE TITLE
Projects ~ Get verified for the next round and know the date that I have to apply by to be accepted

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#139]
- As a Project, I want to get verified for the next round and know the date that I have to apply by to be accepted
***It's true the user only needs to apply one time to be eligible for GIVbacks. This is saying that when you apply that first time, you are applying to be eligible for the next round and beyond (as opposed to applying for the current round).
    - We will want to have a solid CONSERVATIVE calendar with exact cut off times that will be public and respected.
        - For example (A Hypothetical):
            - Round 1 starts on Sunday May 2nd at 10:00 am UTC
            - Round 1 ends and Round 2 Starts on Sunday May 16th at 10:00 am UTC
            - To be verified for Round 1 you must apply for verification before Monday April 26th at 10:00 am UTC
                - If we have extra time and resources to verify, and people submit late, we can exceed expectations and verify late projects for the next round... but all these verifications must be processed chronologically. We should never play favorites... It doesn't matter if Satoshi Nakomoto pushes to get their charity verified despite being late, their charity cannot be verified for the next round with out us also undertaking the verification process for all the people that submitted before them.
            - Round 1 GIVBacks will be awarded on or before Thursday May 20th at 10:00 am UTC and the portion that is claimable can be collected at [https://giv.giveth.io/dashboard](https://giv.giveth.io/dashboard) (or whatever)

**Comment by markoprljic** [comment]
@ForestSoleil I noticed this issue is created in Giveth Planning repo and I believe I have similar issues already created in this epic here https://github.com/Giveth/giveth-2/issues/581 Is this one a duplicate?

**Comment by ForestSoleil** [comment]
Hi Marko, we created GitHub issues for each individual line item of the MVP spec. If you prefer to just have your issue Giveth/giveth-2#581 linking to the MVP spec, that works as well.
