### ISSUE TITLE
Aprendamos ReFi Podcast - Email - May 22

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1390]

**Comment by Cotabe** [comment]
Here is the email draft in English 

https://docs.google.com/document/d/1Dqq2s4dtOqJBsCJXVSlCPvPvp4Ta9G-npXlTwJZBzqE/edit?usp=sharing

Can you help me review @c0ric0ri @oyealmond

**Comment by c0ric0ri** [comment]
Hey @Cotabe I reviewed the english draft. We want this to go out on Monday?

@ahmadabugosh once the edits have been finalized, can you help put this out on Monday to announce the podcast?

**Comment by Cotabe** [comment]
Great edits @c0ric0ri, the email is finalized.

**Comment by c0ric0ri** [comment]
Closing this as we decided not to proceed with emailing since we cannot segment the audience easily enough for this announcement, and we are already sending out an email this week about optimism. Instead we will add an announcement about the podcast launch to our newsletter.
