### ISSUE TITLE
Optimism Rewards campaign Twitter Space. May 24

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1392]
Hey @laurenluz !

Could you review[ this Twitter Space prep](https://docs.google.com/document/d/1j8VWchjttBp24io63vTncrDvlvy0RJPxIC_gmTdcbbk/edit) and Tweets plz?

**Comment by laurenluz** [comment]
Awesome @oyealmond !

I reviewed & scheduled the tweets. As for the space content, tbh, I'm not super familiar w/ optimism. I'm asking Griff & Brichis to provide additional feedback in there.

@brichis @GriffGreen

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1660299925689712641
https://twitter.com/Giveth/status/1660979396012826624
https://twitter.com/Giveth/status/1661401926993321987

**Comment by oyealmond** [comment]
Hey @laurenluz , could you review this tweet promoting the podcast of this GIVtalk please? 

https://docs.google.com/document/d/1nyGxYC21pX14uHAPpIviFMmfJtcPjM5M6HkZYJBz9J8/edit

**Comment by oyealmond** [comment]
hey @laurenluz! gm :) 

Not sure if you're able to review this one.

**Comment by laurenluz** [comment]
Hey @oyealmond - thanks for the reminder, I missed it. just scheduled for next week, made some edits in the doc (like I added another tweet that links to giveth.io/create inviting people to create their projects too)

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1666052836600291329
