### ISSUE TITLE
Zero-fees Documentation / mini blog

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1394]
In the updated version of the project page, we have a box that looks like this:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ce759d63-3919-46d3-9347-79d77f866cc6)

We need somewhere to link people to from "learn about our zero-fee policy" and I think the easiest thing to do is add something to our documentation. This could also be a short blog.

Key points:
- unlike most web2 donation platforms, we don't charge any fees to create a project, send a donation, or receive a donation
- people have to pay gas fees (as usual) to donate in crypto, but Giveth isn't skimming off the top of donations
- we believe that projects should get 100% of the donations to empower them to do good work
- donations are P2P - from the donor's wallet to the project's
- we're working on building economic models instead of business models - leading by example to create a new way to fund public goods

Might be worthwhile to mention something about how Giveth funds itself... creating demand for issued token (in theory)... and imperfect world so grants, donations.

Can pull some ideas from [this talk](https://www.youtube.com/watch?v=PQS9Ux5u9p8) to build this out, maybe think of some FAQs.

Worthwhile asking @GriffGreen or @willyogo some questions for inspiration & to add to this.

@c0ric0ri @ahmadabugosh @danelsuga - are any of you able to tackle this on in the next couple of weeks?

**Comment by laurenluz** [comment]
FYI @mosaeedi @MohammadPCh

**Comment by MohammadPCh** [comment]
@laurenluz Thanks, Let me know when the link is ready.

**Comment by c0ric0ri** [comment]
Here is a first stab at a draft, just want to temperature check that this is on the right path:

https://docs.google.com/document/d/1ezMfkuuSnSqAH25E9ZiifGWlHbSrSxbXCz7k4GmEbRg/edit

@laurenluz @danelsuga @ahmadabugosh

**Comment by laurenluz** [comment]
I think this is 100% on the right path. I left a few comments with thoughts/feedback. would love to see some FAQs too perhaps. 

Great work @c0ric0ri !

**Comment by danelsuga** [comment]
Thanks, @c0ric0ri. I did just a quick review.

**Comment by ahmadabugosh** [comment]
Added some comments too

**Comment by c0ric0ri** [comment]
Thanks @laurenluz @ahmadabugosh @danelsuga , I incorporated the feedback and left the comments there. Please let me know if this looks good now.

**Comment by laurenluz** [comment]
@franculio - can you get this up in the documentation? I'm open to your suggestion on where it should go... somewhere in DApps, I think... and perhaps we have a section called like "Zero-Fees"

**Comment by laurenluz** [comment]
This was so great @c0ric0ri

**Comment by laurenluz** [comment]
Hey Franco! that's great - can you get it up today? :)

**Comment by franculio** [comment]
Doc created https://docs.giveth.io/whatisgiveth/zero-fees

Closing issue
