### ISSUE TITLE
Quadratic Funding Documentation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1395]
We should write this after we develop QF some more... but also creating the issue because I want to make sure we have it link to: https://docs.giveth.io/quadraticfunding

because I told Cherik to put that link in here for "how it works" 
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/bbb8e65d-41c5-4ac5-bcd1-c6f63f377995)

FYI @franculio @divine-comedian

**Comment by franculio** [comment]
Draft here: 

https://docs.google.com/document/d/1rsEO4jsLIGRtLgiIOqrCu4CcOERgtRehcoml1foJHk4/edit?usp=sharing

@laurenluz

**Comment by laurenluz** [comment]
@danelsuga - can you review the docs here? https://docs.google.com/document/d/1rsEO4jsLIGRtLgiIOqrCu4CcOERgtRehcoml1foJHk4/edit

**Comment by danelsuga** [comment]
Reviewed!

**Comment by franculio** [comment]
The doc is live: https://docs.giveth.io/giveconomy/quadraticfunding/

Still needs some reviewing but it can be edited whenever.

**Comment by franculio** [comment]
Link has changed to https://docs.giveth.io/quadraticfunding/

**Comment by divine-comedian** [comment]
Added more comments fix suggestion the word doc, I found a nice visual explainer for the QF formula which will be useful. 

Let me know when the latest version is up @franculio  and I can help add some markdown styling

**Comment by laurenluz** [comment]
thanks for the edits @divine-comedian - if one of you can but these edits up, it would be great.

also... it would be nice to update the images if we can (maybe after the round is live?) the esimated matching images shown are actually using an old calculation that we have since updated.. so they are a bit inflated.

**Comment by franculio** [comment]
I can have these edits up today, thanks @divine-comedian!! I'll change the images tomorrow once we are live @laurenluz

**Comment by franculio** [comment]
Doc updated to last version @divine-comedian

**Comment by oyealmond** [comment]
https://docs.giveth.io/quadraticfunding
