### ISSUE TITLE
Panvala Stamps Distribution - Tweet

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1396]
The Panvala Stamps Program just had their latest distribution round and here are the top Giveth projects that received support from people collecting stamps.
![image](https://github.com/Giveth/giveth-planning/assets/74267818/7d57c185-fb16-491b-888e-60dfd38b29fe)

Lets make a tweet about this!
You can also link to the GIVtalks podcast that talk about the program and how it works

Link to podcast episode: https://open.spotify.com/episode/2a1D9eY3CfB6Fv4jygVT8t?si=b7ec92353d4c4e75

**Comment by c0ric0ri** [comment]
Here is the draft for review: https://docs.google.com/document/d/1xHQ265GXrN_d-OVt9fYOd0XVR4W2cX25eH44peIUHmc/edit

@oyealmond @danelsuga @laurenluz

**Comment by oyealmond** [comment]
thanks @c0ric0ri ! I  swapped the GIVtalk link w/ our youtube Panvala recording. 
I think is ready for @laurenluz final review and schedule. 

Thanks again.

**Comment by laurenluz** [comment]
scheduled

**Comment by c0ric0ri** [comment]
https://twitter.com/Giveth/status/1664603282692513792?s=20
