### ISSUE TITLE
Project Feature - Tweet - Instagram - June 3

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1397]
This project has reached out to us asking for us to feature them on World Bicycle Day - June 3rd.
They are a verified project that provides quality bikes, helmets and locks to disadvantaged kids who would otherwise miss out on the physical, mental and social benefits of owning a bike.

Can we support them and feature them in a tweet and an instagram post?
Their website: https://variety.org/
Their Giveth project: https://giveth.io/project/variety-bikes-for-kids
Their instagram: https://www.instagram.com/varietyinternational/
Their twitter: https://twitter.com/VarietyGB

So far, they have been communicating via email... I can share that info if necessary or I can just let them know once the post has been drafted and is ready to go.

**Comment by SteffanThorn** [comment]
drafted the tweet. 

https://docs.google.com/document/d/1nHdBS4TAdjN2VA62xox8-Xo2z3ezYp-RmehfsFmhoIE/edit?usp=sharing

**Comment by oyealmond** [comment]
oh, does this tweet went out? @SteffanThorn It was great :')

**Comment by laurenluz** [comment]
@WhyldWanderer - are you still in contact w/ them? we can include them in our verifed projects tweet thread perhaps with @NikolaCreatrix  if this doesn't make sense anymore.

or happy to reword/share this some other day.... let me know.

**Comment by SteffanThorn** [comment]
I'm sorry I didn't schedule this. I think this was right at the beginning of our transition and I wasn't clear on scheduling myself or not. 

As Lauren said, we could include them in the next verified projects thread. And I'll clearly say I scheduled this time.

**Comment by laurenluz** [comment]
@NikolaCreatrix - can you remember to add this into your next verified projects tweet thread? then we can close the issue.

**Comment by NikolaCreatrix** [comment]
Yes, okay for the next thread.
