### ISSUE TITLE
Nonprofit Tweets 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1398]
@SteffanThorn made these tweets: https://docs.google.com/document/d/1fWQXFuvSD0wfaKKo-g-dw5K3oeJcIXIr1g11w8WwnpU/edit

I left comments to be reviewed before scheduling.

Trying to get Stee integrated with our Giveth planning flow.

**Comment by laurenluz** [comment]
@SteffanThorn - next steps to finish this out:
- resolve comments in the doc
- scheudule approved tweets in tweethunter
- make notes in the google doc if tweets are scheduled
- leave comments in here (github) with updates

**Comment by SteffanThorn** [comment]
they have all been posted except 2. 
1 I'm forgetting and the other I've moved to another doc. 

Moving this to done.

**Comment by oyealmond** [comment]
@SteffanThorn can we close this one?

**Comment by SteffanThorn** [comment]
Yes
