### ISSUE TITLE
🌞 GM! episode 2 tweet promotion. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1400]
Hey @laurenluz , could you please review [this draft ](https://docs.google.com/document/d/1_pk2LusTV7hazfi4ksmAngMissMLiihZN2y4BVpDZns/edit) promoting the episode 2 of GM! please? 

Thanks!

**Comment by oyealmond** [comment]
to get more listeners we're changing to promote the episode after is launched. 
Keep the 1 hr before it starts tweet. 

Thanks @laurenluz !

**Comment by oyealmond** [comment]
hey @laurenluz ! 
I tweaked the original tweets to have afterwards comms. 
Could you review [these drafts ](https://docs.google.com/document/d/1_pk2LusTV7hazfi4ksmAngMissMLiihZN2y4BVpDZns/edit)please?

**Comment by laurenluz** [comment]
scheduled them - thanks @oyealmond

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1663878517392650240
