### ISSUE TITLE
Updating new chains in "Create a project" doc

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#1402]
Updating images and info in https://docs.giveth.io/dapps/createproject
Adding information about Optimism wallet compatibility. 

@c0ric0ri

**Comment by franculio** [comment]
The draft is ready to be reviewed with the info and new images. Could you please give it a read @danelsuga ?

**Comment by oyealmond** [comment]
hey @danelsuga ! did you already provided feedback on this?

**Comment by danelsuga** [comment]
Apologies @oyealmond @franculio. I have reviewed it now.

**Comment by franculio** [comment]
This has been updated, closing issue!
