### ISSUE TITLE
Newsletter May 2023

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1403]

**Comment by c0ric0ri** [comment]
- Gitcoin grant round - thank the community, add in a couple nice looking stats
- Optimism launch (as well as giveaway)
- Octant NFT claim: @laurenluz can provide more context
- Panvala stamps outcome

**Comment by WhyldWanderer** [comment]
Spreadsheet with the information about Panvala Stamps outcome - https://docs.google.com/spreadsheets/d/16eBE4uEJk5_3uo1FTo0-N87K4NBhB2RuhcsnbT0yj9U/edit#gid=2011529276

Stamps website: https://www.panvala.com/stamps

GIVtalks Twitter Space recording about Panvala Stamps program: https://youtu.be/z1wLX1QbkNU

**Comment by ahmadabugosh** [comment]
This is ready for review: https://docs.google.com/document/d/1PN3PGCBuIv6_lQh7jAci0L1rPR3KYiznJrv5z2jInlU/edit#

@danelsuga @laurenluz

**Comment by WhyldWanderer** [comment]
Panvala didn't make the cut?
We have this cool infographic now... 

![image](https://github.com/Giveth/giveth-planning/assets/74267818/4d2d216d-ec1d-48b0-9b64-05d8fce1cea7)

**Comment by c0ric0ri** [comment]
Left some comments and tweaks @ahmadabugosh, looks pretty good!

**Comment by danelsuga** [comment]
also reviewed.

**Comment by ahmadabugosh** [comment]
hey @WhyldWanderer if you can give me a 1 to 2-sentence blurb I could include Panvala (I just wasn't sure exactly what to say and where to direct people). 

@c0ric0ri For the ambassador program, is there anything else we can share besides the Typeform to give people more context about the program?

**Comment by oyealmond** [comment]
@ahmadabugosh added a text for Ambassadors & Panvala. Please check them out!

**Comment by WhyldWanderer** [comment]
Something like this maybe??

"Congratulations to Emprende DAO, Shenanigan, 1Hive Gardens, Follow the Black Hare, and LunCo for being the top Giveth projects to receive funding in the last Panvala Stamps Program distribution! Find out how your project can be a part of this program by clicking here or listening to this GIVtalks podcast episode."

Link to each project name to their project page on Giveth
https://giveth.io/project/emprende-dao
https://giveth.io/project/shenanigan
https://giveth.io/project/1hive-gardens-0
https://giveth.io/project/follow-the-black-hare
https://giveth.io/project/lunco-robotics-engineering

Link to the Panvala Stamps page: https://www.panvala.com/stamps

Link to the podcast episode on YouTube: https://www.youtube.com/watch?v=z1wLX1QbkNU&list=PL4Artm1rmCWHKWlrB9SoLdjbRfgn5KB_A&index=4

**Comment by oyealmond** [comment]
Maybe we can cut it in two. @laurenluz (for your review): 

1/ 

🌟 Exciting Updates in our latest GIVnews! 🌟

⛓️ Giveth is now on @optimismFND & @Celoorg

🔴 Get 25 $OP adding @optimismFND to your verified project

🌞 In the latest GM! podcast @thegrifft and @jasvinbhasin, delve into the intersection of web3 and AI. 🧵

1.1/

🫶 New partners @gateway_eth working together towards decentralized giving.

👩‍👧 Featured Project @WhisperOrphans 

Discover the latest happenings in our blog! 👇 

https://news.giveth.io/givnews17

**Comment by laurenluz** [comment]
Thanks @ahmadabugosh @oyealmond - I scheduled it as one:

> In our latest newsletter:
> 
> ⛓️ Giveth is now on @optimismFND & @Celoorg
> 
> 🔴 Get $OP rewards as a verified project
> 
> 🗣️ New podcast on web3 and AI w/ @thegrifft & @jasvinbhasin
> 
> 🫶 New partner @gateway_eth 
> 
> 👩‍👧 Featured Project @WhisperOrphans
> 
> Check it out!
> https://news.giveth.io/givnews17

I like fitting it in one tweet, I notice that the 2nd tweet in a thread doesn't get much engagement usually, unless it's special somehow. I also am trying to avoid non-dictionary words like "GIVnews" because I think the algo doesn't like them... but I like the addition of context, i.e. "in our newsletter"

**Comment by laurenluz** [comment]
https://twitter.com/Giveth/status/1664646639145852930
