### ISSUE TITLE
Gateway.fm Partnership Announcement - Tweet - May 26

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1404]
A Twitter post announcing gateway.fm as an infrastructure provider for Giveth. They are supporting Giveth by providing pro-bono infrastructure services on the RPC layer.

Details from @geleeroyale:
The idea here is that they give us infrastructure for free, and we promote them a little as being our supporters. They are very value aligned and don't know how to get recognized for doing cool things for the community (i.e. they run all the major infrastructure for Gnosis Chain) so I think there might be genuinely interesting angles to explore (for blockchain geeks at least and everyone who cares how infrastructure is run.

**Comment by SteffanThorn** [comment]
Got a draft tweet. 
Maybe someone who's tech savvy could add some input into what they do. 

https://docs.google.com/document/d/1zmaZ09WihYWZ7ZrULXUw36-iN9ucnYc0hBfz0zkeKnI/edit?usp=sharing

**Comment by geleeroyale** [comment]
I asked my robot friend to collaborate and left a tweet thread in the google doc. I don't think we need to be more technical than this - please take your pick 🙃

**Comment by SteffanThorn** [comment]
I've made a few tweets that are more palatable for twitter. 

Looping you in @laurenluz

**Comment by c0ric0ri** [comment]
Checking for the Comms contact person at gateway.fm

**Comment by c0ric0ri** [comment]
Nice, I left some comments and changes on the drafts @SteffanThorn, I kind of like each of them in a different way. 

The goal is to announce them as a partner and give them some exposure and I think providing a pitch in the tweet the way you wrote it is the best thing we can do to support them.

Perhaps use one of these drafts soon, and keep one or two others for later on.

Also they have a press kit with logos etc, do we want an image for this first tweet perhaps? https://gateway.fm/press-kit/

**Comment by laurenluz** [comment]
I cleaned up @geleeroyale's thread a bit and got some technical validation on it, and scheduled for next week.

There were some inaccuracies in other tweets there @SteffanThorn

**Comment by rodricastillo9013** [comment]
![image](https://github.com/Giveth/giveth-planning/assets/61791380/e39fbd3d-b50f-4352-9813-ec46820e9bf6)
Hey all! @c0ric0ri

**Comment by SteffanThorn** [comment]
I still think some follow up tweets would also be good. repurposing content for our partnerships is great because content on twitter is not evergreen. 

I saw I got the talking part of RPC wrong. no other comments about what's wrong with the tweets?

**Comment by laurenluz** [comment]
yeah that would be great Stee.

@geleeroyale would be able to help you from the tech side. you could also ask mohammad, carlos, mitch, or try another dev if you want to just ask some questions in a DM. (this is what I would do).

**Comment by SteffanThorn** [comment]
I've added 2 new tweets. Hopefully I'm more correct now.

**Comment by laurenluz** [comment]
Hey @SteffanThorn I still think they might be wrong, though I'm not 100% sure. Did you/can you check in with Kay, Carlos or Mitch on these?

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1668227170823462916
