### ISSUE TITLE
Adding Optimism GIVbacks - need to update docs for GIVbacks & GIVstream

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1406]
This feature is not yet released, but when it is, we will need to adjust our docs accordingly.

**Comment by laurenluz** [comment]
We should also mention in our docs that the 1st 640 projects who add an optimism address, get 25 OP & the details of this campaign: https://twitter.com/Giveth/status/1660299925689712641

**Comment by franculio** [comment]
Hey @laurenluz is there a date for when this is going to be released so I can start the draft?

**Comment by laurenluz** [comment]
I hope it is live before August 8.

**Comment by franculio** [comment]
Info about Optimism has been added to the GIVbacks and GIVpower docs. I still need to add the info in the GIVstream doc. there's a couple of things I'm not sure about. 

<img width="895" alt="Captura de pantalla 2023-09-07 a las 12 02 52" src="https://github.com/Giveth/giveth-planning/assets/79286405/87f20d5e-41dd-4967-b3e1-8409ebc28881">

That is the part that need to be changed, the Mainnet farm is not live anymore right? 

Here's a draft with the changes: 
https://docs.google.com/document/d/1mG98nevyK7aJUzAJYA5ioz1nD8uWvM3vPd_2WbpIdd0/edit?usp=sharing

**Comment by laurenluz** [comment]
I left edits in the doc @franculio. once you accept the, it should be good to go up and we can close this.

**Comment by oyealmond** [comment]
@WhyldWanderer Ash, can you integrate this to our documentation? I believe it was almost done. 

Should I move this to Notion @laurenluz?

**Comment by oyealmond** [comment]
Done. Thank you. https://www.notion.so/giveth/Adding-Optimism-GIVbacks-need-to-update-docs-for-GIVbacks-GIVstream-4a38b6d3adbd42f7a917873128c32e0d?pvs=4
