### ISSUE TITLE
Giveth Optimism campaign meme contest. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1407]
@laurenluz could we throw a meme competition on twitter and reward w/ 25 OP tokens (whenever we get them) to the best meme around our campaign w/ Optimism? 

Some examples. 

![bob.jpeg](https://images.zenhubusercontent.com/62f65d77fa19b9bc859863bc/bc420dc1-5373-4967-bee4-4fbe24c9c2b5)

![interesting. .jpeg](https://images.zenhubusercontent.com/62f65d77fa19b9bc859863bc/59b4c773-defd-4fd5-a43e-ddf2b019cc07)

![Giveth Opt 1.jpeg](https://images.zenhubusercontent.com/62f65d77fa19b9bc859863bc/acf13c67-bf88-4c62-8b65-256bad35da4b)

Let me know your thoughts. 

Thanks!

**Comment by laurenluz** [comment]
Love it Almond!! And those memes are great!!

**Comment by laurenluz** [comment]
lmk if you want me to scheduled it, or what I can help with

**Comment by oyealmond** [comment]
great! if you like the idea I can prepare a thread explaining our competition. Sharing it later today! @laurenluz

**Comment by oyealmond** [comment]
Ready for your review @laurenluz https://docs.google.com/document/d/1-L30BllGJdBuY2GsJdMPv8yU1e3cWdLr09P7jfFGWR0/edit

**Comment by oyealmond** [comment]
hey @laurenluz! 
wdyt of this competition? If we already have too much Optimism we can dismiss this one.

**Comment by laurenluz** [comment]
no, I like it! Still have the tab open... just haven't got to it. A couple of things I was thinking:
- we need to get confirmation that we can actually give some OP to the winner of the competition - can you check with @GriffGreen  on his thoughts?
- would be good to follow up with @spectoregia @hanners-717 or @Cotabe  to find out exactly when/if we are actually going to get the OP needed for all this stuff... and if it would be good to take a small amount out for the competition
- we should be more specific in the tweet about what kinds of memes would be good winners... some examples of some ideas... some messages we'd like people to try to convey - this is so the quality of memes we get have a chance to be better 🤔

**Comment by oyealmond** [comment]
oh great thoughts! Thanks @laurenluz! 
Let me start w/ this right away.

**Comment by oyealmond** [comment]
talked w/ @spectoregia . She mentioned we can figure out this contest until we get the funds (after we pass KYC). Moving this to the icebox for now.

**Comment by oyealmond** [comment]
I think we could do this campaign if we want too now. 
cc @laurenluz @surbhiaroraa

**Comment by laurenluz** [comment]
yeah! I think this is a cool idea... but perhaps we should be give some more guidelines on the memes. like rewards go to people who have the best memes about onboarding nonprofits to optimism... or about using giveth & optimism to fundraise.
