### ISSUE TITLE
Make NFT art for ETH BCN Impact Quests

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1408]
We will be facilitating Impact Quests at ETH Barcelona this year in a similar fashion as we did at ETH Denver.
We will still go with the "Giveth Galaxy" space theme. Can also incorporate anything that is local to Barcelona. (skylines, landmarks, etc)

People will need to complete tasks in order to receive the NFT. 
Here are the quests that we have so far:

 - Cosmic Contribution - donate to a local Barcelona project on Giveth
 - Social Media Supernova - make a tweet featuring your 3 favorite Giveth project
 - Planetary Provisions - Donate food items
 - Moonward Mutual Aid - donate used clothing or hygiene supplies 
 - Spacewalker Sweep - pick up trash on your way to the conference
 
 Each one of these quests will need a design for a badge to award people upon completion.
 There will be more quests coming as we network with local non-profits but we should at least get a head start on these as to not get crunched for time.
 
 We will want to make different designs but here is the issue for the ones we made for ETH Denver for inspiration...
 https://github.com/Giveth/giveth-planning/issues/1137

**Comment by WhyldWanderer** [comment]
Hey @rodricastillo9013... just checking in on this. I saw that you commented in the design channel that you will be working on it. 
Let me know if you have questions or need more details.

**Comment by rodricastillo9013** [comment]
Hey @WhyldWanderer  This week I send you the progress and we continue working on polishing the designs based on your feedback :)
