### ISSUE TITLE
EP2 Twitter thread & linked in post - June 5th

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1413]

**Comment by Cotabe** [comment]
- [ ] Prepare drafts @Cotabe May 29th
- [ ] Review the drafts May 31st
- [ ] Final versions June 1st
- [ ] Share with launching partners before release June 1st

**Comment by Cotabe** [comment]
Here are the drafts for EP2 comms:

Twitter: https://docs.google.com/document/d/16niSqXv6mdORVixAqJrTlYQB4smvsdrkOnXUOP4ZcHc/edit

Linkedin: https://docs.google.com/document/d/1YaT4NzJLu0M5GtpPu8gg72MXglaZJLXeBBHUuoX3_Cs/edit

**Comment by Cotabe** [comment]
@laurenluz 

Hi Lauren, can you help me review this tweet?
https://docs.google.com/document/d/16niSqXv6mdORVixAqJrTlYQB4smvsdrkOnXUOP4ZcHc/edit

**Comment by laurenluz** [comment]
went out today. in the future please try to give a couple more days of notice.. asking on a friday night to schedule something for a monday morning isn't great.

https://twitter.com/Giveth/status/1665735745242374147
