### ISSUE TITLE
EP3 Aprendamos Refi Twitter thread & linked in post - Aug 7th

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1414]

**Comment by Cotabe** [comment]
Here are the drafts for EP3 comms:

Twitter: https://docs.google.com/document/d/1cFjfkcGgOZJoLIFjzoJAnBI2Qo9IRs7kZVqWmuexYkI/edit

Linkedin: https://docs.google.com/document/d/1HjanX48wKSppJaOmUpLkXUF7QYY3WR6rO6EpWqFOAfw/edit

@oyealmond can you review it?

We only need to change the links

**Comment by oyealmond** [comment]
Episode already scheduled on Tw & LinkedIn. @Cotabe 
https://youtu.be/iH9tgrj7SGs

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1688583375152418816 

https://www.linkedin.com/feed/update/urn:li:activity:7094195459098869760
