### ISSUE TITLE
EP5 Twitter thread & linked in post - August 28th

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1416]

**Comment by Cotabe** [comment]
Here are the drafts for EP5 comms:

Twitter: https://docs.google.com/document/d/1S0pbEs4kW9-KvBNlpPybfvnjznFYtLHuInHxTu7rD2M/edit

Linkedin: https://docs.google.com/document/d/1hC_qn98b0fVK5YJxw3NuPYpQprBd-O4-VqqyK6vB6l0/edit

@oyealmond can you review it?

We only need to change the links

**Comment by oyealmond** [comment]
this is scheduled on LinkedIn! 
cc @SteffanThorn . for your knowledge.
