### ISSUE TITLE
GIVbacks blog post

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#142]
- As a Giver, I want to learn more about GIVBacks and how it works.
    - An article explaining how GIVBacks work is published to Giveth's medium or wiki, and linked to from the tooltip above " Learn more about GIVBacks."

**Comment by WhyldWanderer** [comment]
this issue is redundant https://github.com/giveth/giveth-planning/issues/163

**Comment by laurenluz** [comment]
@WhyldWanderer is picking this up from what I started w here: https://docs.google.com/document/d/1cfpVRJD0d9OJPzlwLPhzfueVOMLc7gBOG1v5VxUZOcQ/edit#

**Comment by laurenluz** [comment]
will wait on this for after launch

**Comment by WhyldWanderer** [comment]
Maybe one of the design team peeps can put together a cool graphic that explains the schedule of rounds similar to this... https://docs.google.com/spreadsheets/d/1GBZ7BxLWOxDxJCB9ExF4RdKEqM83QuaXmc4kHnqw6sA/edit#gid=0

**Comment by WhyldWanderer** [comment]
Just want to leave a comment here that we should make sure to be clear that projects cannot receive GIVbacks for donations to their own project or other verified projects.

**Comment by laurenluz** [comment]
should include future plans for GIVbacks evolution

**Comment by laurenluz** [comment]
Ready for QA @WhyldWanderer @Brodyann7 @divine-comedian @ForestSoleil 
https://docs.google.com/document/d/1D6-Sivr-L4Jn-tgWC6RHRNpxmhred0W_wqYarIXZZ9g/edit?usp=sharing

**Comment by Brodyann7** [comment]
reviewed https://docs.google.com/document/d/1D6-Sivr-L4Jn-tgWC6RHRNpxmhred0W_wqYarIXZZ9g/edit?usp=sharing 

left suggestions/comments @WhyldWanderer @Brodyann7 @divine-comedian @ForestSoleilr

**Comment by ForestSoleil** [comment]
Reviewed and made minor updates. This is really fantastic and easy to understand in my opinion.

**Comment by laurenluz** [comment]
Edits have been resolved at this is up in Medium, submitted to publication. Debating when to blast it off... will discuss tomorrow

**Comment by WhyldWanderer** [comment]
Live! https://medium.com/giveth/what-if-giving-gave-back-using-web3-to-evolve-philanthropy-a8500b7636ce
