### ISSUE TITLE
Local Regen Guide 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1421]
Hey @laurenluz @danelsuga ! 

Lauren asked for a Brainstorm around[ Owocki's Greenpill.network Chapter](https://twitter.com/owocki/status/1662129239020421120?t=eTUOXhZqLBUvzEOKPNK8PA&s=19). 

Let me fix us some time to kick off this Local Regen Brainstorm.

**Comment by danelsuga** [comment]
OK!

**Comment by oyealmond** [comment]
hey! 

@laurenluz @danelsuga I filled and sent the form yesterday. 
@laurenluz - maybe will be worth to send Kevin a DM from Giveth Twitter for confirmation? / In the form only asked for my name, I added GIveth too. But just in case.

**Comment by laurenluz** [comment]
yeah! let's see what @GriffGreen's input is on which strategy we should take, and then I think we can send a DM to get confirmation.

**Comment by oyealmond** [comment]
we have @GriffGreen's ok. Form is filled, and already jumped in to they Discord mentioning I'll coordinate Giveth's chapter.

**Comment by oyealmond** [comment]
@laurenluz taking over this effort. No actions needed for now.

**Comment by laurenluz** [comment]
Intro Questions, draft [link to discord](https://discord.com/channels/1096048734976090222/1113881170405494784/1118621690231001233)

Copy:

👋  Intro

My name is Lauren Luz & I'm a product lead at Giveth.io. I live in Ethereum & am currently working building new features (like QF!) into Giveth!

✏️ Title/Subject of Regen Guide

Stakeholder analysis and reputation distribution for Impact DAOs.

Web3 has opened to doors to a bounty of new coordination tools - new voting mechanisms, new ways of distributing power, ultimately, new ways of making decisions from the bottom-up. Fair and evolving reputation distribution systems are critical if we want to empower impact organizations to consider the needs of their various stakeholders including:
Capital providers
Labor contributors
Beneficiaries or people affected by the organization
Leaders or subject matter experts

And THIS is critical if we want to actually innovate in the public goods sector and provide solutions that truly meet the needs of society.

🙌 Target Audience

Nonprofits, impact organizations, or other public goods providers

:light_bulb~1: Problem this is solving

Creating a fair distribution of power/influence in organizations so we move away from our plutocratic world, and move into systems that empower a wide variety of stakeholders in a way that sets them up to succeed in solving large scale public goods "problems" like pollution, deforestation, waste, etc.

🤝 Let's connect!

Find me on twitter: https://twitter.com/karmaticacid
Or telegram: https://t.me/laurenluz
