### ISSUE TITLE
Giveth one pager

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1423]
People from some organizations often ask for a One Pager about Giveth. So I made a draft and gave it to @rodricastillo90 who made a beautiful and clean design for it.

The idea is to convey the why and how of Giveth. As well as, the impact we have had so far in numbers & stories for cold leads that only want to understand the basics of Giveth. Without entering into the details that the pitchdeck has.

I would love to get feedback from fundraising leads @GriffGreen @spectoregia & Comms @c0ric0ri @laurenluz especially to reach out to the Interamerican Development Bank.

https://drive.google.com/file/d/1p0b81qqwELPFyTp8XbTJrFV8wD6xkd5E/view?usp=sharing

**Comment by Cotabe** [comment]
@rodricastillo9013 can you share the access to the Figma here so we can edit the copies?

**Comment by laurenluz** [comment]
this issue is redundant with https://github.com/Giveth/GIVeconomy/issues/876, I left a long comment over there so perhaps we can close this one.
