### ISSUE TITLE
Thread about Web3 wallets pros and cons

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1424]
As Giveth is probably the first Dapp for many people, we could discuss the use of wallets and which ones we recommend. 

Recently I've been enjoying Exodus. 

Metamask UX sucks. 

What wallets do you recommend @laurenluz (please tag other people who you think could share on the topic)

**Comment by laurenluz** [comment]
Giveth doesn't work well with every wallet, we should check the tehnical feasibility of the wallets we recommend. I had trouble, for example even using Tally.

@mateodaza - can you weigh in here?

**Comment by oyealmond** [comment]
One question @SteffanThorn, do you mean recommend Web3 wallets in general? I believe @laurenluz is referring to wallets specifically used at Giveth, which will make more sense.

**Comment by SteffanThorn** [comment]
In my opinion, metamask has a terrible UX. For my own personal use outside of Giveth I've been experimenting with Exodus and Trust Wallet. Exodus looks nicer but has a weird connection UX issue. Trust wallet seems to work cleaner than metamask. 

So if there are other wallets than Giveth is known to be compatible with and has a better UX it would fit in with the whole onboarding aspect. 

Especially for mobile as a lot of potential web3 users will be on mobile.

**Comment by laurenluz** [comment]
I think recently there was a big hack on Exodus wallets... or was it Trust wallets, I can't remember 🤔 

If you want to pursue this one @SteffanThorn, get in touch with @mateodaza or another dev to chat with them some more about which wallets we know work well with Giveth.

You could also then put forward the suggestion that we work on developing more compatibility for other wallets.

**Comment by SteffanThorn** [comment]
@mateodaza Could we get some feedback about web3 wallets ideal for Giveth?

**Comment by oyealmond** [comment]
are we still doing this? Should I move this ti Icebox? @SteffanThorn
