### ISSUE TITLE
may 31 tweet brainstorm

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1425]
A new doc of tweets to check on. 

These are themed towards helping projects a bit more. 

https://docs.google.com/document/d/1CQJvURNoRScjfwviek_fy9rACs_4D0mgA54dxK-GnXA/edit?usp=sharing

@laurenluz

**Comment by laurenluz** [comment]
Hey @SteffanThorn - these are great - I edited some of them directly (just improving and tweaking a little). If I didn't leave a comment, then it's approved!

I also added some suggested edits so it's easier for you to track my ideas.

Do you want to take the approved/edited ones and put them up in tweethunter?

**Comment by laurenluz** [comment]
@SteffanThorn - are these scheduled? can you make a note in the doc if/when they are? and leave a comment here in the issue?

**Comment by SteffanThorn** [comment]
Scheduled all okay bar one that I looked at again and decided to revisit in a later doc. Will move this to done.

**Comment by oyealmond** [comment]
@SteffanThorn can we close this one?
