### ISSUE TITLE
GM! podcast Ep 03 Tweets promotion. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1431]
Hey @laurenluz ! 

Could you help me reviewing and schedule [this tweet ](https://docs.google.com/document/d/1o5TtUr98-CBtTT86lYHgqQbc4EW-34MU-GHpYmbjXRc/edit) 8am Costa Rica time this Friday June 9th please? 

Is the 1 hour before announcement of the new GM podcast. 

I'll provide the rest of the tweets after having the Spotify and Youtube links. 

cc @SteffanThorn

**Comment by laurenluz** [comment]
done

**Comment by oyealmond** [comment]
hey @laurenluz ! could you. help me review the drafts I made promoting this episode please? 

https://docs.google.com/document/d/1o5TtUr98-CBtTT86lYHgqQbc4EW-34MU-GHpYmbjXRc/edit

**Comment by laurenluz** [comment]
I made some tiny edits in the doc and put comments "good" on them (please leave those @oyealmond ! 😄 )

@SteffanThorn - can you have a look and scheduled these 2 (separate) tweets using tweethunter?

the episode aired last week so we could do one on the weekend - perhaps saturday? and one next week?

**Comment by oyealmond** [comment]
Hey team! Just checking this is scheduled? 
Thanks!

**Comment by SteffanThorn** [comment]
I can't access the doc

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1671141377600544769

**Comment by laurenluz** [comment]
@SteffanThorn - please leave a comment in the issue once the tweets are scheduled so we can stay organized.

then our flow is to post a link to the published tweet(s) and then close the issue after they are all out.

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1671911441794846723
https://twitter.com/Giveth/status/1671141377600544769
