### ISSUE TITLE
Tweet for DevOps open position

### ISSUE THREAD

**Issue by hanners-717** [Giveth/giveth-planning#1432]
@SteffanThorn Can we get a tweet for this open job posting? https://giveth.recruitee.com/o/giveth-devops-contributor

**Comment by SteffanThorn** [comment]
We have 2 tweets scheduled. This is also on another issue.

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1677301952659505152
https://twitter.com/Giveth/status/1485987059605069830
