### ISSUE TITLE
Verified Projects tweet thread R38

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1434]
Hola @oyealmond & @laurenluz 

Draft ready for review here:
https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by laurenluz** [comment]
looks great @NikolaCreatrix - I had a super quick read through, looks good!

would love to pass this off to @SteffanThorn to review and then schedule it in tweet hunter :)

**Comment by SteffanThorn** [comment]
hey sorry I totally missed this one. 

Still need scheduling?

**Comment by oyealmond** [comment]
Sorry @SteffanThorn ! 

Getting used to our new process. I added you already!

**Comment by oyealmond** [comment]
hey @SteffanThorn , yes! I believe it still need scheduling 
https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit

**Comment by SteffanThorn** [comment]
Edited and scheduled for next for Friday June 30th
