### ISSUE TITLE
Tweets brainstorm doc June 15th

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1436]
another list of tweets made. 

The shoutout one needs your input @laurenluz 

The rest are proofread. 

https://docs.google.com/document/d/1BGpd_sUL5VGw6IYLu64wbmaEILdUZ6C9wXSsjZ-T-Ss/edit?usp=sharing

**Comment by laurenluz** [comment]
Thanks @SteffanThorn - I made some suggestions and comments. once they're resolved, you can schedule these.

also... until we agree to another process, I would like you to get my "ok" on tweets before scheduling them. there's still a lot of stuff I'm catching. not sure what you meant by "the rest are proofread".

**Comment by SteffanThorn** [comment]
What I meant was the tweet about the supporters might need added content. 

The other tweets needed looking at and editing if need be. 

Sorry for the confusion.

**Comment by SteffanThorn** [comment]
Majority scheduled. Unscheduled tweets I've moved into a later google doc that I will bring up in a future issue. So I'll move this to done.

**Comment by oyealmond** [comment]
@SteffanThorn can we close this one?

**Comment by SteffanThorn** [comment]
Yes
