### ISSUE TITLE
Booth Branding for ETH Barcelona 2023

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1437]
We'll need to provide two pieces of branding for our booth at ETH Barcelona. 

# IMPORTANT INFORMATION

**DEADLINE to send materials: JUNE 26th, 2023**

Please make all of the materials at 300dpi, in PDF (vector is always preferable) and a 2cm bleed. Please transform all the copy text to shapes.

## Side Panel 
The first is a side panel logo that sits on the side of our booth, attached to the wall. Here are the dimensions:

![image](https://github.com/Giveth/giveth-planning/assets/67759413/7bf4c575-4802-4025-a0df-dcf5ad2c0235)

## Table Sticker 
The second piece is a table sticker that will go on top of our table at the booth. 

Here are the dimensions:
![image](https://github.com/Giveth/giveth-planning/assets/67759413/a507b793-8d4d-4507-88f6-db2ac5a0ef6a)

**Comment by rodricastillo9013** [comment]
![Captura de pantalla 2023-06-19 a la(s) 10 17 31](https://github.com/Giveth/giveth-planning/assets/61791380/9126e2bd-36b2-4853-a704-c6aabe6e633c)

@divine-comedian wdyt? Let's confirm the design and prepare to send the print files.
