### ISSUE TITLE
create onboarding guide for Ambassadors Program

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1438]
This is more of a long term issue. 

We should think of: 

1. plan the structure of the guide (which topics should we add & in what order) 
2. develop the topics (assign contributors to develp topics, or have 1 person developing everything) . 
3. Design the deck

**Comment by oyealmond** [comment]
So I believe Maye will be taking ownership of this 
@WhyldWanderer

**Comment by WhyldWanderer** [comment]
Yes! I think I need to help her get on github..

**Comment by oyealmond** [comment]
This was awesome @WhyldWanderer , thank you so much. https://docs.google.com/presentation/d/1UoBXommi6ukMbLd1t9iqvmz3KM4t_1z0ZvfRAsJcm9M/edit#slide=id.g1490bd5040f_0_0
