### ISSUE TITLE
Octant Twitter Spaces 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1439]
create 2 twitter spaces w/ all the orgs participating. Choose dates from June 29 - July 28
@laurenluz

**Comment by SteffanThorn** [comment]
Do we have a tweet for this? @oyealmond

**Comment by oyealmond** [comment]
hey @SteffanThorn ! Im still organizing the spaces. 
I have the guests booked for the 1st date (out of two) ready. 
Will be on July 10th and 11 / 9am ET / 3pm CET 
I'll share more about these Twitter Spaces soon!

**Comment by oyealmond** [comment]
hey @laurenluz[ sharing next week script and Tweets](https://docs.google.com/document/d/11HSAQdJTELXyay5ZtdrHRu2LUJt9IqaW3R0-Aa7tTfw/edit) to promote EpochZero/Octant GIVtalks :) 

Let me know your thoughts

**Comment by laurenluz** [comment]
scheduled them all - great work Almond! thanks so much!
