### ISSUE TITLE
Octant tweets creation. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1440]
Draft Tweets around the octant ETH Distribution to incentivize the community to support Giveth. 
@laurenluz can provide more info on this.

**Comment by SteffanThorn** [comment]
@laurenluz What info do you have about octant ETH distiribution?

**Comment by oyealmond** [comment]
Hey @SteffanThorn :) Sharing some info. 

Octant will distribute 1M worth of ETH to some projects (Giveth included). This is round is called Epoch Zero: this is a pre-launch event for an upcoming release of the Octant app - https://octant.build/. 

Communities will vote with POAPs on Snapshot around how the fund will be distributed. The Snapshot poll will happen between July 21st and July 28th. Communities will get the voting POAPs during virtual events. 

This will be announced on the 29th of June. 

The projects competing: 

Clr.fund - https://clr.fund/
DAO Drops - https://daodrops.io/
Drips - https://www.drips.network/
Ethereum Cat Herders - https://www.ethereumcatherders.com/
ETHStaker - https://ethstaker.cc/
Giveth - https://giveth.io/
Gitcoin - https://gitcoin.co/
Kernel - https://www.kernel.community/en/
Protocol Guild - https://protocol-guild.readthedocs.io/
Supermodular - https://supermodular.xyz/

More info here: 
https://hackmd.io/@gofo-new/HyBKKtdv3

***


I believe @laurenluz wanted to have some drafts around, why to support Giveth on Epoch Zero. 
@laurenluz do you have some bandwidth to help drafting some of these tweets? /  or maybe you could provide more clarity on the type of tweets you envision for the Epoch Zero round

**Comment by SteffanThorn** [comment]
Let me know if I'm on the right track here @laurenluz 

https://docs.google.com/document/d/1cHzKbZFp6wz61qBsRGzRRyexKz-uHnYxXg10ntR92co/edit?usp=sharing

**Comment by SteffanThorn** [comment]
circling back on this @laurenluz @oyealmond

**Comment by oyealmond** [comment]
Ey dear team! @SteffanThorn @laurenluz could you review [the 1st tweet of this draft?](https://docs.google.com/document/d/1qeb0ADvrqgZbBC1FhMDoet9gvPxUHy70NiVx_Ro7kiM/edit) Is a final reminder to claim The Octant POAP.

**Comment by laurenluz** [comment]
scheduled the 1st one and made edits on the 2nd! lmk when we have the link!

**Comment by oyealmond** [comment]
The link is confirmed. Is the final link! @laurenluz

**Comment by oyealmond** [comment]
More Octant tweets for your review [here](https://docs.google.com/document/d/1qeb0ADvrqgZbBC1FhMDoet9gvPxUHy70NiVx_Ro7kiM/edit) @laurenluz . Let me know your thoughts!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1682375379384774661

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1683900436359544834
https://twitter.com/Giveth/status/1684504407486894081
