### ISSUE TITLE
Promote Impact Quest Partners and Prizes

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1441]
We have three confirmed partners for Impact Quests and some prizes we can begin to promote via comms.
### Confirmed Partners
**ETH Barcelona** - Free tickets to attend ETH Barcelona next year https://twitter.com/eth_barcelona
**Aragon** - Swag, water bottles and notebooks, approx 20. of each https://twitter.com/AragonProject
**KeepKey** - 5 KeepKey Hardware Wallets https://twitter.com/cryptokeepkey

### Unconfirmed Partners 
ENS
Green Pill

On top of that Giveth will also chip in Givers PFP NFTs, I would say a cap of 30 total we'll give out.

**Comment by oyealmond** [comment]
nice @divine-comedian! 

Let's use this issue to start putting everything in place. To have more clarity on this: 

1. Let's decide a date to kick off impact quests. (To be more clear on comms) . We will start on July 5th, before? Wdyt? cc @WhyldWanderer 
2. Would be nice to include the organizations in the comms as well. @franculio @Santigs please add the organizations that will be participating on the impact quests in this issue. (The ones that already accepted)
3. @WhyldWanderer I know Rodri has been sick, but I will like to start showing the design of the quests beforehand, promoting the quests showing the images, do you have a date for Rodri to deliver? 
4. @divine-comedian I know you always find the conference Telegram groups, do you have some Telegram groups already for use to promote the quests? 
5. And last, @WhyldWanderer you'll be twitching the Denver quests for Barcelona? Basically adding the Barcelona orgs, and making a little tweaks. Do you want me to help w/ that? 

And finally, 
6.  I can prepare some comms for you @divine-comedian to share w/ the partners. Will be great if they help us promote  as well.

**Comment by oyealmond** [comment]
@divine-comedian Mitch, can you ask the price partners for their Logo please? 

Im going to add the logo of our partners in the Notion.

**Comment by divine-comedian** [comment]
I was going to use this doc to consolidate our Impact Quest information:

https://www.notion.so/giveth/ETH-BCN-Impact-Quests-f3a57ed72cf14d5bbc0dc4c33f07d619?pvs=4

We could starting promoting the quests **as early as 26 of June**, A full 10 days before the conference begins. We could hopefully allow participants to finish quests such as making crypto donations or sharing projects via social media. They will receive an Impact Quest NFT and also be eligible for some virtual prizes (and physical prizes if they will physically be at ETH Barcelona)

### Virtual Prizes could include:
 - $nice tokens (let's say 40?), unlimited prizes available
 - Givers PFPs (30 max for the whole Impact Quests)
 - Tickets to ETH Barcelona next year (Raffle of 5 total available)

Here is an invite link to the Giveth Impact Quests account
https://t.me/givethimpactquests

Here is the link to the official ETH BCN group chat:
https://t.me/ethbarcelona

**Comment by Santigs** [comment]
Updated the social orgs.
Aprenem just confirmed this weekend, working with them to set up their project in Giveth.

**Comment by divine-comedian** [comment]
Doing some more investigation into TG Groups we can blast to:
SOLAR PUNK EVENTS 
https://t.me/solarpunkevents

PROOF OF INTEGRITY (español)
https://t.me/proof_integrity

MOONBEAM (eth bcn sponsor)
https://t.me/Moonbeam_Official

ARAGON (eth bcn sponsor and impact quest partner)
https://t.me/aragonproject
