### ISSUE TITLE
Docs updates - improving info  in #disqualifying-factors-for-the-givbacks-program

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1442]
Based on user feedback (see the info in the verification channel) we will try to simplify information in this section of the documentation:

https://docs.giveth.io/dapps/projectVerification#disqualifying-factors-for-the-givbacks-program

![image.png](https://images.zenhubusercontent.com/621267ef682a86d0321e6ccc/56aef706-120f-4d55-a1e5-5f96ef2cbaff)

I will work on the draft this week. 
cc @WhyldWanderer

**Comment by oyealmond** [comment]
hey @NikolaCreatrix ! You got this? Do you need @franculio support?

**Comment by NikolaCreatrix** [comment]
Actually, since this is very sensitive in terms of what type of vocabulary and explanation we can use to improve this - I won't be able to get this done without @WhyldWanderer

**Comment by oyealmond** [comment]
thanks @WhyldWanderer !
