### ISSUE TITLE
AI June posts promotion. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1444]
Hey team, really sorry for the last minute notice, we'll stream AI June on Youtube, could you [review and schedule](https://docs.google.com/document/d/1f7BaHsg2WQR5m6UoXdG3wgvFys5KHWLebgRL9ADyKSw/edit) these tweets please? 

@laurenluz @SteffanThorn

**Comment by laurenluz** [comment]
all are edited and scheduled.

**Comment by oyealmond** [comment]
thanks you so much @laurenluz !!!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1672289218846965766
https://twitter.com/Giveth/status/1671836226783985664

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1674040504994988034
