### ISSUE TITLE
GM! Ep 04, Tweets. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1446]
hey @laurenluz @SteffanThorn 

[Drafted a tweet 1 hr before the launch of the new GM! episode. ](https://docs.google.com/document/d/1os_d7ITwB37wu_KRZJNosgMzjNbTBPUiz-9n7uUpvq8/edit)

Could you help me review and schedule? 

Thanks!

**Comment by laurenluz** [comment]
scheduled for 10am EST. Thanks @oyealmond

**Comment by oyealmond** [comment]
hey @laurenluz , @SteffanThorn 

[I drafted more tweets to promote the newest GM! episode. Could you review and schedule them? 

Thanks! ](https://docs.google.com/document/d/1os_d7ITwB37wu_KRZJNosgMzjNbTBPUiz-9n7uUpvq8/edit)

**Comment by oyealmond** [comment]
hey @SteffanThorn ! 

I saw you review this, but are they already scheduled?

**Comment by laurenluz** [comment]
I scheduled them for next week.

**Comment by oyealmond** [comment]
thanks! :D @laurenluz

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1675792025088675848

**Comment by SteffanThorn** [comment]
Sorry I mentioned it in the google doc. I'll mention it in this github page next time.
