### ISSUE TITLE
Impact Quests / ETHBcn partner tweets. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1447]
Hey team! @laurenluz @SteffanThorn 

Could you please review [this draft ](https://docs.google.com/document/d/1ku--zFcfyXQPugIajNqq0sF-m5FdkLVxpiGZ4xUnYDE/edit)of the thread thanking our partners for ETHBcn – Impact quests? 

Will be great if can be schedule early next week 

thanks!

**Comment by laurenluz** [comment]
this was posted, but honestly, I think it really lacked context in the intro tweet, we should be mindful of that for later tweets... https://twitter.com/Giveth/status/1673372172717371392
