### ISSUE TITLE
Newsletter June 2023 

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1448]
Topics to include:

- Giveth at ETHBCN and ETHCC
- Optimism proposals 
- RetroPGF optimism proposal (i think it's worth it's own shout out)
- New GM podcast episode: https://twitter.com/Giveth/status/1671911441794846723
- AI June Hackathon
- CTO hiring (this role is relevant for Giveth) https://twitter.com/thegrifft/status/1671545324865716224

Anything else come to mind @oyealmond @laurenluz @danelsuga ?

**Comment by danelsuga** [comment]
For Paris, we'll also be here: https://fundingthecommons.io/#paris-apply

**Comment by laurenluz** [comment]
looks good @ahmadabugosh!

For ETH BCN I think it's worth mentioning out impact quests: https://github.com/Giveth/giveth-planning/issues/1447
And it might be fun to feature the giveth mural in mexico: https://twitter.com/Giveth/status/1664241103564951552

**Comment by oyealmond** [comment]
hey @ahmadabugosh! 
The most recent GM! episode launched today, Is this one. Will be great to promote this episode actually: 

Griff with Nathan Schneider: 

[Youtube](https://www.youtube.com/watch?v=VDyspYLiHcU) & [Spotify ](https://spotifyanchor-web.app.link/e/z2SkNXedSAb). [Tweet](https://twitter.com/Giveth/status/1672243893042126852)

For AI June, the session are live streamed on our Youtube, where people can interact w/ the participants & ask questions. We have 2 sessions up to now: 

[Session 1 ](https://www.youtube.com/watch?v=mdccEoKdSsk&t=255s)
[ Session 2](https://www.youtube.com/watch?v=tzLSoLy3q2s)

**Comment by oyealmond** [comment]
@ahmadabugosh 

This is the link for Impact Quests: https://giveth.io/quests 

(We partner w/ Barcelona orgs & Web3 projects to create a positive Impact in Barcelona).

**Comment by ahmadabugosh** [comment]
Hey @oyealmond @danelsuga @laurenluz @WhyldWanderer , The latest newsletter draft is here please leave your comments (I also left some comments on sections I think we may need to improve on). https://docs.google.com/document/d/18m6iU12Zkj35TBzlWqvFU8X4g6LCsry8AEo95MipXBc/edit

Apologies for this taking longer, I want to send it by tomorrow (June 4th if possible), since I want to promote ETHBCN!

**Comment by danelsuga** [comment]
I added some edits. Hope it's not too late!

**Comment by ahmadabugosh** [comment]
@oyealmond this is sent, if you want to tweet about it too, here is a suggested tweet:

"In this month's newsletter

🇪🇸 Impact Quests @eth_barcelona
🔴 Community Building @retropgf
🫶 GIVfriends @AragonProject @cryptokeepkey @greenpillnet @ENS_DAO 
🗣️ New podcast with @ntnsndr 

https://news.giveth.io/givnews18"

**Comment by laurenluz** [comment]
scheduled
