### ISSUE TITLE
Updating Referral program Documentation

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#1450]
Updating https://docs.giveth.io/giveconomy/referral with the new design. 

Cc @oyealmond

**Comment by franculio** [comment]
Testing site https://giveth-dapps-v2-git-chainvine-for-prod-givethio.vercel.app/project/graceaid-earthquake-relief

**Comment by oyealmond** [comment]
Thanks @franculio :D

**Comment by franculio** [comment]
Hey @laurenluz here's the suggested changes for the Referral docs page, I left some questions there about the percentages which I don't know if they changed or not. 

Cc. @MoeNick 

https://docs.google.com/document/d/16i2OUt5r8MhBG5gVK9JUgvsbbEYg9OHt914fh3QGXH0/edit?usp=sharing

**Comment by laurenluz** [comment]
@franculio - I don't have access to the doc - can you change the settings?

**Comment by laurenluz** [comment]
@franculio - I don't have access to the doc - can you change the settings?

**Comment by laurenluz** [comment]
ok! I tore it apart. I think you can just go through and accept suggestions, then add any links (I made comments), then send this up to the docs! @franculio - thanks :)

**Comment by franculio** [comment]
Updated, closing issue

**Comment by laurenluz** [comment]
BOOM

**Comment by laurenluz** [comment]
https://docs.giveth.io/giveconomy/referral

**Comment by oyealmond** [comment]
thank you so much you both for the work on this! @laurenluz @franculio
