### ISSUE TITLE
Create tweets around the improved Giveth Referral Program. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1451]
We're re launching the improved version of Giveth's Referral Program! 

We need to prepare some tweets in order to promote this launch. 
Comms launch date tbd

Here's the info about Giveth's Referral Program: https://docs.giveth.io/giveconomy/referral/
@laurenluz feel free to share more inputs on the new or improved Referral Program benefits! 

Here's the improved Referral Program testing: 
https://giveth-dapps-v2-git-chainvine-for-prod-givethio.vercel.app/referral

***

@SteffanThorn could you draft some tweets about this? Lmk. Thank you! :)

**Comment by SteffanThorn** [comment]
https://docs.google.com/document/d/1hxCmAmFlygY1ie68_A5o5z9CaXcg7RoqnD1bouISS1Q/edit?usp=sharing

How about these?

**Comment by SteffanThorn** [comment]
@laurenluz looping you in here

**Comment by laurenluz** [comment]
@SteffanThorn - can you try it out for yourself? you can start here: https://giveth.io/referral and the page explains how it works.

important points:
- you can generate a unique referral link to any verified project, or to any page on Giveth
- if someone donates to ANY verified project on Giveth after clicking your link, you get GIV
- GIV is distributed via GIVbacks and can be claimed within 2 weeks (after GIVbacks are sent out) on giveth.io/givbacks
- You get some % (I think 10%) of the GIVbacks that donor would have gotten, and they get the rest... this is how the program works
- we launched the referral program before, but UX wasn't the best, so this is a much improved version... you don't need to outright say this in the tweet, but it's relevant context
- this is the 1st time that projects themselves can get GIVbacks ... they can share a referral link to their own project... and when people donate, they get the donation AND extra GIV via GIVbacks.

It would be good to make one longer thread explaining how the referral program works, and then some shorter tweets with tidbits.

**Comment by SteffanThorn** [comment]
Perfect timing coz wife my wants to donate so I'll get her to use my link

**Comment by SteffanThorn** [comment]
0 instructions on how to set the referral link to a particular project. 
Plus my referral link I can't seem to modify. 

Maybe I'm missing something here but doesn't seem user friendly right now.

**Comment by SteffanThorn** [comment]
@MoeNick maybe I can get some help here. 
Because I can't see any difference my end from before. 

When I click on the "share & get rewarded" button I get given a referral code with no ability to change it. 
There's also no instructions on how to use it for projects. 
When I go to the project page on Giveth, there's no clear option to use a referral. 

Am I missing something here?

**Comment by SteffanThorn** [comment]
Doc is updated with a thread.  @laurenluz @oyealmond take a look and see what you think. 

One part I want to confirm is: when they use the referral link to the verified project, but the person donates to other verified projects, they'll still get the rewards, right?

**Comment by SteffanThorn** [comment]
I've also edited the tweets a little. But relatively the same.

**Comment by laurenluz** [comment]
yeah they still get rewards if the person donates to other verified projects.

**Comment by laurenluz** [comment]
@SteffanThorn - I left some comments - can you make a new edit?

**Comment by SteffanThorn** [comment]
Made new edits:
•shortened the thread at the beginning and end
•changed rewards to earn
•a few other edits and comments 
•some tweets also reworded

**Comment by oyealmond** [comment]
@SteffanThorn , did you scheduled the rest already?

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1688566179122597888
https://twitter.com/Giveth/status/1687086428415471617
https://twitter.com/Giveth/status/1679460539724963841
