### ISSUE TITLE
Moving "Giveth Trace" of the side bar

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#1452]
At the moment we still have Giveth Trace documentation in the **User Guides** sidebar. After talking with @laurenluz we thought of moving it since it would give more visibility to the GIVeconomy section. 

![Captura de Pantalla 2023-06-28 a las 15.57.31.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/a4a5fc96-68f0-4183-8d86-3ba2eecd866b)

Should I move it down to be last under **User Guides**? or move it out of the **User guides** and keep it as separate item? Wdyt @oyealmond @laurenluz ?

**Comment by laurenluz** [comment]
I think it would be nice to have a section called "deprecated" and we can put anything not relevant anymore in there. like we can also put in the angel vault documentation maybe...

**Comment by franculio** [comment]
Done, closing issue
