### ISSUE TITLE
Youtube GM 1st episode links

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1454]
On the first episode of GM, would be good to include bretts links. 

Link to his book “cloud money” 
And link to his substack: brettscott.substack.com 

@laurenluz who handles the youtube content?

**Comment by oyealmond** [comment]
I do @SteffanThorn! I mean, I can help you!

**Comment by oyealmond** [comment]
https://www.youtube.com/watch?v=a15AxFtOaU4
