### ISSUE TITLE
List of projects for QF MVP

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1455]
Ashley, Carlos & I are putting together a list of projects for our QF MVP (hoping to launch July 18). Our planned criteria is to use a maximum of 50 projects who have raised at least $500 all time...

That list is about 71 projects, excluding Giveth, Giveth matching pool, Gitcoin matching pool & earthquake relief matching pool (because I think we shouldn't match funds to matching pools for our MVP and focus on real projects doing real work).

Here is our [speadsheet](https://docs.google.com/spreadsheets/d/1vAH98Q_yhEETouuHheMg-0xD_xxZLeVp1MJ--2lOtMI/edit#gid=1629807942).

@WhyldWanderer - I think we can go ahead and send an email out to the 1st 50 projects on the list and see if we can get them to provide an update to their project? and then only include projects w/ recent updates?

**Comment by WhyldWanderer** [comment]
Emails have been sent to the first 55 projects on the spreadsheet!
