### ISSUE TITLE
Email project owners for QF eligibility

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1456]
Hey team, drafted this here: https://docs.google.com/document/d/1leJBL5RXgXnYYrRVXwYysHtU_MLbpi-hogq5zbpKdUc/edit

in order for projects to be part of our upcoming QF round, they'll need to add an update to their project. we'll be sending this email out to 50 projects, then giving them a week to add an update... and if we don't have enough for the round, we'll send it out to a few more.

@danelsuga I'd love your critical eye for review on this ASAP if you (tomorrow?)

@NikolaCreatrix @WhyldWanderer - would love your edits too, and once we finalize it, we can start sending it out to [our list](https://docs.google.com/spreadsheets/d/1vAH98Q_yhEETouuHheMg-0xD_xxZLeVp1MJ--2lOtMI/edit#gid=1629807942) from info@giveth.io

**Comment by danelsuga** [comment]
Btw as I'm sure you know, this is a great website to share for anyone to understand QF better and to tinker with how it works: https://wtfisqf.com/
Not a bad idea to include it in the message imo.

**Comment by laurenluz** [comment]
sent to all
