### ISSUE TITLE
More GIVbacks POAPs!!

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1457]
I just used the Round 39 POAP and we will need more soon..

Can you help with this @rodricastillo9013 ??

**Comment by rodricastillo9013** [comment]
nice! Jes will be helping us with this task, next week she will send us new designs, :)

**Comment by WhyldWanderer** [comment]
Great! Thank you 🚀

**Comment by WhyldWanderer** [comment]
@rodricastillo9013 - hey there... its that time again and we need more POAPs for GIVbacks... 
Will Jes be helping with this again? I don't have her handle..
