### ISSUE TITLE
Create an email for confirmed projects in the round

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#1460]

**Comment by laurenluz** [comment]
It should say:
- congrats, your project i part of our QF alpha round! (thanks for adding an update!)
- $10,000 of matching funds will be available
- 25 (tbd) projects will be in the round
- round dates July 18-Aug 1 (time TBD)
- donors can see all the projects & donate when the round opens here: https://giveth.io/qf
- donations on all 5 of our chains (list then)
- donors get GIVbacks
- project sort according to GIVpower
- QF < works like this >
- Tips for getting noticed: share on twitter etc etc.

**Comment by laurenluz** [comment]
@danelsuga maybe you can help w/ this one too?

**Comment by danelsuga** [comment]
first draft.
https://docs.google.com/document/d/1j0MCtIQZY9gluZVC3uiS33lFyVYMgZVYeWOHk4KnNWM/edit?usp=sharing

**Comment by danelsuga** [comment]
Think this is done @laurenluz.

**Comment by WhyldWanderer** [comment]
Email sent!
