### ISSUE TITLE
QF Alpha round announcement tweet thread

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1463]
this should go out July 18 when the round starts, telling everybody about it

**Comment by laurenluz** [comment]
assigning you both @oyealmond & @SteffanThorn - but I'm happy to give you some more context. the idea here is to have a nice announcement tweet explaining the round.

a lot of this info is in our docs here: https://docs.google.com/document/d/1rsEO4jsLIGRtLgiIOqrCu4CcOERgtRehcoml1foJHk4/edit

**Comment by SteffanThorn** [comment]
Made a draft thread https://docs.google.com/document/d/1hiO2SdQhHCsVN4Nwl9c1TR2ONkCweI9yvAKmiu4BpFQ/edit?usp=sharing

**Comment by oyealmond** [comment]
hey team! took some ideas from @SteffanThorn https://docs.google.com/document/d/11Kxdabx_GtrLnroti0UbLJ0ne0JRatK440Vidb7vynU/edit . 

Please review whenever you have a chance! @laurenluz

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1681296284592877568
