### ISSUE TITLE
QF alpha round - mid-round tweets

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1464]

**Comment by laurenluz** [comment]
we should write a series of shorter tweets... to go out throughout our 2 week QF round... encouraging people to donate to projects in QF etc.

@SteffanThorn here is our documentation to get you in the loop: https://docs.google.com/document/d/1rsEO4jsLIGRtLgiIOqrCu4CcOERgtRehcoml1foJHk4/edit

Do you think you could handle writing some tweets? we'll want to post them during the round July 18 - Aug 1... maybe like 5-6 tweets total would be great.

we can even have some like "last day to donate in the QF alpha round! browse projects here: link"

**Comment by laurenluz** [comment]
ok... @oyealmond has some drafts in here (near the bottom): https://docs.google.com/document/d/11Kxdabx_GtrLnroti0UbLJ0ne0JRatK440Vidb7vynU/edit

and @SteffanThorn wrote this nice thread here: https://docs.google.com/document/d/1hiO2SdQhHCsVN4Nwl9c1TR2ONkCweI9yvAKmiu4BpFQ/edit

I think both need some edits and then we can schedule them for during this week. what I would like ideally is:
- a tweet or thread explaining some cool things about QF (similar to stee's thread, but minus some of the announcement details)
- some "did you know" tweets that feature Giveth products wrt to QF. like "did you know you get GIVbacks and projects get matching". "did you know you can boost projects to be seen first using your GIV... here's how:" "did you know you can refer people to donate to QF projects and get GIV from our referral program"
- some "what projects are you funding this QF round? (post them below)"
- some "last day to verify your passport to be eligible for matching" "only 1 week left to donate, do it here-->" etc.

Can you @SteffanThorn & @oyealmond work together to make those drafts? one of you make drafts and one review?

**Comment by oyealmond** [comment]
hey! Here's the requested mid-round tweets.

@SteffanThorn if you can review, of @laurenluz ...  
https://docs.google.com/document/d/1hiO2SdQhHCsVN4Nwl9c1TR2ONkCweI9yvAKmiu4BpFQ/edit 

Thanks!

**Comment by laurenluz** [comment]
I edited and scheduled them all - Thank you @oyealmond @SteffanThorn. this was great work!

**Comment by oyealmond** [comment]
oh! I will review the edits to improve next time. Thanks @laurenluz!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1683463319825383425

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1684912091918987265
https://twitter.com/Giveth/status/1686315206677250049
https://twitter.com/Giveth/status/1684579909262352384
