### ISSUE TITLE
MTM August 2nd tweets

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1468]
Hey comms team and @oyealmond, I would like to request help with the comms plan for the next August MTM session.

We'll need these formats:
Twitter
Facebook
LinkedIn

Do we also go for Instagram?

**Comment by oyealmond** [comment]
yes! 

[Here's some tweets ](https://docs.google.com/document/d/1nXOjOmvPLmEZpikByre6GYsYYiUMf10hy93XM6TOxEQ/edit) I drafted. Please @laurenluz , @SteffanThorn can you help me review & schedule? 

This will happen next Wednesday, please choose the dates that best align w/ all the things we have going on rn .

**Comment by SteffanThorn** [comment]
Seems good. Could schedule for tomorrow, in 3 days, then the day. Confirming with @laurenluz on our call tonight.

**Comment by laurenluz** [comment]
I scheduled them all - let's talk about our flow for twitter in our call today
