### ISSUE TITLE
We need to make an email to all project owners and large donors that demands the claim their poap and vote for octant 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#1471]
We need a SUPER SHORT and to the point email that tells people to 

Octant, a Public Goods funding initiative from Golem is giving away $1 MILLION DOLLARS

1. Claim your POAP NOW: https://www.poap.delivery/octant

2. On the 21st, voting opens on: https://snapshot.org/#/octantapp.eth

3. Results will be in and 70% of the funds we get will go to donation.eth, our matching pool that goes to projects on Giveth and 30% will fund further development of the Giveth Platform.

**Comment by laurenluz** [comment]
@danelsuga can you put it together? there's even more context in this tweet thread FYI : https://twitter.com/Giveth/status/1678360924996919298

**Comment by laurenluz** [comment]
oh wait! @oyealmond is back and I think she can write it quick?

**Comment by oyealmond** [comment]
Hey! @laurenluz @GriffGreen yes I'm back! I'll write this.

**Comment by oyealmond** [comment]
[Already reviewed Project Owners draft. ](https://docs.google.com/document/d/1ir6VvqJneXX0PWYJKbyYwqHYAczSYLb18jT6R4dML-0/edit?usp=sharing). 

@ahmadabugosh will send the email tomorrow 1st thing am. 
Thanks!

**Comment by oyealmond** [comment]
@laurenluz @ahmadabugosh @danelsuga 

Please review the [vote for Giveth email ](https://docs.google.com/document/d/1sbOA8Ctrcu_6gos5g0TEJXtU8_CuD5NzGbS3TTBThQc/edit) please!

**Comment by oyealmond** [comment]
Second email sent. 

<img width="883" alt="Captura de pantalla 2023-07-24 a la(s) 16 14 32" src="https://github.com/Giveth/giveth-planning/assets/110692280/c0d91434-e0ee-4301-b89e-f7d0c997957f">
