### ISSUE TITLE
Giveth Tweet Brainstorm july 13

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1472]
A list of tweets to review to fill in the gaps around more specific content. 

https://docs.google.com/document/d/1XakQDMJetbB_b_fuTibiWMdVdeR0cuXfOo5LcWGa-IM/edit?usp=sharing

Looping yous in here for feedback @laurenluz @oyealmond

**Comment by laurenluz** [comment]
thanks @SteffanThorn !! I left some comments & suggestions. let's do another round

**Comment by SteffanThorn** [comment]
Thought I left another comment here. I edited based on your suggestions.

**Comment by oyealmond** [comment]
Maybe could you re organize the doc with the Threads that aren't scheduled yet? So is easier to review it :) 

Thanks @SteffanThorn!

**Comment by SteffanThorn** [comment]
made a new doc and added a few 

https://docs.google.com/document/d/1ZHymXdaEYiuBsvD11gGj02PCpRz09EeFnfF05359eXI/edit?usp=sharing

**Comment by laurenluz** [comment]
reviewed!

**Comment by SteffanThorn** [comment]
Okay thanks. After each tweet I've left what I've done. Either scheduled or moved to a later doc. (most scheduled) 

@oyealmond feel free to move them on the schedule when need be -- they are fillers.

**Comment by oyealmond** [comment]
thanks @SteffanThorn! 

I saw they're scheduled already.

**Comment by SteffanThorn** [comment]
Closing this as these are simply fillers and already scheduled.
