### ISSUE TITLE
Tweet thread Verified Project R39

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1473]
Hey team @laurenluz & @SteffanThorn 
cc @oyealmond 

Rough draft for next round here, ready for final editing and scheduling: https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

Can we start using this hashtag? #MeetTheMakers :)

**Comment by laurenluz** [comment]
@SteffanThorn - can you edit & schedule Nikola's recent draft thread? it's at the top of the doc.

**Comment by SteffanThorn** [comment]
@NikolaCreatrix what's your reasoning with the hashtag? Have you used the hashtag in twitter search? 

I don't see any benefit with it for Giveth.

**Comment by SteffanThorn** [comment]
I see the logic, but unless we are flooding the timeline with #MeetTheMakers it won't make any good affect. 

There are countless projects and companies using the same hashtag. When people click on it they will not be sent to other "Meet The Maker" Giveth threads -- they'll see countless other companies doing the same thing instead. 

For this reason I've changed the hashtag in the first tweet, but included the words. 

https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit

**Comment by laurenluz** [comment]
Agree w/ @SteffanThorn - let's get this posted! @SteffanThorn - can you add it to the scheduled please?

**Comment by NikolaCreatrix** [comment]
Thank you @SteffanThorn for providing your opinion, but please keep the hashtag as requested. I understand your point but this is what we have agreed on as a team in the hope to build more resources around this initiative in Giveth therefore more content on #MeetTheMakers topic.  Thanks a lot.

cc @oyealmond

**Comment by laurenluz** [comment]
noticed this never went out and wasn't scheduled. Added to tweet hunter Monday August 14 @oyealmond @SteffanThorn

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1691102896803250178
