### ISSUE TITLE
qf alpha round discord announcement

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1474]
draft here: https://docs.google.com/document/d/1-2Unsvx6x9MNTT-Xl35jvtezprHqqM0_cYtq1Chb2Oo/edit

we should post in the announcement channel after the tweet goes out.

**Comment by oyealmond** [comment]
got this. At what time the announcement will be out? @laurenluz If it will be Europe time, then maybe @WhyldWanderer will be the best to post this!

**Comment by oyealmond** [comment]
https://discord.com/channels/679428761438912522/864545286251872286/1130855638327623811
