### ISSUE TITLE
Send broadcast notification to our users about the QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1475]
this can be done from admin bro!

we can send something like:

Our Quadratic Funding Alpha Round is LIVE! Explore projects here: https://giveth.io/qf

**Comment by oyealmond** [comment]
I think this is done, no @WhyldWanderer?

**Comment by laurenluz** [comment]
ooh it's an admin bro thing - want to set it up @WhyldWanderer ?

**Comment by WhyldWanderer** [comment]
Finished! 
![image](https://github.com/Giveth/giveth-planning/assets/74267818/717e3dc0-c784-4dc0-a576-ef15dd44e784)
