### ISSUE TITLE
MTM Designs

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1476]
Hi team, I would love your help with new Meet The Makers designs, perhaps we can create some universal, refreshed version only with the name of the event and some generic call. Like a banner that we don't have to change every month... wdyt? @oyealmond 

What are the formats we can use for email and social media?

**Comment by rodricastillo9013** [comment]
![image](https://github.com/Giveth/giveth-planning/assets/61791380/a7f17ad6-755c-42fe-92d6-aa8b77ca61cc)
![image](https://github.com/Giveth/giveth-planning/assets/61791380/65493bb0-6be6-497a-a04f-bad22ef0949e)
@oyealmond @NikolaCreatrix hey :) how are you! here I share 2 ideas, let me know wdyt ! thanks

**Comment by oyealmond** [comment]
I like both! :) 

Can I have both available for edition please? @rodricastillo9013

**Comment by rodricastillo9013** [comment]
https://www.figma.com/file/hkwLhJFNlQszzQQDTn7Qj1/Giveth-Marketing-(Copy-for-team)?type=design&node-id=1512%3A18643&mode=design&t=Bvq1UTaGyTGYCow5-1

Here the figma file :)
