### ISSUE TITLE
Collect wallet addresses from Ambassadors for NFTs/Rewards

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1477]
There were 3 Ambassadors who graduated and will be awarded the NFT.

There were also some Ambassadors that met the requirements of project/donor onboarding as well as Discord invites and should be rewarded for the milestones with GIV. The budget has already been approved. 

We need to collect the Gnosis Chain wallet addresses of these Ambassadors so that we can distribute the rewards.

**Comment by oyealmond** [comment]
The resources we need to calculate the rewards: 

· [Discord onboardings](https://docs.google.com/spreadsheets/d/1pCY0c19EqYX_F7G1duEp86gADeeayubI-SjkP8VpT_A/edit#gid=0)
· [Projects onboarded](https://www.notion.so/giveth/52b7eb6ce18f42f5aba93f1f5fca8e4d?v=7806fbd361db4331b7dbbd1fc4cc8947)
· Get 30 or more in donations, I think no one completed this one
· Graduated [Maye, Cheo, Soho]

**Comment by WhyldWanderer** [comment]
I think that's it!
