### ISSUE TITLE
Mint NFTs for Ambassador Program graduates

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1478]
We need to mint the NFTs for the graduate Ambassadors. 

We are collecting the wallet addresses here
https://github.com/Giveth/giveth-planning/issues/1477

@oyealmond can you link the art here?

@divine-comedian can you help to create the means to distribute the NFTs?

What other steps do we need to take?

**Comment by oyealmond** [comment]
hey @divine-comedian! 
Can you please help us mint this NFT? 

Next thing we need to send it to three ppl. 
Could you help us send it too? 
Should we ask someone else?

**Comment by oyealmond** [comment]
Send it to: 

Cheo: 0x9AE494FBAc34682c122A1D4e3D6ae1Eb5404A469 
Soho: 0x95e3469e6adB95798F294f45896CBcb8C17486dF 
Maye:

**Comment by oyealmond** [comment]
@divine-comedian is saying we should be able to do this without a developer help. In that case, which platform is better? I should just research and do it in whatever platform I like? 
Is it cool to have Giveth NFTs spread all over different platforms? 
@WhyldWanderer should we just mint this as a POAP and deliver it to the ambassadors? 
Maybe we should have @Santigs input on this?

**Comment by WhyldWanderer** [comment]
Hmm okay.. I assumed that we would do it the same way we issued the Impact Quest NFTs but  Im open to other options

**Comment by divine-comedian** [comment]
I did some research and maybe there isn't a great option yet for your specific case - 

Along with the image is there any text or description to be included with the NFT? I would recommend adding something

**Comment by Santigs** [comment]
I think using the same method we did for Eth Barcelona quests is probably the best option, otherwise, we can use the Thirdweb toolkit to create an ERC1155 collection edition and the corresponding minting page for us to mint directly and transfer or to offer ambassadors to mint themselves once we whitelist their addresses. I can do that directly without help from any coder

**Comment by oyealmond** [comment]
thank you both @Santigs & @divine-comedian 
We're testing if the NFT contract worked.

**Comment by oyealmond** [comment]
thanks @divine-comedian!
