### ISSUE TITLE
Newsletter July 2023

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1479]

**Comment by ahmadabugosh** [comment]
Topics to include:

- Launch of QF
- Octant App Epoch Zero (if we get this out by the 28th)
- ETHBCN and ETHCC recap

Does anything else come to mind to include? @oyealmond @WhyldWanderer @laurenluz @danelsuga

**Comment by laurenluz** [comment]
that's a lot and I think it's great!

**Comment by oyealmond** [comment]
great! Thanks @ahmadabugosh!

**Comment by oyealmond** [comment]
Let's add MTM! Happening Aug 2nd.

**Comment by danelsuga** [comment]
Sorry for no review. On vacation this week with mostly no internet at all. Just writing to say I'm sure it's a great job as always! 🤩

**Comment by laurenluz** [comment]
@ahmadabugosh is this done already?

**Comment by ahmadabugosh** [comment]
Hey @danelsuga @oyealmond @laurenluz, sorry again for the delay here is the draft for this edition: https://docs.google.com/document/d/1d69wcJZdUCavcH7O3ub2yXw5EMk-93FSXbRoUFL4jzE/edit

**Comment by oyealmond** [comment]
Hey @ahmadabugosh! Made some edits. Hope @laurenluz & @danelsuga can take a look soon to send it asap. Thanks!

**Comment by danelsuga** [comment]
gave it an edit! thanks, @ahmadabugosh.

**Comment by ahmadabugosh** [comment]
Sent! Can we tweet it please, @laurenluz @SteffanThorn @oyealmond 

"
In this month's newsletter

🚀 The Launch of Quadratic Funding on @Giveth 
💜 Results of @OctantApp Epoch Zero 
🏠 Featured project @andrewfunkspain 
🫶 GIVfriends @lensterxyz 
🗣️ Upcoming podcast with @thegrifft & @jarradhope_ 

https://news.giveth.io/givnews19 

"
