### ISSUE TITLE
tweet thread why traditional donating doesn't work 

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1482]
Made a first draft with a list of ideas. 

https://docs.google.com/document/d/1VQgA9Ib3exQ5Kot0Cr8rnQ8FDuKEdcsURw3hV7p2qHk/edit?usp=sharing

@oyealmond @laurenluz

**Comment by oyealmond** [comment]
I like all the reasons! 
Do you think you could draft a more final Tweet thread? @SteffanThorn

**Comment by SteffanThorn** [comment]
I've added a series of traditional donations vs crypto donations tweets. 

And updated the thread to compare it more to crypto donations on each part. 

Let me know what you think.

**Comment by oyealmond** [comment]
Maybe will be faster if we review these together on a call? @SteffanThorn

**Comment by laurenluz** [comment]
@SteffanThorn I reviewed & left comments. I think it's a great idea, but I think it needs some tweaks.

**Comment by SteffanThorn** [comment]
@laurenluz reviewed comments and scheduled tweets one per week. I think we could schedule the thread after the tweets.

That would be end of September.

**Comment by SteffanThorn** [comment]
If you want I could make another issue specifically for the thread.

**Comment by oyealmond** [comment]
thanks for scheduling @SteffanThorn!
