### ISSUE TITLE
Crypto supporting in Natural Disasters | Tweet Thread. 

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1483]
Okay this one is barely a draft. 

More like a few ideas. 

Would be great to get some help to build a more developed draft:

https://docs.google.com/document/d/18EbEvwI_cfSPugIpmxFIdJk2t9w9Oc8l3fT2MH0h7BU/edit?usp=sharing

@oyealmond @laurenluz

**Comment by SteffanThorn** [comment]
Doesn't look like there was much funding happening for ukraine war on giveth. maybe we could use a different crypto example for this issue -- or leave it out.

**Comment by oyealmond** [comment]
we can leave it out. As I'll be creating some things on the upcoming content. @SteffanThorn

**Comment by laurenluz** [comment]
how come we closed this? I think even if we leave out ukraine war relief, there is some good info in here about the earthquakes.

we can include info about iran as well, mention the GM episode and some of the projects raising funds to support people during the violent protests...

and like almond mentioned, the episode about venezula too.

I think it's delicate to navigate the right wording on these topics, but just highlighting the ideas that crypto can reach people all over the world with examples... it's a cool idea.

**Comment by oyealmond** [comment]
hey @SteffanThorn! 

What do you think of this new insights?

**Comment by SteffanThorn** [comment]
@laurenluz @oyealmond  I'm not sure which GM episodes mention these. Please share links.

**Comment by oyealmond** [comment]
They are not out yet. One is coming this Friday, The last one on Sep1st. @SteffanThorn

**Comment by oyealmond** [comment]
1st one on Crypto and Venezuela is out @SteffanThorn 

https://www.youtube.com/watch?v=itrr6YPAzlc&t=3s
