### ISSUE TITLE
🌞 GM! ep5 Tweets

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1485]
Hey! Could you [check out these drafts](https://docs.google.com/document/d/13sMg6GnJCLK8_YZstWJs3CShon9W4k1SAXuA9aARDvk/edit) for the following GM! episode please? 

@laurenluz 
@SteffanThorn 

Thanks!

**Comment by SteffanThorn** [comment]
they seem good to post

**Comment by laurenluz** [comment]
I added in Stee's edit and made some minor changes - they're good to go! do you want to schedule them @oyealmond ?

**Comment by oyealmond** [comment]
sure! thanks @laurenluz !

**Comment by oyealmond** [comment]
Scheduled!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1689260770184302592
https://twitter.com/Giveth/status/1687463499499204608

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1691797485583233414
