### ISSUE TITLE
Giver NFT tweets brainstorm 

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1486]
Repurposed some information from the Giver NFT article into some tweets. 
These can be filler tweets for gaps in the schedule. 

https://blog.giveth.io/the-givers-nfts-for-the-giveth-community-fa335ef9db01

https://docs.google.com/document/d/1HrptymByc50GLo5dBCQIn0HSaImw4nYfkyBHAZMAQpE/edit?usp=sharing

@oyealmond  @csggene3 @laurenluz

**Comment by oyealmond** [comment]
hey @SteffanThorn I see some Giver NFT Tweets, and other content regarding other stuff too. 

Could you please maybe clean the doc? To review the tweets this issue is purposed. Thanks! ☺️

**Comment by laurenluz** [comment]
reviewed

**Comment by SteffanThorn** [comment]
Scheduled all the GiverNFT tweets once a week. @oyealmond feel free to move them if more important content needs to be scheduled on those dates.

**Comment by oyealmond** [comment]
thanks @SteffanThorn!
