### ISSUE TITLE
QF feedback request email

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1487]
Hey @laurenluz @danelsuga @ahmadabugosh ! 

Could you review these [QF follow up email drafts ](https://docs.google.com/document/d/1wiLsQZ6qOJP1oCkVUntZBThxWwG-QcnCKQOigDlpy74/edit)please? 

After reviewing them we can plan to schedule them @ahmadabugosh 

Let me know your thoughts. 

Thanks!

**Comment by laurenluz** [comment]
made the issue for the feedback form in here: https://github.com/Giveth/giveth-planning/issues/1488

**Comment by oyealmond** [comment]
I added some QF data + the feedback form link. 
The 1st email (qf feedback) is ready. 
I'ld love to have the final @laurenluz ok to send it.

**Comment by oyealmond** [comment]
hey @ahmadabugosh ! 

@laurenluz reviewed the email. We can send it now. It should be send to everyone . Do you think you could support us sending this today? Thanks!

**Comment by ahmadabugosh** [comment]
@oyealmond the survey email has been sent!

**Comment by laurenluz** [comment]
I would have really like to review the feedback form before blasting it out to everyone

**Comment by laurenluz** [comment]
just made some edits to the form in typeform
