### ISSUE TITLE
QF User Feedback Form

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1488]
Can I get a second pair of eyes on this today/tomorrow? do you think I missed anything major in the questions?

@oyealmond @WhyldWanderer @danelsuga @ahmadabugosh 

https://docs.google.com/document/d/12XccXSROZCY5onSHC2bxRwpsdWHHdZtAGPdxs-72g9k/edit

**Comment by laurenluz** [comment]
@MoeNick or @divine-comedian - your feedback would be useful here as well if you have a bit of time today or tomorrow!

**Comment by missgene** [comment]
Here's the live link: https://giveth.typeform.com/to/ZEFauQiu
[(Link on typeform draft)](https://admin.typeform.com/form/ZEFauQiu/create?block=417f4569-da32-4411-b6b7-2e300633ee79)

Let me know what needs to be changed. @laurenluz 

If you have time, can you also review if I added the questions correctly and the order. @oyealmond Thank you! :)

**Comment by oyealmond** [comment]
This is great @missgene! I already tested both donors and project owners questions and it looks great. If @laurenluz we can add it to the email and send it asap.

**Comment by laurenluz** [comment]
thank you @missgene - This was great!

**Comment by oyealmond** [comment]
should we promote this feedback form in any other way besides the email? @laurenluz

**Comment by laurenluz** [comment]
yes please :D
