### ISSUE TITLE
Social Media Request - Ambassador Program

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1489]
Can we make a tweet/social post to invite people to sign up for the ambassador program season 2?

We plan to launch August 21st.. If we could do it by the end of this week? That would be great!
Link to the typeform: https://giveth.typeform.com/to/tP4yTK3u

I wouldnt mention the launch date... just invite people to join and let them know that we are currently contacting applicants

Lemme know if you have questions @oyealmond

**Comment by oyealmond** [comment]
Hey team! Could you provide your feedback on [these drafts](https://docs.google.com/document/d/1JrKB51tr4kPhO5s0HqS7phl4ScDJoFe7rZ8D__7-0Ws/edit), so I can schedule them please? @SteffanThorn @laurenluz @danelsuga 

Thanks!

**Comment by SteffanThorn** [comment]
Seems good @oyealmond 

I applied to this ambassador program to see the process.

**Comment by danelsuga** [comment]
Made a few corrections. All good! Thanks @oyealmond

**Comment by oyealmond** [comment]
thank you both! @danelsuga @SteffanThorn . 
Already scheduled.

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1689623148616962048
