### ISSUE TITLE
Calculating GIVBacks ~ Verified Projects donation history will be reviewed. Graduated Sanctions.

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#149]
## Calculating GIVBacks

5. Verified Projects donation history will be reviewed and we will make sure that we don't have any funny business happening.
    1. Graduated Sanctions: If we see a project is running their donations back through the system, their donors will not receive ANY GIVBacks that round and we will talk with the project and the donors privately about the issue, and decide if the verification should be removed.

**Comment by ForestSoleil** [comment]
Project verification process ongoing & being adapted as we test.

**Comment by ForestSoleil** [comment]
- Needs to be working & actively running verification process once GIVbacks launch.
- Needs to be live on Rinkeby.

**Comment by WhyldWanderer** [comment]
This information has been clearly outlined in the [MVP Spec doc](https://www.notion.so/giveth/Spec-GIVbacks-MVP-2d6335964e5b414082e41d7df89f9b3d) in Notion.
I dont see any more action items for this issue so Im gonna close it.
