### ISSUE TITLE
Video for Referral Program

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1490]
Hey @k3shavgupta @oyealmond , 

I think it would be great if we could make an explainer video for the referral program: https://giveth.io/referral

I made [one earlier](https://www.youtube.com/watch?v=WmCio7JxR8A&ab_channel=Giveth), but it's outdated because we changed the UX of how you can refer.

**Comment by oyealmond** [comment]
hey @ahmadabugosh! 
Sure, we can work on it. 
Couple of questions, you imagine the same format that the video you made before, more of a vlogging on the program? 

I image the video more like a walk through the product, showing product screen, and make it more of a step by step animation. What do you think of this approach?

**Comment by ahmadabugosh** [comment]
hey @oyealmond @k3shavgupta did we make any progress on this video? I think it would be really good to have a new video to promote the referral progtram.
