### ISSUE TITLE
QF main results. Tweet Thread. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1491]
Hey team! 

@WhyldWanderer made a great job putting together [the QF results](https://docs.google.com/spreadsheets/d/19Kp6tPTemjn6dBiMbSpihRoDnwaNrwjGNl_CS3Umy9s/edit#gid=345239806 ), and would be great if @laurenluz can help creating a doc with the main results in a clearer format. 

I saw some different amounts in the donations results on recent texts. 
For the follow up comms, I'll like to have accurate results. 

wdyt? @laurenluz

**Comment by laurenluz** [comment]
Hey @oyealmond!

We should wait until the sybil analysis is done before we start tweeting or publicizing stats. We can say the total amount raised by donors (something like $11k)  & the matching pool amount ($10k)

but we should wait to get the report back from trusta labs for data on "number of unique donors".
I think we could also mention like "number of donors w/ a gitcoin passport" perhaps... but maybe not.

are there other stats you were thinking of?

**Comment by oyealmond** [comment]
yes exactly! The totals. Amount raised, number of unique donors, project that raised the most? (Idk if its relevant). Thanks for the answer!

**Comment by laurenluz** [comment]
Hey @oyealmond!

I put together an email in #1492 that summarized interesting stats from the QF round. We need to still send out the funds... but as soon as we do that, we can send the email + send out some tweets that are basically a summary of the email!

Maybe you can use [this doc](https://docs.google.com/document/d/16Ou3aic4nm5T-cWMbyAeRgOTzJuxFg7ToHslDx91K2M/edit) for the info, and draft a nice tweet thread summartizing it so it's ready mid next week

**Comment by oyealmond** [comment]
Thanks @laurenluz! 

I basically translated your email [into a thread. Please review and provide feedback](https://docs.google.com/document/d/1tneHNLiL3gq0bcOEma8Vi7luCCqeNBj07J3oeVnIUFY/edit?usp=sharing). 

Can you help me review too? @SteffanThorn @danelsuga

**Comment by danelsuga** [comment]
Quick review. Looks great. This is going to sound crazy but how about a few exclamation points particularly in the gratitude section? 😍

**Comment by laurenluz** [comment]
looks great Almond, I added the link & changed some small things (minor edits). wait to get the ok from mitch & carlos before blasting it out!

**Comment by SteffanThorn** [comment]
Looks good apart from the standalone "about projects and donors" tweet IMO. 

I suggest we merge it with the previous tweet -- as suggested in the doc.

**Comment by oyealmond** [comment]
Scheduled for today. Thanks @laurenluz @SteffanThorn @danelsuga
