### ISSUE TITLE
QF - Funds are out! emails

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1492]
we should write an email (or two perhaps, to different audiences) when the funds are distributed, and include stats from the QF round, and perhaps some info from the feedback form

**Comment by laurenluz** [comment]
Drafting here: https://docs.google.com/document/d/16Ou3aic4nm5T-cWMbyAeRgOTzJuxFg7ToHslDx91K2M/edit

**Comment by laurenluz** [comment]
@danelsuga @oyealmond can you give this a review? :)

We should be able to send it out next week after the funds get sent!

**Comment by oyealmond** [comment]
Review it. Is great! 
Adding @ahmadabugosh. We will need to send this soon. 
Thanks @laurenluz!

**Comment by danelsuga** [comment]
Looking great!

**Comment by laurenluz** [comment]
ok I added the link to the forum post. As soon as the funds are sent out, we can send this email. @oyealmond @ahmadabugosh - please wait to get confirmation from Mitch that they are sent!

**Comment by oyealmond** [comment]
Hey @ahmadabugosh! @laurenluz confirmed the funds are out. We are ready to send this email!

**Comment by ahmadabugosh** [comment]
Sent!
