### ISSUE TITLE
R40+41 Verified projects tweet thread

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1493]
Hey team, delivering another thread with 11 projects and a request for the hashtag #MeetTheMakers use. Maybe we want to make it into 2 tweets? We have the potential for flooding here since Meet The Makers is becoming a monthly event. I am open to any useful tips from @SteffanThorn on how to use it as well and as much as we can. cc: @oyealmond @laurenluz 

Draft here: https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by SteffanThorn** [comment]
I've reviewed the thread @laurenluz @oyealmond

**Comment by SteffanThorn** [comment]
@NikolaCreatrix regards to the hashtag. A more unique hashtag like #GivethMakers would make much more sense. 

No one else would use it. 
When people click the hashtag: Tweets would then be organized on the timeline  and easy for users to find related tweets (which is the goal right?)

**Comment by oyealmond** [comment]
could you check out @SteffanThorn edits so we can shedule this soon @NikolaCreatrix ? 
Thank you! :D
https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by NikolaCreatrix** [comment]
Thanks a lot @SteffanThorn that's super helpful! We'll talk about it in our next MTM planning session today, @oyealmond already reached out to me sharing the idea and I am happy we found a solution! :)

**Comment by SteffanThorn** [comment]
@NikolaCreatrix I have to ask. Are you using an AI for these? Because this last one seemed really off for the projects.

**Comment by NikolaCreatrix** [comment]
Really? Yes I am, it saves me hours of time, and writing tweets is not my favorite thing TBH. This makes me ask in return, would you enjoy doing this if I prepared the project links for you?

**Comment by SteffanThorn** [comment]
@NikolaCreatrix Project links would definitely help.

**Comment by SteffanThorn** [comment]
scheduled for August 14th @oyealmond 

Feel free to move if need be.

**Comment by oyealmond** [comment]
Thank you so much @SteffanThorn! 
I saw it scheduled. Is perfect.

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1691102896803250178
