### ISSUE TITLE
Tweets QF feedback form. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1497]
hey @danelsuga @SteffanThorn @laurenluz 

Could you please review [these drafts? ](https://docs.google.com/document/d/1oij_gNXNyVxriKXNsJ_ccFDXpPIopSYwG_yTK7aexZY/edit)

They are a priority :) Thanks!

**Comment by danelsuga** [comment]
Done!

**Comment by laurenluz** [comment]
all reviewed @oyealmond!  I just made direct edits. do you want to add them to the schedule?

**Comment by oyealmond** [comment]
sure thanks @laurenluz!

**Comment by oyealmond** [comment]
Yes no worries! Thanks! :D

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1691072711638781952
https://twitter.com/Giveth/status/1689290960658669570

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1693322561587667294
