### ISSUE TITLE
Tweet brainstorm Aug 9th

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1498]
I pulled ideas from different places. 

In the doc I have the resource in brackers ( ) -- followed by the tweets. 

These tweets can be used to fill up the scheduler around the important content. 

A lot of it is simply reminding our audience of previous ideas. 

https://docs.google.com/document/d/16BUwwURQXEGiYndCTGCk3C0qau3v4HTI4zKPwPyqq0s/edit?usp=sharing

@laurenluz @oyealmond

**Comment by laurenluz** [comment]
reviewed! just one I didn't like and a few small edits. the rest are good! thank you @SteffanThorn

**Comment by SteffanThorn** [comment]
Scheduled all of them apart from the optimism one lauren didn't like. 

@oyealmond feel free to move them more more important content when needed. These are fillers.

**Comment by oyealmond** [comment]
thanks! yeah, def I may be moving some to fill GG18 and Optimism. Thanks @SteffanThorn !
