### ISSUE TITLE
Post a recap thread

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1499]
Hey team @Brodyann7 and @oyealmond 

This is the draft that Anne created: https://docs.google.com/document/d/1mPXffMCMqBGs4Xq4-ETmFoE9jufLR88GjeyyWvWzWT4/edit?usp=sharing

I would like to add based on our discussion:
- link for the stream (twitter or youtube one)
- invitation for next session - teaser - something like stay tuned to learn about the project we'll host next session happening September 6th 9am CR time
- Make sure we include the #GivethMakers (Meet The #GivethMakers)

Ideally to schedule this for asap.

**Comment by oyealmond** [comment]
made some minor edits, you can check them in the doc if you want @Brodyann7 :) 

Already scheduled!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1690061021807828993
