### ISSUE TITLE
Stretch MVP Reqs ~ Givers can create an account to be notified when GIVBacks are ready to be claimed

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#150]
## Stretch MVP Requirements

- As a Giver, I want to create an account so I can be notified when my GIVBack is ready to be claimed.

**Comment by GriffGreen** [comment]
Email notifications are being implemented

**Comment by WhyldWanderer** [comment]
Autopilot should allow us to make a contact list just for GIVback donor outreach.
