### ISSUE TITLE
Update new designs

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1500]
Hola dear @oyealmond 

I created this issue for the updated designs with the new name "Meet The Giveth Makers"

**Comment by NikolaCreatrix** [comment]
Hey @oyealmond just checking in. Did you have a chance to look at updating the designs? I would like to use the banner for creating the Eventribe link. The sooner the better as it depends on it. If I can finish up creating the Eventribe event, then we can include it in the email donor invite as well as other places...

**Comment by oyealmond** [comment]
Here @NikolaCreatrix! 

<img width="1200" alt="LinkedIn_azul" src="https://github.com/Giveth/giveth-planning/assets/110692280/f59ef32d-85d8-4972-9392-b15058985a0e">
<img width="1200" alt="MTM_LinkedIn" src="https://github.com/Giveth/giveth-planning/assets/110692280/09ec00dd-20fb-4584-8029-22ec2b32d69c">

**Comment by oyealmond** [comment]
Here @NikolaCreatrix 

<img width="1200" alt="Linkedin_MTM" src="https://github.com/Giveth/giveth-planning/assets/110692280/b3b86497-fcbd-4d81-9140-86529f9deef6">
<img width="1200" alt="MTM_LinkedIn" src="https://github.com/Giveth/giveth-planning/assets/110692280/8e726ecf-91d2-467c-b483-d92b6d409af1">
