### ISSUE TITLE
Communications for social media (Twitter, FB, Insta, LinkedIn)

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1502]
We need to create comms plan for all social media accounts - Twitter, FB, Insta, LinkedIn, discord

Hoping to start with promotions and execution by next Monday Aug 21st.

**Comment by oyealmond** [comment]
Need all the details of this to prepare the comms. @NikolaCreatrix 

Social media handles of the projects participating
Date, 
Time
 And anything else (info) I'll need to include in the social media posts.

**Comment by NikolaCreatrix** [comment]
Hi @oyealmond, yes, you can see the handles here: https://docs.google.com/spreadsheets/d/1avlSmyCZ-hYSrlhejigqr3gK5QJGJC2HZnhghEbdfdA/edit#gid=0

We have only 5 projects confirmed so far, but it is possible that more projects will respond to my outreach message. One project doesn't have any twitter account, only IG.

Date: September 6th, 2023
Time: 9 am Costa Rica time or 3 pm UTC

The common theme for all 5 projects: Social Impact and Empowerment, or Web3 Technology and Innovation - would be nice to include somehow in the text.

**Comment by NikolaCreatrix** [comment]
Can we try to plan the advertisement? When can we start posting/schedule it? I would like to make sure it is in sync with me sending out the project's ad message in the other issue... @oyealmond 
sorry for the pressure but it's about time to start... do you need any help?

**Comment by oyealmond** [comment]
sure! Here's the tweets for [you to review. ](https://docs.google.com/document/d/11iBuo88UhnxcmD4N3wyGYmJ4E8xhDkA20qyIJedAwXM/edit) 

Let me know your thoughts so I can schedule! 

yes! If you have time to draft some social media posts next time to move faster will be great. We have lot of social media messages happening at the moment.

**Comment by danelsuga** [comment]
I had a quick review! These are great, but I think an important addition would be to be more specific about WHAT web3 tech & innovation they're up to, and have that featured in each tweet.

No one is coming just b/c it's "Meet the Makers". It has to have an appeal to them, a personal appeal. A generic tweet will not do the trick. We have to draw them in with something meaningful and specific.

I can dig around but it's closing in on 1am here so it will have to be tomorrow!

**Comment by oyealmond** [comment]
Thanks @danelsuga! I think you have a great point, we should be more specific about our narrative in order to be more appealing . Maybe this is something @NikolaCreatrix & @Brodyann7 can work on? Strength the narrative a little bit to make the event more appealing. Wdyt?

**Comment by NikolaCreatrix** [comment]
I like your feedback @danelsuga and please go ahead if you have an ideas to make it better... the thing is that those projects are each a bit different in what they focus on so the narrative should be something that connects them all and that's where the common theme comes from. I would prefer if we speak about the social impact and empowerment which they all have in common but each in a different way. Please feel free to improve Almonds tweets and we can use it!

**Comment by danelsuga** [comment]
I gave some ideas. Might have set you over the word count! Give it a try and maybe see if you can integrate some of that info. I tried to write what you explained above; of course it's hard to draw all that into one Tweet-sized narrative, so in general I ended up making items in a series! But I think the second one comes close to being able to say why all of these seemingly disparate subjects are related in the way they are envisioning a bigger picture by focusing on community issues so that progress can have exponential impact. It's hard to cram all that into a Tweet! :P

**Comment by oyealmond** [comment]
Thanks @danelsuga :D . Scheduled on:

Aug 27
Sep 1st
Sept 6th

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1695813946744226286
