### ISSUE TITLE
Invite donors via email

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1503]
Send segment email to donors only with personal invite to the event

**Comment by Brodyann7** [comment]
Draft @NikolaCreatrix 

https://docs.google.com/document/d/14uyjUmraVod0lBKqfr_6qt3E4krY3Xxyr4vREu1Ylb4/edit

**Comment by NikolaCreatrix** [comment]
I love it @Brodyann7 !! I went through and made some minor edits and comments and I would love for @ahmadabugosh have a look and review it as well, see if you have anymore thoughts or feedback. Hoping to send this on Monday lastest...

cc @oyealmond

**Comment by oyealmond** [comment]
I think this is way too long. I'll try to make it shorter before sending it. @NikolaCreatrix @Brodyann7

**Comment by NikolaCreatrix** [comment]
Okay, if you must. When do you think you'll be able to do the final edits @oyealmond so I can organize with ahmad to send this email out?

**Comment by Brodyann7** [comment]
edits accepted @oyealmond

**Comment by oyealmond** [comment]
I made a shorter text @Brodyann7 , only missing some name projects and links, could you help me fill them out?

**Comment by oyealmond** [comment]
Ready! I made a shorter version below. Please[ give it a review](https://docs.google.com/document/d/14uyjUmraVod0lBKqfr_6qt3E4krY3Xxyr4vREu1Ylb4/edit), and I believe will be ready to send! 

@NikolaCreatrix 
@danelsuga 
@ahmadabugosh 
@Brodyann7

**Comment by ahmadabugosh** [comment]
Added some comments too. I think it's ready to send

**Comment by oyealmond** [comment]
@Brodyann7 can you accept @ahmadabugosh suggestions? And then we're ready to go!

**Comment by NikolaCreatrix** [comment]
I pinged @Brodyann7 to accept the last suggestions, but I also see that since we have the final edited version in the doc already, let's send it out! Exciting! :)) can you please send the final version to the donor database @ahmadabugosh pretty please.

**Comment by oyealmond** [comment]
hey @ahmadabugosh! I know you mention you had this on your scope already. Let us know if you need further support!

**Comment by ahmadabugosh** [comment]
Hey @NikolaCreatrix @Brodyann7 @oyealmond , I scheduled this out to send on Monday. I don't want to send it earlier because I just featured Meet the Makers in [our newsletter](https://news.giveth.io/givnews20) yesterday, and I think it's better for these kind of events to invite people closer to the date.

**Comment by oyealmond** [comment]
Agree! Thanks @ahmadabugosh! :)

**Comment by NikolaCreatrix** [comment]
Thanks for the heads up @ahmadabugosh 
Why do you think (or @oyealmond ) it is better to invite/inform donors 2 days before the event/ closer to the date? I would like to understand the logic behind this statement. :)

**Comment by ahmadabugosh** [comment]
Hey @NikolaCreatrix I already sent it out yesterday! I also included it in the newsletter which went out last week. 

What I meant by the statement, is I noticed for events the closer you send the invite to an event (if it's online and free like ours and doesn't require travel or buying a ticket), the higher attendance is.
