### ISSUE TITLE
Advertise on Event aggregator websites

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1504]
Activate the Eventribe account again and use to RVSP.

Post about the event on 10 - 20 websites for web3 events

**Comment by NikolaCreatrix** [comment]
I am waiting for the designs to finish and publish the online event to then start posting on the event aggregator websites based on @ahmadabugosh advice and recommendation. I would love if you have anymore bandwidth to help with finding more of these websites.

I have started this spreadsheet you can add to: https://docs.google.com/spreadsheets/d/1GivheGlep-H3KUrzXve_f34V8BsISx6t062Vt3CjFa0/edit?usp=sharing

**Comment by ahmadabugosh** [comment]
hey @NikolaCreatrix I added a bunch, let me know when this is ready and we can star posting

**Comment by NikolaCreatrix** [comment]
Thanks a lot @ahmadabugosh, the event is created, if you think it's good enough to go, we can start. https://www.eventbrite.com/e/meet-the-giveth-makers-tickets-700158381567?aff=oddtdtcreator

**Comment by NikolaCreatrix** [comment]
Whenever you get to this, I'd love it if you could help with this @ahmadabugosh and track it in the sheet. I think the sooner the better... do you have the bandwidth?
