### ISSUE TITLE
Comms for project's advertisement

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1505]
Hola dear comms and @oyealmond 

Needing your help and support with creating the new comms messages for project owners to share with their community.
Can you help please? We'll need the banner and the message template.

**Comment by oyealmond** [comment]
I think we can share something very simple with the projects mentioning

"Hey ___ please support our GivethMakers event by inviting your community & supporters next *date* at *time* on Giveth's Youtube & Discord channels.  

*Links to Giveth Youtube & Discord*

Please share in your social media, Discord & Telegram Channels invitations for your community to join. A message you can use: 

📣 Calling all Changemakers! 

We'll be participating in @Giveth's Meet The #GivethMaker event next *date* at *time* on their Discord & Youtube Channels. 

Join us, and learn more about our project mission & our future plans! 

*links Giveth Youtube & Discord*" 

Something like that. 
I'll fill the info with the dates, time and links before sharing @NikolaCreatrix

**Comment by NikolaCreatrix** [comment]
Yeah sounds good, I'm ready to distribute it to the projects when the time comes.

**Comment by oyealmond** [comment]
@NikolaCreatrix here's the Youtube link of the next MTGM livestream: 
https://www.youtube.com/watch?v=RJep8F71Kyc  

You can share w projects for them to share too!

**Comment by NikolaCreatrix** [comment]
Sent to projects.
