### ISSUE TITLE
Post ETHBcn Tweet - How to DAO and not die panel. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1508]
Hey @SteffanThorn @laurenluz @danelsuga 

Can you help me review[ this draft](https://docs.google.com/document/d/1u4vmePhx4pOJ47G9vzy2vj9K11xULEl_xzCuyCuiHCg/edit) please?

**Comment by danelsuga** [comment]
Reviewed! Love the video still.

**Comment by SteffanThorn** [comment]
Left some variations for the first line. My initial response to this tweet was something was lacking -- so I hope my suggestions add that in.

**Comment by oyealmond** [comment]
Thanks for your comments @SteffanThorn! Already applied them. Is scheduled.

**Comment by laurenluz** [comment]
oh oops, I made some edits after seeing your comment @oyealmond. take it or leave it

**Comment by oyealmond** [comment]
sure! I can update the tweet on tweethunter! @laurenluz

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1693383099193680337
