### ISSUE TITLE
Optimism Campaign - add your OP address

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1510]
related to #1376

we got the OP finally, so we should start up again the "add your optimism address and get OP tokens campaign"
we'll have optimism GIVbacks & GIVpower going out soon and it will be great to share about it during that time too
the narrative of like "verified project owners, add your optimism address and get OP! When donors give to you, they will get GIV on optimism. Then they can use that GIV to earn rewards, get GIVpower and boost your project"
ofc not all in one pieces like that 👀

we should draft some wsocial media content for this + work it into a nice marketing strategy. it's a great incentive also for new projects to join Giveth, get verified!

@oyealmond @WhyldWanderer @SteffanThorn @missgene

**Comment by SteffanThorn** [comment]
Made a brainstorm doc for posts. 
https://docs.google.com/document/d/1K1Stw0xoVHrJXMKt1_m1R6DxGpLo0E-LR8gXb-akSf8/edit?usp=sharing

I think a good idea would be to do a thread on Optimism:
•Why we expanded to Optimism
•Everything you can now do on Optimism
•Benefits (lower fees, Gitcoin also uses) 
•Free OP tokens for adding address

What do you think?

**Comment by laurenluz** [comment]
yeah we could mention about optimsims's mission... alignment for public goods & shill @ retropgf in one tweet.

one of the biggest reasons we expanded to optimism though is very simply: because they paid us to.

ofc, we also did because it expands chains in which people can raise funds or donate, low gas, it's good to build on Optimism for retropgf.

Not sure if "gitcoin uses optimism too" is super relevant to the thread.

we should say though that when people donate on optimism they will get GIV on optimism... which they can then lock up & boost projects w/ via GIvpwer.

**Comment by laurenluz** [comment]
Just quickly read through the tweets in the doc. Important point:
Projects only get the 25 OP if they are a VERIFIED project that adds their optimism address. So we can make these tweets also explaining that there is an extre incentive to add your project to giveth and get verified.

**Comment by SteffanThorn** [comment]
Thanks for the notes @laurenluz -- I'll do another round of tweets to include the alignments.

**Comment by oyealmond** [comment]
Hey @SteffanThorn @laurenluz @danelsuga can you review this [announcement/tweet](https://docs.google.com/document/d/1cgHcz85kZ0yYv4N14_aRxl4k4_B_MwEDsHk7WkJKWjo/edit?usp=sharing) around this campaign please?

**Comment by danelsuga** [comment]
Done!

**Comment by WhyldWanderer** [comment]
GIVbacks on Optimism should be live in the next few days... tentatively by the end of the week. 
Should we draft some twitter content to announce GIVbacks on Optimism? If you have it ready, I can tell you when they get distributed and you can pull the trigger. 

It can also be incorporated into the existing GIVbacks distribution announcement tweets each round. This will be for round 43

**Comment by missgene** [comment]
@oyealmond Should we also have a post for IG/FB for what Ashley mentioned above? @SteffanThorn In case we already have a draft for this, can you send it my way so we can also post it on our other social media accounts? Thanks!!

**Comment by oyealmond** [comment]
we don't have anything drafted yet, I'll work on this. @missgene would be great to have your support posting this too! 
Let's align on DMs.

**Comment by WhyldWanderer** [comment]
Yes @ahmadabugosh.. you can easily just mention it in the email that you already send out. 

Keep in mind that this distribution include ALL donations made on Optimism until August 22nd... so it will be multiple rounds.

Im not sure how this affects your mailing list since you only send it out to the people who donated in the round right?

**Comment by WhyldWanderer** [comment]
Also, we should consider what type of notifications users will receive in the notification center on the DApp.. 
Do we plan to differentiate between Gnosis GIVbacks and Optimism GIVbacks? Or can they be added together?

Hmm maybe this is a question for @CarlosQ96...

**Comment by SteffanThorn** [comment]
@missgene @WhyldWanderer @oyealmond 

I updated this doc with tweet announcements for optimism. there's also some memes at the bottom. 

https://docs.google.com/document/d/1K1Stw0xoVHrJXMKt1_m1R6DxGpLo0E-LR8gXb-akSf8/edit?usp=sharing

**Comment by oyealmond** [comment]
thanks @SteffanThorn! I added 2 more tweets to your docs, as for this specific case we need some exact details that @WhyldWanderer shared me. Let's use the rest of your tweets when GIVpower is out too

**Comment by oyealmond** [comment]
tweets scheduled! @WhyldWanderer . 
Maybe we can close this issue, and open new ones for the follow up Rounds?

**Comment by WhyldWanderer** [comment]
Sounds good!
