### ISSUE TITLE
Gitcoin Round 18 Email to Database

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1513]

**Comment by oyealmond** [comment]
Hey @anamarija09! Thanks for your help! Can you share a draft of this email 1st so we can review it? 
Thanks!

**Comment by oyealmond** [comment]
hey @anamarija09! 

Any updates on this?

**Comment by anamarija09** [comment]
here is a draft: https://docs.google.com/document/d/1srBrUJmSG1v2Y_wdyzmOOxiGksBG011iFYUIiIg6OtY/edit?usp=sharing

**Comment by oyealmond** [comment]
👆🏼 Can you review this one @ahmadabugosh please?

**Comment by ahmadabugosh** [comment]
Thanks @anamarija09!  I sent you a few examples of previous emails. I would recommend to also add the follwing: 

- Can you mention the dates of the round and when the deadline to donate is
- You can mention the chain they need to donate on (which is Optimism for Giveth)
- Mention how now allows users to add multiple items to their cart and checkout at one time (which is a new feature, making it easier to donate). 
- You can also mention the other Giveth Galaxy projects too (Pairwise, Praise etc.)

**Comment by anamarija09** [comment]
Thank you @ahmadabugosh for the suggestions, new example is in the doc: https://docs.google.com/document/d/1srBrUJmSG1v2Y_wdyzmOOxiGksBG011iFYUIiIg6OtY/edit?usp=sharing

**Comment by ahmadabugosh** [comment]
@anamarija09 @oyealmond Email sent!
