### ISSUE TITLE
Gitcoin Round 18 promo video

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1515]

**Comment by ahmadabugosh** [comment]
Points in the video would be: 
- Support Giveth to continue making progress in our 2023 roadmap and continue thriving in the bear market
Then mention updates we did ([from the landing page](https://explorer.gitcoin.co/#/round/10/0x8de918f0163b2021839a8d84954dd7e8e151326d/0x8de918f0163b2021839a8d84954dd7e8e151326d-86))
- Quadratic Funding
- Gitcoin passport
- Referral program
- New chains (Optimism, Celo, Polygon)
- And beyond with our sights on DAOifying nonprofits

@SteffanThorn @k3shavgupta

**Comment by SteffanThorn** [comment]
@oyealmond @ahmadabugosh I left some hook suggestions. 

It's important to consider who we are targeting. 
If we are targeting people who already know about Giveth, it's fine. 
But if we want to expand our reach to newer donors, we need more info about giveth in the hook.

**Comment by danelsuga** [comment]
Looking good! Made a bit of edits.

**Comment by oyealmond** [comment]
Thanks for your edits! @danelsuga @ahmadabugosh @SteffanThorn . 

We're starting with the creation of this video. 
@k3shavgupta

**Comment by k3shavgupta** [comment]
cool

**Comment by oyealmond** [comment]
Thanks @k3shavgupta! 

https://twitter.com/Giveth/status/1694427147484479924

**Comment by SteffanThorn** [comment]
Awesome work @k3shavgupta -- what your discord? I want to give you some praise.

**Comment by k3shavgupta** [comment]
> Awesome work @k3shavgupta -- what your discord? I want to give you some praise. 

Thanks Stefan 
@k3shavgupta  username on Discord
