### ISSUE TITLE
End of Gitcoin round video for Giveth

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1516]

**Comment by ahmadabugosh** [comment]
@SteffanThorn Had the idea to create a video at the end of the round to promote Giveth and the idea you can support projects beyond the Gitcoin round.

**Comment by oyealmond** [comment]
Don't know if a video with this specific message will be strong enough. I believe will be better to add Giveth 24/7 donation platform in all our messaging instead.
