### ISSUE TITLE
Watch me donate on Gitcoin video

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1517]

**Comment by ahmadabugosh** [comment]
- Record a short screen recording of "how to donate on Gitcoin" for newbies.
- Mention the video on our social pages
- Anyone that wants to can comment their own video of them donating on Gitcoin as proof (ex. @SteffanThorn would show himself donating for the first time and reply on Twitter with his video, encouraging others to do the same)

**Comment by oyealmond** [comment]
mmm, let's share some Youtube tutorial on how to donate. I think we should not spend our resources on smth that's already created...

**Comment by oyealmond** [comment]
@k3shavgupta did the how to donate! 
Thanks! 
https://twitter.com/Giveth/status/1695122332237381879
