### ISSUE TITLE
Get short videos from projects

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1518]

**Comment by oyealmond** [comment]
Oh I love this idea! @ahmadabugosh . And right now we actually have the resources to make this happen! 

Let's make this idea a follow up on the Giveth QF Alpha Round. We should send an email to the projects that participated so we can get stronger testimonies.  

@missgene let's define the questions, and then figure out which is the best channel to contact this projects, Either twitter DM, or Ig, or email...

**Comment by oyealmond** [comment]
Did a [spreadsheet w the Alpha Round Projects ](https://docs.google.com/spreadsheets/d/1YX4Pfe5Qjix1uDSLWzgXg5eAqtz-SdLLzr5HIi9ntEc/edit#gid=0)to follow up who I already contacted.

**Comment by oyealmond** [comment]
Ok, @NikolaCreatrix has the instruction to contact the projects. we should start receiving some videos soon.

**Comment by NikolaCreatrix** [comment]
yeah, working on it. It's looking promising so far. How many do we need?

**Comment by oyealmond** [comment]
Let's follow up on the ones we already requested. Thanks @NikolaCreatrix! Hope they deliver!

**Comment by NikolaCreatrix** [comment]
Hey team, so far I have received 3 videos out of 7 promised. I am working on getting more, hopefully during this week, but for now I have created this folder where I'm dropping them for the team.
https://drive.google.com/drive/folders/1KOdmtwzgRiYN2j-8THJRJsfZ_kAxl50r?usp=sharing

@oyealmond

**Comment by oyealmond** [comment]
Thank you so much @NikolaCreatrix  ! We're already working on this videos you provided. They are amazing thanks!

**Comment by oyealmond** [comment]
hey @danelsuga and @laurenluz could you please help me review [these tweets](https://docs.google.com/document/d/1YiihpUAiKVW_BKUOGa6psnLNxCcEnB7sRf_sPXIw92Q/edit?usp=sharing) of the project owners which we'll be featuring with a video?

**Comment by danelsuga** [comment]
looking good!

**Comment by oyealmond** [comment]
great! thanks @danelsuga . I'll start scheduling these. 
If you have any feedback @laurenluz lmk and I can edit

**Comment by laurenluz** [comment]
skimmed really quick, no objections! great work @oyealmond

**Comment by oyealmond** [comment]
all scheduled, thank you both!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1722555219387535473
https://twitter.com/Giveth/status/1722192838518022170
https://twitter.com/Giveth/status/1724276573128335404
https://twitter.com/Giveth/status/1721830447930331269
https://twitter.com/Giveth/status/1720788589988942293
https://twitter.com/Giveth/status/1720380913568079943

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1728761218100244502

**Comment by missgene** [comment]
Hi @oyealmond! I started tagging you on Notion for the posts to review :) I'll add more posts tomorrow! Also, should we just publish one per week?

**Comment by oyealmond** [comment]
yes @missgene thanks! Let's use this issue to follow up https://github.com/Giveth/giveth-planning/issues/1667

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1734272586287104192
