### ISSUE TITLE
Create Eventribe event and follow ups and post on agregator website

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1519]
I am creating an online event at the Eventribe. Can finish after I have the updated banner.

Todos:

- [x] Create and publish the event
- [ ] Use it in email invites - donors
- [ ] Post about the event on event website aggregators (tips from @ahmadabugosh)
- [ ] craft a follow up message as a reminder after RVSP

**Comment by oyealmond** [comment]
New designs @NikolaCreatrix 

<img width="1200" alt="Linkedin_MTM" src="https://github.com/Giveth/giveth-planning/assets/110692280/a8b7ac48-eb97-48df-b71f-25871e9c3402">
<img width="1200" alt="MTM_LinkedIn" src="https://github.com/Giveth/giveth-planning/assets/110692280/9a0f07f9-c8cb-4875-9e3c-f8a86ab624cb">

<img width="1024" alt="Twitter - MtM" src="https://github.com/Giveth/giveth-plann
<img width="1024" alt="Twitter - MTM2" src="https://github.com/Giveth/giveth-planning/assets/110692280/57a04430-9b5c-46ae-8ad5-0f81d0d2398f">
ing/assets/110692280/22c897bf-69be-4012-b26e-29ffd1b36654">

**Comment by NikolaCreatrix** [comment]
Nice! Thanks Almond, I have uploaded the banner and published the event, this is the URL. https://www.eventbrite.com/e/meet-the-giveth-makers-tickets-700158381567?aff=oddtdtcreator
