### ISSUE TITLE
SEO Landing Page How Nonprofits Can Use Crypto for Fundraising

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1522]
Write content for the landing page with the keyword Nonprofit Fundraising. 
First Draft before 22nd August.

**Comment by surbhiaroraa** [comment]
@oyealmond 
I have created this outline/reference doc for this blog. However require help of some content writer to complete this/improvise this. Can you please assign concerned person for this?
Blog - [How Nonprofits Can Use Crypto for Fundraising](https://docs.google.com/document/d/1Agtv3psOUSA_He0cxVtSKba-8YjkdKIK7lyMnCelJHY/edit?usp=sharing)

**Comment by oyealmond** [comment]
This is looking great to me! 
@surbhiaroraa will be better to always share the link of the doc that's the editable version so we can write suggestions/review right away :) (Already asked you for edition permission). 

@danelsuga can you help us with your editing powers on this one please?

**Comment by surbhiaroraa** [comment]
cc: @divine-comedian  Just to keep you in the loop

**Comment by oyealmond** [comment]
Hey @SteffanThorn! 

Same as you did here https://github.com/Giveth/giveth-planning/issues/1541 and here https://github.com/Giveth/giveth-planning/issues/1539 , could you please help us apply [this outline ](https://docs.google.com/document/d/1Agtv3psOUSA_He0cxVtSKba-8YjkdKIK7lyMnCelJHY/edit)to Giveth for SEO "How Nonprofits Can Use Crypto for Fundraising" please? 

For SEO [this sheet](https://docs.google.com/spreadsheets/d/10e9ltdCl16rXgZ82gxAEZ-ROlhQiSnnIItUKfSaGUgc/edit#gid=325379001) has a list of the keywords we're targeting.

Let me know your thoughts. 
Thanks! :)

**Comment by SteffanThorn** [comment]
I've added the empty parts. Without removing the notes for what to add. 
Also provided an alternative conclusion as the conclusion has the same line as the introduction.

**Comment by surbhiaroraa** [comment]
Hey @SteffanThorn 
Thank you adding the required parts. I had a look - so I just wrote an outline as guiding points what we should write. The tonality language storytelling and plugging in necessary keywords is pending even in that outline. 
Can you relook at the draft from that perspective and improvise the entire thing now?

**Comment by SteffanThorn** [comment]
Refined version made. Scroll down past the original version to see.

**Comment by surbhiaroraa** [comment]
> Refined version made. Scroll down past the original version to see.

@SteffanThorn Please modify the introduction a bit to include and plug in Giveth. Also throughout the article just check if there is any other opportunity to plug in Giveth.

**Comment by oyealmond** [comment]
Hey @surbhiaroraa, I believed the intro already includes Giveth :). Also I added the Giveth links you suggested @SteffanThorn, and added a couple more I thought could be useful. 

I don't know if @ahmadabugosh & @danelsuga already review [this piece?](https://docs.google.com/document/d/1Agtv3psOUSA_He0cxVtSKba-8YjkdKIK7lyMnCelJHY/edit) If not, could you give it a check?

**Comment by danelsuga** [comment]
Let comments. Need to come back tomorrow to support one change if needed. 

Also, this article is making me think: we REALLY need to include --as a matter of course-- that Ethereum uses less than 1% of electricity than Bitcoin. It's really a huge, significantly huge reason why crypt nubes don't believe in crypto. Will bring this up tomorrow in comms.

**Comment by SteffanThorn** [comment]
@danelsuga I made a redo of the unclear project. 

@surbhiaroraa @ahmadabugosh Adding on from What Danel is mentioning above, Do you think having an SEO article talking about something like "Is blockchain/crypto bad for the environment?" would be good? Gives us a somewhat related topic that we could then feed into the concept of ReFi.

**Comment by danelsuga** [comment]
Nice idea @SteffanThorn. I think that's a great place to start. I'm sorry I didn't bring this issue up at comms as planned. I missed half the meeting running to and fro daughter's violin class. Apologies. It does seem to me though that this is a huge huge huge obstacle (read misunderstanding) for regular folk from joining crypto. We need to correct this, and it's easy.

**Comment by SteffanThorn** [comment]
@surbhiaroraa I think this article is good to go

**Comment by surbhiaroraa** [comment]
@oyealmond Let me know once you have finalised this, I will look at the design aspect and go ahead with publishing.

**Comment by oyealmond** [comment]
Sorrry for the delay on this task. I got stuck with our Optimism bomb. This one is ready to be published @surbhiaroraa @SteffanThorn . Don't know if you already have the Medium access @surbhiaroraa

**Comment by surbhiaroraa** [comment]
Thank you @oyealmond 
Thats okay - Optimism indeed is a priority right now. I will start moving ahead on this. Also, I don't have medium credentials. Can you please provide that? Thank you.

@rodricastillo9013 - Need your help with the visuals. For your information these landing pages will be published on Giveth's medium handle so accordingly graphics have to be made. I am adding pointers for each graphic in the document itself. 
[Document here](https://docs.google.com/document/d/1Agtv3psOUSA_He0cxVtSKba-8YjkdKIK7lyMnCelJHY/edit#heading=h.yw3retihq4me)
You can always DM me or call me for any help or clarifications. Lets get this done ASAP please?

**Comment by oyealmond** [comment]
Hey @surbhiaroraa! I think I already mentioned I don't have access to the Giveth Medium. You should ask either @danelsuga or @laurenluz, I believe they can guide you get your credentials. :) 
Also remember Rodri doesn't check Github. You need to coordinate w him through DMs

**Comment by surbhiaroraa** [comment]
Okay @oyealmond. I will take the credentials from them. 
I am coordinating with Rodri on DMs and calls. All good :)

**Comment by danelsuga** [comment]
@surbhiaroraa first set up a Medium account, and we can add your access to Giveth.

**Comment by surbhiaroraa** [comment]
Hi @danelsuga 
I have Medium account - @surbhi.30aroraa. Can you provide me access on this?

**Comment by danelsuga** [comment]
Great. I've just added you as a writer.

**Comment by danelsuga** [comment]
"Only publication owners can add or remove publication editors", which means for you to be an editor (someone who can add or remove stories and directly publish or edit submissions), you'd need to be added by @laurenluz, I believe. For now being a writer is great. You select "add to publication" before you submit the story, and it will pass to the Giveth account so it can be published there. 

Just realizing however, for SEO pages we obviously want them published AS Giveth, so the above does not apply in that case!

**Comment by ahmadabugosh** [comment]
hey @danelsuga, sorry what are we trying to do here? I don't think Medium has the option to publish as the publication i.e "publish as Giveth", so I think it would be fine for Surbhi to publish like we normally do under her name and then we publish it under the Giveth publication.

**Comment by danelsuga** [comment]
Hi @ahmadabugosh thanks. Actually, as far as I know and have seen, it is possible to publish as the account name and without a writer's specific account (so that it says "Giveth" and not a particular person). To do that, the publication has to have a user account as Giveth. I think that makes sense, as we do not want the SEO pages linked to a particular person.

**Comment by danelsuga** [comment]
Medium itself recommends this approach. 

https://help.medium.com/hc/en-us/articles/360053391853-How-do-I-publish-on-Medium-as-a-company-

**Comment by surbhiaroraa** [comment]
@oyealmond - This is scheduled to be published for 2nd November. 
I will share the social media posts to promote this page.

**Comment by oyealmond** [comment]
https://blog.giveth.io/how-nonprofits-can-use-crypto-for-fundraising-ef3edb8c5929
