### ISSUE TITLE
SEO Landing Page: Why Crypto is the Future of Raising Money for Charity

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1524]
Write landing page content for keyword "ways to raise money for charity"
Brief deadline: August 30

**Comment by surbhiaroraa** [comment]
Brief of this is pending on me. 
I am feeling blocked on this particular topic. Any suggestions how can we approach this topic? What can we talk about in this?
@oyealmond @ahmadabugosh @WhyldWanderer @danelsuga @SteffanThorn

**Comment by ahmadabugosh** [comment]
@surbhiaroraa Why not make this about why charities should consider crypto? 

It could be something like "Why Crypto is the Future of Raising Money for Charity", and then mention points like:

- Access to global markets
- Grass roots impact
- Transparency
- Low fees
- Create an economy ([turning non profits into impact daos](https://blog.giveth.io/evolving-nonprofits-into-regen-economies-f8282f97f8d3))

**Comment by surbhiaroraa** [comment]
This is perfect. You are awesome. Thank you.

**Comment by WhyldWanderer** [comment]
Should we include this video somehow?
https://youtu.be/u5nUpYIbABE

**Comment by surbhiaroraa** [comment]
@ahmadabugosh 
Does including video help with SEO?

**Comment by ahmadabugosh** [comment]
@surbhiaroraa It does help because it could appear on the SERP (search engine results page) under the video section and as a preview, plus including a video would make people stay longer on the page, which also helps.

**Comment by SteffanThorn** [comment]
Draft done. Do we have a video to explain the nonprofit to impact DAO concept in more detail?

https://docs.google.com/document/d/1WK9rPuRIKJEzZdP5oOY8j1xUxPeYNilAE825uAeiAI4/edit?usp=sharing

**Comment by surbhiaroraa** [comment]
@SteffanThorn 
Can you please give me edit access to the document?

**Comment by SteffanThorn** [comment]
@surbhiaroraa my bad, done.

**Comment by oyealmond** [comment]
This is great! I added an intro suggestion to give this text more of a Giveth_ish_ voice. Please check it out. 
@SteffanThorn @surbhiaroraa @ahmadabugosh @danelsuga 

https://docs.google.com/document/d/1WK9rPuRIKJEzZdP5oOY8j1xUxPeYNilAE825uAeiAI4/edit

**Comment by ahmadabugosh** [comment]
hey @oyealmond I like your intro suggestions, and I think we can still use them, but I would also keep the original intros we have as well because it sets the stage for the article and serves as a hook for them to keep reading. I think it we right away just started talking about Giveth without at least an intro sentence or two, it wouldn't perform as well.

**Comment by oyealmond** [comment]
agree @ahmadabugosh! Thanks! I think this is also ready to follow up @surbhiaroraa

**Comment by surbhiaroraa** [comment]
I totally agree with Ahmad on this. Combining both these intros makes for a perfect introduction
@SteffanThorn Once you have finalised this from your end please acknowledge here - we can move it further.

**Comment by oyealmond** [comment]
Hey @surbhiaroraa :)  I changed 2 of the subtitles from this text, to make it different from this other landing page content: https://github.com/Giveth/giveth-planning/issues/1522#issuecomment-1722674173 (Transparency & Access to Global Markets were duplicated) . Tweaked some info to make it more accurate, and added the Giveth links Stee suggested, plus a couple more. 

I left 1 question for @SteffanThorn , [maybe you can check it out whenever you have chance](https://docs.google.com/document/d/1WK9rPuRIKJEzZdP5oOY8j1xUxPeYNilAE825uAeiAI4/edit)?

**Comment by SteffanThorn** [comment]
I added more context into the last point. Felt like we where pushing people in the deep end, needed more easing. 

@oyealmond @danelsuga @ahmadabugosh Please check my added edit for point 5. 

cc @surbhiaroraa

**Comment by ahmadabugosh** [comment]
@SteffanThorn I think this is good to go, can we go ahead and post this? @danelsuga

**Comment by danelsuga** [comment]
I'm good! @oyealmond ?

**Comment by surbhiaroraa** [comment]
@oyealmond Let me know once you have finalised this, I will look at the design aspect and go ahead with publishing.

**Comment by oyealmond** [comment]
This is great! @SteffanThorn
[Ready to post](https://docs.google.com/document/d/1WK9rPuRIKJEzZdP5oOY8j1xUxPeYNilAE825uAeiAI4/edit) @surbhiaroraa

**Comment by surbhiaroraa** [comment]
This is scheduled to be published today. 

cc: @oyealmond We can close this issue?

**Comment by oyealmond** [comment]
Before posting, please post the final text (the link) . So the team can review, and add comments if they had any.  @surbhiaroraa

**Comment by oyealmond** [comment]
https://blog.giveth.io/why-crypto-is-the-future-of-fundraising-for-charity-a1b1be1a2daa
