### ISSUE TITLE
SEO Landing Page: How to get cryptocurrency donations

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1526]
Write landing page content for keyword "how to get cryptocurrency donations"
Brief deadline: September 12

**Comment by surbhiaroraa** [comment]
@WhyldWanderer @oyealmond 
Do we have some content already around this which I can use?
Something around getting your project onboarded on Giveth or any other documentation/educational resource which you might have used in some ambassador program session?

**Comment by oyealmond** [comment]
yes! 

This great [workshop ](https://www.notion.so/giveth/Pimp-my-Giveth-project-2caebb4eef6440cc844cd3d9b85dbcd4) that explain how to get funds for projects. 
Also this video on [Promoting your project on Giveth](https://www.youtube.com/watch?v=S6B9bf0GMpk&list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm&index=9)
Also this on [successful projects ](https://www.youtube.com/watch?v=M12faSm9ao4&list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm&index=11)on Giveth
[Bonus Workshop: Fundraising 101 for Projects](https://www.youtube.com/watch?v=QO6iQgnKvfw&list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm&index=12)
And the [Project Quality Assurance Guide](https://docs.giveth.io/dapps/listedUnlisted/)

Hope these works!

**Comment by surbhiaroraa** [comment]
@SteffanThorn 
Can you take this up please? Let me know if you have any questions

**Comment by SteffanThorn** [comment]
Draft done: https://docs.google.com/document/d/1rRYU88Dcjz2p2tunf2CLd8pw9uzDQCgBjKC7pdDNd7o/edit

I used this article as a template for ideas, without trying to sound too much the same: https://coin-sword.com/how-to-get-cryptocurrency-donations/
Then added extra points mentioned in this issue and included the links shared.

**Comment by surbhiaroraa** [comment]
@SteffanThorn 
I have left bunch of comments. Please check and let me know when you are done.

**Comment by SteffanThorn** [comment]
Edited based on your comments

**Comment by oyealmond** [comment]
Hey team! Made an intro suggestion to align this text with Giveth voice. Please check out my suggestion. 

Also I think this text need some @ahmadabugosh & @danelsuga feedback https://docs.google.com/document/d/1rRYU88Dcjz2p2tunf2CLd8pw9uzDQCgBjKC7pdDNd7o/edit 

Thanks!

**Comment by danelsuga** [comment]
Did some editing.

**Comment by SteffanThorn** [comment]
Thanks @danelsuga and @oyealmond 

One last check on the Intro given by Almond and then I think this is good to go @surbhiaroraa @ahmadabugosh

**Comment by danelsuga** [comment]
This is looking really good!

**Comment by ahmadabugosh** [comment]
@SteffanThorn @danelsuga @oyealmond I left some comments on [this one](https://docs.google.com/document/d/1rRYU88Dcjz2p2tunf2CLd8pw9uzDQCgBjKC7pdDNd7o/edit)

- As an SEO best practice, I would recommend we start using H2 header tags for the different sections of the article (I suggested some changes)
- I think we could keep both intros, with the first one serving as the "hook" into the article, which I think is important for context and the second one that Almond wrote as the about Giveth intro that can come after.

**Comment by danelsuga** [comment]
Oooo clever @ahmadabugosh!

**Comment by oyealmond** [comment]
Like your suggestion @ahmadabugosh thanks! 
I see some comments that still need some work around, but I think this one is almost done! 
cc @surbhiaroraa

**Comment by surbhiaroraa** [comment]
@SteffanThorn 
Combining both the intros - Giveth-y and hook makes for the perfect introduction. Suga also left a comment in the doc. Once its done from your end @SteffanThorn please acknowledge and we can move further.

**Comment by oyealmond** [comment]
Hey @surbhiaroraa, I apply Stee's links suggestion around the links for the text, [and added a couple more links](https://docs.google.com/document/d/1rRYU88Dcjz2p2tunf2CLd8pw9uzDQCgBjKC7pdDNd7o/edit). Also I gave another review on this one fixing some minor things.

**Comment by SteffanThorn** [comment]
@surbhiaroraa Looks good to go!

**Comment by surbhiaroraa** [comment]
@oyealmond Let me know once you have finalised this, I will look at the design aspect and go ahead with publishing.

**Comment by oyealmond** [comment]
This is great @SteffanThorn thank you. 
@surbhiaroraa [is ready to post. ](https://docs.google.com/document/d/1rRYU88Dcjz2p2tunf2CLd8pw9uzDQCgBjKC7pdDNd7o/edit)

**Comment by oyealmond** [comment]
https://blog.giveth.io/how-to-get-cryptocurrency-donations-153b86acbfbd
