### ISSUE TITLE
Giveth <> Planet Partnership 

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1529]
Hi @oyealmond @SnakeGH 
I have put together ideas for partnership with detailed examples and messaging. Please have a look and share your thoughts. 
[Giveth <> Planet Partnership ](https://docs.google.com/document/d/1fr2bwHEgAYLwv5VzTPvdRQtpDB1PUk5G9CK7-EMmNRA/edit?usp=sharing)

@oyealmond Whats the process forward to get this going?

**Comment by oyealmond** [comment]
Hey @surbhiaroraa, there's no document, or ideas included in this issue. 
We always include links, follow up, questions, actual work here for the team to comment, and review .

**Comment by surbhiaroraa** [comment]
Sorry!
https://docs.google.com/document/d/1fr2bwHEgAYLwv5VzTPvdRQtpDB1PUk5G9CK7-EMmNRA/edit?usp=sharing

**Comment by surbhiaroraa** [comment]
@WhyldWanderer 
Almond suggested I should definitely take your inputs and get the partnership ideas review by you. Tagging you here.

**Comment by surbhiaroraa** [comment]
@oyealmond 
What are the next steps to materialise this partnership?

**Comment by surbhiaroraa** [comment]
@oyealmond
Just wanted to check with both of you is there any work from our end/my end in this regard?

**Comment by surbhiaroraa** [comment]
The suggestions for this partnership were discussed and closed long back. Now that we are already working with them, this issue doesn't hold relevance.

**Comment by oyealmond** [comment]
hey @surbhiaroraa ! We should not close issues until the task is completely finished, in this case until this partnership is complete. We use this to follow up in the tasks and work in progress. Sharing the Twitter Space that's happening today: https://twitter.com/JoinOurPlanet/status/1706288356093837348 

Opening this again.

**Comment by surbhiaroraa** [comment]
Oh, Sorry.
Sure - understood. Thanks

**Comment by oyealmond** [comment]
Haven't heard from them. Moving this to icebox.
