### ISSUE TITLE
Giveth <> Shapeshift FOXatar Partnership

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1530]
Hi @oyealmond @WhyldWanderer 
I have put together ideas for partnership. Please have a look and share your thoughts.
[Giveth <> Shapeshift FOXatar Partnership](https://docs.google.com/document/d/1lqSPJ2a6pl0YoS485sd63tbldgXkWAkAoosWMTKuriU/edit?usp=sharing)

**Comment by surbhiaroraa** [comment]
@oyealmond 
What are the next steps to materialise this partnership?

**Comment by WhyldWanderer** [comment]
I left some comments in the document.. I will try to take some time to add more ideas there as well.
We should come up with tasks that people can complete involving Giveth to earn Foxatar traits.

If you havn't had a chance to check out how Foxatars work, you can see it here: https://app.mercle.xyz/shapeshift/events
It will help you get an idea of what we are working with and the potential tasks we can offer.

I also shared some of the ideas in the document with Willy at Shapeshift. Here was his reply:
![image](https://github.com/Giveth/giveth-planning/assets/74267818/4867c770-8927-474f-9e6e-e48b2275b372)

I am hoping to see a clear proposal from hpayne with the different offers that we talked about in the call.

**Comment by surbhiaroraa** [comment]
@WhyldWanderer @oyealmond 
Just wanted to check with both of you is there any work pending from our end/my end in this regard?
Also I would love to set up a call with both of you to discuss partnership ideas, potential partners we should reach out and set up some partnership workflow etc etc. Are you both up for the same?

**Comment by WhyldWanderer** [comment]
> Just wanted to check with both of you is there any work pending from our end/my end in this regard?

Not that I am aware of... we are still waiting on hpayne to draft some documentation that we can share with the Giveth community for advice process. @surbhiaroraa

**Comment by oyealmond** [comment]
Moving this to Icebox.
