### ISSUE TITLE
Newsletter August 2023

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1532]

**Comment by ahmadabugosh** [comment]
Topics

- Gitcoin Grants 18
- Meet the Makers
- ReFi Landing page
- QF survey

**Comment by oyealmond** [comment]
@ahmadabugosh , some more to add here: 

· [QF results](https://forum.giveth.io/t/qf-alpha-round-results/1149) and survey
· 1st batch of 25 OP tokens already distributed to 97 projects: add OP as a donation option on your verified project on Giveth! 
· Giveth's [Euro Trip Medium ](https://blog.giveth.io/giveth-at-ethbarcelona-ethcc-2023-bd4853b07a37)

**Comment by danelsuga** [comment]
Is there a link to review the draft?

**Comment by ahmadabugosh** [comment]
Hey @danelsuga, 

[Here is the draft ](https://docs.google.com/document/d/16sC-4sTzHiIsVOgtPJLJi-yLCiDgFT6Q1JisRnyKRPk/edit) 🙏

**Comment by oyealmond** [comment]
Oh I love it! I made just a quick suggestion @ahmadabugosh

**Comment by danelsuga** [comment]
Reviewed, @ahmadabugosh !

**Comment by ahmadabugosh** [comment]
Hey @SteffanThorn @oyealmond , 

The newsletter is out, here is a suggested post to share:

"
In this month's newsletter

💜 Meet the Giveth Makers is back!
📈  Results of the Giveth QF Alpha Round
🏠 Featured projects @Mymamasformamas & @kelownasallyann
🫶 GIVfriends @lex_DAO
🗣️ Recap of @eth_barcelona & @ethcc

https://news.giveth.io/givnews20 

"

**Comment by oyealmond** [comment]
done @ahmadabugosh! https://twitter.com/Giveth/status/1697359869337092356
