### ISSUE TITLE
R42 + 43 Verified projects Tweet Thread

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1533]
Hi @SteffanThorn  here I am sharing the document with prepared links for the regular tweet thread about newly verified projects. Let's try to keep using the #givethmakers hashtag...

Thanks again for being willing to take this one on. :)

https://docs.google.com/document/d/1SO6iR9KUC-2bhneuoZkt5js16-Jde908XMIIHSrjmlc/edit?usp=sharing

**Comment by SteffanThorn** [comment]
Thread is written. Please review @oyealmond @NikolaCreatrix

**Comment by NikolaCreatrix** [comment]
Looks great to me! Thanks @SteffanThorn

**Comment by oyealmond** [comment]
Scheduled!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1695421346342166588
