### ISSUE TITLE
SEO Landing Page: Nonprofit Fundraising: Amplifying Impact Through Strategic Partnerships

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1538]
Hi @oyealmond 
Wrote an outline for this landing page around the keyword nonprofit fundraising which will also help us pitch potential partnerships with nonprofits. [Link to the document](https://docs.google.com/document/d/1rhfZjbEh9lC_-U_A3tgrs__UNzObHlh3ELnHPJisbVk/edit?usp=sharing)

@danelsuga Can you please use your superpowers here to complete and refine this landing page content? 

 cc: @divine-comedian Just to keep you in the loop

**Comment by danelsuga** [comment]
@WhyldWanderer @NikolaCreatrix do you gals have any particularly great "success" stories on Giveth? From any angle: 
e.g., large amount raised in short time, strongly meaningful project to its community, project with an unexpected hurdle, or anything significant that you've encountered. Many examples would be great. Also, if you have nothing notable, I will do the research by looking through project pages, but that is not the best approach. With your direct contact with projects, you have a better perspective on their achievements (or progress, of course), internally and externally. Thanks!

**Comment by WhyldWanderer** [comment]
- This project had its grant removed from gitcoin and consensys stopped hosting the course half way through due to snctions placed by the US on Iran. Giveth didnt take down their grant and they raised quite a bit of funding:
https://giveth.io/project/free-solidity-development-course-in-farsi

You can find them talking during the community spotlight here:
https://youtu.be/O8b1cPdu_i4?feature=shared&t=2525


I will try to think of more this was just the first one that popped into my head

**Comment by WhyldWanderer** [comment]
I would say that maybe some of the earthquake projects were pretty successful

**Comment by WhyldWanderer** [comment]
I think this is also a great one... https://giveth.io/project/free-the-food-0

it was started by two friends and has raised quite a bit so far and had a big impact on the local community.

Giveth has featured them in many things and I think most of their fundraising success is due to their Giveth project

**Comment by WhyldWanderer** [comment]
I think Bloom Network is also a success story... they have received funding from other sources but have thrived off of donations and grants and raised quite a bit on our platform https://giveth.io/project/bloom-network-0

**Comment by WhyldWanderer** [comment]
Interviewing this project could be advantageous as it is owned by someone who is sort of a celebrity in their market
https://giveth.io/project/instituto-skate-cuida
And they have raised quite a bit on Giveth as well

**Comment by oyealmond** [comment]
Hey @surbhiaroraa :) our awesome @WhyldWanderer added some great use cases for you to follow up. Thanks! :D

**Comment by surbhiaroraa** [comment]
> Interviewing this project could be advantageous as it is owned by someone who is sort of a celebrity in their market https://giveth.io/project/instituto-skate-cuida And they have raised quite a bit on Giveth as well

@NikolaCreatrix Will you be able to interview this project? Will help us multifold - for this SEO landing page sure but also for MTM campaign we discussed about. I am happy to help you with questions for the interview.

**Comment by surbhiaroraa** [comment]
@SteffanThorn 
Please keep a tab on this issue. All these success stories will be helpful for another landing page you are working on.

**Comment by NikolaCreatrix** [comment]
> > Interviewing this project could be advantageous as it is owned by someone who is sort of a celebrity in their market https://giveth.io/project/instituto-skate-cuida And they have raised quite a bit on Giveth as well
> 
> @NikolaCreatrix Will you be able to interview this project? Will help us multifold - for this SEO landing page sure but also for MTM campaign we discussed about. I am happy to help you with questions for the interview.

Oh my... so sorry for the late response @ahmadabugosh, let me try to get in touch with them. I thought @danelsuga would be more into it, but if not I can do it.

**Comment by SteffanThorn** [comment]
@ahmadabugosh @divine-comedian near the top of this article there's an introduction about Giveth. I've included some things like 100% of funds, no platform fees, $3.3Million raised --- are there any other metrics we could use (e.g. donor retention, site visits, etc.)

**Comment by SteffanThorn** [comment]
My main blockers for this article: 
 
•We don't have a clearly defined partnership program, so I'm not sure how to edit the second half of this article. 
@surbhiaroraa informed me herself @SnakeGH and @ahmadabugosh will be planning this. 

•If we are including success stories I'm waiting on interview from the project above @danelsuga and @NikolaCreatrix are talking about -- also we have the same projects on another article, so might need some other success stories to include so they look different.

**Comment by NikolaCreatrix** [comment]
Amazing! I was able to get in touch with Bob, the owner of this project - https://giveth.io/project/instituto-skate-cuida, he is stoked to do the interview, he is just very busy and in Rio time... So how do you want to go about it @danelsuga? He is active on Discord. A group chat?
FYI @surbhiaroraa

**Comment by surbhiaroraa** [comment]
@SteffanThorn 
Thank you your very timely updates. We can completely pause on this for now and take this up a month later after higher priority work of OP is done. 

Anyway we do have 7 SEO articles in the pipeline so we are not blocked here

**Comment by danelsuga** [comment]
I am having a call today with Bob from the above-mentioned project. Because he is busy, and the request was already in the pipeline, I'm going to go ahead and chat with him so as not to miss the opportunity, even though this is on the back burner now. @surbhiaroraa if you're around today (tried to ping you), would be great to get your feedback if there are well structured, marketing-oriented questions I should be asking.

**Comment by surbhiaroraa** [comment]
Objective of these calls/interviews with the project owners: 
- Make a catchy powerful story highlighting their success specifically for the website. This section is very helpful for us to build trust, and credibility in the ecosystem which will eventually help get more donors and projects.
- We will often take snippets out of this interview to make certain social media posts.
- If there is some really amazing success story or something captivating we can use it to write a case study blog as well.


As far as the questions are concerned, below are few suggestions:
1. Tell us briefly about your journey, how, when and why you started? Talk bit about your mission/problem you are solving. What are your most urgent needs? 
2. How much were you raising as part of your fundraising activity  - try to capture their overall fundraising goals?
3. How many people are you likely to impact with ..... $x of this above mentioned funds?
4. How much you raised overall and how much you raised via Giveth? Where does most of your funding come from?
5.  Any other source of funds beside fundraising platform? What do private donations help you to do that your other sources of funding don’t cover?  
6. What would make the greatest difference in helping your organization get better at what it does?
7. How are you utilising the funds raised?
8. How do you keep your supporters and donors updated about your efforts and success and usage of funds. 



We can also use this opportunity to take some feedback as we should always strive to improve.
1. How can Giveth support you better in your fundraising goals?
2. Any feedback? Any challenges?

**Comment by danelsuga** [comment]
Thanks! I should have included [this doc](https://docs.google.com/document/d/1_fAuhxBdo5G58EFY1x92LNW8a-s5_wVZep4AS-KguR8/edit) of Q's as well.

**Comment by oyealmond** [comment]
Updates on this @surbhiaroraa ?
