### ISSUE TITLE
Create Medium Piece about "New" Philanthropy and how Giveth is helping create it

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#154]
Inspired by this awesome piece by @jamespfarrell https://www.notion.so/giveth/Narrative-bf7a0b54007f4c448f337b52ebba4084

**Comment by ForestSoleil** [comment]
Deprioritized for now. Comms circle feels this will be good to schedule around launch of Giveth economy.

**Comment by laurenluz** [comment]
I think we touch on a lot of these points in the GIVbacks blog post: https://medium.com/giveth/what-if-giving-gave-back-using-web3-to-evolve-philanthropy-a8500b7636ce

Closing
