### ISSUE TITLE
Follow Up Gitcoin Tweets. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1540]
Hey @SteffanThorn! 

I was thinking on your suggestion on some after GG18 Giveth Tweets mentioning we're a 24/7 donation platform. Wdyt of drafting some? Maybe like 3, no more. 

And without being confrontative, or even mentioning Gitcoin. To not feel this is a beef or smth (Things are king of intense lately regarding Gitcoin and Shell, etc). 

Let me know your thoughts.

**Comment by SteffanThorn** [comment]
I did more than 3 so you can choose which ones you like. 
I did mention Gitcoin in one because it's about the gitcoin passport situation. 
https://docs.google.com/document/d/1GGdZ23zwjr6uJHjEv_Ur8xM5H93hxMm-bm-9mZi4Q1A/edit?usp=sharing

**Comment by oyealmond** [comment]
great @SteffanThorn thanks! I'll schedule these tomorrow, today I spend most of my day editing videos. But tomorrow I'll schedule these ones. Thanks! :D

**Comment by SteffanThorn** [comment]
You can also choose and ask me to schedule on tasks if it makes things easier.

**Comment by oyealmond** [comment]
scheduled! I scheduled the majority, made some edits (added some CTAs and links from our repurposing content efforts). Check them out @SteffanThorn and let me know your thoughts.  https://docs.google.com/document/d/1GGdZ23zwjr6uJHjEv_Ur8xM5H93hxMm-bm-9mZi4Q1A/edit?usp=sharing .
