### ISSUE TITLE
SEO Landing Page: The Best Crowdfunding Platforms for Nonprofits in 2023

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1541]
Link to the document: [Here](https://docs.google.com/document/d/1R4IHyNP1dsr5TcNsMWc8ScZKk50o_SIsLND2a5eCJxM/edit?usp=sharing)

### Brief for the writeup
**Introduction:** We want to create a comprehensive landing page that highlights the best crowdfunding platforms tailored specifically for nonprofits in 2023. The purpose of this content is to guide nonprofits in choosing the right platform to amplify their fundraising efforts. The tone should be informative, engaging, and targeted towards nonprofit organizations.

**Content Structure:**
_Giveth: Revolutionizing Nonprofit Fundraising_
_Brief Description about Giveth:_ Provide a concise yet compelling overview of Giveth. Highlight its unique features and its mission in empowering nonprofits.
_Benefits of Giveth for Nonprofits:_ Emphasize key benefits such as being completely free to use, no platform fees, and other noteworthy advantages.
_What Makes Giveth Special:_ Elaborate on the distinctive aspects that set Giveth apart from other platforms. Focus on its user-friendly interface, transparent approach, and its commitment to making a real impact.

**Exploring Other Crowdfunding Options for Nonprofits** (Below list is just for reference, you can include different platforms as well)
Kickstarter: Describe Kickstarter's suitability for creative projects, including films, music albums, and video games. Mention its fixed fundraising goal model.
Indiegogo: Highlight Indiegogo's flexibility in funding options and provide examples of campaign types that can benefit from it.
GoFundMe: Explain how GoFundMe, while known for personal fundraising, can also be leveraged by nonprofits for specific projects.
Patreon: Discuss Patreon's unique model designed for creators and its ability to generate recurring donations to support ongoing work.
Fundly: Introduce Fundly as a versatile platform with features catering to personal fundraising, business ventures, and nonprofits.

**Pros and Cons:** For each platform mentioned, present a balanced overview of the pros and cons. Highlight key advantages, such as active user communities and ease of use, while also addressing any potential drawbacks such as fees or competitive challenges.

**Conclusion:** Sum up the advantages of choosing the right crowdfunding platform for nonprofits. Reinforce the idea that the right platform can significantly impact a nonprofit's fundraising success. Encourage readers to make an informed choice that aligns with their organization's goals and values.

**Tone and Style:** The tone should be friendly, informative, and empowering. Keep the language accessible and jargon-free, focusing on helping nonprofits make confident decisions.

**SEO Focus:** Ensure that the content includes relevant keywords related to nonprofit fundraising and crowdfunding platforms and fundraising platforms. This will help improve search engine visibility and drive organic traffic to the landing page.

**Call-to-Action:** End the content with a compelling call-to-action inviting nonprofits to explore Giveth and other platforms further and make an informed choice that best serves their fundraising needs.

**References:** Use the provided examples from websites like startupsavant.com and moneycrashers.com as inspiration for the tone, structure, and approach to creating SEO-focused content for Giveth's landing page.

https://startupsavant.com/best-crowdfunding-sites-for-startups (just for example - Ensure the language and tonality of the entire write up is targeted towards nonprofits, not startups as mentioned here. Also choose the crowdfunding/fundraising platforms accordingly)

https://www.moneycrashers.com/best-crowdfunding-sites-personal-needs/ 

@ahmadabugosh Should we feature only crypto/web3 fundraising platforms in this list or make it a mix of traditional and web3?
@SteffanThorn  - Can you please work on this writeup? 

cc: @divine-comedian @oyealmond

**Comment by SteffanThorn** [comment]
Draft complete. The pros, cons part was tricky for some, particularly Fundly -- couldn't find many cons. 

https://docs.google.com/document/d/1guibAqKdJuJEjoRJqvwVy2BRRyMDBZKfDgnNMLc1CcM/edit?usp=sharing

**Comment by oyealmond** [comment]
Thanks @SteffanThorn! Please @surbhiaroraa, follow up on the editing of this landing page :)

**Comment by surbhiaroraa** [comment]
@danelsuga Can you please help with the editing of this one?

**Comment by danelsuga** [comment]
I've started having a look, but I'm not done. I will be back on it later today or probably tomorrow.

**Comment by danelsuga** [comment]
OK! Finished! :D

**Comment by SteffanThorn** [comment]
@danelsuga I've edited based on your suggestions and will be adding your 3 suggested projects soon. 

@surbhiaroraa while discussing this topic in the comments on the doc, I've realized we could do another article that's specifically titled: The Best "Crypto" Donation Platforms for Nonprofits for 2023 to include ONLY crypto donation platforms.

**Comment by surbhiaroraa** [comment]
@SteffanThorn Great suggestion. Lets do that. Can you open an issue and write an article on that please?

**Comment by surbhiaroraa** [comment]
@danelsuga Stee has incorporated your suggestions. Can you please have a look and let me know if this is finalised from your end? Any further changes required on this one?

**Comment by SteffanThorn** [comment]
@oyealmond  I don't think we need to overdo it with this Giveth intro push. 

A generic article like this makes us look fair in assessing us against the competition. 
Also the long-tail keywords of our niche include this as often searched. 

Search the same title on google and you'll see the Giving Block doing something similar.

**Comment by danelsuga** [comment]
I left a few more comments here. I'd also love to hear @surbhiaroraa's thoughts on the intro debate!

**Comment by ahmadabugosh** [comment]
Yeah I agree that we don't need to have a formal Giveth intro, but I do think we could make the articles seem a bit more human and conversational (I left some suggestions on the doc).

**Comment by oyealmond** [comment]
Thanks! I think this is looking great. I think is ready to follow up on the next steps!  @surbhiaroraa.

**Comment by surbhiaroraa** [comment]
@oyealmond Let me know once you have finalised this, I will look at the design aspect and go ahead with publishing.

**Comment by oyealmond** [comment]
@surbhiaroraa [This is ready ](https://docs.google.com/document/d/1guibAqKdJuJEjoRJqvwVy2BRRyMDBZKfDgnNMLc1CcM/edit#heading=h.9p0nvm5coqns). 

Please proceed with publishing and the following steps.

**Comment by surbhiaroraa** [comment]
@rodricastillo9013 Design requirements are added in the [document here ](https://docs.google.com/document/d/1guibAqKdJuJEjoRJqvwVy2BRRyMDBZKfDgnNMLc1CcM/edit#heading=h.9p0nvm5coqns).

**Comment by oyealmond** [comment]
https://blog.giveth.io/the-best-crowdfunding-platforms-for-nonprofits-in-2023-0464ebcfc41b
