### ISSUE TITLE
Learn more about SEO to be more kickass at SEO copywriting

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1542]
Hi @SteffanThorn 
Since you want to learn and develop SEO copywriting skills, I am sharing few resources here for you to learn more about SEO and SEO copywriting. If you have bandwidth please check these out first before you start working on SEO copywriting.

Resources:
1. https://yoast.com/what-is-seo/
2. https://yoast.com/seo-copywriting-checklist/ 
3. https://yoast.com/seo-friendly-blog-post/
4. https://moz.com/beginners-guide-to-seo 
5. https://developers.google.com/search/docs/fundamentals/seo-starter-guide?hl=en&visit_id=638290455436721544-2155543395&rd=1 
6. https://ahrefs.com/blog/seo-tips/

@danelsuga I know you have been doing SEO copywriting so amazingly for long. But just keeping you in the loop here in case you feel like checking out these resources. 

cc: @oyealmond @divine-comedian

**Comment by danelsuga** [comment]
I appreciate that! Thanks, @surbhiaroraa !

**Comment by ahmadabugosh** [comment]
Great list @surbhiaroraa ! I would add this one from ahrefs to it. It's specific to blogging for business but I think it's relevant for us to start thinking about "donations" as "orders" : https://ahrefs.com/academy/blogging-for-business
