### ISSUE TITLE
Youtube Videos and Podcasts to be transcribed to be used for SEO

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1543]
****Youtube Videos (needs transcribing)****

https://www.youtube.com/watch?v=1oS0S1GtcaY&list=PL4Artm1rmCWEVcRkMb8Q9shA8oXf0Ps7H 

_Donor 101 Videos should be converted into mini blog posts_ 
https://www.youtube.com/playlist?list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ 

_Project Owners 101 should be converted into mini blog posts_
https://www.youtube.com/playlist?list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm 

**Giveth Podcast series**
https://www.youtube.com/playlist?list=PL4Artm1rmCWEVcRkMb8Q9shA8oXf0Ps7H 

**Other youtube videos:**
https://www.youtube.com/watch?v=tueMdmNjanI 
https://www.youtube.com/watch?v=bdIumUJZenw 
https://www.youtube.com/watch?v=2eWE667bc3I&t=507s 
https://www.youtube.com/watch?v=1QrlSJRLh-4 
https://www.youtube.com/watch?v=sV0UVkHacR4 
https://www.youtube.com/watch?v=ADSOVkujrI4 
https://www.youtube.com/watch?v=WJ23oQpooG0 
https://www.youtube.com/watch?v=9ZiGlIm2vBs 
https://www.youtube.com/watch?v=WvwjVJ_7mVA 
https://www.youtube.com/watch?v=a15AxFtOaU4 
https://www.youtube.com/watch?v=DBGoX7DON54 
https://www.youtube.com/watch?v=tsiz1p8hWrk 
https://www.youtube.com/watch?v=_fATr5kA4h8 
https://www.youtube.com/watch?v=RB_HrvR9W-U 
https://www.youtube.com/watch?v=4isUvPG5AO0 
https://www.youtube.com/watch?time_continue=1&v=qyd7mvQmn5I&embeds_referring_euri=https%3A%2F%2Fgreenpill.substack.com%2F&feature=emb_logo 

**Audio Podcast** 
https://podcasts.apple.com/ye/podcast/giveths-griff-green-super-charging-public-goods-and/id1512654905?i=1000550338305 

https://zeroknowledge.fm/29-2/ 

https://music.amazon.com/es-ar/podcasts/2edb5112-6a12-4e75-9a82-6c898a3ec089/episodes/2320b334-2a5c-4b6c-a41f-f97b39187f4f/daoists-presents-giveth-io-griff-green-and-lauren-luz-chat-with-eurekajohn 

https://thedefiant.io/giveths-griff-green-super-charging-public-goods-and-charity-with-crypto

https://www.decential.io/podcasts/decent-people-podcast-with-griff-green-of-giveth

https://poddtoppen.se/podcast/792338939/epicenter-learn-about-crypto-blockchain-ethereum-bitcoin-and-distributed-technologies/griff-green-giveth-creating-the-new-economic-model-of-giving

https://saltlending.com/wys-episodes/money-as-a-means-not-an-end/

Hi @oyealmond 
We can use tools like Descript to transcribe and then polish the script to make it SEO optimised. Who do you think has some bandwidtch to take up this task? 

@divine-comedian Just to keep you in the loop.

**Comment by oyealmond** [comment]
Hey @surbhiaroraa, I curated this list w/ the content I believed we should use. 

I like the idea of turning this on blog posts. But with "blog posts" you mean "landing pages"? Or Giveth Medium posts. 
If you mean landing pages would love to hear @ahmadabugosh's thoughts :)
> Donor 101 Videos should be converted into mini blog posts
> https://www.youtube.com/playlist?list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ
> 
> Project Owners 101 should be converted into mini blog posts
> https://www.youtube.com/playlist?list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm

On the interviews content you recommend, I would say will be good to share on social media, but not for transcription. 

- GM! podcast, specially the convo you selected is too abstract. 
- The podcast w Camila Russo, let's share it on social media, but the content of the podcast, I found it redundant. As it is already in the website or documentation . 
- Same with the Zeroknowledge content. The history of Giveth is already [in the documentation. ](https://docs.giveth.io/whatisgiveth/history/)
- With DeCential Media interview, I found it too focused on Griff, not really Giveth. Will be great to share it again on social media. 
- With the Epicenter podcast add Salt I found them too old, the thing with this conversations is that things move forward so fast in the tech space, that some of this interviews already expired. 


Some comments, I found you selected media from Amazon podcasts, iTunes, Youtube, and podcast from integrated websites players. I don't think there's a tool yet able to transcript with AI all of these formats. Cause you will need to either download the audio or the video... I'll do some research, but I don't think there's something like this yet. 

For me it make sense to transcript the Giveth courses, and some of this content , found it valuable to share on social media. 

Let's keep this issue for the next comms call and get feedback from the team on the best way to move forward.

**Comment by surbhiaroraa** [comment]
@oyealmond 
For Donor 101 and Project owners 101, I was referring to blog as its educational and important information and should be available in textual format as well for people to choose what format they prefer - video or text.

**Comment by surbhiaroraa** [comment]
@oyealmond 
Just wanted to check can someone help me out here with transcribing the video content?

**Comment by oyealmond** [comment]
I believe @ahmadabugosh has a paid subscription to Descript. Maybe Ahmad you can help @surbhiaroraa with these texts? 
Maybe we can organize in the next Comms call to define the next steps of how this will turn into a blog. Maybe we can select which videos from the series will be worth to post first. Wdyt @ahmadabugosh?

**Comment by ahmadabugosh** [comment]
Sure I can help with this. Maybe @k3shavgupta also has a tool as well? 

We need to define what the output is we want and maybe start with one video as a test for it.

**Comment by surbhiaroraa** [comment]
@ahmadabugosh 
Thank you. So we can begin with the Project Owners 101. So once you send me the transcribed content, I will make a Project Owners Guide sort of which we plan to use for different marketing activities with the objective of educating and getting more projects on board. Example: I have identified 50 such Facebook communities of Non Profits so I plan to regularly post there and this kind of content will be very helpful to post.

So can you please help with the texts for these videos in this playlist, [Project Owners 101](https://www.youtube.com/playlist?list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm)?

**Comment by ahmadabugosh** [comment]
Hey @surbhiaroraa , 

Youtube has this feature now where you can extract the transcript from the video directly, so you could use that to extract all the text
<img width="917" alt="Screenshot 2023-10-03 at 2 22 26 PM" src="https://github.com/Giveth/giveth-planning/assets/4855928/3bc546e1-70a5-432d-91e2-c6b97e2dbda3">
