### ISSUE TITLE
Can we use 1 page with multiple different page titles? 

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1545]
Hi @ahmadabugosh 
From SEO POV, have been thinking of few things. Not sure of the feasibility. Please clarify if this is something which makes sense and can be done? 
So if you google, 'how to raise funds for charity' you will find a lot of results. 
Few of the top results are [1](https://www.impactguru.com/info/medical-fundraising-mf-g1/?utm_source=google&utm_medium=google-search-ads&utm_campaign=fundraising&utm_content=668796222852&utm_term=ways%20to%20fundraise&device=c&matchtype=p&keyword=ways%20to%20fundraise&adposition=&adgroup=152012437560&model=&location=9062032&network=g&source=google&medium=CMA&gad=1&gclid=Cj0KCQjwl8anBhCFARIsAKbbpyRdDhZr0GGansxhtgFdy_KfJIi7bu282z4sbe-VZx4ZtLjWxXzabqgaArpREALw_wcB), [2](https://www.ketto.org/cause/medical-fundraising?utm_source=external_Ketto&utm_medium=google-search&utm_campaign=S14_4000_SALE_Fundraising_KY_ALL_CLK_IND&utm_term=p_fund%20raiser&utm_content=medical_resp_ad2&utm_placement=KT17_AG_1865_Fundraising_Generic&gclid=Cj0KCQjwl8anBhCFARIsAKbbpySw9ul-Oz4ZnxRvVwX2E4fUMqG06uv3UsVxqI_uptOXiyMDkP3xZdEaAksUEALw_wcB)

Now these pages are not exactly landing pages with content around the topic of ways to raise charity. But it very aptly captures the interest of projects who want to raise funds and they will be likely to register their project.

I want to understand if we can use 1 website page with multiple different page titles? 

cc: @oyealmond @divine-comedian

**Comment by ahmadabugosh** [comment]
hey @surbhiaroraa so if I understand,  there are 2 options for this. 

1) We can create variations of existing landing pages and just change certain aspects of them. For example, we could have 5 different homepages that are duplicated and just change the titles and copy on them, each one would have a different url. The only thing we would need to do is tell Google which one the "real" homepage is (you do this through "canonical links" to avoid Google marking the pages as duplicate content). 

2) The second option is we could target the same keyword across multiple different pages. So we could have 5 pages, all of them targeting the "how to raise funds for charity" phrase, for completely different audiences and goals.

**Comment by surbhiaroraa** [comment]
Okay @ahmadabugosh 
Thank you for explaining this. I will take this task up in 2 weeks.
