### ISSUE TITLE
Zealy Rewards Campaign

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1547]
We could leverage Zealy as a way to incentive people to look at specific content, follow our socials, join our podcast, attend events, etc. 

There are many web3 communities on this app, so it also gives people a chance to explore other communities. And gives us exposure to web3 communities that might not have seen us before. 

I'm not sure what the specific rewards would be, but would like to open up the discussion about this. 

For reference, Kyoto Blockchain has seen huge success with using this app.
Twitter: https://twitter.com/KyotoRefi
Zealy: https://zealy.io/c/kyotoblockchain/invite/iA7arAc0b-ODlKI7KIqPN

Ideas I can think of so far:
•Follow Giveth Twitter
•Follow Giveth Instagram
•Follow Giveth LinkedIn
•Follow Giveth Lens
•Subscribe to Giveth Youtube Channel
•Join Giveth Discord
•Retweet, like, comment our thread on nonprofits to regen economies 
•Retweet, like, comment GivethMakers threads
•Answers Quiz about Giveth GIVbacks
•Answer Quiz about Giveth GIVpower 
•Donate X amount on Giveth 
•Use GIVpower on Giveth
•Use GIVfarm on Giveth 

Please check out what Kyoto is doing, then come back to the list and share your ideas. And @ anyone who is relevant to this topic. (or I can introduce this in one of our comms calls) 

@laurenluz @oyealmond @missgene @danelsuga @NikolaCreatrix @ahmadabugosh @divine-comedian

**Comment by laurenluz** [comment]
this kind of sounds like something that could be used in tandem with our ambassador program. we are also giving rewards for certain milestone actions when ambassadors complete them. maybe we could give GIV bounties for completion of these actions.

we could also consider non-monetary rewards, like creating POAPs or doing some kind of gameification

**Comment by oyealmond** [comment]
Im confused, @SnakeGH introduced us to the Alpha Guilty team. And I see this issue refers to Zealy, which I don't think is the same. You referred to Alpha Guilty @SteffanThorn?
