### ISSUE TITLE
Update documentation to include information about Optimism GIVbacks and GIVpower

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1548]
We should update the documentation to include information about Optimism GIVbacks.

If I donate to a project on Gnosis, Mainnet, Polygon or Celo it gives GIVbacks on Gnosis, but if I donate on Optimism it gives GIVbacks on Optimism.

- [ ] GIVbacks: https://docs.giveth.io/giveconomy/givbacks/

 Maybe we can add it to this section? @franculio?
![image](https://github.com/Giveth/giveth-planning/assets/74267818/f30350f9-892f-4fb4-8e29-0cf146bf598f)

- [ ] GIVpower: https://docs.giveth.io/giveconomy/givpower

I can see a few things that will need small adjustments 
- we should add the new contract addresses on Optimism
- Adjust the text to include Optimism

![image](https://github.com/Giveth/giveth-planning/assets/74267818/408c0536-82e3-4eed-b60d-ed772d07da43)

**Comment by franculio** [comment]
Hey @WhyldWanderer I've drafted this addition for the GIVbacks doc : https://docs.google.com/document/d/1qAXIx9BW4Ioq5wKg1BGHaq7oFXK7TbDZS3uUQx9fBYk/edit?usp=sharing

I went through the GIVpower doc and luckily the only info that needs changing is the one @WhyldWanderer pointed out. Here's the draft for that little part: https://docs.google.com/document/d/1eAEOWsbfRASJNOPfF-GcxeDK1hiLtuaN9MtC4exXpSk/edit?usp=sharing

Could you give a quick review @danelsuga ? It's nothing big

**Comment by danelsuga** [comment]
All good!

**Comment by franculio** [comment]
The info has been updated in docs, closing the issue @oyealmond
