### ISSUE TITLE
Create Wikipedia page for Giveth

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1549]

**Comment by ahmadabugosh** [comment]
Hey team, 

I think we should try to create a Wikipedia page for Giveth. This would be great for SEO because Wikipedia has very high domain authority and would definitely increase our domain ranking and get Giveth more exposure because of how popular Wikipedia is. 

The problem is that it's hard to get a Wikipedia page approved, but it can be done. Mainly if we :

- Mention Giveth on some other page that exists (like the page that talks about [The DAO](the dao wikipedia)) . This can also be done if we mention Griff on that page and then mention he's the founder of Giveth and link it that way. 
- We need to properly source anything we add and it needs to be from reputable sources (even Forbes.com is not good enough,  so we need to maybe get info from books that mention Giveth like the Cryptopians or Out of the Ether etc)
- We also need to make it not seem like a promotional page, instead we should make it educational on what we're doing for the blockchain space. I noticed Wikipedia editors are more likely to approve a page if it has a non-profit or public good focus, which is in our favor, so we should highlight that. 

@danelsuga could this be something you can help out with?

**Comment by danelsuga** [comment]
Sure!

**Comment by oyealmond** [comment]
I love this idea @ahmadabugosh . Will really help with our SEO efforts. Wondering if you will champion this effort? Or we need to design someone to champion it?

**Comment by ahmadabugosh** [comment]
I believe that @danelsuga is championing this

**Comment by oyealmond** [comment]
I really like this idea. @danelsuga do you have the bandwidth to champion this? Or do you prefer to discuss this as a team and figure it out next steps or maybe first, viability? wdyt?

**Comment by danelsuga** [comment]
I can work on this. (I actually have a Wikipedia page myself. :D) But, it's true, I'm not sure it will pass. Giveth as a company is a hard sell. It would indeed have to be strongly based on Griff's reputation and greater significance to Ethereum for example. I do not know if the (wiki-approved) resources exist that point to Griff and then to his own ventures after The DAO hack. I'll be investigating. If anyone has material to contribute, that'd be great. I'll be reading Cryptopians shortly. Maybe @Brodyann7 could support if it's interesting or relevant to you?

**Comment by oyealmond** [comment]
Oh that would be great! let me check how to start @danelsuga @Brodyann7 . Thank you both!

**Comment by danelsuga** [comment]
First draft. It's important not to be too complicated but just to get the approval first.
I am awaiting a couple more resources.
https://docs.google.com/document/d/1z32D07DnHLWno5C4rQkKO5pNCwo4S6Qm_36Gsm0_lcs/edit?usp=sharing

**Comment by ahmadabugosh** [comment]
Thanks @danelsuga , I think it's good but we also need to think about how will it link from other pages on wikipedia too. So for example, can we get Griff listed on [the DAO wikipedia](https://en.wikipedia.org/wiki/The_DAO_(organization)) page and link it there as founder of Giveth (and Giveth as an offshoot of the white hat group)? Or maybe we can think of another way, like we could add a section on public goods to the [blockchain page](https://en.wikipedia.org/wiki/Blockchain) and link it there with other projects?

**Comment by danelsuga** [comment]
@ahmadabugosh  
There are loads of internal Wikipedia links in there including The DAO.

**Comment by danelsuga** [comment]
Oh I see. Got it. Yes.

**Comment by ahmadabugosh** [comment]
@danelsuga yeah exactly, i meant linking the other way (from other wikipedia pages to this Giveth page)

**Comment by oyealmond** [comment]
This is so awesome! Thanks @danelsuga !

**Comment by ahmadabugosh** [comment]
Looks like they deleted it :(
