### ISSUE TITLE
DoinGud - remove from Giveth partner page

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#1550]
I have to sadly report that they are closing their doors this month, so we can go ahead and remove them from our partners page :(

https://giveth.io/partnerships

@MoeNick Im not sure who will take this on, but I know you will, so feel free to change the assignees. :)

**Comment by MoeNick** [comment]
FYI @divine-comedian 
do you want to review our partner page again?

**Comment by divine-comedian** [comment]
This is finished & live on the dapp! 
https://giveth.io/partnerships
