### ISSUE TITLE
Question Posts Brainstorm 6th Sep 

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1551]
The new X algorithm favors discussion. 

We should build up a list of question posts that can get the community talking. 

It could be topics that you've found many discuss within the community that we could bring out onto X. 
Or related topics that are fun and engaging. 

https://docs.google.com/document/d/1SNPtzabSozuzt74hXX32zjysQ8bXbVSXjQ_RcsfQ_B4/edit

@oyealmond @missgene @laurenluz 

I'll also include yous for extra ideas: @danelsuga @NikolaCreatrix @ahmadabugosh @divine-comedian

**Comment by oyealmond** [comment]
Thanks for this effort @SteffanThorn. I like most of the questions! What are you planning to do with this? I don't think we should post them the wat hey are right now...

**Comment by laurenluz** [comment]
I think they are great. I left some comments with a tiny bit of feedback. if I didn't say anything, it means I think it's ok!

**Comment by SteffanThorn** [comment]
We can space them our with the filler posts @oyealmond
