### ISSUE TITLE
SEO Landing Page: The Best "Crypto" Donation Platforms for Nonprofits for 2023

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1553]
This article is for mentioning crypto donation platforms only. 

Any useful resources or suggestions that will help me on my search will be greatly appreciated. 

@ahmadabugosh @danelsuga @oyealmond 

CC @surbhiaroraa

**Comment by ahmadabugosh** [comment]
@SteffanThorn To start, you can look into the ones we have in our [Impact DAO Databse](https://impactdaos.generalmagic.io/)

**Comment by oyealmond** [comment]
The Giving Block
Gitcoin 
Endaoment
RetroPGF
DAO Drops
https://clr.fund/ 

Some that I found @SteffanThorn . 
And then, https://www.cryptoaltruism.org/ is a specialized media that features the "good side of crypto".

**Comment by danelsuga** [comment]
I have provided a lot of these already on the previous landing page. Will bring that info together shortly.

**Comment by SteffanThorn** [comment]
DAO drops website has zero explanation. Please explain it to me like I'm 5

**Comment by SteffanThorn** [comment]
This article has been the hardest for research. 
I've noticed something that I now need to reconsider how I go about this. 

Some crypto donation platform are nonprofit friendly --- ideal for new nonprofits coming into the space. 
Some crypto donation platforms need you to already be in web3, and are actually heavy on helping Impact DAOs or Blockchain for Good projects, rather than non-web3 nonprofits. 

It might be worth splitting this with a new article titled: The Best Crypto Donation Platform for Web3 projects/DAOs

**Comment by oyealmond** [comment]
On DAOdrops @SteffanThorn this Twitter Space in **minute 10:45min** has one of the founders explaining it: https://twitter.com/i/spaces/1RDGlagLkZmJL?s=20 

@SteffanThorn Maybe could be **"The Best Web3 Fundraising initiatives"** 
Could you give us some thoughts on this one? @surbhiaroraa @danelsuga @ahmadabugosh

**Comment by danelsuga** [comment]
For this SEO page, I think earlier I was referring to Mightycause, Tallycoin, Fundition, and a few more (bc crypto). There are quite a few for Bitcoin like Bitgive, Bithope, Bitbond.

**Comment by SteffanThorn** [comment]
Bitgive and bithope look very inactive. 
Unless I'm mistaken.

**Comment by danelsuga** [comment]
Yes, I think you're right.

**Comment by oyealmond** [comment]
I applied @SteffanThorn links, added some more and made a couple of extra fixes. [here](https://docs.google.com/document/d/11Tq6EK0k20nJsfBNQqIIA2gxPg_akDXFk09Oen50yDg/edit)

**Comment by SteffanThorn** [comment]
Looks good. 

For the title, what term do we think would be the best fit? 
RetroPGF, DAOdrops are more like programs (or mechanisms) rather than platforms. 

The Best Crypto Donation Initiatives in 2023
The Best Crypto Fundraising Programs in 2023
The Best Crypto Fundraising Methods in 2023
The Best Crypto Donation Applications in 2023
The Best Ways to Raise Crypto Donation in 2023

@oyealmond @danelsuga @ahmadabugosh @surbhiaroraa

**Comment by danelsuga** [comment]
perhaps the best crypto fundraising **platforms** - for SEO attraction (more standard term)? @ahmadabugosh ?

**Comment by ahmadabugosh** [comment]
Yes, I agree I would make this be "The Best Crypto Donation Platforms for Nonprofits" that keyword is the one we're going after

**Comment by SteffanThorn** [comment]
@surbhiaroraa I think this is good to go. Titles changed to include platform.

**Comment by oyealmond** [comment]
@surbhiaroraa [This is ready! ](https://docs.google.com/document/d/11Tq6EK0k20nJsfBNQqIIA2gxPg_akDXFk09Oen50yDg/edit)
Grat research @SteffanThorn

**Comment by oyealmond** [comment]
https://blog.giveth.io/the-best-crypto-fundraising-platforms-in-2023-cf234227d36a
