### ISSUE TITLE
Meet the Makers Campaign

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1554]
Strategise the entire Meet the Makers event and campaign
Write social media copies, marketing collateral for this campaign
Make a plan for the next month's event. 
See how can we get more donors and projcts through this event.

cc: @oyealmond @NikolaCreatrix @divine-comedian

**Comment by surbhiaroraa** [comment]
This is done.
The entire strategy to improvise the ongoing efforts of this is done. Planned this mont's edition with Nikola. Have drafted the social media copy and there is a separate issue for each month's edition work. So closing this issue.

**Comment by NikolaCreatrix** [comment]
Amazing, @surbhiaroraa thanks for closing this up. The best practice when closing issues is to make sure you share some links to the content produced, in this case, you would link your final MTM campaign proposal. ;)

**Comment by oyealmond** [comment]
thanks @NikolaCreatrix! This is great advice
