### ISSUE TITLE
SEO Landing Page: How can Giveth help you in your fundraising?

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1555]
Made this as a new issue to separate from the KPI article so we can do both a KPI focused articled and this Giveth benefits article. 

Benefits to include: 
•GIVbacks
•GIVpower
•GIVfarm
•GivethMakers
•Quadratic Funding
•Existing web3 community
•Resources to improve funding promotions 

What am I missing? 

@ahmadabugosh @laurenluz @oyealmond @danelsuga @WhyldWanderer 

cc @surbhiaroraa

**Comment by ahmadabugosh** [comment]
@SteffanThorn I would include the points I [mentioned here](https://github.com/Giveth/giveth-planning/issues/1539#issuecomment-1711265679),  and maybe you can add another point about how it benefits donors and keeps them coming back (then you could mention GIVbacks, GIVfarm, GIVstream etc)

**Comment by SteffanThorn** [comment]
Alright I've made the draft. 
I'm not so familiar with the GIVstream @ahmadabugosh  

Correct me if I'm wrong but from what I've heard, when you get GIVbacks you don't get the full percentage back, you get a portions, say 30% and the rest is streamed to you over time -- is this correct?

**Comment by ahmadabugosh** [comment]
I also added comments to the doc

**Comment by SteffanThorn** [comment]
Thanks for your feedback @ahmadabugosh. I've edited based on your suggestions.

**Comment by oyealmond** [comment]
This is great. [This one is ready to post too. ](https://docs.google.com/document/d/1Y2DQ1bksM7w0hdFK0uk6Tr9d7D0zoa4aafPLcc8RkVw/edit) @surbhiaroraa

**Comment by surbhiaroraa** [comment]
Thank you @oyealmond 
@rodricastillo9013 Please refer to the design requirements mentioned at the end of this [document](https://docs.google.com/document/d/1Y2DQ1bksM7w0hdFK0uk6Tr9d7D0zoa4aafPLcc8RkVw/edit)

**Comment by oyealmond** [comment]
https://blog.giveth.io/how-can-giveth-help-you-improve-your-fundraising-efforts-0f624538a315
