### ISSUE TITLE
email to our database Libya & Morocco Giveth relief efforts. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1557]
Hey @ahmadabugosh! 

Could you please help me send[ this email ](https://docs.google.com/document/d/11yFsl0PxQLOdgy1DotgyndlbHD-rSBb1yzvsq)to our entire data base? Is about Giveth effort reliefs. Sorry for the last minute notice, but I'll appreciate if you could send it asap. 

Thank you so much as always.

**Comment by ahmadabugosh** [comment]
[Duplicate issue here](https://github.com/Giveth/giveth-planning/issues/1558)

**Comment by oyealmond** [comment]
oh! I got an error that said that my issue was not publish. I guess it got published! Thanks @ahmadabugosh!
