### ISSUE TITLE
Email relief efforts for Libya and Morocco email. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1558]
Hey @ahmadabugosh! Sorry for the very short notice, 

Could you please send [this email ](https://docs.google.com/document/d/11yFsl0PxQLOdgy1DotgyndlbHD-rSBb1yzvsqA5Zrjo/edit)to our entire database? 

Please do the edits you think are needed. 
Thanks!

**Comment by ahmadabugosh** [comment]
Sent
