### ISSUE TITLE
Write article on Everything You Need to Know - How to Become a Verified Project on Giveth.io 

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#156]
Write article on Everything You Need to Know - How to Become a Verified Project on Giveth.io 

- Verify project and become eligible for real cool stuff coming soon
- Justify why we do it. Making sure they are legit. 
- How to
- Incentive - we are a donor run platform. We care about the donors and want to do some curation for them. 

This article will come out after the token is launched.

**Comment by laurenluz** [comment]
reduanct w #163
