### ISSUE TITLE
Tweet Idea - Partnerships - ETH Barcelona

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1560]
Giveth just received almost 1000$ in donations to the Matching pool from ETH Barcelona...

Remember when they published this? 
https://www.linkedin.com/posts/ethbarcelona_blockchain4good-philanthropy-giveth-activity-7082236671001280512-Xxn7?utm_source=share&utm_medium=member_ios

they chose to donate some of the ticket sales to Giveth and 1 other project on Giveth - ETHKyiv..

@oyealmond @SteffanThorn - This could be good content to post about?

![image](https://github.com/Giveth/giveth-planning/assets/74267818/7e3a3c0e-e580-4f02-a6c3-c876a6842603)

![image](https://github.com/Giveth/giveth-planning/assets/74267818/1a8c00e4-9282-4e93-8b5a-0b28b8ff13a5)

If you need more details... you can contact @patriciayellow on Discord.

ETH Kyiv twitter: https://twitter.com/EthKyiv_
ETH Barcelona twitter: https://twitter.com/eth_barcelona

**Comment by oyealmond** [comment]
Great idea @WhyldWanderer! Thanks! 

https://twitter.com/Giveth/status/1704217344103297416
