### ISSUE TITLE
Promotions for social media (schedule from 25th)

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1561]
@surbhiaroraa to create copies for advertising the October edition. (Twitter, Facebook, IG, IN)

**Comment by NikolaCreatrix** [comment]
Based on previous formats we have created we need updated versions for social media. 
Details:
October 4th, 2023 11:00 am ET / 5pm CET
[RVSP here](https://www.eventbrite.com/e/meet-the-giveth-makers-tickets-717717230557?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&aff=ebdsshcopyurl)

**Comment by surbhiaroraa** [comment]
Hey @NikolaCreatrix,

I have added the social media copy here - [Link](https://docs.google.com/document/d/1W3A9nvBZQQX-bu8-o6uKsdUghSzIeNO-FAC2p6i8q7w/edit?usp=sharing)

Please review and let me know if you need anything else or any changes in this. 

cc: @oyealmond

**Comment by oyealmond** [comment]
Excellent! I'll review and schedule for monday! @NikolaCreatrix @surbhiaroraa

**Comment by NikolaCreatrix** [comment]
Wonderful thank you so much @surbhiaroraa I just commented on the hashtag to correct, otherwise I love the wording you used!

Some helpful links for Google calendar event: https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=Mm9qZmgwZmkyam9tdmJxbTBla2h2bHYxNHJfMjAyMzEwMDRUMTUwMDAwWiBnaXZldGhkb3Rpb0Bt&tmsrc=givethdotio%40gmail.com
Eventbrite RVSP: https://www.eventbrite.com/e/meet-the-giveth-makers-tickets-717716899567?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl
Giveth discord: https://discord.gg/a2pwdH8u
YouTube: maybe we can share this scheduled link? @oyealmond

**Comment by oyealmond** [comment]
here @NikolaCreatrix https://www.youtube.com/watch?v=797cCxRJSqE
