### ISSUE TITLE
Track Giveth's OP contributions and impact metrics 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1563]
@brichis asked to gather all the metrics & results from Giveth's / OP efforts. 
I started in this [doc](https://docs.google.com/document/d/1Hyxq5LJQzcogm7cYMjjtSnUBlaKdosVUns7GO22QwoQ/edit) Brichis shared. 

There's still metrics missing from the devs and GIVeconomy teams. 
Still need that someone from the fundraising team, organize this metrics into the required OP format @SnakeGH (included in the doc) 

cc @laurenluz @GriffGreen @surbhiaroraa

**Comment by SnakeGH** [comment]
Hey @oyealmond let me know what is needed, sorry my brain is still a little unclear of what you are looking for from fundraising team, but I will ensure the right person who did the Giveth RetroPGF round 2 grant provides the needed info in the spot you need them to

**Comment by oyealmond** [comment]
no worries @SnakeGH ! I'm gathering the metrics from this year from our Giveth <> Opt effort.

**Comment by laurenluz** [comment]
I think @GriffGreen will be working on putting together this data & submitting the final application for retroPGF, but he could deinfitely use some help finalizing & fetching the data.

looping in @ahmadabugosh @divine-comedian @RamRamez @CarlosQ96

**Comment by ahmadabugosh** [comment]
If we pull a list of all the projects that put in an OP address, I can look at site data from them from Google Analytics (like visits and donations).

**Comment by oyealmond** [comment]
hey @ahmadabugosh! This is the issue of the Giveth projects with an OP address https://github.com/Giveth/impact-graph/issues/1127#issuecomment-1737991631

**Comment by CarlosQ96** [comment]
https://github.com/Giveth/impact-graph/pull/1146 Leaving the Pr for the backend of the  analytics dashboard.  Need a frontend to take it.
