### ISSUE TITLE
Project Progress Campaign - Featured Update

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1564]
This project recently added a cool update:
Eco Moyo Education Centre - https://giveth.io/project/eco-moyo-education-centre?tab=updates

Let's feature it as a part of the Project Progress Campaign!

They have successfully constructed their new workshop area, featuring two spacious classrooms designed for art, carpentry, and practical skills activities.

There is a link to learn more here: https://www.ecomoyo.com/updates/workshoparea

And Images:
![image](https://github.com/Giveth/giveth-planning/assets/74267818/6c7d1bda-63d1-43e6-91fe-9c8e4b26eae2)
![image](https://github.com/Giveth/giveth-planning/assets/74267818/ddd9cf00-4cd4-4731-93b3-a04e490d6918)
![image](https://github.com/Giveth/giveth-planning/assets/74267818/be3ec6b9-9d55-417d-bb6b-258f197d9ad0)
![image](https://github.com/Giveth/giveth-planning/assets/74267818/72d942b2-be11-44ae-9ad5-c63176a977cd)

@surbhiaroraa Can you decide which platform(s) we will publish this on (twitter, facebook, linkedin, etc), and draft the copy for publication? Thanks!

CC @oyealmond

**Comment by oyealmond** [comment]
oh this is so great @WhyldWanderer ! Thank you! 

@surbhiaroraa could you please write a tweet to spread the word about this project update? We create the copies in google docs so we can review them. Would be great if you can create the copy and then share through here so I can schedule the tweet.

**Comment by surbhiaroraa** [comment]
I believe we should post on all social media channels not just twitter as non profits have more active community on Facebook and Instagram.

I have written copies for all social media channels. Please review this [document](https://docs.google.com/document/d/1yzxe3FU5CHp5LKQdEHKErejjatXq7wmWMu8BaSRe4V8/edit?usp=sharing). Thank you.

**Comment by oyealmond** [comment]
Great! I scheduled 2 posts on Twitter and asked @missgene to schedule on Instagram, and @SteffanThorn to scheduled on LinkedIn. 

Thanks @WhyldWanderer! 💫

**Comment by WhyldWanderer** [comment]
I recieved some messages from the project owner today..
it seems that the workshop was paid for by the Eco Moyo Auction, however our posts make it sound like Giveth donations made it happen
here is the message I got

![image](https://github.com/Giveth/giveth-planning/assets/74267818/218cccff-6b97-4aaa-800e-ca69bc3ff8fb)


Is there any way we can tweak the wording?

**Comment by oyealmond** [comment]
thanks for the heads up @WhyldWanderer! We already tweaked the copies.

**Comment by WhyldWanderer** [comment]
Just checking in on this... Is it complete?

**Comment by oyealmond** [comment]
yes! This one is done. @WhyldWanderer :) 1 more tweet is coming out after the OP QF ends. That's why I didn't closed it.

**Comment by WhyldWanderer** [comment]
https://twitter.com/Giveth/status/1716802249626714472 

Here it is! Closing the issue
