### ISSUE TITLE
Before and After Impact Campaign - 30 uniforms for school children

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1565]
Thanks to donations made on Giveth, this project has been able to reach a milestone. 

This post can be part of our Before and After Impact Campaign to show donors the impact that their donations are making.

https://giveth.io/project/basic-school-supplies?tab=updates

https://youtu.be/Lyn07fdbxpU?si=KxeVmcW0Z1_E6FcC

"We sew a new 30 school uniform for our pupils through the donations we received on the Giveth platform. Our primary school pupils will be wearing a different new school uniform when school resumes on 17th September.

Our goal is to admit 100 vulnerable children to our school when school resumes on 17th September 2023. Your donations will help us to provide basic school supplies and classroom funding like chairs, desks, teaching aids, and computers, etc."

Point of Contact Discord: helpersfoundation#4702

@surbhiaroraa Can you decide which platform(s) we will publish this on (twitter, facebook, linkedin, etc), and draft the copy for publication? Thanks!

CC @oyealmond

**Comment by oyealmond** [comment]
Oh wow! This is so cool indeed! Thanks @WhyldWanderer ! Im really excited to start sharing these updates. 

Same way as the last issue @surbhiaroraa, please draft a copy for twitter on a Google doc so we can review! Thanks!!!

**Comment by surbhiaroraa** [comment]
Please find the copy [here](https://docs.google.com/document/d/17zSEWtWWERxp1zwESHqcjQ9f0zzK51wgQrooSfS9axU/edit?usp=sharing)

**Comment by oyealmond** [comment]
Thanks @surbhiaroraa . [Added some feedback to your draft](https://docs.google.com/document/d/17zSEWtWWERxp1zwESHqcjQ9f0zzK51wgQrooSfS9axU/edit). Would be great if you could provide 2 tweets so we can mention the project at least 2 times. 

I scheduled after the OP QF Round. Thanks!

**Comment by WhyldWanderer** [comment]
Just checking in here.... is this complete?

**Comment by oyealmond** [comment]
yes! This is scheduled! It will come out after the OP QF Round ends. That's why I didn't closed the issue yet :)

**Comment by WhyldWanderer** [comment]
I'm curious as to the progress on this... did it get published?

Only on twitter? Or will this content be featured on other platforms as well?
I think its best if we utilize all of our platforms if we are going to go through the steps of creating the content.

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1720063715754537069

@missgene could you share this as an Ig story please?

**Comment by missgene** [comment]
I added this on our story @oyealmond! I also added it to the Giveth Makers highlight on IG :) Let me know if you saw this!
