### ISSUE TITLE
Posts brainstorm 23 sep

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1566]
I've used a new google sheet format to try and hit different features of Giveth. 

Would give us a more balanced approach for the filler content. 

https://docs.google.com/spreadsheets/d/1fBIa9HYHZ6kZScAq2e-FZXtISldFqrUzVALVctTsft4/edit?usp=sharing

I've left an edit column so I can still see the original post. 

Let me know which posts are good and what you think about the new approach @oyealmond @missgene @laurenluz

**Comment by oyealmond** [comment]
@laurenluz, could you give these a review please?
