### ISSUE TITLE
Support Giveth in Arbitrum Round email 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1567]
Hey @ahmadabugosh ! 

[Could you please help me send this email ](https://docs.google.com/document/d/1uepv_dOtl3qoSBxR7vqYnqxsXydVHno_WX-_ZgTTeK4/edit?usp=sharing)to all our data base? 
Is regarding Giveth participating in Arbitrum's Round on Gitcoin (asking for the community support) .

Thanks!

**Comment by ahmadabugosh** [comment]
Sent!
