### ISSUE TITLE
Newsletter September 2023

### ISSUE THREAD

**Issue by anamarija09** [Giveth/giveth-planning#1568]

**Comment by ahmadabugosh** [comment]
Main points for this month's newsletter:

- Morocco / Libya campaign
- Arbitrum Gitcoin round
- OP Project push (pushing projects to put in their OP address to claim the OP reward)
- Meet the makers
- Planet X Giveth talk
- Onboarding Landing page

Anything else come to mind? @oyealmond @laurenluz @danelsuga @surbhiaroraa @WhyldWanderer ?

**Comment by ahmadabugosh** [comment]
For featured project , @anamarija09 suggested the updates we have on this one: https://giveth.io/project/eco-moyo-education-centre?tab=updates

**Comment by ahmadabugosh** [comment]
Sent: https://news.giveth.io/givnews21

@oyealmond suggested social media post

Check out the latest updates in our newsletter: 

💜 Support us on the @Arbitrum @Gitcoin round
🔴 QF round on @optimismFND 
🌍 Conversation with @JoinOurPlanet 
🫶 Encouraging Impact @banklessDAO 
🙌 Verified projects @heydotxyz @DreamDAO_ @lenstubexyz 

https://news.giveth.io/givnews21
