### ISSUE TITLE
Paid campaign to get verified projects with an OP address. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1569]
As discussed in our today call, we should run a paid campaign on the platform or social media that will give us the most conversions (verified Giveth projects with an OP address) to reach our 640 projects cap. 

Some of the options mentioned in the call: 

- Explore the possibility of Twitter ads. 
- Explore paid banners options: 
https://landing.coingecko.com/advertising/
https://etherscan.io/contactusadvertise
https://optimism.blockscout.com/

@surbhiaroraa can you please lead this effort? Figure out our best platform option, budget, and times. 
My 1st feeling is Twitter will be easier to implement & to target than paid banners. But I will leave the decision in your capable hands.  

@ahmadabugosh is our best ally to support on this matter.

**Comment by ahmadabugosh** [comment]
@surbhiaroraa For both we need to decide the copy, creative (image or video) and targeting. 

1) For Twitter (X), we can record a short vertical video we can use or create a graphic. The targeting would be people that follow OP and public goods funding related accounts. For twitter, it's easy because we can do it on a CPC (cost per click basis).
2) For the website placements, we need to fill their forms and see what their requirments are,  if they have a minimum we need to spend and what options they have for targeting (if we can show our ad just on OP related pages).

**Comment by surbhiaroraa** [comment]
Thank you @oyealmond and @ahmadabugosh 
I put it on discord - putting the update here as well. 
**Update regarding Paid Marketing:**
Have been doing some research for the best options to do paid advertising/marketing. Found some very good marketplaces which have a lot of options. Have sent an enquiry at numerous places to enquire further and need to do more research (Cost benefit analysis, what options will potentially give us more reach and conversions etc etc) before finalising the best options.
Examples of the marketplaces are: https://cointraffic.io/ , https://coinzilla.com/, https://dotaudiences.com/, https://adshares.net/,  https://coinad.media/, etc. and they give options like shown below in a screenshot. So evaluating options provided in different marketplaces.

Alongwith that ofcourse evaluating other things we discussed on the call yesterday like twitter ads, ad on etherscan etc. 

I am wrapping up for the day and I will pick this up on Sunday/Monday (taking an off on the 28th,29th)

**Comment by oyealmond** [comment]
Thanks for your inputs both! @ahmadabugosh @surbhiaroraa! Agree on Twitter we should create a short video about the campaign. Websites, I believe we're un a rush...  Ads in a social media (Twitter) will give us way more results to achieve our goals fast. 

We should start creating right away the creatives for the ads tho. The video script, image, copy... Would be great to take a decision fast asap, as we're already behind on this

**Comment by oyealmond** [comment]
I'll close this issue as it got discarded.
