### ISSUE TITLE
Add to site - "New to Crypto - How to Get Started"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#157]
Based on feedback relayed by @magentaceiba in discord

"I'm continually amazed how #blockchain technology, which offers so much potential utility in terms of creating a frictionless plane for resource (re)distribution, IMO consistently fails the usability test on the front end.
Can anyone but preexisting converts figure this out?"

https://twitter.com/Jeff_Piestrak/status/1374777024397598723

Suggestion to add a link to the landing page and donations page that says something like "New to crypto?" or "How to get started" with a how to about donating with crypto and how to set up a wallet. It could link to a simple one-page within the Giveth domain with some short paragraphs breaking it down, or a Medium article.

**Comment by WhyldWanderer** [comment]
@laurenluz maybe we can also do some how to videos around this subject?

**Comment by laurenluz** [comment]
we have an epic actually.... #161

**Comment by laurenluz** [comment]
this can be an epic within an epic....

**Comment by WhyldWanderer** [comment]
we can have it in both epics!!! so epic!! :P
