### ISSUE TITLE
Social Media posts - invite project owners to participate in the Optimism QF round

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1571]
Create social media posts for QF Optimism about: 

- Invite projects to participate in the round. 

Tagging @laurenluz in case you'll like to add something

**Comment by laurenluz** [comment]
sharing the email that's going out to projects: https://docs.google.com/document/d/1jFUZuNKeSnsgPH_RmOYbOeEKCE8sZz-wBX3Ud44f9sc/edit

we can use this as a baseline for the 1st tweets. I think we should have a 2nd issue for the QF force tweets ;)

**Comment by oyealmond** [comment]
Thanks @laurenluz!  

I already scheduled 3 announcements inviting projects to participate. 
@SteffanThorn, in case you want to draft a couple of more announcements, [here's my drafts](https://docs.google.com/document/d/1JJjUzXBKlYORGpHEtM9Oh9Zr42bjVWvbRUnd1ZWlxwc/edit?usp=sharing)

Remember we only have 1 week to announce this .
Please @SteffanThorn, make a LinkedIn post with this info. 

Thank you so much! 💜
