### ISSUE TITLE
How to market your project on a QF Round? Content creation. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1573]
Create some content for projects to understand how to market and promote during QF Round. 

@laurenluz , could we adapt [this guide to Optimism ](https://www.notion.so/giveth/5320f4c94563418e93e4736d9276cba0?v=0d08a51c7da440278cc5971b9001e8b9&pvs=4 )and share it as a resource?

**Comment by oyealmond** [comment]
Hey @laurenluz @danelsuga, could you review [these tweets please? ](https://docs.google.com/document/d/1oJDYql-VSRs599HUL2u6CEbhvuZr_HoGzbumljBV29M/edit?usp=sharing)

**Comment by danelsuga** [comment]
Got it.

**Comment by oyealmond** [comment]
hey @danelsuga! I'll assumed this are reviewed?

**Comment by danelsuga** [comment]
Apologies. Yes. Thought I'd indicated that somewhere.

**Comment by oyealmond** [comment]
Thanks @danelsuga! :)

**Comment by oyealmond** [comment]
scheduled both! @laurenluz @danelsuga . I'll draft the new thread and share here

**Comment by oyealmond** [comment]
hey @laurenluz! Here's the how to promote your project [draft] for your review (https://docs.google.com/document/d/1inir4dhF1dm6gUITmuf1UTVynBw1JNzoU2HsbPDWlfQ/edit)

**Comment by laurenluz** [comment]
reviewed! good to go! thanks @oyealmond

**Comment by oyealmond** [comment]
thanks @laurenluz! Scheduled.
