### ISSUE TITLE
Promote QF Optimism Round. Invite ppl to donate content . 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1574]
(During the round). 
Create content inviting people to donate and support the projects participating in the Optimism / Giveth QF. 

cc @laurenluz

**Comment by oyealmond** [comment]
Hey @SteffanThorn! 

Maybe you could start drafting some tweets / threads inviting ppl to donate in our next Optimism QF Round? 
Can be general approaches right now, and we can complement whenever we have more info about the round .

**Comment by SteffanThorn** [comment]
So I've made a doc of memes. We can simply quote retweet from the original post explaining the OP QF round, rather than create new content. What do you think?

https://docs.google.com/document/d/15Z_zNPcgjxqC3Q8-b6yMTONCf26XMU9lplXMfE7G4ZY/edit

**Comment by SteffanThorn** [comment]
And here's a doc with tweets

https://docs.google.com/document/d/1j4OrzK6l1eYgBfNAs-A8yAq0AfGw4tXA-NiT3S7NpPA/edit

**Comment by oyealmond** [comment]
Great Thanks @SteffanThorn! I already scheduled a couple . The memes are great. For sure let's use them during the QF Round!

**Comment by laurenluz** [comment]
I made some comments on the memes! some of them don't work imo. Also, in the future, let's post memes in the meme channel on discord.

A long time ago, Ashley Mitch & I had a system where we could only post a meme if it had at least 3 "thumbs ups" on it from community members. that way, we're not posting things that are off base. I think we should set up a system like this again with our crew! you guys can decide the rules, but the point is basically to get approval, and people can also veto memes. then we ensure better quality going out.

I left some comments about the tweets in the social media channel, as I see some already went out.

**Comment by oyealmond** [comment]
hey @laurenluz ! [Can you review these tweets promoting the round please? ](https://docs.google.com/document/d/1s57mds9B8LsIUjsMcuK9H58lHvNUXSiSBpxLdYIxtJw/edit?usp=sharing)

**Comment by laurenluz** [comment]
reviewed & scheduled all from your doc @oyealmond!

@SteffanThorn - do you want to use the content from [these tweets](https://docs.google.com/document/d/1s57mds9B8LsIUjsMcuK9H58lHvNUXSiSBpxLdYIxtJw/edit) and make a few more similar ones? or quote tweets or ones w/ memes? just to fill out the week.

I think we can get creative and go heavy on Optimism QF round content this week

**Comment by oyealmond** [comment]
Also you're very good with the engagement oriented Tweets @SteffanThorn . So maybe you could draft some more around that. [Sample Tweets](https://docs.google.com/document/d/1s57mds9B8LsIUjsMcuK9H58lHvNUXSiSBpxLdYIxtJw/edit)

**Comment by SteffanThorn** [comment]
Here's a doc I made, sorry forgot to put it in earlier : https://docs.google.com/document/d/1-y3uyqJD2Z2c9AEl2npQ_pGl9Y9pxyZpcQp5B-5mWeM/edit?usp=sharing
