### ISSUE TITLE
Invite donors via email

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1576]
Here it comes again, so I took the last one and tweaked and updated it for the current one.
Please any chance this can go out today or tomorrow @ahmadabugosh? Please have a look as well @oyealmond to double check I got all the links right, maybe its too many...
https://docs.google.com/document/d/129eNTl13jw8G2rC2eAffZlgW7dz-gBQkh9XDrgCCtZI/edit?usp=sharing

**Comment by ahmadabugosh** [comment]
Sent
