### ISSUE TITLE
Feedback form to circulate during the event

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1579]
Would love to make sure we try this. Excited to see if we can get any interesting feedback @surbhiaroraa. We can use Typeform or Google forms. Or do you have any other preference?  I'm happy to put it into Typeform I think I have access and if not Ashley does.

At what point during the event do you think it's best to mention and send? I would imagine that more towards the end. Curious to hear your opinion.

**Comment by oyealmond** [comment]
are we still doing this @NikolaCreatrix ?

**Comment by oyealmond** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSeSefEbo5qK0EjF04rHkaiDhkZmgu477pMScyKjpoVO0dJ3BQ/viewform
