### ISSUE TITLE
Message for project's advertisement + presentation info

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1581]
Send to confirmed projects at the start of the sm promotions. They can use the template and invite their communities. Message has two parts:

Message part 1:

"Hi Friend. We have started with the advertisement. 
Please support our GivethMakers event by inviting your community & supporters.

Link to Giveth YouTube scheduled event: https://www.youtube.com/watch?v=797cCxRJSqE

Link to Discord event: https://discord.com/events/679428761438912522/1149011167080095784

Please share in your social media, Discord & Telegram Channels invitations for your community to join. 
You can use this message if you like or create yours, make sure to use the #GivethMakers hashtag.😉

"📣 Calling all Changemakers!

We'll be participating in @Giveth's Meet The #GivethMaker event next Wednesday, Oct 4th at 3 pm UTC on their Discord & Youtube Channels.

Join us, and learn more about our project mission & our future plans!

Links Giveth Youtube (https://www.youtube.com/watch?v=797cCxRJSqE) & Discord (https://discord.com/events/679428761438912522/1149011167080095784)"

attach banner designs from issue #1500 

Message part 2: 

What to prepare for the event? We've got you!
This is the presentation template we prepared for you to make it easier & give you simple guidelines. You will have about 10 10-minute window for your presentation, each project has 3 slides available, please check the template and the instructions and let me know if it works. (add link to the presentation)

**Comment by surbhiaroraa** [comment]
Hi Nikola,
Drafted the message below which you can use when you send the presentation template. It will be better if you send this as an email as well as telegram message or any other channel you prefer. But please send email as well. 

**Preparing for the Meet the Makers Event? We've got you covered!** 

We are eagerly looking forward to your presentations at the upcoming Meet the Makers event. To streamline the process and ensure consistent and impactful delivery, we have prepared a presentation template and set some guidelines to aid in your preparation.

**Presentation Details:**
_Duration:_ You will have a 10-minute window for your presentation.
_Slide Limit:_ Each project is allotted 3 slides.

Check the template here: (Add Link of the presentation template here)

Kindly send in your presentation before 3rd October for us to compile everything together.

**Comment by NikolaCreatrix** [comment]
Thanks Surbi, implemented your comments, and the final template for copies is here: https://docs.google.com/presentation/d/1-8fvfRHRDAsEsdMlXgkH3YSp1PLxvvBEUPEpd85VZh4/edit?usp=sharing 

Sent to projects and the host.
