### ISSUE TITLE
Banner for QF Optimism Round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1583]
This should be similar to this banner.

We will need to:
- have similarly, two sizes for sponsors, big & small and space for about 5-8 sponsors
- have text that says "Quadratic Funding on Optimism"
- have space/text below that says "round starts in < time >" or "round ends in < time >"
- colors/themes of both Giveth & Optimism. I would even be happy if we made it red!
- the banner sized to fit the dApp
- responsive versions for the banner
- banner modified for instagram, Twitter, linkedIn

![image](https://github.com/Giveth/giveth-planning/assets/75490971/9a8d35cb-cd06-474c-84d6-6d6aaa018fe8)

**Comment by rodricastillo9013** [comment]
hey @laurenluz I thought we could do something like this, and distribute the logos in an area like this. 
![image](https://github.com/Giveth/giveth-planning/assets/61791380/3ac823fd-83af-45cf-8d68-69d61e8d671a)
