### ISSUE TITLE
Create typeform to collect Twitter handles for verifiied projects on Giveth

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1585]
We are trying to collaborate with IDriss to integrate [this](https://twitter.com/IDriss_xyz/status/1692567346886455507) - basically people will be able to tip Giveth projects through Twitter.

to make that happen, we need to giveth them a list of:

- Project names
- Project Twitter handles
- Their Optimism recipient address

Ideally we send them info on all our verified projects w/ OP address so they can all partipate in this (as it can extend beyond QF rounds), but we don't have a lot of Twitter handles for a lot of our verified projects.

We shoudl create a simple typeform to collect them, and email this to all our verified projects (and include it also in our "you've been accepted" email.

**Comment by laurenluz** [comment]
@missgene can you help make a super simple typeform for this? this is all your need to put in it:

Title: Get donations to your Giveth project on Twitter/X!

Description: Hey verified project owner! We are planning an integration with IDriss that will allow anyone to donate to your project on Optimism network directly though your Twitter/X account. If you would like to opt-in to this program, please fill out this simple typeform to provide us with your Twitter/X handle.

Questions:

What is your Giveth project URL? (e.g. https://giveth.io/project/Giveth-Matching-Pool-0)

What is your project's Twitter/X handle? (e.g. https://twitter.com/Giveth)

**Comment by missgene** [comment]
Hi @laurenluz! I already sent this via Discord earlier, but I'm going to send it again here!

https://giveth.typeform.com/to/irQ2YO6e

**Comment by laurenluz** [comment]
Hey @miss
