### ISSUE TITLE
Emai to projects letting them know they are in the Optimism QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1586]
We should be sure to include:
- a link to the [notion doc](https://www.notion.so/giveth/5320f4c94563418e93e4736d9276cba0?v=0d08a51c7da440278cc5971b9001e8b9) we made as a resource for projects
- Round dates & times: October 9 - 23 (need to decide the time)
- Matching pool size: likely $25k unless we get updates from @GriffGreen soon
- A link to this typeform asking projects for their Twitter handles: https://github.com/Giveth/giveth-planning/issues/1585
- An invitation to our QF round Twitter space (@oyealmond can you share the link?)

**Comment by laurenluz** [comment]
This is an email that should go out to our *confirmed projects* after they are confirmed to meet the criteria and be accepted into the round!

**Comment by oyealmond** [comment]
ofc! @laurenluz https://twitter.com/i/spaces/1gqxvQvWRkgJB

**Comment by ahmadabugosh** [comment]
First batch has been sent to the first 77 projects

**Comment by oyealmond** [comment]
hey @ahmadabugosh @laurenluz  ! Are we thinking of sending an email to all our data base announcing the Round kick off? If not, should I write something?

**Comment by ahmadabugosh** [comment]
Hey @oyealmond , yes I think we should! If you can start on a draft with the details you think are relevant, I can edit and then send it when the round goes live

**Comment by laurenluz** [comment]
Thank you both!! @oyealmond I'm happy to give it a review as well if it makes sense, keep me in the loop!

**Comment by oyealmond** [comment]
Hey @ahmadabugosh @laurenluz [here's the draft for you to review](https://docs.google.com/document/d/1H1DZl3t8d0nov6AcOI-Vl1QRsRcsB5ClPkb7_Mrflcg/edit?usp=sharing)

**Comment by oyealmond** [comment]
Made a new issue for this @laurenluz @ahmadabugosh https://github.com/Giveth/giveth-planning/issues/1597
