### ISSUE TITLE
Octant Epoch 1 Campaign

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1587]
This Epic is to coordinate Giveth's campaign efforts for Epoch 1 of Octant.

Key dates:
October 19. Deadline to lock GLM on Octant.
October 19- November 2nd (17hrs CEDT). Allocation window.

Here is an overview of the targets, user personas & strategies to reach each of them:

Target: GLM holders staking in Octant.

targeted user-personas:

1. Octant community.
2. GLM community.
3. Epoch 0 voters (They got 1000 GLM to claim on the Octant dapp: https://octant.app/

Strategy per user-persona:

1. Octant community.
1.1 Twitter threads tagging Octant.
1.2 Like & RT their posts.
1.3 Rallying support on their Discord. Invite them to participate on Optimism
1.4 Having Octant & potentially Golem Foundation on the banner on the Optimism QF
1.5 Joining Octants twitter spaces

2. GLM community.
	2.1 Tag them in some of our tweets.
	2.2 RT them. Full transparency is a bit boring: https://twitter.com/GolemFoundation
	2.3 Rallying support in their discord: https://discord.com/invite/2tzyDq9k4A (It’s pretty dead though)
	

3. Epoch 0 voters (They got 1000 GLM to claim on the Octant dapp: https://octant.app/
	3.1 Twitter thread reminding epoch 0 voters to claim their 1000 GLM, to stake & like Giveth.
3.2 Let;s coordinate a strategy to go into [the Epoch zero POAP holders spreadsheet ](https://docs.google.com/spreadsheets/d/1by0AeJ0697Fx0oxChqzePApTkdpULYIBXWBN7AvbKAU/edit#gid=1159257632)DM them to remind them that if they voted they are eligible for 1000 GLM.
3.3 Mailing campaign. Add it to the newsletter, send an email to the audience we sent the email to vote on epoch zero.
3.4 Discord reminders.

**Comment by Cotabe** [comment]
GM @laurenluz @oyealmond @ahmadabugosh 

I drafted these ideas for the epoch1 campaign of Giveth. I would love to know your thoughts.

**Comment by ahmadabugosh** [comment]
Thanks @Cotabe I like the ideas! 

One thing that would help us in marketing is to learn more about how rewards work. Octant mentions on [this thread ](https://twitter.com/OctantApp/status/1688944360291721216) how you can lock and either get rewards yourself or donate them but the mechanism is not super clear (to me at least).

**Comment by Cotabe** [comment]
Hey @ahmadabugosh 

GLM stakers on Octant can decide to get the rewards themselves or donate them (partially or fully) to projects. When they donate rewards projects will get a matching. 

They use this graph to show how the stacking rewards are distributed....
![Octant matching](https://github.com/Giveth/giveth-planning/assets/101358184/07f50cb2-f2f7-4b3b-bb70-9b2e8758a27e)

If less than 50% of GLM is stacked the matching will be larger per dollar donated.

Like Lauren said I would keep it simple.

VERY IMPORTANT NOTE: The rewards are time-weighted. In other words, the longer they stake their GLM the larger the rewards. I suggest starting the Twitter & mailing campaigns ASAP.
