### ISSUE TITLE
Twitter campaign to claim GLM remainder for epoch zero voters before Oct 16th:

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1588]
It would be convenient to launch this tweet this week when there are only the Epoch 0 projects on the Dapp. Less options more chances that Giveth gets on their allocation tab.

I recommend a campaign with 3 tweets (first this week, a last days reminder October 16th, a last day reminder October 18th)

Key ideas:

* Epoch zero voters have 1000 GLM waiting to be claimed here [octant.app](https://t.co/fAPhu1VsKa). (reference https://x.com/Giveth/status/1689315144008966161?s=20)
* If they don't do it by Oct 19th the airdrop will be lost. (Need to confirm this)
* tag [@OctantApp](https://twitter.com/OctantApp) & [@GolemFoundation](https://twitter.com/GolemFoundation)
* Connect your wallet > claim your GLM... since you are already there go to the projects tab & put a heart on your favorite projects (Aham Giveth)
![Octant projects](https://github.com/Giveth/giveth-planning/assets/101358184/2f915adf-98eb-451f-bc18-84a74b66cd8d)

**Comment by Cotabe** [comment]
It would be convenient to launch this tweet this week when there are only the Epoch 0 projects on the Dapp. Less options more chances that Giveth gets on their allocation tab.

Key ideas:
* Epoch zero voters have 1000 GLM waiting to be claimed here [octant.app](https://t.co/fAPhu1VsKa). (reference https://x.com/Giveth/status/1689315144008966161?s=20)
* If they don't do it by Oct 19th the airdrop will be lost. (Need to confirm this)
* tag [@OctantApp](https://twitter.com/OctantApp) & [@GolemFoundation](https://twitter.com/GolemFoundation)
* Connect your wallet > claim your GLM... since you are already there go to the projects tab & put a heart on your favorite projects (Aham Giveth)
![Octant projects](https://github.com/Giveth/giveth-planning/assets/101358184/9377ea25-4d96-4bf3-ab41-e25f04171ce0)

**Comment by Cotabe** [comment]
My schedule suggestion

- [ ]  tweet 1 before Oct 6th
- [ ]  tweet 2. Last days. Oct 16th
- [ ]  tweet 3. Last day. Oct 18th

**Comment by laurenluz** [comment]
@SteffanThorn @oyealmond I think it would be good to set up maybe 1 thread & 1 tweet on this for the next week. can you help to draft?

**Comment by laurenluz** [comment]
I would love to review this before it goes out

**Comment by oyealmond** [comment]
sure @laurenluz check the draft I made [here](https://docs.google.com/document/d/1QLCR8JUX48BCkaPG1yMW4WBglduPhRw-yapjoVC_rl4/edit).

**Comment by Cotabe** [comment]
@oyealmond can you give me access to check it too :)

**Comment by Cotabe** [comment]
VERY IMPORTANT NOTE: 
The rewards are time-weighted. In other words, the longer they stake their GLM the larger the rewards. I suggest starting the Twitter & mailing campaigns ASAP.

**Comment by oyealmond** [comment]
sure! @Cotabe [here](https://docs.google.com/document/d/1QLCR8JUX48BCkaPG1yMW4WBglduPhRw-yapjoVC_rl4/edit?usp=sharing)

tagging @laurenluz so she can review soon too.

**Comment by oyealmond** [comment]
hey @SteffanThorn! Could you help us draft a couple more of tweets encouraging people to lock their GLM? 
You can check out the info in the tweets @laurenluz [drafted here. ](https://docs.google.com/document/d/1QLCR8JUX48BCkaPG1yMW4WBglduPhRw-yapjoVC_rl4/edit?usp=sharing)

**Comment by Cotabe** [comment]
I only suggested to also add: @GolemFoundation

The account is not too active, but even if just one GLM see the tweet thanks to that it could have a large impact & I don't think there is a downside.

**Comment by oyealmond** [comment]
added @Cotabe ! Thanks! @laurenluz @Cotabe

**Comment by SteffanThorn** [comment]
Sorry for the late reply to this issue. 

Just read through octant docs and whatnot to understand what I'm looking at. 

How about we get Giveth Galaxy members who are staking GLM to announce on their account, then we retweet? 

I will also add some Giveth Account content ideas.

**Comment by laurenluz** [comment]
great idea @SteffanThorn - do you want to set that up? maybe maybe a draft message to give to everyone and share it in here... and then we can review & you could share in discord/accross channels?

**Comment by Cotabe** [comment]
@SteffanThorn @laurenluz @oyealmond 

Rotki made this tweet. I think his ask to people that know GLM holders/stakers was nice: https://x.com/LefterisJP/status/1709581129827668245?s=20

The GLM community is scattered & dormant. If we get some OG GLM holders to engage could be huge.

**Comment by SteffanThorn** [comment]
@laurenluz I've made some draft posts for sharing

https://docs.google.com/document/d/18KkzGYj_HR7qHb5FVWLUoW5CWHfjda8mu8wJnedybKs/edit?usp=sharing

Let me know what you think.

**Comment by SteffanThorn** [comment]
Made some content drafts to add to this campaign 

https://docs.google.com/document/d/1Xmcq7iF5jXAyK99SZFbTDp33FDy7adohiAe8iGi7Hqs/edit?usp=sharing

**Comment by laurenluz** [comment]
I just don't know if we can really say you are staking your GLM on a project... you are staking you GLM which makes you entitled to some % of ETH staking rewards.. that you can - during the allocation window - allocation some or all of to a project.

so I'm not sure about those "I staking my GLM on [project]!" drafts... and also don't know what we'd do with these. - Was the idea to send an email out and say like "here are suggested tweets"?

**Comment by laurenluz** [comment]
Check out this... https://twitter.com/gitcoin/status/1714015355998437654

**Comment by laurenluz** [comment]
ok I made & scheduled another draft pre- Oct 19... https://docs.google.com/document/d/1g7bNlKMgAp83Km3v4835eiy-q0Nd62ZDqv1r3XRYTqw/edit

**Comment by oyealmond** [comment]
This is great. I have no comments. Do you want me to schedule @laurenluz? Do you want to take it?

**Comment by laurenluz** [comment]
I already did! :) thanks @oyealmond
