### ISSUE TITLE
Video: How to donate on Giveth tutorial

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#159]

**Comment by laurenluz** [comment]
Script 1st draft ready to review: https://docs.google.com/document/d/12YlnlT8oFJqP5RTifsJvXxdNDgt1HKhIp-PM9XBWan0/edit?usp=sharing

Who wants to take a look? @divine-comedian @WhyldWanderer @Danibelle @ForestSoleil

**Comment by Danibelle** [comment]
Honestly I don't see anything to change! I added a missing word and suggested we revise the image at the end to use the correct Giveth font.

**Comment by laurenluz** [comment]
Woohoo! Thanks for reviewing Dani - I'll make sure that we revise that last image :)

**Comment by laurenluz** [comment]
Hey @markoprljic.... I'm working on a how-to video series for giveth.io. Can you make a quick image for use to use as the final image in the video? 

My idea is just to have something nice/Givethy at the beginning and end while the narrator gives the intro and outro. The beginning one I set as the image you made for the Future of Giving is here article but the ending placeholder right now doesn't have the right font.

Here's the script if you want to have a look: https://docs.google.com/document/d/12YlnlT8oFJqP5RTifsJvXxdNDgt1HKhIp-PM9XBWan0/edit?usp=sharing

**Comment by markoprljic** [comment]
I'd love us to start moving into this design direction ... 
![Image 2021-04-20 at 11 56 00 am](https://user-images.githubusercontent.com/5704285/115376919-6a615d00-a1cf-11eb-8289-62d598ecd5bb.jpg)

Something along that I could create a banner, do you want something specific written on it or just the logo?

**Comment by markoprljic** [comment]
Please @laurenluz create an issue for me just for that and assign me to it. Thanks!
