### ISSUE TITLE
Twitter campaign to support Giveth on the allocation window Oct 19th-Nov 2nd

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1591]
Timeframe: Oct 19th-Nov 2nd

Suggested schedule:

- [x] Allocation window is open tweet. Oct 19th. 
- [ ] Week one with highlights. ~Oct 24th. 
- [ ] Second week with highlights. ~Oct 27th 
- [ ] Last day of the allocation window. Nov 2nd

Target: Octant users with GLM staked on Octant.

Content ideas:

* A step-by-step of how to support.
* An explanation of how Octant & the Golem Foundation are funding public goods.
* How have we used the funds for QF.
* How will we use the funds.
* Some highlights of the allocation window or Giveth stats.
* We should tag Octant & Golem foundation in all the tweets.

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1710233962231021677

**Comment by laurenluz** [comment]
allocation window is open: https://twitter.com/Giveth/status/1715040917365694655

we should use this as a basis for future tweets...

I'll edit the ones Stee created and share the ones I think we should schedule

**Comment by oyealmond** [comment]
Scheduled @SteffanThorn tweets . Thanks @laurenluz!
