### ISSUE TITLE
Emails to support Giveth during allocation window Oct 19-Nov 2

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1592]
Timeframe: Oct 19th-Nov 2nd

Audience: Same that for the claim GLM campaign

Suggested schedule (I suggest only 3 mails because probably most of them will not be holders & not to spam them):

- [ ] Allocation window is open tweet. Oct 19th. 
- [ ] Week one with highlights. ~Oct 24th. 
- [ ] Last day of the allocation window. Nov 2nd

Content ideas:

* A step-by-step of how to support.
* An explanation of how Octant & the Golem Foundation are funding public goods.
* How have we used the funds for QF.
* How will we use the funds.
* Some highlights of the allocation window or Giveth stats.
* We should tag Octant & Golem foundation in all the tweets.

**Comment by laurenluz** [comment]
@oyealmond 1st emai l here: https://docs.google.com/document/d/1jIY4fluR0tSRworKb5R2CQuqg53SQsLjFm-i8NgudeE/edit

I think it could use a 2nd pair of eyes just to review, then we can send out anytime soon. cc @ahmadabugosh

**Comment by oyealmond** [comment]
nice! no comments. Thanks @laurenluz! @ahmadabugosh, for you when you can please!

**Comment by ahmadabugosh** [comment]
Sent, it's a small list (only about a dozen people matched),  and since it's also late in the round, I think one email is enough.
