### ISSUE TITLE
DM Octant stakers & epoch 0 voters

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1593]
Thanks to @ahmadabugosh & @divine-comedian we have this list with the addresses with the Epoch zero poap.

https://docs.google.com/spreadsheets/d/1by0AeJ0697Fx0oxChqzePApTkdpULYIBXWBN7AvbKAU/edit#gid=1159257632

If they voted on the snapshot they are eligible for the 1000 airdrop... We should tell them & share the good news.

* Can we get a list of those who voted on the snapshot to update this spreadsheet?

Suggested tasks:

- [x] Ask the Giveth Galaxy team to go through the spreadsheet & send DM to the people they know with the good news of their airdrop & follow up until they claim.
- [x] Ask the same people for support for Giveth during the allocation window.

**Comment by Cotabe** [comment]
@ahmadabugosh @divine-comedian @laurenluz 

I worked on an updated spreadsheet: https://docs.google.com/spreadsheets/d/1_Nkjh3hCQppaeeS3OV0xGq9eAklAdTZyV3dOBqZK4Gs/edit?usp=sharing

**Comment by Cotabe** [comment]
& here is an analysis of the addresses of whales stacking on the Octant Smart contract 

https://docs.google.com/spreadsheets/d/1dN_z2Ze6P3azxSagIqRHkyMWtUTJ5qbtjKe0Y3uG10c/edit#gid=1699811275

I could only find 6 ENS names (& one is Griff). Probably there won't be much more luck cross-referencing with our data. But we could give it a try. 

They are 41 addresses with over 10K GLM. 31 of them with over 100,000K GLM

**Comment by divine-comedian** [comment]
What's happening with this @Cotabe ?

**Comment by Cotabe** [comment]
Here are the spreadsheets cross-referenced with Giveth database:

Epoch zero voters:
- https://docs.google.com/spreadsheets/d/1-KAvPlmezh5cL1bVDVHBRI1fQEhlpZK9VOsIj_7k--0/edit#gid=1159257632

GLM stackers in Octant Whalers:
- https://docs.google.com/spreadsheets/d/18I1XOGtP_z5MgMQe4DQ7FOCdhA9Vn2RIZFAHSq2-j80/edit#gid=1159257632

**Comment by Cotabe** [comment]
All different spreadsheet & info have been agregated here:

https://docs.google.com/spreadsheets/d/18I1XOGtP_z5MgMQe4DQ7FOCdhA9Vn2RIZFAHSq2-j80/edit#gid=1091155921

I worked with different data sources to know: Who hadn't claimed their GLM yet, Who had claimed but not staked, and who is holding GLM instead of staking.

I already contacted 6 people from the Giveth community that had claimed, but not staked. 4 are staking now. 1 will once he returns to his laptop. 1 has not replied.

Also reached out to 4 people from the Giveth community who voted on Epoch Zero but had not yet claimed their GLM.

@missgene & I had a call. She will enrich the spreadsheet with ENS names & reach out to more people.

We also have the stakers in Octant ready for when the round starts.

**Comment by Cotabe** [comment]
@divine-comedian @laurenluz @GriffGreen I would love to know your thoughts

@missgene & I have a spreadsheet with the addresses & ENS names of those who voted for Giveth with more than 10% of their voting power in Epoch 0. We have started DMing & have helped 10+ claim + stake.

However, there are about 35 people who voted for Giveth for whom we might not have enough information to DM. We could send them an NFT as a token of appreciation for their support in Epoch zero & to remind them to claim before Thursday.

I think there are scams set up in this way. But we could make it in a way that feels less sketchy. Here is a suggestion with almost no design. Not to waste time before getting feedback on the idea.

![NFT to epoch zero supporters](https://github.com/Giveth/giveth-planning/assets/101358184/e0d0d815-26da-44d2-bf86-d5cddc356505)

Feel free to make any edits here: https://www.canva.com/design/DAFxdKbZKvc/9cF75_zx3rXpLXXLVscEww/edit

**Comment by laurenluz** [comment]
how much time would it take to get this up and sent out? and how would they know they have the NFT? only if looking at opensea?

I think at this point... with only really 2 days left until the allocation window starts... the voting power they would get would be super small in epoch 1...

the motivation would be more to let them know about this, get GLM and then they will be set up for all future rounds 🤔 

but it does come down to visibllity. like I personally would not find out about an NFT I was minted today in the next 2 days... I would only stumble upon it sometimes in my infrequest visits to opensea & that hidden/spam section.

**Comment by Cotabe** [comment]
As discussed on the comms call. I shortlisted Giveth supporters in epoch1 that hadn't claimed. With the support of @missgene & @ahmadabugosh we found twitter handles, TG handles & emails. We already did the outreach on social networks to 11 people.

Here a draft for an email to 9 contacts more that haven't claimed & voted for Giveth:
https://docs.google.com/document/d/103PaYvgJi4zhhE065tGTzMb-SehOtZhw5KBJWybNPS8/edit

I'm asking for support to review & send it today or tomorrow morning tops: @oyealmond @ahmadabugosh @laurenluz

**Comment by ahmadabugosh** [comment]
Sent!

**Comment by Cotabe** [comment]
DMs looking for support are in progress... about 30 sent today.

Tomorrow @missgene will continue

**Comment by Cotabe** [comment]
DMs outreach update:

We have the ENS of about 50 people who have staked 10K+ GLM in Octant & 42 that have staked 1K-10K GLM.

@missgene  will start finding their Twitter or TG handles for the outreach.

I also drafted a message & I would love your feedback on it to outreach from Giveth's Twitter account (@laurenluz  @oyealmond @SteffanThorn ) 

An important note: we will most likely only find contact handles for 30 or fewer of the 92 wallers with 1K+ GLM staked.  So I'm also suggesting adding a personal comment on each outreach to the draft for each contact.

DM outreach draft:

https://docs.google.com/document/d/13-UJZXplb1n5vzEyxdre5duqlhYhUNpDH6NUm4IjoiI/edit

**Comment by laurenluz** [comment]
Hey @Cotabe - I made some edits to the draft - looks good!

@missgene has access to the twitter and can support with the outreach.

**Comment by missgene** [comment]
Thanks for editing the draft. I'll start outreach, but unfortunately, we only have few twitter usernames. Is there another way to identify wallet address owners other than using ENS app? ***@***.******@***.***) ***@***.******@***.***)

[Algene C. - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2b35q2)	[2b35q2]

On October 25, 2023 at 22:03 GMT, Giveth/giveth-planning ***@***.***> wrote:

Hey ***@***.***(https://github.com/Cotabe) - I made some edits to the draft - looks good!

***@***.***(https://github.com/missgene) has access to the twitter and can support with the outreach.

**Comment by oyealmond** [comment]
the text looks good @Cotabe! Just watch out with the emojis text that's left: **:star_struck: , :heart_on_fire:** 

Oh, that's a good one @missgene, maybe @ahmadabugosh , @divine-comedian knows a way to identify these ppl Twitter, or social media? @Cotabe

**Comment by divine-comedian** [comment]
@oyealmond  - not sure if it's possible

**Comment by Cotabe** [comment]
@missgene 

Let's start with the ENS that we have & look for them in Twitter, TG & Octant Discord.

**Comment by missgene** [comment]
@Cotabe I have already updated the sheet with the information I found for them (twitter or other social media links) based on their ENS. Unfortunately, the ones we were able to track are the low stakers or those with 1k..

**Comment by Cotabe** [comment]
@laurenluz @oyealmond 

As we are coming to the final hours of Octant. We want to send one last outreach (30% of Octant GLM lockers haven't made any decision yet).

We want, @missgene to send an outreach message from Giveth Twitter account. Can you aprove it or made the necessary adjustments?

https://docs.google.com/document/d/1fmWu2-60G_c4PlgAGipb_bKJvI_wMUq1xf7LeJ2RnZc/edit?usp=sharing

**Comment by laurenluz** [comment]
Hey @Cotabe I edited it quickly... but also... I noticed that we were sending out messages TODAY to people. idk if sending another one as well today is a good idea, it's not great to spam all our contacts.... especially since it's just a select few that would have any influence.

I would recommend being very strategic about who to send this too, i.e.:
- we didn't message them in the last day or two
- we KNOW they have stake in Octant

**Comment by Cotabe** [comment]
Agree

**Comment by missgene** [comment]
Thanks for editing the message @laurenluz! I will only send it to certain people and definitely those that we did not reach out to in the last two days. Hopefully, we can still get a positive response. @Cotabe

**Comment by oyealmond** [comment]
Thanks for the hard work on this! @missgene @Cotabe @laurenluz
