### ISSUE TITLE
IDriss Typeform email & tweet

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1594]
Drafted this content to collect twitter handles for the IDriss integratino: https://docs.google.com/document/d/1l9QGBJBEPAY0HJEymMA53OPi86K1OsfC-T3UA-b-Atc/edit

would be great to send the email out to all our verified projects sometime this week if we could!

**Comment by ahmadabugosh** [comment]
@laurenluz To avoid sending redundant messages, how about I send these to the verified projects that still haven't added their OP address at the end of this week (i.e removing ones where we already send or plan to send the acceptance email)?

**Comment by laurenluz** [comment]
Sure, and if we want to limit it more, we can remove those whose Twitter handles we have already

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1709965874851893737
