### ISSUE TITLE
How can Giveth help nonprofits in fundraising twitter thread

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1595]
I repurposed this from our SEO article #1555 

Used tweethunter to fit it as a thread. 

Let me know what you think @laurenluz @oyealmond @missgene 

I also recommend we explore other ways to repurpose this (e.g. short video, FB post, etc.)

https://docs.google.com/document/d/1V66pd8Y2Jzx9rwlprkSfQecejvjkFdMhwobaOVuCofY/edit?usp=sharing

**Comment by oyealmond** [comment]
this is nice! I edit the thread a little bit, but will def ask @laurenluz to review as there's a lot of GIVeconomy content to check through.

**Comment by oyealmond** [comment]
Make some edits in the doc! Scheduled for tomorrow. Thanks!
