### ISSUE TITLE
#GivingTuesday campaign. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1596]
Hey team, want to bring back to live our #GivingTuesday (Tuesday Nov 28th) Campaign idea. @WhyldWanderer @surbhiaroraa @ahmadabugosh @SteffanThorn  

I was thinking that a low hanging fruit was to make our #GivingTuesday campaign around the new SEO landing pages  https://github.com/Giveth/giveth-planning/issues/1556, sharing them in social media w the  #GivingTuesday #. 

Thinking some are a very intro level around Cryptofundraising, and GivingTuesday targets the traditional nonprofit space would be a good match. It is a great oportunity for this content to be more visible to the target we want to reach. We could post them, and in every social media content add the CTA "make your 1st Crypto donation on @giveth now" 

If you like this idea, the landing pages should be posted, and everything should be ready before Nov 20th (Monday) so we can have a 1 week campaign. 

Wdyt?

**Comment by WhyldWanderer** [comment]
I think thats a great idea! 
Low effort on our part and still takes advantage of our ability to help these orgs raise funds in crypto as well as provides easy onboarding for orgs that arent familiar with crypto.

**Comment by SteffanThorn** [comment]
I think we could combine them with a paid ad strategy on both Facebook and X to increase exposure. 

As you said @oyealmond it's very intro level friendly and FB has a TON of nonprofits -- so I definitely see an importance of focusing on paid ads over there. 

I can join forces with @surbhiaroraa ??and @ahmadabugosh?? to produce these ads and test them on FB.

**Comment by SteffanThorn** [comment]
Could I get some more info on #GivethTuesday? 

So I can provide coherent feedback and ideas.

**Comment by surbhiaroraa** [comment]
@oyealmond The overall idea of Giving Tuesday I love from the start. Its amazing and we should do it. But I am not clear what exactly you mean by SEO landing pages with respect to this campaign. Can you please clarify - I was thinking that a low hanging fruit was to make our #GivingTuesday campaign around the new SEO landing pages https://github.com/Giveth/giveth-planning/issues/1556

Irrespective Giving Tuesday will be very helpful initiative for us. Lets do it. Once you clarify I will start working on it.

**Comment by oyealmond** [comment]
Hey @surbhiaroraa! As talked today in our comms call, the next steps for this will be 
1. @surbhiaroraa post all the SEO in Medium or Giveth website (depending where's the best option) 
2. Coordinate all the designs w @rodricastillo9013 
3. If we want to move forward w the paid campaign, @surbhiaroraa @ahmadabugosh @SteffanThorn plan how our #GivingTuesday campaign will look like. 
4. I will plan the social media posts sharing our SEO content w #GivingTuesday. 

Is there anything else missing? Thanks!

**Comment by surbhiaroraa** [comment]
Thanks @oyealmond 
I am coordinating with @rodricastillo9013 for the designs. He will wrap up designs for 2 SEO pages this week and we can start publishing then. 

As far as the paid campaign is concerned I will discuss this with @ahmadabugosh and @SteffanThorn and update you by Thursday.

**Comment by ahmadabugosh** [comment]
Added some comments. We need to be quick though because Giving Tuesday is next week!

**Comment by rodricastillo9013** [comment]
Today I will have the designs!

**Comment by oyealmond** [comment]
https://blog.giveth.io/giveth-in-givingtuesday-2023-empowering-generosity-with-web3-ef9c263d6e3b

Thanks for your support on getting this done super fast! @rodricastillo9013 @ahmadabugosh @laurenluz

**Comment by SteffanThorn** [comment]
Let's also repurpose this as a thread -- seems to be alright. 
I spaced it to fit. 

And put a CTA for our blog at the end. 

https://docs.google.com/document/d/1qBjK5FQYPv5jMR6wPd0pUwYakIJ0SFxJz8r-EsUfpa0/edit?usp=sharing

**Comment by laurenluz** [comment]
@oyealmond - I edited Stee's thread, but I do see you already made a thread featuring the articles!

**Comment by oyealmond** [comment]
yes! I already made one @laurenluz . But I think bc is a special day we should def schedule both. I will schedule @SteffanThorn later. thanks @laurenluz and @SteffanThorn !!!
