### ISSUE TITLE
OP QF round is LIVE! Donate now / email

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1597]
Made a new issue for you both to review. @ahmadabugosh @laurenluz 

[Please feel free to edit ](https://docs.google.com/document/d/1H1DZl3t8d0nov6AcOI-Vl1QRsRcsB5ClPkb7_Mrflcg/edit?usp=sharing)

**Comment by laurenluz** [comment]
ok @ahmadabugosh - I made some direct edits in the doc! I think this can go out to our user base today after the round starts. I'll DM you when it's time!

**Comment by laurenluz** [comment]
ok! ready to go out!

**Comment by ahmadabugosh** [comment]
Sent!
