### ISSUE TITLE
Shill the Quadratic Force tweets!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1598]
Our quadratic force this round is:

Big donors:
- Octant App
- Public Nouns

Small donors:
- Aragon Project
- Auryn Macmillan
- Charlie Feng

We should make:
- [ ] 1 Tweet thread about all 5
- [ ] 1 tweet about octant
- [ ] 1 tweet about public nouns

These tweets can basically talk a little bit about what they are each doing & link to their site/tag their twitter. Similar to how we did this in the last QF round.

**Comment by oyealmond** [comment]
Hey @laurenluz ! Find the draft of the threads [here](https://docs.google.com/document/d/1DBx3hOV-SOJjFrlTFON40Le6W77GJWMBvJ0HH4cuIo4/edit) . I asked Rodri for Octant, and Public Nouns arts already.

**Comment by laurenluz** [comment]
Finally edited! shared the arts in the Social Media discord chat. There are ready to scheduled @oyealmond!

**Comment by oyealmond** [comment]
thanks @laurenluz! All scheduled w the arts.
