### ISSUE TITLE
Scoping for White label

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-planning#16]
Hey @Danibelle 

I understood correctly the requirements are as per the MVP, [which is defined here](https://www.notion.so/giveth/MVP-Feature-Requirements-7870883572f94a408e6c9e760f6320e4)

White label specific functionality should include:
**1) Additional development estimates:**
- GraphQL server [2 days]
   Add link to organisation to registerWallet
   Add link to the organisation on addProject
   Create organisationById in organisation-resolver
      Secure it

- Front end 
   - update single css object (1 day)
   - separate Gatsby theme (1+? day)
   - Ability to change the logo and add powered by Giveth:

**2) Deployment**
- Run all white labels on same code deployment or separate servers? I think that if we are responsible for management of the code base we might want to run it as a single deployment. We could therefore aim to make each deployment "multi-site" (or Multi label), and there can still be other multi-site deployments.

**3) Whitelist**
**Short term:** Have "verified" campaign managers - once they are trained/authorized can post projects freely

**Longer term:** Longer term it would be good for any user to propose a project then a verified user can approve it for posting.

@Danibelle can you please review this.

Any other requirements should be documented here.

**Comment by Danibelle** [comment]
So it's a bit more than this after review. 

The puzzle pieces and human collaboration graphics have not landed with those we are showing - they want to see a 'green' version..  earth, water, forests, food, sunshine..  

It doesn't have to be 'just for us' - it can be a template that is available to others seeking their own curated project version as well.

**Comment by markoprljic** [comment]
I can try putting together a more generic version.

**Comment by jamespfarrell** [comment]
If we have a design from Marco, we should be able to swap our the stylesheet.

I think the biggest changes will need to be on the GraphQL server backend, but I haven't managed to get into the code to estimate it yet.

GraphQL changes. We need:
1) Only return projects of the Deployed Organisation.

... Probably more

**Comment by Danibelle** [comment]
Project Curation - some variation on a Whitelist or Proposal Review and Approval process is needed.

**Comment by jamespfarrell** [comment]
We can have anyone sign up, and at the point that they try to add a project, we should email the site admin, or message them on telegram / discord or whatever for approval to post projects.
sounds good?

If so, do we need to do that for every project they post, or only once when they post their first project?

**Comment by jamespfarrell** [comment]
[telegram] <danibelle> My instinct is to have "verified" campaign managers for the MVP.. once they are trained/authorized they can post away.
[telegram] <danibelle> Longer term it would be good for any user to propose a project then a verified user can approve it for posting.

**Comment by jamespfarrell** [comment]
**1) Additional development estimates:**
- GraphQL server [2 days]
- Front end update [1 day]
