### ISSUE TITLE
Video: How to make a quality project listing on Giveth to get fundraising. Guide them through project flow.

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#160]

**Comment by Danibelle** [comment]
I'd like to do this one!

**Comment by laurenluz** [comment]
@Danibelle I want to push this one out too along with #159 Do you want to make a script for it? Or did you have specific ideas?

Would be good to create them at the same time so they're consistent with each other. If you don't have the bandwidth, I'm happy to put something together with this too - just lmk

**Comment by markoprljic** [comment]
I'm currently working on refactoring the Create Project flow as you can preview here https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth.io?page-id=4802%3A1792&node-id=5417%3A167&viewport=-4101%2C1783%2C0.6179280281066895&scaling=min-zoom

Do we want to wait with the video production until we have the new UI? 
We haven't discussed this yet in Dev meeting and have no feedback on timeline and priority, as soon as I have I will update you.

**Comment by laurenluz** [comment]
I think yes, it makes a lot more sense to wait until we have the new UI before making a screen record for this one.

I made a separate issue for updating the Create project flow: https://github.com/Giveth/giveth-2/issues/814

Let's make sure that we discuss this in the dev meeting on Wednesday. I can also get some feedback from Comms. Thanks Marko!!
