### ISSUE TITLE
Move the feedback forms from google forms to typeform

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1609]
@surbhiaroraa - Move it to Giveth's official typeform account. 

cc: @oyealmond @WhyldWanderer

**Comment by surbhiaroraa** [comment]
@NikolaCreatrix @WhyldWanderer 
Are we having the next edition of Meet the Makers? If yes - I will complete this task tomorrow. Please let me know.

**Comment by NikolaCreatrix** [comment]
Hey there, no we won't launch any live stream anytime soon.
