### ISSUE TITLE
2nd OPQG X Space. Oct 13th. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1610]
Hey @laurenluz! 

Could you review our Friday [OPQF X Space script](https://docs.google.com/document/d/138DM4EvkwU8v_O3U-RZUJuAVkUvtN695jQAxshH1ZPc/edit?usp=sharing) please?

**Comment by laurenluz** [comment]
done!

**Comment by oyealmond** [comment]
https://twitter.com/i/spaces/1OwxWYjPYapGQ
