### ISSUE TITLE
Social Media content for Optimism Retropgf

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1611]
Hi @oyealmond 

I and @SteffanThorn are collaborating and put some drafts of tweets for the Optimism Retropgf (targeted towards getting donors). Please review and you can schedule them. 

Document - [here](https://docs.google.com/document/d/1o5GyGzdZ6Iel2Wa1QrQ4pwgfoxDuY6FD1ssLfyi9SB8/edit?usp=sharing)

I will add more content on this tomorrow and will update you here.

**Comment by laurenluz** [comment]
Hey @oyealmond I reviewed them and put the final edits at the top. You can use those 5, and maybe add some memes on 3-5

Thanks @surbhiaroraa @SteffanThorn - have a look at the edits I made and make note for future tweets 🙏  lmk if you have any questions

**Comment by oyealmond** [comment]
Thanks @laurenluz! I scheduled them all. Thanks for all the feedback :) Will really encourage @surbhiaroraa to take a look now that she's starting to write content. Thanks!
