### ISSUE TITLE
Send email announcing Polygon QF Round and inviting projects to join. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1614]
Email announcing the Polygon round and inviting projects to join. 
Polygon start onboarding projects in October 31st . 
*Read the copy Polygon puts in theirs* 

I can draft this! Anything I should include @laurenluz? 

cc @ahmadabugosh

**Comment by laurenluz** [comment]
I think we can just keep an eye on what Diana puts together for the Polygon annoucnement email and revamp it :)

**Comment by oyealmond** [comment]
Hey @laurenluz ! [Can you check this draft ](https://docs.google.com/document/d/1657Ovps6gPaynC8C3r_l3TMkM45HtziPRojoBX7jgd4/edit?usp=sharing)before sending to the Polygon team? Thank you so much!

**Comment by oyealmond** [comment]
Hey @ahmadabugosh ! Could you send[ this email ](https://docs.google.com/document/d/1657Ovps6gPaynC8C3r_l3TMkM45HtziPRojoBX7jgd4/edit?usp=sharing)to all our data base please?  

@laurenluz already edited it! :)
