### ISSUE TITLE
Tweet announcing polygon round & inviting projects to join

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1615]

**Comment by laurenluz** [comment]
instagram & linkedin as well

**Comment by oyealmond** [comment]
Hey @laurenluz ! I started [a draft ](https://docs.google.com/document/d/1FLINK4ruPZHLWoo0wnw1tOYkBYsbJzsK16H3eOVZSFw/edit?usp=sharing)but still is very incomplete

**Comment by oyealmond** [comment]
@laurenluz! [Could you review this tweet thread](https://docs.google.com/document/d/1FLINK4ruPZHLWoo0wnw1tOYkBYsbJzsK16H3eOVZSFw/edit?usp=sharing) so we can share w the Polygon team for approval?
