### ISSUE TITLE
Create notion how-to guide for Polygon QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1616]
We should explain to projects how they can access/take charge of their Giveth projects...

and otherwise update the notion for the polygon round

**Comment by laurenluz** [comment]
show them:
- how to sign in (remind them the use the wallet they said was the "owner")
- where to reach out if they have questions or need support
- how to reformat their project description & make it pretty (because theirs will be all default just text)

**Comment by laurenluz** [comment]
Hey @oyealmond! After discussing w/ Polygon team, the approach is a bit different. Projects will need to create their project in Giveth after being accepted into the round.

Our notion doc should:
- explain how to create a project
- tell them they should use the "owner address" to sign in/create the project. and they MUST use the same recipient address as they did in the polygon village form in order to be included in the round.
- We should encourage all projects to then apply to be verified. if they get verified, they will be seen 1st on the project page & donors benefit from GIVbacks.

**Comment by laurenluz** [comment]
If we can have this ready by Nov 6 it will be great!

**Comment by laurenluz** [comment]
I think the round dats might be Nov 27-Dec 4...

And we will need projects to then create their GIveth project before Nov 25... And if they want to be verified, they need to apply by Nov 17

**Comment by oyealmond** [comment]
Hey @laurenluz. So I added the "same address" message and the verification plus in the , [How to create project section. For your review. ](https://www.notion.so/giveth/Create-Verify-Your-Giveth-Project-f10d7e05e903497f81acb2f8f98158dd)

The[ projects eligibility](https://www.notion.so/giveth/Projects-eligibility-98619e2b08564e75809936c7cda631c2) section is incomplete as we're missing some links and further info. 

I[ updated the guide](https://www.notion.so/giveth/5320f4c94563418e93e4736d9276cba0?v=0d08a51c7da440278cc5971b9001e8b9) with Polygon's Round info.
