### ISSUE TITLE
Polygon Round is live. Announcement on social media

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1617]
Tweets, Ig post, LinkedIn Announcing the Round is LIVE! Go an donate. 

@laurenluz

**Comment by oyealmond** [comment]
Hey @laurenluz! 

Please review the announcement Tweet [here](https://docs.google.com/document/d/1na0467K1GDcOlCdkeIFsTJu2YxJW_LEiA6n_-rRMBxg/edit?usp=sharing). Feel free to add comments & feedback

**Comment by laurenluz** [comment]
ready @oyealmond! I made quite a few changes. maybe give it a quick proofread too before we call it done?

**Comment by oyealmond** [comment]
Is great @laurenluz! Thank you!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1746926027647889898
