### ISSUE TITLE
X Spaces w the Polygon team & w/ participating projects. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1618]
Create 3 different Twitter Spaces about the Polygon Round w/ the Polygon team and w/ shilling opportunities. 

@laurenluz

**Comment by laurenluz** [comment]
Since the round is only from Jan 15-24, I think 2 shill spaces is enough... one on like the 16th and one near the end of the round.

Grendel from Polygon is happy to join as well!

**Comment by oyealmond** [comment]
Hey @laurenluz! Sharing the [1st Twitter Space Script ](https://docs.google.com/document/d/1A7yY7i6YS5XZDVNa39q7nw1VUuIp1ni_XDS2PnAO6XU/edit)for your review

**Comment by laurenluz** [comment]
looks good @oyealmond! I think we can share w/ Marco too so he can be prepared.

**Comment by oyealmond** [comment]
Is great @laurenluz! Just a little typo. Thank you so much.

**Comment by oyealmond** [comment]
Perfect Thanks. Already sent.

**Comment by oyealmond** [comment]
Hey @laurenluz! Sharing the [second X Space script. ](https://docs.google.com/document/d/1BHA-vfcguuxsDeZtfo7LJ2OU-hepuj9zJJBBfj0I32A/edit?usp=sharing)for your review.

**Comment by laurenluz** [comment]
reviewd & ready!
