### ISSUE TITLE
Emails to donors polygon round (2 of them, start & end!)

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1619]
Send an email when the round starts inviting donors to donate, and support. 

CC @laurenluz @ahmadabugosh

**Comment by laurenluz** [comment]
We should prep 2 emails:

Round open email - send out Jan 15

One at the start of the round, telling people it is open & time to donate
- Tell them to donate only on Polygon
- Let them know about upcoming shill spaces, especially the first one (but we should link all)

Round close to end email send out Jan 22 or 23
- Tell them time is running out
- Let them know about last shill space.

We could also share the guide

We can copy the emails from #1688

**Comment by oyealmond** [comment]
hey @laurenluz ! Ready the [1st email ](https://docs.google.com/document/d/1G3osYRdAJNkGYe8vA7RSfRXBc02Nf7z8NMFv8tiS8C0/edit?usp=sharing)for your review.

**Comment by oyealmond** [comment]
Thanks for your review @laurenluz . Sharing [email 2](https://docs.google.com/document/d/1TrYx-A7qor4RCZx15aegjRGaIYO5XQ88OdN5oZDUhtQ/edit?usp=sharing)

**Comment by laurenluz** [comment]
all set! thanks @oyealmond

**Comment by laurenluz** [comment]
@ahmadabugosh - can you send this email out to everyone asap? https://docs.google.com/document/d/1G3osYRdAJNkGYe8vA7RSfRXBc02Nf7z8NMFv8tiS8C0/edit

**Comment by ahmadabugosh** [comment]
First email sent

**Comment by ahmadabugosh** [comment]
2nd email sent
