### ISSUE TITLE
Write Copy for xDAI Twitter Thread

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#162]
Mitch to write a thread of tweets around xDAI. One long tweet altogether all the info. Other people can retweet individual tweets from our thread. 

Once complete, Magenta to publish Mitch's tweet thread on twitter.

**Comment by divine-comedian** [comment]
final draft of tweets submitted 5 days ago to @magentaceiba 

https://docs.google.com/document/d/1M6FLZ559clcqsZEFCEQ0OkCI3XaSKd52cT5SpI4K4KI/edit
