### ISSUE TITLE
Social media posts for during the polygon QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1620]
- teach them how to promote their project
- teach them about QF
- talk about polygon & the village initative
- tell people to donate!

**Comment by laurenluz** [comment]
Since this round is shorter than usual, we don't need AS many tweets, but it would be great to explain, at least:
- How to promote your project & why get verified (give projects some resources and encourage them to get verified to take advatage of extra things live GIVbacks & GIVpower)
- Wtf is QF - explain that a small donation can make an impact
- promote notion guide

#1683 was our last rounds' tweets, we can borrow from there.

**Comment by oyealmond** [comment]
Hey @laurenluz! Sharing the [Round Tweets ](https://docs.google.com/document/d/1EEO0LiE5ypXgbqMlM_gUcr6IpwOZMtatEDekHERpdZ4/edit?usp=sharing)for your review. Please add your thoughts and feedback.

**Comment by laurenluz** [comment]
made edits & left a couple of comments just for feedback. ready to go!

**Comment by oyealmond** [comment]
Thanks @laurenluz! Great feedback too. Thanks

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1748405469972947045
https://twitter.com/Giveth/status/1748405476369301566
https://twitter.com/Giveth/status/1748299776574013444
https://twitter.com/Giveth/status/1747575034334310627
https://twitter.com/Giveth/status/1746926027647889898
