### ISSUE TITLE
3rd GIVtalk on OptimismFND QF Round. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1621]
Hey @laurenluz! Sharing the 3rd GIVtalk script + Tweets [for your review](https://docs.google.com/document/d/1rOI-MXBUuCd_UiRWExmou1BUZhgicmooiBYQLU1ZziA/edit) . 

Let me know your comments!

**Comment by laurenluz** [comment]
edited & ready to go! I think maybe having Ahmad makes it too many speakers... but ofc he is welcome still if he wants to go, I just won't push it.

**Comment by oyealmond** [comment]
Thanks @laurenluz! Got it. Already scheduled the tweets.
