### ISSUE TITLE
Last days to donate on the OPQF Round email 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1622]
Hey @ahmadabugosh @laurenluz 

[Drafted this email ](https://docs.google.com/document/d/1D6qkToOrSeEg8UddeBIe4KA83vbR_GMUgmlyZn6qJiI/edit?usp=sharing)to send on the last days of the OP QF Round. 

Though we could send Wed Oct 18th? / or Thu Oct 19th early morning. 

Could you please review and provide feedback?

**Comment by laurenluz** [comment]
reviewed & ready to go out! @ahmadabugosh can you schedule this for Oct 18?

**Comment by oyealmond** [comment]
hey @ahmadabugosh! Tagging you again so we don't forget to send this email tomorrow (Oct 18th) :) 
Thanks!

**Comment by oyealmond** [comment]
Hey @ahmadabugosh! Tagging you here so we don't forget to send [this email tomorrow](https://docs.google.com/document/d/1D6qkToOrSeEg8UddeBIe4KA83vbR_GMUgmlyZn6qJiI/edit). (Oct 18th). Thanks!
