### ISSUE TITLE
Project Progress Campaign - Perfect Villages

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1623]
Another cool update to highlight!
Perfect Villages in Burundi - https://giveth.io/project/creating-the-perfect-villages-in-burundi

They won the Equator Prize - 
The Equator Prize, organized by the Equator Initiative within the [United Nations Development Programme](http://www.undp.org/), is awarded biennially to recognize outstanding community efforts to reduce poverty through the conservation and sustainable use of biodiversity. https://www.equatorinitiative.org/equator-prize/

https://www.equatorinitiative.org/2023/07/06/perfect-village-communities-pvc-burundi/

Let feature this as a part of the Project Progress campaign!

@surbhiaroraa Can you decide which platform(s) we will publish this on (twitter, facebook, linkedin, etc), and draft the copy for publication? Thanks!

**Comment by oyealmond** [comment]
hey @danelsuga , could you review [these tweets threads please? ](https://docs.google.com/document/d/1U7yxRv8kuhuGmH8Ak4dvYKTlpZoU4XiyJoZvWfsxNBw/edit?usp=sharing)

Thanks!

**Comment by danelsuga** [comment]
Ok done!

**Comment by oyealmond** [comment]
thanks @danelsuga! Scheduled

**Comment by WhyldWanderer** [comment]
Aww yeah! 
Here is the tweet link: https://twitter.com/Giveth/status/1718568864009650368
