### ISSUE TITLE
Project Progress Campaign - Mycelia

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1624]
This project recently added a new update:
https://giveth.io/project/mycelia-indigenous-web3-legal-tech

Mycelia was honouring Indigenous Women the 11th of September 2023 at a III Marcha das Mulheres Indígenas ﻿🌿﻿﻿🏹﻿, the third March of Indigenous Women of Brazil which gathered in Brasilia during the last 3 days +7000 women of nearly 300 different ethnic groups on the thematic : "Ecosystem Women in Defense of Biodiversity through Ancestral Roots" .

https://twitter.com/mycelia_uni/status/1703056511386235077?s=20

@surbhiaroraa Can you decide which platform(s) we will publish this on (twitter, facebook, linkedin, etc), and draft the copy for publication? Thanks!

CC @oyealmond

**Comment by oyealmond** [comment]
Hey @danelsuga! Could you review [these tweet threads please](https://docs.google.com/document/d/1Jp5macUtIiMdGnbSi3jApNweo3QqMqFDGKC0jNfKh2g/edit?usp=sharing)? 

Thanks!

**Comment by danelsuga** [comment]
Ok done!

**Comment by oyealmond** [comment]
scheduled! Thanks @danelsuga !

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1717587398479978795
