### ISSUE TITLE
OP Paid ads campaign. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1626]
To run our Twitter ads campaign we need 

1. Get the relevant Twitter accounts to target @GriffGreen 
2. Get[ this OP <> Giveth metrics / information.](https://docs.google.com/document/d/1dkTHAkUybjMBP-DUsxtHYpJcIF15XRN449ZK6PCFsVM/edit) @oyealmond @laurenluz 
3. Create the campaign content (tweets) @laurenluz @oyealmond 

Thanks team! 
This is a priority and we should try to have it as soon as possible.

**Comment by laurenluz** [comment]
@oyealmond massive main retroPGF twitter thread is here:

https://docs.google.com/document/d/13NIh7pI6oLVZ_jU_kyio5JOmMCxrvDbcauDN-W5VNIU/edit

**Comment by oyealmond** [comment]
Uho! Thanks @laurenluz! I see you're still filling some data. In the meantime, @ahmadabugosh and/or @danelsuga can take a look!

**Comment by laurenluz** [comment]
yeah totally! so I think this thread & subsequent tweets can go out starting next week Oct 23... to basically try to get us in front of badgeholders.

But in the next few days.. we could try to keep pushing the OP incentives campaign more if we want? or try to use it perhaps to get some donors to projects in QF in these last days? wdyt @oyealmond @ahmadabugosh ?

**Comment by laurenluz** [comment]
ok 2nd campaign has been sent!

**Comment by oyealmond** [comment]
Third campaign is up since November 7th. @ahmadabugosh is monitoring it right now. Will run until Dec 6th.
