### ISSUE TITLE
Testing notion dashboard for campaign management

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1627]
We are testing notion gardens for campaign management. We are planning to use this for other grants like Gitcoin or RPGF. This will be useful to have a birds eye view, especially for non-technical people.

Here is the dashboard:
https://www.notion.so/giveth/Octant-E1-Garden-fb94a656a82b40b8ba5eb724056fd130

Praise: Pedro for working on this dashboard.

**Comment by Cotabe** [comment]
@laurenluz 

This is the first version of the dashboard to keep all the campaign work organized & easily accessible.  We will test it for Octant & then work on one for Gitcoin. Once we have it I will tag you to add your suggested resources to the dashboard

**Comment by oyealmond** [comment]
Hey @Cotabe! Question , this will be a dashboard for communications? Or is for the fundraising team? I see it has Pedro info on it, so wondering if this is a personal dashboard, or if we (comms) do something w/ it.

**Comment by laurenluz** [comment]
I thought for gitcoin this would be more of a tasklist w/ timelines... showing all the work that needs to be done. I don't quite understand how to use this, maybe it needs to be demo'd
