### ISSUE TITLE
PoWDump donation proposal comms

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1628]
@oyealmond @laurenluz @SteffanThorn 

GM comms team,

First apologies for not communicating this earlier. We have a proposal on CoW Swap gathering support for donating the fees collected from PoWDump to our matching pool. It would be nice to communicate it to our community. There are also a couple of polls based on the replies of the last polls:

1. To see if all proceeds go to donation or if they are split in a way that was suggested in the previous forum post.
2. To see if they are donated to the matching pool or if there are other ideas.

So far there is consensus to donate 100% & donate to the matching pool.

Also the PoWdump devs made this draft to see if we can push it. To also share again about PoWDump & the story about "multilateral collaboration, which led to value creation and some donations towards Giveth projects!"

Do you think we can post something related to this in our own voice sometime next week?

**Comment by oyealmond** [comment]
Hey @Cotabe, yes we can help you, but can you be more clear on what you need from comms? A tweet, do you need information? If you need a social media post, can you provide the information?

**Comment by SteffanThorn** [comment]
@Cotabe could you share related docs/forums about this? 

Would help give me context to create content.

**Comment by Cotabe** [comment]
@oyealmond 

Yes. It would be a tweet.

@SteffanThorn 

Sorry I don't know why I didn't added the links:

1. Current forum post: https://forum.cow.fi/t/cip-draft-powdump-finalisation-donating-powdump-collected-fees/1948
2. PoWDump team draft, what they would like us to share in our own voice: https://docs.google.com/document/d/1e2TF1_A1ipuB2jlKJ0vhfcEEcgeRyVKoCufAC4fwmuA/edit
3. Original post (over a year ago): https://forum.cow.fi/t/grant-proposal-powdump-a-pow-eth-dump-button-using-cross-chain-atomic-swaps/1133/2

**Comment by oyealmond** [comment]
Ready! @Cotabe 

https://twitter.com/Giveth/status/1714389209098727655
