### ISSUE TITLE
Epoch 1 Tweets

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1629]
From Oct 19 - Nov 2

We should write a few tweets to encourage people to vote for us.

These tweets should say:
- How the voting/allocation works
- that 50% goes to our team and 50% to QF matching pool
-  link to the awesome impact that funds from the last epoch did for our verified projects... shill QF/ optimism QF round retrospectively

We should have:
- the allocaiton window is open! here is how you can support us & why you should
- you can change your vote many times (gasslessly!) - vote for us (a couple of these for mid-week
- just before Nov 2 - last day(s) to vote, please support us (and why you should)

@SteffanThorn @oyealmond - idk if eitther of you can take this?

**Comment by SteffanThorn** [comment]
Here's my doc of ideas. One part you'll notice a comment where I'm not sure what link you're referring to. 

https://docs.google.com/document/d/1Dzs0aT2yebSoZgD3NlDJog_ID2bj6vd0tyQnVg_PJ5s/edit?usp=sharing

**Comment by oyealmond** [comment]
Thanks for your support reviewing these @laurenluz! 
Thanks for taking this @SteffanThorn . 
All scheduled.

**Comment by oyealmond** [comment]
Hey @laurenluz! Could you review [these 2 tweets](https://docs.google.com/document/d/1Dzs0aT2yebSoZgD3NlDJog_ID2bj6vd0tyQnVg_PJ5s/edit?usp=sharing) about "last days to support Giveth" please?
