### ISSUE TITLE
Project Verification and TRACE onboarding Blog Post

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#163]
Write article on Everything You Need to Know - How to Become a Verified Project on Giveth.io 
Blocked by the need to determine and confirm the Project Verification process.
Blocked by the GIV Token Economy launch.
Blocked by the launch of GIVbacks and announcement of Verified Projects. 

Forest/Ashley to write. 

- Justify why we do it. Making sure projects are credible.
- How to
- Incentive - we are a donor run platform. We care about the donors and want to do some curation for them.

**Comment by Danibelle** [comment]
I'll add that aligning the problem/solution with one or more Giveth categories/tags is a factor

**Comment by laurenluz** [comment]
As discussed in today's call, let's make this post a combination of
- how to get verified (and make a good project so it gets verified), and
- how to make a project traceable https://github.com/Giveth/giveth-planning/issues/300

**Comment by WhyldWanderer** [comment]
can be augmented from https://github.com/Giveth/giveth-planning/issues/335

**Comment by WhyldWanderer** [comment]
I have created a hackMD document and started to augment this document into a blog post. 

In the governance call yesterday we discussed moving away from TRACE and not promoting its use.
![image](https://user-images.githubusercontent.com/74267818/144116070-5b140c80-b388-41ba-a983-77aa09022bd9.png)

How will that affect this blog post since the idea is to encourage people to make their projects traceable?

**Comment by laurenluz** [comment]
UGH you're right. how far did you get on it? What if just put the project verification details + GIVbacks as the one blog post and then have "verified projects can also get on TRACE" as a single sentence linking to the documentation?

**Comment by WhyldWanderer** [comment]
I honestly think that is the best approach.

We already have documentation about the process that we can link to or direct people too if they want.

This way, the info is there but we're not actively promoting it on our blog.

**Comment by laurenluz** [comment]
ok let's do it that way. I'll put this in the icebox.

**Comment by laurenluz** [comment]
Project verification is covered in our blog post: https://medium.com/giveth/what-if-giving-gave-back-using-web3-to-evolve-philanthropy-a8500b7636ce
