### ISSUE TITLE
Announce ETC integration

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1630]
looks like we will likely go live on Tuesday!!

we'll need:
- [ ] docs
- [ ] a tweet
- [ ] discord annoucement

@oyealmond

**Comment by divine-comedian** [comment]
I don't think we need any docs for this - we didn't do it for other chain launches AFAIK.

The TL;DR for your almond is that we will be adding Ether Classic to our list of donation enabled chains - Users will now be able to donate ETC (Ether Classic Token) and a few other tokens using Giveth 

Projects will be able to add an ETC Address to receive funds from there as well. No GIVbacks will be issued for donations on ETC. 

@MoeNick is the PM for this one and can provide any information missed and can more accurately confirm the release date.

**Comment by oyealmond** [comment]
cool thanks for the info @divine-comedian! 
@MoeNick could you please provide: 
- date of launch 
- which tokens are supported for donations in ETC? 
- ETC supports multisig right? (I researched and saw there are ETC multisigs, but double checking) 

Thanks!

**Comment by oyealmond** [comment]
@laurenluz 1st draft of the announcement [here](https://docs.google.com/document/d/1lCdnqNmDQBdhDckX2Dr2zeZI_uUyvWSAJmx92zwuT1s/edit?usp=sharing)

**Comment by MoeNick** [comment]
We probably do a soft lunch on Tue, but Im not 100% sure due to some blockers we have in the pipeline. in this feature, project owners can add ETC recipient addresses, and users can donate on this network on ETH, WETH and HEBE on ETC. 
I think it will not get too much user engagement on soft lunch, so no need to be concerned. 
I will keep you updated if we succeed in going live on Tue, but I think you can plan it for next week so we have time to test this version on production env for some days. 
btw: if you mean signing in dapp with multisig ? No this feature won't support it but we're close to it in another version.

**Comment by MoeNick** [comment]
For a real launch it would be perfect if we have some projects (say at least 20) add the ETC address so we can create a list or define a campaign in HomePage. It means after soft lunch we reach out to them to add the address on production.

**Comment by divine-comedian** [comment]
> For a real launch it would be perfect if we have some projects (say at least 20) add the ETC address so we can create a list or define a campaign in HomePage. It means after soft lunch we reach out to them to add the address on production. Then we announce.

I don't think that's in the scope of our proposal to do onboarding of projects onto ETC.. 
Just stick to the scope I would strongly suggest

**Comment by MoeNick** [comment]
I mean if there's not any project there receiving funds on ETC, so there's no need to announce! cause nobody can make donations.

**Comment by oyealmond** [comment]
so no announcement @MoeNick @divine-comedian @laurenluz

**Comment by divine-comedian** [comment]
You could make an announcement saying projects can add an ETC address to receive funds and donors can make donations to eligible projects on ETC network (no GIVbacks - right @MoeNick ?)

**Comment by laurenluz** [comment]
they don't get GIVbacks at all? not even on gnosis chain?

I think we should definitely announce it when it goes live and tell projects they can add an ETC address. and we can make it a fun storytelling thing w/ the griff anecdote.

For the docs, we should go through out docs and make sure we mention ETC along w/ the other chains. We say often 5 chains or like... optimism, celo, polygon, etc... We should add mention of ETC, even if we don't make a whole new thing about it.

**Comment by divine-comedian** [comment]
> they don't get GIVbacks at all? not even on gnosis chain?

I can't give you a good answer - since GIVbacks was removed from scope (or will be removed) it wasn't clear on the new agreement. However my thought is to cut scope as much as possible.

Assuming if we have any troubles with reliable $ price feeds it could make GIVbacks more of a headache or even a liability - even if it goes out on GC.

**Comment by oyealmond** [comment]
Ok. @divine-comedian @laurenluz please provide feedback on [this tweet thread announcement. ](https://docs.google.com/document/d/1lCdnqNmDQBdhDckX2Dr2zeZI_uUyvWSAJmx92zwuT1s/edit?usp=sharing)

@franculio, we should add Ethereum Classic Network as a new donation option to projects on Giveth. I'll keep you posted when we go live with this new integration.

**Comment by laurenluz** [comment]
Hey @oyealmond - I edited the thread! I think we can post tomorrow after we confirmation about the HEBE liquidity... I can schedule it after that coordination.

@franculio - this is live already so if you could comb the docs and add "Ethereum Classic" as a chain option wherever we list "Ethereum Mainnet, Gnosis Chain, Celo, Polygon, Optimism..."... and change "raise funds on 5 networks" to "6 networks"... that should be good.

**Comment by oyealmond** [comment]
Great! Thanks @laurenluz!

**Comment by laurenluz** [comment]
ok scheduled for tomorrow! I'll make another issue for franco for the docs
