### ISSUE TITLE
Last days to support Giveth on GG19 Round! 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1638]
Prepare x days left email, share w @ahmadabugosh when ready.

**Comment by oyealmond** [comment]
Hey @ahmadabugosh ! Could you please check [this draft? ](https://docs.google.com/document/d/10fHiZFsz2sG043RkFGkLMG5yfLLOcjYUuhnYWnG8Zuw/edit?usp=sharing) and if is ok, could you send this last days email on Monday please? 

cc @laurenluz

**Comment by oyealmond** [comment]
perfect! thanks @ahmadabugosh ! 💜

**Comment by oyealmond** [comment]
Hey @ahmadabugosh! I had some issues w my email and I couldn't see if this actually went out? Can you confirm?

**Comment by ahmadabugosh** [comment]
@oyealmond this just went out
