### ISSUE TITLE
Announce web3 wallet connect integration + mobile improvements

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1639]
@divine-comedian what are the most important things to mention here?

That you should check out Giveth on mobile... iphone & android... because it's all optimized?

@oyealmond we could make a short tweet or thread about this, it's a great update.

**Comment by laurenluz** [comment]
cc @MoeNick

**Comment by divine-comedian** [comment]
Yeah! 

We've brought back Wallet Connect to the Giveth Dapp, migrating to the latest wallet connect v2 

we also started using wallet connect's web3modal package to allow users to connect from desktop & mobile 
this means users can now browse and do all the giveth things from their favourite mobile browser such as safari or chrome
they can also use their mobile wallet to connect to Giveth on a desktop browser
currently we've limited the mobile  experience for using MetaMask only but we plan to add in more wallets as soon as we can go through making sure they work properly, piece by piece

A fun question would be to ask people what are their preferred mobile wallets that we should work on adding in to use on Giveth

**Comment by oyealmond** [comment]
sure! This is cool. @divine-comedian @laurenluz please review [this thread draft](https://docs.google.com/document/d/1jc1rqD5ia2n0qTHSUrvF3rnrQdMKbtDqipHgGIW6zec/edit?usp=sharing) & provide your feedback.

**Comment by divine-comedian** [comment]
@oyealmond gave a review - made some small changes

**Comment by SteffanThorn** [comment]
Rainbow seems to be a popular one for regens. 
Also recently had a verified project that didn't take part in QF because of not being able to use rainbow from their phone.

**Comment by divine-comedian** [comment]
> (adding a note) Rainbow seems to be a popular one for regens. Also recently had a verified project that didn't take part in QF because of not being able to use rainbow from their phone.

Yeah Rainbow wallet is a big one we see requested but it causes a lot of bugs - so while it is on the list it will take time to make sure it works well with our website

**Comment by oyealmond** [comment]
great! I scheduled for Monday @divine-comedian . If you have any feedback @laurenluz I can still edit the thread.

**Comment by laurenluz** [comment]
https://twitter.com/Giveth/status/1718976568431620492
