### ISSUE TITLE
Share Dev updates on Medium bi-weekly at the end of each sprint. 

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#164]
Share Dev updates publicly in short & sweet Medium article bi-weekly at the end of each sprint. 

- Dev updates tag, post as Medium article. 
- Not on main page of Medium but organized/categorized.  Adds legitimacy. 
- Lauren to start from last week’s sprint. 
- Specially note when we are implementing feedback from the community, from their direct feature requests in filling out the website feedback form. 

**Include:**

- What did we do last sprint?
- What’s the 1 big feature we are prioritizing for next sprint? _Underpromise, overdeliver._

**Comment by laurenluz** [comment]
1st post ready for review:
https://medium.com/giveth/giveth-transparency-dev-update-march-17-31-3f5f201bfbf3

**Comment by laurenluz** [comment]
@Danibelle and @mateodaza approved! And published to medium: https://medium.com/giveth/what-dappened-march-17-31-3f5f201bfbf3

**Comment by Danibelle** [comment]
Loving this and the action on work flow between Dev and Comms - great work @laurenluz !
