### ISSUE TITLE
Onboard at least 10 projects to Solana

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1641]
As part of the grant agreement we need to onboard 10 Solana native projects onto Giveth and we need 10 projects with $1k in donations made on Solana for a total of $10k USD

This should be completed within 2 weeks of launching the Solana integration 

The SF provided a list of projects they would like to see onboarded so this gives us a good place to start:

- [ ] Sig - Validator client https://www.syndica.io/contact
- [ ] Rakurai - New validator with a better sequencer https://rakurai.io/
- [x] Magic Block - Open Source games tools https://www.magicblock.gg/
- [ ] TipLink - smart wallet https://tiplink.io/
- [ ] Cubik - Open Source Funding platform (like Giveth, Gitcoin) https://www.cubik.so/

## ReFi Projects:

- [ ] Sun Nation
- [x] Sunrise Stakes
- [x] EcoToken
- [ ] Coral Tribe
- [ ] Gainforest

## DePIN projects:

- [ ] Hivemapper https://hivemapper.com/explorer
- [ ] SynesisOne https://linktr.ee/synesisone
- [ ] Render
- [ ] Io.net

**Comment by oyealmond** [comment]
Tagging @WhyldWanderer @laurenluz to start conversations on how to do the projects onboarding to Solana

**Comment by divine-comedian** [comment]
We will only need to worry about this once the integration is done - early december likely - but we should keep it on our radar since it is a requirement for the grant

**Comment by WhyldWanderer** [comment]
Sounds good! I think @Danibelle also knows of some Solana native projects that we could onboard...

**Comment by oyealmond** [comment]
Hi! 

I reached out through Giveth Twitter to the projects on your list @divine-comedian. [Here's the messaging and the channels I used to contact the projects](https://docs.google.com/document/d/1ysbWhM8zFun2_rJ2jVCAQNFrAYO_7bYYexUbpIYC2Ks/edit?usp=sharing). I'll let you know if someone answers.

**Comment by oyealmond** [comment]
The projects are taking v long to respond, or rejecting getting onboarded to Giveth. We need to research for more (specially RefI) Solana projects as a next step on this @NikolaCreatrix

**Comment by divine-comedian** [comment]
So far our leads are: 

Sunrise Stakes (already made a project)
EcoToken
Magicblock 

Anyone else? @oyealmond  CoralTribe?

**Comment by oyealmond** [comment]
Coral Tribe is not interested. But, they invited me to present the opportunity in their Solana ReFi community call. I went and presented, and then I wrote the opportunity in the [Telegram group they invited me to. ](https://t.co/qBoIhtAak7). No one responded so far. 🥲

I'll contact through DMs the people from this chat , and share the opportunity in a 1:1 as the next step.

**Comment by oyealmond** [comment]
can we close this issue @divine-comedian ?

**Comment by divine-comedian** [comment]
Yep!
