### ISSUE TITLE
Launch Incentive program for project to add a Solana address

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1642]
As part of the grant we will have $2500 to buy SOL tokens and provide as an incentive for projects to get a solana address 

we will have to check the price of SOL closer to when we are ready to decide how many tokens we can buy and the target # of projects to onboard - probably keep the incentives around $25 USD value per project so ~100 projects

**Comment by oyealmond** [comment]
same dynamic than the 25 $OP? @divine-comedian

**Comment by divine-comedian** [comment]
Yeah same deal
