### ISSUE TITLE
Tweet thread for retroPGF application for the Giveth house

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1643]
Griff suggested we prepare a tweet thread similar to the one I did for Giveth... explaining the Giveth house & it's contributions to optimism.

This should be put out hopefully early next week!

@franculio @oyealmond @SteffanThorn

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1731267545829654793

**Comment by SteffanThorn** [comment]
I'm not sure what Optimism stuff to put in, but I've got the ball rolling with types of posts. 

https://docs.google.com/document/d/1ywQF3fGLf5LC934lRAepEHfQHHLPKC3LWXDX35IcuS8/edit?usp=sharing
