### ISSUE TITLE
ENS small grant support tweet

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#1644]
ENS small grants unexpectedly open yesterday.

Giveth, Giveth Galaxy & Grant Management projects are in there. https://ensgrants.xyz/rounds/31

We should make a tweet calling ENS token holders to vote for Giveth. I think it can be a simple tweet with a call to action, not necessarily a thread.

Key things to know as context (not necessarily for the tweet):

* There are 36 proposals. First place 🥇 gets 5 ETH,  Second place 🥈 gets 3 ETH,   Third place 🥉 gets 2 ETH. Places 4th to 10th get 0.3 ETH.

* $ENS holders can vote, their vote is divided equally between the projects they are supporting.

* Giveth is in 2nd place now.

* It's not much money. But very few people vote on it. So one "whale" is a game changer.

Examples from other projects:

https://x.com/ethdaily/status/1717210696893579682?s=20

https://x.com/Research_Kairos/status/1717278457636548994?s=20

@oyealmond @SteffanThorn @laurenluz

**Comment by oyealmond** [comment]
Hey @SteffanThorn! 

Do you think you can take this issue and create a couple of tweets based on @Cotabe's examples?

**Comment by SteffanThorn** [comment]
So @oyealmond we can make a long-form post like below. With a short video showing the proposal page and scrolling down (about 5-7 seconds) --- Long-form and Videos get boosted on the algo, will need to be manually posted.  



Your vote helps us evolve the donation space 👇

✅ 100% of donation to projects
✅ 0 platform fees
✅ 50-80% $GIV rewards for verified project donations
✅ $2million+ raised on our platform
✅ 5 networks: Ethereum, Gnosis, Optimism, Polygon & Celo
✅ 150K+ for future quadratic funding rounds
✅ Referral program for user rewards

And a vision to turn nonprofits into microeconomies that no longer rely on donations. 

Will you support our cause? 
https://ensgrants.xyz/rounds/31/proposals/777

**Comment by oyealmond** [comment]
Thanks @SteffanThorn! 

I took your thread and added it [here](https://docs.google.com/document/d/1wGAitviNo0ZnpGwjGp87DDHajvk7ultH15lS6LxxQ5s/edit?usp=sharing). @laurenluz @Cotabe Could you please add feedback, so we can post asap? 

Thanks!

**Comment by SteffanThorn** [comment]
For future refereence @oyealmond, long-form posts are not threads. 

They're a unique feature only available to blue check accounts. 

They're boosted more on the alogrithm than threads, but they can't be scheduled.

**Comment by oyealmond** [comment]
oh, thanks for the feedback @SteffanThorn ! Ik long-form. @Cotabe @laurenluz can you review the tweet [here](https://docs.google.com/document/d/1wGAitviNo0ZnpGwjGp87DDHajvk7ultH15lS6LxxQ5s/edit) and we can have it as a long-form , or a thread. Whatever you think is better.

**Comment by laurenluz** [comment]
Content looks good to me @oyealmond ! I'm not famliar with the ENS small grants process, so I just left some comments from what I'm picking up in the last like... 10 min.

I think the long-format post is a good idea... but you'd have to post it directly on Twitter. which you can totally do!

I keep seeing Tweethunter say that long format is the way to go atm... and I see gitcoin & other orgs using it instead of threads... so it's worth trying imo

**Comment by oyealmond** [comment]
great! Thanks for your feedback @SteffanThorn @laurenluz! Let's post it as a long format as Stee was suggesting.

**Comment by oyealmond** [comment]
tweeted. https://twitter.com/Giveth/status/1719019086611357705 

Thanks for the feedback.

**Comment by Cotabe** [comment]
Congrats team. Giveth was first place in ENS Small grant

**Comment by Cotabe** [comment]
Maybe we could thank the supporters

**Comment by oyealmond** [comment]
Nice @Cotabe ! 
Here you go https://twitter.com/Giveth/status/1719446483391365256
