### ISSUE TITLE
Newsletter October 2023

### ISSUE THREAD

**Issue by anamarija09** [Giveth/giveth-planning#1645]

**Comment by oyealmond** [comment]
Some things to add: 

- Giveth OP QF Round, some stats, amount donated, x donors, 125 projects, etc
- Vote for Giveth in Octant's Epoch One! (This closes Nov 2nd, so we should hurry). 
- Learn about Giveth's impact on Optimism Ecosystem on this [tweet thread] & RT, share & like! (https://twitter.com/Giveth/status/1717481976200880400)
[- Wallet Connect V2 on Giveth is now live](https://twitter.com/Giveth/status/1718976568431620492). Users will have a way better mobile 
experience
[- Ethereum Classic is now available on giveth](https://twitter.com/Giveth/status/1717874303557894547)
[- Meet the Giveth Makers event ](https://twitter.com/Giveth/status/1718740663724822643)(is on Nov 1st, Idk if we'll have time to send this before Nov 1st) 

Projects Spotlight 
- project that raised more in the Giveth OP QF Round. 
- Unconference Trusted Seed. 

Something missing @laurenluz ?

**Comment by laurenluz** [comment]
We should encourage projects to add an ETC address

**Comment by ahmadabugosh** [comment]
hey @oyealmond @laurenluz can i get a quick proof read on this? https://docs.google.com/document/d/1GbhUC4as296aAK2VDyz_bgz_Aw0IYyvk9HOb-2o3khs/edit
