### ISSUE TITLE
Repurpose Content for IG. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1648]
Hey Algene! 

Wondering if you could repurpose this content to Ig. You already shared the Eco Moyo post, so is kind of the same you can decide if turn the into actual posts, or Ig stories. Whatever you think is best.

Tweet 1: 
https://twitter.com/Giveth/status/1718568864009650368 

Tweet 2: 
https://twitter.com/Giveth/status/1717587398479978795

Also I got the[ Meta Business available for Ig today ,](https://business.facebook.com/latest/?asset_id=122860007394916&business_id=546800657540498&nav_ref=instagram_web_self_profile_megaphone_xfam_graduation_upsell) don't know what changed, but before we didn't had access before. Maybe you can use it to schedule Ig posts too! 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnlNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca056b40cc0b083c25c4f5820da10e61c75101b0/Captura%20de%20pantalla%202023-10-31%20a%20la%28s%29%2014.23.22.png)

Thanks Algene! 
I will use this issue to share you content to repurpose.

**Comment by missgene** [comment]
Thanks for sending this my way, Almond! I will work on this :) @oyealmond

**Comment by missgene** [comment]
Hi @oyealmond! These are available for review:

Tweet 1
[Perfect Village for IG](https://www.notion.so/giveth/4d9d40ab72654a858f0ac15f4522838b?v=253392a477be4e0cb7b7016c761cd83d&p=f9c96ca6c31b4f189e72d2ebe163c61e&pm=c)

Tweet 2
[Mycelia for IG](https://www.notion.so/giveth/4d9d40ab72654a858f0ac15f4522838b?v=253392a477be4e0cb7b7016c761cd83d&p=649da53f88b84fc3b36dd5ed98fdf7c1&pm=c)

**Comment by oyealmond** [comment]
Oh wow! These are great @missgene! Thank you so much! Approved! 
Your designs are just awesome.

**Comment by oyealmond** [comment]
Hey dear @missgene, leaving some more repurpose requests below: 

Dream Village update. [Find the tweet w the text to repurpose on Ig and FB here. ](https://docs.google.com/document/d/1tXd0ke0MMk_tpYXbXdsIa6b0eHNtOduwYR_jjoq_0O0/edit?usp=sharing)
