### ISSUE TITLE
Repurpose content for LinkedIn. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1649]
Hey @SteffanThorn , could you please repurpose these tweets content to LinkedIn please? 

Tweet 1: 
https://twitter.com/Giveth/status/1718568864009650368 

Tweet 2: 
https://twitter.com/Giveth/status/1717587398479978795

Tweet 3: 
https://twitter.com/Giveth/status/1716802249626714472

Lmk if you have questions! 
Thank you.

**Comment by missgene** [comment]
Hi @oyealmond! This was delegated to me by @SteffanThorn. Can you please check the initial posts?

Tweet 1
[Perfect Village (Giveth Makers Spotlight)](https://www.notion.so/giveth/4d9d40ab72654a858f0ac15f4522838b?v=253392a477be4e0cb7b7016c761cd83d&p=9a507cdfaeeb4f68ae6c34b537ff62cd&pm=c )

Tweet 2
[Mycelia (Giveth Makers Spotlight) ](https://www.notion.so/giveth/4d9d40ab72654a858f0ac15f4522838b?v=253392a477be4e0cb7b7016c761cd83d&p=9778d6dbf199464180d776795b8710c1&pm=c)

Tweet 3
[Eco Moyo (Giveth Makers Spotlight)
](https://www.notion.so/giveth/4d9d40ab72654a858f0ac15f4522838b?v=253392a477be4e0cb7b7016c761cd83d&p=5e29356fcf5f43c4890ed805684aeab2&pm=c )

Let me know if you want the images to be changed or there are major edits needed for the captions. Thank you!

**Comment by missgene** [comment]
Also, I scheduled them to go once every week. Kindly inform me as well if you want a different schedule to be followed. Thank you!

**Comment by oyealmond** [comment]
Loved them @missgene! All approved thank you so much! :D 
The images and the graphics are just GREAT.

**Comment by oyealmond** [comment]
Hey dear @missgene, leaving some more repurpose requests below: 

Dream Village update. [Find the tweet w the text to repurpose on LinkedIn here. ](https://docs.google.com/document/d/1tXd0ke0MMk_tpYXbXdsIa6b0eHNtOduwYR_jjoq_0O0/edit?usp=sharing)
