### ISSUE TITLE
Project Progress Campaign -  Free Solidity Development Course in Farsi

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1650]
This project recently added a new update:
https://giveth.io/project/free-solidity-development-course-in-farsi?tab=updates

![image](https://github.com/Giveth/giveth-planning/assets/74267818/cc30a267-6df8-478f-91b1-7df08fed08ae)

The course has just finished and students are competing with their projects for the DevConnect scholarship.
This could be cool stuff to highlight before DevConnect starts. 

Maybe we can get in touch with Shayan (https://twitter.com/sbetamc) or Crypt0zan (https://twitter.com/crypt0zan) the project owners to get more details on the results of the scholarship.

@surbhiaroraa Can you decide which platform(s) we will publish this on (twitter, facebook, linkedin, etc), and draft the copy for publication? Thanks! <3

CC @oyealmond

**Comment by oyealmond** [comment]
Thanks @WhyldWanderer! 
Update schedule for next week. @missgene I think we could do an Ig story and a LinkedIn post w this one: 

<img width="317" alt="Captura de pantalla 2023-11-27 a la(s) 5 52 37 p m" src="https://github.com/Giveth/giveth-planning/assets/110692280/324cc430-c468-463c-9762-4dc3eed09c48">

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1734529039891615744 

Hey @missgene ! Please add this as an Ig story

**Comment by oyealmond** [comment]
Hey @missgene ! Did this story went out? If yes, please close this issue :)
