### ISSUE TITLE
Project Progress Campaign - End Homelessness thanks to Web3 Community

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1651]
Great update from this project! 
https://giveth.io/project/end-homelessness-thanks-to-web3-community?tab=updates

![image](https://github.com/Giveth/giveth-planning/assets/74267818/a59dcdcc-2c20-429e-9377-59953189a97c)

Lets feature it as part of our Project Progress campaign...

Some stats from Homeless Entrepreneur:
![image](https://github.com/Giveth/giveth-planning/assets/74267818/695e2e0d-ce42-441f-b037-3b7507af5c5d)

Check out the website:
https://www.homelessentrepreneur.org/en/home

A video introducing Carlos:
https://www.youtube.com/watch?v=54DnXPvrYW0&t=16s

@surbhiaroraa  Can you decide which platform(s) we will publish this on (twitter, facebook, linkedin, etc), and draft the copy for publication? Thanks! <3

CC @oyealmond

**Comment by oyealmond** [comment]
thanks @WhyldWanderer . Tweet is scheduled for next Monday: 

<img width="352" alt="Captura de pantalla 2023-11-27 a la(s) 5 02 42 p m" src="https://github.com/Giveth/giveth-planning/assets/110692280/3d8262e1-ca63-4add-8229-76dc1de95493">

@missgene we already have planned a Homelessness Entrepreneur video for Ig and LinkedIn, so I think we can just share this content as an Ig story.

**Comment by oyealmond** [comment]
Hey @missgene !Did this went out? If yes, you can close this issue
