### ISSUE TITLE
Before & After Impact Campaign - Dream Village

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1652]
Evidence of Impact over time

Dream Village has turned a depleted state farm land into a thriving food forest.
From 2017 until now

https://giveth.io/project/dream-village

https://youtu.be/mkHUlorDNxY?si=Qad3b-SDN1SuShMa

Let;s highlight their story!

@surbhiaroraa  Can you decide which platform(s) we will publish this on (twitter, facebook, linkedin, etc), and draft the copy for publication? Thanks! <3

CC @oyealmond

**Comment by oyealmond** [comment]
Ready @WhyldWanderer . Tweet scheduled for November 15. :) Thanks! 

If you want to check the repurpose issues, check here. [Meta,](https://github.com/Giveth/giveth-planning/issues/1648) [LinkedIn](https://github.com/Giveth/giveth-planning/issues/1649)

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1726888705745408101
