### ISSUE TITLE
Behind the Scenes Campaign - Giveth House

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1653]
The Giveth house has a new pet!
People love cat pictures!

Let's make a post about the new cat!

@franculio do you have any good photos or video content?
What is his name again? Reginald “Cacahuetes” II ?? 

@surbhiaroraa Can you decide which platform(s) we will publish this on (twitter, facebook, linkedin, etc), and draft the copy for publication? Thanks! <3

CC @oyealmond

**Comment by oyealmond** [comment]
Aw, love this! Please @franculio, whenever you can send the pictures! Will be great to feature the cat. 
Thanks @WhyldWanderer !

**Comment by franculio** [comment]
Hey @WhyldWanderer ! I think we could make a more general Giveth house post for Instagram and include some picture of the cat! I'll gather some nice pics and put them here.

**Comment by oyealmond** [comment]
@franculio amix, ¿me pasas por aquí algunas fotitos de la casa por fi? Para publicarlas.
