### ISSUE TITLE
Add Giveth TG Group to the linktree

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1654]
Can we add a link to join the Telegram group here?

![image](https://github.com/Giveth/giveth-planning/assets/74267818/2ba25d16-c394-4f79-b29c-e00df7fe3df7)

https://linktr.ee/givethio

https://t.me/Givethio

Thanks!!

**Comment by oyealmond** [comment]
ofc @WhyldWanderer! 

Done: https://linktr.ee/givethio
