### ISSUE TITLE
GIVbacks Distribution Round 47 Social Media post

### ISSUE THREAD

**Issue by surbhiaroraa** [Giveth/giveth-planning#1655]
Social Media post options:
![GIVbacks Round 47](https://github.com/Giveth/giveth-planning/assets/140404865/96b63726-6053-484e-8e26-f53077aaf400)

Donate. Make an Impact. Get Rewarded. 
Our latest GIVbacks distribution is here! Every 2 weeks, we give back to our amazing donors, turning every donation into a rewarding experience. Check out the details of our latest distribution and see how your generosity is making an impact! 💙 

Donate to give back to society, and we'll give you GIVbacks for your generosity! It's a win-win that makes every donation count. 
Details of GIVbacks distribution round 47 are here!
Donate. Make an Impact. Get Rewarded. 

Please schedule this @oyealmond

**Comment by oyealmond** [comment]
hey @surbhiaroraa! Thanks, but I asked to have separated the numbers from the project highlight so it's optimized for social media. If not the information is too much to have it as 1 image.

**Comment by surbhiaroraa** [comment]
Sure. Here is the updated graphic.
![GIVbacks Round 47](https://github.com/Giveth/giveth-planning/assets/140404865/0ad4ec09-f6ff-4e87-8bdc-2a050dd549df)

Can we schedule it for tomorrow?

**Comment by surbhiaroraa** [comment]
Adding the Project Spotlight one here (putting multiple with different titles, you can choose or let me know if you want any changes)
![Project 1](https://github.com/Giveth/giveth-planning/assets/140404865/10d2858e-672b-4513-990e-4fb258fc1ca7)
![Project 2](https://github.com/Giveth/giveth-planning/assets/140404865/76ab310c-fe20-448c-8613-5f2cc654f249)
![Project](https://github.com/Giveth/giveth-planning/assets/140404865/9217823d-c452-4ba3-b8b7-36edba95d325)

**Comment by oyealmond** [comment]
Hey @surbhiaroraa I was reviewing these materials w/ @laurenluz and there some adjustments to be done:

Some typos: 

 "Donations" 
<img width="664" alt="Captura de pantalla 2023-11-08 a la(s) 21 30 03" src="https://github.com/Giveth/giveth-planning/assets/110692280/3e404c50-5849-49ae-ad1d-2a27e9042a4c">

 "Donations" 
<img width="654" alt="Captura de pantalla 2023-11-08 a la(s) 21 30 17" src="https://github.com/Giveth/giveth-planning/assets/110692280/0945e919-1290-4315-9096-ca0f08a4b0f5">

GIVbacks definition is not correct

Title: **GIVbacks program** 
When you give you get GIV back! GIVbacks rewards donors to verified projects with GIV, super-charging Giveth as a donor-driven force for good.

<img width="658" alt="Captura de pantalla 2023-11-08 a la(s) 21 30 28" src="https://github.com/Giveth/giveth-planning/assets/110692280/40658057-a639-4530-a497-602d30fa0180">

And then there is too much text in the projects images. There are some mistakes here too: 

- Title should be "Giveth Makers Spotlight" (This is the one I've been using in social media). 
- And the text should be a short resume on the projects updates. In the posts copies I can add a description of the project. No need to add what's the project about on text. 
- We should remove the "donate" button, as it is weird to have a button on an image. 
- And also not necessary the "Building the Future of Giving" . Lets keep it simple. 


<img width="663" alt="Captura de pantalla 2023-11-08 a la(s) 21 31 03" src="https://github.com/Giveth/giveth-planning/assets/110692280/aec24d4d-951b-4401-bbe2-4bddedcf807c">

----------------------------

The infographic format is still not friendly for social media platforms. @rodricastillo9013 can we create an Instagram , and a Twitter format for these materials? 

And then also @laurenluz suggested we can have the editable for every round for this task to be easier. 

Is too late for this to be posted at this Round happened at the beginning of October, so let's do these fixes and post it for the next round. .

Lmk if you have any questions :) 
Thanks!

**Comment by rodricastillo9013** [comment]
equipment! We should separate this information for Instagram into 3 separate images, maybe use a carousel. what do you think? @oyealmond @surbhiaroraa

**Comment by divine-comedian** [comment]
Can we make sure this goes out for round 48 with all of the appropriate content and format? 

Disappointed to see we didn't make it for this round

**Comment by rodricastillo9013** [comment]
@oyealmond @surbhiaroraa here you have the last version 
![image](https://github.com/Giveth/giveth-planning/assets/61791380/7de09c8c-98ee-44af-bf3d-d9b4769d75ab)
![image](https://github.com/Giveth/giveth-planning/assets/61791380/a61c5141-3597-4a0f-9a45-c31e533d43b0)

**Comment by rodricastillo9013** [comment]
social media version @oyealmond @surbhiaroraa 
![image](https://github.com/Giveth/giveth-planning/assets/61791380/f6505ffa-1759-49b0-96c9-f4ebcba6a001)
![image](https://github.com/Giveth/giveth-planning/assets/61791380/dcf1b40f-1fc1-4d41-a00d-94899be24968)
![image](https://github.com/Giveth/giveth-planning/assets/61791380/ac0338c3-100a-4a79-85b0-efede2b40b4a)

**Comment by rodricastillo9013** [comment]
https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?type=design&node-id=4138%3A4215&mode=design&t=IEH41LOrVn0LLySG-1 Figma File

**Comment by WhyldWanderer** [comment]
> https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?type=design&node-id=4138%3A4215&mode=design&t=IEH41LOrVn0LLySG-1 Figma File

Hey @rodricastillo9013... can I have edit access for this file so that I can adjust it for each round?

**Comment by rodricastillo9013** [comment]
Done! @WhyldWanderer
