### ISSUE TITLE
Istanbul social media. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1656]
**Ig**  @oyealmond & @missgene 
- Stories from every day (resume) .
- Repost stories from other ppl 
- Instagram reel? @oyealmond 
- Post at the middle of the week
-  Post at the end of the week

**Twitter**
- Twitter thread from the Giveth retreat [here](https://docs.google.com/document/d/1s2XHkkAn2VN44fsVFDVWvrCbTkUDG1AyuzWFzeh81ec/edit?usp=sharing)
- RTs

**LinkedIn** @missgene 
- LinkedIn posts from Instagram. Repost.

**Comment by oyealmond** [comment]
Dear @missgene do you think you can help me make a Drive with all the pictures from the telegram photo channel from Istanbul please?

**Comment by missgene** [comment]
Hi @oyealmond! Yes, I can definitely help you with this. So the first step is to download all the files we have so far on the Telegram group and just upload all of them in our Drive? Thank you!

**Comment by oyealmond** [comment]
exactly! @missgene and post the drive link here. Thanks Algene!

**Comment by missgene** [comment]
Hi @oyealmond! I already uploaded the photos and videos on this folder:
https://drive.google.com/drive/folders/1ElSpCAnZgbyWXVHTZWNQLKnyzk2U3ddo?usp=sharing 

I also created a different folder for the ones I took! Let me know what you think. I can help creating reels or posts for the GIVconnect event :)

**Comment by oyealmond** [comment]
love it @missgene ! You're the best! Thank you so much! YES, would be great to create some content about it. 
To have it scheduled.
