### ISSUE TITLE
Post about How2DAO Conference

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1657]
I'm giving a talk at How2DAO & they want to include Giveth as their Impact Partner!

It's actually really awesome to have all that free publicity & they have been super supportive

Here is their tweet about my talk: https://twitter.com/HowDAObook/status/1721046472903557133

And here is the link to the event: https://www.eventbrite.ca/e/how-to-dao-devconnect-istanbul-2023-tickets-751798127437

People can use the discount code GIVETH30 to get tickets to the event... and we should make a tweet inviting them to do it!!

We can QT their tweet about my talk if we want.

@oyealmond can you whip that up quick? we could make 2 tweet at least... one for today/tomorrow... then one to post monday day-of, before the event saying like "come! it starts today!"

**Comment by oyealmond** [comment]
Sure! Sharing [the drafts ](https://docs.google.com/document/d/1XDSErwcEb0qApVCFsdcMbPecbD6-FpUs51h8dYT_vLw/edit?usp=sharing). Let me know your thoughts and feedback @laurenluz

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1722902428415152145
