### ISSUE TITLE
Check for new Optimism Addresses: Drop 4

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1658]
We'll need to query the db to check for verified projects that have added an OP address. You know the drill @mohammadranjbarz 

Then I will compare against our previous data to find the new projects and setup the distribution of 25 OP each and set it up via our multisig 

Once setup and sent we will inform the comms team to make external communication. 

Here is the spreadsheet I've been keeping data in for reference 
https://docs.google.com/spreadsheets/d/1pZ7SUtFcf6sNZ3A8fZXBvtDGAn_w21qD3WOaB4baDOE/edit?usp=sharing

**Comment by mohammadranjbarz** [comment]
related to https://github.com/Giveth/impact-graph/issues/1155

## Query
```
SELECT 
    pa."createdAt" as "walletAddressAddedTime",
    pa."projectId",
    pa.address,
    p.slug
FROM 
    project_address pa
JOIN 
    project p ON pa."projectId" = p.id
WHERE 
    pa."networkId" = 10 AND pa."isRecipient" = true AND p.verified = true AND p."statusId"=5
ORDER BY 
    pa."createdAt" ASC;
```

## Result
[verified_project_with_optimism_address_2023-11-30.csv](https://github.com/Giveth/giveth-planning/files/13517211/verified_project_with_optimism_address_2023-11-30.csv)

**Comment by divine-comedian** [comment]
tx is up and awaiting signatures to send to 16 projects 
https://app.onchainden.com/safes/oeth:0x4d9339dd97db55e3b9bcbe65de39ff9c04d1c2cd/transactions/0xae20526e9f689f530b49768d10bbd4de51f98bb6a114e0324fbb67807b3eca24


FYI @oyealmond

**Comment by divine-comedian** [comment]
@oyealmond - this latest batch went out! 
https://app.onchainden.com/safes/oeth:0x4d9339dd97db55e3b9bcbe65de39ff9c04d1c2cd/transactions/0xae20526e9f689f530b49768d10bbd4de51f98bb6a114e0324fbb67807b3eca24

16 projects have received 25 OP as part of the ongoing incentives program
![image](https://github.com/Giveth/giveth-planning/assets/67759413/eb8e1be4-d9e3-4ff6-af01-bd1c517396c0)

**Comment by oyealmond** [comment]
ok, scheduled! thanks @divine-comedian
