### ISSUE TITLE
It would be awesome to add ourselves as a project on the Giving Block to understand their flow

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#166]
The giving block uses Gemini to do an off ramp... they have a very interesting flow... it would be good to build a bridge with them ;-D

**Comment by Danibelle** [comment]
Nice - I'll take this on.

**Comment by WhyldWanderer** [comment]
@Danibelle have we done this yet?
Im willing to support you on this

**Comment by laurenluz** [comment]
@WhyldWanderer @Danibelle is this done?

**Comment by laurenluz** [comment]
Can we close this or icebox it if there's no energy for it?? @Danibelle @WhyldWanderer
