### ISSUE TITLE
Tweet for telling projects that funds from the Optimism QF round have been sent!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1660]
These should get sent soon! Can keep an eye on this tx: https://app.onchainden.com/safes/oeth:0x6e8873085530406995170Da467010565968C7C62/transactions/0x858bcbc34cb88fe9d20d94ebbedba0e591cf6c3c4c70e18c9a8ce98651fca03b

The summary of the matching funds can be found in here:
https://forum.giveth.io/t/qf-optimism-round-results-october-9-23-2023/1226

We should make a tweet or short thread saying "thank you all donors & projects who participated in our Optimsim QF round!" and then we can summarize some of the stats - number of projects onboarded to optimism, number of participating projects, number of unique donors, amount donated, amount of matching.

There can be a second tweet linking to the forum post that shows the results (forum post) for anyone wondering about more details.

we should send this asap after the funds are actually sent.

@oyealmond @SteffanThorn

**Comment by oyealmond** [comment]
Hey @laurenluz! @divine-comedian just confirmed this is sent. So I'll start w/ the comms.

**Comment by laurenluz** [comment]
great work @oyealmond ! These are ready to go!

**Comment by oyealmond** [comment]
Hey @ahmadabugosh could you help us send [this email ](https://docs.google.com/document/d/13T0YfpATJaGW0h5LXuj1uLILiWIq-8TJKe8F-7FIDLk/edit)asap please?

**Comment by oyealmond** [comment]
Hey @ahmadabugosh! Whenever you have a chance can you send[ this email?](https://docs.google.com/document/d/13T0YfpATJaGW0h5LXuj1uLILiWIq-8TJKe8F-7FIDLk/edit?usp=sharing)

**Comment by oyealmond** [comment]
Only the tweet went out. 

https://twitter.com/Giveth/status/1728136487084970030
