### ISSUE TITLE
Add QF results into the database for Optimism round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1661]
We shoudl input the final matching amounts into the backend so that it shows the *actual* matching amount now on the donation tab.

Here are the final matching amounts: https://docs.google.com/spreadsheets/d/1mvEBigyt1ecJSQnTbWNVt_8hK8T8-kJogRqjCYn1qt0/edit#gid=619125131

here is the tx link: https://optimistic.etherscan.io/tx/0x0046a5c4e9d3609583709273fc5202074de86592124cdfd8c14516b551675d80

You should input the tx link as well!

@CarlosQ96 @mohammadranjbarz - who has time for this asap?

**Comment by CarlosQ96** [comment]
Data inputted!

**Comment by CarlosQ96** [comment]
@laurenluz

**Comment by laurenluz** [comment]
@CarlosQ96 - there is an issue, when I click "view tx" it goes to a crazy link.. I think there is something wrong w/ the way we go to the link... see the .iotx? should there be a "/"?

https://explorer.optimism.iotx/0x0046a5c4e9d3609583709273fc5202074de86592124cdfd8c14516b551675d80

I was testing w/ this project: https://giveth.io/project/giveth-house?tab=donations

**Comment by CarlosQ96** [comment]
@laurenluz I think that link is built in the frontend. I only send the txhashes. @mateodaza or @RamRamez  can you check?

**Comment by mateodaza** [comment]
on it!

**Comment by CarlosQ96** [comment]
It simple, I merged. Thanks Mateo

**Comment by CarlosQ96** [comment]
It's fixed @laurenluz

**Comment by laurenluz** [comment]
great! thanks guys!
