### ISSUE TITLE
Quadratic Force Master - Design

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1663]
I made this summary/master doc to give to sponsors interested in funding QF rounds: https://docs.google.com/document/d/1C7qRKgxLmYUxX7QzDYIug2dzakb_nNVENHc_QW-OfM8/edit

@rodricastillo9013 is working on making it into a pretty design.

Creating this issue so we can all be in the loop on updates/follow up!

Rodri - let us know where you're at with this :)

cc - @SnakeGH @brichis

**Comment by rodricastillo9013** [comment]
Tomorrow I will have this finished!

**Comment by rodricastillo9013** [comment]
@SnakeGH @laurenluz 
[GivethQF Marketing.pdf](https://github.com/Giveth/giveth-planning/files/13529734/GivethQF.Marketing.pdf)
hello! Sorry for the delay, here I leave the first proposal, you can leave me comments and changes to the figma https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?type=design&node-id=4240%3A247&mode=design&t=CdbE1fKjr9IkbvE6 -1, I would also need you to share photos of the people we are missing to add it!

**Comment by laurenluz** [comment]
love it Rodri! can you add a link to https://forum.giveth.io/t/qf-optimism-round-results-october-9-23-2023/1226

on the stats for the Optimism round? similar to how you did it for the Alpha round (I think it was my mistake for not including it in the google doc).

For the missing people, maybe you can use their twitter images
https://twitter.com/charliecfeng
https://twitter.com/richatlarge

**Comment by rodricastillo9013** [comment]
@SnakeGH Tomorrow for sure!

**Comment by SnakeGH** [comment]
GM @rodricastillo9013 any updates on this, as I see the edits are still pending :)

**Comment by rodricastillo9013** [comment]
[Giveth Marketing QF Force.pdf](https://github.com/Giveth/giveth-planning/files/13580268/Giveth.Marketing.QF.Force.pdf)

Hello team, sorry for the delay, I have already made the changes.
- Updated photos
- I have added the link to the forum to see more information about optimism Round

This information is already added here, what other information are you referring to? @laurenluz 
![Captura de pantalla 2023-12-06 a la(s) 11 38 27](https://github.com/Giveth/giveth-planning/assets/61791380/f3d0ec47-c577-4b00-8634-53b37237547a)

@SnakeGH
