### ISSUE TITLE
Social Media Content for Giveth Wgs. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1665]
Hi @laurenluz, @divine-comedian, @WhyldWanderer, @SnakeGH / @brichis 

I will prepare a new pull of content for Giveth's social media and wondering what are your working group priorities/messages that you want to communicate in the next days/months. 

Some examples so you can have a reference: 

- With @WhyldWanderer - Have done content about specific Giveth projects
- With @laurenluz - Content for QF Rounds and time sensitive initiatives. 

Will be great if you can provide as much info/resources for the content you need. 

cc @SteffanThorn @missgene

**Comment by SnakeGH** [comment]
For Fundraising Circle really only right now is: Gitcoin Grants #19 ending in 2 days (which I know you have already been all over Comms on it) but recap, everyone needs to ensure they use Griff's Picks and ensure you donate to 15 of them. https://explorer.gitcoin.co/#/projects?collectionId=griffs-oss and here is a nice bridge to PGN - https://www.layerswap.io/app

Only other "fundraising item" would be maybe another Optimism RetroPGF #3 push since voting ends on Dec 7th. Not sure how it should look but good to have a follow up message this week and next

**Comment by SteffanThorn** [comment]
I can help with the retropgf push

**Comment by oyealmond** [comment]
hey @SteffanThorn! when would you be able to deliver the RetroPGF content? We need to replace the paid campaign tweet thread soon. Lmk if I can support you w smth! :)

**Comment by oyealmond** [comment]
@divine-comedian @WhyldWanderer @laurenluz Any requests?

**Comment by divine-comedian** [comment]
Sure! We can talk about the following topics from the dapp update: 

## Spanish Translations 🇪🇸
- This feature is live! Thanks @Ramin amin, based on your browser settings and country, the dapp should now show up automatically in Spanish!

## Multisig/Gnosis Safe Integration 🖋️
- This will allow organizations with multisigs to use Giveth - allowing them to sign in, create profiles, projects and even boost projects with their GIVpower! 
- @Mateo & @Carlos have finished the first version and passed onto testing.
- Work is ongoing to test & fix as needed, expected delivery is in 1-2 weeks for this feature

**Comment by laurenluz** [comment]
### Polygon Round
- The applications close today, so we should keep an eye on Jokerace comms and make posts directing people to vote
- Polygon is right now hosting "quests" where people can vote on how many projects should be in the round [tweet](https://twitter.com/0xPolygonLabs/status/1730257920061751647). maybe we make a quote tweet of it
- We should finalize the notion for the round & prep some content for after jokerace that says like "projects! here is a guide to help you add your project" and distribute it via email to the projects & on social media.

### Christmas QF
- We are thinking to host a round from Dec 19- Jan x so we should prep content for:
- [ ] Projects, join the round
- [ ] Donate in the round (round started, a few in between, some "last days")
- FYI Mitch had an idea to let Giveth NFT holders choose the projects in the round, so for the 1st part... we should prep content saying like "Givers holders get to choose... get a giver here, fill out this form to nominate a project" (will provide clearer details on this soon)

### Retro PGF push
- I think Stee is working on this, but it's really important so want to mention it here! I think we should make some memes to post like the one I did about onboarding nonprofits to Optimism etc.

**Comment by SteffanThorn** [comment]
We are doing a xmas round?

Okay memes for RetroPGF I can do. 

I like the Giveth NFT holders ideas.

**Comment by SteffanThorn** [comment]
Can we have an ideographic a bit like the one in the link, but Giveth Xmas adapted? 

Here's the link: https://twitter.com/Crypto_Altruism/status/1711521061374718159/photo/1

Here could be Giveth script:

What is QF?

Quadratic Funding encourages democratic allocation of funds among groups of projects and their communities. 

What difference does QF make?

Smaller donors in QF can get a greater say when part of a bigger community. The more people who donate to a project, the more weighted that project is in matching funds. 

How to be a part of Giveth Xmas QF?

Contact [person/discord channel] to be on the list. 

Get voted in by Giveth NFT holders

**Comment by SteffanThorn** [comment]
Got some RetroPGF tweet: https://docs.google.com/document/d/1ivP7GEWQ_OEElkb2p9urcKcLa9pGrWyNww1pPfHKwWo/edit?usp=sharing

And some Giver NFT holder tweets: https://docs.google.com/document/d/1TdF5JI8TKJaAm1AFlVkKmeEFdUz2zGrIj-q6ZONv1eU/edit

**Comment by SteffanThorn** [comment]
Do we want a thread for RetroPGF too?

**Comment by oyealmond** [comment]
Maybe @laurenluz , could you support with a RetroPGF thread?

**Comment by oyealmond** [comment]
hey @SteffanThorn! Thanks for your content support! 
@divine-comedian the Spanish dApp update tweets are scheduled, lmk when the Multisig/Gnosis Safe Integration is ready to announce it. 
And well as the RetroPGF & GG19 tweets went out as well @SnakeGH . 
Im working closely with @laurenluz with the missing QF Rounds content. 
Closing this issue, to work in separated issues

Thanks!
