### ISSUE TITLE
Mobilize our community to get prepared for Octant Epoch Two

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-planning#1669]

**Comment by brichis** [comment]
Hey @oyealmond! I spoke with @laurenluz about some preps for Octant's Epoch 2 and I think the first one if to mobilize our community to lock sooner. If I'm right, they can buy GML during these days and lock it at: https://octant.app/allocation to allocate rewards during Epoch Two.
https://docs.octant.app/tips-for-beneficiaries.html#mobilizing-your-community

The key points are really useful if we want to explain first what is Octant but let me know if you need some extra info from me.
https://docs.octant.app/#key-points

Important days to consider:
📸 Snapshot Vote: Jan 1-5, 2024
🪟 Allocation Window for Epoch Two: Jan 17-31, 2024

This is our old proposal for Epoch One:
https://octant.app/project/1/0x6e8873085530406995170Da467010565968C7C62

**Comment by laurenluz** [comment]
thanks @brichis! this is great!

exactly @oyealmond or @SteffanThorn can prep something for this. the idea is really simple, we can just put out a couple of tweets about "the longer you stake your GLM, the greater your voting power".

And we could mention the upcoming dates... & tell people that they will be able to vote on which projects are recipients.

We could also summarize some of the impact created with funds from the last epoch.

These could go out any time this month when we have a bit of downtime after retropgf & before the christmas qf round.

**Comment by oyealmond** [comment]
Thanks @brichis @laurenluz . Madre some [drafts](https://docs.google.com/document/d/1cFzEVDaPHqmRlu2RY9U6_6h9NzVTwV2Zr-JXxTrO830/edit) here. Please take a look and provide feedback. Thanks!

**Comment by laurenluz** [comment]
I think they're great @oyealmond! made some small edits & left a comment. I think the tagged projects you'd need to double check. you could ask in the fundraising channel which of our projects got in... I think praise, pairwise & giveth were all above the threshold & will participate again. Rotki for sure, and gitcoin.

**Comment by oyealmond** [comment]
Great @laurenluz, thanks! 
Im already scheduling this. 
I asked @brichis when is the deadline for ppl to do this so I can schedule in the proper dates. Thanks!

**Comment by laurenluz** [comment]
I think the "deadline" will be in January, but people get proportionally less voting power if they wait until closer to the allocation window date to stake. so I would space these out on quiet days during December

**Comment by oyealmond** [comment]
Thanks for the clarification @laurenluz ! 
I scheduled this 2nd tweet for Dec 28th: 
<img width="323" alt="Captura de pantalla 2023-12-15 a la(s) 4 02 34 p m" src="https://github.com/Giveth/giveth-planning/assets/110692280/6fa1f19f-e08d-4aca-8ee0-200a1a10a90b">

Lmk if you have any thoughts or observations!

**Comment by oyealmond** [comment]
hello @laurenluz @brichis ! 

Any other comms request around Epoch Two you need?

**Comment by brichis** [comment]
Hey @oyealmond! Yes please, allocation window is starting soon. Could you prepare some tweets about it? It will be from Jan 17 to Jan 31. Thanks!

**Comment by brichis** [comment]
Hey @oyealmond! Yes please, allocation window is starting soon. Could you prepare some tweets about it? It will be from Jan 17 to Jan 31. Thanks!

**Comment by oyealmond** [comment]
Hey @laurenluz! Whenever you can can you review these drafts, https://docs.google.com/document/d/1ZyhvgXZRTodaXShFnIM5FYBqbP2s6NuEEmE6UO7oWJY/edit?usp=sharing? 

Lmk your thoughts so I Can schedule these content. 

cc @brichis

**Comment by laurenluz** [comment]
Hey @oyealmond I modified & posted the 1st one: https://twitter.com/Giveth/status/1747687395246453013

**Comment by laurenluz** [comment]
made some edits also to the 2nd one - want to post it as well some time early next week?

I think it might be nice also to create at least one more for Jan 30 that's like - time is running out to support ( round ends tomorrow)... if you don't take action, your rewards will go back to Golem.

**Comment by oyealmond** [comment]
Already [wrote a last tweet](https://docs.google.com/document/d/1ZyhvgXZRTodaXShFnIM5FYBqbP2s6NuEEmE6UO7oWJY/edit) to remind ppl about the deadline to allocate funds. Lmk you thoughts @laurenluz. I'll post the second Octant tweet early next week

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1752350609775145160
