### ISSUE TITLE
Donation Metrics on Giveth.io! Where / How to display and share?

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-planning#167]
From the Giveth 2 Dev channel on Discord:

Some interesting data from the database:
- 236 donations
- $4,996 raised
- average donation = 21.16$
- 190 donations in xDAI - 639$ (average 3.36$)

Would be so cool to have this presented on the Home Page somewhere, and communicated in regular Comms updates!

**Comment by laurenluz** [comment]
I can add this into future what's dappened posts

**Comment by WhyldWanderer** [comment]
That would be awesome @laurenluz! I know @jamespfarrell likely has the capability to pull a few interesting stats from the db.

It would be nice to have some of the stats featured on one of the slides that @markoprljic  is working on for the banner/header.

Im not sure if there is an issue to reference for the slides but there has been some discussion about it in the design channel on discord.

**Comment by laurenluz** [comment]
Check out #656

**Comment by laurenluz** [comment]
https://giveth-dashboard.herokuapp.com/public/dashboard/5218ea60-42ef-416b-80f0-4b58fc78ef49
