### ISSUE TITLE
Update project description and define some deets

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-planning#1670]
I talked with @laurenluz  about next steps for Octant and she told me that we have to update our Octant’s project description, make some decisions about how much money we want to keep and how much to donation.eth.

Important dates:
📅 Project Info Submission Deadline: Dec 22, 2023
📸 Snapshot Vote: Jan 1-5, 2024
🪟 Allocation Window for Epoch Two: Jan 17-31, 2024

**Comment by laurenluz** [comment]
Here's what I wanted to change the description to last round: https://docs.google.com/document/d/1g0CNZjTCtEpHJZv2GPpev_bJP0RsrdSMkVH3WGjMW-U/edit

We missed the time to send it in though. it's good I think for the next one, but we should really decide if we want to use funds still for donation.eth or for us - or what split (in epoch 1 we did 50/50) - we can discuss this perhaps in the fundraising call.

**Comment by laurenluz** [comment]
Griff thinks we should go ahead w/ the 50/50 split again.. so there it is! We could use that to update our description. I will tell James in our chat w/ him on discord

**Comment by brichis** [comment]
Yei! Perfect! Can I close this issue @laurenluz? :D

**Comment by laurenluz** [comment]
sure! though I like this issue better than the other one I assigned you to because the dates you put at the top are useful! maybe you can copy/paste them over :)
