### ISSUE TITLE
Post about kick-off of ENS Small Grants

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-planning#1672]

**Comment by brichis** [comment]
Hey @oyealmond! Can comms prepare something to announce that ENS Small Grants has already started? Last time they took like a month to start the voting period so I'm pretty sure there is a lot of people who is not aware of this.

**Comment by brichis** [comment]
Looks great! Maybe we can have something about... Check if you have a voting card! If you previously engaged in small grants rounds, submitted projects in past rounds... You probably have it, check it here: Opensea link to Vote Card NFT. wdyt? In the past round a lot of people didn't know they had a vote card

**Comment by oyealmond** [comment]
Added! 

Thanks
<img width="324" alt="Captura de pantalla 2023-12-04 a la(s) 9 15 24 a m" src="https://github.com/Giveth/giveth-planning/assets/110692280/4f0f0828-0327-4712-99c2-e9568fcb7883">

**Comment by brichis** [comment]
Thank you so much @oyealmond!
