### ISSUE TITLE
Polygon Jokerace flow update tweet

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1673]
@oyealmond - here's a draft!

idk if we should post this or not... Polygon didn't tweet anything from their official account yet.

Maybe you can keep an eye out on their Twitter / ask in the chat if it makes sense? or we just wait & see

https://docs.google.com/document/d/1Fjb1Qd1JW8JThD4mqK0k2N3iSraV-2ie4VTuOWo3bng/edit

**Comment by oyealmond** [comment]
Great! I'll ask on the chat to double check. Thanks @laurenluz!

**Comment by oyealmond** [comment]
Hello @laurenluz . Polygon posted about next steps. I used your tweet and tweaked it a little bit to fit Polygon's info. [Lmk your thoughts. ](https://twitter.com/Giveth/status/1734708395930792436)

**Comment by laurenluz** [comment]
Thanks @oyealmond ! saw it got posted: https://twitter.com/Giveth/status/1734948428952563811

great :)
