### ISSUE TITLE
Update Onboarding Guide for Holiday QF Round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1674]
Hey @oyealmond 
Can you help to [update the notion guide](https://www.notion.so/giveth/5320f4c94563418e93e4736d9276cba0?v=0d08a51c7da440278cc5971b9001e8b9) for the Holiday QF Round?

we should save a copy of the Polygon version... We might even want to have like multiple versions... because we might end up sharing both guides at the same time!

So perhaps you can have a pre-section that's like: which round are you interested in? Polygon Village Builders or Giving Season?

Info:

Basic round details:
Matching funds: $25,000+ on OP Mainnet (DAI or USDGLO, and I put "+" because we increase the pool size if we are able to do a good fundraise this week!
Number of projects: approx. 125 (might be more if we can increase the matching pool)
Dates: December 19, 2023-January 2, 2024
Eligible chains for Donations: Optimism ONLY

Project eligibility:

In order to join the round, projects must be nominated by someone who holds a Giver! An individual address can nominate up a maximum of 5 projects - but can only nominate one project per Giver they hold.

Projects must also be VERIFIED & must have an Optimism recipient address to participate in the round.

**Comment by oyealmond** [comment]
Hello @laurenluz :) 
[Please review the guide.](https://www.notion.so/giveth/Giveth-Quadratic-Funding-3478aa27eb094a699f9ddd6a8b611027) Feel free to edit, or send me a DM so I can edit
