### ISSUE TITLE
Giving Season QF Round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1675]
Basic round details:
Matching funds: $25,000+ on OP Mainnet (DAI or USDGLO, and I put "+" because we increase the pool size if we are able to do a good fundraise this week!
Number of projects: approx. 125 (might be more if we can increase the matching pool)
Dates: December 19, 2023-January 2, 2024
Eligible chains for Donations: Optimism ONLY

Project eligibility:

In order to join the round, projects must be nominated by someone who holds a Giver! An individual address can nominate up a maximum of 5 projects - but can only nominate one project per Giver they hold.

Projects must also be VERIFIED & must have an Optimism recipient address to participate in the round.

**Comment by oyealmond** [comment]
anything else on the Giving Season that's missing @laurenluz? Can we close this epic?

**Comment by laurenluz** [comment]
closed!
