### ISSUE TITLE
Creating project nomination form for Giver NFT Giving Season QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1677]
We want Giver holders to be able to nominate projects, @divine-comedian helped me set up this form for it: https://giveth.deform.cc/qf-nomination/

**Comment by laurenluz** [comment]
@oyealmond I just wanted you to know this exists :-D

**Comment by oyealmond** [comment]
great @laurenluz! Question. This week Givers tweets have a "get one" CTA. Should I start adding the QF projects nominations component to the Givers tweets?

**Comment by laurenluz** [comment]
I think YES! but it would be great if we could announce the round first. So maybe we draft something today/tomorrw & put it out on Thursday?
