### ISSUE TITLE
Tweets & Email asking people to get Givers & nominate projects!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1678]
We should prepare content to announce the upcoming holiday round & ask people to get Givers & nominate project!!

- Tell people we are running the round & start [round details] like Optimism network, $25k matching pool, verified projects chosen by Giver holders - use "spirit of Christmas" vibes & emojis!
- Tell people what Givers are, where the money goes & to mint them [here](https://giveth.io/nft/mint).  This can be quick like "the Givers are an NFT collection representing the Giveth community, all proceeds go to making Giveth better"  / we can borrow the best of our original Givers content. 
- Share the [deform link](https://giveth.deform.cc/qf-nomination/) where they can nominate projects, and include details if we want... like each Giver can nominate 1 projects & that each address can nominate up to 5 projects. Projects will need to be verified & have an Optimism address (you can see more of this info on the form)

Might be worht mentioning explicity that projects need to be Verified, and will need to add an Optimism address by Dec 15 to qualify.

@oyealmond - either you or I (or if someone else can!) can do this... as soon as we have the notion doc ready, we can start putting this out too asap (like in the next 2 days)

**Comment by laurenluz** [comment]
We should prep:
- [ ] 1 long form or thread style post explaining all about the round in detail
- [ ] some short form tweets teling people to mint givers, nominate projects, etc (repetition). maybe like 5 of these
- [ ] 1 email to go out to everyone explaining the round + all the details with sections: for everyone (saying get a giver & nominate & stay tuned to donate) & for projects (saying get verified, add an Optimism address (get 25 OP bonus for the 1st time) ask people to nominate them, or get a giver and do it themselves!

**Comment by oyealmond** [comment]
Hey @laurenluz! I created the announcement tweet. Please review it[ here](https://docs.google.com/document/d/1lCYDlBZHlqbhQKBoTjiFgSa_gT4egkFwZQ0gfKoV7MM/edit?usp=sharing). Based on your corrections I will do the rest of the materials. I think at least with this one, we can post it asap.

**Comment by laurenluz** [comment]
great!! although when I put it in tweethunter a couple of them were too short. I edited & scheduled it for today!

I think the sooner we announce the better :)

**Comment by oyealmond** [comment]
Great @laurenluz! 

Sharing [the rest of the tweets](https://docs.google.com/document/d/1gC9VggJpTToL7J8vKVpw2OZsa8meZ0Pz0AjL4KNu2DI/edit?usp=sharing) for your review

Working right now with the guide, and on the email.

**Comment by oyealmond** [comment]
@ahmadabugosh @laurenluz please review [this email](https://docs.google.com/document/d/1TusbCtOs8GDaLN9CJ1yqdaeZvvHyKOiJyAYQOBwUcI4/edit)

**Comment by laurenluz** [comment]
@ahmadabugosh - this email is ready to go! can you help to schedule it to go out to our full list? https://docs.google.com/document/d/1TusbCtOs8GDaLN9CJ1yqdaeZvvHyKOiJyAYQOBwUcI4/edit

**Comment by ahmadabugosh** [comment]
@laurenluz @oyealmond the first email has been sent (the one to our full database). 

I'll send the other one early next week just to the GIVers NFT holders

**Comment by oyealmond** [comment]
Thanks @ahmadabugosh !
