### ISSUE TITLE
Creating How to run a QF round notion

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1679]
https://www.notion.so/giveth/Running-a-Giveth-QF-Round-4c12191f08b8444c80198bf033faafd0

**Comment by oyealmond** [comment]
Hello @laurenluz :) 

Is this done? Or should I move it to Notion. 

Thanks!

**Comment by laurenluz** [comment]
ahh it's not done, but don't worry about recreating the issue, it's on my mind anyway because I need to train someone to cover for me.
