### ISSUE TITLE
Draft launch Tweets and recurring Tweets/threads for change-maker campaign

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#168]
We will need to draft tweets for launch and recurring tweets/threads recurring post-launch for the social media change-maker campaign.

**Comment by divine-comedian** [comment]
Check out Sage to Saddle creating change! Providing Native American youth in South Dakota healthy lifestyle alternatives via equine relationships and horse care. Bravo! #Giveth4Change 

@jonimadere
https://giveth.io/project/sage-to-saddle/

--------------------------------

Check out Conscious Medicine Collective fostering community wellness. Making a space for exploration into holistic healing and plant medicine therapy in the Basque Pyrenées. Keep up the dream! #Giveth4Change 

@jonimadere
https://giveth.io/project/conscious-medicine-collective/

**Comment by laurenluz** [comment]
Been spending time today upping my twitter game, and would like to revise the above tweets to increase engagement:

Help Native American youth rise above poverty and substance abuse.

Sage to Saddle provides kids with healthy lifestyle alternatives via equine relationships and horse care.

Make a difference! Like, Retweet or Give👇
https://giveth.io/project/sage-to-saddle/

@jonimadere 
#giveth4change

**Comment by laurenluz** [comment]
Interested in psychedelic exploration and plant medicine therapy? 

Conscious Medicine Collective is combining art, medicine and spirituality, creating an experiential club for consciousness elevation.

Like, retweet or Give👇
https://giveth.io/project/conscious-medicine-collective/

@jonimadere
#giveth4change

**Comment by divine-comedian** [comment]
Amazing! :ok_hand:

**Comment by jonimadere** [comment]
These are all super. Thank you both for the support!

Joni

joni madere
jonimadere.com
310.733.7064

**Comment by laurenluz** [comment]
Want to transform the world by empowering regenerative projects?

Bloom Network is creating connections between initiatives that are solving major social and environmental problems.

Like, Retweet or Give🌷
https://giveth.io/project/bloom-network/

@OurBloomNetwork
#giveth4change

**Comment by laurenluz** [comment]
We called and the change-makers answered!

Check out these amazing projects on giveth.io that are raising funds and making a difference in the world 👇

Don't forget to share your story with #giveth4change to be featured next!

https://medium.com/giveth/calling-all-change-makers-7fa964684c2b

**Comment by laurenluz** [comment]
Want to raise funds while making the world a better place?

Add your project to giveth.io and tweet with #giveth4change to join the change-makers👉https://cutt.ly/Abo1Xe2

@PermaAction @Anne_Connelly @Pollinationproj @ awesomefound @ NewEconomics @AlliedMediaConf 

![image](https://user-images.githubusercontent.com/75490971/116449502-796f8d00-a817-11eb-9e04-c0ef2db23db1.png)

@Danibelle @magentaceiba @divine-comedian - ready to blast this out tomorrow on twitter - does that work?

**Comment by magentaceiba** [comment]
Permaaction and anne connely already have projects on there - i think they may be good people to retweet an invite/announce to their audiences

**Comment by magentaceiba** [comment]
couple other data points - the others are coalitions (or grant-giving institutions) made of projects that are actively raising funds through normal pathways, they just don't have enough usually. They're actively change-makers, just underfunded. Also they're mostly BIPOC, not sure if that matters with the white guy in the meme. This is what I meant about I don't have the headspace to write copy for the specific kinds of outreach.

**Comment by laurenluz** [comment]
hahaha so many nuances!! yeah, I was looking at their twitters after making the draft and thinking that it might be good to reach of personally. I'll work checking them out and sending DMs. Just I noticed some of them, like awesome foundaiton, have DMs disabled. 🤔 

For perma-action and Anne connely are you suggesting I ask them personally to retweet us?

**Comment by divine-comedian** [comment]
Ah you stole my comment mid typing Lauren, haha. I think we'll have to spend some time drafting more personal tweets for each. I don't think the meme fits in either.

**Comment by laurenluz** [comment]
Sorry @magentaceiba I didn't read your original comment as thoroughly as I could of. I'm making a new issue for this and assigning myself, @WhyldWanderer and @Danibelle so we can reach out to each in the appropriate way:

https://github.com/Giveth/giveth-planning/issues/183

**Comment by jonimadere** [comment]
Hi @laurenluz,
I'm loading 3rd project and Giveth is now asking for me to input Eth address which I didn't have to do with the others. Is this a new thing or...?
Thank you!

**Comment by laurenluz** [comment]
@jonimadere I replied in the discord #support channel - we can chat there :)

**Comment by laurenluz** [comment]
closing this in favour of more holistic weekly twitter planning (new issue)
