### ISSUE TITLE
Check for new Optimism Addresses: Drop 5 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1680]
We'll need to query the db to check for verified projects that have added an OP address. You know the drill @mohammadranjbarz 

Then I will compare against our previous data to find the new projects and setup the distribution of 25 OP each and set it up via our multisig 

Once setup and sent we will inform the comms team to make external communication. 

Here is the spreadsheet I've been keeping data in for reference 
https://docs.google.com/spreadsheets/d/1pZ7SUtFcf6sNZ3A8fZXBvtDGAn_w21qD3WOaB4baDOE/edit?usp=sharing

**Comment by mohammadranjbarz** [comment]
## Query
```
SELECT 
    pa."createdAt" as "walletAddressAddedTime",
    pa."projectId",
    pa.address,
    p.slug
FROM 
    project_address pa
JOIN 
    project p ON pa."projectId" = p.id
WHERE 
    pa."networkId" = 10 AND pa."isRecipient" = true AND p.verified = true AND p."statusId"=5
ORDER BY 
    pa."createdAt" ASC;
```

## Response
[verified_project_addresses_with_optimism_address_drop5.csv](https://github.com/Giveth/giveth-planning/files/13627314/verified_project_addresses_with_optimism_address_drop5.csv)

related to https://github.com/Giveth/giveth-planning/issues/1658#issuecomment-1834449401

**Comment by divine-comedian** [comment]
Looks like there's no new projects to add this month! We'll check back in january

**Comment by divine-comedian** [comment]
@mohammadranjbarz - can we take another look at this one since it has been a month?

**Comment by mohammadranjbarz** [comment]
@divine-comedian 

## Query

```
SELECT 
    pa."createdAt" as "walletAddressAddedTime",
    pa."projectId",
    pa.address,
    p.slug
FROM 
    project_address pa
JOIN 
    project p ON pa."projectId" = p.id
WHERE 
    pa."networkId" = 10 AND pa."isRecipient" = true AND p.verified = true AND p."statusId"=5
ORDER BY 
    pa."createdAt" ASC;
```

## Result
[verified_project_addresses_with_optimism_address_drop6.csv](https://github.com/Giveth/giveth-planning/files/13860456/verified_project_addresses_with_optimism_address_drop6.csv)

**Comment by divine-comedian** [comment]
Thanks Mohammad! 

This tx is pending on the multisig: https://app.onchainden.com/safes/oeth:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd/transactions/0x1baebaa4845154793789f71fbdadba9d9750876ca998fb70a0a0e9a0574e8be9

When it passes @oyealmond  we can notify via twitter as usual.

**Comment by oyealmond** [comment]
perfect.[ This tweet](https://docs.google.com/document/d/141qEZM_-2iysqgHdzymuK3yPJ4AQmjQmzu9IyjM42_c/edit?usp=sharing) is schedule for tomorrow. Thanks @divine-comedian

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1745793258775560654
