### ISSUE TITLE
Join the Quadratic Force tweets

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1682]
draft(s) here: https://docs.google.com/document/d/1d8SJlmnAdJ7jscKS2f4VjoxqhMdFUFJ-JM1sI4Mirm4/edit

posting asap!

cc @oyealmond

**Comment by oyealmond** [comment]
thanks @laurenluz !
https://twitter.com/Giveth/status/1734559251320741919
https://twitter.com/Giveth/status/1733472083743502833
