### ISSUE TITLE
Social media content for promoting Giving Season QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1683]
We need some tweets for during the round (Dec 16 - Jan 2), similar to: #1574

I think we can/should repurpose tweets like [these](https://docs.google.com/document/d/1s57mds9B8LsIUjsMcuK9H58lHvNUXSiSBpxLdYIxtJw/edit):
- announce the round
- promote GIVpower
- promote referral program
- promote GIVbacks
- promote QF guide 

Plus some like:
- how to promote your project [repurpose this](https://docs.google.com/document/d/1inir4dhF1dm6gUITmuf1UTVynBw1JNzoU2HsbPDWlfQ/edit)
- or some general ones like "shill your fave project etc." similar to the ones in [here](https://docs.google.com/document/d/1-y3uyqJD2Z2c9AEl2npQ_pGl9Y9pxyZpcQp5B-5mWeM/edit)

And some more ideas:
- just a few days left to donate
- last day to donate
- merry christmas & donate (it's the biggest time of year for donations, maybe include some stats)
- ring in the new year & donate (some tips about like how to start the new year off right & use "donating in QF" as one of the points)

@oyealmond can you help with these before you go on vacation? :) then we can edit & schedule them all in advance.

**Comment by laurenluz** [comment]
We can also make a tweet asking for feedback via [this updated form](https://giveth.typeform.com/QFfeedback)

**Comment by oyealmond** [comment]
Sure! I started drafting the content [here](https://docs.google.com/document/d/1wV5JtCZLLwf17IT6mwB9jQ7KtzFpBjtjx8TaSkGCkR4/edit?usp=sharing). This is a work in progress. Missing some content still.

**Comment by oyealmond** [comment]
hello @laurenluz  Please find the tweets [here](https://docs.google.com/document/d/1wV5JtCZLLwf17IT6mwB9jQ7KtzFpBjtjx8TaSkGCkR4/edit) . Please start reviewing them so we can edit or add what's missing. Thanks!

**Comment by laurenluz** [comment]
they are awesome @oyealmond I made some edits, but nothing major.

Some points:
- you are using Christmas images & gifs right? we should take advantage of the colors of the holiday season in the imagary as much as possible... I didn't check the images in the doc through tweethunter (FYI)
- I think we are going to do the round in USDGLO on Optimism so we should perhaps we can make one more tweet saying something about why we're using GLO & how this is aligned w/ holiday season vibes

**Comment by laurenluz** [comment]
added you to the Glo group on tg where we are coordinating round stuff. I asked them to share some links/context so you can draft a tweet :)

**Comment by oyealmond** [comment]
here's the draft for your review @laurenluz ! https://docs.google.com/document/d/1AQTtkHC6uHCNMDeJOZwqnGSkVUkVJMzm9Sj7Qyv_L0s/edit

**Comment by laurenluz** [comment]
I saw this went out already, right @oyealmond ?

**Comment by oyealmond** [comment]
yes! @laurenluz already out
