### ISSUE TITLE
Plan Twitter Shill Spaces for Giving Season QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1684]
We should host some shill spaces for projects during the Giving Season QF round. I think we can make them similar to the ones from OP, but with perhaps less intro time just talking about OP etc.

I think it would be good to host at least 2 spaces... if not 3. If @oyealmond is not around to help, maybe we can coordinate w/ @missgene to help manage the projects in the round.

We can do like 20 min of talking time & then 40 min of shill time.

We can talk a little about:
- the guide we prepared
- tips on how to promote your project
- what is verification & why you should donate to verified projects (or why get verified)
- the Givers NFT collection & the nomination experiment
- our QF Rounds feedback form (we can tweet it some day & collect new feedback)
- something to do with news years / new start / new years resolutions
- Optimism & why optimism (but not too much time on this)

Here are the links I found from the last spaces, to use as a reference / starting point:
- [OP Kickoff](https://docs.google.com/document/d/1Nipie1udAxZoX_8DpMLaVYaXLNd15UsNwiwAzdu0yII/edit)
- [OP Halfway there](https://docs.google.com/document/d/138DM4EvkwU8v_O3U-RZUJuAVkUvtN695jQAxshH1ZPc/edit)
- OP Final - I couldn't find the old link

I'll be in ET for these spaces, so let's coordinate on the best times to host them.

**Comment by oyealmond** [comment]
Hey! 
So we decided having one X Space on the 20th – I'll run it. And a second on the 27th, run by @anamarija09 . 
Sharing our Spaces links through here, 

[X space on the 20th. ](https://twitter.com/i/spaces/1yoJMwnZMdOKQ)
[X Space on the 27](https://twitter.com/i/spaces/1yNGaZyNVVXJj)

I also created the calendar events from Giveth email. 
Sharing tomorrow the scripts, questions and tweets to promote them. 

Thanks!

**Comment by oyealmond** [comment]
[Sharing the script + tweets from our X Space happening this Wed 20th.](https://docs.google.com/document/d/1sMt9t-4IH5Tedf5zb0z0z92m8GUOhWq1Z6X3U4SWqRg/edit) @laurenluz, please review & share your feedback.

**Comment by oyealmond** [comment]
[And here's the second script](https://docs.google.com/document/d/1dUTgfG7UMbrfv_gerIkMCn53PdyI-VsbaRBhJ2s5JSs/edit?usp=sharing) with @anamarija09 running & @laurenluz hosting for your review.
