### ISSUE TITLE
Onboard projects (gitcoin mini edition)

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1686]
Hey team, I created this issue to stay aligned on the progress of this task.

I have pulled out the most promising projects I could find in GG19 climate solutions round, and education round, including the most supported ones during the rounds that ended. I will have one last fishing check once Im finished with the current list.

Now I am almost finished with the project prescreen (filtering only those we can VERIFY), it is taking a bit more time and I try to balance my other tasks, however, it's coming together and I have a strategy in mind.

The idea is to begin an outreach from my personal accounts (utilizing Algene's help) and invite those projects to onboard onto Giveth, get Verified, and claim their OP for adding OP address. As a win for Giveth this should bring great projects, they shall bring their own community support/donors and that will ideally generate more adoption.

For checking on the state of the list, you can check it here:
https://docs.google.com/spreadsheets/d/10vyttgfLUpBeHegMC_ihy-M1Uh_HVoY5VtXp91VHOsk/edit?usp=sharing

cc @oyealmond 

I wonder if I should try to push this outreach during December or wait until after Christmas. Not sure which is smarter...

**Comment by oyealmond** [comment]
Hey @NikolaCreatrix ! This list looks great! I'll not wait and start contacting them right away, thinking that these are less packed days for a lot of people and could have more mental space to consider Giveth, and review the information. So I'll recommend to start right away. 

Let me know if you need something from me!

**Comment by NikolaCreatrix** [comment]
Alright, thanks a lot. I finalized the prescreen and added some more open-source projects. The final number on the list is 41.

I am feeling confident to manage the outreach by myself at this point. (@missgene )

Thanks to @oyealmond 's feedback I was able to craft a sweet personal message:

"Hey there, my name is Nikola and I hope this message finds you well. I saw this project (revoke.cash) in the last GG round, congratulations on such a great success! 

I would love to share with you about Giveth – I believe it could be a great tool to strengthen your project! Giveth (giveth.io) is a crypto donation platform & our mission is to empower public goods projects (like yours!) with Web3 tools.

As part of the project verification team, I would love to offer you to join our platform as a complementary fundraising option. I will help you with the onboarding and with the verification process: completely FREE! This could be a HUGE win-win! :smile: 

If you decide to join Giveth & get verified, you'll get: 

· 25 OP tokens (over 55 USD right now) by adding an OP address 
· You will become part of the GIVbacks program which means donors who donate to your project via Giveth will be rewarded with GIV tokens (possibly up to 80% of their donations back) 
· 100 % of each donation goes directly to your project, we're a peer-to-peer donation platform. 
· You can activate or deactivate your project whenever you want.

I would love to share more benefits.
What do you think? Do you have any questions? I'd love to talk! 

Nikola"

And I am jumping into this. Will keep tracking my progress in the doc

(https://docs.google.com/spreadsheets/d/10vyttgfLUpBeHegMC_ihy-M1Uh_HVoY5VtXp91VHOsk/edit?usp=sharing)


cc and FYI @GriffGreen

**Comment by oyealmond** [comment]
Is this still happening @NikolaCreatrix ? Should I move this to icebox?
