### ISSUE TITLE
SEO Article for 2024

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-planning#1687]
I think it's a great method to make SEO articles, and then repurpose them into twitter content. 

Plus SEO articles get us higher on google searches. 

So, here is a list of article titles. 

Would like to nominate @surbhiaroraa to help the process follow through. 

Information and guidance can come from @laurenluz @ahmadabugosh @oyealmond @divine-comedian 

Here's a current list I've come up with: 

Is Regenerative Finance good for the environment?
The main challenge of collecting crypto donations
The problem of trust between donors and nonprofits
The power of sharing your organization's story (MeetTheGivethMakers) 
Should people be paid for volunteer work?
What is the future role of governments?
How to make global donations
How to donate without a bank account
How can you donate with bitcoin? 
How can you donate with Ethereum? 
Is donating good for the environment? 
What are the top catastrophes that could happen to humanity? 
Is crypto bad for the environment? 
How is a DAO different to a traditional organization? 
What are the pros and cons of building a DAO? 
What is a bonding curve? 
Where does GIV's value come from? 
What is the future of public goods web3? 
How to make a web3 wallet with email
How can we end poverty?
Is cryptocurrency safer than fiat?

**Comment by divine-comedian** [comment]
Hey @SteffanThorn - Please refer to @oyealmond for approving comms tasks and assigning work to contributors

**Comment by oyealmond** [comment]
Hello @SteffanThorn . Our last season SEO initiative was incomplete, as nobody was able to track & measure impact of what we did.  If you want to create some of these articles as content for Giveth's Medium, I can help you review and publish. 

Send your pieces through here . 
Thanks.

**Comment by SteffanThorn** [comment]
Happy New Year. 

Here's my first SEO piece: https://docs.google.com/spreadsheets/d/1M5i11BJlenxenenbL-W9HE15HJ1YSw4bnNDKvn8xm8o/edit#gid=929450173

**Comment by SteffanThorn** [comment]
@oyealmond please tag relevant editor/reviewers and let's get this ball rolling. 

I will continue to build out content -- then repurpose it into content for X and Li 

If there needs to be a new issue for each article that's all goods, just let me know.

**Comment by SteffanThorn** [comment]
Another one: 
DeFi vs ReFi
https://docs.google.com/document/d/1TY9iOWbcTnuj3EeBD0V80dJrXCPyTG7_S4gCmMW6ZR0/edit?usp=sharing

**Comment by SteffanThorn** [comment]
Paid-volunteering/Contribution rewards
https://docs.google.com/document/d/1JepBgA6u4NEg5LgNx9ABFU6L82axws2SjcFaptS7MMM/edit?usp=sharing

**Comment by oyealmond** [comment]
Hey @SteffanThorn! Today @ahmadabugosh during the comms call had some great ideas around creating articles related to QF... Letting him develop more on this

**Comment by ahmadabugosh** [comment]
Hey @SteffanThorn , 

Yes, so to give you context I was thinking it would be more beneficial to go after a more crypto native audience first and dominate that market on SEO. 

To start, I would recommend focusing on "quadratic funding" keywords. There isn't a ton of info on that topic besides Gitcoin, so I think it would be super easy for us to rank for it. 

Content longer form than: https://www.wtfisqf.com/

I noticed a lot of people are also searching for the formula for how quadratic funding is calculated, I think that could be a good post too. 

A few ideas could be: 

- "What is Quadratic Funding in Crypto & Web3"
- "Quadratic Funding Formula Calculation Crypto"
-  "Top 3 Crypto platforms for Quadratic Funding" (listing Giveth, Gitcoin and clrfund)
- "The power of quadratic funding for crypto projects", this could be an explainer post on the orignins of QF, how it helps allocate a matching pool and why it's a great way to democratically allocate funds. 

<img width="866" alt="Screenshot 2024-01-12 at 10 55 40 AM" src="https://github.com/Giveth/giveth-planning/assets/4855928/7f1eb8cd-e60c-491e-a3f1-73c92d5bccc8">

**Comment by SteffanThorn** [comment]
Got a QF article here:
https://docs.google.com/document/d/15f8h8D8MuVaA7ItKoTLAdB_J-C2kbfIfIDuXw_WOMIA/edit?usp=sharing

Tried out a story way of showcasing what it is. 

Also, the link above about QF removed the equation -- I tried learning it from another resource but got confused -- maybe a math-savvy member could explain it to me :D

**Comment by SteffanThorn** [comment]
Another QF article: 
https://docs.google.com/document/d/1d18eW72jXIUp4ETfgRoEuCIYXxKnd_6aHwWuTdZ59qI/edit?usp=sharing

This one is more focused on the benefits of blockchain tech for funding, including QF.

**Comment by oyealmond** [comment]
Hey @ahmadabugosh ! Do you think you can help me check these articles please?

**Comment by oyealmond** [comment]
On this one , I think @laurenluz's input would be awesome! https://docs.google.com/document/d/15f8h8D8MuVaA7ItKoTLAdB_J-C2kbfIfIDuXw_WOMIA/edit

**Comment by oyealmond** [comment]
I made a bunch of edits in this one https://docs.google.com/document/d/1d18eW72jXIUp4ETfgRoEuCIYXxKnd_6aHwWuTdZ59qI/edit 

Can you review it @ahmadabugosh please?

**Comment by ahmadabugosh** [comment]
@oyealmond Can we hand this SEO project to Kareem / Denitsa?

**Comment by oyealmond** [comment]
Will pause the SEO strategy for this quarter. Moving this to icebox.
