### ISSUE TITLE
Emails for Giving Season round (2 emails)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1688]
We should prep 2 emails:

Round open email - send out Dec 19
- One at the start of the round, telling people it is open & time to donate
- Tell them to donate only on Optimism
- Let them know about upcoming shill spaces, especially the first one (but we should link all)

Round close to end email send out Dec 30 or 10
- Tell them to ring in the new year w/ a donation! time is running out
- Let them know about last shill space.

We could also share the guide or "how to promote your project" notion.

**Comment by oyealmond** [comment]
Hey @laurenluz @ahmadabugosh here's the [Round open email ](https://docs.google.com/document/d/1T0ZwhrqmQwzEBEWD9iFg7-vLibUzgXmhYYZRih4KAQY/edit?usp=sharing)for your review.

**Comment by oyealmond** [comment]
Hello @laurenluz @ahmadabugosh , here's the [last days to donate email](https://docs.google.com/document/d/18hzSw1GAMCOgd59u2yqmRavWNmU3vC0g44eY08TOgLY/edit?usp=sharing) for your review. 

Didn't include the X Space link, as will happen before sending this reminder (Dec 30, Jan 1st)

**Comment by laurenluz** [comment]
Made some edits on both, they are good to schedule, whenever you can @ahmadabugosh!

The [1st one](https://docs.google.com/document/d/1T0ZwhrqmQwzEBEWD9iFg7-vLibUzgXmhYYZRih4KAQY/edit) should go out on December 19 sometime after 11am ET

The [2nd one](https://docs.google.com/document/d/18hzSw1GAMCOgd59u2yqmRavWNmU3vC0g44eY08TOgLY/edit) should go out on Jan 1.

**Comment by ahmadabugosh** [comment]
First email sent!
