### ISSUE TITLE
Email to projects to let them know they are in!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1689]
We should be sure to include:

- a link to the [notion doc](https://www.notion.so/giveth/a85a3d1557d04a7e9fd3d43eddce6e60?v=8db00935f63b48be82ba61e5ea6527c6) we made as a resource for projects
- Round dates & times: December 19 - January 2
- Matching pool size: likely $25k in USDGLO on Optimism 
- A link to this typeform asking projects for their Twitter handles (if they didn't fill it out already) [form](https://giveth.typeform.com/to/irQ2YO6e)
- An invitation to our QF round Twitter spaces

**Comment by oyealmond** [comment]
hey @laurenluz @ahmadabugosh! [Sharing this draft](https://docs.google.com/document/d/1nzPI_r0ZRKmzmX9-MPYhXhZKR0tGE0_WDzQCap362Sk/edit) for you to review & send whenever's ready.

**Comment by laurenluz** [comment]
it's awesome @oyealmond I made some edits, and ready to go. working to the get the list of project emails now

**Comment by laurenluz** [comment]
ok! Ashley is putting this in Autopilot to send out to project owners now. The list is in [this spreadsheet](https://docs.google.com/spreadsheets/d/19C1uJyuBlSLSXi11cAZcYk1rKQi4ZSIUDpB4RQsHmwc/edit#gid=1993554789)

**Comment by laurenluz** [comment]
it was!
