### ISSUE TITLE
GIVbacks Round 48 Impact Report Infographics

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1690]
Here they are @oyealmond! 

Round 48 GIVbacks were distributed yesterday... it took me a while to get Figma to cooperate but I have since figured it out and will try to make sure it is ready on the same day that the distribution happens so that we can post about it all at the same time in the future.

Long Format:

![image](https://github.com/Giveth/giveth-planning/assets/74267818/580d0350-830b-4297-9506-f0baa3ec7c42)

Instagram:

![image](https://github.com/Giveth/giveth-planning/assets/74267818/16d8fa56-96a7-4689-aa69-c83c799d807d)
![image](https://github.com/Giveth/giveth-planning/assets/74267818/3fc13662-8d97-4210-a1d7-e78a78524a72)

**Comment by oyealmond** [comment]
sure! Sharing a draft [here. ](https://docs.google.com/document/d/1H9WspOyHAst0_Z0UILs5UKUwBEsidDfTaFu0dweZhNw/edit?usp=sharing). @WhyldWanderer @divine-comedian could you help me review please ?

**Comment by divine-comedian** [comment]
Wow this is so awesome! Great work Ash!
