### ISSUE TITLE
Quadratic Force GivingRound tweets. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1691]
We need one with all, one for octant and (most likely) one for public nouns. 
cc @laurenluz

**Comment by oyealmond** [comment]
Hey @laurenluz ! Sharing Quadratic Force tweets [here](https://docs.google.com/document/d/12D2S1jHAGsPIaYKY4EWDZx4-Ep97U1D1c6kqHDReb_8/edit?usp=sharing). 

Also @rodricastillo9013 , if you can share the Quadratic Force designs from this round would be great! Thanks!

**Comment by laurenluz** [comment]
I think these drafts are great @oyealmond - I will schedule them once we have the info confirmed about public nouns, so you can leave it with me :)

**Comment by oyealmond** [comment]
hey @laurenluz ! this week Im still here! Im out until the 25

**Comment by laurenluz** [comment]
all reviewed! it would be good to ask Sky or ask in the chat for public nouns to give the ok on the public nouns tweet.

I don't think we need to do that for octant because it's pretty much the same as last time

**Comment by oyealmond** [comment]
thanks @laurenluz ! sharing PN thread in our Discord group.

**Comment by oyealmond** [comment]
scheduled! Thanks!
