### ISSUE TITLE
GIVbacks Round 49 Impact Report Infographics

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#1692]
@oyealmond 
GIVbacks R49 just got distributed!!
Oct 31-Nov 14

I know the last one JUST went out so Im not sure if you want to wait a day on this one... 
also the data isn't very convincing for this round :/ it was a small one

<img width="1889" alt="R49 Mail Infographic" src="https://github.com/Giveth/giveth-planning/assets/74267818/89c78e61-3edf-48d6-bf75-05febd3777fb">
<img width="1080" alt="R49 Instagram 1" src="https://github.com/Giveth/giveth-planning/assets/74267818/14c31564-311c-47b4-a924-a1221635886c">
<img width="1080" alt="R49 Instagram 2" src="https://github.com/Giveth/giveth-planning/assets/74267818/2bef7b29-b93d-448a-9334-7fd9c88fd403">

**Comment by oyealmond** [comment]
oh! yes, I would not recommend to publish this one, as we just recently published the last one. I'll say to wait to the next round to publish @WhyldWanderer

**Comment by WhyldWanderer** [comment]
closing this issue because it is no longer relevant
