### ISSUE TITLE
Wrong link in GIVnews

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#1693]
<img width="913" alt="Screenshot 2023-12-20 at 2 29 03 PM" src="https://github.com/Giveth/giveth-planning/assets/14945613/66f0962c-ac8d-4093-936b-6a25bad4d23a">

The link is wrong here... its linked to the optimism results... I assume it should be this one: https://x.com/Giveth/status/1725122064602874199?s=20

**Comment by oyealmond** [comment]
thanks @GriffGreen ! 
@ahmadabugosh , could you fix this link? Is still fixable?

**Comment by ahmadabugosh** [comment]
Done, link fixed here: https://news.giveth.io/givnews23
