### ISSUE TITLE
Newsletter December 2023

### ISSUE THREAD

**Issue by anamarija09** [Giveth/giveth-planning#1694]

**Comment by ahmadabugosh** [comment]
This has been sent out.

Sorry if this is too late, but can we post on X about this today reminding people that it's the last day of the QF round? 
@laurenluz @oyealmond 

In our first newsletter of 2024 ✉️
🎅 Last few hours to donate to the Giveth QF round on @optimismFND
💙 Thanks to our GIVfriends @OctantApp @glodollar @PublicNouns 
🏥 Featured project @ThePCRF 
🎖️ Newly verified projects @greenpillnet @RevokeCash @eas_eth 
https://news.giveth.io/givnews24

**Comment by laurenluz** [comment]
https://twitter.com/Giveth/status/1742266583521607747
