### ISSUE TITLE
Multisig Compatbility release comms

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1696]
The Multisig compatbility feature is now available on the Giveth Dapp! 

We should tell people about it! We should make two announcements: 

1. Twitter thread
2. Discord Announcement

## Feature Summary
Giveth users can now sign into the Giveth dApp using their Safe Multisigs, this allows organizations using Multisigs to: 

1. Create Giveth user profiles
2. Own & manage projects
3. Get GIVpower & boost projects
4. Donate to projects
5. Receive GIVbacks

This also allows all of the signers on a given multisig to perform the above actions, meaning if a project or set of projects would like to have multiple "managers" then using a multisig now makes this a possibility!

We also have documentation showing users how to go about 'logging in' with their multisig: 
https://docs.giveth.io/dapps/multisigs

**Comment by oyealmond** [comment]
great! Please review [this announcement ](https://docs.google.com/document/d/1sbHX5tlA5SGh7RsoFQyAjZP3KNk8lG4duyJV2kzFqkM/edit?usp=sharing). Feel free to edit or add feedback

**Comment by divine-comedian** [comment]
@oyealmond - this is ready to go, finally - you can push the tweets whenever appropriate.

**Comment by oyealmond** [comment]
great! This is scheduled for tomorrow @divine-comedian

**Comment by oyealmond** [comment]
posted https://twitter.com/Giveth/status/1748043089548079131
