### ISSUE TITLE
Email to projects confirming that they are IN the Giveth QF round (from Giveth)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1697]
polygon is going to be emailing projects, but we should send one to their emails once we confirm/add them to the round.
This email should include:

- a link to the notion doc we made as a resource for projects
- Round dates & times: Jan 15 8AM PT  to Jan 24 end of the day PT
- Matching pool size: likely 250k MATIC on Polygon PoS
- An invitation to our QF round Twitter spaces

Similar to [this email](https://docs.google.com/document/d/1nzPI_r0ZRKmzmX9-MPYhXhZKR0tGE0_WDzQCap362Sk/edit) that we sent to projects.

**Comment by oyealmond** [comment]
Hey @laurenluz! Sharing the email [here](https://docs.google.com/document/d/17m7iDcRFZKL84d0TOEizv9WZGJ_nGTd5Sf0W7zXs-Sk/edit?usp=sharing). Let me know your thoughts and feedback.

**Comment by laurenluz** [comment]
edited & ready!

@WhyldWanderer @ahmadabugosh - maybe we want to start sending this out to projects that we accept? we could add one more column to our [spreadsheet](https://docs.google.com/spreadsheets/d/1AEcsrm2Dzy3rjsXKEgj7JT2L-ob4ORhLpupAQyygKrQ/edit#gid=920297084)?

I think the sooner we start sending this to projects, the less questions we'll get
