### ISSUE TITLE
2023 GIVbacks infographic. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1699]
Hey @WhyldWanderer! 

Creating this issue to create the infographic we discussed in out call today . Lmk whenever the info is ready so I can give a quick review and @rodricastillo9013 can help us design. 

As we discussed this needs to be done before this Fri Jan 12th. 

Thanks!

**Comment by WhyldWanderer** [comment]
Hey @oyealmond... I hope its not too late to publish this today!? Or maybe to schedule for the weekend...

<img width="1889" alt="Imfographic -  Mail (1)" src="https://github.com/Giveth/giveth-planning/assets/74267818/b646ed53-83a8-464b-b918-8c765c683f27">

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1746522915372257615
