### ISSUE TITLE
Crypto Onboarding

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-planning#17]
Met Ome, former CTO of Bity, and he thinks they have what we need.

https://bity.com/products/crypto-exchange-api/

@GriffGreen is aware of them, and initial conversations with them registered concerns that this may not work for people in the US. TBD

it's a fiat on ramp api. Transfer money to an IBAN and it turns into crypto. We could actually onboard a user and allow them to donate and initiate transfer,and we could show that their token donation has worked but only pending, until payment clears and real tokens are issued. Or we loan them the tokens, or...?

If that's unclear it's cause I'm just throwing ideas around.

**Comment by jamespfarrell** [comment]
@willyogo

**Comment by willyogo** [comment]
very cool @jamespfarrell!

Do you know of any example implementations of their API I can check out?

I'm in favor of leveraging an API like this for a more native experience post MVP (http://ramp.network/ is another cool, similar provider)

**Comment by jamespfarrell** [comment]
@willyogo maybe we should go with Moonpay for now, since we get it near free with Torus [Moonpay] (https://docs.tor.us/torus-wallet/api-reference/topup)

**Comment by jamespfarrell** [comment]
![image](https://user-images.githubusercontent.com/10499048/88230338-88b32000-cc72-11ea-877e-b1a4b564493f.png)

**Comment by jamespfarrell** [comment]
![image](https://user-images.githubusercontent.com/10499048/88230390-9ec0e080-cc72-11ea-8b32-54f2c063de3f.png)

**Comment by Danibelle** [comment]
I just had a great chat with David Casey on the app he built with Oleksii -- the crypto and token engineering is all behind the scenes disguised as 'coupons' .. perhaps there is something to leverage for the fiat ramping from their project?

https://www.resourcenetwork.co/about
