### ISSUE TITLE
Change-maker Bloom Network launch post and recurring posts

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#170]
Draft and publish posts to Bloom Network announcing change-maker campaign, check bloom network for stories/submissions. create recurring posts to send out via Bloom Network. @WhyldWanderer I see your name on the comms doc to assist on this one, is that still the case?

**Comment by magentaceiba** [comment]
I think @WhyldWanderer was tagged to post the outreach for stories for it to Bloom Network's discord where there are many rad projects

**Comment by WhyldWanderer** [comment]
Posted on 4/14 in Bloom discord
