### ISSUE TITLE
Criteria for disqualification for QF rounds

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1701]
When we have open rounds like the POlygon one... we need to make explicity some criteria for disqualification, like people can't do quid pro quos...

maybe we can look at things gitcoin used and put something together.

@oyealmond do you have time to help with some of that research?

**Comment by oyealmond** [comment]
for sure! @laurenluz I'll prepare something and have it ready for tomorrow.

**Comment by laurenluz** [comment]
it's live!

praise almond!
https://docs.giveth.io/quadraticfunding/#disqualifying-factors-for-giveth-qf
https://www.notion.so/giveth/Disqualifying-factors-for-Giveth-QF-c1d383d23996437691a514634638df76
