### ISSUE TITLE
For future fundraiser after trial period... maintain our charmverse profile for Optimism

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#1703]
https://app.charmverse.io/giveth-scary-cyan-butterfly/getting-started

I can log in and add an email and customize this page with the grants.giv.eth key... I can probably share ownership, maybe 

Thx for bringing this to my attn @divine-comedian

**Comment by oyealmond** [comment]
Do you understand this @divine-comedian? Should I move it to Notion?

**Comment by divine-comedian** [comment]
> Do you understand this @divine-comedian? Should I move it to Notion?

You can leave it here
