### ISSUE TITLE
Create announcement about Giveth <> MetaPool partnership - post Jan 18 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1704]
MEtapool asked us to tweet the partnership, they prepped this draft:

> [1] Giveth is thrilled to partner with Meta Pool for a groundbreaking Quadratic Funding Round! 🌟 Thanks to the power of liquid staking, our community is uniting to fuel web3 innovation in the Asia Pacific region. 
>
> Know the details on how YOU can be a part of this impactful journey! 🌐
> 
> [2] Dive into the heart of the collaboration! With a round size of 10,000 USD in mpETH and a matching cap of 20%, this partnership aims to support web3 builders in countries like Vietnam, Indonesia, and more 🌏.
> 
> [3] 🌈 The open call dates are from January 19th to February 12th. Get ready to make a difference! [Link]  

It's a good start to give an idea of the vibe... but we should change it a lot imo :) Need to include:
- Explain matching pool & project eligibility (emphasize APAC region & specific details)
- Explain how to apply for the round (tell projects to create --> get verified --> fill typeform)
- Link to the twitter space that metapool will share in tg tomorrow
- Don't mention the matchin cap
- Link to notion guide

@oyealmond can you help w/ it?

hey also let's add the disqualifying factors thing to the metapool guide & other guides

**Comment by oyealmond** [comment]
yes! I'll share later today.

**Comment by oyealmond** [comment]
Sharing the draft here https://docs.google.com/document/d/1_rg1ZTd-bCFXUJv3c601t1DRNQDyfavhgyW6wPKCZz8/edit 

Lmk your thoughts and feedback! @laurenluz

**Comment by laurenluz** [comment]
https://twitter.com/Giveth/status/1747967584597586216
