### ISSUE TITLE
Optimism thanks tweet 2. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1707]
Referencing this issue https://github.com/Giveth/giveth-planning/issues/1702, wondering if you could help me with some brainstorm of completed milestones, or future plans for OP. @laurenluz @divine-comedian 

We could include: 

- Amount of 25 OP rewards distributed. 
- Amount donated on Optimism (I believe the Giving Round donations are already figured) 
- Number of projects on Optimism / verified and not. 
- What would be some future plans? QF Rounds,

**Comment by laurenluz** [comment]
I think also, an interesting stat is that w/ our OP-focused QF rounds.. there was $50k of matching funds (total accross the two) and an extra $42k donated from unique donors...

so $50k of matching led to $92k of impact on verified public goods projects - and all of this was on Optimism alone.

Maybe in the tweet we can also do like a CTA for verified project owners - add your OP address and get 25 OP just for that... maybe talk about how it's cool to join the optimism ecosystem and that they are doing innovative work like the amazing retropgf stuff that just happened.

We could also to a CTA to follow @ retropgf to stay abreast of other opportunities on optimism.

I also like the idea of including the number of verified projects on Optimism network as a straight number. you can get it from the stats dashboard: https://stats.giveth.io/

FYI  the next QF round will be the metapool one and the matching funds will be optimism... so you could say that if projects are trying to get in that round, they will need to add an OP address... (but FYI donations on any of our support chains are eligible)

As for our next "general verified projects QF rounds" I'm pretty sure it will actually be on arbitrum and we shouldn't mention it in this tweet. 🤔  ofc we need to add arbitrum first... but anyway... we promised arb that we would do that.

**Comment by oyealmond** [comment]
Thanks for your input @laurenluz . I made a draft [here](https://docs.google.com/document/d/1UhOQYzwqsnWuFRX5p6sRotSTy_iH2GIaQrl5K37HzMk/edit?usp=sharing). Could you help me review?

**Comment by oyealmond** [comment]
Hey @laurenluz :) whenever you have some time could you review this please?

**Comment by laurenluz** [comment]
ok @oyealmond! Finally edited. ready to go!

**Comment by oyealmond** [comment]
Loved it @laurenluz! Tksm. I'll post in on Monday.

**Comment by oyealmond** [comment]
Posted https://twitter.com/Giveth/status/1754500489054454216

I also filled the Optimism Marketing form.

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1754500489054454216
