### ISSUE TITLE
Invite APAC projects participate in the Meta Pool Round . 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1708]
Hey @laurenluz! 

Created some simple tweets of the upcoming Meta Pool QF Round[ inviting APAC projects to apply to participate. ](https://docs.google.com/document/d/15cSu4fHNVPoYpGOS4m8PHp4DnTh2TDhWiv92fo203oA/edit). 

Lmk your thoughts & feedback 

Thanks.

**Comment by laurenluz** [comment]
edited, ready to schedule! Thank you Almond!!

**Comment by oyealmond** [comment]
Thanks @laurenluz! All scheduled.

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1756302503832944728
