### ISSUE TITLE
Meta Pool Twitter space - Mon Jan 29 - 8pm CDMX time

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1709]
The goal of this space will be to invite projects to join the round... and make it in a time that's friendly to Asia
we can make it kind of AMA style... metapool will be the guests...
we should explain the project eligibilty, process to apply to the round, important dates, matching pool amounts, etc.

we should also explain QF and give the mic to metapool to talk about what is liquid staking & their goals to fund public goods w/ it.

**Comment by oyealmond** [comment]
Perfect. [Sharing the script here. ](https://docs.google.com/document/d/1vPjDSFpHg6YFE_qJzQ4Y1Z8RAJLyu4CZp9qaEjsqiKk/edit)Let me know your comments & feedback.

**Comment by laurenluz** [comment]
perfect! made tiny changes. I think the tweets can be scheduled and we can share the doc w/ metapool for feedback

**Comment by oyealmond** [comment]
Thank you @laurenluz! Done.

**Comment by oyealmond** [comment]
https://twitter.com/i/spaces/1mrGmylDQRMGy?s=20
