### ISSUE TITLE
Stake Together Partnership 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1711]
Stake Together https://staketogether.org/ will partner with **Giveth to create a pool where the rewards will go to supporting the top 10 boosted (with GIVPower) projects on Giveth**. 

Stake Together works like this:

1. Stake ETH on their website
2. Choose a cause to support
3. get stpETH (like rocket ETH, earns passive interest)
4. Enjoy passive interest while also supporting causes with part of the rewards

Web3 users can get involved by staking their ETH on the stake together website, choosing to support the Giveth pool, getting their stpETH and that's it! As long as they hold stpETH they will be supporting Giveth projects! 

Giveth will distribute funds to the projects who on average had the highest GIVpower rank in a minimum range of 6 weeks (3 rounds), but could be longer. The pool requires at least $200 worth of rewards to distribute, so distribution might take longer than 6 weeks if that condition is not met.

I will have more details & links once the pool is live.

cc: @laurenluz

**Comment by oyealmond** [comment]
great. Noted. We need to announce this partnership, and. make some extra tweets. The call to action will be, boost your favorite projects so they can earn even. more, right? @divine-comedian

**Comment by laurenluz** [comment]
yeah exactly... or like "boost your project to get extra funding" as a secondary CTA... but your is better if you have to choose just one

**Comment by divine-comedian** [comment]
Yeah, and every time we pay out we can announce who was in the top 10 and how much they got

**Comment by oyealmond** [comment]
[Ready the draft](https://docs.google.com/document/d/17xEjFd_ubf75paTewQZVpoK9knncTK8x5iRVSbNyTdE/edit). Just missing the Giveth pool link. 
@laurenluz , could you give it a quick review please?

Thanks
