### ISSUE TITLE
Add our dapp to the Blockscout dapp page

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#1712]
https://airtable.com/appiy5yijZpMMSKjT/shr6uMGPKjj1DK7NL

Make sure to check Arbitrum and Other (and add Celo)

**Comment by oyealmond** [comment]
Done! 

<img width="1139" alt="Captura de pantalla 2024-01-26 a la(s) 10 52 39 a m" src="https://github.com/Giveth/giveth-planning/assets/110692280/0d15000d-aa3a-460e-9c26-adfba5b05485">
