### ISSUE TITLE
Create notion guide for ENS builders round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1717]
This will be similar to metapool:

Round size: $10,000 on Optimism  (I think it will be in USDC, but for now we can just not say anything)
Donations made on the following chains are eligible for matching: ALL
Round 1 start time: ETA mid march (not date finalized/confirmed)
Number of projects in the round: TBD
Matching cap: TBD - depends on the number of projects

Project eligibility:
- projects must be building a public good
- team size must be 5 people or less

How to join the round:
- create a giveth project
- apply for verification / get verified (we will see if you are a public good)
- fill out typeform w/ more info (I will create an issue for the form RN)

Other notes:
- We will include gitcoin passport and since projects will be verified... we can include info about givbacks, givpower, referral program as in Giving season round.
- we need to include disqualifying factors in there

**Comment by oyealmond** [comment]
Understood @laurenluz ! Thanks for the info. I'll start working on this tomorrow!

**Comment by oyealmond** [comment]
Hi @laurenluz! Sharing the Notion guide [here](https://www.notion.so/giveth/002901b63e9a4daaac41bc2f365e4314?v=bc7c8cb78f87461b80d4fe2558431df2). 

I know the dates are not defined yet, so I wrote TBD . Thanks!
