### ISSUE TITLE
Create application typeform for ENS builders round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1718]
The content of the form is here in this doc: https://docs.google.com/document/d/1JOaOHx9z_8dMOKC3-zJbfg-jlo1rZbDcutpL5aSD2Lk/edit

Once content is approved, we should create a typeform for this round and use it in our notion guide & other comms.

@missgene can you help me make it?

cc @oyealmond

**Comment by laurenluz** [comment]
@missgene this is reviewed & ready to make up! can you help create it in the giveth typeform?

**Comment by missgene** [comment]
Hi Lauren!

Form: 
https://giveth.typeform.com/to/Z88GZo8O 

Backend:
https://admin.typeform.com/form/Z88GZo8O/create?block=9802a4666087281d 

Let me know if you want some of the fields to be changed. Also adding the copy version here for record purposes:
https://docs.google.com/document/d/1N3P45wqfMfdd5cfIm0028a8ddJTiSyHaBJSdrT5guYM/edit

**Comment by laurenluz** [comment]
Thanks @missgene! I made some direct edits. Some feedback for the future (since I get your help on this a lot!):
- double check the "end" slide (the slide you see after you submit the form)... this time it was saying something about the ambassador program
- when we ask for a link, make sure you use the "website" option, not short answer
- make sure you change the metadata preview/text to be something related to the 1st page, instead of the default
- create a custom URL too, so it's like /ENSbuilders or /polygonQF or something
- this is really minor, but you included one question accidentally from the previous form
- check to make sure punctuation & spacing is all the same (like every subtext ends in a period, every title ends with no space at the end)

Also re: metadata.. maybe you kmow some hack... I changed it in typeform, but when I paste the link it still shows the old version... is there something I need to do?

**Comment by laurenluz** [comment]
https://giveth.typeform.com/ENSbuilders

**Comment by missgene** [comment]
Hi @laurenluz! Thank you for sharing the feedback. I will take note of these!! Also, I think the meta data is already correct?

"The ENS x Giveth builder’s round is an experiment that aims to provide funding for small teams or individuals building Public Goods with a proven track record." 

I can also see that the meta data is updated when loading the site :) 

![image](https://github.com/Giveth/giveth-planning/assets/93360299/b310949f-b6f3-41a6-87e5-6cc46438e717)

**Comment by laurenluz** [comment]
yeah! it's just strange though, when I paste it in telegram, the preview is still old/wrong <img width="370" alt="image" src="https://github.com/Giveth/giveth-planning/assets/75490971/c9f784d6-18e0-4401-99b0-29c26d3c9e5c">
