### ISSUE TITLE
Solana Launch Comms 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1722]
Planning to launch Solana Integration this coming week! Likely it will be on Giveth as early as January 28. We should plan our communications to go out ~January 31st. Based on our conversations with Solana we have the following: 

## From Solana
- [x] - r/Solana reddit post 
- [ ] - Solana weekly update 
- [x] - QT from their twitter account 

## From Giveth 
- [x] Announcement post on Twitter
- [x] Monthly Newsletter update
- [x] Discord announcement
- [x] Host X space and invite someone from SF

# Integration details 

## Sign in with Solana 
Sign into the dapp with Solana - users can use the following wallets to log in to the Giveth dapp
- Phantom
- Solflare
- MetaMask

## Add a Solana address to your project 
Projects can now add a Solana address to their projects to receive donations to

## Donate on Solana
Donors can now donate to projects that have added a Solana address in SOL as well as some of the top tokens on the Solana network. 

# Fundraising Contest 
For the month of February we will be running a donation contest for public goods and ReFi projects that are building natively on Solana. 

The top 10 eligible Solana projects who raise the most amount of funds by the end of February will get a bonus donation from Giveth. (max $200 USDC in SOL tokens per project)

### How to participate
1. Make your project on Giveth
2. Apply for verification
3. Include your intention to apply for this contest in the first description box of the verification form
![image](https://github.com/Giveth/giveth-planning/assets/67759413/9b86756b-fc38-412f-a264-9ce8a55a57fb)
4. Engage your community to support you with donations! 

#### Notes: 
We will notify you via email if you are included in the contest. 

Any projects caught making fradulent donations (i.e donating to themselves) will be disqualified and lose their verification status.

## Ongoing comms
We will probably want to keep it minimal so it doesn't conflict with the MetaPool round, just a few tweets here and there tagging the SolanaFND and promoting projects to apply and fundraise.

**Comment by oyealmond** [comment]
Thanks for the information @divine-comedian! 

Please @divine-comedian @laurenluz give a quick review to the Solana announcement [here](https://docs.google.com/document/d/1SbuUdqw08-Le5UmB_oUhqfRjXRkMxnSbrPgnpBZW11I/edit?usp=sharing), and let me know your thoughts.

**Comment by oyealmond** [comment]
Also @divine-comedian, we could add send an email about this announcement to the Giveth data base as another actionable. 

And, do we have an image for this? To add it to the homepage. 

Thanks!

**Comment by laurenluz** [comment]
@oyealmond I breezed through and made some edits (see the alternative option for 1.3/) but since mitch was in there too, didn't want to step on his toes!

Anyway, I think it looks pretty good!

**Comment by divine-comedian** [comment]
Discord and Tweet is out - need to follow up w/ them for Reddit and weekly updates 

I see the newsletter is in draft and the twitter space is planned 8th of Feb!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1756997080470491288
https://twitter.com/Giveth/status/1753373247813414959
https://www.reddit.com/r/solana/comments/1ah8huy/solana_is_now_an_option_for_donating_receiving/ 

Hey @divine-comedian ! Is there something missing in our end?

**Comment by divine-comedian** [comment]
> https://twitter.com/Giveth/status/1756997080470491288 https://twitter.com/Giveth/status/1753373247813414959 https://www.reddit.com/r/solana/comments/1ah8huy/solana_is_now_an_option_for_donating_receiving/
> 
> Hey @divine-comedian ! Is there something missing in our end?

I couldn't confirm if Giveth was included in their weekly update - but not missing anything from Giveth
