### ISSUE TITLE
Newsletter January 2024

### ISSUE THREAD

**Issue by anamarija09** [Giveth/giveth-planning#1723]

**Comment by laurenluz** [comment]
I think you can also add an update from the Giving season round... we will be posting the final results w/ the matching funds on the form this week! 

.. it took us a while to process the data.. but on the exciting side there was $19k donated in the round in addition to the $25k matching  pool.

**Comment by oyealmond** [comment]
@anamarija09! Sharing [here](https://docs.google.com/document/d/17xEjFd_ubf75paTewQZVpoK9knncTK8x5iRVSbNyTdE/edit) the Stake Together announcement for you to have more info on this.

**Comment by anamarija09** [comment]
the draft is ready to review: https://docs.google.com/document/d/1diNul2rVUA_8pU8Dv9iKhfSaAfJyUjR6DK9SfjTxIrU/edit?usp=sharing
@oyealmond @laurenluz @ahmadabugosh

**Comment by ahmadabugosh** [comment]
Hey @anamarija09 , thanks for this looks good!

I think we just confirmation on the Solana point from @divine-comedian (updates on the Solana project onboarding, from Lauren's comment) https://docs.google.com/document/d/1diNul2rVUA_8pU8Dv9iKhfSaAfJyUjR6DK9SfjTxIrU/edit

**Comment by divine-comedian** [comment]
> Hey @anamarija09 , thanks for this looks good!
> 
> I think we just confirmation on the Solana point from @divine-comedian (updates on the Solana project onboarding, from Lauren's comment) https://docs.google.com/document/d/1diNul2rVUA_8pU8Dv9iKhfSaAfJyUjR6DK9SfjTxIrU/edit

Thanks for the ping, left some details in the comments about the fundraising contest we are running for solana native verified public goods on Giveth! Super Important we make this one stand out so we hit our final milestone for the solana grant.

**Comment by oyealmond** [comment]
thanks for your comments! 
I think this is ready to go. As @ahmadabugosh mentioned in the comms channel, I think we will send this to the entire data base. Would be great if we can send this today!

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1754596993442132059 

Thanks @ahmadabugosh!
