### ISSUE TITLE
For big rounds like Polygon, we should create a simple form where projects can post their tweets & ask for RTs from us.... then can do it!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1724]
Seeing some feedback from polygon projects some were disappointed that they were not spotlighted during QF rounds.

Optimism has this typeform thing were you can ask to be featured..  if we run a big round like this in the future, we should create somethign similar...

we can ask info about the project and then make a tweet.. or just ask them to post a link to the tweet they want us to reshare - we can go about it in different ways...

but the bottom line is that it would be nice if we had a clear avenue where projects could request to be features or RT'd through Giveth during QF rounds.

@oyealmond - can you help me w/ this? we could even try putting something in place for the metapool round and then battetest it.

**Comment by oyealmond** [comment]
Great! I'll design something on typeform. @laurenluz

**Comment by laurenluz** [comment]
Awesome @oyealmond! I made some direct edits. Let's call this good! Do you want to add it into the notion guides for Meta Pool & ENS rounds, where appropriate? 

We can also make a tweet about it, and keep in mind that it exists when we're writing out future emails for QF rounds.

**Comment by laurenluz** [comment]
Whoa! what kind of black magic... ? hahah I edited it in one spot & it was auto-synced to the other page. cool notion trick @oyealmond ;)

this is great, I think we are done, will inform everyone about the form.

**Comment by laurenluz** [comment]
ooh will you be checking this regularly? or how should we do it?

**Comment by oyealmond** [comment]
sure! @laurenluz. I can check it regularly. Thank you!

**Comment by oyealmond** [comment]
Hey @WhyldWanderer ! 
Tagging you here to follow up on the Discord channel creation to show the Giveth projects social media amplification requests: 

Form: https://giveth.typeform.com/commsrequest
Backend https://admin.typeform.com/form/lVzuIgYW/create?block=9802a4666087281d

We mentioned open a channel only for CommsStar role

**Comment by WhyldWanderer** [comment]
Discord channel is here:
https://discord.gg/Q6hZnZh7

Does it seem good for you @oyealmond ?

**Comment by oyealmond** [comment]
Seems great! Thanks @WhyldWanderer ✨
