### ISSUE TITLE
Scope out comms work & budget for QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1725]
How much time are we putting into the comms for QF rounds?
Are we charging partners enough for that work?

We should scope this out! I can do this w/ you help @oyealmond - I agree maybe we can have a call to discuss it, making this issue not to forget

**Comment by oyealmond** [comment]
love this! Let's meet next week! @laurenluz

**Comment by oyealmond** [comment]
Hey @laurenluz! 

Can I close this one? 
Or should we work in something else? 
Thanks!

**Comment by laurenluz** [comment]
oh maybe we can move it to notion, it's not done.

**Comment by oyealmond** [comment]
Done https://www.notion.so/giveth/Scope-out-comms-work-budget-for-QF-round-e33d3711c87a4326b6ac9ef36b7946af?pvs=4
