### ISSUE TITLE
Giveth Onboarding page promotion .. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1726]
Hey @ahmadabugosh! 

You would like to promote more the Giveth onboarding page right? https://giveth.io/onboarding 
I was thinking drafting some tweets, anything else you think we could do? 

 @divine-comedian maybe we can also include it as part of our project onboarding emails? Could you support on this?

**Comment by divine-comedian** [comment]
We have this as part of another issue here: https://github.com/Giveth/giveth-dapps-v2/issues/3467 to make it more visible on the website. 

I also have been adding the link in more emails as part of the email service migration which I'm currently working on.

**Comment by oyealmond** [comment]
this is great @divine-comedian. Thanks. I'll prepare some content
