### ISSUE TITLE
Check for new verified projects with Optimism addresses: Drop 6

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1727]
We'll need to query the db to check for verified projects that have added an OP address. You know the drill @mohammadranjbarz 

Then I will compare against our previous data to find the new projects and setup the distribution of 25 OP each and set it up via our multisig 

Once setup and sent we will inform the comms team to make external communication. 

Here is the spreadsheet I've been keeping data in for reference 
https://docs.google.com/spreadsheets/d/1pZ7SUtFcf6sNZ3A8fZXBvtDGAn_w21qD3WOaB4baDOE/edit?usp=sharing

**Comment by jainkrati** [comment]
is this somethign we can automate ? @mohammadranjbarz pls feel free to take it up and also brainstorm ideas with Amin , Carlos offline if required.

**Comment by divine-comedian** [comment]
@jainkrati - we only need to do this until we've run out of incentive funds, we've spent about 50% of the allocation thus far, if we think automating it for this temporary initiative is worth the time then sure, in the meantime I will need this query ASAP to move forward with this month's pending distribution.

**Comment by mohammadranjbarz** [comment]
## Query
```
SELECT 
    pa."createdAt" as "walletAddressAddedTime",
    pa."projectId",
    pa.address,
    p.slug
FROM 
    project_address pa
JOIN 
    project p ON pa."projectId" = p.id
WHERE 
    pa."networkId" = 10 AND pa."isRecipient" = true AND p.verified = true AND p."statusId"=5
ORDER BY 
    pa."createdAt" ASC;
```
## Response
[Project with OP address drop 6.csv](https://github.com/Giveth/giveth-planning/files/14231849/Project.with.OP.address.drop.6.csv)


related to https://github.com/Giveth/giveth-planning/issues/1680#issuecomment-1880955429

**Comment by divine-comedian** [comment]
@oyealmond  - The multisig transaction is up here to airdrop some more OP to verified project owners on Optimism 
https://app.onchainden.com/safes/oeth:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd/transactions/0xa7b623169caed97b766a6cf62a6fa7caadcd494eb2b14908e4b936a06133fd44

When this passes could we notify our community via twitter? 

22 verified projects this time for a grand total of 259 projects we've distributed to so far

**Comment by oyealmond** [comment]
great! I'll be aware when this passes to write a tweet. @divine-comedian

**Comment by divine-comedian** [comment]
> great! I'll be aware when this passes to write a tweet. @divine-comedian

I just checked in on it and executed it - ready to be announced!

**Comment by oyealmond** [comment]
great @divine-comedian . Posted https://twitter.com/Giveth/status/1757821445323829733 thanks!
