### ISSUE TITLE
Giving Season funds distributed email. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1730]
Hey @ahmadabugosh and @laurenluz ! 

Sharing [the draft for the funds are distributed email](https://docs.google.com/document/d/1PLy9oim-w1OAVZOnarS1Lac8paIqQNJdrG-PuWCF7UE/edit?usp=sharing). 
Please let me know your thoughts and comments.

**Comment by laurenluz** [comment]
@ahmadabugosh - I edited this and the funds have been sent! can you send the email out to our user base?

if the new email system is set up, you could try emailing it JUST to projects & donors who participated in the giving season QF round, but if not, at your discretion.

**Comment by ahmadabugosh** [comment]
Sent!
