### ISSUE TITLE
Meta Pool Announcement & recurrent QF round content. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1732]
Hi @laurenluz! 

Sharing [Meta Pool's QF Round announcement & Recurrent Tweets](https://docs.google.com/document/d/1LpTZMTyESyQue4x-SG-IEVByZZ8ed_gHObY2egRg08s/edit) for your review. 

Please let me know if something missing, or needs extra edition.

**Comment by laurenluz** [comment]
great work @oyealmond - I edited all and left some comments on a couple. these are good to schedule (unless there is a comment that requires pending work, like the feedback form)
