### ISSUE TITLE
Invite projects participate in the round content. 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#1734]
Hi @laurenluz! 

[Sharing the content inviting projects to participate in the ENS QF round](https://giveth.notion.site/How-to-join-the-ENS-Builder-s-Round-58435aaf62744d13aaf9b1a281c126be). 
Please let me know your thoughts and feedback. 

Thanks

**Comment by laurenluz** [comment]
Hey @oyealmond - did you prep some tweets? the link here goes to the notion, which is great, but we should make some social media content and start posting this this week.

**Comment by oyealmond** [comment]
yes! https://docs.google.com/document/d/1rMLHGE49caF9kC7A1V3lGNyIPdmnmcSyIjNj4D1HYK8/edit?usp=sharing 

Sorry the link was wrong @laurenluz

**Comment by laurenluz** [comment]
ok awesome! edited & good to go! 

I posted it in the ENS group so they can have a look, but I think if they give a thumbs up or don't say anything critical, we can start scheduling, spacing out between now and March 14.

great work, as always @oyealmond !
