### ISSUE TITLE
Meta Pool - email to projects letting them know they are IN!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1735]
We should let them know all the round details & dates, plus link forum post. We should basically send this out over the weekend after the final list & emails are confirmed.

@oyealmond can you draft it?

**Comment by oyealmond** [comment]
Ofc. [Here's the draft for your review](https://docs.google.com/document/d/1hRqn5oSTWQwuJ3U3j1cj6vdcKfmr7K-bSD6u39lYT6Q/edit?usp=sharing) @laurenluz 

Tagging @ahmadabugosh, so he can help us send this out.

**Comment by laurenluz** [comment]
great job @oyealmond! I made some edits. This will need to go out on Sunday, will get you the list as soon as I have it @ahmadabugosh

**Comment by laurenluz** [comment]
ok we have the list of confirmed projects! all but the yellow one: https://docs.google.com/spreadsheets/d/14q_y25M5tu6oGGb0evKumRHFOnxq6EBq/edit#gid=411690982

there are only a few emails actually... one person owns 3 of the projects in the round...

@ahmadabugosh can you send it out?

**Comment by ahmadabugosh** [comment]
This has been sent!
