### ISSUE TITLE
Donorship Announcement Comms

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#1740]
We are ready to announce our partnership with Donorship! 

Donorship is a widget that is placed on crypto websites allowing their users to make donations to non-profits and public goods! 
https://donorship.io/

![image](https://github.com/Giveth/giveth-planning/assets/67759413/c738c074-d5ac-4305-8722-ad2d7756b6a8)

![image](https://github.com/Giveth/giveth-planning/assets/67759413/6c293aa0-6ec4-448a-8d1f-341682c0870c)

You can see it in action on the glo dollar website: 
https://www.glodollar.org/

Our partnership with Donorship will have Giveth's verified projects listed on this widget to be able to receive donations. They are already integrated with The Giving Block so Giveth project's will show up alongside The Giving Block projects

Donorship team will be post a tweet along with a medium article they wrote regarding the partnership

To use Donorship

1. Visit a participating website such as glo dollar 
2. Use their widget to select an organization & token to donate
3. Choose the amount to donate & confirm the transaction!

### Details 

- Donations made on the widget won't receive GIVbacks or be eligible for QF matching 
- It could take up to 3 weeks for donations to show up on the Giveth dApp since it is a manual process of adding them.. for now

## To-do list 
@oyealmond 

- [x] Tweet
- [ ] included in GIVnews
- [x] Discord announcement

Something else??

**Comment by oyealmond** [comment]
Great @divine-comedian . Please review [this tweet ](https://docs.google.com/document/d/1ZM2kOD8W1JBG2S9sgn4JYMHi0ht7Wk3OKVGyIjYBh2M/edit), and after you editing it, I'll create a couple more to post regularly about this integration.

**Comment by divine-comedian** [comment]
> Great @divine-comedian . Please review [this tweet ](https://docs.google.com/document/d/1ZM2kOD8W1JBG2S9sgn4JYMHi0ht7Wk3OKVGyIjYBh2M/edit), and after you edit it, I'll create a couple more to post regularly about this integration.

Reviewed! :heavy_check_mark:

**Comment by oyealmond** [comment]
https://twitter.com/Giveth/status/1760983355850441204

**Comment by divine-comedian** [comment]
Great! Last task is to make sure we get it in the GIVnews
