### ISSUE TITLE
tweets for Glo Dollar gitcoin grant

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1742]
Hey @oyealmond so as mentioned, we are in a funding round w/ glo dollard on Giveth, it would be nice to put our a couple of tweets during the round period (Feb 19 - March 12).. maybe one per week?

Elizabeth was starting to write some content for this, it's here: https://docs.google.com/document/d/18cNjL0pKIIiupA9e0GG4GHoV43kuSRgPJT5gg0e3E9s/edit

Feel free to use any of that that you like or simplify it. It's a $10k round and there are quite a few projects in it, so I don't think we should put a lot of work into a HUGE push.... but a little effort to support Glo & the round would be great (and ofc atttract some donors).

I, for some reason, can't find the round link... but I added you to the tg gorup where they are giving the details.

**Comment by oyealmond** [comment]
Hey @laurenluz! Could you review these tweets please? 

https://docs.google.com/document/d/1Bbw2Yu9c_etJMpnKfj5WAUWswaRPiu6kesGAycutkKw/edit

**Comment by oyealmond** [comment]
All scheduled. Thanks!
