### ISSUE TITLE
Create an onboarding flow for new users

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#1744]

**Comment by ahmadabugosh** [comment]
When a user creates a new account on Giveth and enters their email, we should send them a welcome sequence, similar to the one we have on the [giveth.io/onboarding](https://giveth.io/onboarding) page.

[Uploading... Screen Shot 2024-02-20 at 7.49.04 PM.png]


We need to think about: 
 - What the trigger is (if they save an email in their profile)
 - What is the email sequence and if we want to have multiple paths (if they're interested in becoming a donor or project etc.) 
 - If there are any additional triggers (if we send them a difference sequence if they make a donation or setup a project etc.)

**Comment by oyealmond** [comment]
hello @divine-comedian . For this issue, as @ahmadabugosh's mentioning, when user create a profile and adds an email, is possible for us to send them an email sequence? 

cc @krmet

**Comment by ahmadabugosh** [comment]
<img width="592" alt="Screenshot 2024-03-08 at 11 48 54 AM" src="https://github.com/Giveth/giveth-planning/assets/4855928/853dcf5c-14cd-4e81-b9bd-81fe22d5a8c0">


Maybe something like this would work? @divine-comedian @krmet

**Comment by krmet** [comment]
Thanks looping me in @oyealmond I think the entry criteria for subscribed less than 1 day ago should work. 

I want to test it but am not able to make changes in the preference centre. Can you upgrade my permission please? @ahmadabugosh @divine-comedian

**Comment by oyealmond** [comment]
@ahmadabugosh @krmet  
Got it. Let's move this to Notion please. Closing this issue https://www.notion.so/giveth/Create-Giveth-onboarding-sequence-98a164902bc04b3ca1092a1940b03bc3?pvs=4
