### ISSUE TITLE
p3 - Celo should list Giveth as a dapp integration in their docs... i think we can make a PR

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#1745]
Add Giveth here
https://docs.celo.org/integration/dapps#-bridges

**Comment by oyealmond** [comment]
@divine-comedian do you understand this issue? Who manages our documentation now? Or we don't have someone?

**Comment by divine-comedian** [comment]
This is for CELO's documentation not ours, no idea about this issue

**Comment by oyealmond** [comment]
maybe @SnakeGH could dig into this?
