### ISSUE TITLE
Team "Blast-off" - Distribution across channels

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#175]
We should shill/share the medium article and social media campaign in a bunch of channels. We should to this (1) at launch, and (2) every time we blast out a new medium round-up piece. We'll have different people sharing to different channels so we're not too spammy. Here's the breakdown of who's blasting where:

- [x] Medium @divine-comedian @magentaceiba 
- [x] Reddit @divine-comedian
- [ ] Twitter @magentaceiba (@ForestSoleil to draft tweets)

Discord Servers:
- [x] Metgame @laurenluz 
- [x] TEC @laurenluz 
- [x] Commons stack @laurenluz 
- [x] cadCAD @laurenluz 
- [x] Giveth @laurenluz 
- [x] Diamante Bridge Collective @laurenluz 
- [x] bloom network @WhyldWanderer 
- [x] 1hive @WhyldWanderer 
- [x] MetaSpace @WhyldWanderer 
- [x] Panvala @WhyldWanderer

**Comment by WhyldWanderer** [comment]
reference to https://github.com/Giveth/giveth-planning/issues/178

**Comment by laurenluz** [comment]
Initial blast off complete
