### ISSUE TITLE
Create What's Dappened Medium Post #2

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#176]
Part of our series of end-of-sprint dev update posts

**Comment by laurenluz** [comment]
First draft (copy/pasted from medium so it had aaalmost all the appropriate formatting) ready for review:

https://docs.google.com/document/d/1I5aOo13RX5-gpongPlrKEQeRZW6QG0zDe1qXy7Iv_fY/edit?usp=sharing

@mateodaza be my dev eyes and will review for accuracy.

@Danibelle @divine-comedian @ForestSoleil @WhyldWanderer @magentaceiba - can any of you beautiful people review for consistency, voice and grammar? Please assign yourself if you are taking this on so we don't have redundant reviewers.

**Comment by WhyldWanderer** [comment]
Reviewed! Added some comments... Looks great!

**Comment by laurenluz** [comment]
Thanks @WhyldWanderer and @mateodaza for reviewing! I'll blast this off on Monday so it's 2 weeks after our previous post and we can have it as the focus of our Monday tweet

**Comment by divine-comedian** [comment]
reviewed!

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1384154336846962690

https://medium.com/giveth/what-dappened-march-31-april-14-e8e3513132f7
