### ISSUE TITLE
Create a new flow for feedback collection, categorization, and prioritization.

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#177]
I would like to create a new flow for feedback collection, categorization, and prioritization.
A user shouldnt be expected to create a github account in order to provide feedback.

Also, as we collect feedback, there will be redundant issues and things that are higher priority etc.

It would be awesome to have a typeform or a form that we create within the application that can be integrated with github to create issues with correct labels for which department the issue is geared toward.

Maybe we even have a seperate repo for all feedback issues collected by the form?
I would even be willing to take responsibility for keeping the repo monitored, organized and streamlined.
We will also be collecting form information for GIVBacks upon launch and these forms could then be sent to this repo as well?

**Comment by WhyldWanderer** [comment]
We could use something like this for integration. It says its free for developers... https://pipedream.com/apps/github/integrations/typeform

Otherwise I know of zapier that allows for integration but its a paid subscription. And there could be other options that Im unaware of. https://zapier.com/apps/typeform/integrations/github

**Comment by WhyldWanderer** [comment]
What do you think @geleeroyale @jamespfarrell @mateodaza @markoprljic?

Or maybe there is a way to connect the typeform with a discord channel? I dont know how much control we would have over labelling etc. that way though.
The dream would be to collect the feedback and trigger github issues with correct labels if necessary, solicit direct help from someone on the team or maybe some type of suggestion box...

We could ask questions to categorize things like:
Technical or critical problems such as donation missing etc
Are you reporting an issue or a bug?
Feature requests
Design feedback
Suggestion box

**Comment by ForestSoleil** [comment]
@Ashley, I recommend you assign this issue to one of the devs to flag it for their response.

**Comment by geleeroyale** [comment]
1 - There is the **contact us** form which will pipe any input directly into the #support channel on discord
2 - We are working on having a support chat widget on the site that would allow any user (even without a discord account) to directly chat with #support
3 - I just left a similar response including suggestions in https://github.com/Giveth/giveth-2/issues/421

**Comment by WhyldWanderer** [comment]
I see a big difference as well... support chat would be for assisting people who are unable to complete the project creation or donation flow. Essentially, these would be people who needed help with something in the moment.
Where as the contact us or provide feedback form would be for things more like feature requests or small bugs/ design issues, etc. 

The contact us form could be made a bit more dynamic and it could be useful to look into the different triggers and actions available for the integrations. if someone were to report a bug, it could trigger a github issue but if they are requesting a feature, maybe it goes to an appropriate discord channel?

**Comment by WhyldWanderer** [comment]
I have pinpointed 5 reasons why people would want to contact us so that we can start to figure out the best tools and best practices to use. Here is my suggestion for an ideal situation..

Reasons people would provide feedback or need to contact us:

**Problem with project creation flow or urgent need of support**
-Chat support widget

**Report a bug or issue (UX/UI, txn issues, hearts not working, etc** 
-Form that triggers an appropriately labelled issue in github

**Request a new feature**
-Form that triggers a message in a ‘#requested features’ channel in discord?
-Form that triggers an appropriately labelled issue in github?

**General inquiries**
-Form that triggers a message in a ‘#feedback’ channel in discord?

**General suggestions or feedback**
-Form that triggers a message in a ‘#feedback’ channel in discord?

If there are any other use cases you can think of, we can add them as well....

**Comment by markoprljic** [comment]
I'd like to think about of all possible way to improve our product to reduce the need for support to the minimum (except for third party dependencies such as tx problems or just technical issues). This is why we all should prioritize UX and usability.

**Comment by ForestSoleil** [comment]
Amazing, Ashley! Love your suggestions! Is the suggestion to have both a live chat support widget and also 1 typeform with categories/questions that guide the user toward one of the reasons and associated triggers you mention here? If so, I agree!

**Comment by Jen-Xxx** [comment]
Hi guys, i hope i'm not to late with my reply. Here my 5 cents: I think its a great idea to not have to create a github account to just report an issue/feedback etc. It should be as quick and easy as possible for users to give feedback, right? Having said this, it seems simple enough to use the contact form on the website for website issues. But what do I do if i have questions about the structure of the team, the team itself,responsibilities, or all things that are not website related? If the contact form would be used for those issues as well, it would make sense to feed it into a different channel. I like the idea that the form on the website could feed into a "feedback" channel- it would make things maybe better/more efficiently organised and maybe quicker to take care off?

**Comment by geleeroyale** [comment]
I would like to push this to the next level so we can code it up for our users. Apart from what we have here I think we should do the following:

Put individual support methods like the **contact form** and **make github issue button** in their respective places where they make sense, but also make **a new support page** where we group all of them together with the typeform flow as suggested above - in that way people can see at a glance what options are available?

**Comment by markoprljic** [comment]
Good suggestion, this calls for a dedicated Support page.

**Comment by WhyldWanderer** [comment]
ive been playing with the github and discord integrations on the typeform. And I have been able to successfully trigger github issues with correct labelling and discord messages in one of my play servers

The thing that Im learning is that the trigger happens when the form is submitted therefore it is impossible (as far as i know) to have multiple triggers from one form.

On the contact page (and throughout the site where applicable) we can have use of  4 different buttons for 

Request Feature
Issue or Bug
Inquiries that require a response
General Suggestions/Feedback

Each button would trigger a small popup form with one or two questions and once that is submitted it will trigger the desired outcome.

Request Feature - trigger github issue with Requested Feature Label
Issue or Bug - trigger github issue with Bug label
Inquiries that require a response can go to a discord channel or to an email address
General Suggestions or feedback can go into a 'feedback' channel on our discord

we wouldnt even need any logic within the forms and having seperate forms will allow us to use them in the areas that they are relevant to the application.. like request a feature could be used in one of our banners where the user can then quickly and easily request a feature without having to move through a longer form flow.. 

just 4 different very simple forms that trigger different things

![image](https://user-images.githubusercontent.com/74267818/117213984-911bb800-adb9-11eb-9381-8f1e481e8b4d.png)

![image](https://user-images.githubusercontent.com/74267818/117214072-9973f300-adb9-11eb-8c76-e919e5714c2b.png)

**Comment by WhyldWanderer** [comment]
I made a super quick 'mock up' of what the contact page can look like.

@laurenluz and I have been chatting about ways that we can have consistancy across contact, join, and about us pages....

![Uploading contact.jpg…]()

**Comment by markoprljic** [comment]
I like your ideas @WhyldWanderer. I think this could work really well. I don't have objections to implementing this.
