### ISSUE TITLE
Implement New Autopilot journey for project created email flow

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#179]
@divine-comedian created this journey:
https://app.autopilothq.com/#autopilot/draft/campaign_3286E674-DA94-431F-89D4-6250960CCD22

This issue is for comments/feedback.

@laurenluz reviewing

**Comment by laurenluz** [comment]
Some questions/comments: 

- What's the purpose of having 2 different email as options after project creation? I think "project created" is better and more clear.
-I like the email after 2 weeks suggesting a project update. I think we should also include confirmation emails after a project has performed an update that also suggests that they share to social media.
- Maybe we should also include update checks before the 3 and 9 month emails.
- What happens after 9 months? If we're not going to be sending more emails after 9 months, perhaps the final emails should say something about that?
- I think project updates should reset an email journey so that we keep interacting with the users that are interacting with us.

**Comment by divine-comedian** [comment]
thanks for the suggestions! I'll look into what is possible for programming our journeys. Hopefully we can get segment and autopilot to play nice soon (they are not atm) and then this should be a breeze.
