### ISSUE TITLE
Design/suggest opening and closing slides for Giveth How-To Videos

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#180]
This is related to #159 and #160

@markoprljic can you help with a simple idea for the beginning and ending slides for these how-to videos. 

Would love:

- dark background & light text
- Subtext for 1: "How to Donate" - otherwise, can have the Giveth logo or some other imagery.. would be nice if it also said Giveth.io somewhere
- Subtext for 2: "How to Make a Quality Project" - same image/idea as the previous slide (this will be for the second video)
- Subtext for 3: "Thanks for Watching" (this will be the ending slide for both videos)

@Danibelle tagging you in case you also have some feedback you'd like to add

**Comment by markoprljic** [comment]
@laurenluz See suggestions...
I'm still playing with the brand and exploring. These are the colors and style I'm leaning towards unless I come up with something new in the meantime :D :D :D  

![Image 2021-04-27 at 7 37 05 pm](https://user-images.githubusercontent.com/5704285/116286920-12f35c00-a790-11eb-8124-f5639aaec1b3.jpg)

**Comment by geleeroyale** [comment]
Want to point you guys towards our great [sonic logo](https://brand.iheart.com/sonic-logo) made by Joshua some while back -> [Giveth sonic logo](https://drive.google.com/file/d/1UReHcAPNrKOjOAeDrnwSYYhldfz3g28a/view?usp=sharing)

**Comment by markoprljic** [comment]
We're gonna do a new one 🙂
Thanks Kay!

**Comment by laurenluz** [comment]
@markoprljic are you happy with these designs? I am, and would be happy to close this issue :)

**Comment by markoprljic** [comment]
Yeah, let's use those.
