### ISSUE TITLE
Add updates to the Giveth Project on giveth.io

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#181]
I think that weve made soo much progress and I would love to share it on our project page on giveth.io.

We can even add some of the highlights from the whats dappening posts and maybe a link to the medium where they can see all of the updates.

@Danibelle, you are the project owner for this one so Im assigning this issue to you. <3

**Comment by geleeroyale** [comment]
These updates are taking way too long as well! We should aim for at least once per month

**Comment by laurenluz** [comment]
I think it's a great idea to simply add the what's dappened posts. I'm writing them anyway and I'm including updates on giveth.io and a little bit of general/design/comms stuff. We just need external links from project descriptions to be working and someone to be committed to regularly going in an updating them..

https://medium.com/giveth/what-dappened-march-17-31-3f5f201bfbf3

https://medium.com/giveth/what-dappened-march-31-april-14-e8e3513132f7

https://medium.com/giveth/what-dappened-april-21-may-5-f918958e403e

**Comment by WhyldWanderer** [comment]
Now that we have rich text capabilities, it would be great to get some nice updates on the project.

@Danibelle do you need support with this?

**Comment by laurenluz** [comment]
@Danibelle can you update this? or can we transfer ownership to @WhyldWanderer or someone who has more energy for this? it's still not updated.

**Comment by laurenluz** [comment]
Hey @Danibelle I'd like to take ownership of the giveth project on io to update it and add regular updates, cool w you?

**Comment by laurenluz** [comment]
ok Dani yes ok! @mateodaza can you give me the power?

**Comment by laurenluz** [comment]
any objections? @WhyldWanderer @divine-comedian @Danibelle 

https://giveth.io/project/the-giveth-community-of-makers

**Comment by laurenluz** [comment]
This is the google doc if you want to suggest changes.

https://docs.google.com/document/d/1ufoSW6wFNht32CylUPCu7yYOBUw7n55jIRCQGX_VYU4/edit#

**Comment by divine-comedian** [comment]
Reviewed! Looks good
