### ISSUE TITLE
Update the Giveth 2 campaign description on TRACE

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#182]
I was looking at TRACE and realized that our info is outdated in the campaign description for Giveth 2 on TRACE.
The links arent as relevant and some things have changed since the campaign was created.
It would be fantastic to get those all up to speed.
https://beta.giveth.io/campaign/giveth-2

@willyogo, you are the campaign manager on this one so Im assigning this to you.
Let me know if I can help in any way. <3

**Comment by willyogo** [comment]
Ah yes thanks for calling this out @WhyldWanderer, happy to get this updated!

**Comment by laurenluz** [comment]
Hey @willyogo - this is still out of date - can you update it?

**Comment by Danibelle** [comment]
I am the Campaign Manager for the Giveth 2 Campaign on Trace and have updated the description - https://trace.giveth.io/campaign/giveth-2

@laurenluz feel free to review and let me know if you see anything that needs to be revised!

**Comment by laurenluz** [comment]
Hey Dani! Thanks for doing the update! I read it over, found some things and decided to do quick QA so I copy/pasted into google and made suggestions.

https://docs.google.com/document/d/1g2UUI0artMFbRwMDOowybreOP6pjfqjpgoiA5_XM5EI/edit

Please review and update :)

**Comment by laurenluz** [comment]
looks like you fixed it up! Thanks @Danibelle 

https://trace.giveth.io/campaign/giveth-2
