### ISSUE TITLE
Reach out to suggested groups in DMs for partner/press outreach

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#183]
From @magentaceiba in discord:
"Here are some of the orgs that might be good to reach out to in a not salesy but an inviting way. DM's on twitter tend to get the best responsiveness, however, only the first two groups here have open twitter dm's. A template email to them could be the best thing. I just don't have the headspace to write that right now. It could be a modified email from the one you sent to projects directly. Most of the groups below are coalitions or groups that do small grants."

From @Danibelle in discord:
"Ohh hmm thanks @magenta great new contributor task perhaps with some coordination from @WhyldWanderer on outreach..  I think we have some good contacts to help reach most of these, and there's a few people i wouldn't do a template email but personal intro letter to find out who is the best person to collaborate with so we can tag them personally too if it fits"

Let's reach out as a team in the appropriate way. Assigning folks appropriately... The ones with no owner are up for grabs/open to suggestions.

- [x] Permaculture Action Network - on twitter (their project is on giveth) - https://twitter.com/PermaAction @laurenluz 
- [x] Anne Connelly - Trust (graphic novel) -(their project is on giveth) - https://twitter.com/Anne_Connelly @laurenluz 
- [ ] Thriving Resilient Communities Collaboratory - https://thrivingresilience.org/  @WhyldWanderer 
- [ ] Pollination Project- https://thepollinationproject.org/ - https://twitter.com/Pollinationproj 
- [ ] Awesome Foundation - https://www.awesomefoundation.org/en - https://twitter.com/awesomefound 
- [ ] New Economy Coalition- https://neweconomy.net/ - https://twitter.com/NewEconomics 
- [ ] Norcal Resilience Network - https://norcalresilience.org/  @WhyldWanderer 
- [ ] Allied Media Conference - https://amc.alliedmedia.org/ - https://twitter.com/AlliedMediaConf

**Comment by divine-comedian** [comment]
did you guys end up reaching out to all of these groups?

**Comment by laurenluz** [comment]
no... only the ones that are checked off
