### ISSUE TITLE
Weekly twitter planning

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#184]
Wanting to create an organized flow for twitter. Forked this from the Commons Stack for planning and started planning the week here:

https://docs.google.com/spreadsheets/d/1Es1ZhOzsRnZW3IBNPEwQqQhQFYty6FJY0AtU08I06tk/edit#gid=2089041821

Details:

- Month tabs (May, June, etc.): for planning the week and scheduling tweets for flow
- Idea log: for list-form ideas/things we can tweet about
- To be Scheduled: list of drafted tweets, memes, status, author
- Evergreen content: for blog posts/youtube videos/talks/etc that are "forever green" i.e. can be tweeted about at any time

Please feel free to contribute to this doc to add info the flow of tweets. Would also appreciate QA/review on drafts as well.

FYI info on voice, useful tips, etc. can be found here: https://docs.google.com/document/d/1e1oBAUN4KoppGFC7fN8j1vGPw4xpmXsj-GGzJIlrzaE/edit

@magentaceiba @Danibelle @divine-comedian @WhyldWanderer @ForestSoleil - please un-assign yourself after you review the info and feel free come back to this issue later with comments

**Comment by divine-comedian** [comment]
Looks great Lauren, very well thought out!

**Comment by laurenluz** [comment]
Moving this to done, and I'll close it soon if there are no objections to clean up the board. Just a reminder that we also now how have a twitter channel in discord where you can also share you ideas, tweets or other twitter-related tingz

**Comment by ForestSoleil** [comment]
Looks good to me!

**Comment by laurenluz** [comment]
closing this, got it covered in the doc and twitter channel
