### ISSUE TITLE
Wiki--> Docs: Communications>Intro to Communications

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#186]
The original wiki page: https://wiki.giveth.io/communications/

The HackMD Document: https://hackmd.io/4aqlBkCPRLykHA0CICee5Q

**Comment by WhyldWanderer** [comment]
Finished! Ready for QA and integration into the docs.

**Comment by laurenluz** [comment]
Edits look good - I honestly didn't have anything to say/add/change

**Comment by ForestSoleil** [comment]
Looks awesome, Ashley! Approved from my end.

**Comment by laurenluz** [comment]
added a lil' comment

**Comment by WhyldWanderer** [comment]
@laurenluz I left comments on your comment... :P

**Comment by laurenluz** [comment]
comments have been integrated. preparing for lift-off 🚀

**Comment by ForestSoleil** [comment]
Are we closing these issues when draft, QA review & edits integration has been completed? Or are we waiting until all of the docs have actually be migrated online and published?

**Comment by WhyldWanderer** [comment]
I think there was confusion about this earlier as well.
Mitch was closing them as he added the info into contentful but the thing we ran into is that some of them are connected to one another and as edits are made in the other issues/documents, some of the finished ones might need small edits to reflect what was changed.
Im not sure what the final descision was on the flow of closing issues.

**Comment by ForestSoleil** [comment]
@divine-comedian @laurenluz what do you think?

**Comment by laurenluz** [comment]
we're holding off closing issues until all parts are ready to be put up officially on the docs . they should only be closed when they are fully done, i.e. live on Giveth docs.

it's exactly because of what Ashley mentioned.... because small changes (or in some cases, bigger changes) come up as we go through the process of editing other sections.

**Comment by divine-comedian** [comment]
@WhyldWanderer  let me know when this one is ready to go!

**Comment by WhyldWanderer** [comment]
Its ready @divine-comedian

**Comment by divine-comedian** [comment]
done!
