### ISSUE TITLE
Wiki--> Docs: Communications>Documentation and Tutorials>Use of Riot

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#187]
Original Wiki page: https://wiki.giveth.io/communications/riot-migration/

HackMD Document: https://hackmd.io/8NVdNYUhTUOOwSOpuFdG9w

**Comment by WhyldWanderer** [comment]
Related to https://github.com/Giveth/giveth-2/issues/887

**Comment by WhyldWanderer** [comment]
Finally! I think I feel like I can call this one done! 
Ready for review... Please take a look and tell me what you think..

The one thing that I am missing is a description of the @Unicorn role..
I have reached out for advice from Kay and Dani..
Kay says we could use the word family here
Still waiting to hear Danis description...

I think we need to have 
1. A description of the role
2. What a new user needs to do to acquire that role

Let me know if you guys have any ideas... thx.

**Comment by divine-comedian** [comment]
Reviewed! Left comments and fixed some punctuation and markdown editing. 

I threw in some documented functions for discord bots into `code` brackets to make them more distinct in the doc, feel free to remove them if you don't like the look.

**Comment by laurenluz** [comment]
nice job Ashley, this is really good. I made a bunch of comments, edits using strikethroughs, and just took the liberty to make spelling fixed directly in the doc.

**Comment by WhyldWanderer** [comment]
Im not sure why i closed this issue.... I dont see this document live on the docs yet.. oops
Reopening so that we can get it live.

**Comment by divine-comedian** [comment]
I don't think the message was sent that the QA was finished and that it is ready for upload

**Comment by WhyldWanderer** [comment]
no worries.. it was my bad. 
I dont think i communicated it clearly and i have no idea why i closed the issue...

**Comment by divine-comedian** [comment]
so it is ready to go?? 

at this link - https://hackmd.io/8NVdNYUhTUOOwSOpuFdG9w

**Comment by WhyldWanderer** [comment]
YES!

**Comment by divine-comedian** [comment]
okay! I added it and merged! should be live soon - https://github.com/Giveth/giveth-docs/pull/31
