### ISSUE TITLE
Wiki --> Docs: What is Giveth & Mission, Vision and Values (formerly "about the Giveth DAC" and "mission")

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#188]
hackMD: https://hackmd.io/cXxKup9_REe2vCxaoLRedw

original wiki: https://wiki.giveth.io/dac/ & https://wiki.giveth.io/dac/mission/

original docs: https://docs.giveth.io/whatisgiveth/

**Comment by laurenluz** [comment]
@divine-comedian @WhyldWanderer @ForestSoleil 

1st draft FINALLY ready for review - thanks to all of your help :)

https://hackmd.io/cXxKup9_REe2vCxaoLRedw?both

**Comment by WhyldWanderer** [comment]
This is looking so awesome! Great job to everyone in the hack session. I only found one grammatical change which I left in the comments of the HackMD.

**Comment by ForestSoleil** [comment]
Awesome, I have reviewed again and made several relatively small/medium sized edits. Mostly around typos, punctuation and updating verbiage so that we are not using the same terms in consecutive sentences/paragraphs.

**Comment by laurenluz** [comment]
Thanks team! I just went in and accepted your changes - I think it's looking awesome 😍

**Comment by laurenluz** [comment]
the vision and values here are complete, we need to finalize the Giveth mission before we can push this live

**Comment by ForestSoleil** [comment]
Yes, and decide where we want to save our KPIs if we keep them internal since they'll frequently be adapted I imagine.
@divine-comedian I'm curious if you and Moe Nick spoke in more detail about that?

**Comment by divine-comedian** [comment]
No, we're going to hack wednesday and get some calrity. My immediate thoughts is that notion would probably be the best place to keep track of our KPI's for each circle, recording each iteration and building new KPI's as we continue to grow.

**Comment by WhyldWanderer** [comment]
Just missing the Mission... we are almost there guys!
@ForestSoleil has there been anything discussed or scheduled for mission statement workshops with @willyogo or @markoprljic?

**Comment by ForestSoleil** [comment]
Willy sent out a doodle poll today for the overall giveth mission quest this weekend.

**Comment by laurenluz** [comment]
pushed the mission live!
