### ISSUE TITLE
GIVbacks program documentation for Giveth Docs

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#189]

**Comment by ForestSoleil** [comment]
Who did we assign for this? Or has it not yet been assigned? 
@divine-comedian @WhyldWanderer @laurenluz @Danibelle

**Comment by laurenluz** [comment]
I think we can simply adapt #191 once it is written and throw it into the docs. We're going to be totally revamping the docs anyway

**Comment by WhyldWanderer** [comment]
I agree with Lauren on this one... its essentially the same information. Just maybe will need a change in voice.

**Comment by laurenluz** [comment]
#142 is the relevant related issue. I closed #191 due to redundancy
