### ISSUE TITLE
GIVdrop Medium post

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#190]

**Comment by laurenluz** [comment]
Working on this here: https://docs.google.com/document/d/1LUmQZZGF4HLC_w4UNKphzVfhjYR9mW2V9re3tULyelc/edit

Will let you know when it is ready to review (not yet 😉)

**Comment by laurenluz** [comment]
@divine-comedian @WhyldWanderer @ForestSoleil 

I read this over again, I think it's good and not likely to have to change before lanunch. Video's locked in, I think we're safe to do some QA on this too. Can I get one of you to dive in?

**Comment by WhyldWanderer** [comment]
Wow Lauren! It looks really awesome! I left a few suggestions..

Some things I noticed that are still missing:
Token Addresses
Links

**Comment by laurenluz** [comment]
Thanks Ashley!
