### ISSUE TITLE
Wiki --> Docs: Governance > Intro to Giveth Governance

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#204]
Original wiki page: https://wiki.giveth.io/governance/ 

HackMD Document: https://hackmd.io/@ReForest/BJQnjNlKO/edit 

5/17 - Just transferred copy as is over to HackMD. Currently making edits in line. Will comment here again when it's ready for review.

**Comment by ForestSoleil** [comment]
This page has been fully edited and is ready for QA review! 
@laurenluz @WhyldWanderer @Danibelle @divine-comedian 

If the simple poll confirms we are moving from DAC to Community, I'll make that adjustment.

**Comment by divine-comedian** [comment]
Reviewed! Added comments and strikethrough on suggested omissions with suggestions next to them. 

Nice work! :+1:

**Comment by laurenluz** [comment]
I like Mitch's suggestions. Added a few more. Nice job, Forest :)

**Comment by ForestSoleil** [comment]
Edits have been integrated. Thanks y'all!

**Comment by divine-comedian** [comment]
ping me @ForestSoleil  when this is ready to go! Also this doc is Intro to Giveth Governance or simply 'Giveth Governance'?

**Comment by ForestSoleil** [comment]
This beast is finally done and ready for QA! https://hackmd.io/nb9s-1xnSW6C8n6nZs-chw

@divine-comedian @laurenluz @WhyldWanderer  =)

**Comment by WhyldWanderer** [comment]
wait.. im confused. I see two different documents in this issue. 
One for Intro to Giveth Governance and one for Meetings guide.

**Comment by divine-comedian** [comment]
@ForestSoleil  you dropped the wrong link! 

> This beast is finally done and ready for QA! https://hackmd.io/nb9s-1xnSW6C8n6nZs-chw
> 
> @divine-comedian @laurenluz @WhyldWanderer =)

**Comment by ForestSoleil** [comment]
I did not drop the wrong link. Lauren and I incorporated the meeting recordings guide with the governance of meetings and called it the Meetings Guide. This is correct; please QA - https://hackmd.io/nb9s-1xnSW6C8n6nZs-chw

**Comment by WhyldWanderer** [comment]
Oh okay... What about the Intro to Governance documentation in the very first post above? Is that one finished and ready to go?

**Comment by divine-comedian** [comment]
the link you dropped at the beginning of this issue is the intro to the governance circle which to my understanding is not the same article as governance of meetings/ meetings recordings guide,

**Comment by ForestSoleil** [comment]
Okay I just re-reviewed and made some updates to links. It's ready to go. Sorry for initial confusion with two different governance page links. https://hackmd.io/LcrbZvagQ_CYB3o7Iipezw
@divine-comedian

**Comment by divine-comedian** [comment]
DONE
