### ISSUE TITLE
Wiki --> Docs: Governance > Job Openings

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#205]
Original wiki page: https://wiki.giveth.io/governance/jobs/

HackMD Document: https://hackmd.io/@ReForest/HkV9pSgtu/edit

READY FOR QA!
@laurenluz @divine-comedian @WhyldWanderer @Danibelle

**Comment by divine-comedian** [comment]
Reviewed! Left some comments. 
I striked out suggested omissions and added suggestions next to them or in the comments

Nice work!

**Comment by laurenluz** [comment]
this is done?

**Comment by ForestSoleil** [comment]
Yes, I just added the Backend Developer positiong to the bottom. Does anyone know how to make a thing at the top where it highlights the roles and when you click on them it takes you directly to that part of the page?

Lead Solidity Developer
Backend Developer

**Comment by divine-comedian** [comment]
done! I split this into two separate documents and they will live in the jobs tab on the giveth docs

**Comment by ForestSoleil** [comment]
Thanks so much @divine-comedian besitos!
