### ISSUE TITLE
Wiki --> Docs: Governance > Documentation and Tutorials > Meetings Guide

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#206]
Original Wiki link: https://wiki.giveth.io/dac/contributors-guide/

Updated HackMD doc: https://hackmd.io/@ReForest/B1-sZ8gKd/edit

Work in progress - still editing; NOT yet ready for review.

**Comment by laurenluz** [comment]
hey Forest - when do you think you'll be done this one?

**Comment by ForestSoleil** [comment]
I hacked on this today. It's a work in progress. I hope to finish up more in the morning before our comms hack session. 
Ashley & Dani are connecting on how to reward contributors. I've created a placeholder section for that here.
Also added a page break and the Contributor Covenant Code of Conduct. Do we like how that's formatted here or prefer a separate page for that? 
https://hackmd.io/Lk3X4BF9SUqa7bh_He_w4A

**Comment by ForestSoleil** [comment]
Ready for QA: https://hackmd.io/Lk3X4BF9SUqa7bh_He_w4A

**Comment by divine-comedian** [comment]
left comments Forest! Need some more polish but it's lookin' good!

**Comment by ForestSoleil** [comment]
Now that we figured out the confusion around governance links.... =) 
I re-reviewed, implemented your feed-forward @divine-comedian and this is ready to publish if it hasn't already gone live. https://hackmd.io/nb9s-1xnSW6C8n6nZs-chw

**Comment by laurenluz** [comment]
hey @divine-comedian - this one is ready to go live.

can you close the issue after you push it up?

**Comment by laurenluz** [comment]
it's this, btw: https://hackmd.io/nb9s-1xnSW6C8n6nZs-chw

**Comment by WhyldWanderer** [comment]
Has this gone live @divine-comedian? I dont see it in the tree structure...
Just for clarity, im referring to the meetings guide here: https://hackmd.io/nb9s-1xnSW6C8n6nZs-chw

**Comment by WhyldWanderer** [comment]
LIVE: https://docs.giveth.io/whatisgiveth/meetingsGuide
