### ISSUE TITLE
User Feedback: Torus wallet users unclear on what is an eth address

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#207]
I've gotten this question twice. Users (unfamiliar with crypto) are not sure what an eth address is, why it is autofilled, where the donations go in the end, etc.

I imagine that this is mainly Torus users... they just sign in with their social media, click "yes yes yes" and then wonder what that is. They don't even know to check app.tor.us for access to the wallet.

Maybe we can add a little "what is this?" under the "set eth address" with a popup that explains. That's my first idea. Would love feedback @WhyldWanderer @divine-comedian @ForestSoleil @Danibelle 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a7037b7b-9d80-4975-9f59-c4d692e320b5)

**Comment by divine-comedian** [comment]
![image](https://user-images.githubusercontent.com/67759413/118684523-4bef8100-b7d0-11eb-925f-22522a471a05.png)

Maybe we can link them to some ethereum resources - https://ethereum.org/en/wallets/

I had a quick glance at the torus documentation and it is NOT beginner friendly. 
a long term solution I propose is to draft some documentation for our docs that we can link to. I'm willing to take this on to make a first draft

**Comment by laurenluz** [comment]
I totally agree 👀 It didn't hit me before, but yeah, we are doing somewhat of a disservice by making it too easy to create a wallet.

I think for a short term solution, yeah, let's add a "what is this?" write up a little explanation and add in the link to that ethereum wallet explanation... I can do this.

Would love it if you want to draft some Torus documentation for the docs @divine-comedian - you want to make some issues for this?

**Comment by divine-comedian** [comment]
Yup! I'll make an issue

**Comment by laurenluz** [comment]
Wrote text for the popup and made an issue for the devs: https://github.com/Giveth/giveth-2/issues/884
