### ISSUE TITLE
Wiki Migration - Making Traces (formerly how to make milestones)

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#209]
Making Traces first draft ready for review - 

https://hackmd.io/IqQgjPz4RW2cU8IngPNFNg

@laurenluz @forestsoleil @whyldwanderer

**Comment by WhyldWanderer** [comment]
I reviewed this and left some comments in the doc. It looks really good Mitch! way to streamline and bring everything up to date!..

**Comment by MoeNick** [comment]
@horus2021 would u pls take a look at the doc.
