### ISSUE TITLE
Get the Wiki ready for launch

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-planning#21]
_This came up at community meeting of 08/30/2020_

**Comment:** Lots of the Wiki needs updating. The current implementation is a little cumbersome for editors. I would be down to set up [Docusaurus2](https://v2.docusaurus.io/) which is the current standard for documentation, much better for contributors to handle as it features better UX and it gets free CI via GitHub pages.

In order to not break any links we could import the old Wiki into the new one, but should mark the entries in their info as being deprecated.

**Comment by laurenluz** [comment]
#185
