### ISSUE TITLE
Wiki Migration - Exchange rates

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#210]
Exchange Rates document first draft ready for review 

https://hackmd.io/n8CpqlIUTCSUOkbGptADxQ

@laurenluz @forestsoleil @whyldwanderer

**Comment by WhyldWanderer** [comment]
Reviewed!
I left comments in the document...

**Comment by MoeNick** [comment]
I left some comments.
pls see this json: we support these currencies.
https://feathers.beta.giveth.io/whitelist
