### ISSUE TITLE
Wiki Migration - Development Process

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#211]
Updated doc for Giveth TRACE development process
first draft ready for review - https://hackmd.io/kj_C5WjBRwKvWsnTG66hdQ?view

@laurenluz @forestsoleil @whyldwanderer

**Comment by WhyldWanderer** [comment]
Great work @divine-comedianI I have reviewed it and left some small fixes/comments in the document.

I think it would be a good idea to also have a technical review from @MoeNick or @aminlatifi to ensure that the information is correct because I am unfamiliar with the development side.

**Comment by MoeNick** [comment]
I left some comments.
pls see this json: we support these currencies. 
https://feathers.beta.giveth.io/whitelist
