### ISSUE TITLE
Wiki Migration - Giveth Bridge Security Implementation

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#212]
Following an update with Griff The two sections 'Deployments' and 'Smart Contract Roadmap' are fully deprecated. 

Proposing this doc in place - https://hackmd.io/aR7SQK6KQA6AUo0azVJ57w
first draft ready for review

@laurenluz @WhyldWanderer  @forestsoleil

**Comment by laurenluz** [comment]
is it really called a "ghetto bridge server"?

**Comment by laurenluz** [comment]
the last section... the "possible security issues"... needs a lot of edits. it's written really informally. 

it also has a lot of run on sentences and the use of just unprofessional wording like "this is a very very..."

I left a couple of comments but not quite up to my satisfaction. I can go in and hack but I'm actually not entirely sure what these security issues are and it's hard to understand them from the doc. Also just want to check in w you first.
