### ISSUE TITLE
Wiki Migration - Intro to Giveth TRACE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#214]
updating documentation for migration to giveth docs
Intro to Giveth TRACE (formerly intro to Giveth DApp) first draft ready for review 
https://hackmd.io/1XYSLZTETTS17OJDzeNCUw

@laurenluz @WhyldWanderer @ForestSoleil

**Comment by MoeNick** [comment]
Thanks @divine-comedian , I left some comments 
About the whole context, I think we can use more marketing stuff of maybe attractive slogans etc, showing the purpose of this platform and its differentiation with  io .... focusing on Traceability, Transparency and Community-based economy...

**Comment by WhyldWanderer** [comment]
Reviewed and left comments in the doc! Looks good...

**Comment by WhyldWanderer** [comment]
> showing the purpose of this platform and its differentiation with io
We could link to the medium post describing the differences somewhere ini this document...

Or even better!.. we just have a DApp Development Circle page where we talk about how our DApp development circle is structured with a bit about each platform.. Here we can state the primary and secondary goals of the circle as well as link to the medium post that mitch wrote. 

From there it would break into a Giveth TRACE section and a Giveth.io section with the intros to each.

**Comment by divine-comedian** [comment]
I'm planning to have a page in the same section where we outline our other circles that will cover those points both of you just mentioned @MoeNick  and @WhyldWanderer with regard to each DApp, taking some cues from the article you linked above. Then point the user to our separate section for Giveth TRACE documentation
