### ISSUE TITLE
Enhance documentation for Torus Wallet

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#215]
relating to issue #207 
Building on and consolidate documentation for Torus Wallet on the giveth docs. Explain or link to an explanation what an eth address is. Following previous discussion we should actively encourages users to do a base amount of research and give them the knowledge to understand what torus wallet does and how their funds are stored.

**Comment by divine-comedian** [comment]
Torus Wallet documentation draft ready for review :point_down: 

https://hackmd.io/t55ptAMdQwuTdk01ckadRg

@WhyldWanderer  @laurenluz @ForestSoleil

**Comment by WhyldWanderer** [comment]
Reviewed! I left comments in the HackMD document.
Thanks for taking this on Mitch! I think it will prove to be very useful to people who know nothing about crytpo.

**Comment by ForestSoleil** [comment]
^ That's all I needed to hear, Ashley! haha reviewing now....and hoping to learn a thing or two! LOL

**Comment by ForestSoleil** [comment]
Looks great, Mitch! Made some minor edits directly and left 2 or so comments.

**Comment by divine-comedian** [comment]
awesome! thank you all for reviewing! suggestions have been incorporated

**Comment by laurenluz** [comment]
Nice job Mitch. I made a bunch of edits as strikethroughs and a few comments. I noticed actually that on giveth.io "My Wallet" links to etherscan... not to Torus... so I adjusted that as well in your doc.
