### ISSUE TITLE
Wiki --> Docs Migration: Intro to DApp Development

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#216]
Each of the other circles have a general introductory sections where we describe what is the circle, how to get involved, and the goals of that circle.

I think this should include:
- general intro
- the differences between TRACE and giveth.io and what they offer
- how to get involved (which channels in discord, when the calls are)
- goals

I added in the goals and started on the top. @divine-comedian you may be the best person to review this.

Original Wiki: https://wiki.giveth.io/dapp/
New Proposal: https://hackmd.io/bB0Yrqw0SE6s8_8-IgYcIA

**Comment by laurenluz** [comment]
1st draft ready for review: https://hackmd.io/bB0Yrqw0SE6s8_8-IgYcIA

@WhyldWanderer @divine-comedian @ForestSoleil

**Comment by WhyldWanderer** [comment]
Reviewed! I dont see any changes to be made. It looks good!

I left a comment regarding channel names in the doc as they may be subject to change. (see https://github.com/Giveth/giveth-2/issues/887)

And Im leaning more towards the blanket 'goals' section rather than the primary secondary format. I like it!

**Comment by divine-comedian** [comment]
left some suggestions! 

I agree with Ashley and the goals look great!

**Comment by laurenluz** [comment]
Thanks for the suggestion's y'all. I put 'em in and we're locked and loaded 💯

**Comment by laurenluz** [comment]
@divine-comedian this one is ready-to-go... just not sure where it should go in the tree structure

**Comment by divine-comedian** [comment]
got it!
