### ISSUE TITLE
Wiki --> Docs Migration: What is Giveth --> Giveth Circles (Formerly Organization & Goals)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#217]
This is a combination of the "organization" and "goals" sections of the wiki

old organization: https://wiki.giveth.io/dac/team-organisation/
old goals: https://wiki.giveth.io/dac/goals/
new: https://hackmd.io/ZH70JRdlSlK-CwUXRSiflw

1st draft ready for review @WhyldWanderer @divine-comedian @ForestSoleil

**Comment by WhyldWanderer** [comment]
I reviewed this and added some comments in the HackMD..

I will get started on the Community Circle section tomorrow!

**Comment by ForestSoleil** [comment]
Reviewed and left some minor comments. Thanks lauren! And thanks for sharing your screen with me to show me how to track my comments visibly in hackmd

**Comment by laurenluz** [comment]
Ok this is looking great - thanks to all you edits. Only waiting on "community goals" from @WhyldWanderer once she makes them 🙏

**Comment by divine-comedian** [comment]
we're still holding off on this one? just curious what/when I can link the mention to this document from the finances one.

**Comment by laurenluz** [comment]
this is ready now

**Comment by laurenluz** [comment]
@WhyldWanderer @ForestSoleil @Danibelle @divine-comedian 

we need to fully update this doc based on the new circles... once you have the goals sections complete, can we add them to the hackMD?

**Comment by ForestSoleil** [comment]
Absolutely! Ashley & I have a HackMD document for Community Circle that we've been working on and we are going to meet tomorrow morning before our comms call to hopefully finish it up. Once that's gone through advice process, then we can replace the old content with new approved stuff in the HackMD link in this issue.

**Comment by divine-comedian** [comment]
I'm going to have a hack session with the devs on monday, - this is the current WIP  - https://docs.google.com/document/d/1tMMYSirmnE6rE7OfhJVEm5Mo4pOlwPBKlDjuFiGEiAk/edit?usp=sharing 

I might migrate this to notion so it can be a more collaborative document

**Comment by WhyldWanderer** [comment]
This is live now right @divine-comedian? can we close this?

**Comment by divine-comedian** [comment]
DONE
