### ISSUE TITLE
Wiki Migration - Finances

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#218]
@Danibelle you mentioned you could tackle this one for the update/migration. Can you let us know when you'll be able to do this?

I started a hackMD and copy/pasted from the old wiki to get you started. 

Old: https://wiki.giveth.io/dac/finances/
New: https://hackmd.io/J8Ji68wfSYeEzoe5r-d9eA

**Comment by laurenluz** [comment]
update: Dani will have this ready by next week Wednesday!  June 9

**Comment by Danibelle** [comment]
Ready!

**Comment by laurenluz** [comment]
looks good Dani - I did some QA.... nothing major, I just edited directly in the doc so you don't have to go through again.

@divine-comedian @WhyldWanderer @ForestSoleil - any of you want to do a final QA?

**Comment by WhyldWanderer** [comment]
Reviewed! It looks good to me... just missing a link to team organization... where was this link intended to direct people?

**Comment by laurenluz** [comment]
Thanks for your QA ladies, I added them in. The "team organization" (now changed to "giveth circles") link will go internally to the docs... to the doc I worked on with circles goals. Let's call this done for now.

@divine-comedian - it's ready to go... the link "giveth circles" goes to the internal doc link of #217

**Comment by divine-comedian** [comment]
got it!
