### ISSUE TITLE
Wiki Migration: History

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#219]
@geleeroyale you volunteered to work on this piece. Can you give us an ETA on when you'll be able to do this part?

I opened a hackMD and copy/pasted the history in there to get it started.

Old: https://wiki.giveth.io/dac/history/
New: https://hackmd.io/OO31TfHoTRWVMBYzd3MzZg

**Comment by geleeroyale** [comment]
Should be ready by next week 😁

**Comment by geleeroyale** [comment]
Not quite finished yet still have to write up a full year

**Comment by laurenluz** [comment]
This is looking so fun Kay! Any idea when it will be ready for QA?

**Comment by geleeroyale** [comment]
Ok - was not able to add too much more as there was a "big break" in 2019. However, the history is now available for review. If there are questions or needed clarification I am happy to expand the content.

https://hackmd.io/@geleeroyale/rJ8oleTKu

**Comment by laurenluz** [comment]
just did some QA - I think it makes sense to also add 2021... the team grew a lot, we launched giveth.io. we're ready to launch TRACE. we're developing the GIV token economy.

Do you want to add that in @geleeroyale ? I think it's nice that it's all in your voice.

Other than that just made some suggestions as strikethrough corrections (mostly grammatical). Also.. were there really no in person gatherings since 2019 until now?

also - @divine-comedian @WhyldWanderer @ForestSoleil this is ready for QA if any of y'all want to be a third pair of eyes

**Comment by geleeroyale** [comment]
Truly - there were no more gatherings - at least official ones. Thanks Covid 🙄

**Comment by divine-comedian** [comment]
left some comments, a very interesting read!

**Comment by ForestSoleil** [comment]
Looks awesome Kay! I reviewed completely and made some edits in line. =)

**Comment by laurenluz** [comment]
hey @geleeroyale can you finish this out? there's a bunch of edits and comments there that need to be incorporated. if you need support, let us know in the comms channel.

**Comment by geleeroyale** [comment]
Thanks for the reminder - will try to finish this week!

**Comment by laurenluz** [comment]
@divine-comedian if you could incorporate the feedback that's already in the hackMD and then move it over to google docs and ping us for collaboration/idea generation for what happened since Jan 2021... would be great

**Comment by divine-comedian** [comment]
okay heres a google doc with the hackmd edits incorporated - 

I kept it in the raw MD format for my own sanity later on... 

https://docs.google.com/document/d/1YsXXoyTZ26QcsW-I_ykePD_g-kjQ-JM1xeB1AgmcMdI/edit?usp=sharing

**Comment by divine-comedian** [comment]
here's the doc with some edits, but also the order of events has been reversed - what do you guys think? 

https://docs.google.com/document/d/1T9Q1c0DDUxWVyndrzsunGKgKx5f02jCbtVMnI9JoPXk/edit?usp=sharing

**Comment by ForestSoleil** [comment]
I like the new chronological flow. Thanks Mitch!

**Comment by divine-comedian** [comment]
https://docs.giveth.io/whatisgiveth/history - LIVE

**Comment by laurenluz** [comment]
oh whoa - it's live... I didn't see that. I just finished QA in the google doc

**Comment by divine-comedian** [comment]
> oh whoa - it's live... I didn't see that. I just finished QA in the google doc

no problem! I put it in your edits and just merged it, should be live in a few.
