### ISSUE TITLE
Update JOIN info in wiki (and homepage)

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-planning#22]

**Comment by WhyldWanderer** [comment]
with reference to https://github.com/Giveth/giveth-2/issues/752

**Comment by WhyldWanderer** [comment]
this issue is relevant to https://github.com/Giveth/giveth-2/issues/806

**Comment by laurenluz** [comment]
for updates to join: https://github.com/Giveth/giveth-2/issues/806
for updates to wiki: #185
