### ISSUE TITLE
Wiki Migration - The Advice Process

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#220]
Updated first draft ready for review - https://hackmd.io/UUR-vsmfS0qdvlZp1pgLow
OG Doc - https://wiki.giveth.io/governance/advice-process/

The main shift that I propose in the updated doc is a departure from the idea that in our decentralized organization ANYONE can make a decision and implement it. I think just the implications of that notion is inviting a whole mess of organizational issues, things that right now we are trying to tackle. 

I suggested the advice process then instead becomes part of the proposal making process that is more inclusive and synchronous. There's still quite a lot of excellent content from the old article that I modified.

This document is my proposal and now I can coming to you all in my advice process on the advice process! Have a look please and leave comments and suggestions. 

@WhyldWanderer  @ForestSoleil  @laurenluz

**Comment by WhyldWanderer** [comment]
Reviewed! I left comments in the HackMD document as well as corrected some small punctuation errors.
Great job Mitch!

**Comment by laurenluz** [comment]
I made many notes and revisions 😅 thanks Mitch!

I also noticed that you took out a lot of whole sections from the original wiki... I think it is ok as it is, but I will comb through a little later and make more comments if I have additional suggestions

**Comment by laurenluz** [comment]
Ok I reviewed the old wiki version. Added a couple of sentences, but for the most part I'm aligned with you (Mitch) on what you chose to omit.

**Comment by ForestSoleil** [comment]
First I want to name that I really like how you posted in italics up at the top "(freely adopted from ‘Reinventing Organizations’ by Frédéric Laloux)" - that's a cool way for us to credit the folks who are inventing the tools and processes we've come to adopt, and for readers to have the resources to go deeper down the rabbit hole if they so choose.

Secondly,  great job Mitch!  Very thorough. I read through and edited the HackMD document, leaving my minor edits directly as you requested and through strikethroughs. I left 1 or 2 in line comments. I think this is looking great overall.

**Comment by divine-comedian** [comment]
Okay I took all of your great suggestions and cleaned it up!

**Comment by laurenluz** [comment]
this is ready-to-go, right?

**Comment by divine-comedian** [comment]
Yup!

**Comment by divine-comedian** [comment]
loaded!
