### ISSUE TITLE
Conflict Resolution Documentation

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#221]
This is the OG doc from the wiki - https://wiki.giveth.io/governance/conflict-res/ 
While the RJ system is interesting it is not how conflict resolution is being done currently and rather than re-introduce something that might not be the best fit for what Giveth is now perhaps it's time to consider a new strategy.

Following the discussion among comms team and Juan from TEC Gravity we would like to introduce a new conflict resolution process incorportating the well documented principles and practices of Gravity. 

Gravity WG proposal from the TEC - https://docs.google.com/document/d/1J2Vrlb7zXcnCIWf-xmylCY39bL88PJLibz5AdXy-e2M/edit#heading=h.a6hblvgzwj5q
Gravity WG Manifesto - https://docs.google.com/document/d/1yrEcPoOW8Q1qDE-YWWF0MhXlcvpiMk0jmdQx25nfZ6k/edit#heading=h.4qr126s3qfr1

I would like to see the discussion continue and take some time to agree on what our process is as a community. Oversee its implementation (Gravition training, internal procedures) and then document the final agreement on what the process is.

I'd like to collect more ideas and see what we can borrow from Gravity documentation to create a new conflict resolution doc. 
@Danibelle  @ForestSoleil  @laurenluz @WhyldWanderer

**Comment by JuankBell** [comment]
Thanks for this!

Yeah, im super into updating this process, we could schedule a hack session to receive insights on what can we build, if we want to have gravity as it is in the TEC, or tweaking things for Giveth.

Like, do you want to use the same typeform/registry we use for the cases in the TEC, or use another one.

It would be nice to know what changes are expected, if we want to complement what was done, or start new.

**Comment by Danibelle** [comment]
I think it would be beneficial to look at this the other way around as JuanCa suggests..

What, if anything, would need to be changed in TECs Gravity for implementation with Giveth as a collaborative communities initiative - rather than what can we leverage from Gravity to make our own!

**Comment by laurenluz** [comment]
I'm super happy to be involved in a hack session, I feel really passionate about alternative dispute resolution. maybe we can discuss a little bit in Friday's call and then schedule a working group if needed.

**Comment by ForestSoleil** [comment]
**Restorative Justice -** 
I read the original article. I'm curious why restorative justice is not applicable to Giveth currently? It's a fairly simple and transformative process of ownership communication,  reflective listening and resolution. 

**Gravity -** 
Wow, 14 page long document. This is thorough but also complex in some sections. I found myself getting lost in all the text. My first thought is that this is overcomplicating things. In our documentation, I do not feel we need to publish this amount of detailed information. Rather, a simple step by step process, tools for supporting private negotiation, and link to typeform to request mediation or conciliation. 

I'm interested in being included in this hack session.

**Comment by JuankBell** [comment]
Looking forward what we can build! Sorry forest if you are looking at this [doc](https://docs.google.com/document/d/1J2Vrlb7zXcnCIWf-xmylCY39bL88PJLibz5AdXy-e2M/edit#heading=h.a6hblvgzwj5q), it was the initial document and it needs update. This is the [step by step process we have now](https://forum.tecommons.org/t/gravity-easy-step-by-step/354) and we are working on infographics to connect all the dots. 

My ideas are these:

Gravity offers "certification" for conflict management agents (people visible and trained in the community)
Giveth already has a conflict management system that needs facilitators (with the RJ approach)

I think that Gravity can be iterated and adapted according to the needs of each org.
So We could include RJ into the next Gravity training, and in that way Giveth's Gravitons can continue using that framework.

We have made a typeform and a registry that can be used for various communities, but you could have also your own registry and typeform. They are just tools to promote easy access and accountability

**Comment by ForestSoleil** [comment]
Amazing, @JuankBell! Yes, I was looking at the old document. Thanks for the clarity. I resonate with your suggested plan. 

I am interested in getting certified as a conflict management agent, particularly since I facilitate calls for two of our teams. I have a background in authentic relating and circling, so this is an area of passion and interest for me.

**Comment by WhyldWanderer** [comment]
I would also love to be a part of the Graviton group and trainings. I was able to catch a few of the lessons in the first training section you conducted but wasnt able to be present for them all. I look forward to learning more and building a robust conflict management team for giveth.

**Comment by ForestSoleil** [comment]
Drafting the content for Conflict Resolution is on hold until our Gravity process is more defined and onboarded.

**Comment by laurenluz** [comment]
inclusive of #241

**Comment by laurenluz** [comment]
Forest to set up sync w @JuankBell

**Comment by laurenluz** [comment]
went through final slides for last 2 gravity trainings & reached out to juanka

**Comment by laurenluz** [comment]
From @ForestSoleil in discord:

> Lil' update on my process with implementing Gravity for Giveth ~ Scheduling meeting with Juanka.  Explored/re-read the  following documents to familiarize  myself with TEC Gravity inter-workings... the TEC Gravity  Manifesto document (it had been a few months), Scale of Conflicts Forum post, relevants parts of the TEC Onboarding and Resources Guide, Public Goods / Positive Sum Worlds article, Gravity funding draft document/proposal. I have on my to do list this week to delve more deeply into: Gravity section of TEC Code of Conduct, and "Gravity" Conflict Management for the TEC documents,  as well as to do some continued learning by going through the pre/post learning links in the 'Gravity study plan' doc.

**Comment by ForestSoleil** [comment]
Met with Juan Carlos this week and had a really awesome session with him. So stoked on all the possibilities! I am actively working on this. Do we need documentation by a certain date? I can put something together, but it will be a work in progress and something that I adapt as we go to heat fit Giveth and our economy.

**Comment by laurenluz** [comment]
discussing creating regular spaces to voice concerns & communicate about things so they don't become issues.

interested in writing conflict resolution in DAO

**Comment by ForestSoleil** [comment]
Here it is ~ https://www.notion.so/giveth/Conflict-Resolution-Working-Group-a0348cf929ca48b89357772d68b85ca5

Ready for qa

@laurenluz @divine-comedian @WhyldWanderer @JuankBell

**Comment by laurenluz** [comment]
Can we make this as a google doc, edit it and get it on the docs? I read it in notion, looks pretty good.

**Comment by ForestSoleil** [comment]
Sure thing, here is the google doc
https://docs.google.com/document/d/1jXKBVH8sz3Jx2ej_FsJRr7mwXrV3mhXnyAky9KsA4DQ/edit?usp=sharing

**Comment by laurenluz** [comment]
@jahanzaib-jay @divine-comedian this is ready to go up into the docs

**Comment by laurenluz** [comment]
I'm noticing that it needs to be put into markdown formatting first - @jahanzaib-jay can you do it when you put this up?

**Comment by jahanzaib-jay** [comment]
Hi @laurenluz , I have already converted this into markdown formatting and have submitted the pull request. Waiting for mitch to review and approve.

**Comment by laurenluz** [comment]
https://docs.giveth.io/whatisgiveth/conflictResolution/
