### ISSUE TITLE
Wiki Migration - Meetings Guide (or Recording Meetings Guide)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#222]
Original: https://wiki.giveth.io/governance/record-meetings-guide/
New: https://hackmd.io/nb9s-1xnSW6C8n6nZs-chw

**Comment by laurenluz** [comment]
ok, ready for review: https://hackmd.io/nb9s-1xnSW6C8n6nZs-chw

as mentioned, we'll be adding this together with issue #223 and making it just "Meetings Guide" including info on record keeping, announcing and governance.

@WhyldWanderer @divine-comedian @ForestSoleil

**Comment by laurenluz** [comment]
Thanks Forest! hm... we can use the same one I guess! it might be easier to see it all in one place in the end. what do you think?

**Comment by ForestSoleil** [comment]
Yeah sounds good! I'll add to that one and we can make it one comprehensive merged doc.

**Comment by laurenluz** [comment]
@ForestSoleil I'm going to close the other issue so we just have one issue about meetings guide

Old: https://wiki.giveth.io/governance/governance-meetings/

**Comment by divine-comedian** [comment]
Oops, looks like I showed up late to QA.. I made some suggestions from Forest dropping the wrong link in the other issue. If I'm too late I can understand if you don't want to revisit this doc..

**Comment by ForestSoleil** [comment]
The link is correct, please see discussion in that thread. We put everything together into the Meetings Guide.

**Comment by laurenluz** [comment]
closing this one... just need to push #206 live
