### ISSUE TITLE
Wiki--> Docs: Social Coding>Intro to Giveth Social Coding

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#224]
Wiki doc: https://wiki.giveth.io/social-coding/
New Intro to Community Circle Doc: https://hackmd.io/0i-KIdLhSNKeC-ZcSjT1DA

**Comment by laurenluz** [comment]
Hey Ashley - when do you you'll be able to finish this one? do you need support?

**Comment by WhyldWanderer** [comment]
I think i just need to add the links and it will be done.
I think a lot will eventually change for this one... adding stuff about support team, gravity team, and the forum.

But I think its good enough for now and we can always add more later as it develops.

**Comment by laurenluz** [comment]
so ready for QA?

**Comment by WhyldWanderer** [comment]
sure... go for it but like i said in my last comment, keep in mind the links are not added yet

**Comment by ForestSoleil** [comment]
Great start, Ashley! Make some strikethroughs and direct minor edits. =)

**Comment by WhyldWanderer** [comment]
Ready! @divine-comedian

**Comment by divine-comedian** [comment]
done!
