### ISSUE TITLE
Hire 1-2 backend developers

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#235]
- Role description being hacked on here: https://www.notion.so/Back-End-Developer-Role-Description-b1015cc86a1b47488e41e92132cc0c9f) 
- Feedback from Griff, Mateo & Kay has been implemented
- RJ MIIIIIIGHT return to Giveth!!!! #prayers (for solidity or back end?)
- Offering a referral bonus: 0.5 ETH for hiring, 0.5 ETH for new hire staying on board for 6 months (can use TRACE for a bounty).

**Comment by ForestSoleil** [comment]
Description complete. 
Forest shared everything with new hiring person Heather to publish to cryptojoblist.com
Heather to publish listing and send live link to Forest so that comms team can promote on social media.

**Comment by WhyldWanderer** [comment]
The team decided that this position is not needed at the moment
