### ISSUE TITLE
Team to confirm participation w/ Ashley & book travel for Nosara Costa Rica, June 2021

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#237]
Please unassign yourself from this issue once you have done so.

- Nosara Airbnb for Giveth & Gaia Gives teams, June 19-28
- [Visionaries Immersion, June 25-27](https://www.visionariescr.com/)

**Comment by WhyldWanderer** [comment]
Nosara Airbnb for Giveth & Gaia Gives teams is June 19-28

**Comment by ForestSoleil** [comment]
Thanks Ashley! I messaged you on Discord about the domestic flights I found on June 20th to meet y'all there in the evening. I haven't booked yet b/c I wanted to make sure this is officially official first. I think they are non-refundable. 

Also - will y'all have a space in the car on the return trip for me if I go back at the same time with y'all? And when is the vehicle departing? I haven't decided if I will fly or drive back yet. Wanting to see how I feel physically closer to.
