### ISSUE TITLE
Middle East team to plan gathering for June 2021 date

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#238]
Synchronized, Decentralized, Global session including a Middle East Gathering?
Can Middle East team get together at the same time as the Americans team is gathering in Costa Rica? June 21-24 (According to mountain time days) ideally.

**Comment by ForestSoleil** [comment]
Thanks for the update, Moe Nick! That does sound challenging. Let us know if we can support in any way!

**Comment by MoeNick** [comment]
We booked our accommodation with the help of Amin. We will gather together from 21 to 24  but leaving 24th afternoon localtime, means we may not be available at last day. 
part time staff like, hadi, cherik and mehdi will also join. 
It's cool place in the forest, Amin paid  all the booking expenses at this step.

**Comment by MoeNick** [comment]
What did u do regularly at the gathering?
