### ISSUE TITLE
European Team Gathering June 2021

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#239]
Synchronized, Decentralized, Global session including a European Gathering?
Can Europe team get together at the same time as the Americans team is gathering in Costa Rica? June 21-24 (According to mountain time days) ideally.

**Comment by markoprljic** [comment]
I don't understand what this gathering is about? Should this be online or in person?

**Comment by ForestSoleil** [comment]
Hey @markoprljic on our last two community calls, Dani & Griff shared that the Americas team will be gathering in person in Nosara, Costa Rica June 21-24 with some people staying longer for a visionary immersion and crypto conference. And they encouraged gatherings to happen simultaneously for our teams in other parts of the world during those dates, or even a 1-day, so that we can video conference the teams together while doing in person team bonding and Giveth building activities together at the same time. It's not a requirement, but would be really great if there's potential to make it happen. The Middle East team is currently exploring their options to meet in person.

**Comment by markoprljic** [comment]
Thanks for clarifying @ForestSoleil 
Unfortunately, I won't be able to travel anytime soon which means I won't be able to organize a gathering in Europe.
