### ISSUE TITLE
Update Giveth Community Join Links on Giveth.io

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-planning#24]
We need to remove Riot links and provide Discord links!

![image](https://user-images.githubusercontent.com/39466970/98825256-e625d500-23f9-11eb-8bdf-885f3ddc19e4.png)

**Comment by geleeroyale** [comment]
Hi Dani. I think I answered this before, but the plan is to move giveth-2 to giveth.io. The site you are referencing has a remaining lifespan of weeks. If we think its super critical I can still add it, if we think its important, but I would hold off until we make the switch.

The join page already has been fully realized on staging.giveth.io/join and you can visit it right now to get a look into the future.

Our Riot links still work. In fact we will use the same links with giveth2.

**Comment by Danibelle** [comment]
OK. It's coming up for me strong because I applied for those grants and we have teams evaluating us right now as well as doing a big social media push around those grant apps and positions to fill.  As long as this new information does not change your previous position I accept it ;)

**Comment by geleeroyale** [comment]
@Danibelle Yes - that justifies still changing the actual page. I did not put too much work into it, but everything is updated (mainly Riot became Element and Discord was added as the best way to talk to us!

**Comment by Danibelle** [comment]
Bless youu!
