### ISSUE TITLE
Adapt Gravity conflict resolution training to Giveth

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#241]
Juan Carlos to lead.
Forest to create doodle poll since Juan Carlos does not appear to be on GitHub.

**Comment by JuankBell** [comment]
All Giveth team interested in talking more about Gravity are kindly Invited to our weekly sync. 
On the TEC Discord, Thursdays after Community call https://calendar.google.com/calendar/u/0/embed?src=5mkep1ad1j860k6g7i7fr8plq0@group.calendar.google.com&ctz=Europe/Berlin

**Comment by WhyldWanderer** [comment]
Next Grvity Training:
Dates: September 21 - November 23, 2021
Location: TEC discord server
Sign up:
https://docs.google.com/spreadsheets/d/1PhvCZJFkk_j63Q8Aszay2DAn2qg39x6zJDSLlj924TY/edit#gid=679275498
