### ISSUE TITLE
Giveth needs a PraiseBot!

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-planning#25]
Bring back the RewardDAO in the new iteration of a Praisebot on Telegram..

We are building a new team for Giveth 2.0 from Development to Communications and Governance.. growing the community by rewarding new contributors for their time to learn and use the DApp, provide feedback through GitHub, and help with communications, blogs demos and social media..

Giveth's RewardDAO was great, and it's evolved into a great tool on Telegram - let's get one please 👍

**Comment by willyogo** [comment]
Preach!

Adding this to the GIV token epic because it was identified as a blocker/requirement in the Miro session

**Comment by Danibelle** [comment]
Telegram though, or will this be in Discord now -- can it be both?
