### ISSUE TITLE
Fabio & Edu to deploy front end to Rinkeby. 

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#252]
**GIVdistro** 
Testing the UI for claiming tokens and viewing total tokens.
Action: Griff to get Delfi & Edu to deploy front end to Rinkeby.

**Comment by GriffGreen** [comment]
Major progress: 
https://giveth-claims.vercel.app/
Claims is up and working

**Comment by ForestSoleil** [comment]
**Rinkeby deployment:** Get front end going, run testing, and have everything working end-to-end (claim and vote) 

- Moving to getting DappNode ready.
- Testing everything for DappNode b/c they're probably going to launch first.
- Amin, Fabio working with DappNode team. Amin going to bring in additional TRACE devs. Maybe also Mitch and Lauren to get launch ready. We'll do our Rinkeby testing with them.
- For DappNode - design and everything is frozen. They're going to deploy with what they have.
