### ISSUE TITLE
GIVfarm Designs

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#253]
**GIVdistro**
UI for claiming tokens and viewing total tokens
Action: Marko to change up the DappNode logos for Giveth logos & update color scheme.

**Comment by markoprljic** [comment]
Where can I see and test the current UI?

**Comment by ForestSoleil** [comment]
@GriffGreen @willyogo can you please share these files with Marko?

**Comment by GriffGreen** [comment]
Sent to him directly this morning... but i will put it here too

https://giveth-claims.vercel.app/ <--- current test GIVdrop and GIVstream test deployment
https://gardens-rinkeby.1hive.org/#/garden/0xda1b46663b5ba949f6213d7c3135080b32ad2295 <---- Current Giveth Gardens deployment

Gardens will be redeployed to use a new token that has been upgraded to work with our liquidity mining contracts and UI.. not sure when but it will mean that we have to redeploy everything

**Comment by laurenluz** [comment]
in progress: https://www.figma.com/file/FBqHg0UfeuaIueDEZG0tBS/Giveth.io?node-id=5815%3A2020

**Comment by GriffGreen** [comment]
looks so good!

**Comment by laurenluz** [comment]
Closing this because we're using the GIVeconomy board for tracking these
