### ISSUE TITLE
Confirm Global Lockup Params

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#258]
Global Lockup Params

- 13.33% initially Claimable
    - Need to confirm the vesting percent on the liquidity mining program.
        - ^ What does it look like when done?
        - Vote on 3 options for solutions for this and what the outputs would look like if we use that percent.
- ✅ 4 year unlock period - No objections
- [distribution and issuance spreadsheet](https://docs.google.com/spreadsheets/d/1vpoKMSYVIuV2Db84TVJC1AUPj9GReWg8qTkBoMfFyXA/edit?usp=sharing)

**Comment by laurenluz** [comment]
10% initially unlocked, 5 years streaming: https://aragon.1hive.org/#/giveth/0x6747e3a01f31621a5e024d08f8f7c99fac0dc814/vote/63/
