### ISSUE TITLE
When a Giver donates to a verified project they are notified with an email

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#270]
- As Giveth admins, we want to give GIVbacks to Givers that donate to verified projects on Giveth.
    - When a Giver donates to a verified project they are notified that they will receive up to 75% of the USD value donation back in GIV Tokens. And they are notified of the project verification round date so they know to stay tuned and check back in to see the amount of GIVbacks that will be received.

**Comment by laurenluz** [comment]
#329
