### ISSUE TITLE
Email notification for when GIVbacks are sent

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#273]
As a Giver, I can see at the time of donation that I will get some GIV tokens for their donation “ie. X GIV tokens will be rewarded proportionally to donors over the next 2 weeks, up to 75% of the value of the donation (meme: donation mining). GIVBacks will be subject to the global lockup schedule. Learn more about GIVBacks.”

At the end of each 2 week period, Giveth Admins can easily export the logs and/or calculate GIVbacks for each donor.

Email notification.

**Comment by laurenluz** [comment]
#329
