### ISSUE TITLE
Proposal to change Unicorns to Givethers to identify primary contributors

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#279]
## Context: 
At the outset of Giveth, back in 2017 the core team members had referred to themselves as Giveth Unicorns. This was at the time we can say, before Unicorns went 'mainstream' in the cryptospace. It was cool, it was magical, it captured the passion the team had for building Giveth and it's brand. 

But times have changed..

 We fast forward to the year 2021, there's a new set of faces working on the team, the crypto universe has gone supersonic in terms of size and diversity. The Unicorn which might have been unique and fresh 4 years ago unfortunately, is no longer as rare a sight.

## THE ISSUE:
While updating the Giveth Wiki the communications circle came across the Unicorn references and there were mixed feelings. A **unilateral** decision could not be made and the discussion has been brought to the team. 

#### Do we continue to refer to our core team members as Unicorns or do we change it to something else? If so, then to what? 

In the Governance Discussion held on June 7, 2021 we brought it up on a video call and had the chance to capture everyone's opinion.

## The Proposal
I have gathered and reviewed everyone's advice and opinions in the [GIV GOV meetings notes](https://www.notion.so/giveth/GIV-GOV-WG-Call-June-7-41afb5bc450d49409a13ce41a195582d) and feel confident to put forth a proposal for the community to judge.

#### **I propose we change how we refer to our Giveth team of contributors from 'Unicorns' to simply 'Core Givers'.**

There was noticably stronger favour to move away from Unicorns than to remain. In the discussion the term 'Core Givers' seemed to come out naturally. Without using any extra resources or bandwidth a transition should be easy to facilitate in our terminology. No animals, no mascots. We are the core, the nucleus that keeps Giveth alive and Giving. Without the Giving that we all do, and that all Giveth Contributors of the past have done, what would our DApps and our brand be?

I don't expect 'Core Givers' to be a forever and always term. Just as times changed and the luster of the Unicorn began to fade so might one day we revisit this issue in the future and have new ideas and solutions. 

For now I believe this is the most effective solution having considered all advice given.

Please react with :+1:  If you are in favour of my proposal or :-1:  if you are not in favour.

**Comment by laurenluz** [comment]
I honestly think the use of the term "Givers" to refer to both us (creators, contributors, builders, communicators) and our key target audience (the donors) creates a confusing lack of distinction between clearly distinct groups. I also don't really want to refer to us as the "core", I think we can come up with something that feels a little more exciting

I'm not attached to "unicorn" necessarily, but it feels more fun for now AND we're already used to using it... so I think it might make sense just to hold onto "unicorn" until we come up with something that feels like a better long term name change.

**Comment by Danibelle** [comment]
My resistance point..

I can't get down with Core, it's just too centralized.. we are not an apple. 

I would rather we activate something like "Givethers", as a deepening of Givers.

**Comment by markoprljic** [comment]
I'm against Core, just Givers is fine. 
I don't see an issue referring to all groups the same.

**Comment by ForestSoleil** [comment]
I am against the term 'Core'. I am okay with Givers if we need to move this forward now, but agree with Lauren that our term of distinction for the team should be something different from the whole.

I suggest something along the lines of the Giveth Family, the Giveth Crew or the Giveth Squad to refer to our contributors.

**Comment by GriffGreen** [comment]
Stewards?

**Comment by GriffGreen** [comment]
I like the term Givers for GIV token holders and Change Makers and everyone...

We still need a tag in discord for the crew that is organizing everything.

From mentioned above... I like Givethers... there are Givers (everyone that touches us) and Givethers (people working on Giveth) seems easy and fun

other options

GivHands 
GivStewards
GivCrew
Givicorns
GivFam
Givective
Givtributor

**Comment by divine-comedian** [comment]
![](https://i.imgflip.com/5d17cf.jpg)

**Comment by divine-comedian** [comment]
Hell yeah I love all this advice! Look at us go.

I really like the comments from Griff and Dani
My top 3 picks would be 
Givicorns - (why not have both?)
Givtributor
Givether

I'll follow up with a simple poll in the GOV discord and update my proposal based on those results.
More Advice is of course, always welcome.

**Comment by divine-comedian** [comment]
Okay everyone! Following the Simple Poll it seems like there is a clear winner. 
![image](https://user-images.githubusercontent.com/67759413/121931056-1d05f580-cd11-11eb-9b2b-8402b3dfadb3.png)
Also following some insight from @Danibelle on the GOV call today I will update my proposal 

Revising my proposal to:

**I propose we change how we refer to our Giveth team of contributors FORMALLY from 'Unicorns' to 'Givethers'. We will keep the term Unicorns as an informal reference; a nod to the Giveth of past and something fun and flavourful we can use to refer to ourselves internally.**



Please :+1:  if you are in agreeance, or :-1:  if otherwise.

**Comment by markoprljic** [comment]
Looking back at everything and reading the proposal again I'm questioning the need for change not finding a valid reason and benefits this change will bring us. 
I apologize for not speaking up earlier and taking a clear stance, but after this process I realized this question hasn't been answered, or I'm not aware of it.
My intention is not to make this first world problem as we have way more important issues to deal with.
That being said, if we must I vote for Givethers, otherwise I'd keep Unicorns until needed to change.
