### ISSUE TITLE
Wiki Migration - Giveth Entities and Roles (formerly product definition)

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#280]
Migrating and updating the Wiki docs to our new Giveth Docs website.

Old Doc
https://wiki.giveth.io/dapp/product-definition/

New Doc WIP (first draft written by @MoeNick )
https://hackmd.io/o0eQ1yLrQD-CQAvSWnkxFg

**Comment by divine-comedian** [comment]
Looks like this one slipped through the cracks

First Draft ready to review! It's a beast.
(in page anchor links won't work in hackMD but they will work once live in the docs)

https://hackmd.io/@r6krWxuqQh6X2NbuP6LiIw/SymLuEEt_

@WhyldWanderer @ForestSoleil @laurenluz @MoeNick

**Comment by MoeNick** [comment]
@divine-comedian where can I review I got 404 in hackMD

**Comment by divine-comedian** [comment]
the original issue description should have a working link ☝️ (New Doc WIP)

**Comment by laurenluz** [comment]
Reviewed, made a bunch of edits. Most grammatical, but also worth noting that we have completely removed "Milestones"... now there are just three traces: payments, expenses and bounties.

I also thing we should update the diagrams to have the correct updated terminology.

Thanks for putting this together Mitch 👍

**Comment by divine-comedian** [comment]
I was under the impression that Milestones were just going away for a bit to remove any confusion during the transition to traces.

I don't mind editing the photos but I don't think it should be a blocker for uploading this document to the docs

**Comment by laurenluz** [comment]
Ahh you're right. So it makes sense to keep them in the docs! Agreed not to make editing the pictures a blocker, but I also think it's a good idea to change them as soon as we can.

**Comment by laurenluz** [comment]
noticing this in the docs... anyway for reformat the captions to be actual captions? the formatting is weird

![image](https://user-images.githubusercontent.com/75490971/122103656-18564580-cdd4-11eb-82f4-38e9a6865b50.png)

**Comment by divine-comedian** [comment]
I hear what you're saying. I did have it originally with the h6 headers but they were too small to be clearly legible so I opted for the slightly bigger ones

**Comment by ForestSoleil** [comment]
Reviewed and made some very minor edits directly. Nice work! This is really thorough and clear.
