### ISSUE TITLE
Giveth TRACE launch post for Medium

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#281]
This is a WIP! Will ping y'all when ready for QA

**Comment by laurenluz** [comment]
First Draft: https://docs.google.com/document/d/1eQCh8VQmBHb4BhI3KkCSL3njJh1N2XPJWDgEMXcs_dc/edit#

**Comment by laurenluz** [comment]
@WhyldWanderer @divine-comedian @MoeNick @ForestSoleil First draft of the Giveth TRACE launch post article is more or less done. Would love some feedback or QA as comments or suggestions.

**Comment by WhyldWanderer** [comment]
Reviewed! I left feedback in the document.

**Comment by laurenluz** [comment]
https://docs.google.com/document/d/1eQCh8VQmBHb4BhI3KkCSL3njJh1N2XPJWDgEMXcs_dc/edit#

ready for more QA @Danibelle @divine-comedian @GriffGreen @WhyldWanderer @ForestSoleil 

it's much better, I think

**Comment by laurenluz** [comment]
@MoeNick @aminlatifi - maybe you guys want to have a quick read through as well? the plan right now is, if everyone agrees, to blast this off and publicly announce on Wednesday July 7

**Comment by MoeNick** [comment]
Sure I will check and let you know.

**Comment by ForestSoleil** [comment]
Edited with my simple suggestions in the google doc. Looks great! We just need to adjust the call to action links with unique URLs for tracking before this goes live, assuming Mitch is able to set that up. I'm creating a GitHub issue for it.

**Comment by divine-comedian** [comment]
Reviewed! Fun Article

**Comment by aminlatifi** [comment]
I reviewed and put some comments. I totally disagree with mentioning individual members in article and we should only focus on our brand and product.

**Comment by laurenluz** [comment]
Thanks for your feedback Amin! really awesome, I will make some changes today

**Comment by laurenluz** [comment]
I uploaded this to the medium as a draft already. if you guys have any more pressing changes, please DM me

**Comment by ForestSoleil** [comment]
Published to Medium! We are live.
