### ISSUE TITLE
Wiki to Docs - Covenant

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#283]
https://hackmd.io/66cll3ZuQTG9-8WkGigO9A

**Comment by laurenluz** [comment]
we should combine the covenant doc that @ForestSoleil adapted above with the one from the Giveth Garden and have it consistent everywhere

https://github.com/Giveth/giveth-planning/issues/203#issuecomment-848974612

**Comment by laurenluz** [comment]
this is nice too: https://gardens-rinkeby.1hive.org/#/garden/0x9b4294bf467d97b29f7a96489536da2dd14080bf/covenant

**Comment by laurenluz** [comment]
Ok for QA https://hackmd.io/fasEfiHgRKelVVxAUCya1A?edit

@WhyldWanderer @divine-comedian @ForestSoleil

**Comment by WhyldWanderer** [comment]
I left a couple comments in there! It looks great Lauren and I think it covers all of the bases... thanks for putting it together!

**Comment by ForestSoleil** [comment]
I think it's fantastic. Very well written. My only in-line edits were in punctuation of commas and putting bullets instead of paragraphed dashes for the yes/no policies.

**Comment by laurenluz** [comment]
Thanks @WhyldWanderer @ForestSoleil for the QA

@divine-comedian I think this is ok to put up... can we put this on the docs?

**Comment by divine-comedian** [comment]
Going up! :rocket:

**Comment by laurenluz** [comment]
Hey fam... I added a little bit to our covenant... about rGIV and added that we'll use Gravity. I'm not totally totally sure that this is 100% correct (though I think it is)...

@Danibelle or @divine-comedian can one of you take a look? Let me know if it looks all good and I'll update it in the docs and in the garden

https://hackmd.io/fasEfiHgRKelVVxAUCya1A?both

**Comment by divine-comedian** [comment]
Reviewed!

**Comment by laurenluz** [comment]
thanks @divine-comedian! I added in your edits. sent to Griff for confirmation, then will push it out
