### ISSUE TITLE
Giveth Contributor Interview Video

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#284]
The idea is to interview Givethers and create a compilation video with clips from the interviews. Would love some feedback/additional ideas on questions for interviews. We could even take some time during this week's meetups to record.

List of questions for Giveth Contributors:

- what brought you to Giveth?
- what do you do at Giveth?
- what are you passionate about?
- what does "the future of giving" look like to you?
- why is revolutionizing philanthropy important?

@divine-comedian @WhyldWanderer @ForestSoleil @Danibelle @willyogo 

What do you guys think?

**Comment by ForestSoleil** [comment]
I brought a lighting ring stand for smart phone that we can use to record video today at the retreat if we'd like to schedule interviews with some folks from Giveth and Gaia Gives teams today. I think Matt has audio recording device that we can use as well.
