### ISSUE TITLE
Write new Milestone creation instructions for Giveth 1

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-planning#30]
Ashley on the Giveth Costa Rica team will be contributing to this!!

**Comment by Danibelle** [comment]
@WhyldWanderer I know you made a Milestone doc for the Diamante Luz DAC ..  can you tweak it for Giveth 1?

**Comment by WhyldWanderer** [comment]
Sure thing! Ive been meaning to sit down with it again anyways.
