### ISSUE TITLE
Create Design Work for GIVdrop and GIVstream

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#301]
**GIVdrop** *(we give)* **& GIVstream** *(we give you more)*
- Create design work (Marko)

**Comment by markoprljic** [comment]
Please can you write a good issue description clarifying the scope of work, intended outcome, and output deliverables?
It should be clear to anyone reading the issue regardless of the assignee. "Create Design Work" doesn't tell much :)

Thanks!

**Comment by ForestSoleil** [comment]
Met with the team and we decided to pause on requesting this clear deliverable until Griff, Lauren, Marko & anyone else interested in participating have an over the phone chat with you to discuss the breakdown of how this flows. @markoprljic

**Comment by ForestSoleil** [comment]
https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth.io?page-id=5776%3A1952&node-id=5776%3A12401&viewport=1151%2C-3330%2C0.2548738420009613&scaling=min-zoom&starting-point-node-id=5776%3A12401
