### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#306]

**Comment by ForestSoleil** [comment]
These are duplicates - I already created an epic and issues for this a few weeks ago, and some are older than that.

Epic "Communications Messaging for GIV Economy Launch" https://github.com/giveth/giveth-planning/issues/196

Issues:
GIVbacks Medium https://github.com/Giveth/giveth-planning/issues/142
GIVbacks Twitter https://github.com/Giveth/giveth-planning/issues/193
GIVbacks Reddit https://github.com/Giveth/giveth-planning/issues/194
GIVbacks Outreach https://github.com/Giveth/giveth-planning/issues/19
Airdrop https://github.com/Giveth/giveth-planning/issues/190
GIVgarden https://github.com/Giveth/giveth-planning/issues/265
Project Verification https://github.com/giveth/giveth-planning/issues/163

We can keep these issues from what Mitch created and assign them here: 
GIVstream https://github.com/giveth/giveth-planning/issues/310
GIVmining https://github.com/giveth/giveth-planning/issues/311

**Comment by WhyldWanderer** [comment]
@ForestSoleil This epic is for GIV documentation in the Giveth Docs.

**Comment by ForestSoleil** [comment]
Thanks for clarifying @WhyldWanderer !

**Comment by WhyldWanderer** [comment]
Lets make sure to reference this somewhere within the giv documentation
https://github.com/Giveth/giveth-planning/issues/43
