### ISSUE TITLE
GIVdrop

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#309]

**Comment by laurenluz** [comment]
Starting to work on this here: https://hackmd.io/UtbiH6ogSgau_O2yCLTv2g?edit

**Comment by laurenluz** [comment]
The brightID folks did a little tutorial on how to claim the airdrop... Should I put something like this in the docs as well? @divine-comedian @WhyldWanderer 

I am otherwise just planning to explain who is eligible, that the drop is on xdai and that people also get the stream.

**Comment by divine-comedian** [comment]
The tutorial sounds great, we can have it right in the drop I think, with a prominent header, and some in-page links so any users can jump right to that tutorial from logical points within the entire article

**Comment by WhyldWanderer** [comment]
+1 to adding the tutorial... I think this will be a helpful document to refer people to when they come to the discord wondering how to claim. Thanks Lauren!

**Comment by WhyldWanderer** [comment]
reviewed!

**Comment by laurenluz** [comment]
Need @GriffGreen to make trusted seed blog post to creation explanation!!

**Comment by laurenluz** [comment]
@divine-comedian this one can go up too

https://docs.google.com/document/d/17qjPAyrjxVbpcUHqQCQcLgkPx6-B10BNZmZeJs5JY5U/edit

**Comment by divine-comedian** [comment]
LIVE 
https://docs.giveth.io/giveconomy/givdrop
