### ISSUE TITLE
GIVfarm

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#311]

**Comment by divine-comedian** [comment]
this is my comment

**Comment by laurenluz** [comment]
Just took a quick look. I think this is a good start, but before we add to the docs we should add a little more enthusastic colouring... like in our other docs posts. Something that says like "become a liquidity provider and get even more GIV!"

I also think we should stick the the framing of the stream not as "tokens are being held" but rather, "your stream is growing when you interact with the GIVeconomy". DAppNode used the "tokens being held" framing and a lot of people seemed not to like that. Made a couple of comments in the doc

**Comment by laurenluz** [comment]
from last comms call:
we're doing the first round of 26 weeks and then going to take our learnings and apply them to set up future rewards
the % allocated to the first round hasn't been determined yet... I think a forum post for this will be made

**Comment by laurenluz** [comment]
https://forum.giveth.io/t/giv-liquidity-mining-plan/169/9

**Comment by divine-comedian** [comment]
updated with information from approved GIVfarm spec - 
https://hackmd.io/d5tY1KCSQMOCsxRDs-qRKw

**Comment by laurenluz** [comment]
@laurenluz @WhyldWanderer @ForestSoleil

**Comment by WhyldWanderer** [comment]
I took a look.. everything seems pretty clear to me.

Missing pieces that i noticed:
LP Token Addresses (Mainnet & xDAI)
Staking Contract Addresses
Round 1 Duration

**Comment by divine-comedian** [comment]
? It says right above the distro breakdown 

> **Round 1 (26 weeks)** weekly GIV rewards distribution percentages based on LM supply are as follows:

Good to write down though - we'll be able to fill in all the contract address once we have the final deployment

**Comment by WhyldWanderer** [comment]
Yeah.. I wasn't sure if that part had been ratified at this point.
I just wanted to leave comments of things that need to be revisited before publishing like we talked about in the comms call.

**Comment by laurenluz** [comment]
ok I made some changes in the hackMD, I think this is good to go up.

**Comment by divine-comedian** [comment]
LIVE 
https://docs.giveth.io/giveconomy/givfarm

**Comment by laurenluz** [comment]
@divine-comedian we need to add a little more detail to the doc about the univ3 pool. Things to explain:

- if a user is unstaking an NFT, they also harvest rewards for *that NFT* (and with this, they get rewards also from their GIVstream)
- if a user has an NFT staked... when they harvest rewards... the tx is a multicall wherein the NFT is unstaked, the rewards is computed, the rewards go the user and the NFT is staked again.
- if a user has multiple NFTs staked and they harvest rewards, the multicall unstakes all the NFTs, gets all the rewards and restakes all the NFTs (so gas can start getting a little high)
- if a user has multiple NFTs staked and they unstake one, the multicall tx unstakes their *one* NFT and harvests its rewards (and any rewards claimable for GIVstream), but doesn't touch the other staked NFT .... it doesn't get unstaked & its rewards are not harvested,

**Comment by divine-comedian** [comment]
nice! added in a section to the GIVfarm 

https://github.com/Giveth/giveth-docs/commit/b3db870405e770eaa2c6047b77ecbd7ea6a8be68
