### ISSUE TITLE
Update "What is Giveth?" Page in the docs

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#315]
Related to issue - https://github.com/Giveth/giveth-2/issues/380

Changing the button the giveth.io homepage to our updated what is giveth page - 

this content was written hastily and needs some love. Some suggestions have been to update it with our MVVs and explain more about what Giveth is now - we have so much more to tell! 

Current Working DOC - https://docs.google.com/document/d/1c4fykZmJZ9XPGYfpI-7ROYltYZSMphLxcRJjKiOROFI/edit?usp=sharing

---
Related Info
welcome to Giveth hackMD - https://hackmd.io/cXxKup9_REe2vCxaoLRedw?view
Giveth MVV in notion - https://www.notion.so/giveth/Vision-Mission-09429a1f219c491e9d3f7042bbb4d7f8

**Comment by divine-comedian** [comment]
QA ready! 
https://docs.google.com/document/d/1c4fykZmJZ9XPGYfpI-7ROYltYZSMphLxcRJjKiOROFI/edit?usp=sharing

**Comment by laurenluz** [comment]
wait... it doesn't makes sense to have two working copies of the MVV... this was here: https://github.com/Giveth/giveth-planning/issues/188

The vision is done, the values haven't been approved yet... the mission statement is coming later, after the circles...

Adding suggestions to the rest, but we should not have two redundant docs in progress open for QA

**Comment by divine-comedian** [comment]
Thanks Lauren for the great QA on the doc.. @ForestSoleil  @WhyldWanderer  do you guys want to take a gander before this goes up on the docs?

**Comment by divine-comedian** [comment]
LIVE! - https://docs.giveth.io/whatisgiveth/
