### ISSUE TITLE
Community Project Spotlight Article #1 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#316]
As discussed in the comms channel  we found value in drafting another article to highlight verified and other quality projects using our DApps.

Here's the first draft ready for QA - 

https://docs.google.com/document/d/1FceXdzbdzxAUaYEuIM-Sy_A-Yi2ujGc79QNxwqEPxN4/edit?usp=sharing

@WhyldWanderer @ForestSoleil  @laurenluz

**Comment by laurenluz** [comment]
reviewed
