### ISSUE TITLE
Update Giveth.io and Giveth TRACE Gitcoin Grants Blurbs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#319]
write new revised blurbs, share here for QA before pushing live on gitcoin grants

**Comment by divine-comedian** [comment]
current listing on Gitcoin - 
https://gitcoin.co/grants/2154/givethtrace

https://gitcoin.co/grants/795/givethio-panvala-league

**Comment by divine-comedian** [comment]
first draft ready for QA - https://docs.google.com/document/d/1w5P8NVC3LgrwnbORrVVzkAHGheLMU5NruPFpxgbnNbE/edit?usp=sharing

@WhyldWanderer @ForestSoleil @laurenluz @MiA-Engel

**Comment by laurenluz** [comment]
did QA

**Comment by WhyldWanderer** [comment]
Not sure if this has already been updated but I left some comments in your doc @divine-comedian ..

**Comment by Danibelle** [comment]
I have added the notable achievements per notes from Sunday Community Call.
