### ISSUE TITLE
Email Gitcoin donors list before GR11 start (sept 8) to let them know our listings have been updated

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#323]
#319 must be completed and blurbs updated first

**Comment by laurenluz** [comment]
Did this ever happen? If not maybe we can write a "last chance to donate" message since there are only 2 days left.

**Comment by divine-comedian** [comment]
Unsure, I don`t have the list or the superpowers to do such actions! @Danibelle
