### ISSUE TITLE
Update Giveth.io Terms & Conditions

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#324]

**Comment by laurenluz** [comment]
Giveth.io terms and conditions needs to be updated.

Alex from the Giving block said we could use theirs and fork it:
- [Giving Block Terms of Use](https://www.thegivingblock.com/termsofservice)

We can also use our Covenant and the TEC Covenant for reference... The Covenant will also be used in the GIVgarden
- [TEC Covenant](https://docs.google.com/document/d/1inHqkkQuZzWQQhuq5A6sVwV0a3oQwfuDRv5nctYj8IE/edit#heading=h.um917am6mfff)
- [Giveth Covenant](https://hackmd.io/fasEfiHgRKelVVxAUCya1A?view)

The terms of use will the grounds on which we cancel projects and we will link to the this in the email we send to project owners of cancelled projects

**Comment by Danibelle** [comment]
OK I see this is Me and Mia now - copied the Giving Block ToS and created a doc for drafting [our version here](https://docs.google.com/document/d/19r56M2WBAf5v3tfFPil4L7o5uRNStS_D0nIf_LMKaF0/edit)!

**Comment by Danibelle** [comment]
OK I've done all I can do - there are a few outstanding items:

Privacy Policy
Cookies Policy
Arbitration Jurisdiction Selection
Mailing Address for Giveth communications & opt out letters
Jurisdiction for Small Claims Court unless we can strike this due to Arbitration

Ready for final review, I'll post in Forum!

**Comment by laurenluz** [comment]
@Danibelle can you update us here once you finish it? or perhaps you can make the issue in giveth-next to change it on the DApp instead of me? then you can follow it through better

**Comment by laurenluz** [comment]
@Danibelle @MiA-Engel what's the status here?

**Comment by laurenluz** [comment]
@divine-comedian to cat herd

**Comment by Danibelle** [comment]
alright I think all the issues have been cleared, thanks for the herding @divine-comedian  ..

The next steps are to pass this off to Development to add the required notifications that link to these docs..

1.) Pop-up for Accepting the Cookie Policy
2.) Link to Terms of Use and Privacy Policy

**Comment by laurenluz** [comment]
https://giveth.io/tos LIVE
