### ISSUE TITLE
Email to Unlisted projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#326]
As per: https://forum.giveth.io/t/make-our-giveth-io-dapp-more-resilient-before-giveconomy-deploy/73/11

We need an email that will be sent to projects that admins decide should remain unlisted on giveth.io... something saying "add more information to your project to get it featured on our projects page" with some examples of good projects

**Comment by laurenluz** [comment]
#325 is the guide, for reference

**Comment by divine-comedian** [comment]
I started working on a draft. It's not explicitly clear the review process in the guide how a user can fix their project and become listed. I'm going to write in something along the lines of coming to our support channel and asking for a review of their updated project.

**Comment by divine-comedian** [comment]
first draft is here - https://app.ap3prod.com/giveth/assets/613cd03879fd09441964ff35

it's just missing a link to the full listed/unlisted article which will be in the documentation?
