### ISSUE TITLE
Email to Cancelled projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#327]
When we decide to cancel a project we should send an email to the project owner to explain why. Projects should really only be cancelled if they violate our [covenant ](https://docs.giveth.io/whatisgiveth/covenant) or terms and conditions https://github.com/Giveth/giveth-planning/issues/324

**Comment by laurenluz** [comment]
#325 is the guide for reference

**Comment by divine-comedian** [comment]
to clarify some things currently there exists the ability to deactivate projects, which is currently what we do with projects that violate our ToS. Projects can still become re-activated afterwards. This can be triggered by either by an admin or by the project owner themselves. 

Are we creating a new action of cancelling where the project is removed entirely from Giveth or is this just a renaming of the project deactivation action?

**Comment by laurenluz** [comment]
yeah! so for simplification, you and I decided in DMs that the same email goes to project owner when they cancel or when they deactive (since it's the same event on giveth.io), with wording explaining the difference and linking the terms of use.

**Comment by laurenluz** [comment]
oh oof, yeah that's not good... the project owner shouldn't be able to reactive their project in we cancel it... @mateodaza what do you think? Is it possible to remove the project if it's cancelled?

**Comment by laurenluz** [comment]
This is done for the case of the user deactivating a project

For the case of an admin cancelling it, it's blocked by code being developed to create separate cases for when a user cancels it or when an admin cancels it

**Comment by laurenluz** [comment]
awesome! think we should close then?

**Comment by divine-comedian** [comment]
OH YEAH, CLOSE IT BABY
