### ISSUE TITLE
Write and setup push email to Givers to verified projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#329]
2 emails:
- [x] To Giver when they donate to a verified project
- [x] To Giver when GIVbacks are ready to claim

**Comment by laurenluz** [comment]
in backend, is there a way to know if a donor donated to a verified project or non-verified project?
We think it's possible in the backend.

Include info that 1million GIV is allocated to each round.
Link to GIVbacks page where the round detail information is.

**Comment by laurenluz** [comment]
@WhyldWanderer to draft emails
@divine-comedian to work on creating autopilot journey

**Comment by laurenluz** [comment]
@WhyldWanderer just needs to write content for the email

**Comment by WhyldWanderer** [comment]
Im working on the "Givers to verified projects email'

Heres what is written so far...
![image](https://user-images.githubusercontent.com/74267818/147018673-f63a8e04-87f7-4de4-a51b-e8c045815763.png)

But when I send the test email, it is not autopopulating the information.
This is what it looks like:
![image](https://user-images.githubusercontent.com/74267818/147018772-d27a0d9d-c1df-4f9b-9f83-675f689aea6d.png)

@divine-comedian Any idea of what is happening? i still can't access Segment.

**Comment by divine-comedian** [comment]
let's figure it out - In the meantime I would remove the refrence to 75% of your donation back - let's be less explicit and just say they'll receive GIV tokens at the end of the GIVbacks round

**Comment by divine-comedian** [comment]
I think we resolved the mystery for this issue - can we call this done @WhyldWanderer ?

**Comment by WhyldWanderer** [comment]
Yes!
