### ISSUE TITLE
Send Giveth info over to SDG impact fund to be listed on their site

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#33]
See the other projects currently listed on SDG impact fund, and provide the same fields for Giveth (ie. name, description, images). example: https://www.sdgimpactfund.org/elev3n-gives 

We can use existing descriptions (https://gitcoin.co/grants/795/giveth-20) or draft new content

**Comment by Danibelle** [comment]
Google doc: https://docs.google.com/document/d/1DL1VvhvTC0FxQgXyHsSx92L1sl5iwXTfAkoiY32YSuw/edit#

**Comment by Danibelle** [comment]
Comments appreciated - today is the 28th so our window is open again for SDG tasks, we can get comments today and submit :)

**Comment by magentaceiba** [comment]
I've pulled some photos and a video to use and linked to those in this word doc. Please review that photos are ok/up-to-date. My text edits are complete for comments and final review.

**Comment by Danibelle** [comment]
I've reviewed and commented!

**Comment by Danibelle** [comment]
Sending to Bryan :)
