### ISSUE TITLE
rGIV DAO blog post

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#330]
Based on Griff's post in the forum: https://forum.giveth.io/t/hey-yall-our-rgiv-dao-is-really-powerful-d-lets-collect-info-on-it-here/93

@hannahjojo is going to take on the task of writing a medium post about the rGIV DAO and it's role in our economy... apparently its issuance model is "very fun and novel" :eyes:

**Comment by hannahjojo** [comment]
first draft done and sent to @Danibelle for additional context on "how we got here" and "what we've learned along the way" :-)

**Comment by laurenluz** [comment]
@hannahjojo can you add the link here?

**Comment by laurenluz** [comment]
@divine-comedian to cat herd on this

**Comment by Danibelle** [comment]
I've been hacking on this as we evolve the DAO from rGIV to nrGIV ..

It might be a 2 parter now lol..

Finishing it up now - open for comment and review:
https://docs.google.com/document/d/1FeMVhfdFRbFguCIIwMHsZOXt2ZIK9hx2cSEou_OS5w8/edit#

**Comment by laurenluz** [comment]
Mitch pushing forward w followup efforts

**Comment by Danibelle** [comment]
I saw a few comments from Mitch but no suggested edits?
From my view it is ready to (🌈) Roll.

**Comment by divine-comedian** [comment]
OKay if the content is good to go I will give it one more QA pass

**Comment by divine-comedian** [comment]
Reviewed! @Danibelle  left comments in the doc

**Comment by Danibelle** [comment]
Here's the Medium Draft Link for final look at how it feels there: 
https://medium.com/giveth/the-giveth-dao-community-givernance-84f55fa1ce36

**Comment by laurenluz** [comment]
Lauren to give final read through and publish.

To tweet... something like "the story of the Giveth DAO", how we did it, how we're doing it now - how we deal w decisions.

To publish soon, shill early next week
