### ISSUE TITLE
Discord Promo Push

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#331]
- reach out to other servers to subscribe to our announcements @WhyldWanderer 
- write GIVeconomy video & gitcoin blurb to push to other servers @laurenluz

**Comment by WhyldWanderer** [comment]
Are we still planning this for monday the 13th?

Ive also been thinking that it might be cool to put more things in the announcements channel to try to get more involvement from other communities. Maybe we can start announcing our community calls and meme parties in the channel once more servers are subscribed...

**Comment by laurenluz** [comment]
Ok I finally wrote something up quick: https://docs.google.com/document/d/1lQC07nRh4u5SAFYfgeGHQ2qaKCf9qPX1URF2zdTrfwk/edit

What do you think? Too much? Open to edits @WhyldWanderer @divine-comedian 

I think we should shill this perhaps tomorrow morning?

**Comment by laurenluz** [comment]
This our previous list of servers to blast in... Pasting here... We don't have to do them ALL, but for ideas:

- [ ] Commons Stack MITCH @divine-comedian 
- [ ] TEC MITCH @divine-comedian 
- [ ] Metagame @laurenluz 
- [ ] 1hive - @WhyldWanderer 
- [ ] bloom - @WhyldWanderer 
- [ ] panvala - @WhyldWanderer 
- [ ] dappnode MITCH @divine-comedian 
- [ ] gaia gives
- [ ] bright ID @laurenluz 
- [ ] WOCA @laurenluz 
- [ ] gitcoin  - @WhyldWanderer 
- [ ] BoringBananasCo. - @WhyldWanderer 
- [ ] MetaCartel DAO - @WhyldWanderer 
- [ ] ReSource Network - @WhyldWanderer 
- [ ] WalletConnect - @WhyldWanderer
- [ ] $WHALE - @WhyldWanderer 
- [ ] Aavegotchi - @WhyldWanderer 
- [ ] RARA.house - @WhyldWanderer 
- [ ] Avastars - @WhyldWanderer 
- [ ] Agave - @WhyldWanderer 
- [ ] xDai and Friends - @WhyldWanderer 
- [ ] sourcecred - @WhyldWanderer

**Comment by laurenluz** [comment]
OMG you guys are amazing! Thanks so much for the push - Ashley says we've got 502 members now!!! 🚀 So we can start collecting analytics from discord

BOOOOOOOOOOOOOMMMMM

**Comment by WhyldWanderer** [comment]
Success!!
