### ISSUE TITLE
Create Gitcoin bounty to onboard a video editor to explain the GIVdrop

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#332]
@WhyldWanderer to investigate how to add a bounty before Sept 8 GR11

The video will:
- explain the GIVdrop
- explain the utility/applications of GIV (farm, garden, backs, stream)
- be short, punchy, cool, animated?

**Comment by WhyldWanderer** [comment]
Okay... it seems like its pretty easy to set a bounty on gitcoin.
We can see in this video how to do it: https://www.youtube.com/watch?v=m1X0bDpVcf4
As well as a short explanation here: https://gitcoin.co/bounty/new
I dont know how to do it in Giveth's name though... only under my account.

Information that we would need...
- how much are we offering
- detailed information about what we expect
- how long we expect it should take

![image](https://user-images.githubusercontent.com/74267818/132787419-6dfb87cf-23a7-4c39-a1c5-f65e7f1adf62.png)

**Comment by laurenluz** [comment]
Great! Thanks Ashley. I asked Willy and Griff for their thoughts on how much we should offer. As for timing on how long it would take to produce... I asked Calvin to see how long these kinds of things take.

Do you want to take on putting together the detailed info to publish on the bounty? I don't think we'd need to put the script on the bounty (and anyway I can help write that if we find someone...). Maybe we just link to Giveth, our MVV, the video of griff taking about the GIVeconomy (or the explainer one I made??) and then something saying the kind of thing we're looking for.

I was thinking something like this for reference... https://dappnode.io/
Or, even simpler... https://www.youtube.com/watch?v=mTU6J4WTPtk

**Comment by laurenluz** [comment]
Ok so I found someone to take this on! We don't need a bounty any more. Budget of ~$1000...

I'll work on the script as per #285
