### ISSUE TITLE
Community Spotlight Medium Post

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#333]
Medium blog post highlighting some awesome projects on Giveth. @divine-comedian to have ready to launch by Sept 10ish so we can can shill around the start of GR11.

**Comment by divine-comedian** [comment]
First Draft ready for review! - https://docs.google.com/document/d/13pBdMsNbkOGmkC4xd8ZGzi0UBD5bnrqmwp8uGAm5gN0/edit?usp=sharing

@laurenluz @WhyldWanderer @hannahjojo
@MiA-Engel

**Comment by laurenluz** [comment]
QA complete - really enjoyed that. man, ETHOS is so cool. I love the idea of raising funds to build houses + hire artists --> artist make the houses beautiful --> NFTs are minted --> NFTs are auctioned and funds are used to buy furniture.

Most interesting (to me) use of NFTs I've come across so far.

NICE WORK MITCH

**Comment by laurenluz** [comment]
It live

https://medium.com/giveth/community-project-spotlight-2-dc0c5ca4757d
https://twitter.com/Givethio/status/1436322934033952773
