### ISSUE TITLE
Documentation - How to make a project traceable

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#335]
We should add this to the docs once we have the process clear... Related to #312 because the project must first get verified

**Comment by divine-comedian** [comment]
first draft ready! 

https://hackmd.io/Cqj_evGeQDCEE3Nondq45A

feel free to review @laurenluz @hannahjojo and especially @WhyldWanderer

**Comment by laurenluz** [comment]
This is awesome Mitch! I left some comments... This is a perfect guide for users on how/why to get their project verified... I think Ashley is working on the guide for people to join the project verification team doc in #312....

A couple of big picture notes ( I also left this as a comment)...

> I think you should mentioned that getting verified makes your donors eligible for GIVbacks and also means you can add your project to TRACE for all the benefits...
> 
> And we should call this doc "How to get Verified"
> 
> And then we should add a couple of questions in our FAQ
> 
> "how to add your project to Giveth TRACE"
> 
> and
> 
> "why get your project verified?"
> 
> ...both linking to this documentation.

Can you do those follow up things?

Also... The project verification confirmation email needs to be updated.

**Comment by divine-comedian** [comment]
Great I made those changes! We should leave some notes of all the FAQ updates we need once this documentation goes live, you're referring to be clear, the FAQ that is currently on Giveth.io?

**Comment by WhyldWanderer** [comment]
I reviewed this and left some comments...
i also, edited the Project Verification Acceptance email to reflect Lauren's comments.

**Comment by divine-comedian** [comment]
> I reviewed this and left some comments...
> i also, edited the Project Verification Acceptance email to reflect Lauren's comments.

let me know when this is finalized and I'll update the screenshot!

**Comment by WhyldWanderer** [comment]
@divine-comedian - I confirmed with the devs that the 'make my project traceable' wizard is only on develop at this point. I plan to do a bit of testing just to make sure its all working and then I will talk with MoeNick about getting it live.

I think the best approach is to wait to take the screenshot of the updated email until the link is live. Which shouldnt block the document at all since it can't be published until then anyways. I will update here once its live and we can move forward.
