### ISSUE TITLE
Use GIVbacks dashboard analytics data on giveth.io

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#336]
Related to #318

As discussed in comms call, figure out how to use this data, perhaps by making a dashboard that is show on giveth.io. @WhyldWanderer to check in with Fabio...

From Mitch
> Analytics Dashboards for Giveth.io and Giveth TRACE can be found on Amplitude -
> 
> Giveth.io - https://analytics.amplitude.com/giveth/dashboard/gslvjnl
> Giveth TRACE - https://analytics.amplitude.com/giveth/dashboard/a41z2gk
>

**Comment by WhyldWanderer** [comment]
I reached out to Fabio... ill post here when I have more info

**Comment by WhyldWanderer** [comment]
Griff says that @mendesfabio should have more time to dedicate to Giveth in a few weeks and as also has a great point that he is probably the best person for the task rather than me trying to figure out how to pull the data myself.

**Comment by laurenluz** [comment]
inclusive of #167

**Comment by laurenluz** [comment]
Donna is interested in supporting this!

**Comment by laurenluz** [comment]
We have the GIVbacks dashboard which includes tons of great info, I think we should decide how to best use this content and make some suggestions to add to the DApp.

http://dashboard.giveth.io/public/dashboard/4717fd91-a311-42cf-93d9-185ec8c08a04?round_range=2022-02-04~2022-02-18

@markoprljic @mosaeedi when working on improvements to the DApp, it would be great to include some ideas of how we might want to use this GIVbacks round data
