### ISSUE TITLE
Update email: project created (add info on how to get traceable)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#337]
Not urgent, but I think admins (when using the dapp) should have the options to send an email to projects and suggest they apply for verification. Email should say:

- We love your project!
- Apply to get verified to attract more donors and to rewards them for their contributions
- Just fill out this typeform and we'll get back to you

**Comment by laurenluz** [comment]
It should also include information on the start and end dates for the GIVbacks rounds and say that they need to get verfied by Y date to be eligible for GIVbacks round X

**Comment by WhyldWanderer** [comment]
This email already exists in autopilot. All you need to do is add the project's contact to the "invite for verification" list and they will receive an email inviting them to get verified. Once the admin dashboard is implemented we will add functions for automated emails for accepted applications, rejected applications, listed/unlisted projects and cancelled projects.

By the end of the week, the 'project created' email will also include a link to invite projects to get verified.

> It should also include information on the start and end dates for the GIVbacks rounds and say that they need to get verfied by Y date to be eligible for GIVbacks round X

Once the dates are decided and the docs are live, we can easily link to the documentation about rounds etc. within the email.

**Comment by laurenluz** [comment]
ok makes sense, thanks Ashley

**Comment by laurenluz** [comment]
being sent to invite projects to get verified... later to update w invitation to add to trace
