### ISSUE TITLE
GIVeconomy Intro Documentation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#340]
This is to introduce the GIVeconomy... talk about GIV, the distro, it's initial ultility and features... and future visions...

Still missing some details like the pie chart for the distro, but first draft is ready for review. @divine-comedian @WhyldWanderer 

https://hackmd.io/UtbiH6ogSgau_O2yCLTv2g?both

**Comment by divine-comedian** [comment]
reviewed! :)

**Comment by WhyldWanderer** [comment]
reviewed!

**Comment by laurenluz** [comment]
https://docs.google.com/document/d/1RHkWPqJBTo7ZzclVBt6PB59Tx7V1zrGdSLS50UTN_fo/edit?usp=sharing

https://hackmd.io/UtbiH6ogSgau_O2yCLTv2g?both

@divine-comedian ready to blast

**Comment by divine-comedian** [comment]
LIVE 
https://docs.giveth.io/giveconomy/
