### ISSUE TITLE
GIVeconomy FAQ

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#341]
Looking at other people's token drops and FAQs are a great asset... This is how we prevent the bombardment of redundant questions in our discord...

Some examples:
https://gitcoin.co/quadraticlands/faq
https://shapeshift.zendesk.com/hc/en-us/articles/4403645992077-FOX-Airdrop-How-it-Works

What I'm starting:
https://hackmd.io/WyG1lN_MQiiQWv3dA8bK9Q

**Comment by laurenluz** [comment]
will add this to the giveth.io FAQ when it's ready under a separate category or header

**Comment by laurenluz** [comment]
In testing parties - great way to add questions to this!!

**Comment by laurenluz** [comment]
@divine-comedian @WhyldWanderer @ForestSoleil 

Please review the GIVeconomy FAQ. I think it's good. Maybe some of the questions need to be re-ordered... or maybe we want to have sub headers.... Maybe there are more questions that you think are missing.

If you have more questions to add, please write the answers in as well.
https://docs.google.com/document/d/1Zgv4CvtRPAM4HIlvBXW1fn28Fwe8oMCSgZuV7hOuztk/edit?usp=sharing

## References
The hackMD is here if you want to see the formatting: https://hackmd.io/WyG1lN_MQiiQWv3dA8bK9Q?both

**Comment by divine-comedian** [comment]
reviewed! left some comments!

**Comment by laurenluz** [comment]
thanks for the feedback @divine-comedian ! I asked @WhyldWanderer to do a final read through and then she's going to put this in some organized way in contentful.

@WhyldWanderer - the up-to-date version is in the google doc: https://docs.google.com/document/d/1ArudRhCo7MWY5g8JpawKDsR22nH2Nqkfhl8M_0RvNcU/edit

**Comment by ForestSoleil** [comment]
Yes i am reviewing this now

**Comment by ForestSoleil** [comment]
Review complete, comments in doc

**Comment by WhyldWanderer** [comment]
FAQ's are ready to go up...
We just need the live economy links

**Comment by WhyldWanderer** [comment]
FAQ's are updated, publicly published, and links are functioning! Thanks Mateo!!
