### ISSUE TITLE
Governance Process

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#343]
We need to add an explanation of our govenance process (and figure it out!) to both the docs and the forum.

The covenant already includes a lot of this information, but it's missing details on:
- how long proposals should stay on the forum for advice process
- when something goes to a vote... how/where etc... whether this is rGIV of Gardens... we should explain this

Here's shapeshift's for reference:
https://forum.shapeshift.com/t/fox-governance-process/55

Here's our covenant, for reference:
https://hackmd.io/fasEfiHgRKelVVxAUCya1A?view

@divine-comedian I'm thinking you might be the person for the job, but let's discuss in the comms call on Wed,  I think this is also a governance task but important to get organized before we launch the GIVeconomy

**Comment by WhyldWanderer** [comment]
As I mentioned in the call, some of this info (the stuff referring to rDAO process) will be available in the Contributors guide. 
However, now that I look at this issue more in depth, I think it would still be useful to have a document under the GIVernance circle in the docs that outlines both DAOs, their purposes and their process though.

**Comment by divine-comedian** [comment]
sorry this is getting confusing when we mention rDAO and rGIV and GIVernance - are we talking about the same DAO or am I missing something here? I see this document as being a mix of contributor guide and covenant documentation

**Comment by WhyldWanderer** [comment]
my bad... rGIV is the token for the rDAO (Aragon DAO).... so they are one in the same in my mind. Ill try to keep my wording the same so that we are all on the same page.

**Comment by laurenluz** [comment]
reminder that we're should mention both the GIVgarden and the rGIV/rDAO (from comms call)

**Comment by divine-comedian** [comment]
WIP - https://hackmd.io/lAMbIad3StCyFcNbRtI0zg

**Comment by divine-comedian** [comment]
Okay let's have a first pass on this and anything that might be missing. Please some QA. 
I did review the FOX Governace post and the covenant and I took the parts out that I found to be useful.

https://hackmd.io/lAMbIad3StCyFcNbRtI0zg

@laurenluz @WhyldWanderer @hannahjojo

**Comment by laurenluz** [comment]
I made some comments - thanks Mitch!

**Comment by divine-comedian** [comment]
great! I incorporated most of your feedback and created another section relating to off-chain decision making

**Comment by laurenluz** [comment]
I think this is good - thanks for the updates Mitch!

**Comment by laurenluz** [comment]
Hey @divine-comedian the TEC covenant links to their [governance process forum post](https://forum.tecommons.org/t/tec-polycentric-governance-framework/717) which includes a summary of when to use Conviction Voting, Tao Voting, etc.

Think you could add in some links and sentences so that this is our similar "living document" that we can point to from our covenant?
