### ISSUE TITLE
GIVdrop claim Tutorial

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#344]
The purpose is to show users how to check eligibility and claim the GIVdrop, including screenshots of the GIVdrop flow.

Some references:
https://brightid.gitbook.io/brightid/bright/getting-bright/fairdrop
https://shapeshift.zendesk.com/hc/en-us/articles/4403645992077-FOX-Airdrop-How-it-Works

This will be linked to from the FAQ #341

**Comment by laurenluz** [comment]
@hannahjojo to take this on once we have the front end deployed so we can get accurate screeshots.

**Comment by divine-comedian** [comment]
I'll pick up the flag on this one - waiting for GIVdrop page to be finalized from @laurenluz @pkretzschmar

**Comment by divine-comedian** [comment]
ready for review! missing some final screenshots and links once the UI is finalized  
https://hackmd.io/jRfk1T_ER76xFPtveA74Lg
@laurenluz @WhyldWanderer @ForestSoleil

**Comment by laurenluz** [comment]
Looks great Mitch, I made some small edits directly in the doc... Couple of things I think we should maybe update:

- put in pics with a nice modest address on a deployment where things look right (the ones in there have some weird formatting things)
- Can you add something about this weird wallet connected to a different address thing? https://github.com/Giveth/GIVeconomy/issues/267

**Comment by laurenluz** [comment]
Also, not sure, but maybe the "you missed the GIVdrop" one could show a not-real address... or a blank input field, instead of a real address

**Comment by divine-comedian** [comment]
okay photo changes have been incorporated!

**Comment by divine-comedian** [comment]
I added a small blurb in reference to the getting stuck issues you mentioned - https://hackmd.io/jRfk1T_ER76xFPtveA74Lg#If-you-get-stuck-in-the-GIVdrop-claim

**Comment by divine-comedian** [comment]
LIVE! - missing some UI links from the final deployment 

https://docs.giveth.io/giveconomy/givdrop/#claiming-your-givdrop
