### ISSUE TITLE
Take down wiki.giveth.io or at least document that it is a historical artifact

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#349]
lots of old bad info there... probably best to take it down or at the very least rename it to "OLD Giveth Wiki left up for historical context"

**Comment by laurenluz** [comment]
@geleeroyale you have the power here, right?

**Comment by geleeroyale** [comment]
Yes - we should form some consensus on what to do. Since Ashley, Lauren and Mitch did a great job at revamping the docs I would be in favor of just shutting it down (and redirect wiki.giveth.io to docs.giveth.io)

**Comment by laurenluz** [comment]
If we shut it down, will we still have access to information?

**Comment by laurenluz** [comment]
Hey Kay! I went though the wiki one more time and made issues for the remaining little pieces missing. You can take it down now :)

**Comment by laurenluz** [comment]
this now just redirects to the docs. thanks @geleeroyale !!
