### ISSUE TITLE
Liquidity mining - Reward liquidity providers with GIV

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#35]
In order to reward liquidity providers with a token, the DAO needs to be updated to mint the token.

**Comment by Danibelle** [comment]
Would this actually be spinning up another DAO for GIV, the Utility Token, separate from rGIV, the Reputation Token?

It seems there are a few decisions to make here:
1.) Specify design criteria for the DAO that mints the token 
2.) Create new DAO?
3.) On Aragon 1hive still, or elsewhere?

**Comment by Danibelle** [comment]
We *could* upgrade the existing DAO.. 
But.. if we want to do the Conviction Voting and Karma DAO fork, then creating a new one would make more sense..
DAO is just the token, the software adds packets of rights to that token.. 
So do we add to the existing or make a new space?
Figure out Design first! With spec in hand we can decide the path.

**Comment by willyogo** [comment]
Update: Edu has the liquidity mining contract built for honeyswap (xdai)! Bonus: he set it up so liquidity mining rewards will be subject to the global GIV vesting schedule (ie. on day one, liquidity miners will have 13.33% of their rewards available immediately, and the rest will unlock over 4 years; liquidity miners in year 4 will have ~80-100% of their rewards avaialable immediately, and the rest will unlock over the remainder of the 4 year vesting period that will begin in 2021)

Next steps here are to write, review, and deploy the liquidity mining for Uniswap and Balancer on mainnet, as well as the token staking/project curation on xDAI.
