### ISSUE TITLE
Add the fact that we stole 208 mil with the whg in july 2017 to the giveth history in the docs

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#350]
https://mashable.com/article/ethereum-stolen-white-hat-group-rescued

and 

https://www.vice.com/en/article/qvp5b3/how-ethereum-coders-hacked-back-to-rescue-dollar208-million-in-ethereum

**Comment by hannahjojo** [comment]
On July 19, the White Hat Group was finishing up a Giveth Product meeting when they heard that a hacker had stolen what was $32 million of ether at the time by breaching a wallet. They realized over 500 wallets were vulnerable to this type of attack. The Giveth devs wasted no time. They started taking advantage of the same vulnerability in wallets and emptying the wallet's cryptocurrency before the other hacker could. What was different? They were going to give it all back. Giveth was rescueing the funds, while the hacker was stealing them. 
In the first account, they rescued a staggering 47,000 ether. They went on to empty each of the 500 vulnerable wallets, siphoning the funds into a secure Giveth account. Not only were they hacking at breakneck speed, with help from the entire ethereum community, but they were actively working to be as transparent as possible via Reddit so those who's wallets were being emptied knew they would see their funds again. 
By July 31, the Giveth team had created new, secure wallets for each of these accounts, and delivered the funds back to those accounts and their rightful owners. At the time, they rescued over $208 million worth of crypto, and stated they would not be accepting any donations for their work. 

Is this too long?

**Comment by hannahjojo** [comment]
On July 19, the White Hat Group was finishing up a Giveth Product meeting when they heard that a hacker had stolen what was $32 million of ether at the time by breaching a wallet. The Giveth Devs instantly started taking advantage of the same vulnerability in 500 susceptible wallets and emptying the wallet's cryptocurrency before the other hacker could. 
In the first account, they rescued a staggering 47,000 ether. They went on to empty each of the 500 vulnerable wallets, siphoning the funds into a secure Giveth account. The Giveth team was as transparent as possible via Reddit so those who's wallets were being emptied knew they would see their funds again. 
By July 31, the Giveth team had created new, secure wallets for each of these accounts, and delivered the funds back to those accounts and their rightful owners. At the time, they rescued over $208 million worth of crypto, and stated they would not be accepting any donations for their work. 

Here is a shorter version!

**Comment by hannahjojo** [comment]
@laurenluz

**Comment by laurenluz** [comment]
Hey Hannah! I did some QA on both. I prefer the short version. See edits here: https://docs.google.com/document/d/15ON90RH4TJZrIL_xrkECdmMZu3pJGVL8Hojs4hrHl0I/edit?usp=sharing

Thanks so much!!

**Comment by hannahjojo** [comment]
Love the edits @laurenluz , consider changes committed!
