### ISSUE TITLE
Add Code of conduct to discord

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#352]
@WhyldWanderer to add this to discord when it's done: https://github.com/Giveth/giveth-planning/issues/342

**Comment by laurenluz** [comment]
ok @WhyldWanderer the code of conduct is done and live... I added it to the forum already, and it's on the docs...

use your discretion to decide which version to add to the discord (or if you want to tweak it a little to be discord applicable)

Full version: https://docs.giveth.io/whatisgiveth/codeofconduct
Abridged version on the forum: https://forum.giveth.io/t/forum-guidelines-and-code-of-conduct/137/2

**Comment by WhyldWanderer** [comment]
Done!
![image](https://user-images.githubusercontent.com/74267818/136825070-3e62dbbe-9659-4e75-9e4c-e3fc552eb3e7.png)
