### ISSUE TITLE
Reformat community call to make it interesting to whole community

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#354]
- Make slides with high-level overviews from community leads
- streamline it

**Comment by WhyldWanderer** [comment]
slide deck is complete.. we will see how today's call goes and adjust if needed.

link to current slide deck: https://docs.google.com/presentation/d/1R4tBEWJtqEcw3hPoK1WMjVwwGaaja56S06aENYZqJmk/edit?usp=sharing

**Comment by laurenluz** [comment]
Need to consider restructuring community call ... too much overlap on working groups. to discuss in comms channel & ask feedback in community call
