### ISSUE TITLE
Project Verification Spec

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#359]
We should create a doc roughly outlining out MVP (with the verifaction team)... and then next steps... like adding in Celeste, decentralized project verification with tokens... adding identity verificaiton for donors and projects etc.

@WhyldWanderer what do you think?? a notion doc where we put this info so we have it in one place for future reference

**Comment by laurenluz** [comment]
Something to add... we could add some kind of feature where in order to get the max amount of GIVbacks you can, you have to do idx verification... like the gitcoin trust bonus.

could be that donors get 50% of their max GIVbacks as an anonymous donor... 60% if they add their email... 100% if they're verified in some way (gitcoin uses idena, brightID, PoH, POAP and more). (an idea)

**Comment by WhyldWanderer** [comment]
The MVP document is here: https://www.notion.so/giveth/Spec-GIVbacks-MVP-2d6335964e5b414082e41d7df89f9b3d

I will add your suggestion as a comment so that we can talk about it further.

**Comment by laurenluz** [comment]
oh ok cool, yeah. I didn't realize that all the details wrt to project verification were in there as well.
