### ISSUE TITLE
Make our Forum better

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#362]
Add rules of engagement, governance process, MVV... taking a look at gitcoin, shapeshift, TEC & 1hive for inspo

**Comment by laurenluz** [comment]
Ok I added...

Rules of Engagement: https://forum.giveth.io/t/forum-guidelines-and-code-of-conduct/137/2
MVV: https://forum.giveth.io/t/giveth-mission-vision-and-values/138/2

@divine-comedian when you're done w the gov process #343 can you add in the GIVernance category and we can pin it globally?

**Comment by divine-comedian** [comment]
it has a big section on the GIVgarden.. is it too soon?

**Comment by laurenluz** [comment]
yeah I was thinking it might be too soon for the GIVgarden stuff. if you feel like posting the relevant sections and updating later, we can do that. or just wait and post it as is when we're ready

**Comment by laurenluz** [comment]
ok we have decided that adding gov process to the forum is the last action item for this!
