### ISSUE TITLE
Pre-GIVeconomy launch Project Verification Media Push

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#366]
- twitter push to encourage projects to get verified
- need memes on benefits of getting verified
- blog post on how to get verified & why

**Comment by laurenluz** [comment]
this will include #142

**Comment by WhyldWanderer** [comment]
id say we did a great job with this between twitter and emailing current projects..
Weve been receiving more applications..
Is there any other tasks that we need to complete before we close this?

**Comment by WhyldWanderer** [comment]
I guess there is the blog post thing.. Not sure how much bandwidth we have for that right now though. I think the GIVbacks documnetation and the Doc that mitch made about verification will have to be good enough for now?

**Comment by laurenluz** [comment]
happy to close it if you are
