### ISSUE TITLE
Update Quality Score Documentation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#369]
Need to update this: https://docs.giveth.io/dapps/qualityscore

Once we update this: https://forum.giveth.io/t/revise-quality-score-for-projects-on-giveth-io/104

**Comment by divine-comedian** [comment]
its been removed from the documentation 

https://github.com/Giveth/giveth-docs/commit/702a200ad37d7e620bbca0988dafb06f50d09837

**Comment by WhyldWanderer** [comment]
I dont see this anymore, I think we can close this
