### ISSUE TITLE
Liquidity mining - Select chain/AMM (ie. xdai or eth)

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#37]
Which chain do we want to incentivize users to provide liquidity on? (ie. mainnet ETH, xdai, etc.)
Which AMM? (ie. uniswap, balancer honeyswap, etc.)

**Comment by Danibelle** [comment]
Consensus in Gov Call is to go with xDAI!

**Comment by willyogo** [comment]
Updated consensus is to launch liquidity mining programs on eth mainnet **and** xDAI for the best of both worlds! (from [GIV tokens spreadsheet](https://docs.google.com/spreadsheets/d/1vpoKMSYVIuV2Db84TVJC1AUPj9GReWg8qTkBoMfFyXA/edit?usp=sharing))  Let's continue the discussion here, discord, and the next gov call
