### ISSUE TITLE
GIVeconomy tweet thread

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#371]

**Comment by laurenluz** [comment]
@divine-comedian @WhyldWanderer @ForestSoleil 

Can I get some eyes to QA this?

https://docs.google.com/document/d/1bZa8Cy1NTSGTaQJ_3FmKAqSEou05xOtwgeLN6vRIbkY/edit

**Comment by WhyldWanderer** [comment]
Reviewed and left comments!

**Comment by divine-comedian** [comment]
reviewed! comments in da doc
