### ISSUE TITLE
Make Discord More resilient

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#376]
Vyvy-vi is supporting w this

**Comment by WhyldWanderer** [comment]
Update: this is ongoing.. talking with vyvyvi about adding a verification bot that his friend made. 
He said he will look at our current Discord server and make suggestions based on our current setup.

If anyone has other suggestions about how to make the discord more resilient before launch, please leave ideas in this issue

**Comment by laurenluz** [comment]
looking at replacing out captcha bot w a question one :)

**Comment by laurenluz** [comment]
@divine-comedian @laurenluz @WhyldWanderer to consider reorganizing discord flow... people get a little confused in our server

**Comment by divine-comedian** [comment]
I think we could incorporate circles into the categories and remove some others, so have as categories `WELCOME` , ``COMMUNITY` , `PLATFORM` , `GIVERNANCE` .. we could change the current `community` category into `BRIDGES`  going down the list this could look like (with comments) : 

## welcome 
welcome
mission - erase messages and have a clean, pinned copy of the MVV statements
contribute - maybe remove? not a lot of action, probably doesn't need a dedicated channel
assign-roles
announcements
partner-updates

## community 
general
scheduling
meetingnotes - seems under utilized, could this be merged with scheduling? or even just keeping the link to meeting notes pinned in the relevant WG channels
ideas
support
communications
tweeter
memes 
shtnsggles
praise
project-onboarding
fundraising - maybe archive? seems unclear what its for
type-form feedback
support-internal - can this be combined with typeform-feedback?

## governance
governance
dao
wg-stewards
giveth-trace-payments
multisigs

## platform
all-dev
givethtrace-dev
givethio-dev
giv-economy
design
test-reports
env-sharing
givethio-event-log
ops
devops
github
segment-dev

## bridges
1hive
tec
metagame
panvala
gaia-gives
dappnode - needs to be bridged


new-projects - archive? 
dappnode - archive?
airdrops - archive?

 at this point I think we should look for ways to remove channels and make our discord less overwhelming, we can always add more channels organically as new topics arise.

**Comment by laurenluz** [comment]
vy-vy-vi is going to come in after the TEC discord fixes and give ours a makeover

@WhyldWanderer to update the categories on discord this saturday

**Comment by WhyldWanderer** [comment]
Channels have been rearranged! thanks for your help mitch!

Vyvy-vi plans to have the bots implemented by the 15th.

I will provide him with content for the guide.... check out the tec discord for a preview.

**Comment by WhyldWanderer** [comment]
I sent the content for the guide to @Vyvy-vi...
You can see it here: https://docs.google.com/document/d/1KTDvpTadxNrX33XTNeJ5YXjdXhH4E1yNG5m458KBMTM/edit#

**Comment by WhyldWanderer** [comment]
Verification bot has been added... testing is in progress

**Comment by WhyldWanderer** [comment]
bots are in! verification is smooth.. tested.. I think we are good to go on this.
Feel free to create a Discord test account if you want to try it out

**Comment by Vyvy-vi** [comment]
I think we still need to remove the old Captcha bot

**Comment by WhyldWanderer** [comment]
> I think we still need to remove the old Captcha bot

Done!

**Comment by laurenluz** [comment]
Will be adding bots!

**Comment by laurenluz** [comment]
Cat herding is hard, but it's pretty good right now...
