### ISSUE TITLE
Giveaway & Contest ideas

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#381]
From @WhyldWanderer:

I found a few that look cool, are donating a considerable amount to charities, and might be willing to do a giveaway...

MetaVoicers
https://metavoicers.io/
https://twitter.com/metavoicers
![image](https://user-images.githubusercontent.com/74267818/138353878-cd813268-9046-41c6-b006-28415686c632.png)

Dystopia XXI
https://dystopiaxxi.com/
https://twitter.com/dystopiaxxi
![image](https://user-images.githubusercontent.com/74267818/138353998-7f9e88c8-9331-4bd0-bfa7-28bfac82c2fc.png)

Kids of Tomorrow
https://kidsoftomorrow.art/
https://twitter.com/kotnft
![image](https://user-images.githubusercontent.com/74267818/138354651-9a898e5c-1eb7-4237-bd8a-db33091ed6e9.png)

SharkZWorld
https://www.nftsharkzworld.com/
https://twitter.com/SharkZWorld

_Originally posted by @WhyldWanderer in https://github.com/Giveth/giveth-planning/issues/375#issuecomment-948987956_

(pulling from #375)

**Comment by WhyldWanderer** [comment]
Rainbow rolls offered to do another giveaway for the month of November

**Comment by laurenluz** [comment]
@divine-comedian @laurenluz to add other NFT projects that are charity based if we find them!! looking for people donating at lesat 50% to charity.

Ashley to shill/reach out
