### ISSUE TITLE
Add recurring email to unverified projects to ask them to apply for verification

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#383]
keeps going until they click the link @WhyldWanderer 

every 3 weeks!

**Comment by WhyldWanderer** [comment]
Update: figuring out how I can set the journey trigger to work with this. 

Currently, I see how I can set it to trigger when a link is clicked but I'm not sure how I can set the journey to trigger when a link is not clicked. 

I reached out to Willy... ill update here.

Maybe @divine-comedian knows how I could accomplish this?

**Comment by laurenluz** [comment]
Mitch to look into making jounrey, Ashley to check in w willy
