### ISSUE TITLE
Community Project Spotlight #4

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#384]
projects have been selected for this batch, starting draft this week..

**Comment by divine-comedian** [comment]
first draft ready for review! 
https://docs.google.com/document/d/1Tx9efoGwczPrueiaumUFo5YNYLXPCFKfSw-aHVvQPVE/edit?usp=sharing

@laurenluz @WhyldWanderer

**Comment by laurenluz** [comment]
Reviewed! It's really good

**Comment by laurenluz** [comment]
will submit for publishing by end of the week!

**Comment by laurenluz** [comment]
to blast off mid-late next week (last publication was oct 19)
