### ISSUE TITLE
Add VIsual UI Designer Job posting to docs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#385]
https://docs.google.com/document/d/1-H0ZkftLT3SCReVHlSSDWvXhletnz6mYLAawtqhzvEc/edit

**Comment by WhyldWanderer** [comment]
we can post to this site for free as well https://cryptolancer.work/post-a-crypto-job/

**Comment by divine-comedian** [comment]
LIVE on the docs - https://docs.giveth.io/jobs/UIdesigner
