### ISSUE TITLE
GIV Token General Road Map Direction

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#39]
Get consensus from Giveth governance and community on general roadmap direction (including medium and long term plans)

**Comment by willyogo** [comment]
To clarify, this roadmap/narrative is specific to the GIV token and announcement. This will require some clarity on the Giveth 1 and 2 roadmaps as well.

Next step: write a paragraph or so and share with governance/community

**Comment by ForestSoleil** [comment]
@Danibelle do you have a status update to share on this issue? By when do you think you could have this ready?

**Comment by Danibelle** [comment]
draft for this Sunday.. :)

**Comment by ForestSoleil** [comment]
Blog posts for launch
Consider Whitepaper/Wiki living on or navigated to from website 
(Uniswap announcement good example)

**Comment by Danibelle** [comment]
https://uniswap.org/blog/uni/

**Comment by ForestSoleil** [comment]
3/5 Marketing update:
- Dani & Griff connected last night 3/4 and outlined the key messaging. 
- Created in 1 roadmap in GitHub to break out actions from the roadmap.

**Comment by ForestSoleil** [comment]
Do you have link to the GitHub roadmap you are working from for this @Danibelle ? We have our GIV Token sprint 3 check-in today. Thank you!

**Comment by ForestSoleil** [comment]
@Danibelle can you share a link to the latest draft of this? I'd like to review before our Thursday morning team hack session. And preferably review before Griff and I hack tonight specifically for GIV token. Thank you!

**Comment by WhyldWanderer** [comment]
I feel like this is in accordance to the mvv workshops we will be conducting.

Once we know the overall goals and roadmap of Giveth as a whole, we will be able to break down the individual roadmaps of projects ie. trace, giveth.io, and givbacks..

**Comment by ForestSoleil** [comment]
We will discuss road mappingl, Q3 milestone planning and sprint #10 planning in our pre-planning session today. Here's the agenda: https://www.notion.so/giveth/Sprint-10-0c9d81d5d1ca44eaa2f6c4d40d6044e1
