### ISSUE TITLE
Add VIsual UI Designer Job posting to crypto job listing sites and Giveth LinkedIn account

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#390]
Here is a list of free crypto job posting sites..

https://cryptolancer.work/post-a-crypto-job/
https://crypto-job.com/
https://crypto.jobs/
https://www.cryptorecruit.com/
https://remote3.co/
https://cryptojobs.com/post-a-job/

We should also make a post on the LinkedIn account... does anyone know who has access to this? @Danibelle @laurenluz @geleeroyale?
https://www.linkedin.com/company/givethio/

**Comment by laurenluz** [comment]
Thanks Ashley! I sent the issue to Heather too since she's managing applications for this one (not sure her github).

I think Krisis is probably the one w the linkedin access. 

It would also be good to get this on Bankless because of all the people interested in Giveth after Griff's podcast.
