### ISSUE TITLE
Add to Giveth.io FAQ

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#391]
@DonnaOftadeh suggested adding the following questions

What is verified project? and how I can get my project verified?
What is traceable project and how can I make my project traceable

I think it's a great idea, and we can link to our existing documentation.

**Comment by laurenluz** [comment]
can update this in contentful, credentials are in discord (ask Lauren if you want them)

@divine-comedian to look into making clickable parts of FAQ underlines (links underline)

**Comment by divine-comedian** [comment]
underline on links is now live on `next.giveth.io/faq` 

What is a verified project?

and 

What is a traceable project? should be added in to the FAQ, if you have any revisions please make them directly in contentful

**Comment by laurenluz** [comment]
@laurenluz to review
