### ISSUE TITLE
Update Partnerships Page on Giveth.io

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#394]
https://giveth.io/partnerships

I think this is out-of-date

**Comment by laurenluz** [comment]
should at least include TEC (dashboard), SDG impact fund (non-profit status), Giving Block (projects), 1hive (gardens), Gitcoin (dgrants)

**Comment by divine-comedian** [comment]
@GriffGreen  are there any partnerships listed on [giveth.io](https://giveth.io/partnerships) that would merit being taken off the current list?

**Comment by divine-comedian** [comment]
Okay, I added in all of the above to the partnserhips page and dappnode as well. 

it is live on https://giveth.io/partnerships

any revisions please make them directly in contentful.

**Comment by laurenluz** [comment]
Can we change "Partnerships" to "Partners & Friends" everywhere? In the footer, title, URL & subtext...

## can we remove:
- [ ] Alive
- [ ] Swarm City
- [ ] Salt Lending
- [ ] CanYa

## and add:
- [ ] BrightID
- [ ] Panvala
- [ ] Rainbow Rolls
- [ ] xDai
- [ ] WhiteHat Group
- [ ] The DAOist
- [ ] clr.fund
- [ ] Swarm
- [ ] Gravity DAO
- [ ] Meta Gamma Delta
- [ ] Ethereum Colombia
- [ ] SourceCred
- [ ] Vocdoni
- [ ] MetaCartel

& we're DMing to check in with the following groups... (DMer / DMee):

- [ ] gitcoin Griff / Kris
- [ ] DoinGud Griff / Manu
- [ ] Shapeshift Lauren / Willy
- [ ] iden3 Griff / Jordi
- [ ] polygon hermez Griff/ Jordi
- [ ] governauts Lauren / Livia

**Comment by divine-comedian** [comment]
Okay, most of those have been added - those left unchecked I was unable to find enough information on

I couldn't find a logo, website or anything verifiable for the whiteHat Group 

swarm I found a campaign on TRACE but the link to their website seems to be broken/dead

changing the text everywhere looks like it messes up a lot of the formatting since its quite a bit longer. I don't think it's worth it personally.

**Comment by laurenluz** [comment]
Wow Mitch - you're amazing! Thanks so much!!

Ok... leave the URL and the footer as "partnerships". And let's just have "partners & friends" be text on the page... either the title or the subtext or both.

As for the "ones to check in on"... they're all cool. Can you add:
- [ ] Shapeshift DAO: A free, open-source, and community-owned wallet & interface
- [ ] governauts 
- [ ] gitcoin 
- [ ] DoinGud
- [ ] iden3
- [ ] polygon hermez

As for Swarm & WhiteHat Group...

Swarm: https://www.ethswarm.org/

White Hat Group:
Logo: https://github.com/Giveth/giveth-design-assets/blob/e179c90ed0837cf2e1dbfadd61df1010f714a6d3/05-icons/WHG/whg.svg
Description: Trusted group of Ethereum hackers that have rescued 100's of millions of dollars multiple times.
Link: https://mashable.com/article/ethereum-stolen-white-hat-group-rescued

**Comment by divine-comedian** [comment]
nice! okay everything has been updated and is live on https://giveth.io/partnerships
