### ISSUE TITLE
Come up with good practice GIVgarden proposals for the GIVeconomy video

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#395]
We need to demo the GIVgarden in the GIVeconomy video... would love to show the user scrolling through proposals. So! What would be some good proposals that we would like to see in the GIVgarden after launch?

If we brainstorm here, we can then make them in the test GIVgarden and Harry can do a screen record.

**Comment by laurenluz** [comment]
@divine-comedian to help brainstorm

- NFT collaboration things
- audit our smart contracts

**Comment by divine-comedian** [comment]
I put in a bunch on the latest GIVgarden deployment
