### ISSUE TITLE
Gitcoin grants round 12 prep! Dec 1-16

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#396]
We need to get ready for this!! @WhyldWanderer @divine-comedian 

Can we make a list of to-dos?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/85ccfe79-80f2-4b6a-91ec-ef1ca71cf422)

**Comment by laurenluz** [comment]
- [ ] Make Github account for Giveth @divine-comedian 
- [ ] Write shill skeleton post (w links to blog posts etc) @laurenluz 
- [ ] Make some memes !
- [ ] Check out "Galaxy" grouping

**Comment by laurenluz** [comment]
https://gitcoin.co/blog/announcing-grants-round-12/

**Comment by divine-comedian** [comment]
I checked in w/ Dani on the issues relating to ownership - The owner has no extaordinary rights vs. team members - anyone on the team for the listing has the ability to update the listing copy text, add team members, change title, claim funds to the grants ethereum address. I am currently on both TRACE and IO team grant listings so any access issues should be resolved!

**Comment by laurenluz** [comment]
I wrote an updated blurb for the giveth.io listing: https://docs.google.com/document/d/1zH7sUsIIFmOUAqcvFoPFcf9TCEcCYHHFaM1qqFrFGTg/edit#

@divine-comedian or @WhyldWanderer can you QA and then update our listing:  https://gitcoin.co/grants/795/givethio-panvala-league

**Comment by divine-comedian** [comment]
I did some rapid QA - looks good, I'm updating the listing meow...

**Comment by divine-comedian** [comment]
Okay both TRACE and IO listing have been updated using the copy that Lauren provided. Particularily for TRACE I said that  our main funding objective for TRACE is to begin deploying it on xDai and other L2 chains..

**Comment by laurenluz** [comment]
Thanks Mitch!! hey but xDai is actually a sidechain, not a L2

**Comment by laurenluz** [comment]
Thanks so much Mitch! Juanka is making a really nice, clean collection for TEC / commons stack / Giveth. I think we should shill that in our media. Once he / we decide(s) on a name for the collection, I'll share it here...

For now it's a bulk add: gitcoin.co/grants/cart/bulk-add/3951;5;283,2978;5;283,2154;5;283,1155;5;283,1127;5;283,899;5;283,795;5;283,539;5;283,517;5;283,308;5;283

**Comment by laurenluz** [comment]
Let's blast this off!

## Basics:
- [ ] announcements channel Giveth @laurenluz 
- [ ] send an email out to previous gitcoin donors @divine-comedian
- [ ] tweet

## Discord Servers:
- [ ] Commons Stack MITCH @divine-comedian 
- [ ] TEC MITCH @divine-comedian 
- [ ] Metagame @laurenluz 
- [ ] 1hive - @ForestSoleil 
- [ ] bloom
- [ ] panvala
- [ ] dappnode @divine-comedian
- [ ] bright ID @ForestSoleil 
- [ ] WOCA @laurenluz 
- [ ] gitcoin
- [ ] MGD - @ForestSoleil 

## Bonus Discord Servers:
- [ ] BoringBananasCo. - @WhyldWanderer 
- [ ] MetaCartel DAO - @WhyldWanderer
- [ ] WalletConnect - @WhyldWanderer
- [ ] $WHALE - @WhyldWanderer 
- [ ] Aavegotchi - @WhyldWanderer 
- [ ] RARA.house - @WhyldWanderer
- [ ] Agave - @WhyldWanderer 
- [ ] xDai and Friends - @WhyldWanderer 
- [ ] sourcecred - @WhyldWanderer 
- [ ] Nfty Riots - @WhyldWanderer 
- [ ] Pooltogether - @WhyldWanderer 
- [ ] 3Box - @WhyldWanderer 
- [ ] OpenSea - @WhyldWanderer 
- [ ] E1337 - @WhyldWanderer 
- [ ] SHE - @WhyldWanderer 
- [x] ceramic - @WhyldWanderer 
- [x] beezu - @WhyldWanderer 
- [x] poap - @WhyldWanderer 
- [x] biconomy - @WhyldWanderer 
- [x] ethglobal - @WhyldWanderer 
- [x] tip.cc - @WhyldWanderer 
- [x] balancer - @WhyldWanderer 
- [x] metaspace - @WhyldWanderer 
- [x] defi signals dao - @WhyldWanderer 
- [x] WIP Publishing - @WhyldWanderer 
- [x] ladz city - @WhyldWanderer 
- [x] metagammadelta - @WhyldWanderer 
- [x] raidguild - @WhyldWanderer 
- [ ] grassroots economics - @WhyldWanderer 
- [x] metavoicers - @WhyldWanderer 

## Awesome collection to share:
https://gitcoin.co/grants/explorer/?page=2&limit=12&me=false&sort_option=weighted_shuffle&collection_id=18644&network=mainnet&state=active&profile=false&sub_round_slug=false&collections_page=1&grant_regions=&grant_types=&grant_tags=&tenants=&idle=true&featured=false&round_type=false

**Comment by laurenluz** [comment]
Our shill doc: https://docs.google.com/document/d/1gZFQ8qXBOpPwwn0u78th0_BnwfR-rQT_MnO5CTa4QYM/edit
