### ISSUE TITLE
Press Release (for non-crypto audience) announcing GIVeconomy

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#397]
From conversation w Marko, would be good to create a press release to send to some major news/media outlets that are not crypto native to announce Giveth & the GIVeconomy

https://discordapp.com/channels/679428761438912522/790268394251354143/910555326145781770

![image](https://user-images.githubusercontent.com/75490971/142261858-147d0a01-eca9-4dbb-bbc8-a14a56c607e5.png)

**Comment by oyealmond** [comment]
Rescuing this issue [here](https://github.com/giveth/giveth-planning/issues/875)
