### ISSUE TITLE
OMG we need to update the FAQ

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#398]
https://giveth.io/faq

**Comment by divine-comedian** [comment]
I've updated a lot of the current headings. related to some questions from @laurenluz to clarify how giveth is funded - well, how should we explain this? 

@GriffGreen  I think you're the person who has the most info

**Comment by laurenluz** [comment]
Well i think just saying we're funded solely by donations... no investments, no grants. 

That's what I wrote w feedback from Griff on twitter

**Comment by laurenluz** [comment]
Did you update the content too? It seemed like this was pulled from trace... and was still using the DAC framing

**Comment by divine-comedian** [comment]
I'll update that as well, going to give it another pass today.

**Comment by laurenluz** [comment]
nice :) here's the tweet btw.
https://twitter.com/Givethio/status/1454084287184130049

Maybe it could be:

"How is Giveth funded?"

"Giveth has been adding value to Ethereum for 5 years, funded solely by donations. No investments, No Grants. We've been working [to advance Ethereum](https://twitter.com/Givethio/status/1454084287184130049) in pursuit of our ultimate mission: To reward and empower those who give. You can support us by [donating to our project](https://giveth.io/project/the-giveth-community-of-makers)."

**Comment by laurenluz** [comment]
I confirmed that answer w Griff

**Comment by divine-comedian** [comment]
Nice! I'll work that into something more cohesive for the FAQ. One concern is that wouldn't we consider the money we receive from gitcoin grants as.. grants?

**Comment by laurenluz** [comment]
no, money from gitcoin grants are donations. a grant is something that comes from an grant giving org. gitcoin grants is crowdfunded.

optimism would be a grant, but we haven't gotten that money. if the payment is followed through then that will be our first grant ever.... the last 5 years we've been operating only on donations.

**Comment by laurenluz** [comment]
review by @laurenluz @ForestSoleil @WhyldWanderer

**Comment by laurenluz** [comment]
@WhyldWanderer going to do a final read when she takes care of #341

**Comment by ForestSoleil** [comment]
Just reviewed. Looks good.

Minor:
Need a period at end of paragraph and a comma after SDG Impact Fund in the 2nd question. 

Under question 'can i donate on giveth if i dont have crypto' i suggest defining the term 'fiat'. 

In the last question there's a closing quotation mark only on one side of a sentence. And a period at the end where there should not be.

Curious what the process is for adding other FAQ questions. Surely there are more. Or perhaps these are just the ones you're seeing regularly in discord support threads?

**Comment by divine-comedian** [comment]
> Just reviewed. Looks good.
> 
> Minor: Need a period at end of paragraph and a comma after SDG Impact Fund in the 2nd question.
> 
> Under question 'can i donate on giveth if i dont have crypto' i suggest defining the term 'fiat'.
> 
> In the last question there's a closing quotation mark only on one side of a sentence. And a period at the end where there should not be.
> 
> Curious what the process is for adding other FAQ questions. Surely there are more. Or perhaps these are just the ones you're seeing regularly in discord support threads?

If you get the log in credentials for contentful it's very easy to add in more question to the FAQ
