### ISSUE TITLE
Developer Coworking

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-planning#4]
Schedule times where devs can work together during the week OR regular (daily?) 15 minute standup to review status of zenhub issues.

@geleeroyale @aminlatifi

**Comment by aminlatifi** [comment]
> I thought more about this, and it's hard for me to commit to certain times and days, as I am currently moving around a lot, and meeting lots of people.
> 
> I feel that we can be very responsive here on Github or on Discord and support each other though.
> @aminlatifi - what do you suggest?

Sorry for late response, as we are not dedicated all our time to this project I agree with you. Personally has not engaged completely yet, so we can decide later if it's needed.
