### ISSUE TITLE
Get someone to support claiming Optimism RetroPGF funds

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#401]

**Comment by laurenluz** [comment]
@ForestSoleil has a friend in portugal who may be willing to do us the favour

would be good to clearly outline process of what this entails

**Comment by laurenluz** [comment]
it's "capital gains" - would be good if someone wants to have legal income

**Comment by WhyldWanderer** [comment]
WE found this person yeah? can we close this?

**Comment by laurenluz** [comment]
yep
