### ISSUE TITLE
GIVeconomy partner outreach for twitter

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#404]
Before launch we need to reach out to our partners and ask them to prep to help us with a quote tweet

Some examples:

Gardens: https://docs.google.com/document/d/1q9LKFWqGdlMJU45sXJRZGCzepgsYnrwWGkq5g61oALU/edit

Panvala:
> Okay we're live! Our suggested format for a quote tweet is to combine one option from Part 1 and one option from Part 2 below. Lmk if you have any questions, thanks! 
> Part 1: Comment about how our community uses Panvala
> 
> - Panvala has helped our community by...
> - Our participation in Panvala's network has brought us closer to communities like...
> 
> Part 2: Join us in Panvala
> 
> - We want to share Panvala with your community! Join us!
> - We think your community will love Panvala as much as we do! Join us! https://twitter.com/PanvalaHQ/status/1433067368469565440?s=20

BrightID: https://docs.google.com/document/d/1R_vcsaRB4nMAcKF4TXPvx8aRvN7o-MToCyqxIY6qwko/edit

**Comment by laurenluz** [comment]
Our spreadsheet: https://docs.google.com/spreadsheets/d/10d3-NFU6M7Dl9u4A4W0g4JZa96zNuUpGzXxtljJuF94/edit#gid=0

Our groupings of people to contact:
- Verified projects
- GIVdrop recipients
- Partners

**Comment by WhyldWanderer** [comment]
Here is a link the the other outreach spreadsheet we have... its kinda messy but maybe we can harvest some info from here:
https://docs.google.com/spreadsheets/d/1Itb-64dyseTGElTOuA3CUozkLFmfFrK_pn80LfLOOG0/edit#gid=862856503

**Comment by laurenluz** [comment]
https://docs.google.com/document/d/1AQ4vM7jALdqHgs-hpdXeTAr5Om7bv7X-wyeNFHXuGCo/edit#heading=h.td60336cxkb1

**Comment by laurenluz** [comment]
Ok I'm done with this, I messaged somewhere between 50-100 people
