### ISSUE TITLE
Review autopilot emails for the GIVeconomy

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#406]
@WhyldWanderer to do a review & set up drafts

Ensure that tenses are correct
If things need to be QA'd will add issues, send links or screenshots

**Comment by WhyldWanderer** [comment]
Emails have been reviewed! I have made issues regarding each one for Q/A process.
Progress can be tracked in this epic: https://github.com/Giveth/giveth-planning/issues/361
