### ISSUE TITLE
Add tax deduction info to Terms of Service now that we will have a token and GIVbacks program

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#407]
We need to add some clarification to the Terms of Service around tax deductions. Somewhere in this section... 
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/4ce9409b-c773-4f7e-8c57-0c09e2026a93)

Something that mentions that we do not support donors in obtaining tax deductions, and that by receiving GIV tokens, the tax deduction might be unavailable.

**Comment by WhyldWanderer** [comment]
"Giveth takes steps to confirm each Verified project that claims to be a nonprofit is a registered nonprofit organization by confirming the tax ID number. In the US, these nonprofit organizations are tax-exempt under section 501(c)(x) of the Internal Revenue Code. For international organizations, we confirm they are the equivalent of a 501(c)(x) organization and confirm they are registered in their respective countries. Not all verified projects are registered nonprofit organizations.

However, each Donor must make its own determinations that an Entity requesting contributions through our Tools is suitable for such Donor (and eligible to accept cryptocurrency as a donation). Giveth is only responsible for connecting Entities and Donors, and is not and will not be responsible for the use of any Donations. Giveth similarly is not and will not be responsible for ensuring that information (including credentials) an Entity or Donor provides is accurate or up-to-date. We don’t control the actions of any Entities or Donors. We do not support donors in obtaining tax deductions and if a donor receives GIVbacks for donating to a verified project, we can not guarantee that the donation is legally tax deductible."

**Comment by laurenluz** [comment]
Should have review call with @Danibelle @GriffGreen @WhyldWanderer to review some pieces of terms of service & SDG thing and be certain that things makes sense.

@GriffGreen was going to reach out to some legal support

**Comment by laurenluz** [comment]
Griff and Ashley were just talking about this... that we should remove the SDG stuff from the terms for now. take out the non-profit stuff and just don't mention it

**Comment by divine-comedian** [comment]
any updates on the legal review? can we put this text @WhyldWanderer  posted as is?

**Comment by divine-comedian** [comment]
okay - checked in w/ Griff - changes are in https://github.com/Giveth/giveth-next/commit/749f4dd38ae9687fd36c0b761b8ca3220d814486

**Comment by WhyldWanderer** [comment]
Looks good! changes have been implemented...
