### ISSUE TITLE
Create Spreadsheet for new PAN payments system 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#409]
from GIVernance notes: 
- **WG PAN allocations**
    - Mitch's idea from Discord based on last week's feedback. Safe enough to try?
    
    [https://discord.com/channels/679428761438912522/892792397849821215/912417108191739914](https://discord.com/channels/679428761438912522/892792397849821215/912417108191739914)
    
    > I would envision that each WG is allocated a percentage of the total distro for a given period. Each Steward then decides what the percentage they think each WG deserves, and then we take an average of everyone's response. this is similar to what happened last round but instead of stewards deliberating on individuals we instead look at WGs. From there then Stewards can allocate how much is given to the contributors in their WG.
    > 
    
    > During the second step of Stewards allocating to WG contributors we can have it more transparently laid out in the sheet who is receiving regular rewards or not. We encourage stewards to reward PAN in greater proportion to non-regular contributors without any explicit rules, rather at their discretion.
    > 
    
    > I also think this can likely be done 100% async over the course of 4-5 days. We can create a forum post or lead discussions here for any disagreements or clarifications needed for allocations
    > 
- send out distro as is from spreadsheet where Stewards analyzed invidiual contributors - took average
    - what chain do you want to receive PAN on? Zksync or Mainnet? Zkysnc for donating/ Mainnet for selling/staking
    - batch it into one trace and move it to xDAI?
    - sum of contributors is much higher than people in this call - can add several people
    
    *Action Items:* 
    
    - [ ]  Someone to pickup the flag on this since Hannah is scaling down role - DANI  and GENE (@csggene3) to spearhead - Mitch will support
    - [ ]  Finalize Distro - use old system
    - [ ]  hash out new system with corner issues -

**Comment by csggene3** [comment]
Sweet! this will be fun for me to jump into since I've never had the opportunity to work with trace, and prepping a new system to use?? ++more cool =D

**Comment by csggene3** [comment]
The data is in the repo or a separate spreadsheet or? just a finger towards step0 and i'll b off =)

**Comment by csggene3** [comment]
or slow the role and sync with dani?

**Comment by divine-comedian** [comment]
> or slow the role and sync with dani?

sync with Dani! 

here's some of the old spreadsheets:
https://docs.google.com/spreadsheets/d/13V6WVmmHGDjTgx6ImuODuqKSI-oTh3iUC_p_IAe8_HA/edit?usp=sharing

https://docs.google.com/spreadsheets/d/1O3NBPndjm-e7CEMKwhMNHQxvug4SyuozO9xw2XeabS4/edit?usp=sharing

**Comment by laurenluz** [comment]
going to disperse as before & will stop using PAN for payments & will use for liquidity or something else

**Comment by csggene3** [comment]
I'm going to be much more active on github moving forward, so this same **weeks without action issue** will not reoccur, but I should probably stick to solo assignments since it seems like my own inability to coordinate with @Danibelle caused the poor result on this issue. She was willing to meet and coordinate on multiple occasions, and I've just been really trying to navigate the myriad of coordination and comms tools only very recently; but I think I might be getting a handle on them now. We'll see. Apologies @Danibelle @divine-comedian @laurenluz for letting you down on this one.

**Comment by laurenluz** [comment]
No worries @csggene3 !! It was also chatted about in the governance call and we decided to use GIV for the payments and PAN for other stuff. Happy to have you on the team though!
