### ISSUE TITLE
GIVeconomy Launch party

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#411]
- could use airmeet? could use stage in discord?
- do we want to include people to spotlight projects?

- old givethers
- team members presenting - farm, project verification, GIVbacks,
- Giveth projects?
- gardens representative
- interactive things? can we give GIV tokens & donate to projects together during launch party?
- [tip.cc](http://tip.cc) bot? Ashley to investigate & ask Willy
- GIVbacks & giving as focal point of the launch party
- Reach out to projects on Giveth who are crypto savvy * contact verified projects * contact list in autopilot already

Ashley planning to make an outreach email to verified projects to get them to share about the GIVeconomy & GIVbacks!
GIVeconomy - each of the components why & how
Q & A
costs $1000 to get GIV on tip.cc... do they have it on xDai?
separate spotlight call in airmeet

ashley & Lauren & forest to set up outreach to projects
lauren to create tweet thread for economy announcement

**Comment by WhyldWanderer** [comment]
>  do they have it on xDai?
Yes they do!
Willy sent me these videos that Shapeshift made about depositing, tipping, and withdrawing from tip.cc
https://m.youtube.com/watch?v=lEeo4qNZjV8
https://m.youtube.com/watch?v=O5_YzYCFZKE

**Comment by WhyldWanderer** [comment]
tip.cc bot only works in Discord and Telegram so we wouldn't be able to use this during the meet the makers event on airmeet.
Maybe we can give everyone GIV tokens at the launch party and encourage them to come to the meet the makers event to donate them/receive GIVbacks for those donations?
