### ISSUE TITLE
Update 'project created' email

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#414]
Current/prelaunch version:
![image](https://user-images.githubusercontent.com/74267818/147004134-f3df475e-2675-48c4-a42c-a9c02493c669.png)

To be published at launch:
![image](https://user-images.githubusercontent.com/74267818/147006641-8cb6e601-9577-4491-8c34-a38e7ae4675b.png)

**Comment by laurenluz** [comment]
This is great Ashley!
