### ISSUE TITLE
Update 'Project Approved' email

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#417]
I think this one could use a little more work. Any ideas?
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/ae3a3356-4e09-41f8-96fd-1b11ecead757)

I would like to add a link so that the project can share from twitter or social media that they are now verified... do you know how to do this @laurenluz?

**Comment by laurenluz** [comment]
I don't know how, but I think it's a great idea. I bet you @mateodaza knows! Can you help us out?

**Comment by mateodaza** [comment]
> I don't know how, but I think it's a great idea. I bet you @mateodaza knows! Can you help us out?

passing the ball to @divine-comedian what do you think?

**Comment by divine-comedian** [comment]
there's a way to add HTML into the emails - we could potentially create something using <script> and the twitter API - I will investigate with @mateodaza

**Comment by laurenluz** [comment]
seems very complicated - let's cut the shareable links from scope.
