### ISSUE TITLE
Launch Shilling

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#419]
Okay guys... here we go!
As per the [launch plan](https://docs.google.com/document/d/18MXQV1bX6ng8tZv7QxH7Gb1vZsdbOSitLgt9BURgfa0/edit?usp=sharing) here is the list of shilling channels. Please feel free to add more.
Check the box and add your name to the ones you will own:

- [ ]  Write shill skeleton post (w links to discord, blog, giveth, etc)

Discord Communities to shill in:
 - [x]  1hive
 - [x]  Giveth Announcements
 - [x]  TEC
 - [x]  Commons Stack
 - [x]  MetaGame
 - [ ]  Bloom Network (?)
 - [x]  DappNode
 - [x]  TE Academy (?)
 - [x]  Panvala
 - [ ] Commons Stack
 - [x] dappnode
 - [ ] bright ID 
 - [ ] WOCA
 - [ ] gitcoin 
 - [ ] MGD 
 
Bonus Discord Servers:
 - [x] BoringBananasCo. 
 - [x] WalletConnect 
 - [x] $WHALE 
 - [x] Aavegotchi 
 - [x] RARA.house 
 - [ ] Agave -
 - [x] xDai and Friends 
 - [x] sourcecred 
 - [x] Nfty Riots 
 - [x] Pooltogether
 - [ ] OpenSea 
- [x] E1337 
 - [ ] SHE 
 - [x] ceramic 
 - [ ] beezu 
 - [ ] poap 
 - [ ] biconomy 
 - [ ] ethglobal 
 - [ ] tip.cc
 - [ ] balancer 
 - [ ] metaspace 
 - [ ] WIP Publishing 
 - [x] ladz city 
 - [ ] raidguild 
 - [ ] grassroots economics 
 - [x] metavoicers 
 - [x] DoinGud 
 - [x] SharkZWorld 
 - [x] BabylonDAO

**Comment by laurenluz** [comment]
I made a launch shilling template: https://docs.google.com/document/d/1s_Q0eZ41Z0Ono2NG0AJ19rIRwesOlPPtprYG_aLixS0/edit

@WhyldWanderer @divine-comedian you have edit access so if you want to copy/paste it below and make it your own, feel free!

**Comment by WhyldWanderer** [comment]
You da best! Thanks Lauren
