### ISSUE TITLE
Project Verification documentation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#420]
we should write something good and change all our links explaining it

**Comment by laurenluz** [comment]
Document in notion outlines the process
This document will basically explain what we look for in the typeform

**Comment by ForestSoleil** [comment]
Ready for QA: https://docs.google.com/document/d/1LgSJSrlSVFfdoEtR6kjG3mJDMEexaq9f2PleMLcyJaQ/edit# 

@laurenluz @WhyldWanderer @divine-comedian

**Comment by WhyldWanderer** [comment]
Reviewed! I left suggestions in the doc.

**Comment by divine-comedian** [comment]
@Brodyann7  a good first issue for ya! :point_up:

**Comment by ForestSoleil** [comment]
Thanks Ashley! I incorporated your suggestions.

**Comment by Brodyann7** [comment]
Also Reviewed the doc, some suggestions.

**Comment by laurenluz** [comment]
Left a comment in the doc, but will restate it here

The graduated sanctions part already is in the docs, but a bit different.. updated/improved up since the original notion version (where I'm assuming this came from):  https://docs.giveth.io/giveconomy/givbacks#disqualifying-factors-for-givbacks-program

Also in the GIVbacks doc, we have the details about the rounds: https://docs.giveth.io/giveconomy/givbacks#project-verification

My suggestion:
1. We use the copy that is live on the docs instead of the one from the notion (that is missing some improvements) so replace the graduated sanctions section with a copy/paste from the docs... or, someone goes through them both and takes best of both worlds...

2. Add to this doc a copy/paste of the project verification rounds that currently is in the GIVbacks doc.

3. Remove those parts from the GIVbacks doc that is live currently and change it a little so that those sections are simple things that link to the parts of the project verification documentation
Show less

@WhyldWanderer I think you might be the best person to make this make sense, what do you think?

**Comment by WhyldWanderer** [comment]
I think your plan sounds good...

I can take the best from both worlds as you say.
I will need for there to be a project verification section somewhere here:
![image](https://user-images.githubusercontent.com/74267818/149440706-bebf0bc1-f143-4305-995a-548e86ac947c.png)

I will take the parts from the current live GIVbacks doc that make sense... I think that the rounds should be included in both sections... the project verification doc will have the deadlines for getting verified and when to expect your badge and the GIVbacks doc will have the rounds as they are for a donor expecting GIVbacks explaining revision and claiming etc.

I will update the notion to match the disqualifying factors from the live docs - i think we should still have this guide in notion for members of the team to refer to for discord verification etiquette and spreadsheet access etc.

@ForestSoleil Are you okay with me taking it from here?

**Comment by ForestSoleil** [comment]
Yes no problem @WhyldWanderer thanks for checking in!

**Comment by laurenluz** [comment]
@WhyldWanderer - sounds perfect!

Thanks to you both!! you're heroes!

**Comment by WhyldWanderer** [comment]
Okay here we go!

GIVbacks - to go live at docs.giveth.io/giveconomy/GIVbacks - https://docs.google.com/document/d/1nNPQNGCgv9HH4F_zWTr2lskgZ1r0Xhq9qmEMzM0JD4w/edit?usp=sharing

Project Verification - to go live at docs.giveth.io/giveconomy/ProjectVerification  - https://docs.google.com/document/d/1o5_oM7uiPb3k97U6PFnJAewUDuNIshQPvVbesfdDXzg/edit?usp=sharing

I decided that if we are going to have 2 documents, disqualifying measures should be on both however the sanctions are geared toward the audience accordingly imo.

Please GIV it a review and see what you think! @laurenluz @ForestSoleil @divine-comedian

**Comment by laurenluz** [comment]
"GIV" it a review indeed.... I made a few small suggestions... and noticed the GIVbacks round infographic was omittied... I think it should be put back 🤔 

Looks really good @WhyldWanderer !

**Comment by divine-comedian** [comment]
just an FYI to everyone - images don't copy from google docs to markdown - make sure you have an original copy of your image so it can be imported into the giveth-docs repo

**Comment by WhyldWanderer** [comment]
I think the infographic should be there also... I was thinking we can have one for project verification rounds and one for givbacks rounds for each document accordingly.

**Comment by divine-comedian** [comment]
double review! left some comments

**Comment by ForestSoleil** [comment]
Reviewed updates to the pv doc and made a few super minor edits. Looks great!

**Comment by laurenluz** [comment]
@WhyldWanderer let me know when this is live, I need to fix the links in the GIVbacks blog post

Ashley will add in graphics about dates to doc when ready from catarina

**Comment by WhyldWanderer** [comment]
GIVbacks doc is updated... just waiting on a place to put the project verification one.. @divine-comedian

**Comment by divine-comedian** [comment]
https://docs.giveth.io/dapps/projectVerification LIVE
