### ISSUE TITLE
Add weird stake/wrap GIVgarden staking 100% pool on GIVfarm

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#421]
as per: https://github.com/Giveth/GIVeconomy/issues/395

**Comment by divine-comedian** [comment]
add to Gardens documentation - 

wrapping contract in gardens function is approve then wrap instead of permit - that is why we always need to approve then stake while staking GIV in the GIVfarm

**Comment by divine-comedian** [comment]
clarify that GIVfarm and GIVgarden wrapping tokens is the same thing inside of giveth documentation

**Comment by divine-comedian** [comment]
LIVE - https://docs.giveth.io/giveconomy/givfarm#givfarming-the-givgarden
