### ISSUE TITLE
Create email to project owners who received a GIVdrop

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#422]
Anyone who created a project before Dec 10th received a GIVdrop.
I think we should inform these users that might not follow us on social media or Discord.

This issue is blocked by the claim UI not allowing users to connect with their torus accounts.
Once we have torus integration I will send an email.

**Comment by laurenluz** [comment]
@WhyldWanderer can you test on production?

**Comment by laurenluz** [comment]
@WhyldWanderer did we send this out?

**Comment by WhyldWanderer** [comment]
Received email list... will send out in the morning

**Comment by laurenluz** [comment]
ready to close?

**Comment by WhyldWanderer** [comment]
yes!
