### ISSUE TITLE
Get on gnosis chain as ads!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#424]

**Comment by laurenluz** [comment]
From Mojmir on telegram:

Below is the offer for Giveth. It is up to you if you want to use only #1 or only #2 or both. Everything is free of charge. 

We can add your Ads into the xDai instance of BlockScout. In case you are interested, below is what we need from you in order to do so: 

1. Text ads 

- Name
- Logo in svg
- Text, 120 characters max
- CTA (button text, 20 characters max)
- URL

2. Banner ads

- It’s a graphic banner, can be static or animated. Static format: JPG, PNG. Animated format: GIF, HTML5
- Size: 728x90 for desktop ads and 320x100 for mobile ads
- Creatives should contain project logo, name, title, CTA
- Examples can be viewed at https://blockscout.com/xdai/mainnet/
- URL

Please let me know if you have any questions or something is not clear.

**Comment by laurenluz** [comment]
Text ad:
- Name: Giveth
- Logo in svg: https://raw.githubusercontent.com/Giveth/giveth-design-assets/3afd519e74fd56e14ef75d7f02712a73b94a109c/02-logos/GIV%20Token/GIVToken_360x360.svg
- Text, 120 characters max: Building a culture of giving that rewards & empowers those who give - to projects, to society, & to the world
- CTA (button text, 20 characters max): Join the GIVeconomy
- URL: https://giv.giveth.io/

**Comment by laurenluz** [comment]
For the banner ad, @rodricastillo9013 is going to help us!

**Comment by rodricastillo9013** [comment]
![Gnosis Ads 1](https://user-images.githubusercontent.com/61791380/149393038-24523013-e58c-4952-9ec0-76b5d01973d7.gif)

What do you think? I have adjusted the timings and animations.

**Comment by rodricastillo9013** [comment]
Option 2! Wdyt? @laurenluz
![Gnosis Ads 2](https://user-images.githubusercontent.com/61791380/149562446-2438e1bf-e7c4-4bc3-98d6-a309588c2534.gif)

**Comment by rodricastillo9013** [comment]
@laurenluz hello! do you have any feedback on this?
![Gnosis Ads 2](https://user-images.githubusercontent.com/61791380/149765293-70525d3e-f68a-4f2c-bf68-cd59693c48b6.gif)

**Comment by laurenluz** [comment]
They're great @rodricastillo9013 !! Let me send it to my contact and see if the size and length is ok.

I'm going to go with option #2 :)

**Comment by rodricastillo9013** [comment]
ok perfect, let me know if it's ok, I have to create it in a smaller format.

**Comment by laurenluz** [comment]
@rodricastillo9013 he said that it was too big, but they are going to try to make it work.

I am waiting to hear back to see if we need to resize or not, will let you know.

FYI - he sent me this information regarding size
![image](https://user-images.githubusercontent.com/75490971/150201083-45fa0ba4-df85-4c95-b662-5db41ad81172.png)

**Comment by rodricastillo9013** [comment]
ok! @laurenluz otherwise I will try to reduce the time and make it lighter. Thanks :)

**Comment by laurenluz** [comment]
Hey @rodricastillo9013 can you send me the animated banner sized 320x100 for mobile ads?

**Comment by rodricastillo9013** [comment]
yes I will prepare it! and I will send it to you

**Comment by laurenluz** [comment]
Thank you!

**Comment by rodricastillo9013** [comment]
![Ads 320x100px](https://user-images.githubusercontent.com/61791380/152831200-d477b506-b55a-4f81-bcf5-798780eff018.gif)

Done! :)

**Comment by laurenluz** [comment]
Thank you @rodricastillo9013 !

**Comment by laurenluz** [comment]
This is live!!
