### ISSUE TITLE
Add to code of conduct

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#429]
Need to add to discord & to the forum..

Currently it looks like this: https://forum.giveth.io/t/forum-guidelines-and-code-of-conduct/137

We should add this, I think as #4 (and bump up all the other numbers)

--> 4. Please only chat or post a comment if you are adding value to the conversation. No excessive or repetitive use of one-word comments allowed.

@WhyldWanderer what do you think?

**Comment by WhyldWanderer** [comment]
I think it looks great! I will add it now..

**Comment by WhyldWanderer** [comment]
Discord and Forum have been updated
