### ISSUE TITLE
Create boundaries with the discord/twitter army

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#430]
@ForestSoleil to write best practices & get feedback from crusher

@WhyldWanderer to support & explore the shillers' discord

**Comment by ForestSoleil** [comment]
Here's the google doc I created for communication agreements and best practices. 

https://docs.google.com/document/d/1Kcx13dUMoH2HZRj9ha9VDnQLrvYAu9lTinhT3fs4ANY/edit?usp=sharing

Sharing with Crusher now for feedback. Will implement his feedback into the google doc then look for QA from our comms team before we push this live.

**Comment by ForestSoleil** [comment]
In active communication with crusher (aka Erik)

**Comment by laurenluz** [comment]
Can connect with heather because she has some helpful resources

**Comment by ForestSoleil** [comment]
This Giveth Community Communications Guide is ready for QA: https://docs.google.com/document/d/1Kcx13dUMoH2HZRj9ha9VDnQLrvYAu9lTinhT3fs4ANY/edit#

@WhyldWanderer @laurenluz @divine-comedian

**Comment by divine-comedian** [comment]
@Brodyann7 here's a good first issue for you

**Comment by ForestSoleil** [comment]
This has been reviewed by Heather (Hanners). Anyone else want to take a look to qa? @Brodyann7

**Comment by laurenluz** [comment]
@Brodyann7 reviewed! 

@ForestSoleil to put in markdown formatting... @divine-comedian will share the googles doc extension to do it automatically

**Comment by laurenluz** [comment]
Can put this in the docs under "What is Giveth"

**Comment by ForestSoleil** [comment]
Downloaded the markdown add on extension for google docs so that output is featured on the right hand side now. Is this how i was meant to do it @divine-comedian ?

https://docs.google.com/document/d/1Kcx13dUMoH2HZRj9ha9VDnQLrvYAu9lTinhT3fs4ANY/edit

**Comment by divine-comedian** [comment]
> Downloaded the markdown add on extension for google docs so that output is featured on the right hand side now. Is this how i was meant to do it @divine-comedian ?
> 
> https://docs.google.com/document/d/1Kcx13dUMoH2HZRj9ha9VDnQLrvYAu9lTinhT3fs4ANY/edit

the output will only show on your computer - you can copy paste it or I can just copy your doc and run the extension on my comp when this document is ready to be uploaded

**Comment by ForestSoleil** [comment]
Yes it is! Thanks Mitch

**Comment by divine-comedian** [comment]
live! - https://docs.giveth.io/whatisgiveth/communityCommsGuide
