### ISSUE TITLE
Improve Giveth Basics Contributors Guides

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#432]
https://www.notion.so/Giveth-Basics-bff76dceaec64839b73aa89ba2fb8be4

https://forum.giveth.io/t/starting-kit-for-new-contributors-in-development-wg/235

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0a02ac16-96a8-425b-858b-285eb3bea123)

**Comment by laurenluz** [comment]
https://miro.com/app/board/uXjVOYaa00Y=/

**Comment by laurenluz** [comment]
will make separate guides for difference WGs

**Comment by laurenluz** [comment]
@Brodyann7 @danelsuga you might want to check this out too for reference! https://docs.giveth.io/dapps/contributors

**Comment by danelsuga** [comment]
Thank you!
