### ISSUE TITLE
Get rid of contentful

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#434]

**Comment by laurenluz** [comment]
@markoprljic @mateodaza @MoeNick - is this something we could make happen in the new typescript version?

The comms team loathes contentful

**Comment by MoeNick** [comment]
> @markoprljic @mateodaza @MoeNick - is this something we could make happen in the new typescript version?
> 
> The comms team loathes contentful

Yeah we make it in that repo . you can see the draft here: https://typescript.giveth.io/about

**Comment by MoeNick** [comment]
Feel free to create issue under this Epic: https://github.com/Giveth/giveth-io-typescript/issues/31

**Comment by laurenluz** [comment]
done! https://github.com/Giveth/giveth-io-typescript/issues/56

**Comment by mateodaza** [comment]
I love this issue. I know @WhyldWanderer will appreciate this sooo much 😆 

I'll keep the conversation going on the other issue. Let's propose better alternatives
