### ISSUE TITLE
Add "proposals" category to the forum

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#435]
Sem made a great suggestion... copy/pasting here:

In 1hive we have a category called proposals with a prefilled template, I adapted it for giveth:
...

## Proposal Information
**Proposal description:** 
*An accurate and detailed description of what you are proposing*

**Proposal Rationale** 
*Detailed rationale for why this proposal exists and should matter to GIV holders, the Giveth community, and/or giving ecosystem*

**Expected duration or delivery date (if applicable):**
*How long do you think it will take to deliver on your proposal* 

## Team Information (*For Funding Proposals*)
**Names, usernames, and/or relevant social links for team members (Twitter, Github, Giveth Forum, etc.):**

**Skills and previous experience in related or similar work:**
*What are some of your skills or related experience that might help inform GIV holders about your ability to execute on your proposal* 

## Funding Information (*For Funding Proposals*)
**Amount of GIV requested:**

**Ethereum address where funds shall be transferred:**

**More detailed description of how funds will be handled and used:**

...
I think it could be interesting for the giveth forum, could you add it? Here is some more info: https://meta.discourse.org/t/what-are-topic-templates/38295

**Comment by laurenluz** [comment]
should check to see if it's in-line with governance process document

**Comment by laurenluz** [comment]
so I added the "About the proposals" category section (cut from gov process): https://forum.giveth.io/t/about-the-proposals-category/297

And a "proposals template" section: https://forum.giveth.io/t/proposal-template/303/2

Do you like it @WhyldWanderer @divine-comedian ?

If we like it, I think we should communicate this in our next gov call to everyone

**Comment by WhyldWanderer** [comment]
I like it! I think this setup is definitely better than how it was...
And yes we should let people know in the #governance channel as well as on the call in case some aren't present this week.

Lets see what Mitch thinks and move forward with this

**Comment by divine-comedian** [comment]
sounds good!
