### ISSUE TITLE
Tweet thread for hiring for open positions

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#437]
To post in other people's jobs boards!

**Comment by laurenluz** [comment]
We should go into the docs and update them so that the listed date is up-to-date!

**Comment by laurenluz** [comment]
we have: https://giveth.recruitee.com/

when it is ready, we should shill this link!

change the docs jobs section to giveth recruitee when this is ready

@ahmadabugosh keep us posted when we should start to share this!

**Comment by laurenluz** [comment]
@ahmadabugosh @ heather (why can I' find your github 🤔 ) - do you want to set me up with a tweet thread that I could share from giveth regarding most important roles and maybe some info on what we're looking for?

Could be a thread with like... one tweet per role

**Comment by jfbtheii** [comment]
Yep, @ahmadabugosh. I'll get going on that today.

**Comment by jfbtheii** [comment]
https://docs.google.com/document/d/1kaK_1zSdNvulQ2U6xJVZXXBSDLG5oOY44w4QYt6DL4o/edit

Here is the general outline for the thread. There is a lot of material for each job description. What aspects of the job descriptions should I be including in each tweet? @ahmadabugosh @laurenluz

**Comment by jfbtheii** [comment]
https://docs.google.com/document/d/1SNUvjA39nEj9WrRZKOAkXzcSZsAbI2YNF9d_Wdpg634/edit 
Here are the open positions thread link. I'll reach out to Heather via discord to get her take on this @ahmadabugosh @laurenluz

**Comment by laurenluz** [comment]
Hey @jfbtheii I just sent it to Heather on telegram - will wait for her eyes on it before I hack much. In the meantime, can you add some fun emojis? They are especially nice at the start of sentences.
