### ISSUE TITLE
Narrative/meme - Make more memes!!!!

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#44]
It's essential that we have the best giving memes. This is a requirement

**Comment by Danibelle** [comment]
tax deductions without taxes or governments!
Deduction is negative, PROduction is a positive - give for anyone, any where in the world
"Back to the Future" no deductions..
Brand Giveth as the Giveth Lego - use our economic blocks to build your project

Karma farming - how to memify ..
Panvala tried this, we need better memers to make this - get funny, be like Doge Giv Token

Exit to the Community - here's a way to give to the community

Do good, hodl token..

**Comment by divine-comedian** [comment]
I made a miro board so we can start meme storming! https://miro.com/welcomeonboard/KSgUVp4uk4ZayCFVU7I9QHyoYYG3nEPspzw4bRboF48DMp03j3rfQgGhZ0oaiKwQ

**Comment by mateodaza** [comment]
![image](https://user-images.githubusercontent.com/18689480/103663212-d977b600-4f3e-11eb-82a3-d52df2c6847f.png)

**Comment by Danibelle** [comment]
#GIV4
#GIV4Goods
#GIV4Goals
#GIV4JustCoz
#GIV4Growing
#GIV4Values
#GIV4Garbage
...

[]()![20210105_091741.jpg](https://user-images.githubusercontent.com/39466970/103663772-55193900-4f26-11eb-8545-77f19c19ff46.jpg)
