### ISSUE TITLE
How to import your Torus Wallet into Metamask

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#440]
This should be a guide in our documentation to show our torus users how to get on metamask... it's just better and the path we want to build for our users.

You can actually import your torus wallet private key into metmask and then start using metamask frm there. Seems pretty easy, but I'd love if we had this with the giveth spin and curated appropriate links to help our crypto newbie users.

I would love if we could also suggest to send this to projects when we ask them to claim their GIVdrop.

Some context to the conversation:
https://discordapp.com/channels/679428761438912522/759816279623467023/928383006568230962

@divine-comedian or @WhyldWanderer are either of you interested in taking this one?

**Comment by divine-comedian** [comment]
maybe we could rework some of these ? 

https://docs.giveth.io/torusUserGuide

https://docs.giveth.io/dapps/donatingmetamask

**Comment by laurenluz** [comment]
yeah!

also we can add:
- when you're using torus, you need to lower shields on brave

**Comment by laurenluz** [comment]
@scottbenjd @csggene3 to collaborate!

**Comment by scottbenjd** [comment]
Here's the link to what we have so far. Any comments or suggestions are welcome! Please let me know what the next steps are.

https://docs.google.com/document/d/1aNaV4oOdGkYAX8jYw_hCmw6YA6CqP7vs1kk7U9vvRzI/edit?userstoinvite=csggene3@gmail.com&actionButton=1#heading=h.kbia2qduegm

**Comment by laurenluz** [comment]
This is great @scottbenjd @csggene3!! Thank you so much. I fussed with the intro a little bit to give more context (since the purpose is to help newbies) and made a few small suggestions.

FYI - for our documentation, we use markdown formatting so that it's easy to upload to docs.giveth.io - that's why I made some suggestions on link formatting etc. 

Next steps:
1. go through the suggestions and make final edits
2.  come up with some logical suggestion on perhaps where this doc should go in the tree structure of our docs, what it should be called, and maybe add a little something to this [Torus User Guide](https://docs.giveth.io/dapps/torusUserGuide) which connects the two pieces
3. make a comment here when all that's done and tag Mitch who can upload it and make everything fit 🙌 

Re: lowering the shields... I think this makes most sense to add as a small section in the Torus user guide, so I will add that to the other issue and assign you and Gene

**Comment by laurenluz** [comment]
@WhyldWanderer to do final review

**Comment by scottbenjd** [comment]
@divine-comedian was thinking this could go in the Wallets section as its own article between "Donating fiat via the Torus on-ramp"  and "Donating with MetaMask"

**Comment by WhyldWanderer** [comment]
I gave this a final review... its looks good!
@divine-comedian this one can go up!

**Comment by divine-comedian** [comment]
https://docs.giveth.io/dapps/importTorusMM LIVE
