### ISSUE TITLE
Goldem Foundation Interview - written

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#441]
Marta Brewer reached out to me for an interview similar to: https://golem.foundation/2021/12/03/interview-HQureshi.html

Will answer the questions in a google doc & get some QA

https://docs.google.com/document/d/1hmnYXbQYCJS9n5RM031cqQOUqdMF3bVgjwOIY4viDTM/edit

**Comment by laurenluz** [comment]
@WhyldWanderer @Brodyann7 @divine-comedian - would really appreciate it if one or two of you could do a little QA on this! Her questions are in italics and my answers below. 

https://docs.google.com/document/d/1hmnYXbQYCJS9n5RM031cqQOUqdMF3bVgjwOIY4viDTM/edit

**Comment by WhyldWanderer** [comment]
Reviewed! I left some comments in the doc.
Thanks for doing this @laurenluz!

**Comment by Brodyann7** [comment]
Also left suggestions. Great article @laurenluz

**Comment by laurenluz** [comment]
Thanks for the review @WhyldWanderer @Brodyann7 !!

I made changes based on your comments and suggestions and submitted it! Will post here when it's live

**Comment by laurenluz** [comment]
Waiting on Marta to hear back... I ask her to share w me when it's life so I can tweet it

**Comment by laurenluz** [comment]
https://twitter.com/GolemFoundation/status/1496163464250806277
