### ISSUE TITLE
Update Giveth LinkedIn

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#442]

**Comment by laurenluz** [comment]
reached out to Ekene

**Comment by laurenluz** [comment]
@WhyldWanderer has owner access

**Comment by laurenluz** [comment]
Ekene offered many tips about how to maintain linkedin

**Comment by laurenluz** [comment]
Makeover is a WIP! https://www.linkedin.com/company/givethio

Ann is workin' on it :) will put future post drafts in github and tag the team for QA for the next months until mastering the Giveth voice

**Comment by WhyldWanderer** [comment]
@Brodyann7 How much of this issue has been completed? Does it need any more updates?

**Comment by Brodyann7** [comment]
The makeover is done, but someone needs to maintain the linkedin page
