### ISSUE TITLE
Update Gnosis Chain brand assets

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#444]
Got a message from their comms person - we should update this wherever we have xDai logos!

FYI @markoprljic @mateodaza @MoeNick 

> Hey! 
> 
> I am sending you Gnosis Chain brand assets to update it in your materials. Please find the zip file attached. The main color is green one.
> 
> Additionally, there is a second zip file that contains brand assets for the xDai stablecoin (native token of the Gnosis Chain). 
> 
> Let me know if you have any questions, thank you!

**Comment by laurenluz** [comment]
[Gnosis Chain Brand Assets.zip](https://github.com/Giveth/giveth-planning/files/7830466/Gnosis.Chain.Brand.Assets.zip)

**Comment by laurenluz** [comment]
https://drive.google.com/drive/folders/1XoRh5fruJYPRNr4XG33XyFumlm_-1U8R?usp=sharing

**Comment by WhyldWanderer** [comment]
https://drive.google.com/drive/folders/1XoRh5fruJYPRNr4XG33XyFumlm_-1U8R?usp=sharing

**Comment by markoprljic** [comment]
@laurenluz Should we change the network logo to be GNO instead of xDAI?

**Comment by markoprljic** [comment]
![Image 2022-01-14 at 7 07 39 pm](https://user-images.githubusercontent.com/5704285/149564039-31a0d3da-afe5-42e1-8c92-59f68dce0554.jpg)

Updated here. The rest of the screens will be update soon as @mosaeedi makes the update in the design system figma file and publishes new library.

**Comment by laurenluz** [comment]
I think we should... but we need to update it everywhere. if we're updating the logo, we should update all the "please switch to xdai network" thing. There's an issue for this in the giveconomy repo https://github.com/Giveth/GIVeconomy/issues/402

**Comment by markoprljic** [comment]
@mosaeedi Can you please update the xDAI brand in GDS and push new library changes so all components are updated? When done please inform us here and close the issue.

**Comment by mosaeedi** [comment]
GDS is updated. I was checking the files too, it's updated there too.
