### ISSUE TITLE
POAPs for every GIVback round!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#446]
@playingleela is down to work on designs
@paxthemax is down to help with the smart contracts

What we need is a clear action plan/spec

**Comment by laurenluz** [comment]
FYI @markoprljic

**Comment by paxthemax** [comment]
@laurenluz Do we have an idea on the number of people eligible for rewards at this time?

**Comment by laurenluz** [comment]
@mendesfabio is going to work on a dashboard of analytics for that information in https://github.com/Giveth/GIVeconomy/issues/444 this will be helpful for the future!

@mohammadranjbarz can you tell us how many eligible people were in GIVbacks round 1?

**Comment by laurenluz** [comment]
FYI we'll only be able to recognize unique addresses, not unique people... if we're going to make a habit of distributing NFTs (not just POAPs...) we should integrate BrightID or proof of uniqueness....

**Comment by mohammadranjbarz** [comment]
> @mendesfabio is going to work on a dashboard of analytics for that information in [Giveth/GIVeconomy#444](https://github.com/Giveth/GIVeconomy/issues/444) this will be helpful for the future!
> 
> @mohammadranjbarz can you tell us how many eligible people were in GIVbacks round 1?

It's not finalized yet, but for now it's about 912 ( it may change a little)

**Comment by laurenluz** [comment]
@WhyldWanderer thinks a poap is the easiest thing to do

@markoprljic can you assign someone to design a poap for us?

**Comment by markoprljic** [comment]
Catarina and/or Rodri.

**Comment by laurenluz** [comment]
Great. So the vision is:

Give every donor in each GIVback round a POAP!

POAPs are like this: https://poap.delivery/hatch-tech-holder
and we can distribute them to everyone who donated.

First, we need designs. Maybe something with the GIVback hands... the one with the heart or the hands passing the token. Maybe we can pull elements from the swag (lots of nice GIVbacks stuff in there)

It would be really nice to make this scalable... so we just change something small like the round number or border colour... then we can make it easy so that every 2 weeks we have a new one.

We can revisit the design and update it after some months, but it would be good if we had them ready to go for at least 6 months.

@rodricastillo9013 @playingleela

**Comment by playingleela** [comment]
amazing lauren! gonna send you tomorrow the first ones, i think
 rodri is also preparing something (:

**Comment by playingleela** [comment]
hey everyone! I did some options for poaps, let me hear what you think ((:
![poap_01](https://user-images.githubusercontent.com/94190369/149556858-cc02999e-3810-490e-8e28-edfe322d442d.png)
![poap-02](https://user-images.githubusercontent.com/94190369/149556875-3985f409-9e7c-4a1c-820f-833e762d5280.png)
![poap-03](https://user-images.githubusercontent.com/94190369/149556885-a19c0fea-552e-4ae4-b051-374053c3bea0.png)

**Comment by laurenluz** [comment]
Hey @playingleela - they looks super cool, but I think poaps should be round, I've never seen a square poap. Check with acidlazzer for the specs on the size - he has experience making them for the TEC. My picture has some examples.

Also, let's avoid using the bees & tractor in these... GIVbacks doesn't have much to do with 1hive or the GIVfarm. Flowers are ok, but I would make the focus on the hands and coins.

Could you make some revisions? Make them round, maybe a little less detailed since they will be small, remove the bees & tractors :)

![image](https://user-images.githubusercontent.com/75490971/149564302-8572c07a-c5f7-4d3d-abb6-9e43bed3daaa.png)

**Comment by playingleela** [comment]
thank you so much @laurenluz for the feedback!! ah yes, I see.. Manuel told me the size should be 500x500 but I didnt know about the circle thing, I will check with him and I will work on the changes ((:

**Comment by rodricastillo9013** [comment]
![POAPS-24](https://user-images.githubusercontent.com/61791380/149597573-fd3c5aef-3962-4622-8c2c-1ac6d97d18c5.png)
![POAPS-25](https://user-images.githubusercontent.com/61791380/149597582-c265a7cd-826f-4ea2-b750-be1ee5183001.png)

Hi team! here attached some proposals based on feedback. Can we use gif?

**Comment by rodricastillo9013** [comment]
![POAP 3](https://user-images.githubusercontent.com/61791380/149597787-703083fd-3061-4f9a-8bbb-ce982857e8eb.gif)

**Comment by paxthemax** [comment]
@laurenluz what are your thoughts on the actual NFTs we distribute? Do we just do POAPs or do we want something more wild? :star_struck:

**Comment by rodricastillo9013** [comment]
Hi team! :) have some feedback for this?

**Comment by playingleela** [comment]
hey everyone, here are the changes based on the feedback, let me know if its good, so we can prepare the next rounds ((: thank you!
![POAPS_01](https://user-images.githubusercontent.com/94190369/149775061-5f2ba7b9-74b5-40b2-b47b-d48241f58b56.png)
![POAPS-02](https://user-images.githubusercontent.com/94190369/149775071-0c8e29d4-6b0b-4bb7-81ae-ee197d1c9412.png)
![POAPS-03](https://user-images.githubusercontent.com/94190369/149775076-85dbe538-f3d2-4366-9ad3-acaed5790e94.png)

**Comment by laurenluz** [comment]
@markoprljic can you give your feedback on what we should move forward with? my favourite is the round 1 one from Rodri, and in general, I think they look nicer with a little less background detail - because they will be small.

Maybe we just go with a design like that one and make all the future rounds the same but in different colours?
Or do you think it's worthwhile to have new designs for every round?

**Comment by laurenluz** [comment]
@paxthemax we chatted about this with the comms team and though just to do POAPs to keep things simple. I really don't have any experience with NFTs though, but I think it would be awesome to do something a little extra!

What are your suggestions?

**Comment by markoprljic** [comment]
@playingleela @rodricastillo9013 Do you have all these in Figma?

**Comment by markoprljic** [comment]
> @markoprljic can you give your feedback on what we should move forward with?

I'd work a bit more on this just to make one solid version we can go with and change colors for next few rounds. However, we will soon run out of colors and will need to start creating designs such as Catarina provided.

**Comment by rodricastillo9013** [comment]
@markoprljic no, we have worked in illustrator, I will add them to figma without problem

**Comment by rodricastillo9013** [comment]
@markoprljic https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?node-id=396%3A416

**Comment by markoprljic** [comment]
Great! Thanks @rodricastillo9013 
@playingleela can you please do the same as Rodri?

**Comment by playingleela** [comment]
sure, just imported there @markoprljic

**Comment by playingleela** [comment]
https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?node-id=396%3A416

**Comment by playingleela** [comment]
hey everyone! hope you are doing good! wdyt of those versions? and should we keep this color scheme? or make each one a different color? thanks!
<img width="500" alt="POAP ROUND 8 (1)" src="https://user-images.githubusercontent.com/94190369/149987452-f039f610-cbae-4345-84f6-d00813932c8d.png">
<img width="500" alt="POAP ROUND 5 (1)" src="https://user-images.githubusercontent.com/94190369/149987465-21c1a73b-d26c-412a-867f-4cd3e657f203.png">
<img width="500" alt="POAP ROUND 6" src="https://user-images.githubusercontent.com/94190369/149987484-461da09f-f3d4-4471-a052-01d36f81dbb6.png">

**Comment by markoprljic** [comment]
I like these! @playingleela Some minor cleaning up to make pixels look nice but I'd go with these. 
@laurenluz Please review.

**Comment by laurenluz** [comment]
They are great! @paxthemax do you know how to actually make these POAPs and distribute them?

**Comment by playingleela** [comment]
nice! (:

**Comment by playingleela** [comment]
![Frame (2)](https://user-images.githubusercontent.com/94190369/150005524-e8aec913-271a-4247-9deb-3111d3fc4ae5.png)
![Frame (3)](https://user-images.githubusercontent.com/94190369/150005541-a2c244a3-b213-4040-b6ec-ac2b21ec6992.png)
![Frame (4)](https://user-images.githubusercontent.com/94190369/150005558-89aa7c2d-2716-4620-9d44-e08b12ad502e.png)
is it better now @markoprljic?

**Comment by playingleela** [comment]
good morning everyone!  round nr 3 was updated, so here it goes (: tks @markoprljic

![Frame (7)](https://user-images.githubusercontent.com/94190369/150092851-dfb4805d-177d-4ae6-97ec-13f79f0d644c.png)

**Comment by laurenluz** [comment]
@WhyldWanderer knows how to make these into POAPs
- you can say how many links you need (so it's a new link for each user)... can't send a unique link in each email
- how to distribute them?

@WhyldWanderer to ask @Vyvy-vi or Acidlazzer for tips

**Comment by playingleela** [comment]
hey everyone! there were some little changes on the poaps, here it is the final versions 
![Frame 2 (2)](https://user-images.githubusercontent.com/94190369/150402607-a88c51aa-4fc6-4c09-87d1-01a4132c2b30.png)
![Frame (8)](https://user-images.githubusercontent.com/94190369/150402617-094a66db-5fd2-43c8-b4c4-dcd3af58e6a7.png)
![Frame (9)](https://user-images.githubusercontent.com/94190369/150402630-c7244826-8a19-4390-8a44-c7fcb8a9c9a6.png)

**Comment by WhyldWanderer** [comment]
Round 1 POAP is claimable here: https://poap.delivery/givbacksround1

**Comment by markoprljic** [comment]
> Round 1 POAP is claimable here: https://poap.delivery/givbacksround1

Should we be sending out an email blast to all projects inviting them to claim it?

**Comment by laurenluz** [comment]
We are! @WhyldWanderer put it in the email telling projects their GIVbacks are ready to claim

**Comment by laurenluz** [comment]
oh wait! I just checked and it's not in the email. @WhyldWanderer can you add the new one for the email for round 2?

**Comment by WhyldWanderer** [comment]
My bad! I realized about 1/3 of the way through the list that it wasnt in there... so I think only like 20 emails went out without the link for round 1... I will definitely be sure to add it in round 2 for all emails.

**Comment by laurenluz** [comment]
you da best @WhyldWanderer <3

**Comment by laurenluz** [comment]
Hey @rodricastillo9013 or @playingleela - can one of you help to set up the next 3 rounds of poaps?

**Comment by playingleela** [comment]
hey @laurenluz of course, I will start it rn

**Comment by playingleela** [comment]
here it goes:
<img width="500" alt="Frame (10)" src="https://user-images.githubusercontent.com/94190369/151773851-73ac1d41-d2c1-4a5a-a89e-32cfdcf7ff13.png">
<img width="500" alt="Frame (11)" src="https://user-images.githubusercontent.com/94190369/151773863-46c094ed-32b4-4252-bdbc-344a9e863916.png">
<img width="500" alt="Frame (12)" src="https://user-images.githubusercontent.com/94190369/151773876-a782f44c-5839-4706-ae33-730e68f00b00.png">

**Comment by laurenluz** [comment]
They're awesome!! Thanks @playingleela 

If they're good w you @markoprljic we can just use these.

**Comment by playingleela** [comment]
@markoprljic let us know if these POAPs needs any changes, thanks!

**Comment by markoprljic** [comment]
All good on my end.

**Comment by laurenluz** [comment]
hey @playingleela is there a link to the figma where these all are?

**Comment by playingleela** [comment]
yess @laurenluz its here: https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?node-id=396%3A416

**Comment by playingleela** [comment]
the last line/frames are the final versions

**Comment by WhyldWanderer** [comment]
POAP for GIVbacks Round 3: 
https://poap.delivery/givbacksround3

**Comment by WhyldWanderer** [comment]
POAP for GIVbacks Round 4:
https://poap.delivery/givbacksround4

**Comment by laurenluz** [comment]
@rodricastillo9013 We will need new designs for Rounds 7 , 8 , 9 - can you help with that?

**Comment by rodricastillo9013** [comment]
hi @laurenluz ! yes we are working on this! today or tomorrow I will share the link with the new designs

**Comment by rodricastillo9013** [comment]
hi @laurenluz here yo can see the new POAPs. 
https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?node-id=396%3A416
if you have any feedback let me know :) thanks

**Comment by laurenluz** [comment]
I think they're great! Can you share them as pngs in this issue? I think that makes it easier for @WhyldWanderer or @scottbenjd to make them into POAPs.

**Comment by rodricastillo9013** [comment]
yes no problem! I prepare it! and share here

**Comment by scottbenjd** [comment]
Do you have a link to the week 12 POAP? @rodricastillo9013
I see it on the figma board but need the png. Looks great btw!

**Comment by rodricastillo9013** [comment]
![Captura de Pantalla 2022-06-16 a la(s) 14 19 33](https://user-images.githubusercontent.com/61791380/174068172-6503f160-3b86-4b4c-8643-cf6a79a3fed3.png)

**Comment by scottbenjd** [comment]
okay @rodricastillo9013 thanks! I'm personally a fan of v3 but I'll let other weigh in.

**Comment by WhyldWanderer** [comment]
POAPS can be found here:
https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?node-id=396%3A416

Sorry I didnt see the above comments until now... do we still need this issue?

**Comment by laurenluz** [comment]
@WhyldWanderer do you think we can close this issue? is it embedded in our other flow better now?
