### ISSUE TITLE
NFTs for Givers/community members

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#447]
@markoprljic has an idea in the discord:

> How about we create a collection of Giveth NFTs on Opensea and all proceeds from sales go to fund our development?
> Additionally we can create some "Giver"  "Supporter" and such NFTs and give them to donors and community members.

I think we don't need to collect funds for development since we have the economy but it's worth brainstorming having NFTs and giving them to donors or minting them and proceeds going to projects.

This is issue is for brainstorming

**Comment by WhyldWanderer** [comment]
I created a forum post discussing incorporating NFT's here: https://forum.giveth.io/t/givcuration-and-nft-incorporation-ideas-brainstorming/289

Could also be a good place for brainstorming.

**Comment by playingleela** [comment]
hey everyone @WhyldWanderer @laurenluz (: @markoprljic mentioned about the NFTs and I just read the forum Ashley created, I really like the idea so I will start to sketch the levels and as soon as I have something I will send it over so we can discuss if its the right direction. so for the first level I will start with something more simple around the logo as its mentioned in the forum and the next ones, something growing up in the aesthetics as a representation of achieving a phase/next level. If you have any more ideas of what you all would like each level to be, let me know (: thank you!

**Comment by playingleela** [comment]
hey @WhyldWanderer @laurenluz @markoprljic I hope you are doing good!
I started a first round of the levels, let me hear your feedbacks (: 
<img width="3000" alt="NFT  1 1 (1)" src="https://user-images.githubusercontent.com/94190369/150967068-2da804dc-82ed-4e5c-a9db-a36f84a80216.png">
![NFT  2 1](https://user-images.githubusercontent.com/94190369/150967082-2d0de516-047b-4707-9185-cef5983c0a81.jpg)
<img width="3000" alt="NFT  3 1" src="https://user-images.githubusercontent.com/94190369/150967096-aa80832c-291d-46f0-a66f-fc0666b27697.png">

**Comment by markoprljic** [comment]
Those should look like accomplishment badges that I'd be proud to own in my collection. Similar to what Gowalla app did many years ago, and a lot of games are doing these days. The mockups above don't really convey that :/
I suggest we do a pinterest collection for inspiration and go from there?

**Comment by playingleela** [comment]
sure, let's do it @markoprljic

**Comment by playingleela** [comment]
hey everyone, I did a new round. here it goes (:
![NFT  2 1 (1)](https://user-images.githubusercontent.com/94190369/151553167-4dc3fe0f-45c1-446e-b416-9e7c24d1107b.jpg)
<img width="3000" alt="NFT  3 1 (2)" src="https://user-images.githubusercontent.com/94190369/151553203-1d5d66a2-8774-4dad-bcd3-eef2c2b8c9f2.png">
![NFT  3](https://user-images.githubusercontent.com/94190369/151553237-a974a98c-6f6b-4b48-be40-e89c81e4ab6d.jpg)

**Comment by markoprljic** [comment]
These illustrations look nice! :)
Not sure we need the numbers though since those were for the GIVbacks rounds. For the NFT's we don't need that. 

Overall, this is a nice direction. Well done @playingleela 
What we need to do before moving forward is to define all kind of NFT's we want to mint / reward people. Once we have a list of NFT's based on a purpose then we'll be able to customise and create the rest.

@laurenluz @WhyldWanderer Ideas?

**Comment by WhyldWanderer** [comment]
Heres a few:
If I think of more, I will add them here...
- The project gets an NFT upon their first donation
- The project could receive a badass NFT once they reach a certain funding goal
- Category based NFT’s - once you donate to 3 different projects that are in the ‘animals’ category, you would receive an ‘animal advocate’ NFT or something
- First donor to a project receives an NFT
- Donors of $100 or more to verified projects in each GIVbacks round

**Comment by WhyldWanderer** [comment]
I think we can also ask the project to send in art for some of these that are specific/unique to their project...

**Comment by laurenluz** [comment]
I think we should focus on NFTs for donors instead of for projects to encourage more donors to give, and I think we should make it competitive... Definitely for starters:
- Top donors in each GIVback round gets an NFT
- Maybe we give NFTs to top 5 donors? Make the top top especially cool and rare?

If we want to make one that can be minted many times...
- NFT to donors who donate over $5000, over $10,000, etc.

@paxthemax was interested in NFT implementation, maybe he has some ideas.

**Comment by markoprljic** [comment]
Might be good to explore generative art @playingleela

**Comment by paxthemax** [comment]
I'm exploring a general purpose contract we can deploy on Gnosis chain (still getting used to that name) that should be flexible enough to serve almost any purpose we can come up with:

https://github.com/thesandboxgame/thesandbox-contracts/tree/master/src/Asset
