### ISSUE TITLE
Add turkish translation to medium

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#448]
Original article: https://medium.com/giveth/welcome-to-the-giveconomy-b3e372da63dd

**Comment by alipostaci2001** [comment]
https://medium.com/@mcb2001/giveconomy-e-hoş-geldiniz-a25a4b825658

**Comment by alipostaci2001** [comment]
I have translated " welcome-to-the-giveconomy" in turkish.
here is:
https://docs.google.com/document/d/1Q7Ca20F0z-QwIZi7-7GlVeejFd_-y65EH0mYRiykQE0/edit?usp=sharing

**Comment by laurenluz** [comment]
@alipostaci2001 can you make this doc "anyone can comment"?

**Comment by laurenluz** [comment]
@alipostaci2001 added a disclaimed to the bottom of this article, I think it is ok as-is for now. moving to done.

In the future it would be great to have approved translations submitted to the Giveth publication so that our medium followers can see them all there!

Thanks for taking the initiative on this @alipostaci2001! I think in the future if you want to contribute with more translations it would be great if you synced up with the team. There are a couple of forum posts right now proposing to make translations, maybe you could connect with one of those teams: https://forum.giveth.io/t/giveth-gitbook-translations/311

**Comment by alipostaci2001** [comment]
original link:
 https://medium.com/giveth/what-if-giving-gave-back-using-web3-to-evolve-philanthropy-a8500b7636ce
 
 turkish version:
 https://medium.com/@mcb2001/ya-bağışlar-geri-gelirse-hayırseverliği-geliştirmekte-web3ü-kullanmak-5cdd3088cb97


https://docs.google.com/document/d/1CCftL1HmZeXXMJCPZw9k8A4-47IC6aUKSplWmyplp6c/edit
