### ISSUE TITLE
Coin Market Cap "Detailed Project Description"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#450]
To apply to get listed on coin market cap, they have a bunch of requirements... one is a description of the project... Here is what they ask for:

> Our data shows that our users spend more time on pages that use descriptions that adhere to this template: https://tinyurl.com/yy2mw9v7. Recommended word count: 450 - 600 words. Provide a detailed description of your project, which may be used on the asset page (https://coinmarketcap.com/currencies/cardano/), Minimize the use of hyperbole, superlatives, and redundant statements (e.g. leading, amazing, best, first of its kind, state of the art, decentralized blockchain). It should not read like a sales pitch. Focus on factual statements about your project. Write in third-person. Be concise - avoid redundant statements. (e.g. decentralized blockchain). For example, Launched in [dd/mm/yyyy] by a team based in [country], [project] is a smart contract platform that enables developers to build decentralized applications. See https://coinmarketcap.com/currencies/cardano/.

Here is what I wrote. Would love someone else to QA this before I blast it out... @divine-comedian @WhyldWanderer 
https://docs.google.com/document/d/1RlvDjVdauHenRoFlifYENSrI_jTI-JSqpdJXm8Xo0fM/edit?usp=sharing

**Comment by divine-comedian** [comment]
left some comments, looks great though!

**Comment by laurenluz** [comment]
Thanks @divine-comedian - I incorporated your comments and submitted the form
