### ISSUE TITLE
Add to Torus documentation - lower shields

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#451]
From Mateo in the Comms channel:

> So @Comms Stars I just had a call with a torus dev and they are working on a solution to the Brave issue about needing cookies for the login. They recommend we let the users know they need to lower the "shield" protection or at least accept cookies for a couple of domains. So I was thinking the best solution for us is to make a quick post explaining this as a tutorial and just link the user to it when he/she's trying to login on Brave with torus. It's tops 3 screenshots and really straight forward I think. So yeah, sadly is the only option we have for now until they fix it. 

https://discordapp.com/channels/679428761438912522/790268394251354143/930820513520054342

**Comment by mateodaza** [comment]
This should be enough config for the shield

![msg-477140687-16378](https://user-images.githubusercontent.com/18689480/149154459-2d6160d5-1b91-4960-9164-48f5c598d64a.jpg)

**Comment by laurenluz** [comment]
@divine-comedian do you want to throw this in the torus documentation?

**Comment by laurenluz** [comment]
I think we should add this information as a section to the existing Torus documentation: https://docs.giveth.io/dapps/torusUserGuide

@scottbenjd @csggene3 do one of you guys want to take this? Check out mine and Mateo's comments in [this issue](https://github.com/Giveth/giveth-io-typescript/issues/83) for more context.

**Comment by scottbenjd** [comment]
I'm thinking this could go in the "Using the Torus Wallet" article in a new "Interacting with dApps" section right before the "More Functions" section.  Does that work?

**Comment by csggene3** [comment]
I think that spot looks ideal @scottbenjd ; in this same doc there is a "(link doc internally)" message under More Functions that looks like it needs a link inserted, but I'm not sure whether the next doc in line titled Donating with Fiat via the Torus on-ramp is what was intended. Should we just draft another small section or a separate small doc?

**Comment by scottbenjd** [comment]
https://docs.google.com/document/d/1FaonG_rT0Y-Rmaj9_3CBFWoOARz1fGcuzYcIHsk87ek/edit

**Comment by divine-comedian** [comment]
just an FYI to everyone - images don't copy from google docs to markdown - make sure you have an original copy of your image so it can be imported into the giveth-docs repo @scottbenjd  @csggene3

**Comment by laurenluz** [comment]
@laurenluz to review

**Comment by laurenluz** [comment]
Hey @scottbenjd can you make it "anyone can comment" - I can't suggest edits.

At a glance:
- We *just* updated the wallet connect thing using web3 authentic, so you need another screetshot 😉 - it looks different now
- Please stress the importance that user connects with the email/facebook/twitter... the specific account they used to create the wallet. If they set it up with facebook and they sign in with email, they won't see their funds
- Please add the photos in as markdown formatting. it looks like ![image ... some maddness]... you can use hackMD and "paste" a photo in there and it will format it right.

**Comment by scottbenjd** [comment]
@laurenluz 
Yup. I just updated the sharing setting so you should be able to comment but that's probably not necessary with your comments here. I'll pull another screenshot for the web3 authentic.

Since the pictures need to be added to the repo anyway, does the location and md formatting in the google doc matter?  

@divine-comedian 
Does it work better for you if we use the actual path used for the repo in the !{image...  formatting so that you can just drop those picture files? I can pull that path from another article.

**Comment by divine-comedian** [comment]
I got it figured out - almost ready for upload

**Comment by scottbenjd** [comment]
@divine-comedian This issue or the other Torus one (#440)? I didn't swap out the screenshot yet. Wanted to follow up with Lauren.

@laurenluz the GIVeconomy page is the only one that doesn't have the "sign in with ETH". Is that the web3 auth? 

I don't think the settings mateo included are enough to let Torus connect. I haven't been able to connect unless I completely turn off shields but may be missing something.

**Comment by divine-comedian** [comment]
https://docs.giveth.io/dapps/torusUserGuide#interacting-with-the-giveconomy LIVE 

I also added a sneaky section to the GIVeconomy 

![image](https://user-images.githubusercontent.com/67759413/150538441-f43d1837-66a7-4595-8f5d-f2eea4a0c288.png)

**Comment by laurenluz** [comment]
Nice, I just pushed some edits... the version you uploaded was missing the recent changes from Ben.

Seems good now! Moving to done.
