### ISSUE TITLE
GIVbacks article - medium article picture

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#457]
@playingleela - can you make me a banner image for this article? maybe something like the original designs your make for the POAPs? :)

https://docs.google.com/document/d/1D6-Sivr-L4Jn-tgWC6RHRNpxmhred0W_wqYarIXZZ9g/edit#heading=h.dy5g66uo0t83

@markoprljic FYI

**Comment by playingleela** [comment]
sure @laurenluz same theme of givbacks, right?

**Comment by laurenluz** [comment]
yep!! @playingleela

**Comment by playingleela** [comment]
heyy @laurenluz wdyt of something like this?? 
I made two sizes, one is cover and the other one is post outset cause I wasn't sure of which one you will use but let me know if it works or if it needs any changes ((: thank you!
<img width="1500" alt="Medium Cover" src="https://user-images.githubusercontent.com/94190369/149787872-b7c52e09-1442-433c-8fc0-62e4acf937a4.png">
<img width="2040" alt="Medium Post - Outset" src="https://user-images.githubusercontent.com/94190369/149787882-0d19bde0-980e-4a1a-a31b-f7a5323aa825.png">

**Comment by laurenluz** [comment]
Looks great! Thank you @playingleela !!
