### ISSUE TITLE
Regular tweets to announce new verified projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#459]
Would love if we could announce newly verified projects in tweet threads once per week. or once per round??

Would love it if perhaps @Brodyann7 could coordinate with @WhyldWanderer and @ForestSoleil... get a list of the newly verified projects and write short descriptive tweets about them

**Comment by Brodyann7** [comment]
@laurenluz sounds good, @WhyldWanderer gave me access to verification channel and we will synch next week and do a small onboarding session to see if I can also help out with project verification.

**Comment by WhyldWanderer** [comment]
List of projects that were approved for verification in the last round:

https://giveth.io/project/catalandao
https://giveth.io/project/cahuita-roots-regenerative-development-project
https://giveth.io/project/osmotic-funding
https://giveth.io/project/Moloch-Cloudship-0
https://giveth.io/project/all-for-climate-dao
https://giveth.io/project/gitcoin-grants-matching-pool
https://giveth.io/project/story-blanket
https://giveth.io/project/CREATING-THE-PERFECT-VILLAGES-IN-BURUNDI
https://giveth.io/project/alumnos-de-civichub
https://giveth.io/project/territorial-regeneration-in-barichara-colombia
https://giveth.io/project/commons-infrastructure-road
https://giveth.io/project/Fusion-0
https://giveth.io/project/the-river
https://giveth.io/project/perma-vida-foundation

**Comment by laurenluz** [comment]
Niiiiiice! man that's a lot. Would be great if we could include their handle on twitter for each tweet.

Do you think it's too many to share? should we highlight our favourite 5 in a thread and then tag the rest as a final shout of tweet? @Brodyann7 @WhyldWanderer

**Comment by Brodyann7** [comment]
Maybe the ones that haven't been on the project spotlight should be more prioritized?

**Comment by Brodyann7** [comment]
Why not make the world a better place starting today!? 🙌  🌏  💜

We've got a bunch of amazing new verified projects for the next round! When you become a Giver, you get rewarded with 
givbacks! 💝   
#Givethio #giveandyoushallreceive #givethforchange 

🧵 A thread: 👇 

Tweet 1: 

🌐  CatalanDAO is a collaborative effort to launch the world’s first Digital Nation DAO, where anybody, Catalan or not, can join as a digital citizen or a supporter.

https://giveth.io/project/catalandao 
@catalandaoETH

Tweet 2: 

🌱  Diamante Bridge Collective are working from a distributed ecovillage in Costa Rica, preserving surrounding lands and watersheds.

https://giveth.io/project/commons-infrastructure-road

Tweet 3: 

👩‍🌾   Regenerate Barichara is focused on regenerating an entire bioregional territory in Barichara, Colombia and are seeking to set up a learning center that focuses on the transformation of food, healing of cultural traumas, and cultivation of leadership among women in the community. 

https://giveth.io/project/territorial-regeneration-in-barichara-colombia
@cognitivepolicy 

Tweet 4: 

☀️ All for Climate DAO is a community of active citizens seeking to raise funds to support various climate-related projects and initiatives

https://giveth.io/project/all-for-climate-dao
@all4climatedao  

Tweet 5: 

🔨 'PCV Burundi’ is helping improve the living conditions in vulnerable rural communities using regenerative agriculture.

https://giveth.io/project/CREATING-THE-PERFECT-VILLAGES-IN-BURUNDI 
@MugishaParfai11

Tweet 6: (optional - if you want more engagement) 

Let us know below which of these projects you contributed to and please share this thread with your friends to help spread the love! ❤️ 🌈

**Comment by laurenluz** [comment]
I love it @Brodyann7! Thank you! I'll tweet it tomorrow if there's nothing pressing that comes up in between

**Comment by ForestSoleil** [comment]
I love this idea! Thank you for supporting, Ann!

**Comment by laurenluz** [comment]
It's LIVE! https://twitter.com/Givethio/status/1484178959797424130
