### ISSUE TITLE
Community Newsletter

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#462]
Create a draft for our community newsletter, to send out to our email database of donors and projects. This could potentially include:

- Community project spotlights: This could include a write up, graphic or video on the project we want to highlight

- Giveth community updates: Updates from Giveth and the Giveconomy. This could be updates on the project, features or initatives to get involved with.

- Content Highlight: Resharing popular or relevant content posted elsewhere (from the blog, podcast appearances etc.)

**Comment by laurenluz** [comment]
What platform would we use for this?
Can use campaign feature on autopilot, or use mailchimp or something else.

Can have a central point of contact, where everyone else sends their "newsletter worthy" things to.

Do people have to subscribe to it? How do they unsubscribe?
Initially can have people on a list - include all donors and projects... can send first one as a welcome email.

@ahmadabugosh to be central point of contact

**Comment by laurenluz** [comment]
@laurenluz @GriffGreen @WhyldWanderer @divine-comedian to send content ideas (if any) to Ahmad!

**Comment by laurenluz** [comment]
@ahmadabugosh For starters, some content we may want to include:

- [GIVeconomy Blog Post](https://medium.com/giveth/welcome-to-the-giveconomy-b3e372da63dd)
- [GIVbacks Blog Post](https://medium.com/giveth/welcome-to-the-giveconomy-b3e372da63dd
- [GIVeconomy Launch Video](https://www.youtube.com/watch?v=LEw8PaJylNA)
- [GIVeconomy Launch Tweet Thread](https://twitter.com/Givethio/status/1474425481684520976)
- [New Verified Projects Tweet Thread[(https://github.com/Giveth/giveth-planning/issues/459) - this is yet to published, but will go out soon
- [MetaView Podcast w Lauren & Economy of GIVing](https://youtu.be/VV7TmNILk6o)
- Giveth team will be at ETHDevner (Griff will have a talk for sure)
- DAOists Event in Denver Feb 15-16 (Griff and Lauren will have talks)

Every week for the community call I put together a summary of notable comms things... you could review them each month as well and pull your favourite this. @WhyldWanderer do you have a link to the folder where they're all saved?

**Comment by laurenluz** [comment]
Maybe we also want to include this awesome GIVeconomy dashboard https://dune.xyz/metacrypto/giveconomy

**Comment by ahmadabugosh** [comment]
Hey @Brodyann7, do you have a good project or case study you would recommend to highlight for our first newsletter?

**Comment by Brodyann7** [comment]
@ahmadabugosh For which round? Newest projects?

**Comment by laurenluz** [comment]
@ahmadabugosh form our meeting today:

- Want to share on Monday Jan 31st!
- Name? GIVnews
- Blast out to newsletter subscripion people & send a separate email to everyone else that says: “We’re starting a newsletter - Want in?"
- Investigate adding newsletters to docs.giveth.io so they can live in one place forever @divine-comedian maybe can help w this

**Comment by ahmadabugosh** [comment]
@WhyldWanderer I think this would be how we can add people to multiple lists (and let them unsubscribe from just the newsletter): https://support.autopilothq.com/hc/en-us/articles/204972905-Add-list-specific-subscribe-or-unsubscribe-links-to-your-emails

**Comment by laurenluz** [comment]
@ahmadabugosh if we want this to go out by the 31st, we'd need the draft ready for QA by the end of the day today. If you prepare it, please share the google doc link here and tag me :)

**Comment by laurenluz** [comment]
if not, I don't think it's criticial that we send it on Jan 31

**Comment by ahmadabugosh** [comment]
Hey @laurenluz I sent you @WhyldWanderer  and @ForestSoleil a first draft. Let me know what you think! :)

**Comment by laurenluz** [comment]
@ahmadabugosh I made edits in the doc - it's looking good! Thanks so much.

Please go through and make sure that none of the formatting gets weird w/ my suggestions... and then once you finish the edits, I think it's safe to blast off tomorrow to our newsletter subscribers.

**Comment by ahmadabugosh** [comment]
First edition sent!
