### ISSUE TITLE
GIVbacks article tweet thread

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#463]
Want to make this article into a nice tweet thread:

https://medium.com/giveth/what-if-giving-gave-back-using-web3-to-evolve-philanthropy-a8500b7636ce

**Comment by laurenluz** [comment]
@danelsuga let me know if you're down to create this! If so, you could make the tweet thread in a google doc and link it here. Tag me for QA :)

**Comment by danelsuga** [comment]
https://docs.google.com/document/d/1-Wl5ScTHUKqmRU15xeULTBFz1brkJqJY4i0lH6_Ob4Y/edit

@laurenluz

**Comment by laurenluz** [comment]
Hey @danelsuga I think perhaps I didn't explain this issue clearly. What we need is a tweet thread that summarizes the article's key points... So make it in to tweets, that are engaging, use emojis. Check out the Giveth twitter for inspiration on writing tweets.

There should be at most 10 tweets, ideally 7... like this:
1  Say what is GIVbacks, say this is a thread, add a link to the article
2-6 One tweet for each of the 5 "Big Picture" subsections
7 Some kind of closing... maybe explaining the amount available for GIVbacks, the rounds, the round we're in, or something current and relevant

**Comment by danelsuga** [comment]
Oh, sorry! OK!

**Comment by danelsuga** [comment]
OK! Updated.

https://docs.google.com/document/d/1-Wl5ScTHUKqmRU15xeULTBFz1brkJqJY4i0lH6_Ob4Y/edit?usp=sharing

I didn't included the fun stuff yet (emojis, etc.), since that seems more "in the moment" when you publish, but you can tell me. Thanks! @laurenluz

**Comment by laurenluz** [comment]
Hey @danelsuga! Thanks so much for putting this together. I left a bunch of comments in the doc.

Please have a look! I would love to make a bunch of changes to this, and I really think it's such a good learning opportunity. I hope you don't mind all the many comments, but I think it's so worthwhile to take some more time on it :)

oh also feel free to have fun w/ emojis!

**Comment by danelsuga** [comment]
Back at you for another review! @laurenluz 

https://docs.google.com/document/d/1-Wl5ScTHUKqmRU15xeULTBFz1brkJqJY4i0lH6_Ob4Y/edit

**Comment by laurenluz** [comment]
Blasted it out! Made some changes in twitter before sending

https://twitter.com/Givethio/status/1511364134729826309
