### ISSUE TITLE
New graphic for project verification rounds

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#465]
@WhyldWanderer to talk to @playingleela

**Comment by WhyldWanderer** [comment]
Basically we want to separate this graphic into two.
One for verification.. and one for GIVbacks.

This is my paint version lol.. basically we need:

**Verification:**
 - to change the text on day 1 to say "Approved projects will receive emails and 'Verified' badges"
  - to change day 7 and day 14 to normal dark blue squares
![image](https://user-images.githubusercontent.com/74267818/150244528-1eb22337-52a3-47cc-bda5-16f8e8b9e4ff.png)

**GIVbacks**
- Change day 1 to say "GIVbacks from the previous round are calculated and reviewed for fraud"
- Change day 8 and day 14 to normal dark blue squares
![image](https://user-images.githubusercontent.com/74267818/150245129-49e4ec1e-4fd9-4f86-8468-edf6d4f2b5fe.png)

Both graphics should still say "GIVbacks Rounds" at the top.
Let me know if you have questions or need more info!

**Comment by playingleela** [comment]
hey girls, got it @WhyldWanderer everything is clear (:

**Comment by playingleela** [comment]
@WhyldWanderer here it goes (: let me know if you need anything else and I will be glad help! thanks
<img width="1728" alt="Verification" src="https://user-images.githubusercontent.com/94190369/150339788-4651789e-0089-46b6-9939-886b79d1497c.png">
<img width="1728" alt="GIVBacks Rounds" src="https://user-images.githubusercontent.com/94190369/150339807-994a6439-b9cb-497b-b079-6f8e06f8e3d0.png">

**Comment by WhyldWanderer** [comment]
Perfect!! Thanks so much Catarina!!
