### ISSUE TITLE
Setup lastpass for password and access management

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#467]

**Comment by ahmadabugosh** [comment]
Hey @laurenluz please add me to the twitter account whenever you set this up (since I need it to set up Zapier crossposting)

**Comment by ahmadabugosh** [comment]
Hey @laurenluz for Lastpass, you can share passwords with multiple people if you just get one paid account (you don't need to get a business account and pay for each user). 

So if we pay just for one account for $3 a month, that would allow us to share passwords with anyone else (they just need to create a free lastpass account first) : https://www.lastpass.com/pricing (the Single Users & Families option)

**Comment by laurenluz** [comment]
Hey @ahmadabugosh - just finished setting this up.

It seems that you can share access to multiple people even with just the free account. If that turns out not to be the case we can upgrade.

**Comment by laurenluz** [comment]
Ok! I set up a lastpass for Giveth. We have:
- email
- orbit
- zapier
- cmc
- contentful
- facebook
- instagram
- linkedin
- twitter
- reddit

Should be able to do all kinds of magic sharing now.
