### ISSUE TITLE
Tweet about Giveth being a guild on MetaGame

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#468]
@WhyldWanderer if you know what this means and have ideas for the tweet, post here :)

https://my.metagame.wtf/guild/Giveth

**Comment by WhyldWanderer** [comment]
Here is the landing page: https://test.metagame.wtf/join/guild

Can probably pull something from there..
maybe meme off of the web3, pieces of "new world" puzzle, what the bigger picture looks like when all the pieces are together, collaboration in web3 space, etc?
