### ISSUE TITLE
Set up biweekly call for Community WG

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#469]
@WhyldWanderer will contact Freshelle for info and set up the call! Will start with biweekly meetings and adjust according to workload. Team will use giveth planning for issue management.

**Comment by WhyldWanderer** [comment]
https://calendar.google.com/event?action=TEMPLATE&tmeid=NTZqOG82dXZnaDEwbW50NGE3bmI4djNsYmNfMjAyMjAyMDJUMTkwMDAwWiBnaXZldGhkb3Rpb0Bt&tmsrc=givethdotio%40gmail.com&scp=ALL
