### ISSUE TITLE
Transform telegram group into a better version of itself

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#470]
- [x] make it "announcments only" so only admins can post. keep the bridge with the general channel in discord
- [x] add a pinned message with the mission statement, a link to the discord & explanation that this group is for announcements... @WhyldWanderer I wonder if we should consider changing the bridge from the general channel to the announcements channel in our discord. if you like that idea, maybe you can check w Kay?
- [x] change the "join" page message giveth.io/join to reflect the new purpose of the telegram group

**Comment by WhyldWanderer** [comment]
Telegram group is now announcements only - there is a pinned message - Kay says he would rather just close the bridge for this channel
