### ISSUE TITLE
GIVstream blog post

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#474]

**Comment by WhyldWanderer** [comment]
Suga is willing to take on the blog post with assistance from the team

**Comment by laurenluz** [comment]
Naw, I got this one. I created the issue for myself. it's a nuanced and complex concept & I need to do it, then we have it as a resource for explaining to new contributors.

**Comment by laurenluz** [comment]
Ok, written and ready for review. @danelsuga @divine-comedian maybe you can help w this?

I want to blast it out before we go live with Regen Farms

https://docs.google.com/document/d/1IzvuwLJpsvdNQb3HxcoaRvSTuACr6jAnPHXDPmF8ilM/edit?usp=sharing

**Comment by danelsuga** [comment]
Brilliant.

I found one typo.

Well done! Fire away!

**Comment by danelsuga** [comment]
Omg. Of course you did the "typo" on purpose! Ha! And the hilarious thing is that I realized that it was on purpose just as I received your message telling me. :-/ Oops. Sorry for being a dunce. And thanks! :D

**Comment by divine-comedian** [comment]
Review in progress!

**Comment by laurenluz** [comment]
This is in medium, waiting for publishing. Thanks all for the review!

**Comment by laurenluz** [comment]
https://medium.com/giveth/your-givstream-flow-into-the-future-of-giving-f6dcd3615eae
