### ISSUE TITLE
Video Minicourse - Why Giveth is the future of giving

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#480]

**Comment by ahmadabugosh** [comment]
To Do

- [ ] Create Script

 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by laurenluz** [comment]
Put together short bullet list for script: https://docs.google.com/document/d/15YMv_NS3gasx0d77Y1cA3nwhCdl_CCfTGRez1Qz66oE/edit?usp=sharing

Comments are totally welcome! Is there any key points I'm missing? @danelsuga @WhyldWanderer @GriffGreen @ahmadabugosh

**Comment by ahmadabugosh** [comment]
@laurenluz added a couple of small comments

**Comment by laurenluz** [comment]
Thanks @ahmadabugosh I put this on Griff's list for the week and scheduled time so he could record it. Will send it to you when ready. Is it ok if we send you a link to a video on youtube?

**Comment by ahmadabugosh** [comment]
Thanks @laurenluz ! Yes, a YouTube link would be great (I can easily download it from there if it needs any edits)

**Comment by laurenluz** [comment]
@ahmadabugosh here it is: https://www.youtube.com/watch?v=08qPRbDr05E

Can you edit it? :)

**Comment by ahmadabugosh** [comment]
Hey @laurenluz, I tried something a little different (putting it in a video template), since the video format wasn't that great (and it has the zoom logo). Let me know what you think: https://www.youtube.com/watch?v=tVVpRTXFmvg&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=1&ab_channel=Giveth

**Comment by laurenluz** [comment]
It's pretty cool! I kind of feel like with the format the template stuff should change to show parts of the DApp or something... but it would be a lot more to setup up, so I think it's also good as it is.

What would be nice though, is if there was a header page with the same colour/formatting as the other videos. Looks strange to see this one dark blue and all the others light.

**Comment by ahmadabugosh** [comment]
Hey @laurenluz I changed the color scheme and thumbnail, let me know if this is better: https://www.youtube.com/watch?v=kfoyvsPYnrE&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=1&ab_channel=Giveth

**Comment by laurenluz** [comment]
Awesome! Let's "ship it".
