### ISSUE TITLE
Video Minicourse - Why you should consider donating money in crypto on Giveth

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#481]
We'd like to record a short video that gets people excited about the opportunity to donate money with crypto. Some talking points would be: 1) How it's transparent 2) How it has zero fees 3) How it has network effects etc.

**Comment by ahmadabugosh** [comment]
To Do

- [ ] Create Script

 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by laurenluz** [comment]
Some more talking points:
- zero fees, 100% goes to the project
- immutable & transparent: recorded on the blockchain
- transcends borders: international
- you can actually *get* something for giving: GIVbacks & the GIVstream
- An upside to donating - if GIV token goes up, can end up with more $ than you donated
- Connecting into web3 community presents more opportunities: yield farming, governance power, potential airdrop

Maybe @GriffGreen has some more ideas

**Comment by laurenluz** [comment]
I think I can actually cover these points in #480 and already started a script for it. maybe we don't need to have two at all.
