### ISSUE TITLE
update Governance process docs with cut off times to request nrGIV from quarterly distros

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#486]
decided in GOV call jan 17 to allow for 1 month from first quartlerly nrGIV token request for others to submit proposals - after 1 month no more token requests will be accepted for that distro. 

update governance process doc with this info.

**Comment by divine-comedian** [comment]
LIVE - https://github.com/Giveth/giveth-docs/commit/cdf4998033ce377bc2789c3e6d0ec70fd6f8ea35

**Comment by laurenluz** [comment]
Do we need to add it also to: https://forum.giveth.io/t/governance-process/209 ?

@divine-comedian

**Comment by divine-comedian** [comment]
DONE! 
https://forum.giveth.io/t/governance-process/209
