### ISSUE TITLE
Evergreen content for Giveth

### ISSUE THREAD

**Issue by Brodyann7** [Giveth/giveth-planning#487]
Lauren and I discussed creating a repository for evergreen content for Giveth that can be reposted on multiple social media platforms, like facebook etc. 

Would love if people could suggest/add what some this content might be, blogs, video etc. Thank you!
@laurenluz @WhyldWanderer @divine-comedian @GriffGreen @Danibelle @ForestSoleil 

You can add it to this google doc: https://docs.google.com/document/d/1f4Q8sOT6LnzBUzb-jtKXuFwmIYNI1ZTLXpFPVyn0J7w/edit?usp=sharing

**Comment by laurenluz** [comment]
https://medium.com/giveth/the-future-of-giving-is-here-d480388a3338
https://medium.com/giveth/two-flavours-of-giveth-which-one-to-choose-a3c31207a205
https://medium.com/giveth/the-giveth-dao-community-givernance-84f55fa1ce36
https://medium.com/giveth/welcome-to-the-giveconomy-b3e372da63dd
https://medium.com/giveth/what-if-giving-gave-back-using-web3-to-evolve-philanthropy-a8500b7636ce
https://medium.com/giveth/the-minime-token-open-sourced-by-giveth-2710c0210787
https://medium.com/giveth/conviction-voting-a-novel-continuous-decision-making-alternative-to-governance-aa746cfb9475
https://medium.com/giveth/deep-dive-augmented-bonding-curves-3f1f7c1fa751
https://www.youtube.com/watch?v=ASv420Vf3F8&feature=emb_imp_woyt
https://www.youtube.com/watch?v=LEw8PaJylNA
https://www.youtube.com/watch?v=2eWE667bc3I
https://www.youtube.com/watch?v=9ZiGlIm2vBs
https://www.youtube.com/watch?v=VV7TmNILk6o
https://twitter.com/Givethio/status/1454084287184130049
https://docs.giveth.io/whatisgiveth/history
