### ISSUE TITLE
Video Minicourse - Walkthrough of the GIVeconomy

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#488]
10 Minute Video
Lauren 

Explain how the ecosystem works together between donors, GIVfarm, GIVbacks, GIVstream and GIVgarden

 To Do
- [ ] Create Script
- [ ] QA/ Review Script
- [ ] Record Video - Lauren
- [ ] Edit Video / add closed captions in English
- [ ] Upload to video hosting platform
- [ ] Promote video

**Comment by laurenluz** [comment]
Recorded this one ahmad! https://drive.google.com/drive/folders/1XQcnb7xWaFPp48GOc-RCwkDYb0FGRKDf?usp=sharing

**Comment by ahmadabugosh** [comment]
Thanks @laurenluz, edited and added here: https://www.youtube.com/watch?v=_ULHxC5jwrg&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=5&ab_channel=Giveth. Please have a quick look before closing this issue

**Comment by laurenluz** [comment]
looks good.
