### ISSUE TITLE
Video Minicourse - How to fund your wallet

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#489]

**Comment by ahmadabugosh** [comment]
To Do

- [ ] Create Script
 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by ahmadabugosh** [comment]
To assign to Ben (need to add him on GitHub)

**Comment by laurenluz** [comment]
Part of #490
