### ISSUE TITLE
Reward donors - Propose and get consensus on implementation details

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#49]
"Decide what gets rewarded (maybe only donating to Causes on Giveth2 gets rewarded) 
Decide on mode (tax deduction or token? Vs. minting on request? Vs minting automatically by watching DAI contract - OR MIX)"

Make and/or solicit proposals and get consensus with governance and community on the key decisions for when and how GIV tokens are rewarded to donors.

**Comment by ForestSoleil** [comment]
@GriffGreen & @willyogo to propose at next Governance call or sooner. Then create vote.

**Comment by ForestSoleil** [comment]
3/10 update:
    - Allmmmoooossssttt **Complete!** Some minor manual work remaining (see below)
    - Buckets complete. Donors listed out. Sorted all uncertainties. Cross referenced lists. Cleaned up spreadsheet. Math all adds up. Allocated tokens according to math we reviewed in governance call on Monday. Quadractic share helped to even things out.
    - Remaining Action:
        - Zero out Giveth multisig due to double donations. Griff to remove or add proper address.
        - People who have multiple addresses - combine them.
        - Double check folks who are set to receive more than 30K tokens.
        - Edu's suggestion to create a governance that can claim/send tokens. Instead of [BadgerHunt contract.](https://etherscan.io/address/0x22ba8eeac5bddf7b5a298d2169a24c6f9e12baa0#code)

**Comment by ForestSoleil** [comment]
6/8/21 Update:
**Airdrop close out**

- Bowen's spreadsheet complete.
- Mapping complete for missing addresses
- Next steps:
    - Griff & DappNode hacking tomorrow, Tues June 8th to deploy this on Rinkeby Wednesday. Ready for testing Thursday. Marko & Fabio hacking on claim UX for this.
    - Brainstorm initial proposals for people to vote on when we airdrop tokens to them.
        - Pay core Giveth contributors using this DAO system.
    - Airdrop List ready for QA review! Bring this up on next Monday's governance call: The list is up, we will share final proposal for final review before distribution.
    - Leave 109,000 surplus to the end & then review who was left out and needs to be rewarded (DappNode, for example) and then assign to them.
- Tentative date for Airdrop?
    - Would be great to get it out for the CC mid-July this year.
    - We can aim for this goal, but it's MOST important to ensure everything is solidly ready to launch.
