### ISSUE TITLE
Video Minicourse - Using Giveth to donate

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#490]

**Comment by ahmadabugosh** [comment]
To Do

- [ ] Create Script
 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by ahmadabugosh** [comment]
To assign to Ben (need to add him on GitHub)

**Comment by laurenluz** [comment]
@scottbenjd

**Comment by laurenluz** [comment]
@scottbenjd I made this google doc as a jumping off point for things you might want to include in the video! https://docs.google.com/document/d/196LymlIK-jtObRRTgJ-4Jr_G-oIIy5ghtA4HEozmGyE/edit

**Comment by scottbenjd** [comment]
Here is the WIP script for my section. Comments and edits welcome!
[https://docs.google.com/document/d/1X3zyL84gNYo-3g-B99ApuLIs6wmR_kt1W8fV9Y7gP4A/edit?usp=sharing](url)

**Comment by scottbenjd** [comment]
https://drive.google.com/file/d/1CIjb6R8vbJHIZSQA8DsshKl6MuIsf2X1/view?usp=sharing

**Comment by laurenluz** [comment]
This is cool! I think it's great. Did we decided to put the "building the future of giving" at the end or at the beginning though? I think maybe at the end is the best?

I also think it would be awesome to have the link to Giveth... so after funding your wallet be like "now you can choose your favourite projects and donate directly to them from your metamask through Giveth"... just the tie in to explain the purpose to funding your wallet in the first place...  and our purpose is to donate!

**Comment by scottbenjd** [comment]
Here's the Camtasia 3 version. I think the sound might still need some dialing. There's a noticeable shift after the intro and first little Coinbase part. I included the Giveth animation at the beginning and end but that's a pretty easy fix. Is there a static Giveth logo we could use for the intro or should I just extend the starting frame of the coinbase recording?
https://drive.google.com/file/d/19Pijwi1LQax7HXS5GcBpboA98S_H5r2l/view?usp=sharing

**Comment by laurenluz** [comment]
I think we can ask @rodricastillo9013 @markoprljic or one of our designers to make a quick video banner for each of these videos... just showing the title on giveth branded background

**Comment by ahmadabugosh** [comment]
@laurenluz we have this issue already https://github.com/Giveth/giveth-planning/issues/529

**Comment by rodricastillo9013** [comment]
hello! do you need my help then?

**Comment by ahmadabugosh** [comment]
hey @rodricastillo9013! I think no need since we already have the other task https://github.com/Giveth/giveth-planning/issues/529 (so if you send us the Google slide for that it should solve it)

**Comment by rodricastillo9013** [comment]
@ahmadabugosh oh! perfect! solved! https://docs.google.com/presentation/d/1hBXwaRh4mOiN40C1t-oCjZ9TwfY9z5gsSQjS1unOzSI/edit?usp=sharing thanks :)
