### ISSUE TITLE
Video Minicourse - How to bridge funds to Gnosis

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#491]

**Comment by ahmadabugosh** [comment]
To Do

- [ ] Create Script
 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by laurenluz** [comment]
part of #490
