### ISSUE TITLE
Video Minicourse - How to donate on Giveth

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#492]

**Comment by ahmadabugosh** [comment]
To Do

- [ ] Create Script
 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by ahmadabugosh** [comment]
To Do

- [ ] Create Script
 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by laurenluz** [comment]
part of #490

**Comment by laurenluz** [comment]
This video should definitely mention:
- only verified projects are eligible for GIVbacks
- 100% of the donation goes to the project, and donor gets GIV from Giveth
- there are no fees added by giveth on donations - 100% always goes to the project
- only tokens in the drop down list are eligible for GIVbacks
- to add tokens to that list, you can leave a comment in the forum
- you can donate any token by pasting the address
- "my donations" list
- filling out your profile to appear in the leaderboard

some of this could have gone in the GIVbacks video, but wasn't there, so perhaps we can add it in here

**Comment by laurenluz** [comment]
More points:
- Types of projects: Listed/Unlisted/Verified/Traceable/Giving Block/New
- "My Account" shows your donations, total donated, etc.
- Categories, Search, Filter
- Any questions: Get support! https://giveth.io/support

@scottbenjd lmk if you want to discuss this a little more - maybe you can make an outline w these points before you record and I can have a quick look for comments

**Comment by laurenluz** [comment]
I think that requires a bit of coordination with @ahmadabugosh who is going to re-record part of the GIVbacks video. If he covers it, great! but they should be mentioned in one or the other. (I think better in GIVbacks)

**Comment by ahmadabugosh** [comment]
Yeah no need to cover GIVbacks in detail @scottbenjd, since there is a whole video for it, but it doesn't hurt to briefly mention it (just saying verified projects are eligible)

**Comment by scottbenjd** [comment]
[https://drive.google.com/file/d/1FLZt2iwsvxhwNB91xUbAo4Y2opDKjs5W/view?usp=sharing](url)

**Comment by scottbenjd** [comment]
The tail end of this clip is the raw screen capture of setting up an account and the profile features. I can record some narration for that as well. 

I originally narrated "Congrats. You're now a Giver!" but it felt really flat. Any ideas for something more exciting?

**Comment by ahmadabugosh** [comment]
Thanks @scottbenjd !

A few comments I have: 

1. A lot of what you say here is similar to the GIVbacks video, but I think it's fine to keep it as a standalone video we can share with people that just simply want to donate

2. You could also mention the "Updates" tab, and how you can check how active a project is and more info on how they're using their funds (as well as see the donation history and stats to get a sense of how popular a project is)

3. At the end, could you also mention something like, "you can see all of your donations from your profile by going to this link" (you should it, but there is no sound or voiceover for that part at the end)

4. 4. You could also mention that we encourage you to fill in your profile and email address if you want to receive updates from us, including when you can claim your GIVbacks and other updates from Giveth +  filling out your profile to appear in the leaderboard

5. Also, you could mention how some projects like from "The Giving Block" only allow for donations on ETH mainnet

6. Also @laurenluz  has some comments above as well like a) explaining what Listed/Unlisted/Verified/Traceable/Giving Block/New mean) b) 100% of the donation goes to the project, and donor gets GIV from Giveth, there are no fees added by giveth on donations - 100% always goes to the project (I think it's worth spending time on that because it's an important "selling point" for Giveth)

**Comment by scottbenjd** [comment]
Okay, here is the link to the updated video. I'll use numbering consistent with your feedback, Ahmad.

[https://drive.google.com/file/d/12zmbC6lueNcC6MBD5qA093ZadQKyTjCD/view?usp=sharing](https://drive.google.com/file/d/12zmbC6lueNcC6MBD5qA093ZadQKyTjCD/view?usp=sharing)


1. I deleted part of the GIVbacks section but think we should mention which projects are eligible in case someone only watches the donation video.
2. I added a section to show the project page with updates and donations list.
3. I added a section on setting up a profile w/ an email so that they can receive updates.
6. Added a brief explanation on giving block projects and a "why donate with giveth" part. I didn't mention listed/unlisted. I think that might have been more relevant for the project tutorials we had in mind when we started out. 

Let me know if you have any final changes. If not, we can clean it up publish the series!

**Comment by ahmadabugosh** [comment]
Hey @scottbenjd can you make it public (I couldn't view the video)

**Comment by scottbenjd** [comment]
Whoops. Switched sharing to editor permissions.  Let me know if you aren't able to view still.

**Comment by ahmadabugosh** [comment]
Nice work @scottbenjd ! I think it's great and covers all the key points. 

Anything to add @laurenluz ?

**Comment by laurenluz** [comment]
It's great!!

**Comment by ahmadabugosh** [comment]
Edited, added intro screen & outro and added to the playlist: https://www.youtube.com/watch?v=UlaXjiamHZk&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=4&ab_channel=Giveth
