### ISSUE TITLE
Video Minicourse - Givbacks

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#494]

**Comment by ahmadabugosh** [comment]
To Do

- [ ] Create Script
 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by ahmadabugosh** [comment]
This is done: https://www.youtube.com/watch?v=96I0s6DB23k&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=4

**Comment by ahmadabugosh** [comment]
Let me know if you have any comments on this video or need me to add or rerecord! @WhyldWanderer @laurenluz

**Comment by laurenluz** [comment]
This one is pretty good, a couple of notes:
- the liquid portion of your GIVbacks actually needs to be claimed before it goes to your wallet
- verified projects need to prove that they are providing *public good*, not just raising funds for personal gain

Otherwise, I think you hit key points pretty well. I would be ok with leaving it as-is. @WhyldWanderer any comments?

**Comment by laurenluz** [comment]
Ok I watched again and I realized that you say the "this token is eligible for GIVbacks" is a "this project is eligible for GIVbacks".... when it's actually referring to the token... it's important to say that only tokens from the drop down are eligible for GIVbacks. Users can paste a token address and send it, but they won't get GIVbacks.

Also, tbh, I think we should rerecord this when v2 is launched. It looks bad to see "this is a test" and "phishing" and "how many photos is too many photos" as the "verified projects".

Maybe we can keep the parts at the beginning and rerecord the latter section when the dapp is live.

**Comment by ahmadabugosh** [comment]
Ok cool @laurenluz let me rerecord and add those points once v2 is live!

**Comment by ahmadabugosh** [comment]
Thanks @laurenluz , I made a new version here with the new DApp, moving to QA: https://www.youtube.com/watch?v=X8_UDMmJZyE&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=7&ab_channel=Giveth

**Comment by laurenluz** [comment]
yay! it's great!!
