### ISSUE TITLE
Video Minicourse - Ways to follow and help Giveth's mission

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#498]

**Comment by ahmadabugosh** [comment]
To Do

- [ ] Create Script
 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by ahmadabugosh** [comment]
Hey @laurenluz I created the video for this issue here: https://youtu.be/H8PY86cu0QI Let me know if you have any comments (if you think anything is missing, needs changing etc)!

**Comment by laurenluz** [comment]
it's GREAT
