### ISSUE TITLE
Reward donors - Roadmap

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#50]
"Make a roadmap for this [the rewarding donors use case] specifically… Some pieces are easy, some are hard, we should prioritize the easy wins and publish the roadmap for the rest."

**Comment by ForestSoleil** [comment]
- Hack session for Willy & Griff scheduled for this evening/Wednesday at 530 pm mountain / 730 pm eastern to determine "How many GIV tokens to reward each address in Airdop"
- Then Willy & Griff present/propose to the group to obtain consensus.
