### ISSUE TITLE
Change xdai to gnosis chain in documentation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#500]

**Comment by laurenluz** [comment]
let's call it "Gnosis Chain (formerly xDai Network)"

**Comment by laurenluz** [comment]
@danelsuga to take it!

**Comment by danelsuga** [comment]
It appears I can only propose changes, as I am not authorized to make direct changes. Before doing that and creating loads of forms, @laurenluz laurenluz could I instead get direct access to edit please? Thanks!

**Comment by danelsuga** [comment]
It appears I can only propose changes, as I am not authorized to make direct changes. Before doing that and creating loads of forks, @laurenluz laurenluz could I instead get direct access to edit please? Thanks!

**Comment by danelsuga** [comment]
It appears I can only propose changes, as I am not authorized to make direct changes. Before doing that and creating loads of forks, @laurenluz could I instead get direct access to edit please? Thanks!

**Comment by divine-comedian** [comment]
@danelsuga  you should have access now

**Comment by danelsuga** [comment]
Advice process please! And some guidance.

I have read all the documents at https://docs.giveth.io/ and have only found two references to xDai network. Can that be right?

I’d also like to know if I should commit the changes directly to the master branch or create a new branch and start a pull request? Somehow the former makes more sense for this particular change since it’s something small and obvious and everyone knows.

Thanks for helping the newbie!

@Giveth/communication

**Comment by laurenluz** [comment]
Hey @danelsuga please make PRs so someone can review them. For new contributors I think it's important to do a little QA/double checking, although their small changes, mistakes can happen.

Thanks!

**Comment by danelsuga** [comment]
👍🏽

**Comment by laurenluz** [comment]
@danelsuga to make one final check and then move this to done! :)

**Comment by danelsuga** [comment]
Hi @divine-comedian @krrisis and @laurenluz Would it be possible please to update on your blog posts « Gnosis Chain (formerly xDai Network) » ? 

@divine-comedian 
https://docs.giveth.io/blog/flavorsOfGiveth/#givethio

@krrisis 
https://docs.giveth.io/blog/realigningIncentives/#wait-but-how

@laurenluz 
https://docs.giveth.io/blog/welcomeGIVeconomy/#token-info

**Comment by divine-comedian** [comment]
I don't think we should retroactively edit the blog posts - they are historical relics and I wouldn't spend too much time honestly picking at them inside the docs

**Comment by danelsuga** [comment]
I disagree with the historical aspect. The new 21st century paradigm allows and expects online content to reflect real time: if these documents are meant to be useful, they need to remain relevant. However, if they are reflections of something past, so be it. Many a time Griff asked me to update posts to include more recent info.

**Comment by laurenluz** [comment]
Welcome to the GIVeconomy is pretty recent and still very relevant... so I don't think it's a bad idea to mention gnosis chain. the article does though on one instance already. I don't think more are really necessary.

Kris's article was written in 2019... I'm w/ mitch on this one... this is a historical piece. it contains tons of outdated information and I really don't think it is pertinent to go through and edit them.

Flavours of Giveth... I could go either way. I think it's acceptable to leave as is - especially since we are not actively pushing users to use TRACE anymore... it's also becoming a historical piece.

We should keep information that is important NOW up-to-date... but anything that's being phased out... I don't think it's worht the time to edit.
