### ISSUE TITLE
Naming Giveth Multiverse

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#501]
https://www.notion.so/giveth/Giveth-Multiverse-119dee420bc145edb82d413fe6c850c9

**Comment by laurenluz** [comment]
GIVfrens is too exclusive!
Giveth Multiverse - cute because it plays off the GIViverse!!

**Comment by laurenluz** [comment]
@danelsuga can  help brainstorm more ideas!

**Comment by GriffGreen** [comment]
RegenFarms
Regeniverse
MultiStream

**Comment by divine-comedian** [comment]
GIVstellations
GIVivero...
GIVeroids (hehe)

**Comment by divine-comedian** [comment]
from TheJeweler:

>GIvOpia? GivHopia, GivEden, GivPhoria, GivAlliance,

**Comment by danelsuga** [comment]
> RegenFarms
> Regeniverse
> MultiStream

Haha. Ok, so I come from a different universe but relevant all the same I think: when I read these ideas of @GriffGreen I wondered why he was using “Regen”, which means “rain” in German. 😂 Let’s keep brainstorming! 😁

**Comment by laurenluz** [comment]
Regen as opposed to Degen @danelsuga  :) and regen... like regenerative.

**Comment by danelsuga** [comment]
Yes! I know! Hee hee. 😁

**Comment by markoprljic** [comment]
Giveth Galaxy. We already use it, we already collaborate with the projects from the Galaxy, now they can be part of the GIVeconomy as well.

**Comment by danelsuga** [comment]
Oooooo

**Comment by laurenluz** [comment]
I like RegenFarms because it's the most descriptive. The other names sounds interesting... but ultimately imo at first glance don't have a lot to do with the concept.

I think the core points are:
- turns liquidity providers into long term hodlers w the streams
- farm participants stay invested for the next X years
- **degens become regens**
- this builds relationships between Giveth and other 4good DAOs
- % of the DAOs funds go directly to donation.eth for matching funds to verified projects

I think RegenFarms is good because... the GIVfarm is for earning GIV... the RegenFarms are for earning yields for DAOs working towards regeneratively... 

If we put "GIV" in it... it would only really make sense because some funds go to the matching pool and probably will turn into GIV and get donating.... and I guess... we are Giveth... but hmm... I guess I'll make some more ideas

DAOstreams
StreamFarm
FlowFarms

I still like Regen Farms the best.

**Comment by willyogo** [comment]
Thanks everyone for the awesome thoughts! Just had a quick call with Lauren and we agreed that all things considered, RegenFarms is our personal fav of the above options

**Comment by danelsuga** [comment]
Thanks, @willyogo !
@laurenluz I really appreciate the elaborate explanation as to your choice. I love that attention to shared understanding not only of where you’re coming from but the info in general. Super helpful for me in particular!

**Comment by danelsuga** [comment]
Would it ultimately be “Giveth’s Regenfarms” then? Where does Giveth come in?

Also, would it be plural, or is the idea that it’s one collective farm?

**Comment by divine-comedian** [comment]
I think the point of degens to regens is a flimsy argument at best - the only people in this current spec that are regenerating are the DAOs who are paying a fee to create a farm.

**Comment by markoprljic** [comment]
Giveth Delta - where all streams flow into one

**Comment by laurenluz** [comment]
It's just "RegenFarms" no "Giveth"... in most cases it will be DAOs offering incentives in their token for people to provide liquidity for their token and some other token... not necessarily GIV.

The GIVfarm has different farming opportunities where you can earn GIV
The RegenFarms have different farming opportunities where you can earn the tokens of different Blockchain4good DAOs, or, we can even say... DAOs using blockchain to make regenerative systems for the world.

**Comment by danelsuga** [comment]
While I don’t fully understand the nuances and continue to appreciate your explanations, @laurenluz, I’ll say that I really like Giveth Delta @markoprljic because it contains « Giveth » and also because it’s a pleasant and clear metaphor. It suggests something that Giveth participates in and even guides —or not— it can be understood simply as the place of flow for different DAO streams merging together.

**Comment by divine-comedian** [comment]
There's some cool themes to play with in Giveth Delta - however a delta works the other way around doesn't it - where one stream splits into many - anyway RegenFarms is cool too but I think the whole Regen meme is going to be played out soon so might just end up hating the name in like a month lol

**Comment by GriffGreen** [comment]
I think Regen is a meme that's time has come... Gitcoin is pushing it hard and the momentum around it is still building

**Comment by danelsuga** [comment]
👍🏽
