### ISSUE TITLE
GIVfarm Medium post

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#503]
Medium blog post explaining the GIVfarm & why it's beneficial for GIV and the Giveth ecosystem

- the purpose is to show that GIV has liquidity in 4 places: balancer, univ3, sushi & honeyswap and on 2 chains: mainnet and xdai (so liquidity runs deep because we created rewards programs)
- we are offering the same rewards to stakers on xDai as voters... therefore rewarding both voters & hodlers (explain that staking in the GIVgarden staking pool gives you voting power in the Garden)
- it's part of our mission to empower nonprofits and donors with knowledge & experience on web3 tools...& rewards those who give... donors get GIV from GIVbacks and then can grow their rewards in the farm, and projects who get GIV can also play with staking and voting, growing rewards in a low-risk environment while starting to play with DAO & defi tools
- rewards include the stream so we turn degens into regens... bringing people in w sick APRs and they support the ecosystem because of the 5 year stream

To push out asap so we can get it live while the rewards are still higher

**Comment by laurenluz** [comment]
For more context from Griff:

the purpose is to turn degens into regens
the audience is the degens
who are more likely to ape in, buy GIV etc if they have something entertaining to read that explains how the farms work
so you want to explain how the farms work as well, since it's kind of unique
b/c of the stream
b/c of the univ3
b/c 2 networks
b/c insane APYs
b/c gnosis chain which isn't used by many people for farming opportunities (and wow, low gas)
b/c GIVgarden voting
"it's about turning out documentation into something entertaining to encourage more degens"
he said not to focus on the empowering donors & projects to learn about defi/web3 opportunities... but you could squeeze it in as well
for the GIVfarm article
he's like "we want liquidity! no matter who is providing it... and in the meantime we turn degens into regens with the slippery slope"

**Comment by divine-comedian** [comment]
1st draft ready for review! 

https://docs.google.com/document/d/17oE49hDN7TOqzAzzXWHS-wrvlYyHRD5Y0SmoMKZXgao/edit?usp=sharing

@WhyldWanderer @ahmadabugosh @laurenluz @ForestSoleil @Brodyann7

**Comment by ForestSoleil** [comment]
Reviewed - left comments & edited with suggestions in the google doc.

**Comment by laurenluz** [comment]
This is great @divine-comedian, love the style of it. Left a bunch of suggestions and a few comments. lmk if anything is weird or doesn't make sense.

I'll push on this naming the giveth multiverse thing in the next days and we can blast this out mid-week

**Comment by divine-comedian** [comment]
edits are in from suggestions from forest, griff and lauren 

we'll wait for consensus on the  GIV multiverse naming and push this to medium for publishing

**Comment by laurenluz** [comment]
LIVE https://medium.com/giveth/farm-to-table-yields-with-decentralized-philanthropy-a5d71d28ef0d
