### ISSUE TITLE
Meet the Makers Tweet 

### ISSUE THREAD

**Issue by Brodyann7** [Giveth/giveth-planning#504]
promoting the upcoming Meet the Makers on Tuesday, February 1st from 10:00 - 11:30 am Central Standard Time / Costa Rica time. We'll be meeting in Airmeet 

@Brodyann7 @laurenluz @ForestSoleil @WhyldWanderer

**Comment by Brodyann7** [comment]
Hey Fam! 💝 
 
✏️  Mark your calendars! 🗓️. 👇
 
“Meet the Makers” is happening Tues Feb 1st from 10:00-11:30 am central time.
 
🌏  You will get a chance to connect with and learn more about some of the incredible work our change makers are doing in the Giveth community!  🙌
 
🤩 Check out our amazing roster of participants 👇
 
🔨 Njombe Innovation Academy 

Njombe Innovation Academy is committed to creating an environment where local youth in Njombe, Tanzania, can gain access to tools and mindset to transform the challenges that surround them into social enterprises. 

https://giveth.io/project/Njombe-Innovation-Academy-1

👩‍🌾  Red Armonía 

Red Armonía is an ELEV8D initiative in the South Pacific region of Costa Rica that is committed to promoting community sovereignty by creating technologies that connect local community with organic farmers and sellers, building Community Gardens using sustainable local resources and educating people on the benefits of organic and harmonious practices. 

https://giveth.io/project/Red-Armonia-0
 
🌱 Free The Food 

Free the Food plants street-side food systems and provides educational content to help others worldwide successfully implement these systems.

https://giveth.io/project/Free-The-Food-0
 
💧 Rios Limpios Neighborhood Grey Water Filtration

Rios Limpios Neighborhood Grey Water Filtration is working on restoring water purity in the Diamante Valley of Costa Rica by installing grey water filtration systems throughout the valley. 
 
https://giveth.io/project/Rios-Limpios-Neighborhood-Grey-Water-Filtration-0

🐠 Moonjelly DAO 

Moonjelly DAO is raising new sources of funding for Ocean Impact projects. 
 
https://giveth.io/project/Moonjelly-DAO-0 
 
📚 REcenter the Resource Education Center
 
The Stewards of Diamante Luz and Luz del Bosque have teamed up to allocate a portion of roadside land for housing a larger Resource Education Center and Materials Processing Facility.

https://giveth.io/project/RECenter-the-Resource-Education-Center-San-Salvador-0

**Comment by Brodyann7** [comment]
Let me know if anything here needs to be tweaked, or feel free to adjust it yourselves. Wanted to get this out sooner rather than later to you since this is happening next week!

**Comment by laurenluz** [comment]
This is great @Brodyann7! Meet the makers has been postponed, but I will share this once the date is set.

**Comment by ForestSoleil** [comment]
Awesome, thank you @Brodyann7 ! Most of the makers you featured here I have scheduled for our second MTM event happening Tuesday, March 22nd from 11-00 am - 12:30 pm central standard time. Around an ENVIRONMENTAL theme.

March 22nd https://docs.google.com/document/d/120quv9cbQxLR6yNKw7hMVZZJRXdDwUf1EKeQBIFjaVQ/edit?usp=sharing

Theres a different array of makers for our kickoff event on Tuesday, Feb 22nd from 11-1230 around a YOUTH theme. 

Kickoff Feb 22nd https://docs.google.com/document/d/1Xmn3gxCC4z8QZOA0CDCTeDOY7JpZ29Jv1I4fCpX6qu4/edit?usp=sharing
