### ISSUE TITLE
Connect Social Media Platforms Together

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#506]
Buffer
Zapier

can publish tweets onto other platforms

**Comment by WhyldWanderer** [comment]
Ahmad is waiting on twitter access to connect all platforms together.
@laurenluz can you help with this?

**Comment by laurenluz** [comment]
I need to set up the password manager for it, and I don't have time rn w ethdenver. Next week.

**Comment by laurenluz** [comment]
Hey @ahmadabugosh did we already set this up in Zapier?

**Comment by ahmadabugosh** [comment]
Hey @laurenluz, I set this up and it's posting on Facebook now. automatically (we just need to monitor that it makes sense, and i'm not sure how threads will look). 

I could set it up for LinkedIn too, but we ran out of free zaps (we only get 5 with the free account) :/ .  I can set it up on a new Zapier account (if you share access to the Twitter account with me on Lastpass), or we could pay to upgrade our Zapier account
