### ISSUE TITLE
"GIVnews" Newsletter header image

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#507]
Hey team, we're sending out our first community newsletter in a few days and decided to call it "Give News". Can you please create a header image graphic for it (having a width of roughly 700px), that just says "Give News" and maybe some icons in the background or whatever you think would make people understand it's a community newsletter. Thanks!

**Comment by markoprljic** [comment]
@playingleela can you take this on? We have a Figma with all newsletter desisgn already.

**Comment by playingleela** [comment]
hey @markoprljic for sure! Ok, thanks!

**Comment by playingleela** [comment]
hey @ahmadabugosh here it goes
<img width="600" alt="Header_ newsletter" src="https://user-images.githubusercontent.com/94190369/151415994-4100d23c-9dff-439f-8f50-dd510bc1aba9.png">

**Comment by playingleela** [comment]
let me know if you need anything else and I will be glad to help! thanks (:

**Comment by ahmadabugosh** [comment]
> let me know if you need anything else and I will be glad to help! thanks (:

Thanks @playingleela, looks good ! Can I have a variation please where it is one word, spelled like "GIVnews", so that it matches our other branding?

**Comment by Elizardwizzard** [comment]
Hey! I am Elizabeth, if you need any extra help I am more than glad to participate :)

**Comment by markoprljic** [comment]
> Hey! I am Elizabeth, if you need any extra help I am more than glad to participate :)

Hi Elizabeth, thanks for the offer :) What would you specifically want to help with? What are you skills? 
Maybe you want to join our Discord if not already and we can chat there.

Thanks.

**Comment by playingleela** [comment]
hey @ahmadabugosh Im sorry that I missed this message, here it goes
<img width="600" alt="Header_ newsletter (1)" src="https://user-images.githubusercontent.com/94190369/151657615-464f1a68-e962-4ff0-b683-bb1e9b631ada.png">

**Comment by ahmadabugosh** [comment]
Thanks so much @playingleela, looks great!
