### ISSUE TITLE
Comms Onboarding Guide

### ISSUE THREAD

**Issue by Brodyann7** [Giveth/giveth-planning#509]
These are the onboarding notes I have so far! Feel free to add things I've missed. 

@laurenluz @WhyldWanderer @ForestSoleil @danelsuga 

https://docs.google.com/document/d/11sU6ltK24JDIXd-MDTRx5MekupctZJo-wHJiLC__hr4/edit?usp=sharing

**Comment by danelsuga** [comment]
Thank you @Brodyann7!

**Comment by danelsuga** [comment]
I'd like to sync with @Brodyann7 @WhyldWanderer @ForestSoleil if you each have 10 or 20 minutes for a chat? Thank you!

**Comment by ForestSoleil** [comment]
Sure thing, dm me on discord

**Comment by danelsuga** [comment]
Here’s what I’ve got so far. 

https://docs.google.com/document/d/14Esr-bjBj5XEKX9QFsZ67GAdLyZI111hOZcWGIcTHyg/edit

**Comment by laurenluz** [comment]
Looking good @danelsuga - I left some comments and suggestions. Are you going to add in what Ann did to make this more comms-specific?

**Comment by danelsuga** [comment]
Will do!

**Comment by laurenluz** [comment]
@jahanzaib-jay it would be great if you take this on from Suga! I'm available for any questions

**Comment by laurenluz** [comment]
We want to make is something like this: https://docs.giveth.io/dapps/contributors

but for comms :)

**Comment by laurenluz** [comment]
What Suga started would be great to add to : https://github.com/Giveth/giveth-planning/issues/432

but we still need something comms-specific. This is for you @jahanzaib-jay ! :)

**Comment by jahanzaib-jay** [comment]
https://docs.google.com/document/d/1M8U4RNIJAB5OoeK2_mDb4OO0cdViEpTv2cSly7UqB-I/edit?usp=sharing

**Comment by laurenluz** [comment]
@SymSL @ahmadabugosh @scottbenjd

**Comment by ahmadabugosh** [comment]
Looks good @jahanzaib-jay ! I would add more though on getting people started for the first time. For example, I would  1) Mention to introduce themselves in the "introduce yourself" channel along with what skills they can bring to Giveth (we frequently check that to see how people can contribute) 2) Include a section on "getting started with your first issue", where they can look at the "good first issue tag" and to hop on a comms call and volunteer for anything they think they can add value to (since that's often the hardest part, is getting started with their first issue)

**Comment by laurenluz** [comment]
Mia made this awesome guide once, it would be great to pull some pieces from that: https://docs.google.com/document/d/1yXj4LLJXcsuSr2VJ9xpDUU-8bQyu07aR1Psh8bgby9E/edit#heading=h.zhsa8za9et

**Comment by danelsuga** [comment]
Here is an updated comms onboarding guide.

https://docs.google.com/document/d/1pV-gD14E0rV_hlbOPB3JhJd2-6tIEFRIi8QQ6_25aI4/edit?usp=sharing

**Comment by laurenluz** [comment]
left some suggestions :)

maybe @WhyldWanderer could take a look to review too

**Comment by danelsuga** [comment]
This should be done now. Just looking for one updated Google Drive link (or remove reference). What do you think @laurenluz ?

https://docs.google.com/document/d/1pV-gD14E0rV_hlbOPB3JhJd2-6tIEFRIi8QQ6_25aI4/edit#

**Comment by laurenluz** [comment]
it's awesome, left just some small comments... once they're resolved I think it's ok to upload. Thanks Suga!

**Comment by danelsuga** [comment]
@WhyldWanderer when you get a chance, could you please check out a couple small loose ends in this doc? Thank you!!

https://docs.google.com/document/d/1pV-gD14E0rV_hlbOPB3JhJd2-6tIEFRIi8QQ6_25aI4/edit#

**Comment by c0ric0ri** [comment]
Linking the copy of the onboarding email I received here: https://docs.google.com/document/d/1pv0SgbwZwHJERGtqG1Wyr83zsokffN6Z6uMyr7QJJ04/edit?usp=sharing

**Comment by WhyldWanderer** [comment]
Looks good @danelsuga! I answered some questions in the comments and changed one little thing... 

Thanks so much! I bet it feels great to finally check this one off.

**Comment by WhyldWanderer** [comment]
@divine-comedian Can you help us get this one up in the docs?

**Comment by danelsuga** [comment]
Great! Thanks @WhyldWanderer ! This is ready to go @divine-comedian ! Thanks!

**Comment by divine-comedian** [comment]
LIVE!

https://docs.giveth.io/whatisgiveth/commsContributorGuide

**Comment by laurenluz** [comment]
OMG! Amazing!!! Thanks @danelsuga @WhyldWanderer @divine-comedian
