### ISSUE TITLE
Add Newsletter Section to Docs

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#511]

**Comment by ahmadabugosh** [comment]
Hey @divine-comedian ,

1) Can you please add a section in the docs for the Newsletter, and add 

- An intro about how we have a newsletter and a link for people to subscribe https://giveth.io/#subscribe
- A list of all of the issues, starting with the first 

2) For the first issue,  I added the markdown file here along with the images. Let me know if this format is ok to add to the docs. https://drive.google.com/drive/u/0/folders/1TNKFOxHHuFCP8_QBCcgrcjfO2TRIXstz

**Comment by divine-comedian** [comment]
LIVE - https://docs.giveth.io/newsletter/
