### ISSUE TITLE
Meet the maker tweet thread for Feb 22

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#513]

**Comment by laurenluz** [comment]
related to #504

**Comment by ForestSoleil** [comment]
Created this google doc for Feb 22nd tweets & shills: 

https://docs.google.com/document/d/17EBwGa7Zk715FirDMmld1iBafOohmVrf0i8Y3Ma8XT0/edit?usp=sharing

Created tweet thread for Feb 22nd and double checked within 280 characters for each tweet.

**Comment by laurenluz** [comment]
Left some comments @ForestSoleil :) please ask Rodri to create a twitter banner for this (I left more details in the comment in the doc)

**Comment by laurenluz** [comment]
it looks great btw!

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1498315796795166723
