### ISSUE TITLE
Meet the makers tweet thread for April

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#515]
related to #504

**Comment by ForestSoleil** [comment]
Made this doc for all meet the makers tweets & shills:

https://docs.google.com/document/d/17EBwGa7Zk715FirDMmld1iBafOohmVrf0i8Y3Ma8XT0/edit?usp=sharing

Currently in process of confirming projects for March 22nd. Will update once we have that locked in.
