### ISSUE TITLE
Meet the Maker Kickoff March 1st Blog post

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#516]

**Comment by ForestSoleil** [comment]
Ready for QA!
https://docs.google.com/document/d/1Xmn3gxCC4z8QZOA0CDCTeDOY7JpZ29Jv1I4fCpX6qu4/edit?usp=sharing

@laurenluz ....weird it wont let me tag mitch or ashley hmmm.

**Comment by divine-comedian** [comment]
reviewed! left some comments

**Comment by WhyldWanderer** [comment]
One more person could QA - Forest will implement feedback and publish

**Comment by ForestSoleil** [comment]
@ahmadabugosh said he will qa

**Comment by WhyldWanderer** [comment]
Reviewed! left comments/suggestions in the doc..

**Comment by ahmadabugosh** [comment]
Thanks for putting this together @ForestSoleil ! I reviewed it as well

**Comment by ForestSoleil** [comment]
Great thanks yall! Will integrate your feedback.

**Comment by danelsuga** [comment]
Looking great! I noted some small things.

**Comment by laurenluz** [comment]
This is great @ForestSoleil thanks so much!

**Comment by laurenluz** [comment]
@WhyldWanderer you can review the blog post here!

**Comment by ForestSoleil** [comment]
Uploaded to medium. Waiting on banner from design team then will submit to giveth medium for lauren to review formatting that i did.

**Comment by laurenluz** [comment]
https://medium.com/giveth/meet-the-makers-of-the-giveth-io-giveconomy-1fa9a713aca4
