### ISSUE TITLE
Calender invites for meet the maker

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#519]
Add clear description of the event and a link to airmeet

**Comment by WhyldWanderer** [comment]
https://calendar.google.com/event?action=TEMPLATE&tmeid=MGM0cW1xaWdhaHQ3cmoya3ZzaXM1cmgzNjQgZ2l2ZXRoZG90aW9AbQ&tmsrc=givethdotio%40gmail.com
