### ISSUE TITLE
Meet the makers speaker prep

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#521]
If Givethers are going to be representing the GIVeconomy between presenters... we should have speakers organized and perhaps even a rough outline of the script, i.e. organization of speaking flow.

**Comment by ForestSoleil** [comment]
@laurenluz @WhyldWanderer @divine-comedian @willyogo @GriffGreen interested in any of these slots? ^ for tuesday, march 1st kicking off Meet the Makers

**Comment by GriffGreen** [comment]
Cool I assume these are costa rica time. I can make any of them.

**Comment by laurenluz** [comment]
I'm happy to join and support. I can take any of these speaker slots. If Griff wants to join as well maybe we alternate?

**Comment by ForestSoleil** [comment]
That sounds ggreat @laurenluz ! Griff told me in dm that he is happy to take any/all slots. Love that or love you alternating. I plan to intro each of the projects at the beginning of their slot. And ashley is also available. Lets discuss on comms today. Thanks!

**Comment by ForestSoleil** [comment]
Ashley to manage tech
Forest to intro project owners
Griff & lauren to alternate speaking slots for giveth, as well as welcome and close the event.

**Comment by laurenluz** [comment]
As discussed in today's comms call, for next round, it would be good to have clearer expectations on what to explain & timing for speaker slots
