### ISSUE TITLE
Email donors (and project owners?) about Giveth Matching Pool

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#523]
https://giveth.io/project/donation-eth

**Comment by laurenluz** [comment]
@jahanzaib-jay is down to look into it!

**Comment by jahanzaib-jay** [comment]
Working on this doc: 

https://docs.google.com/document/d/1jh8NLEvy-OtaeyL45t-gZoswDnYv-ovI5dTcmgQvnUg/edit?usp=sharing

Will update you when this is done.

**Comment by jahanzaib-jay** [comment]
@laurenluz can you please have a look and share our thoughts?

**Comment by laurenluz** [comment]
Made suggestions in the doc.

**Comment by jahanzaib-jay** [comment]
All changes accepted. Added a couple of emojis as well.

**Comment by laurenluz** [comment]
Just did a quick read through again, there were still two typos. Please, after accepting changes, do a final check to make sure there are no mistakes.

Now this needs to actually get added to autopilot and send to our email list of donors & projects. Once it is sent, please comment here.

**Comment by laurenluz** [comment]
@cotabe would be great if you could help set this up as a one-time email to go out to our list of donors & project owners

@ahmadabugosh can help

**Comment by Cotabe** [comment]
@jahanzaib-jay  @ahmadabugosh  @laurenluz 

Sent a test email to all of you. Made a few tweeks for layout purposes. The name goes random. Let me know what you think and I will send it widely.

**Comment by laurenluz** [comment]
looks good!

**Comment by Cotabe** [comment]
Schedule for tomorrow :)

**Comment by Cotabe** [comment]
DONE

**Comment by laurenluz** [comment]
thanks Cotabe!!
