### ISSUE TITLE
Add Giveth Matching Pool explainer to docs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#524]
https://giveth.io/project/donation-eth

**Comment by danelsuga** [comment]
https://docs.google.com/document/d/1iv0vBEf3gIbzDxMn2cYTdHTYzobAyCWZ3mbU1ATkvaE/edit?usp=sharing

**Comment by laurenluz** [comment]
@danelsuga made some comments - please lmk if you have questions

**Comment by danelsuga** [comment]
Updated! Lmk what you think.

**Comment by laurenluz** [comment]
Hey @danelsuga! I went through and left some comments, thanks for putting this together. Sorry for hacking it apart a little, I really appreciate your writing voice & also wanted to make the key concepts more clear. Lmk if anything seems off to you! I added some links as well.

**Comment by danelsuga** [comment]
I believe this is ready to go. @laurenluz 

https://docs.google.com/document/d/1iv0vBEf3gIbzDxMn2cYTdHTYzobAyCWZ3mbU1ATkvaE/edit

**Comment by laurenluz** [comment]
Looks great! @jahanzaib-jay @divine-comedian can you put this up on the docs?

tbh I don't know the best place for it. @danelsuga maybe you can weigh in w your suggestion?

**Comment by danelsuga** [comment]
I suppose it should go under GIVeconomy:

GIVdrop
GIVbacks
GIVstream
GIVgarden
GIVfarm

What is the order of those things anyway? (Should they be alphabetical at this point?)

(And should this be GIVmatch or something?)

**Comment by jahanzaib-jay** [comment]
Arranging them alphabetically is a good idea.

**Comment by laurenluz** [comment]
Oh, I wouldn't do alphabetical.. GIVdrop happens first.  Then GIVbacks is second most relevant to the economy. They're organized in terms of relevance.... or like in terms of complication.

We can put this in there. Call it Giveth Matching Pool, and maybe put it beneath GIVbacks, before GIVstream

We decided not to call it GIVmatching because it's not only matching donations in GIV.

@divine-comedian wdyt?

**Comment by divine-comedian** [comment]
Yeah let's drop it in under GIVbacks

**Comment by divine-comedian** [comment]
hitting some technical issues - this isn't live yet

**Comment by laurenluz** [comment]
ooh sorry, I didn't even mean to close it

**Comment by divine-comedian** [comment]
pending PR https://github.com/Giveth/giveth-docs/pull/96

**Comment by laurenluz** [comment]
https://docs.giveth.io/givethMatchingPool/
