### ISSUE TITLE
Update Giveth Finances Documentation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#525]
https://docs.giveth.io/whatisgiveth/finances

**Comment by c0ric0ri** [comment]
@laurenluz is this still relevant?

**Comment by laurenluz** [comment]
ughhh  yes it is. in fact, it's so wrong as-is... we should at the very least take it down if we're not going to try to improve it,

@divine-comedian wdyt? burn it?

**Comment by divine-comedian** [comment]
> ughhh yes it is. in fact, it's so wrong as-is... we should at the very least take it down if we're not going to try to improve it,
> 
> @divine-comedian wdyt? burn it?

BURN IT! :fire:

**Comment by divine-comedian** [comment]
I removed it from the sidebar so it should no longer be publicly accessible - we still have the doc in our repo if we choose to update it later.

**Comment by laurenluz** [comment]
Thanks Mitch! @c0ric0ri feel free to close it... or icebox it if you think it's a useful reminder as something we could update
