### ISSUE TITLE
Meet the makers promo video

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#527]

**Comment by ahmadabugosh** [comment]
Hey team I made a video promo for Meet the Makers here: https://drive.google.com/file/d/1w8xUv_Fwd-rgspJ-xFN6REDLPaCmnF42/view?usp=sharing Please let me know if you have any comments!

**Comment by laurenluz** [comment]
This is great Ahmad! I put some comments in the discord, but I think they might make more sense in here... a copy/paste:

1. Can we change the join link to either "discord.giveth.io" or "join.giveth.io"?
2. Is it easy to unanimate the project title text to make it easier to read? feels busy with the title and the subtext animated simultaneously

**Comment by ahmadabugosh** [comment]
Hey here is the updated video 
1) Changed it to join.giveth.io, since discord.giveth.io doesn't redirect in all cases
2) Made the titles load first 

https://drive.google.com/file/d/1-gz1byHFzVJE3lweqYERC_cPSZI2uVLx/view?usp=sharing

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1498677262421577728
