### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#528]
I created a google doc here with my suggestions of relevant giveth docs to translate. 

https://docs.google.com/document/d/1AmjI2aoRGv7zM6HYP1Py4iJevnHZ7vF3ixUK2gyitkI/edit

@divine-comedian care to take a look when you return from vacation?

**Comment by laurenluz** [comment]
@divine-comedian at a quick review, this looks fine to me, can you give it a quick look?

**Comment by divine-comedian** [comment]
Ooops! this was already reviewed and went into the forum 

https://forum.giveth.io/t/giveth-gitbook-translations/311/13
