### ISSUE TITLE
Intro Screen for Video Course

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#529]

**Comment by ahmadabugosh** [comment]
Hey design team, can you help us create an image file for us to use as a video intro title screen that we can use for our video content (it will also serve as the video thumbnail)? Something editable (as an image in a PSD file), where we can manually change it for different video titles (for example, "How to use Metamask", "How the GIVeconomy works" etc.). We want to use it in videos, so probably a 16:9 aspect ratio would be best. Thanks!

**Comment by markoprljic** [comment]
I think best would be a Google slide template so you don't rely on Photoshop. @rodricastillo9013

**Comment by ahmadabugosh** [comment]
Yes, Google slide template would work well!

**Comment by rodricastillo9013** [comment]
![You tube](https://user-images.githubusercontent.com/61791380/153604079-dfa151f1-759f-4b4c-9b91-07e57b94c0fb.png)

Hi Good moring! I leave here the design sample, once we take advantage of it, I will put it together a google slides without problem!

**Comment by ahmadabugosh** [comment]
This is great, I think it looks good, thanks @rodricastillo9013 ! If you can share the Google slide version we can close this issue.

**Comment by ahmadabugosh** [comment]
Hey just pinging you on this @rodricastillo9013, if you can export a Google slides version for us 🙏

**Comment by rodricastillo9013** [comment]
Hi, excuse me! I was on vacation! I will prepare it as soon as possible and I will send it to you! Thanks a lot

**Comment by rodricastillo9013** [comment]
Sorry for the delay! here you have the link! https://docs.google.com/presentation/d/1hBXwaRh4mOiN40C1t-oCjZ9TwfY9z5gsSQjS1unOzSI/edit?usp=sharing

**Comment by ahmadabugosh** [comment]
No worries at all, thanks @rodricastillo9013 , this works great!
