### ISSUE TITLE
Rewarding contributors - Figure out the plan for paid work and contributors

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#53]
As the Giveth DAO, we want to implement a sustainable system for equitably rewarding contributors to Giveth's development and operations.

How will we decide how much to reward each contributor? Can we use sourcecred to inform this decision (with the goal of automating and/or decentralizing it)?

Please make or solicit a proposal and get consensus with governance and community

**Comment by ForestSoleil** [comment]
Do you feel this is complete based on our SoureCred, !praise and Airdrop decisions? @willyogo
