### ISSUE TITLE
Meeting the Giveth team 

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#530]
I’d like to have short voice chats with as many team members as possible.
Please reach out to help me learn who you are! 
It will also help me get a sense of how things are organized and how they function.
I have difficulty in joining the meetings due to the time difference, especially the Community Call: I'm in transit on a bike at that time! :(
Thank you!
Not sure who to tag...
@laurenluz 
@WhyldWanderer 
@ForestSoleil 
@ahmadabugosh 
@GriffGreen

**Comment by laurenluz** [comment]
Happy to meet this week @danelsuga! I'll DM you

**Comment by danelsuga** [comment]
Thanks!

**Comment by WhyldWanderer** [comment]
For sure! Let's sync up.. Ill send you a DM as well...
