### ISSUE TITLE
Define Community Circle Routines

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#534]
These are the main ones so far...

- Communitas Weekly Meet-Up
- Newsletter
- Meet the Makers events

If we think of any others, let's add them in this issue

**Comment by EventHunter** [comment]
**Daily**
Daily Happiness - Share today's activities that make the world, your loved ones, or you better. (I make a donation today, I prepare a sandwich for myself, I call my mom to say I love you)

**Weekly**
Contribute Space - Join us to contribute to Giveth Community or one of our member's work. (30 min call where members can find the chance to share their ideas or contribute each other's work) (30 min call before onboarding session) 
Community Onboarding - We can prepare some presentations for that maybe? And some icebreaking events. Invite people at the start of the week by tagging them. 
Weekly Content - Creating weekly content in different areas and resources 

**Bi-Weekly**
Meet the Makers

**Monthly**
Creating a place for sharing Community Insights in our newsletter
