### ISSUE TITLE
Investigate Listing and Marketing Inquiries / Influencer Outreach

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#535]
Since launch I have been recieving multiple DM's in Telegram as well as emails from people with listing offers... or want to promote Giveth on their YouTube channel, etc.

I have made this spreadsheet with all the info from the messages. I dont have the bandwidth to research who they are or follow up with any of them. Some could be spam and others may be valuable.

If anyone else has been receiving solicitation of this type, you can add the info in this spreadsheet.

https://docs.google.com/spreadsheets/d/10mY0QniRVej3GQZb8AyRnINs0JW8prHbPxl_fClIikM/edit?usp=sharing

If anyone feels like doing some investigation into which exchanges we might actually be interested in getting listed on please do! And please leave notes in the spreadsheet along with any lilnks that you may have found while researching. We want to look for opportunities that are aligned with the Giveth values and not just take any listing opportunity.

We can take a look at them in the comms call and decide if we want to move forward on any of them.

**Comment by laurenluz** [comment]
@symsl this one's for you!

**Comment by SymSL** [comment]
Hello! I've taken a look through the spreadsheet (thanks again @WhyldWanderer for organising!) And have some questions:

- Most are from Telegram, are there any that come through the website? I think there was a submit/contact form
- Is there a way to grant access for a team member to liaise and get the email addresses from the people who enquired? Email will be better for comms.
- Most are asking for some sort of paid collaboration. If this is an option, we should identify an entire list of creators we could reach out to, and prioritise them.
- Is there anything else that could be a potential value trade? 
- I've added to the spreadsheet tabs for Creators, Charities & Cryptos that we could reach out to

I've put together some potential scripts we could send to reach out easier that we can discuss in the call if there is time, or I'll DM it

**Comment by WhyldWanderer** [comment]
Just to put here what I mentioned in our little sync after the Comms Call

The main objective, as of now, is to research the different exchanges, youtube channels, marketing oportunities, etc. to see if they are value aligned with Giveth. Maybe leave notes in one of the columns to indicate what you found while researching their exchange/channel. Once we have done the research and determined that it is valuable for us to accept the offer, we can beging to reach out and take next steps.

I can make sure that you get the right login info for the info@giveth.io email once we know who we will reach out to.

As far as compensation, I see two main options...
- we can invite them to create a post on our forum introducing themselves and offereing to list our token or promote via their youtube etc. Once the community has determined that this is something that is valuable during the advice process, one of the team members can put the proposal up for them
- Communications team can submit a budget proposal for marketing purposes and then delegate funds as they need.

**Comment by jahanzaib-jay** [comment]
Working on adding stats and other findings to finalize the list of exchanges we can consider.

**Comment by SymSL** [comment]
Hello all, just an update on this 
- we have gone through the **Listings/Exchanges** & added some basic notes & @jahanzaib-jay has kindly offered to add more research and stats so we can prioritise these and then get info on what their costs/proposals are to list our coin there. Thank you for bringing your great energy to this task!
- We chatted this morning and agreed to prioritise & select 5 initially to investigate listing our token & once those are decided we can list another 5
- From those who have reached out to us, these seem to be good options to look at first: Kucoin, Huobi Exchange, OKX, possibly Bitrue and Bitfinex if we dont find any negative reviews. There are also the top 3 platforms that havent reached out but we can investigate: Binance, Hotcoin Global, Mandala Exchange
- **Influencers**: I've filtered through those who reached out, and there are 2 x AMA proposals we should take up (Crypto Talkz & a marketer from the UAE) and the other influencers are generally looking for us to do a cross promotion which is potentially paid, so we could reach out and find out more.
- There are 7 influencers we can reach out to so far, but I will add in columns for Subs and avg views so we can calculate what is to be expected if we went to promote Giveth on these channels. In the mean time we could reach out to them and find out the details on promoting us on their channel. 
- The other sheets need to be filtered so if there are any extra hands for this project it would be great :) 

For both the exchanges and the influencers, having a giveth email is handy, but for getting info on the exchanges is not a barrier

**Comment by SymSL** [comment]
**Listings:** Summarising the ones we will look at first: Kucoin, Huobi Exchange, OKX, Bitrue and Bitfinex + Binance, Hotcoin Global, Mandala Exchange. If no one else can get to these sooner, I'll try tackle them in the next few days to see their requirements to have us listed there.

**Influencers:** Some influencers that need to be emailed (Davidcryptooff@gmail.com), but most need to be DM'd on Telegram to get their details - would this be possible @WhyldWanderer? I've indicated a Y in a column next to the influencers we could investigate first. This will be necessary even for the AMAs.

**Comment by jahanzaib-jay** [comment]
Upon further research, the top 5 exchanges/listings we should consider are Kucoin, OKX, Huobi exchange, Gate exchange and Upbit. 

Following are some key stats on every platform:

### Kucoin
1. Rank in Top Cryptocurrency Exchanges Ranking by Trust Score - Spot of CoinGecko: 9th 
2. Rank in Crypto exchange rankings on Coinmarketcap: 5th
3. Last 3 months visit: 13.5M
4. Playstore downloads: 5M +
5. Avg Playstore ratings: 4.6
6. Apple store ratings: 4.6

### OKX
1. Rank in Top Cryptocurrency Exchanges Ranking by Trust Score - Spot of CoinGecko: 2nd 
2. Rank in Crypto exchange rankings on Coinmarketcap: 17th
3. Total visitors in last 3 months: 9.5 Million
4. Playstore downloads: 5 Million+
5. Avg Playstore ratings: 4.5
6. Apple store ratings: 4.9

### Huobi exchange
1. Rank in Top Cryptocurrency Exchanges Ranking by Trust Score - Spot of CoinGecko: 10th 
2. Rank in Crypto exchange rankings on Coinmarketcap: 6th
3. Last 3 months visit: 6.5M
4. Playstore downloads: 5M+
5. Avg Playstore ratings: 4.5
6. Apple store ratings: 4.5 

### Gate exchange
"1. Rank in Top Cryptocurrency Exchanges Ranking by Trust Score - Spot of CoinGecko: 8th 
2. Rank in Crypto exchange rankings on Coinmarketcap: 7th
3. Last 3 months visit: 13.7M
4. Playstore downloads: 1M +
5. Avg Playstore ratings: 3.4
6. Apple store ratings: 3.5 

### Upbit
1. Rank in Top Cryptocurrency Exchanges Ranking by Trust Score - Spot of CoinGecko: 34th 
2. Rank in Crypto exchange rankings on Coinmarketcap: 24th 
3. Last 3 months visit: 9.7M 
4. Playstore downloads: 100,000 + 
5. Avg Playstore ratings: 2.3
6. Apple store ratings: 3.5

**Comment by laurenluz** [comment]
@cotabe is willing to help with this!

**Comment by SymSL** [comment]
Here is a potential script I had put together a while back for the influencers, suggestions always welcome: https://docs.google.com/spreadsheets/d/15-twj68kRcCFN815NAk7XgAibvRZTzJmB0HDed-2Oig/edit#gid=0

**Comment by SymSL** [comment]
Hey @laurenluz, yes its here: https://docs.google.com/document/d/1g-7URt_-Ugmw6VtKWVDF6nENst689b4dzZ9aaAI8ewo/edit

Feel free to adjust and suggest. These will be tweaked for each send out as well
