### ISSUE TITLE
Communicate mandatory updates to verified project owners

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#538]
As discussed in the governance call on 2/21/22, we will be requiring verified project to make regular updates to their projects to maintain their verified status.

They will need to provide at least one update every 3 months (quarterly).
We should communicate this as follows:

Step 1. Project applies for verification
add language to typeform application stating that regular updates are required for verified status.

Step 2. Project becomes verified
add language to acceptance email stating that regular updates will be required. (recommend monthly)

Step 3. If project has not added an update by 1.5 months
Send an email reminder

Step 4. If project has not added an update by 2 months
Send an email reminder

Step 5. If project has not added an update by 2.5 months
Send an email warning

Step 6. If project has not added an update by 3 months
Revoke verified badge and project must reapply

**Other places to communicate**
Docs:
 Project Verification Guide

Emails: 
 Invite for verification email

**Comment by laurenluz** [comment]
@ahmadabugosh let's add this to the March newsletter once the details are worked out

**Comment by laurenluz** [comment]
@WhyldWanderer will add the spec doc to this! the scope has broadened

**Comment by WhyldWanderer** [comment]
Here is the doc:
https://docs.google.com/spreadsheets/d/1IKjEE8Vg1P2sxlle6imtf-eBljNMKTnCTV8P0qlntFg/edit?usp=sharing

Next step: Forum post by the end of the week

**Comment by WhyldWanderer** [comment]
fourm post: https://forum.giveth.io/t/mandatory-updates-for-verified-projects/723
