### ISSUE TITLE
March newsletter 2022

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#540]
Add #538 into this as well as blog post for ETHdenver

**Comment by ahmadabugosh** [comment]
@laurenluz  so what I want to include in this newsletter

1. Eth Denver megathread
2. Regen farms article
3. DAOist CDMX
4. Highlighted jobs we're hiring for
5. Project of the month: Unchain
6. Givbacks round analysis dashboard http://dashboard.giveth.io/public/dashboard/4717fd91-a311-42cf-93d9-185ec8c08a04?round_range=2022-03-04~2022-03-18

Anything else?

**Comment by laurenluz** [comment]
GIVstream instead of Regen Farms
Top Tweet: DAOist CDMX party

**Comment by laurenluz** [comment]
Add in fundraiser: https://forum.giveth.io/t/raising-1-000-000-for-the-angel-vault/467

**Comment by ahmadabugosh** [comment]
Hey @laurenluz , Here is the draft of the newsletter for QA: https://docs.google.com/document/d/1iwqZLPcooqvz-qR52ksPm3-mioyauWsBMeLVDRQeVZg/edit#

1) I played around with the format a bit to make it a little punchier and fun, let me know what you think! 
2)  We still have a couple of days to send it, to let me know if you want to wait to include any more info on the ICHI angel vault (the typeform etc.) 

Also @ForestSoleil let me know if you have a one liner to include for the next meet the makers (I can put it in the Top Stories section)

**Comment by laurenluz** [comment]
Hey @ahmadabugosh I edited the angel vault part & add a link to the typeform.

**Comment by ahmadabugosh** [comment]
Hey @laurenluz Cool! I made all the edits you suggested and embedded a GIF for the daoist party video (along with a blurb). Let me know if it's ready to send out (if yes I can send it our tomorrow)

**Comment by laurenluz** [comment]
Hey @ahmadabugosh - it's great. I made capitalization suggestion, but yeah! good to go tomorrow!

**Comment by ahmadabugosh** [comment]
Sent!
