### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#541]
Want to try to get our stuff higher on google, consider using certain key words

step 1: do an audit & share your findings w the team!

**Comment by jahanzaib-jay** [comment]
[https://docs.google.com/document/d/13TRiqGG-owkNPMa0rpFGbvx7C9yZHFi-G8kz39gBKQA/edit?usp=sharing](url)

Working on this link with Ahmad.

**Comment by laurenluz** [comment]
@SymSL

**Comment by laurenluz** [comment]
What is outstanding on this issue before we can close it? I know we have many other issues now for implementing these findings, but is this still in progress?

@jahanzaib-jay @ahmadabugosh

**Comment by jahanzaib-jay** [comment]
Hi, I think you can close this issue. 
We have already created an epic and are working on 5 different issues for SEO.
What do you think @ahmadabugosh ?
