### ISSUE TITLE
Amend gov process doc

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#542]
Add something saying that if they need to skip the 5 day advice process, they need to explain why in their forum post

@divine-comedian do you want to take this on? it's as per our gov call discussion

**Comment by divine-comedian** [comment]
yup! no problem

**Comment by divine-comedian** [comment]
Okay Here is a paragraph I drafted that can be inserted under the On Chain -> Decision Making Header 

## On-chain

### Decision Making

Giveth uses an [Advice Process](https://docs.giveth.io/whatisgiveth/adviceProcess) as its primary practice for flat decision making to empower contributors with agency to move their cultural proposals forward. For a proposal that will eventually move to a formal vote via the GIVgarden or [nrGIV DAO](https://aragon.1hive.org/#/nrgiv/) it must remain on the forum, open for advice, for a minimum of 5 days until it can move to a proposal on the DAO. If a proposal desires to skip or shorten the Advice Process, in the case of financial urgency for example, they may do so while providing a written disclaimer and a reason for doing so on their proposal. Skipping or shortening the Advice Process decreases the chances of a proposal passing, do so with great discretion!

. . . 
you can read the whole covenant, in its current form, to get a better idea here - https://ipfs.io/ipfs/QmPnZ7SK7JyfGkqhnAJ8wAPveWs3zehwLuLDYuY1DNBGsA

**Comment by divine-comedian** [comment]
bump here - please review and give it a :+1:

**Comment by divine-comedian** [comment]
updated in the forum and docs! did not update the covenant since it links to the gov process
