### ISSUE TITLE
blog post on regen farms

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#544]

**Comment by laurenluz** [comment]
All set, and ready for QA: https://docs.google.com/document/d/1tZ_YnFBQmoF7snwDmoG2xT3a56I6uQ58XNYmwIqVmf4/edit#heading=h.81iol0ikgzgf

@willyogo @divine-comedian @danelsuga

**Comment by laurenluz** [comment]
Sorry maybe that link is weird: https://docs.google.com/document/d/1tZ_YnFBQmoF7snwDmoG2xT3a56I6uQ58XNYmwIqVmf4/edit?usp=sharing

This one should have comment access for anyone.

**Comment by danelsuga** [comment]
This is really good, Lauren. No typos. ;)

On a personal level, I have the same question as Manuel Maccou, as I still don’t seem to understand how the numbers are so high, and I don’t understand how the article answers that question, but that is part of my learning-still-to-be-had, I guess. :D I’m exploring.

In any case, your writing is really good here. Logical clarity and flow.

**Comment by laurenluz** [comment]
Thanks @danelsuga !

The reason is because not all the rewards are liquid right away... part goes into the "stream", flowing slowly for 5 years... so it's impossible to dump the tokens all right away.

I tried to explain that in the GIVstream post (which will get published first. Does it make sense? or should I tweak it?
![image](https://user-images.githubusercontent.com/75490971/159082232-271f2e07-4f9f-4e74-8152-2ab62f4aa525.png)

**Comment by danelsuga** [comment]
Ah! Yes! I understand now. No, no need to tweak it I don't think. Thank you!

**Comment by divine-comedian** [comment]
reviewed! excellent writing @laurenluz 
left some comments

**Comment by laurenluz** [comment]
Thanks friends! I'll move this to done, ready to blast off when the product is ready

**Comment by laurenluz** [comment]
https://medium.com/giveth/regenfarms-the-next-generation-of-refi-opportunities-7a46f3cf1e09
