### ISSUE TITLE
Email/blog post to invite to add your project to Giveth

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#545]
to encourage new project to join Giveth, would be great to have a template email/post that we send to projects.

**Comment by laurenluz** [comment]
important to have it inviting/inclusive... we're not selling anything!

**Comment by jahanzaib-jay** [comment]
Here are a couple of suggestions for the email: 

https://docs.google.com/document/d/176wH2Ut6cCdDXUkkUvwVstc7IYaobzJO25LxT-Pb_I0/edit?usp=sharing

Let me know what you think.

**Comment by ahmadabugosh** [comment]
@jahanzaib-jay I made some comments on it, my main points are:

1) I think we may need two emails (one for new projects and one for existing projects that we want to have listed on our platform). Not all of them are brand new as the messaging suggests. It might make the exercise easier if you have a couple of profiles in mind of who the email would go to (that way you can write it in a voice that would be relevant for them, and not as generic)

2) I think you need to do a better job at highlighting why they should care about joining Giveth and the value proposition. Just by reading it, they might think that it's just like any other crowdfunding site, and probably wouldn't see the valiue. So for example you should include more social proof, play up the angle of zero fees, and simplify how they could access the GIVeconomy (but in a way that someone from outside the project would understand)

**Comment by oyealmond** [comment]
hey @ahmadabugosh ! Part of the new email organization ?

**Comment by oyealmond** [comment]
Hey @laurenluz ! Do you know if we can close this?

**Comment by laurenluz** [comment]
@oyealmond - up to you. we can either edit & use the content, or just close it. whatever you think is useful. I think either way is fine.
