### ISSUE TITLE
Add Newsletter February 2022 Newsletter to Docs

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#546]

**Comment by ahmadabugosh** [comment]
Hey @divine-comedian , can you please add the February 202 Newsletter to the docs
https://drive.google.com/drive/u/0/folders/1YLOFaa_oPuhqPNxozSYCr8d0EaAkdtyp

 (also if you share access with me, I can start posting them myself going forward) @laurenluz

**Comment by divine-comedian** [comment]
I would love to collab with @jahanzaib-jay  on this one and get him onboarded into using our giveth-docs so we can decentralize the task of maintaing our documentation. 

@jahanzaib-jay  are you familiar with code editors/git? let me know if this is something you want to work on together

**Comment by jahanzaib-jay** [comment]
@divine-comedian would love to work on this.

**Comment by jahanzaib-jay** [comment]
@divine-comedian I have submitted the pull request. Please let me know if it's good to go :)

**Comment by divine-comedian** [comment]
merged! https://docs.giveth.io/newsletter/February2022
