### ISSUE TITLE
Gitcoin Grants Rd 13 prep

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#548]

**Comment by laurenluz** [comment]
Since we have a DAO and an economy now, I don't think we should put a lot of work into begging for funding from GR13. However, I think we *should*:
- update our listing for [Giveth.io Panvala League](https://gitcoin.co/grants/795/givethio-panvala-league) to keep it active
- update our listing for [Giveth TRACE](https://gitcoin.co/grants/2154/givethtrace)
- shill that you can donate to the [gitcoin grants matching pool on Giveth](https://giveth.io/project/gitcoin-grants-matching-pool) & get GIVbacks
- create a nice cart of projects we love to support and share it

I think when we update both projects we should mention:
- the launch of the GIVeconomy & $GIV
- the gitcoin grants matching pool on Giveth meaning you can get GIVbacks to support open source

**Comment by laurenluz** [comment]
I made suggestions for Giveth.io grant here: https://docs.google.com/document/d/1Tkv2GZo1Ami7O8FOapeO3j5fb-c8ozov-ubBMf4cFoU/edit?usp=sharing

**Comment by laurenluz** [comment]
I think for TRACE... we should leave the explainer of what it is, say that supports are indicating that they are interested in a Giveth TRACE revamp... where we solve some of the current issues wrt costly gas.

We should also say we launched the GIVeconomy & that you can donate to gitcoin gratns via Giveth and get GIVbacks.

We should change the job link to https://giveth.recruitee.com/

**Comment by danelsuga** [comment]
@laurenluz I'm awaiting access from @divine-comedian. He didn't have my handle and so couldn't get me on the team last night.

**Comment by danelsuga** [comment]
Joined the team! Thanks, @divine-comedian! I've since updated the Giveth.io description and am going to tackle TRACE now.

**Comment by danelsuga** [comment]
I've updated TRACE now too. I haven't done any shilling nor created a nice cart of projects.
