### ISSUE TITLE
Update Univ3 content in docs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#549]

**Comment by laurenluz** [comment]
We shut off the univ3 pools after a long ordeal... we need to update the docs ro reflect the situation:
https://docs.giveth.io/giveconomy/givfarm

**Comment by laurenluz** [comment]
@cotabe can take this one!

**Comment by Cotabe** [comment]
@laurenluz here is a new version. Let me know if you can check it or we should tag someone else.

https://docs.google.com/document/d/1iT2yxwYrlROcQpRut_nLjNBW05mE-QrjPsOwVdwKuU4/edit#

**Comment by laurenluz** [comment]
Great job @Cotabe - I made some suggestions and comments. please make edits and then tag me again for final review.

**Comment by Cotabe** [comment]
Thanks @laurenluz!!! Happy to help. I made most edits already. Only two corrections missing because I don't know the exact week of the shutdown (13?), nor how to calculate the distributions per week after that

**Comment by laurenluz** [comment]
Well, the shut off date was like march 22 or something... start date was dec 24.

5 mil tokens were allocated.. and for univ3 it would be the same amount going out each week.

So see how much time passed since the start to the end... if 6 months was supposed to be the total time to distribute 5million, how many tokens was leftover when we shut off the pool.

Its easy math, but if that's confusing still, i can do it. Pretty tired ATM and probably not explaining well.

**Comment by Cotabe** [comment]
@laurenluz This is done

Just to double-check that there is no mistake... I considered 10M allocated to Univ3 as in the doc, but your comment states 5 M, this might have been an example or a mistake. Just want to make sure :)

**Comment by laurenluz** [comment]
oh yeah - you were right! my mistake :) I'll upload to the docs. Thanks so much @Cotabe !

**Comment by laurenluz** [comment]
committed changes to live: https://docs.giveth.io/giveconomy/givfarm
