### ISSUE TITLE
Airdrop to past patrons - Compile list of eligible accounts

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#55]
Put together a list of all ETH accounts that have donated to Giveth on Giveth 1, Gitcoin, and to the Giveth multisig (revolution.eth)

**Comment by willyogo** [comment]
Need to compile lists of: 
**Old Donors to Giveth directly and amount donated** - Donations to giveth grants on Gitcoin and donations to revolution.eth 
**Old Donors to Projects on Giveth and amount donated** - Donations to any campaign on Giveth 1. big projects will be FairData, Commons Stack, DAppNode, Aragon DAC, Gaia Giveth
**Old Projects on Giveth 1, organized by DACs, Campaigns, and Milestones** - List of people who created DACs, Campaigns and Milestones... there will be some details that need to be worked out here

**Comment by willyogo** [comment]
Hey @aminlatifi! Can we get a status update on this?

**Comment by ForestSoleil** [comment]
@aminlatifi How is this going? Can you share a status update? we are beginning our 2nd sprint for GIV Token tomorrow. thanks!

**Comment by aminlatifi** [comment]
@ForestSoleil I sent you a report in discord DM, see whether it fits

**Comment by willyogo** [comment]
@aminlatifi thank you for the list of all donors to projects on Giveth! That looked perfect. Can you also export the addresses of anyone who created a campaign, milestone, or DAC on Giveth?

**Comment by aminlatifi** [comment]
@willyogo Yes it's possible, just let me know when you need it

**Comment by aminlatifi** [comment]
The script to generate latest report is ready, you can see report of now here
https://github.com/Giveth/feathers-giveth/pull/394#issuecomment-787941790
