### ISSUE TITLE
Edit cryptophilanthropy club podcast

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#551]
Review Griff's podcast.

**Comment by danelsuga** [comment]
Task completed.
Waiting for Cleo from the club to confirm.

**Comment by danelsuga** [comment]
This has been passed back to Alex from the cryptophilanthropy club for review.

**Comment by danelsuga** [comment]
I suggested the following bites:

5M40
Giveth is trying to be that focal point to bring all of these forces for good together on one even playing field.

6m20? There is no other donation platform that does what Giveth can do.

12m25 Our mission is to make giving effortless and frictionless and so I think we're making great headway on that.

12m45 The biggest dream of Giveth is to actually be able to give them away to augment their project from just receiving donations to actually having a DAO, having their own economy that rewards them for the good work they're doing.

15m30 We believe in the ability for communities to come together and design their own economic game.... Giveth is creating a sort of path towards that. ..... When I say collective economic game I mean basically people with tokens can vote to reward the package of tokens that they collectively control according to who is producing towards the mission. 

20m00 we start with nonprofits at zero that have no idea what crypto is...... We take this pattern of when people succeed on the platform, we support them into reaching the next step.

20m45 Would you like to DAO? Let's DAO! Let's learn how to govern, let's learn how to decentralize and collectively govern your project.

22m00 Hey volunteers how about you get rewarded too? This is the trickiest part of Giveth. It's really hard to get non profit people to believe that their work has value when they've been traumatized for decades of being told that they have to volunteer and sacrifice to do the work that they're doing, to create value for society.

31m30 We have just basically created a system that will allow nonprofits to turn into reward-based regen economies. And they can start rewarding their volunteers and maybe even start paying salaries. And people can actually speculate on their success. This is what really gets me excited... Taking all the great parts of the free market, capitalist society and leaving the bad. What if starting a nonprofit had the same investment capabilities as starting a tech start-up?

32m20 We're taking the people on the ground through a journey so they can learn how to master these tools. And as they succeed then we help them take the next step to the point where they've built their own economy and they have agency and they can use it to achieve their goals.

36m18 I dream of a day where communities can design their own economies and these nonprofits can actually have the tools to build a competitive startups on their own to do good work in the world.

44m20 We're never going to get rid of politics over shared resources [that's not what I'm proposing.], but I do think that we can bring these politics to the forefront and have clear decision making processes. And more importantly, reward the people fairly and competitively for doing collective work that creates value. And we can do that in a better way than has ever been done before if we take agency over the creation of our own currencies.

53m00 Jump on Giveth and try donating to something. It is so cool and fun and easy, and you get paid to do it!

My personal favorites are 44m20 and also the ones in the 30s.

**Comment by laurenluz** [comment]
@danelsuga this is great!!!!!!!!!!!!!

does this need to go to anyone else? or do we call it done?

**Comment by danelsuga** [comment]
Thanks! I think we can call it done. I sent them to her (didn't hear back but she did receive them). 

Guess it's done! :D

**Comment by ahmadabugosh** [comment]
Hey @danelsuga I was a bit confused by this issue, do you want me to make sound bites videos from these?

**Comment by danelsuga** [comment]
Not at all. This is unrelated to that issue.
