### ISSUE TITLE
ETHDenver talk video summaries

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#553]
To be posted as youtube video descriptions @danelsuga has written them already!

**Comment by danelsuga** [comment]
I have descriptions of Griff and Willy's talks for EthDen that I will add to their YouTubes.

**Comment by danelsuga** [comment]
Here are those descriptions.

https://docs.google.com/document/d/1p_JRxHU5hzgBYHPPa5Ewt8faQkxmnKfZD5fbNO12Ipc/edit?usp=sharing

**Comment by laurenluz** [comment]
meeeeee! This is awesome. Let me see what kind of hacks I can do to get them in there.

**Comment by laurenluz** [comment]
Hey @danelsuga I actually don't have access to those videos on YouTube, so I asked Griff the best place for this. He suggested the Giveth Forum.

Can you add each of these descriptions to the Giveth forum with a link to the youtube video? 

You can title them like: <name of the talk> Talk Summary
or whatever you think.

This would be nice because then they are easily to share externally.

once it's done, you can close this issue :)

**Comment by danelsuga** [comment]
Got it!

**Comment by danelsuga** [comment]
Creating Schelling Points for Public Goods via Micro-economies
https://forum.giveth.io/t/ethden-2022-talk-summary-creating-schelling-points-for-public-goods/548

The Biggest Web3 Opportunity That No One Is Talking about
https://forum.giveth.io/t/ethden-2022-talk-summary-biggest-web3-opp-no-one-is-talking-about/549

Building a Future without Fees: Positive Sum Economies
https://forum.giveth.io/t/ethden-2022-talk-summary-positive-sum-economies/550
