### ISSUE TITLE
Twitter MEGA THREAD for ETHDenver

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#554]
can use all the soundclip videos to this thread - JACK!

**Comment by laurenluz** [comment]
Here's the draft post: https://medium.com/giveth/giveth-at-ethdenver-2022-964aa457878c

**Comment by jfbtheii** [comment]
https://docs.google.com/document/d/1kaK_1zSdNvulQ2U6xJVZXXBSDLG5oOY44w4QYt6DL4o/edit
Still WIP but the mega thread is coming along.

**Comment by jfbtheii** [comment]
@laurenluz

**Comment by laurenluz** [comment]
Hey @jfbtheii! Looking good! I know you're not finished but I left some comments in there. As general feedback, try to find the hard hitting points to use as tweets and avoid the "check this out". "Check this out" is good too, but I find we get more engagement when we have something meaty to say.

Lmk if you have questions!

**Comment by jfbtheii** [comment]
Got it! sounds good

**Comment by jfbtheii** [comment]
Ive touched up the thread and have a more completed rough draft to check out. Could you help me get a big group pic for the initial tweet of the thread and a twitter link for your interview with iUSA? Also, let me know what other adjustments would be necessary!

**Comment by laurenluz** [comment]
Ok! here's a tweet for iUSA: https://twitter.com/karmaticacid/status/1503521594987188226

And for a group pic, this is really the best we got:
![image](https://user-images.githubusercontent.com/75490971/158280262-76ad2fd4-e6e9-43a4-9bfe-6fa00a0d92b7.png)

**Comment by laurenluz** [comment]
Made some comments @jfbtheii

**Comment by laurenluz** [comment]
Coming along great! I made a couple more comments :) almost there

**Comment by jfbtheii** [comment]
Touched up the final comments and moved back to review @laurenluz

**Comment by laurenluz** [comment]
@ahmadabugosh this is the twitter thread for ethdenver

**Comment by laurenluz** [comment]
Looks good @jfbtheii ! I made some small edits. I think we can use the video sound bites that Ahmad is prepping and then put this out!

**Comment by jfbtheii** [comment]
Cleaned up those edits. Sounds good, the sound bites will be a great touch! @laurenluz

**Comment by jfbtheii** [comment]
The sound bites are awesome! The only thing is they are an off-platform link rn. Should we have the sound bites embedded so there are no links moving away from Twitter?

**Comment by ahmadabugosh** [comment]
@jfbtheii For sure you should upload them on Twitter directly! I downloaded the ones I made so far here: https://drive.google.com/drive/u/0/folders/1m4HJ-wLf1tc9OoYSbiUJMzUlhxEmkkgn

**Comment by ahmadabugosh** [comment]
hey @laurenluz @jfbtheii do you think this will go up before Wednesday (so I can include it in the newsletter)?

**Comment by laurenluz** [comment]
I'll try to share it today or tomorrow, just trying to review all the sounds bites & get it organized. will post here when it's done.

**Comment by laurenluz** [comment]
@ahmadabugosh https://twitter.com/Givethio/status/1508458566075703299
