### ISSUE TITLE
Ukraine Tweet thread - how can you help

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#555]
https://docs.google.com/document/d/1kaK_1zSdNvulQ2U6xJVZXXBSDLG5oOY44w4QYt6DL4o/edit

@laurenluz this is ready for review

**Comment by laurenluz** [comment]
@jfbtheii I left some comments in there - looks really good!

Would love to shoot this off soon if we can, if you can dive in with edits today & have it ready for me to send tomorrow morning, that would be great :)

**Comment by jfbtheii** [comment]
Sounds good!
