### ISSUE TITLE
SEO: Create Search Console / Webmaster Tools and submit sitemap

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#557]

**Comment by ahmadabugosh** [comment]
Hey @laurenluz @WhyldWanderer, do you know if we have Google Search Console setup? https://search.google.com/search-console/about

It's super easy to do, and it lets us submit our sitemap directly to Google to make sure all of our pages are properly indexed, so if we haven't done it, we definitely should!

**Comment by laurenluz** [comment]
@geleeroyale do you know if we have anything like this setup already?

**Comment by geleeroyale** [comment]
However you want - can I also add you as a manager to the existing one?

**Comment by ahmadabugosh** [comment]
@geleeroyale Oh great! If you still have access to the old one, please add me, that should be enough! 🙏 ahmadabugosh@gmail.com

**Comment by ahmadabugosh** [comment]
This is done
