### ISSUE TITLE
SEO: Create one article to rank for

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#560]

**Comment by laurenluz** [comment]
This could be part of the RegenFarms announcment piece, would be great to get a list of key words to include. @jahanzaib-jay to share spreadsheet :)

**Comment by jahanzaib-jay** [comment]
List of Keywords to include:
https://docs.google.com/spreadsheets/d/12WramHIFG2dZDI7PA-Pwqsa_dQHR3yRFi_msaV0dUWo/edit#gid=0

SEO DOC: 
https://docs.google.com/document/d/13TRiqGG-owkNPMa0rpFGbvx7C9yZHFi-G8kz39gBKQA/edit#

I will go through the list of KWs again and update the KWs we can include in the upcoming article.
