### ISSUE TITLE
SEO: Add subdomain for Medium

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#561]

**Comment by jahanzaib-jay** [comment]
Hi @ahmadabugosh , I went through a few crypto websites and found out that most of the crypto platforms do have a blog page on their website. In most cases, the blog page is at the bottom of the website. 

Keeping this in mind, I still think that adding a blog page on our website is the best way to go and it will add a lot of value in terms of SEO. 

Let me know what you think.

**Comment by jahanzaib-jay** [comment]
@laurenluz @WhyldWanderer @SymSL what are your thoughts on this?

**Comment by ahmadabugosh** [comment]
@jahanzaib-jay I think it's an easy win if we just make the medium be on a subdomain, like blog.giveth.io : https://help.medium.com/hc/en-us/articles/115003053487-Setting-up-a-custom-domain-for-your-profile-or-publication

That would keep us on Medium but allow us to build up the ranking of the giveth.io domain.

**Comment by SymSL** [comment]
Hi everyone, thanks Jahanzaib for the research, I agree with Ahmad about the easy win and creating the subdomain rather than adding it to the site directly. I did some reading up between the SEO benefits of subdomain vs subdirectory, and seems like it's an ongoing debate but Google views it the same and attribute the SEO closely to the main site so that will be the most beneficial. Here is an article on it if you're interested :) https://blog.hubspot.com/marketing/subdomain-vs-subdirectory. If we feel at any point we aren't getting the SEO benefits then we can relook in a few months but I think this should work according to the article

**Comment by laurenluz** [comment]
Next steps:
- @ahmadabugosh to check with tech support that previous links reroute
- pass to devops team to add subdomain to our domain & point to medium
- @laurenluz to change settings in medium

**Comment by ahmadabugosh** [comment]
Hey @laurenluz , they said the old links will automatically redirect (it's in their [FAQ's](https://help.medium.com/hc/en-us/articles/115003053487-Setting-up-a-custom-domain-for-your-profile-or-publication) second)

@geleeroyale , can you help us add a subdomain to our DNS, so we can redirect our medium to it? We were thinking: blog.giveth.io

(you can read the instructions on what IP to point in the A records for that subdomain here: https://help.medium.com/hc/en-us/articles/115003053487-Setting-up-a-custom-domain-for-your-profile-or-publication)

**Comment by geleeroyale** [comment]
Sure! We can add a simple redirect for free - in fact we already have one (medium.giveth.io). So we could just add ` blog.giveth.io` and redirect it like the other one

If we want to go the route that is described in the medium post you linked, we would need an active subscription - do we have one?

**Comment by laurenluz** [comment]
what's an active subscription? we have a very active medium! https://medium.com/giveth

**Comment by ahmadabugosh** [comment]
@laurenluz I think @geleeroyale means a paid Medium membership subscription (which is like $5 a month I believe). I'm not 100% sure if this is needed or not  for publications (if you add me I can check the settings)

**Comment by geleeroyale** [comment]
It's from the link posted above:

![Screenshot_20220404-213451.jpg](https://user-images.githubusercontent.com/317685/161618742-4c14d475-3242-4c6f-ac4c-bcbf5e86ed45.jpg)

**Comment by geleeroyale** [comment]
Incredible! Keep me updated - If you come to a point were they tell you the only thing missing is setting up the DNS record I will do that promptly!

**Comment by laurenluz** [comment]
@ahmadabugosh only the publication owner can so anything w/ custom domain. I am not the publicatoin owner. It might be Griff, Krisis, Jeff Emmett, Jordi 🤔 not sure, needs catherding,

![image](https://user-images.githubusercontent.com/75490971/165637973-9283b8a4-49fb-4949-930c-671be82ae05c.png)

**Comment by geleeroyale** [comment]
@krrisis Do you know who owns Giveth Medium?

**Comment by krrisis** [comment]
Yes, Griff.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GriffGreen** [comment]
Ok! So can we confirm this looks good... 
<img width="705" alt="Screen Shot 2022-04-28 at 1 48 27 PM" src="https://user-images.githubusercontent.com/14945613/165833969-1b12a7cb-5a61-490b-9b5f-f129eff3078f.png">

Then thethe next step is on @geleeroyale and i can click continue

**Comment by geleeroyale** [comment]
Ooops - did not see this in the sea of GitHub notifications. Record has been set - you can click continue :-D

**Comment by geleeroyale** [comment]
@GriffGreen Can you try going there again and hitting continue? (If the numbers did not change) - If they did change, please dm them to me and I will set them promptly. Let's do this 👯‍♂️

**Comment by GriffGreen** [comment]
This is fucked up crew... i'm sorry I didn't prioritize this faster and now the feature is removed 👎 

https://help.medium.com/hc/en-us/articles/115003053487

![Screen Shot 2022-05-18 at 11 10 25 AM](https://user-images.githubusercontent.com/14945613/169102897-9fb57a5f-d821-4779-a55b-1ef5dd5494c5.png)

I'm sorry i failed us :-(

**Comment by geleeroyale** [comment]
I can redirect blog.giveth.io to our medium publication if its any consolation 😃

**Comment by ahmadabugosh** [comment]
Medium reactivated this feature, I think we just need to pay for Medium (which is just $50 a year, I think totally worth it for the SEO benefits).  https://help.medium.com/hc/en-us/articles/115003053487

@GriffGreen can you set this up for us (get a medium membership and then choose a custom subdomain blog.giveth.io)?

**Comment by ahmadabugosh** [comment]
This is done! Our blog now redirects to: https://blog.giveth.io/
