### ISSUE TITLE
Update nrGIV info in the Docs

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#562]
We have a new rGIV DAO... **nrGIV**

The documentation should be updated to reflect this
https://docs.giveth.io/whatisgiveth/governanceProcess/#rgiv-token-holder

**Comment by danelsuga** [comment]
I thought I could tackle this no prob, but I'm confused. From first paragraph of doc: 

"rDAO members hold nrGIV"

And above, @WhyldWanderer says, "We have a new rGIV DAO... nrGIV."

I don't understand the distinction among the following concepts then:
rGIV
rDAO
rGIV DAO
nrGIV

Thank you!

@laurenluz

**Comment by danelsuga** [comment]
I made changes in two places: 
Governance Process
Giveth Finances

**Comment by laurenluz** [comment]
Hey @danelsuga - did anyone review this? we have a practice of 2 reviewers QAing anything before it goes live on the docs. Sometimes excepts can be made to allow only 1 reviewer

**Comment by danelsuga** [comment]
Oops. Sorry @laurenluz Don’t know why I did that. Particularly as I didn’t do hard changes but forks to be approved!

**Comment by danelsuga** [comment]
Finances: danelsuga-patch-3
Gov: danelsuga-patch-1

I made the PR with @laurenluz and @WhyldWanderer to review. 

Sorry about that!

**Comment by laurenluz** [comment]
@danelsuga did you make that one small tweak? is this done and ready to go?

**Comment by danelsuga** [comment]
I've fixed it in the patch if you just want to approve that now. Thx. @laurenluz
