### ISSUE TITLE
Research article with Jeff Emmett

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#563]
I’ll be working on a series of articles with Jeff Emmett, the first being related to E. Ostrom’s work on the 6 challenges of a commons.

**Comment by laurenluz** [comment]
@danelsuga can we close this one?

**Comment by danelsuga** [comment]
We can close it as long as it’s on your radar. I am not at all close to completing the first one, as I have not been able to commit adequate time yet.

**Comment by danelsuga** [comment]
Bear market has put this on hold.
