### ISSUE TITLE
Testing environment: Typo in the web copy

### ISSUE THREAD

**Issue by jahanzaib-jay** [Giveth/giveth-planning#565]
Hi everyone, 
I was going through the web copy of the testing environment and found a typo on the homepage. 

![1.png](https://images.zenhubusercontent.com/620d7be8f7acb77200f9d2d9/f6fe8731-b76f-45f4-9804-a77ff6090eeb)

it should be add "your project"
we are missing an "R"

Will go through the entire copy again and suggest changes (if needed here in this thread)

**Comment by jahanzaib-jay** [comment]
@laurenluz @WhyldWanderer @ahmadabugosh

**Comment by laurenluz** [comment]
@jahanzaib-jay Thanks for reviewing the DApp! The correct place for issues like this is the v2 repo - this is where the devs will see it and be able to fix it.

That said, this typo was already caught and and issue was made: https://github.com/Giveth/giveth-dapps-v2/issues/153

It's amazing if you want to go through v2 and make any other issues, but make sure you check the repo to make sure that an issue has not already been created :)
