### ISSUE TITLE
Marketing plan working document

### ISSUE THREAD

**Issue by SymSL** [Giveth/giveth-planning#567]
I've started on a document with the intention to consolidate our marketing efforts and create a strategy of what will bring the most impact quickest, but also just to add to and track our growth from month to month. I am adding to it but will be more effective with more hands and minds involved in improving it so adding it Here: https://docs.google.com/presentation/d/1DTGwC6jNBJTYSdFAnseDlC_iQq_SOWQxEsLNtur56sU/edit?usp=sharing

You will see its a skeleton with some notes for now and needs the input of many others who have more insights than I do. If this isnt a duplication of someone elses work, I'll keep adding to it from what I can see on Orbit & our channels, and we can have a chat about it perhaps next week? 

Adding this as a task so we can have others join in with this and share their knowledge.

@laurenluz @WhyldWanderer @ahmadabugosh

**Comment by laurenluz** [comment]
@jfbtheii @jahanzaib-jay are interested in supporting on this as well!

**Comment by SymSL** [comment]
Document has been expanded and now includes:
Giveth overarching communication goals
Audiences and audience insights
Messaging matrix
Channel growth goals
Priority channels to plan for

Todays planning session to expand on the plans for some channels. We focussed on: 
**Giveth Newsletter content** (cadence will continue at once per month) & we will set up a content session once every 2 weeks to discuss content across a few of our channels (not only for the Giveth newsletter) but which will help with planning ahead
**Giveth Social** - We will start having planning sessions/check ins for Giveth Social (Focus on Twitter for 301s and Instagram for 201s for now)
**Giveth Website** - We will have a dedicated session to focus on how we could encourage visitors on the site to become donors/create a project/ suggest a our org to project? or (at least) join our community before they leave. We will also need to install metrics on to the site to track numbers - Ahmad is already having conversations on this

We will create issues for each of these

**Comment by SymSL** [comment]
2 more documents have been created from this effort, the Content Planning [sheet](https://docs.google.com/spreadsheets/d/17Mgd1pfPsC1q50FlO59PtsKph8js3Kr7ou_LKA-K5qc/edit?usp=sharing) where the plans for channels can be created and shared, and the [Content ideas document]

(https://docs.google.com/presentation/d/1n6kmd5YMlFr0FEY9JtpzWrBtoZkvZLb8jK5fl1RjwIU/edit#slide=id.g12a455db593_0_0) for contributing info that would work as cool and engaging content for our users.

**Comment by SymSL** [comment]
Next step is to fill out the social and blog/newsletter plan more concretely (and not over commit to the amount of content that can be done) and then to expand the calendar to include a plan to engage influencers to promote Giveth and help onboard more donors.

**Comment by ahmadabugosh** [comment]
Hey @SymSL thanks for putting this together! 

A couple of comments I have
1) Can you please add my email (or make the doc publicly editable)? 
2)  Just in terms of building a process and getting started, I think that it would make more sense to have it be split by month instead of day by day, since I think it would get tedious and daunting to fill out what we want to post every day here. Plus for Twitter and Instagram there would be a lot of spur of the moment content shared. So it might be: for June we want to share these 10 pieces of content, rather than: this is what we need to post exactly for all 30 days and we need to know the exact post for each day. 
Wdyt?

**Comment by SymSL** [comment]
Hey @ahmadabugosh thanks so much for the feedback, I have added you to the docs and made sure anyone with the link can access so let me know if you have any hassle. I hear you on the daunting task of each day so have opened a new tab that simplified it to the 4 weeks of each month which does make it look alot easier to digest :) Whoever does the planning can then expand on it in more detail
