### ISSUE TITLE
Autopilot Audit and Cleaning

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#568]
We need to clean it up, see if we want to move to something more advanced.

Current use case:
- donors emails
- project emails

@WhyldWanderer is pretty familiar with the ways we are using it. Ashley can you work with @ahmadabugosh & @jahanzaib-jay to explain what we're doing... then they can take over doing an audit and assessment

**Comment by ahmadabugosh** [comment]
Hey @WhyldWanderer the context of this is that @divine-comedian was telling me (and I agree) that we need to dive deeper into how we're using Autopilot in relation to "user journeys, contact management system and email content, links, media etc.." . 

I've already been using it for the monthly newsletter but also when I send the Givbacks email, I'll see how the flow is, then based on that I'll update you on what I recommend we do (and we can have a discussion once you're back)

**Comment by laurenluz** [comment]
@Cotabe tagging you because you mentioned you were interested in this

**Comment by Cotabe** [comment]
@laurenluz I am happy to help with this. I think @jahanzaib-jay also mentioned he has expertise on it and can contribute.

I think I will have the bandwidth from Wednesday or Thursday

**Comment by divine-comedian** [comment]
@Cotabe  please feel free to reach out since myself and @WhyldWanderer  have done a huge chunk of the setup that already exists on autopilot

**Comment by Cotabe** [comment]
Ok, I have bandwidth again. I will reach out @divine-comedian

**Comment by jahanzaib-jay** [comment]
A suggestion: When someone subscribes to the email, he/she should receive a thank you email- confirming the subscription. 

I tried subscribing with 2 different email addresses and didn't receive any confirmation.

**Comment by jahanzaib-jay** [comment]
This could be the text for the email:

Hello!

Welcome to the Giveth community! We are excited to have you on board.

Our goal at Giveth is to use blockchain technology to build the future of giving. We believe that by creating open, transparent and free access to the revolutionary funding opportunities available within the Ethereum ecosystem, we can support and reward the funding of public goods. We would love to have you involved in our community!

If you're interested in learning more about what we're doing, please check out our docs or join our Discord channel. 

Till next time... 
Regards,

**Comment by ahmadabugosh** [comment]
Here is a doc of all the processes we're using Autopilot for (I'll keep adding to it): https://docs.google.com/spreadsheets/d/1d34y9rsX8LU--kI7b-EcAfEhkt3XlWhew2Eiu8KlE7E/edit#gid=0

**Comment by Cotabe** [comment]
I think this comment is suited for this epic.

In the "Thanks for Donating" email, it says "you may be eligible to receive GIV tokens after this GIVbacks round ends!".

At least for me... this immediately trigers a reaction of on what does it depends... maybe we can word it that does not triggers this reaction without compromising if for any reason there won't be GIVbacks

**Comment by Cotabe** [comment]
I miss some emails because it arrives to my promotions tab.

If possible, I would suggest to send the emails from another email & build positive reputation to prevent getting tagged as a promotion. For example, ask something to get replies.

I can help with that :)

**Comment by divine-comedian** [comment]
nice! that's a great idea - maybe having separate email sender address too might help us get important emails through

**Comment by oyealmond** [comment]
should we close this @divine-comedian as you are already working on the migration?
