### ISSUE TITLE
Content Calendar

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#571]
Google sheet of upcoming important dates
@Elizardwizzard to set up a template for content calendar - Lauren to add in dates

**Comment by Elizardwizzard** [comment]
Hey! Does this looks good?
Twitter
https://docs.google.com/spreadsheets/d/1VOOt3q5VPItxK7STBBC-qYSzX5qhHBf2Z1i-R8Ok9ko/edit?usp=sharing

Newsletter
https://docs.google.com/spreadsheets/d/1VOOt3q5VPItxK7STBBC-qYSzX5qhHBf2Z1i-R8Ok9ko/edit?usp=sharing

**Comment by laurenluz** [comment]
Hey Elizabeth! It looks really nice, but I think something a little simpler to start would be better. Maybe set it up the columns at the top being days of the week, and then there are rows below.

You could have multiple rows too, starting with just:
Twitter
Medium
DApp
Autopilot

and there's like 1 box per media per day... we don't need so many categories to start. I think this is more just to visualize all the major things coming up.

I'm not sure I'm explaining that well, but something like this pic:

![image](https://user-images.githubusercontent.com/75490971/159073653-889e5c48-b3be-4368-8e17-567d3a6e9856.png)

**Comment by ahmadabugosh** [comment]
hey @Elizardwizzard ! yeah I agree with Lauren, I think for now it needs to be a bit simpler like an Editorial calendar (here are some examples from Hubspot: https://blog.hubspot.com/marketing/business-blog-editorial-calendar-templates) 

I think the main fields we need to capture for now are 1) Date and 2) Description of the content (this could also include a url, key messages talking points, calls to action etc) and 3) Channels (where we want to post it)

One way of doing it might just be to have each row one content piece and just add columns with all the fields (that would make it more structured like a database and we could filter by channels and even visualize it), but I'll leave it up to what you think makes sense!

**Comment by Elizardwizzard** [comment]
Something like this? I added some extra columns that might help to organize/assign the content pieces (author, due date,  topic and keywords) if they are not needed I can remove them :) ahttps://docs.google.com/spreadsheets/d/1VOOt3q5VPItxK7STBBC-qYSzX5qhHBf2Z1i-R8Ok9ko/edit#gid=1125462361

**Comment by ahmadabugosh** [comment]
@Elizardwizzard I added a few minor edits (like making Twitter and the Newsletter seperate tick boxes). I think it's fine to start using for now, we'll probably start changing it once we start populating it with data. Let's discuss it in today's meeting :)
