### ISSUE TITLE
Update Project Deactivated email

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#573]
It feels really scary when the user has deactivated their own project.

Maybe this can be:

Your project, This project is a test, has been cancelled or deactivated! 🚨 🚫

It is no longer displayed on the Giveth.io DApp and cannot receive donations.
- If you deactivated your project, no worries! This email is just a confirmation.
- If you did not, there is a chance it has been flagged as suspicious or violated our [Terms of Service](https://giveth.apms5.com/anywhere/m?s=giveth&m=tr_98fbc890-51f2-420c-902e-47d13d3a6d9c&u=e1jq4wvfdtfkeh1r74tkaghn5mtm4g9r5mu4ahhh5n13ed9h5n0m4h9r6x34adj26x1k6&r2=d1u78w3k78qjytv9etjq8u1ed5qjyx3fec&n=1) and was cancelled by an Administrator.

A few examples of why Giveth deactivates projects: 

- The use of violent or sexualized language or imagery, and sexual attention or advances of any kind
- Trolling, insulting, derogatory, abusive or vulgar comments, and personal, political, or religious attacks
- Public or private harassment
- Publishing others’ private information, such as a physical or email address, without their explicit permission (including doxing)

If you would like to review your project on Giveth and get it project re-activated and open for donations, reach out on the support channel in the [Giveth Discord](https://giveth.apms5.com/anywhere/m?s=giveth&m=tr_98fbc890-51f2-420c-902e-47d13d3a6d9c&u=e1jq4wvfdtfkeh1r74tkaghn5mtm4g9r5mu4ahhh5n13ed9h5n0m4h9r6x34adj26x1k6&r2=d1u78w3k78qjyt39edhpywk45tkpjxk5ehm2wubf&n=2).

![image](https://user-images.githubusercontent.com/75490971/158701864-8c5bd459-a10f-4f5e-a178-eeb070f83f1f.png)

**Comment by ahmadabugosh** [comment]
Done @laurenluz !
