### ISSUE TITLE
Blog Post: A Hitchhikers Guide to the Giveth Galaxy

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#574]
The purpose: to help blockchain4good folks understand how all these orgs relate! Including:
- Giveth
- Commons Stack
- TEC
- General Magic
- Trusted Seed
- BrightID
- DAppNode

Mention also:
- Whitehat Group
- Iden3
- Hermez

@GriffGreen can help provide a lot of context for this post!

**Comment by danelsuga** [comment]
work-in-progress


https://docs.google.com/document/u/1/d/10Zd96ZZYHQd77EWw8kKfwz35dIP0-bkOOtUxtg6a2uw/edit

@laurenluz @GriffGreen

**Comment by GriffGreen** [comment]
oooooo

**Comment by danelsuga** [comment]
Ready for some eyes on this thing. I tried to keep it short, as it had the potential to get huge, which I don't think would be useful.

A few more additions by @GriffGreen might be in order however.

@laurenluz  

https://docs.google.com/document/d/10Zd96ZZYHQd77EWw8kKfwz35dIP0-bkOOtUxtg6a2uw/edit#

**Comment by danelsuga** [comment]
This should be done, but there are a couple details I can't find the answers to. Can you have a look again please? Thank you!

@laurenluz 
@GriffGreen

**Comment by laurenluz** [comment]
I will go through it all today! I didn't get a chance to finish on my last read through. So sorry for the delay.

**Comment by laurenluz** [comment]
@divine-comedian @WhyldWanderer If either of you have any bandwidth, would love some QA support, I haven't yet had a chance to go through fully.

@geleeroyale @Danibelle might be good to get your comments as well if you feel like it! Since you are familiar with a lot of the history of giveth & the galaxy!

**Comment by Danibelle** [comment]
Ok I gave it a pass, added some comments with link offerings and a few edit suggestions ;)

**Comment by divine-comedian** [comment]
added some comments - i think this doc needs some restructuring, the story gets a bit lost in the weeds in details. Details are important but I felt in general that I got exhausted reading this article at some points.

I wish I had more concrete feedback but this is what I noticed while reading.

**Comment by danelsuga** [comment]
Guess I'm too much of an academic!

This article is bring recast to be shorter, etc. 

Stand by.

**Comment by danelsuga** [comment]
New draft

https://docs.google.com/document/d/1DkYQ1SbqdTFQciPXnZ4Q3c8BWpv8pPtkdooMi04OnkQ/edit?usp=sharing

**Comment by laurenluz** [comment]
Hey @danelsuga! It's coming along really well. I made it through up to 1hive in more detail. Some general comments:
- I think skipping the founders names would really help things feel more focused & save space
- for a lot of the resrouce links, add them to words/phrases instead of having sentences like "you can find this explained here", it will help cut it down too

Also, I think having a "thesis" kind of like "we are all trying to change the way we fund public goods by building DAO toolkits that will eventually enable nonprofits to become DAOs w/ regen microeconomies" would be really good. I tried to add comments around that. 

I also thing the way that bright & dappnode fit into that as well are like... adding infrastructure layers. would love to see a little more linking the orgs, you know? I tried to make some examples in the first ones like giveth to commons stack to TEC.

super happy to chat more about this, but it's really getting there! take a look at my comments and lmk what you think.

**Comment by danelsuga** [comment]
@laurenluz please have a peek when you get a chance! I tried to weave in the metaphor. Each section has a segue into the next. The ending might be tweaked still? Give me your feedback! Thank you.

**Comment by laurenluz** [comment]
YEAH! I'm loving it!! especially the beginning & the first 3 stops... really strong thread of connection.

I totally agree with you, I would definitely tweak the ending a bit, but before that, I would love see a tiny bit more connection between Giveth & the bottom orgs - particularly iden3 & hermez. I left a long comment at that secion... kind of debating the idea of keeping founders names out completely or putting them in a little when necessary for the story. I think here it might be necessary.

Anyway, have a look!

**Comment by danelsuga** [comment]
I'm desperate for this to be done! Tell me what you think @laurenluz. 

https://docs.google.com/document/d/1DkYQ1SbqdTFQciPXnZ4Q3c8BWpv8pPtkdooMi04OnkQ/edit?usp=sharing

**Comment by laurenluz** [comment]
@danelsuga just finished QA-ing! It's great!

Are you still going to update the images for Giveth & TEC? I think we should use current branding.

Otherwise, I think you could just integrate those last suggestions and put the draft in Medium. I'll give it a final read when you submit to the giveth publication.

Next steps:
- [ ] write tweet announcement & even a thread (that's on me)
- [ ] do a little outreach to other DAOs/twitters letting them know it's coming and asking them to reshare (probably on me too, but perhaps we could do outreach together)

**Comment by danelsuga** [comment]
Thanks @laurenluz  
Got the new Giveth banner. I pulled the TEC from the website. Should I find one somewhere else?

**Comment by laurenluz** [comment]
@rodricastillo9013 do you have access to the right banner/branding for the TEC? I thought it should be yellow. This is what we have right now:
![image](https://user-images.githubusercontent.com/75490971/169896018-0f312fc3-1046-4129-8fbb-f28b832e1bd5.png)


@danelsuga once that's fixed, draft it up in medium and submit to the giveth publication :)

**Comment by rodricastillo9013** [comment]
@laurenluz Hello, I can prepare one with the indicated colors

**Comment by laurenluz** [comment]
@rodricastillo9013 la cosa es que estamos buscando el logo mas usado por TEC... yo pense que era amaillo pero en realidad... si ellos queren el azul, podemos usar esto.

Creo que usted sabe mejor que yo. Deberia que ser amarillo? or Azul?

si es amarillo serie super bueno si nos podriamos ayudar con esto 😅

**Comment by rodricastillo9013** [comment]
<img width="703" alt="banner" src="https://user-images.githubusercontent.com/61791380/170085130-83732f30-c701-4267-bfa0-8fa533847a6a.png">
algo asi esta bien @laurenluz

**Comment by markoprljic** [comment]
> @rodricastillo9013 la cosa es que estamos buscando el logo mas usado por TEC... yo pense que era amaillo pero en realidad... si ellos queren el azul, podemos usar esto.
> 
> Creo que usted sabe mejor que yo. Deberia que ser amarillo? or Azul?
> 
> si es amarillo serie super bueno si nos podriamos ayudar con esto 😅

I don't understand Spanish, sorry :(

**Comment by markoprljic** [comment]
> The problem is that I am not sure this "yellow" multicolored one that I've inserted here is more up-to-date. I feel like it is not. I feel like this is the old branding that springs from Commons Stack (they look very similar).

Yes we use this one, and solid yellow as well. 
All branding assets can be found here https://github.com/CommonsBuild/tec-branding-assets

**Comment by danelsuga** [comment]
Thaaaaaaanks @markoprljic !

**Comment by laurenluz** [comment]
Thanks everyone!

**Comment by danelsuga** [comment]
So @laurenluz I have the multi-colored one, but the background is white. Same for yellow. Do we want it black? The multi-colored one with the black background is something I pulled off the web, so it's so res and tiny.
![TEC Logo Full Color](https://user-images.githubusercontent.com/81351744/170435263-1277bf7b-58b3-4720-bb5b-8b4820dbd964.png)
![TEC Logo Full Dark](https://user-images.githubusercontent.com/81351744/170435270-977709d5-c6d0-4753-a3ff-61896b310856.png)

**Comment by rodricastillo9013** [comment]
yes!
<img width="703" alt="TEC" src="https://user-images.githubusercontent.com/61791380/170551556-e2b5e3dc-3b25-4660-913c-a59c50f45070.png">

Done

**Comment by danelsuga** [comment]
Woohoo! Gracias!

**Comment by danelsuga** [comment]
@laurenluz This article has been submitted to Giveth on Medium. I suggest we publish it after the winner of the Commons Prize is announced (should be this week?), so that we can include that.

**Comment by laurenluz** [comment]
Perfect!

**Comment by laurenluz** [comment]
POSTED! So happy to close this issue. Thank you @danelsuga for all your hard work!!!!!

https://medium.com/giveth/the-hitchhikers-guide-to-the-giveth-galaxy-3e081d31f6c5

**Comment by danelsuga** [comment]
Yes!! Thank you so much, Lauren!! Sooo much help. This one was almost like having a baby. Almost... (not at all actually but still...) 🤣

**Comment by laurenluz** [comment]
hahahahahaa
