### ISSUE TITLE
Add terms & conditions for conviction voting to docs, and link to it from the covenant in the GIVgarden

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#575]
Ivy created this for the TEC: https://docs.google.com/document/d/1BltyTWMCkyJZktdEZu7o7hM1vI8v_JJmqhX74LNGNFM/edit

We should adapt it for Giveth

**Comment by danelsuga** [comment]
Here's the doc!

https://docs.google.com/document/d/1ZL_RO846O8AnatUDMdqk4Khbv8gPWiPEeQpu2LeZrjA/edit?usp=sharing

@laurenluz let me know what you think.

**Comment by laurenluz** [comment]
Thanks @danelsuga ! seems like it was duplicated? I deleted half of it, make some small changes as suggestions through. Please review for your reference and we can call this done.

**Comment by divine-comedian** [comment]
this is ready to go up? I can see you changed the pipeline @laurenluz

**Comment by laurenluz** [comment]
ahh, wait, we gotta wait for Suga to accept changes... sorry, I'll move it back.

**Comment by danelsuga** [comment]
Sorry about the sloppy mistakes. All changes accepted. @laurenluz

**Comment by jahanzaib-jay** [comment]
Please confirm if this is good to go and I will add it to the docs.

**Comment by danelsuga** [comment]
Thanks @jahanzaib-jay ! Good for me but maybe let @laurenluz double check.

**Comment by laurenluz** [comment]
yeah! it's great! Thanks @danelsuga !

**Comment by laurenluz** [comment]
@divine-comedian @jahanzaib-jay this is ready to go up... @divine-comedian if you can decide where is good, that would be good.

**Comment by divine-comedian** [comment]
@jahanzaib-jay  let me know when you've uploaded the doc and made the PR - I will find a clever place for it in the docs

**Comment by jahanzaib-jay** [comment]
PR Submitted.

**Comment by divine-comedian** [comment]
LIVE 
https://docs.giveth.io/termsForProposals

**Comment by divine-comedian** [comment]
LIVE! 
https://docs.giveth.io/giveconomy/termsForProposals
