### ISSUE TITLE
Update "Your project is live!" email link

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#576]
View Projects is going to: https://giveth.io/account?data=all&view=projects
which actually just shows the overview....

perhaps this is not very important, but it would be nice if it showed the "my projects" tab... put the URL is not unique.

![image](https://user-images.githubusercontent.com/75490971/158852235-2d70ae18-ae70-426b-be81-699fcda6dc4a.png)

**Comment by laurenluz** [comment]
Maybe this should be going to https://giveth.io/account?tab=projects ?

I think that would work. @Cotabe can you look into it and adjust in autopilot?

**Comment by Cotabe** [comment]
Should be working now. 

I think someone else should test it with:

a) project that gets created at once
b) project that becomes a draft and then gets created

For some reason I can't tag

**Comment by laurenluz** [comment]
Can you not test it @Cotabe ?

**Comment by laurenluz** [comment]
create a project on staging.giveth.io
recieve the email
click the link and see if it goes to "my projects"

**Comment by laurenluz** [comment]
@Cotabe were you able to test this?

**Comment by c0ric0ri** [comment]
I definitely created the project but couldn't find an email. @Cotabe do you need more input from me here?

**Comment by Cotabe** [comment]
Tested!

**Comment by Cotabe** [comment]
And working
