### ISSUE TITLE
Regen Farms Documentation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#577]
We need documentation explaining:
- criteria for DAOs to get involved: https://github.com/Giveth/liquidity-mining-dapp/issues/180
- what they need to provide: https://github.com/Giveth/GIVeconomy/issues/516
- what is regen farms: https://www.notion.so/giveth/Giveth-Multiverse-aka-RegenFarms-119dee420bc145edb82d413fe6c850c9

**Comment by laurenluz** [comment]
@danelsuga @divine-comedian maybe @willyogo... maybe @Cotabe ?

Can 1-2 of you plz review? This is for the docs. https://docs.google.com/document/d/1ovTipT_6I1Ovagu2cKCa4IKbQqRxFHhOOwbStma7Zpo/edit?usp=sharing

**Comment by danelsuga** [comment]
Will do!

**Comment by divine-comedian** [comment]
reviewed!

**Comment by danelsuga** [comment]
Reviewed!

**Comment by laurenluz** [comment]
@jahanzaib-jay @divine-comedian can one of you put this up? I think it should go under GIVeconomy, after GIVstream.

**Comment by laurenluz** [comment]
we want to launch the FOX farm tomorrow FYI... so hopefully will be announcing
