### ISSUE TITLE
Design for GIVstream Blog Medium Post

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#578]
@rodricastillo9013 me puede ayudar a hacer un banner por ese blog post 

"Your GIVstream: Flow Into the Future of Giving"

Puede ser algo asi:
<img width="1024" alt="GIVstream" src="https://user-images.githubusercontent.com/75490971/159057127-38f2a91a-f556-4c16-abf9-c45c03e53a4f.png">

**Comment by rodricastillo9013** [comment]
<img width="1400" alt="Medium Post - Full width" src="https://user-images.githubusercontent.com/61791380/159072748-3f76bd27-9e10-4cdf-af86-441795f61486.png">
que piensas lauren?

**Comment by laurenluz** [comment]
It's awesome!!! Perfecto - gracias Rodri! <3

**Comment by rodricastillo9013** [comment]
genial!
