### ISSUE TITLE
Create a spreadsheet that has all direct donations to all DACs, Campaigns, Milestones on Giveth that has Amount donated, Address, Name, Campaign, DAC, (and if a milestone, the campaign that it was in) 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#58]

**Comment by Danibelle** [comment]
the USD Value at the time of the Donation would be epicly helpful!

**Comment by willyogo** [comment]
Hey @aminlatifi! Can we get a status update on this?

**Comment by aminlatifi** [comment]
@WhyldWanderer  It's the same requirement of #55?
I sent you a report I had prepared on discord DM

**Comment by aminlatifi** [comment]
@mohammadranjbarz Please create a simple script in https://github.com/giveth/feathers-giveth to generate this report every time we want. I generate one manually by exporting DB, but it doesn't have Project name and link to them.

**Comment by willyogo** [comment]
beautiful! thank you @aminlatifi. the csv looks perfect.

According to this export, total donations to campaigns and milestones on Giveth is $1,151,381. nice!
