### ISSUE TITLE
POAP design for people who help us get stables for ICHI vault raise

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#581]
waiting for forum post:
- people will put in stables, and get GIV at a discount
- 1% goes to giveth matching pool

**Comment by laurenluz** [comment]
Forum post is LIVE! https://forum.giveth.io/t/raising-1-000-000-for-the-angel-vault/467

Perhaps we want to make 3 POAPs for this? One for each raise tier? @markoprljic do you think this a good one for the new design recruits? We'd need them by March 29, so it would be great if we had some drafts later this week.

**Comment by markoprljic** [comment]
@rodricastillo9013 can you coordinate with Jes?

**Comment by laurenluz** [comment]
We discussed this further in the GIVeconomy & comms calls, and we think that we should have one generic POAP for EVERYONE who puts money into the fundraiser.

I also created a separate issue for NFTs that will go to donors who put in stables at certain amounts.

So this issue is just for *one* POAP design that will go to investors as per [this forum post](https://forum.giveth.io/t/raising-1-000-000-for-the-angel-vault/467)

We want to launch the raise on Tuesday, so we could really use a design asap!

**Comment by laurenluz** [comment]
para el POAP:
- tiene que decir "Giveth Angel Vault Investor"
- puede usar Giveth branding
- tambien puede usar el branding de Ichi & FEI:

ICHI: https://www.ichi.org/
FEI: https://fei.money/

Pero puede ser creativo... no tiene que usar ICHI, FEI o GIveth branding... pero puede usarlo para inspiration

lo mas important es que se ve muy cool!

**Comment by rodricastillo9013** [comment]
Ok! perfect! work on it now! :)

**Comment by laurenluz** [comment]
@rodricastillo9013 this one is done, right? :) can you post the image in here?

**Comment by rodricastillo9013** [comment]
![POAPS Hero Vault-36](https://user-images.githubusercontent.com/61791380/161299625-f2d91ee2-2843-4337-ba9b-4c6286bd5cf3.png)
Yes! Done

**Comment by laurenluz** [comment]
Thanks Rodri! Reopening. Will close once we setup the claim for it.
