### ISSUE TITLE
Tweet thread to explain how we donated ETH from rainbow rolls

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#582]
https://forum.giveth.io/t/what-to-do-with-the-eth-from-rainbow-rolls/173/23

**Comment by laurenluz** [comment]
Amazing @Elizardwizzard ! Thanks for taking this on! The story is basically:
- Rainbow rolls made an NFT project where people could mint rolls and the funds would get donated to public goods
- They donated a big chunk to us
- We decided as a community how to allocate it (refer to the forum post)
- We distributed 6+ ETH to for-good projects on Giveth by way of donations

In the thread it would be good to:
- explain rainbow rolls (find a good tweet by them or by us to link to)
- explain what they did with the funds: link to their tweet announcing the funds raised
- perhaps link to our forum post
- explain the process by which our community decided to send funds to different projects (maybe)
- highlight the projects we donated to on Giveth

Some hot takes that might be fun:
- the funds donated the RIP medical debt helped them HUGE but people were mad about it... there was an article on vice explaining it... you can find it in the Giveth twitter as well
- They donated a huge chunk to gitcoin grants matching pool
- NFT projects can be used *for good* to raise loads of capital
- we can use web3 to make the donation space better: GIVbacks, NFT raises... there can be an upside to "donating" where you help projects & get somethign in return for it

And a last piece:
- we are working on a partnership with some of the RainbowRolls people on a new project called PoignART to support Ukraine
- we hope to in the future integrate NFTs in to Giveth for more of this "upside" stuff

**Comment by laurenluz** [comment]
https://forum.giveth.io/t/what-to-do-with-the-eth-from-rainbow-rolls/173

**Comment by Elizardwizzard** [comment]
Also, I think it would be cool to make another thread about how crypto donation is faster than conventional donation, when urgency state is critical time saving is a key factor.

**Comment by laurenluz** [comment]
Great first draft!! So much character! I love your style

I made a google doc & added in suggestions and comments here. add yourself as an editor and then change the sharing to "anyone can comment".

Next time it helps to make these threads in google docs with "anyone can comment" access and then post the link so me or whoever can review more easily.

https://docs.google.com/document/d/1WklgHsxOgUqmPADKKz4gfSk4N6yg8uqPewHChfFcD4Y/edit?usp=sharing

**Comment by Elizardwizzard** [comment]
https://docs.google.com/document/d/1WklgHsxOgUqmPADKKz4gfSk4N6yg8uqPewHChfFcD4Y/edit

**Comment by laurenluz** [comment]
Love it! Will blast this off this week <3 Thanks @Elizardwizzard

**Comment by laurenluz** [comment]
Posted https://twitter.com/Givethio/status/1521534811466354688
