### ISSUE TITLE
Create Typeform for Contributor Feedback

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#583]
## Contributor Feedback
To be filled out by contributors who want to give feedback (positive/negative) to a fellow contributor. This is open for all. This form pertains to the ordinary and escalated critical feedback as mentioned above.

as per 
https://forum.giveth.io/t/upgrading-giveth-hr-work-agreements-termination-and-intra-wg-governance/431/9?u=mitch

**Comment by freshelle** [comment]
Draft typeform: https://giveth.typeform.com/to/OS7vBx5w

Set of questions is found here - https://docs.google.com/document/d/16_wPhtYZ7rWm8r2lNUp7mIM6x1oZ1pn1ZH2iUVVyRBY/edit?usp=sharing

**Comment by divine-comedian** [comment]
@freshelle 

Left some comments! nice work!

**Comment by freshelle** [comment]
Thanks @divine-comedian 
I've made the changes and added the links to the typeform

**Comment by laurenluz** [comment]
this is done? @freshelle ?

**Comment by freshelle** [comment]
If no one else leaves review, then I guess it's done. We'll start using this for Q1 buddy reviews

**Comment by freshelle** [comment]
Based on @laurenluz feedback on improving the contributor feedback form, I've made some edits to the form - https://giveth.typeform.com/to/OS7vBx5w
Also incorporating @divine-comedian's follow up comments.

Please review and see what other changes are needed

**Comment by laurenluz** [comment]
I think it's good!

**Comment by laurenluz** [comment]
Are we calling this good now? or updating with advice from gravity pros?

**Comment by divine-comedian** [comment]
have not heard back from gravity, will ping

**Comment by ahmadabugosh** [comment]
hey @freshelle one piece of feedback I have on this is when you choose to not be anonymous by mentioning your name, it's not clear if you're not anonymous to the buddy or just the contributor. 

I would suggest we add an option that lets people choose to let themselves be known to the buddy but not the contributor (since sometimes I might want the buddy to know the feedback is coming from me for them to know the context, but I might not want the contributor to specially know I gave the feedback). 
Wdyt?

**Comment by freshelle** [comment]
Thanks for this great feedback @ahmadabugosh! I reflected these suggestions to the form.

**Comment by divine-comedian** [comment]
@freshelle  what else can we add from the feedback we received from Juan from Gravity?

**Comment by divine-comedian** [comment]
I just tested it out, this looks great! nice work fresehelle, calling this DONE

**Comment by WhyldWanderer** [comment]
Weve been using these for a while now... seems to be working great.. closing this issue
