### ISSUE TITLE
Create Typeform for Contributor Self-Review and Giveth Feedback

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#585]
## Contributor Self-Review and Giveth Feedback

To be filled out by each contributor and will be shared to their buddy (reviewer) for further discussion during their quarterly buddy review.

as per - 
https://forum.giveth.io/t/upgrading-giveth-hr-work-agreements-termination-and-intra-wg-governance/431/9?u=mitch

**Comment by freshelle** [comment]
Draft typeform: https://giveth.typeform.com/to/bjUF2RyI

Set of questions is found here - https://docs.google.com/document/d/16_wPhtYZ7rWm8r2lNUp7mIM6x1oZ1pn1ZH2iUVVyRBY/edit?usp=sharing

**Comment by laurenluz** [comment]
is this done? or needs review? @freshelle

**Comment by freshelle** [comment]
If no one else leaves review, then I guess it's done. We'll start using this for Q1 buddy reviews

**Comment by divine-comedian** [comment]
@freshelle  sorry! just jumped in and left some comments - otherwise this looks great

**Comment by freshelle** [comment]
@divine-comedian  I just checked it out, and accepted your edit suggestions. Thanks Mitch!
