### ISSUE TITLE
Invitation for verification - maybe this email shouldn't go to projects that are decidedly "unlisted"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#588]
@WhyldWanderer I got this email for "This project is a test" after it was reviewed in adminbro and decidedly "unlisted"... wdyt?

**Comment by laurenluz** [comment]
@Cotabe @ahmadabugosh - keep an eye on this one!

**Comment by laurenluz** [comment]
@Cotabe can you check the autopilot journey to make sure the  invitation to get verified only goes out when projects become "listed"

lmk if you have any questions :)

**Comment by Cotabe** [comment]
Can I unlist my own project. Or do I need admid powers to test this ? :)

**Comment by laurenluz** [comment]
wait they should get the journey if they are *listed* not *verified*. that's a typo, right?

**Comment by Cotabe** [comment]
Yes, sorry... Listed
