### ISSUE TITLE
Add to Torus wallet docs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#589]
https://docs.giveth.io/dapps/importTorusMM

We explained that users can import their keys, but we should also explain that... well... facebook could theoretically steal their money.

The user in the best case scenario would create a new metamask account, then send the funds from torus to their new metamask.

**Comment by scottbenjd** [comment]
Since this requires them to set up a MM wallet anyway but still leaves them with the vulnerabilities of Torus, should we go ahead and change this article to "Transfer funds to New MM" rather than importing the key?

**Comment by laurenluz** [comment]
Yeah, or you could even go more general like "Protect your Funds Long-term"

**Comment by scottbenjd** [comment]
Short and sweet. Title is flexible. 

https://docs.google.com/document/d/1HPU3Otl1-aav63WEZO6gv7U05UNSSYHLQ2fZb2Ejtrk/edit?usp=sharing

**Comment by laurenluz** [comment]
it's great. maybe the title needs to be improved. can you work out a logical way to append this to the other torus wallet parts? makes sense I think to add after the "import your seed into metamask" thing 🤔

**Comment by scottbenjd** [comment]
Hey Lauren! I need a better way to track github notifications. Sorry it took me so long to get to this. I appended the import private key content after the transfer, so that the preferred transfer is the first option. Think that works?

[Move Funds from Torus to MetaMask](https://docs.google.com/document/d/1HPU3Otl1-aav63WEZO6gv7U05UNSSYHLQ2fZb2Ejtrk/edit?usp=sharing)

**Comment by laurenluz** [comment]
I think that's good! does it need anymore QA? I didn't fully read it just now.

**Comment by laurenluz** [comment]
btw @scottbenjd it would be really helpful if you changed the pipeline to "review QA" when things are ready for review.

you can also add the "ready for review label"

**Comment by scottbenjd** [comment]
Gotcha. Yeah, I haven't been utilizing the workflow at all. 
I could use eyes on the second paragraph. Other than that, I only added the content from the "Import Private Key into MetaMask" doc.  Whenever this goes up, we can take that doc down.

**Comment by laurenluz** [comment]
@danelsuga to review

**Comment by danelsuga** [comment]
@scottbenjd nice work! I made some minor comments.

**Comment by scottbenjd** [comment]
Thanks @danelsuga!
Started a pull request for this update. The image that needs to be added is attached here.  

@divine-comedian, let me know if the image is something I can add directly. May make things easier for you when do make updates. 

![transferTorusMM.png](https://images.zenhubusercontent.com/607be33bfedfab4064941d70/bf816734-cc8d-478b-af45-4c2510367119)

**Comment by divine-comedian** [comment]
> Thanks @danelsuga! Started a pull request for this update. The image that needs to be added is attached here.
> 
> @divine-comedian, let me know if the image is something I can add directly. May make things easier for you when do make updates.
> 
> ![transferTorusMM.png](https://camo.githubusercontent.com/c4421d35fb0821f164ae392ddf2bf99783371861003882a3e4a5adc15e25ea8b/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630376265333362666564666162343036343934316437302f62663831363733342d636338642d343738622d616634352d346332353130333637313139)

you'll have to add the saved image file directly into the appropriate folder in the repo - should be somewhere in here 
https://github.com/Giveth/giveth-docs/tree/master/static/img/content

copy this string right below the article data 

`import useBaseUrl from '@docusaurus/useBaseUrl'`

and then you'll need to inser the HTML tag of where you want the image to appear it should looks something like this

<img alt="photo description here" src={useBaseUrl('img/content/yourImageName.png')} />

**Comment by scottbenjd** [comment]
added the img, updated doc, and made pr 
https://github.com/Giveth/giveth-docs/pull/120

**Comment by scottbenjd** [comment]
@divine-comedian let me know if something doesn't look right.
Thanks!

**Comment by divine-comedian** [comment]
changes are meged! sorry for the delay
