### ISSUE TITLE
Send user monthly email reminder to donate again to project they donated before

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-planning#590]
Feature suggestion:
- Send user monthly email reminder to donate again to project they donated before
- include link to turn off those notifications
- include Notifications settings in My Account
- on Donations table in My Account page include link to "Donate again" next to each donation in History table

**Comment by MoeNick** [comment]
> Feature suggestion:
> 
> * Send user monthly email reminder to donate again to project they donated before
> * include link to turn off those notifications
> * include Notifications settings in My Account
> * on Donations table in My Account page include link to "Donate again" next to each donation in History table

**Comment by laurenluz** [comment]
This needs to be written up actually. @danelsuga do you want to draft en email?

**Comment by danelsuga** [comment]
I can do it, but I'm really swamped by other issues at the moment if that's ok!

**Comment by danelsuga** [comment]
@markoprljic could I get some more guidance on this please? 

Are all of the items in the issue description to be included in the email? Or it looks like those are various items to include in their Giveth account? (Apart from the second point, which I think means the email includes a link to "unsubscribe"?)

At the present, donors do not receive any follow-up to support again?

I imagine this would be a very short email. Would it be formatted to include a link to the project previously supported? Or would it just be a general format for everyone? 

Thanks!

**Comment by markoprljic** [comment]
@danelsuga Yes!

So, the idea is to send follow up email to donors on a regular intervals (to be defined) and nudge them to donate again, not to forgetting about the projects and Giveth itself.

Email could be formatted as following:
```
Subject: Consider donating again (or something catchy)
Body: Hi! You donated to several projects on Giveth and we thank you for that. Please consider to continue to support these projects by donating again. 
<if possible insert recent projects user donated to>
CTA: View your recent donations
Thanks. You'd contribution goes a long way!

Smallprint: If you do not wish to receive emails like this you can Unsubscribe.
```

We could probably include Notifications settings in users My Account but that's more dev effort. For now we can leave it out and use only Unsubscribe link. 

In the History table of My Donations on hover we could include a button "Donate again".
<img width="1359" alt="Screenshot 2022-05-05 at 12 04 02" src="https://user-images.githubusercontent.com/5704285/166902315-b489635d-c9ac-47c3-afe2-4ecc5fa4aa4f.png">

Hope this helps.

**Comment by danelsuga** [comment]
Thanks!!

**Comment by oyealmond** [comment]
hey @danelsuga ! Are we still working on this? @ahmadabugosh do you think this will be good to implement?
