### ISSUE TITLE
Giveth General Survey collating Feedbacks from Giveth Donors and Project Owners

### ISSUE THREAD

**Issue by Tosinolawale** [Giveth/giveth-planning#592]
For Subsequent Giveth Projects, either improving new features or creating a new one (Like GIVpower),  we will need to collate feedbacks from Users of the Platform, which falls broadly into Project owners and Donors.

The Goal of this task is to create an adaptable survey form which will be tailored towards getting users thoughts and insights needed for Usability studies for improving the platform overall.

**Comment by laurenluz** [comment]
@Tosinolawale is an awesome designer who is leading this effort... looking to get feedback on the new giveth design, UI. sync with him if you have any context-related questions.

I'm going to share this on twitter this week & ask for user feedback. The purpose (from Tossain) is "to help improve the overall user experience and your interaction with project verification on the platform."

**Comment by danelsuga** [comment]
I am making some changes (but not publishing obvs). 

For Q 3, I don't know how to modify the answers. I think they should be more specific (because what is average anyway?), like:

0-> 1-2 hours
5-> 3-5 hours
10-> +5 hours

Or maybe:

0-> once a week
5-> once a day 
10-> at least twice a day

**Comment by Tosinolawale** [comment]
Thanks @danelsuga. The survey form looks really good. I made the Q3 a multiple choice format and included
- Once a day
- More than once a day
- Once or twice a week
- once a twice a month
I published it and @laurenluz can take a look and see if we are good to go.

**Comment by laurenluz** [comment]
went live today

https://twitter.com/Givethio/status/1509190180867125256
