### ISSUE TITLE
Create NFTs for investors in angel vault treasury

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#594]
@markoprljic

**Comment by markoprljic** [comment]
Not me, please forward all graphic design requests to Rodri for now.

**Comment by laurenluz** [comment]
@rodricastillo9013 we want to create designs for NFTs... and give them to investors in out [Angel Vault fundraiser](https://forum.giveth.io/t/raising-1-000-000-for-the-angel-vault/467)

I'm thinking we do different tiers:

- Cherub: 5k or more
- Angel: 25k or more
- Archangel: 50k or more
- GIVangel: 100k or more

There is also [some discussion](https://forum.giveth.io/t/raising-1-000-000-for-the-angel-vault/467/5) about making a unique NFT for each of the top 3 donors... cool idea as well.

So we need at least 4 and up to 7 unique NFT designs.

@rodricastillo9013 can you help us with this? we can ask some others too for support.

@paxthemax tagging you because I think we'll need your help to actually make these into NFTs... and maybe Rodri has questions.

**Comment by rodricastillo9013** [comment]
Hi @laurenluz ! if it would be great to help! I think I understand perfectly for now. just some questions that maybe you can help me

1- In what format will we make the NFTs? It can be a Square format, for example 1000px x 1000px.
2-The aesthetic should be from giveth? Or something just with Giveth colors and some different artwork just for these kind of NFTs.
3-When should this project be finished?

**Comment by laurenluz** [comment]
Yay! You're the best @rodricastillo9013 

1 - not sure! @jfbtheii do you know the best size/format for NFTs? 
2 - feel free to explore! Giveth colours would be good, but we want these to be really attractive, fun. Feel free to play around and get outside of the Giveth aesthetic
3 - well, we want to start the fundraise Tuesday of next week. I know that doesn't give you much time to do it, but the sooner the better. I would say latest, end of next week to have finalized designs?

**Comment by jfbtheii** [comment]
From what I understand, 512px x 384px is average size for NFT’s @rodricastillo9013

**Comment by rodricastillo9013** [comment]
ok thanks! @jfbtheii

**Comment by laurenluz** [comment]
Para los NFTs... seria 6 en total:

- Cherub (5k +)
- Angel (20k +)
- Archangel (50k +)

+ 3 otros unicos que seria para los personas que dan lo maximo

No lo pongas los numbers (5k, 20k, etc.) el el deseno pero puede usar las palabra.. o no... usa imagines de angeles
no debe que ser en Giveth branding 
queremos algo muy cool 🙂

**Comment by markoprljic** [comment]
I'd love to see early sketches.

**Comment by jfbtheii** [comment]
I found a good illustrator that has done well with other NFT projects @laurenluz @rodricastillo9013
Waiting on a response now to see if they could have illustrations done in the next 7 days

**Comment by markoprljic** [comment]
> I found a good illustrator that has done well with other NFT projects @laurenluz @rodricastillo9013 Waiting on a response now to see if they could have illustrations done in the next 7 days

Can you share their profile?

**Comment by rodricastillo9013** [comment]
From what Lauren had told me and she had shown me some first sketches, we had already found an illustrator, are we talking about the same one? @laurenluz @jfbtheii

**Comment by jfbtheii** [comment]
![image](https://user-images.githubusercontent.com/101155830/161274322-4427ca05-0104-476d-a8cc-beaa154741d0.png)

**Comment by jfbtheii** [comment]
Different artist. Last two illustrators I sent you didn't have any nft experience

**Comment by rodricastillo9013** [comment]
great! i like the style! Well, if you share the progress with us, it would be great! Thank you
