### ISSUE TITLE
Willy's talk at ETHdenver soundbite

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#598]
Current at: https://drive.google.com/drive/u/0/folders/1m4HJ-wLf1tc9OoYSbiUJMzUlhxEmkkgn

**Comment by laurenluz** [comment]
@ahmadabugosh I think you missed my back and forth w @p-i-e-r-c-e in the other issue (because there was so much there!). The suggested soundbites were in his commnet:

> @ahmadabugosh For the video with [Willy](https://www.youtube.com/watch?v=y-TOlyguMjQ&t=50s) - I think these sound bites may be more relevant. I tried getting access to the spreadsheet to add them as well but will post here in the mean time.
> 
> 1:50-2:17 - Willy talks about how there are better ways for Dapps to monetize than extraction and also speaks on benefits for users
> 
> 0:50-1:04 Asks listeners to imagine a future where other than fees, people don't pay to use Dapps

The original one he suggested really wasn't the central theme of the talk.

from https://github.com/Giveth/giveth-planning/issues/552#issuecomment-1071993750

Can you fix it?

**Comment by ahmadabugosh** [comment]
Thanks @p-i-e-r-c-e & @laurenluz , apologies for missing this. 

I created these 2 here: 

1. [](https://share.descript.com/view/YrrdOAaCmAv)
2. [](https://share.descript.com/view/5UJ4iNh6eGG)

Also the files are in the folder: https://drive.google.com/drive/u/0/folders/1m4HJ-wLf1tc9OoYSbiUJMzUlhxEmkkgn
