### ISSUE TITLE
Autopilot trigger issue: "Your project has launched" email goes out before project is published

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#605]
I made this test project to test drafts... and it says it is inactive on the dapp, but I got this email

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e56d3e76-d3dc-4789-bb44-d25e8e58746b)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/77d54bf0-44da-4fbb-a299-d2abf424ad62)

**Comment by ahmadabugosh** [comment]
Hey @WhyldWanderer when you're back, can we check the trigger of this together? It's taking from Segment, so I want to see how to debug it, and also that would help me figure out ways we can optimize Autopilot

**Comment by WhyldWanderer** [comment]
I think this is related to the dev issue about projects that havent been reviewed showing up in the projects list. 

I dont think this email would have triggered under normal circumstances.

**Comment by WhyldWanderer** [comment]
@CarlosQ96  said he was looking in to it.. im not sure of the status

**Comment by CarlosQ96** [comment]
@laurenluz @WhyldWanderer Hello! This issue was fixed last week,  by not sending the email when it's a draft. I think it's related to this issues https://github.com/Giveth/giveth-dapps-v2/issues/360#issuecomment-1085217744.
Mitch created a new email when we publish the draft.

Does the issue still persist?

**Comment by CarlosQ96** [comment]
It's on staging.

**Comment by MoeNick** [comment]
Do we have this in production now? @CarlosQ96 @MohammadPCh

**Comment by laurenluz** [comment]
@Cotabe do you think you could test this one?

**Comment by laurenluz** [comment]
if the email is not being triggered, please go ahead and close the issue
