### ISSUE TITLE
Add link in covenant to Terms & Conditions

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#607]
Once we call it done on #575 and get it live on the docs we need to modify the covenant both in our docs & in the GIVgarden.

Covenant in docs: https://docs.giveth.io/whatisgiveth/covenant/
Link to gardens: https://gardens.1hive.org/#/xdai/garden/0xb25f0ee2d26461e2b5b3d3ddafe197a0da677b98

To change in the docs, it's straightforward, to change in the garden, we'll need to make & pass a Tao Vote.

**Comment by laurenluz** [comment]
this is live: https://docs.giveth.io/giveconomy/termsForProposals/

we need to add the covenant to the appropriate place

**Comment by laurenluz** [comment]
@divine-comedian - @scottbenjd is interested in learning how to do this. Do you want to help empower him to make a Tao Vote?

**Comment by laurenluz** [comment]
otherwise, I can, I think....

**Comment by divine-comedian** [comment]
I can show him, he'll need 5000 GIV though ;)

**Comment by scottbenjd** [comment]
Thanks @divine-comedian! When's a good time for you?

**Comment by scottbenjd** [comment]
Hey @laurenluz. Do you think we should append the terms and conditions content to the Covenant or add a link?

**Comment by laurenluz** [comment]
I think we should just add a sentence/phrase with a link :) check out the TEC's (if you can find it) to see how they did it

**Comment by scottbenjd** [comment]
Do we want terms and conditions in IPFS as well? 
TEC has the ABC terms are linked on IPFS but seeing terms and conditions linked in the TEC covenant.

**Comment by scottbenjd** [comment]
If you all are okay with the following language, I will upload to pinata and start a proposal. I tacked on the "in accordance with the GIVgarden terms and conditions" part. 

## On-chain
### Decision Making
Giveth uses the [Gardens](https://gardens.1hive.org/#/home/) governance platform to manage the GIVgarden configurations and allocate funds to projects that are aligned with its [mission, vision, and values](https://docs.giveth.io/whatisgiveth/) in accordance with the [GIVgarden terms and conditions](https://docs.giveth.io/giveconomy/termsForProposals/).

**Comment by laurenluz** [comment]
sounds good!!

**Comment by scottbenjd** [comment]
Passed and check the link. Looks like the changes went through and the link is working!
