### ISSUE TITLE
Should we take down Giveth Galaxy page?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#608]
@geleeroyale this is really out of date, but it is the top-ranked site for giveth.io in google

https://galaxy.giveth.io/

wdyt?

**Comment by geleeroyale** [comment]
I think before we finally take it offline comms should take a look at what was trued here. Think it failed ultimately, but the giveth galaxy wanted to serve as testament to explain how Giveth fits into the world. Our governance, side projects, community engagement.

I think Giveth Galaxy is a strong brand for this sort of activity.

But - I am not married to it. If it's gotta go, I will put it offline.

**Comment by geleeroyale** [comment]
To have a quick fix I just deleted the record for galaxy.giveth.io and replaced it with a forwarding link to giveth.io

but we still might to think about having such a portal that collects initiatives in a sort of link collection

**Comment by geleeroyale** [comment]
It might be the top result because I think google analytics were never added to the current main DApp!
