### ISSUE TITLE
Design for RegenFarm Banner

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#609]
For this blog post:
https://docs.google.com/document/d/1tZ_YnFBQmoF7snwDmoG2xT3a56I6uQ58XNYmwIqVmf4/edit#heading=h.81iol0ikgzgf

"RegenFarms: The Next Generation of ReFi Opportunities"

Want a banner for medium that has a tractor or some seedlings

@rodricastillo9013 can you help w this? want to publish tomorrow

**Comment by rodricastillo9013** [comment]
yes of course, i will try to send you something today, if not tomorrow morning is it ok? @laurenluz

**Comment by laurenluz** [comment]
yeah that's awesome!

**Comment by rodricastillo9013** [comment]
<img width="1400" alt="Medium Post farms 3- Full width" src="https://user-images.githubusercontent.com/61791380/161102749-b1601c54-31b2-4783-83b0-a43902164b99.png">
