### ISSUE TITLE
Confirm there are no other sources of donations in the past

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#61]

**Comment by GriffGreen** [comment]
There was an initial donation platform... from way back in the day... I think thats it tho... the rest was all going to the Multisig.

**Comment by willyogo** [comment]
Added the [CozDAO donation address](https://etherscan.io/address/0x90dfc35e747ffcf9631ce75348f99632528e1704) and the [dharma wallet](https://etherscan.io/address/0xB5410de3c8Fe15872511eC8247EFd34CB8836A29) that we used in early days of Giveth 2 to [this spreadsheet](https://docs.google.com/spreadsheets/d/1vpoKMSYVIuV2Db84TVJC1AUPj9GReWg8qTkBoMfFyXA/edit?pli=1#gid=289640702)
