### ISSUE TITLE
regenfarms tweet thread

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#610]
from #544 @jfbtheii when the thread is ready, post it here! hopefully we can send it off tomorrow.

**Comment by jfbtheii** [comment]
https://docs.google.com/document/d/138r7r3jCQCZWXri0e2y0eZwopHyiUusOrDIk73AyMHk/edit

lmk what you think!
@laurenluz

**Comment by laurenluz** [comment]
@jfbtheii Tweeted about regen farms on Friday: https://twitter.com/Givethio/status/1509920392001036296

I used some pieces from your draft but still changed it quite a lot. Have a look for future reference :)
