### ISSUE TITLE
Donor Onboarding Course - Regen Farms

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#618]

**Comment by laurenluz** [comment]
Recorded this one too! https://drive.google.com/drive/folders/1XQcnb7xWaFPp48GOc-RCwkDYb0FGRKDf?usp=sharing

**Comment by ahmadabugosh** [comment]
Thanks @laurenluz , edited and added here: https://www.youtube.com/watch?v=vIQGUoWVTVI&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=8&ab_channel=Giveth 

This one had some background bird noises but I think it's ok

**Comment by laurenluz** [comment]
haha those birds. Looks great @ahmadabugosh thanks for this!
