### ISSUE TITLE
Tweet thread on why donating in crypto is better/faster than conventional donation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#619]
Also, I think it would be cool to make another thread about how crypto donation is faster than conventional donation, when urgency state is critical time saving is a key factor.

_Originally posted by @Elizardwizzard in https://github.com/Giveth/giveth-planning/issues/582#issuecomment-1087881242_

Great idea Elizabeth! If you want to take this one it would be great!

**Comment by Elizardwizzard** [comment]
thanks again  for your patience!
https://docs.google.com/document/d/1R_1f4mW53vlFLkwOi7cQMnxIKxXq8ODEvyu1VFhn__I/edit

**Comment by SteffanThorn** [comment]
Please give me access and I can go through it.

**Comment by laurenluz** [comment]
@SteffanThorn - it's set to anyone can edit. you can use some ideas from here if you like

**Comment by SteffanThorn** [comment]
Provided edits. @laurenluz and @oyealmond I would love some feedback on this one. 

Perhaps there's a few things I'm missing. 
And I feel the Russian/Ukraine war part could be minimized to one tweet.

**Comment by oyealmond** [comment]
hey @SteffanThorn! 
How is this looking?

**Comment by SteffanThorn** [comment]
I don’t believe any feedback was given on my edits. 

I can clean it up and make a “final edit” to move this along.

**Comment by SteffanThorn** [comment]
Made a final draft. 
@laurenluz @oyealmond

**Comment by oyealmond** [comment]
I like the final thread! I would love to hear @laurenluz's thoughts. But I really like it! https://docs.google.com/document/d/1R_1f4mW53vlFLkwOi7cQMnxIKxXq8ODEvyu1VFhn__I/edit

**Comment by laurenluz** [comment]
I like the thread @SteffanThorn ! I left comments for some small changes, and then once you resolve those, this is good to go.

**Comment by oyealmond** [comment]
edited and scheduled. Thanks!
