### ISSUE TITLE
Token Swaps Tweet Thread

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#621]

**Comment by laurenluz** [comment]
Hey @jfbtheii So!

We have been doing token swaps with other DAOs to get DAO-owned liquidity. This is really good for GIV because it makes sure we have liquidity on DEXs without relying on farming... farming is a good short term solution, but incentivizing liqudity with your project's token creates sell pressure.

We did swaps successfully w/ BRIGHT, NODE, TEC

There is a pending ones with FOX... and we are also working w/ GNO

We're also making progress with WATER which includes several other DAOs.

All the details of these are in forum proposals in the giveth forum.

A tweet thread announcing the successful and pending swaps would be great. Also to give some context as to why this is important/good.

@chad-fi has been working on a lot of these so is a good person to ask quick questions to.

**Comment by laurenluz** [comment]
@jfbtheii any updates? been almost 2 weeks.

**Comment by jfbtheii** [comment]
Hi! That's my fault. I'll have a draft tomorrow

**Comment by SteffanThorn** [comment]
I'm not happy with this first draft at all, but I chucked a question into Bard and made a thread based on that. 

I'm probably need to see the actual forum to make this a lot better. 

But here we go:
https://docs.google.com/document/d/1NgaKqo1LgTxX5J7jFJjfr4YFTtFTrMiEzXBrEBCUpw0/edit?usp=sharing

**Comment by SteffanThorn** [comment]
@laurenluz could either you or someone who you think is suited review this thread? 

Need to see if my facts are correct here.

**Comment by oyealmond** [comment]
Oh, I like the content of this thread! 
But for sure we need @laurenluz input on this as this is her expertise.

**Comment by laurenluz** [comment]
commented

**Comment by SteffanThorn** [comment]
Alright fiar points on the comments. Closing .
