### ISSUE TITLE
Get great projects from gitcoin onto giveth

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#622]

**Comment by laurenluz** [comment]
Focusing primarily on meatspace for-good projects.
Compile a list, get contact info & then we can do some outreach.
Might even be nice to prep outreach material... explaining what is giveth, why you should get on it. links to GIVbacks article, docs, create a project, project verification applicate, or whatever works - at your discretion.

**Comment by danelsuga** [comment]
Chipping away! 😍🤩

**Comment by danelsuga** [comment]
Still working on this.

**Comment by danelsuga** [comment]
I would love some help on this. I've got an excel listing the projects, but it's taking me ages to get through it. If it could be divided up by sections of the alphabet, for example, it could be done in no time!

@ahmadabugosh any chance you could split a bit with me and/or have thoughts on who could? Thanks!

https://docs.google.com/spreadsheets/d/1NeH9TeBaI2XSE3U9_T_cr6DmXTqbU7sV6kZE5rsfS6o/edit#gid=0

**Comment by laurenluz** [comment]
Can you make it "anyone can comment" or edit access? Can't see it.

Also, @todd-x-y I think might be interested in helping with this at some point.

**Comment by danelsuga** [comment]
Done!

Ok, thanks!

**Comment by todd-x-y** [comment]
This is one of a few things I'm hoping to support! 

Suga, would you want to meet on Discord to sync on where you're at and what your needs are?

**Comment by ahmadabugosh** [comment]
hey @danelsuga sure would be glad to help, I just requested edit access. Once you have a chat with @todd-x-y, let me know how I can support (maybe we can split them between us three)!

**Comment by danelsuga** [comment]
Sounds good! What's your time zone?

**Comment by danelsuga** [comment]
Thanks, guys!

The doc should be accessible.

**Comment by danelsuga** [comment]
If you all want to tackle it without a sync, anyone could simply pick a letter of the alphabet or start at the end of the list of about 900 grant projects on Gitcoin, and you'll see on the doc, I'm just starting by collecting info:
Name
Website
Twitter
Gitcoin link
Brief description 

The projects being collected are meatspace, irl projects that aren't necessarily crypto savvy etc. (or their audiences/supporters/recipients aren't necessarily crypto-involved). 

Thanks!!

**Comment by todd-x-y** [comment]
> Sounds good! What's your time zone?

I'm in Mountain Time, which happens to be the same as Costa Rica.

**Comment by todd-x-y** [comment]
> If you all want to tackle it without a sync, anyone could simply pick a letter of the alphabet or start at the end of the list of about 900 grant projects on Gitcoin, and you'll see on the doc, I'm just starting by collecting info: Name Website Twitter Gitcoin link Brief description
> 
> The projects being collected are meatspace, irl projects that aren't necessarily crypto savvy etc. (or their audiences/supporters/recipients aren't necessarily crypto-involved).
> 
> Thanks!!

I'll start to put together a Google Sheet with a CMS like-structure, using the columns you outlined here.

**Comment by danelsuga** [comment]
I think we can keep it simple: the current spreadsheet is suitable just to fill in any and all projects from Gitcoin as described above. To avoid confusion, overlap, etc.

**Comment by laurenluz** [comment]
Just some notes from today's meeting:
- start with a draft outreach template & begin reaching out to projects
- can use spreadsheet for outreach tracking
- avoid shilling Giveth directly on the gitcoin side, better to contact project owners directly
- contract project owners will some supportive messages such as explaining, zero-fees, gnosis chain w/ low gas, donors getting GIVbacks etc.

**Comment by danelsuga** [comment]
Hi gang! Per comms call yesterday and Lauren's suggestion, I would LOVE if this could turn into a teamwork project and also include Connect.

Here is the doc:
https://docs.google.com/spreadsheets/d/1NeH9TeBaI2XSE3U9_T_cr6DmXTqbU7sV6kZE5rsfS6o/edit#gid=0

I'm going through all roughly 1000 Gitcoin grants (filtered by a-z) and just dropping in their name and twitter.

At first I was filling it out more but a waste of time.

Give yourself a letter or two or three or four of the alphabet, and chip away! The goal is to gather the projects that are really working in the nonprof, non-tech.

There is also a message for outreach if you want to help there too by actually doing the outreach. It's important that each message have a personal touch related to the project, so this task should probably have some good QA involved before anything goes out. 
https://docs.google.com/document/d/1OG1kyB9reY_B1A5BuKw3Gdt0Bz7z5HA0Cz_ljK6U8ZY/edit

@ahmadabugosh 
@SymSL 
@Elizardwizzard 
@Cotabe 
@melodysongq 
@WhyldWanderer 
@rainerhoell 
@clara-zi 
@laurenluz

**Comment by melodysongq** [comment]
Thanks Suga forr including the Connect WG input.  My suggestion is to qualify this lists with some more thoughts, especially around impact, sustainability and regerative nature of the project mission (some seems one off - like an event).  This is really going to the curation process that @rainerhoell is leading to put together.   The Connect WG is happy to draft the messaging for further revision.  Perhaps let's talk about it  in the connect meeting? I am away next week but @clara-zi can also facilitate and get something started?

**Comment by danelsuga** [comment]
Thanks @melodysongq !

Yes, I did have a lot more info in the doc originally as you can see, but in the interest of outreach, it seemed better to move more quickly and eventually allow the rest to follow later, as all that information can then be regarded when the outreach itself happens, since that will require more personalization anyway. 

I was just trying to get through that giant list with at least names and simple contact! 

Sounds good for Monday. Thanks.

**Comment by melodysongq** [comment]
@danelsuga  I wonder if Giveth can convince Gitcoin as an institution donor to use the platform exclusively for Gitcoin grant donations.  This is potentially good for them with Giv backs?  Then the projects will need to all sign up (the process can be explained as a simple few minute set up especially for the DAOs) to receive grant with a certain date (even the ones who are not nonprofit,  they will just not be verified).  Maybe for those you sorted out, we can provide verification badge in bulk if this arrangement can be made?

**Comment by laurenluz** [comment]
@melodysongq what do you mean "use the platform exclusively for Gitcoin grant donations"? Gitcoin has it's own processes, quadratic funding, grant rounds, sybil protection. They do funding rounds once every quarter (I think)... I don't think trying to convince them to abandon their own project & donate to the same projects on giveth makes sense.

The purpose of this outreach (if you check out the draft message) is to connect with individual grant owners and let them know about Giveth. With Giveth, they can do year-round fundraising & donors get GIVbacks... it makes sense to add their project to both because they have different advantages.

I think the projects should still have to go through the verification process... maybe we can discuss that futher because I do think gitcoin has their own processes, but our team should at least review them.

Instead of growing the scope, the purpose of this is to breakup the outreach... have more people looking a projects. We don't need to get them ALL, but if everyone in the list reached out to 10-20 projects or so, we'd get 100 more awesome projects on our platform.

**Comment by Cotabe** [comment]
I will pitch in in this issues one or two hours a week :)

But I think I want to start with the Common Prize since it's fresher

**Comment by danelsuga** [comment]
Yes @Cotabe !

**Comment by melodysongq** [comment]
> @melodysongq what do you mean "use the platform exclusively for Gitcoin grant donations"? Gitcoin has it's own processes, quadratic funding, grant rounds, sybil protection. They do funding rounds once every quarter (I think)... I don't think trying to convince them to abandon their own project & donate to the same projects on giveth makes sense.
> 
> The purpose of this outreach (if you check out the draft message) is to connect with individual grant owners and let them know about Giveth. With Giveth, they can do year-round fundraising & donors get GIVbacks... it makes sense to add their project to both because they have different advantages.
> 
> I think the projects should still have to go through the verification process... maybe we can discuss that futher because I do think gitcoin has their own processes, but our team should at least review them.
> 
> Instead of growing the scope, the purpose of this is to breakup the outreach... have more people looking a projects. We don't need to get them ALL, but if everyone in the list reached out to 10-20 projects or so, we'd get 100 more awesome projects on our platform.

@laurenluz thanks for the explaination, I have no idea of the Gitcoin process just a suggestion which can be used on other institution donors if they don't have a process and just want to give.

**Comment by clara-zi** [comment]
@danelsuga just want to double-check on what needs doing: "Give yourself a letter or two or three or four of the alphabet, and chip away! The goal is to gather the projects that are really working in the nonprof, non-tech meatspace". Do you need help to complete the list with contacts and other data or help to start firing out messages (by email or other)? (I can do either).

**Comment by laurenluz** [comment]
Yeah! 100% agree. We don't have to get ALL the projects, but getting some would be awesome so I think the sooner we start the active reaching out the better.

You wonderful people can decide the best platform for outreach... I would probably try discord or telegram if you could first, and then email if not.

**Comment by danelsuga** [comment]
#663

**Comment by danelsuga** [comment]
@ahmadabugosh is checking out if he can pull the whole list through an API all at once! Stand by!

**Comment by laurenluz** [comment]
The draft outreach email is here: https://docs.google.com/document/d/1OG1kyB9reY_B1A5BuKw3Gdt0Bz7z5HA0Cz_ljK6U8ZY/edit

We're getting all the data though an API, right? not mass emailing? or?

**Comment by ahmadabugosh** [comment]
hey @danelsuga @Cotabe I managed extracted the top 1,000 projects and their twitter handles here (in the "Extract" tab):  https://docs.google.com/spreadsheets/d/1NeH9TeBaI2XSE3U9_T_cr6DmXTqbU7sV6kZE5rsfS6o/edit#gid=1538045452

**Comment by danelsuga** [comment]
AMAZING!! I knew you would do it! No less amazing however. :) Thank you!

**Comment by ahmadabugosh** [comment]
hey @danelsuga, after around 1,000 the total amount raised was less than $300, and it was taking a while to pull the data because I kept getting blocked for doing so many requests. 

I can still pull them if you think it's useful though, let me know!

**Comment by danelsuga** [comment]
Gotcha! No, this is probably good for now! Amazing. What do you think @laurenluz?

**Comment by clara-zi** [comment]
First thing I notice is that the links break when pasted into Twitter DM.

**Comment by danelsuga** [comment]
😭but probably just needs to be put in markdown.

**Comment by danelsuga** [comment]
Try now. 

Or maybe I’m remembering you can’t do embedded links in Twitter actually…

**Comment by ahmadabugosh** [comment]
Hey @clara-zi my personal recommendation is to keep the first message short on Twitter to gauge initial interest (when you're doing cold outreach). Maybe something like this: 

Hi X, 

Hope you're well! I noticed that you started raising funds on Gitcoin, and I thought your project mission aligns with what we're building at Giveth. We're a public goods fundraising platform that allows projects to raise money with zero fees + we reward your donors through our GIVbacks program! If this sounds interesting to you, let me know and I can share more info!

**Comment by clara-zi** [comment]
Thanks @ahmadabugosh that's more in line with the kind of outreach I've done before through LinkedIn DM. Wdyt gang?

**Comment by clara-zi** [comment]
@danelsuga had you originally planned to reach out through email when message was drafted?

**Comment by NikolaCreatrix** [comment]
Hi there! Can I help with this? I know you @danelsuga were going to have sync up call with @clara-zi about this outreach...Did it happen already? Wanna help you do this! ;)

**Comment by danelsuga** [comment]
For sure @NikolaCreatrix ! Thank you!

**Comment by danelsuga** [comment]
Groovy! Thanks so much for chiming in @laurenluz ! 😍

Full speed ahead @clara-zi ! 🤩

**Comment by NikolaCreatrix** [comment]
Okay cool, since there are more of us interacting with the spreadsheet, I'm going to pick a section, use some color, and comment on each one in the section 'message sent'.

Do we want to have more tracking around which ones actually responded and what was the outcome? ;)

**Comment by NikolaCreatrix** [comment]
I can see that some of those projects will already be on the platform, just in case nobody noticed, so it might be useful to check giveth.io/projects as part of the process before reaching out.

**Comment by danelsuga** [comment]
Thanks @NikolaCreatrix ! 

I just made an “outreach” column at the beginning for indicating the particular project’s status.

**Comment by clara-zi** [comment]
I started on the wrong sheet - I'm on the 'extract' tab where there are 999 projects - is there anything wrong with doing this sheet or should I just plough on...

**Comment by danelsuga** [comment]
Ah, the trick with the extracted sheet is that it hasn’t been “vetted”. In other words, that’s ALL projects and not just public goods, meatspace projects. So just don’t do the crypto-y ones once you get to looking them up.

**Comment by Cotabe** [comment]
Also something to consider is that DMs in Twitter as closed by default. What I did for the projects on Commons Stacks was: 

1. Checking their twitter, like and retweet what I liked.
2. Find a twit that I felt like making a comment. Make the comment and slide something like "I'm a DAO member @ [@Givethio](https://twitter.com/Givethio). If you're looking into fundraising, I'd love to help 🤩"

Or send FR on Discord. I think the results were good. I got responses from about 8/32

**Comment by clara-zi** [comment]
> Also something to consider is that DMs in Twitter as closed by default. What I did for the projects on Commons Stacks was:
> 
> 1. Checking their twitter, like and retweet what I liked.
> 2. Find a twit that I felt like making a comment. Make the comment and slide something like "I'm a DAO member @ [@Givethio](https://twitter.com/Givethio). If you're looking into fundraising, I'd love to help 🤩"
> 
> Or send FR on Discord. I think the results were good. I got responses from about 8/32

Thanks @Cotabe - I like this suggestion and it's similar to strategy I've used in LinkedIn before and generally got better results than cold messaging.
@danelsuga @laurenluz @NikolaCreatrix @ahmadabugosh is it ok to go ahead with this style of outreach?

**Comment by laurenluz** [comment]
sounds great! Thanks everyone

**Comment by danelsuga** [comment]
Anybody working on this lately? Reaching out to Gitcoin grant projects? Would be awesome if we could blaze through this together and kill it.
@NikolaCreatrix @Elizardwizzard 
@clara-zi

**Comment by danelsuga** [comment]
@c0ric0ri join the Gitcoin outreach party! :smile:

**Comment by c0ric0ri** [comment]
@clara-zi @scottbenjd @c0ric0ri @danelsuga + need one more to split up the 1000 into 200 each for 5 people to tackle outreach

**Comment by danelsuga** [comment]
Suga = 400-600

**Comment by scottbenjd** [comment]
I added a project id column so we have a number that follows the row regardless of sorting. Taking ids 801-997.

**Comment by c0ric0ri** [comment]
I'll just take 1-200 then

**Comment by c0ric0ri** [comment]
@clara-zi will you take 200-399? I'll skip number 200 :)

**Comment by c0ric0ri** [comment]
@Cotabe would you have capacity to take on a group of projects for outreach?601-800 needs coverage

**Comment by clara-zi** [comment]
> @clara-zi will you take 200-399? I'll skip number 200 :) 
yeh - or swap with you? - I'd already made a little start on 1-200 back in the day..

**Comment by NikolaCreatrix** [comment]
Okay, did my part. Reviewed all 1000 items, and projects I found on Giveth are marked with purple and commented on.

**Comment by danelsuga** [comment]
🙏🏼

**Comment by danelsuga** [comment]
It looks like all sections but one (of 200 projects each) are actively being worked on.

**Comment by clara-zi** [comment]
On 'Extract' tab, I added a lookup to bring Suga's research and project detail from 'Sheet1'.

**Comment by SnakeGH** [comment]
Hey @danelsuga, @clara-zi, @c0ric0ri, @Cotabe, and anyone else working on this that I missed. Just fyi, I have reviewed all the comments plus had a quick call with @NikolaCreatrix and feel like I have a pretty good understanding of what the purpose of this outreach is and instructions for how to outreach, as well as notate in the shared Gitcoin excel.  With that said, Id love to start out by taking 50 or so of the columns and do some outreach. Anyone want to give me 50 of theirs?

**Comment by clara-zi** [comment]
@SnakeGH - you can take the next few of mine. I started at line 1. You can see which ones I've done so far. Feel free to continue down the list. It's great that you will continue this outreach work. Thank-you.

**Comment by SnakeGH** [comment]
@clara-zi Thank you, when I have some time ill make sure to jump in there and stay in the 1-200 section of the excel. 

Which reach out template have you been using, Suga's or the small note that Ahmad created?

**Comment by clara-zi** [comment]
@SnakeGH I have included each outreach message sent in Column H ('extract tab') labelled 'message sent'. Mostly long version but I think it makes sense to mix it up a bit to see which message, style of outreach is most sticky.

**Comment by danelsuga** [comment]
Please help with mine too if possible! 400-600. I haven't tackled it lately but I keep notes so it's possible to see what's already done. Thanks, @SnakeGH !

**Comment by SnakeGH** [comment]
@danelsuga what did you mean with "skip the more crypto'y" ones? I just want to make sure I am not reaching out to projects that we shouldn't, as I am about to start my outreach campaign. That is the only part of the outreach that I am a little worried about. Stepping over the project line....

**Comment by danelsuga** [comment]
You can totally reach out to all the projects! But basically the focus of this issue was to try to reach out primarily, or perhaps initially, to projects irl, e.g., projects on the ground affecting change physically, if you see what I mean: schools, gardens, clean water, medical, etc.

**Comment by SnakeGH** [comment]
Got it, thanks for the clarity Suga! :) Also, someone needs to allow me access to edit pretty please, and Ill get rocking on it ASAP

**Comment by danelsuga** [comment]
Done! Thanks!!

**Comment by SnakeGH** [comment]
@danelsuga and @clara-zi wanted to let you know that I went ahead and I reviewed, researched, commented and outreached where needed on 100 of the projects in your sections. Good luck with the others :)

**Comment by danelsuga** [comment]
Amazing @SnakeGH ! Thank you!

**Comment by SnakeGH** [comment]
@clara-zi, @danelsuga and all you other wonderful people, I had some time to jump back in here and so I finished out the rest of rows 1 through 200, as well as 400 through 600. 

If I have more time in the coming days, Ill jump back in and try to close the 200 to 400 gap some

**Comment by SnakeGH** [comment]
Hey team, just an update that I have completed columns 13 up until 600 out of the 1000. Ill keep pushing through with hopes of finishing them all up, but please do let me know if anyone would still like to take any of them on, as well : )

Additionally, please do make sure to add all orgs & contacts to the new CRM (hubspot) as I have run into two orgs that are already on our platform, which I would have known about if we had the CRM in the past, so point to the story, the CRM will work and is needed :)

**Comment by danelsuga** [comment]
This is AMAZING @SnakeGH !! Thank you so much!

**Comment by SnakeGH** [comment]
Wow @danelsuga you are fast, as I literally just finished reviewing the last of the 1000 projects about 2 minutes ago haha and I was just going to say you could close it now, as I have completed them all. 

All projects that I ended up reaching out to have been added to our CRM system Hubspot as well, but if you want to review all of them in general, here is the completed excel sheet too 

https://docs.google.com/spreadsheets/d/1NeH9TeBaI2XSE3U9_T_cr6DmXTqbU7sV6kZE5rsfS6o/edit#gid=1538045452
