### ISSUE TITLE
Research on Donor Profiles

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#623]

**Comment by laurenluz** [comment]
The intention is to get more donors using Giveth... and to tailed Giveth to donor needs. Some action items:
- determine how to target comms to crypto philanthropists
- interview donors
- create a donor profile
- check out leaderboards, ENS names - Gitcoin, Giving Block

**Comment by laurenluz** [comment]
Hey @melodysongq would you be interested in supporting this? We would love to do some research on how are these big donors?

Might be an opportunity at ETH barelona to talk to people in person.

@cotabe is interested in supporting as well.

**Comment by melodysongq** [comment]
@laurenluz definitely.  Would love to do a proper research.  @Cotabe would love to put a plan together and maybe schedule meeting already as pre Eth.

**Comment by ahmadabugosh** [comment]
hey @melodysongq, @Cotabe can you hand this off to Jake (I see you already connected over Discord)? Since his role is focused exclusively on donor activation, I think this would be a great task for him

**Comment by melodysongq** [comment]
@ahmadabugosh sure.  Happy to support if Jake needs Donor Empathy Mapping/Personas Creation as well as major donor strategy support as this is in fact my day job.

**Comment by ahmadabugosh** [comment]
@melodysongq Awesome! I see you have a call already planned, feel free to jump in and take over wherever you think makes sense.  🙌 Just know he's a resource that's here to support you

**Comment by laurenluz** [comment]
@WhyldWanderer please add Jake to the assignees :)

**Comment by SnakeGH** [comment]
@melodysongq  has shown some amazing initiative and drafted up a Giveth Donor Survey template that I will be adding thoughts to today. We would really like others input in the coming week as well. Thanks! 

Please visit the link below....https://docs.google.com/document/d/1tJeL9XTnmh11Mb4Qc-5VSB3rY8ymlgbBjZ-8Jb48mUU/edit

**Comment by SnakeGH** [comment]
Survey is up and viewable for final offerings here: https://docs.google.com/document/d/1tJeL9XTnmh11Mb4Qc-5VSB3rY8ymlgbBjZ-8Jb48mUU/edit

Also, please take the typeform and let us know if there are any issues with it here: https://giveth.typeform.com/donorsurvey?typeform-source=www.google.com

**Comment by ahmadabugosh** [comment]
Looks good @SnakeGH , thanks for all the effort on getting so many takers!

As the next step, can you look for any commanalities and recurring answers and start with a draft of what the profiles and personas would look like (maybe as an editable sheet so we can keep adding to it)? You mentioned to me before for example, you noticed a large number of them care about zero fees etc.
