### ISSUE TITLE
Add March Newsletter to docs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#625]
@ahmadabugosh can you give the copy to @divine-comedian or @jahanzaib-jay to upload to: https://docs.giveth.io/newsletter/ ?

**Comment by ahmadabugosh** [comment]
Hey @jahanzaib-jay can you upload the March Newsletter on the docs please: https://drive.google.com/drive/folders/1YJF6_1KRGVdsdP3zXszMZ4OacaPjpb7y?usp=sharing

**Comment by jahanzaib-jay** [comment]
PR submitted. 
@divine-comedian

**Comment by divine-comedian** [comment]
LIVE 
https://docs.giveth.io/newsletter/March2022
