### ISSUE TITLE
QA improvements for donor course

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#627]
First thing goes first... Big shout out to @ahmadabugosh and @laurenluz for recording and editing such cool videos that I believe anyone entering Giveth should watch.

Just a few quick comments that IMO could improve the current course, especially from the perspective of a donor, not web 3 native

- In the 4th video. (Gnosis Chain & Bridging Funds). There is a part about funding your wallet that is repeated in the third video. No big deal.

- I think it would be beneficial to see how to add the gnosis chain to the Metamask wallet. Feels a bit awkward watching a tutorial that tells you to follow the instructions of a doc.

- I feel there is not a smooth transition between the 4th and 5th video. Going from funding your wallet to the GIV stream. For example, in the 5th video it mentions that as mentioned in previous videos you can earn yield by stacking or providing liquidity, this wasn't mentioned before. And a few similar, not big issues. I consider the flow would be much smoother if  the videos were rearranged the following way:

5th video GIVbacks 
6th video GIVfarm
7th video GIVstream
8th video Claiming GIVstream rewards
9th video GIV garden

There would still be one or two comments of the GIVstream before it is explicitly explained but IMHO, for non-web 3.0 donors it would be easier to follow. The GIVacks and GIVfarm videos are more thoroughly and slowly explained easier to grab the first time you come across such topics. Whereas the last 3 videos have amazing energy, but they are more suitable after understanding the GIVbacks and GIVfarm better.

Finally, I think it would be great to have a video outside of these series that meets the audience where they are...  a video for donors that are not currently interested in Giveth and tell them in a quick video... why Giveth is revolutionizing giving. Why they should be giving through Giveth. I recommend to make a short version of these beauty https://www.youtube.com/watch?v=ADSOVkujrI4

**Comment by ahmadabugosh** [comment]
Hey @Cotabe, all great points!

I just rearranged the order, I think it flows better you're right. 

For the other comments, mainly 1) Editing the 4th video (and adding a section on adding Gnosis Chain to Metamask) 2) Adding a short video from Griff's talk, I'll start working on them!

**Comment by scottbenjd** [comment]
What do you all think about getting rid of the third video entirely? My intention was to only use the fourth with funding a wallet and bridging combined. The downside would be having a longer video.

**Comment by ahmadabugosh** [comment]
Finished most of these, just waiting on @scottbenjd for the Donate video and @jfbtheii for the video descriptions for the videos

**Comment by laurenluz** [comment]
I'm going to close this because the other two issues are as separate issues.
