### ISSUE TITLE
Email subscribes ones they subscribe to mailing list

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#632]
This could be the text for the email:

Hello!

Welcome to the Giveth community! We are excited to have you on board.

Our goal at Giveth is to use blockchain technology to build the future of giving. We believe that by creating open, transparent and free access to the revolutionary funding opportunities available within the Ethereum ecosystem, we can support and reward the funding of public goods. We would love to have you involved in our community!

If you're interested in learning more about what we're doing, please check out our docs or join our Discord channel. 

Till next time... 
Regards,

_Originally posted by @jahanzaib-jay in https://github.com/Giveth/giveth-planning/issues/568#issuecomment-1092690810_

**Comment by oyealmond** [comment]
hey @ahmadabugosh! Is this text useful for you? for complementing the Giveth newsletter journey?

**Comment by ahmadabugosh** [comment]
Yes, this is done, closing now.
