### ISSUE TITLE
POAP design for completing Donor onboarding course

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#634]
We are almost done the [Donor onboarding course](https://www.youtube.com/watch?v=qY9F5X1b1QA&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=1)

We want a nice POAP to award to participants who complete the course and take part in a quiz :)

The POAP should be:
- congratulatory / celebratory
- mention the "Giveth Donor Course"
- perhaps have some student design elements like books or checkmarks
- be in Giveth branding

@ahmadabugosh @scottbenjd do you have any other ideas/advice on what this POAP should include?

@rodricastillo9013 can you help with this? It would be nice to have it done within 2 weeks.

**Comment by ahmadabugosh** [comment]
How I imagined this POAP is something related to a person or hand planting a flower or tree with a certificate or badge on top

**Comment by rodricastillo9013** [comment]
![option-35](https://user-images.githubusercontent.com/61791380/164314172-ab620dfe-6860-4d5b-926e-0a3041d79af7.png)
![option-36](https://user-images.githubusercontent.com/61791380/164314184-13462962-0cc7-41d1-8019-8b6eacb221a0.png)
![options-37](https://user-images.githubusercontent.com/61791380/164314186-22c375cb-314b-43c6-8f76-ddbe3e55d0ef.png)
![options-38](https://user-images.githubusercontent.com/61791380/164314189-6a8c68b8-6c19-4eb7-979c-a351e4eec7b4.png)
Hello how are you! I have worked on some options, I await your feedback!
I've changed the sentence to be a bit shorter :)

**Comment by rodricastillo9013** [comment]
brilliant! When they define the name, let me know and I'll update the design.:) @ahmadabugosh

**Comment by laurenluz** [comment]
My favourite is the last one too, shall we just go with "Giveth Donor 101" @ahmadabugosh ? I think that is the best option.

**Comment by rodricastillo9013** [comment]
ok perfecto, realizo los cambios, y vuelvo a enviar :)

**Comment by rodricastillo9013** [comment]
![image](https://user-images.githubusercontent.com/61791380/165777667-ef4e12e0-32e4-4ed2-9e28-5994d9975c02.png)

**Comment by laurenluz** [comment]
Perfecto @rodricastillo9013! muchisimas gracias.

@ahmadabugosh @scottbenjd next steps, we need to set this up so that anyone with the link can claim, and then add that link at the end of the typeform quiz :)

**Comment by rodricastillo9013** [comment]
De nada! @laurenluz :)
