### ISSUE TITLE
Donor Onboarding Course: Create a Quiz

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#635]
Want to reward donors who complete the youtube series & answer a quiz correctly with a POAP!

We need to make that quiz.
Thinking about creating via typeform & using logic jumps.

**Comment by ahmadabugosh** [comment]
I'll take this on! @laurenluz, Can I have access to our Giveth Typeform please?

**Comment by laurenluz** [comment]
sent you access @ahmadabugosh :) you know

**Comment by ahmadabugosh** [comment]
I made a draft of it here @laurenluz let me know what you think: https://giveth.typeform.com/to/IZndeKbH

**Comment by danelsuga** [comment]
I did the edits asap in case you want to integrate them yourself @ahmadabugosh while the Typeform account gets upgraded.

**Comment by laurenluz** [comment]
I just upgraded out typeform to premium so I could share access now with whoever needs it.

Also, I just added a couple of small extra edits to Suga's editing doc 😅  I hope that's not confusing.

**Comment by laurenluz** [comment]
Oh yeah! and let's remove the POAP from the front page.. it should be at the end, I think

**Comment by danelsuga** [comment]
Great! That was fast. Ha ha.

**Comment by danelsuga** [comment]
I can make those edits @laurenluz @ahmadabugosh if I can get in the Typeform account please?

**Comment by ahmadabugosh** [comment]
Thanks @danelsuga ! I made all the edits you listed and changed question 4 to "What tokens can you donate to a project to qualify for GIVbacks?"  Let me know if I missed any! 

I can't share the password, since @laurenluz has to do it through Lastpass. To get ready for it, I recommend you signup for Lastpass (with your personal email), and install the Browser extension

**Comment by danelsuga** [comment]
Aw yeah! Great! I’ve got Last Pass, but sounds like you’re on top of this!!

**Comment by laurenluz** [comment]
maybe will help: https://docs.google.com/document/d/1YJGfb-CuEIGSD41A02YlByKZ1fksL0Vf_hV82UHbqwU/edit?usp=sharing

**Comment by laurenluz** [comment]
we should figure out a better way to explain the 75% thing.........

**Comment by danelsuga** [comment]
Looking great! I actually really like and appreciate the detailed response for the GIVbacks Q. 

Great job @ahmadabugosh !

**Comment by laurenluz** [comment]
For this answer, should we mention like... that really anyone can raise funds for anything (if it doesn't violate our terms)? doesn't have to be a charity or even a public goods project... Maybe it doesn't matter

![image](https://user-images.githubusercontent.com/75490971/168940645-337b3701-d716-41bf-b217-26eaec966186.png)

**Comment by laurenluz** [comment]
This is waaay too much:

![image](https://user-images.githubusercontent.com/75490971/168940923-3958a42f-7dc5-48b1-ab8e-57ed40e9d69e.png)

I suggest:
Yes, indeed. You can get up to 75% of the value of your donation "back" in GIV, streamed over 5 years.

**Comment by laurenluz** [comment]
I think we can take out "formerly xDAI"

![image](https://user-images.githubusercontent.com/75490971/168941706-46fb2d32-1992-4f29-a3dd-dda791e84fac.png)

**Comment by ahmadabugosh** [comment]
Great! I added your comments, now closing this issue. Last thing is to integrate the POAP from [issue 658](https://github.com/Giveth/giveth-planning/issues/658)
