### ISSUE TITLE
Coordinate with Stonky of translations team.

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#636]
They recieved generous funding.. but I don't see anything getting done.

https://forum.giveth.io/t/giveth-gitbook-translations/311

**Comment by danelsuga** [comment]
👍🏼

**Comment by laurenluz** [comment]
Ok this is active in the forum. @danelsuga if you can just keep an eye on it and relay any question in the communications channel on discord, would be great. closing this issue.

**Comment by danelsuga** [comment]
Sent out a request for updates on the forum.

https://forum.giveth.io/t/giveth-gitbook-translations/311/35

**Comment by danelsuga** [comment]
Mitch clarified on the forum. 

Oops. This issue is closed by I keep adding to it. 🤣
