### ISSUE TITLE
Newsletter April 2022

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#637]

**Comment by ahmadabugosh** [comment]
We need:

1. Top stories
2. Featured Project
3. Tweet of the Month
4. Meme of the month

**Comment by laurenluz** [comment]
https://giveth.io/project/grassroots-economics-community-currency-0

**Comment by laurenluz** [comment]
https://medium.com/giveth/regenfarms-the-next-generation-of-refi-opportunities-7a46f3cf1e09

**Comment by laurenluz** [comment]
https://medium.com/giveth/meet-the-makers-spotlight-on-environmental-projects-14ed38780b26?source=collection_home---4------0-----------------------

**Comment by laurenluz** [comment]
GIV/DAI Univ2 pool launching April 30
Token Swaps

**Comment by ahmadabugosh** [comment]
@laurenluz Added a draft here for review here: https://docs.google.com/document/d/1plTTyDIyaWAhkczDmWSE5ADOCtUTVzYnDNcv-nQdtio/edit?usp=sharing

I couldn't find info on the GIV/DAI Univ2 pool launch on the forum, is that still happening this month?

**Comment by laurenluz** [comment]
Pushing it now, I hope it goes live today, to announce tomorrow. rewards will start Friday or Saturday - working out details right now.

**Comment by laurenluz** [comment]
this could be meme of the month: https://imgflip.com/i/6awavn

**Comment by laurenluz** [comment]
Maybe worth mentioning FRO 2022 - the fundraising conference that melody & I spoke at last week? https://twitter.com/TheResAlliance/status/1517145518454935556

**Comment by laurenluz** [comment]
left suggestions in there - this is great @ahmadabugosh. when should it go out? if we wait a few more days we can make sure univ2 is all good and get it in there too.

**Comment by ahmadabugosh** [comment]
Sent (also made an issue to add it to the docs)
