### ISSUE TITLE
Hire a Project Manager 

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-planning#64]
I'd like to invite others to interview Forest to take on our project management role and responsibilities; Willy and I have already done so and she won our confidence.

Forest has taken notes on her questions to clarify the role and our answers, you can see her work as documented in the job description:  https://docs.google.com/document/d/19XmJVGMBqQBJjJHakmZ5TCwrF6vIMF6J0_EdPrpjYe0/edit?usp=sharing

@aminlatifi and @mateodaza please feel free to message her directly on Discord: @Reforest#1211

@GriffGreen you mentioned having Tam interview her?

**Comment by aminlatifi** [comment]
Thanks @Danibelle 
Any cv?

**Comment by Danibelle** [comment]
Oh yes, she was in our original applicant pool, resume and letter of introduction here:  https://docs.google.com/spreadsheets/d/1vgO3eqNzo0N4xlr8YL2PQibAgFu2XHjkdeOIq38EDQg/edit#gid=0

**Comment by Danibelle** [comment]
I'm noticing this additional applicant on there who I didn't see before or interview, I will reach out and see if he's still available if you guys think we need to keep looking after you talk to Forest.

**Comment by Danibelle** [comment]
Forest hired 👍
