### ISSUE TITLE
Design for Self Producing Video Doc

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#640]

**Comment by ahmadabugosh** [comment]
Thanks @rodricastillo9013 ! I think a pdf would be fine, but just thinking out loud, if there is an option to make it editable maybe we can use it for other guides we need (for example, we could make one for "How to promote your project" or other things that have multiple steps).

**Comment by rodricastillo9013** [comment]
perfect! thanks

**Comment by ahmadabugosh** [comment]
Thanks @rodricastillo9013, I think it looks great! 

@melodysongq @clara-zi any comments before we close this issue?

**Comment by clara-zi** [comment]
Thanks @rodricastillo9013 It looks great.
I took out name, our project name and date and left it with a placeholder.
![image](https://user-images.githubusercontent.com/100724132/166476427-f936d6d7-dd04-45ce-816b-d5ff88eaaec2.png).

**Comment by melodysongq** [comment]
This looks great.  Do we have a list of projects that raised over $10K?  If so, I would love to send this to all of them.  Is $10K a good threshold?

**Comment by rodricastillo9013** [comment]
@clara-zi do you want me to remove it or replace it with data?

**Comment by clara-zi** [comment]
You can leave it like that if it's ok with everyone?

**Comment by ahmadabugosh** [comment]
I'm closing the issue, thanks again @rodricastillo9013 this looks great! :)
