### ISSUE TITLE
Office hours for project onboard

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#641]
We discussed in the connect sync that projects may benefit from having a regular office hour in at least two time zones.

The benefits are:

- A safe space for asking questions.
- Collect feedback
- Listen to others if they don't have specific questions, but they don't know what to do next.
- Projects can meet each other and connect offline.

Does this intersects with community orientation @WhyldWanderer ?

People interested in pushing the issues forward are @melodysongq  @clara-zi @Cotabe @ahmadabugosh 

Next steps:

- Choose times
- Design the structure
- Who would moderate?

**Comment by melodysongq** [comment]
I am happy to host a project community hour on Wednesdays or Fridays during CET time zone.   Alternatively we can have one community hour around the communitas meetings and have 15 min 1 on 1 as well where people can book through a calendly?

**Comment by Cotabe** [comment]
I can do every other week. Thursday's afternoon CST

**Comment by clara-zi** [comment]
I would like to be involved to learn more about issues around accessing crypto funds / offramping 
and facilitate sharing of solutions

**Comment by clara-zi** [comment]
@Cotabe @WhyldWanderer @melodysongq we should discuss this in the context of what can be achieved in the Weds AMA session.

I wonder if we should consider making this call a little earlier, so that it's accessible to people who aren't in the Americas, Africa or Europe?

**Comment by Cotabe** [comment]
We are adding an invitation to the AMA/orientation session on the emails that sent after the creation of a project, verification accepted and verification rejected. With the intention that more projects get more engaged and maybe help them develop fundraising skills. Idea of @Nikola.

I think the connect WG has rightfully spotted that most projects are raising very little. IMO is a priority to support projects to develop fundraising skills to help Giveth scale. I'm excited to see @melodysongq Fundraising 101 material and support in what I can (including facilitation).

Here is a short list of people interested in develop fundraising skills: Jerusha, Vijshen (propel), Jeremey&TheGospelofChange#8201, @gospelofchange, @DiogoJ. Not one person that I have asked if they want to develop fundraising skills have said they are not interested.

**Comment by clara-zi** [comment]
Plan is to add topics of interest to every 4th Communitas AMA starting the end of July, commencing with 'Fundraising 101' for projects.

**Comment by melodysongq** [comment]
I suggest to close this issue as a channel is created on Discord under Giveth-Connect to discuss ongoing meeting schedules and themes.
