### ISSUE TITLE
Tweet thread on Griff's Biggest web3 opportunity talk

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#655]
https://www.youtube.com/watch?v=ADSOVkujrI4

**Comment by laurenluz** [comment]
This might help too https://forum.giveth.io/t/ethden-2022-talk-summary-biggest-web3-opp-no-one-is-talking-about/549

Suga made an awesome summary of the talk

**Comment by laurenluz** [comment]
The idea is to create something similar to [this summary](https://twitter.com/Givethio/status/1521877035358068737) that I made for [Griff's commons stack talk](https://www.youtube.com/watch?v=cTMUh__9cWs)

Here are [Griff's slides](https://docs.google.com/presentation/d/1k6i-kGWsdzK_xLCOyLFG17ZWj-OJo9DjSMOUwtyjbfE/edit#slide=id.g11544a88a83_1_66), which could be used for screenshots.

@c0ric0ri would you be down to take this on?

**Comment by laurenluz** [comment]
oops, sorry, I linked the wrong slies: https://docs.google.com/presentation/d/1vpEwTjDTHz_S3iMZfqCEMjVEcOmK6NbJdue30PL3eHs/edit#slide=id.g115a6c4ca4d_0_412

**Comment by c0ric0ri** [comment]
Making final changes on this, planning to finish before end of the week!

**Comment by ahmadabugosh** [comment]
@laurenluz @c0ric0ri  should I make an audiogram similar to this one? https://twitter.com/Givethio/status/1493242526202884096 (if yes, just let me know what timestamps to take)

**Comment by laurenluz** [comment]
Hey @c0ric0ri, I just spent the time to get into this closely. I left a lot of comments and kind of hacked it up a bit. It's a great start, but I think there are some pieces of the story missing and some inaccuracies in the roadmap. Let's talk about this on Thursday in our call - it's a tough one!

But in the meantime, would be great if you could go through the comments, and feel free to make any changes that make sense. Reach out if anything is confusing.

Also @ahmadabugosh - you already made this one in #601 😄

**Comment by c0ric0ri** [comment]
Hey @laurenluz I've updated and cleaned up the tweet for further review per our last call. Just got a bit stuck again on Gurves...

**Comment by laurenluz** [comment]
Hey @c0ric0ri! I wrote some tweets for Gurves and made some more comments & suggestions. Passing off to you again for review/edits.

After we're satisfied w/ the content, would love if you could go in and add emojis, and add appropriate images too to the last tweets that I wrote :)

**Comment by c0ric0ri** [comment]
@laurenluz moving this to done :)

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1547599825088045057
