### ISSUE TITLE
QA of Giveth Donors 101 course

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#657]
Video onboarding course is so close to being done!

The task is to watch the videos & provide any feedback like:
- the title page text should be updated
- this one is missing the description
- this one has the old, outdate UI
- etc.!

Those are just some preliminary ideas. It would be really helpful if you could link the video along with your feedback in the comments on this issue.

Here is the video series: https://www.youtube.com/watch?v=vIQGUoWVTVI&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=12

Suga is down too check them all, but it would be great to get any other feedback as well from other contributors who wish to check it out.

@ahmadabugosh @danelsuga @scottbenjd @Cotabe @melodysongq

**Comment by laurenluz** [comment]
@ahmadabugosh  we should update the title page on the ("Intro" video) [https://www.youtube.com/watch?v=qY9F5X1b1QA&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=2] to say "Giveth Donors 101 Introduction" instead of Giveth Onboarding.

Also perhaps we want to update all the titles of the videos to be like:
- "Giveth Donors 101: Why Giveth?"
- "Giveth Donors 101: Introduction"
- "Giveth Donors 101: What is a Browser Wallet?"
etc.

I think we should leave the title pages, but adding the description to the title on youtube would help keep things organized, I think.

**Comment by danelsuga** [comment]
Great job!! As I get started, I'm just thinking:

The video is awfully small in relation to all the giant purple space all around it. Is there a reason for that?

It seems like it would be a lot better if the video itself took up at least half the video space.

More thoughts on aesthetics: I don't think Griff's name needs to take up so much space either. (And maybe it should say, "Griff Green, co-founder" for example? I'd also probably steer clear of the faux signature font.)

**Comment by danelsuga** [comment]
Ooooo, next video...

I see the differences going on here! Great.

For the video called "Giveth Onboarding", the "F" should be capitalized because that is the official slogan of Giveth, and across the board, I believe that is how it's done.

The next video "Browser Wallets" was WAY LOUDER for me than the first two.

**Comment by danelsuga** [comment]
"Browser Wallet" video minute 2ish: viewer is thinking, what is a seed phrase!?

**Comment by danelsuga** [comment]
Using the Giveth Matching Pool as a sample project is a teeeeeny bit confusing to the newbie viewer.

**Comment by danelsuga** [comment]
In the same video, narrator says that projects are verified when "the Giveth team has reviewed a project to check that the project is legitimate". I don't think that's actually correct? The project has to apply to become verified as far as I understand it.

**Comment by danelsuga** [comment]
How to Donate on Giveth ( minute 3:30): I'm not sure we want to say this in this manner? "In addition, if the donation is to a verified project, the donor may receive up to 70% of the donation back in GIV tokens."

**Comment by danelsuga** [comment]
@ahmadabugosh @laurenluz
Great job!
I had a lot of comments, so I made a doc. Hope that's OK. I was spamming in the comments last night but figured it was a bit overboard. :'D

https://docs.google.com/document/d/1m4AwFoUOZ0DrT4RP1Pdlec5hd3zXm2bDet3tyCnkzu4/edit?usp=sharing

**Comment by danelsuga** [comment]
@ahmadabugosh !

Can the title of the second video be changed to this?
Intro to Getting Started with Giveth
https://www.youtube.com/watch?v=qY9F5X1b1QA&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=2

It just takes out the colon and decapitalizes "to" (prepositions should never be capitalized unless they start a title).

Thanks!

**Comment by danelsuga** [comment]
@ahmadabugosh !

Can the title of the second video be changed to this?
Intro to Getting Started with Giveth
https://www.youtube.com/watch?v=qY9F5X1b1QA&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=2

It just takes out the colon and decapitalizes "to" (prepositions should never be capitalized unless they start a title).

Thanks!

**Comment by danelsuga** [comment]
On second thought, maybe it should just be "Getting Started with Giveth". None of the others say Ïntro to". And "intro to" "getting started" is a bit redundant, no?

**Comment by danelsuga** [comment]
I guess it's not possible to take "today"out of the Wallet Funding video? Maybe that tiny second could just be cut off? No big deal, I guess. Just seems a bit weird, as it's a video right in the middle of the series, so the person most likely has already heard several at that point.
https://www.youtube.com/watch?v=O-Vq7i4FqOw&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=4

**Comment by danelsuga** [comment]
The GIVeconomy video should just be called "GIVeconomy" and not "GIVeconomy intro". 

https://www.youtube.com/watch?v=_ULHxC5jwrg&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=6

**Comment by ahmadabugosh** [comment]
Thanks @danelsuga ! I made those edits you just suggested (changed the titles and I trimmed the beginning of the Wallet Funding and Regen videos, they're being processed now). I agree about the bird noises not being the most professional, maybe we can reshoot some of those videos later? 

Also, I'm working on the other notes you mentioned in the doc (but most of them require me to re-edit the entire video, so I may hold off on some until after we ship v1 of the series). I'll keep you posted!

**Comment by ahmadabugosh** [comment]
Ok done! I fixed all the issues you mentioned in your comments here and the doc you shared with the exception of two videos:

1) How to Donate (slight error in 70% versus 75%, the framing of "legitimate" projects and using another project in the example besides Giveth matching pool)
2) Regen Farms (the bird noises 🦚)

@laurenluz @danelsuga I suggest we launch it as is, and make seperate issues to fix those two videos (so we don't delay launching, since I think this video series is one we need to contstantly change anyway, and I think we should get it out the door). Wdyt?

**Comment by laurenluz** [comment]
Agree, let's ship it! It's never going to be perfect, but it is certainly good enough right now! 

Sorry about the bird noises 👀 there are a lot of birds here... plus side though, I bumped into someone today that watched the whole series (Griff shared it with them) and they said they found the videos I narrated to be very relaxing and easy to understand... maybe the bird noises added to the mood 🤣
