### ISSUE TITLE
Set up POAP Claim for Giveth Donors 101 course

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#658]
The design is in #634

We want this to be claimable by "anyone with the link", and have the link only available at the end of the quiz from #635

**Comment by scottbenjd** [comment]
Drop created. Working on website now.
https://app.poap.xyz/admin/events/giveth-donor-101-course-completion-2022

**Comment by scottbenjd** [comment]
Did we decide on how many we wanted to distribute? Start with the first 100, then request additional links from there?

**Comment by scottbenjd** [comment]
I'm not sure if there's a notification. I'm hoping the # minted is tracked on the website so we can check there periodically, if nothing else. I submitted the website for 100. We can always request more. I wouldn't mind testing out the additional mint request process anyway.

**Comment by ahmadabugosh** [comment]
Thanks @scottbenjd !

1)  I think 100 would be good to start with, plus it gives some scarcity we can market. 

2) So in terms of workflow, anyone with the link can claim? We don't need to pre-add their addresses? 

3) Also, I think we should extend the deadline. I'm not sure what the difference is between "end date" and "expiry date", but it would probably make sense to extend it to mid or end of June, to give us time to market it

**Comment by WhyldWanderer** [comment]
bends is away so Im gonna help out with this one... 

As far as I know, we have 2 options for delivery.

1. We request a number of links. these links are unique and can only be claimed once. This would be something we could send in an email to the person who completes the course. We would want to make sure that each email address can only be sent one link (can be done in autopilot). 

2. We enter a list of addresses.

I dont think there is anyway that we can set it up as 'anyone with the link' unfortunately. I will look into it a bit more and update here if I learn something different.

> Also, I think we should extend the deadline. I'm not sure what the difference is between "end date" and "expiry date", but it would probably make sense to extend it to mid or end of June, to give us time to market it

End date is when the event ends. It is common for POAPs to be handed out at events.
Expiry date is when the poap is no longer available... this can be set up to one year from the start date of the event.

**Comment by ahmadabugosh** [comment]
Thanks @WhyldWanderer ! 
In that case, should we ask them for their address as a question in the typeform at the end and then say we'll reach out for them to claim the POAP? Or do you think we should request a bunch of links? Is there any downside to either approach? Which one do you prefer?

**Comment by laurenluz** [comment]
Do we have any process to remember to send these out every x weeks? Is that just on your plate @ahmadabugosh ?

**Comment by laurenluz** [comment]
Ahmad can put out the poaps w/ the GIVbacks
Really powerful to use GIVback rounds as out time marker for everything

**Comment by ahmadabugosh** [comment]
Closing this issue, created [another issue](https://github.com/Giveth/giveth-planning/issues/718) to deal with spam
