### ISSUE TITLE
Tweet thread to announce Giveth Donor 101 Series

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#659]
https://www.youtube.com/watch?v=kfoyvsPYnrE&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=1

**Comment by laurenluz** [comment]
https://docs.google.com/document/d/1bDp4FBCQ2nZRx2I9gZ5UT70-r3VcRyZL61buhz2q7QM/edit?usp=sharing

@ahmadabugosh @danelsuga if you guys could provide some feedback soon, would be awesome :) we're all ready to announce this

**Comment by danelsuga** [comment]
Looking good! Isn’t it 70%?

**Comment by laurenluz** [comment]
you know better than me!

**Comment by danelsuga** [comment]
We'll confirm with @ahmadabugosh hopefully. I believe it's 7 out of 10 Q's correct.

**Comment by laurenluz** [comment]
Griff is asking if we can make it 8/10 since it's multiple choice and we WANT people to watch the videos. 7/10 is pretty easy to get even without watching them at all.

**Comment by danelsuga** [comment]
Good idea.
