### ISSUE TITLE
Blog post to announce the Giveth Donor Onboarding Series

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#660]
Here is the course:  https://www.youtube.com/watch?v=kfoyvsPYnrE&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=1

This should be a blog post summarizing some of the key concepts in the series, and basically giving a 101 level intro to what is giveth & why you should use it to donate.

A starting point could be #628

@Elizardwizzard it would be great to have a first draft of this week early next week (perhaps by Tues april 10?) - lmk if that's too soon, or reach out if you want to schedule a 1:1 to get some more insight into this.

**Comment by Elizardwizzard** [comment]
Hey Lauren! I'll have the draft by the end of the day :)  no questions until now 
Going thru the videos I noticed someone asked for Gnosis chain documentation mentioned in the Wallet Funding video https://www.youtube.com/watch?v=O-Vq7i4FqOw&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=4

**Comment by ahmadabugosh** [comment]
Thanks @Elizardwizzard ! I added the video descriptions and answered her

**Comment by laurenluz** [comment]
Hey @Elizardwizzard - can't open the doc. can you make it "anyone can comment"?

**Comment by Elizardwizzard** [comment]
Are you able to see it now?

**Comment by laurenluz** [comment]
Hey @Elizardwizzard! Thanks for putting this together! It's a good summary of the first couple of videos, maybe we can convert these into documentation or use the content to add to our existing docs.

For this blog though, I was hoping more for an announcement of the course overall. Something like "Giveth is a donation platform that uses web 3 to create huge opportunities for donors! This course is designed to give you the low down on all you need to know to become a giveth donor" etc. etc. Giving a brief overview of the videos, and a few paragraphs on the "what is Giveth/why use giveth".

Since this is blocking our release of the video series I'll pass it on to @danelsuga to finish out quickly since I'm not sure of your bandwidth for Giveth :)

Let me know if you have any questions!

**Comment by danelsuga** [comment]
https://docs.google.com/document/d/1W_i8Oe6EBdPGzgdGPkw6Vb6YA423IRxAzxcZSBkIfrg/edit?usp=sharing

**Comment by danelsuga** [comment]
@laurenluz @ahmadabugosh

**Comment by ahmadabugosh** [comment]
Hey @danelsuga looks good! I have a few comments:

1. Make sure to link the latest playlist video (for example the first "Why Giveth?" video is the old unlisted one, [this is the new one](https://www.youtube.com/watch?v=-JXwwIGJGQQ&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=2&ab_channel=Giveth)
2.  Can you include a link to the quiz: https://giveth.typeform.com/to/IZndeKbH
3. Maybe liven it up with some emojis?

**Comment by danelsuga** [comment]
Right! Ok! Will do in morn.

**Comment by danelsuga** [comment]
"Why Giveth?" meaning the same video that kicks off the series?

**Comment by ahmadabugosh** [comment]
@danelsuga Yes, exactly!

**Comment by danelsuga** [comment]
Thanks again!

@rodricastillo9013 could you help out with a banner please? Something with Giveth elements along with something school/text related.

And the title would be cinematic style with "Presenting" in small text followed by "The Giveth Donor 101 Course" in big text.

**Comment by rodricastillo9013** [comment]
yes, sure :)

**Comment by danelsuga** [comment]
Thaaaanks!

**Comment by rodricastillo9013** [comment]
Hi! wydt? 
<img width="578" alt="Banner" src="https://user-images.githubusercontent.com/61791380/169547385-d5e8001b-421f-4bf7-acbf-832b96ed1deb.png">

**Comment by danelsuga** [comment]
Great! Thanks @rodricastillo9013 !

**Comment by danelsuga** [comment]
This is ready to go. @laurenluz @ahmadabugosh can you give it a last look please?

**Comment by ahmadabugosh** [comment]
I think it's great! 

I was just thinking, maybe we can have a catchier title. What about something like: "Become a Certified Giver!", "Learn to Maximize Your Social Impact as a Giveth Donor", or "Join the Future of Giving by Becoming a Giveth Donor"

**Comment by danelsuga** [comment]
Thanks!

Ok, in that case, can we leave the banner Rodri made, and we'll just change the article title?

**Comment by danelsuga** [comment]
I really like the "Giveth Donor 101 Course", so it'd be good just to add to it then. But I think key is we don't want to discourage folks from reading (which is why, you recall, we used "Donor" for the course and not "Giver"). 

But maybe "Become a Certified Giver" could work if we have both titles going on. Except it implies something about being officially certified. Are we offering that? I guess they get a POAP if they do the course, but I'm not sure that's what they means. I still like it though. That one is my favorite of your ideas. I'll have a think as well.

**Comment by ahmadabugosh** [comment]
I think we can leave the banner as is. In a way it's kind of like how when we discussed Twitter in our last meeting, when we said that the Twitter banner could give more information. So in this case the banner and title both would convey a slightly different message, that encourage people to read the article.

Yeah I was thinking the certification is the POAP, so that one might work

**Comment by danelsuga** [comment]
Great!

**Comment by laurenluz** [comment]
@rodricastillo9013 can you make the banner taller? formatted for Medium, like this one:
![image](https://user-images.githubusercontent.com/75490971/169892405-e7543416-b0bc-4a9b-baed-232a42d18682.png)

@danelsuga @ahmadabugosh I'm down with changing the title to something catchier, although I think it helps to be explicit about what to expect. Maybe something like "Everything you need to know about donating on Giveth" or something that describes to the user what they are about to learn.

Not sure "becoming a certified giver" is the right framing because the purpose is to offer support to those who are new/unsure. This kind of title could be intimidating.

**Comment by laurenluz** [comment]
Otherwise, I left some last small comments, and I think this is ready to submit to the Giveth publication when you're ready @danelsuga

**Comment by rodricastillo9013** [comment]
ok i prepared it :)

**Comment by rodricastillo9013** [comment]
<img width="1400" alt="Medium Post - Full width" src="https://user-images.githubusercontent.com/61791380/169898487-fcbbb018-1176-43aa-915c-f5137e998598.png">

**Comment by danelsuga** [comment]
Live
https://medium.com/giveth/the-abcs-of-donating-on-giveth-6e3bd147397e
