### ISSUE TITLE
"Project Fundraising Guide" Documentation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#664]
We should help projects with the Giveth messaging to share with their donors. Things like "how to take advantage of this opportunity to raise funds on Giveth".  Some examples:
- zero fees
- low gas on gnosis chain
- donors get GIVbacks
- how to add to the transparency of your project.
- how we can support you with amplifications (twitter, meet the makers, etc.)

Would be great to add this to our documentation.

@melodysongq @clara-zi maybe you'd be interested in collaborating with someone from the comms team to put this together

**Comment by melodysongq** [comment]
We should definitely look at this.  After getting to know Giveth better with trying it out, I think there are many questions and problems that project would have that can’t be simply addressed.  For example, 
1. “no fee” may need a little explaining (no fee to Giveth) but projects should know (which many don’t) that they would need to pay fees to get the money off ramp
2. “gnosis chain” needs explaining, and most don’t understand what  is a “gas fee”
3.  we are lacking in resources for projects to make things easier to happen on their end (i.e. resources for fundraising on social media, resources to amend a “gift acceptance policy” for their board if they have one, resources to manage “cash” and organisational accountabilities to receive crypto as it really is a “cash room”) 
4.  how to talk to their donors about Givbacks - this needs to be simple as Rainer had mentioned a simpler senarrio is needed

Maybe we can have a focused agenda item for this issue tomorrow (May 10).  Melody









Melody Song MA CFRE
Co-Founder & Principal Solution Designer
***@***.*** I +49 1621750914
dogoodhere.org <http://dogoodhere.org/>

Book a meeting: https://calendly.com/melody-54/60min

**Comment by clara-zi** [comment]
essentially a mini-guide to running a fundraising campaign on Giveth. Started drafting a google doc.

**Comment by clara-zi** [comment]
Draft document (WIP) can be found here. @melodysongq would love your wisdom on fundraising process: I'm sure there is more that can be added.

**Comment by melodysongq** [comment]
> Could we automate sending reminder emails for different stages of fundraising campaign set-up and suggestions of what to post and when? Worth brainstorming a timeline? @melodysongq @Cotabe

Let's create a space on Miro for brainstorming.   I will start with something and post a link for others.

**Comment by melodysongq** [comment]
Here is a space we can brainstorm timeline and visualize ideas before putting them into a document:
https://miro.com/app/board/uXjVOHUtG4M=/?moveToWidget=3458764525529864655&cot=14

**Comment by clara-zi** [comment]
also includes ideas for social messaging. Would be nice to brainstorm more.

**Comment by clara-zi** [comment]
Soundbites for social media in Section 7. Ideas for any more? @danelsuga @SymSL @laurenluz @ahmadabugosh

**Comment by WhyldWanderer** [comment]
This has already been uploaded to the docs! 
https://docs.giveth.io/whatisgiveth/fundraisingGuide

Closing this issue for you @clara-zi!
