### ISSUE TITLE
Support review process for Cryptoholics

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#667]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/79aa833f-a949-4b86-b759-8e1cdfeebcb6)

Worth pursuing, I think... Who's interested in coordinating on this? @SymSL @danelsuga @ahmadabugosh @scottbenjd

**Comment by oyealmond** [comment]
@laurenluz , can I close this?
