### ISSUE TITLE
Reach out to top projects for success stories

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#668]

**Comment by ahmadabugosh** [comment]
Hey @melodysongq @clara-zi I just shared this doc that has the emails of the top projects, to reach out to for the task we mentioned in the last meeting (to record self produced videos / to get their success stories: https://docs.google.com/spreadsheets/d/1KHbgirrxhiRpwtw7SCZX9WfRgkAV3Fd2FZLz7vLhL5o/edit#gid=0

**Comment by melodysongq** [comment]
I've drafted an email to be sent to the project owners, please take a look:
https://docs.google.com/document/d/1uy3LR6S83mtgKifOUORVfzIzTAGWQ9DUE_vpZGzg3H4/edit

**Comment by melodysongq** [comment]
@Cotabe let me know what's the next step to email this out.  This in fact can go one by one since there are only 20 or so (there are a few internal matching fund in the list) but preferrably from a Giveth email.  What's your suggestion?

**Comment by ahmadabugosh** [comment]
Yeah I think sending to Autopilot could be one option, but if it's only 20, maybe one to one emails would be doable. @laurenluz do we have a shared giveth.io email we can use to send out one to one emails or for outreach?

**Comment by clara-zi** [comment]
> @Cotabe let me know what's the next step to email this out. This in fact can go one by one since there are only 20 or so (there are a few internal matching fund in the list) but preferrably from a Giveth email. What's your suggestion?

if it's easier and quicker to do one-by-one - I'm happy to split the load and send some @melodysongq melodysongq 

@Cotabe @ahmadabugosh

**Comment by melodysongq** [comment]
I've looked into the spreadsheet and highlighted those internal projects and those projects may not be legible to ask for a success. https://docs.google.com/spreadsheets/d/1KHbgirrxhiRpwtw7SCZX9WfRgkAV3Fd2FZLz7vLhL5o/edit#gid=0

**Comment by Cotabe** [comment]
@melodysongq @ahmadabugosh I can't access the spreadsheet. Just asked for access

**Comment by melodysongq** [comment]
you should be able to access from here: https://docs.google.com/spreadsheets/d/1KHbgirrxhiRpwtw7SCZX9WfRgkAV3Fd2FZLz7vLhL5o/edit?usp=sharing <https://docs.google.com/spreadsheets/d/1KHbgirrxhiRpwtw7SCZX9WfRgkAV3Fd2FZLz7vLhL5o/edit?usp=sharing>
We have a standard email which is as follows: 
https://docs.google.com/document/d/1uy3LR6S83mtgKifOUORVfzIzTAGWQ9DUE_vpZGzg3H4/edit <https://docs.google.com/document/d/1uy3LR6S83mtgKifOUORVfzIzTAGWQ9DUE_vpZGzg3H4/edit>

PDF of the instruction that can be sent as an attachment should be on the issue.
Also note that those highlighted in red will not be sent the instruction as they are either internal, a matching fund, or not a verifiable project anymore. 
We just want to get someone with a Giveth email account to send this out.  Claire and I can do it if we have access.
Melody








Melody Song MA CFRE
Co-Founder & Principal Solution Designer
***@***.*** I +49 1621750914
dogoodhere.org <http://dogoodhere.org/>

Book a meeting: https://calendly.com/melody-54/60min

**Comment by ahmadabugosh** [comment]
@Cotabe I just shared it with you (I didn't want to make it public because it has private emails on it).

@melodysongq Also I think you should also get a giveth.io email (either a shared one for the connect group or an individual one for you) for these one-to-one outreaches for projects or external partners. Let me check with the team on that

**Comment by clara-zi** [comment]
Thanks @ahmadabugosh I await decision about email. @Cotabe Once you have access to sheet, let us know if there's anything you'd like to add.

**Comment by melodysongq** [comment]
> @melodysongq Also I think you should also get a giveth.io email (either a shared one for the connect group or an individual one for you) for these one-to-one outreaches for projects or external partners. Let me check with the team on that

let's have something like project@giveth.io  or projectsupport@giveth.io email and have Claire and I with access.

**Comment by Cotabe** [comment]
I am checking if we can get one of the emails that @melodysongq suggested.

Interestingly some of the project owners were different. But I found all but one which I highlighted in yellow.

The email draft is already created... but I have a few concerns:

- Currently the default email is no-reply@giveth.io. We are asking for a reply so we need no change this. @ahmadabugosh any ideas?

- I am not sure if asking for a 2-3 minute video is the best CTA. Making a video takes energy, some people want to make it perfect or they don't do it. I think that there are several valuable insights we could harness from these project owners including testimonials, tips and tricks for crypto fundraising, feedback, and profiling insights to find similar successful project/project owners. Would it make sense to invite them to a 1 on 1 meeting, ask permission to record it and get as much content as possible from this project owners? The tradeoff is that it would require more bandwidth but the results may be worth it

**Comment by melodysongq** [comment]
> * I am not sure if asking for a 2-3 minute video is the best CTA. Making a video takes energy, some people want to make it perfect or they don't do it. I think that there are several valuable insights we could harness from these project owners including testimonials, tips and tricks for crypto fundraising, feedback, and profiling insights to find similar successful project/project owners. Would it make sense to invite them to a 1 on 1 meeting, ask permission to record it and get as much content as possible from this project owners? The tradeoff is that it would require more bandwidth but the results may be worth it

Cotabe, this has been successful with other nonprofit and I found short video updates gives a lot of credibility to the project itself and it becomes a content that the platform can use and the charity can use as well.  We can definitely as for other things like testimonials etc. too.  A tik-tok like video is easy but really good to see faces behind the projects (and the diversity of it).    This is why we are asking.  From a project point of view,  people always love to have ideas for stewarding donors. Also a feel-good content generating for project promotion.  I think it's win-win and can be  an ongoing ask.

**Comment by ahmadabugosh** [comment]
@Cotabe We made an email that @clara-zi has access to "projects@giveth.io", you can use that one for the reply to

**Comment by clara-zi** [comment]
Hi @Cotabe let me know if/when you need the details. Email should be set-up and live now. I've just completed the set-up but making sure it works.

**Comment by Cotabe** [comment]
Email tested. Now replys will go to: projects@giveth.io

I edited a bit the copy and used some design elements. But I'm not sure if it lacks some "punch". 

I sent the test to @ahmadabugosh and @melodysongq 

@clara-zi I can send it to you if you share your email :)

**Comment by ahmadabugosh** [comment]
@Cotabe Looks good! 

A few comments:

1) There is a small typo in the preview text ""feautirng"
2) Can you include a link to the design explainer doc: [Rodri created for this](https://docs.google.com/document/d/1cbzPr6eU7wY32Zq-ShPZ1w0JEIXjwOzMdxJmU0hnsDE/edit ?) Maybe export it as a pdf if possible? 
2) What do you think about adding to the end something about if they don't want to record a video, they can send us a written testimonial instead (maybe mention how we would love to see them record a video and we think it would have a stronger impact, but if they're shy a written testimonial would work too)?

**Comment by clara-zi** [comment]
> Email tested. Now replys will go to: [projects@giveth.io](mailto:projects@giveth.io)
> 
> I edited a bit the copy and used some design elements. But I'm not sure if it lacks some "punch".
> 
> I sent the test to @ahmadabugosh and @melodysongq
> 
> @clara-zi I can send it to you if you share your email :)

clairepapazidis@gmail.com

**Comment by Cotabe** [comment]
@ahmadabugosh Thanks for the great comments.

> * There is a small typo in the preview text ""feautirng"
> * Can you include a link to the design explainer doc: [Rodri created for this](https://docs.google.com/document/d/1cbzPr6eU7wY32Zq-ShPZ1w0JEIXjwOzMdxJmU0hnsDE/edit ?) Maybe export it as a pdf if possible?
> * What do you think about adding to the end something about if they don't want to record a video, they can send us a written testimonial instead (maybe mention how we would love to see them record a video and we think it would have a stronger impact, but if they're shy a written testimonial would work too)?

1. Is fixed.

2. This is great, but to keep it consistent I'ld suggest we agree on recommended duration (60-90 sec or 2-3 minutes) and what do we want them to touch upon.
Here are a few suggestions, I think we should keep only about 3.
A.	Introduce yourself.
B.	What you like about Giveth
C.	State how Giveth helped your organization/What are we (giveth) doing good for you?
D.     Key factors to your success.
E.     What could we improve?

I would go for A, C and D. A because we want them to talk about their project. B & C are great for testimonial, but IMO may overlap, I like more the wording of C. D is one of the main reasons why we are reaching out to these audience, to get insights on tips and tricks.to share with others projects.

Also on the document that Rodri made, do we want to leave social media so general, knowing our IG and FB are not much in use?

3 Love the idea... I added that they can send a written testimonial if they are feeling shy.

@clara-zi sent it.

**Comment by ahmadabugosh** [comment]
Thanks @clara-zi I just got it, it looks good! I would just suggest that you share the Self Product Video Guide as a PDF (instead of the Google doc, by exporting the file in pdf format)

**Comment by ahmadabugosh** [comment]
Thanks @Cotabe ! 

1. I would suggest 60-90 seconds, if people want to go over we won't stop them, but even a 10 second soundbite would be useful for us. 
2. Yes, I agree A, C and D are the ones I like too

**Comment by Cotabe** [comment]
@ahmadabugosh I will make it a PDF and attach it once we figure out the small inconsistencies. I would like to briefly discuss it on tomorrow's connect call.

**Comment by melodysongq** [comment]
@Cotabe @ahmadabugosh @clara-zi I wonder if the email is too "designed" and does not feel personal.  Since the PDF is quite designed already, I would love to see a simple email in a letter format just like when we send an email to friends.  This way, people don't feel that they are just part of a promotion but a more "personal" request from the platform and donors and it become a little more meaningful.  What do you think?

**Comment by clara-zi** [comment]
@Cotabe Thanks for sending me a copy of the email. 
I think "What has help you have a succesful fundraising?" should be "What has helped you have a successful fundraiser?" or "What has helped you to fundraise"?

@Cotabe no Connect Call today - strategy session is replacing it.

**Comment by clara-zi** [comment]
> @Cotabe @ahmadabugosh @clara-zi I wonder if the email is too "designed" and does not feel personal. Since the PDF is quite designed already, I would love to see a simple email in a letter format just like when we send an email to friends. This way, people don't feel that they are just part of a promotion but a more "personal" request from the platform and donors and it become a little more meaningful. What do you think?

To Melody's point - readers will know from the design that it's been sent as a mailshot or as part of a campaign. Will this affect someone's motivation to create and send a video? Maybe. Readers may be less likely to read and understand what we're asking - they may think it's a promotional email.
What I do like about the email is that:
- it summarises what we're expecting from the participant
- all the information is easy to access
- it's in a format, uses language and a style that we're very used to seeing

For me it's a discussion and decision over personal, friendly style or campaign, informal style?

For me both have merits but I think ultimately, if people like making videos they will do one, if not, they won't. I'm not sure the email style will make a massive amount of difference.

**Comment by melodysongq** [comment]
@clara-zi in fact this subject has been studied to death with lots of email copies being tested.  The one with less picture and longer text in fact engage people better which results in better donation and higher donation amount.  However, the ones with fancier outlook will increase click-through rate but results in lower donation/action taken.   I wish we could do a control group and measure the response rate.  My gut feeling is a plain email will do the trick.

**Comment by clara-zi** [comment]
"Feeling shy about a video, but wanna help? We get it, you can also reply in text..." 

Does this make our request look a little one-sided - that it the video will be for our benefit only? What we are asking will also help the project with their promotion.

Could we say something like: 
"Feeling shy about a video, but wanna share your story in writing or pictures? We'd love to hear all about it by email or tag "@giveth.io" on Twitter and your other social channels".

**Comment by Cotabe** [comment]
I like the ideo of having a control group. Unfortunately, even with our full targeted audience it would be statistically significative. But I think having an A/B test would be great, because this is very contended and I think we are using a lot of time based on perspectives. I will apply all the feedback here and send you two emails: A. More personal, text oriented and without the link. B. Still personal with the link. 

Then reply again here with edit sugestions.

**Comment by clara-zi** [comment]
I don't think these emails have been sent yet. 
This issue needs final decision on content of outreach email. It would be really good to get these sent and get some success story vids @melodysongq @Cotabe @ahmadabugosh 

>

**Comment by clara-zi** [comment]
> Thanks @Cotabe !
> 
> 1. I would suggest 60-90 seconds, if people want to go over we won't stop them, but even a 10 second soundbite would be useful for us.
> 2. Yes, I agree A, C and D are the ones I like too

@cotabe @ahmadabugosh @melodysongq please check the tip sheet document that Design made, as I think it was more along the lines of A B C. (I only have the draft doc). I think we should keep the email text consistent with the attachment we are sending. wdyt?

Agree that we should remove IG and FB until there are more active.

**Comment by melodysongq** [comment]
@Cotabe @clara-zi I wonder if you can share the email draft link here. I can't find it.  Thinking from the project's point of view, a video should: 1) help them promote their cause - so they should definitely say in the video what they do; 2) give tips to others or provide support/confidence about using the Giveth platform... so it's D?   Oki mentioned that video lenghth really depends on the platform.  Youtube 1-2 min, tiktok shorter.  I would love to see project touching all the point and 1-2 min is really short.   Maybe we can finalize the discussion at the Connect call tomorrow June 7.

**Comment by clara-zi** [comment]
@melodysongq could you please share a copy of the tip sheet created by Design team?

**Comment by melodysongq** [comment]
@clara-zi I think it's this one that's shared in this string, or has it changed? https://docs.google.com/document/d/1cbzPr6eU7wY32Zq-ShPZ1w0JEIXjwOzMdxJmU0hnsDE/edit
I don't have the email though as I only received a test email but can't find a link to a document.  Do you have?

**Comment by Cotabe** [comment]
Sorry, last week I focus on other topics and left this in my backlog. 

I just sent 2 versions of this mail to @ahmadabugosh @melodysongq & @clara-zi . The first from autopilot w/ design, the second from my email with simple text (more of a personal touch). We can discuss the feeling of both tomorrow.

I was thinking that we could just send the simple text from projects@giveth.io. However, we would lose the tracking of emails opened, clicks, etc. We can send something similar from Autopilot.

Tomorrow I will probably join from a governmental office, as I have to do some paperwork if I wanna go to Barcelona. I hope there are no communication issues.

**Comment by ahmadabugosh** [comment]
Looks good @Cotabe ! I like the simple text better myself. 

I'm pretty sure you could keep the tracking on if you send it through Autopilot as a simple text email (and put the reply to as project@giveth.io)?

**Comment by clara-zi** [comment]
> I don't have the email though as I only received a test email but can't find a link to a document. Do you have?
@melodysongq here is a quick copy and paste....

"Hey  {{ person.firstname | default: 'there' }},

This is [Name] from Giveth, I am excited to see that your project is doing so great and your efforts are paying off!

We would love to know more about your story and share it. It would be amazing if you could share with us a short video saying in a nutshell:

- What's your project about?
- How Giveth helped your organization?
- What has helped you raise funds successfully?

Your success story will help us support you better, support other projects to learn fundraising skills, and help you be more successful by promoting your projects to potential donors through your impact story. If you need more guidance we are attaching a guide to help.

If you are feeling shy about making a video, but you wanna help, it's understandable, you can also reply to this email sharing your story, how has giveth helped you and what has helped you raise funds. We would love to hear from you. 

Videos are great to connect with people, though 🤩 

Thanks for using Giveth, we are looking forward to seeing your video! ✌️

Best,
[Name]

**Comment by clara-zi** [comment]
@Cotabe @melodysongq @ahmadabugosh shall we aim to get this sent before the end of the week? Have we reached a consensus around the mail wording/style? Thanks

**Comment by laurenluz** [comment]
@clara-zi seeing this come up in my inbox. looks pretty good to me! some small suggestions to the bottom to shorten/simplify:

> If you are feeling shy about making a video but you want to help, you can also reply to this email to share your story. Videos are great to connect with people, though 🤩
> 
> Thanks for using Giveth, we look forward to hearing from you! ✌️

Also in the future, it's create to share content like this that asks for comments in the text via an "anyone can comment" google doc... That way people can leave comments and suggestions there directly.

**Comment by Cotabe** [comment]
Scheduled

**Comment by clara-zi** [comment]
Nice one folks, what a fabulous surprise to wake up to a response to our outreach for success story videos.
However, responder has asked for an interview (through 'projects' email).
