### ISSUE TITLE
Create Subdomain for Newsletter Platform

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#669]

**Comment by ahmadabugosh** [comment]
Hey @geleeroyale can you create a subdomain for our Newsletter called: 

1. Point it to: news.giveth.io
2. It's for the platform.  https://www.getrevue.co/

Here are the details below on the CNAME records: 

"Create a CNAME to www.getrevue.co
 Make sure that your subdomain is successfully pointing to Revue (this may take a while)."
 
 Let me know if you have any questions!

**Comment by geleeroyale** [comment]
Record is set

**Comment by ahmadabugosh** [comment]
Thanks @geleeroyale, the domain is working (yay): https://news.giveth.io, however it doesn't have the ssl certificate yet. Can you see if that is something you can activate or see what you recommend? http://help.getrevue.co/en/articles/4465817-how-to-make-your-custom-domain-secure-with-ssl

**Comment by ahmadabugosh** [comment]
Hey @geleeroyale I'm closing this for now, but please add it to the backlog and let us know if you come up with a solution 🙏

**Comment by ahmadabugosh** [comment]
Hey @geleeroyale , we recently moved our newsletter to Paragraph and want to setup our subdomain news.giveth.io for it.  Can you help with that? See instructions here: https://docs.paragraph.xyz/docs/customizing-your-publication#custom-domain

**Comment by ahmadabugosh** [comment]
This is done! Our newsletter is now on: https://news.giveth.io
