### ISSUE TITLE
Liquidity Mining

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-planning#67]
As Giveth DAO, we want to incentivize GIV token holders to provide GIV token liquidity to DEXs.
As a user, I want to be able to earn GIV by providing GIV liquidity on DEXs and staking my liquidity pool token.

AC:
1. Users can stake GIV liquidity pool tokens for a variety of pairs and DEXs (TBD) and and earn GIV tokens

**Comment by willyogo** [comment]
As Giveth DAO, we want to incentivize GIV token holders to provide GIV token liquidity to DEXs.
As a user, I want to be able to earn GIV by providing GIV liquidity on DEXs and staking my liquidity pool token.

**Comment by ForestSoleil** [comment]
**GIVmining** - Liquidity Mining (Edu, Fabio, DappNode crew)
Update as of July 2nd:
- 1) front end complete
- 2) launching token on rinkeby
- 3) begin testing to ensure all liquidity mining contracts are all tied together, working in alignment, front end dev work is all running smoothly
- 4) ^ once all of this is connected, Giveth will look at the user flow and how we want to modify it
- 5) Design work for GIVmining
