### ISSUE TITLE
Guide for projects: Volatile vs Stable coins

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#670]
Document explaining the significance between volatile vs stable coins and the significance of volatility for projects.

**Comment by WhyldWanderer** [comment]
I looked at the doc but it seems like youre still working on it @clara-zi ?

Moving back to sprint backlog

**Comment by clara-zi** [comment]
Only that I was waiting for review to be completed.

**Comment by c0ric0ri** [comment]
@WhyldWanderer @laurenluz would be great to get your eyes on this for final confirmation!

**Comment by WhyldWanderer** [comment]
I think it looks fine... its nice to have some reference of this for projects when they dont understand why the $ amount on their project and the $ amount in their wallet dont match.

Do you plan to put this in the docs @clara-zi? Maybe it would make sense to put it in this section?
https://docs.giveth.io/dapps/crypto

We should have one more reviewer and then this can go live in the docs

**Comment by c0ric0ri** [comment]
@SymSL would be great for you to review!

**Comment by c0ric0ri** [comment]
Hey @SymSL are you still good to review this one? Would be great to get this completed!

**Comment by SymSL** [comment]
I've reviewed and think its really great. If there is any explanation as to why coins may lose their peg, would be great to include a one liner (not that I know if there is any simple explanation for this). I've left a few other comments, great job @clara-zi

**Comment by c0ric0ri** [comment]
Hey @clara-zi can you please clean up this final draft and add it to the docs?

**Comment by c0ric0ri** [comment]
@clara-zi would be great if we can close this issue out soon. When can you have this completed by?
