### ISSUE TITLE
GIVpower Documentation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#672]

**Comment by laurenluz** [comment]
@divine-comedian I made a doc with roughly the list form of stuff we should include in the documentation. Thanks so much for offering to help w/ this.

https://docs.google.com/document/d/1UdM5_TFXOkl0Hj4oj2VRkGNYzcKHpGdXY_8NR3Sck6Q/edit

**Comment by divine-comedian** [comment]
first draft for review:
https://docs.google.com/document/d/12P-LjYWIBlUkASR8QOf2hC4J67-9sVmK1V6R21WsHKU/edit?usp=sharing

**Comment by divine-comedian** [comment]
I implemented changes suggested from Lauren's review

**Comment by c0ric0ri** [comment]
@tropicalmangos would be great if you can review this for easiness to understand!

**Comment by divine-comedian** [comment]
> @c0ric0ri @laurenluz have reviewed and provided feedback from a newbie perspective :) My thought process was to make sure it's easy for just about anybody to understand

Better to look at the assignee and update them that you reviewed. No need to move the issue or assign anyone

**Comment by laurenluz** [comment]
@tropicalmangos FYI our process for closing issues... we only close them after the content is publish & the link is added to the issue.

**Comment by c0ric0ri** [comment]
@divine-comedian @tropicalmangos is the documentation update live? If yes, please provide link here and close the issue please. Thanks!

**Comment by laurenluz** [comment]
It's live https://docs.giveth.io/giveconomy/givpower/

It's just hidden. We will need to unhide it when we launch Oct 4. I will put this in "done" and then once it is unhidden, we can close the issue.

**Comment by divine-comedian** [comment]
oh and we need to fill in the launch date and the production smart contract addresses!

**Comment by laurenluz** [comment]
it is updated and live! https://docs.giveth.io/giveconomy/givpower
