### ISSUE TITLE
New Twitter Bio & Banner for Giveth

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#673]
Working on updating out Bio & Banner for more impact...

From meeting w/ Steee:

Bio points:
- add mini mission statement
- can use stats to give authority like "over x projects raising funds in crypto" or "over x funds raised"
- go for clairty + hype/buzz. People should understand it & want to be a part of it

Banner idea:
- optimize space: include 3-4 words explaining what Giveth is

Bio phrases for brainstorming:
•Transforming the way we fund public goods (personally I love this)
 •Rewarding and empowering people who create value for society.
 •Rewarding and empowering projects & doners who create value for society.

Work on this:

https://docs.google.com/document/d/1Awvdl-KqaqcOGxFEbUu_g4Iw0cEDO4aX2fv_D4viFeI/edit?usp=sharing

**Comment by rodricastillo9013** [comment]
hello! we should define some phrases so that I can go to the design stage, which ones do you like the most?

**Comment by laurenluz** [comment]
Should add to linkedIn & facebook when complete

**Comment by laurenluz** [comment]
https://twitter.com/Givethio

Transforming the way we fund public goods | P2P | Zero Fees | Donor Rewards | Regenerative Crypto Economics | Decentralizing Charity | DAO

![image](https://user-images.githubusercontent.com/75490971/170146144-bc6e055c-09e3-4bf2-b11a-f4403a513ac5.png)
