### ISSUE TITLE
New Banner for giveth Twitter

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#674]
As per Giveth/giveth-planning#673 - we should make a new banner for the Giveth twitter that doesn't say "giveth" but makes us of the space to provide more context to who we are.

I'm working on some ideas in that issue, and once they are finalized, I'd love your help @rodricastillo9013 to use those words & giveth branding to update the art for the banner!

![image](https://user-images.githubusercontent.com/75490971/167491971-46bab9bf-15a7-4366-95df-d3c78c6eac55.png)

**Comment by rodricastillo9013** [comment]
brilliant! when you have some phrases, you share it with me and we will design it!

**Comment by laurenluz** [comment]
Hey @rodricastillo9013!

Ready! Can you make it say:

"Welcome to the Future of Giving"
"Donate Crypto | Get Rewarded"

And then any Giveth design elements that you think would look good :)

**Comment by laurenluz** [comment]
Hey Rodri!

I want it to say both things on one banner... just one banner.

I love the hands with the GIV token backgrounf but i think since twitter will have the profile pic on the left side, it should have the text more in the center :)

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/168633282-29ba4b72-54ea-4aa3-b186-a41c9ab039e5.png)

**Comment by rodricastillo9013** [comment]
perfect! I'll work on it!

**Comment by rodricastillo9013** [comment]
![Twitter header](https://user-images.githubusercontent.com/61791380/168641583-d2afea60-79ab-4fa8-8ed3-8eae102940d7.png)
something like this?

**Comment by laurenluz** [comment]
Oh yeah!!! I'll show it to the twitter specialist and ask for his feedback too 😄  I love it!!

**Comment by rodricastillo9013** [comment]
Nice! thanks :)

**Comment by rodricastillo9013** [comment]
ok, I will wait for your feedback. Thanks

**Comment by laurenluz** [comment]
Hola Rodri! puedes hacer el parte "donate crypto | get rewarded" mas vibrante? como bold o algo asi? tal vez un poquito mas grande?

**Comment by rodricastillo9013** [comment]
<img width="1500" alt="Twitter header" src="https://user-images.githubusercontent.com/61791380/169388948-b725f313-d1ac-4e0b-9ec0-e118d626fce8.png">
what do you think? @laurenluz

**Comment by laurenluz** [comment]
love it! <3
