### ISSUE TITLE
How do we communicate the amount of GIVbacks the user gets?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#676]
It's not just "75%" 

@ahmadabugosh @todd-x-y @danelsuga @Elizardwizzard

**Comment by laurenluz** [comment]
https://docs.google.com/document/d/1jZlg6QqL6E0AChBkK1_eDfdrcSuOKU5o2mBI7KGTB4M/edit

may help!! ^

**Comment by Elizardwizzard** [comment]
https://www.youtube.com/watch?v=w08lE-SOFzg
Hey! Im thinking of doing something like this? wdyt? @laurenluz

**Comment by laurenluz** [comment]
I love this idea @Elizardwizzard !! 

We would need someone to work on a script. Maybe this is something @c0ric0ri might be interested in supporting!

**Comment by c0ric0ri** [comment]
@Elizardwizzard let's connect on this!

**Comment by laurenluz** [comment]
@c0ric0ri here's the GIVbacks documentation: https://docs.giveth.io/giveconomy/givbacks/#getting-givbacks

**Comment by c0ric0ri** [comment]
Haven't gotten to this yet but it's on my radar to start tackling this week!

**Comment by c0ric0ri** [comment]
@Elizardwizzard got back to me so we can connect this week!

**Comment by danelsuga** [comment]
Any solutions on this yet?

**Comment by laurenluz** [comment]
Working on a GIVbacks calculator: https://github.com/Giveth/giveth-dapps-v2/issues/481#issuecomment-1194165207
