### ISSUE TITLE
Send NFT project feedback Typeform using autopilot

### ISSUE THREAD

**Issue by Santigs** [Giveth/giveth-planning#680]
Dear Giveth project creator. 

We are always in search of new ways to generate more funding for Giveth projects. We are considering the implementation of a new feature where:
1.- Artists can donate art to support projects
2.- That art will be turned into NFTs
3.- Collectors can purchase those NFTs via Giveth, and
4.- 100% of funds involved from sales would go to the verified project!

Before moving forward with the development of this feature, we want to know if this is something you & your community of donors would use! Let us know your thoughts by filling out this quick typeform: https://giveth.typeform.com/fundingwithart

Thank you very much for your time and feedback!

**Comment by laurenluz** [comment]
Hey @Cotabe are you able to create an email out of this to send to our projects owners?

**Comment by Cotabe** [comment]
@Santigs I sent it to your email for QA (Quality Assurance). Check it out, if you approve I will send it.

@laurenluz didn't send it to you, because I think you have a lot on your plate. But I can send it anyways if you want.

**Comment by laurenluz** [comment]
Thanks @Cotabe! All good. Next time perhaps just send it. If I don't have time to read it, I won't, but it's good to have the option without the extra coordination :)

**Comment by Cotabe** [comment]
Agreed!

Should we close the issue?
