### ISSUE TITLE
Switch Newsletter to Revue

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#682]

**Comment by ahmadabugosh** [comment]
Hey @laurenluz I added our Newlsetter to Revue:  http://news.giveth.io/

The next steps are:

- [ ] Import our existing list (this is in process, I submitted our list, but I'm waiting for them to verify our account, which may take 24 hours)
- [ ] Edit our bio / design (I added you onto the account so you can do this) 
- [ ] Add our Newsletter to our Twitter page (with the direct integration, so people can subscribe from our Twitter page directly)
- [ ] Change the links in our docs
- [ ] Change the embed form on the homepage

**Comment by laurenluz** [comment]
I tweaked the bio a little, and tried to add it to Twitter. at first it worked but then wouldn't update the bio changes... so I removed it and then readded... but it's still weird, not showing up on our page. Maybe it takes time?

**Comment by laurenluz** [comment]
FYI @ahmadabugosh our Giveth branded colors are in the branding guide here: https://www.figma.com/file/bV3f7aLHK2pIs7tlzLGVgH/Giveth-Branding?node-id=986%3A1453

I changed them for the newsletter

**Comment by laurenluz** [comment]
oh boom it worked 
![image](https://user-images.githubusercontent.com/75490971/170141496-e2131655-39b7-42d0-881a-528cdfb3a499.png)
