### ISSUE TITLE
Newsletter May 2022

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#683]

**Comment by ahmadabugosh** [comment]
For our upcoming May Newsletter, let me know if you have any

1. Projects you'd like to highlight
2. Updates about Giveth / GIVeconomy
3. Community updates / things we want to promote
5. Funny Memes

@laurenluz @danelsuga @Cotabe @WhyldWanderer @scottbenjd @melodysongq @clara-zi  @SymSL 

(I'll bring it up in the next comms call as well)

**Comment by melodysongq** [comment]
I wonder if we can do a "how to" or some basic definition (like, this is what this mean) for the 101 subscribers of the Newsletter.   Let's talk about this in the Connect Call.  Also featuring a team member (contributor) is always a great idea that gives the platform credibility.

**Comment by laurenluz** [comment]
love melody's ideas!

Suggestions for that:
- basic definition: "seed phrase"
- featured contributor: we should ask who would like to be featured.... maybe we start with a long time dev like Mateo... or Marko for design

Other content suggestions:
- Giveth Donor 101 course (if we can get it out)
- Ask for feedback for the NFT integration: https://twitter.com/Givethio/status/1524072516498698244
- THIS WAS EPIC (ETH barelona video) https://twitter.com/Givethio/status/1522589983323959296
- 1hive TV spotlight: https://www.youtube.com/watch?v=OR997P-ktXQ (explained all kinds of things we were up to lately)

If you need more content, maybe this would be good to share too: https://twitter.com/Givethio/status/1521877035358068737

**Comment by laurenluz** [comment]
Also this was our top tweet so far (though I can't find the link to it for some reason)
![image](https://user-images.githubusercontent.com/75490971/168939824-523dc750-5bab-4895-8bf3-c4f89d557d05.png)

**Comment by laurenluz** [comment]
could also mention honeyswap hack & rescue - shilling/supporting partners like 1hive

**Comment by laurenluz** [comment]
Could also share information like:
- number of unique donors
- number of verified projects
- how projects used the funds

Get project testimonials that we can use on social media & elsewhere

**Comment by laurenluz** [comment]
This is also super cool! https://www.decential.io/features/k68j0bp6u49hmuq3heg96o4z6y3ja1

**Comment by melodysongq** [comment]
Here is a write up for feature projects that amplify and help other projects to be successful, please edit and use in other issues if there is already featured projects in this one : https://docs.google.com/document/d/1p76UPJnSlKx4zTJ-qaMKB89sS2RYHSQHoXn_xCCZ8UE/edit

Also love the idea of "seed phrase" looking forward to reading what it means.

**Comment by melodysongq** [comment]
Also suggest you give the Connect WG scheduled deadlines for each newsletter, we are happy to schedule accordingly write ups for feature projects in this "column".

**Comment by laurenluz** [comment]
look great Ahmad! left comments/suggestions

**Comment by laurenluz** [comment]
@ahmadabugosh are we still going to try to put these up in our docs?

**Comment by ahmadabugosh** [comment]
[Made an issue about this ](https://github.com/Giveth/giveth-planning/issues/705)
