### ISSUE TITLE
Gitcoin GR14 prep

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#686]
It's June 8 - 23!

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c9f0a9eb-948b-48a3-8746-90d9ef728655)

We should:
- [ ] update listing for Giveth.io
- [ ] consider removing listing for Giveth TRACE
- [ ] make some memes in support of the grants rounds
- [ ] advertise gitcoin matching pool on Giveth

**Comment by laurenluz** [comment]
Keep an eye on this vote: https://snapshot.org/#/gitcoindao.eth/proposal/0xf8a7f4c5c6f894046555d608d5508ab04ae608670c135b27869c184c3c325236

**Comment by danelsuga** [comment]
The vote has ended and is favor of the following option:

FOR GR14 Structure & FOR New Eligibility

You approve the GR14 structure as is, and are in favour of us removing the "no token" eligibility requirement.

---
I just want to confirm that this means that DAOs/projects WITH tokens may pursue grants?

**Comment by laurenluz** [comment]
yeah it sounds like they mean that DAOs may pursue grants

**Comment by laurenluz** [comment]
ahh, Suga, they voted AGAINST new eligibility... so:

> Option 2: FOR GR14 Structure & AGAINST New Eligibility
> 
> You approve the GR14 structure as is, but are NOT in favour of us removing the “no token” eligibility requirement. If this option prevails, GR14 eligibility will remains as-is.

There is apparently someway we can/should appeal our removal from it. If you could, it would be great to find the application to appeal disqualification.

**Comment by danelsuga** [comment]
Very sorry about that mix up.

**Comment by laurenluz** [comment]
I think we might be ok even if we don't apply for anything. let's just draft updates and send 'er!

**Comment by danelsuga** [comment]
This is prob too much stuff (and super super rough draft) but wanted to hopefully get your eyes on the ideas before the weekend @laurenluz. 
Thank you. 

https://docs.google.com/document/d/15AwNMSuym4_cvGe8n-aUD8GMr3zzrllR30EnxklVrxo/edit

**Comment by laurenluz** [comment]
Hey Suga! I left comments/suggestions. I agree on it being too much stuff :) left my suggestions for things to remove. Otherwsie, I think it's great and if you clean it up a little, we're good to go.

Did you write one for TRACE?

**Comment by laurenluz** [comment]
@danelsuga

**Comment by danelsuga** [comment]
Thanks!! It's super draft-y!

No trace yet. Prob can't get to it over weekend. But no worries. Will do asap.

**Comment by laurenluz** [comment]
awesome!!

**Comment by danelsuga** [comment]
Both grants are updated. Now they need to be included in the upcoming (June 8) active matching round.

For [TRACE](https://gitcoin.co/grants/2154/givethtrace), I added:
"To date, Giveth TRACE has facilitated $2 Million USD of donations for countless for-good projects and has spent $40k USD on gas fees in support of those projects."

[Giveth.io](
https://gitcoin.co/grants/795/givethio-panvala-league) had a few more changes.

**Comment by laurenluz** [comment]
- [ ] discord shill our gitcoin grants @WhyldWanderer @danelsuga to draft
- [ ] send email out to previous gitcoin donors via gitcoin @danelsuga

**Comment by danelsuga** [comment]
previous shill doc (from old issue #396) https://docs.google.com/document/d/1gZFQ8qXBOpPwwn0u78th0_BnwfR-rQT_MnO5CTa4QYM/edit

**Comment by danelsuga** [comment]
I modified @WhyldWanderer's old shill a bit. (Is the Panvala matching still valid?)

Dear donors,

Welcome to Gitcoin GR14! As you know, with Gitcoin’s matching pool, even the smallest donation can make a huge difference for funding open-source projects.

During this round, I want to draw your attention once again to the revolutionary donation platform :Giveth: **Giveth** is a community focused on **Building the Future of Giving** using blockchain technology.

**Giveth.io** is an easy-to-use donation platform that allows anyone to open crypto funding portals by creating for-good projects --with zero fees and where 100% of the donations go directly to the projects. 

Donors can choose from a wide range of for-good projects: feeding homeless people, funding public goods, saving the environment – it’s all on Giveth.io, and when donors donate to verified projects, they get rewarded! You can donate to the Giveth.io grant here: https://gitcoin.co/grants/795/givethio-panvala-league (PAN donations get extra matching.)

**Giveth TRACE** is the OG Giveth Donation Application, built in 2017. It pioneered the first Ethereum bridge, overcoming the scaling and gas issues of the time by bridging Ethereum mainnet to Rinkeby testnet. You can donate to this grant here: https://gitcoin.co/grants/2154/givethtrace 

Thank you for supporting the Future of Giving! Join our Discord server to say hello, see what we’re up to or ask any questions! Subscribe to our “announcements” channel to keep in the loop as we roll out new developments. We have some awesome news to GIV, just around the corner!! :wink: 
https://discord.gg/3FrZh2DE

@laurenluz - some QA for this message? And I'll send on Gitcoin.

**Comment by laurenluz** [comment]
Hey @danelsuga! I think it's way too long and with too many CTAs... I think we didn't have as much experience when it was drafted.

I would try to keep it simple, remove as much fluff as possible. Saying something along the lines of:

> We're excited about gitcoin GR14 and would love your support for Giveth!
> 
> We are Building the Future of Giving, starting with a zero-fee donation platform where for-good projects can raise funds, and donors can actually get directly ewarded for donating. We have two active grants, on for each of our open-source dApps:
> 
> Giveth.io: https://gitcoin.co/grants/795/givethio-panvala-league 
> Giveth TRACE: https://gitcoin.co/grants/2154/givethtrace
> 
> Even a small donation goes a long way in gitcoin grants! And if you donate to us in PAN we'll actually get extra donation matching from Panvala!
> 

Please feel free to fix up/reword, I wrote that in just a few minutes based on your post :)

**Comment by danelsuga** [comment]
Ok, thanks!

We can just use your update since it's simple and straight forward.

**Comment by laurenluz** [comment]
sounds good, maybe just fix up my grammar/spelling a bit

**Comment by danelsuga** [comment]
Dear donor,

We're excited about Gitcoin GR14 and would love your support again for Giveth!

We are Building the Future of Giving, starting with a zero-fee donation platform where for-good projects can raise funds, and donors can actually get directly rewarded for donating. We have two active grants, one for each of our open-source dApps:

Giveth.io: https://gitcoin.co/grants/795/givethio-panvala-league
Giveth TRACE: https://gitcoin.co/grants/2154/givethtrace

Even a small donation goes a long way with Gitcoin grants! Plus, if you donate to Giveth in PAN, we'll actually get extra donation matching from Panvala!

——

To be clear: this is the message for previous donors? Also, super rookie question:  the heck do I send it? I was looking all over Gitcoin, and I cannot find what I thought was going to be some messenger where I could communicate to previous donors. Please help! @WhyldWanderer @laurenluz

**Comment by danelsuga** [comment]
@divine-comedian

**Comment by danelsuga** [comment]
So far I haven't been able to connect previous donors. @WhyldWanderer  proposes that it's not possible during the grant rounds. Would you know @Danibelle how to contact previous donors on the Gitcoin platform? Seems there should be a DM feature? I can't find it. Any further support on this @divine-comedian ? Thanks, gang.

**Comment by divine-comedian** [comment]
This is it here, no?
![image](https://user-images.githubusercontent.com/67759413/173429874-3015d326-c282-481e-8e0b-861a359345cc.png)
https://gitcoin.co/grants/795/givethio-panvala-league

click the check box next to `Email grant funders` to send an email to previous gitcoin donors to Giveth.

**Comment by danelsuga** [comment]
Nice! Thanks! I'll check it out!

**Comment by danelsuga** [comment]
done.
