### ISSUE TITLE
Modify Twitter Banner for Facebook & LinkedIn

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#689]
@rodricastillo9013 

me puede ayudar a cambiar el tamano de este:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ce96a5ea-6c7c-45ed-8894-cf35b655d654)

para que funciona bien por el banner de facebook & linkedin?

**Comment by rodricastillo9013** [comment]
yes, of course :)

**Comment by rodricastillo9013** [comment]
<img width="1584" alt="Linkedin" src="https://user-images.githubusercontent.com/61791380/170267305-7d3a73db-b965-4c89-a914-c27353bb5253.png">
<img width="820" alt="Facebook" src="https://user-images.githubusercontent.com/61791380/170267323-ba718d88-46ce-4249-96a1-f8944e70f8cb.png">
Done! @laurenluz

**Comment by rodricastillo9013** [comment]
<img width="1584" alt="Linkedin" src="https://user-images.githubusercontent.com/61791380/170267644-5c10f849-e852-4ba3-9c11-6c4709ab9adc.png">

Linkedin

**Comment by laurenluz** [comment]
@WhyldWanderer to update linkedin

**Comment by WhyldWanderer** [comment]
Oops @rodricastillo9013 

The linkedin one is off - it gets cut off on the top and bottom:
![image](https://user-images.githubusercontent.com/74267818/172673496-c7dc4232-c0f4-4d06-9ed2-1721a134fe07.png)

It says that 1128 x 191px is recommended.

**Comment by rodricastillo9013** [comment]
ok i fix this! thanks @WhyldWanderer

**Comment by rodricastillo9013** [comment]
No! I have forgotten this, I will do it as soon as possible

**Comment by WhyldWanderer** [comment]
Done!
