### ISSUE TITLE
Tokenlog - how to use

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#691]

**Comment by clara-zi** [comment]
"It would be really cool to use github for submitting projects and Tokenlog with the GIV token for prioritizing them adds utility to GIV tokens" @GriffGreen

**Comment by clara-zi** [comment]
@Cotabe I think this functionality is also covered in Dework from your demo yesterday - being able to vote on the priority of projects/tasks.
@WhyldWanderer

**Comment by clara-zi** [comment]
@rainerhoell identifies support for project and prioritises...useful for what you're working on? wdyt?

**Comment by Cotabe** [comment]
Hey @clara-zi thanks for bringing this up. Here is a forum proposing using Dework to submit project/ideas and upvote them. https://forum.giveth.io/t/should-we-pilot-using-dework/648

The positive: the platform has community suggestions and a bounties dashboard. Having both things in one place could help builders grab ideas from community suggestions even before they are passed to the bounties dashboard.

The negative: Upvoting is not token weighted, so doesn't provides an extra utility for GIV.

Please vote and give feedback on the forum proposal https://forum.giveth.io/t/should-we-pilot-using-dework/648

Also reach out if there are any questions. I'm willing to do the heavy lifting to get this rolling.

**Comment by laurenluz** [comment]
tokenlog is being setup in #703 - can we close this issue?

**Comment by laurenluz** [comment]
I'm going to close this issue, since we're moving forward with tokenlog & discussion in #703

**Comment by clara-zi** [comment]
Yeh. Thanks. I saw that myself and have been meaning to close.
