### ISSUE TITLE
Outreach to networks related to our niche(s); also see #687 #622

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#695]
Grassroots Foundation
Guerilla Foundation
Streetfootballworld Network
Ecovillage Networks
Kiva (Microloans)
Elinor Network
Edge Funders

**Comment by rainerhoell** [comment]
Reached out to all of them except Kiva.

**Comment by laurenluz** [comment]
context from comms calls:
- some are donor platforms supporting community based donor groups
- some specialized projects groups

**Comment by ahmadabugosh** [comment]
Can someone also reach out to 

1. [Effective Altruism ](https://www.effectivealtruism.org/)
2. [Giving What We Can ](https://www.effectivecrypto.org/)
3. [Effective Crypto ](https://www.effectivecrypto.org/)

I think they'd be great groups to partner with

**Comment by melodysongq** [comment]
I would prefer to have these "prospective projects" to be tracked in a database instead of an issue.   So recommend we close the issue but capture these project nominations and will assign them a category in the database.

**Comment by clara-zi** [comment]
I've created a Google sheets to track this outreach pending database/pipeline system up and running. WDYT?

https://docs.google.com/spreadsheets/d/1JZvVn7zCY3E-d0lHGX_Dbt_oO05ed3moz6Lr5GpWrg0/edit?usp=sharing.

Suggest we move all the updates here until new process is ready?
If in agreement, I can close this issue.

**Comment by melodysongq** [comment]
The link takes me to a Giveth Gap analysis... for some reason. Maybe a wrong link? Thanks.

**Comment by clara-zi** [comment]
> The link takes me to a Giveth Gap analysis... for some reason. Maybe a wrong link? Thanks.

Oh no! Try now. Link above updated. Sorry, folks.

**Comment by SnakeGH** [comment]
@c0ric0ri the only project I see in Hubspot is "Giving What We Can," which I have been in contact with Luke, but I can't confirm for the rest unfortunately :(

**Comment by c0ric0ri** [comment]
ok @clara-zi I will move this to Done and plan to close it by the end of the week. In the meantime could you please ensure these accounts are in hubspot?

**Comment by clara-zi** [comment]
@SnakeGH @rainerhoell are these accounts and progress in HubSpot?

**Comment by c0ric0ri** [comment]
@clara-zi no they are not, as per Jake's comment above the only project seen in Hubspot is "Giving What We Can".

Are you willing to take over transfer of these lists into accounts in Hubspot?

I'm planing to close this issue this week either way.

**Comment by clara-zi** [comment]
@c0ric0ri handing over to @rainerhoell who had connection with these projects previously and reached out to them on behalf of Giveth. I can complete HubSpot (or @SnakeGH can), if @rainerhoell you can send us the info. Thanks

**Comment by SnakeGH** [comment]
@clara-zi i have no problem adding it to hubspot for sure, but like you said, I'll need all the information and past communications and then I'll simply ask whoever is running with the orgs / contacts to post the updated (future) comms into hubspot. :)

**Comment by c0ric0ri** [comment]
@SnakeGH @rainerhoell @clara-zi triple checking, am I good to close this? Are these names in Hubspot now?
