### ISSUE TITLE
Giveth Website Marketing Suggestions

### ISSUE THREAD

**Issue by SymSL** [Giveth/giveth-planning#698]
Hello!

This issue is for idea sharing on how to improve the Giveth website to make sure that when people land there, they either

- Successfully become a donor
- Successfully create a project
- Join our community
- Other (feel free to add)

Here is a Doc with a few UX suggestions so far, please add more/comment. Once we have a final list of changes we can submit the changes :) https://docs.google.com/presentation/d/17HYGsHhqi95SQbbh0L1rcdmQ3iKFK9yeXuryL0mwR9s/edit#slide=id.g12eca2b4b5c_0_0

There is also a discussion on website analytics we need on the site so we can better understand where most users come from, and their main drop off points, this is being investigated by @ahmadabugosh and we have some nice options already.

@laurenluz @WhyldWanderer

**Comment by laurenluz** [comment]
Hey @SymSL!! Awesome issues... I think many of them can be created already for the devs, I left comments on which, as well as who to tag for additional advice/comments in those issues.

Some others I think we can discuss a bit more in the doc before sending them to the devs :)

**Comment by laurenluz** [comment]
@danelsuga if you could continue this on and do a nice audit of the website to see if we're hitting our different audiences well

**Comment by danelsuga** [comment]
I've submitted several, very small error issues to devs. And I've submitted several UX issues to @SymSL's slideshow, pasted here again: https://docs.google.com/presentation/d/17HYGsHhqi95SQbbh0L1rcdmQ3iKFK9yeXuryL0mwR9s/edit#slide=id.g12eca2b4b5c_0_0

**Comment by danelsuga** [comment]
What's our next step on this @SymSL @laurenluz ?

**Comment by laurenluz** [comment]
did you get a chance to walk through the dapp while considering the different audiences? If you feel like the content is easily understood/accessible for 101, 201  & 301 level audiences, I think we're good :)

**Comment by SymSL** [comment]
Hey Suga and Lauren, great additional comments on this - The next step is putting these on the Giveth Planning Board on github for the devs to implement: https://github.com/Giveth/giveth-dapps-v2/issues

**Comment by danelsuga** [comment]
@SymSL how shall we parse out the different issues? Do you want to go through your doc and pull all of them out one by one? Or should I do the ones I added myself?

As for the audit, I'm going to walk through the website again.

**Comment by SymSL** [comment]
Hey @danelsuga I'll spend time on this tonight and add the ones I can. If you'd be able to add yours that will be great. With some of the ones I mentioned, there were decisions to make on the exact flow or placement of assets but I'll brief them in and we can discuss with the rest of the team from there.

**Comment by SymSL** [comment]
Hello, I've opened up some tasks for the dev team, please share any suggestions you may have on them:
These cover issues on slides 1, 3, 4, 5 so far

Slide 1, Button text changes: https://github.com/Giveth/giveth-dapps-v2/issues/1058
Slide 3: Delaying the "Wallet Connection" Request: https://github.com/Giveth/giveth-dapps-v2/issues/1059
Slide 4: Adding the Report an issue/ Ask a question icons on to the project creation page & the donation page (same issue as above)
Slide 5: Adding the newsletter sign up pop up: https://github.com/Giveth/giveth-dapps-v2/issues/1060

**Comment by danelsuga** [comment]
I've also opened up issues:
1063
1064
1065
For slides 6, 7, and 8 respectively. 

I'm unable to assign anyone to them however.

**Comment by danelsuga** [comment]
I'm closing this, as I think the various issues have been tackled through the devs' repo now.
