### ISSUE TITLE
Move Donor Course Quiz to Google Forms

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#699]

**Comment by ahmadabugosh** [comment]
Hey @laurenluz @danelsuga @WhyldWanderer, we're still getting spam POAP farmers filling the typeform (even after moving it to another account and adding a captcha, which I changed multiple time, they must have some kind of script)! 

I moved the quiz over to Google forms instead, which although it's not as flashy, it's free, has built-in spam protection and doesn't have a response limit. I also added a question asking people if they want to subscribe to our newsletter :) 

Let me know what you think and if you're fine with it, please replace the other quiz links we have: https://forms.gle/uLC71Ljk3EJyAJG4A

**Comment by danelsuga** [comment]
Oh no! 😭 Terrible but well done.

**Comment by danelsuga** [comment]
Fixed two quiz links on Medium article.

**Comment by laurenluz** [comment]
Looks good, thanks @ahmadabugosh & @danelsuga
