### ISSUE TITLE
Giveth Garden using 1Hive+Karma DAO design pattern

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-planning#70]
Following the [hacker kit](https://github.com/1hive/hacker-kit) we'd need to solve the following issues 

1. Deploy components as showed in the [1Hive Honey Template](https://github.com/1Hive/honey-template/) which forks from [Karma Template](https://github.com/lkngtn/karma-template) for their HNY token

- [ ] Conviction Voting
- [ ] Hooked Token Manager
- [ ] Dandelion Voting
- [ ] Tollgate
- [ ]  Issuance OR Marketplace (According to [the Gardens overview](https://forum.1hive.org/t/gardens-overview/32) it is recommended to use the Marketplace or Issuance app, but not both. Having two continuous issuance policies can easily lead to unintuitive results, potentially even recursive feedback loops.)

2. Deploy Giveth subgraph on [The Graph](https://thegraph.com/explorer/subgraph/1hive/aragon-xdai) as it is a dependency for the conviction and dandelion voting apps.
 
3. Build the Aragon connect frontend for our GIV token, [forking](https://github.com/Giveth/garden-interface) from 1Hive's [honey pot template](https://github.com/1Hive/honey-pot)

**Comment by ForestSoleil** [comment]
Process to get fundraising? --> Create a proposal to the 1Hive DAO. Beforehand want to chat with their community around it. We should have support from their team & members. Their team interested in supporting us with Honey for this process.

**Comment by ForestSoleil** [comment]
**GIVgardens**
Update as of July 2nd:
- Need to redeploy to use the new token contract (Gabi)
- Rinkeby testing (not immediate priority)
- Educate people on how to use it - adapt 1Hive docs (not immediate priority)

**Comment by 0xGabi** [comment]
We already did the deployment of the new token contract and template. 

Should I go ahead and create another Garden with the same Rinkeby setting that the last one has?

**Comment by ForestSoleil** [comment]
^ @GriffGreen @laurenluz @WhyldWanderer

**Comment by WhyldWanderer** [comment]
Hey @0xGabi ... I checked with Griff and he said Yes! We would love a Rinkeby Garden with the new token contract and template.
Please go ahead and create the Garden on Rinkeby with the same setting that the last one had.

Thanks so much Gabi for all of your work and collaboration efforts!

**Comment by 0xGabi** [comment]
This is done 👍
