### ISSUE TITLE
Fix pinned messages on Giveth Medium

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#701]
The pinned messages on Giveth's Medium are ancient history and are likely blocking readers from seeing the latest news (which, weirdly, is always at the bottom unless pinned).

Could I please have Medium access so I can fix that? Or could you just fix it @laurenluz ? Might be better if you let me take it off your plate however.

**Comment by ahmadabugosh** [comment]
Yes, I agree! Also, I think we should revisit the categories we have, and clean up the Medium a bit. @SymSL are you still up to take on [that issue](https://github.com/Giveth/giveth-planning/issues/460)?

**Comment by laurenluz** [comment]
Hey @danelsuga! I updated the Medium - thanks for the reminder, I neglected it for a bit too long. I try to keep the posts at the top like "most relevant to the Giveth overall mission" and then have other key articles down on the page as well.

Anyway, happy to discuss a little more & give you access if you want to maintain it.

+1 on revisitng the categories

**Comment by danelsuga** [comment]
Yay! Thanks @laurenluz !
