### ISSUE TITLE
Allow GIV holders to vote on which projects we help onboarding - tokenlog & typeform

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#703]
The purpose of this issue to create a means for GIV token holders to vote on which projects we actively help onboard. The steps:
- [x] setup tokenlog for voting
- [x] setup typeform for people to nominate projects (will create github issues automatically)
- [ ] get people to vote!

I will investigate what's required for tokenlog.
@WhyldWanderer can help setup that typeform to create github issues.

@ahmadabugosh @rainerhoell @Cotabe tagging you to keep in the loop!

**Comment by Cotabe** [comment]
Just tried out a few Tokenlogs of other teams. There is a button to create a new issue directly on Github, but the issue is not reflected immediately on Tokenlog, I'm not sure if it's configured that way or what's happening. 

Therefore even if we use a typeform as a different UX/UI than using the tokenlog interface and go straight to Github. I would like to know if those issues will immediately be created on our Tokenlog :)

**Comment by WhyldWanderer** [comment]
I'm ready to start the typeform part of this...

I would love to have some clearer information or drafts of questions that we want on this form..
@rainerhoell .. do you have any questions in mind for this typeform? What is the information we are asking people to provide about their nominations?

I imagine our repo will end up looking something like this: https://github.com/commons-stack/commonsprize/issues
If you click on the issues, you can see all of the submissions. I imagine we can follow in CS's footsteps for a lot of this.

**Comment by laurenluz** [comment]
We used gGIV as the voting token. So people need to stake their GIV to vote :)

**Comment by rainerhoell** [comment]
> I'm ready to start the typeform part of this...
> I would love to have some clearer information or drafts of questions that we want on this form.. @rainerhoell .. do you have any questions in mind for this typeform? What is the information we are asking people to provide about their nominations?
> I imagine our repo will end up looking something like this: https://github.com/commons-stack/commonsprize/issues If you click on the issues, you can see all of the submissions. I imagine we can follow in CS's footsteps for a lot of this.

Thanks for the links. Commons Prize are self-nominations, so nominators have a lot of information on the projects (and motivation to provide it). As we are asking donors/GIV holders (and as we don't intend to run this as a full-blown award process), I would keep it a lot more simple. If donors are really keen to see the project on the platform, they will write more. If not or if they have very little time, it's at least important to get the name and contact information.

A draft:
1) Which project should absolutely be on Giveth?
2) The project's Twitter/Discord/Website/Email?
3) Who are you (Discord/Twitter/Email)?
3) Optional: How would you describe the project in one sentence?
4) Optional: Why are you convinced by this project?
6) Optional: More information: Which public good does the project provide/support? Who is involved? Etc.

**Comment by rainerhoell** [comment]
@WhyldWanderer Thanks, I looked through the typeform. Looks great!
Three ideas:
* After the last questions we could add a checkbox: "Are you affiliated with the projects? (Not a problem, just helpful for our followup.)"
* After that another one: "Do you own GIV tokens?"
* A message at the end could say: "Thank you very much for your nomination! Please note: If you hold GIV tokens, you can vote to prioritize nominations [here]."

**Comment by ahmadabugosh** [comment]
<img width="1089" alt="Screen Shot 2022-06-11 at 2 10 40 AM" src="https://user-images.githubusercontent.com/4855928/173157232-bcab750b-2a23-434c-9a76-55850615d118.png">

Minor thing, but I think we should add some text on the title screen (now it's blank). Maybe something like 

**Nominate a Project to List on Giveth!** 
Doing so will add this project to our Token Log Page (_add the link once it's ready_) for GIV holders to vote on (the projects with the most votes will get priority)

**Comment by laurenluz** [comment]
@melodysongq @rainerhoell @clara-zi would great to have you review this~

**Comment by laurenluz** [comment]
@WhyldWanderer can we update this title page to give more context?

Something like: 

**Nominate a Project & We'll help them get on Giveth!**
Want to donate to a project that's not Giveth? We want to help them onboard!
1. Nominate your favourite projects via this form.
2. GIV holders will be able to vote on their top choices via Tokenlog(link).
3. Our team will reach out to and support the community's top choices!

![image](https://user-images.githubusercontent.com/75490971/173716248-6bafefd6-9746-405b-baa1-bc22d6c700fa.png)

**Comment by melodysongq** [comment]
@laurenluz I think this is a great scalable solution.  However, originally I was thinking of a less formal approach like a Discord channel where people can suggest projects and start open dialogues more casually.  It worked really well in PopcornDAO, where you can also observe people's conversation about their motivation to give and why they like to give for the project they suggested.   At the same time, there is more reason for people to participate in the community dialogue.   That said, the Type Form is definitely more scalable and I do like how it's structured now.  I am thinking  it also probably does not hurt to do both?  Have a social impact zone on the channel so that the community can talk in a "safe" space about their idea on social impact will help Giveth get insights?

**Comment by melodysongq** [comment]
Anther thought is that if a community member suggest a project that really fit the criteria for being an excellent project on Giveth,  should we just reach out?  Does it need a top vote?  In other words, are we gathering data on projects ideas not from a governance point of view here?   I am interested to hear what you think @rainerhoell and @clara-zi

**Comment by clara-zi** [comment]
The new Discord server migration is complete and there is now a channel in the Giver Space where givers/donors can have these kinds of chats. I will start a discussion. There is also a project-activity channel in the Giver Space to help donors stay up-to-date on what their favourite projects are doing.

**Comment by laurenluz** [comment]
Yep all sounds good. We can definitely also use the discord channel.

The nice thing about the tokenlog is that it gives extra ultility to the GIV token. 

We don't need to limit ourselves to *only* reaching out to the projects suggested via tokenlog but the process of voting might encourage more community pariticpation.

So! What are next steps? Is this ready to share out via Twitter? @WhyldWanderer

**Comment by WhyldWanderer** [comment]
I implemented the changes that you suggested for the form wording. 
I think things are good to go! Thanks @laurenluz
