### ISSUE TITLE
DAO of the week for Gnosis Chain newsletter

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#704]
DAOhaus has been tasked with providing a DAO of the Week for the gnosis chain newsletter & they want to feature Giveth! It’s a quick 100 words, so very succinct. We should try to convey what is most important to Giveth and also note where Gnosis and DAOhaus is used.

We use gardens & aragon on gnosis chain, we facilitate donations on gnosis chain... incentivize GIV staking on gnosis for voting in the garden... we will soon have GIVpower on gnosis chain (could tease about this).

We have a couple of weeks to get this out, and can coordinate with their team a bit to finalize a draft.

@c0ric0ri I think this might be a great issue for you. Are you down?

**Comment by c0ric0ri** [comment]
@laurenluz and I had a call with Gnosis last week, and a follow up call was scheduled - right @laurenluz?

**Comment by laurenluz** [comment]
not scheduled yet! I'll ping Christina to schedule something :)

**Comment by laurenluz** [comment]
Christina is going to send me a draft for review this weekend

**Comment by laurenluz** [comment]
https://gnosischain.substack.com/p/-gnosis-chain-weekly-01-july-2022
