### ISSUE TITLE
Include "Working with giveth as an external collaborator" in the documentation

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#706]
The draft is here https://docs.google.com/document/d/13f2VYF3ikKv36fqLFJA-YfpZUf2UJL7J-TNm9E2uGjU/edit

It has been reviewed by Ashley, Lauren and MoeNick.

The tone is laid back in general.

There are a few things that are in there that have not yet been implemented like the builders discord channel and the Dework dashboard. I think both of these things will be piloted soon, so IMO it makes sense to keep it already like this, but always open for suggestions.

**Comment by Cotabe** [comment]
@danelsuga always helpful to have your input.

**Comment by danelsuga** [comment]
Gave it a pass!
Great work, @Cotabe.

**Comment by laurenluz** [comment]
I think the next step here might be to actually upload this to docs @Cotabe. Once you review/accept changes, find a place you think it would fit and then tag Mitch to get it up there.

**Comment by WhyldWanderer** [comment]
Discord is updated @Cotabe! 
Have the new links been added?

**Comment by c0ric0ri** [comment]
@Cotabe please update this issue and close it, thank you!

**Comment by Cotabe** [comment]
@divine-comedian 

Can you help me add to Giveth documentation/ Guides the doc of working with Giveth as an external contributor https://docs.google.com/document/d/13f2VYF3ikKv36fqLFJA-YfpZUf2UJL7J-TNm9E2uGjU/edit

I know it´s not the focus now, but to close that issue that was pending.

**Comment by divine-comedian** [comment]
should be live in a few minutes - I made some small styling changes in markdown so it looks more attractive on the page

**Comment by oyealmond** [comment]
hey @Cotabe ! can we close this issue?

**Comment by oyealmond** [comment]
@franculio ami, podemos cerrar esto?

**Comment by franculio** [comment]
@oyealmond Sí amix. This was done, but it will probably need updating when I re-organize the docs. Closing for now, I'll create a new issue when is needed.
