### ISSUE TITLE
Email Autopilot list to subscribe on Revue / check spam

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#708]

**Comment by ahmadabugosh** [comment]
Hey @laurenluz @danelsuga lmk what you think of this email (for people to check their spam and resubscribe on the new email platform): https://docs.google.com/document/d/1Ki5ysVeSMA0WmonAmU2VYe6unZrS1F7309832mH0_9c/edit#

**Comment by danelsuga** [comment]
I dig it.

**Comment by ahmadabugosh** [comment]
Sent!

**Comment by laurenluz** [comment]
I saw it! super cute
