### ISSUE TITLE
Active Facebook & LinkedIn

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#710]

**Comment by clara-zi** [comment]
@laurenluz parking this here to start discussion.

**Comment by laurenluz** [comment]
DM me your email for lastpass if that sounds good!

**Comment by laurenluz** [comment]
sent you access

**Comment by clara-zi** [comment]
Thanks.
Well this is interesting - this password gave me access to a different giveth.io account, which doesn't have a lot going on:
https://www.facebook.com/profile.php?id=100079316710151

This appears to be the live one: https://www.facebook.com/givethio

Mysteriouser and mysteriouser. MMmm!

**Comment by laurenluz** [comment]
Hey @clara-zi! I just had a call w/ @c0ric0ri and we discussed activating our facebook a bit more. The ideas:
- Tailor facebook to the 101 level nonprofit audience
- Cori to make some suggestions to "about us" and banner & create some regular content
- Would love support from Claire to get this content & our page in front of more key audiences throughout facebook

I would love it if the two of you could coordinate and work together on the best way to make our facebook and effect piece of social media.

**Comment by ahmadabugosh** [comment]
I would also suggest posting on groups as well (since groups are more active on facebook), which I think could work if we do it in a non-spammy way (providing value to them). For example, we can start with 1) Charity / Donations groups (effective altruism etc) or 2) Location specific grassroots groups (on the ground causes, volunteer groups), and start engaging with them (either getting them to list their projects on giveth or donate to existing projects).

**Comment by c0ric0ri** [comment]
100% @ahmadabugosh this needs to happen as part of our outreach strategy as soon as we have our page updates, thanks for outlining

**Comment by clara-zi** [comment]
I totally agree @ahmadabugosh - I have done this kind of outreach before for our charity and it has been successful with carefully curated content. 

We could even consider a FB group for beginner level crypto philanthropy at some point in the future: could be good for engagement, generating curiosity and 101-level education, promoting awareness and funnelling interested members to our Discord. 

I would love to work with @c0ric0ri (if that would be ok with you, Cori?). Thanks for suggesting @laurenluz

**Comment by c0ric0ri** [comment]
Yes let's do it @clara-zi !

**Comment by c0ric0ri** [comment]
@clara-zi and I are setting up a call for later this week, after call with Sym

**Comment by clara-zi** [comment]
https://docs.google.com/document/d/1tULJI-K9qlf8FrwkkEnwmHkZbfiM-TFmWTapQgcY6MM/edit

**Comment by clara-zi** [comment]
1. Auto-posting content from Planable for FaceBook and LinkedIn is live.

3. Some agreement on hashtags for both platforms is needed. Here are my suggestions:
Facebook: #futureofgiving #cryptophilanthropy #cryptogiving (these hashtags are active and group mostly related and relevant content)
LinkedIn: #cryptophilanthropy #cryptogiving #cryptodonors #futureofgiving #giveth (so that we can group our own content)

**Comment by clara-zi** [comment]
**Planning of content** for LinkedIn and FaceBook is now underway for Sep. with draft posts to be finalised and ready for review by the mid-Aug to allow for edits etc. If this approach works well, content planning will begin a month in advance with drafts finalised by the 15th of the prior month.

**Categories** in Planable: I have started creating categories in Planable, such as 'newsletter', 'project highlight'. These can be applied to each post to assist with visual planning.

**Comment by clara-zi** [comment]
Now live with Planable scheduling app. Closing this issue.
