### ISSUE TITLE
Featured Projects Tweet Thread

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#713]

**Comment by NikolaCreatrix** [comment]
Yes! Thank you again, I'm excited for this one! Happy to get inspired from previous posts ;)

**Comment by laurenluz** [comment]
Thanks for taking this on @NikolaCreatrix !

Here are some examples:

https://twitter.com/Givethio/status/1484178959797424130

https://twitter.com/Givethio/status/1486364927816343556

https://twitter.com/Givethio/status/1491411523796824066

**Comment by NikolaCreatrix** [comment]
Love it! Great inspiration, thanks @laurenluz ! So I would love to create the best consistency and flow. And I have several questions.:)

Do we want to create separate threads? 
We can continue this format - 4 new verified projects every 2 weeks, right?
And then freshly listed and/or updated projects would get their separate post? And if so - shall we do once a week or 2 weeks?

When is the next round announcement coming out?  Tmrw?? Today??

**Comment by laurenluz** [comment]
I think it's kind of up to you how you want to swing it...

We could do one per week and alternate:
- one week we post newly verified projects (right when a new GIVbacks round begins)
- next week (mid-round) we post recently updated projects?

I think focusing the attention on verified projects is great because this extra publicity could be like an extra incentive to get verified, but I'm open to having the mid-round post be a mix of what you think is best. (@WhyldWanderer wdyt?)

Let's start this first one with an announcement of newly verified projects on Monday or Tuesday of next week. So if you could have a draft by Friday, it would be great!

**Comment by NikolaCreatrix** [comment]
I like this alternating! Thanks for your support - I will have my draft ready by tmrw (Friday) latest.

**Comment by NikolaCreatrix** [comment]
[https://docs.google.com/document/d/1EjH2j3HQqDbkqGUK_LOmEF661ebD8Tq_Hkh9d_uQ-yA/edit?usp=sharing](url)

@laurenluz cc: @WhyldWanderer 


Draft for Mon/Tue Verified projects tweet

**Comment by laurenluz** [comment]
Hey @NikolaCreatrix! Looks good!! Just a few suggestions:
- Can you add some tweet-appropriate emojis to the start of each project tweet?
- Replace all "and"s with "&"s
- No hastags, because twitter algorithm doesn't like them
- Find the official twitter page for each of the orgs, and include it in the tweet. For example "@artxvnft" is one
- No titles/bold text on tweets :) you can just start the sentence like "Play4change DAO is a ...."
- Would be great to have like.. one sentence describing them, and then the next sentence saying "Donate to help them..." I made a suggestion on the one for play4change

Tag me when it's ready for another review! Great work!

**Comment by NikolaCreatrix** [comment]
@laurenluz how about this? :) Thanks for great feedback.

🎉In GIVbacks round 13 we verified 4 stunning projects raising funds to change the world!🌎

💝 Give to verified projects & get GIVbacks!

✨ Are you ready to see the stars of the last round?
 🔍 Let’s shine some light on them! 

1/ 

🕹️ [@play4changedao](https://twitter.com/play4changedao?s=20&t=uN5cSmZxvIvBVnRrCjiTjg)’s purpose is to genere financial inclusion, educational empowerment & social transformation by leveraging web3 tools.

Donate to help build a future where opportunities are not limited by our place of birth, family connections or appearance. 
https://giveth.io/project/play4change-dao
2/


👨‍🎓 Learning with Innovative Technology Hubs, a project under [@40acresdao](https://twitter.com/40acresdao?s=20&t=SC1JssGyFPcZqbkZHR4KMA) Uhuru Force, is an internet native community with focus on educating, engaging & empowering historically excluded communities.

Donate to help provide free resources & assistance to those in need.
https://giveth.io/project/learning-with-innovative-technology-hubs
3/


🎨 [@artxvnft](https://twitter.com/artxvnft?s=20&t=1N7c34eHEEvBvPL2KCp2Dg) is the 1st NFT collective for neurodivergent artists that gives underrepresented & marginalized artists the exposure, financial independence & recognition they deserve through selling their work as NFTs, which they were previously denied by the traditional art world. 

Donate to help build an unity of neurodivergent artists, art lovers & allies.
https://giveth.io/project/artxv-supporting-neurodivergent-artists

4/

🎟️ [Dandelion](https://dandelion.earth/) is an open-source platform for ticketed events & co-created gatherings created by the not-for-profit worker co-operative Dandelion Collective. 

Donate to support this platform & participate in co-creating heathier future with more meaningful gatherings. https://giveth.io/project/dandelion

**Comment by laurenluz** [comment]
Hey @NikolaCreatrix! this is great. Thanks so much.

Next time, it's better if you make the changes in the google doc and then just comment here saying to check it again so I can leave comments :)

**Comment by laurenluz** [comment]
@NikolaCreatrix several of the tweets were actually way too long for twitter. The max is 280 characters.

Next time around, can you please copy/paste them into a tweet and make sure it's not over the character limit first? 

Otherwise, it's great. Let's do another one!! I'll make an issue.

This was posted today: https://twitter.com/Givethio/status/1539272200246775815
