### ISSUE TITLE
Create Twitter Dev credentials and provide them to dev team

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-planning#714]
We need some twitter dev credentials that should be provided to @mohammadranjbarz 
https://developer.twitter.com/en/docs/authentication/oauth-2-0

Not sure who has access, would be great to use the official profile for production.

Whoever sets it up will need to be provided all these values:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/317685/172663389-71098512-a9a0-4909-8a44-1afa5be35d40.png">

**Comment by MoeNick** [comment]
@mohammadranjbarz would u pls provide the information for this form?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz would u pls provide the information for this form?

@geleeroyale 
I think we should have two applications for **staging** and **production** ENVs and just callback URL is important for me , feel free to fill other fields yourself
Callback URL  :
* **Staging** : https://serve.giveth.io/socialProfiles/callback/twitter
* **Production** https://serve.giveth.io/socialProfiles/callback/twitter
