### ISSUE TITLE
Update giveth history

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#715]
@danelsuga wrote some great content in the original #574 that I think we should add to Giveth's history in the docs: https://docs.giveth.io/whatisgiveth/history/

@WhyldWanderer also suggested we add some spicy memes to jazz it up!

I think it's worthwhile going through Giveth history and making it a little cooler, more fun to read, more in depth.

**Comment by danelsuga** [comment]
Yeah!!

**Comment by oyealmond** [comment]
hey @franculio! sorry to tag you again, but this is something you'll be willing to do?

**Comment by oyealmond** [comment]
@laurenluz hey hey does this makes sense to move it to notion, or does this issue needs to be updated to?

**Comment by laurenluz** [comment]
yeah maybe we can keep it. it's a nice issue although not really high priority.
