### ISSUE TITLE
Write updates for Giveth project & Giveth maching pool project

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#716]

**Comment by c0ric0ri** [comment]
@laurenluz I actually do not know where to start with this. Is there more context?

**Comment by laurenluz** [comment]
Right! So on the Giveth dApp you can add updates to projects, and we want to set an example with regular updates to our own projects.

The Giveth Project: https://giveth.io/project/the-giveth-community-of-makers
The Giveth Matching Pool: https://giveth.io/project/Giveth-Matching-Pool-0

It's been a while since our last update, and we should make a new one. This issue is to make a draft for a new update.

For the Matching Pool, I suggest to draft something simple based on how the conversation has developmed in the Giveth forum. https://forum.giveth.io/t/givmatching-idea-generation-on-how-to-distribute-funds/346

For the Giveth project, I would check out the last newsletters for anything major that is relevant to giveth development/products... but probably would just summarize the content from this tweet: https://twitter.com/Givethio/status/1507391007180132360 

I would also link that tweet in the update post.

Lmk if you have any other questions.

**Comment by laurenluz** [comment]
I just created 2 updates in the giveth project: https://giveth.io/project/the-giveth-community-of-makers

And one for the matching pool: https://giveth.io/project/donation-eth

@c0ric0ri please try to keep track of your assigned issues, there wasn't much communication on this one.
