### ISSUE TITLE
Remove/rename "Consume" list on giveth.io/join

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#717]
The word "Consume" heads the list of reading engagement tools on the Giveth join page (giveth.io/join). I think this word needs to be removed. For one, from an economics standpoint, it has terrible connotations that, I believe, are directly in conflict with the MVV of Giveth. For two, it doesn't really make sense. For three...

I alerted Mateo to it recently, who said he would remove it or replace it, so I wanted to confirm that here. @laurenluz 
![consume.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/ffa4b3d9-27cf-434f-8959-5afd4bfc023c)

**Comment by c0ric0ri** [comment]
@laurenluz @danelsuga I like Learn or Connect. Was a decision already been made here?

**Comment by laurenluz** [comment]
Learn & Connect are both good! I'm partial to Connect, but I think @danelsuga you just pick your favourite and then make an issue in the v2 repo. You can assign Mateo & tag MoeNick

**Comment by danelsuga** [comment]
Ok. Connect seemed vaguely confusing as we have a Connect WG? Maybe that's out in left field. Also, engaging in one-way media (reading, watching) is not really connecting. Maybe it is. I don't know. :P I think the idea of connect is better for referring to Discord and other two-way media.

**Comment by laurenluz** [comment]
Sounds good! If you're done w/ this issue now, go ahead & close it. I think I saw the dev issue was already created.
