### ISSUE TITLE
Clean donor course quiz submissions to send POAP

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#718]
Cleaning out the list of 11,000 + people that filled the donor course quiz, to figure out which are spam and which are real

**Comment by ahmadabugosh** [comment]
I'm working with missgene on this (I don't see her on github)

**Comment by missgene** [comment]
Hi @ahmadabugosh! I just requested a new access to the spreadsheet responses. Can you please grant me access? Thank you!

**Comment by ahmadabugosh** [comment]
@missgene done!

**Comment by ahmadabugosh** [comment]
hey @WhyldWanderer I have the list ready to send, I just need the link to the POAP's

**Comment by WhyldWanderer** [comment]
Im sorry! I thought I shared this with you long ago...
Sending you the doc in a DM on Discord

**Comment by ahmadabugosh** [comment]
@scottbenjd said he'll work on this and should have the new POAP ready by this week! 

FYI, @laurenluz @WhyldWanderer

**Comment by scottbenjd** [comment]
@laurenluz @WhyldWanderer @ahmadabugosh 
Okay, I have a drop created for a first round of POAPs using the same method we do for Givbacks. [Donor Course POAP](https://app.poap.xyz/admin/events/giveth-donor-101-course-completion-round-1-2022)
If we're okay using this method, we just need eth addresses. 

How frequently do we want to do donor course poap distributions? Same schedule as givbacks?

**Comment by ahmadabugosh** [comment]
thanks @scottbenjd !

But I'm still a bit confused on the process. Do we need the addresses before you create the POAP, so we do it in rounds, or is it possible to keep adding addresses to the same POAP?

For example, if 10 people finish the quiz, then we create the POAP with those 10 addresses, then a week later we want to add 5 more people, is that possible? Or do we need to create a new POAP for each time we add new addresses?

**Comment by WhyldWanderer** [comment]
Yeah... thats the trouble with this method. We will have to create a new poap delivery for every round of distribution because we have to add the addresses at the time of creation and you cannot add more in the future.

@ahmadabugosh - have we already sent a POAP to anyone for completing the course?
If so, we should continue to use this same drop and just make a new delivery rather than a whole new drop. Otherwise, it will technically be a whole new POAP and we wont have a complete list of those who claimed.

**Comment by scottbenjd** [comment]
Okay yeah. If it's 10-20 each week and we have email contacts, requesting additional claim links seems like the way to go. I was thinking if  it's 150+, like givbacks then sending individual links could be more time consuming, unless you have some way to automate

You were already requesting more links for the poap we already created right, @WhyldWanderer?

**Comment by WhyldWanderer** [comment]
Yes.. Im not sure if any have gotten sent yet though. Ahmad was working on this part.

**Comment by ahmadabugosh** [comment]
No we didn't send any yet, so we can decide on the process that makes the most sense. 

What's the next step for this?

**Comment by scottbenjd** [comment]
Don't know exactly where we need to pick up the process but this is what I think would be the best course of action. 

1. Remove obvious bot submissions
2. Distribute POAP for remaining submissions with BOTH eth address and email.
If you can get the list of these eth addresses, we can create a poap delivery and return the delivery link to you to distribute via email.
3. Distribute POAP for remaining submissions with an email but no eth address using unique claim links.
4. Going forward we can create deliveries periodically and email the delivery link.

@ahmadabugosh I think we need to sync to make sure we're on the same page on the more specific logistics.

**Comment by laurenluz** [comment]
we got a looot of submissions via twitter the last few days. I think we might need @missgene's help to filter them.

**Comment by scottbenjd** [comment]
I know we wanted to get at least an initial distribution out this week. If there’s a list of addresses ready, could we go ahead with those since we’ll have to do more deliveries in the future anyway?

**Comment by scottbenjd** [comment]
hi @missgene were you able to remove spam up to a certain date? is so is there another sheet with those addresses/emails?

**Comment by scottbenjd** [comment]
I just submitted a petition for the first delivery. Should hear back sometime tomorrow.

**Comment by ahmadabugosh** [comment]
Finally happy to close this! :)
