### ISSUE TITLE
Community Building Planning & Strategy

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#720]
Identify gaps in community building activites, prioritise tasks, build strategy, formulate processes and activities with schedule (#534 #700)

docs and resources
https://www.notion.so/giveth/Giveth-Community-Building-45fcf05c12b3499ea4fb1c9def2e85af

**Comment by clara-zi** [comment]
Community Building Activities Giveth Gap Analysis: 
https://docs.google.com/spreadsheets/d/1JZvVn7zCY3E-d0lHGX_Dbt_oO05ed3moz6Lr5GpWrg0/edit#gid=0

**Comment by clara-zi** [comment]
https://whimsical.com/our-people-KsUEK2u8PXLH8kGLUDsecp 
This document now breaks our members into 5 groups in line  with Comms segmentation.
It is my goal to use these two documents to help understand how we prioritise, conduct community activities, allocate resources to specific community building activities. 
It will be really great to identify/create more community-led activities.

**Comment by clara-zi** [comment]
Orbit app @WhyldWanderer: looks like we need to update our member list for each platform in Orbit?
1) Who set-up Orbit data? 
2) Do you know if it was set-up using .csv file uploads with member ids. Was it automated with an API?
3) Do we have any Orbit experts in the team?

**Comment by WhyldWanderer** [comment]
These are all very good questions @clara-zi.
Ezetec (@EventHunter)  set it up... I just assumed it updated automatically but I also noticed that things werent looking quite right and I manually updated the Discord stuff.

I will see what I can find out because I agree that it isn't as helpful if its not staying updated.

**Comment by clara-zi** [comment]
Can you make me a workspace 'owner' or 'editor' please?

**Comment by clara-zi** [comment]
Discussion with Orbit support team: Functionality for Twitter feed with Orbit API is still in development, see comments for Orbit:
"Hi Claire,

We don't track historic Twitter followers. That means anyone who followed you prior to the Twitter integration being connected doesn't get captured as a follow activity. Unfortunately the data on followers provided by the Twitter API is a bit incomplete and lacks the date they became followers. For Orbit's mission when someone followed you is important to building that activity that is displayed in reports and graphs. 

We do capture new follows as activities. 

Many of our default community reports and filter exclude teammates so that can cause some confusion as well.

I see that ClaraZi has 20 followers -- but in Orbit there is 0. I think the way this works is that information is updated when you have a new Twitter activity. Would you mind trying a test? Mention @Givethio on the ClaraZi Twitter and see if the follower count updates in Orbit"

**Comment by WhyldWanderer** [comment]
Join Community Building sync to learn more! Closing this issue for now
