### ISSUE TITLE
Create Personas for Donors

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#724]

**Comment by SnakeGH** [comment]
Hey Team, I compiled the highest voted or selected answers in our donor survey result excel and turned them into PERSONAS that are now available for review and commenting.

Please have a look at my Miro board, as it is full of really good feedback we can use in all areas of our Comms; Donor, Project, Partnerships or simply broadcasting and where to broadcast our important items.

https://miro.com/welcomeonboard/N1RqMW11U1dnZlB2Y2U5WVpWNHpZNVp1ZlREMmFmeEtyWDdmUm5YZTVITVBqdGtmNFcwZnNITFZ1OWpuZ214UHwzNDU4NzY0NTM1MTYxMzg2MTY3fDI=?share_link_id=852497889300

Upon your review, I would love to see some sticky notes in the Miro with your suggestions or feedback. Thanks!
