### ISSUE TITLE
Create Form to get feedback from donor personas

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#725]

**Comment by laurenluz** [comment]
Is this the issue @SnakeGH is working on?

**Comment by SnakeGH** [comment]
@laurenluz not yet, but this is something @ahmadabugosh and I have discussed. We will create the Donor Survey (GitHub #623 ) first and that will help us build Donor Personas

**Comment by ahmadabugosh** [comment]
Thanks @tropicalmangos ! I added the option for both (online and inperson) for that question + I made the last screen easier (I added links for them to automatically generate the tweet and to automatically follow us)

**Comment by SnakeGH** [comment]
Thanks @tropicalmangos for the input, and I know you already saw my responses via discord. Also thanks @ahmadabugosh for making those changes in the survey. We are currently at 73 and would love to get to 100 takers.

**Comment by SnakeGH** [comment]
@tropicalmangos our Giveth meetings, channels & social media, as well as having our Giveth partners share it on their social channels.

**Comment by SnakeGH** [comment]
I didn't create a "form" for say, but I did create this Miro board with some donor personas I have initially created using feedback from our donor survey, which had over 85 takers! Go ahead and review and let me know your thoughts / comments 

https://miro.com/app/board/uXjVPQDoICc=/

**Comment by oyealmond** [comment]
hey @SnakeGH ! Can we close this issue?

**Comment by SnakeGH** [comment]
Yeah, I think we are good with closing :)
