### ISSUE TITLE
Project Owners 101 Video: Perks of getting verified

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#736]

**Comment by laurenluz** [comment]
We should definitely say:
- Your donors get GIVbacks
- coming soon, GIVpower

I can do this one, but would love your suggestions for anything else to add @WhyldWanderer

**Comment by ahmadabugosh** [comment]
Closing this as we mention perks of getting verified in [this issue](https://github.com/giveth/giveth-planning/issues/737).
