### ISSUE TITLE
Project Owners 101 Video: How to get verified

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#737]

**Comment by laurenluz** [comment]
@WhyldWanderer or @NikolaCreatrix - it would be awesome if one of you helped with this

**Comment by NikolaCreatrix** [comment]
Hey there, I would love to help with this.... @laurenluz @WhyldWanderer 
Where to start here? @ahmadabugosh

**Comment by WhyldWanderer** [comment]
@NikolaCreatrix 
The best thing to do is to start creating a bulleted list of the topics you think should be included in the video.

Here is one that Lauren made for one of the videos in the donor course that you can use as a reference:
https://docs.google.com/document/d/15YMv_NS3gasx0d77Y1cA3nwhCdl_CCfTGRez1Qz66oE/edit

**Comment by NikolaCreatrix** [comment]
Thanks @WhyldWanderer that was super helpful :)

Something like this? https://docs.google.com/document/d/1kDiv9uOHVqW4V3ijBLGVnebpFvVtLBgJnM1HI67Tvx8/edit?usp=sharing

@ahmadabugosh

**Comment by ahmadabugosh** [comment]
Thanks @NikolaCreatrix nice work, you went into a lot of detail which is great! A few comments I have are:

1)  I think you should mention at the end what happens after they submit the verification form. So basically, what happens after the form is submitted, and what does the timeline typically look like for us to get back to them (+how many other steps are involved). 

2) What is required of them when we get back to them (for them to post on social media etc), in terms of how we actually have them verify.  

3) Mention some of the community initiatives we have, like the Community calls, AMA's, Discord channels etc. for them to get support if they have any questions.

**Comment by oyealmond** [comment]
Heeey team! @NikolaCreatrix @WhyldWanderer @ahmadabugosh @c0ric0ri I see this is work in progress, I can help record the video and the voice over, if someone help me finish the script. 
I see is almost there: https://docs.google.com/document/d/1kDiv9uOHVqW4V3ijBLGVnebpFvVtLBgJnM1HI67Tvx8/edit 

Maybe we just need to add the visual material to show in the video.

**Comment by ahmadabugosh** [comment]
Hey @oyealmond, I think this is good to start recording. I added a couple of comments to the script and I think it's ready for us to record a draft. 

For the visual references, I recommend just to keep it simple and record the website + have some slides with bullet points if that makes it easier. You can use these : [https://docs.google.com/presentation/d/1VSrV5QxM2XVyFxiGM81qqC8-FtcxDeo1-Z2K0WslfqA/edit#slide=id.gfdefa94949_0_0](https://docs.google.com/presentation/d/1VSrV5QxM2XVyFxiGM81qqC8-FtcxDeo1-Z2K0WslfqA/edit#slide=id.gfdefa94949_0_0) and see how I recorded the [$nice token video](https://www.youtube.com/watch?v=NV3kfo2YvoQ&ab_channel=Giveth) as an example. 

Thanks!

**Comment by oyealmond** [comment]
Perfect! I can start with this :) @ahmadabugosh :) Send it later today!

**Comment by oyealmond** [comment]
Hey @ahmadabugosh @c0ric0ri , finish this first video. 
Can you share your thoughts? This is useful, or not at all? https://drive.google.com/file/d/1jbKZhDQug_eTEi-6HeREj-k_6DR6Fbyt/view?usp=sharing

**Comment by oyealmond** [comment]
I was thinking that, will be nice if we count w some background music @ahmadabugosh to cheer the tutorials a bit

**Comment by ahmadabugosh** [comment]
Great work @oyealmond ! I think this is ready for review by someone that works close to project verification like @WhyldWanderer or @NikolaCreatrix .

 Once they give the go ahead, I can add some soft background music to it and make minor edits to ship it

**Comment by ahmadabugosh** [comment]
@oyealmond a few more thoughts I had on this that we can improve on: 

1) I think you should spend a little more time on filling the form, especially for "tricky" parts that might be new to projects not familiar with web3. For example, what to put for their address (a few projects I talked to got stuck on that part because they never used Metamask etc before). You could just explain you need a wallet address, and you can watch the video where we talk about how to create your own wallet in the video description (and we'll link [this one](https://www.youtube.com/watch?v=TLlebSlRDyo&list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&index=3&t=45s&ab_channel=Giveth&themeRefresh=1))

2) You should mention at the end, what to do if you get stuck, for example reach out to us on Discord on the support channel https://discord.giveth.io

3) You should also mention the new project verification changes that were recently made , like email verification and oath etc. (this issue [841](https://github.com/Giveth/giveth-planning/issues/841)

**Comment by oyealmond** [comment]
Hey @ahmadabugosh ! 
Thanks for the feedback. 
Here is the video update with your observations. Lmk your thoughts https://drive.google.com/file/d/1VDoqC2SUrEb2EFcaD7oGq8VZm-r79jsz/view?usp=sharing

**Comment by NikolaCreatrix** [comment]
Hi @oyealmond and @ahmadabugosh , wow I am actually so happy you took and pushed this forward Almond, cause I felt stuck and then also waiting for the new Verification Dapp... Great job and I like your voice. :))


Few thoughts and comments, I echo Ahmad's feedback and would like to add to it these things that come out of the experience:

- Before you can Verify your project first you have to create one. (I know this is silly but not everyone can understand it obviously)
- Explain we need their personal social media, then projects/organization's social media, and THEN the URL for social media link post for the project that they need to share on the ORGANIZATION's/PROJECT's social media profile. (This is usually the most problematic part that people don't do and get confused, and rejected) 
- Stay in the process longer and walk through each step during filling in the application - this was a bit too fast and you apparently already walked through the process a second time seeing the checkmarks on sections... - the better prepared they get, the better they fill the tricky parts...
- the more information they can share with us, the better for them. Emphasize the importance that we really need to see some reputation at stake.
- at the end and revoke info include information about 'mandatory updates' Smth like: " Make sure you post regular updates to your project. Your status will be revoked after 3 months of no updates in your update section."

- oh and, I would practice a little bit more the English pronunciation I had difficulty understanding some parts...so sorry Almond, I love your Spanish accent and I think its cute:), and on the other hand I am also not native eng speaking person and sometimes have to work hard with my language to be understood well.  

Once again thank you Almond for taking this over, it seems like you did it in no time! 👯 Visual, presentation, voice - beautiful! Little bit of music in bckrnd will be nice.

**Comment by NikolaCreatrix** [comment]
@oyealmond sure I can help, I can work on it this week, will try my best to do it asap. And your voice is great!! I would absolutely encourage you to give your voice to it!! Just a little tiny bit of practice and there you go...it ll be awesome, I believe in you! :)

**Comment by oyealmond** [comment]
Sure I can give it a try, I believe in you too! Thank you for helping adding this details to the script , Still I think that if my voice does not work, maybe @ahmadabugosh or @WhyldWanderer can help us on this

**Comment by oyealmond** [comment]
Hello @NikolaCreatrix . Ready de video with the changes you requested. Hope is good this time 😥 
cc @WhyldWanderer @ahmadabugosh 
https://drive.google.com/file/d/10Auv5OPSb7Bubq89EM4hY3LSWd81lDkg/view?usp=sharing

**Comment by NikolaCreatrix** [comment]
Hey @oyealmond excellent work!! I think it's perfect now, good to go and green lights from me!

**Comment by ahmadabugosh** [comment]
Really great work on this one as well @oyealmond ! 

I uploaded it on Youtube [here] (https://youtu.be/8myBgJCKXiU)

I have the video unlisted now, @WhyldWanderer can you just do a quick final check before I make it public? (since you're very involved with the verification process) 🙏

**Comment by WhyldWanderer** [comment]
Wow!! This looks so great you guys...

I think you have covered everything in an easily digestible amount of time. 
Great work Almond and Nikola!
