### ISSUE TITLE
Project Owners 101 Video: Policies

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#738]

**Comment by c0ric0ri** [comment]
List out here what you want to cover in the video, then tag a reviewer with knowledge on that topic

**Comment by ahmadabugosh** [comment]
@c0ric0ri to take this and check @WhyldWanderer

**Comment by oyealmond** [comment]
Hey @c0ric0ri!! 
I can help with this, we just need to create a script and I can record the video nd make the voice over. Anyone that could help me with the script?

**Comment by c0ric0ri** [comment]
I checked both the covenant and the Terms of Use. There are a lot of points but most of it seems to boil down to policies around harassment and data mining. @ahmadabugosh I actually couldn't find anything about looping donations, I'm curious where that's stated?

Here's a first script outline.

Projects should act in accordance with the Giveth covenant and Giveth terms of use:

1. Making Giveth a warm and safe environment, free of harassment of any kind

- Examples of unacceptable behaviour include:
* The use of sexualized language or imagery, and sexual attention or advances of any kind
* Trolling, insulting or derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others’ private information, such as a physical or email address, without their explicit permission (commonly called doxing)
* Other conduct which could reasonably be considered inappropriate in a professional setting

3. Refraining from inappropriate advertising, data mining, or improper use of support services
4.. Not “looping donations”, aka using funds from their donations / GIVbacks to keep donating to their project

**Comment by ahmadabugosh** [comment]
@c0ric0ri I don't remember where I read about the looping donations (it may have just been on a call, I can't find it on the forum), but yes basically we should mention how we don't allow people to re-donate funds they received. 

I think this needs someone who handles project verifications to comment on , cc @NikolaCreatrix @WhyldWanderer

**Comment by ahmadabugosh** [comment]
hey @c0ric0ri are you up for recording this one, or do you need support? @oyealmond offered to record it if you think the script is ready

**Comment by c0ric0ri** [comment]
Hey @NikolaCreatrix @WhyldWanderer would you mind double checking this before we start recording?

**Comment by oyealmond** [comment]
sure I can help! 
I think Ive seen a couple of m ore 101 Videos missing, maybe we can arrange a call to align and finish them all :) @ahmadabugosh @c0ric0ri

**Comment by WhyldWanderer** [comment]
Disqualifying Factors for the GIVbacks Program

Once a GIVbacks round ends, there is a period of time allocated for our team to review flagged projects and donations for disqualifying factors before GIV is distributed to donors. A project could have their Verified status revoked if any of these factors are found. Donors to projects who are found with any of the following activity may also be denied GIVbacks for that round. Disqualification factors are as follows:

1. Giving/offering goods or services to donors in exchange for their donation. A project owner cannot offer goods such as a sponsorship for a conference, Girl Scout cookie purchases or tickets for a dinner, even if the proceeds go to charity. Project owners cannot provide services like acting as a crypto exchange for their donors. They can explain how to use an exchange, but they cannot convert the money for their donors.

2. Circulating donations raised by other means. Only “first touch” donations count for GIVbacks. If a project receives funding from a donor and is found to be circulating these donations within the Giveth platform to receive GIVbacks, they will be disqualified. For example, a project should not be sending fiat donations received elsewhere back to their donors and asking them to donate on Giveth with crypto.

3. The funds are not being used for what is expressed in the project page or submitted verification application. Verified projects are responsible for keeping their projects up-to-date with information on how the funds are being used. If the project states explicitly that they are, for example, using the funds to develop education programs but are found to be using the funds to employ developers, they may be disqualified from the GIVbacks program.

4. Unscrupulous or fraudulent activity. This can be the use of violence, breaking laws, or other behaviour that does not uphold the values of the Giveth community. Projects found to be violating our Terms and Conditions will not only lose their verification status, but they also will be canceled.

Reference this doc: https://docs.giveth.io/dapps/projectVerification

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh @oyealmond I think I do need support with recording this, I am struggling to find the time and don't want to be the bottleneck on this

@oyealmond would you be ok taking this over?

**Comment by oyealmond** [comment]
No worries @c0ric0ri I got you. 

@ahmadabugosh , [I made a scrip for you to help me review it first so I can record it ](https://docs.google.com/document/d/1viH6KDzRk7iLAAihU_rXss1Exg-nIEDX2N-FSxEwk0A/edit?usp=sharing) . Please feel free to add any changes without asking.

**Comment by ahmadabugosh** [comment]
Thanks @oyealmond great work! I made some edits on the doc, and it should be ready to record now. 🙏

**Comment by oyealmond** [comment]
yeyy! I will record it today. Thank you @ahmadabugosh !!!

**Comment by NikolaCreatrix** [comment]
Wow! Beautiful work you guys, looking forward to watching it!

**Comment by oyealmond** [comment]
Hey dear team. [Here's the video](https://drive.google.com/file/d/1xSx8LgF7EU4LTlbmkkEOD4VYucaTtDdt/view?usp=sharing). Hope is useful :) 
Let me know your thoughts

@NikolaCreatrix @ahmadabugosh

**Comment by ahmadabugosh** [comment]
Amazing, great work @oyealmond! 🙌 I uploaded it here as an unlisted video here https://youtu.be/u8SytXVpxpQ. Once we get a final confirmation from @WhyldWanderer or @NikolaCreatrix I'll make it public

**Comment by NikolaCreatrix** [comment]
I love the work, very well done @oyealmond , looks really great to me! 

The only little tiny thing I wondered about while watching the video was - should we also mention that one of the new policies is -  A project can get their verified status revoked if they don't post any update for a 3 months period.

Sorry I didn't think of it earlier...

**Comment by oyealmond** [comment]
I thought about that too, but I believe this is not deployed yet? @NikolaCreatrix

**Comment by NikolaCreatrix** [comment]
@oyealmond it's not deployed because we don't want to revoke the majority of verified projects, which would be the case unfortunately at this point.

In a nutshell, we have been already sending email notifications about this for several weeks. Basically, we need more projects to post updates, teach them how to do it, etc...so the more communication channels we can communicate this, the better.

From my understanding, we were about to deploy fully on October 15th and we paused because of the lack of updates issue...now Ashley and I are going through the list of all projects without updates and assessing manually their activity and revoking the status...so within next week or so, we may be able to move forward into the final stage of deployment. I think, mentioning this policy in the video could help us and also cover us (Giveth) if there are any post-issues with project owners... I think it would be great to have it in, but not sure if its way to much work to edit it in... otherwise we can make sure to bring that awareness in other forms, in any case.

**Comment by NikolaCreatrix** [comment]
> For sure I think we should include it. But specially here that's not mentioned - https://www.youtube.com/watch?v=8myBgJCKXiU&t=2s

here it's great, it is mentioned in the 2:19 timestamp.

The new part for the policies video I think would go well to the part starting on 1:17 timestamp where you already mention that verification status could be revoked...
 
 
![image](https://user-images.githubusercontent.com/100084867/197637838-0065eba3-781b-4d16-8444-7b92b948d64a.png)


Maybe just add one last sentence in this section of the presentation, something like: 'And lastly, the project's verified status can be revoked after 3 months of no updates activity.'

**Comment by oyealmond** [comment]
Oh you're so right @NikolaCreatrix! In the first one is actually mentioned! Great! I will include in this new one as well :)

**Comment by oyealmond** [comment]
Hey team! The corrections are ready. [Please check it out. ](https://drive.google.com/file/d/1TWNFYiz4zNX05sSG8KVpq7cUOvfMVC2q/view?usp=sharing)

I added the 3 months update part. @NikolaCreatrix @ahmadabugosh

**Comment by c0ric0ri** [comment]
Hey @oyealmond remember to move to Review/QA status :) I'm doing it now!

**Comment by ahmadabugosh** [comment]
Thanks @oyealmond ! Updated the new one on the playlist: https://www.youtube.com/watch?v=Lf-ewaPmrAM&list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm&index=7
