### ISSUE TITLE
Project Owners 101 Video: Off-ramping your funds

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#740]

**Comment by c0ric0ri** [comment]
@WhyldWanderer @clara-zi

**Comment by clara-zi** [comment]
@WhyldWanderer I've been giving this some thought: we can't cover all the offramping routes end-to-end for all the different variables around the world but what we could do is something like these:

1) deal with different bridging for common tokens donated on our platform (ie xdai to DAI bridge)
2) talk about stable vs volatile
3) talk about the major centralised exchanges
4) GIV does not need to be offramped and an intro in the different uses of GIV

**Comment by ahmadabugosh** [comment]
Thanks @clara-zi , i would also add 

5. Have a walkthrough video that shows offboarding funds as an example. Even if we explain how each country has a different process and exchange, I think it would be useful to show a live example of how to go from your Giveth project funds -> Browser wallet -> xDAI bridge to DAI  -> Exchange -> Withdraw to a bank account
6. I think at the end we should include a database of people to reach out to in each geography. This would be a great time to revisit [this doc](https://docs.google.com/spreadsheets/d/1I7n3oCCEFMm1875ZvkSI3ditxP-3n27VGMZIh3lPnAc/edit?disco=AAAAXDQycIw&usp_dm=false) that we started on earlier this year. 


Is this one that you can record? I think it would be great if we show what it looks like fully from the project side. Is there a test project we can use to record this, or maybe someone from our team that has a project can record this one?

**Comment by oyealmond** [comment]
Hey @clara-zi @ahmadabugosh @c0ric0ri @WhyldWanderer I can help recording this video if smth is willing to team with me and finish the script ! :) Someone down?

**Comment by ahmadabugosh** [comment]
Hey @oyealmond since you're taking other ones, I can record this one :)  I'll work on it, and share it with you to get your feedback.

One thing I do need though is help on what it looks like from the project side when you receive a donation (to show that in the walkthrough of how to offboard funds). @NikolaCreatrix is that something you can help me out with (recording a short video that shows what it looks like when you receive a donation from the project side and how to get your donations to show up in Metamask)?  
Thanks!

**Comment by oyealmond** [comment]
Perfect @ahmadabugosh ! :)

**Comment by ahmadabugosh** [comment]
hey @NikolaCreatrix, wanted to ping you on this again, can you share a short recording for this on what it looks like when a project receives funds, and how to make those funds show up in Metamask? Once it's in Metamask I can explain how to offboard it from there, but I want to have what it looks like when a project receives donations so we can have the entire flow recorded easily for them step by step.

**Comment by NikolaCreatrix** [comment]
Hey hi! Oh yeah this! Okay. Sorry for the delay. I think I can do this with a little bit of your help @ahmadabugosh :)

I can start working on it slowly  (create a little script and learn the recording tool) but I will have more bandwidth to actually work on this after this week...and after I land back in Costa Rica...

**Comment by ahmadabugosh** [comment]
Hey @NikolaCreatrix can you help me out with just one small thing for this? If you can please just record your screen (not even a voice-over, just your screen using something like Loom.com etc) to show what it looks like when a project receives funds. This could include notifications you get (emails etc), what it looks like in your dashboard and what it looks like in your wallet + anything else you think is relevant. 

That's the only missing piece I have (since I don't have a project that is collecting funds), just a visual of those things from the project side. I can do the rest (the voice over and how to offboard), but I just need to have that part! 🙏

**Comment by NikolaCreatrix** [comment]
Hii @ahmadabugosh 
Catching up, @c0ric0ri really appreciate you pinging me in the discord!

Yeah okay, let's do that, Ahmad can we have a maybe super quick couch session on how to record my screen and I'm down to do this.
So we need to record:
- when a project receives funds - email notification, project's donation dashboard, showcase in wallet. Also maybe when receiving the GIV - how it looks on the screen, icon next to the profile picture...

Do we also want to show them how to swap for stables in uniswap? Or bridge to binance? I can help with that one too, I offramp using a binance smart chain...

lmk @ahmadabugosh if we can start with a fast Loom guide, if you can help me with that. Then it should be fast. :)

**Comment by ahmadabugosh** [comment]
This last video is fiiaaanaly done! 

https://youtu.be/6gsKBVesE7w

Thanks so much for the help @NikolaCreatrix @clara-zi ! 

Can you please review it and let me know if you have any comments before I make it live? 🙏 cc @WhyldWanderer

**Comment by ahmadabugosh** [comment]
Hey team I reuploaded a new version here, ready for review: https://www.youtube.com/watch?v=1z66GxECThM&list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm&index=10

**Comment by NikolaCreatrix** [comment]
Wow @ahmadabugosh major praise to you, awesome work!!! Long video, but really detailed and easy to understand!

**Comment by WhyldWanderer** [comment]
I think it looks great @ahmadabugosh! You are very clear and to the point and it is easy to understand...

I agree with Nikola that it is kind of long.... is there any way to shorten the time?
Maybe we can speed up the spots when metamask is loading, etc?

**Comment by ahmadabugosh** [comment]
Hey @WhyldWanderer I think we should keep those parts in, since for beginners they're helpful and if we skip of any of the steps they'll get confused.,

However, I did add 13 chapters to the video to make the longer video easier to digest (and people can skip around to different sections)

<img width="832" alt="Screen Shot 2022-11-04 at 3 29 37 PM" src="https://user-images.githubusercontent.com/4855928/199962726-f4eca8e7-5c82-43e3-8ac3-1e4e913cf57e.png">

**Comment by NikolaCreatrix** [comment]
I think this is a great solution @ahmadabugosh Its a complex process... its literally a workshop session :))

**Comment by ahmadabugosh** [comment]
hey @WhyldWanderer @NikolaCreatrix , since I mentioned FTX in the video, I cut out that part and reuploaded it 😅 : https://www.youtube.com/watch?v=LLSft1g-wIc&list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm&index=8

**Comment by NikolaCreatrix** [comment]
Great catch @ahmadabugosh !!! :)
