### ISSUE TITLE
Meet the Makers Spec doc

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#745]
I am pulling out all information I can find here on Github. I am working on a draft of spec doc, which then I will bring and present + discuss w @WhyldWanderer in ETHBarcelona.

The goal is to create a clear template/project management guidelines around this event to follow, for me and/or anyone else who would take on and like to manage this event in the future.

**Comment by NikolaCreatrix** [comment]
I think I'm pretty much ready for other eyes on this. 🙌



[Meet the makers spec doc](https://docs.google.com/document/d/11pAUmN18p9_xm-DSG2dNKPApBFph0V5QNv90B5D-2p4/edit)

I would also like to break down the chronological plan - what needs to happen when and in what order so that there is a clear action steps guide. Schedule to follow... if you know what I mean 🙂 trying to logically figure out the comms part and need somebody with more experience.
@laurenluz please feel free to leave any insights or comments. Your feedback is invaluable.

**Comment by laurenluz** [comment]
left some comments in there @NikolaCreatrix! It looks like a great breakdown. feel free to ask anymore questions.

**Comment by NikolaCreatrix** [comment]
Hello there :) @WhyldWanderer and @laurenluz 

I feel like the spec is ready for review.

Today, Sep 8th, we have a first Meet The Makers warm up call to form a team, gather feedback and ideas and start moving toward a specific date frame.
And speak with 3 potential outside collaborators for further project interviews.

**Comment by c0ric0ri** [comment]
Hey @WhyldWanderer are you able to review this week and move this to Done?

**Comment by NikolaCreatrix** [comment]
This is actually pretty much done and we are already working with it the EPIC #860 

So we can close this issue. I am on it.
