### ISSUE TITLE
Giveth constituents CRM (for projects, donor, partnership management)

### ISSUE THREAD

**Issue by melodysongq** [Giveth/giveth-planning#747]
Looking into tracking outreach through a CRM system to better manage active recruitment of partnership, donor, and project.  Here is a draft for the database design:

https://docs.google.com/spreadsheets/d/16b8yiXjsvSm48HK314t9MUa7WCd8Tv-zrJ6D17O6CGo/edit#gid=2112929636

**Comment by melodysongq** [comment]
@Cotabe @clara-zi @ahmadabugosh

**Comment by SnakeGH** [comment]
Id like to run with this now and get a CRM going ASAP. It will be very beneficial not only for all items previously mentioned but specifically for Donor Relations. 

Has Giveth operated with Hubspot in the past or does anyone remember setting up a free account? 

@MoeNick, Ashley thought you might be the person to ask about this. Any insight by chance? Thanks!

**Comment by MoeNick** [comment]
Hey, As I know, we did not. However, I would like to contribute on this, just let me know which Api you need to set it up.

**Comment by SnakeGH** [comment]
I have gone ahead and started a Giveth account with Hubspot, as I wasn't able to locate any decentralized CRM options. Our account number is 26098969. 

Please create a free Hubspot account and link to this Giveth account # so we can all be connected and use the CRM together :)

**Comment by ahmadabugosh** [comment]
Thanks @SnakeGH! Anyone that wants access to it, just send Jake your email and he can add you

**Comment by SnakeGH** [comment]
Our CRM is up and running, create an account at Hubspot (https://app-eu1.hubspot.com/login) and send me your email so I can easily add you to the Giveth account (#26098969)
