### ISSUE TITLE
New Process for Donor Quiz POAP Claiming

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#748]

**Comment by ahmadabugosh** [comment]
hey @laurenluz @WhyldWanderer for new requests to claim the quiz POAP,  I recommend that we change the process to:

1) In the quiz form they have to fill their Eth Address (so we can tie the POAP to each address instead of having links)
2) At the end, instead of sending it by email, I'll ask for their Twitter handle in the form and ask them to follow our twitter and tweet us. I suggest something like  "I just completed the @Givethio Donors 101 Quiz! Test your knowledge of crypto, the Future of Giving and the GIVeconomy to earn a special POAP!"

**Comment by laurenluz** [comment]
That sounds great.
