### ISSUE TITLE
Tweet Thread Round 15 Projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#751]

**Comment by NikolaCreatrix** [comment]
Sorry for the delay. This round was also very low on applications and pretty tough. We were able to verify only 3 projects this time.

Draft ready here: 

https://docs.google.com/document/d/1VB-D-KbHoMyT_SAMjbuzSvpAleLL_iWI7A0wwBJs3-Y/edit?usp=sharing

**Comment by laurenluz** [comment]
This is great Nikola! Thanks!
