### ISSUE TITLE
ETH Barcelona recap blog post

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#757]

**Comment by danelsuga** [comment]
Notes: https://docs.google.com/document/d/1IFuHIl0FvzyNYn7XCEYLZ5AhJDn8Jy77dGJ59cY2LRk/edit

**Comment by c0ric0ri** [comment]
Hey @danelsuga do you have capacity to finish this week? Thinking it would be cool to get it out by end of this month!

**Comment by danelsuga** [comment]
Working on this for next week.

**Comment by danelsuga** [comment]
This is ready for some eyes! 

https://docs.google.com/document/d/17xS8AX9UDDhNCMa7mqztVELoxpWBcg6jzRNLENwS9uw/edit?usp=sharing

Thanks!

@laurenluz 
@c0ric0ri 
@ahmadabugosh
@SymSL 
@WhyldWanderer

**Comment by danelsuga** [comment]
Note there are extra pics in the draft. I would plan on one for each part. There are too many for the tie-dye party for example. Wasn't sure which one to pick. 

Also, I am missing a photo of TaiChi and am missing link for Griff's interview.

**Comment by c0ric0ri** [comment]
Hey @danelsuga I went ahead and reviewed with just a few tiny tweaks!

Checking the group chat for pics of TaiChi. Let's see if we can hunt down that interview link

**Comment by danelsuga** [comment]
Thanks!! Yeah, I know the photo exists. I've seen it! But can't remember...

And I'll search for that link too. Thanks!

**Comment by laurenluz** [comment]
Hey @danelsuga! Thanks for putting this together so quick! I read through and left a bunch of comments. Tbh, I think the piece is really missing the *meat* of the talks/interview/etc. in general. There is a lot of vague mentions of things happening... but not a lot of focus on our message.

The key messages of the talks is the _most important_ part of this piece imo. This is an opportunity to tell a story of Giveth... our message, our ideas, our plans... to talk more about where we're going and how all these things come together to support our mission.

I linked a bunch of tweet threads I wrote throughout the conference that I think can help add some more context. Would really like to see this upgraded a good amount before we publish.

I know you wrote it quickly, and I know you are amazing! Lmk what you think or if any of that doesn't make sense.

**Comment by danelsuga** [comment]
This is ready for review again. @laurenluz @c0ric0ri

Two thinks I still want, if you have any leads:

- I would like a good pic of ETHCC. 

- I would like a link to the claim/results that ETHBCN/DoinGud was going to donate part of the conference proceeds to a project voted on by the conference participants.

**Comment by danelsuga** [comment]
@laurenluz @c0ric0ri I’m traveling again tomorrow (from MT to CA), so it’d be great if I could publish this today! Let me know if you have any more feedback. X

**Comment by c0ric0ri** [comment]
Wow that was a doozy! @danelsuga I put a bunch of suggestions in there, would help a lot if you can clean it up and I'll take another look.

**Comment by danelsuga** [comment]
@c0ric0ri I don't know what you mean by it being a doozy, but thank you very much for your great help. 

If you two reviewers @laurenluz  can give the green light asap, I'd like to take care of it by Friday. 

Thank you's.

**Comment by laurenluz** [comment]
GREAT work Suga!! You really nailed it on those talk summaries at the top. Thank you so much for putting so much love into this!

I left some comments & suggestions, not so much, mostly small things - have a look! I love your writing, but I do think sometimes that it gets a little wordy that makes things a bit too long, so just keep that in mind for next time. 

Also, I really think we should cut the ETH CC stuff, and make that perhaps a second, much shorter article, instead of having it at the bottom of this one. I think we'll lose our readers with too much length.

Anyway, I think after those edits, this should be good to go! Thanks so much for putting this together - I love it!!

**Comment by danelsuga** [comment]
Thanks, @laurenluz ! I have put it on medium for final review. 

Just realizing the banner says EthBCN and EthCC. So I've asked Rodri to make a new one. 

There are also a few glitches if you will:

- no further info on the donating proceeds from EthBCN to a project of attendees' choice. 

- no "solarpunk message" video embed, but I did a possibly clever workaround.

- no Griff Offical EthBCN interview link.

- there are two tie-dye beach pics, which previously was ok but maybe no good now on account of change-up with pic captions approach. Not sure if I should delete one. 

Meanwhile:

Delete some wordiness as you like. I'm not crazy about deleting any of your interview links since this somehow records them and offers them an audience they wouldn't otherwise have, which is never a bad thing.  But up to you.

Some things in that area of article had to be (and had been already in its former context) structured in a way to create a flow to the article, which is why I think embedding even your cryptovlog was important for flow. Check it out. 

For example, with no embed from Griff's interview, it looks weird to have paragraphs stacked without more photos or embeds or something. Maybe you'll see what I mean. I tried to even it all out.

Thanks!!

**Comment by danelsuga** [comment]
The article is submitted to Giveth on Medium. 

@laurenluz could you please add this banner in place of the old one? (I don't appear to be able when it's in that limbo space.)

Then it should be fine to publish. See above for caveats. 

![image](https://user-images.githubusercontent.com/81351744/183691074-1c8dbc60-4ae6-4931-936b-32f34652078c.png)

**Comment by danelsuga** [comment]
Ok, never mind. I can put the banner in myself! Thanks @laurenluz ! Got it.

**Comment by danelsuga** [comment]
The correct banner is in there now.

**Comment by laurenluz** [comment]
@danelsuga 

I deleted one shapeshift pic, and I think the quadratic funding ETH barcelona this is ok as it is w/ no link.

Griff's interview video: https://www.youtube.com/watch?v=tueMdmNjanI

I think we should delete the vlog embed... maybe just link it, and embed this one instead. can you adjust the text a little?

I will try to figure out a solution w/ this solarpunk video

**Comment by danelsuga** [comment]
Ok!

**Comment by danelsuga** [comment]
Done.

**Comment by danelsuga** [comment]
https://medium.com/giveth/giveth-at-eth-barcelona-giving-on-the-ground-f7f1b55c320d
