### ISSUE TITLE
Figure out value of each donation at time of donation

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#76]
When airdropping GIV to past donors, we want the reward to be proportional to the amount donated.

This is completed for all of the sheets besides the 'revolution.eth token donors', and I could use some help finishing filling out the **Token Price** and **Cost Basis** columns on that sheet. 

Please use the CoinGecko script to figure out the value of each token at the time of donation in the ['revolution.eth token donors' spreadsheet](https://docs.google.com/spreadsheets/d/1vpoKMSYVIuV2Db84TVJC1AUPj9GReWg8qTkBoMfFyXA/edit?usp=sharing)

@laurenluz has volunteered to help with this!

**Comment by laurenluz** [comment]
Ok so I went through and tried to fill them all out... getting a weird error with the import function though... it's seemingly dependent on what row it's pasted in. Can't seem to figure out why there's an error in some rows and others... If you could check it out @willyogo would be awesome.
