### ISSUE TITLE
NICE token announcement blog post

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#765]
@divine-comedian it would be cool if you added some fun pics of people in swag in this one.

**Comment by divine-comedian** [comment]
first draft ready for review! 

https://docs.google.com/document/d/1wMJaKIwyKxM9plboegWAw2RL3B9lnJ6A6Eht8Pyih_k/edit?usp=sharing

**Comment by laurenluz** [comment]
you're amazing. that was fast. I made some comments/suggestions, feel like it's pretty good to ship! Thanks so much, motch!

if we could get one more read through from @danelsuga @WhyldWanderer or @c0ric0ri - would be awesome.

**Comment by danelsuga** [comment]
OK! Great job, Mitch! I made a pass.

**Comment by laurenluz** [comment]
https://medium.com/giveth/the-perks-of-being-nice-support-giveth-and-earn-rewards-df910a792319
