### ISSUE TITLE
Weekly tweet about farming rewards - GIVfarm friday

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#766]
Every 2 weeks rewards change. we should tell people.

**Comment by laurenluz** [comment]
Ok! new goal: the intention is to update users about farming rewards everything friday.

I made the first iteration of this: https://twitter.com/Givethio/status/1555640396847333376

@c0ric0ri would love if you could draft this thread on a weekly basis starting next week! Let me know if you have any questions, we can go over the farm in our next call.

(in the meantime, I highly encourage you to play around in there a little!)

**Comment by laurenluz** [comment]
@c0ric0ri just a reminder to have a draft of this ready for thursday so I can review it before publishing on Friday

**Comment by c0ric0ri** [comment]
Tweets are up and running regularly now so I will close this issue!
