### ISSUE TITLE
Update GIVbacks email to include $nice

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#768]
@WhyldWanderer soon we'll be distributed $nice as well as GIVbacks.

@divine-comedian already wrote the blog for it.

Can we add the "you may also have $nice to claim" bits to the regular GIVbacks email, which will start to go out soon.

**Comment by divine-comedian** [comment]
here's a link to the documentation draft for context:
https://docs.google.com/document/d/1fClRSLl2nZyrEge0-gnU-8ik950BXmVh3MmdQtfhJ_g/edit?usp=sharing

**Comment by c0ric0ri** [comment]
hey @WhyldWanderer how are things looking with this?

**Comment by ahmadabugosh** [comment]
I created this draft (see the last paragraph for what was added based on the GIVbacks email). Open to comments! @laurenluz @c0ric0ri @danelsuga @WhyldWanderer @divine-comedian  https://docs.google.com/document/d/1vhkfCmp4KoSQjVHfFJI_1MjTcKrbdebYayb4bw2lWbs/edit

**Comment by laurenluz** [comment]
awesome @ahmadabugosh, I made some edits, I think it's good to go.

**Comment by WhyldWanderer** [comment]
I think it looks great @ahmadabugosh!

**Comment by WhyldWanderer** [comment]
moving this to In Review!

**Comment by danelsuga** [comment]
I had a peek. Thanks, @ahmadabugosh !

**Comment by c0ric0ri** [comment]
@ahmadabugosh @WhyldWanderer is this offiically updated? Can we close this issue?
