### ISSUE TITLE
Giveth House project description

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#769]
Updating the Giveth House project description on Giveth.io

https://docs.google.com/document/d/1Xor7Dlp7_yEm-XtaxuIhyoE1lITfp_zHZFKRrL3cqOQ/edit?usp=sharing

@laurenluz 
@GriffGreen 

Need Franco's handle.

**Comment by laurenluz** [comment]
It;s great Suga, although, I think Franco should be the person to review it :)

You can send it to him via telegram, I will DM you his handle

**Comment by danelsuga** [comment]
Yes, I already sent it to him. I tagged you two to keep you in the loop! :)

**Comment by danelsuga** [comment]
This is done. Just waiting for Franco to add the pics and put it online.

**Comment by franculio** [comment]
I just saw this, it's already been reviewed and posted!

**Comment by danelsuga** [comment]
Thanks, @franculio ! Before we close this, there are a couple teeny, tiny spacing errors:
coworking , hack sessions - remove space before comma
comradery,freedom - insert space before freedom
market.We - insert space before We


https://giveth.io/project/giveth-house

**Comment by franculio** [comment]
All done! Thanks @danelsuga!!

**Comment by danelsuga** [comment]
Great! Thanks, @franculio !
