### ISSUE TITLE
Angel Vault Announcement Blog Post

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#770]

**Comment by laurenluz** [comment]
Working on this here:

https://docs.google.com/document/d/10o0xmlcr_DHDfdQ7rfxvk8kw18YuJLkc01sHYIuKFj4/edit?usp=sharing

**Comment by laurenluz** [comment]
Ok ready for eyes on this... hopefully we'll publish it tomorrow.

Sent it to @danelsuga @divine-comedian & Griff... not sure who'll be able to have a look today so tagging also @c0ric0ri @WhyldWanderer 

Would love 2 reviewers, please comment here if you're on it.

**Comment by laurenluz** [comment]
ok I got griff to review it. would love one more from someone.

**Comment by danelsuga** [comment]
Will do!

**Comment by divine-comedian** [comment]
reviewed and left lots of comments. In general I think the article gets a bit too in the weeds on details, some sections are too long and the details didn't engage me as a reader. 

I also think we could get creative in the way we explain some of the generic defi jargon, finding simpler terms. This could help broaden the amount of readers that will understand this article. 

examples of defi jargon:
price volatility
buy side liquidity
upward price action
maximise capital efficiency

A few places we sort of re-explain or reuse some of the same phrases and the article sometimes gets redundant.

**Comment by danelsuga** [comment]
I reviewed. I like Mitch’s idea regarding jargon, but that might be too hard to tackle right here right now on this article since I think you want to get it out asap.

I admit I did not understand the whole thing, but I do appreciate the detail and plan to read again tomorrow (midnight here) with a less sleep-heavy head.

**Comment by danelsuga** [comment]
@laurenluz do you have an outline I could look at? That would help me visualize Mitch’s comments better, which I think is important, and would also help me edit better to assist with that feedback. I want to see how you have structured it, if possible.

**Comment by laurenluz** [comment]
Hey @divine-comedian @danelsuga thanks for your great edits and feedback. I did my best to make adjustments based on your comments in the little time I've had.

Also, would like to mention... I wrote the article w/ the DeFi builder audience in mind.... with the intention of explaining our lessons learned & explaining how we got here...and why the angel vault is cool & important.

I added a disclaimed at the bottom of the TL;DR that says:
"Note: This remainder of this blog post was written for a DeFi builder audience with the intention of sharing wisdom gained throughout 8 months of liquidity experimentation."

There are also a lot of external links peppered throughout explaining things like capital efficiency, dollar cost averaging... I even linked to an awesome technical piece explaining more the benefits of angel vaults.

To make this friendly to all audiences, I honestly think it would need to be completely rewritten. Perhaps it's worthwhile to post another blog post later, if someone is willing to take on the task of turning these concepts into simple terms, but idk who is willing or able to do that.

I simply don't have the time.

**Comment by laurenluz** [comment]
@danelsuga unfortunately I don't have an outline. I wrote a sketelon/some notes before starting writing, but basically wrote over it.

For a shorted version of the angel vault, you can see the documentation: https://docs.google.com/document/d/1viCwIugLW9RaYDOQbTlDoQ_3afKmruY7eYrldFK8d1w/edit#heading=h.tzjfyc8vmgi3

**Comment by danelsuga** [comment]
No worries! I think it's great.

**Comment by laurenluz** [comment]
https://medium.com/@karmaticacid/the-evolution-of-giv-liquidity-introducing-the-giveth-angel-vault-5ee34b2965c1
