### ISSUE TITLE
Multi-address Feature Tweet Announcment

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#773]
New product being added to the dApp. we should announce in a tweet/facebook.

**Comment by laurenluz** [comment]
@WhyldWanderer if you can just let us know what's the info is here in a bullet list, I can make a thread :)

**Comment by laurenluz** [comment]
@oyealmond - can you paste the google doc w/ this in here? or is this issue a duplicate? can't find it.

**Comment by oyealmond** [comment]
Sure! 
[Heres the doc](https://docs.google.com/document/d/1g8Dnu_6Eu-AEFOQspKrTODr8Mx_nQRlaHXWVkp7p7U4/edit?usp=sharing )

[And here's the issue](https://github.com/Giveth/giveth-planning/issues/882 )

**Comment by laurenluz** [comment]
ohhh thank you!
