### ISSUE TITLE
GIVpower Memes!

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#779]
@oyealmond would be awesome if you can please set up a meme party for this!

**Comment by c0ric0ri** [comment]
Hey @oyealmond I think you had the party right? Can you please update this issue with comments + links to memes, and update the status?

**Comment by oyealmond** [comment]
Hey @c0ric0ri ! 
It was a great party full of content. 
Find the memes here: https://discord.gg/fFEZrjdw 

Let me know if there's something else missing regarding this issue

**Comment by c0ric0ri** [comment]
@oyealmond just going to move the Giveth Planning status to "Closed" since we have the link here now, and this issue is tied to the GIVpower Epic so we can reference it there. 

Great job!!
