### ISSUE TITLE
Tweet thread to introduce GIVpower first launch

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#780]

**Comment by laurenluz** [comment]
This is ready! Got review already from Griff, and waiting on Stee for a second pass.
https://docs.google.com/document/d/1q8shVpNoXnp4vHaR9sB4agZN2BMucUAIK4qrlamAo40/edit

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1577340015285354496
