### ISSUE TITLE
Tweet thread for R16 verified projects

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#784]
Hi @laurenluz, I hope you don't mind I went ahead and created this new issue for myself. 

Will be sharing the doc link later today...

I am just wondering if you can help me with this - I would love to be able to assign myself (at least) for the issues I create and want to take on... do I need to get some other permissions to be able to do this here in Github?

**Comment by NikolaCreatrix** [comment]
The thread is ready here @laurenluz 

https://docs.google.com/document/d/1D16AAm9PW3frBDM9zBlwuBvmkJccBTyuyUYb5qnJfys/edit?usp=sharing

**Comment by NikolaCreatrix** [comment]
I tried to assign myself, move the issue to a different section as well as add a label, and non of that worked (it says there is an error updating the issue) :(

**Comment by laurenluz** [comment]
Aweome Nikola! Thanks!
Also I added you to the "Communications" team, which should give you write access on this repo. see again if you can move issues.

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1551599224118206466
