### ISSUE TITLE
Tweet about Donors 101 Course POAP

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#785]

**Comment by ahmadabugosh** [comment]
Hey Lauren, can we tweet at some point that we have sent out our first round of the POAP for the donors course to everyone that was eligible? 

Also, I added another filter. For them to qualify, they need to have donated at least $1 to any project (I think that's the best way to prevent these POAP farmers) https://docs.google.com/forms/d/e/1FAIpQLSf8hzFS5kq9pZYVClNR6GC6EavjpeYsFFD_DNKMq19jM6_alw/viewform?usp=sf_link

**Comment by laurenluz** [comment]
Hey @ahmadabugosh - I'll set this to go out tomorrow, sorry for the delay.

How are we going to check if they donated to a Giveth project? Will you have Algene looking into it?

**Comment by laurenluz** [comment]
it's scheduled for tomorrow :)

**Comment by ahmadabugosh** [comment]
Hey @laurenluz, awesome! Actually adding just the $1 minimum seems to have gotten rid of all the spam completely, but yes I'll have Algene look through it if we need any filtering
