### ISSUE TITLE
Newsletter July 2022 

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#786]

**Comment by ahmadabugosh** [comment]
Hi team, here is the issue if you have any topics you'd like to add to the upcoming newsletter (to be send out at the end of next week). 

Also, going forward, I recommend you add any new topics on the sheet here (I cleaned it up and simplified it a bit) :
https://docs.google.com/spreadsheets/d/1VOOt3q5VPItxK7STBBC-qYSzX5qhHBf2Z1i-R8Ok9ko/edit#gid=1125462361

@laurenluz @c0ric0ri @danelsuga @Cotabe @SymSL @clara-zi @WhyldWanderer

**Comment by laurenluz** [comment]
$nice token launch
ethbarcelona - many talks! ask @danelsuga for the links
ethcc - also many talks! @c0ric0ri can send you the links

**Comment by laurenluz** [comment]
Griff was also on this panel: https://twitter.com/karmaticacid/status/1548741609067528193
And I was in this interview: https://twitter.com/AravaGerzonRaz/status/1547538772790755328
Maybe we want to shill the project nominations thing? https://twitter.com/Givethio/status/1547950498493239299

**Comment by c0ric0ri** [comment]
- include updates from the conferences
    - best talk would be Griff’s: SBS would be ideal explaining the Giveth roadmap, depends when it comes out (@c0ric0ri will keep eye out for its release)
    - including section about ETH BCN Giveth presence and onboarding numbers highlighted
- leave out commonstack talks due to space
- $nice launch
- teaser for angel vault launch
- donor survey
- project nomination
- project spotlight (Ashley will check)
- Fundraiser 101 event recap
- idea to highlight newly verified projects which provides them an extra incentive

**Comment by ahmadabugosh** [comment]
Hey @laurenluz @c0ric0ri @danelsuga 

The newsletter is ready for review: https://docs.google.com/document/d/1Uz2FQVe8UGVknvlBPstJObtjNiL29l3tE7aLp3Zym58/edit?usp=sharing 

I tried to include everything I can. I left out the ETHBCN and CC content since we don't have it ready + the project nomination form (I thought it was already too crowded with the donor survey)

**Comment by laurenluz** [comment]
great job as usual @ahmadabugosh !

I made some comments & suggestions. let's coordinate on the tweet for this too! if you write it just send it over for a quick review & make sure we don't overlap w/ schedule.

**Comment by danelsuga** [comment]
Awesome. Will give it a pass tomorrow if not too late.

**Comment by ahmadabugosh** [comment]
Done! Scheduled for 9:30am Costa Rica time today
