### ISSUE TITLE
Newsletter Blurb to Partners Requesting Announcement/Promo of Giveth 2 Launch to their Audience in their Newsletter

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#79]
Write newsletter blurb to send to partners, requesting them to send announcement/promo of Giveth 2 Launch in their newsletter.
Determine what our specific copy/request is for them to include in their newsletter.

*Assign to Magenta once she is added to GitHub.

**Comment by ForestSoleil** [comment]
2/12 Marketing sync update:
- Magenta needs to know dependencies & when this should be distributed
- Has list of partners. Needs latest aggregated list from Ashley for outreach. 
- Has prior copy, can edit once she has all of the details.

**Comment by laurenluz** [comment]
2/19/21 Marketing Call Update:

- related to #81 
- List of bloggers/publications for outreach will be in that issue for @magentaceiba

**Comment by ForestSoleil** [comment]
2/23 Marketing update:
- Magenta to write this week and post here.

**Comment by magentaceiba** [comment]
Drafted here, includes newsletter blurb and sample tweets.
https://docs.google.com/document/d/1ziyu92NgvVku9RR6b5-NyDNAvbo1dFVpbK6-4QNQAQ8/edit?usp=sharing

**Comment by magentaceiba** [comment]
@ForestSoleil pls review the above blurb thanks! this will mostly be going out via twitter dm

**Comment by ForestSoleil** [comment]
3/2 Marketing update:
- Magenta reviewing with fresh eyes today. 
- Magenta to tag 1 person to review, then once that's complete tag another person to review.
- Forest & Ashley to be tagged for review.
- Launch Date: Devs trying for Wednesday March 3rd launch, but stay tuned! Not ready yet. Have not begun testing yet. In the future, whenever devs are ready, this is the marketing hand off date, then marketing team to finalize and determine launch date.

**Comment by ForestSoleil** [comment]
Review/edit complete as suggestions in google doc. Passed to Lauren for 2nd review.

**Comment by ForestSoleil** [comment]
3/5 Marketing update:
- @laurenluz editing today.
- @magentaceiba & @WhyldWanderer to sync on communications strategy to Partners to ensure we are streamlined in our reach outs.

**Comment by laurenluz** [comment]
Just reviewed - looks good to me

**Comment by laurenluz** [comment]
@magentaceiba - can we close this? this happened, right?

**Comment by magentaceiba** [comment]
Yep
