### ISSUE TITLE
Blog Post about Evolving Nonprofits into Regen Economies - from Griff's SBS talk

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#794]
https://docs.google.com/presentation/d/11lYUTWk3YomY3N8lj1CqR7gE1PxxzHutyQHCaG-QVVI/edit#slide=id.g115a6c4ca4d_0_27

**Comment by c0ric0ri** [comment]
@laurenluz yes thank you for the link!

**Comment by c0ric0ri** [comment]
https://docs.google.com/document/d/1GwfIic_IuC7zcOB78L8XIaHEzYMJbHjgi0f5UhnHGqA/edit

Transcript above for reference! @danelsuga

**Comment by ahmadabugosh** [comment]
Let me know if you want a soundbite for this one too @c0ric0ri :)

**Comment by danelsuga** [comment]
Thanks @c0ric0ri !

**Comment by danelsuga** [comment]
My notes: https://docs.google.com/document/d/17i8QwcnHv0vIIDvGtx2XRAPWkOdlcaGSaYJHd_V-WOA/edit

**Comment by laurenluz** [comment]
@danelsuga can you make it comment access?

**Comment by laurenluz** [comment]
@tropicalmangos I think this would be a great content writing issue for you. The purpose is to take griff's talk (Cori transcribed it, and suga made some notes)... and turn it into a blog explaining the Giveth roadmap.

Are you down to take a stab at it?

**Comment by c0ric0ri** [comment]
@tropicalmangos that would be great, yes. We have a backlog of content and really need support with writing at the moment. This is an important piece that is higher priority to complete. 

Do you think you could get a first draft going by early next week?

**Comment by laurenluz** [comment]
Hey @tropicalmangos - this is a great start! excited to see some of the giveth roadmap pieces coming together for you. I think there are some parts that lack clarity still... and the trajectory isn't super clear yet.

I made some comments to try to guide it a little, have a look and please get back to me with some questions. one critical part to doing a good job w/ this I think is having a crystal clear understanding of how all the parts come together so you can tell a good story w/ it.

**Comment by danelsuga** [comment]
What a great undertaking, @tropicalmangos ! I finished an editing pass. Let me know how I can help further.

**Comment by danelsuga** [comment]
I'll have time Wed. Thanks!

**Comment by laurenluz** [comment]
@tropicalmangos thanks for putting so much effort into this. It's a good attempt considering you are still pretty new to giveth concepts, but there are nuances in there that a bit mixed up or missed. I'm concerned that this might be a bit too much of undertaking for you to finish off alone.

I left some comments & suggestions... more general things that I think should be reworked, but I'm a little concerned about it just going again & again through more revision cycles.

I really think there are two paths forward at this point:
- we walk through it together on a call and give you the opportunity to ask questions on any parts you are not absolutely certain about
- we put this into someone else's hands to finish off and make it a co-authored piece

What do you think?

In either case, it would be good if you could include images (taken from the slides) on key sections to help illustrate concepts.

**Comment by laurenluz** [comment]
My preference is to give you one more chance with this so that you can use our call time next week effectively to get concepts down... 

I asked Griff for his feedback on it and his suggestions were, if you want to take another stab at it:
- shorten it & remove repetition
- stick to the content in the talk (those "steps" for example, or Snapshot/tokenlog)
- avoid "guessing" on things you are not sure about (especially wrt to bonding curves)

Also, please don't resolve comments until I can see the changes so I don't have to repeat myself.

**Comment by c0ric0ri** [comment]
Hey I took a look at the outline without going into detail on grammar etc, and I like the way it's structured. 

I'm trying to tie the pieces together from the last two updates in this issue, but is the point here for someone to pick up writing this post now using the outline?

@tropicalmangos @laurenluz

**Comment by laurenluz** [comment]
Hey @tropicalmangos - nice job! it's really coming a long. The beginning especially was waay better. I left a bunch of comments - can you weave them into the outline? 

I would say you've almost got it all, except for Gurves. When you get down to that section, try your best w/ the comments in there, but it it's still "????" then I can write a few paragraphs for that part and you can add it in.

**Comment by c0ric0ri** [comment]
Hey @tropicalmangos can you please provide an estimated date for you can have it updated?

**Comment by laurenluz** [comment]
@tropicalmangos please copy/paste from medium into a google doc and set it to anyone can comment access.

Medium, while good for drafting and formatting, isn't very good for leaving comments/suggestions... so there is one step missing

**Comment by danelsuga** [comment]
I will be able to review this for tomorrow Tuesday.

**Comment by danelsuga** [comment]
Hi @tropicalmangos ! I made a pass!

I'm sorry I added so many comments. 😭 I know you've been working hard on this for so long. I don't know if I'm taking you a step back. Hopefully, the thoughts can be helpful one way or another! 💜

**Comment by danelsuga** [comment]
Great! I've gone through it and answered to all the open comments. They can also be closed now, and maybe we can reach out to @GriffGreen to see what he thinks about us modifying that regen econ "definition". Griff! Check out this comment: https://docs.google.com/document/d/10IlshsuwS5WQFKOx5PZ1x42ZcQKS0SgL7kNlBPwiZ0U/edit?disco=AAAAmhp0sy0

I am wondering if we can add a little more info to your blurb on regen econs to make it more clearly a definition as opposed to just a collection of great qualities. You have said: 

"Regen economies are collectively-designed, constantly-evolving coordination networks."

Perhaps you have also said: 

"Regen economies are collectively-designed, constantly-evolving economic games."

I personally take issue with "economic games," as I think the connotation is negative. HOWEVER, more importantly, I would love for this blurb to actually say what regen econs are. Here is what I propose:

"Regen economies are collectively-designed, constantly-evolving, token-based expressions of circularity.
token-based expressions of circularity."

Maybe the end is clumsy (or amazing :P), but I'm trying to find a way to include the CE element (without repeating "economy" for example). Wdyt @GriffGreen ?

The point is, I'm wondering if we can expand on that slide/quote of yours with/out your approval? Can you speak to this at all @laurenluz ? Thanks!

**Comment by danelsuga** [comment]
(Wow, I have to leave my mistake of doubling the phrase in there because it is pretty funny in light of my subsequent comment.)

**Comment by danelsuga** [comment]
Great! I've gone through it and answered to all the open comments. They can also be closed now, and maybe we can reach out to @GriffGreen to see what he thinks about us modifying that regen econ "definition". Griff! Check out this comment: https://docs.google.com/document/d/10IlshsuwS5WQFKOx5PZ1x42ZcQKS0SgL7kNlBPwiZ0U/edit?disco=AAAAmhp0sy0

I am wondering if we can add a little more info to your blurb on regen econs to make it more clearly a definition as opposed to just a collection of great qualities. You have said: 

"Regen economies are collectively-designed, constantly-evolving coordination networks."

Perhaps you have also said: 

"Regen economies are collectively-designed, constantly-evolving economic games."

I personally take issue with "economic games," as I think the connotation is negative. HOWEVER, more importantly, I would love for this blurb to actually say what regen econs are. Here is what I propose:

"Regen economies are collectively-designed, constantly-evolving, token-based expressions of circularity."

Maybe the end is clumsy (or amazing :P), but I'm trying to find a way to include the CE element (without repeating "economy" for example). Wdyt @GriffGreen ?

The point is, I'm wondering if we can expand on that slide/quote of yours with/out your approval? Can you speak to this at all @laurenluz ? Thanks!

**Comment by danelsuga** [comment]
Hopefully we can get @laurenluz or @GriffGreen to chime in.

**Comment by laurenluz** [comment]
@tropicalmangos I left a bunch of edits & comments - please go through them and tag me again. I'll have another look after and then we should get Griff to do one more read before it goes out.

**Comment by laurenluz** [comment]
> I personally take issue with "economic games," as I think the connotation is negative. HOWEVER, more importantly, I would love for this blurb to actually say what regen econs are. Here is what I propose:

>"Regen economies are collectively-designed, constantly-evolving, token-based expressions of circularity."

>Maybe the end is clumsy (or amazing :P), but I'm trying to find a way to include the CE element (without repeating "economy" for example). Wdyt @GriffGreen ?

>The point is, I'm wondering if we can expand on that slide/quote of yours with/out your approval? Can you speak to this at all @laurenluz ? Thanks!

@danelsuga I agree that this definition could be expanded on, but I think your proposal needs a bit more work. We should try to make it as clear to a new reader as possible, and I think "expressions of circularity" is very confusing without context.

I do like the original, "Regen economies are collectively-designed, constantly-evolving coordination networks."

But maybe we can add to it considering there points:

collectively designed
constantly evolving
coordination networks
DAO governance
tokenized
creating non-excludable value
financially regenerative
regenerative also for society 
bottom-up
efficient feedback mechanisms
web3

**Comment by danelsuga** [comment]
Thanks @laurenluz ! Yes, I feel it just needs something to pull it down to what it actually is. I agree my idea is off in the clouds of poetic confusion somewhere. But I also don't think "coordination networks" explains much either. (By the way, in economic theory, "circularity" is a term to mean the same as "circular economy." But I realize no one knows that and/or it doesn't bring across its meaning very easily.)

"Regen economies are collectively-designed, constantly-evolving, tokenized coordination networks for..."

Getting too long? 🤣

"Regen economies are collectively-designed, constantly-evolving, tokenized coordination networks for creating non-excludable value."

But I'm thinking more along the lines of:

"Regen economies are collectively-designed, constantly-evolving, tokenized community coordination networks."

Still brainstorming...

**Comment by laurenluz** [comment]
Thanks @tropicalmangos - I DM'd it to @GriffGreen so hopefully he can review this week.

Can you send me your medium handle so I can add you as a writer for giveth?

**Comment by laurenluz** [comment]
I like this trajectory @danelsuga !

"Regen economies are collectively-designed, constantly-evolving, tokenized coordination networks focused on creating public goods in a regenerative way." 

wdyt @GriffGreen ?

**Comment by laurenluz** [comment]
this is up in medium! thinking of publishing this week

**Comment by laurenluz** [comment]
https://medium.com/giveth/evolving-nonprofits-into-regen-economies-f8282f97f8d3
