### ISSUE TITLE
Blog post on BitDAO proposal

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#796]

**Comment by SymSL** [comment]
https://docs.google.com/document/d/1iizsQcgy51Rdl5rplx-IFf_-_JT3bE4dZm28OUO0v0M/edit @danelsuga Hey Suga! Here is an attempt at the BitDao blog post, if you are able to finesse it that would be amazing. I'm not sure if its a bit long (i'd say so for a normal blog post but this may be an exception) - let me know what you think!

**Comment by laurenluz** [comment]
Amazing @SymSL!

on first glance, looks great. We should have @spectoregia review it :)

Yass - please have a look. We are planning to publish via the Giveth Medium to get more exposure for the proposal. Please provide feedback & add any other info that you think might be missing.

**Comment by danelsuga** [comment]
Great job, @SymSL ! I gave it a pass. I see a lot of potential for some modifications, and I offered a few but mostly pointed things out. I can make a repass. What's the timeframe on this? I'm tied up in the immediate future with the ETH confs recaps, but I can help anytime, either by just changing things (didn't want to do that without checking with you) or reviewing changes, etc.

**Comment by spectoregia** [comment]
This is an absolutely amazing idea! thank you for putting it together.
I certainly have a couple of comments (based on the proposals I have read on BitDAO that got a pass). will add them in the word doc tonight. let's aim to get it published by Wednesday if possible. :)

**Comment by SymSL** [comment]
Hey everyone, I made a couple more changes to the doc, there are some points in there I am struggling to break down and put into simpler language because I don't understand the concepts well enough myself yet. Please add any comments or questions and we'll aim for finalising on wednesday

**Comment by danelsuga** [comment]
I need to circle back round, @SymSL. Will shoot for tomorrow if that's ok.

**Comment by spectoregia** [comment]
hi all, I made quite a few suggestions. My aim here was mainly to have it drafted in a way that I am hoping it could get picked up or at least inspired by BitDAO authors to draft the main proposal for the snapshot vote.

**Comment by laurenluz** [comment]
great work everyone! it's really coming along. I left a bunch of comments and suggestions in the doc. It really needs some more pictures illustrating the concepts... especially wrt to bonding curves, givpower etc.

feel free to pull photos from past presentations. I would pull the info graphic ones from "evolving nonprofits", maybe some pretty ones of GIVpower... could also use a screen short of the GIVpower test deployment page for this...

https://docs.google.com/presentation/d/11lYUTWk3YomY3N8lj1CqR7gE1PxxzHutyQHCaG-QVVI/edit#slide=id.g115a6c4ca4d_0_27

https://docs.google.com/presentation/d/1qR3YDPPduVaIk4KayTzmgQXFjk4lLzwzZfIGKlEjg_0/edit#slide=id.g143087ec9a7_0_0

https://docs.google.com/presentation/d/1vpEwTjDTHz_S3iMZfqCEMjVEcOmK6NbJdue30PL3eHs/edit#slide=id.g115a6c4ca4d_0_412

**Comment by laurenluz** [comment]
This is queued up in medium and ready to go! When is idea to post it? @spectoregia

**Comment by spectoregia** [comment]
if we can post it even today let's please go ahead! I can then immediately populate BitDAO channels with the post and reach out to individuals from there to pitch it. 
Otherwise, the next best day would be Sunday evening/early Monday.

**Comment by c0ric0ri** [comment]
https://medium.com/giveth/giveth-bitdao-a-partnership-to-change-the-world-c9dfcfad6637
