### ISSUE TITLE
Lauren ETH BCN Video Snippet & Tweet

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#799]
This interview I think is reaally good/ shareable for twitter.

Would love a snippet/soundbite & a good tweet or thread about it. It's only 5 min and covers a lot of the Giveth vision.

https://www.youtube.com/watch?v=IkQRVb03aE0

@SymSL @c0ric0ri @scottbenjd - anyone up for it?

**Comment by c0ric0ri** [comment]
https://docs.google.com/document/d/1L5vxm9xaStd1rT_0W17H5vm49UsWjWHPd85CEKjXYas/edit

**Comment by laurenluz** [comment]
Hey @c0ric0ri - nice job & I love the quote you picked out! I think the interview is a bit short for such a long thread though! some of the tweets are kind of repeats of other tweets. I left some small suggestions and one bigger comment.

Could you try to condense it a little? I saw like 3-4 key concepts.

**Comment by laurenluz** [comment]
Hey @ahmadabugosh !

Thanks for making that happen! TBH I prefer the other format. This is kind of fun, but the video gets cut off and I feel like the music is a bit distracting. I think for twitter... the video w/ the bigger text is nice because it's more eye catching text than your usual tweet text.

Is it easy to make in the other format?

Also, little typo:
"...what value **we're** creating for society..." (not are)


And @c0ric0ri I noticed you edited the tweet thread, edits look great. Can you clean it up and comment here when it's done?

**Comment by c0ric0ri** [comment]
@laurenluz we're all set!

**Comment by ahmadabugosh** [comment]
No worries @laurenluz the other one is actually easier for me to do! :) 

Here it is: [https://share.descript.com/view/WM3WOGEvhnh](https://share.descript.com/view/WM3WOGEvhnh)

**Comment by laurenluz** [comment]
Thanks @ahmadabugosh @c0ric0ri - I have this queued up in tweet hunter to go out this week.

I made some changes @c0ric0ri to the thread to make the message a little clearer. I hope that feedback is valuable!

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1562783987122454528?s=20&t=1QGeURohxysAU41191QtHQ
