### ISSUE TITLE
Write Medium blog about Donation pathways

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#80]
Write short blog content about SDG Impact Fund donation pathway when it’s ready to go. For posting on Medium.

**Comment by ForestSoleil** [comment]
2/5/21 Update from Dani in Marketing Call - 
- Dani working with Brian currently on this. 
- BLOCKER: ETH address is not yet published anywhere that users can donate to for tax deductions. Kay to add this onto the website before we publish the article. 
- 1st Draft ready for review by Monday, Feb 8th. 
- Copyediting to be completed within 48 hours - 1 minimum non-technical copy review, DAO final review from Willy or Kay.

**Comment by Danibelle** [comment]
Giveth Foundation ETH Address at SDG Impact Fund: 0x24431A0ecC8f85B65679e3113a6AbdA7F30251E2

**Comment by ForestSoleil** [comment]
2/9/21 Marketing check-in update:
- 1st draft not yet ready. Will post link later today in GitHub.
- Outline complete.
- Blog about Donation Pathways on Giveth, including SDG Impact - not solely on them. Not much of our audience is interested in tax deductions from her research, so making this more widely applicable.

**Comment by Danibelle** [comment]
Draft in progress: https://docs.google.com/document/d/1dFY-3KWRDsOgdYB0tmUHCGh9Y1oQoo582Iys7VaArhg/edit?usp=sharing

**Comment by ForestSoleil** [comment]
2/12 Update:
- Closing not yet complete. Links not yet added. Content mostly complete and 1st review could begin.
- Ideal reviewers: Willy (financials), + anyone for non-technical review
- Forest to review today.

**Comment by laurenluz** [comment]
2/19/21 Marketing Call Update:

- Working w SDG impact... kind of a mess RN - Dani doesn't want to publish right now
- Dani going to do a final pass re: Forest's comments
- Will post when SDG is stabilized

**Comment by ForestSoleil** [comment]
3/5 marketing update:
- this is deprioritized until SDG and donation pathways are more clear and stable.

**Comment by ForestSoleil** [comment]
3/22 comms notes - 
Goal to publish Thursday, March 24th at GitCoin Grant round closes.
Dani content in progress.
Dani to tag reviewers when ready.
@Danibelle

**Comment by Danibelle** [comment]
Please review!
https://docs.google.com/document/d/1dFY-3KWRDsOgdYB0tmUHCGh9Y1oQoo582Iys7VaArhg/edit#
@ForestSoleil @laurenluz @divine-comedian

**Comment by laurenluz** [comment]
I started hacking, then getting confused with Mitch's hacking, then getting confused with the images... so then decided to make a copy, remove the images and hack at it a whole bunch, put the images back... Still put "suggesting mode" so you can see my hacks. Added some of Mitch's hacks in to the copy as well:
https://docs.google.com/document/d/1BrUI2bdGzJMqCBcMxqVlC7mMf97yuKKz4Q7ZnqXQKsM/edit#

Agree with Mitch's feedback that all the images and headers made it a bit busy. I put three images at the bottom that I suggest maybe taking out?

Sorry for the abundance of hacks - Awesome job Dani!

**Comment by ForestSoleil** [comment]
Is this ready to close & schedule for publication @Danibelle ? Need support with anything? Waiting for FIAT integration with Transact?

**Comment by ForestSoleil** [comment]
Update as of 5/3:
- Dani working on this. 
- Will make a few content changes since time has gone by and we've learned a bit
- Mitch and Lauren hacked on it a lot so Dani will polish it up
- Aiming to publish this to Medium next week

**Comment by ForestSoleil** [comment]
What's the latest on this one @Danibelle ?

**Comment by laurenluz** [comment]
@Danibelle - do we still want to publish this?

**Comment by WhyldWanderer** [comment]
Anyone know the status of this? @laurenluz @Danibelle @ForestSoleil ?

**Comment by Danibelle** [comment]
Abort.
Payment pathways are pain ful still.. giving is easy, paying out is hard. Technology upgrades on their part are needed.

**Comment by WhyldWanderer** [comment]
okay.. lets close this for now and we can revisit this when its less complicated
