### ISSUE TITLE
Communicate GIVbacks POAP threshold

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#804]
We will need to communicate to users that starting in Round 16, we will only be issuing GIVbacks POAP's to donors whose donations total at least 10 $USD value to verified projects in that round.

We will need to tweet this for sure...

Do you guys think we should communicate it any other way? In an email or other social medai account?

**Comment by laurenluz** [comment]
I think twitter might be enough, I don't think an email for this is super super necessary. We should add it to our documentation perhaps.

**Comment by WhyldWanderer** [comment]
This was tweeted about... https://twitter.com/Givethio/status/1554470106167742464
