### ISSUE TITLE
Mandatory updates - Send emails

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#806]
We will need to create the following emails in autopilot for mandatory updates:

**Current Makers**

- [x]  Coming soon! Verified projects will need to provide quarterly updates to keep status.

- [x] Reminder of policy change - you have 30 days to add an update or you will lose verified status.

**Email flow upon implementation:**

- [x] Don’t forget to add your updates! - 45 days

- [x] Friendly reminder, you have 14 days to add your quarterly update - 75 days

- [x] If you don’t add an update within 14 days you will lose your status - 90 days

- [x] You have lost your status. Here’s how you may get it back - 104 days

- [x] Your update needs more information to keep your status.

We can create the emails now but we wont send them until the pieces are in place - @WhyldWanderer

**Comment by WhyldWanderer** [comment]
@NikolaCreatrix agreed to help with a few of these <3
Assigned

**Comment by NikolaCreatrix** [comment]
Yes, I have done the first two most important ones, the draft is [here](https://docs.google.com/document/d/15c0wjLJUNbFQ6wy4qJvEGZR4l_zgY0u-J-Tr6R0vOS4/edit?usp=sharing) @WhyldWanderer, and I am happy to write all of them! It's fun :)
I will provide some new drafts by this Friday!

**Comment by NikolaCreatrix** [comment]
Okay 1,2 and 3 drafts are ready for review [here](https://docs.google.com/document/d/15c0wjLJUNbFQ6wy4qJvEGZR4l_zgY0u-J-Tr6R0vOS4/edit?usp=sharing)

And I have a question @WhyldWanderer 
Are we missing one more email option for newly Verified projects upon implementation? Shall we also adjust the email that the project receives when awarded with a badge to let them know that they got verified and now they have 3 months to post their first update?

Also with the current projects - how will we distinguish projects that need to be also notified about the policy change but they do regular updates already?

**Comment by NikolaCreatrix** [comment]
All email drafts are ready for review @WhyldWanderer

**Comment by WhyldWanderer** [comment]
Reviewed! They look good to me... Now we just need to send them out!
First one going out today!!

**Comment by WhyldWanderer** [comment]
Sending Schedule:

Current Makers

- [ ]  Coming soon! Verified projects will need to provide quarterly updates to keep status.

- [ ]  Reminder of policy change - you have 30 days to add an update or you will lose verified status. - September 15th

**Comment by WhyldWanderer** [comment]
Email sent!
We will look at the results on Friday to see if more projects have made updates.
