### ISSUE TITLE
Mandatory updates - Twitter announcement

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#807]
Announce policy change on twitter to inform current verified project owners to add updates!!

Celebrate projects that recently updated great updates to their projects, Tweet them to use as examples!

Making this issue now so I don't loose track - I will add the tweet info here and ping @laurenluz when it is ready to announce.

**Comment by laurenluz** [comment]
@WhyldWanderer - keep me posted on this! when it goes like I will be sure to tweet it.

**Comment by laurenluz** [comment]
maybe @c0ric0ri would be down to draft a thread summarizing the details?

**Comment by laurenluz** [comment]
I think we can draft this for next week @c0ric0ri - sent you a DM. The exact timeline for how long people have until they lose their status is undecided... but updates are officially "mandatory" or you will eventually lose your status.

I would make this a thread and have one part be targeted to existing project owners like "we don't want to lose, you! do it soon!"

And other parts be to donors.. a commitment to ensuring that they can trust "verified" projects (or something)
And to project... keep your donors in the loop to encourage them to continue supporting you! Past donors get emails FYI when a project updates.

**Comment by c0ric0ri** [comment]
Drafting here - https://docs.google.com/document/d/1E3Nx-Fum7HAqyhbR-2Xv9oxda9N1EWswWupOmXhdSfQ/edit

**Comment by WhyldWanderer** [comment]
@c0ric0ri The projects need to provide quarterly updates... so once every 90 days.

We do give them a grace period of 14 days which brings the total to 104 days but we have written 90 days so far in all emails and comms.

**Comment by c0ric0ri** [comment]
@laurenluz @WhyldWanderer this draft just needs a final review. 

Also, somehow we had crossover and @NikolaCreatrix [also wrote a draft.](https://github.com/Giveth/giveth-planning/issues/1013) I'm thinking perhaps we can use both, or adapt the one Nikola wrote for the other platforms and Discord.

**Comment by laurenluz** [comment]
Hey @c0ric0ri I just left some comments. Try to make the 1st tweet stronger & more interesting. I would avoid any mention of just general "quality of the dApp or platform.

have a look.

**Comment by laurenluz** [comment]
I combined ideas from the two threads and posted it today https://twitter.com/Givethio/status/1602322692459356160

**Comment by NikolaCreatrix** [comment]
@laurenluz saw it, retweeted & LOVE it! Yay!
