### ISSUE TITLE
Mandatory updates - Email Templates

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#809]
I think Rodri designed our current email templates found here: https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=2985%3A85583

We need a few additions for the mandatory update emails described in this issue:
https://github.com/Giveth/giveth-planning/issues/806

Maybe one that says

- [x] Reminder!

- [x] Coming Soon!

- [x] Don't Forget!

- [x] We need more information

Do you think you can help with these @rodricastillo9013 ?

**Comment by rodricastillo9013** [comment]
hi! I think it's finished, let me know if it's ok! I have left it in the same figma document, do you need me to create them in autopilot? @WhyldWanderer

**Comment by WhyldWanderer** [comment]
Looks great @rodricastillo9013!! Thanks so much <3

The figma is fine..
Can be found here: https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=2985%3A85583
