### ISSUE TITLE
Research bloggers and publications to add to outreach list

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#81]
Research bloggers and publications that report on fundraising / non-profit technology. Add to outreach list.

**Comment by ForestSoleil** [comment]
Ongoing List:
- CoinMonks (Dani has had a post republished here before) 
- The Block
- REKT
- Product Hunt
- Coin Desk
- Better Giving Studio, The Gates Foundation (Dani in communication with, copying Forest in)

To Do: 
- Dani to look at her email newsletter sign-ups and add those to list.
- Tommy to support in research.

**Comment by ForestSoleil** [comment]
2/9/21 Marketing check-in:
- WIP from Dani, tabs are open & will add comments to this issue.

**Comment by laurenluz** [comment]
2/19/21 Marketing check-in:
- This issue is basically: looking for bloggers to repost our blogs after we produce them
- Reach out to Jeff Emmett - he knows all these bloggers and can help us add to the list

Add to list:
- Common Stack

@Jeff-Emmett Do you think you could revise this list of blogs/publications (in the lists above) and see if there are any others you'd suggest us to add for outreach?

**Comment by Jeff-Emmett** [comment]
Happy to help!  Although I don't have direct contact with any of the above, I have a few to add to the list within our immediate network:
- Crypt0's News (Omar Bhan is a good friend of @GriffGreen and will def give airtime to the news!)
- The Blockchain Socialist 
- P2P Foundation Network
- I also have a number of engaged telegram channels I'd be happy to drop an announcement tweet of where to find more information

If you are able to draft a few copy/paste messages about the announcement that could serve as the basis for a message to some of these contacts, I would be happy to help reach out to those in my network!

**Comment by ForestSoleil** [comment]
Hey Jeff, thank you so much for your support! Someone awesome from our Marketing team, @magentaceiba is drafting that copy/paste announcement outreach message this week and will share it here when ready for you! =)

**Comment by WhyldWanderer** [comment]
Iive added the above list into our outreach spreadsheet
https://docs.google.com/spreadsheets/d/1Itb-64dyseTGElTOuA3CUozkLFmfFrK_pn80LfLOOG0/edit#gid=850659605
