### ISSUE TITLE
Co-Marketing Campaign w/ ICHI

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#810]
ICHI team wants to do some cross-promotion w/ Giveth using something called glean. Seems pretty cool & with the momentum from the Angel Vault launch, I think it's a good opportunity to grow our following and get people exicted about recent products.

@c0ric0ri pr @tropicalmangos can you champion this? Require someone to coordinate & keep things organized.

I screenshotted the PDF, but also, it is attached below.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5f7873f5-3e2b-4a85-86c6-5b4603af67a0)
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1b772d13-0f7b-4dfe-b653-40f100ae9ba5)

[https://app.zenhub.com/files/278726184/73337893-74f1-4e7f-af67-d78815859e30/download](https://app.zenhub.com/files/278726184/73337893-74f1-4e7f-af67-d78815859e30/download)

**Comment by c0ric0ri** [comment]
For preparing tweets:

https://docs.google.com/document/d/1nSJKNM_A_ynt4DnZSCgOxkz-plICWRMUjme2xpK1juM/edit
