### ISSUE TITLE
Update the Discord Guide

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#811]
This document is now outdated and needs an update:

https://docs.giveth.io/whatisgiveth/introDiscord

**Comment by clara-zi** [comment]
https://docs.google.com/document/d/1AMn-SWBv1wuU9kJieNSwatg_6H-bAgtJI7wo8JnzuX0/edit?usp=sharing

**Comment by clara-zi** [comment]
1st draft can be reviewed.

**Comment by c0ric0ri** [comment]
Hey @WhyldWanderer have you had a chance to review this? Do we need more eyes on this to tag?

**Comment by WhyldWanderer** [comment]
Sounds good! Thanks so much for taking the reigns of this @clara-zi

**Comment by clara-zi** [comment]
https://github.com/Giveth/giveth-docs/pull/161 for review @WhyldWanderer

**Comment by WhyldWanderer** [comment]
Hmmm Ive never reviewed a pull request before... how do I see the changes you made?
