### ISSUE TITLE
Adapt content from Fundraising 101 session to be included in 101 video course

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#812]
The video recording of the event can be found on the youtube here: https://youtu.be/QszCrqQNN7A

Or downloaded here: https://we.tl/t-uIoqBn20Xp

Bends said he would be willing to take on the editing of this one since theres no real recording that needs to be done.

Maybe there will be an opening/closing screen or something though? Im not sure if this has been planned out that much yet..

**Comment by scottbenjd** [comment]
[Fundraising 101 Video](https://drive.google.com/file/d/1uTiYOW7WK9G8X5eTIqjgCdsSuW87-2IZ/view?usp=sharing)

**Comment by ahmadabugosh** [comment]
I did some minor edits and uploaded the video here: https://www.youtube.com/watch?v=QO6iQgnKvfw

I'm thinking of including it as a bonus video at the end of the Project Donors 101 playlist. Wdyt @WhyldWanderer ?

**Comment by ahmadabugosh** [comment]
@WhyldWanderer sounds good!
