### ISSUE TITLE
HODL vault tutorial for our docs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#814]
Great feedback from @divine-comedian - this is really complicated.

Ichi is workin on updating their UI, once that is done, we should make a video, share it etc.

**Comment by ahmadabugosh** [comment]
Hey @laurenluz I recorded this video tutorial for the Angel Vault, let me know if you think it's good for the docs and social media: https://youtu.be/9zxSpsXdqjk

**Comment by oyealmond** [comment]
Oh nice @ahmadabugosh! Thank you :) 

I included your video tutorial as well [in the drafts. Uhoo](https://docs.google.com/document/d/1jHWyb1cxO7XGDHJ0fh4ae_IlWTveCbNQW1iSpLKsfvU/edit?usp=sharing)

cc @laurenluz @c0ric0ri

**Comment by c0ric0ri** [comment]
@ahmadabugosh @laurenluz what do we want to do with this, socials aren't necessary anymore I assume. Do we still want to update our docs?

**Comment by ahmadabugosh** [comment]
@c0ric0ri Maybe we should wait until we launch the new HODL (if that's what it's called) vault with them?

**Comment by divine-comedian** [comment]
> @c0ric0ri Maybe we should wait until we launch the new HODL (if that's what it's called) vault with them?

The vault is already live but let's see if it actually works before we advertise it 

also worth mentioning there is no rewards program for it so maybe it's not a strong message :thinking:

**Comment by franculio** [comment]
Hey @c0ric0ri is this something that we still want to update or put somewhere in the docs? or can this issue be closed?

**Comment by laurenluz** [comment]
@divine-comedian - have you ever used this? I'm not sure if adding content to our docs is worthwhile.

**Comment by divine-comedian** [comment]
I have used it once but maybe ICHI has docs we can use?

**Comment by franculio** [comment]
We have an [Angel Vault guide](https://docs.giveth.io/angelVault) in our docs. Is this what need to be updated? Or the HODL vault is something different?

**Comment by divine-comedian** [comment]
> We have an [Angel Vault guide](https://docs.giveth.io/angelVault) in our docs. Is this what need to be updated? Or the HODL vault is something different?

the Angel Vault is deprecated - maybe this needs to be mentioned somewhere. basically after the hack we noticed it wasn't performing very well even before so we chose not to restart it

this is the Giveth HODL Vault - I think it's just called a Vault though.
https://app.ichi.org/vault?token=0x900dB999074d9277c5DA2A43F252D74366230DA0

**Comment by oyealmond** [comment]
@divine-comedian, this didn't happened right? Should I move this to Notion?
