### ISSUE TITLE
Powerinside Tweet Thread

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#815]
We need to write a tweet thread telling this story a  h/t to cool people who audited the giveconomy

https://www.notion.so/giveth/powerinside-twitter-post-58fef525df0f4a77a389e7011b175c1a

**Comment by laurenluz** [comment]
I drafted this in notion and it's scheduled for next week

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1562082253336895490?s=20&t=1QGeURohxysAU41191QtHQ
