### ISSUE TITLE
Create Event Template 

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#817]
Lets coordinate our efforts around events better... hopefully this helps.

I created a category called events in the forum and will be pinning this event template to the top.

Am I forgetting anything? @laurenluz @Cotabe @NikolaCreatrix ?

https://docs.google.com/document/d/1xeWBCCXzPcLW-KX7AZuOAvsZxKBkFYIdeAlflYItcvk/edit?usp=sharing

**Comment by ahmadabugosh** [comment]
Hey @WhyldWanderer I think a major part that would help us that I recommend is to have a way for people to RSVP to an event, so they will automatically get notified when the event is about to start and it's added to their calendar (without us having to send reminders.  This would also allow us to estimate how many people will attend an event, get more external contacts as a lead magnet and have an easy way to send event recaps post event. 

At the very least we should create a sesh bot link on Discord for every event so they can add the event to their calendar, and even consider using something like [Eventbrite](https://www.eventbrite.com/) for external events.

**Comment by WhyldWanderer** [comment]
I know that people can RSVP to events through Sesh on Discord, and they can mark interested on our discord events, additionally they can follow our calendar on Google.

The idea of this template is for communications and collaboration on shilling. 

The event template is now live and you can see better what I mean @ahmadabugosh . 

This is a template where the facilitator can have all of the info for the event and a completed ocmmunications plan as to what they need from the comms team id. twitter posts, blog posts, emails, etc and this information can easily be plugged in by a comms star. I noticed that we had had a few events that could have been communicated better but there was a lack of information from the organizers which made it hard to create tweets etc. This way all of the information is in once place and thevarious teams (comms, community, etc) can coordinate between wgs in a streamlined fashion. I hope this is helpful!!

Closing this issue as this template is now live. https://forum.giveth.io/t/event-planning-template/762
