### ISSUE TITLE
Donor Survey Outreach - Previous Donors

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#818]
Hey Community, 

There are over 340 previous donors (_*that have donated at least 1 DAI worth_) to the Giveth platform, that I would like to perform some outreach (via email) to about taking our Donor Survey, but before I do, I'd appreciate any feedback on the body of the email that I am about to send. 

Please take a moment to review and offer some suggestions, comments or criticism. Thanks! 

"Hey Giveth Donor AKA, Our Philanthropy Bestie,

As you have probably seen in the past, we here at Giveth love us some evolution, and there is no better way to evolve our crypto philanthropy platform then going straight to the source, YOU! And since your heart is so giving (as well as your wallet 😉) all we are asking for is a couple minutes of your time…which we will even be rewarding you for.

Simply, click here (*hyperlink,) follow the instructions, and take the Giveth Donor Survey for your chance to win some Giveth $nice tokens, and more importantly, help us build a stronger platform for the Future of Giving!

Much love, 

Jake
Giveth Outreach & Partnership Manager"

**Comment by c0ric0ri** [comment]
@c0ric0ri @ahmadabugosh to review this text and give ok

**Comment by SnakeGH** [comment]
Hey @c0ric0ri and @ahmadabugosh any luck getting to review by chance? would love to start outreach on this. Thanks

**Comment by ahmadabugosh** [comment]
Hey @SnakeGH I made some small changes here: [https://docs.google.com/document/d/1O0eiopsAoU95nj1Y9RUohRuglBHIbzlIBVXSeY02u_E/edit](https://docs.google.com/document/d/1O0eiopsAoU95nj1Y9RUohRuglBHIbzlIBVXSeY02u_E/edit). I think this is ready to send out, so I'll schedule to send it out today or tomorrow.

**Comment by SnakeGH** [comment]
@ahmadabugosh love it, I made a couple typing grammatical fixes as well as added to my signature, but otherwise thanks Rockstar! Keeping me posted on pushing it through Autopilot.

**Comment by c0ric0ri** [comment]
Hey @SnakeGH @ahmadabugosh I added some changes in as well to clarify what feedback we're looking for and fixed some grammatical things as well. Would love to see those adapted if you agree, and then I'd say this is good to go!

**Comment by ahmadabugosh** [comment]
Just sent it! Closing this issue.
