### ISSUE TITLE
Donor Outreach - Prospects

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#819]
Hey Giveth Peeps, 

I have started to compile a list of possible new donors to the Giveth platform via crypto leaderboards and other web3 outlets, but before I perform outreach, I wanted everyone to review my google shared doc and ensure there are no problems with the people on it (or offer insight if you know them)...as well as offer any suggestions, comments or criticism for the body of my future email. Thanks!

Here is the link to my list so far: 

https://docs.google.com/spreadsheets/d/1oPdeNDDvOT5wrLGqo1LyK8assv3u2M_jsfTizz3hLvM/edit?usp=sharing

...and here is the body of the email I'm proposing to send: 

"GM - 

Hope this message finds you well! Reaching out today because I’ve noticed how important generosity is to you, especially when it comes to crypto, and I thought you may be interested in checking out what we're building over here at Giveth, if you haven’t done so before. 

If you aren’t familiar with us, Giveth is a zero-fee fundraising platform for for-good projects, where 100% of every donation goes straight from the donor’s wallet to the projects. Moreover, we reward donors that donate to verified projects with $GIV through a program called “GIVbacks”. And even more, Giveth facilitates direct P2P donations on Ethereum Mainnet, as well as on Gnosis Chain to take advantage of extremely low gas fees.

If this sounds like something you’d like to check out, just head over to our website (*insert hyperlink) or fire back a response and we can chat in more detail. 

Thanks for your time, 

Jake
Outreach & Partnership Manager
jake@giveth.io
Twitter: @GivJake"

**Comment by c0ric0ri** [comment]
@Cotabe can you please check this list?

**Comment by Cotabe** [comment]
I love the email! It has all the relevant content and is very straightforward. But maybe we we can highlight more the rewards, something like:

 Moreover, we reward donors that donate to verified projects with up to 75% fo their donation back on $GIV through a program called “GIVbacks” (link to info: docs or tweet)

The donors database that you put together is amazing. But I would be concerned of sending an email without their permission at least as a first touch point. From my experience with investors (not donors, but might be similar). They get tens or hundreds of proposals weekly from people that don't even know their investment (in this case donation) thesis. What I have heard them say is that they prefer a quick contact showing you know their investment thesis. For example:

Holly Grimm has her twitter DMs open. In a quick research I realized she is both software developer and artist. She supports several projects Redmption DAO, Kolectivo, ReFi Dao, impact certificates and the regen movement (https://twitter.com/johnx25bd/status/1548329312352251905?s=20&t=IHmLjOiLnVlNuWg3bGFxyQ). I would suggest approaching by linking several of her tweets, maybe even engaging in a few & then maybe send a DM like this

a) Not salesly option, but building a relationship and asking about her.
"Hey Holly, it's so refreshing to see the work you are doing on the blockchain4good space. I work at giveth.io, I'm curious to know what is important to you when supporting a project"

b) Straight-forward 
"Hey Holly, it's heart warming and admirable to see the support you gave to projects on the last Gitcoin round. I work in donors relationships at giveth.io, I'm curious to know what is important to you when you donate to a project, if you don't mind my question"

I know this approach is way more time consuming, but for the amazing list that you collected. With donors above 10K, I think it's totally worth it to have a more personal approach.

**Comment by SnakeGH** [comment]
@Cotabe absolutely legendary response and looking forward to that call to dig in even deeper

**Comment by SnakeGH** [comment]
tweaked the message and been sending this out for most emails: 

Hey (*potential new donor), 

Hope you’re having a great day! 

I know this message is out of nowhere and you don’t know me, but I felt the need to express how heartwarming and admirable it is to see your support via (*location where I found their contact) during the last round of projects, and since I work in outreach over here at Giveth.IO, I’m very curious to know what is important to you when you are deciding on a project to donate (if you don’t mind me asking?)

I am always trying to improve our philanthropy platform and your response would be very insightful and helpful. Thanks 😊 

Respectfully, 

Jake
Outreach & Partnership Manager
jake@giveth.io
Twitter: @GivJake

**Comment by SnakeGH** [comment]
and for Twitter DMs this is the message Ive been going with: 

Hey (*potential new donor), hope you’re having a great day! 

I know this message is out of nowhere and you don’t know me, but I felt the need to express how heartwarming and admirable it is to see your support via (*location where I found their contact) during the last round of projects, and since I work in outreach over here at http://Giveth.IO, I’m very curious to know what is important to you when you are deciding on a project to donate (if you don’t mind me asking?)

I am always trying to improve our philanthropy platform and your response would be very insightful and helpful. Thanks 😊 

Jake
jake@giveth.io

**Comment by SnakeGH** [comment]
This project will be never ending, speaking of find new donors and outreaching, but this specific issues of requesting assistance with my outreach emails is good, I believe, so going to consider it closed for now
