### ISSUE TITLE
Write Medium blog “Outlining Core Functionality & Pro Features of Giveth TRACE / What has been Successful”

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#82]

**Comment by ForestSoleil** [comment]
Also add Ashley as assignee when she has been added to GitHub.

**Comment by ForestSoleil** [comment]
2/5/21 Update on Marketing call:
- Who is the audience for this blog?
- Prioritizing blogs is important. Is this something we need to have published before the launch? **No. Focus on Giveth 2 for pre-launch content.**
- This feels like an article on the Giveth 2 blog. _Are you wondering where those cool features of Giveth 1 are? Have no fear, here's where you can learn all about them._
- Fast Follow call-to-action button "Are you looking for the Beta Version 'Name'?" and have people easily able to go to Giveth 1 features list article.

**Comment by laurenluz** [comment]
2/19/21 - Not essential before launch

**Comment by ForestSoleil** [comment]
3/2 Marketing campaign:
- Post launch piece to highlight the pro features of Giveth TRACE that users can still find and enjoy. 
- This cannot be published until Giveth TRACE has been announced and we transition over to the new platform. 
- Blocker: Need onboarding documentation (how to make a milestone, etc.) to be current and actionable for reference before publishing this article.
- Dani will begin hacking on this.
