### ISSUE TITLE
Tweet thread R17 verified projects

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#822]
Hi there, so sorry I am sending this late. I can honestly say I didn't manage my work well during last week and my time in Prague...

This round we had many many projects, so this time I picked 6 of them trying to keep it diverse. 

@laurenluz @c0ric0ri 

Draft ready for tweet here:

https://docs.google.com/document/d/1zyZ1wJNFla3Q049rn_-cwaj_Vqlcr4zN67ZCrr-7hiA/edit?usp=sharing

**Comment by laurenluz** [comment]
it's awesome @NikolaCreatrix and no worries! I thought you were on vacation :)

love the projects, and great thread. made some small comments for some grammar tweaks/extra context. have a look.

**Comment by NikolaCreatrix** [comment]
Thanks @laurenluz :) a lot, I did some corrections, let me know if things sound better and make more sense now🙏

**Comment by laurenluz** [comment]
Excellentttttt!!!! 🚀  Thanks @NikolaCreatrix

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1560250668035760134?s=20&t=H4BAgAm77Ecmwpq9c7kcwA
