### ISSUE TITLE
$nice token tweet thread

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#823]
wil be announcing PFP!

@divine-comedian drafting & to share w/ @laurenluz for feedback after

**Comment by divine-comedian** [comment]
locked and loaded 

thanks for improving the draft tweet thread. 

I suppose we'll see this up on twitter sometime next week

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1559525910172389376?s=20&t=OxtDYAF1B9K1s9qlb05JyQ
