### ISSUE TITLE
Complete Donation Flow overview Video (to embed in the Giveth dApp)

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-planning#825]
Explainer Video - Project Donation Pg

- Overview of whole process
- “How to donate”
- Timestamps
- How GIVbacks work
- GIVbacks- what happens after donation, how it works
- GIV Calculator- how GIV works 

Video Overview here
https://www.loom.com/share/b098413ad7674261920698e36b4f1ac8

**Comment by ahmadabugosh** [comment]
Hey @tropicalmangos , thanks so much for the Loom video, I really like your approach and the donor workflow you mentioned! 

The way I see it, there are a few things for us to improve on:

1) Adding elements / videos etc. to the dapp @MoeNick can help with them 

2) Email workflows. I think that's something we can definitely improve on within Autopilot (our email client). Let's bring this up in the next comms call. The trick is we don't want to overwhelm people, but I think there are definitely things we can do to 'drip' more information to them. 

3) For educational videos, I definitely think we need to improve on them and your comments are great. However, we do mention in the video you linked how to get xDAI from a faucet (if you don't have any xDAI). You do have a point though that it can be confusing for beginners. 

What I suggest is to have a video that goes through the entire process from scratch as a walkthrough. So for example, I'll start with a completely blank wallet and show how I donate on Giveth step by step (we can add that video at beginning of the [Donor Playlist](https://www.youtube.com/playlist?list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ), then the videos that come after would go into more detail and explain what happened. I can record this one :) 

Wdyt?

**Comment by laurenluz** [comment]
Hey @ahmadabugosh love all your thoughts, and I'll just let you and @tropicalmangos hash through most of this. Just wanted to leave a small comment re: donor video:

While I think there is value in having a video that goes from have a blank wallet through everything to donating... I think a lot of users who come to our site probably already have a crypto wallet.

I think for a video we actually add within the donor flow, it would be good to have one explaining how to donate (assuming you have funds already) and then explaning about GIVbacks, verified projects... When you should expect your GIV and how to use it to get more involved... I think this would be really valuable.
