### ISSUE TITLE
Gitcoin GR15 Prep

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#826]
GR15 Starts Sept 7, and we should update our grant listings by Sept 3! I will be away, so I'm leaving this in your capable hands @danelsuga @c0ric0ri 

We need:
- [x] to draft & update our Giveth.io listing (we should mention recent developments, especially like "improving the project verification flow so that it's part of our dApp now" ( @NikolaCreatrix or @MoeNick can explain) and other things we recently added & improved on the dApp!)
- [x] to draft & updated out Giveth TRACE listing (this shouldn't need much change from the last time, but a small edit so it shows as "recently updated")
- [ ] create nice GR15 donation memes
- [x] send an email message our via gitcoin grants to our previous donors
- [ ] draft tweets

Here is the email I just got w/ GR15 details 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/7b947a48-cf89-4baa-b685-73dfec2a21a8)
GR15 is fast approaching!
 
We’re excited to announce that our 15th Grants Round is right around the corner!

 

It all begins Sept. 7, and runs through until Sept. 22. Mark your calendars for the biggest funding & building event in Web3! 

 

This round, we’re encouraging all grantees to get ahead of the pack and submit their grants BEFORE Sept. 3. Getting prepared early will allow you to focus on building community hype for your grant and get EVEN MORE support during the round! Check out all you need to know below.

A brief overview for GR15
 
We will, once again, host a Main Round, multiple Cause Rounds, and multiple Ecosystem Rounds. One difference for this round is that, pending governance approval, we’ll be decoupling the main round from our side rounds. This means your grant could be approved into a side round, without meeting the main round criteria. Note that this will not impact existing approved grants.

Main Round
 
The Main Round is our longest standing Gitcoin Grants in support of open source software projects in web3.

 

Projects that meet the criteria for main round eligibility are open source, haven't raised VC funding over $500k, don't have a token, are not selling NFTs, are not advertising tokens/NFTs through the grant, and are public goods overall.

Cause Rounds
 
We believe that funding projects that straddle the intersection of web3 and traditional causes can change our world for the better.

 

The GR15 Cause Rounds showcase projects using web3 to build & fund solutions related to 4 key social and environmental causes:  Climate Solutions, Crypto Advocacy,  DEI (Diversity Equity & Inclusion), and DeSci (Decentralized Science).

 

1. Climate Solutions

 

The Climate Solutions round enables communities to build and fund a broad variety of digital and real-world climate solutions. 

 

2. Advocacy - Crypto Regulation

 

The Crypto Advocacy round is focused on building support for trailblazing organizations at the forefront of good crypto policy and in defense of the open web. 

 

3. Diversity, Equity and Inclusion (DEI)

 

The DEI Round enables communities to build and fund projects that advance DEI in web3, ensuring individuals from all backgrounds have an equal opportunity to participate.

 

4. Decentralized Science (DeSci) [NEW]

 

The DeSci round seeks to expand and distribute humanity's shared knowledge. It supports projects that are reimagining the incentives, culture, and infrastructure for research using web3 tools and technology.

 

As we finalize the details for these rounds, more information will be released on round eligibility criteria and matching funds available. Stay tuned!

Ecosystem Rounds 
 
Ecosystem Rounds are focused on funding grants that support the objectives of a specific ecosystem. Ecosystem Round grants typically focus on accomplishing one or more of the following for their respective ecosystems:

Usability – improving UX
Community – growing the ecosystem
Tooling – improving the developer experience
Governance – building tools and enhancements for on-chain governance
Our first set of confirmed ecosystem partners for the round are:

Polygon (@0xPolygon)
Unlock Protocol (@UnlockProtocol)
Web3 Social (@realmasknetwork)
ENS (@ensdomains)
Aurora (@auroraisnear)
Ethereum Infrastructure (@coinbase / #coinbasegiving, @iearnfinance)
Open Gaming (@OPGames_, @G7_DAO & others)
Lootverse (@lootproject)
ZK Tech (@ZKValidator & others)
Celo (@CeloOrg)
[NEW!] a16z (@a16z)
[NEW!] Greater China Community (@PlanckerDao) 
 

More partners to be confirmed alongside round eligibility criteria in the coming weeks!

Important Info for Grants Submissions
 
We’re inviting you to get ahead of the pack early by preparing you grant now! 

 

New grant owners: check out this handy grantee onboarding guide that walks through a step-by-step breakdown of how to create your grant. 

 

Current grant owners: you will need to update your grant in order to maintain an ‘active’ grant status and be eligible to receive Matching Pool funding. 

 

What to include in your grant updates:

Updated project roadmap

Progress update including metrics

New/updated social media links

New logos and/or branding assets 

 

Need assistance? We’ll be happy to lend a hand.

 

If you need support creating, updating or optimizing your grant for funding success, please check the NEW Grantee Onboarding Document or the Grants FAQ page for more info. If you still have questions, please feel free to reach out in the #grants-support channel in our Discord Server! 

 

Our grantee experience team will also be hosting a series of GR15 Community Q&A Twitter Spaces to support notable and effective grant creation - keep your eyes peeled on @Gitcoin for more info.

 
Grants Rounds wouldn't be possible without your support. Thank you!

**Comment by danelsuga** [comment]
I'm working on this now.

**Comment by danelsuga** [comment]
Can I get some help on this part please @NikolaCreatrix @MoeNick?

Lauren says to mention: "improving the project verification flow so that it's part of our dApp now" (@NikolaCreatrix or @MoeNick can explain)"

**Comment by danelsuga** [comment]
I'll take care of project updates and will bring the issue up in the next comms call for more support on these items asap:

- create nice GR15 donation memes
 
- send an email message our via gitcoin grants to our previous donors
(https://docs.google.com/document/d/1tC7AiyYwzxSX3hbpQSaT_zKqnzHmu3xYRuS7wKRtgFg/edit)

- draft tweets

@ahmadabugosh 
@SnakeGH 
@tropicalmangos 
@c0ric0ri 
@oyealmond 
@scottbenjd 
@Cotabe

**Comment by danelsuga** [comment]
I'll take care of project updates BUT NEED IMMEDIATE SUPPORT to establish a list of relevant updates that occurred in the last three months. (For example, does the Angel Vault get mentioned on Gitcoin? I don't think so but need input.)

I will also bring the issue up in the next comms call for more support on these items asap:

- create nice GR15 donation memes
 
- send an email message our via gitcoin grants to our previous donors
(https://docs.google.com/document/d/1tC7AiyYwzxSX3hbpQSaT_zKqnzHmu3xYRuS7wKRtgFg/edit)

- draft tweets

@ahmadabugosh 
@SnakeGH 
@tropicalmangos 
@c0ric0ri 
@oyealmond 
@scottbenjd 
@Cotabe 

It's important to have an accurate description of updates by the end of this week if anyone can help out! Thanks!

**Comment by ahmadabugosh** [comment]
Hey @danelsuga looking at the last few newsletters, I would say the top highlights from the last 3 months are:

- Launch of the $nice token 
- Giveth Angel Vault 
- ETHBarcelona how we were a sponsor and helped onboard people on the ground
- August 2022 was our highest donation month with $320K donated
- Top projects. For example, you could mention how https://giveth.io/project/expedition-grundeinkommen raised over $400k

**Comment by danelsuga** [comment]
You are the best @ahmadabugosh !

**Comment by oyealmond** [comment]
@danelsuga checking this right now, is there any specifics that I could support you with around the GR15?

**Comment by danelsuga** [comment]
Thanks @oyealmond ! With @ahmadabugosh's feedback, I think the urgency has passed for this week. I'll be able to do the description. (But actually there is still the issue of improving project verification flow. Not sure if you or some one can help? I need to post the description tomorrow, so it'd be great if anyone could support that. 

Meanwhile, I'll do the description for Friday, then you can check back and maybe help create a tweet thread and/or memes? I'll be able to do the donor email part. Thanks!!!

**Comment by oyealmond** [comment]
Around the new verification flow, I wrote this doc yesterday around the new verification process improvements - 
Basically it was removed the Typeform for a new in house form, and now email and social media verification steps were added to gain reliability. Is still need to be reviewed 
 https://docs.google.com/document/d/1Th8mIV3QZYXhEexQSKp2P7QLiWju0QyLQ52tEV4S5lE/edit?usp=sharing 

Lmk if this is useful, @danelsuga

**Comment by danelsuga** [comment]
@oyealmond oh wow. Thank you. This teamwork is so fabulous. Yes, this is great! Thank you!!!

**Comment by danelsuga** [comment]
Quick Q @oyealmond : does your verification flow doc have a Github issue? I can't find it. I took the liberty of doing some quick edits while I was reading :) and I wanted to be able to let you know in the appropriate Github issue! Thanks. If there is no issue, go ahead and make one (or I can). If there is an issue, just tag me in it. thx

**Comment by oyealmond** [comment]
Loved your edits @danelsuga  thank you! Here it is https://github.com/Giveth/giveth-planning/issues/841#issuecomment-1231894794

**Comment by MoeNick** [comment]
> Around the new verification flow, I wrote this doc yesterday around the new verification process improvements - Basically it was removed the Typeform for a new in house form, and now email and social media verification steps were added to gain reliability. Is still need to be reviewed https://docs.google.com/document/d/1Th8mIV3QZYXhEexQSKp2P7QLiWju0QyLQ52tEV4S5lE/edit?usp=sharing
> 
> Lmk if this is useful, @danelsuga

Hey @oyealmond Thanks for the doc, I think we should use real screenshots, with real projects and for all steps, this flow has lots of details that users will love them. If Im not wrong  I sent these screenshots to Cori and I was not thinking this will get used from private chats :)

**Comment by MoeNick** [comment]
You can simply define a test project with full details and good examples which seem to be real, then simply open the project and click on Verify Your Project button (while connected and signed in) then you are redirected to the flow and you can fill all data needed, I think @NikolaCreatrix also did it several times before so she can help a lot to provide help. :)

**Comment by oyealmond** [comment]
Thank you @MoeNick! The guidance of @NikolaCreatrix would be great on this matter 🙏🏻

**Comment by oyealmond** [comment]
Hey @danelsuga great to hear it :) 
Im not a 100% align around the memes we need... Maybe @c0ric0ri @ahmadabugosh have better feedback around this?

**Comment by ahmadabugosh** [comment]
@oyealmond I think it's just any meme we can think of that mentions GR15 and ties it with Giveth. For example, previously we did stuff like [this](https://twitter.com/Givethio/status/1504527321830731783) or [this](https://twitter.com/Givethio/status/1466059527388909570)  or [this ](https://twitter.com/Givethio/status/1470391239321268236).  I would also check in our memes discord channel for inspiration

**Comment by oyealmond** [comment]
I think would be great if maybe we can create a quick comms campaign as the GR15 ends on the 22th and we still have not posted anything yet. Maybe we can gather Monday 12th to come w a bunch of ideas and start asap comms? @ahmadabugosh

**Comment by ahmadabugosh** [comment]
Sounds good! To make it easier, how about you make a brainstorming Google doc where we can put ideas and we can discuss it on Tuesday (during or right after our comms meeting if we don't have time, since it's a little hard for us to organize a meeting with everyone in such short notice)

**Comment by oyealmond** [comment]
Yes :) @ahmadabugosh
Im really not good at meme creation, but I'll try my best
 https://docs.google.com/document/d/1mtIFmycUghOXFO9Co0CfgnDZ6-vsw1xVJXG2DZttCLw/edit?usp=sharing

**Comment by danelsuga** [comment]
How's the meming and tweeting going for GR15 @oyealmond @ahmadabugosh ? I would say don't worry about memes if you're not up to it, but it'd be great to get the tweets out!

**Comment by danelsuga** [comment]
How's the meming and tweeting going for GR15 @oyealmond @ahmadabugosh ? I would say don't worry about memes if you're not up to it, but it'd be great to get the tweets out!

**Comment by c0ric0ri** [comment]
@Cotabe @oyealmond Let's quickly draft messages today for:

- General to post to Discord and other places
- LinkedIn, Facebook

@c0ric0ri to focus on Twitter format today

**Comment by c0ric0ri** [comment]
Tweet drafts are here! The first one is ready for review @danelsuga @ahmadabugosh @WhyldWanderer 

https://docs.google.com/document/d/1rSezVbbuPQO8szMQq1k7QtvKQCLjlCYV-xNtbdra5Q4/edit

**Comment by danelsuga** [comment]
Good work @c0ric0ri !

**Comment by oyealmond** [comment]
Girls @danelsuga @c0ric0ri I made some copies for Facebook/Discord, can you check the out? 
https://docs.google.com/document/d/1rSezVbbuPQO8szMQq1k7QtvKQCLjlCYV-xNtbdra5Q4/edit
I used the same doc you opened Cori

**Comment by Cotabe** [comment]
@danelsuga @c0ric0ri @laurenluz @oyealmond 

I did my best to create a simple, yet comprehensive narrative of our vision. That can be implemented in different formats (twitter, LinkedIn facebook).

I'm super biased, but this is where I would like to direct potential donors. I would love to get your opinions before working on customizing the content for different platforms.

**Comment by Cotabe** [comment]
@danelsuga @c0ric0ri @laurenluz @oyealmond

I also suggest to add the following activities to this issue:

- [ ] Send announcement on Discord tagging everyone asking to support our grant and linking our best piece of content. Maybe also to chill Giveth to GR15 donor communities.

- [ ] Ask contributors to maybe through a discord post tagging unicorns to (1) support Giveth GR15 project, (2) Dedicate some time this week to find communities to shill our Grant (in twitter, TG, Discord or wherever they see fit) and (3) Think about ways to go better on GR15. We are on a bear market and it's on our best interest that Giveth does well.

Other options to consider... send email to our donors, makers with a quick message to support our grant and a link to our best piece of content.
