### ISSUE TITLE
Zodiac Wiki

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#829]
Steps to approach this:

- research the page to see where Giveth can best contribute
- create task list of suggested content to be created / reused and submitted (e.g. Praise system, tools, frameworks, etc)

**Comment by franculio** [comment]
I've been looking around the Zodiac Wiki site and they have a contribution guide which basically explains there's 2 ways of contributing to the website:

1.PATTERNS - The project is trying to create a collaborative pattern language for DAOs where each organization can upload a specific challenge or problem they've encountered with the respective solution applied. This is where maybe we could upload something about the Praise system how it works and what problem solves. Here’s an example of an pattern uploaded: 

![Captura de pantalla 2022-08-24 a las 13.19.56.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/18cea23d-27ef-45d3-8f51-e56846ae4167)

2.LIBRARY - The zodiac.wiki Library is a collectively curated selection of texts related to decentralized governance. Ranging from books to hyperlinks, the library items are considered by the Zodiac ecosystem to be rich, informative, or historically important. Here we can give a Giveth brief description and put a link to our “handbook” (which is our Docs site). Here's is an example of another DAO in the Library:

![Captura de pantalla 2022-08-24 a las 13.20.20.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/4e3a76dd-9d1b-423b-bd46-081a9f8ea6c8)

For the brief description I think we could use the first two paragraphs of the Covenant section in the docs:

The Giveth DAO is a self-governed organization dedicated to revolutionizing philanthropy and "Building the Future of Giving" by bridging the Ethereum and non-profit worlds. Giveth's mission is to build a culture of giving that empowers and rewards those who give - to projects, to society, and to the world.

_Giveth envisions a future in which giving is effortless and people all around the world are rewarded for creating positive change. The Giveth platforms aim to be free for donors and projects, globally accessible and self-sustaining. Giveth aims to facilitate the efficient, transparent flow of funds directly to where they have the most positive impact._

Let me know if you think this is ok and I can go ahead and create the Library item for Giveth and we could give a little bit more thought about what we could add to the patterns section. @c0ric0ri @clara-zi @SymSL

**Comment by franculio** [comment]
@danelsuga

**Comment by danelsuga** [comment]
Thanks for taking this on, @franculio ! 

1) As for patterns, presenting Praise there would be quite ambitious. Perhaps it doesn't have to be though. The more I think about it, the more it seems quite relevant and also important to share. I suppose it could be presented in a general way, with the full package  proposed by the Commons Stack suggested in there somehow. Praise is obviously a fabulous tool system that every DAO should adopt!

2) For the library, linking to the Giveth handbook makes sense. And I think using that description of Giveth works well too.

**Comment by franculio** [comment]
Thank you @danelsuga ! 

I'll go ahead and make that entry on the library which is very simple, and regarding the praise system I'll work a bit more on it and post something here before getting it into the Zodiac Wiki.

**Comment by c0ric0ri** [comment]
hey @franculio just checking in on the status of this issue, is there still more than needs to be done or can it be moved to completion?

**Comment by franculio** [comment]
Hey @c0ric0ri ! There's still the praise system solution to be added to the patterns section of the ZodiacWiki. I don't think this is urgent and I wanted to first get involved in the upgrade that's happening this week to get a better idea on how to put it in. Should I move this to done then? or to backlog until I get back to it?

**Comment by c0ric0ri** [comment]
@franculio let's close this issue, and would you mind starting a new issue to add Praise to the ZodiacWiki? Then we can keep it in the Backlog until we're ready to work on it

**Comment by franculio** [comment]
@c0ric0ri Ok. I will create a new one. Thanks!
