### ISSUE TITLE
Communicate with past Giveth projects to invite them to participate in soft launch by adding their projects

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#83]
Ashley as assignee when she's been added to GitHub.

**Comment by ForestSoleil** [comment]
2/5/21 Marketing call update:
- Someone to build relationships with past project donors. Give them a personal update on what's happening with Giveth. Explore whether they have a blog, newsletter, partners list on their website, or at minimum be willing to retweet or share about our Giveth 2 launch.
- Though we don't have a TON of information to share right now, we can be strategic and build excitement with the minimal information we do have.
- There are around 10 projects to reach out to. 
- Ashley to draft sample reach out email, share here in comments for copy review, then customize & make personal for each project.
- Ashley - sample email drafted by Sunday community call.

**Comment by WhyldWanderer** [comment]
@ForestSoleil are we reaching out to past projects or past donors?.. 
Im under the impression that we will be reaching out to the projects for interviews

**Comment by WhyldWanderer** [comment]
Heres a rough draft... It seemed most logical to gear toward the projects rather than the donors. I would like to add more about the new features once theyre confirmed and maybe add links to other blog posts etc.

Hello fellow Giveth user

The Giveth community appreciates your participation and use of our platform. We couldn't have come this far without you!

Giveth has some big news in store! We are geared to launch our new application to the public and are looking for current Giveth campaigns and communities that would like to participate by adding a project there.

The functionality has been streamlined and is very user friendly. As you and others begin to use the platform we can add features based on your needs. We appreciate your feedback! You can read about the new platform functionality here (link to blog post)

So we cordially invite you to once again join us in building the future of giving.
Get started now at giveth.io!

**Comment by ForestSoleil** [comment]
- Intro is a placeholder; replace with custom intro based on person's name & project. Or, we can create something fun and informal. Ideas: Giveth Lights, Givethers, Friends & Fans of Giveth, Makers (projects)
- Change 2nd paragraph to "Giveth has some big news to share!"
- Hyperlink "by adding a project here" to where user can do that on new application.
- Add in sentence about how to submit feedback.
- If FIAT donations are not official by time we initiate communication with these folks, leave it out and once it's official, we can always reply and let them know about this "awesome new feature!". 
- ^ Can say "FIAT currency is coming, but still in development and not yet released. Stay tuned!" (...something along those lines)

**Comment by Danibelle** [comment]
Greetings from the family at Giveth!

It’s an exciting time in the EtherSphere, and DApp development has been accelerating exponentially this year for everyone. For us, Giveth took a brief hiatus to reevaluate our direction, then resumed buidling on a new, cleaner version.

So the time has now come to share an update, extend an invitation, and offer to you our gratitude as a member of the Giveth Galaxy.  We are geared to launch our next major release to the public and as one who has reached out to us before, you are on our soft launch invite list to add a project you love to the Giveth donation application (DApp).  

Projects added now will be featured in our launch campaign for charitable giving, seen by donors around the world who seek regenerative philanthropy options, and able to receive donations instantly!

The functionality has been streamlined and is very user friendly. As you and others begin to use the platform we can add features based on your requests. We really appreciate your feedback! You can read about the new platform functionality here (link to blog post)

So we cordially invite you to once again join us in building the future of giving.
Get started now at giveth.io!

**Comment by laurenluz** [comment]
2/19/21 Marketing Call Update:

- Ashley waiting to receive login info for gmail
- Ashley to blast this email out to projects once received

**Comment by WhyldWanderer** [comment]
https://docs.google.com/spreadsheets/d/1Itb-64dyseTGElTOuA3CUozkLFmfFrK_pn80LfLOOG0/edit?usp=sharing

**Comment by WhyldWanderer** [comment]
Email sent to emails listed on Projects tab of above spreadsheet 2/21/21

**Comment by magentaceiba** [comment]
This could use a follow-up email if we want to really encourage these projects to make a listing. If post-launch, send with link to giveth.io and hyperlink to Lauren's medium post to read more context.

**Comment by ForestSoleil** [comment]
3/5 Marketing update:
- email content above. outreach in progress. 
- outreach spreadsheet being tracked with outreach dates
- should we communicate with people more than once if they haven't responded? --> Not a top priority, but send out a second reminder email in a fresh way in a few weeks if we don't see their project added.
