### ISSUE TITLE
Tweet thread R18 Verified Projects

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#830]
Create a tweet thread for newly verified projects for round 18

**Comment by NikolaCreatrix** [comment]
Hola hey happy Friday, these are the outstanding heroes of round 18 @laurenluz 

[Tweet thread R18 Verified Projects](https://docs.google.com/document/d/11uxhy4CGO3xSb5tjVxRkLYsvI_h0TqsKbqrr_PhkAo0/edit?usp=sharing)

**Comment by laurenluz** [comment]
Thanks Nikola ! FYI @c0ric0ri :) you can do some qa and then pick a good day in the next two weeks to tweet this one.

Since we just did the verified projects for 17 on Thurs, pick some day late next week or the following

**Comment by c0ric0ri** [comment]
Reviewed and will plan for it to go out early next week!

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1564608353564872721?s=20&t=JwZ8ftw5BgFehRv5kGl8zA
