### ISSUE TITLE
Forum Post: Open Call for GIVpower Delegates

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-planning#834]
Following Balancer's example here: 

https://forum.balancer.fi/c/delegate-citadel/14

**Comment by laurenluz** [comment]
Hey Katya - what happened with this? It would be good to start collecting delegates when we launch staking & locking on tuesday

**Comment by laurenluz** [comment]
@tropicalmangos I made some comments/suggestions to your forum post in the doc. Can you try to fix 'em sometime early tomorrow so I can give it one more review before it gets posted Monday night/Tuesday morning?

Also please talk to @divine-comedian or @WhyldWanderer on the best place/way to post this in the forum and how to do the categories, etc.

https://docs.google.com/document/d/1JmajezLVYu0rIjKuTLlI-UPHAcKdhrP5eVCH1iSn5i8/edit#

**Comment by divine-comedian** [comment]
category already exists - just awaiting content 

https://forum.giveth.io/c/community/givpower/15

**Comment by divine-comedian** [comment]
Template is done @tropicalmangos:

![image](https://user-images.githubusercontent.com/67759413/193677869-d64b2812-986f-4488-ad5f-6cdc1724e238.png)

FYI I made you the owner of this post - so you can put in your content there 
https://forum.giveth.io/t/givpower-delegation/779

**Comment by laurenluz** [comment]
@divine-comedian - you ROCK! Is there an easy link that goes to creating a post w/ that template... so we can link it like "please nominate yourself by creating a post via *this template*"?

@tropicalmangos - I finished adding suggestions in the google doc - please incorporate them & post when you're ready :D

**Comment by divine-comedian** [comment]
> @divine-comedian - you ROCK! Is there an easy link that goes to creating a post w/ that template... so we can link it like "please nominate yourself by creating a post via _this template_"?
> 
> @tropicalmangos - I finished adding suggestions in the google doc - please incorporate them & post when you're ready :D

If they click create topic inside of the GIVpower category the template will come up automatically - you can try it for yourself
https://forum.giveth.io/c/community/givpower/15

**Comment by laurenluz** [comment]
@tropicalmangos I finished integrating edits in the forum post and got it up. says your the owner. Template is working well for the nominations: https://forum.giveth.io/t/open-call-for-givpower-delegates/779

Only weird thing is... why is it so hard to find this post? I don't see it in the main feed of the forum or when I open the community section - @divine-comedian ?

**Comment by divine-comedian** [comment]
ah I think I hid it. I just need to push a button to make it publicly viewable

**Comment by laurenluz** [comment]
ooh yeah - push the button! I will tweet it tomorrow, everything is on live & seemingly working fine, so we're on track

**Comment by laurenluz** [comment]
yeah I think we can close it! Thanks @tropicalmangos
