### ISSUE TITLE
Giveth Partnership Program Pitch Deck 

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#837]
Hey Team, 

Would like to propose putting together a "Partnership Program Pitch Deck" or template to use when deciding on or even when the time is right to offer a partnership with Giveth. This is by no means the final draft, nor should it be used to make the ultimate decision on if a partnership is valuable to Giveth or mutually beneficial for both sides, but was thinking of simply putting together an organized, colorful pitch deck and having it in our back pockets to help with initiating a partnership conversation or guide young contributors in the future. 

Please have a look and offer any suggestions, comments or missing parts. Thanks! 

**“Partnership Program / Package”** 

What Partner would get:
- Join our community call as a “spotlight”
- Listed on our website
- Quarterly social media posts (twitter, FB, LI, etc. - Jake would track) 
- A YouTube interview style video
- Highlighted in our newsletter (twice a year, what do you think @ahmadabugosh ?)
- Partake in Giveth events as panel members
- Quarterly 1:1 meeting with Giveth Partnership Team 
- Create a POAP of our partnership 

What Giveth would get in return:
- Spotlighted in their “community call”
- Listed on their website
- Quarterly social media posts (twitter, FB, LI, etc. - Jake would track) 
- A YouTube interview style video
- Highlighted in their newsletter (if they have one)
- Partake in their lead events as panel style members
- Quarterly 1:1 meeting with Giveth Partnership Team 
- Create a POAP of our partnership

**Comment by SnakeGH** [comment]
@WhyldWanderer & @Cotabe please make sure to add some of your amazing comments to this issue, when you can, to get the ball rolling. :)

**Comment by WhyldWanderer** [comment]
transferring from discord comments:
![image](https://user-images.githubusercontent.com/74267818/186257483-9d3f8f7b-b6ce-4b3b-9b4b-1a17f16964aa.png)

Also would like to remind us that if a partnership includes some sort of funding support, a proposal would need to be created in the forum by the interested partner outlining the details of partnership and funding requested

**Comment by oyealmond** [comment]
Hey team! I think will be great to outline some of the actions/benefits/etc that we could offer to potencial communities/ppl/allies as a team to have more clarity and bring more support. Thank you for the initiative @SnakeGH ! 
Agree with @WhyldWanderer would be better to team work on putting the packages together as some of them will need follow up and would be important to asigne someone (Ex curating communities for the community spotlight, or having the band with to create a video - who would be the person in charge of the interviews? etc etc) to asure everything will be delivered. 
@Cotabe Maybe this partnership exchange can be integrated in the GPIs working sessions to assure every action makes sense and brings value to Giveth and also is achievable?

I will suggest to review all the packages bullets.

**Comment by Cotabe** [comment]
@oyealmond I agree this can be good to align it to the result of the GPS sessions.

I like POAPs as a way to make partnerships more visible

I agree that interviews would be high maintenance. We need to know who would make them and how.

I really like the collab we had with ICHI, I think that one and when we released the CULT regen farm are probably the 2 most effective cross-pollinations in Twitter at least. 

I suggest:

A cross-pollination marketing campaign that may include a series of twits like:
1. What the other DAO is all about?
2. Main milestones of the other DAO
3. Next steps
4. Call to action
5. Possibilities with this partnership
6 Meme competition

**Comment by SnakeGH** [comment]
Thanks, a big bunch @tropicalmangos as its coming together really nicely. @ahmadabugosh which Giveth designing contributor do you think can assist us with the design and "WOW" next step?

**Comment by rodricastillo9013** [comment]
hi! if it seems like a good idea! @tropicalmangos

**Comment by rodricastillo9013** [comment]
added the information that I had overlooked and made the changes! @SnakeGH @tropicalmangos

**Comment by SnakeGH** [comment]
Ok, ICHI got me the twitter and discord increase for both them and Giveth but does anyone know the answer to this question? Once I have it, I can close up this issue and finalize the Partnership Pitch Deck

1.) What would be the answer to this....Angel Vault staking participation increased with new net inflows of $XXX thanks to the collaboration.

@divine-comedian @laurenluz maybe you can help or point me in the right direction for the answer...

**Comment by ahmadabugosh** [comment]
@SnakeGH I mean if you just want to see participation on the Giveth Angel Vault, you can see the data here (and add up the token value amounts): https://etherscan.io/address/0xc3151A58d519B94E915f66B044De3E55F77c2dd9#tokentxns

**Comment by SnakeGH** [comment]
@tropicalmangos good news is Lauren has connected me directly with ICHI and so I was able to collect the twitter / discord increase for both groups :)

@ahmadabugosh but I am not sure I can filter it to see the increase due directly to the partnership...

**Comment by divine-comedian** [comment]
> Ok, ICHI got me the twitter and discord increase for both them and Giveth but does anyone know the answer to this question? Once I have it, I can close up this issue and finalize the Partnership Pitch Deck
> 
> 1.) What would be the answer to this....Angel Vault staking participation increased with new net inflows of $XXX thanks to the collaboration.
> 
> @divine-comedian @laurenluz maybe you can help or point me in the right direction for the answer...

You can see some data here that i gathered while investigating GIVfarm fees
https://docs.google.com/spreadsheets/d/1QOLRZRATg6Z0UpYImRBk-OfcwDxU76RtFZpudHJ4zLE/edit?usp=sharing

**Comment by SnakeGH** [comment]
ICHI and with the help of @divine-comedian and @laurenluz have ensured this deck is complete and put to bed. 

I am closing the issue so go ahead and download yourself a copy for distro, when speaking with potentially new parters 

@Cotabe would you be so kind to add it to the shared drive of Giveth decks, pitches, docs, etc. ???


https://docs.google.com/presentation/d/16pus0-911X7drZU3hUOEfI3wod13XXkAhVjtsmcwJOE/edit#slide=id.p
