### ISSUE TITLE
Newsletter August 2022

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#838]

**Comment by ahmadabugosh** [comment]
Topics to add

-  ICHI angel vault
- Reminder about $nice token
- Team at burning man
- End of GIVfarm rewards (but get ready for GIVpower)
- ETHBarcelona blog post

**Comment by c0ric0ri** [comment]
BitDAO proposal (blog post)
Winners of meme contest for Gleam campaign?

**Comment by WhyldWanderer** [comment]
Featured project idea
https://giveth.io/project/modoc-earthrace-conservation
https://giveth.io/project/earthrace-2

The projects are connected and are from the same organization that is 501c3 registered... These projects were verified in the most recent round (17)

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri @danelsuga ,  the newseltter is ready for your comments! Ideally I'd like to send it out by Wednesday (the 31st)

[https://docs.google.com/document/d/147Lg3niAlaL87JK7dno5oK7pU35oEVaaDuFdijhtXqQ/edit](https://docs.google.com/document/d/147Lg3niAlaL87JK7dno5oK7pU35oEVaaDuFdijhtXqQ/edit)

Also, since Lauren is out, I'd appreciate it if any others (@oyealmond @tropicalmangos or anyone else) can give it a quick read and let me know if you have any comments)  🙏

**Comment by c0ric0ri** [comment]
Added some comments and grammer corrections @ahmadabugosh , otherwise all good from my end!

**Comment by danelsuga** [comment]
I'll review later today @ahmadabugosh

**Comment by danelsuga** [comment]
OK! Gave it a go! Brilliant as always @ahmadabugosh

**Comment by ahmadabugosh** [comment]
Yes, just sent it out! :) https://www.getrevue.co/profile/giveth/issues/in-the-arms-of-an-angel-vault-1328563
