### ISSUE TITLE
Giveth Donor Pitch Deck

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-planning#840]
Hey!

We would like to create a Giveth New Donor Pitch Deck to ideally educate some native crypto users on why they should perform philanthropy with Giveth. Here are some of the issues we hope to address: 

1. A web 3 audience that knows about crypto but doesn't know about crypto for good (charitable giving), a ideal audience for us that would convert well and get us more donors. We're early in the journey and every new donor to the Giveth community is a win 

2. Doing local meetups where the donor relations team can also use the presentation, means feedback where we can tweak it based on what's working/ what's not. Feedback is valuable for us 

3. This would be something new we'd be trying and if it works it's scalable 

4. Even if we don't convert the audience to donors, it builds awareness of the space and of Giveth, that's also a win and helps to push the space forward. 

5. This Crypto Philanthropy 101 presentation can also be re-purposed and used for other events run by Giveth, so the content in itself would also be valuable

Those are my initial thoughts off the top of my head, let me know if I missed anything?

**Comment by Cotabe** [comment]
This looks great! congrats! As you said, I think consistency is the key aspect for anyone that is prepare to launch it in their community. I think, I don't have the bandwidth right now

**Comment by oyealmond** [comment]
Hey @tropicalmangos! Some communities had reached out to me asking to give a press about Crypto philanthropy, so this deck would be super useful. I can help you put together this deck, would be very useful for me to learn. I think @WhyldWanderer had some presentations that we could use as a base right? Also we have this video to start 
ttps://www.youtube.com/watch?v=i8kjxGxGSkA 

Let's make a session to plan and organize the creation of this if your down

**Comment by SnakeGH** [comment]
Hey @tropicalmangos thanks for making a GH issue for the pitch deck, but I believe your details here are actually meant for the donor stragety GH #726. I would suggest changing the details here to be for the pitch deck and then keep the details here on the other GH issue :) 

Also, putting Yass' pitch deck on the issue too, if anyone else wants to look at it and create a pitch deck from it 

https://docs.google.com/presentation/d/1cGpllVLyFxQ3apa8ZG8fhCKwXpgKZlrUwUTxAxgN85c/edit#slide=id.g137e3849ded_0_0

**Comment by danelsuga** [comment]
Great job @tropicalmangos !

I had a look and made some comments.

**Comment by oyealmond** [comment]
Hey @tropicalmangos , Thank you for this. Made some comments too. Let me know your thoughts.

**Comment by danelsuga** [comment]
Great job. Left just one more comment @tropicalmangos

**Comment by oyealmond** [comment]
Added more comments here @tropicalmangos  https://docs.google.com/presentation/d/1oiHb-HPbAYQsshBEkUkgigjMR5iAUDGz8dfQuPE4Ayo/edit#slide=id.g1490bd5040f_0_0

**Comment by SnakeGH** [comment]
@tropicalmangos awesome work on the donor pitch deck. Go ahead and close the issue at this point then :)

**Comment by divine-comedian** [comment]
@SnakeGH 

Sorry I'm late to the party! I left a few comments since there is some incorrect information regarding GIVfarms and perhaps some oversimplification or missed highlights of our history, products and roadmap!

**Comment by SnakeGH** [comment]
@tropicalmangos would you be so kind to address @divine-comedian comments, as I know the pitch deck was now locked for distribution and you are the only Google doc owner? :)
