### ISSUE TITLE
Blog Post / Video Explainer for Project Verification Update

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#841]
We should create a blog post or perhaps video explainer to announce the new project verification flow (with new button). 

- New verification button
- New verification flow ( [screenshots](https://docs.google.com/document/d/1Th8mIV3QZYXhEexQSKp2P7QLiWju0QyLQ52tEV4S5lE/edit?usp=sharing) )

We can explain each page, specially the email verification and oAuth of user socials.
Compared to the previous flow with Typeform, we will no longer ask users to provide the project name and the address again. It's integrated on my account.
We can now check that the user's socials and emails are verified, so they are more reliable.

**Comment by ahmadabugosh** [comment]
@franculio @oyealmond to take this!

**Comment by oyealmond** [comment]
Question we reviewed w @ahmadabugosh yesterday this text will be to update the Giveth documentation, but now Im not sure if this was thought to be a Medium text (which will require a different tone) . 

Could you review the text , modify and/or add your feedback please? 🙂
https://docs.google.com/document/d/1Th8mIV3QZYXhEexQSKp2P7QLiWju0QyLQ52tEV4S5lE/edit 

@ahmadabugosh @ahmadabugosh @c0ric0ri @franculio

**Comment by danelsuga** [comment]
@MoeNick @NikolaCreatrix here's the place for project verification flow support! 😄

**Comment by danelsuga** [comment]
Great! Nice to see you again @NikolaCreatrix !!

**Comment by NikolaCreatrix** [comment]
Sorry it took me ages to get here...I will improve with being more up to speed w github notifications. 
So yeah I am helpin out with finetuning the script for the video part.

Do you need any help with the blog post or anything else @danelsuga ?

**Comment by NikolaCreatrix** [comment]
Ty @oyealmond  great job on the video tutorial!!!

I made tiny little suggestions in the doc, looks good to me!!

**Comment by oyealmond** [comment]
Ty @NikolaCreatrix and @danelsuga for the comments on this! 
I think we are goo to go @c0ric0ri

**Comment by c0ric0ri** [comment]
hey @WhyldWanderer I know you wanted to review the video one more time, is it good to go?

**Comment by oyealmond** [comment]
hey team. I believe @WhyldWanderer was ok with this content already . Can you confirm @WhyldWanderer ?

**Comment by WhyldWanderer** [comment]
The video looks great!! I made comments in the original issue here: https://github.com/Giveth/giveth-planning/issues/738

As far as the document above, I think that it is good for showing the new flow...

I can use this to update the docs... It would be really nice to keep a lot of the stuff that we have (like qualifying/disqualifying measures etc) and just update it with this new information and screenshots. Thanks for putting this together! I will comment here once the updates are live.

It seems too cut and dry to be a medium post and I think we should wait to do a Medium post until the project verification has received the full overhaul.. then we will have a good amount of content to create a blog.

**Comment by oyealmond** [comment]
Ty for your feedback @WhyldWanderer ! 
Agree is too dry for a Medium post, and will be better to only update the documentation. 
Thank you for owning the doc updating ♥️

**Comment by c0ric0ri** [comment]
@oyealmond we can close this issue, correct? Since we're going with the video explainer in the second issue referenced above?

**Comment by oyealmond** [comment]
I think @WhyldWanderer was going to update the documentation? Or maybe Im wrong. Could you clarify pls @WhyldWanderer ?

**Comment by c0ric0ri** [comment]
Hey @WhyldWanderer you wanted to comment here once the updates were live, so just checking in - has the documentation been updated?

I can change the name of this issue to reflect this and then close it.

**Comment by oyealmond** [comment]
@franculio May also help on this as I believe you are now in the team in charge of updating the documentation? 
. Franco we're trying to figure out if the Project Verification documentation is already updated with the latest info. 

I recently checked and I didn't saw it updated yet.

**Comment by franculio** [comment]
@oyealmond @c0ric0ri I created a separate issue in the docs update epic #980 
You can close this one
