### ISSUE TITLE
Medium article on Griff's SBS talk July 2020

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#843]
@c0ric0ri made a transcript of the talk:
https://docs.google.com/document/d/1GwfIic_IuC7zcOB78L8XIaHEzYMJbHjgi0f5UhnHGqA/edit

**Comment by danelsuga** [comment]
@c0ric0ri don't know if you've had a chance to continue on this? I was away and then you were sick, I think. Let's reconnect.

**Comment by danelsuga** [comment]
https://www.youtube.com/watch?v=bdIumUJZenw&list=PL_0VrY55uV1_sM2hl8L-MosZZiV_JVnIs&index=12

**Comment by laurenluz** [comment]
@danelsuga - how come this is in the icebox? it would be really nice to make this into a blog about the Giveth roadmap, I think that would be really useful as supporting content for our messages.

**Comment by danelsuga** [comment]
@laurenluz in the icebox bc I didn't get to working on it when my niece died in the summer. @c0ric0ri and I were bouncing it back and forth a little, but it wasn't clear moving forward, and she was sick at that time and you were still gone, so it lost traction. So then I switched to the Stanford article to focus the energy.

**Comment by laurenluz** [comment]
cool - well I wouldn't icebox it, but it's ok if we need to reassign it. general icebox is like the place where issues go when we may never get to them or they are a distant future nice-to-have (imo). This is something I'd just put in the backlog

**Comment by danelsuga** [comment]
Ok thanks.
