### ISSUE TITLE
Giveth Donor Road Map – From “Cold Call” to “Donor”

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#844]
Hey Team, 

I think its smart to put together a road map, for how to move a new donor from cold call through to current donor, if nothing more as a template for new Giveth contributors with no experience in this realm, as well as using it to think about where else we can create road maps inside Giveth. 

Additionally, I have been doing a lot of donor research for different strategies, and almost all of them mention having a road map in place, so lets get started with this very high level skeleton road map. 

By no means is this a one size fits all template, but its something to start the discussion...  

Please take some time to review the shared doc and offer your suggestions / feedback :) 

https://docs.google.com/document/d/1zrgOjdog13xk_dCGsV170fLi1h7F-cVt0Dnb_MNcM0g/edit?usp=sharing

**Comment by c0ric0ri** [comment]
Hey @SnakeGH I think this is a great initial outline. Let's get some more eyes on this!

**Comment by laurenluz** [comment]
Looks good! left some comments.

**Comment by SnakeGH** [comment]
Had our amazing graphics team make this into a fun flyer, of course it was at the very bottom of their priority list and why it's been a couple months before I could post it here, but here it is now. Enjoy 

https://drive.google.com/file/d/1arapRDALVRk2jGcabAi90ohJVfGPjWnD/view?usp=sharing
