### ISSUE TITLE
Create a marketing campaign over a Public Good Balancer Pool

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#846]
We are pushing forward for having up to 8 DAOs aligned with public goods co-creating a balancer pool and having more DAO-owned liquidity on Main Net.

It would be perfect to have:

- A blog post.
- A Twitter campaign. 

@c0ric0ri  @chad-fi

**Comment by c0ric0ri** [comment]
I'll turn this into an epic so we can organize these various pieces of content. 

@Cotabe we will need a lot more context added here of course. Is that something you can provide, or who is involved?

**Comment by laurenluz** [comment]
They drafted a suggestion in here:
https://github.com/Giveth/GIVeconomy/issues/628

I don't think this merits a blog post, we can make a tweet thread and go from there.

**Comment by laurenluz** [comment]
iceboxing this... too many projects with limited bandwidth, we should return to this after radicle, optimism, etc.
