### ISSUE TITLE
Tweets promoting Twitter Space around ReFiNFT auction for Giveth 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#847]
Giveth will be co Hosting a Twitter Space around an NFT auction powered by RefiNFT which funds will go a 100% to Giveth Mental Health projects. Would like to schedule 2 tweets inviting the community to join and support! 

**Monday 7th | time tbd**

🎙 Come join us next Wednesday 5pm EDT | 11pm CET in the Twitter Space we will be co-hosting with @ReFiNFT
🥳 We will be talking around the importance of mental health with different organizations and the NFT auction in favour of Giveth @RefiNFT will be organizing 
🔔 https://twitter.com/i/spaces/1dRJZMjkmjmGB

**Wednesday 7th | time tbd**

🎙 Today we will be co-hosting a Twitter Space with @ReFiNFT to talk about mental health! 
🫂 Will be talking with @HappyDAO3 @GravityDAO about their work towards mental health and the NFT auction in favour og Giveth @RefiNFT is launching! 
🔔 https://twitter.com/i/spaces/1dRJZMjkmjmGB

**Comment by oyealmond** [comment]
@ahmadabugosh @c0ric0ri @Cotabe  plz provide feedback to the following tuits, I can tweet both after reviewing

**Comment by ahmadabugosh** [comment]
hey @oyealmond I made some changes and put it in this doc: https://docs.google.com/document/d/12-qx2d7QWASbeyVCKX4CGCrOUV0AA0YRKZWfHLzpNWs/edit

Mainly I fixed some minor grammar, added a hook at the beginning and because of the character limit took out the timing (I don't think it's neccessary, because when you post the space link it automatically converts it into the user's own timezone):

**Comment by oyealmond** [comment]
Love it! Thank you @ahmadabugosh !

**Comment by oyealmond** [comment]
Thank you for your feedback @ahmadabugosh @c0ric0ri . 
@c0ric0ri could you help me tweet the already reviewed Tweet please?

**Comment by c0ric0ri** [comment]
@oyealmond tweeted first one yesterday, we'll do the next one tomorrow.

In the meantime I'm copying @Cotabe's duplicate issue here. It's a great idea to do some outreach to these orgs!

We will be co-hosting a Twitter space with ReFi NFT to introduce Mental Health-focused Giveth Projects to the Web3 community in preparation for the NFT auction whose proceeds will be going to Mental Health-focused Giveth Projects.

Comms goals:

Get as many Giveth projects related to Mental Health to:
+ Be at the Twitter space.
+ Participate in the dynamic to get part of the proceeds.

Get a larger audience at the twitter space to the projects, Giveth, ReFiNFT & participate on the auction.

Comms suggestions:

Twitter post tagging Giveth projects related to Mental Health (invite them to share with their communities)
https://giveth.io/project/peer-collective
https://giveth.io/project/sex-worker-community-support-line
https://giveth.io/project/samaanta-foundation (a bit on the edge)
https://giveth.io/project/sage-to-saddle
https://giveth.io/project/greyston-foundation
https://giveth.io/project/social-impact-dao-llc
https://giveth.io/project/happydao
https://giveth.io/project/reunited-alliviate-pain-worldwide
https://giveth.io/project/gravity-dao
https://giveth.io/project/w4life
https://giveth.io/project/Help-cancer-patients-get-access-to-emotional-healing-0
https://giveth.io/project/Salu-pa-Tur-0
https://giveth.io/project/The-Wellness-Bus-0
https://giveth.io/project/Refugee-Women-Empowerment-0

Email to the projects of that list (invite them to label themselves as Makers on Discord

Post on the makers channel

**Comment by c0ric0ri** [comment]
@oyealmond I added some comments for the second tweet tomorrow, please just clean it up a bit and it should be good to go!

**Comment by oyealmond** [comment]
Ty @c0ric0ri ! Those are great edits. I just changed the guests as we have new confirmed people for tomorrow. I will add the new tweets regarding this matter in the same doc

**Comment by Cotabe** [comment]
Hey team, 

I prepared the email for Giveth projects working on mental health. I would live your feedback before sending :)

Hey {{ person.firstname | default: 'there' }},

You know better than most how important is mental health. We love the work being done by {{ person.organization | default: 'you'}}.

We want to help you get funds to create more impact and here is a simple way.

ReFi NFT, Giveth, Happy DAO and Charged Particles are working together with the artist Auspicious Victory to present and Art Exhibition and an NFT Auction. All proceeds of the auction will go to projects working on Mental Health on Giveth (that can be you).

The auction will be held 10th-17th of September. Here is what you need to be part of this funding opportunity.

1. Make sure are on Giveth's Discord and you have self-assigned the Maker role (on the [assign roles channel](https://discord.com/channels/679428761438912522/902259962540077146)).
2. Follow [@ReFiNFT](https://twitter.com/ReFiNFT) on Twitter.
3. Follow [@Givethio](https://twitter.com/Givethio) on Twitter.
4. Reply to this email and let us know if you want to talk about your project in a twitter space.


This is a rare opportunity for only a few projects working on this topic & it's time sensitive.

We hope this helps you get more funds & create more impact.

With 💜 from the Giveth team

**Comment by oyealmond** [comment]
Thank you @Cotabe :) ♥️

could you just add in the 4. point the day and time of the next Twitter Space? 

**Reply to this email and let us know if you want to talk about your project in a twitter space happening this Monday 12th, 3pm EST, 9pm CET**

And just let me know who answer back interested in joining to add it to the comms.

**Comment by Cotabe** [comment]
YES, good idea.

Also... here are projects that also have something about mental health, but are not verified. Maybe this can push them to get verified:

https://giveth.io/project/hurricane-agatha-relief-efforts-on-the-oaxacan-coast
https://giveth.io/project/25-to-lifestyle-sentenced-to-thrive

**Comment by c0ric0ri** [comment]
@oyealmond please accept the suggestions in the doc so we have a clean version :) and then I can post it!

**Comment by c0ric0ri** [comment]
Wanted to get it out quickly actually so here is the post!
https://twitter.com/Givethio/status/1567508158477639682?s=20&t=R25I8IawEuKZgN2Fg8oOAw

**Comment by oyealmond** [comment]
Great Tweet. ty so much @c0ric0ri !
