### ISSUE TITLE
Tweet thread for R19

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#849]

**Comment by NikolaCreatrix** [comment]
Hello there @c0ric0ri and @laurenluz 

The tweet for R19 verified projects is ready for review as a draft, please comment or provide feedback and I will be happy to make any changes.

FYI @laurenluz I thank you for your feedback and this time I wrote also the 'first tweet'. :)

[Tweet thread r19](https://docs.google.com/document/d/1RuWudknxjxr9ChbpLhj8rc98yB3Xg6Ykat78Zh0gG5M/edit?usp=sharing)

**Comment by c0ric0ri** [comment]
@NikolaCreatrix this is great, thank you for putting this together! Left some comments and minor adjustments, after that we should be good to go

**Comment by NikolaCreatrix** [comment]
Thanks @c0ric0ri, reviewed and adjusted, we are good to go.

Also, will be creating a new issue and sharing the draft for R20 latest by tmrw, fyi.

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1574428214755311616
