### ISSUE TITLE
Meet the Makers <> ReFi NFT - Mental Health Edition comms plan

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#850]
We will be co-hosting a Twitter space with ReFi NFT to introduce Mental Health-focused Giveth Projects to the Web3 community in preparation for the NFT auction whose proceeds will be going to Mental Health-focused Giveth Projects.

Comms goals:

- Get as many Giveth projects related to Mental Health to:
               + Be at the Twitter space.
               + Participate in the dynamic to get part of the proceeds.

- Get a larger audience at the twitter space to the projects, Giveth, ReFiNFT & participate on the auction.

Comms suggestions:

- Twitter post tagging Giveth projects related to Mental Health (invite them to share with their communities)

https://giveth.io/project/peer-collective
https://giveth.io/project/sex-worker-community-support-line
https://giveth.io/project/samaanta-foundation (a bit on the edge)
https://giveth.io/project/sage-to-saddle
https://giveth.io/project/greyston-foundation
https://giveth.io/project/social-impact-dao-llc
https://giveth.io/project/happydao
https://giveth.io/project/reunited-alliviate-pain-worldwide
https://giveth.io/project/gravity-dao
https://giveth.io/project/w4life
https://giveth.io/project/Help-cancer-patients-get-access-to-emotional-healing-0
https://giveth.io/project/Salu-pa-Tur-0
https://giveth.io/project/The-Wellness-Bus-0
https://giveth.io/project/Refugee-Women-Empowerment-0

- Email to the projects of that list (invite them to label themselves as Makers on Discord

- Post on the makers channel

**Comment by oyealmond** [comment]
Thank you @Cotabe 
This is the same comms plans we already review @ahmadabugosh @c0ric0ri . Leaving here the issue to avoid duplicates 
https://github.com/Giveth/giveth-planning/issues/847#issuecomment-1235373219
