### ISSUE TITLE
Weekly copies to promote AMA calls

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#851]
Dear team, 
I created [this doc](https://docs.google.com/document/d/1rn5doTwDiZD8N7yxaJQeENXF63d65jvrS4lEZDEmxTk/edit) With copies to promote the weekly AMAs Wednesday's call. 

The idea will be me creating copies in advance for the team to have time to review and tweet/post. 

Please let me know if this will be a useful workflow for this promo to start happening. 

Would love your thoughts and feedback on this. @c0ric0ri @ahmadabugosh @laurenluz @WhyldWanderer

**Comment by oyealmond** [comment]
Hey @c0ric0ri 💜 I know there's a lot happening right now, but do you think we are good to go to start promoting this week? Thank youuu. Sharing the doc again https://docs.google.com/document/d/1rn5doTwDiZD8N7yxaJQeENXF63d65jvrS4lEZDEmxTk/edit?usp=sharing

**Comment by c0ric0ri** [comment]
@oyealmond as this is an ongoing living document, let's discuss in the next call how to set this up for regular content scheduling. We can then close this issue eventually and continue regular planning.

**Comment by oyealmond** [comment]
yes agree @c0ric0ri , thank you! This can be part of @WhyldWanderer's suggestion around comms process improvements .

**Comment by laurenluz** [comment]
Scheduled for Oct 12, 19 & 26

**Comment by oyealmond** [comment]
You're the best! thank you @laurenluz !

**Comment by oyealmond** [comment]
Dear team, I made more copies for @laurenluz to review and schedule our next AMA session. Quick reminder the AMA will be pushed 1 hr beginning Nov 2nd meaning 11am CT - 6pm CET

https://docs.google.com/document/d/1rn5doTwDiZD8N7yxaJQeENXF63d65jvrS4lEZDEmxTk/edit?usp=sharing

cc @c0ric0ri

**Comment by laurenluz** [comment]
cool @oyealmond - nice job! minor edits & scheduled them all.

**Comment by oyealmond** [comment]
Thank you so much! And super excited about the RegenFarmers gathering! 🤩🚀

**Comment by oyealmond** [comment]
Dear @laurenluz , I got the last copies with time mistakes. Im sorry, Still Im not sure if I got the time correct. Could you please (only for this time) help me review if the time is correct? I don't want to get the copies wrong again. 

Sorry for this inconvenience

**Comment by laurenluz** [comment]
omg this makes me nuts, can you do it carefully for these? the images need to be updated.. you can look at the date & times for different places here: https://www.worldtimebuddy.com/

just look at your calendar & then look at that website for the particular date.

**Comment by oyealmond** [comment]
Yeah Ik :( Sooorry. It will not happen again. Thank you so much for the tool! Is great guidance! 
I corrected everything + times + image + information. 
Will not happen again
@laurenluz

**Comment by laurenluz** [comment]
thank you @oyealmond !! way to take on for the team. this stuff makes my head spin 😵

**Comment by oyealmond** [comment]
Yes, it was super useful for me. I was about to cry. Thank you for sharing @laurenluz ! Already shared w the team, and sorry again for the changes.
