### ISSUE TITLE
Tweet Highlighting August Donations

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#853]
Pull stats from Amplitude to show our biggest month

**Comment by c0ric0ri** [comment]
hey @ahmadabugosh would you mind helping me to pull a nice screenshot of August donations for a promo tweet? 

I was toggling a bit in Amplitude but not sure I'm getting it right...

**Comment by ahmadabugosh** [comment]
Sure thing, let me know if this ->

<img width="1144" alt="Screen Shot 2022-09-16 at 12 34 36 AM" src="https://user-images.githubusercontent.com/4855928/190503699-7dcf4649-d7e9-4a3c-bbbc-c3d95a23601c.png">


<img width="882" alt="Screen Shot 2022-09-01 at 4 25 26 PM" src="https://user-images.githubusercontent.com/4855928/190503721-31e3b59e-f376-4561-8309-68babaabfd11.png">

**Comment by c0ric0ri** [comment]
Thanks @ahmadabugosh 

I wonder if we can get a nicer design of this to use on social media. @rodricastillo9013 would you be able to help with that?

**Comment by rodricastillo9013** [comment]
yes, perfect, I can help, for which social network will you need it? to know the format to design :) @c0ric0ri

**Comment by c0ric0ri** [comment]
@rodricastillo9013 for Twitter! And I think that image would be easy to reuse for Facebook and LinkedIn so one format is fine

**Comment by rodricastillo9013** [comment]
![Twitter - Post](https://user-images.githubusercontent.com/61791380/191488022-6e643140-b6e8-4d77-a2c5-43ff94356957.png)
If it's ok, I'll adapt it to Facebook and LinkedIn

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1572606750335074304?s=20&t=EKfCutTa7kCx9LO4BsCGTg

**Comment by c0ric0ri** [comment]
<img width="1024" alt="Twitter_-_Post" src="https://user-images.githubusercontent.com/106524383/191567432-72bb2b2d-d023-433d-b7f6-a9db2db30540.png">
