### ISSUE TITLE
Write Medium Blog for Crypto community & Giveth Supporters “Key Differences between GivethTRACE & Giveth”

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#86]
Who will take this on? 
When can we expected 1st draft for team to review?

**Comment by ForestSoleil** [comment]
2/5/21 Marketing call update:
- Can compare G1 & G2 in table format side by side or other creative ways
- This one is more technical document for crypto community & Giveth supporters
- Discuss: what smart contracts are being used, how funds move around in the backend, security. 
- The other article (#84 is non-technical article focused on user experience)
-

**Comment by ForestSoleil** [comment]
2/9/21 Marketing check-in:
- Mitch has a good understanding of differences between G1 & G2. WCC for drafting blog post.
- Mitch will have 1st draft ready for review Thursday morning in advance of next marketing check-in Fri morning.

**Comment by divine-comedian** [comment]
blog post ready for review an commenting HERE! 

https://docs.google.com/document/d/1_KfvFYCHev-H-zxwQor2n5t41nuPGLt52BYjynu8MNw/edit?usp=sharing

**Comment by ForestSoleil** [comment]
Would like technical dev reviewer 1-2. James available to review.
Non-technical copy review due in 34 hours. Who from the team would like to take this?

**Comment by laurenluz** [comment]
2/19/21 Marketing Call update:

- Blog post still in progress - being reviewed by Griff, James, etc.
- Features are changing week-to-week.... want to wait until we have more clarity to be ready-to-publish
- It's about 90%, just waiting for launch to finalize

**Comment by ForestSoleil** [comment]
2/23 Marketing update:
- 95-98% Pretty much done
- Mitch wants to finalize content around on ramping to ensure appropriate language is being used
- GIV Token: Griff says we can lightly hint at token economy, but do not say anything concrete. Better to talk about things we have done, not speculating on possible future things. 
- This article has been reviewed by 4-5 people now. 
- Ideal to publish this after launch. Magenta to schedule.

**Comment by ForestSoleil** [comment]
Moved into "ready to publish folder".
Waiting for launch.
Dev team still adding features - will update content if needed surrounding launch.
We can always publish and then put "article edited on X date" at the top to reflect new updates.

**Comment by divine-comedian** [comment]
Document Updated ready for QA ahead of publishing next week. 
https://docs.google.com/document/d/1_KfvFYCHev-H-zxwQor2n5t41nuPGLt52BYjynu8MNw/edit?usp=sharing

@laurenluz @GriffGreen @Danibelle @ForestSoleil

**Comment by laurenluz** [comment]
Checked! Left a bunch of comments. Looks really good Mitch! Love the personality 😘
