### ISSUE TITLE
Meet The Makers |Education| October 2022

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#860]
The time has come! Meet The Makers is alive again!

Please see the current spec doc and event plan here: (note it's a living document) https://docs.google.com/document/d/11pAUmN18p9_xm-DSG2dNKPApBFph0V5QNv90B5D-2p4/edit?usp=sharing

**We have formed a team! Yay**

Coordinators: @NikolaCreatrix  & @oyealmond 
Coordination Advice & Support: @WhyldWanderer 
Call/event moderators: Nikola & Almond
Quiet moderator on the chats: Ashley & @franculio 
Hypepeople/supporters: Ashley, Franco, @Cotabe 
Livestreamer/recorder: Ashley

**We picked a date! AMA slot October 5th, 9 am CST| 5 pm CET**

This Epic will hopefully help us to navigate our next MTM edition on the theme of Education as Public Good smoothly.

### Event Description:

_90min length_

Meet the makers is an event series where a handful of project owners, “Makers”, will meet in one space to share their vision, mission, and impact in the public space and their local community. Participants can ask questions and get connected for future conversations and collaborations.

The intention of this event is to bring Makers and Givers in one place to help build and nurture the future of giving for web3 and projects on the ground.

This epic can be closed after completing the whole lifecycle of the October Edition.

- [x] Invitations & Outreach
- [x] Communications Plan
- [x] Event & Post Event Coordination

**Comment by oyealmond** [comment]
Quick note: 
In Oct 5th Education as a Public Good , Meet the Makers session we had 20 attendees.

**Comment by NikolaCreatrix** [comment]
Great work team! :) Let's set up a sync up call to evaluate and start planning on the next one. Maybe we wait until after the Devcon if it feels better for you @oyealmond & @WhyldWanderer ;) I want you to have fun overthere.
