### ISSUE TITLE
Invitations & Outreach

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#861]
Following are tasks to do as first things first:

 

- [x] Set up MTM event in giveth.io calendar
- [x]  Select 5 projects
- [x]  Craft personal email invites for selected projects
- [x] Send personal email invites to selected projects
- [x]  Craft general email invite for all participants
- [x] Send general email invite to all participants

**Comment by NikolaCreatrix** [comment]
Following are tasks to do as first things first:

- [ ] Set up MTM event in giveth.io calendar
- [ ] Select 5 projects
- [ ] Craft and send personal email invites to selected projects 
- [ ] Craft and send a general email invite for all participants

**Comment by NikolaCreatrix** [comment]
Projects to send the invite to I have selected mostly based on the Typeform responses we have here and part is from my own knowledge about verified projects and friends we have in the theme of EDUCATION

Document with responses, and personal invite email drafts here:
https://docs.google.com/spreadsheets/d/1Fqb0l0g-VMcYCyNYGPb4OsgjTS8teah7Vnf1rBPs6WA/edit?usp=sharing

Nikola will send a personal invite to:
1. Samaanta Foundation /https://giveth.io/project/samaanta-foundation


Ashley to send invite email to:
2. https://giveth.io/project/basic-school-supplies chidi.okeke@helpersfoundation.org, name: Okeke Chidi
3. https://giveth.io/project/facilitating-blockchain-adoption-for-mena-residents ammar@taxir.xyz, name: Ammar Manla Hasan
4. https://giveth.io/project/quest-chains weetopol@gmail.com, name: Vid
5. https://giveth.io/project/bankless-brasil-dao - this project didn't fill in the typeform, it is my personal pick, parcerias@banklessbr.com, name: Gustavo Dorea

**Comment by NikolaCreatrix** [comment]
Selected projects invite draft:

"Hi _First Name_, 

Greetings from Giveth! Thank you for showing your interest to participate with your project '_Project Name_' at our upcoming Meet the Makers event!

URL link to the project

Our next Meet The Makers edition will be focused on 'Education as Public Good' and we think you are doing really great work in the world and would love to feature you and your project.                                                                          
Meet The Makers | Education as Public Good | will take place October 5th, 9 am CST| 5 pm CET in our Discord voice channel and will be streamed live on YouTube. Are you available to participate in this session? 

Each project will be introduced, then have 5 - 10 minutes to present their project & cool milestones/achievements and ways our community can get involved, then we will open it up to live audience Q&A for 3-4 minutes after your presentation. We are intending to have 5 projects as guests.

You can respond to this email or text me on telegram @NikolaCreatrix +506 8973 3380 to coordinate.

Thank you!
-Nikola @Giveth"

**Comment by oyealmond** [comment]
Adding comms plan here to have visibility towards comms updates - 

https://docs.google.com/document/d/1tsAVtIBasH9DKHxJ-FhCxr5tyTcfDAWX7wCp-4HSkWc/edit?usp=sharing

**Comment by NikolaCreatrix** [comment]
Note: General invite email draft is in issue #873

**Comment by NikolaCreatrix** [comment]
Closing this issue, this is the script and flow we will apply + confirmed guests. 

https://docs.google.com/document/d/17uyO6D8WZtOTZdEy1V4hafLIHeZYXXVAze_7MiikSP0/edit?usp=sharing
