### ISSUE TITLE
Communications Plan (execution start latest at 22nd of October)

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#862]
Here the plan is to create a smooth plan for comms around MTM:

Using this template to help follow a timeline: 
https://app.mural.co/invitation/mural/whyldwanderer3222/1660258367644?sender=u41f679b014bb5e9221347994&key=e950f8ad-5bc4-49a1-bfc9-c01f2fdc2715

We will need:

- [x] Event banner
- [ ] Blog post/Medium article
- [x] Tweet shill
- [x] Facebook & LinkedIn shill
- [x] Discord shill message

**Comment by NikolaCreatrix** [comment]
This should help us to stay well organized ;) see the taskbar above

https://docs.google.com/document/d/1tsAVtIBasH9DKHxJ-FhCxr5tyTcfDAWX7wCp-4HSkWc/edit

@oyealmond

**Comment by oyealmond** [comment]
adding the Desing issue here 
https://github.com/Giveth/giveth-planning/issues/867 

This is the right. place @WhyldWanderer ?

**Comment by oyealmond** [comment]
Sharing the issue to send the email to Giveth's database 
https://github.com/Giveth/giveth-planning/issues/873

**Comment by oyealmond** [comment]
Issue for social media posts: 
https://github.com/Giveth/giveth-planning/issues/880

**Comment by c0ric0ri** [comment]
FYI I'm moving this to In Progress for better oversight!

**Comment by oyealmond** [comment]
After communications follow up issue: 
Share in a tweet the session recording: 
https://github.com/Giveth/giveth-planning/issues/919
