### ISSUE TITLE
Event & Post Event Coordination

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#863]

**Comment by NikolaCreatrix** [comment]
Event script introducing the flow and invited projects.

https://docs.google.com/document/d/17uyO6D8WZtOTZdEy1V4hafLIHeZYXXVAze_7MiikSP0/edit?usp=sharing

**Comment by NikolaCreatrix** [comment]
Event was succesfull. All the guests showed up. We had 20 participants.

Video recording can be found here: 
https://www.youtube.com/watch?v=7eRV_4QnwyY

**Comment by oyealmond** [comment]
Ready @laurenluz !
