### ISSUE TITLE
Announce new categories, new sorting, search and filtering

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-planning#865]
we are ready to launch a new design of projects' pages, including new Categorization, new sorting, and new filtering.
to see how it looks, pls take a look at  https://givfilter.vercel.app/

Most eye-catching changes are in the projects page, the way user sort by categories and filter or sort. 
Also, there are some changes in single page view in the right pane for showing categories, as well as categories list in create/edit projects. 
With this version, users can find the projects better.

![image](https://user-images.githubusercontent.com/80677512/191066269-eac25cfd-bef0-4227-9563-4bb23f0f031e.png)

![image](https://user-images.githubusercontent.com/80677512/191066290-0771e9a5-1af8-48eb-94a4-2f0176f89a6f.png)

![image](https://user-images.githubusercontent.com/80677512/191066330-a4409282-12e0-4e62-9ad5-04c96c354a76.png)

![image](https://user-images.githubusercontent.com/80677512/191066376-f6b783dd-5b62-436b-ad62-c4641bc25df4.png)

![image](https://user-images.githubusercontent.com/80677512/191066397-f0e57612-3f43-4f77-bf72-4ec9cd54d01a.png)

**Comment by ahmadabugosh** [comment]
Hey @MoeNick, thanks for this! 

I have a few comments

1) I noticed that the filters are not inclusive or exclusive. For example, when you deselect "From GivingBlock" it still shows GivingBlock projects. Could you make the functionality be by default they are all selected, then you can deselect the ones you don't want? For example, if you deselect "From GivingBlock" it would not show them etc. 


2) Can you add a section for text below the image, so we can have content for SEO purposes (just one small paragraph ex. 
"Donate crypto directly to **Economics and Infrastructure** projects on Giveth! Support projects and get rewarded for giving with zero added fees."

3) Where are these categories being pulled from? The communitas group discussed last meeting this list we made with all the possible categories (31 in total) we could think [about here](https://docs.google.com/spreadsheets/d/1DAB5UHCYO4hkw_RLRtz8DLXpGduVDRMHfiW-71H0m8o/edit#gid=0). 

4) What should be the next steps for us in finalizing the categories? 

If we want to use our list, do we then need to go back into the other projects and retag their categories?

**Comment by MoeNick** [comment]
and for #2, can we go live with what is it, then have the suggested changes later? 
We hold this version for a long time and it could be very costly for us to wait more weeks.

**Comment by ahmadabugosh** [comment]
Thanks @MoeNick !

1) So for example, let me give you a common use case that we frequently run into. Now, there is no way to easily check if a project is a) On Gnosis chain (not Giving Block) and b) A verified project 
(I got this complaint from several people before). What do you suggest for that use case using filters?

2) Yes, please go with that for now, and we can edit them later maybe as a new issue. 

3) Yes, sorry about the confusion, that issue got lost for a long time! I brought this up several times with the community building group and I think it's good for now (in the future we might have small changes, but for now I think the list I shared it comprehensive for what we need). 

For the top banners (like NGO etc.), can't that just be a text H1 tag (instead of a banner)? 

For sure, I'll be happy to take on whatever you need for remapping old categories or discussing with the team, just let me know! :)

**Comment by MoeNick** [comment]
1- I suggest adding a filter "accept funds on Gnosis" or "giveth projects" or "not from GivingBlock" we can also adding "accept funds on eth and gnosis chain"

2- @mosaeedi thinks it's not a good choice for design, can we add it in header and also in the alt of picture (kinda tooltip) ? 

3- let's do it today, I DMed you on this, this is the issue https://github.com/Giveth/GIVeconomy/issues/723#issuecomment-1254606854

**Comment by ahmadabugosh** [comment]
This moved to implementation within the dev team, so closing this issue

**Comment by c0ric0ri** [comment]
@ahmadabugosh but to be clear what comms should we plan for this? 

For example we were discussing a bi-weekly feature update tweet thread, for example. Would this be included there? Not sure if this issue is ready to be closed because I thought the point is to align comms with the dev team implementation

**Comment by MoeNick** [comment]
I just created the Epic to address all of your points @ahmadabugosh  #1157
https://github.com/Giveth/giveth-dapps-v2/issues/1557

Some issues underneath this epic are assigned to you, FYI.

**Comment by MoeNick** [comment]
If you don't have the Zenhub extension installed, I can provide a screen shot of all related issues:
![image](https://user-images.githubusercontent.com/80677512/192559789-3192fdc3-1c1a-4678-872b-a4b7e73f9044.png)

From @ahmadabugosh side, we need content for #1559, mapping old with new ones in 723, I also just added "Accepts funds on Gnosis" filter, if you want to add another one like "original Giveth projects" please let me know.

**Comment by ahmadabugosh** [comment]
Thanks @MoeNick ! I'll have an update for you by this week

**Comment by MoeNick** [comment]
@c0ric0ri @ahmadabugosh can you give us thumbs up to launch this one and make a complimentary one, 2 weeks later? 
It's a little bit costly to keep this one in the pipeline. 
or do you prefer we have to wait until all changes apply?

**Comment by MoeNick** [comment]
Hey comms team :) I think the requested changes are going to finalize next week on staging, just a heads up if we want to agree on a release date!

**Comment by c0ric0ri** [comment]
hey @MoeNick yes let's set up a sync!

@ahmadabugosh do you have an update to share here?

**Comment by ahmadabugosh** [comment]
@c0ric0ri , sure mainly it's about:

- We updated our categories and now made it easier for you to find projects you care about. 
- Sort through over 40 public goods categories, including Arts & Culture, Community, Economics & Infrastructure, Education, Environment & Education, Equality, Health & Wellness, Nature, Technology and more! 


Once it's live, we can also include screenshots etc.

**Comment by MoeNick** [comment]
Hey @ahmadabugosh 
all changes applied to  https://staging.giveth.io/  please take a look, 
Let's go live if you can confirm :)

**Comment by ahmadabugosh** [comment]
hey @MoeNick!

I left a note on Discord, but pasting here too for visibility.  I think it's good to go, but I have a couple of comments:

1) I noticed there are still test categories 'Test & Filter', 'TestMary', 'testmary02'. Will those be removed in production?

2) Once it's live, as a new issue can you give us a sheet with a list of all of the projects and their categories, so we can sort them all to fit the new category format (it will be a long job, but I think it's necessary)

**Comment by MoeNick** [comment]
Hey @ahmadabugosh 1- yes they will be removed 2- sure 👌

**Comment by c0ric0ri** [comment]
Hey @laurenluz we'll need to create a tweet thread around this. Would you be willing to take that?

Either we set it up as it's own independent thread, or we batch it together with another upcoming feature update as part of our recurring content (we have an issue for dApp updates). But it seems this one could be standalone.

**Comment by laurenluz** [comment]
@c0ric0ri yeah I can write it

**Comment by laurenluz** [comment]
drafted & scheduled for monday.

**Comment by laurenluz** [comment]
actually, scheduled for tomorrow.

Tired of scrolling to find causes you care about?

We have now made it easier for you to connect with projects you'll love!

🧵👇


Giveth categories now allow you to fine-tune your project search.

Choose from over 40 public goods categories including:
🎨 Art & Culture
🌱 Environment & Energy
🌉 Economics & Infrastructure

And more!
 [img:X-PKOa8lb]


🔎 Narrow your search by using one of our filters!

Find verified projects, projects that accept funds on @gnosischain or your favourites from @TheGivingBlock in just a few easy clicks. [img:KFxrU8PN2]


Finding projects you love has never been easier. Head over to giveth.io to try it for yourself!


Got feedback on this feature? Let us know in the comments!

💜 Let's Build the Future of Giving, together.
