### ISSUE TITLE
Design & Brand Guidelines (Giveth Docs) pdf file unavailable

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#866]
Pdf file is missing from Docs page: https://docs.giveth.io/whatisgiveth/brandBook/

**Comment by clara-zi** [comment]
@markoprljic do you have this .pdf - is it easy for you to attach?

**Comment by clara-zi** [comment]
Thanks @markoprljic 

@rodricastillo9013 is the Design & Brand Guidelines complete and ready to be uploaded to page: https://docs.giveth.io/whatisgiveth/brandBook/ ?

**Comment by rodricastillo9013** [comment]
Yes! @clara-zi

**Comment by oyealmond** [comment]
oh actually the PDF is still unavailable. 
Let's work to upload again the brand book to the documentation :) @franculio
