### ISSUE TITLE
Newsletter September 2022

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#869]

**Comment by ahmadabugosh** [comment]
Topics to cover in this issue:

1) What to cover
- GIVpower coming soon
- Winner of survery + $nice tokens
- Verified Projects highlights
- Devcon

2) Does anyone have a favorite highlighted project? or want to add anything else? 

3) I'm thinking of doing a Meet the team segment where I highlight a new person that works at Giveth each issue (like a profile). Wdyt?

**Comment by c0ric0ri** [comment]
Project testimonials
Profiles on people who are giving talks soon
Upcoming events

**Comment by laurenluz** [comment]
Angel vault updates? maybe mention that GIV is performing better than ETH
DevCon / Bogota --> Mateo & Cotabe I think are planning to give talks at the DAOist
Griff has a talk scheduled for DevCon (Although I am not 100% sure if he will be there)

GIVpower staking & locking should launch hopefully by the end of this month. We are actively working on boosting.

**Comment by laurenluz** [comment]
Also did we ever mention our BitDAO blog postin a newsletter? it was a really nice explainer of our overall mission/vision

**Comment by WhyldWanderer** [comment]
**Upcoming events:**

Meet the Makers
Colombia Talks

**Comment by WhyldWanderer** [comment]
GR15 recap - maybe we want to talk about this if it went well...
If we didnt do so good maybe we dont need to

**Comment by ahmadabugosh** [comment]
Thanks everyone for the suggestions! 

@laurenluz yes, we mentioned BitDAO in the [last edition!](https://www.getrevue.co/profile/giveth/issues/in-the-arms-of-an-angel-vault-1328563) 

@tropicalmangos thanks! 1) An education section might be interesting, let me think about what to include in the next one 2) We use [Revue](https://www.getrevue.co/profile/giveth), it does give us stats like subscriber growth and issue specific metrics like open rate etc and also at the end of each one it has a thumbs up and thumbs down for people to say how they like it :)

**Comment by ahmadabugosh** [comment]
Also mention POWdump

**Comment by ahmadabugosh** [comment]
Hey @laurenluz , @c0ric0ri , @danelsuga , if you have a few minutes, I need some support to review the upcoming newsletter draft (I left some comments on areas I could use help in): https://docs.google.com/document/d/1Geh82Tj6AGneAPD6Tvm7s92X1wxPyIALh51uezLN3O0/edit

Thanks! 🙏

**Comment by laurenluz** [comment]
great work @ahmadabugosh !
