### ISSUE TITLE
Send email to Giveth Database inviting to Meet the Makers session 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#873]
Hey dear @ahmadabugosh, we need help to send and email to the Giveth data base inviting everyone to the next meet the makers session, could you help us? 
The email text is here below: 
The email is ready to send whenever you have chance

Email Subject: 
Meet the Makers Event - Come meet the projects that are making it happen!

### Inviting all Giveth’s Community to join the next Meet the Makers virtual session! 

Are you a donor or project maker??? This event is for you. Meet the Makers is a virtual series event happening on Giveth’s Discord dedicated to highlight project owners (“Makers”) to share their vision, mission, and impact with the public and local communities. 
We would love to invite you join the next Meet the Makers session happening October 5th at 10am CT, 5pm CET in Giveth’s Discord Community Voice Channel - link to: https://discord.gg/qhzqp7Xf 
In this session you will have the opportunity to get to know and network with some of Giveth's verified projects focused on Education as Public Good.

Event Details: 
📆 Oct 5th | 10am CT , 5pm CET
📍Giveth Discord Community Voice Channel 
⏰ 90 minutes session 
– 60 minutes presentations
– 30 minutes Q&A

**Comment by ahmadabugosh** [comment]
Hey @oyealmond I edited the email, and added an RSVP link (that will add it to Google calendar). 

Let me know if it's good to go, and I'll send it right away!  [https://docs.google.com/document/d/1NaFLPQgs-wOewcm5-jmu13qk-KJtVYTrjbWd7g1nX50/edit#](https://docs.google.com/document/d/1NaFLPQgs-wOewcm5-jmu13qk-KJtVYTrjbWd7g1nX50/edit#)

Also, in the future, for these emails please make them as a Google doc to make it easier to collaborate and edit 🙏

**Comment by NikolaCreatrix** [comment]
Hey @ahmadabugosh thanks so much! I just reviewed the doc and the email is great! Yes, let's send it out!

Thanks @oyealmond for the great coordination!

**Comment by oyealmond** [comment]
Thank you for reviewing @NikolaCreatrix ! 
And copied @ahmadabugosh , next time I will use Google Docs as well.

**Comment by ahmadabugosh** [comment]
Sent!
