### ISSUE TITLE
Tweet promoting the Giveth New Features Survey

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#876]
Hey dear team, 
Heard in the community call the team is looking for some testers for new features, I prepared some posts for us to get some testers. Could we make some posts around it?  
Pls make all the corrections you believe are necessary, I'll check them afterwards:  

https://docs.google.com/document/d/1xzEkQKBRBma1GXlXVwtO4rDC3d1qVMTbknm-MiTihqs/edit?usp=sharing.

**Comment by c0ric0ri** [comment]
@oyealmond thanks for setting this up. Please keep the issue assigned to yourself, and just tag team members in the comment for review. Sometimes we may share assignment of issues but mainly we want to have one one owner per issue who is responsible for driving it forward

**Comment by oyealmond** [comment]
Ty always for your valuable feedback @c0ric0ri . From now on I will only assign me , and tag the team members in the comments. Already review and edit the copies according to your feedback. Let me know if are ok

**Comment by c0ric0ri** [comment]
Hey @oyealmond thanks! I added some more suggestions in the doc. Would be great to see the other tweets adjusted as well!

@laurenluz FYI

**Comment by laurenluz** [comment]
@oyealmond @c0ric0ri - Tosin is actually not looking for people to sign up on his calendly any more… there was a broken link somewhere in cross-WG communication. At this point, there is nothing about test sessions to tweet…

Soon he wants to send out survey to users…https://github.com/Giveth/giveth-planning/issues/920
& especially want to know how users are getting on with GIVpower

When that’s ready, we’ll need to tweet out the survey.... we can change this issue title & modify the doc tweets to suit that use case.
