### ISSUE TITLE
Giveth Bi-Weekly Twitter Spaces Planning

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#877]
Hey dear team, as discussed in different meetings, Giveth's having new releases (GIVPower + New Praise system soon, etc) + the community is growing bringing more talented makers to the platform. 

To have an extra promotion/communication(community channel, I would like to propose having weekly 45 min Twitter Spaces, produced in house with a dedicated team to deep dive into the Giveth makers, new releases, and more.  

[Find the proposal details here](https://docs.google.com/document/d/1qB5_zGQHQS6bYdna1guSylXT-AfpCWwWGjatESh45DM/edit?usp=sharing)

Would love to hear your thoughts and feedback to this effort meant to strength and amplify Giveth voice.

**Comment by ahmadabugosh** [comment]
Hey @oyealmond I love this idea and think it would be great to grow our audience!

Just one thing I think we need to think about is what will we cover in these sessions.  Some ideas could be things we wanted to mention regularly on social media  (like platform updates, and newly verified projects etc.), we could also interview members of the Giveth team on what they love about working with Giveth, have 101 crypto sessions (educational content) and more! Those are just some of my ideas, but I think the content is something we should brainstorm on as well.

**Comment by Danibelle** [comment]
Hey Almond! Thank you for putting this together, I am in support of this proposal.
The Giveth Community Call is very informational and shares a lot outward, without room for dialogue and engagement. A Twitter space opens up a channel to receive feedback and gauge interest in topics, proposals, etc. which is something that will provide a lot of benefit to governance as well.

**Comment by oyealmond** [comment]
Yes, I think this proposal need a further planning and discussion @ahmadabugosh , let me include the planning with topics for the team to take a look. 
Yeey, so glad you support @Danibelle :) Let's make this happen.

**Comment by oyealmond** [comment]
According to @ahmadabugosh , I put a schedule with suggested topics for two months conversation according to the most recent discussions and events. Added suggested hosts, and days for the Spaces to happen. 
Your feedback will be v much appreciated - https://docs.google.com/document/d/1qB5_zGQHQS6bYdna1guSylXT-AfpCWwWGjatESh45DM/edit?usp=sharing

cc @laurenluz @c0ric0ri

**Comment by laurenluz** [comment]
Hey @oyealmond ! Love what's happening here. I left some comments in the doc. What about starting with once every 2 weeks and making sure we have the bandwidth?

Also let's get started with planning our first space following the staking/locking GIVpower launch on Tuesday

**Comment by oyealmond** [comment]
Yeey! Thank you @laurenluz, already review your feedback. I love it , and will love to bring @Danibelle to host some of the spaces as well. Perfect. Let's start bi-weekly from next week with the GIVpower launch. 
Already request the design templates for start the promotion.
