### ISSUE TITLE
Adjust the rhythm of the verification team for future rounds

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#879]
@WhyldWanderer just want to make sure that this is in front of your eyes: https://github.com/Giveth/giveth-dapps-v2/issues/1544

We are going to be moving the rhythm of GIVbacks rounds, it would be great if the whole verification team could make any necessary adjustments @NikolaCreatrix @oyealmond 

Feel free to close this issue if it's not useful.

**Comment by WhyldWanderer** [comment]
Thanks for the heads up!

We will discuss this in the verification party this week and I will post the results here.

**Comment by laurenluz** [comment]
@WhyldWanderer have we sorted this out?

**Comment by NikolaCreatrix** [comment]
Yes, our rhythm was successfully adjusted. @laurenluz :)
