### ISSUE TITLE
Tweet about new feature: add multiple recipient addresses for multiple chains

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#882]
This is spinning out of #842 :)

It should be just a simple tweet explaining the new feature where you can add multiple recipient addresses & why that's awesome.

This is pulled from an earlier draft and can be used as a starting point: https://docs.google.com/document/d/1g8Dnu_6Eu-AEFOQspKrTODr8Mx_nQRlaHXWVkp7p7U4/edit

@oyealmond - do you want to try making a new draft keeping in mind the feedback from #842 ? :) if not, I'm happy to take it!

**Comment by oyealmond** [comment]
Hey @laurenluz :) 
I made a draft of the tweet, which I think is pretty long. Can you check it out? And maybe add some of your meme talent as well . Thank you!

**Comment by laurenluz** [comment]
Hey bella! I edited this and scheduled for Satuday. Thanks!

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1579110215487815681

**Comment by oyealmond** [comment]
Loved the edits. Ty @laurenluz !
