### ISSUE TITLE
Twitter Space AMA about GIVpower after Oct 4 launch

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#884]

**Comment by oyealmond** [comment]
Adding the design request for the Twitter Space issue [here](https://github.com/giveth/giveth-planning/issues/893)

**Comment by oyealmond** [comment]
@laurenluz , could you help me schedule next Thursday Twitter Space? the title could be smth like **#GIVpower AMA with Giveth team and friends!** 🚀

@laurenluz @c0ric0ri some tweets for you to review inviting the community to join to the AMA GivPower Twitter Space - https://docs.google.com/document/d/1cZt_W6BmoHNLF9Y7BzZcPs1HtXK3_jJzTXWRZnPb8Kw/edit?usp=sharing

**Comment by oyealmond** [comment]
@WhyldWanderer , I added some details for the event creation (Discord/email) [here](https://docs.google.com/document/d/1cZt_W6BmoHNLF9Y7BzZcPs1HtXK3_jJzTXWRZnPb8Kw/edit?usp=sharing)
Could you help us making it?
Thank you!

**Comment by laurenluz** [comment]
This is scheduled! https://twitter.com/i/spaces/1gqxvyLRnZaJB

I'll tweet about it with Giveth on Wed w/ a reminder on Thursday.

**Comment by oyealmond** [comment]
Yeeeey! Great! Ty @laurenluz !

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1579472577742995462
