### ISSUE TITLE
Email to Donors & Projects Announcing GIVpower Launch

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#885]
Please draft an email announcement

Plan to send it out October 4th to announce GIVpower launch

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh do you have the draft ready to share today so we can review it before tomorrow? I saw this is still in Backlog so please share some updates here, thank you!

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri @laurenluz @danelsuga Can I get a quick proof read on this so I can send it today (I basically just took what Lauren posted on Discord)?  [email draft](https://docs.google.com/document/d/1E85mW068yYSRkv2Ds-tf7cO1mIeYmscPplZdxR5oAck/edit)

**Comment by danelsuga** [comment]
Having a look now. @ahmadabugosh

**Comment by laurenluz** [comment]
Look great! (she says because she wrote it in the annoucements channel 🙈 )

I made a couple of small suggestions/comment. Thank you @ahmadabugosh !
