### ISSUE TITLE
GIVpower infographics

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#886]
Looking for a Graphic explainer that shows the process flow from donating to GIVbacks, to staking, locking, getting GIVpower and supporting projects. @tropicalmangos & @rodricastillo9013 to collaborate!

**Comment by laurenluz** [comment]
@tropicalmangos made this: karmaticacid
#1218
GIVpower graphic

karmaticacid
 added 
Rodricast
 to the group.
 — 09/26/2022
karmaticacid
 changed the channel name: 
GIVpower graphic
 — 09/26/2022
karmaticacid — 09/26/2022
Hola Rodri! Estamos hablando en creer un graphico para el launch the GIVpower... que explica el proceso de donar hasta recibir GIV, GIVpower & apoyar projectos
Tenemos esta chat para coordination 🙂
nos puede ayudar con esto?
Luego te explico mas
Rodricast — 09/27/2022
hola!
buen dia!
bueno saber de ti lauren! hace mucho no hablamos! jaja
porsupuesto puedo ayudar
tropicalmango — 09/27/2022
Lauren, te cuento que rodri y yo vamos a tomarnos un cafe mañana  😇
lo podemos hablar mañana rodri !
Rodricast — 09/27/2022
Si!
Genial
karmaticacid — 09/27/2022
Gracias Rodri! siiii hace tiempo no hemos hablado! pero ya volvi de las aventuras 😄
Katya va a coordinar contigo en este, pero estoy aqui si tienen preguntas
seria super bueno si podemos tener el deseno al fin de esta semana porque vamos a tener GIVpower staking/locking todo listo el martes
gracias chicos ❤️ que disfruten su reunion!
Rodricast — 09/27/2022
Genial! Lo intentaremos
Genial tenerte de vuelta!
tropicalmango — Today at 7:04 AM
hola que tal ? 🙂  ya termine el grafico para GIVPower (es una idea nada mas, Rodri le va poner su toque magico de diseño grafico) 🪄 

https://miro.com/welcomeonboard/SGtzZ01xMnAzaGFHZ1M0ZmVMUlp4VWN5ZXNUSzY0UVpPendLWUVIS284VFpFQklyRkl5YkxINm9pNUd3NDZZSnwzNDU4NzY0NTMwNzk5NzE1ODE5fDI=?share_link_id=109611721605 

And I left some comments that need to be integrated. @tropicalmangos can you make a new iteration on this and then we can get some more eyes on it for advice process?

**Comment by rodricastillo9013** [comment]
Hi everyone! great I have seen there! I'll try to start tomorrow, I haven't been able to yet, this week I was very busy... I'll share when I have progress! Thank you @laurenluz @c0ric0ri @tropicalmangos

**Comment by laurenluz** [comment]
@rodricastillo9013 - wait on this... it's not approved yet.

@tropicalmangos I think we should discuss this in our next call so I can explain things more, still some inaccuracies.

**Comment by rodricastillo9013** [comment]
okay! When it's approved, let me know! and start, thanks!

**Comment by c0ric0ri** [comment]
Hey @rodricastillo9013 could you share here any existing graphics we have right now which shows GIVpower?

**Comment by c0ric0ri** [comment]
Thanks @rodricastillo9013 ! 

Can you create a much more simplified version that takes just the GIVpower parts of this graphic, and show the flow?

1. GOT GIV (Donate to verified projects)
2. Stake your GIV & Lock your GIV for multiplier
3. Get GIVpower from this
4. Boost projects to increase their rank
