### ISSUE TITLE
GIVpower Twitter partner outreach - Dec 6

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#887]

**Comment by c0ric0ri** [comment]
We're going to save this for when we launch Boosting for GIVpower

- Create some support materials so people know what to do
- Reach out to donors and projects with support materials and ask for support to push the launch comms

**Comment by c0ric0ri** [comment]
Working via this draft: https://docs.google.com/document/d/1z66askHlAKa6VZX8dBOSlVg-l2fldR_jH5u_ULCPDns/edit#

**Comment by c0ric0ri** [comment]
@oyealmond FYI we'll want to add in the Twitter space details here once we have it prepared for GIVpower.

**Comment by laurenluz** [comment]
Hey @c0ric0ri ! This was great, I did tear it apart a little, but mostly just to save time. If you've got time early tomorrow to clean it up a bit, have at! Also, I think it would be great to have a quick sync on GIVpower outreach & GIVpower comms tomorrow in general - perhaps w/ Almond too. 

I'll write in our group

**Comment by laurenluz** [comment]
Hey @Cotabe @SnakeGH - we are planning to start doing outreach to people about the upcoming launch of GIVpower - would you be able to help us with doing some of that outreach?

We will have a doc prepped with all the details & a spreadsheet w/ names - and we're hoping to have a quick sync to answer any questions early next week. Are you down?

**Comment by c0ric0ri** [comment]
Partner Outreach Contact Spreadsheet: https://docs.google.com/spreadsheets/d/10d3-NFU6M7Dl9u4A4W0g4JZa96zNuUpGzXxtljJuF94/edit#gid=1511320055

**Comment by laurenluz** [comment]
@WhyldWanderer @NikolaCreatrix - we want to do some outreach as well to project owners to let them know about this launch - we can do a mass email ( which we have an issue for already), but also would love to know if there are any with twitter accounts that you would suggest we add?

You could help us add to the spreadsheet?

**Comment by c0ric0ri** [comment]
@laurenluz made some adjustments on the first half of the doc. If it looks good I'll delete out the crossed out copy for a final clean version.

I'm struggling a bit with the call to actions, I'll look again the next days with fresh eyes. @oyealmond would you want to take a look at the tweets as well?

**Comment by oyealmond** [comment]
Hey @c0ric0ri ! Added the Twitter Space info. I saw @laurenluz put some good CTA to projects, donors and holders too! :) 
This guide is looking great

**Comment by Cotabe** [comment]
I've added a few contacts! Then @oyealmond beat me on the outreach to most, amazing job!

But I did outreach on the other ones.
