### ISSUE TITLE
PoW Dump comms

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#888]
PoW Dump decided to donate 25-40% of their fees to Giveth projects. As reciprocity, they are asking us to help with comms.

Here is what they are asking https://docs.google.com/spreadsheets/d/1O2hyy55HA-mUOmJzKraSsSSgmrU1BR1hpBltYb1TS5o/edit?pli=1#gid=0

But here it is synthesized on a to do list:

- [ ] Tweet about PoW dump supporting Giveth (ideally 09-28-22) - Cotabe will draft.

- [ ] Retweet PoW dump tweet (09-29-22) - Twitter team

- [ ] Share on the tweet on Giveth discord (09-29-22) - Cotabe

- [ ] Retweet PoW dump tweet (10-02-22) - Twitter team

FYI @c0ric0ri @laurenluz @oyealmond

**Comment by Cotabe** [comment]
(1/5) 
A story of collaboration for the environment, for regenerative economies and for users.

How @DumpPoWETH @cowswap and Giveth.io are working together to sunset ETHW, help users get ETH out of it and give back to the environment and the Ethereum ecosystem.

(2/5)
Few weeks ago @DumpPoWETH reached out to explain how pow.dump.today would help everyone DUMP their ETH. 

Key benefits:

1. Reduce carbon emissions.
2. Support Ethereum's Community vision of PoS.
3. Help users get ETH out of their ETHW.

But there was more...

(3/5)

They wanted to give back a big chunk of the fees to:

- Reduce carbon emissions
- Regenerative economies
- Other causes in the ETH ecosystem.

We decided to work together, part of the fees will be donated to Giveth projects working on these topics

(4/5)

The app launched shortly after the Merge... at the beginning, it was a bit clunky as expected. A market needed to evolve on the ETHW side to match the selling offers...

But now that there are actors taking advantage of arbitrage and MEV opportunities... big DUMPS are being released.

(5/5)

You can DUMP your ETHW today for ETH and support environmental and Ethereum-related projects on Giveth.

Helping offset emissions and make a better ETH and IRL ecosystem for all.

**Comment by c0ric0ri** [comment]
Thanks a lot @Cotabe! Just a couple of things as I'm trying to get this board functioning properly. :)

1. Please always put comms drafts into a Google Doc, with the link posted here so that reviewers can comment and edit.

2. Make sure to assign the issue to yourself if you are overseeing it.

3. Make sure to change the issue status to "Review/QA" so that when people are checking the dashboard for things to review will see it there ready to check. Otherwise it just stays hidden in the pile of github New Issues, and lost in a sea of email notifications.

Thank you!!

**Comment by c0ric0ri** [comment]
Dropped the draft into a Google Doc here: https://docs.google.com/document/d/194ZzzPK7dHYZQ4dbKYYxeOCQUVEzWJ7ZCz69vKkcXxs/edit

**Comment by laurenluz** [comment]
Hey @Cotabe @c0ric0ri - I left some comments in the doc. I like where this thread is going and it's written well, but tbh, I personally am not super familiar w/ POW dump and what it all means - so I think a lot of our audience isn't as welll!

Would love to see this story told with a little more context to answer some questions. I put some questions in the doc. Please help! :D

**Comment by Cotabe** [comment]
Hey @laurenluz @c0ric0ri 

Great questions @laurenluz 
I made some modifications to the thread to address those questions and make the thread easier to understand

**Comment by c0ric0ri** [comment]
Hey @Cotabe @laurenluz I saw the new edits today and made some further adjustments to meet Twitter character limits etc.

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1576567192681938946
