### ISSUE TITLE
Determine estimated date that Giveth 2 Marketing is Ready for Official Public Launch

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#89]
Once we know this, Sync with Devs & jointly confirm/agree upon a tentative launch date that coordinates tech and marketing promo.

**Comment by ForestSoleil** [comment]
2/5/21 Marketing call update:
- Thoughts on date estimation:
>>> It's really important for us to have everything ready before we launch. More important than launching by Valentine's Day.
>>> Soft launch site transitioned over Feb 14th, but still squashing bugs before official public launch. 
>>> The developers are really asking for the soft launch on Feb 14th. 
>>> Dani is in the process of trying to schedule other full multi-day DBC time consuming things. She's looking to schedule those things starting Monday, Feb 22nd. So ideally soft launch is before Monday, Feb 22nd. Okay to be in soft launch during DBC time off. 
>>> BLOCKER: Are we going to have FIAT ready? 
>>> DEPENDENCY: Better Giving Studio, Bill & Melinda Gates Foundation IDEO announcement - we need our soft launch completed BEFORE this announcement so the link is WORKING. "A few weeks", sent 4 days ago - probably within the next 3 or less weeks. Dani to confirm date with them.

Timelines:
- Which articles do we want to publish pre-launch to build excitement vs which articles do we want to publish at the time of launch and post-launch? Create this in content calendar to review on next marketing call.

**Comment by ForestSoleil** [comment]
March 21st - marketing
Dev team requested Mon March 1st as official public launch. 
This works for marketing.

**Comment by laurenluz** [comment]
Can we close this issue now that we know the dates? @ForestSoleil

**Comment by ForestSoleil** [comment]
Wednesday, March 24th morning
