### ISSUE TITLE
Design for GIVpower banner on giveth.io

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#892]
Would love to see a banner on the Giveth.io website that announces GIVpower.

If we could have this up and ready when staking/locking is released Oct 4, would be great, but if not, shortly after is good as well!

@rodricastillo9013 could you help with that?

I'd love it to say:

"GIVpower is coming!
Stake & lock GIV today to multiply your rewards & get ready to boost projects."

And make sure to use the Rocket design elements. :)

**Comment by rodricastillo9013** [comment]
![givpower banner](https://user-images.githubusercontent.com/61791380/192834146-13e9a102-475a-4bf3-a94b-cb1c4dbdd8a6.png)
wdyt ? @laurenluz

**Comment by rodricastillo9013** [comment]
![banner GIVPowe2](https://user-images.githubusercontent.com/61791380/192834426-20fcdbbf-75b2-4043-a65a-ab719f6f85f6.png)

**Comment by laurenluz** [comment]
Looks great!!

Can we make a little text fix:

" Stake & lock GIV today to multiple your rewads,
and get ready to boost projects!"

**Comment by rodricastillo9013** [comment]
![Final](https://user-images.githubusercontent.com/61791380/192841430-8c24f60b-7986-44ce-8159-4bbe30ccc942.png)
Yeah! :)

**Comment by laurenluz** [comment]
perfect!!~!!
