### ISSUE TITLE
Design request for Giveth Twitter Spaces 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#893]
Hey dear @rodricastillo9013 , me again 💐. 
Requesting this time 2 templates for Twitter format only. 
These again need to be in pptx format to edit the info.
As this will be two different conversation invitations, could you make the background in different colors? 
Something you think will be cool to differentiate both.   

Design 1 text: 

GIVtalks - Twitter Space (bigger text**)
Conversations around the Giveth Universe (smaller text*)
"GIVPower launch" (editable text - this will be the conversation topic) 
Thursday 6th, 2pm CT | 9pm CET (editable text) 

Design 2 text: 

Meet The Makers - Twitter Space (bigger text**)
Shaping the future of giving (smaller text*) 
"GIVPower launch" (editable text - this will be the conversation topic) 
Thursday 6th, 2pm CT | 9pm CET (editable text) 

***
Thank you!

**Comment by rodricastillo9013** [comment]
Perdona la demora! aqui lo tienes! https://docs.google.com/presentation/d/1KlmmdT8DI3fox9XzAs4IBqngG2tP9uIOa5t0FT29UQI/edit?usp=sharing

**Comment by c0ric0ri** [comment]
Hey @oyealmond , we can move this into Done status right?

**Comment by oyealmond** [comment]
Yes! Thank you for chiming in on this @c0ric0ri !
