### ISSUE TITLE
Comms for the new XDAI/Regen farm

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#894]
@Cotabe commented on [Tue Sep 27 2022](https://github.com/Giveth/giveth-dapps-v2/issues/1554)

Here are a few ideas of comms:

- [ ] Teaser tweet (if possible) - "He are cooking a FOXprise for you... coming soon @shapeshift "
- [ ] Countdown tweet (10-02-22) - draft a tweet to send the day the countdown goes live
- [ ] Launching day tweet (10-05-22) - draft a tweet to send the day of the launch
- [ ] Retweet FOX comms about it

FYI @c0ric0ri @laurenluz @oyealmond 

---

@laurenluz commented on [Tue Sep 27 2022](https://github.com/Giveth/giveth-dapps-v2/issues/1554#issuecomment-1259822858)

Looks good! I think we might be a bit too packed this week for the teaser tweet though, we can try.

---

@laurenluz commented on [Tue Sep 27 2022](https://github.com/Giveth/giveth-dapps-v2/issues/1554#issuecomment-1260053928)

@Cotabe also I think this issue would be better in the giveth planning repo, and just link it in the epic, then Cori has an easier time keeping track of it too.

**Comment by c0ric0ri** [comment]
For tweet prepping: https://docs.google.com/document/d/1VB3MS4FXQ2tMV-uqupvbnPqMx5_IY-_2ZenXBZiABlE/edit

**Comment by Cotabe** [comment]
I've updated the dates according to the release schedule

@c0ric0ri

**Comment by c0ric0ri** [comment]
@laurenluz I have tried a couple first tweet drafts for this, would love your review on it. 

Maybe a meme is cool as teaser? @Cotabe

**Comment by Cotabe** [comment]
Agreed

**Comment by c0ric0ri** [comment]
Tweets Posted:

https://twitter.com/Givethio/status/1580962081934671877

https://twitter.com/Givethio/status/1582059639105294339
