### ISSUE TITLE
GIVbacks Extension Tweet

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#895]
Craft a tweet to announce that:

- we are extending GIVbacks round 20 to October 4th
- new schedule going forward

**Comment by c0ric0ri** [comment]
Tweet here for review: https://docs.google.com/document/d/1Wr13Eboaa2C-HZlvQpafVmlzMUJ-PyNZB0126mks1SE/edit

@laurenluz

**Comment by laurenluz** [comment]
Thanks @c0ric0ri! This is great, I extended it into a thread and scheduled it in tweethunter for tomorrow morning at 9:08am costa rica time.

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1575498044056838145
