### ISSUE TITLE
GIVpower workshop for donors

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#897]
@oyealmond to help organize for the week of the 10th

**Comment by oyealmond** [comment]
This issue will be covered here: https://github.com/Giveth/giveth-planning/issues/898

**Comment by c0ric0ri** [comment]
@oyealmond that issue you referenced is for project owners. Should we keep this issue open for a second workshop for donors? Or is this now a duplicate?

**Comment by oyealmond** [comment]
This is a duplicate @c0ric0ri . We intended to make two workshops at first, one for projects and another one for donors. 
But then we figured will be better to do just one two both: projects and donors.
