### ISSUE TITLE
GIVpower party! Feb 22 | 2023

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#898]
@oyealmond to help organize

**Comment by oyealmond** [comment]
Let's do this workshop on the 19th. 
I will use the AMA slot .

**Comment by oyealmond** [comment]
Hey dear team, prepared a planning doc for the next GIVpower workshop session. 
Found will be better to destinate 1hr session to both targets projects & donors, and see if a second session is needed . 
I will be creating separate issues for each accionable. 
https://docs.google.com/document/d/1QaHl3ZM5Ga-EepBVvlKzmu_0rqPnA7nsatxDJHJKUrU/edit?usp=sharing

**Comment by oyealmond** [comment]
Promoting tweets issue here: https://github.com/Giveth/giveth-planning/issues/928 
Sending an email to donors here: https://github.com/Giveth/giveth-planning/issues/927

**Comment by laurenluz** [comment]
Hey @oyealmond I think this is amazing, but also thinking perhaps we should postpone until GIVpower boosting is launched...

Since we don't actually have everything ready for people to use yet, I think it might be better to wait until we do. Wdyt?

**Comment by oyealmond** [comment]
A 100% agree. Thank you for the feedback and for being aware of this. We can use this materials later. @laurenluz

**Comment by c0ric0ri** [comment]
Targeting Dec 14th for the GIVpower workshop

**Comment by oyealmond** [comment]
Hey team! @c0ric0ri @laurenluz 
To align and start preparing the details around the workshop would love your vobo in: 

- The workshop will happen after the Q&A Twitter Space, 10amCT / Dec 14th at Discord (community voice channel.) 
- I will recommend to prepare the workshop in a presentation format. For ex:  
1) Intro, what is GIVpower
2) Functionalities & how it works
3) Benefits & players
4) Q&A
- The workshop will be facilitated by @laurenluz w/ @WhyldWanderer & my support to stream, answer chat questions etc. Would you like to include someone else to facilitate w/ you @laurenluz? 
- The workshop will be 1 hr. long
- We will invite ppl form the Twitter Space to join the workshop 
- This session can also be include in the GIVpower press release https://github.com/Giveth/giveth-planning/issues/1027 & the GIVpower Twitter partner outreach https://github.com/Giveth/giveth-planning/issues/887 as part of the boosting launching strategy. 

wdyt? Any thoughts? Input around this? 
Thank youuu

**Comment by laurenluz** [comment]
I think I can handle facilitating on my own, but also open to having others jump in to support. I think that's a good flow, I can screen share & do demos during 2 (so that would be the longest part). I also think we can do Q&A throught... actually get people to get using GIVpower during the call & I can help troubleshoot any issues... make it more hands-on.

I like the idea of inviting people to join after the twitter space, just give 'em everything! We can have a second workshop in January so that we have more opportunities for people to join.

**Comment by oyealmond** [comment]
hey @laurenluz ! 
Thank you for your feedback! I added my last comment before our Friday synch in which I believe we mentioned will be better to push to Jan? 

Either way Im ok having two workshops! one right after the Twitter space of the 14th , and another one in Jan. 
So are we aligned to have a Discord GIVpower workshop on the 14th, after the Twitter Space? Just to be a 100% sure. Thank you! 

cc @c0ric0ri

**Comment by laurenluz** [comment]
Just on a call w/ @c0ric0ri right now - thinking it's not a bad idea to do twice! since we'd have the AMA call anyway... we can make this more GIVpower focused & see who shows us.

We should still have the follow up in Jan

**Comment by oyealmond** [comment]
great! I love it. To have the AMA more GIVpower focused. Anything really produced or formal, but a space to follow up & get closer w/ user to get feedback. Like it! 

@laurenluz

**Comment by c0ric0ri** [comment]
Hey @oyealmond can you update this issue title with the workshop date please, just for clarity and better oversight? Right now it says early Jan

**Comment by oyealmond** [comment]
Ofc! 

· Updated the title to Jan 25th. 
· Same time as the Giveth AMA
· Objective: Invite GIVpower users & listen to their experience so far. 
(I suggest being open to orient newcomers to GIVpower if someone new arrive & is interested. WDYT @laurenluz?) 

Details 
 
[· We have a Discord event](https://discord.com/channels/679428761438912522/979783352783609866/1061094711424725032)
· Title: Let's talk about GIVpower 
(I tried to think of smth less official, but suggestions are welcome) cc @c0ric0ri @laurenluz 

· For the invitation we'll be focusing on GIVpower users, @WhyldWanderer & @laurenluz provide [this GIVpower user list to email](https://docs.google.com/spreadsheets/d/1XdUfaiHAVW7cenxJ-JOWNDadKj5PuCMvsaMT6e57ehc/edit?usp=sharing). 
· Next steps: prepare comms
– invitation email 
– social media channels.

**Comment by oyealmond** [comment]
[Evenbrite event is ready ](https://givpowerparty.eventbrite.com/)

**Comment by laurenluz** [comment]
oh wow this is so cool @oyealmond - but since we are postponing this... is it easy to change the date of the event?

**Comment by oyealmond** [comment]
Sure! We can change the date. Let's synch on the best day tomorrow

**Comment by oyealmond** [comment]
Session got pushed to Feb 22, at 10 am CST

**Comment by oyealmond** [comment]
Hey @laurenluz :) 
We're readyyy. 

Can you help me tweet the tomorrow's party please? 
Here's you'll find [the drafts. ](https://docs.google.com/document/d/1jg8oJhJu_iHprMe12p1ExVRDGVDLHexNvdk6Q2FImOc/edit)
