### ISSUE TITLE
 Twitter Engagement Guide

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#899]
Hey @laurenluz ! 

Creating an issue to review Twitter responding and polish this . 

Some answers to start reviewing: 

https://twitter.com/mrsThreshold/status/1557785913689776133
https://twitter.com/karmaticacid/status/1557796004790841344 
https://twitter.com/ShapeShift/status/1558179930982289408  https://twitter.com/eth_barcelona/status/1558163928147841024 
https://twitter.com/DiamanteBridge/status/1558232326202687489 
https://twitter.com/ichifoundation/status/1558862165846532096 
https://twitter.com/tecmns/status/1559252818657218560  – https://twitter.com/Cotabe_M/status/1559192063672864768  https://twitter.com/ichifoundation/status/1559275745087696896  https://twitter.com/pavlebatuta/status/1560195487055183873  https://twitter.com/solar_gustakes/status/1560256358133678081 
https://twitter.com/BanklessBR/status/1560260869744840706  https://twitter.com/agroforestDAO/status/1560360897473875974  https://twitter.com/boeltermc/status/1560605408879775744n https://twitter.com/Marcobear_eth/status/1560650243259367424  https://twitter.com/Rohekbenitez20/status/1560686444414484480
https://twitter.com/karmaticacid/status/1561375388294451205 
https://twitter.com/Givethio/status/1575584176350253056
https://twitter.com/Givethio/status/1575284682333343744
https://twitter.com/Givethio/status/1575284373754085376
https://twitter.com/Givethio/status/1575283563435548675
https://twitter.com/Givethio/status/1575151158674571271
https://twitter.com/Givethio/status/1573368325375393792
https://twitter.com/Givethio/status/1572989873430069255
https://twitter.com/Givethio/status/1572989613832081411
https://twitter.com/Givethio/status/1572688834936320000
https://twitter.com/Givethio/status/1575914945241239552

Our next steps can be: 
· Reviewing the Twitter tone and polish the answering. 
· Check some of the Twitter Analytics. 
· Figure out a Twitter process (specially with Twitter Spaces starting to happen) with @c0ric0ri 

Should we set up a session for this @laurenluz ? 
Maybe on the 5th (After GIVpower launch).

**Comment by oyealmond** [comment]
Next steps create a AMA document with an answering base for Giveth Twitter.

**Comment by oyealmond** [comment]
Hey @laurenluz and @c0ric0ri ! Here's our Most Asked Questions and Common Twitter Scenarios guide 
(is a work in progress and I will be complementing with more cases coming). If you want to start reviewing 👉🏼 https://docs.google.com/document/d/1cCEBCbnptMEsoQGNCIuBD09gGgT5kPVzMQg6blSXmgI/edit?usp=sharing

**Comment by c0ric0ri** [comment]
hey @oyealmond just making sure, do we want to keep this issue open now for the AMA document?

If yes, please rename this to Twitter Engagement Guide or something like that so we have this pinpointed to something specific we're creating. I'm also moving this to In Progress :)

**Comment by oyealmond** [comment]
Ready @c0ric0ri ! Ty! Yes please, let's keep it open as this is still a work in progress :)
