### ISSUE TITLE
Post tweets inviting the community to the informative Praise session 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#900]
Hey @laurenluz and @c0ric0ri , This Thursday after the community call we're throwing a Praise demo session . - The intention is to introduce Praise to the community. 

Could you help us post these tweets inviting ppl to join? 👉🏼 

https://docs.google.com/document/d/1eTjqSMbRyCpJ3neeR72j76CZiAHslr9cEwL39nO73BU/edit?usp=sharing 

(There is a design available as well. Find it on the document)

Also, @WhyldWanderer , can you help us creating the event and email invitation? The title, description and details [are here](https://docs.google.com/document/d/1eTjqSMbRyCpJ3neeR72j76CZiAHslr9cEwL39nO73BU/edit?usp=sharing)

**Comment by oyealmond** [comment]
cc @franculio . Para que estés al tanto!

**Comment by oyealmond** [comment]
Hey dear @laurenluz and @c0ric0ri . I know this week we're full of events, but wanted to ask if you could make space to invite the community to the Praise informative session we're having this Thursday . 

Posted some copies if you find them useful - https://docs.google.com/document/d/1eTjqSMbRyCpJ3neeR72j76CZiAHslr9cEwL39nO73BU/edit?usp=sharing

**Comment by laurenluz** [comment]
@oyealmond I scheduled one tomorow & one thursday :)

**Comment by laurenluz** [comment]
I copy/pasted my edits in the doc so you can review, maybe take some ideas for next time.

**Comment by franculio** [comment]
Great work @oyealmond ! and thanks @laurenluz !

The event for discord is already created. Don't know if @WhyldWanderer already sent out the email invite, if not I can do it!
