### ISSUE TITLE
Other Leading Crypto Philanthropy Platforms - Highlights of their Benefits 

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#901]
Think it would be great to have a document for our internal use to compare the leading, other crypto philanthropy platforms for when a potential donor, project or partnership asks "why Giveth instead of (insert other crypto philanthropy platform)?" 

In the link below is a list I have come up with, please add any other leaders to it (as well as if you already know their Pros & Cons), so I can start creating the Pros & Cons of each. Thank you! 

https://docs.google.com/document/d/1zWR6Nac_KOM8e7U_qzLuw_yrAvGW4jkdCqsXn_RtLN8/edit?usp=sharing

**Comment by c0ric0ri** [comment]
Hey @divine-comedian @Danibelle maybe you want to weigh in on this list? Not sure who would be best to tag, who is aware of the competitive landscape for donation platforms. But this seems like a great initiative from Jake for review.

**Comment by divine-comedian** [comment]
sorry I'm not super knowledgeable in this arena! probably @GriffGreen

**Comment by c0ric0ri** [comment]
Hey @SnakeGH, I'd suggest asking for feedback on this in Discord and in the Communitas working group

**Comment by SnakeGH** [comment]
@c0ric0ri its been dropped in discord and highlighted in Communitas and I believe even the Comms call, so at this point, everyone has added what they liked and I think we are at a good place with the current status of the doc. 

Now I would close but I believe this doc will move as other leading platforms come up or even as they fall off, so let me know how to proceed with the issue.

**Comment by SnakeGH** [comment]
Added this to our Communitas notion page, so closing now 

https://www.notion.so/giveth/Giveth-Community-Building-45fcf05c12b3499ea4fb1c9def2e85af
