### ISSUE TITLE
Partnership Program - next initiatives 

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#902]
Hey Giveth Team, 

I have an idea about moving forward with our current partners and thereafter, any partners we link up in the future, but in order to perform this idea appropriately, I'd like to confirm that the list of current partners I have is not missing any (https://giveth.io/partnerships - 35 partners in total). 

Once I have confirmed these are ALL of our current partners, as well as once the Partnership Flyer (GH #837) is finished the next step would be as follows: 

a.	Come up with list new target partnerships 
b.	Create partner program discord channel for constant communication 
c.	Start engagement with partners in that channel 

First step, please help me confirm the list of current partners is correct:

1.	1Hive
2.	Alibre
3.	Aragon
4.	BrightID
5.	Change
6.	Clr.fund 
7.	DappNode
8.	Datafund
9.	District0x
10.	DoinGud
11.	Ethereum Colombia 
12.	Gitcoin
13.	Gnosis Chain
14.	Governauts 
15.	GravityDAO
16.	Iden3
17.	Maker DAO
18.	Meta Cartel
19.	Meta Gamma Delta
20.	MyCrypto 
21.	MyEtherWallet (MEW)
22.	Panvala
23.	Polygon Hermez
24.	PrimeDAO
25.	Rainbow Rolls
26.	SDG Impact Fund
27.	ShapeShift DAO
28.	SourceCred
29.	Status.im 
30.	Swarm
31.	The Common Stacks
32.	The DAOist 
33.	Token Engineering Commons
34.	The Giving Block 
35.	White Hat Group

**Comment by SnakeGH** [comment]
Hey, specifically @WhyldWanderer @ahmadabugosh @Danibelle @laurenluz @divine-comedian @GriffGreen could you please assist me with collecting some information in this google shared drive, which I will then upload to our CRM Hubspot, as well as use to take the next steps in strengthening our current and future partnerships? 

https://docs.google.com/document/d/1iq1cWGWqxGRl4DuP15bYc-D5ZT2231Ic0dK-FmrtV8M/edit?usp=sharing

**Comment by SnakeGH** [comment]
@laurenluz I went ahead and added TGB info to not only this shared doc but to our CRM Hubspot

Also the doc should be completely open for all to comment, please let me know if that is not the case

**Comment by SnakeGH** [comment]
Thanks @divine-comedian for adding what you know, I have a couple follow up on the contact info, please let me know. 

@laurenluz @WhyldWanderer hoping you might be able to assist too with some info?

**Comment by SnakeGH** [comment]
Anything highlighted in yellow I need everyone's assistance please. 

@GriffGreen I'm sure you would be a great resource for filling this in, if you had a moment please

**Comment by WhyldWanderer** [comment]
More info from Community Building Sync call notes:
![image](https://user-images.githubusercontent.com/74267818/196463795-841dc72f-cf1c-419a-8bd6-bbbf8dcee05f.png)

**Comment by SnakeGH** [comment]
Action Items: 

-quickly review google doc and add points of contact with current partners
- Create Discord channel to have a direct communication channel. 
- Set up a process and a structure from Giveth to us set our own terms.  

What are we offering? (ideas) 
Add them to the monthly newsletter. 
Share their status in our social media. 
Dedicated calls 
Partner Twitter Spaces. 

Here is a deck of thoughts we all agreed upon for what Giveth can offer 

https://docs.google.com/presentation/d/16pus0-911X7drZU3hUOEfI3wod13XXkAhVjtsmcwJOE/edit#slide=id.p

**Comment by SnakeGH** [comment]
Updates - all current partners information has been confirmed / received and added to Hubspot. Initial outreach by Jake will happen this week and tracking of the comms will be added to hubspot. 

Additionally, tasks in hupspot will be added to ensure continuos and regular check ups are being made by Jake

If a partnership develops into many action items, a discord channel will be created 

If a partnership requires monthly marketing tasks, an Github issue will be created, and an Epic will be applied 

This will be the process moving forward for all current partnerships
