### ISSUE TITLE
Key stats & data

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#904]
Share stats that would be interesting to various target groups, and showing progress in certain aspects. Timeline is really up to us on what want to highlight. We should properly brainstorm these - I've set up [a document here to work in](https://docs.google.com/document/d/1wgJC9Cw9UnXh2_QdQmKLuLc2pdgbOFCPkKw8sOmbsqM/edit).

**Comment by ahmadabugosh** [comment]
hey @c0ric0ri, what time range are you thinking of (or do you have a certain format in mind)? Google Analytics just started collecting data this week, so we may have more going forward, but here are some top stats I found (I think doing them by quarter might be more impressive than biweekly) :

For Q3 2022 (July to September 2022)
- 558 K USD in Donations that went directly to projects
- 232 new public goods projects listed on Giveth
- 60 new projects were verified and added to the GIVbacks program
- 1,141 new users started donating to projects

Let me know what you think. Also, maybe we should have the design team make an infographic?

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh these are great. I'm thinking we share stats that would be interesting to various target groups, and showing progress in certain aspects. Timeline is really up to us on what want to highlight. We should properly brainstorm these - I've set up [a document here to work in](https://docs.google.com/document/d/1wgJC9Cw9UnXh2_QdQmKLuLc2pdgbOFCPkKw8sOmbsqM/edit).

Infographics are also great, yes.

Important Target Groups like:

- Investors
- Donors
- Projects

Show Growth or progress in:

- number of projects on the platform / new verifications
- total donations
- number of individual donors
- number of GIVbacks claimed by donors
- amount of GIVpower allocated to donors
- amount of GIVpower being staked / locked

**Comment by c0ric0ri** [comment]
@SymSL @clara-zi @tropicalmangos are there certain monthly stats you would add the doc?

**Comment by c0ric0ri** [comment]
Per @ahmadabugosh infographics would be great to report on stats externally

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri , I'm not sure how to proceed with this issue. Can we discuss it in the comms meeting?

1) A lot of the suggestions here are hard to extract (like number of amount of GIVpower allocated to donors) and others I don't think would be very impressive (like number of GIVbacks distributed or Regen rewards). 

2) I suggest we stick with simple ones we can extract (I recommend we do this every 2 weeks, to keep it in line with the GIVbacks rounds), such as:
a) Data from the new Giveth dashboard: https://analytics-dashboard-blue.vercel.app/ (like # of donations, # of new projects and $ of donations)
b) Interesting or fun stats about projects, such as the most popular project this month, the project with the greatest impact (which would be subjective that the community builders team can help with). 
c) We could have fun stats from Google Analytics, like the breakdown of donors by country or the breakdown of projects by country (to show how international we are). 

------

Once we decide on the simple regular things we can compile every 2 week, let's get help from the designers to make a nice infographic format.

**Comment by clara-zi** [comment]
> @SymSL @clara-zi @tropicalmangos are there certain monthly stats you would add the doc?

@c0ric0ri Could add some DAO stats - ie how active our community is - eg no. of new proposals: could be a way to start a conversation about how our governance works, how creative our community is etc.

**Comment by SymSL** [comment]
Hey guys, I've added some suggestions to [Cori's document](https://docs.google.com/document/d/1wgJC9Cw9UnXh2_QdQmKLuLc2pdgbOFCPkKw8sOmbsqM/edit) from what I can see from the analytics that may be a good start for the infographic, either one big one, or smaller ones to share as posts on social. I have also added a log of the monthly analytics on[ slide 12 of this doc](https://docs.google.com/presentation/d/1xSy5rTGeupV1_F1-OUOX5h9d2mkPxFx02Yvqi933oNQ/edit#slide=id.g1b22360eae9_0_102) if you'd like to look back.

Something I am not sure of: If the analytics taken from [here](https://analytics-dashboard-blue.vercel.app/) are duplicating the monthly amounts from month to month when I try pull data for each month. If I select only August, for example "2022 - 08" to "2022 - 08" it brings up Zero. But if I select "2022 - 08" to "2022 - 09" I am not sure if its including Septembers numbers in there (I cant select the day, can only select by month). If anyone knows please let me know. This becomes an issue when trying to see Septembers numbers I can only do that by selecting "2022 - 09" to "2022 - 10", and am not sure if the numbers are being included for both months there too.

**Comment by clara-zi** [comment]
end of Jan report here to begin building a picture for trends.
https://docs.google.com/presentation/d/1LTzZ7yRk2wD558nzbqKZhctlTNRfHXdiu34URXsVZAY/edit?usp=sharing
I will see what these stats can look like in Google studio for metrics dashboard @SymSL and whether it can save time and be more visual. @ahmadabugosh gave me a demo - thanks :)

**Comment by clara-zi** [comment]
@SymSL using Google studio will make it easier to compile stats each month. Here's a draft: https://lookerstudio.google.com/s/khFesB04u60  that I'm working on

**Comment by ahmadabugosh** [comment]
hey @clara-zi can you share it with the public, I can't open it

**Comment by clara-zi** [comment]
Just checking back in to see if the share worked this time @ahmadabugosh

**Comment by ahmadabugosh** [comment]
I got it, looks good @clara-zi nice work! Maybe you can go over it in tomorrow's comms meeting?

**Comment by c0ric0ri** [comment]
Do you want to keep this for social media strategy? @ahmadabugosh @oyealmond

**Comment by oyealmond** [comment]
yes! Thanks @c0ric0ri! 


@ahmadabugosh as owner of stats subchapter, could you please check out the status of this issue & work in a proposal of the stats you believe are the most useful to start measuring and presenting please?

**Comment by oyealmond** [comment]
As discussed in today's synch we're starting w/ high level metrics: 

**- Analytics (done on a per month basis)**
    - Dapp from [https://analytics-dashboard-blue.vercel.app/](https://analytics-dashboard-blue.vercel.app/) / Blockchain data. Doesn’t give us the source.
        - # of donations
        - Amount of donations
        - # of new projects
        - # of verified projects / verification team. AdminBro (projects verified or unverified). - Filter. (Exclude the Giving Block?)
        - GIVbacks amount / GIVbacks sheet.
    - Website (Google Analytics)
        - Dimensions: Sources (channels) /Twitter, SEO, etc
        - Metrics: Total visits, New users, Donations made, Projects made

Next steps 
Create a spreadsheet w/ this information to kick off. 

@ahmadabugosh

**Comment by NikolaCreatrix** [comment]
Hey @ahmadabugosh I have commented in the doc with the numbers of verified projects per those months, we will have to obviously wait for the June one... is this what you wanted?

**Comment by WhyldWanderer** [comment]
The rounds that were in January 2023 were Round 27, 28, and 29.
I was able to find them by looking at the forum posts

Round 27 - Dec 27th - Jan 10th
Round 28 - Jan 10th - Jan 24th
Round 29 - Jan 24th - Feb 7th

https://forum.giveth.io/t/round-27-givbacks-and-nice-distribution/966
https://forum.giveth.io/t/round-28-givbacks-and-nice-distribution/987
https://forum.giveth.io/t/round-29-givbacks-and-nice-distribution/996

**Comment by ahmadabugosh** [comment]
hey @oyealmond @WhyldWanderer , I'm thinking to leave out the GIVbacks amount from the KPI sheet because: 

1) It doesn't align with monthly tracking because it's every 2 weeks.
2) I don't think it really benefits us much, since we're already tracking the donation amount. I think instead we could look at the GIVbacks amount as a percentage of the total donation amount, and just monitor it separately (in the future maybe we could do KPI's for the GIV token and GIVeconomy, which could include stats about GIVbacks, GIVpower, GIVfarm etc.)

**Comment by oyealmond** [comment]
agree @ahmadabugosh ! Thanks!

**Comment by WhyldWanderer** [comment]
Makes sense to me!
