### ISSUE TITLE
Design GIVpower banner for giveth.io for when we launch boosting

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#905]
Hey @rodricastillo9013 !

When we launch boosting we'll need another GIVpower banner, but the copy will change (and it would be cool to make it look different too).

We can say something like:

"GIVpower is here!"
"Earn rewards while boosting projects to new heights."

**Comment by laurenluz** [comment]
it would be great to have something for this sometime late this week - no rush!

**Comment by rodricastillo9013** [comment]
ok! perfect!

**Comment by rodricastillo9013** [comment]
<img width="1440" alt="givpower2" src="https://user-images.githubusercontent.com/61791380/194023508-c9286d67-b932-48f9-8ad2-70ca68a4e625.png">
wdyt?

**Comment by laurenluz** [comment]
PERFECT 🚀

**Comment by c0ric0ri** [comment]
So cool! Moving this to Done :)

**Comment by MohammadPCh** [comment]
@laurenluz  @rodricastillo9013 Thanks,
It's good to have separate text and background, so then we can handle some situations like this:
![image](https://user-images.githubusercontent.com/17097576/196471524-9cfffa1a-e9b4-4632-b5fb-e400416c7916.png)

**Comment by laurenluz** [comment]
@rodricastillo9013 can you separate them for Cherik?

**Comment by rodricastillo9013** [comment]
so
<img width="589" alt="Group 659" src="https://user-images.githubusercontent.com/61791380/196982765-41adbf6c-2125-46fa-873b-06c505fdabcd.png">
<img width="1440" alt="Frame 2465" src="https://user-images.githubusercontent.com/61791380/196982769-be4538a2-37b4-44ac-8bb1-b47c7d81a11c.png">
rry for the delay @MohammadPCh
