### ISSUE TITLE
Big impact issue!! Update "What is Giveth" in the docs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#907]
I notice that many many many people who feature Giveth just copy/paste the first lines of this page in our docs: https://docs.giveth.io/whatisgiveth/

I see *all the time*, and tbh, it feels a bit weak/outdated. The first paragraph on this page should be STRONG. And later on the page, we should show our Giveth roadmap.

[This issue](https://github.com/Giveth/giveth-planning/issues/906/) has some great ideas for improvements. I think we should revise the 1st paragraph to something like my suggestion:

> "Giveth is building a culture of giving that rewards and empowers those who give. Beginning with a crypto donation platform on Ethereum, Giveth has created the "GIVbacks program" where donors to for-good projects are rewarded with GIV. The long-term vision is to continue this trajectory and use web3 technology to transform the funding and stewardship of public goods by helping for-good projects become DAOs with their own regenerative micro-economies."

And add the roadmap content somewhere as per @divine-comedian 's suggestion:

> How does Giveth support Public Goods?
> 
> Giveth supports for-good projects and public goods in a myriad of capacities, one only needs to look at our token economy (GIVeconomy) roadmap features:
> 
> GIV - A transferrable ERC-20 token that lies at the heart of the future of giving.
> 
> GIVbacks - The entry point to the GIVeconomy, donors to verified projects, including public goods, get GIV tokens in return. This flips the script on tax deductible donation, creating a decentralized and borderless way of incentivizing donations. (LAUNCHED ✅ )
> 
> GIVgarden - GIV token holders are able to propose and vote on how to use the Giveth community treasury, including funding external builders, sponsorships and public goods. (LAUNCHED ✅ )
> 
> GIVpower - Donors can wrap their GIV tokens for GIVpower and use them to boost/curate projects and public goods on the platform. Projects with more GIVpower are ranked higher and in turn, reward their donors with more GIVbacks. (Q3 2022)
> 
> GIVmatching - Top-ranked public goods and for-good projects on the platform will have the opportunity to have their donations matched via a collectively funded matching pool. (Q2 2023)
> 
> GURVES - The holy grail of public goods funding. Public goods on the platform can opt to be turned into fully fledged micro-economies. Giveth deploys an Augmented Bonding Curve for projects that allows Givers to invest GIV in projects and provide continuous funding for the project's goals. (TBA)

**Comment by divine-comedian** [comment]
I could take a stab at this unless you had someone in mind. 

I also was hoping to update some of these useful docs:

https://docs.giveth.io/dapps/projectdonating
https://docs.giveth.io/dapps/createproject
https://docs.giveth.io/dapps/gettingStarted
https://docs.giveth.io/dapps/faq (Make it match - https://giveth.io/faq)
https://docs.giveth.io/dapps/torusUserGuide
https://docs.giveth.io/dapps/torusonramp
https://docs.giveth.io/dapps/donatingmetamask

**Replace photos**
https://docs.giveth.io/dapps/givethIO

It could be worth getting a newbie's eye on this I thought if @tropicalmangos wanted to own a task this may be good for her.

**Comment by danelsuga** [comment]
Updating docs other issue: 
https://github.com/Giveth/giveth-planning/issues/908

**Comment by danelsuga** [comment]
I will do this on Wednesday or Friday (Oct. 12 or 14) when I have time.

**Comment by danelsuga** [comment]
I will not say no to that! Thanks @tropicalmangos !!

**Comment by danelsuga** [comment]
How's it going @tropicalmangos ? I sent in @laurenluz's suggested changes as a pull request for now, but you/we/I can and should modify until we've got the best we can do!

**Comment by danelsuga** [comment]
I said, "I will not say no!" (An expression which means yes, wow, thank you.) 🤣

**Comment by danelsuga** [comment]
Sorry about that!

In the explanation of this issue, Lauren asks for an upgrade to the text of "What Is Giveth?" and à way to incorporate the roadmap there are well. I put in her suggested text for the first part, but I think we ought to fine tune it. Secondly, we can find a way to incorporate the roadmap as well. Maybe you can help brainstorm where/how to incorporate that roadmap? Thanks for jumping in!

**Comment by danelsuga** [comment]
Thanks!! I don't think there is a google doc, if that's what you mean. In the first post of the issue is the Giveth doc to be modified.

**Comment by laurenluz** [comment]
@tropicalmangos @danelsuga - let's keep this issue to one assign-y... I spoke with @danelsuga about this in our buddy call because it's a good issue for her as someone who is really familiar with the Giveth messaging & roadmap.

@tropicalmangos will message you with some suggestions for tasks you can pick up.

@danelsuga if you want some feedback after you have a draft, feel free to tag mango or anyone else (especially me, this is very important to me).

**Comment by c0ric0ri** [comment]
Hey @danelsuga ! Would you please provide an estimate date for a first draft on this, what you think is within your capacity?

This is in reference to our discussion around timeline estimates in the Comms meeting this week, I'll be putting out reminders for a bit. :)

**Comment by danelsuga** [comment]
This can be done in a week. I've got here a draft. 

https://docs.google.com/document/d/1I8xiDFtUZ1gbXhoS5buJNt9giy4C_C7Qky3gUgA75Xc/edit?usp=sharing

I didn't edit @divine-comedian's roadmap. Just wanted to get some feedback on the layout.

I designed it to have a succinct and impactful first paragraph. And then let the MVV remain, followed by the road map. Seemed like a good layout, since modifying the MVV isn't really part of the equation.

Feedback requested.

**Comment by divine-comedian** [comment]
> let's keep this issue to one assign-y...

are you trying to spell assignee?

@danelsuga the roadmap isn't comprehensive - I made that quick draft to help yass pitch giveth's public goods angle to optimism

the biggest thing missing on there is GIVfi

**Comment by danelsuga** [comment]
Ok! Thanks! Will take care of it.

**Comment by danelsuga** [comment]
This has taken a backburner to the Project Owners 101 Course article I'm working on this week instead.

However, I had already written the preliminary text, which anyone is welcome to review.

https://docs.google.com/document/d/1I8xiDFtUZ1gbXhoS5buJNt9giy4C_C7Qky3gUgA75Xc/edit

**Comment by danelsuga** [comment]
This has taken a backburner to the Project Owners 101 Course article I'm working on this week instead.

However, I had already written the first paragraph(s), which anyone is welcome to review.

https://docs.google.com/document/d/1I8xiDFtUZ1gbXhoS5buJNt9giy4C_C7Qky3gUgA75Xc/edit

**Comment by danelsuga** [comment]
I've written a new introduction and have cleaned up the roadmap. Can some folks have a look please? 
adding a couple new tags in that case:
@c0ric0ri @ahmadabugosh @WhyldWanderer

**Comment by ahmadabugosh** [comment]
hey @danelsuga looks good, but can you also add some of the wording we have in this recent pitch deck we compiled https://docs.google.com/presentation/d/1ra3wETvHsHHDk1ogQ9FNc4LPQ7UV_lAg-K3ZsLhmzpQ/edit#slide=id.g1717d430748_0_0 (especially around GIVfi, Gurves etc.)

**Comment by danelsuga** [comment]
Separate issue: could I have access to that deck for editing, if you don't mind @ahmadabugosh? I'd love to be able to clean it up a bit in terms of copyediting stuff, if that's ok. Thanks.

**Comment by danelsuga** [comment]
Looking for another pair of eyes for QA on this doc "What Is Giveth?"

Most importantly, the first paragraph section and the roadmap at the end.

https://docs.google.com/document/d/1I8xiDFtUZ1gbXhoS5buJNt9giy4C_C7Qky3gUgA75Xc/edit?usp=sharing

@divine-comedian 
@GriffGreen 

Thanks!

**Comment by divine-comedian** [comment]
reviewed!

**Comment by GriffGreen** [comment]
reviewed!

**Comment by danelsuga** [comment]
Thank you @GriffGreen and @divine-comedian !

I'll be going over last edits, and this'll be done asap.
