### ISSUE TITLE
Update important Giveth docs

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#908]
Please think about recording or documenting this in some way for onboarding purposes

**Comment by c0ric0ri** [comment]
@divine-comedian

**Comment by divine-comedian** [comment]
I think the most important step will be to get yourself familiar with markdown syntax - this is what we use to format text in the docs to make it beautiful - it also is used in the forum as well! 

https://www.markdownguide.org/

**Comment by franculio** [comment]
Thanks @divine-comedian ! 

I already learned route 1 in a masterclass about markdown, hackmd and how to do update through github with Lauren. So I'm familiar with this way. 

I do have vscode installed in my computer but I never really played with it much, maybe it's time! I'll do research on this.

My one question is about the images uploading, last time I updated through github I just copied them and they were available through imgur server and you changed to the local server (makes sense) but I don't know how to do that.

**Comment by divine-comedian** [comment]
Okay yes I'm down! 

If you guys want to go the vscode route here's some things to get started:

- generate an ssh key and link it to your github account
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh

- set your username and email in git 
https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git#setting-your-git-username-for-every-repository-on-your-computer

**Comment by divine-comedian** [comment]
maybe this friday we can plan something?

**Comment by laurenluz** [comment]
I could do 9-10am Friday Costa Rica time, or else can't make it. We'll be heading to SJO Friday.

**Comment by franculio** [comment]
Friday works for me! Just to be sure 9am Costa Rica is 5pm CET right?

**Comment by divine-comedian** [comment]
Okay I made the event - it should be on the giveth calendar 
https://calendar.google.com/event?action=TEMPLATE&tmeid=MWJtdWlvczVjcXFqM3VhZWo1MXZ0YzJjYTIgZWNwLm96ekBt&tmsrc=ecp.ozz%40gmail.com

**Comment by divine-comedian** [comment]
@franculio another side note - we also need to maintain our spanish translation of the docs
As you're updating some key docs I am making a note here to show you how to put in the spanish versions as well

**Comment by franculio** [comment]
Perfect, thanks @divine-comedian !

**Comment by franculio** [comment]
Thanks @c0ric0ri for making this an epic! I've already created the issues for each update. I'll be working on this this week.

**Comment by oyealmond** [comment]
@franculio can we close this epic?

**Comment by franculio** [comment]
Closing epic
