### ISSUE TITLE
Finalize list of Airdrop recipients

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#91]
Finalize the list of airdrop recipients. Griff to make sure Jordi is on the list. Willy to add donations to the daostack address. 
    1. Should airdrops degrade/expire if they aren't claimed? ie. BadgerDAO and stakeDAO
    2. Will we reward contracts? Yes
    3. Will we reward failed txs? No
    4. Ideally make sure everyone who has donated to giveth on chain is included (no donor left behind)
        1. Tasks:
        2. Figure out the quadratic algorithm
        3. Figure out value of donations at the time (ideally at the time of donation) for all the erc20 donations. Could even be a manual task because there aren't too many donations. 
        4. Get spreadsheets of all direct donors to giveth, Amin is delivering the spreadsheet of donations on Giveth 1 and the spreadsheet of donations to Giveth multisig and Gitcoin, 
        5. Go through the spreadsheets and figure out how to distribute each bucket of airdrop tokens to donors in that category
        6. Should we donate to everyone who donated on Gitcoin?
        7. Should we donate to everyone who contributed on clr.fund?

**Comment by Danibelle** [comment]
Past Donors Distribution List Complete - BUT, found some missing addresses - is this updated yet?
Past Contributors Distribution List Complete - not voted on yet?
Current Contributors In Progress - Dani needs spreadsheet formula support on [this doc](https://docs.google.com/spreadsheets/d/1Kp8WqRwDGyORqaDcXpeGR2PnhVTMKlTdU-eDRWeDBN8/edit#gid=0)

**Comment by ForestSoleil** [comment]
@bowensanders @willyogo let us know when this issue is ready to close
