### ISSUE TITLE
Improve our listing on DeepDAO

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#910]
https://deepdao.io/organization/e30d591d-76f2-4eb4-bd05-04124e100210/organization_data/dig_deeper

**Comment by ahmadabugosh** [comment]
@franculio can you take this on? 🙏

**Comment by franculio** [comment]
Hey @ahmadabugosh ! Yes, I can definitely help out here! 

I would need for someone to give me access to the profile already created so I can upload the info. Do you know who listed Giveth there @GriffGreen ?

**Comment by laurenluz** [comment]
@franculio just seeing this issue, Griff basically never sees github tags, so best to DM him to get the info you need :)

**Comment by franculio** [comment]
I'm closing this issue since it's been referenced this [issue](https://github.com/Giveth/GIVeconomy/issues/729).
