### ISSUE TITLE
Giveth Contributors Twitter Session - G Essentials 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#913]
We can add to Giveth essentials program

The purpose being to create a doc about what is Twitter, why it is important, how to grow you account, use it to support Giveth etc.

And then have a one-off meeting opt-in to explain the topics to Unicorns.

**Comment by oyealmond** [comment]
Hey @c0ric0ri ! 
This is an issue that was created around having a session around Twitter. Basically the same session you and me discussed today. 

Just pointing this out to use this same issue to organize it.

**Comment by oyealmond** [comment]
Hey dear team! @c0ric0ri & @laurenluz 
I prepared[ this Notion guide](https://www.notion.so/giveth/Twitter-Best-Practices-d00e5d88707f463c981c4cecb9db1142) to follow on our next G Essentials Titter Best Practice session, next Tuesday after Comms Call. 

Let me know your thoughts.

**Comment by oyealmond** [comment]
Great session! 
https://www.youtube.com/watch?v=DJB9QXlyR8w&list=PL6oqELoqsEmpf9nSjr5kRj4IQginmcrmc 
Thank you team! @c0ric0ri @laurenluz
