### ISSUE TITLE
Tweet the Meet the Makers session recording 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#919]
Hey dear team! We have a really successful Meet the Makers session! 
Could you help us share the recording in a Tweet in case someone interested missed it? 

@c0ric0ri @laurenluz 

Here's the tweet draft - https://docs.google.com/document/d/1APP7SaOYb3ZHCD7yA9sVlD8Lfb4nvLti54yEbknj9zg/edit?usp=sharing

**Comment by c0ric0ri** [comment]
Thanks @oyealmond ! I added some edits and we can plan to share (@laurenluz).

**Comment by oyealmond** [comment]
Already accepted the edits! Ty @c0ric0ri !

**Comment by laurenluz** [comment]
I'll schedule it for friday, made some tweaks. tomorrow is way too many event announcements.

**Comment by laurenluz** [comment]
Thanks to you both for moving this forward! really helpful.

**Comment by oyealmond** [comment]
Ty both!

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1578385414087491587
