### ISSUE TITLE
Strategically brainstorm community call intentions & livestreams

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#92]
- Forest & Dani to strategically brainstorm how to transition our community calls to taking questions from community, involving project owners in sharing rather than doing work as internal team
- Ask Willy to share his story around Cause and ETHvember. There are things we aren't talking about full yrigh tnow that would make sense to share in a community call and build buzz/excitement. 
- Also remember Discord and our ability to use that platform to communicate with these communities, projects & people. 
- How to share epic livestreams in twitter campaigns?

**Comment by Danibelle** [comment]
Praising each other is great!  What else can we praise?
New projects listed, name the "best in class" each week?
Donor stats that James is pulling! How much raised, how many new donors?
New contributors to Giveth, joined Discord AND introduced themselves?
Cool things in the Ecosystem, airdrops and staking/liquidity mining discoveries from the team?
