### ISSUE TITLE
Giveth New Features Survey

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-planning#920]
Tosin created this draft for the New Features survey that he would like to send out to users.

Are there a few people that can take a look at this and give feedback as well as QA?
@laurenluz @danelsuga @c0ric0ri 

https://docs.google.com/document/d/1ro-ozCDm4L_QowN3AcFWRv4lI5sf3Buo0bPJgIfap3o/edit?usp=sharing

**Comment by Tosinolawale** [comment]
HI guys, still waiting on update for this.

**Comment by Tosinolawale** [comment]
Hi @c0ric0ri Would love to have the survey ready and sent out before this week's community call. So just go over the draft on your end, edit and make comments and I will prepare the typeform when we are good to go.(Hopefully before Thursday)

**Comment by danelsuga** [comment]
Hi. I did some editing of the survey. Great job with thorough ideas. However, it seems really long! I also noted that a few of the questions could be combined or at least shifted so that they are together. See my comments. Great job!

**Comment by Tosinolawale** [comment]
Thank you @danelsuga, @WhyldWanderer and @c0ric0ri

**Comment by Tosinolawale** [comment]
> Hi. I did some editing of the survey. Great job with thorough ideas. However, it seems really long! I also noted that a few of the questions could be combined or at least shifted so that they are together. See my comments. Great job!

Will go through them all. Really appreciate this.

**Comment by Tosinolawale** [comment]
https://giveth.typeform.com/to/UBOpjhhq

That is the generated typeform for the survey @WhyldWanderer @danelsuga @c0ric0ri

**Comment by laurenluz** [comment]
Hey @Tosinolawale, taking a look at this, I think it should really be broken up into multiple surverys.. one for each topic. some people may not be "verified project owners" and may only be interested in GIVpower, for example.

Having it all together makes it prohibitively cumbersome and I don't think we will get much engagement.

**Comment by Tosinolawale** [comment]
> Hey @Tosinolawale, taking a look at this, I think it should really be broken up into multiple surverys.. one for each topic. some people may not be "verified project owners" and may only be interested in GIVpower, for example.
> 
> Having it all together makes it prohibitively cumbersome and I don't think we will get much engagement.

Yeah. @mosaeedi and I had a discussion on this too. We've actually considered having multi surveys for each feature, and I think that will make more sense too. The only drawback here is how overwhelming it can also be sending three or four surveys out at once.

**Comment by laurenluz** [comment]
I think it is less overwhelming overall and will produce better results. We could make a twitter thread... with one line in each tweet. Or a few bullets in an email... with one survey on each link.

Then people can pick & chose which ones apply to then. @Tosinolawale

**Comment by WhyldWanderer** [comment]
Hmm... thats a great question. I know that @Tosinolawale did a series of surveys and they got changed or evolved after this draft. I can see the surveys in typeform but none of them sound like 'new features' survey.

Tosin.. do you know if this issue was completed? Or did we decide not to do it?
Or maybe it is one of these forms and was titled something different?

![image](https://github.com/Giveth/giveth-planning/assets/74267818/edb6d538-30a9-4049-ba2c-6c2e9bad27b8)
cc. @oyealmond
