### ISSUE TITLE
DevCon / Bogota Tweet

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#921]
Would love to write on Sunday, a thread with some details on where to catch Giveth during Bogota.

I am giving a talk at sustainable blockchain summit: “Reimagining the Money Game”  is scheduled for 3:00pm - 3:15pm (15 mins) on Wednesday, October 12th on the Selva Stage.

@GriffGreen is speaking at DevCon, Wed Oct 12 

@mateodaza is speaking at ETH Latam on a panel

@Cotabe is giving a talk at the DAOist

I would love a thread that mentions the titles, times & speakers for all these talks, tag the org that's hosting them, link to where to register/view the stream (if possible).

And it would be perfect to get this out Sunday Oct 9

@c0ric0ri can you try to put this together? it will require checkin in w/ these people and doing some searching for tags and links. It would also be good to ask the rest of the team attending in case we missed anything!

**Comment by c0ric0ri** [comment]
Yes I'll work on this!

**Comment by c0ric0ri** [comment]
@mateodaza:

Event: ETHLatam
Stage: Andina
Title of Panel: Qué son los "Public Goods"

Panel attendees: Ale Borda, Fifty Years + Cristian Espinoza G. , Cryptex Finance & Ethereum Honduras + Mateo Daza, Giveth.io + Manu Alzuru, DoinGudHQ
Monday october 10th - Andina Stage
15:30-16:00
https://ethlatam.org/

@laurenluz:

Event: Sustainable blockchain summit
Talk title: “Reimagining the Money Game”
Stage: Selva
3:00pm - 3:15pm (15 mins) on Wednesday, October 12th
https://sbs.tech/#agenda

@Cotabe:

I checked the full The DAOist Bogota schedule and don't see Cotabe anywhere, so definitely need input. Sent DM, but I know he's very part time this week so if anyone else has info please let me know! 
https://www.thedaoist.co/schedulebogota

@GriffGreen:

Event: DevCon Bogota
TItle: The Biggest Web3 Opportunity No One is Talking About!
Day 3 —Thu, Oct 13- 16:00 - 16:30 local time
Stage: Tropical Sunset
https://app.devcon.org/schedule/7NU8VB

**Comment by c0ric0ri** [comment]
Hey @laurenluz , the first draft is ready for review here! https://docs.google.com/document/d/1_IYoArBgbFhLKAzOQWAUYQHzwbmmoEWg_oJbQFWR04k/edit

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1578747800199860225?s=20&t=dVvAZRoXo4Ir5nlL9oHY4Q
