### ISSUE TITLE
Share GIVpower AMA Twitter Space recording 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#922]
Dear Twitter team! @c0ric0ri @laurenluz 

Could you please schedule the recording for our last Twitter Space whenever is best? 
Hope this copy is useful: 

https://docs.google.com/document/d/1NWvZgj1HYj9B67HMyRHnqwMp6igCJRc79csLS_-dL7U/edit?usp=sharing

**Comment by laurenluz** [comment]
nice - I scheduled it for monday (minor edits) - thanks!

**Comment by laurenluz** [comment]
ooh hey almond -please add these tweet issues to the twitter epic next time too: 
![image](https://user-images.githubusercontent.com/75490971/194435910-e92ef7ce-ef64-462d-b70c-4ef8f23868a1.png)

**Comment by oyealmond** [comment]
Thank you so much @laurenluz ! I didn't found the Epic before. ✨

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1579472577742995462
