### ISSUE TITLE
Tweet - remind people of angel vault

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#924]

**Comment by laurenluz** [comment]
we should post this within 2-3 weeks, anyone can take this on drafting

**Comment by c0ric0ri** [comment]
Thanks @oyealmond for taking this on!

It would be great to draft a new tweet thread that:

- reminds people we launched the Angel Vault this summer
- summarizes the benefits of the Angel Vault
- references the medium article
- encouraging people to provide liquidity to the oneGIV / GIV pool in the GIVfarm: https://giveth.io/givfarm
- they can read our docs as well: https://docs.giveth.io/angelVault/

Some references:

The tweet thread we posted announcing the launch: https://twitter.com/Givethio/status/1554154140242087936?s=20&t=GJUCKXBr4yR55Wo659DjPw

And the medium post: https://medium.com/giveth/the-evolution-of-giv-liquidity-introducing-the-giveth-angel-vault-5ee34b2965c1

**Comment by laurenluz** [comment]
wow - great outline @c0ric0ri!!

**Comment by oyealmond** [comment]
Heeey @laurenluz and @c0ric0ri, check out 2 drafts [here. ](https://docs.google.com/document/d/1jHWyb1cxO7XGDHJ0fh4ae_IlWTveCbNQW1iSpLKsfvU/edit?usp=sharing ). Feel free to edit and schedule.

**Comment by ahmadabugosh** [comment]
hey @oyealmond I also made a video here that you may be interested in including in the thread (if @laurenluz approves): https://github.com/Giveth/giveth-planning/issues/814

**Comment by oyealmond** [comment]
Oh nice @ahmadabugosh! Thank you :)

I included your video tutorial as well [in the drafts. Uhoo](https://docs.google.com/document/d/1jHWyb1cxO7XGDHJ0fh4ae_IlWTveCbNQW1iSpLKsfvU/edit?usp=sharing)

cc @laurenluz @c0ric0ri

**Comment by laurenluz** [comment]
Hey friends, sorry for this... but putting it in the icebox becuase we are likely to terminate the angel vault incentives.

**Comment by oyealmond** [comment]
ofc, completely understand. @laurenluz 
Here to support
