### ISSUE TITLE
Tweet - Announce 5 Giveth Donor Survey $NICE winners

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-planning#925]
Hey @c0ric0ri 

For better organization, as discussed, here is the issue to have a tweet to announce the 5 winners of the donor survey reward. 

**Priority** - in next week so maybe Tuesday Oct 12th or Wednesday Oct 13th 

**Video I made to announce the winners** -https://www.loom.com/share/328722cef6c04f4b93bd5454459df4c3

**Message (but feel free to edit to better represent Giveth)** - 

"Thank you to everyone who took our Giveth Donor Survey and are helping to shape the future of giving!

Now onto the prize of some $NICE tokens! I present to you the video below… 

*Please note, 21 participants were eligible, and the 5 winners will need to DM @givjake their wallet addresses*"

**Winners twitter handles to tag in message** -   @zeptimusQ @diamantebridge @kaicanna @mettoddo @validatoreth

**Comment by SnakeGH** [comment]
@laurenluz @oyealmond also tagging you, as I know you 3 are the Tweet Queens.

**Comment by c0ric0ri** [comment]
Thanks @SnakeGH !

I reworked the draft a bit into a thread in the doc below. Let me know what you think @laurenluz 

https://docs.google.com/document/d/1nWnqkVwE_nDy7hKHQd_stAFNFk--OMJx-PylFfzy35E/edit

**Comment by laurenluz** [comment]
Thanks both! I edited it a little in tweet hunter & queued up for next week.

**Comment by SnakeGH** [comment]
@c0ric0ri @laurenluz really AMAZING edits...thanks and can't wait to see it on Tuesday!

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1580559738701586433?s=20&t=maFqy2mV_TbmhKNnwQWaGA
