### ISSUE TITLE
Tweets Promoting GIVpower Workshop - early Jan

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#928]
Hey dear team, whenever you can could you help me review and schedule whenever you find best, this tweets around our next GIVpower workshop? 
@laurenluz @c0ric0ri 

Found copies at the end of [this doc](https://docs.google.com/document/d/1QaHl3ZM5Ga-EepBVvlKzmu_0rqPnA7nsatxDJHJKUrU/edit?usp=sharing)

Thank you!

**Comment by c0ric0ri** [comment]
Hey @oyealmond when do you want this ready by? I'm trying to prioritize reviews by urgency right now

**Comment by c0ric0ri** [comment]
Actually yes @oyealmond , I'll move this back to Backlog until we know we want to prioritize it for the week. I've also added it to the GIVpower Launch epic.
