### ISSUE TITLE
Medium post announcing social impact campaigns + shared across channels

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#93]
2/5/21 Marketing call update:
- Twitter hashtag to involve other people
- Post campaign on twitter, people can share videos
- Can we incentivize through giving out GIV tokens? **Need to vote on as full team around distribution. **
- Intention of campaign: welcome all social impact camaigns, not just Giveth users. 
- August to draft outline of this campaign, rules & incentives. WIP draft of this ready by Sunday, Feb 7th.
- Ideally have a video explaining this as well. Team up with Calvin. 
- Stagger this - great to announce this after launch to keep the momentum going. We want to hear the stories, what are you building?
- Is anyone else interested in collaborating with August on this? Ashley can support in sharing this campaign with past Giveth projects.

**Comment by laurenluz** [comment]
2/19/21 Marketing Call Update:

-Add video from Calvin at diamante luz to social impact campaign
- @divine-comedian to collaborate w August

**Comment by ForestSoleil** [comment]
2/23 Marketing update:
- Outline of campaign from August: https://docs.google.com/document/d/12t9gjgg8FWgOPGKaKf6rquiRfkw-UZs6al_mEcR5Osg/edit?usp=sharing
- Mitch would like to support moving this along. 
- Sharing this on Reddit.

**Comment by ForestSoleil** [comment]
3/2 Marketing update:
- Take the outline August wrote and blast it on social channels: Reddit, Twitter, etc.
- Then, feature projects and onboard new projects to Giveth.
- Edit the outline to arrange for each audience: Twitter thread vs Reddit vs Medium. 
- Mitch to own editing for Reddit and Medium.
- For Twitter, pull a tiny blurb of copy and link to official Medium post. 
- Lauren offering to support on ideation and QA.

**Comment by divine-comedian** [comment]
August and I hopped on a call this evening and we hacked out a 1st draft, ready for review! - https://docs.google.com/document/d/197oPHlxjFNhd3Jfhsb0oXViYsAa_0-n9qubbrg38Eh4/edit?usp=sharing

**Comment by laurenluz** [comment]
@divine-comedian and August... I reviewed and made a bunch of suggestions in the google doc:
https://docs.google.com/document/d/197oPHlxjFNhd3Jfhsb0oXViYsAa_0-n9qubbrg38Eh4/edit

Also I suggested at the bottom a more streamlined flow for the call-to-action, i.e.:

"Your Task?
1. Go to Giveth.io and add your project
2. Tell your story*
3. Share your project and story to your social media and tag us @ giveth"

then we can have more details on the "tell your story" part connected via " * " at the bottom of the article

This is getting posted on reddit? Maybe we could also post to Medium? Where do we get the most reach?

**Comment by ForestSoleil** [comment]
3/22 comms call notes- 

- Schedule this post to be published around mid April. TBD date scheduling - Are there any live webinars/talks from @GriffGreen , @willyogo , etc. who can share the social impact campaign kickoff?
- Run this campaign for 2-4 weeks. If campaign is successful, we will have stories to share to continue momentum across channels.

**Comment by divine-comedian** [comment]
https://docs.google.com/document/d/197oPHlxjFNhd3Jfhsb0oXViYsAa_0-n9qubbrg38Eh4/edit - final draft for QA @laurenluz @WhyldWanderer @ForestSoleil @Danibelle

**Comment by laurenluz** [comment]
I hacked at this a bunch... I think we should make a clear decision about the "end date" and in the launch piece say something about how we will highlight projects... I added my suggestion as a paragraph at the end of the doc. Let's discuss today in the hack sesh.

**Comment by ForestSoleil** [comment]
Thanks Lauren!

Agenda for comms jam session today:
- Review checklist for preparation we can go through on the epic Mitch created on github. 
- Quick discussion on how we can collect info as submissions are made
- Decide on how exactly we plan to feature projects (so we can include that in the launch post)
- Create a distribution schedule for sharing/shilling and take respective ownership so it's not just one person in all the channels
- Make awesome memes about the social impact campaign
