### ISSUE TITLE
GIVbacks round 20 is out! tweet

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#930]
@c0ric0ri could you write up a quick draft for this? It might be cool to mention that it was our longest round ever (because of the shift) and that more then 1M GIV went out (the exact number, I think you could look up)

It's kind of a fun version of our regular tweet

**Comment by laurenluz** [comment]
oooh and $nice went out too.

Here are the links, would be cool to make it a lil' thread. If you post a draft here sometime before tomorrow americas monring, I can do a final edit & post.

**Comment by laurenluz** [comment]
Sept 16th - October 4th
https://poap.delivery/givbacksround20
Also $nice went out
forum post: https://forum.giveth.io/t/round-20-givbacks-nice-distribution/847

**Comment by c0ric0ri** [comment]
@laurenluz here's the draft!

https://docs.google.com/document/d/1-rQyt5NkfjupdF_rchV753HrdzEuwqk7FDJKgwUo9us/edit

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1579835001931194369?s=20&t=0wiLevSpJhREHgbec75h7Q
