### ISSUE TITLE
Tweet Thread Verified projects R21

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#931]
Hi there, alright here we come with the next tweet thread about verified projects.

https://docs.google.com/document/d/1g990c4Nrg2Knrx5PvCIeeqMfGWXuvb6Hzxox82o4h74/edit?usp=sharing 

Let me know if it all makes sense or I shall correct anything. :)

@c0ric0ri 

Also, not sure if you want me to keep creating separate issues like this one or if you have now a different system. Just let me know what works best for you, please. 
Shall I put a 'content' label?

**Comment by c0ric0ri** [comment]
Awesome job @NikolaCreatrix thanks for this! I made some minor tweaks for you to confirm, and also left a few comments for you to check.

**Comment by c0ric0ri** [comment]
Hey @NikolaCreatrix friendly reminder to please check the edits :) 

@laurenluz we should schedule this one soon!

**Comment by NikolaCreatrix** [comment]
Hey @c0ric0ri thanks for the reminder! I loved your suggestions and thanks for couching me on how to improve my work. 

It should be good to go now.

**Comment by c0ric0ri** [comment]
@laurenluz this is good to schedule!

**Comment by laurenluz** [comment]
Thanks friends! scheduled for this week.
