### ISSUE TITLE
Project Donating

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#932]
Update https://docs.giveth.io/dapps/projectdonating

**Comment by franculio** [comment]
I've drafted an update for this doc. No major changes just added categories and sorting menu. 

@danelsuga could you take a quick look and review?

https://docs.google.com/document/d/1yHF3QjGNc4wKLcZj_DopsFbFAEIDw8QwkBgAhstz4lc/edit?usp=sharing

**Comment by danelsuga** [comment]
Great! Done! @franculio

**Comment by franculio** [comment]
Amazing @danelsuga ! Thanks!

**Comment by franculio** [comment]
This doc has been updated. Closing the issue
