### ISSUE TITLE
Create a Project

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#933]
Update https://docs.giveth.io/dapps/createproject

**Comment by laurenluz** [comment]
@franculio - @tropicalmangos is willing to take this on? is it still outstanding? can you give her some guidance

**Comment by franculio** [comment]
@tropicalmangos That'd would be awesome, it would be very much appreciated! 

Let's organize a meeting and tackle this together!

**Comment by laurenluz** [comment]
@franculio - awesome!! I think if you want to have a meeting, by all means, but I was thinking it might be easier if @tropicalmangos just works on the content & then when it's ready (and reviewed!) she can ask you to get it up on the docs.

Also, if there is something in particular that you know needs to be updated in this one from a content standpoint - it would be great if you could let her know (maybe by just a simple comment in here).

Anyway, not to dissuade you from meeting, just I didn't think it was necessary 😅

**Comment by franculio** [comment]
@laurenluz Great! Yes, that also works. I was just looking for an excuse to call @tropicalmangos 😊 

Thanks Lauren!

**Comment by franculio** [comment]
@tropicalmangos the document you posted needs permission to access, could you make it public?

**Comment by franculio** [comment]
I'll take a look today! Thank you @tropicalmangos

**Comment by franculio** [comment]
This has been updated, closing the issue!
