### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#935]
Make https://docs.giveth.io/dapps/faq/ match to https://giveth.io/faq

**Comment by NikolaCreatrix** [comment]
Hi @franculio Yess, happy to help.

Let's take the least sentence starting with 'If you would like to....' and let's say this:

"If you would like to apply to receive the 'Verified' badge, encourage more giving and give back to those who have helped you reach your goals, learn more about how to apply [here](https://docs.giveth.io/dapps/projectVerification/)."

so it links to the docs first.

Also Franco, are you working on the docs too? Or now only on giveth.io/faq

Cause it would be great to do some more minor edits in this section:
https://docs.giveth.io/dapps/projectVerification/

I found some minor grammar mistakes, see the picture. Also where it says PIC - that could be a place for prinscreen I am attaching here as well.

![image](https://user-images.githubusercontent.com/100084867/197259454-b76697f1-5e36-42ba-9609-3bf703831ae3.png)

![Untitled3](https://user-images.githubusercontent.com/100084867/197259485-9322adc5-d5a2-4b60-87bb-285621b5ae70.png)

WYT @franculio and @c0ric0ri

**Comment by franculio** [comment]
Thank you @NikolaCreatrix ! This is great, I'll add that little change to the FAQ, it was the only thing that I thought it needed to be different since we don't have the form anymore and we have the button.

About the Project Verification Process and Guidelines I did not have it in the epic but I'll create an issue to update it. I think the pic it's a great idea and I'll double check all the spelling in there. 

Could you maybe give this list a review and that everything that is in there is correct information that is being asked at the verification process? 

<img width="1185" alt="Captura de Pantalla 2022-10-25 a las 13 21 59" src="https://user-images.githubusercontent.com/79286405/197760079-413ec82c-87ee-4c8f-906d-bfbe76fdc487.png">

Also maybe we can take out the "Current project owners have until October 14th, 2022 to update projects" since that date was last week?

<img width="821" alt="Captura de Pantalla 2022-10-25 a las 13 19 56" src="https://user-images.githubusercontent.com/79286405/197760154-6fd2edee-8749-4a3b-a308-0f97bc62ca0e.png">

Let me know and thanks!

**Comment by NikolaCreatrix** [comment]
Hi @franculio sorry for the delay...yeah we may want to adjust slightly. In this [document](https://docs.google.com/document/d/1IAa8Osu7lbrULRAKkBA9ZtfTV0jq4dvns-9lyEAQS48/edit?usp=sharing) you see the new flow and all the questions as they follow. Might be faster this way... :)

**Comment by NikolaCreatrix** [comment]
Hey @WhyldWanderer wdyt?
