### ISSUE TITLE
Torus user guide

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#936]
Update https://docs.giveth.io/dapps/torusUserGuide/

**Comment by franculio** [comment]
Hey @danelsuga this is the update for this doc https://docs.google.com/document/d/1tzGutBdf40_6U8ErDlGVK8_F-RicU82-mP_x5PixFjs/edit?usp=sharing

Would be able to check that everything is looking good?

**Comment by danelsuga** [comment]
I just went through with some edits. :) @franculio

**Comment by franculio** [comment]
This has been updated.
