### ISSUE TITLE
Torus onramp

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#937]
Update https://docs.giveth.io/dapps/torusonramp/

**Comment by franculio** [comment]
Here's the updated guide:

https://docs.google.com/document/d/1-D-ipLXWATD8IB3RfLKEwQ3kS9KRRVNGkABURzwXKrQ/edit?usp=sharing

@danelsuga could you review this as well?

**Comment by danelsuga** [comment]
OK!

**Comment by franculio** [comment]
This doc has been updated. Closing the issue!
