### ISSUE TITLE
How to post an update to your project

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#944]
I would love to help with this one. 
As we implement the mandatory updates, we noticed that some users assumed that editing their project page will do it, so obviously, we need to be more clear on this, and creating a short little guide section in our docs would be very helpful and easy to refer to...

So in the USER Guides section of the Giveth docs, this one called 'How to post an update to your project' could become part of this 

![image](https://user-images.githubusercontent.com/100084867/195163835-e3d925b2-be6e-418c-98ac-c1be93fbccc0.png)

See the red line, that would be my suggestion for where to create this new section.

In the next few days I will work on the content and make sure to add print screens also.

**Comment by franculio** [comment]
This is done, closing the issue.

CC @c0ric0ri
