### ISSUE TITLE
Onboarding Email Campaign

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-planning#946]
Create an email campaign to onboard new subscribers who join our newsletter. Onboarding will include things such as: explaining what giveth is about, how to make the most out of giveth, how to donate, how to create projects etc.

**Comment by ahmadabugosh** [comment]
Thanks @tropicalmangos, I added some comments and links to your doc. 

In general, I think for the first emails we should avoid jargon that people don't know about like GIVeconomy, GIVbacks etc. until we get a chance to explain what those things are. 

I think it looks good now (and the other emails you suggested in the sequence seem fine to me too). 

Maybe one more person can take a look like @danelsuga ?

**Comment by ahmadabugosh** [comment]
@tropicalmangos Sounds good! 🙌

**Comment by danelsuga** [comment]
I left some comments on the first.

**Comment by laurenluz** [comment]
Hey @tropicalmangos - I went through and made some edits. The first two emails are good and after you accept suggestions/make changes, I think we could get a final review & send it out!

For the last, on verification, get some help from @NikolaCreatrix - maybe she can help write it with you. You didn't describe how to get verified well (missing steps) and the rest of the email was a bit choppy/repetitive. I make some suggested edits, but I think it could still be improved. Make sure you mention that verified projects are part of GIVbacks & of GIVpower... and that they get a rank.

I think GIVpower will be live before we set these up so assume that it is :)

**Comment by NikolaCreatrix** [comment]
@tropicalmangos absolutely, I will take a look and get back to you. Give me till the beginning of the upcoming week. I will look at this Monday latest.

**Comment by NikolaCreatrix** [comment]
Hello there @tropicalmangos sorry for my delay, I just left some comments for you.

**Comment by NikolaCreatrix** [comment]
@tropicalmangos its looking great now! Just left some minor edits and suggestions for you.

**Comment by SnakeGH** [comment]
Anything like the donor survey will have or would have a GH issue created, so here is where you can locate it: https://app.zenhub.com/workspaces/giveth-planning-5f08ce1f9264b300166a0185/issues/gh/giveth/giveth-planning/623

But for ease, here is the type form link as well:  https://giveth.typeform.com/donorsurvey?typeform-source=www.google.com

**Comment by laurenluz** [comment]
@tropicalmangos left suggestions in the doc

**Comment by oyealmond** [comment]
hey @tropicalmangos ! 
I went through the emails, but my question is, how do you envision these on a Tweet? The action around Giveth sending emails, or the info itself? cc @laurenluz

**Comment by ahmadabugosh** [comment]
hey @tropicalmangos nice work with this!

I have one suggestion though. I think that we should add a second email (between the current first and second email), to help onboard beginners, since I think we're jumping too fast into donating right away and GIVbacks. 

I'm thinking that second email could discuss:

1. How you should have a web wallet like Metamask 
2. How you should connect to Mainnet and Gnosis chain
3. How to load funds on your wallet

Basically content from the [Donors 101 course](https://www.youtube.com/playlist?list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ). I would suggest framing it like: " Before we dive into the Giveth platform, it's important that we make sure you are setup with the right web3 tools. If you're an expert this might seem obvious to you, but if you're a beginner, it's important that you make sure you have a wallet, connect to our dapp, load funds etc."

That way the onboarding series would be really onboarding to anyone new to Giveth even complete newbies. I feel that in the current format if they are new to web3 we would lose them right away on the second email, which is not good.

**Comment by danelsuga** [comment]
I had a look for some edits!

**Comment by ahmadabugosh** [comment]
Thanks @tropicalmangos, for this we need to figure out what are the triggers for them to be on this list to get this sequence. For example, are the triggers going to be multiple ones like: 

- Enter their email on the bottom of the homepage
- Enter their email and setup their account
- Should we add more places for them to enter the campaign (like a popup for example)?

Maybe we should discuss this on the comms call? 

Once you figure out what the triggers are, then we need to figure out how those triggers are configured in Autopilot to set it up.

**Comment by danelsuga** [comment]
Did the onboarding campaign emails all go out? Is this issue closed @laurenluz @c0ric0ri ?

**Comment by danelsuga** [comment]
Did the onboarding campaign emails all go out? Is this issue closed @laurenluz @c0ric0ri @ahmadabugosh  ?

**Comment by ahmadabugosh** [comment]
@danelsuga Not yet, unfortunately. The main bottleneck is figuring out how people get started with the sequence (what the trigger is). 

@WhyldWanderer and I spoke briefly about this when we met last week, but we have a lot of other high priority thing like GIVPower notifications we're solving for first. This is another one that may need us to put it on hold for a few weeks and revisit.

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh we should have the triggers figured out for this now, right? Users should be entering the sequence from our Onboarding Landing Page.

**Comment by oyealmond** [comment]
This is so great @ahmadabugosh @anamarija09 @SteffanThorn ! Thanks! 💫 

I left some comments. You can accept the ones you think are useful.

**Comment by ahmadabugosh** [comment]
This is launched. I'm closing this issue, but please let me know If anyone has any ways to improve the email sequences.
