### ISSUE TITLE
Fundraising Campaign

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-planning#948]
Create an email campaign funnel to fundraise from our existing newsletter subscribers (get donations)

**Comment by clara-zi** [comment]
There's no description yet, so not really sure what the issue is about but wondered if this doc is useful?
[is this relevant?](https://docs.google.com/document/d/1nqrhxv_-WpRM2lQBaAOiTBIUFWEszPJmVdOLZ08PBb8/edit?usp=sharing)
