### ISSUE TITLE
Good quality photos and Graphics - collection for social media

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#949]
We need a shared space to compile good quality images for Giveth social media

**Comment by c0ric0ri** [comment]
@danelsuga

**Comment by c0ric0ri** [comment]
@clara-zi can you drop the google drive link here?

Let's also add videos in here!

**Comment by danelsuga** [comment]
Photos! https://drive.google.com/drive/u/0/folders/16uWHF97kfTGr2Jp_EmNXLDqN3GxiyVhz

**Comment by laurenluz** [comment]
@oyealmond @Cotabe @WhyldWanderer - do you have any photos from devcon that we could add to here?

trying to get a bunch of content in here for socials

**Comment by WhyldWanderer** [comment]
I only took a few actually... but I uploaded the ones that I do have

**Comment by oyealmond** [comment]
Also have a few too . I already added them :/

**Comment by c0ric0ri** [comment]
hey @clara-zi where are we with this issue? Can we progress with it?

**Comment by clara-zi** [comment]
Used some photos. Good for archive.

**Comment by oyealmond** [comment]
@clara-zi I only found ETHbarcelona folder, do you have Devcon link? Or is there a respository of all photos?

**Comment by oyealmond** [comment]
ETHBarcelona 2023 Drive: 

https://drive.google.com/drive/folders/1fsgLw1eRBn3fEncD0exunxvnsx5yQ713

**Comment by oyealmond** [comment]
@danelsuga @laurenluz @hanners-717  do you have photos / videos from ETHCC? Could you please drop them [here?](https://drive.google.com/drive/folders/1l98K3QDqG2JlWutxBmRbuP5E3bfkvUBN?usp=sharing)

**Comment by laurenluz** [comment]
@oyealmond I added a bunch and also added you to our chat and asked people to share theirs as well
