### ISSUE TITLE
Tweet Thread on Devcon - Biggest Web3 Opportunity Talk

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#952]
Starting here: https://docs.google.com/document/d/100rokGI4aHBQ71JcDXyKECwCB5wea8vu8rV8JknTJy8/edit

Slides; https://docs.google.com/presentation/d/1jaD4R11dJxraWXYUBHZh_qdTjSyQDh7w3I3dDP2OaY4/edit#slide=id.g1643f9f897f_0_0

Talk: https://www.youtube.com/watch?v=SAVvu-5Kg7o&t=19105s

**Comment by oyealmond** [comment]
Hi team! ✨ @laurenluz also the comms team is planning Sound bites for your talk and Griff's talk here -
https://github.com/Giveth/giveth-planning/issues/954 

@c0ric0ri @ahmadabugosh

**Comment by ahmadabugosh** [comment]
@laurenluz @oyealmond @c0ric0ri soundbites are also done on this sheet: https://docs.google.com/spreadsheets/d/1KoVy2Ttvo3Q3GxnFx-6pNS01VfvgjDok95aNY9JKTik/edit#gid=374624886

**Comment by c0ric0ri** [comment]
@laurenluz has it targeted to work on this thread this week

**Comment by laurenluz** [comment]
draft is in here: https://docs.google.com/document/d/100rokGI4aHBQ71JcDXyKECwCB5wea8vu8rV8JknTJy8/edit

Will probably post tomorrow, if anyone feels so inclined to review before then, please do.

**Comment by oyealmond** [comment]
added a couple of comments..This thread should have it's own Giveth Essential session. jojojo @laurenluz

**Comment by laurenluz** [comment]
lolololol @oyealmond 🤣 - thanks for the comments! I incorporated. Posted today: https://twitter.com/Givethio/status/1585642002930028544
