### ISSUE TITLE
Soundbite clips from Devcon

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#954]

**Comment by ahmadabugosh** [comment]
Hey @c0ric0ri @danelsuga, 

Can you help out by providing me with a couple of soundbites timestamps from these 2 Devcon talks so I can clip videos for social media? 

1) Griff's biggest web3 opportunity https://www.youtube.com/watch?v=SAVvu-5Kg7o&t=19105s
2) Lauren's reimagining the money game: https://www.youtube.com/watch?v=bUA3FX6XSeU&ab_channel=Filecoin

**Comment by c0ric0ri** [comment]
Hey @SymSL would be awesome if you can jump on this one!

At least 45 seconds and up to 2 minutes are good for clips, maybe you can grab a few per talk?

**Comment by SymSL** [comment]
Thanks! Have got these so far from Lauren's talk:

0.16- 1.01
6.44-7.10
7.21-9.07
9.17-10.52

Will get some from Griff later this evening

**Comment by oyealmond** [comment]
Hey @ahmadabugosh @c0ric0ri @SymSL ! 
Also Im working for sound bites for this Mateo , public goods panel - 
Find it on hr 5:54 

https://www.youtube.com/watch?v=gvYaRfQgBKg 

Issue here - https://github.com/Giveth/giveth-planning/issues/963

**Comment by SymSL** [comment]
Griff so far, will add more later
5.19.27 - 5.20.29
5.20.35 - 5.22.09
5.22.35 - 5.24.17
5.24.20 - 5.26.09

**Comment by c0ric0ri** [comment]
Hey @ahmadabugosh , I'm thinking if you have the first few already done it would be great to get the link here as you keep working through the rest! 

We can simultaneously start reviewing them and schedule the first few for posts this week :)

**Comment by laurenluz** [comment]
Hey @ahmadabugosh - maybe this isn't worth your time to adjust, but nonprofits is actually one word, no hyphen. A lot of people make that mistake.

**Comment by laurenluz** [comment]
argh, in the last clip for reimagining the money game "GIV tokens"  not "give tokens"
![image](https://user-images.githubusercontent.com/75490971/196804022-9f8ef4e0-5107-4181-9599-48a9f27c514a.png)

**Comment by laurenluz** [comment]
Hey @SymSL @oyealmond - in the future, we should keep these clips to like 30 s MAX. When they get to be a 1min plus, they become a lot harder to understand... everything taken out of context... not really this "bite sized talk snippet" you know?

Imagine you are just scrolling through twitter... what words/sentences will catch your eye?


I like clip #2 for the reimagining the money game talk, as a good example.

cc @c0ric0ri @ahmadabugosh

**Comment by oyealmond** [comment]
mm, yur right. Ty for the feedback! @laurenluz

**Comment by laurenluz** [comment]
@ahmadabugosh shortened all the clips for reimagining the money game and they are all GREAT.

**Comment by danelsuga** [comment]
Oxford hyphenates non-profit (which is considered an older term; most folks nowadays use not-for-profit) but no one else.

**Comment by SymSL** [comment]
Okay I'll do some max 30 seconds during today. I thought they'd be used as teaser sound bites posted with a link to the full talk, but makes total sense to have them shorter if they will be tweet threads

**Comment by laurenluz** [comment]
They are being used as teasers with links to the full talk... via twitter / social media.

Also... the clips chosen for Griff's talk... they don't really really get to the punch parts of the talk. They're ok, totally usable... but it would been nice to see something about the difference between donation games & economic games... a big central point of his talk is that solving the public goods problem w/ web3 looks like 1. start by optimizing donations with cool donation games where people get points... but donation games are not ideal because they still require sacrifice. What we really want are *economic games* where you fund public goods via issues... where people are rewarded for adding value to public goods and no one really needs to donate/sacrifice.

Donation games are great, but they are not the end goal.

Anyway... the clips all kind of miss that point.

**Comment by SymSL** [comment]
Hey there, not sure if the clips you're mentioning were mine, there's alot
on this thread, but I've only gotten through the first section of both
yours and Griffs talks (was told these are time sensitive so have gotten
them out asap), so there were still more sections coming. The intention
being to have as many as possible to use for a long time as teasers for the
talk. If it's really only a few of the most important points, max 30
seconds, then I'll pick a few out of the whole talk and only give 4 or 5
from there.

**Comment by laurenluz** [comment]
we can use them later, but talks don't have the longest ever shelf life. the reason for getting them out soon is to share about the talk while the ideas are still fresh, the conference is still recent & peope still care. 

The ideal outcome is to get a key central message of the talk... short, punchy points. 20-30s. Process should be:
- someone listens to the talks & makes 4-5 suggestions
- someone else (either someone familiar with the message or someone responsible for putting these out on a platform) reviews/ chooses 2-3 that suit their needs
- ahmad (or someone he empowers) makes clips into short videos
- the person who will post them reviews them, drafts surrounding content & sends it out

We should strive for quality, not quantity, in the interest of time & effectiveness.

Side note, the clips about GIVbacks & GIVpower are kind of cool too for other use cases like social media posts about those products (so not used to necessarily shill the talk), so they are kind of nice for more evergreen things.

@SymSL they were all good clips, just I'm saying that the 4 chosen for Griff's devcon talk miss the central point of his talk... so are less good for shilling his talk. I was trying to explain what the key point of his talk was.

**Comment by SymSL** [comment]
Hey there,
I've done more +-30 second timestamping and split them into concepts. Some
can be used to promote the talk and some can be used as the evergreen
content. Ones marked with a * could be used for promoting the talk but any
would do for various audiences/channels

Economic games: 5.26.10 - 5.26.34
How Grant DAOs work: 5.27.50 - 5.28.18
Protocol funding: 5.30.21 - 5.30.41
GIVbacks: 5.31.15 - 5.31.47
Givpower: 5.32.30 - 3.32.57
Givpower continued: 32.50 - 5.33.28
Givpower continued: 5.33.30 - 5.34.00
*Economic games win win (issuance): 5.34.19 - 5.34.52
Issuance:
*Bonding curves: 5.38.06 - 5 38.35
Token bonding curve economy: 5.38.55 - 5.39.27
*Gurves: 5.39.30 - 5.40.06
Cool end note: 5.40.35 - 5.40.52
