### ISSUE TITLE
RegenFarms Twitter Space

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#957]
We have some new developments for our RegenFarms and it would be great to host a Twitter Space around this topic to bring more attention to the concept.

- We have new RegenFarm in the works coming up with The Standard (https://www.thestandard.io/)

- We just had a new RegenFarm go live yesterday with ShapeShift

The Standard has just reached out to us requesting some comms collaborations around the partnership, so this is a great way for us to approach it - we can highlight our partnerships while informing our community about the purpose and benefits of RegenFarms!

Partners to invite: The Standard, ShapeShift, & Cult DAO

Date: November 2 at 17:00 CET

@oyealmond is this doable? @laurenluz if I'm missing any partners here please let us know.

**Comment by oyealmond** [comment]
hey @c0ric0ri ! Thank you for this initiative! Is great. The only thing is, can we schedule for Nov 2th 9am CT | 4pm CET . You have the contact for The Standard and I have the contact for ShapeShift. Only Cult DAO contact will be missing. Do you have a contact to share with me? 

Also , @c0ric0ri would you be down to host? Or would you like to. nominate someone else? 
This Twitter Space will happen over GTalks 
Ty!

**Comment by laurenluz** [comment]
I made a thread w/ you @oyealmond and my contacts from Cult.
Also looping in @Cotabe here who might be interested in knowing about this!

**Comment by laurenluz** [comment]
Once we get the parties' consent, we should great a group DM on discord w/ all attendees so that they can be looped in on the prep!

**Comment by oyealmond** [comment]
You're the best @laurenluz ! Thank you! 
I have a call with @c0ric0ri today, shared me will be great to have someone more knowledgable around the Farms hosting (and she will be happy to co-host). Asked @Cotabe already and he's down to host Nov 2. 

Thank you for the group! yeeeeey

**Comment by c0ric0ri** [comment]
Recording here:

https://twitter.com/i/spaces/1YqJDoYgyOeGV?s=20
