### ISSUE TITLE
Tweet about The Standard RegenFarm & Partnership

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#958]
To be posted October 19th or 20th

**Comment by c0ric0ri** [comment]
https://docs.google.com/document/d/1lzhh7c0sAFC8SRhY_UK7VbVOdaarlRCHDd-VlKapeVQ/edit

@laurenluz for October 20th ideally. I thought pointing to the forum post is best for this one.

**Comment by laurenluz** [comment]
scheduled for tomorrow!

**Comment by c0ric0ri** [comment]
https://twitter.com/Givethio/status/1583096462812102661?s=20&t=RRO2VNouTe2Z7Xr0GRp5pg
