### ISSUE TITLE
Comms WG tasks / scope of work summary

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#961]
Review Comms summary of tasks in Comms section of this doc:

https://docs.google.com/document/d/1KkvL4rIpLZEzKyZkV3_lWpHuhRUGSYQe0d64IHiNz8w/edit#heading=h.wxk4vozcy2k4

1) Add tasks that are missing
2) Comment if tasks are no longer relevant / out of scope
3) Add any other comments
4) WG group description?

**Comment by laurenluz** [comment]
@c0ric0ri is on this!

**Comment by clara-zi** [comment]
This issue is no longer relevant as WG structures are changing and this description was to help contributors allocate their hours to the correct WG for budgeting purposes. Closing issue.
