### ISSUE TITLE
tweet about eth latam panel w/ mateo

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#963]
mateo was on a public goods panel in spanish.

would be so fun to find a great soundbite from this and write a short tweet to shill it. 

soundbite can be in spanish w/ the bulk of the message in the tweet in english.

@oyealmond can you find this talk and take this?

**Comment by oyealmond** [comment]
Love it! 

Here are Mateo's soundbites (He did great btw!!) -
From hr 5:54:00
https://www.youtube.com/watch?v=gvYaRfQgBKg

@ahmadabugosh could you help me edit it please?  

**Times for soundbites**
5:55:52 - 5:57:03 - "Mi nombre es Mateo" - "Por esto" 
6:03:22 - 6:04:42 - "Coordinación en mi opinión" - "Poquito más sostenibles" 
6:08:34 - 6:09:29  "Las ideas" - "esta un poco subestimado" 

@laurenluz 
here's the Tweet draft for your review - 
https://docs.google.com/document/d/1uqZM_pseaQdVgF-sUjgFBZFQTNdVD4CD5YtjEv6ffWQ/edit?usp=sharing

**Comment by laurenluz** [comment]
@oyealmond this is great - can you please write out the entire clip (in spanish) for the soundbites? @ahmadabugosh will need this to prep the video.

**Comment by ahmadabugosh** [comment]
@oyealmond yes, I need it the whole quote written in Spanish, because I'll definitely make a mistake if I just take it as is 😅

**Comment by oyealmond** [comment]
Hey @ahmadabugosh ! no worries! these are really short quotes, so I dont have any problem writting the whole statement. No worries! doing it right away

**Comment by oyealmond** [comment]
hey @ahmadabugosh ! 
[Here's the whole transcription for the soundbites. ](https://docs.google.com/document/d/1uqZM_pseaQdVgF-sUjgFBZFQTNdVD4CD5YtjEv6ffWQ/edit?usp=sharing)

Let me know if this works or if I need to add something else.

**Comment by ahmadabugosh** [comment]
Hey @oyealmond I made the first one here: https://share.descript.com/view/uamGyovXJUB 

Let me know if it's ok and check for typos because I don't know Spanish. Also, let me know if one is ok or if you need the other 2, because it's a bit time consuming for me in Spanish (maybe I can show you how to use the software later?) 🙏

**Comment by oyealmond** [comment]
Hey @ahmadabugosh ! Is perfect! Only one thing, can you remove this "a" please? - 

<img width="401" alt="Captura de Pantalla 2022-10-20 a la(s) 9 16 56" src="https://user-images.githubusercontent.com/110692280/196974179-1f296ce8-1da0-4251-bf02-d7dcec8b2c7b.png">

Can you please help me with one more soundbite? 
Is shorter than the one you did. [Is here in the doc](https://docs.google.com/document/d/1uqZM_pseaQdVgF-sUjgFBZFQTNdVD4CD5YtjEv6ffWQ/edit?usp=sharing)

And for sure! I can learn how to use the tool and help you! When do you have time?

**Comment by ahmadabugosh** [comment]
No worries @oyealmond ! Here is the updated link fixing the typo: https://share.descript.com/view/E17ea9AeLxH

I'll work on the other one and try to send it by tomorrow :)

**Comment by oyealmond** [comment]
Yeeey! ty so much! and please, I will be super happy to learn how to use the tool so we can create more of this. I think they're great

**Comment by ahmadabugosh** [comment]
Hey @oyealmond let me know if this works for the second soundbite: https://share.descript.com/view/8ZyuzpC1NJm

For sure, maybe it would be easier if I record a short video to show the process

**Comment by oyealmond** [comment]
yes! A loom will work perfect! uhoo! 

only 2 things and we are good to go: 

Here the word is **empoderar**

<img width="396" alt="Captura de Pantalla 2022-10-20 a la(s) 17 41 41" src="https://user-images.githubusercontent.com/110692280/197073024-0db1e51b-bc9b-4a4c-bbe9-25c0be1adee8.png">

And here should say **DAOs**

<img width="400" alt="Captura de Pantalla 2022-10-20 a la(s) 17 42 12" src="https://user-images.githubusercontent.com/110692280/197073033-49d11a8f-bdc8-4846-b710-c82dabe0a9be.png">

Thank you so much!

**Comment by ahmadabugosh** [comment]
@oyealmond let me know if this is ok: https://share.descript.com/view/bP3VqxuxoMG

**Comment by oyealmond** [comment]
Perfect! ty @ahmadabugosh ! 
@laurenluz , [tweet thread draft is here for your review :) ](https://docs.google.com/document/d/1uqZM_pseaQdVgF-sUjgFBZFQTNdVD4CD5YtjEv6ffWQ/edit?usp=sharing)

**Comment by laurenluz** [comment]
@oyealmond reviewed - check it out

**Comment by oyealmond** [comment]
Yey! Updated! @laurenluz

**Comment by laurenluz** [comment]
Awesome @oyealmond - I really like the first one. I scheduled it for Tuesday. I put the other one as a draft in tweet hunter that maybe we use on another day if the timing is right.
