### ISSUE TITLE
Post Updates to the Giveth Matching pool projecct

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#968]
This is a recurring content issue... we should make an update to the Giveth matching pool project at least once every 3 months.

This next one should be live by Oct 29.

https://giveth.io/project/Giveth-Matching-Pool-0

The update should include a short summary of important things that happened since we last posted an updated. Information could be collected from [this forum post](https://forum.giveth.io/t/givmatching-idea-generation-on-how-to-distribute-funds/346/21), or from discussion about GIVmatching with Griff, me, mitch

@danelsuga @tropicalmangos are either of you able to take on this issue & post a draft here in the next couple of days?

**Comment by laurenluz** [comment]
@danelsuga  - Mango is going to take on the other issue - could you do this one?

**Comment by danelsuga** [comment]
I can try to do this as requested. However I do not have the bandwidth to have a draft in the next days.

**Comment by laurenluz** [comment]
Awesome! when do you think you could do it? it's a short issue, not more than a paragraph or two. should be post live by the latest Oct 29.

**Comment by danelsuga** [comment]
Oh, I see. No problem. Will do asap!

**Comment by danelsuga** [comment]
Any updates on this front?

"We are also in conversation with Gitcoin about their upcoming dGrants product and hope to work with them in the future to use dGrants on Giveth for donation matching."

**Comment by laurenluz** [comment]
oh yeah, Griff & I are having a call with them next week. Going to try to share some of our dev resources to work together

**Comment by danelsuga** [comment]
Ok, great. So that itself will be the update on that front! Thanks.

**Comment by danelsuga** [comment]
OK, @laurenluz, here's a draft!

https://docs.google.com/document/d/1iN8WvkNpRpWhUsVluWylQIpzzyeVvkz0sZNg5g6adtg/edit?usp=sharing

**Comment by laurenluz** [comment]
Hey @danelsuga ! Made some edits & posted - thanks!

Apparently ( I didn't realize before) there was a limit to 2000 characters so I had to cut it down on the fly.

Here it is: https://giveth.io/project/Giveth-Matching-Pool-0

**Comment by danelsuga** [comment]
Oops, OK. Thanks!
