### ISSUE TITLE
Giveth @ ETH Medellin

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-planning#969]
On Wednesday 19th of October I'll be guiding a workshop focused on raising funding for web3 startups for ETH Medellin at Ruta N

Here's the [info](https://www.ethmedellin.co/event-details/web-3-0-masterclass-learn-the-fundamentals-with-tropykus-finance-giveth-evento-en-espanol)! 

It's a in presence event, I think I'll have @WhyldWanderer supporting there as she's in the city :)

Let's strategize for twitter :)

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1582775112583221249
