### ISSUE TITLE
Metagame Metaradio Followup Podcast Interview

### ISSUE THREAD

**Issue by tommygiveth** [Giveth/giveth-planning#97]
Griff has been featured once before, but maybe we can schedule a followup for release of Giveth Now and Giveth Then ;)

**Comment by tommygiveth** [comment]
Possible whenever an interviewee has time. Is not possible before launch on Mar 1. Metagame has its own things to shill for beginning of March.

**Comment by WhyldWanderer** [comment]
@tommygiveth, is this a subject that we can revisit now that MetaFest is complete?
