### ISSUE TITLE
GIVpower Boosting Documentation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#974]
We need to explain:
- how multipler affects GIVpower
- how to use GIVpower
- first project gets 100% of GIVpower
- you allocate percentages to projects, and then the % on other projects decreases proportionally
- ranking changes when the next round starts
- delegation will come soon (but you can apply to be a delegate now), what this means
- GIVpower tracking uses snapshots & averages them out
- GIVbacks will be affected by GIVpower ranking
- matching funds will be affected by GIVpower
- ranking will eventually take into consideration other things
- when you tokens get unlocked (or you lock more tokens) GIVpower goes down or up... and all projects after affected proportionally
- you can only boost verified projects, if you a project becomes unverified, your GIVpower will be divvied up among your other boosted projects.. if you had no other boosted projects, GIVpower becomes inactive (i.e. you need to boost again)

This is the [GIVpower spec](https://docs.google.com/document/d/1NpyiETNClSw2BGLqE4ucr2eem5VtmZcIpHzFneC0ciE/edit#heading=h.ayfvgyuy22lo) which includes a lot of this info.

@divine-comedian @franculio @WhyldWanderer - am I missing anything in the above this?

**Comment by laurenluz** [comment]
existing documentation: https://docs.giveth.io/giveconomy/givpower

starting draft:  https://docs.google.com/document/d/1pIwsCE9k2rlnEVtbESLI2TxBJHwDio-JHFvhi4gsag0/edit

**Comment by laurenluz** [comment]
can only boost a max of 20 projects

**Comment by laurenluz** [comment]
adjusting your boostings, you can click the lock to lock in changes. the other %s change according to?? what logic?

**Comment by divine-comedian** [comment]
first updated draft in!
https://docs.google.com/document/d/1pIwsCE9k2rlnEVtbESLI2TxBJHwDio-JHFvhi4gsag0/edit

please review - lots of content that you may not be able to see - working on a preview

**Comment by laurenluz** [comment]
@divine-comedian - sorry it took me so long to review this. I just finished. It's great! Check out my comments.

Also, we should really be consistent with calling the GIVbacks max factor exactly that. There was a lot of like... GIVbacks matching percentage - which is a confusing name. I hope you can work in a clear definition for the GIVbacks max factor at some appropriate part, and then link back to it when it's mentioned in another doc.

Also! Things I think are missing (but also, I may have just forgotten)... just make sure they're there:
- snapshots are taken every 4 hours, and the rank is the average of all data in the snapshots
- ranking will eventually consider more than just GIVpower (and soon will include budget box)
- you can only boost verified projects

**Comment by laurenluz** [comment]
Thank you so much, this was a huge thing.

**Comment by laurenluz** [comment]
https://docs.giveth.io/giveconomy/givpower/
