### ISSUE TITLE
Get the Coinmarketcap circulating supply connected to the same api coingecko is using

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-planning#975]
Doneshould look like the Coinmarket cap website showin gthe same market cap as Coingecko

<img width="201" alt="Screen Shot 2022-10-22 at 2 41 28 PM" src="https://user-images.githubusercontent.com/14945613/197361596-115e578a-ec81-4569-abbe-90d7e495a308.png">
https://coinmarketcap.com/currencies/giveth/

**Comment by oyealmond** [comment]
hey @laurenluz ! 

Could you provide more context on this issue? Thanks!
