### ISSUE TITLE
Project survey creation

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-planning#978]
Reach out to projects to:
- understand their experiences and satisfaction level using the Giveth platform
- understanding of Giveth token / GIVeconomy
- whether they have been able to use the funds raised for their project

**Comment by clara-zi** [comment]
https://docs.google.com/spreadsheets/d/1HfKMZd963TImW4ViudMLBNKTslHuyaQxUlJSEgKUNd0/edit?usp=sharing - draft for scope

**Comment by clara-zi** [comment]
If anyone has a minute: please review project survey and give feedback on questions, wording, structure etc.
Each tab represents a different section in the survey.  Questionnaire is relevant for projects listed on Giveth and projects that aren't.
There will be a 'navigation' through the final survey to ensure that participants do not have to answer questions that are not relevant.

@SnakeGH @c0ric0ri @laurenluz @rainerhoell @danelsuga @WhyldWanderer @tropicalmangos

**Comment by clara-zi** [comment]
@ahmadabugosh you made a good suggestion last week around asking some questions relevant to the new project profile templates - could you add some comments on this in the template please?

**Comment by SnakeGH** [comment]
Not sure how much more work it would be, but it might be easier to leave comments on a google shared doc vs spreadsheet but if that's going to cause a lot of difficulty, then ill take a crack on the spreadsheet

**Comment by SnakeGH** [comment]
Not sure how much more work it would be, but it might be easier to leave comments on a google shared doc vs spreadsheet but if that's going to cause a lot of difficulty, then ill take a crack on the spreadsheet

**Comment by danelsuga** [comment]
Just started having a peek, and I see some pretty basic typographical errors, which are probably just mistakes (missing period, question mark in wrong place, etc.). Do you want me to leave comments for all of these tiny things? Would be easier just to correct them.

**Comment by laurenluz** [comment]
You can also also danelsuga@gmail.com as an editor :)

**Comment by clara-zi** [comment]
@danelsuga - done. 
Thank-you. With this kind of detailed review - we will be able to copy/paste into the Typeform for the final survey.

**Comment by ahmadabugosh** [comment]
@clara-zi So I was thinking that we could mention on the survey,  something like "fill out these details to be first in line when we lauch our next project page format to get more exposure to your project" etc. 

Some suggestions I would add to the survey would be:

1) Social links / Website link

2) Impact metrics (what is the thing that you are trying to accomplish). For example, dig more wells, feed more families, build more schools etc. Ideally we could ask also, what is the $ amount for reach activity i.e how much does it cost to dig one well, feed one family, build one school etc. 

I think this point is tricky to figure out, but it would be amazing to capture.

3) What is your fundraising goal (ongoing no goal, or let them define a number). This is also tied to point 2.

**Comment by WhyldWanderer** [comment]
There is now a Google Document where this survey can be commented on and reviewed to be put into typeform..

Maybe @danelsuga and @ahmadabugosh  or anyone else who wants to could take a look and leave any comments there in the doc. I hope to get this into typeform before our next community builder sync.

**Comment by ahmadabugosh** [comment]
Hey @WhyldWanderer, can you add some of the questions I mentioned above to get their social links, as well as their fundraising or impact goals? That would make it easier to add that info if we add it to the project pages.

**Comment by clara-zi** [comment]
> 2\. dig more wells, feed more families, build more schools

@ahmadabugosh - added

**Comment by c0ric0ri** [comment]
Added a bunch of comments!

It would be great to ultimately flush out projects' expectations vs reality using Giveth. How is fundraising actually going? How can we improve to help them with this? That's the ultimate reason they are on Giveth and willing to promote Giveth to others. 

Everything else is nice to know but if we are trying to keep the survey concise, that's the core.

**Comment by clara-zi** [comment]
Aiming for project survey to go out in New Year:

- Not to conflict with holiday time to get best response
- Holiday season email campaign planned to bring in more donations (existing projects and donors): we don't want to swamp inboxes or compete for attention
- Project survey email msg can be along the lines of: 'New Year and Giveth wants to take a fresh look at how we are supporting projects and making the platform even better by listening to projects' feedback.....'

Gives time to plan comms etc.

**Comment by clara-zi** [comment]
https://giveth.typeform.com/projectsurvvey

**Comment by clara-zi** [comment]
Forum post: https://forum.giveth.io/t/rewards-for-project-survey-respondents/965

**Comment by clara-zi** [comment]
@WhyldWanderer we have some test/sample responses - can we delete/reset before the survey goes out - so that they don't skew the results?

**Comment by clara-zi** [comment]
@WhyldWanderer Two final tweaks to project survey questions:
please change: "What has so far stopped you from listing on Giveth?" to "Has your organisation received cryptocurrency donations in the past?"

Please change last question from "Is there any other contact method you would like to provide?" to: "Please provide your userid for any other way you'd like to connect with Giveth? eg Facebook or LinkedIn."

**Comment by c0ric0ri** [comment]
Hey @clara-zi can we close this issue now that the survey is out?
