### ISSUE TITLE
Deprecate Giveth TRACE documentation

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#979]
Update information about the shutdown of Giveth TRACE in https://docs.giveth.io/dapps/introTrace

It would be nice to create some content about the experience that was Trace and why we decided to move away from it and still leave the record of the useful information about how it worked in the docs.

Maybe someone is interested in writing this? @c0ric0ri

**Comment by franculio** [comment]
@danelsuga Maybe you're interested?

**Comment by danelsuga** [comment]
Thanks but zero bandwidth at the moment.

**Comment by c0ric0ri** [comment]
@divine-comedian or @Danibelle is this something you could help us to draft?

**Comment by divine-comedian** [comment]
I can draft a small paragraph and append it to all the relevant trace documentations - We'll need a translation in spanish, portuguese and turkish

**Comment by divine-comedian** [comment]
We can append this paragraph onto all relevant documentation:

> Giveth TRACE has officially been deprecated. After 5 years of faithful service, Giveth and it's platform, services and products have fully migrated to https://giveth.io. With the deprecation of the Rinkeby network and low user activity, the Giveth DAO decided to sunset its original dApp in Q3 of 2022. The code has and will forever be open-source and you can find it in [Giveth's Github repositories](https://github.com/Giveth). This documentation will remain available for historical reference. 

can you give this quick read @danelsuga ?

**Comment by danelsuga** [comment]
Thanks for this, @divine-comedian !

Just a couple tiny things:

...Giveth and its platform...
(its)

The code has and will forever be open-source, (COMMA) and you can find it in Giveth's Github repositories.

**Comment by divine-comedian** [comment]
> Giveth TRACE has officially been deprecated. After 5 years of faithful service, Giveth and its platform, services and products have fully migrated to https://giveth.io. With the deprecation of the Rinkeby network and low user activity, the Giveth DAO decided to sunset its original dApp in Q3 of 2022. The code has and will forever be open-source, and you can find it in [Giveth's Github repositories](https://github.com/Giveth). This documentation will remain available for historical reference.

**Comment by divine-comedian** [comment]
okay it's been implemented in English - looks pretty good imho 

![image](https://user-images.githubusercontent.com/67759413/199119829-43857509-fbff-4f47-97ed-62aa942d4276.png)

We need that text block translated and implemented as well to call this complete:
- [ ] spanish @franculio ?
- [ ] turksih
- [ ] portuguese

**Comment by franculio** [comment]
I'll start the Spanish translation today!

**Comment by franculio** [comment]
Translation into Spanish:

>Giveth TRACE ha quedado oficialmente en desuso. Después de 5 fieles años de servicio, la plataforma, servicios y productos de Giveth han sido completamente trasladados e incorporados a https://giveth.io/. Con el cierre de la red Rinkeby y el bajo número de usuarios que la utilizan, la Giveth DAO decidió dar fin a la dApp original en el Q3 de 2022. El código fue y siempre será open-source y se puede encontrar en los [repositorios públicos de Giveth en Github](https://github.com/Giveth). Esta documentación quedará disponible con el fin de tener una referencia histórica de la primera etapa de Giveth.

@oyealmond could you give it a read and tell me what you think of the translation?

**Comment by divine-comedian** [comment]
turkish 

> Giveth Trace resmi olarak operasyonlarına son verdi. 5 yıllık sonra düzenli servisimiz sonunda, bütün giveth ve platformu, servisi ve ürünleri tamamen [giveth.io](https://giveth.io) ya taşındı. Rinkeby networkün durması ve düşük kullanım sebebiyle Giveth DAO orjinal aplikasyonu 2022 i nin 3. çeyreği itibariyle durdurma kararı aldı. Trace kodu hala açık kaynak ve hep öyle kalıcak, [givethin github reposundan](https://github.com/Giveth) koda ulaşabilirsiniz. Bu döküman tarihsel referans olarak ulaşılabilir olucak.


portuguese 
> Giveth TRACE foi oficialmente descontinuado. Depois de 5 anos de serviços, Giveth e suas plataformas, serviços e produtos migraram totalmente para [Giveth.io](https://giveth.io/). Com a descontinuação da rede Rinkeby e a baixa frequência de usuários, o Giveth DAO decidiu encerrar seu dApp original no terceiro trimestre de 2022. O código é e sempre será aberto. Você pode encontrá-lo nestes [repositórios do Github](https://github.com/Giveth). Toda a documentação do Giveth TRACE vai permanecer disponível para referência histórica.

**Comment by divine-comedian** [comment]
ready to review in a few mins on https://docs.giveth.io 

you should be able to see all Giveth TRACE categories appended with (Deprecated) 

You should see the disclaimer text in all languages at the beginning of each trace documentation article
