### ISSUE TITLE
Project Verification Process

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-planning#980]
Correct grammar, update picture and info in https://docs.giveth.io/dapps/projectVerification

**Comment by franculio** [comment]
Following the request in the #935 from @NikolaCreatrix

**Comment by franculio** [comment]
Following the request on #935 @NikolaCreatrix

**Comment by franculio** [comment]
Here's what the update is looking. @danelsuga @NikolaCreatrix  Please take a look and correct anything that you see necessary. 

https://docs.google.com/document/d/1Wn0UEQxP3TcRNM72mWmPy6pJYiDQnwBvlW_KYglg9pU/edit?usp=sharing

**Comment by danelsuga** [comment]
Great! Thanks! Gave it an editing pass. Thanks @franculio

**Comment by franculio** [comment]
That was quick! Thank you so much @danelsuga !!!

**Comment by NikolaCreatrix** [comment]
Hey @franculio sorry for the delay, it looks good to me, all the important info is there.... just a reminder I saw in the Comms chat Lauren mentioned that documents created on behalf of giveth should be reviewed by 2 comms starts before posting, so...the second one, that's not me. :D We need one more pcomm start to review this I guess. :)

**Comment by NikolaCreatrix** [comment]
Hey @WhyldWanderer just checking in, did you have in mind any specific scenario for this part of the docs? I know you recorded the whole new flow [here.](https://docs.google.com/document/d/1IAa8Osu7lbrULRAKkBA9ZtfTV0jq4dvns-9lyEAQS48/edit?usp=sharing) so we don't miss anything here...
