### ISSUE TITLE
Create Lens Profile (Mirror Tweets on Lens) 

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-planning#981]
Lens is a new and fast growing Web 3 social media platform. 
https://lenster.xyz/

While we may not have the resources at present to dedicate a lot of time to this, I think we can still take advantage of this blossoming ecosystem by mirroring our tweets on Lens through an integration (will be automated). 

https://reflect.withlens.app/

If this platform really takes off, we'll have first movers advantage and grow more quickly than other saturated platforms. 

Happy to take this on and get it done. What do you think?

**Comment by laurenluz** [comment]
my concern is around the management of a private key that accesses that account. wondering if they have some features for orgs who have collaborative social media?

**Comment by laurenluz** [comment]
Hey also, we can only get a lens profile if we're eligible. I made a fresh address to try to claim Giveth.lens with it anyway.. but I can't. So @tropicalmangos if we want to make this happen, we need to keep an eye out on lens for the drops or find some connection.

**Comment by laurenluz** [comment]
are you sure you get on a waitlist? doesn't seem that way to me:

![image](https://user-images.githubusercontent.com/75490971/204296763-a2d74056-4d35-40c3-aad4-5a75684db388.png)

**Comment by brichis** [comment]
![photo1670283946.jpeg](https://images.zenhubusercontent.com/635c6dd0ed86045e2c4cd152/8032c31b-d1af-40fc-ba13-c5772696dfdb)

**Comment by brichis** [comment]
He answered me this, what address should I give to him?

**Comment by laurenluz** [comment]
can we change the address on the account later?

**Comment by laurenluz** [comment]
If we can, give him this one: 0x996546Cf9e404FC22250Fe8501e456E5929F7DFd

It's a new one I created & control, and we can use it at least for lens part 1

**Comment by brichis** [comment]
I think yes, someone make an offer today for brichis.lens hahaha let me confirm with him anyways

**Comment by brichis** [comment]
Good news: 

Thank you, added you to the allowlist to test Lens Protocol beta by claiming your handle at http://claim.lens.xyz and you can also post your genesis post (say gm, share music, art or photos) after the claim on http://Lenster.xyz

**Comment by brichis** [comment]
@tropicalmangos yep, with the address that @laurenluz gave to us: 0x996546Cf9e404FC22250Fe8501e456E5929F7DFd

**Comment by laurenluz** [comment]
yeah I asked @brichis to look into it more because giveth.lens is apparently reserved? would love if it could be reserved and we could claim it now

lmk what you find out @brichis

**Comment by brichis** [comment]
Hey @laurenluz could you try again, please?

**Comment by brichis** [comment]
Hey @tropicalmangos, @laurenluz already has the handle so you can continue with the mirror thing if you want :)

**Comment by laurenluz** [comment]
@tropicalmangos I just looked at this to set it up, and this reflect actually mirrors lens posts to twitter... and has limitations on characters (280) & media you share.

It doesn't mirror tweets to lens at all from what I can tell.

Or is there something I'm missing?
