### ISSUE TITLE
Workshops/resources for projects to get more donors

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#982]
easy info for how givbacks work, how givpower works
suggested campaigns

**Comment by c0ric0ri** [comment]
@oyealmond I'd love to throw this issue to you

**Comment by oyealmond** [comment]
sure! 
We have our verification workshop / 101 course launch today. 
https://discord.com/events/679428761438912522/1037460248363020408 

. 
Thank you for assigning me :) 
I would love to update and work around this issue. @c0ric0ri
