### ISSUE TITLE
Blog Post to Announce Project Owner 101 Video Course

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#983]
Would be great to have a draft of this by the end of this week, to be reviewed and finalized by early next week (Nov 1)

**Comment by danelsuga** [comment]
No idea what the issue was for the article on the donor course. I can't find it.

Here is the article itself:
https://medium.com/giveth/the-abcs-of-donating-on-giveth-6e3bd147397e

**Comment by danelsuga** [comment]
https://docs.google.com/document/d/1aeWLviC2xAwR4yj20DP60RttCDE-hIKZMDZ2vl2cNjY/edit?usp=sharing

**Comment by c0ric0ri** [comment]
Moved this to Review/QA

Thanks so much @danelsuga ! I left some initial comments and edits. Would be great to get more reviews to finalize.

**Comment by danelsuga** [comment]
Thanks! I hadn't written much in the comments here to say it was done, just pasted the link. Was hoping to get back to it to work on more, so super glad you've already buckled down to review. Thanks!

**Comment by c0ric0ri** [comment]
@danelsuga no problem! To clarify your last comment, are you still planning to add more to this? Or is it ready to tag another reviewer? if yes, please tag :)

**Comment by danelsuga** [comment]
I would like to get back to it myself. I didn't get to that today. Will do tomorrow.

**Comment by laurenluz** [comment]
https://medium.com/giveth/the-abcs-of-creating-a-project-on-giveth-55ff82c060f8
