### ISSUE TITLE
Promotion for RegenFarms Twitter Space (Nov 2nd)

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-planning#985]
Hey dear team! 

Here are the tweets to promote our amazing  next RegenFarms Twitter Space! 
@laurenluz already reviewed some  . 

https://docs.google.com/document/d/1e6xD0fQlzH3KC6mEj8VJMzYIVlyf2GzaJOXLgOrgPOo/edit?usp=sharing

@c0ric0ri in this doc you will also find the script for the session. 

Thank you!

**Comment by laurenluz** [comment]
scheduled them all! Thanks @oyealmond

**Comment by oyealmond** [comment]
@laurenluz , sorry for the following, I made a mistake with the new time of the AMA session (bc of the World changing clocks this week) and got the time (and image wrong) :( I already fixed and pointed for you in the doc w the replacements. Could you help me fixing the copies please? 

And also (sorry for the last minute change 🥺), the team needs a Verification workshop for projects, so we're planning to have it on the 9th instead of the regular AMA. I already posted the tweets to replace the tweet of the 8th. 

Sorry again for the inconvenience 🥺

**Comment by laurenluz** [comment]
@oyealmond - these were all ok I think- right? re: timezones? I think you deleted a commet here.

**Comment by oyealmond** [comment]
Yes! These are correct as they are only showing the link to the reminder, they don't have times included. 
Thank you!
