### ISSUE TITLE
Tweet Thread to Intro Project Owner 101 Course

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#986]
Plan to have a draft ready by Friday

**Comment by c0ric0ri** [comment]
Ran late on this. But now that we have the blog post draft reviewed, i will create the tweet tomorrow

**Comment by c0ric0ri** [comment]
Draft is here for review! https://docs.google.com/document/d/1rTn-lyHSgXmNAkQe9CPgJH2e-XW3j3Z-1aAnxbmSdkA/edit

**Comment by ahmadabugosh** [comment]
Thanks @c0ric0ri can you make it any one can comment?

**Comment by c0ric0ri** [comment]
@ahmadabugosh yes it's fixed!

**Comment by laurenluz** [comment]
@c0ric0ri I made some comments... one blocker for this is the video embed, which I've made too many instances of comments on already so I won't repeat myself here.

**Comment by laurenluz** [comment]
ok! blocker is resolved! we will post the image instead. so if you can just resolve the comments @c0ric0ri we're good

**Comment by laurenluz** [comment]
https://twitter.com/Givethio/status/1589981833445376000
