### ISSUE TITLE
PFP Launch Comms Planning

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#987]
Reviving this epic on Feb 1 with new updates, as the PFP Collection is now getting ready for launch!

https://docs.google.com/document/d/1L3UMKgq7nE0NNBSZg8aJp_m3iTyFpJ5bGHCbPW5ATGs/edit

We will need to prepare communications for social channels & our blog, including creating relevant media assets.

The idea is to start communications & generate hype around the collection at ETHdenver by offering 1-2 PFPs as prizes for our impact quests.

Following the conference, myNFT will be hosting an event where we could auction a few more of our PFPs.

After this point, we can plan a mint date for those on our allow list, followed by a public mint date.

Doc to reference that Almond & Mitch created: https://giveth.notion.site/Givers-PFP-Collection-3bc23c4a995247afbd23b9249987411a

_Previous notes from @tropicalmangos to consider:_
Some items to prepare:

- Video teasing the art collection - this takes time so we need to start early
- Blog Post - prepared by mid November
- Tweets to promote Allow List
- FOMO Countdown Tweets
- Twitter Thread Launch Announcement
- Partner Support Guide Outreach Document - do we want this?
- pfp drop promo video

**Comment by c0ric0ri** [comment]
Hey @tropicalmangos would be great if you can add your notes here about PFP launches!

**Comment by oyealmond** [comment]
yeeey :) @c0ric0ri I think @tropicalmangos has excellent ideas around comms we can do for this. 
I for sure will be working with her and supporting. 

@laurenluz would be good to ask the person that makes videos for Giveth if is available?

**Comment by laurenluz** [comment]
We can ask him for sure - I can make a group DM w/ him? he wasn't cheap... who would be interested in managing this?

**Comment by oyealmond** [comment]
@tropicalmangos please L :)

**Comment by c0ric0ri** [comment]
Hey @tropicalmangos regarding the videos, it's important that we assess cost for these (and time). 

1. Art teaser video - seems very lowkey and low effort, to go out first to tease the project

2. Promo video to build hype and encourage people to join the waitlist - this is IMO very important and if I had to choose 1 of the two, I would go with this one to prioritize

3. PFP drop video for day of launch, like you indicated

I think 2 and 3 can probably be the same video cut slightly different ways to reduce effort, so they basically have different call to actions (join whitelist & save mint date, or minting is live now etc) but graymachine has to do the work once.

It would make sense to get a quote for these 3 and then we can decide. Can you prioritize the quote for this week?

**Comment by oyealmond** [comment]
Agree w you @c0ric0ri this can be 1 video, and then the rest can be adaptations. We need first to align on the narrative and messaging we're going to tell about the drop integrating GIVpower + Christmas + 1 year after the GIV airdrop , I would love to have a brainstorm session  for everyone to drop ideas and have smth to build over. Is this smth we could organize for this week? wdyt? @c0ric0ri @tropicalmangos

**Comment by Santigs** [comment]
Here are the links to the PFP collection.

[Minting page design](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=14997%3A268092)
[Collection Document](https://docs.google.com/document/d/1L3UMKgq7nE0NNBSZg8aJp_m3iTyFpJ5bGHCbPW5ATGs/edit?usp=sharing)

**Comment by laurenluz** [comment]
@c0ric0ri @Santigs - can you guys please work together to create and coordinate on issues to build hype for this launch. we should start soon with tweet etc.

and if we plan to write a short blog or anything, we need somone on that asap.

**Comment by oyealmond** [comment]
Her dear team 💫 

@c0ric0ri @Santigs @divine-comedian & myself had a synch around the PFP launch strategy. I believe follow up sessions regarding this will work to make this release as successful as we can according to our capabilities.
Details I believe could be strengthen: 

## **Rational**
- We're launching a 1250 PFP collection to get  support from our community during this though Bear Market. All proceeds will be use to support Giveth's operations. 

## **Comms tagline**
_What will be the CTA that will make ppl want one?_
- Get a #Giver4Good & support our mission to fund public goods using Web3 innovations. 
- #Givers4Good community is the next level of Web3 heroes funding public goods w/ Web3 technology! 

## **Target (potential buyers)** 
- Giveth community & Giveth's friends & partners. 
_Suggestion_ - Make a list of communities & key people that may be interested on getting a Giver and be on the allowlist. 
I would strongly suggest to open spots at the allowlist to the people that had support Giveth in the past.

## **Sell strategy** 
- Hype create a brand & hashtag! I suggest #Givers4Good
- Allowlist for friends & family. Make a pre sale campaign building some actions around the allowlist. (Ex Mint party - Make a Discord or a Twitter Space Mint Party for the allowlist members. I prefer mint parties than auctions tbh.)
- Everyone on Giveth need to change their profile pic for a Giver4Good
- Giveth Social Media Posts (Mainly Tw)
- Partner outreach (reach out to the ppl above offering a Giver4Good ) 
- Shilling: get interviews, press notes, Newsletters features, get tweeted by other communities. 
- Twitter Space talking about the collection. 

## **Benefits** 
- PFP collections are meant to open the door to people to join a community and have decision power, specially decision power regarding funding. Ex Nouns DAO, Bright Moments.
- If this collection will have cosmetic benefits effects integrated into the dApp we could say the owners are the SUPER Giveth community. Idk, something that make PFP holders stand out from the regular community members.

We could use other sessions to polish some of these ideas and define launching stages dates & the messages tied to each one of these:
 
- ETHDenver
- allowlist
- pre minting
- open mint

wdyt? 
cc @laurenluz

**Comment by Santigs** [comment]
Thank you @oyealmond.
I got some feedback from myNFT last evening and this is their answer:

"We are currently working towards the week of 6th-12th March meaning **it might be ‘Giveth Day’ on the 8th or 9th March** but I realize this is not particularly useful as it's not a final date. I will give you this as soon as I have it. 

We have some final QA coming up and when that is done, we can confirm the exact date. I’m sorry that I can’t be more specific at this point but I’ll hopefully know more within the next 2 weeks."

We can define our calendar considering ETH Denver's "soft" introduction and myNFT auction event as the initial launch before the general public minting.

Do you guys want to meet next Monday/Tuesday? @c0ric0ri @laurenluz @divine-comedian

**Comment by divine-comedian** [comment]
Next monday is good for me I think

**Comment by Santigs** [comment]
Before or after Governance call?

**Comment by oyealmond** [comment]
me too! :) 
Monday Feb 6, 11 am CST / 6pm CET work for you all? @divine-comedian @c0ric0ri @laurenluz @Santigs

**Comment by Santigs** [comment]
Timeline
1.- giving away 50 pfps on impact quest participants at Eth Denver
2.- auction 5 units my myNFT 
3. Allowlist
4. Open minting.

**Comment by Santigs** [comment]
Here are some sketches from the art we can use for comms support if needed.
We can also generate some new ones from the final art using a sketch online tool.

![background_sketch1](https://user-images.githubusercontent.com/34634436/217300883-f8f14fb6-d0ca-45b3-9adc-93489653eb50.jpg)
![background_sketch2](https://user-images.githubusercontent.com/34634436/217300920-04925cb8-5e68-4595-a0f7-dcdcf51a84e6.jpg)
![background_sketch3](https://user-images.githubusercontent.com/34634436/217300934-93cea03a-dbcf-422e-83e5-ed532f19050e.jpg)
![background_sketch4](https://user-images.githubusercontent.com/34634436/217300943-88e8c9fe-3591-44bb-bd67-423335487f41.jpg)
![background_sketch5](https://user-images.githubusercontent.com/34634436/217300946-8af72eab-78d5-4e77-a349-dd5b8feb39d5.jpg)
![background_sketch6](https://user-images.githubusercontent.com/34634436/217300950-7efca61c-cf95-4477-877a-b74722da3c66.jpg)
![proposition_6_sketch1](https://user-images.githubusercontent.com/34634436/217300954-c3c261f4-a1d6-40aa-a635-d139c04edc43.jpg)
![proposition_7_sketch2](https://user-images.githubusercontent.com/34634436/217300955-178edfdd-363d-407a-b2aa-da0b207cb874.jpg)
![proposition_7_sketch3](https://user-images.githubusercontent.com/34634436/217300957-5ea22087-09a0-4ed4-b4b1-b30185b52613.jpg)
![proposition_7_sketch4](https://user-images.githubusercontent.com/34634436/217300963-8c671ee5-5a1c-4746-9611-ee5fa4b1cdc1.jpg)

**Comment by oyealmond** [comment]
Hey @Santigs ! 

I think we should as the designer to create a special design for comms purposes. Actually I think we may need several designs, but more smth like: 

![FmHcOsLWIAIfwgj](https://user-images.githubusercontent.com/110692280/217303995-0a899a8e-1ef3-4fbc-a70c-a548bc1e4f19.jpg)

With specific characteristics: 

- Twitter format size
- a special & attractive design announcing the launch
- the information of the launch

And we may need several designs: 

- a design for the blog post cc @divine-comedian 
- a design announcing the minting party (if we agree we will have one) 
- a design for the open minting. 

I don't think we could use these sketches, as at least for me they don't represent the collection. We should create specific formats & designs. 

Could you help us leading the creation of this w/ the PFP designer? @Santigs

**Comment by laurenluz** [comment]
@rodricastillo9013 - are you in the loop on this?

**Comment by Santigs** [comment]
The Punk Domain guys have requested to coordinate on the announcement of the Giveth domains minting launch.
I suggested them to make the official launch during the minting party on March 23 and that works for them but they would like to coordinate comms efforts.
Do you want me to add you to the discord group @oyealmond ?

**Comment by oyealmond** [comment]
Hey @Santigs ! No. I'll prefer not be added to the Discord Group. And if possible, you or @divine-comedian that have already a  relation with Punk Domains to coordinate this and me just executing copies or what's needed.
