### ISSUE TITLE
PFP Launch Blog Post

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#989]

**Comment by laurenluz** [comment]
Will adapt this to a short blog: https://www.notion.so/giveth/Givers-PFP-Collection-3bc23c4a995247afbd23b9249987411a

**Comment by laurenluz** [comment]
@danelsuga @divine-comedian @oyealmond 

ready for QA https://docs.google.com/document/d/1OUCJ6nqIwe12ANTaRp49aOsENHOC7Edqq96aAjSAJIg/edit#

**Comment by oyealmond** [comment]
Aww, I loved it! @laurenluz ✨🥲

**Comment by danelsuga** [comment]
Great job! I gave it a go @laurenluz !

**Comment by c0ric0ri** [comment]
@laurenluz when is this planned to be published?

**Comment by laurenluz** [comment]
https://medium.com/giveth/the-givers-nfts-for-the-giveth-community-fa335ef9db01
