### ISSUE TITLE
Tweets Promoting PFP Allow List

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#990]

**Comment by danelsuga** [comment]
Would be great to have the Twitter link in the issue.

**Comment by danelsuga** [comment]
Here're all the PPF tweets I rounded up.

(March 22)
https://twitter.com/Givethio/status/1638617061768175630
(March 17 features Twitter space clip)
https://twitter.com/Givethio/status/1636805183035277316
(March 16 features medium article)
https://twitter.com/Givethio/status/1636397418420764673
(March 15 announces Twitter space)
https://twitter.com/Givethio/status/1636005100467507202
(March 14 announces Twitter space)
https://twitter.com/Givethio/status/1635717941327953944
(March 10 thread)
https://twitter.com/Givethio/status/1634223109124288514
