### ISSUE TITLE
Twitter Thread PFP Launch  - March 20

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#991]

**Comment by laurenluz** [comment]
For this, I would love to see:

- [ ] Tweet for March 19 saying it's the last day to join the allowlist
- [ ] Tweet for March 23 telling allowlist members about the premint party (or maybe we skip this?)
- [ ] Nice, hype-y thread for March 24 on the offical launch date

For the 3rd one, I'd love to pull some nice pieces from [this blog](https://docs.google.com/document/d/1OUCJ6nqIwe12ANTaRp49aOsENHOC7Edqq96aAjSAJIg/edit#)  regarding art, fun facts, etc.

**Comment by laurenluz** [comment]
ok I talked to @oyealmond - let's make this issue simple:

- Nice, hype-y thread to publish March 24 on the offical launch date
- Pull pieces from [this blog](https://docs.google.com/document/d/1OUCJ6nqIwe12ANTaRp49aOsENHOC7Edqq96aAjSAJIg/edit#) regarding art, fun facts, etc.
- 1st draft by March 20 latest

Assigning to @c0ric0ri

**Comment by c0ric0ri** [comment]
Draft here for review:

https://docs.google.com/document/d/1jq1wR767HfYcFy7-0tPvO2excyszWaPkqueTbsuw_9c/edit

@laurenluz @oyealmond @danelsuga

**Comment by laurenluz** [comment]
looks great @c0ric0ri - I made some small comments, can you fix them?

**Comment by c0ric0ri** [comment]
Made the edits @laurenluz we should be good to go!

**Comment by laurenluz** [comment]
Thanks Cori! Scheduled

**Comment by danelsuga** [comment]
Would be awesome if Twitter links could be added here!

**Comment by danelsuga** [comment]
The Givers 
(March 22, need an older one)
https://twitter.com/Givethio/status/1638617061768175630
(March 17 features Twitter space clip)
https://twitter.com/Givethio/status/1636805183035277316
(March 16 features medium article)
https://twitter.com/Givethio/status/1636397418420764673
(March 15 announces Twitter space)
https://twitter.com/Givethio/status/1636005100467507202
(March 14 announces Twitter space)
https://twitter.com/Givethio/status/1635717941327953944
(March 10 thread)
https://twitter.com/Givethio/status/1634223109124288514
