### ISSUE TITLE
January update to the Giveth project - Jan 19

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#992]
This is a recurring content issue... we should make an update to the Giveth project at least once every 3 months.

This next one should be live by Jan 20ish and should include updates from Nov - Jan

https://giveth.io/project/the-giveth-community-of-makers

The update should include a short summary of important things that happened since we last posted an updated. Information could be collected from the past newsletters (because they included a lot of highlights). Also, the update needs to be less than 2000 characters

**Comment by NikolaCreatrix** [comment]
Maybe we can start posting some bullet points here for the updates summary:

- We implemented Mandatory updates + improved our Verification process (new Dapp)
- re-launched Meet The Makers on discord (verified) and newly also MTM Twitter spaces (all Giveth projects)
- launched video course Project Owners 101
- launched GIVpower 

That's all I can think of from the top of my head atm. 

I would like to gather some more updates from other working groups... would you like to share some bullet points about what cool new updates we can share on our Giveth - Community of Makers project? 

@WhyldWanderer @MoeNick @markoprljic @c0ric0ri @GriffGreen @laurenluz @divine-comedian

**Comment by divine-comedian** [comment]
- Began research on GIVfi 
- recovered from a hack in early november
- upgraded our praise system and launched the rewards WG
- began work on internationalization of the dapp - "spanish translation"
- development of PFP collection
- development of fiat integration for donations

**Comment by NikolaCreatrix** [comment]
Hey guys, thanks @divine-comedian thats awesome!

Okay January is coming closer, so just a gentle reminder, would be good to hear also from @WhyldWanderer @MoeNick @markoprljic @GriffGreen 

And maybe if @danelsuga would be down to compile it into something nice and coherent for the updates (2000 characters for one update post limit) ...would you be interested Suga? :)

**Comment by laurenluz** [comment]
I think this list is good enough if no one else chimes in.

I can write this really quickly in a couple of weeks if you remind me Nikola! I'm the project owner and can just post it there as well... maybe less time overall if I just do it.

**Comment by NikolaCreatrix** [comment]
@danelsuga fyi you can also get some content here for the gitcoin grant...

Oki @laurenluz I will poke you on 16th as agreed. ;)

**Comment by danelsuga** [comment]
I need to get out the Looking Forward post ([Issue 1125](https://github.com/Giveth/giveth-planning/issues/1125))  by Thursday imo since it's featuring the Gitcoin Grant. Would be awesome if this could be featured too. Would that be possible @laurenluz ?

**Comment by c0ric0ri** [comment]
Hey @NikolaCreatrix @laurenluz where are we at with this update? Do we have the draft finalized?

**Comment by c0ric0ri** [comment]
Hey @laurenluz here's the draft to be posted. It's 1782 characters so we should be good!

Can we still add the Looking Forward Blog Post link later after it's live?

**Comment by danelsuga** [comment]
[2023 Giveth Looking Forward](https://medium.com/giveth/2023-giveth-looking-forward-c6c66fb82c3e)
