### ISSUE TITLE
Tweet to encourage people to vote with GIV on Giveth roadmap (Tokenlog)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#994]

**Comment by ahmadabugosh** [comment]
@c0ric0ri I think this is related to people voting on what our dev team should work on next on the Giveth roadmap on Tokenlog: https://tokenlog.xyz/Giveth/roadmap

**Comment by laurenluz** [comment]
ugh yes exactly. the thing is though... right now our tokenlog voting power is not reading correctly... so we should not tweet this until that is fixed. It's still relevant though.

**Comment by c0ric0ri** [comment]
Some notes on this copied from a duplicate issue:

We can invite our community of GIV holders to vote on our roadmap. They must hold GIV or wrapped GIV to vote.

https://tokenlog.generalmagic.io/Giveth/Roadmap

**Comment by c0ric0ri** [comment]
@MoeNick we talked about this again recently. Has the issue been fixed that the tokenlog voting power is now reading correctly, or are we still working on it?

**Comment by laurenluz** [comment]
yeah, the voting power is corrert now, but we discussed that we should have our internal team vote before we invite people publicly to provide input.

@divine-comedian - thoughts? are we there yet?

**Comment by divine-comedian** [comment]
> yeah, the voting power is corrert now, but we discussed that we should have our internal team vote before we invite people publicly to provide input.
> 
> @divine-comedian - thoughts? are we there yet?

I don't see more than 4 votes on a single issue - we should have our team vote so the list is a little bit more curated by people with the most context before having the masses participate.

I am shilling hard within discord but as they say - you can lead a horse to water but you can't make it drink.

**Comment by c0ric0ri** [comment]
I'm going to move this to Backlog now until we're ready to promote this to the public

**Comment by divine-comedian** [comment]
I think it's ready - We've given over a month for contributors to engage so let's move on

**Comment by laurenluz** [comment]
Scheduled:

What new products & features do you want to see on Giveth?

If you're staking $GIV in the GIVfarm, you've got the power to vote & participate in decentralized roadmap planning!

👏 Props to @wslyvh and @Generalmagicio for building this tool!

https://tokenlog.generalmagic.io/Giveth/Roadmap
