### ISSUE TITLE
The Standard.io Regen Farm

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-planning#996]

**Comment by c0ric0ri** [comment]
hey @Cotabe what is the issue for? We already have an epic for The Standard.io partnership.

When creating new issues please make sure to check first for existing issues to avoid duplicates, and add a description for clarity.

I would say to please delete this unless we need it for some reason?

**Comment by Cotabe** [comment]
Thanks for the heads up @c0ric0ri, it's useful to have one to manage the deployment of the actual farm. This is the one https://github.com/Giveth/giveth-dapps-v2/issues/1752

I think I created this by mistake in the wrong repo and forgot to close it.
