### ISSUE TITLE
Giveth Galaxy Twitter Space

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#997]
Hey @oyealmond! Can you put some of the details of this upcoming twitter space in here?

Also! @danelsuga wrote the awesome hitchhiker's guide to the galaxy article and might be a great host/co-host or even just a great person to suppport in questions.

**Comment by oyealmond** [comment]
Thank you @laurenluz :) I loved the guide. 

[Here's the planning doc w the Script + Promotional Tweets ](Ofc :) 
Here's[ the planning doc ](https://docs.google.com/document/d/1DdS2W_yLjrRkXhg0IhtDiXeZFTrfN2E0AuqR12XTobo/edit?usp=sharing)with the script and promotional Tweets. ):) Please take a look and leave your comments. 

I would love to have the Giveth Galaxy Twitter Space maybe happening every month or 2 months to touch base on everyone. In this first one, I drop questions behind how everything started and how everything connects. Wdyt? 

If we like the idea of having more Giveth Galaxy Twitter Spaces, we can explore more specific work-action items.

**Comment by laurenluz** [comment]
looks great Almond! I made some suggestions.

+1 on repeating this every 2 months or so! will be so nice to great more cohesiveness between orgs.

**Comment by oyealmond** [comment]
Yey loved it! Wohoo, let's make it every two months! I would love to keep up w everyone . 
Loved the edits, [leave some final comments,](https://docs.google.com/document/d/1DdS2W_yLjrRkXhg0IhtDiXeZFTrfN2E0AuqR12XTobo/edit?usp=sharing) and I think after those is ready to share.

**Comment by oyealmond** [comment]
I think we're good to go @laurenluz :D . @danelsuga reviewed and accepted co hosting! yey!! 
So, if everyone is aligned we can share the doc to all the participants

**Comment by laurenluz** [comment]
Hey @oyealmond! I just made a couple more small comments, just have a look and then I think it's fine to share w/ everyone - we can get their feedback as well :)

**Comment by oyealmond** [comment]
yeeey, Agree on take the italics/bold part out. 
Thank you again @laurenluz ! uhoo
