### ISSUE TITLE
Update the GIVfarm documentation

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#999]
With some changes happening after the hack this weekend, we'll need to update our GIVfarm documentation. 

This is pending completion of the post-attack cleanup events and also the passing of the "ending the rewards" snapshot.

**Comment by c0ric0ri** [comment]
An adapted version of this video might be helpful:

https://github.com/Giveth/giveth-planning/issues/814

**Comment by c0ric0ri** [comment]
@franculio would you want to take this issue?

@divine-comedian FYI

**Comment by divine-comedian** [comment]
I wrote a small blurb into the top - can you add in the spanish translation @franculio ?

**Comment by laurenluz** [comment]
@franculio was this done? can we close?

**Comment by oyealmond** [comment]
cc @franculio

**Comment by oyealmond** [comment]
este @franculio qué tal? 
Lo cerramos?

**Comment by franculio** [comment]
Hecho y cerrado!
